### ISSUE TITLE
Running 4 x D435i

### ISSUE THREAD

**Issue by fiorano10** [realsenseai/realsense-ros#1001]
Is it possible to run 4 x D435i on 4 x USB 3.0 (1 x 3.0 bus master)  ?

**Comment by MartyG-RealSense** [comment]
You should be able to if you have a decent enough computing device to attach them to.  An Intel Core i7 processor or better would be advisable for 4 cameras.  A good hardware spec is especially important if you are going to be using more than one stream on each camera.

The **multicam** example program demonstrates what is achievable.

https://github.com/IntelRealSense/librealsense/tree/master/examples/multicam

**Comment by fiorano10** [comment]
Thanks!
