### ISSUE TITLE
API Mismatch

### ISSUE THREAD

**Issue by Rohan035** [realsenseai/realsense-ros#1006]
[ERROR] [1575024018.750131608]: Failed to load nodelet [/camera/realsense2_camera] of type [realsense2_camera/RealSenseNodeFactory] even after refreshing the cache: API version mismatch: librealsense.so was compiled with API version 2.30.0 but the application was compiled with 2.25.0! Make sure correct version of the library is installed (make install)

**Comment by doronhi** [comment]
checkout this answer:
https://github.com/IntelRealSense/realsense-ros/issues/950#issuecomment-557136583

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Rohan035....was doronhi's suggestion helpful?

If we don’t hear from you in 7 days, this issue will be closed.
