### ISSUE TITLE
Possible bug in decision when to get new color image

### ISSUE THREAD

**Issue by NikolasE** [realsenseai/realsense-ros#102]
I'm trying to setup an F200 and while I still have driver problems, I had a look at the code and found :

[l. 713 in base_nodelet.cpp](https://github.com/intel-ros/realsense/blob/indigo-devel/realsense_camera/src/base_nodelet.cpp#L716)

getStreamData(RS_STREAM_COLOR) fills image_[RS_STREAM_COLOR] which is read in publishPCTopic to create a colored pointcloud. I especially don't understand the '<= 0' part. Shouldn't an image get pulled if we have at least on subscriber (for the color image OR the colored pointcloud)?

**Comment by rjingar** [comment]
Hi @NikolasE 

Nodelet publishes topics/streams only if there is a subscriber. So if there is no subscriber to the color stream, getStreamData(RS_STREAM_COLOR) will not be called. In this case if user subscribes to pointcloud topic, image_[RS_STREAM_COLOR] needs to be filled by calling getStreamData if no color data is already available. So '<=0' check in l.713 covers the case when there is no subscriber to color stream but a subscriber to pointcloud.

**Comment by rjingar** [comment]
Closing due to no response.
