### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by walaa-oth** [realsenseai/realsense-ros#1023]
Hello,
Is there any paper explain the theoretical principle used in this code? I also have a problem while using this algorithm with my camera D435i. The imu data it is not synchronized with the RGB images .
Thanks in advance

**Comment by doronhi** [comment]
Can you be more specific? What part of the code? What algorithm you are having problems with?
What do you mean by "not synchronized"? How do you test? I'm asking so that we can make sure we understand what you mean, reproduce and confirm the problem.

**Comment by walaa-oth** [comment]
I am talking about SLAM using D435i. I want to know which technique is been using in this implementation and if there any paper about it. I am trying the algorithm on a virtual box hosted by Ubuntu 19.10 and powered by ubuntu 16.04. I meant by that, that the IMU data from the camera is not correct.

**Comment by doronhi** [comment]
Are you referring to the example in the wiki [SLAM-with-D435i](https://github.com/IntelRealSense/realsense-ros/wiki/SLAM-with-D435i)?
If that is the case then I am aware that there were problems regarding the imu publishing rate not being fixed. That was corrected in the last release (2.2.11).
Other then that, I suspect there are more issues causing the IMU not to have the expected effect in the rtabmap algorithm, but I don't know what the problems are.
So, if you indeed refer to that example I would appreciate if you could supply more details as to problems with the IMU messages or the launch files in that example.
Or were referring to something else?

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Hi @Valia3

Any update on the questions outlined by doronhi?

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

I'll be closing out the thread if there is nothing further necessary.
