### ISSUE TITLE
align_depth behaviour

### ISSUE THREAD

**Issue by JadTawil-theonly** [realsenseai/realsense-ros#1028]
I just want to be clear,

setting align_depth to True aligns all images (left, right, color) to the depth image, so those images are transformed to the coordinate frame of the depth image? Where is this frame defined? is it the geometric center of the D435?

**Comment by RealSenseSupport** [comment]
Hi,

As per the D4xx datasheet, the stereo depth baseline is defined as the distance between the center of the left and right imagers.

https://www.intelrealsense.com/wp-content/uploads/2020/06/Intel-RealSense-D400-Series-Datasheet-June-2020.pdf

Will you be needing further help with this? If we don’t hear from you in 7 days, this issue will be closed.

Thanks
