### ISSUE TITLE
issue while using opensouce_tracking.launch on raspbery pi 3b with a D435

### ISSUE THREAD

**Issue by LittleMoonMan** [realsenseai/realsense-ros#1044]
I am trying to make a map for my robot with use of the D435.
the guide that i am folowing tells me i need to use opensource_tracking.launch
when i use this launch file rivz start up like normal but i dont get a immage (or anything else for that matter) the only moment i get a pointcloud is when i use the demo_pointcloud.launch file. i am new with ROS and realsense so it could be a real dum mistake.

here some more information that might clarify the situation

'
`ruudstaal@ruudstaal-desktop:~/emely_ws$ roslaunch realsense2_camera opensource_tracking.launch
... logging to /home/ruudstaal/.ros/log/4ddeccd2-2bd1-11ea-9431-b827ebcfb969/roslaunch-ruudstaal-desktop-10378.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://ruudstaal-desktop:36198/

SUMMARY
========

CLEAR PARAMETERS
 * /ukf_se/

PARAMETERS
 * /ImuFilter/_publish_tf: False
 * /ImuFilter/_world_frame: enu
 * /ImuFilter/use_mag: False
 * /camera/realsense2_camera/accel_fps: 250
 * /camera/realsense2_camera/accel_frame_id: camera_accel_frame
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: True
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/allow_no_texture_points: False
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/calib_odom_file: 
 * /camera/realsense2_camera/clip_distance: -2.0
 * /camera/realsense2_camera/color_fps: 30
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: 480
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: 640
 * /camera/realsense2_camera/depth_fps: 30
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: 480
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: 640
 * /camera/realsense2_camera/device_type: 
 * /camera/realsense2_camera/enable_accel: True
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye1: True
 * /camera/realsense2_camera/enable_fisheye2: True
 * /camera/realsense2_camera/enable_fisheye: True
 * /camera/realsense2_camera/enable_gyro: True
 * /camera/realsense2_camera/enable_infra1: True
 * /camera/realsense2_camera/enable_infra2: True
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_sync: False
 * /camera/realsense2_camera/filters: 
 * /camera/realsense2_camera/fisheye1_frame_id: camera_fisheye1_f...
 * /camera/realsense2_camera/fisheye1_optical_frame_id: camera_fisheye1_o...
 * /camera/realsense2_camera/fisheye2_frame_id: camera_fisheye2_f...
 * /camera/realsense2_camera/fisheye2_optical_frame_id: camera_fisheye2_o...
 * /camera/realsense2_camera/fisheye_fps: 30
 * /camera/realsense2_camera/fisheye_frame_id: camera_fisheye_frame
 * /camera/realsense2_camera/fisheye_height: 480
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: 640
 * /camera/realsense2_camera/gyro_fps: 400
 * /camera/realsense2_camera/gyro_frame_id: camera_gyro_frame
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/imu_optical_frame_id: camera_imu_optica...
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra_fps: 30
 * /camera/realsense2_camera/infra_height: 480
 * /camera/realsense2_camera/infra_width: 640
 * /camera/realsense2_camera/initial_reset: False
 * /camera/realsense2_camera/json_file_path: 
 * /camera/realsense2_camera/linear_accel_cov: 1.0
 * /camera/realsense2_camera/odom_frame_id: camera_odom_frame
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/pose_frame_id: camera_pose_frame
 * /camera/realsense2_camera/pose_optical_frame_id: camera_pose_optic...
 * /camera/realsense2_camera/publish_odom_tf: True
 * /camera/realsense2_camera/publish_tf: True
 * /camera/realsense2_camera/rosbag_filename: 
 * /camera/realsense2_camera/serial_no: 
 * /camera/realsense2_camera/tf_publish_rate: 0.0
 * /camera/realsense2_camera/topic_odom_in: odom_in
 * /camera/realsense2_camera/unite_imu_method: linear_interpolation
 * /camera/realsense2_camera/usb_port_id: 
 * /points_xyzrgb/approx_sync: True
 * /points_xyzrgb/decimation: 4.0
 * /points_xyzrgb/voxel_size: 0.0
 * /rosdistro: kinetic
 * /rosversion: 1.12.14
 * /rtabmap/rgbd_odometry/approx_sync: True
 * /rtabmap/rgbd_odometry/config_path: 
 * /rtabmap/rgbd_odometry/frame_id: camera_link
 * /rtabmap/rgbd_odometry/ground_truth_base_frame_id: 
 * /rtabmap/rgbd_odometry/ground_truth_frame_id: 
 * /rtabmap/rgbd_odometry/guess_frame_id: 
 * /rtabmap/rgbd_odometry/guess_min_rotation: 0.0
 * /rtabmap/rgbd_odometry/guess_min_translation: 0.0
 * /rtabmap/rgbd_odometry/odom_frame_id: odom
 * /rtabmap/rgbd_odometry/publish_tf: True
 * /rtabmap/rgbd_odometry/queue_size: 10
 * /rtabmap/rgbd_odometry/subscribe_rgbd: False
 * /rtabmap/rgbd_odometry/wait_for_transform_duration: 0.2
 * /rtabmap/rgbd_odometry/wait_imu_to_init: False
 * /rtabmap/rtabmap/Mem/IncrementalMemory: true
 * /rtabmap/rtabmap/Mem/InitWMWithAllNodes: false
 * /rtabmap/rtabmap/approx_sync: True
 * /rtabmap/rtabmap/config_path: 
 * /rtabmap/rtabmap/database_path: ~/.ros/rtabmap.db
 * /rtabmap/rtabmap/frame_id: camera_link
 * /rtabmap/rtabmap/ground_truth_base_frame_id: 
 * /rtabmap/rtabmap/ground_truth_frame_id: 
 * /rtabmap/rtabmap/landmark_angular_variance: 9999.0
 * /rtabmap/rtabmap/landmark_linear_variance: 0.0001
 * /rtabmap/rtabmap/map_frame_id: map
 * /rtabmap/rtabmap/odom_frame_id: 
 * /rtabmap/rtabmap/odom_sensor_sync: False
 * /rtabmap/rtabmap/odom_tf_angular_variance: 1.0
 * /rtabmap/rtabmap/odom_tf_linear_variance: 1.0
 * /rtabmap/rtabmap/publish_tf: True
 * /rtabmap/rtabmap/queue_size: 10
 * /rtabmap/rtabmap/scan_normal_k: 0
 * /rtabmap/rtabmap/subscribe_depth: True
 * /rtabmap/rtabmap/subscribe_odom_info: True
 * /rtabmap/rtabmap/subscribe_rgbd: False
 * /rtabmap/rtabmap/subscribe_scan: False
 * /rtabmap/rtabmap/subscribe_scan_cloud: False
 * /rtabmap/rtabmap/subscribe_stereo: False
 * /rtabmap/rtabmap/subscribe_user_data: False
 * /rtabmap/rtabmap/wait_for_transform_duration: 0.2
 * /ukf_se/acceleration_gains: [0.8, 0.0, 0.0, 0...
 * /ukf_se/acceleration_limits: [1.3, 0.0, 0.0, 0...
 * /ukf_se/alpha: 0.001
 * /ukf_se/base_link_frame: camera_link
 * /ukf_se/beta: 2
 * /ukf_se/control_config: [True, False, Fal...
 * /ukf_se/control_timeout: 0.2
 * /ukf_se/debug: False
 * /ukf_se/debug_out_file: /path/to/debug/fi...
 * /ukf_se/deceleration_gains: [1.0, 0.0, 0.0, 0...
 * /ukf_se/deceleration_limits: [1.3, 0.0, 0.0, 0...
 * /ukf_se/frequency: 300
 * /ukf_se/imu0: /imu/data
 * /ukf_se/imu0_config: [False, False, Fa...
 * /ukf_se/imu0_differential: True
 * /ukf_se/imu0_linear_acceleration_rejection_threshold: 0.8
 * /ukf_se/imu0_nodelay: False
 * /ukf_se/imu0_pose_rejection_threshold: 0.8
 * /ukf_se/imu0_queue_size: 5
 * /ukf_se/imu0_relative: False
 * /ukf_se/imu0_remove_gravitational_acceleration: True
 * /ukf_se/imu0_twist_rejection_threshold: 0.8
 * /ukf_se/initial_estimate_covariance: ['1e-9', 0, 0, 0,...
 * /ukf_se/kappa: 0
 * /ukf_se/map_frame: map
 * /ukf_se/odom0: rtabmap/odom
 * /ukf_se/odom0_config: [True, True, True...
 * /ukf_se/odom0_differential: False
 * /ukf_se/odom0_nodelay: False
 * /ukf_se/odom0_pose_rejection_threshold: 10000000
 * /ukf_se/odom0_queue_size: 2
 * /ukf_se/odom0_relative: True
 * /ukf_se/odom0_twist_rejection_threshold: 10000000
 * /ukf_se/odom1: example/another_odom
 * /ukf_se/odom1_config: [False, False, Tr...
 * /ukf_se/odom1_differential: False
 * /ukf_se/odom1_nodelay: False
 * /ukf_se/odom1_pose_rejection_threshold: 2
 * /ukf_se/odom1_queue_size: 2
 * /ukf_se/odom1_relative: True
 * /ukf_se/odom1_twist_rejection_threshold: 0.2
 * /ukf_se/odom_frame: odom
 * /ukf_se/pose0: example/pose
 * /ukf_se/pose0_config: [True, True, Fals...
 * /ukf_se/pose0_differential: True
 * /ukf_se/pose0_nodelay: False
 * /ukf_se/pose0_queue_size: 5
 * /ukf_se/pose0_rejection_threshold: 2
 * /ukf_se/pose0_relative: False
 * /ukf_se/print_diagnostics: True
 * /ukf_se/process_noise_covariance: [0.05, 0, 0, 0, 0...
 * /ukf_se/sensor_timeout: 0.1
 * /ukf_se/stamped_control: False
 * /ukf_se/transform_time_offset: 0.0
 * /ukf_se/transform_timeout: 0.0
 * /ukf_se/twist0: example/twist
 * /ukf_se/twist0_config: [False, False, Fa...
 * /ukf_se/twist0_nodelay: False
 * /ukf_se/twist0_queue_size: 3
 * /ukf_se/twist0_rejection_threshold: 2
 * /ukf_se/two_d_mode: False
 * /ukf_se/use_control: False
 * /ukf_se/world_frame: odom

NODES
  /camera/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)
  /rtabmap/
    rgbd_odometry (rtabmap_ros/rgbd_odometry)
    rtabmap (rtabmap_ros/rtabmap)
  /
    ImuFilter (imu_filter_madgwick/imu_filter_node)
    points_xyzrgb (nodelet/nodelet)
    rviz (rviz/rviz)
    ukf_se (robot_localization/ukf_localization_node)

ROS_MASTER_URI=http://localhost:11311

process[camera/realsense2_camera_manager-1]: started with pid [10398]
process[camera/realsense2_camera-2]: started with pid [10399]
process[ImuFilter-3]: started with pid [10400]
process[rtabmap/rgbd_odometry-4]: started with pid [10401]
process[rtabmap/rtabmap-5]: started with pid [10402]
process[rviz-6]: started with pid [10403]
process[points_xyzrgb-7]: started with pid [10404]
process[ukf_se-8]: started with pid [10405]
type is rtabmap_ros/point_cloud_xyzrgb
[ INFO] [1577802746.963268810]: Initializing nodelet with 4 worker threads.
[ INFO] [1577802750.400575153]: RealSense ROS v2.2.11
[ INFO] [1577802750.400747861]: Running with LibRealSense v2.30.0
[ INFO] [1577802750.929675872]:  
libEGL warning: DRI2: failed to authenticate
[ INFO] [1577802751.059822075]: Device with serial number 827312073019 was found.

[ INFO] [1577802751.060354938]: Device with physical ID /sys/devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3:1.0/video4linux/video0 was found.
[ INFO] [1577802751.060575510]: Device with name Intel RealSense D435 was found.
[ INFO] [1577802751.091125714]: Device with port number 1-1.3 was found.
[ INFO] [1577802751.180678676]: getParameters...
[ INFO] [1577802751.689199469]: setupDevice...
[ INFO] [1577802751.689555406]: JSON file is not provided
[ INFO] [1577802751.689649207]: ROS Node Namespace: camera
[ INFO] [1577802751.689751186]: Device Name: Intel RealSense D435
[ INFO] [1577802751.689826446]: Device Serial No: 827312073019
[ INFO] [1577802751.689916758]: Device physical port: /sys/devices/platform/soc/3f980000.usb/usb1/1-1/1-1.3/1-1.3:1.0/video4linux/video0
[ INFO] [1577802751.690009519]: Device FW version: 05.11.15.00
[ INFO] [1577802751.690092747]: Device Product ID: 0x0B07
[ INFO] [1577802751.690168893]: Enable PointCloud: Off
[ INFO] [1577802751.690238841]: Align Depth: On
[ INFO] [1577802751.690306965]: Sync Mode: On
[ INFO] [1577802751.692112897]: Device Sensors: 
[ INFO] [1577802751.693695130]: Stereo Module was found.
[ INFO] [1577802751.694217785]: RGB Camera was found.
[ INFO] [1577802751.694728252]: (Fisheye, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1577802751.694988251]: (Fisheye, 1) sensor isn't supported by current device! -- Skipping...
[ INFO] [1577802751.695082001]: (Fisheye, 2) sensor isn't supported by current device! -- Skipping...
[ INFO] [1577802751.695168302]: (Gyro, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1577802751.695254239]: (Accel, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1577802751.695336687]: (Pose, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1577802751.696366788]: num_filters: 0
[ INFO] [1577802751.696642412]: Setting Dynamic reconfig parameters.
[ INFO] [1577802752.135578036]: Starting node...
[ INFO] [1577802752.136361627]: Done Setting Dynamic reconfig parameters.
[ INFO] [1577802752.374549789]: depth stream is enabled - width: 640, height: 480, fps: 30, Format: Z16
[ INFO] [1577802752.376385564]: infra1 stream is enabled - width: 640, height: 480, fps: 30, Format: Y8
[ WARN] [1577802752.377563425]: Given stream configuration is not supported by the device!  Stream: Infrared, Stream Index: 2, Width: 640, Height: 480, FPS: 30
[ INFO] [1577802752.390095411]: color stream is enabled - width: 640, height: 480, fps: 30, Format: RGB8
[ INFO] [1577802752.408010764]: setupPublishers...
[ INFO] [1577802752.957108080]: Initializing nodelet with 4 worker threads.
[ INFO] [1577802752.961109107]: Expected frequency for depth = 30.00000
[ INFO] [1577802752.964733834]: Initializing nodelet with 4 worker threads.
[ INFO] [1577802753.486240624]: Expected frequency for infra1 = 30.00000
[ INFO] [1577802753.678740876]: Expected frequency for aligned_depth_to_infra1 = 30.00000
[ INFO] [1577802753.864917713]: Expected frequency for color = 30.00000
[ INFO] [1577802754.038720688]: Expected frequency for aligned_depth_to_color = 30.00000
[ INFO] [1577802754.211497417]: setupStreams...
[ INFO] [1577802754.217218282]: insert Depth to Stereo Module
[ INFO] [1577802754.218586194]: insert Color to RGB Camera
[ INFO] [1577802754.219149994]: insert Infrared to Stereo Module
[ INFO] [1577802754.278622022]: SELECTED BASE:Depth, 0
[ INFO] [1577802754.384670343]: RealSense Node Is Up!
 31/12 15:32:34,420 WARNING [1775236128] (ds5-timestamp.cpp:64) UVC metadata payloads not available. Please refer to the installation chapter for details.
 31/12 15:32:34,452 WARNING [1712301088] (ds5-timestamp.cpp:64) UVC metadata payloads not available. Please refer to the installation chapter for details.
[ WARN] [1577802754.486407689]: Frame metadata isn't available! (frame_timestamp_domain = RS2_TIMESTAMP_DOMAIN_SYSTEM_TIME)
[ INFO] [1577802756.326217029]: Approximate time sync = true
[ WARN] [1577802757.141963868]: Hardware Notification:USB SCP overflow,1.5778e+12,Error,Hardware Error
[ WARN] [1577802759.144852009]: Hardware Notification:USB SCP overflow,1.5778e+12,Error,Hardware Error
[ WARN] [1577802761.147988277]: Hardware Notification:USB SCP overflow,1.5778e+12,Error,Hardware Error
[ WARN] [1577802763.004327779]: Messages of type 0 arrived out of order (will print only once)
[ WARN] [1577802763.150354657]: Hardware Notification:USB SCP overflow,1.5778e+12,Error,Hardware Error
[ INFO] [1577802763.549766625]: Odometry: frame_id               = camera_link
[ INFO] [1577802763.550083238]: Odometry: odom_frame_id          = odom
[ INFO] [1577802763.550275425]: Odometry: publish_tf             = true
[ INFO] [1577802763.550416466]: Odometry: wait_for_transform     = true
[ INFO] [1577802763.550570007]: Odometry: wait_for_transform_duration  = 0.200000
[ INFO] [1577802763.550886412]: Odometry: initial_pose           = xyz=0.000000,0.000000,0.000000 rpy=0.000000,-0.000000,0.000000
[ INFO] [1577802763.551074016]: Odometry: ground_truth_frame_id  = 
[ INFO] [1577802763.551213182]: Odometry: ground_truth_base_frame_id = 
[ INFO] [1577802763.551352557]: Odometry: config_path            = 
[ INFO] [1577802763.551500108]: Odometry: publish_null_when_lost = true
[ INFO] [1577802763.551644691]: Odometry: guess_frame_id         = 
[ INFO] [1577802763.551800524]: Odometry: guess_min_translation  = 0.000000
[ INFO] [1577802763.551936200]: Odometry: guess_min_rotation     = 0.000000
[ INFO] [1577802763.552064585]: Odometry: guess_min_time         = 0.000000
[ INFO] [1577802763.552197866]: Odometry: expected_update_rate   = 0.000000 Hz
[ INFO] [1577802763.553776298]: Odometry: wait_imu_to_init       = false
[ INFO] [1577802763.876217758]: /rtabmap/rtabmap(maps): map_filter_radius          = 0.000000
[ INFO] [1577802763.876459892]: /rtabmap/rtabmap(maps): map_filter_angle           = 30.000000
[ INFO] [1577802763.876556715]: /rtabmap/rtabmap(maps): map_cleanup                = true
[ INFO] [1577802763.876630881]: /rtabmap/rtabmap(maps): map_always_update          = false
[ INFO] [1577802763.876695673]: /rtabmap/rtabmap(maps): map_empty_ray_tracing      = true
[ INFO] [1577802763.876764422]: /rtabmap/rtabmap(maps): cloud_output_voxelized     = true
[ INFO] [1577802763.876840932]: /rtabmap/rtabmap(maps): cloud_subtract_filtering   = false
[ INFO] [1577802763.876915307]: /rtabmap/rtabmap(maps): cloud_subtract_filtering_min_neighbors = 2
[ INFO] [1577802763.911777788]: /rtabmap/rtabmap(maps): octomap_tree_depth         = 16
[ INFO] [1577802764.504757506]: rtabmap: frame_id      = camera_link
[ INFO] [1577802764.505432087]: rtabmap: map_frame_id  = map
[ INFO] [1577802764.505853336]: rtabmap: use_action_for_goal  = false
[ INFO] [1577802764.506190887]: rtabmap: tf_delay      = 0.050000
[ INFO] [1577802764.506515313]: rtabmap: tf_tolerance  = 0.100000
[ INFO] [1577802764.506838645]: rtabmap: odom_sensor_sync   = false
[ WARN] [1577802765.171877275]: Hardware Notification:USB SCP overflow,1.5778e+12,Error,Hardware Error
[ WARN] [1577802767.173923246]: Hardware Notification:USB SCP overflow,1.5778e+12,Error,Hardware Error
[ INFO] [1577802769.104593642]: Setting RTAB-Map parameter "Mem/IncrementalMemory"="true"
[ INFO] [1577802769.111341899]: Setting RTAB-Map parameter "Mem/InitWMWithAllNodes"="false"
[ WARN] [1577802769.179177232]: Hardware Notification:USB SCP overflow,1.5778e+12,Error,Hardware Error
[ WARN] [1577802771.182278260]: Hardware Notification:USB SCP overflow,1.5778e+12,Error,Hardware Error
[ INFO] [1577802771.765002133]: RGBDOdometry: approx_sync    = true
[ INFO] [1577802771.765674891]: RGBDOdometry: queue_size     = 10
[ INFO] [1577802771.766220931]: RGBDOdometry: subscribe_rgbd = false
[ INFO] [1577802771.766667700]: RGBDOdometry: rgbd_cameras   = 1
[ INFO] [1577802772.083359704]: 
/rtabmap/rgbd_odometry subscribed to (approx sync):
   /camera/color/image_raw,
   /camera/aligned_depth_to_color/image_raw,
   /camera/color/camera_info
[ WARN] [1577802773.186436892]: Hardware Notification:USB SCP overflow,1.5778e+12,Error,Hardware Error
[rtabmap/rgbd_odometry-4] process has died [pid 10401, exit code -11, cmd /home/ruudstaal/emely_ws/devel/lib/rtabmap_ros/rgbd_odometry --delete_db_on_start rgb/image:=/camera/color/image_raw depth/image:=/camera/aligned_depth_to_color/image_raw rgb/camera_info:=/camera/color/camera_info rgbd_image:=rgbd_image_relay odom:=odom __name:=rgbd_odometry __log:=/home/ruudstaal/.ros/log/4ddeccd2-2bd1-11ea-9431-b827ebcfb969/rtabmap-rgbd_odometry-4.log].
log file: /home/ruudstaal/.ros/log/4ddeccd2-2bd1-11ea-9431-b827ebcfb969/rtabmap-rgbd_odometry-4*.log
[ WARN] [1577802775.186683771]: Hardware Notification:USB SCP overflow,1.5778e+12,Error,Hardware Error
[ WARN] [1577802777.197943948]: Hardware Notification:USB SCP overflow,1.5778e+12,Error,Hardware Error
[ INFO] [1577802778.162226268]: RTAB-Map detection rate = 1.000000 Hz
[ INFO] [1577802778.167206563]: rtabmap: Deleted database "/home/ruudstaal/.ros/rtabmap.db" (--delete_db_on_start or -d are set).
[ INFO] [1577802778.167559843]: rtabmap: Using database from "/home/ruudstaal/.ros/rtabmap.db" (0 MB).
[rtabmap/rtabmap-5] process has died [pid 10402, exit code -11, cmd /home/ruudstaal/emely_ws/devel/lib/rtabmap_ros/rtabmap --delete_db_on_start rgb/image:=/camera/color/image_raw depth/image:=/camera/aligned_depth_to_color/image_raw rgb/camera_info:=/camera/color/camera_info rgbd_image:=rgbd_image_relay left/image_rect:=/stereo_camera/left/image_rect_color right/image_rect:=/stereo_camera/right/image_rect left/camera_info:=/stereo_camera/left/camera_info right/camera_info:=/stereo_camera/right/camera_info scan:=/scan scan_cloud:=/scan_cloud user_data:=/user_data user_data_async:=/user_data_async gps/fix:=/gps/fix tag_detections:=/tag_detections odom:=odom imu:=/imu/data __name:=rtabmap __log:=/home/ruudstaal/.ros/log/4ddeccd2-2bd1-11ea-9431-b827ebcfb969/rtabmap-rtabmap-5.log].
log file: /home/ruudstaal/.ros/log/4ddeccd2-2bd1-11ea-9431-b827ebcfb969/rtabmap-rtabmap-5*.log
[ WARN] [1577802779.208240123]: Hardware Notification:USB SCP overflow,1.5778e+12,Error,Hardware Error
`

![Screenshot at 2019-12-31 15-34-53](https://user-images.githubusercontent.com/50405650/71624514-41384a00-2be3-11ea-9fc6-042bb4256743.png)
![Screenshot at 2019-12-31 15-36-24](https://user-images.githubusercontent.com/50405650/71624534-57dea100-2be3-11ea-8169-9cfb05f4f75f.png)

**Comment by MartyG-RealSense** [comment]
Are you using the guide for the D435i camera model in the link below please?

https://github.com/IntelRealSense/realsense-ros/wiki/SLAM-with-D435i

The D435 does not contain an 'IMU' tracking hardware component that the D435i ( 'i' for IMU) has.

For SLAM mapping with an IMU-less D435, the SLAM software 'ORB_SLAM2' may be a good choice.  The link below has a guide to using it with ROS.

http://wiki.ros.org/orb_slam2_ros

And here is a discussion on using it with a D435, ROS and Rviz.

https://github.com/ethz-asl/voxblox/issues/184

**Comment by LittleMoonMan** [comment]
thank you for your help

i was not using a D435i but a D435. with the new package i was able to get some dots on my screen (after that my raspberry overheated). do you know sombody that was able to make a map with a raspberry or am i pushing it to a limit with it.

**Comment by MartyG-RealSense** [comment]
You could try offloading some of the CPU's work onto the GPU using a Librealsense technique called GLSL Processing Blocks and see if distributing the workload reduces your Pi's temperature.

https://github.com/IntelRealSense/librealsense/pull/3654

The Pi 3 and models before it use a  VideoCore IV GPU, whilst the new Pi 4 uses a more powerful VideoCore VI GPU.

A low-power development board such as Pi may struggle with computing SLAM, even with just one camera attached (though as you found, it should be able to handle a one-camera setup).  The discussion in the link below addresses the subject of using SLAM on low-power boards.

https://github.com/IntelRealSense/librealsense/issues/3218

If your robot can accommodate a larger board and you have the budget for it, the Up Squared is an excellent powerful choice of development board to pair with a 400 Series camera.  

The Pi 4, which is a similar low price to the Pi 3 and offers desktop-level performance, is also becoming a popular option for RealSense users.  It is also the first Pi to have USB 3, enabling RealSense cameras to access their full capabilities on a Pi for the first time.

**Comment by LittleMoonMan** [comment]
in my research with the raspberry pi 4 I coudent find a version of ubuntu (mate) that was compatible with ROS. Did i mis some thing or are people using different programs?

**Comment by MartyG-RealSense** [comment]
The RealSense ROS wrapper officially has compatibility with ROS Indigo (14.04) and Kinetic (16.04).  Some users have said that the wrapper's instructions work too with Melodic (18.04).  

I rarely hear of Ubuntu MATE being used (it was recommended by Intel for use with Raspberry Pi 3 Model B).  As Pi 4 is more powerful and can provide desktop-level performance, it may be beter to use one of the mainstream Ubuntu versions such as 18.04 with the ROS wrapper if possible.

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@LittleMoonMan Any other questions for this ticket? Looking forward to your reply. Thanks!

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@LittleMoonMan Any update from your side? Will close the issue if no other questions. Thanks!

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@LittleMoonMan Could you please update if you still need support on this? Thanks!
