### ISSUE TITLE
Cannot disable pointcloud

### ISSUE THREAD

**Issue by wikpunGitHub** [realsenseai/realsense-ros#1045]
Hi, I set enable pointcloud to false but I still observe pointcloud in the /camera/depth_registered/points topic. I am running on Jetson Nano so I would like to save any computing power I could. I am using D435. Thanks!

**Comment by doronhi** [comment]
You are running with "rs_rgbd.launch" which uses 3rd-parties nodes to publish the pointcloud.
Use "rs_camera.launch" which by default publishes no pointcloud and with `filters:=pointcloud` publishes pointcloud on topic "/camera/depth/color/points".

**Comment by wikpunGitHub** [comment]
Thanks a lot!
