### ISSUE TITLE
Set manual exposure prior to streaming

### ISSUE THREAD

**Issue by rghl3** [realsenseai/realsense-ros#1049]
Hi,
    I am trying to set manual exposure values for T265 camera using this [launch file.](https://github.com/IntelRealSense/realsense-ros/blob/development/realsense2_camera/launch/rs_t265.launch)

I have disabled the auto-exposure using below ros param
```
<rosparam>
    camera/tracking_module/enable_auto_exposure: false
</rosparam>
```
as mentioned in [here.](https://github.com/IntelRealSense/librealsense/issues/4413#issuecomment-520200355)

But I am not sure how to set the manual exposure value using launch file.

Adding the below line to rosparam,
```
<rosparam>
    camera/tracking_module/enable_auto_exposure: false
    camera/tracking_module/exposure: 200
</rosparam>
```
produces the following error.
```
To control exposure you must set sensor to manual exposure mode prior to streaming
```
What is the correct procedure to set manual exposure value using launch file?

**Comment by shannonwarren** [comment]
@rghl3 Any update on this?

**Comment by FergalLonerganKUL** [comment]
@doronhi Could you have a look at this please? Regardless of where you add the rosparam to your launch file the enable_auto_exposure remains set to true when you open rqt_reconfigure with the error regarding setting the exposure before streaming outlined above.

**Comment by doronhi** [comment]
It seems like a bug in the librealsense2 library. The enable_auto_exposure option should turn automatically to Off when exposure is set. This bug can be reproduced with the realsense-viewer application.
Thanks for reporting this. We will try to correctly it shortly.

**Comment by digiamm** [comment]
@doronhi is there any update?

**Comment by RealSenseSupport** [comment]
Hi,

Will you be needing further help with this? If we don’t hear from you in 7 days, this issue will be closed.

Thanks
