### ISSUE TITLE
Multiple realsense cameras

### ISSUE THREAD

**Issue by karry3775** [realsenseai/realsense-ros#1050]
Hello there! I wanted to know if multiple t265 cameras can be launched from ros now. The document online says that t265 doesn't support multiple cameras launch at this moment. Is there a work around this, I really have to use multiple cameras for a project of mine and any help is appreciated. You can really close down this issue as this is not really one. I just wanted to get in touch with you to discuss about the possible solution here. My email: kartikprakash3775@gmail.com

**Comment by RealSenseSupport** [comment]
Hi,

Will you be needing further help with this? Unfortunately this ROS functionality is still not available.

If we don’t hear from you in 7 days, this issue will be closed.

Thanks

**Comment by karry3775** [comment]
Thank you for your response. You can close this issue. Cheers!
