### ISSUE TITLE
detached head issue while executing readme

### ISSUE THREAD

**Issue by shreyas2311** [realsenseai/realsense-ros#1052]
While executing the following line from the readme, I get an error saying that I am in the detached head state. It would be great if this is resolved soon.

git checkout `git tag | sort -V | grep -P "^\d+\.\d+\.\d+" | tail -1`

**Comment by doronhi** [comment]
Hi, sorry for the late response.
The message regarding the detached head is not an error. It means that the right version is now on the disk but it is not attached to a specific branch.
Attaching it to a specific branch is optional and is not needed the the successful completion of the building process.
You can attach it to a specific branch of your choice if you want to commit some changes to it, merge it to your own version or any other git option.

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Hi @shreyas2311,

As @doronhi have said, the detached head state does not interfere with the successful completion of the building process. Please let us know if you need any further clarifications regarding this topic.

Thank you!

**Comment by shreyas2311** [comment]
@RealSenseCustomerSupport Alright! Thanks for the update!
