### ISSUE TITLE
enable_laser2 issue

### ISSUE THREAD

**Issue by job-1994** [realsenseai/realsense-ros#1053]
Device: Jetson Xavier
Ubuntu 18.04
ROS Melodic
librealsense 2.31.0
realsense-ros 2.2.12

I am trying to get the streams running using the rs_camera.launch file, setting the initial_reset to true, however it always fails after a few seconds after a Hardware Notification:

[ WARN] [1578911730.399397915]: Hardware Notification:USB REC overflow,1.57891e+12,Error,Hardware Error
[ WARN] [1578911499.052760224]: Hardware Notification:IR stream start failure,1.57891e+12,Error,Hardware Error

leading to 

[ERROR] [1578911499.053030123]: Hardware Reset is needed. use option: initial_reset:=true

For obvious reasons I cannot have the camera resetting every few seconds, and after playing around with a few of the ros parameters for the launch file I have found the following:

when laser1, color, gyro and accel are enabled with the rest set to false, the node runs fine
when laser2 is added to the enabled list, it fails after a few seconds
This even happens when laser2 is enabled on its own. 

Before I dive into the code and such, I was wondering if there were any suggestions that might help me solve this issue, or narrow down where to look for it

EDIT:
Now, when I run rs-enumerate-devices, it no longer lists Infrared 2 as a supported mode, have tried updating the firmware to no avail, this seems like a serious issue

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Hi @job-1994,

First of all, could you please provide us with the following details about your system configuration :
HW configuration details (all platforms names, how the camera(s) is/are connected, etc)
Linux Kernel version
number of cameras in active use in the system
for each camera please provide :
   camera model (D435,D435i,etc)
   FW version

Second, please elaborate on "updating the firmware to no avail". What tools do you use?
What's exactly happening when you are trying to update the firmware?

Third, if you reset the camera and run rs-enumerate-devices is Infrared2 still not in
the list of supported modes?

Thank you!

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@job-1994,

Do you still need help with this question?

**Comment by job-1994** [comment]
Camera is connected via USB3 to the Jetson Xavier platform 
Linux Kernel Version (result of `uname -r`): 4.9.140-tegra
amount of active cameras: 1
Model: D435i

I just tried running the enumerate command and Infrared2 is now showing up, so that part of the issue seems to have solved itself, however now the problem is that the camera simply wont run, it keeps coming with the following error after executing 'roslaunch realsense2_camera rs_camera.launch`
`
[ INFO] [1581587287.175490315]: Initializing nodelet with 4 worker threads.
[ INFO] [1581587288.283696998]: RealSense ROS v2.2.12
[ INFO] [1581587288.284117831]: Running with LibRealSense v2.31.0
[ INFO] [1581587288.674418402]:  
 13/02 10:48:08,787 WARNING [547074265472] (types.cpp:49) hwmon command 0x4f failed. Error type: No data to return (-21).
[ INFO] [1581587288.797955710]: Device with serial number 939622072066 was found.

[ INFO] [1581587288.798336031]: Device with physical ID /sys/devices/3610000.xhci/usb2/2-3/2-3:1.0/video4linux/video0 was found.
[ INFO] [1581587288.798440607]: Device with name Intel RealSense D435I was found.
[ INFO] [1581587288.801420869]: Device with port number 2-3 was found.
[ INFO] [1581587288.806072783]: Resetting device...
[ INFO] [1581587294.854423446]:  
 13/02 10:48:14,917 WARNING [547074265472] (types.cpp:49) hwmon command 0x4f failed. Error type: No data to return (-21).
[ INFO] [1581587294.923454111]: Device with serial number 939622072066 was found.

[ INFO] [1581587294.923982496]: Device with physical ID /sys/devices/3610000.xhci/usb2/2-3/2-3:1.0/video4linux/video0 was found.
[ INFO] [1581587294.924089952]: Device with name Intel RealSense D435I was found.
[ INFO] [1581587294.926001604]: Device with port number 2-3 was found.
[ INFO] [1581587294.973639555]: getParameters...
[ INFO] [1581587295.211164760]: setupDevice...
[ INFO] [1581587295.211499128]: JSON file is not provided
[ INFO] [1581587295.211684377]: ROS Node Namespace: camera
[ INFO] [1581587295.211875001]: Device Name: Intel RealSense D435I
[ INFO] [1581587295.211977049]: Device Serial No: 939622072066
[ INFO] [1581587295.212076250]: Device physical port: /sys/devices/3610000.xhci/usb2/2-3/2-3:1.0/video4linux/video0
[ INFO] [1581587295.212324058]: Device FW version: 05.12.01.00
[ INFO] [1581587295.212465786]: Device Product ID: 0x0B3A
[ INFO] [1581587295.212785403]: Enable PointCloud: On
[ INFO] [1581587295.212885915]: Align Depth: Off
[ INFO] [1581587295.212982075]: Sync Mode: On
[ INFO] [1581587295.213720317]: Device Sensors: 
[ INFO] [1581587295.214217534]: Stereo Module was found.
[ INFO] [1581587295.214375166]: RGB Camera was found.
[ INFO] [1581587295.214599871]: Motion Module was found.
[ INFO] [1581587295.214890527]: (Fisheye, 1) sensor isn't supported by current device! -- Skipping...
[ INFO] [1581587295.215130944]: (Fisheye, 2) sensor isn't supported by current device! -- Skipping...
[ INFO] [1581587295.215221440]: (Pose, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1581587295.215365376]: Add Filter: pointcloud
[ INFO] [1581587295.248249473]: num_filters: 1
[ INFO] [1581587295.248737154]: Setting Dynamic reconfig parameters.
[ INFO] [1581587295.584935226]: Done Setting Dynamic reconfig parameters.
[ INFO] [1581587295.724538317]: depth stream is enabled - width: 640, height: 480, fps: 6, Format: Z16
[ INFO] [1581587295.726248369]: infra1 stream is enabled - width: 640, height: 480, fps: 6, Format: Y8
[ INFO] [1581587295.728169717]: infra2 stream is enabled - width: 640, height: 480, fps: 6, Format: Y8
[ INFO] [1581587295.734437921]: setupPublishers...
[ INFO] [1581587295.764997277]: Expected frequency for depth = 6.00000
[ INFO] [1581587295.990893691]: Expected frequency for infra1 = 6.00000
[ INFO] [1581587296.103865593]: Expected frequency for infra2 = 6.00000
[ INFO] [1581587296.246677522]: setupStreams...
[ INFO] [1581587296.252994110]: insert Depth to Stereo Module
[ INFO] [1581587296.254057888]: insert Infrared to Stereo Module
[ INFO] [1581587296.254804322]: insert Infrared to Stereo Module
[ INFO] [1581587296.255631779]: insert Gyro to Motion Module
[ INFO] [1581587296.256094116]: insert Accel to Motion Module
 13/02 10:48:16,344 WARNING [546735911296] (backend-hid.cpp:681) HID set_power 1 failed for /sys/devices/3610000.xhci/usb2/2-3/2-3:1.5/0003:8086:0B3A.0002/HID-SENSOR-200073.1.auto/iio:device2/buffer/enable
[ INFO] [1581587296.460986742]: SELECTED BASE:Depth, 0
[ INFO] [1581587296.536546411]: RealSense Node Is Up!
[ WARN] [1581587296.590296180]: Hardware Notification:Motion Module force pause,1.58159e+12,Error,Hardware Error
[ERROR] [1581587296.590918197]: Hardware Reset is needed. use option: initial_reset:=true
 13/02 10:48:18,000 ERROR [546678071680] (types.h:304) get_xu(...). xioctl(UVCIOC_CTRL_QUERY) failed Last Error: No such device
 13/02 10:48:18,003 ERROR [546928845184] (types.h:304) get_xu(...). xioctl(UVCIOC_CTRL_QUERY) failed Last Error: No such device
 13/02 10:48:18,004 ERROR [546928845184] (error-handling.cpp:68) Error during polling error handler: get_xu(...). xioctl(UVCIOC_CTRL_QUERY) failed Last Error: No such device
 13/02 10:48:18,015 ERROR [546727518592] (types.h:304) Cannot open '/dev/video0 Last Error: No such file or directory
[ERROR] [1581587298.015703515]: get_xu(...). xioctl(UVCIOC_CTRL_QUERY) failed Last Error: No such device
 13/02 10:48:18,016 ERROR [546727518592] (synthetic-stream.cpp:47) Exception was thrown during user processing callback!
[ERROR] [1581587298.017010173]: An error has occurred during frame callback: Error occured during execution of the processing block! See the log for more info
 13/02 10:48:18,018 ERROR [546727518592] (backend-v4l2.cpp:276) xioctl(VIDIOC_QBUF) failed when requesting new frame! fd: 28 error: No such device
 13/02 10:48:18,019 ERROR [546903667072] (types.h:304) Cannot open '/dev/video0 Last Error: No such file or directory
 13/02 10:48:18,019 ERROR [546903667072] (global_timestamp_reader.cpp:188) Error during time_diff_keeper polling: Cannot open '/dev/video0 Last Error: No such file or directory
 13/02 10:48:18,020 ERROR [546727518592] (types.h:304) xioctl(VIDIOC_DQBUF) failed for fd: 28 Last Error: No such device
 13/02 10:48:18,020 ERROR [546727518592] (backend-v4l2.cpp:1235) xioctl(VIDIOC_DQBUF) failed for fd: 28 Last Error: No such device
[ WARN] [1581587298.021086245]: Hardware Notification:xioctl(VIDIOC_DQBUF) failed for fd: 28 Last Error: No such device,1.58159e+12,Error,Unknown Error
 13/02 10:48:18,030 ERROR [546886881664] (backend-v4l2.cpp:276) xioctl(VIDIOC_QBUF) failed when requesting new frame! fd: 31 error: No such device
 13/02 10:48:18,044 ERROR [546886881664] (types.h:304) xioctl(VIDIOC_DQBUF) failed for fd: 31 Last Error: No such device
 13/02 10:48:18,044 ERROR [546886881664] (backend-v4l2.cpp:1235) xioctl(VIDIOC_DQBUF) failed for fd: 31 Last Error: No such device
[ WARN] [1581587298.045329557]: Hardware Notification:xioctl(VIDIOC_DQBUF) failed for fd: 31 Last Error: No such device,1.58159e+12,Error,Unknown Error
 13/02 10:48:18,120 ERROR [546903667072] (types.h:304) Cannot open '/dev/video0 Last Error: No such file or directory
 13/02 10:48:18,121 ERROR [546903667072] (global_timestamp_reader.cpp:188) Error during time_diff_keeper polling: Cannot open '/dev/video0 Last Error: No such file or directory
 13/02 10:48:18,223 ERROR [546903667072] (types.h:304) Cannot open '/dev/video0 Last Error: No such file or directory
 13/02 10:48:18,223 ERROR [546903667072] (global_timestamp_reader.cpp:188) Error during time_diff_keeper polling: Cannot open '/dev/video0 Last Error: No such file or directory
 13/02 10:48:18,325 ERROR [546903667072] (types.h:304) Cannot open '/dev/video0 Last Error: No such file or directory
 13/02 10:48:18,327 ERROR [546903667072] (global_timestamp_reader.cpp:188) Error during time_diff_keeper polling: Cannot open '/dev/video0 Last Error: No such file or directory
 13/02 10:48:18,428 ERROR [546903667072] (types.h:304) Cannot open '/dev/video0 Last Error: No such file or directory
 13/02 10:48:18,428 ERROR [546903667072] (global_timestamp_reader.cpp:188) Error during time_diff_keeper polling: Cannot open '/dev/video0 Last Error: No such file or directory
 13/02 10:48:18,530 ERROR [546903667072] (types.h:304) Cannot open '/dev/video0 Last Error: No such file or directory
 13/02 10:48:18,530 ERROR [546903667072] (global_timestamp_reader.cpp:188) Error during time_diff_keeper polling: Cannot open '/dev/video0 Last Error: No such file or directory
 13/02 10:48:18,632 ERROR [546903667072] (types.h:304) Cannot open '/dev/video0 Last Error: No such file or directory
 13/02 10:48:18,632 ERROR [546903667072] (global_timestamp_reader.cpp:188) Error during time_diff_keeper polling: Cannot open '/dev/video0 Last Error: No such file or directory
 13/02 10:48:18,733 ERROR [546903667072] (types.h:304) Cannot open '/dev/video0 Last Error: No such file or directory
 13/02 10:48:18,734 ERROR [546903667072] (global_timestamp_reader.cpp:188) Error during time_diff_keeper polling: Cannot open '/dev/video0 Last Error: No such file or directory
 13/02 10:48:18,841 ERROR [546903667072] (types.h:304) Cannot open '/dev/video0 Last Error: No such file or directory
 13/02 10:48:18,841 ERROR [546903667072] (global_timestamp_reader.cpp:188) Error during time_diff_keeper polling: Cannot open '/dev/video0 Last Error: No such file or directory
 13/02 10:48:18,943 ERROR [546903667072] (types.h:304) Cannot open '/dev/video0 Last Error: No such file or directory
 13/02 10:48:18,944 ERROR [546903667072] (global_timestamp_reader.cpp:188) Error during time_diff_keeper polling: Cannot open '/dev/video0 Last Error: No such file or directory
 13/02 10:48:19,005 ERROR [546928845184] (types.h:304) get_xu(...). xioctl(UVCIOC_CTRL_QUERY) failed Last Error: No such device
 13/02 10:48:19,006 ERROR [546928845184] (error-handling.cpp:68) Error during polling error handler: get_xu(...). xioctl(UVCIOC_CTRL_QUERY) failed Last Error: No such device
 13/02 10:48:19,046 ERROR [546903667072] (types.h:304) Cannot open '/dev/video0 Last Error: No such file or directory
 13/02 10:48:19,049 ERROR [546903667072] (global_timestamp_reader.cpp:188) Error during time_diff_keeper polling: Cannot open '/dev/video0 Last Error: No such file or directory
 13/02 10:48:19,152 ERROR [546903667072] (types.h:304) Cannot open '/dev/video0 Last Error: No such file or directory
 13/02 10:48:19,153 ERROR [546903667072] (global_timestamp_reader.cpp:188) Error during time_diff_keeper polling: Cannot open '/dev/video0 Last Error: No such file or directory
 13/02 10:48:19,255 ERROR [546903667072] (types.h:304) Cannot open '/dev/video0 Last Error: No such file or directory
 13/02 10:48:19,256 ERROR [546903667072] (global_timestamp_reader.cpp:188) Error during time_diff_keeper polling: Cannot open '/dev/video0 Last Error: No such file or directory
 13/02 10:48:19,358 ERROR [546903667072] (types.h:304) Cannot open '/dev/video0 Last Error: No such file or directory
 13/02 10:48:19,359 ERROR [546903667072] (global_timestamp_reader.cpp:188) Error during time_diff_keeper polling: Cannot open '/dev/video0 Last Error: No such file or directory
 13/02 10:48:19,461 ERROR [546903667072] (types.h:304) Cannot open '/dev/video0 Last Error: No such file or directory
 13/02 10:48:19,462 ERROR [546903667072] (global_timestamp_reader.cpp:188) Error during time_diff_keeper polling: Cannot open '/dev/video0 Last Error: No such file or directory
 13/02 10:48:19,564 ERROR [546903667072] (types.h:304) Cannot open '/dev/video0 Last Error: No such file or directory
 13/02 10:48:19,566 ERROR [546903667072] (global_timestamp_reader.cpp:188) Error during time_diff_keeper polling: Cannot open '/dev/video0 Last Error: No such file or directory
 13/02 10:48:19,668 ERROR [546903667072] (types.h:304) Cannot open '/dev/video0 Last Error: No such file or directory
 13/02 10:48:19,670 ERROR [546903667072] (global_timestamp_reader.cpp:188) Error during time_diff_keeper polling: Cannot open '/dev/video0 Last Error: No such file or directory
 13/02 10:48:19,773 ERROR [546903667072] (types.h:304) Cannot open '/dev/video0 Last Error: No such file or directory
 13/02 10:48:19,774 ERROR [546903667072] (global_timestamp_reader.cpp:188) Error during time_diff_keeper polling: Cannot open '/dev/video0 Last Error: No such file or directory
 13/02 10:48:19,876 ERROR [546903667072] (types.h:304) Cannot open '/dev/video0 Last Error: No such file or directory
 13/02 10:48:19,877 ERROR [546903667072] (global_timestamp_reader.cpp:188) Error during time_diff_keeper polling: Cannot open '/dev/video0 Last Error: No such file or directory
[ERROR] [1581587299.962028728]: The device has been disconnected!
 13/02 10:48:19,979 ERROR [546903667072] (types.h:304) Cannot open '/dev/video0 Last Error: No such file or directory
 13/02 10:48:19,981 ERROR [546903667072] (global_timestamp_reader.cpp:188) Error during time_diff_keeper polling: Cannot open '/dev/video0 Last Error: No such file or directory
 13/02 10:48:20,007 ERROR [546928845184] (types.h:304) get_xu(...). xioctl(UVCIOC_CTRL_QUERY) failed Last Error: No such device
 13/02 10:48:20,009 ERROR [546928845184] (error-handling.cpp:68) Error during polling error handler: get_xu(...). xioctl(UVCIOC_CTRL_QUERY) failed Last Error: No such device
 13/02 10:48:20,083 ERROR [546903667072] (types.h:304) Cannot open '/dev/video0 Last Error: No such file or directory
 13/02 10:48:20,086 ERROR [546903667072] (global_timestamp_reader.cpp:188) Error during time_diff_keeper polling: Cannot open '/dev/video0 Last Error: No such file or directory
 13/02 10:48:20,177 ERROR [547082658176] (types.h:304) xioctl(VIDIOC_STREAMOFF) failed for buf_type=1 Last Error: No such device
 13/02 10:48:20,260 WARNING [546895274368] (backend-hid.h:48) write_fs_attribute with 0 failed. The specified path /sys/devices/3610000.xhci/usb2/2-3/2-3:1.5/0003:8086:0B3A.0002/HID-SENSOR-200076.2.auto/iio:device3/buffer/enable is not valid
 13/02 10:48:20,262 WARNING [546895274368] (backend-hid.cpp:681) HID set_power 0 failed for /sys/devices/3610000.xhci/usb2/2-3/2-3:1.5/0003:8086:0B3A.0002/HID-SENSOR-200076.2.auto/iio:device3/buffer/enable
 13/02 10:48:20,265 WARNING [546735911296] (backend-hid.h:48) write_fs_attribute with 0 failed. The specified path /sys/devices/3610000.xhci/usb2/2-3/2-3:1.5/0003:8086:0B3A.0002/HID-SENSOR-200073.1.auto/iio:device2/buffer/enable is not valid
 13/02 10:48:20,266 WARNING [546735911296] (backend-hid.cpp:681) HID set_power 0 failed for /sys/devices/3610000.xhci/usb2/2-3/2-3:1.5/0003:8086:0B3A.0002/HID-SENSOR-200073.1.auto/iio:device2/buffer/enable
 13/02 10:48:20,268 ERROR [547082658176] (types.h:304) Failed to enable_sensor /sys/devices/3610000.xhci/usb2/2-3/2-3:1.5/0003:8086:0B3A.0002/HID-SENSOR-2000e1.3.auto/enable_sensor Last Error: No such file or directory
 13/02 10:48:20,269 ERROR [547082658176] (sensor.cpp:1033) An error has occurred while stop_streaming()!
 13/02 10:48:20,275 ERROR [547082658176] (types.h:304) Failed to enable_sensor /sys/devices/3610000.xhci/usb2/2-3/2-3:1.5/0003:8086:0B3A.0002/HID-SENSOR-2000e1.3.auto/enable_sensor Last Error: No such file or directory
 13/02 10:48:20,276 ERROR [547082658176] (sensor.cpp:672) An error has occurred while stop_streaming()!
 13/02 10:48:20,277 ERROR [547082658176] (types.h:304) open() failed with all retries! Last Error: No such file or directory
 13/02 10:48:20,279 ERROR [547082658176] (types.h:304) open() failed with all retries! Last Error: No such file or directory
[ INFO] [1581587300.298684457]: Checking new devices...
[ INFO] [1581587300.299112606]:  
 13/02 10:48:20,371 WARNING [547082658176] (types.cpp:49) hwmon command 0x4f failed. Error type: No data to return (-21).
[ INFO] [1581587300.377832631]: Device with serial number 939622072066 was found.

[ INFO] [1581587300.378266125]: Device with physical ID /sys/devices/3610000.xhci/usb2/2-3/2-3:1.0/video4linux/video2 was found.
[ INFO] [1581587300.378374771]: Device with name Intel RealSense D435I was found.
[ INFO] [1581587300.380115723]: Device with port number 2-3 was found.
[ INFO] [1581587300.398647639]: getParameters...
[ INFO] [1581587300.644172893]: setupDevice...
[ INFO] [1581587300.644519055]: JSON file is not provided
[ INFO] [1581587300.644649718]: ROS Node Namespace: camera
[ INFO] [1581587300.644846656]: Device Name: Intel RealSense D435I
[ INFO] [1581587300.644957221]: Device Serial No: 939622072066
[ INFO] [1581587300.645120333]: Device physical port: /sys/devices/3610000.xhci/usb2/2-3/2-3:1.0/video4linux/video2
[ INFO] [1581587300.645212562]: Device FW version: 05.12.01.00
[ INFO] [1581587300.645320216]: Device Product ID: 0x0B3A
[ INFO] [1581587300.649532621]: Enable PointCloud: On
[ INFO] [1581587300.649807387]: Align Depth: Off
[ INFO] [1581587300.649950818]: Sync Mode: On
[ INFO] [1581587300.650596931]: Device Sensors: 
[ INFO] [1581587300.650891538]: Stereo Module was found.
[ INFO] [1581587300.651041722]: RGB Camera was found.
[ INFO] [1581587300.651174080]: Motion Module was found.
[ INFO] [1581587300.651290630]: (Fisheye, 1) sensor isn't supported by current device! -- Skipping...
[ INFO] [1581587300.651394700]: (Fisheye, 2) sensor isn't supported by current device! -- Skipping...
[ INFO] [1581587300.651838242]: (Pose, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1581587300.651965737]: Add Filter: pointcloud
[ INFO] [1581587300.671176727]: num_filters: 1
[ INFO] [1581587300.671520009]: Setting Dynamic reconfig parameters.
[ INFO] [1581587300.999808757]: Done Setting Dynamic reconfig parameters.
[ INFO] [1581587301.074197604]: depth stream is enabled - width: 640, height: 480, fps: 6, Format: Z16
[ INFO] [1581587301.075932859]: infra1 stream is enabled - width: 640, height: 480, fps: 6, Format: Y8
[ INFO] [1581587301.077131511]: infra2 stream is enabled - width: 640, height: 480, fps: 6, Format: Y8
[ INFO] [1581587301.081106910]: setupPublishers...
[ INFO] [1581587301.093850364]: Expected frequency for depth = 6.00000
[ INFO] [1581587301.276367306]: Expected frequency for infra1 = 6.00000
[ INFO] [1581587301.381478006]: Expected frequency for infra2 = 6.00000
[ INFO] [1581587301.499337345]: setupStreams...
[ INFO] [1581587301.505672894]: insert Depth to Stereo Module
[ INFO] [1581587301.506045073]: insert Infrared to Stereo Module
[ INFO] [1581587301.506289405]: insert Infrared to Stereo Module
[ INFO] [1581587301.506712978]: insert Gyro to Motion Module
[ INFO] [1581587301.507085957]: insert Accel to Motion Module
 13/02 10:48:21,572 WARNING [546912166272] (backend-hid.cpp:681) HID set_power 1 failed for /sys/devices/3610000.xhci/usb2/2-3/2-3:1.5/0003:8086:0B3A.0003/HID-SENSOR-200073.1.auto/iio:device4/buffer/enable
[ INFO] [1581587301.638053663]: SELECTED BASE:Depth, 0
[ INFO] [1581587301.713522272]: RealSense Node Is Up!
[ WARN] [1581587302.004079662]: Hardware Notification:Motion Module force pause,1.58159e+12,Error,Hardware Error
[ERROR] [1581587302.005449458]: Hardware Reset is needed. use option: initial_reset:=true
 13/02 10:48:23,153 ERROR [546678071680] (types.h:304) get_xu(...). xioctl(UVCIOC_CTRL_QUERY) failed Last Error: No such device
 13/02 10:48:23,155 ERROR [546727518592] (types.h:304) Cannot open '/dev/video2 Last Error: No such file or directory
[ERROR] [1581587303.156354187]: get_xu(...). xioctl(UVCIOC_CTRL_QUERY) failed Last Error: No such device
 13/02 10:48:23,156 ERROR [546727518592] (synthetic-stream.cpp:47) Exception was thrown during user processing callback!
[ERROR] [1581587303.156700700]: An error has occurred during frame callback: Error occured during execution of the processing block! See the log for more info
 13/02 10:48:23,160 ERROR [547023909248] (types.h:304) Cannot open '/dev/video2 Last Error: No such file or directory
 13/02 10:48:23,161 ERROR [546727518592] (backend-v4l2.cpp:276) xioctl(VIDIOC_QBUF) failed when requesting new frame! fd: 25 error: No such device
 13/02 10:48:23,161 ERROR [546727518592] (types.h:304) xioctl(VIDIOC_DQBUF) failed for fd: 25 Last Error: No such device
 13/02 10:48:23,161 ERROR [546727518592] (backend-v4l2.cpp:1235) xioctl(VIDIOC_DQBUF) failed for fd: 25 Last Error: No such device
[ WARN] [1581587303.162662654]: Hardware Notification:xioctl(VIDIOC_DQBUF) failed for fd: 25 Last Error: No such device,1.58159e+12,Error,Unknown Error
 13/02 10:48:23,164 ERROR [547023909248] (global_timestamp_reader.cpp:188) Error during time_diff_keeper polling: Cannot open '/dev/video2 Last Error: No such file or directory
 13/02 10:48:23,164 ERROR [546895274368] (types.h:304) get_xu(...). xioctl(UVCIOC_CTRL_QUERY) failed Last Error: No such device
 13/02 10:48:23,165 ERROR [546895274368] (error-handling.cpp:68) Error during polling error handler: get_xu(...). xioctl(UVCIOC_CTRL_QUERY) failed Last Error: No such device
 13/02 10:48:23,171 ERROR [546903773568] (backend-v4l2.cpp:276) xioctl(VIDIOC_QBUF) failed when requesting new frame! fd: 31 error: No such device
 13/02 10:48:23,172 ERROR [546903773568] (types.h:304) xioctl(VIDIOC_DQBUF) failed for fd: 31 Last Error: No such device
 13/02 10:48:23,173 ERROR [546903773568] (backend-v4l2.cpp:1235) xioctl(VIDIOC_DQBUF) failed for fd: 31 Last Error: No such device
[ WARN] [1581587303.173806781]: Hardware Notification:xioctl(VIDIOC_DQBUF) failed for fd: 31 Last Error: No such device,1.58159e+12,Error,Unknown Error
 13/02 10:48:23,265 ERROR [547023909248] (types.h:304) Cannot open '/dev/video2 Last Error: No such file or directory
 13/02 10:48:23,266 ERROR [547023909248] (global_timestamp_reader.cpp:188) Error during time_diff_keeper polling: Cannot open '/dev/video2 Last Error: No such file or directory
 13/02 10:48:23,367 ERROR [547023909248] (types.h:304) Cannot open '/dev/video2 Last Error: No such file or directory
 13/02 10:48:23,368 ERROR [547023909248] (global_timestamp_reader.cpp:188) Error during time_diff_keeper polling: Cannot open '/dev/video2 Last Error: No such file or directory
 13/02 10:48:23,469 ERROR [547023909248] (types.h:304) Cannot open '/dev/video2 Last Error: No such file or directory
 13/02 10:48:23,470 ERROR [547023909248] (global_timestamp_reader.cpp:188) Error during time_diff_keeper polling: Cannot open '/dev/video2 Last Error: No such file or directory
 13/02 10:48:23,571 ERROR [547023909248] (types.h:304) Cannot open '/dev/video2 Last Error: No such file or directory
 13/02 10:48:23,572 ERROR [547023909248] (global_timestamp_reader.cpp:188) Error during time_diff_keeper polling: Cannot open '/dev/video2 Last Error: No such file or directory
 13/02 10:48:23,673 ERROR [547023909248] (types.h:304) Cannot open '/dev/video2 Last Error: No such file or directory
`

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@job-1994,

Did you have a chance to find all the needed details? Do you still need an assistance with this matter?

**Comment by job-1994** [comment]
Yes, please see previous post for details

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@job-1994,

We still don't have information about FW version you use and about how the camera is connected to the host system (powered/unpowered hub, direct connection,etc). Please provide us with these details.

Thank you!

P.S.  - please provide answers for the questions we're asking in the new comments instead of
editing your already posted comments.
