### ISSUE TITLE
catkin_make failed recipe for target 'realsense-ros/realsense2_camera/CMakeFiles/realsense2_camera.dir/all' failed

### ISSUE THREAD

**Issue by msfarhan** [realsenseai/realsense-ros#1059]
Hello,
my realsense was camera working all fine suddenly after updates I guess it giving my some errors which 

error is 

```
make[2]: *** No rule to make target '/opt/ros/kinetic/lib/x86_64-linux-gnu/librealsense2.so.2.30.0', needed by '/home/farhan/catkin_ws/devel/lib/librealsense2_camera.so'.  Stop.
CMakeFiles/Makefile2:10996: recipe for target 'realsense-ros/realsense2_camera/CMakeFiles/realsense2_camera.dir/all' failed
make[1]: *** [realsense-ros/realsense2_camera/CMakeFiles/realsense2_camera.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 97%] Built target rosbridge_library_generate_messages
[ 97%] Built target realsense2_camera_generate_messages
[ 97%] Built target tf2_web_republisher_generate_messages
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j4 -l4" failed


and when i do 

```
sudo find / -name librealsense2.so*
/opt/ros/kinetic/lib/x86_64-linux-gnu/librealsense2.so.2.31.0
/opt/ros/kinetic/lib/x86_64-linux-gnu/librealsense2.so
/opt/ros/kinetic/lib/x86_64-linux-gnu/librealsense2.so.2.31

i tried [this](https://github.com/IntelRealSense/realsense-ros/issues/513#issuecomment-443534460)
still not solved 

im using ubuntu 16.04 with 4.15.0-74-generic kernel x86_64
```

```

**Comment by RealSenseSupport** [comment]
Hi,

Will you be needing further help with this? If we don’t hear from you in 7 days, this issue will be closed.

Thanks
