### ISSUE TITLE
SR300 urdf or axis model

### ISSUE THREAD

**Issue by lepalom** [realsenseai/realsense-ros#1066]
Someone has a documentation of how are defined the camera axes in the Realsense SR300?

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Hi @lepalom

Sorry for the delay on this topic.  We do not have this information for SR300.

**Comment by swinterbotix** [comment]
So what TF frames are being used then when running the rs_camera launch file with the SR300 camera? Rviz still displays the frames with some offset between them?!?!?

For anyone else who finds their way here, I was able to figure out the appropriate (I think!) TF frames from  https://www.intelrealsense.com/wp-content/uploads/2019/07/RealSense_SR30x_Product_Datasheet_Rev_002.pdf (Page 48). You should just hard-code these values in your own custom URDF and set 'publish_tf' to False in the rs_rgbd.launch file (first have to add it though as it's not in the launch file by default).
