### ISSUE TITLE
Nothing published when using an external nodelet manager

### ISSUE THREAD

**Issue by mjsobrep** [realsenseai/realsense-ros#1069]
This might be similar to #697 , but I am still having trouble. 

If I run this launch file (case 1):
```xml
<launch>
    <node pkg="nodelet" type="nodelet" name="cust_manager"  args="manager"/>
    <include file="$(find realsense2_camera)/launch/rs_camera.launch">
        <arg name="external_manager" value="false"/>
        <arg name="manager"          value="cust_manager"/>
    </include>
</launch>
```
Then things work well enough for me, some video gets published, etc. 

If I run this though (case 2):
```xml
<launch>
    <node pkg="nodelet" type="nodelet" name="cust_manager"  args="manager"/>
    <include file="$(find realsense2_camera)/launch/rs_camera.launch">
        <arg name="external_manager" value="true"/>
        <arg name="manager"          value="cust_manager"/>
    </include>
</launch>
```
Then nothing gets published. 

Any thoughts as to what is going on?

## Case 1 launch printouts:
<pre> roslaunch flo_telepresence min_realsense.launch 
... logging to /home/nuc-admin/.ros/log/638b85a0-43a2-11ea-b0d9-e470b83e61ec/roslaunch-flo-nuc-4060.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is &lt;1GB.

<b>started roslaunch server http://10.42.0.189:44275/</b>

SUMMARY
========

PARAMETERS
 * /camera/realsense2_camera/accel_fps: 250
 * /camera/realsense2_camera/accel_frame_id: camera_accel_frame
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: False
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/allow_no_texture_points: False
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/calib_odom_file: 
 * /camera/realsense2_camera/clip_distance: -2.0
 * /camera/realsense2_camera/color_fps: 30
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: 480
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: 640
 * /camera/realsense2_camera/depth_fps: 30
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: 480
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: 640
 * /camera/realsense2_camera/enable_accel: True
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye1: True
 * /camera/realsense2_camera/enable_fisheye2: True
 * /camera/realsense2_camera/enable_fisheye: True
 * /camera/realsense2_camera/enable_gyro: True
 * /camera/realsense2_camera/enable_infra1: True
 * /camera/realsense2_camera/enable_infra2: True
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_sync: False
 * /camera/realsense2_camera/filters: 
 * /camera/realsense2_camera/fisheye1_frame_id: camera_fisheye1_f...
 * /camera/realsense2_camera/fisheye1_optical_frame_id: camera_fisheye1_o...
 * /camera/realsense2_camera/fisheye2_frame_id: camera_fisheye2_f...
 * /camera/realsense2_camera/fisheye2_optical_frame_id: camera_fisheye2_o...
 * /camera/realsense2_camera/fisheye_fps: 30
 * /camera/realsense2_camera/fisheye_frame_id: camera_fisheye_frame
 * /camera/realsense2_camera/fisheye_height: 480
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: 640
 * /camera/realsense2_camera/gyro_fps: 400
 * /camera/realsense2_camera/gyro_frame_id: camera_gyro_frame
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/imu_optical_frame_id: camera_imu_optica...
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra_fps: 30
 * /camera/realsense2_camera/infra_height: 480
 * /camera/realsense2_camera/infra_width: 640
 * /camera/realsense2_camera/initial_reset: False
 * /camera/realsense2_camera/json_file_path: 
 * /camera/realsense2_camera/linear_accel_cov: 0.01
 * /camera/realsense2_camera/odom_frame_id: camera_odom_frame
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/pose_frame_id: camera_pose_frame
 * /camera/realsense2_camera/pose_optical_frame_id: camera_pose_optic...
 * /camera/realsense2_camera/publish_odom_tf: True
 * /camera/realsense2_camera/rosbag_filename: 
 * /camera/realsense2_camera/serial_no: 
 * /camera/realsense2_camera/topic_odom_in: odom_in
 * /camera/realsense2_camera/unite_imu_method: 
 * /rosdistro: kinetic
 * /rosversion: 1.12.14

NODES
  /camera/
    cust_manager (nodelet/nodelet)
    realsense2_camera (nodelet/nodelet)
  /
    cust_manager (nodelet/nodelet)

auto-starting new master
<b>process[master]: started with pid [4070]</b>
<b>ROS_MASTER_URI=http://localhost:11311</b>

<b>setting /run_id to 638b85a0-43a2-11ea-b0d9-e470b83e61ec</b>
<b>process[rosout-1]: started with pid [4083]</b>
started core service [/rosout]
<b>process[cust_manager-2]: started with pid [4100]</b>
<b>process[camera/cust_manager-3]: started with pid [4101]</b>
<b>process[camera/realsense2_camera-4]: started with pid [4102]</b>
[ INFO] [1580417533.011812306]: Initializing nodelet with 4 worker threads.
[ INFO] [1580417533.043819405]: RealSense ROS v2.2.8
[ INFO] [1580417533.043854124]: Running with LibRealSense v2.31.0
[ INFO] [1580417533.688221936]: getParameters...
[ INFO] [1580417533.762252369]: setupDevice...
[ INFO] [1580417533.762281930]: JSON file is not provided
[ INFO] [1580417533.762307653]: ROS Node Namespace: camera
[ INFO] [1580417533.762329644]: Device Name: Intel RealSense D415
[ INFO] [1580417533.762343092]: Device Serial No: 912322061173
[ INFO] [1580417533.762357985]: Device FW version: 05.12.01.00
[ INFO] [1580417533.762372675]: Device Product ID: 0x0AD3
[ INFO] [1580417533.762388225]: Enable PointCloud: Off
[ INFO] [1580417533.762399367]: Align Depth: Off
[ INFO] [1580417533.762410256]: Sync Mode: Off
[ INFO] [1580417533.762655335]: Device Sensors: 
[ INFO] [1580417533.762834943]: Stereo Module was found.
[ INFO] [1580417533.762877406]: RGB Camera was found.
[ INFO] [1580417533.762920144]: (Fisheye, 0) sensor isn&apos;t supported by current device! -- Skipping...
[ INFO] [1580417533.762939820]: (Fisheye, 1) sensor isn&apos;t supported by current device! -- Skipping...
[ INFO] [1580417533.762954683]: (Fisheye, 2) sensor isn&apos;t supported by current device! -- Skipping...
[ INFO] [1580417533.762969634]: (Gyro, 0) sensor isn&apos;t supported by current device! -- Skipping...
[ INFO] [1580417533.762984424]: (Accel, 0) sensor isn&apos;t supported by current device! -- Skipping...
[ INFO] [1580417533.762999767]: (Pose, 0) sensor isn&apos;t supported by current device! -- Skipping...
[ INFO] [1580417533.763185627]: num_filters: 0
[ INFO] [1580417533.763201430]: Setting Dynamic reconfig parameters.
[ INFO] [1580417533.913835560]: Done Setting Dynamic reconfig parameters.
[ INFO] [1580417533.931383032]: depth stream is enabled - width: 640, height: 480, fps: 30
[ INFO] [1580417533.931896955]: infra1 stream is enabled - width: 640, height: 480, fps: 30
[ INFO] [1580417533.932353326]: infra2 stream is enabled - width: 640, height: 480, fps: 30
[ INFO] [1580417533.944252792]: color stream is enabled - width: 640, height: 480, fps: 30
[ INFO] [1580417533.944294984]: setupPublishers...
[ INFO] [1580417533.947266268]: Expected frequency for depth = 30.00000
[ INFO] [1580417533.970961613]: Expected frequency for infra1 = 30.00000
[ INFO] [1580417533.989461733]: Expected frequency for infra2 = 30.00000
[ INFO] [1580417534.008060769]: Expected frequency for color = 30.00000
[ INFO] [1580417534.027910181]: setupStreams...
[ INFO] [1580417534.028795296]: insert Depth to Stereo Module
[ INFO] [1580417534.028968903]: insert Color to RGB Camera
[ INFO] [1580417534.029017394]: insert Infrared to Stereo Module
[ INFO] [1580417534.029054552]: insert Infrared to Stereo Module
[ INFO] [1580417534.045594559]: SELECTED BASE:Depth, 0
[ INFO] [1580417534.129942557]: RealSense Node Is Up!
</pre>

## Case 1 topics:
<pre><font color="#EEEEEC"><b>[I]</b></font><b> </b><font color="#8AE234"><b>➜ </b></font><font color="#4E9A06">rostopic</font> list
/camera/color/camera_info
/camera/color/image_raw
/camera/color/image_raw/compressed
/camera/color/image_raw/compressed/parameter_descriptions
/camera/color/image_raw/compressed/parameter_updates
/camera/color/image_raw/compressedDepth
/camera/color/image_raw/compressedDepth/parameter_descriptions
/camera/color/image_raw/compressedDepth/parameter_updates
/camera/color/image_raw/theora
/camera/color/image_raw/theora/parameter_descriptions
/camera/color/image_raw/theora/parameter_updates
/camera/cust_manager/bond
/camera/depth/camera_info
/camera/depth/image_rect_raw
/camera/depth/image_rect_raw/compressed
/camera/depth/image_rect_raw/compressed/parameter_descriptions
/camera/depth/image_rect_raw/compressed/parameter_updates
/camera/depth/image_rect_raw/compressedDepth
/camera/depth/image_rect_raw/compressedDepth/parameter_descriptions
/camera/depth/image_rect_raw/compressedDepth/parameter_updates
/camera/depth/image_rect_raw/theora
/camera/depth/image_rect_raw/theora/parameter_descriptions
/camera/depth/image_rect_raw/theora/parameter_updates
/camera/extrinsics/depth_to_color
/camera/extrinsics/depth_to_infra1
/camera/extrinsics/depth_to_infra2
/camera/infra1/camera_info
/camera/infra1/image_rect_raw
/camera/infra1/image_rect_raw/compressed
/camera/infra1/image_rect_raw/compressed/parameter_descriptions
/camera/infra1/image_rect_raw/compressed/parameter_updates
/camera/infra1/image_rect_raw/compressedDepth
/camera/infra1/image_rect_raw/compressedDepth/parameter_descriptions
/camera/infra1/image_rect_raw/compressedDepth/parameter_updates
/camera/infra1/image_rect_raw/theora
/camera/infra1/image_rect_raw/theora/parameter_descriptions
/camera/infra1/image_rect_raw/theora/parameter_updates
/camera/infra2/camera_info
/camera/infra2/image_rect_raw
/camera/infra2/image_rect_raw/compressed
/camera/infra2/image_rect_raw/compressed/parameter_descriptions
/camera/infra2/image_rect_raw/compressed/parameter_updates
/camera/infra2/image_rect_raw/compressedDepth
/camera/infra2/image_rect_raw/compressedDepth/parameter_descriptions
/camera/infra2/image_rect_raw/compressedDepth/parameter_updates
/camera/infra2/image_rect_raw/theora
/camera/infra2/image_rect_raw/theora/parameter_descriptions
/camera/infra2/image_rect_raw/theora/parameter_updates
/camera/rgb_camera/auto_exposure_roi/parameter_descriptions
/camera/rgb_camera/auto_exposure_roi/parameter_updates
/camera/rgb_camera/parameter_descriptions
/camera/rgb_camera/parameter_updates
/camera/stereo_module/auto_exposure_roi/parameter_descriptions
/camera/stereo_module/auto_exposure_roi/parameter_updates
/camera/stereo_module/parameter_descriptions
/camera/stereo_module/parameter_updates
/diagnostics
/rosout
/rosout_agg
/tf_static
</pre>

## Case 2 launch printouts:
<pre> roslaunch flo_telepresence min_realsense.launch 
... logging to /home/nuc-admin/.ros/log/f41e642a-43a2-11ea-b0d9-e470b83e61ec/roslaunch-flo-nuc-5528.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is &lt;1GB.

<b>started roslaunch server http://10.42.0.189:45491/</b>

SUMMARY
========

PARAMETERS
 * /camera/realsense2_camera/accel_fps: 250
 * /camera/realsense2_camera/accel_frame_id: camera_accel_frame
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: False
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/allow_no_texture_points: False
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/calib_odom_file: 
 * /camera/realsense2_camera/clip_distance: -2.0
 * /camera/realsense2_camera/color_fps: 30
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: 480
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: 640
 * /camera/realsense2_camera/depth_fps: 30
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: 480
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: 640
 * /camera/realsense2_camera/enable_accel: True
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye1: True
 * /camera/realsense2_camera/enable_fisheye2: True
 * /camera/realsense2_camera/enable_fisheye: True
 * /camera/realsense2_camera/enable_gyro: True
 * /camera/realsense2_camera/enable_infra1: True
 * /camera/realsense2_camera/enable_infra2: True
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_sync: False
 * /camera/realsense2_camera/filters: 
 * /camera/realsense2_camera/fisheye1_frame_id: camera_fisheye1_f...
 * /camera/realsense2_camera/fisheye1_optical_frame_id: camera_fisheye1_o...
 * /camera/realsense2_camera/fisheye2_frame_id: camera_fisheye2_f...
 * /camera/realsense2_camera/fisheye2_optical_frame_id: camera_fisheye2_o...
 * /camera/realsense2_camera/fisheye_fps: 30
 * /camera/realsense2_camera/fisheye_frame_id: camera_fisheye_frame
 * /camera/realsense2_camera/fisheye_height: 480
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: 640
 * /camera/realsense2_camera/gyro_fps: 400
 * /camera/realsense2_camera/gyro_frame_id: camera_gyro_frame
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/imu_optical_frame_id: camera_imu_optica...
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra_fps: 30
 * /camera/realsense2_camera/infra_height: 480
 * /camera/realsense2_camera/infra_width: 640
 * /camera/realsense2_camera/initial_reset: False
 * /camera/realsense2_camera/json_file_path: 
 * /camera/realsense2_camera/linear_accel_cov: 0.01
 * /camera/realsense2_camera/odom_frame_id: camera_odom_frame
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/pose_frame_id: camera_pose_frame
 * /camera/realsense2_camera/pose_optical_frame_id: camera_pose_optic...
 * /camera/realsense2_camera/publish_odom_tf: True
 * /camera/realsense2_camera/rosbag_filename: 
 * /camera/realsense2_camera/serial_no: 
 * /camera/realsense2_camera/topic_odom_in: odom_in
 * /camera/realsense2_camera/unite_imu_method: 
 * /rosdistro: kinetic
 * /rosversion: 1.12.14

NODES
  /camera/
    realsense2_camera (nodelet/nodelet)
  /
    cust_manager (nodelet/nodelet)

auto-starting new master
<b>process[master]: started with pid [5538]</b>
<b>ROS_MASTER_URI=http://localhost:11311</b>

<b>setting /run_id to f41e642a-43a2-11ea-b0d9-e470b83e61ec</b>
<b>process[rosout-1]: started with pid [5551]</b>
started core service [/rosout]
<b>process[cust_manager-2]: started with pid [5568]</b>
<b>process[camera/realsense2_camera-3]: started with pid [5569]</b>
</pre>

## Case 2 topics:
<pre><font color="#4E9A06">rostopic</font> list                      
/rosout
/rosout_agg
</pre>

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Hi @mjsobrep,

An ability to use external manager has been added long time ago. Can you please clarify what are you trying to achieve in both cases and describe the structure of your system including nodes/nodelets that should run in the system, managers, etc.

Thank you!

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@mjsobrep,

Do you still need help with this question?

**Comment by mjsobrep** [comment]
@RealSenseCustomerSupport Sorry I was slow to respond. In the 2 months between my original question and your response I had to move on. I might come back to this later...

**Comment by shuhaowu** [comment]
I ran into the same issue. You need to have the absolute path in `external_manager`, like this:

```
 <arg name="manager"          value="/cust_manager"/>
```

Otherwise, it tries to find cust_manager in the camera namespace.
