### ISSUE TITLE
RGB data is not displaying in both realsense viewer, as well in rostopic echo, #window_crash #no_image_display

### ISSUE THREAD

**Issue by chaitudarz** [realsenseai/realsense-ros#1070]
Hello,

Today, I have installed the real sense-ros wrapper, using https://github.com/IntelRealSense/realsense-ros. Everything was fine, but when I launched the realsense-viewer, I can't see the RGB data, when I turn **on** the toggle button in the viewer, the entire realsense-viewer screen gets crashed out. Secondly, even I tried checking using the rostopic echo /camera/color/image_raw, I can't even see any data get publishing. 
![error_all](https://user-images.githubusercontent.com/32367931/73666454-2013bf00-46a3-11ea-9517-9cdafbd486e2.png).

![3](https://user-images.githubusercontent.com/32367931/73667961-623e0000-46a5-11ea-91c0-c58ac0587858.png)
![1](https://user-images.githubusercontent.com/32367931/73667962-623e0000-46a5-11ea-9e49-a23007735078.png)

Sometimes, I even see this error along with other errors.

> realsense-viewer: ../../src/xcb_io.c:274: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
 03/02 16:32:44,823 ERROR [140614238713600] (backend-v4l2.cpp:1235) oject_pixel_to_point(float*, const rs2_intrinsics*, const float*, float)
Segmentation fault (core dumped)

I am using 

- Linux 16.04, 4.15.0-76-generic

- ROS: kinetic

- Camera: D435i

I tried to figure out by reading the closed issues, but I couldn't find one. 
This was my first issue throughout the Github. Please let me know if the question and description were not clear.

Regards,
Chaitu

**Comment by RealSenseSupport** [comment]
Hi,

Do you still need further help with this? 

Everything appears to work as expected here. Have your tried removing and reinstalling the SDK from latest? 

If we don’t hear from you in 7 days, this issue will be closed.

Thanks
