### ISSUE TITLE
Pointcloud Unreliable (D435)

### ISSUE THREAD

**Issue by danem** [realsenseai/realsense-ros#1071]
I'm using the ROS wrapper for realsense and I'm running into performance and reliability issues. Running:

    roslaunch realsense2_camera rs_camera.launch serial_no:=<serial> filters:=pointcloud 

and 

    rostopic hz /camera/depth/color/points

usually results in a series of `no new messages` errors, and on the off chance that I do get a message it's usually around 0.5hz.

[Here](https://github.com/IntelRealSense/realsense-ros/files/4155242/log.txt) is the output of `rs_camera.launch`. 

[Here](https://github.com/IntelRealSense/realsense-ros/files/4155246/log.txt) is the output of `rostopic hz`. 

Note that I'm running from a Docker container (Ubuntu 18.04) with the cameras mounted using the `device` flag. When running `realsense-viewer` I don't see any reliability issues.

Here is htop:

![htop](https://user-images.githubusercontent.com/828112/73775867-96640000-473b-11ea-9900-4c693e37229f.png)

**Comment by doronhi** [comment]
It seems like a duplication of #1047. [Librealsense PR#5751](https://github.com/IntelRealSense/librealsense/pull/5751) fixes that. It will be available in the upcoming release.

**Comment by RealSenseSupport** [comment]
Hi,

Will you be needing further help with this? If we don’t hear from you in 7 days, this issue will be closed.

Thanks
