### ISSUE TITLE
Recorded bag files for recurring problems with T265 

### ISSUE THREAD

**Issue by shannonwarren** [realsenseai/realsense-ros#1082]
I've been trying to integrate the realsense T265 with our existing SLAM setup. It works fairly well for an indoor robot however heavily depends on the environment. For environments like malls etc with highly reflective floors and walls there is a significant amount of pose jump however for carpeted floors I've seen better results. I've been plotting stats and collecting bag files for tracking confidence, pose jumps, NaN readings and device restarts and hoping for some help with these issues.

<img width="1648" alt="Screen Shot 2020-02-14 at 11 02 42 AM" src="https://user-images.githubusercontent.com/46359438/74559896-4266d180-4f1a-11ea-806f-947edd30aaed.png">

Here tracking confidence of 3 is the highest and 0 being the lowest. Pose jumps are categorized on a jump of more than 0.25m from the previous pose (our robot travels at a max speed of 0.5m/sec with wheel odometry fed into the T265 at every 10hz ). I'm trying to use the T265 as a visual odometry input to my SLAM algorithm with pose_jump; relocalization and mapping setup to false.

https://drive.google.com/open?id=1VTmSggySz8-yxLuI3MiUVNV0la0y4Lud

This first bag file shows NaN readings after a sudden halt in motion. Here the pose jumps, throws a bunch of NaN readings and the device restarts. 

The second bag files is something I've seen in the lastest version of librealsense 2.32. Even when the robot is in motion the output pose of the T265 is 0,0,0 but the orientation is updated and it takes a couple of seconds  for the T265 to send out a pose. (The solution is to unplug and plug the wire from the T265 camera )

My solution to these issues is to restart my SLAM at the point of failure however its happening to often and hence not a viable solution. On the bright side, the accuracy of the T265 odometry when the tracking confidence is high is fairly accurate which makes me want to push for this as a soltuion to our existing SLAM system and I would like any assistance with solving these recurring issues. Thanks @doronhi @schmidtp1 https://github.com/IntelRealSense/realsense-ros/issues/1061

**Comment by RealSenseSupport** [comment]
We are familiar with the issues that you are seeing with T265.  These are known issues as outlined in the specification document:  https://dev.intelrealsense.com/docs/tracking-camera-t265
