### ISSUE TITLE
Realsense D400 with gazebo 

### ISSUE THREAD

**Issue by q8wwe** [realsenseai/realsense-ros#1094]
Can I use intel realsense SDK with gazebo .
I want to work on it with gazebo simulation before test on real robot .therefor ,  can compile this wrapper and use it with gazebo simulation ?

**Comment by MartyG-RealSense** [comment]
There is a tutorial for using Gazebo for ROS that was designed for Kinect but says it can be used with other depth cameras.

http://gazebosim.org/tutorials?tut=ros_depth_camera&cat=connect_ros

There was an official RealSense Gazebo plugin a couple of years ago but it was designed for the older RealSense R200 stereo camera model.

https://github.com/intel/gazebo-realsense

A RealSense user later wrote their own evolution of that plugin.

https://github.com/SyrianSpock/realsense_gazebo_plugin

**Comment by q8wwe** [comment]
thank you , I will check it.

**Comment by q8wwe** [comment]
I'm still looking for a stimulation I searched around but still can't make it work with gazebo .
by the search i get the sense it possible but still i don't know how!!

**Comment by MartyG-RealSense** [comment]
Recently there was an article on the RealSense blog about building your first RealSense robot, called the ERWHI Hedgehog.

https://www.intelrealsense.com/hedgehog-robot-by-erwhi/

The main website for the ERWHI Hedgehog robot project says that it can be simulated in Gazebo Simulator.

https://gbr1.github.io/erwhi_hedgehog.html

If you investigate the details of the ERWHI Hedgehog project's construction then this may provide one of the most user-friendly ways to get a modern RealSense camera working with a Gazebo simulation.

Below are the Gazebo links from the ERWHI Hedgehog site.

http://gazebosim.org/

https://github.com/gbr1/erwhi-hedgehog-ros/tree/kinetic/erwhi_gazebo

https://www.youtube.com/watch?v=R5mXczDg0mo

**Comment by q8wwe** [comment]
Thank you , i will check and come back

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
