### ISSUE TITLE
Error in catkin_make on a Nvidia Jetson AGX: error: ‘wheel_odometer’ in namespace ‘rs2’ does not name a type rs2::wheel_odometer _wo_snr

### ISSUE THREAD

**Issue by DrDiegoPaez** [realsenseai/realsense-ros#1100]
This error came very recently after some updates to the Nvidia Jetson AGX:
catkin_make -DCATKIN_ENABLE_TESTING=False -DCMAKE_BUILD_TYPE=Release

Nvidia Jetson AGX, with ROS Melodic 
librealsense v2.17.1

Error LOG:

[ 95%] Built target fake_dynamic_reconfigure_server
In file included from /ssd_nvidia/autonomy_ws/src/realsense-ros/realsense2_camera/src/realsense_node_factory.cpp:6:0:
/ssd_nvidia/autonomy_ws/src/realsense-ros/realsense2_camera/src/../include/t265_realsense_node.h:25:18: error: ‘wheel_odometer’ in namespace ‘rs2’ does not name a type
             rs2::wheel_odometer _wo_snr;
                  ^~~~~~~~~~~~~~
/ssd_nvidia/autonomy_ws/src/realsense-ros/realsense2_camera/src/realsense_node_factory.cpp: In member function ‘void realsense2_camera::RealSenseNodeFactory::getDevice(rs2::device_list)’:
/ssd_nvidia/autonomy_ws/src/realsense-ros/realsense2_camera/src/realsense_node_factory.cpp:159:8: error: ‘class rs2::context’ has no member named ‘unload_tracking_module’
   _ctx.unload_tracking_module();
        ^~~~~~~~~~~~~~~~~~~~~~
realsense-ros/realsense2_camera/CMakeFiles/realsense2_camera.dir/build.make:62: recipe for target 'realsense-ros/realsense2_camera/CMakeFiles/realsense2_camera.dir/src/realsense_node_factory.cpp.o' failed
make[2]: *** [realsense-ros/realsense2_camera/CMakeFiles/realsense2_camera.dir/src/realsense_node_factory.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /ssd_nvidia/autonomy_ws/src/realsense-ros/realsense2_camera/src/t265_realsense_node.cpp:1:0:
/ssd_nvidia/autonomy_ws/src/realsense-ros/realsense2_camera/src/../include/t265_realsense_node.h:25:18: error: ‘wheel_odometer’ in namespace ‘rs2’ does not name a type
             rs2::wheel_odometer _wo_snr;
                  ^~~~~~~~~~~~~~
/ssd_nvidia/autonomy_ws/src/realsense-ros/realsense2_camera/src/t265_realsense_node.cpp: In constructor ‘realsense2_camera::T265RealsenseNode::T265RealsenseNode(ros::NodeHandle&, ros::NodeHandle&, rs2::device, const string&)’:
/ssd_nvidia/autonomy_ws/src/realsense-ros/realsense2_camera/src/t265_realsense_node.cpp:10:38: error: class ‘realsense2_camera::T265RealsenseNode’ does not have any field named ‘_wo_snr’
                                      _wo_snr(dev.first<rs2::wheel_odometer>()),
                                      ^~~~~~~
/ssd_nvidia/autonomy_ws/src/realsense-ros/realsense2_camera/src/t265_realsense_node.cpp:10:56: error: ‘wheel_odometer’ is not a member of ‘rs2’
                                      _wo_snr(dev.first<rs2::wheel_odometer>()),
                                                        ^~~
/ssd_nvidia/autonomy_ws/src/realsense-ros/realsense2_camera/src/t265_realsense_node.cpp:10:56: error: ‘wheel_odometer’ is not a member of ‘rs2’
/ssd_nvidia/autonomy_ws/src/realsense-ros/realsense2_camera/src/t265_realsense_node.cpp:10:77: error: no matching function for call to ‘rs2::device::first()’
                                      _wo_snr(dev.first<rs2::wheel_odometer>()),
                                                                             ^
In file included from /usr/local/include/librealsense2/hpp/rs_record_playback.hpp:8:0,
                 from /usr/local/include/librealsense2/hpp/rs_context.hpp:8,
                 from /usr/local/include/librealsense2/rs.hpp:9,
                 from /ssd_nvidia/autonomy_ws/src/realsense-ros/realsense2_camera/include/../include/realsense_node_factory.h:11,
                 from /ssd_nvidia/autonomy_ws/src/realsense-ros/realsense2_camera/include/base_realsense_node.h:6,
                 from /ssd_nvidia/autonomy_ws/src/realsense-ros/realsense2_camera/src/../include/t265_realsense_node.h:3,
                 from /ssd_nvidia/autonomy_ws/src/realsense-ros/realsense2_camera/src/t265_realsense_node.cpp:1:
/usr/local/include/librealsense2/hpp/rs_device.hpp:52:11: note: candidate: template<class T> T rs2::device::first() const
         T first() const
           ^~~~~
/usr/local/include/librealsense2/hpp/rs_device.hpp:52:11: note:   template argument deduction/substitution failed:
/ssd_nvidia/autonomy_ws/src/realsense-ros/realsense2_camera/src/t265_realsense_node.cpp:10:77: error: template argument 1 is invalid
                                      _wo_snr(dev.first<rs2::wheel_odometer>()),
                                                                             ^
/ssd_nvidia/autonomy_ws/src/realsense-ros/realsense2_camera/src/t265_realsense_node.cpp: In member function ‘void realsense2_camera::T265RealsenseNode::initializeOdometryInput()’:
/ssd_nvidia/autonomy_ws/src/realsense-ros/realsense2_camera/src/t265_realsense_node.cpp:36:10: error: ‘_wo_snr’ was not declared in this scope
     if (!_wo_snr.load_wheel_odometery_config(wo_calib))
          ^~~~~~~
/ssd_nvidia/autonomy_ws/src/realsense-ros/realsense2_camera/src/t265_realsense_node.cpp: In member function ‘void realsense2_camera::T265RealsenseNode::odom_in_callback(const ConstPtr&)’:
/ssd_nvidia/autonomy_ws/src/realsense-ros/realsense2_camera/src/t265_realsense_node.cpp:69:5: error: ‘_wo_snr’ was not declared in this scope
     _wo_snr.send_wheel_odometry(0, 0, velocity);
     ^~~~~~~
realsense-ros/realsense2_camera/CMakeFiles/realsense2_camera.dir/build.make:110: recipe for target 'realsense-ros/realsense2_camera/CMakeFiles/realsense2_camera.dir/src/t265_realsense_node.cpp.o' failed
make[2]: *** [realsense-ros/realsense2_camera/CMakeFiles/realsense2_camera.dir/src/t265_realsense_node.cpp.o] Error 1
CMakeFiles/Makefile2:2076: recipe for target 'realsense-ros/realsense2_camera/CMakeFiles/realsense2_camera.dir/all' failed
make[1]: *** [realsense-ros/realsense2_camera/CMakeFiles/realsense2_camera.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j4 -l4" failed

**Comment by RealSenseSupport** [comment]
Thank you for highlighting this issue while using T265. We have moved our focus to our next generation of products and consequently, we will not be addressing this issue in the T265.
