### ISSUE TITLE
tf dynamic thread never joins in desctructor

### ISSUE THREAD

**Issue by Dominik-FKIE** [realsenseai/realsense-ros#1103]
only checking ros::ok() in its main loop not enough, one needs another bool signaling end-of-lifetime. Something like

```
~BaseRealSenseNode()
 {
    _is_alive_tf_t = false;
    if (_tf_t && _tf_t->joinable())
        _tf_t->join();
...
}
```

and

```
publishDynamicTransforms()
{
     _is_alive_tf_t = true;
...
   while (ros::ok() && _is_alive_tf_t)
...
}
```

**Comment by doronhi** [comment]
While I see the logic in your claim, could you suggest a test case demonstrate? to show that using ros::ok() is not enough?
How will we notice a difference once implemented and applied your suggestion?

**Comment by Dominik-FKIE** [comment]
First of all, you have to set the parameter "tf_publish_rate" to something else than 0, because otherwise the thread will not be spawned. E.g. this is necessary in the multi-camera single nodelet_manager case, since then tf_static is buggy.

Then it is easily reproducible that your nodelet will not terminate properly but hang at the join() call until the nodelet_manager is also terminated (-> ros::ok() becomes false).

**Comment by RealSenseSupport** [comment]
Hi @Dominik-FKIE,

Please check the latest build of [ROS Wrapper v2.2.13](https://github.com/IntelRealSense/realsense-ros/releases/tag/2.2.13) and let us know whether you still see the problem.

Thank you!

**Comment by RealSenseSupport** [comment]
@Dominik-FKIE,

Did you have a chance to check the latest build of ROS Wrapper? Please inform us if you have any additional concerns and questions regarding this matter.

Thank you!
