### ISSUE TITLE
Setting up on Raspberry Pi

### ISSUE THREAD

**Issue by courtneyconroy** [realsenseai/realsense-ros#1105]
Hi,

I am having some difficulty setting up ROS on the raspberry pi when following the instructions. It says to install ROS kinetic first and then clone in realsense-ros into the source folder. Which package do I need to install? Is it desktop_full? Do I do the complete setup for ROS kinetic and then add it into source?  I want to use this for occupancy mapping with the T265 and D435.

Thanks.

**Comment by aswinkumar2019** [comment]
What is the problem you are facing?
Problem in installing realsense ros or, don't know the installation procedure?
If you have some problem in installing realsense ros package, give the problem you face while installing it. 
Installation procedure:
First, you have to install ros(install ros melodic)
Then, install librealsense, I think you have to install from source for raspberry pi(I am not sure about it).
Then, you have to install realsense ros package. 
Regards, 
Aswin Kumar

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@courtneyconroy For ROS Kinetic installation, please refer to http://wiki.ros.org/kinetic/Installation/Ubuntu

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@courtneyconroy Did you get it through? Looking forward to your update. Thanks!

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@courtneyconroy  Could you please update? Thanks!

**Comment by courtneyconroy** [comment]
Hi,

I decided to use Ubuntu mate 18.04 with ROS MELODIC. Worked fine then

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@courtneyconroy Thanks for the update! Close this accordingly.
