### ISSUE TITLE
realsensel D435/D453i  can not work

### ISSUE THREAD

**Issue by callmeSir007** [realsenseai/realsense-ros#1106]
OS: UBUNTU 18.04 lts

it work well，when i use the version ：
SDK: 2.26.0
realsense-ros： 2.2.7
dmks ： 1.3.6
fw：5.11.6.250

now，upgrade the version to：
SDK: 2.31.0
realsense-ros： 2.2.12
dmks ： 1.3.13
fw：5.11.15.0/  5.12.1.0 / 5.12.1.100

it can not work，

v:/opt/ros/melodic$ roslaunch realsense2_camera rs_camera.launch 
... logging to /home/igv/.ros/log/515de9d2-5f44-11ea-9f16-54b2038b5c5e/roslaunch-igv-693.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://igv:42841/

SUMMARY
========

PARAMETERS
 * /camera/realsense2_camera/accel_fps: 250
 * /camera/realsense2_camera/accel_frame_id: camera_accel_frame
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: False
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/allow_no_texture_points: False
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/calib_odom_file: 
 * /camera/realsense2_camera/clip_distance: -2.0
 * /camera/realsense2_camera/color_fps: 30
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: 480
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: 640
 * /camera/realsense2_camera/depth_fps: 30
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: 480
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: 640
 * /camera/realsense2_camera/device_type: 
 * /camera/realsense2_camera/enable_accel: True
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye1: True
 * /camera/realsense2_camera/enable_fisheye2: True
 * /camera/realsense2_camera/enable_fisheye: True
 * /camera/realsense2_camera/enable_gyro: True
 * /camera/realsense2_camera/enable_infra1: True
 * /camera/realsense2_camera/enable_infra2: True
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_sync: False
 * /camera/realsense2_camera/filters: 
 * /camera/realsense2_camera/fisheye1_frame_id: camera_fisheye1_f...
 * /camera/realsense2_camera/fisheye1_optical_frame_id: camera_fisheye1_o...
 * /camera/realsense2_camera/fisheye2_frame_id: camera_fisheye2_f...
 * /camera/realsense2_camera/fisheye2_optical_frame_id: camera_fisheye2_o...
 * /camera/realsense2_camera/fisheye_fps: 30
 * /camera/realsense2_camera/fisheye_frame_id: camera_fisheye_frame
 * /camera/realsense2_camera/fisheye_height: 480
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: 640
 * /camera/realsense2_camera/gyro_fps: 400
 * /camera/realsense2_camera/gyro_frame_id: camera_gyro_frame
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/imu_optical_frame_id: camera_imu_optica...
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra_fps: 30
 * /camera/realsense2_camera/infra_height: 480
 * /camera/realsense2_camera/infra_width: 640
 * /camera/realsense2_camera/initial_reset: False
 * /camera/realsense2_camera/json_file_path: 
 * /camera/realsense2_camera/linear_accel_cov: 0.01
 * /camera/realsense2_camera/odom_frame_id: camera_odom_frame
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/pose_frame_id: camera_pose_frame
 * /camera/realsense2_camera/pose_optical_frame_id: camera_pose_optic...
 * /camera/realsense2_camera/publish_odom_tf: True
 * /camera/realsense2_camera/publish_tf: True
 * /camera/realsense2_camera/rosbag_filename: 
 * /camera/realsense2_camera/serial_no: 
 * /camera/realsense2_camera/tf_publish_rate: 0.0
 * /camera/realsense2_camera/topic_odom_in: odom_in
 * /camera/realsense2_camera/unite_imu_method: 
 * /camera/realsense2_camera/usb_port_id: 
 * /rosdistro: melodic
 * /rosversion: 1.14.3

NODES
  /camera/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)

auto-starting new master
process[master]: started with pid [710]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 515de9d2-5f44-11ea-9f16-54b2038b5c5e
process[rosout-1]: started with pid [729]
started core service [/rosout]
process[camera/realsense2_camera_manager-2]: started with pid [737]
process[camera/realsense2_camera-3]: started with pid [743]
[ INFO] [1583455762.524300450]: Initializing nodelet with 4 worker threads.
[ INFO] [1583455762.612116824]: RealSense ROS v2.2.12
[ INFO] [1583455762.612154552]: Running with LibRealSense v2.31.0
[ INFO] [1583455762.947650801]:  
[ INFO] [1583455763.360439879]: Device with serial number 922612070377 was found.

[ INFO] [1583455763.360481673]: Device with physical ID 2-4-9 was found.
[ INFO] [1583455763.360497766]: Device with name Intel RealSense D435 was found.
[ WARN] [1583455763.361044466]: Error extracting usb port from device with physical ID: 2-4-9
Please report on github issue at https://github.com/IntelRealSense/realsense-ros
[ INFO] [1583455763.366277990]: getParameters...
[ INFO] [1583455763.430069710]: setupDevice...
[ INFO] [1583455763.430101941]: JSON file is not provided
[ INFO] [1583455763.430127302]: ROS Node Namespace: camera
[ INFO] [1583455763.430159072]: Device Name: Intel RealSense D435
[ INFO] [1583455763.430177118]: Device Serial No: 922612070377
[ INFO] [1583455763.430194001]: Device physical port: 2-4-9
[ INFO] [1583455763.430213011]: Device FW version: 05.11.15.00
[ INFO] [1583455763.430230291]: Device Product ID: 0x0B07
[ INFO] [1583455763.430246540]: Enable PointCloud: Off
[ INFO] [1583455763.430264952]: Align Depth: Off
[ INFO] [1583455763.430281101]: Sync Mode: Off
[ INFO] [1583455763.430324726]: Device Sensors: 
[ INFO] [1583455763.430372380]: Stereo Module was found.
[ INFO] [1583455763.430393774]: RGB Camera was found.
[ INFO] [1583455763.430433616]: (Fisheye, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1583455763.430454386]: (Fisheye, 1) sensor isn't supported by current device! -- Skipping...
[ INFO] [1583455763.430470238]: (Fisheye, 2) sensor isn't supported by current device! -- Skipping...
[ INFO] [1583455763.430487399]: (Gyro, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1583455763.430503625]: (Accel, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1583455763.430519879]: (Pose, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1583455763.430549142]: num_filters: 0
[ INFO] [1583455763.430568941]: Setting Dynamic reconfig parameters.
[ INFO] [1583455768.601865945]: Done Setting Dynamic reconfig parameters.
[ INFO] [1583455768.660803074]: depth stream is enabled - width: 640, height: 480, fps: 30, Format: Z16
[ INFO] [1583455768.661068407]: infra1 stream is enabled - width: 640, height: 480, fps: 30, Format: Y8
[ INFO] [1583455768.661249961]: infra2 stream is enabled - width: 640, height: 480, fps: 30, Format: Y8
[ INFO] [1583455768.706926867]: color stream is enabled - width: 640, height: 480, fps: 30, Format: RGB8
[ INFO] [1583455768.707071436]: setupPublishers...
[ INFO] [1583455768.711322332]: Expected frequency for depth = 30.00000
[ INFO] [1583455768.755255756]: Expected frequency for infra1 = 30.00000
[ INFO] [1583455768.799320962]: Expected frequency for infra2 = 30.00000
[ INFO] [1583455768.861429294]: Expected frequency for color = 30.00000
[ INFO] [1583455768.910047237]: setupStreams...
[ INFO] [1583455769.018791394]: insert Depth to Stereo Module
[ INFO] [1583455769.018849716]: insert Color to RGB Camera
[ INFO] [1583455769.018870029]: insert Infrared to Stereo Module
[ INFO] [1583455769.018884937]: insert Infrared to Stereo Module
 06/03 08:49:29,109 WARNING [139700580902656] (messenger-libusb.cpp:42) control_transfer returned error, index: 300, error: No data available, number: 3d
[ INFO] [1583455769.328613975]: SELECTED BASE:Depth, 0
[ INFO] [1583455769.375154188]: RealSense Node Is Up!
 06/03 08:49:29,385 WARNING [139700580902656] (messenger-libusb.cpp:42) control_transfer returned error, index: 300, error: No data available, number: 3d
 06/03 08:49:29,446 WARNING [139700580902656] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 06/03 08:49:29,555 WARNING [139700580902656] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 06/03 08:49:29,658 WARNING [139700580902656] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 06/03 08:49:29,846 WARNING [139700580902656] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 06/03 08:49:30,029 WARNING [139700580902656] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
calR

**Comment by jorgemiar** [comment]
I get the same warning messages when trying to run on an Up Squared board with Ubuntu 16.04, Librealsense 2.33.1, ROS Kinetic, ros-realsense 2.2.12 and the D435i

**Comment by doronhi** [comment]
@callmeSir007 , Thanks for the log file. I can see warning that are known and being investigated. Besides the uncomfortable warning messages, is there any topic that doesn't work or other behavior that prevent you from working?
@jorgemia ?
Thanks

**Comment by jorgemiar** [comment]
@callmeSir007 @doronhi I managed to fix these by applying PR #1088 (that didn't fix it immediately) and then running sudo apt purge ros-kinetic-librealsense2 as suggested in #1051 . After this, I ran catkin_make and no longer get issues when setting up the ros node.

**Comment by callmeSir007** [comment]
@jorgemia @doronhi 

thank you for your response

I use the patched kernel modules instead of libuvc and now i can not see the warning message。

reference：
https://github.com/IntelRealSense/realsense-ros/issues/1073
https://github.com/IntelRealSense/librealsense/issues/5212

-------

Now I have another problem

i keep the camera running and display pointcloud data through rviz

I always get an error message：

1583734285.459592471 ERROR /camera/realsense2_camera_manager [/igv_ros_ws/src/sensor/realsense/realsense2_camera/src/base_realsense_node.cpp:1604(BaseRealSenseNode::frame_callback)] [topics: ] An error has occurred during frame callback: Error occured during execution of the processing block! See the log for more info

After a while，The process encounters an error and restarts automatically

Refer to the attachment for details of the log
[rosout.log](https://github.com/IntelRealSense/realsense-ros/files/4305743/rosout.log)



Why did this error occur？？

**Comment by RealSenseSupport** [comment]
Hi,

Will you be needing further help with this? If we don’t hear from you in 7 days, this issue will be closed.

Thanks
