### ISSUE TITLE
 Error extracting usb port from device with physical ID: 2-1-3

### ISSUE THREAD

**Issue by jion8199** [realsenseai/realsense-ros#1107]
My system is Ubuntu18.04
Follow the instructions to complete the installation
![2020-03-06 11-31-36](https://user-images.githubusercontent.com/49380905/76047936-3b723280-5f9f-11ea-979f-7ae5fa37211e.png)
![2020-03-06 11-30-50](https://user-images.githubusercontent.com/49380905/76047959-4dec6c00-5f9f-11ea-8cb0-a118874d7362.png)
![2020-03-06 11-31-56](https://user-images.githubusercontent.com/49380905/76047974-5775d400-5f9f-11ea-97ae-d519bfb4664d.png)

**Comment by jion8199** [comment]
Added that my system is Jetson TX2, Ubuntu 18.4, ROS melodic,

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Hi @jion8199,

The issue was addressed in this PR: https://github.com/IntelRealSense/realsense-ros/pull/1088
Please let us know, if you need any further assistance with this matter.

Thank you!
