### ISSUE TITLE
No D435i model in realsense2_description

### ISSUE THREAD

**Issue by mcamurri** [realsenseai/realsense-ros#1127]
I see there is no D435i model in the description, but only the D435.
Therefore, it is no possible to have the IMU frames when the driver is not running live.

I've made a PR to fix this: #1126

**Comment by MartyG-RealSense** [comment]
@mcamurri   Thanks so much for the pull contribution, which has passed checks!

**Comment by mcamurri** [comment]
No problem, I'm happy to contribute.
Looking forward to see this and the other PR I've made merged.

**Comment by MartyG-RealSense** [comment]
As the pull has passed all checks, I will close this case now.  Thanks again for your contribution!
