### ISSUE TITLE
Camera error on Nvidia Jetson AGX Xavier: control_transfer returned error, index Resource temporarily unavalable, number

### ISSUE THREAD

**Issue by amburkoff** [realsenseai/realsense-ros#1131]
Camera error on Nvidia Jetson AGX Xavier
Computer: Jetson Xavier 
kernel 4.9.140-tegra
Jetpack 4.2
L4T 32.1.0
librealsense 2.32.1
realsense-ros 2.2.13
Firemware: ros camera fw 05.12.02.100
Camera Realsense d435

When I start one camera, after a while without displaying any errors, the camera stops publishing messages.
In this case, a lot of errors are still displayed, but the camera is working.
(see image realsense_single_camera.png)
https://drive.google.com/file/d/1YXLsZqkyeTlENp42CB4LIHp_5uuPMI65/view

**Comment by MartyG-RealSense** [comment]
There is a similar case recently reported with Jetson Nano, in the discussion linked to below.  I hope that the advice in that discussion will be helpful to you.

https://github.com/IntelRealSense/librealsense/issues/6062

**Comment by MartyG-RealSense** [comment]
This case will be closed after 7 days from the time of writing this message if there are no further comments.   Thanks!
