### ISSUE TITLE
occupancy-mapping will not run properly

### ISSUE THREAD

**Issue by justin-chau** [realsenseai/realsense-ros#1134]
**LibRealSense** v2.33.1
**D435i FW Version** 05.12.03.00
**T265 FW Version** 0.2.0.926

Running the occupancy-mapping demo following the readme results in the following error:
` 19/03 01:51:38,575 ERROR [140631456347904] (handle-libusb.h:95) failed to claim usb interface: 0, error: RS2_USB_STATUS_BUSY
 19/03 01:51:38,596 WARNING [140632491784064] (rs.cpp:283) null pointer passed for argument "device"
[ERROR] [1584597098.596200099]: An exception has been thrown: failed to set power state
[FATAL] [1584597098.596385518]: Failed to load nodelet '/d400/realsense2_camera' of type 'realsense2_camera/RealSenseNodeFactory' to manager 'realsense2_camera_manager'
[d400/realsense2_camera-5] process has died [pid 2715, exit code 255, cmd /opt/ros/melodic/lib/nodelet/nodelet load realsense2_camera/RealSenseNodeFactory realsense2_camera_manager __name:=realsense2_camera __log:=/home/justin/.ros/log/b2b8f882-69a5-11ea-9264-04d4c4483cb4/d400-realsense2_camera-5.log].
log file: /home/justin/.ros/log/b2b8f882-69a5-11ea-9264-04d4c4483cb4/d400-realsense2_camera-5*.log
`

Rviz launches and only displays the pose of the T265, but does not properly run otherwise. The D435i does not seem to launch properly. I suspect that the issue may be that the branch isn't being maintained and I am running a newer version of librealsense. Does anyone have some guidance on how I can get this to work?

Any help is appreciated! Thanks!

**Comment by zainmehdi** [comment]
Same error here. ROS melodic, D435i

**Comment by RealSenseSupport** [comment]
Hi,

Will you be needing further help with this? If we don’t hear from you in 7 days, this issue will be closed.

Thanks
