### ISSUE TITLE
how do i get pointcloud from rviz

### ISSUE THREAD

**Issue by suk8267** [realsenseai/realsense-ros#1135]
i successed from follow, but i don't know about how to get pointcloud by a coordinate. is there any exmaple?

**Comment by suk8267** [comment]
when i launch rs_rgbd.launch and turn on the rviz, i can see pointcloud, so launch file must be publishing topic. but i don't know about the topic's form

**Comment by MartyG-RealSense** [comment]
Here is an example image from the RViz section of Intel's D435i SLAM guide that I hope will be helpful, where the topic **/camera/color/image_raw** is used.

https://github.com/IntelRealSense/realsense-ros/wiki/SLAM-with-D435i#personalize-rviz

![image](https://user-images.githubusercontent.com/41145062/77062699-4b910580-69d4-11ea-8b04-4b4727ee58c6.png)

**Comment by MartyG-RealSense** [comment]
This case will be closed after 7 days from the time of writing this message if there are no further comments.  Thanks!
