### ISSUE TITLE
unable to locate package ros-melodic-realsense-camera

### ISSUE THREAD

**Issue by PonyZhou** [realsenseai/realsense-ros#1136]
i run  "sudo apt-get  install  ros-melodic-realsense-camera"  command and got a error "unable to locate package ros-melodic-realsense-camera"
i have updated the source list but still got the error

**Comment by MartyG-RealSense** [comment]
I note that in the instruction you quoted, there is a '2' missing from the 'realsense' part of the instruction.  It should be:

sudo apt-get install ros-melodic-realsense2-camera

**Comment by PonyZhou** [comment]
Thanks！You are right and had better correct the same wrong command in the Installation Instructions.

**Comment by MartyG-RealSense** [comment]
@PonyZhou  If you are referring to this instruction:

https://github.com/IntelRealSense/realsense-ros#method-1-the-ros-distribution

I will tag the wrapper's developer @doronhi into this discussion to highlight about including the installation instruction for Melodic.  Thanks!

**Comment by PonyZhou** [comment]
Yes, under the "Method 1: The ROS distribution:"

**Comment by doronhi** [comment]
Fixed. Thank you guys!

**Comment by MartyG-RealSense** [comment]
I will close this case now that the fix has been performed.  Thanks!
