### ISSUE TITLE
How to use full T265 Cam power : imu+fisheyes, for VSLAM MELODIC

### ISSUE THREAD

**Issue by elpimous** [realsenseai/realsense-ros#1141]
Hi Friends.
Using actually a D435 for gmapping and amcl, and rtabmap of course...

Now, I have a D435 and a T265 + robot wheels odometry...

I see on realsense_camera for Ros, that the launch only use T265 imu !!
And depth/rgb, from D435 !!

It's not the promised things !!

T265 would be very helpfull with fisheye cameras (see pirobot work with fisheyes test)
This fisheye could help too, in a very large vision, seing obstacles in avance...

IS there any launch file to help me integrate ALL input informations : 

Depth,rgb, both fisheyes, imu's and wheels odom.

What lib should  I use ?? Carto. ? Rtabmap ?

I really Hope yes..

Impatient to read U 

Thanks,
Vincent.

**Comment by RealSenseSupport** [comment]
Hi @elpimous 

Within our librealsense library and ROS library, the only starting point would be this launch file:  https://github.com/IntelRealSense/realsense-ros/blob/development/realsense2_camera/launch/rs_d400_and_t265.launch

Although one may need to modify for a given configuration.

If we don’t hear from you in 7 days, this issue will be closed.
