### ISSUE TITLE
How to convert pointcloud (x, y, z) to rgb image pixel(x, y) and convert back?

### ISSUE THREAD

**Issue by shadowdk3** [realsenseai/realsense-ros#1151]
Hi, 
I am using D435i, and want to:
1. convert pointcloud (x, y, z) to correspondence rgb image pixel (x, y)
2. convert rgb image pixel (x,y) to pointcloud (x, y, z)

I subscribe topic `/camera/depth/color/points` to get point cloud and want to point out in rgb image.

reference `def convert_pointcloud_to_depth(pointcloud, camera_intrinsics)` in 
[https://github.com/IntelRealSense/librealsense/blob/master/wrappers/python/examples/box_dimensioner_multicam/helper_functions.py](https://github.com/IntelRealSense/librealsense/blob/master/wrappers/python/examples/box_dimensioner_multicam/helper_functions.py)

After calculation, pixel is wrong.

My camera intrinsics info:
`"fx": 211.0712127685547, "fy": 211.0712127685547, "height": 240, "width": 424, "coeffs": [0.0, 0.0, 0.0, 0.0, 0.0], "ppy": 119.0328140258789, "ppx": 211.8135986328125, "model": "distortion.brown_conrady"`

My result:

origin pointcloud
![image](https://user-images.githubusercontent.com/38104992/78333788-159b7600-75bd-11ea-910b-97ac3fbbbc98.png)

extracted plane
![image](https://user-images.githubusercontent.com/38104992/78333799-1fbd7480-75bd-11ea-87ca-41ed044c5f24.png)

want to point out plane in rgb image, but the calculated pixel is wrong
![image](https://user-images.githubusercontent.com/38104992/78333828-28ae4600-75bd-11ea-9867-01f90ba70d7f.png)

When I convert the pixel back to point cloud, I subscribe topic `/camera/aligned_depth_to_color/image_raw`, and also try `/camera/depth/image_rect_raw`.

I pickup depth in depth image `depth = depth_img[y][x] / 1000` and use `def convert_depth_pixel_to_metric_coordinate(depth, pixel_x, pixel_y, camera_intrinsics)` convert pixel to pointcloud, but the value seem wrong.

I check the point could of plane, value Y are between 0.30 to 0.34. Then, I pick a point in rgb image and convert to point could, the result of value Y is 0.4.
 
I cannot proof I get a wrong data or I missing some param in camera config or using wrong formula.
I need help in this conversion. Thanks you.

**Comment by shadowdk3** [comment]
Finally, I found the camera intrinsics that generated from `profile.as_video_stream_profile().get_intrinsics()` is different to `/camera/aligned_depth_to_color/camera_info`. However, I don't know why `profile.as_video_stream_profile().get_intrinsics()` cannot get correct value.

**Comment by navneeth594** [comment]
Hi I was having trouble in the first part of getting the pixel coordinates of the point cloud could you post your code 
It would help me alot , Thank you
