### ISSUE TITLE
catkin_make -DCATKIN_ENABLE_TESTING=False -DCMAKE_BUILD_TYPE=Release

### ISSUE THREAD

**Issue by Shumine** [realsenseai/realsense-ros#1158]
Hello, I want to install real sense library for my ubuntu 18.04. 
but the error had occured when I type command below
"$ catkin_make -DCATKIN_ENABLE_TESTING=False -DCMAKE_BUILD_TYPE=Release"  at my terminal.
![error for catkin](https://user-images.githubusercontent.com/55174548/78865173-18441280-7a78-11ea-9fd2-e07f5923643f.png)

So I tried to do a lot of things to fix error..... 
And when I change  "-DCATKIN_ENABLE_TESTING=False" to
 " -DCATKIN_ENABLE_TESTING=True" , catkin_make command works successfully.

Now I have dont' idea what the "-DCATKIN_ENABLE_TESTING" thing(for configure catkin option??) works for "catkin_make".

Please let me know which file have this configuration code about this.  

Thanks

**Comment by MartyG-RealSense** [comment]
Another RealSense ROS user had problems with this command in March 2020.  They found that the problem disappeared once they removed folders they were not using inside **joystick_drivers**.

https://github.com/IntelRealSense/realsense-ros/issues/1101

Does your full log include mention of those joystick drivers like that other user's log did, please?

![image](https://user-images.githubusercontent.com/41145062/78871742-14949980-7a40-11ea-9e06-837f0d577cc6.png)

![image](https://user-images.githubusercontent.com/41145062/78871903-56bddb00-7a40-11ea-8ef7-293ad9036f80.png)

**Comment by MartyG-RealSense** [comment]
This case will be closed after 7 days from the time of writing this message if there are no further comments.  Thank you.

**Comment by Shumine** [comment]
You can close this case now. 

I installed my ubuntu 18.04 again, and now I could install real sense library perfectly.

Thank you.

**Comment by MartyG-RealSense** [comment]
Great news - thanks so much for the update!
