### ISSUE TITLE
Synthetic Stream Error

### ISSUE THREAD

**Issue by haydenhager** [realsenseai/realsense-ros#1161]
Camera Model: D415 x 1 via usb3
Firmware: 05.12.03.00
Operating system: Ubuntu 18.04.1
Kernel: 5.3.0-46-generic
Platform: x86_64 desktop intel i7
Language: ROS/realsense-viewer
SDK: 2.34.0
ROS distro: Melodic 2.2.13

I upgraded all of the debian packages with apt-get do to another issue we were having with v412 backend error. Upgrading fixed that issue but now we are seeing this error from realsense-viewer:

 10/04 11:55:39,853 ERROR [140382513903360] (synthetic-stream.cpp:48) Exception was thrown during user processing callback!

Unfortunately the viewer is not wanting to output the logs to a file so I had to copy this from the 'output' from the viewer. 

This is what we are getting as output from our ros rs_camera.launch:

started roslaunch server http://hayden-hp:35323/

SUMMARY
========

PARAMETERS
 * /camera/realsense2_camera/accel_fps: 250
 * /camera/realsense2_camera/accel_frame_id: camera_accel_frame
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: True
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/allow_no_texture_points: True
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/calib_odom_file: 
 * /camera/realsense2_camera/clip_distance: -2.0
 * /camera/realsense2_camera/color_fps: 30
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: 720
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: 1280
 * /camera/realsense2_camera/depth_fps: 30
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: 720
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: 1280
 * /camera/realsense2_camera/device_type: 
 * /camera/realsense2_camera/enable_accel: True
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye1: True
 * /camera/realsense2_camera/enable_fisheye2: True
 * /camera/realsense2_camera/enable_fisheye: True
 * /camera/realsense2_camera/enable_gyro: True
 * /camera/realsense2_camera/enable_infra1: True
 * /camera/realsense2_camera/enable_infra2: True
 * /camera/realsense2_camera/enable_pointcloud: True
 * /camera/realsense2_camera/enable_sync: False
 * /camera/realsense2_camera/filters: 
 * /camera/realsense2_camera/fisheye1_frame_id: camera_fisheye1_f...
 * /camera/realsense2_camera/fisheye1_optical_frame_id: camera_fisheye1_o...
 * /camera/realsense2_camera/fisheye2_frame_id: camera_fisheye2_f...
 * /camera/realsense2_camera/fisheye2_optical_frame_id: camera_fisheye2_o...
 * /camera/realsense2_camera/fisheye_fps: 30
 * /camera/realsense2_camera/fisheye_frame_id: camera_fisheye_frame
 * /camera/realsense2_camera/fisheye_height: 720
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: 1280
 * /camera/realsense2_camera/gyro_fps: 400
 * /camera/realsense2_camera/gyro_frame_id: camera_gyro_frame
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/imu_optical_frame_id: camera_imu_optica...
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra_fps: 30
 * /camera/realsense2_camera/infra_height: 720
 * /camera/realsense2_camera/infra_width: 1280
 * /camera/realsense2_camera/initial_reset: False
 * /camera/realsense2_camera/json_file_path: 
 * /camera/realsense2_camera/linear_accel_cov: 0.01
 * /camera/realsense2_camera/odom_frame_id: camera_odom_frame
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/pose_frame_id: camera_pose_frame
 * /camera/realsense2_camera/pose_optical_frame_id: camera_pose_optic...
 * /camera/realsense2_camera/publish_odom_tf: True
 * /camera/realsense2_camera/publish_tf: True
 * /camera/realsense2_camera/rosbag_filename: 
 * /camera/realsense2_camera/serial_no: 
 * /camera/realsense2_camera/tf_publish_rate: 0.0
 * /camera/realsense2_camera/topic_odom_in: odom_in
 * /camera/realsense2_camera/unite_imu_method: 
 * /camera/realsense2_camera/usb_port_id: 
 * /rosdistro: melodic
 * /rosversion: 1.14.5

NODES
  /camera/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)

auto-starting new master
process[master]: started with pid [11232]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 1ad16db2-7b41-11ea-b8c0-f0921cea8253
process[rosout-1]: started with pid [11243]
started core service [/rosout]
process[camera/realsense2_camera_manager-2]: started with pid [11250]
process[camera/realsense2_camera-3]: started with pid [11251]
[ INFO] [1586533014.825093750]: Initializing nodelet with 8 worker threads.
[ INFO] [1586533014.916741773]: RealSense ROS v2.2.13
[ INFO] [1586533014.916781781]: Running with LibRealSense v2.33.1
[ INFO] [1586533014.930651305]:  
 10/04 10:36:55,034 WARNING [140097737795328] (uvc-device.cpp:664) interrupt event received: 1, 3, 0, 7, 0, 11, 
 10/04 10:36:55,038 WARNING [140097737795328] (uvc-device.cpp:664) interrupt event received: 1, 3, 0, 7, 0, 13, 
 10/04 10:36:55,042 WARNING [140097737795328] (uvc-device.cpp:664) interrupt event received: 1, 3, 0, 7, 0, 12, 
 10/04 10:36:55,046 WARNING [140097737795328] (uvc-device.cpp:664) interrupt event received: 1, 3, 0, 7, 0, 3, 
 10/04 10:36:55,050 WARNING [140097737795328] (uvc-device.cpp:664) interrupt event received: 1, 3, 0, 7, 0, 20, 
 10/04 10:36:55,054 WARNING [140097737795328] (uvc-device.cpp:664) interrupt event received: 1, 3, 0, 7, 0, 23, 
 10/04 10:36:55,058 WARNING [140097737795328] (uvc-device.cpp:664) interrupt event received: 1, 3, 0, 7, 0, 23, 
[ INFO] [1586533015.288968342]: Device with serial number 821212060619 was found.

[ INFO] [1586533015.289010470]: Device with physical ID 4-2-4 was found.
[ INFO] [1586533015.289024110]: Device with name Intel RealSense D415 was found.
[ INFO] [1586533015.289475423]: Device with port number 4-2 was found.
[ INFO] [1586533015.291147882]: getParameters...
[ INFO] [1586533015.319463147]: setupDevice...
[ INFO] [1586533015.319490005]: JSON file is not provided
[ INFO] [1586533015.319524728]: ROS Node Namespace: camera
[ INFO] [1586533015.319546609]: Device Name: Intel RealSense D415
[ INFO] [1586533015.319566692]: Device Serial No: 821212060619
[ INFO] [1586533015.319586911]: Device physical port: 4-2-4
[ INFO] [1586533015.319605473]: Device FW version: 05.12.03.00
[ INFO] [1586533015.319625777]: Device Product ID: 0x0AD3
[ INFO] [1586533015.319643228]: Enable PointCloud: On
[ INFO] [1586533015.319660868]: Align Depth: On
[ INFO] [1586533015.319675740]: Sync Mode: On
[ INFO] [1586533015.319721727]: Device Sensors: 
[ INFO] [1586533015.319762573]: Stereo Module was found.
[ INFO] [1586533015.319792410]: RGB Camera was found.
[ INFO] [1586533015.319823963]: (Fisheye, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1586533015.319844055]: (Fisheye, 1) sensor isn't supported by current device! -- Skipping...
[ INFO] [1586533015.319855980]: (Fisheye, 2) sensor isn't supported by current device! -- Skipping...
[ INFO] [1586533015.319866821]: (Gyro, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1586533015.319888132]: (Accel, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1586533015.319908396]: (Pose, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1586533015.319940741]: Add Filter: pointcloud
[ INFO] [1586533015.320396412]: num_filters: 1
[ INFO] [1586533015.320413263]: Setting Dynamic reconfig parameters.
[ INFO] [1586533020.442893416]: Done Setting Dynamic reconfig parameters.
[ INFO] [1586533020.482154749]: depth stream is enabled - width: 1280, height: 720, fps: 30, Format: Z16
[ INFO] [1586533020.482775556]: infra1 stream is enabled - width: 1280, height: 720, fps: 30, Format: Y8
[ INFO] [1586533020.483317926]: infra2 stream is enabled - width: 1280, height: 720, fps: 30, Format: Y8
[ INFO] [1586533020.510457941]: color stream is enabled - width: 1280, height: 720, fps: 30, Format: RGB8
[ INFO] [1586533020.516642280]: setupPublishers...
[ INFO] [1586533020.519035126]: Expected frequency for depth = 30.00000
[ INFO] [1586533020.541496551]: Expected frequency for infra1 = 30.00000
[ INFO] [1586533020.553727103]: Expected frequency for aligned_depth_to_infra1 = 30.00000
[ INFO] [1586533020.569909302]: Expected frequency for infra2 = 30.00000
[ INFO] [1586533020.582081249]: Expected frequency for color = 30.00000
[ INFO] [1586533020.594093797]: Expected frequency for aligned_depth_to_color = 30.00000
[ INFO] [1586533020.606805161]: setupStreams...
[ INFO] [1586533020.708900052]: insert Depth to Stereo Module
[ INFO] [1586533020.709048989]: insert Color to RGB Camera
[ INFO] [1586533020.709084428]: insert Infrared to Stereo Module
[ INFO] [1586533020.709132339]: insert Infrared to Stereo Module
[ INFO] [1586533020.976029107]: SELECTED BASE:Depth, 0
[ INFO] [1586533021.009115789]: RealSense Node Is Up!
 10/04 10:37:01,247 WARNING [140097712617216] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 10/04 10:37:01,307 WARNING [140097712617216] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
[ WARN] [1586533021.453642225]: Hardware Notification:IR stream start failure,1.58653e+12,Error,Hardware Error
 10/04 10:37:02,054 WARNING [140097471117056] (uvc-device.cpp:664) interrupt event received: 1, 3, 0, 7, 0, 22, 
 10/04 10:37:02,233 WARNING [140097712617216] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 10/04 10:37:02,293 WARNING [140097712617216] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 10/04 10:37:02,396 WARNING [140097712617216] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 10/04 10:37:02,456 WARNING [140097712617216] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
[ WARN] [1586533022.474444075]: Hardware Notification:Depth stream start failure,1.58653e+12,Error,Hardware Error
 10/04 10:37:02,538 WARNING [140097712617216] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 10/04 10:37:02,719 WARNING [140097712617216] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 10/04 10:37:03,030 WARNING [140097471117056] (uvc-device.cpp:664) interrupt event received: 1, 3, 0, 7, 0, 12, 
 10/04 10:37:03,298 WARNING [140097471117056] (uvc-device.cpp:664) interrupt event received: 1, 3, 0, 7, 0, 23, 
[ WARN] [1586533023.495665979]: Hardware Notification:IR stream start failure,1.58653e+12,Error,Hardware Error
 10/04 10:37:03,892 ERROR [140096781395712] (uvc-streamer.cpp:106) uvc streamer watchdog triggered on endpoint: 130
 10/04 10:37:05,042 WARNING [140097737795328] (uvc-device.cpp:664) interrupt event received: 1, 3, 0, 7, 0, 12, 
 10/04 10:37:05,366 WARNING [140097737795328] (uvc-device.cpp:664) interrupt event received: 1, 3, 0, 7, 0, 23, 
[ WARN] [1586533025.526914695]: Hardware Notification:IR stream start failure,1.58653e+12,Error,Hardware Error
 10/04 10:37:06,083 WARNING [140097712617216] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 10/04 10:39:49,480 WARNING [140097712617216] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 10/04 10:39:49,540 WARNING [140097712617216] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 10/04 10:39:51,914 WARNING [140096747824896] (types.cpp:49) Out of frame resources!
 10/04 10:39:51,914 ERROR [140096747824896] (synthetic-stream.cpp:48) Exception was thrown during user processing callback!
 10/04 10:39:52,150 WARNING [140096747824896] (types.cpp:49) Out of frame resources!
 10/04 10:39:52,150 ERROR [140096747824896] (synthetic-stream.cpp:48) Exception was thrown during user processing callback!
 10/04 10:39:52,251 WARNING [140096747824896] (types.cpp:49) Out of frame resources!
 10/04 10:39:52,251 ERROR [140096747824896] (synthetic-stream.cpp:48) Exception was thrown during user processing callback!
 10/04 10:39:52,514 WARNING [140096747824896] (types.cpp:49) Out of frame resources!
 10/04 10:39:52,514 ERROR [140096747824896] (synthetic-stream.cpp:48) Exception was thrown during user processing callback!
 10/04 10:39:52,716 WARNING [140096747824896] (types.cpp:49) Out of frame resources!
 10/04 10:39:52,716 ERROR [140096747824896] (synthetic-stream.cpp:48) Exception was thrown during user processing callback!
 10/04 10:39:52,881 WARNING [140096747824896] (types.cpp:49) Out of frame resources!
 10/04 10:39:52,882 ERROR [140096747824896] (synthetic-stream.cpp:48) Exception was thrown during user processing callback!
 10/04 10:39:53,048 WARNING [140096747824896] (types.cpp:49) Out of frame resources!
 10/04 10:39:53,048 ERROR [140096747824896] (synthetic-stream.cpp:48) Exception was thrown during user processing callback!
 10/04 10:39:53,216 WARNING [140096747824896] (types.cpp:49) Out of frame resources!
 10/04 10:39:53,216 ERROR [140096747824896] (synthetic-stream.cpp:48) Exception was thrown during user processing callback!
 10/04 10:39:53,382 WARNING [140096747824896] (types.cpp:49) Out of frame resources!
 10/04 10:39:53,382 ERROR [140096747824896] (synthetic-stream.cpp:48) Exception was thrown during user processing callback!
 10/04 10:39:53,548 WARNING [140096747824896] (types.cpp:49) Out of frame resources!
 10/04 10:39:53,548 ERROR [140096747824896] (synthetic-stream.cpp:48) Exception was thrown during user processing callback!
 10/04 10:39:53,713 WARNING [140096747824896] (types.cpp:49) Out of frame resources!
 10/04 10:39:53,713 ERROR [140096747824896] (synthetic-stream.cpp:48) Exception was thrown during user processing callback!
 10/04 10:39:53,779 WARNING [140096747824896] (types.cpp:49) Out of frame resources!
 10/04 10:39:53,779 ERROR [140096747824896] (synthetic-stream.cpp:48) Exception was thrown during user processing callback!
 10/04 10:39:53,846 WARNING [140096747824896] (types.cpp:49) Out of frame resources!
 10/04 10:39:53,846 ERROR [140096747824896] (synthetic-stream.cpp:48) Exception was thrown during user processing callback!
 10/04 10:39:54,081 WARNING [140096747824896] (types.cpp:49) Out of frame resources!
 10/04 10:39:54,081 ERROR [140096747824896] (synthetic-stream.cpp:48) Exception was thrown during user processing callback!
 10/04 10:39:54,314 WARNING [140096747824896] (types.cpp:49) Out of frame resources!
 10/04 10:39:54,314 ERROR [140096747824896] (synthetic-stream.cpp:48) Exception was thrown during user processing callback!
 10/04 10:39:54,414 WARNING [140096747824896] (types.cpp:49) Out of frame resources!
 10/04 10:39:54,414 ERROR [140096747824896] (synthetic-stream.cpp:48) Exception was thrown during user processing callback!
 10/04 10:39:54,646 WARNING [140096747824896] (types.cpp:49) Out of frame resources!
 10/04 10:39:54,647 ERROR [140096747824896] (synthetic-stream.cpp:48) Exception was thrown during user processing callback!
 10/04 10:39:54,749 WARNING [140096747824896] (types.cpp:49) Out of frame resources!
 10/04 10:39:54,750 ERROR [140096747824896] (synthetic-stream.cpp:48) Exception was thrown during user processing callback!
 10/04 10:39:54,980 WARNING [140096747824896] (types.cpp:49) Out of frame resources!
 10/04 10:39:54,980 ERROR [140096747824896] (synthetic-stream.cpp:48) Exception was thrown during user processing callback!
 10/04 10:39:55,081 WARNING [140096747824896] (types.cpp:49) Out of frame resources!
 10/04 10:39:55,081 ERROR [140096747824896] (synthetic-stream.cpp:48) Exception was thrown during user processing callback!
 10/04 10:39:55,314 WARNING [140096747824896] (types.cpp:49) Out of frame resources!
 10/04 10:39:55,314 ERROR [140096747824896] (synthetic-stream.cpp:48) Exception was thrown during user processing callback!
 10/04 10:39:55,414 WARNING [140096747824896] (types.cpp:49) Out of frame resources!
 10/04 10:39:55,415 ERROR [140096747824896] (synthetic-stream.cpp:48) Exception was thrown during user processing callback!
 10/04 10:39:55,615 WARNING [140096747824896] (types.cpp:49) Out of frame resources!
 10/04 10:39:55,615 ERROR [140096747824896] (synthetic-stream.cpp:48) Exception was thrown during user processing callback!
 10/04 10:39:55,747 WARNING [140096747824896] (types.cpp:49) Out of frame resources!
 10/04 10:39:55,747 ERROR [140096747824896] (synthetic-stream.cpp:48) Exception was thrown during user processing callback!
 10/04 10:39:55,812 WARNING [140096747824896] (types.cpp:49) Out of frame resources!
 10/04 10:39:55,812 ERROR [140096747824896] (synthetic-stream.cpp:48) Exception was thrown during user processing callback!

I am still able to use the camera while it is giving this error but my %CPU when I updated went from around 40% to over 100% for the nodelet when trying to stream the image through roslibjs. On lesser pc's it is crashing the nodelet.  

Any advice on how to mitigate this error?

**Comment by MartyG-RealSense** [comment]
I located another currently active case that has similarities to yours in terms of the errors generated.

https://github.com/IntelRealSense/realsense-ros/issues/1110

It is very long, so I will pick out some useful quotes from @doronhi the RealSense ROS wrapper developer about a couple of the main warnings that you have experienced.

"The warning message "interrupt event received" can be ignored and indeed will be removed in future versions".

"The warning message "control_transfer returned error" reflects communication error with the device that is resolved by repeating the attempt. These messages are still under investigation but as long as they appear only now and then, say at the beginning of the run, they can safely be ignored for now".

"If the message "messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11" is continuous, that is appears multiple times per second, then it is not good. It suggest a real communication problem between the code and the device and can have effects".

"The "Out of frame resources!" message and the "Exception...processing callback!" could be related to the "IR stream failure" but more often they are related to lack of system resources - the app can't keep up with the incoming flow of images. For that you can reduce frame rate and resolution.
Building with CUDA support should really help in that case on NVidia machines".

I recommend also reading the linked case from the start of course to see if any of the other advice in that discussion is helpful to your own situation.

**Comment by MartyG-RealSense** [comment]
@haydenhager    If you are still experiencing these errors, I would recommend investigating the possibility of using a mains electricity powered USB 3 hub to increase USB port stability if your project allows it (for example, it is not a mobile robot that would be unsuited to being tethered to a wall power socket).

Otherwise, the situation may require programming additions from the RealSense developers to reduce the likelihood of errors such as **control_transfer returned** occurring.  So I will close the case, as the developers are aware of the problem and are likely investigating it.
