### ISSUE TITLE
Add USB plug/cable to model

### ISSUE THREAD

**Issue by JStech** [realsenseai/realsense-ros#1165]
I recently broke a USB cable plugged into a D415 as a result of a self-collision. I've updated our model to include a plug with a short length of cable to prevent this, but it'd be a nice feature to have the plug in the URDF with a parameter controlling whether it is included.

**Comment by MartyG-RealSense** [comment]
Thanks so much for your suggestion @JStech - I have labelled this message with an "Enhancement" (Feature Request) tag so that it can be tracked by @doronhi the RealSense ROS wrapper developer.

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Hi JStech,

Are you saying you physically "broke" the USB cable? ... by cutting it?

Thanks

**Comment by JStech** [comment]
I bent it. The robot squeezed the camera past its forearm link, and there was no collision with the camera body, but the plug wasn't included in the model, so it didn't survive.
![IMG_20200411_122941](https://user-images.githubusercontent.com/519268/79609312-c290eb00-80b3-11ea-9a1c-37eef9ca0e03.jpg)

**Comment by RealSenseSupport** [comment]
Oh, even the locking cable plug is bent? ... that looks hit very hard.

**Comment by MartyG-RealSense** [comment]
Hi @JStech    Your pull request still has some conflicts that need to be resolved in order for the contribution to be merged into the SDK.   Are you still working on this pull please?   Thanks!

https://github.com/IntelRealSense/realsense-ros/pull/1173

**Comment by doronhi** [comment]
> Hi @JStech Your pull request still has some conflicts that need to be resolved in order for the contribution to be merged into the SDK. Are you still working on this pull please? Thanks!
> 
> #1173

Thanks for the reminder @MartyG-RealSense . @JStech , it looks like a nice addition. It would be great if you could update your PR and we'll try to merge it by the next release.

**Comment by JStech** [comment]
Thanks for the ping. Should be good to go.

**Comment by doronhi** [comment]
Thanks for the PR. It's merged now.

**Comment by MartyG-RealSense** [comment]
As the PR has been merged, I will close this case now.  Thanks everyone!
