### ISSUE TITLE
Issue in launching the file 

### ISSUE THREAD

**Issue by raman24-panessar** [realsenseai/realsense-ros#1169]
Hello guys, 

I have this Pico_flexx_lidar camera with me and i have to do object detection in this but i am facing the following continues errors 

i hope you guys can help me i have just stuck in this small issue 

please help me out i have my thesis hanging only because of this error 

[royale_camera_driver-4] restarting process
process[royale_camera_driver-4]: started with pid [26576]
[ INFO] [1587036818.933362562]: Loading nodelet /royale_camera_driver of type royale_in_ros/royale_nodelet to manager royale_camera with the following remappings:
[ERROR] [1587036818.950300885]: Failed to load nodelet [/royale_camera_driver] of type [royale_in_ros/royale_nodelet] even after refreshing the cache: Could not find library corresponding to plugin royale_in_ros/royale_nodelet. Make sure the plugin description XML file has the correct name of the library and that the library actually exists.
[ERROR] [1587036818.950333560]: The error before refreshing the cache was: Could not find library corresponding to plugin royale_in_ros/royale_nodelet. Make sure the plugin description XML file has the correct name of the library and that the library actually exists.
[FATAL] [1587036818.950488923]: Failed to load nodelet '/royale_camera_driver` of type `royale_in_ros/royale_nodelet` to manager `royale_camera'
[royale_camera_driver-4] process has died [pid 26576, exit code 255, cmd /opt/ros/melodic/lib/nodelet/nodelet load royale_in_ros/royale_nodelet royale_camera __name:=royale_camera_driver __log:=/home/ramandeepsingh/.ros/log/1bc0b59a-7fd6-11ea-b3cf-9822efb96e3b/royale_camera_driver-4.log].
log file: /home/ramandeepsingh/.ros/log/1bc0b59a-7fd6-11ea-b3cf-9822efb96e3b/royale_camera_driver-4*.log

Best Regards,
Ramandeepsingh 
Panessar

**Comment by MartyG-RealSense** [comment]
Hi @raman24-panessar   As the question does not involve a RealSense camera or the RealSense SDK software or its ROS wrapper, a better place to re-post it would be at the ROS Answers forum.   Good luck with your thesis!

https://answers.ros.org/questions/

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
