### ISSUE TITLE
TX2 Computation and USB Questions

### ISSUE THREAD

**Issue by seanxu112** [realsenseai/realsense-ros#1177]
Hello,

I am a big fan of the realsense cameras that I have received. Currently trying to run D435 and T265 on TX2. While there are a lot of other posts about this. I still have a few more questions. In librealsense, I have set BUILD_WITH_TM2=ON, BUILD_WITH_CUDA=ON, and FORCE_RSUSB_BACKEND=ON. SDK version 2.33.1 and realsense-ros 2.2.13. When I only use D435, the camera works ok, only has these on start: `Hardware Notification:IR stream start failure,1.58769e+12,Error,Hardware Error
(messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
`
When I tried to connect both D435 and T265 with an unpowered usb3.0 port, the error above shows up consistently with usb scp overflow issue. I wonder if a powered usb port would potentially solve this problem? My Kernel is:4.4.38-tegra

Also, what is the expected cpu usage with D435 if I built with CUDA. Seems like on TX2 it is still using more than one core when I set align_depth=true. 

Sincerely,
Sean

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@seanxu112 Could you please share what launch file you used to run D435 and T265 when get the issue? Thanks!

**Comment by seanxu112** [comment]
Just the default rs_d400_with_t265.launch

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@seanxu112 Any problem if you only start T265 with demo_t265.lauch?
https://github.com/IntelRealSense/realsense-ros/blob/development/realsense2_camera/launch/demo_t265.launch

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@seanxu112 Any update from your side? Thanks!

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@seanxu112 Could you please update if you see any problem when start T265 with demo_t265.launch? Thanks!

https://github.com/IntelRealSense/realsense-ros/blob/development/realsense2_camera/launch/demo_t265.launch

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@seanxu112 Could you please update? Please note that the issue will be closed if we don't get your response in 7 days. Thanks!

**Comment by seanxu112** [comment]
Running t265 by itself works then. However, our whole system changed a lot since the day of posting, switching to 2.23.0 sdk, and 2.2.6 ros driver works now on tx2. Is there a new release of sdk and ros driver that works on tx2?

**Comment by RealSenseSupport** [comment]
@seanxu112 The latest ROS wrapper 2.2.14 and SDK 2.35.2 are published. Could you please have a try? Thanks!

**Comment by RealSenseSupport** [comment]
@seanxu112 Did you get chance to try the latest ROS wrapper to see if you still have issue? Thanks!

**Comment by RealSenseSupport** [comment]
@seanxu112 Could you please update if you still support on this? Thanks!

**Comment by darshb34** [comment]
Hello All,

I am using one t265 and 2 d430s and 2 d435i for my project on jetson tx2 as well same with jetson xavier.

The command `sudo apt-get install ros-melodic-realsense2-camera` installs latest ros wrapper as well as the latest compatible librealsense2.

My question is, 
1. _Does it have these libraries with CUDA enabled ? If yes, how can I test if it is really using CUDA?_ 
2. Do I need to have opencv build with CUDA before doing `sudo apt-get install ros-melodic-realsense2-camera`? If yes than what which opencv (3.3.2 or 4.1.1)?
3._does it allow me to use import pyrealsense2 in python2 and python3 ?_

Thank you

**Comment by RealSenseSupport** [comment]
@darshb34 According to https://github.com/IntelRealSense/librealsense/issues/6302#issuecomment-619531064 Debian packages are already built with CUDA. 

Also you can refer to https://github.com/IntelRealSense/librealsense/issues/6302#issuecomment-619516818 to check CUDA if enabled or not.

**Comment by doronhi** [comment]
The debian packages stored in the ros-distro are NOT built with CUDA support. remove "ros-melodic-librealsense2" and install librealsense2 according to the installation guide in the [librealsense2 repository](https://github.com/IntelRealSense/librealsense)

**Comment by RealSenseSupport** [comment]
@doronhi Thanks for the clarification! 
@darshb34 Please refer to doronhi's comment to set BUILD_WITH_CUDA=true to build with CUDA. Thanks!

**Comment by darshb34** [comment]
I checked the instructions and I realized that I need I have to match correct versions of  realsense-ros and librealsense2 when building the librealsense2 from source which can be done. 

But in this case my librealsense2 version will be stay old version unless I rebuild them regularly. 
will this break when realsense2_camera gets updated automatically as it is deb package and librealsense2 will stay the same version?



Thank you @doronhi and @RealSenseSupport

**Comment by doronhi** [comment]
If I understand you correctly then the answer is yes, the connection between librealsens2 version and realsense2_version will break when realsense2_camera gets updated.
The new version of realsense2_camera will require the latest version of librealsense2.
In librealsense2's installation guide are instructions for the installation of librealsense2-dev debian package from intel's s3 (amazon) repository. I think it is compiled with CUDA and may suite your needs.
You can, alternatively, build from source using the correct building flags.
Whatever methos you use, you will need, to make sure the librealsense2 version matches the realsense2_camera version you have every time the later is being updated.

**Comment by RealSenseSupport** [comment]
@seanxu112 @darshb34 Any other questions about this with Doronhi's reply? Looking forward to your update. Thanks!

**Comment by RealSenseSupport** [comment]
@seanxu112 @darshb34 Could you please update？Thanks!

**Comment by darshb34** [comment]
> The debian packages stored in the ros-distro are NOT built with CUDA support. remove "ros-melodic-librealsense2" and install librealsense2 according to the installation guide in the [librealsense2 repository](https://github.com/IntelRealSense/librealsense)

Hi @RealSenseSupport @dorodnic 

I cannot remove "ros-melodic-librealsense2" without having "ros-melodic-realsense2-camera" removed automatically with it as well. I tried apt-mark hold to hold the "ros-melodic-realsense2-camera" but that made removing "ros-melodic-librealsense2" fail. Please guide further

Thank you

**Comment by RealSenseSupport** [comment]
@darshb34 You may refer to method 2 to install RealSense ROS wrapper: https://github.com/IntelRealSense/realsense-ros#step-1-install-the-latest-intel-realsense-sdk-20

**Comment by RealSenseSupport** [comment]
@darshb34 Any update from your side? Looking forward to your reply. Thanks!

**Comment by RealSenseSupport** [comment]
@seanxu112  @darshb34  Any other questions about this? Thanks!

**Comment by RealSenseSupport** [comment]
@seanxu112 @darshb34 If no other questions about this, will close it accordingly. Thanks!

**Comment by maxiuw** [comment]
Two solutions:
1. The best one - Usb 3.0 cable connected to USB 3.0 port
2. Drastically reduce the frame rate, as mentioned in #1751 if you reduce the framerate it will only work if you also define width and height, otherwise, fps won't be changed and you will keep on getting the error. i.e. 
`roslaunch realsense2_camera rs_camera.launch depth_width:=640 depth_height:=480 depth_fps:=5`
