### ISSUE TITLE
Dosen't work with rs_t265.launch

### ISSUE THREAD

**Issue by Geonhee-LEE** [realsenseai/realsense-ros#1188]
----------------------------------------------------------------------------------------------------

| Required Info                         |                                                                |
|---------------------------------|------------------------------------------- |
| Camera Model                       | T265  | 
| Firmware Version                   | (Open RealSense Viewer --> Click info) | 
| Operating System & Version |    Linux (Ubuntu 18)   | 
| Kernel Version (Linux Only)    |  5.3.0-51-generic                                         | 
| Platform                                 | PC |
| librealsense                       |  v2.34.0 }                          | 
| ros wrapper                         |  v2.2.13 }                          |                         | 
| Segment			|  ROBOT }                          | 

### Issue Description

Hi, I want to use the tracking camera T265.
So that use it I installed the librealsense(v2.34.0) and realsense_ros(v2.2.13) pkg. I could check the working well using Realsense-viewer. But When I launch with rs_t265.launch, it occurred the error like below:

`07/05 15:19:53,915 ERROR [139789561546496] (tm-device.cpp:2036) Bulk request error RS2_USB_STATUS_NO_DEVICE
 07/05 15:20:03,916 WARNING [139789561546496] (messenger-libusb.cpp:66) bulk_transfer returned error, endpoint: 0x2, error: No such device, err. num: 19
 07/05 15:20:03,916 ERROR [139789561546496] (tm-device.cpp:2036) Bulk request error RS2_USB_STATUS_NO_DEVICE
 07/05 15:20:03,916 WARNING [139789561546496] (messenger-libusb.cpp:66) bulk_transfer returned error, endpoint: 0x2, error: No such device, err. num: 19
 07/05 15:20:03,916 ERROR [139789561546496] (tm-device.cpp:2036) Bulk request error RS2_USB_STATUS_NO_DEVICE
 07/05 15:20:13,917 WARNING [139789561546496] (messenger-libusb.cpp:66) bulk_transfer returned error, endpoint: 0x2, error: No such device, err. num: 19
 07/05 15:20:13,917 ERROR [139789561546496] (tm-device.cpp:2036) Bulk request error RS2_USB_STATUS_NO_DEVICE
 07/05 15:20:13,917 WARNING [139789561546496] (messenger-libusb.cpp:66) bulk_transfer returned error, endpoint: 0x2, error: No such device, err. num: 19
 07/05 15:20:13,917 ERROR [139789561546496] (tm-device.cpp:2036) Bulk request error RS2_USB_STATUS_NO_DEVICE
 07/05 15:20:23,917 WARNING [139789561546496] (messenger-libusb.cpp:66) bulk_transfer returned error, endpoint: 0x2, error: No such device, err. num: 19
 07/05 15:20:23,917 ERROR [139789561546496] (tm-device.cpp:2036) Bulk request error RS2_USB_STATUS_NO_DEVICE
 07/05 15:20:23,918 WARNING [139789561546496] (messenger-libusb.cpp:66) bulk_transfer returned error, endpoint: 0x2, error: No such device, err. num: 19
 07/05 15:20:23,918 ERROR [139789561546496] (tm-device.cpp:2036) Bulk request error RS2_USB_STATUS_NO_DEVICE
 07/05 15:20:33,918 WARNING [139789561546496] (messenger-libusb.cpp:66) bulk_transfer returned error, endpoint: 0x2, error: No such device, err. num: 19
 07/05 15:20:33,918 ERROR [139789561546496] (tm-device.cpp:2036) Bulk request error RS2_USB_STATUS_NO_DEVICE
 07/05 15:20:33,918 WARNING [139789561546496] (messenger-libusb.cpp:66) bulk_transfer returned error, endpoint: 0x2, error: No such device, err. num: 19
 07/05 15:20:33,919 ERROR [139789561546496] (tm-device.cpp:2036) Bulk request error RS2_USB_STATUS_NO_DEVICE`

Please help me.
regards.

**Comment by SalahSoliman** [comment]
I get the same issue, how did you solve it?

**Comment by Geonhee-LEE** [comment]
@SalahSoliman  Hi, the problem is USB connection

**Comment by SalahSoliman** [comment]
Thank you for the quick response, so it’s only the usb cable was causing the problem? 😮
