### ISSUE TITLE
Mean Intensity Set Point for Auto Exposure

### ISSUE THREAD

**Issue by manomitbal** [realsenseai/realsense-ros#1199]
Hi,

I am using version 2.30 for librealsense and was wondering if there was an exposed parameter to tune the Mean Intensity Set Point to determine the range of intensities to determine auto exposure value as shown in librealsense viewer screenshot below.

![ae](https://user-images.githubusercontent.com/5944780/81970858-2c86ac80-95ee-11ea-9aef-16a37a756af3.png)

I have noticed that the slider is not movable and has a set static value in the viewer, but my intention is to procure and set these values through realsense-ros, is there a way to do that through the current setup? 

Thanks!

**Comment by MartyG-RealSense** [comment]
The approach that I would recommend to set values that are part of **Advanced Mode** is to define a visual preset file (also known as a **json**) that sets the Mean Intensity Set Point to the desired value.  Then you could try calling the json file from your ROS launch file.

https://github.com/IntelRealSense/realsense-ros/issues/411#issuecomment-477463559

I believe that the json command for setting auto-exposure set point would be **aux-param-autoexposure-setpoint**.  Here is an example:

**"aux-param-autoexposure-setpoint": "400"**

An easy way to define a custom json file is to set the values up in the RealSense Viewer program and then use the json export option on the toolbar at the top of the Viewer's options side-panel.

If you are not familiar with Custom Presets, the link below has documentation about them.

https://github.com/IntelRealSense/librealsense/wiki/D400-Series-Visual-Presets

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

as Marty recommended, you can export the setting to json file
and even there is no slide bar for this setting
you can still edit its value by click the edit icon at right side  to enter text edit mode to tweak its value manually

**Comment by manomitbal** [comment]
This worked! Thanks guys!

**Comment by MartyG-RealSense** [comment]
Great news - thanks for letting us know!   :)

**Comment by ghhhgfgh** [comment]
Hello. Can I know what is the parameters name of “aux-param-autoexposure-setpoint” in ros2 humble? I cannot see the parameter in ros2 parameter list. Thank you

**Comment by MartyG-RealSense** [comment]
Hi @ghhhgfgh  You would have to define the parameter in a json configuration file and then import the json file during launch to apply the settings in the file by using the ROS2 **json_file_path** parameter to define the path to the file.

For example, define the path in a launch command:

`ros2 launch realsense2_camera rs_launch.py json_file_path:=/config.json`

Or define the parameter's path in the launch file:

https://github.com/realsenseai/realsense-ros/blob/ros2-master/realsense2_camera/launch/rs_launch.py#L29

**Comment by ghhhgfgh** [comment]
Thanks for the reply @MartyG-RealSense, so I cannot directly set the param in launch such as
 `ros2 launch realsense2_camera rs_launch.py aux-param-autoexposure-setpoint:=XXX`
I need to change the param in json_file_path and put it into the launch, right? 

Also, can I dynamically set it through like this?
`ros2 params set /camera/camera aux-param-autoexposure-setpoint 600`

Since I bought a 750nm filter mask to the realsense d435i for the outdoor detection(avoid the ghost noise), the shop said it is necessary to set the mean intersity set point to 600

Thank you very much again for your reply!!

**Comment by MartyG-RealSense** [comment]
I am not aware of a means of applying the setpoint parameter in ROS other than defining `aux-param-autoexposure-setpoint` in a json and then importing it via launch command or by editing the launch file.
