### ISSUE TITLE
ROS 1 Noetic TF not published from URDF model

### ISSUE THREAD

**Issue by BriceRenaudeau** [realsenseai/realsense-ros#1216]
Hi,
We use D435 cameras en Noetic.
The package builds from source. +1
And TF publisher/Depth point cloud seems to work with real cameras.

Unfortunately, there is some trouble with the URDF :
In roslaunch realsense2_description view_d435_model.launch
The launch uses the deprecated [state_publisher]
But even after fixing it, the TF tree is still not published.

**Comment by MartyG-RealSense** [comment]
Hi @BriceRenaudeau  Regarding your mention in the pull link that **robot_state_publisher** had been removed from Noetic: there is a Noetic dev branch for robot_state_publisher in the link below.  Is this of any use to you, please?  Or did you mean in the pull description that **state_publisher** has been deprecated and removed? 

https://github.com/ros/robot_state_publisher

![image](https://user-images.githubusercontent.com/41145062/83357563-f9217d00-a364-11ea-97c8-ea80e9c9cdcf.png)

**Comment by BriceRenaudeau** [comment]
HI, 
Yes, I was talking about `state_publisher` that has been deprecated and removed.
In the PR I changed it to `robot_state_publisher`.
Thanks for your concerns.

**Comment by MartyG-RealSense** [comment]
Closed due to no further comments received.
