### ISSUE TITLE
Need help; Launch file modify?

### ISSUE THREAD

**Issue by Andyshen555** [realsenseai/realsense-ros#1222]
I have installed the ros wrapper from command line on Ubuntu18.04 and ROS M, how and where should I modify the launch files?

**Comment by MartyG-RealSense** [comment]
Hi @Andyshen555   You can create or modify launch files using a **text editor** program of your own preference.  

Addmitedly I am not sure where the RealSense ROS launch files are stored though.  I would speculate that they are in the vicinity of the catkin workspace - catkin_ws/src/ - where the RealSense ROS wrapper is installed to.

**Comment by Andyshen555** [comment]
I used to build the wrapper from source, so I know how to modify those launch files. But now I used `sudo apt-get install ros-$ROS_VER-realsense2-camera` , so where do I have access to the launch files? Theres nothing in the src now. Do I need to download the source code and build from that to change launchfile?

**Comment by Andyshen555** [comment]
Found it, it's in the default folder and can be found using dpkg -L

**Comment by MartyG-RealSense** [comment]
Glad you found it - thanks for the update and details of how you found it!

**Comment by mintnguyenn** [comment]
hi @Andyshen555 can you show me how to find the launch file? Many thanks

**Comment by Andyshen555** [comment]
@mintnguyenn It's in /etc/ros/ros_ver/share/realsense2/launch for Linux by default
