### ISSUE TITLE
Combining the IMU data of t265 and d435i

### ISSUE THREAD

**Issue by armanhamzehlou** [realsenseai/realsense-ros#1230]
Hello, 

Are there any advantages in combining the IMU and Odom data of the two sensors to get a better 3d reconstruction of the environment? does it improve the quality of tracking and captured point-cloud?
does Intel provide any example or tutorial on this? 

Edit, Just to add: In a handheld or drone scenario with a D435i and T265.

Thank you,

**Comment by RealSenseSupport** [comment]
Hi,

Will you be needing further help with this? The T265 already has an IMU.

FYI...if we don’t hear from you in 7 days, this issue will be closed.

Thanks

**Comment by armanhamzehlou** [comment]
> Hi,
> 
> Will you be needing further help with this? The T265 already has an IMU.
> 
> FYI...if we don’t hear from you in 7 days, this issue will be closed.
> 
> Thanks

The issue is resolved. Thank you.
