### ISSUE TITLE
 get_device_time_ms() took too long (more then 2 mSecs)

### ISSUE THREAD

**Issue by comwise** [realsenseai/realsense-ros#1231]
PARAMETERS 
 * /front/realsense2_camera/accel_fps: 250 
 * /front/realsense2_camera/accel_frame_id: front_accel_frame 
 * /front/realsense2_camera/accel_optical_frame_id: front_accel_optic... 
 * /front/realsense2_camera/align_depth: False 
 * /front/realsense2_camera/aligned_depth_to_color_frame_id: front_aligned_dep... 
 * /front/realsense2_camera/aligned_depth_to_fisheye1_frame_id: front_aligned_dep... 
 * /front/realsense2_camera/aligned_depth_to_fisheye2_frame_id: front_aligned_dep... 
 * /front/realsense2_camera/aligned_depth_to_fisheye_frame_id: front_aligned_dep... 
 * /front/realsense2_camera/aligned_depth_to_infra1_frame_id: front_aligned_dep... 
 * /front/realsense2_camera/aligned_depth_to_infra2_frame_id: front_aligned_dep... 
 * /front/realsense2_camera/allow_no_texture_points: False 
 * /front/realsense2_camera/base_frame_id: base_footprint 
 * /front/realsense2_camera/calib_odom_file:  
 * /front/realsense2_camera/clip_distance: -2.0 
 * /front/realsense2_camera/color_fps: 30 
 * /front/realsense2_camera/color_frame_id: front_color_frame 
 * /front/realsense2_camera/color_height: 720 
 * /front/realsense2_camera/color_optical_frame_id: front_color_optic... 
 * /front/realsense2_camera/color_width: 1280 
 * /front/realsense2_camera/depth_fps: 90 
 * /front/realsense2_camera/depth_frame_id: front_depth_frame 
 * /front/realsense2_camera/depth_height: 240 
 * /front/realsense2_camera/depth_optical_frame_id: camera_link3 
 * /front/realsense2_camera/depth_width: 424 
 * /front/realsense2_camera/device_type:  
 * /front/realsense2_camera/enable_accel: False 
 * /front/realsense2_camera/enable_color: True 
 * /front/realsense2_camera/enable_depth: True 
 * /front/realsense2_camera/enable_fisheye1: True 
 * /front/realsense2_camera/enable_fisheye2: True 
 * /front/realsense2_camera/enable_fisheye: False 
 * /front/realsense2_camera/enable_gyro: False 
 * /front/realsense2_camera/enable_infra1: False 
 * /front/realsense2_camera/enable_infra2: False 
 * /front/realsense2_camera/enable_pointcloud: True 
 * /front/realsense2_camera/enable_sync: False 
 * /front/realsense2_camera/filters:  
 * /front/realsense2_camera/fisheye1_frame_id: front_fisheye1_frame 
 * /front/realsense2_camera/fisheye1_optical_frame_id: front_fisheye1_op... 
 * /front/realsense2_camera/fisheye2_frame_id: front_fisheye2_frame 
 * /front/realsense2_camera/fisheye2_optical_frame_id: front_fisheye2_op... 
 * /front/realsense2_camera/fisheye_fps: 30 
 * /front/realsense2_camera/fisheye_frame_id: front_fisheye_frame 
 * /front/realsense2_camera/fisheye_height: 480 
 * /front/realsense2_camera/fisheye_optical_frame_id: front_fisheye_opt... 
 * /front/realsense2_camera/fisheye_width: 640 
 * /front/realsense2_camera/gyro_fps: 400 
 * /front/realsense2_camera/gyro_frame_id: front_gyro_frame 
 * /front/realsense2_camera/gyro_optical_frame_id: front_gyro_optica... 
 * /front/realsense2_camera/imu_optical_frame_id: front_imu_optical... 
 * /front/realsense2_camera/infra1_frame_id: front_infra1_frame 
 * /front/realsense2_camera/infra1_optical_frame_id: front_infra1_opti... 
 * /front/realsense2_camera/infra2_frame_id: front_infra2_frame 
 * /front/realsense2_camera/infra2_optical_frame_id: front_infra2_opti... 
 * /front/realsense2_camera/infra_fps: 30 
 * /front/realsense2_camera/infra_height: 720 
 * /front/realsense2_camera/infra_width: 1280 
 * /front/realsense2_camera/initial_reset: False 
 * /front/realsense2_camera/json_file_path:  
 * /front/realsense2_camera/linear_accel_cov: 0.01 
 * /front/realsense2_camera/odom_frame_id: front_odom_frame 
 * /front/realsense2_camera/pointcloud_texture_index: 0 
 * /front/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_ANY 
 * /front/realsense2_camera/pose_frame_id: front_pose_frame 
 * /front/realsense2_camera/pose_optical_frame_id: front_pose_optica... 
 * /front/realsense2_camera/publish_odom_tf: True 
 * /front/realsense2_camera/publish_tf: True 
 * /front/realsense2_camera/rosbag_filename:  
 * /front/realsense2_camera/serial_no:  
 * /front/realsense2_camera/tf_publish_rate: 0.0 
 * /front/realsense2_camera/topic_odom_in: front/odom_in 
 * /front/realsense2_camera/unite_imu_method:  
 * /front/realsense2_camera/usb_port_id:  
 * /rosdistro: kinetic 
 * /rosversion: 1.12.14 
 
NODES
  /camera/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)

ROS_MASTER_URI=http://localhost:11311

process[camera/realsense2_camera_manager-1]: started with pid [24673]
process[camera/realsense2_camera-2]: started with pid [24674]
[ INFO] [1591356580.954990472]: Initializing nodelet with 4 worker threads.
[ INFO] [1591356581.007654689]: RealSense ROS v2.2.13
[ INFO] [1591356581.007695626]: Running with LibRealSense v2.34.0

[ INFO] [1591346259.353617175]:  
 05/06 16:37:39,408 WARNING [139943332878080] (types.cpp:49) hwmon command 0x4f failed. 
Error type: No data to return (-21). 
 05/06 16:37:39,408 WARNING [139943332878080] (ds5-motion.cpp:464) IMU Calibration is not available, see the previous message 
[ INFO] [1591346259.408580674]: Device with serial number 845112070197 was found. 
[ INFO] [1591346259.408612793]: Device with physical ID /sys/devices/pci0000:00/0000:00:14.0/usb2/2-3/2-3:1.0/video4linux/video0 was found.
[ INFO] [1591346259.408630452]: Device with name Intel RealSense D435I was found.
[ INFO] [1591346259.409721662]: Device with port number 2-3 was found.
[ INFO] [1591346259.416193505]: getParameters...
[ INFO] [1591346259.622845056]: setupDevice...
[ INFO] [1591346259.622894866]: JSON file is not provided
[ INFO] [1591346259.622909838]: ROS Node Namespace: front
[ INFO] [1591346259.622925394]: Device Name: Intel RealSense D435I
[ INFO] [1591346259.622936544]: Device Serial No: 845112070197
[ INFO] [1591346259.622950369]: Device physical port: /sys/devices/pci0000:00/0000:00:14.0/usb2/2-3/2-3:1.0/video4linux/video0
[ INFO] [1591346259.622965181]: Device FW version: 05.10.13.00
[ INFO] [1591346259.622978823]: Device Product ID: 0x0B3A
[ INFO] [1591346259.622990104]: Enable PointCloud: On
[ INFO] [1591346259.623000346]: Align Depth: Off
[ INFO] [1591346259.623010710]: Sync Mode: On
[ INFO] [1591346259.623073018]: Device Sensors: 
[ INFO] [1591346259.623122471]: Stereo Module was found.
[ INFO] [1591346259.623145633]: RGB Camera was found.
[ INFO] [1591346259.623184009]: Motion Module was found.
[ INFO] [1591346259.623205442]: (Fisheye, 1) sensor isn't supported by current device! -- Skipping...
[ INFO] [1591346259.623213192]: (Fisheye, 2) sensor isn't supported by current device! -- Skipping...
[ INFO] [1591346259.623219657]: (Pose, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1591346259.623237032]: Add Filter: pointcloud
[ INFO] [1591346259.623820391]: num_filters: 1
[ INFO] [1591346259.623844816]: Setting Dynamic reconfig parameters.
[ INFO] [1591346259.761190478]: Done Setting Dynamic reconfig parameters.
[ INFO] [1591346259.762408704]: depth stream is enabled - width: 424, height: 240, fps: 90, Format: Z16
 05/06 16:37:39,762 WARNING [139943332878080] (backend-v4l2.cpp:1223) Pixel format 36315752-1a66-a242-9065-d01814a likely requires patch for fourcc code RW16! 
[ INFO] [1591346259.764293804]: color stream is enabled - width: 1280, height: 720, fps: 30, Format: RGB8
[ INFO] [1591346259.764396693]: setupPublishers...
[ INFO] [1591346259.769682740]: Expected frequency for depth = 90.00000
[ INFO] [1591346259.809101107]: Expected frequency for color = 30.00000
[ INFO] [1591346259.850539244]: setupStreams...
[ INFO] [1591346259.850956849]: insert Depth to Stereo Module
[ INFO] [1591346259.850996400]: insert Color to RGB Camera
[ INFO] [1591346259.860084143]: SELECTED BASE:Depth, 0
[ INFO] [1591346259.878825855]: RealSense Node Is Up!
 05/06 16:37:39,943 WARNING [139942959847168] (ds5-timestamp.cpp:73) UVC metadata payloads not available. Please refer to the installation chapter for details. 
[ WARN] [1591346259.944057697]: Frame metadata isn't available! (frame_timestamp_domain = RS2_TIMESTAMP_DOMAIN_SYSTEM_TIME)
 05/06 16:37:40,045 ERROR [139943203604224] (types.h:307) get_device_time_ms() took too long (more then 2 mSecs) 
 05/06 16:37:40,201 ERROR [139943203604224] (types.h:307) get_device_time_ms() took too long (more then 2 mSecs) 
 05/06 16:37:40,288 WARNING [139942968239872] (ds5-timestamp.cpp:73) UVC metadata payloads not available. Please refer to the installation chapter for details. 
 05/06 16:37:40,415 ERROR [139943203604224] (types.h:307) get_device_time_ms() took too long (more then 2 mSecs) 
 05/06 16:37:41,723 ERROR [139943203604224] (types.h:307) get_device_time_ms() took too long (more then 2 mSecs) 
[ERROR] [1591346281.124088576]: An error has occurred during frame callback: Error occured during execution of the processing block! See the log for more info
 05/06 16:38:21,094 ERROR [139943203604224] (types.h:307) get_device_time_ms() took too long (more then 2 mSecs) 
 05/06 16:38:41,156 ERROR [139943203604224] (types.h:307) get_device_time_ms() took too long (more then 2 mSecs) 
 05/06 16:38:47,208 ERROR [139943203604224] (types.h:307) get_device_time_ms() took too long (more then 2 mSecs) 
 05/06 16:40:19,245 ERROR [139943203604224] (types.h:307) get_device_time_ms() took too long (more then 2 mSecs) 
 05/06 16:40:50,262 ERROR [139943203604224] (types.h:307) get_device_time_ms() took too long (more then 2 mSecs) 
 05/06 16:41:10,273 ERROR [139943203604224] (types.h:307) get_device_time_ms() took too long (more then 2 mSecs) 
 05/06 16:41:12,281 ERROR [139943203604224] (types.h:307) get_device_time_ms() took too long (more then 2 mSecs) 
 [ERROR] [1591346479.413763025]: An error has occurred during frame callback: Error occured during execution of the processing block! See the log for more info
 [ERROR] [1591346488.346784044]: An error has occurred during frame callback: Error occured during execution of the processing block! See the log for more info
 [ERROR] [1591346556.552866367]: An error has occurred during frame callback: Error occured during execution of the processing block! See the log for more info
 [ERROR] [1591346566.551524715]: An error has occurred during frame callback: Error occured during execution of the processing block! See the log for more info

----
get_device_time_ms() took too long (more then 2 mSecs)
 An error has occurred during frame callback: Error occured during execution of the processing block! See the log for more info
--- 
What could cause this? my sdk lib ? 
ubuntu 16.04   linux kernel 4.15.xx
last version is ok   RealSense ROS 2.2.8  and SDK 2.26.0
current version is  RealSense ROS 2.2.13 and SDk 2.34.0
can you tell me why?  I'm looking forward to your reply soon

**Comment by MartyG-RealSense** [comment]
Looking through your log, the initial errors - **requires patch for fourcc code RW16!** and **UVC metadata payloads not available** - suggest that there is a problem related to patching.  Did you compile Librealsense from source code please, and did you apply a patch script?

**Comment by comwise** [comment]
@MartyG-RealSense i just downloaded these packages by "apt-get install", then i install libs to other pc by the following scripts: 
 sudo apt install -y ros-kinetic-cv-bridge \
    ros-kinetic-image-transport \
    ros-kinetic-tf \
    ros-kinetic-diagnostic-updater \
    dkms || { echo -e "${RED}deps install realsense d435i runtime lib failed ${NC}"; exit 7; }
download_rs_pkgs=(
    librealsense2-udev-rules_2.34.0-0~realsense0.2250_amd64.deb
    librealsense2-dkms_1.3.11-0ubuntu1_all.deb
    librealsense2_2.34.0-0~realsense0.2250_amd64.deb
    librealsense2-dev_2.34.0-0~realsense0.2250_amd64.deb
    )
for pkg in ${download_rs_pkgs[@]}; do
    [ -f ${debs_dir}/${pkg} ] || ${download_tool} -P ${debs_dir} ${server}/third_parties/all_debs/${pkg}
    sudo dpkg -E -i ${debs_dir}/${pkg}
done

is there anything wrong?

**Comment by MartyG-RealSense** [comment]
@comwise    Installing files in this way is outside of my ROS knowledge unfortunately, so I cannot offer advice about it.  The best way to do a Librealsense installation in Ubuntu is with a fresh Ubuntu install or if that is not convenient, by removing all previous Librealsense installations before doing a new installation.

**Debian package uninstall**

https://github.com/IntelRealSense/librealsense/blob/master/doc/distribution_linux.md#uninstalling-the-packages

**Clean-up when compiling from source code**

sudo make uninstall && make clean && make && sudo make install

**Comment by MartyG-RealSense** [comment]
@comwise  Do you still require assistance with this case please?   Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no futher comments received.
