### ISSUE TITLE
Only one camera was launched (either D435 or D435i) on Jetson AXG Xavier PCI-E USB

### ISSUE THREAD

**Issue by amburkoff** [realsenseai/realsense-ros#1238]
<table>
<tr><th>Computer</th><th>Nvidia Jetson AXG Xavier 32 GB</th></tr>
<tr><th>Jetpack Version</th><th>4.3</th></tr>
<tr><th>L4T Version</th><th>32.3.1</th></tr>
<tr><th>Camera 1</th><th>D435i</th></tr>
<tr><th>Camera 2</th><th>D435</th></tr>
<tr><th>Firmware</th><th>05.12.03 (for both cameras)</th></tr> 
<tr><th>USB Controller</th><th>PCI-E x1 ORIENT NC-3U4PE</th></tr>
<tr><th>Cable use</th><th>Original cabel</th></tr>
<tr><th>OS</th><th>Ubuntu 18.04.4</th></tr>
<tr><th>Kernel</th><th>4.9.140-tegra</th></tr>
<tr><th>ROS Version</th><th>Melodic</th></tr>
<tr><th>LibRealSense</th><th>v2.33.1 (install from apt)</th></tr>
<tr><th>RealSense ROS</th><th>v2.2.13 (install from apt)</th></tr>
</table>

We conducted camera fault tolerance tests. 
The first test was long time test (***17 hours***). During this time camera worked fine.
After that, we immediately conducted short tests (***one minute each***). In most cases, the cameras launched normally.
But sometimes only one camera was launched (*either D435 or D435i*). After that, on the next start, both cameras started normally.
 `lsusb -t` showed that one camera didn't have the ***driver parameter*** in the case when only one camera was launched. Both cameras had this option during normal startup.
We tried to reconnect the camera in a loop.
The launch command is:
```
mon launch realsense2_camera rs_multiple_device serial_no_camera1:=<SERIAL_NUMBER> serial_no_camera2:=<SERIAL_NUMBER>
```
We used `mon launch` to conveniently save logs.
Log files:
- log_10_06_2020-13_06.txt - both cameras worked well
- log_10_06_2020-13_07.txt - one camera didn't connect
- log_10_06_2020-13_09.txt - both cameras worked well

Screen when one camera does not have a driver parameter through lsusb -t  - https://drive.google.com/file/d/1VTBFDU_wiPDql_m6IxQnHZFqaf_I6g3X/view?usp=sharing
Screen when both cameras started through lsusb -t  - https://drive.google.com/file/d/1bcCCoeuDHDcsv0QxXHHm7Y1eG5k648eQ/view?usp=sharing
log_10_06_2020-13_06.txt  - https://drive.google.com/file/d/1m1Fxb6m5aLVwp2sbPOBPOoEZzpThREef/view?usp=sharing
log_10_06_2020-13_07.txt  - https://drive.google.com/file/d/1Lh0bjpAJL1mC7_5lxe4B17jJ4yfCTIPX/view?usp=sharing
log_10_06_2020-13_09.txt  - https://drive.google.com/file/d/1jDVgb-JO82fSnvcBOjXGZpsBhGtMpd5F/view?usp=sharing

**Comment by doronhi** [comment]
We are still looking into it.

**Comment by RealSenseSupport** [comment]
Issue was addressed after building librealsense with native backend. 
Closing this ticket.
