### ISSUE TITLE
One Realsense D435, Intel NUC. RT IC2 Config error

### ISSUE THREAD

**Issue by amburkoff** [realsenseai/realsense-ros#1240]
# Environment 

|                           |                                |
|---------------------------|--------------------------------|
| Computer                  | Intel NUC                      |
| OS                        | Ubuntu 18.04                   |
| ROS verison               | Melodic                        |
| Realsense type            | D435                           |
| Camera firmware           | 05.12.05                       |
| Realsense connection type | original realsense cable       |
| LibRealSense version      |  v2.33.1 (install through apt) |
| RealSense ROS version     |  v2.2.13 (install through apt) |

In addition to privious issues https://github.com/IntelRealSense/realsense-ros/issues/1226#issuecomment-641137175 we had the same error using just **one D435 camera**. But in this test realsense node could reset and reconnect camera.

Error:
```
Tue 2020-06-09 08:59:50.576: realsense2_camera_manager:  [33m[BaseRealSenseNode::setupErrorCallback]: Hardware Notification:RT IC2 Config error,1.59168e+12,Error,Hardware Error [0m
Tue 2020-06-09 08:59:50.576: realsense2_camera_manager:  [31m[BaseRealSenseNode::setupErrorCallback]: Performing Hardware Reset. [0m
```
Another error after reset:
```
Wed 2020-06-10 10:09:51.632: realsense2_camera_manager:  10/06 10:09:51,632 ERROR [140183059293952] (global_timestamp_reader.cpp:188) Error during time_diff_keeper polling: usb device disconnected
```

The launch command is:
```
mon launch realsense2_camera rs_camera.launch serial_no:=828112074585 usb_port_id:=2-3 --log="/home/courier/realsense_tests/test_23"
```

## Log files:
- test_29.txt - first test that all is fine
- test_30.txt - realsense node tried reset camera
- test_31.txt - realsense node tried reset camera
- list_29.txt - list of usb devices before execute launch
- list_29_2.txt - list of usb devices after execute launch
- list_30.txt - list of usb devices before execute launch
- list_30_2.txt - list of usb devices after execute launch
- list_31.txt - list of usb devices before execute launch
- list_31_2.txt - list of usb devices after execute launch

[list_29.txt](https://github.com/IntelRealSense/realsense-ros/files/4759142/list_29.txt)
[list_29_2.txt](https://github.com/IntelRealSense/realsense-ros/files/4759143/list_29_2.txt)
[list_30.txt](https://github.com/IntelRealSense/realsense-ros/files/4759144/list_30.txt)
[list_30_2.txt](https://github.com/IntelRealSense/realsense-ros/files/4759145/list_30_2.txt)
[list_31.txt](https://github.com/IntelRealSense/realsense-ros/files/4759146/list_31.txt)
[list_31_2.txt](https://github.com/IntelRealSense/realsense-ros/files/4759147/list_31_2.txt)
[test_29.txt](https://github.com/IntelRealSense/realsense-ros/files/4759148/test_29.txt)
[test_30.txt](https://github.com/IntelRealSense/realsense-ros/files/4759149/test_30.txt)
[test_31.txt](https://github.com/IntelRealSense/realsense-ros/files/4759150/test_31.txt)

**Comment by MartyG-RealSense** [comment]
The first step that I would recommend trying is using either the serial number or usb_port_id in the launch instruction, but not both.  This reduces the possibility of confusing the ROS wrapper by providing two different means of looking for the camera.

**Comment by MartyG-RealSense** [comment]
Hi @amburkoff   Do you require further assistance with this case, please?  This case will be closed in 7 days if we do not hear from you.  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
