### ISSUE TITLE
Realsense D435. Probe-commit control transfer failed with error: RS2_USB_STATUS_PIPE

### ISSUE THREAD

**Issue by amburkoff** [realsenseai/realsense-ros#1241]
# Environment 

|                           |                                |
|---------------------------|--------------------------------|
| Computer                  | Intel NUC                      |
| OS                        | Ubuntu 18.04                   |
| ROS verison               | Melodic                        |
| Realsense type            | D435                           |
| Camera firmware           | 05.12.05                       |
| Realsense connection type | original realsense cable       |
| LibRealSense version      |  v2.33.1 (install through apt) |
| RealSense ROS version     |  v2.2.13 (install through apt) |

We conducted camera fault tolerance tests. After executed launch file rs_camera, we had the fallowing error:
```
Tue 2020-06-09 11:00:01.341: realsense2_camera_manager:  09/06 11:00:01,341 ERROR [140431479441152] (uvc-device.cpp:857) Probe-commit control transfer failed with error: RS2_USB_STATUS_PIPE
```
And then launch was shut down.
Then we tried to execute launch file again and had the same error.

The launch command is:
```
mon launch realsense2_camera rs_camera.launch serial_no:=828112074585 --log="/home/courier/realsense_tests/test_23"
```
We use mon launch just for easily logs' safe.

## Log files:
- test_23.txt - first test logs
- test_24.txt - second test logs
- list_23.txt - list of usb devices after execute launch
- list_24.txt - list of usb devices after execute launch

[list_24.txt](https://github.com/IntelRealSense/realsense-ros/files/4759231/list_24.txt)
[list_23.txt](https://github.com/IntelRealSense/realsense-ros/files/4759232/list_23.txt)
[test_24.txt](https://github.com/IntelRealSense/realsense-ros/files/4759233/test_24.txt)
[test_23.txt](https://github.com/IntelRealSense/realsense-ros/files/4759234/test_23.txt)

**Comment by doronhi** [comment]
Could be that you had connection problems? I saw this line the the log:
`Tue 2020-06-09 10:59:55.483: realsense2_camera_manager: [31m[RealSenseNodeFactory::change_device_callback]: The device has been disconnected!`
If the connection was not stable, all kind of communication problems could happen next.

**Comment by RealSenseSupport** [comment]
Issue closed. Please feel free to let us know if problem persists. Thank you.
