### ISSUE TITLE
the test bag

### ISSUE THREAD

**Issue by ghost** [realsenseai/realsense-ros#1244]
Can you share a bag with  D435i camera data for slam about https://github.com/IntelRealSense/realsense-ros/wiki/SLAM-with-D435i?
Thanks.

**Comment by MartyG-RealSense** [comment]
The RealSense sample data page has a zip-file download containing two D435i bag files ('walking' and 'walk around') that contain IMU motion module data.  Would this meet your needs please?

https://github.com/IntelRealSense/librealsense/blob/master/doc/sample-data.md

**Comment by ghost** [comment]
Thanks for your reply.But I want to test the result of indoor D435i data.
Can you help me ?

**Comment by MartyG-RealSense** [comment]
I did a careful research for available indoor D435i bag files that could be downloaded but could not find any.  I am sorry.

**Comment by ghost** [comment]
OK. Thank you very much.

**Comment by MartyG-RealSense** [comment]
Case closed due to non-availability of D435i indoor bag file.
