### ISSUE TITLE
D435i : unable to set manual exposure 

### ISSUE THREAD

**Issue by echoGee** [realsenseai/realsense-ros#1245]
I am trying to disable autoexposure on D435i camera. But there is no parameter for that when I run `rosrun dynamic_reconfigure dynparam` 

Any reference for this ?

**Comment by MartyG-RealSense** [comment]
I could not find definite information on doing this for D435i.  On T265 though it can be done in the launch file with **rosparam**.

https://github.com/IntelRealSense/realsense-ros/issues/1049

An adaptation for D435i might look like this:

```
<rosparam>
  /camera/rgb_camera/enable_auto_exposure: false
  /camera/stereo_module/enable_auto_exposure: false
</rosparam>
```

**Comment by MartyG-RealSense** [comment]
Hi @echoGee   Do you still require assistance on this case please, or can it be closed?   Thanks!

**Comment by echoGee** [comment]
Found out a method
`rosrun dynamic_reconfigure dynparam set /camera/rgb_camera exposure 100`

To see what values of parameters are already set, use `rosrun dynamic_reconfigure dynparam get /node` which in an example would be `rosrun dynamic_reconfigure dynparam get /camera/rgb_camera`

**Comment by MartyG-RealSense** [comment]
Great news - thanks for sharing your solution!
