### ISSUE TITLE
dose realsense camea support v4l2 command (for ex, VIDIOC_S_FMT)

### ISSUE THREAD

**Issue by liyuming1978** [realsenseai/realsense-ros#125]
I need do video-streaming from realsense color camera, (it's /dev/video0), if I get the data from ROS, the latency is too high, it's better to get directly from v4l2, 
but, I can not call  VIDIOC_S_FMT or other v4l2 command for these cameras.
I want to know, is it possible to encoder directly from camera interface?

**Comment by mdhorn** [comment]
Are you working in ROS or some other application for using the camera?

If you are working in ROS, then we need to address the latency concerns.

If you working directly with the camera for non-ROS applications, then you just need to be using librealsense: https://github.com/IntelRealSense/librealsense/
which is the library realsense-camera relies upon.

**Comment by mdhorn** [comment]
@liyuming1978 Let me know if you are working in ROS and if we need to follow up on this.
