### ISSUE TITLE
D435 & T265 Doesn't working suddenly!!

### ISSUE THREAD

**Issue by Eslamrady42** [realsenseai/realsense-ros#1253]
I have a problem in D435 & T265 they worked with me perfectly once on my laptop then I shutdown my laptop then tried in the next day but it's not working by this error:

eslam@root:~$ roslaunch realsense2_camera rs_camera.launch filters:=pointcloud
... logging to /home/eslam/.ros/log/83eda49a-b3af-11ea-aac9-64006afb8a06/roslaunch-root-11466.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://root:34765/

SUMMARY
========

PARAMETERS
 * /camera/realsense2_camera/accel_fps: 250
 * /camera/realsense2_camera/accel_frame_id: camera_accel_frame
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: False
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/allow_no_texture_points: False
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/calib_odom_file: 
 * /camera/realsense2_camera/clip_distance: -2.0
 * /camera/realsense2_camera/color_fps: 30
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: 480
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: 640
 * /camera/realsense2_camera/depth_fps: 30
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: 480
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: 640
 * /camera/realsense2_camera/device_type: 
 * /camera/realsense2_camera/enable_accel: True
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye1: True
 * /camera/realsense2_camera/enable_fisheye2: True
 * /camera/realsense2_camera/enable_fisheye: True
 * /camera/realsense2_camera/enable_gyro: True
 * /camera/realsense2_camera/enable_infra1: True
 * /camera/realsense2_camera/enable_infra2: True
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_sync: False
 * /camera/realsense2_camera/filters: pointcloud
 * /camera/realsense2_camera/fisheye1_frame_id: camera_fisheye1_f...
 * /camera/realsense2_camera/fisheye1_optical_frame_id: camera_fisheye1_o...
 * /camera/realsense2_camera/fisheye2_frame_id: camera_fisheye2_f...
 * /camera/realsense2_camera/fisheye2_optical_frame_id: camera_fisheye2_o...
 * /camera/realsense2_camera/fisheye_fps: 30
 * /camera/realsense2_camera/fisheye_frame_id: camera_fisheye_frame
 * /camera/realsense2_camera/fisheye_height: 480
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: 640
 * /camera/realsense2_camera/gyro_fps: 400
 * /camera/realsense2_camera/gyro_frame_id: camera_gyro_frame
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/imu_optical_frame_id: camera_imu_optica...
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra_fps: 30
 * /camera/realsense2_camera/infra_height: 480
 * /camera/realsense2_camera/infra_width: 640
 * /camera/realsense2_camera/initial_reset: False
 * /camera/realsense2_camera/json_file_path: 
 * /camera/realsense2_camera/linear_accel_cov: 0.01
 * /camera/realsense2_camera/odom_frame_id: camera_odom_frame
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/pose_frame_id: camera_pose_frame
 * /camera/realsense2_camera/pose_optical_frame_id: camera_pose_optic...
 * /camera/realsense2_camera/publish_odom_tf: True
 * /camera/realsense2_camera/publish_tf: True
 * /camera/realsense2_camera/rosbag_filename: 
 * /camera/realsense2_camera/serial_no: 
 * /camera/realsense2_camera/tf_publish_rate: 0.0
 * /camera/realsense2_camera/topic_odom_in: odom_in
 * /camera/realsense2_camera/unite_imu_method: 
 * /camera/realsense2_camera/usb_port_id: 
 * /rosdistro: melodic
 * /rosversion: 1.14.6

NODES
  /camera/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)

auto-starting new master
process[master]: started with pid [11484]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 83eda49a-b3af-11ea-aac9-64006afb8a06
process[rosout-1]: started with pid [11495]
started core service [/rosout]
process[camera/realsense2_camera_manager-2]: started with pid [11502]
process[camera/realsense2_camera-3]: started with pid [11503]
[ INFO] [1592737710.827572710]: Initializing nodelet with 4 worker threads.
[ INFO] [1592737730.932880973]: RealSense ROS v2.2.13
[ INFO] [1592737730.932911221]: Running with LibRealSense v2.33.1
[ INFO] [1592737730.941857885]:  
[ INFO] [1592737731.273399197]: Device with serial number 944122071903 was found.

[ INFO] [1592737731.273496035]: Device with physical ID 2-2-14 was found.
[ INFO] [1592737731.273618049]: Device with name Intel RealSense D435 was found.
[ INFO] [1592737731.274533669]: Device with port number 2-2 was found.
[ INFO] [1592737731.277748770]: getParameters...
[ INFO] [1592737731.331722532]: setupDevice...
[ INFO] [1592737731.331753349]: JSON file is not provided
[ INFO] [1592737731.331772202]: ROS Node Namespace: camera
[ INFO] [1592737731.331792357]: Device Name: Intel RealSense D435
[ INFO] [1592737731.331825135]: Device Serial No: 944122071903
[ INFO] [1592737731.331840215]: Device physical port: 2-2-14
[ INFO] [1592737731.331867286]: Device FW version: 05.12.03.00
[ INFO] [1592737731.331897343]: Device Product ID: 0x0B07
[ INFO] [1592737731.331918683]: Enable PointCloud: On
[ INFO] [1592737731.331938758]: Align Depth: Off
[ INFO] [1592737731.331965739]: Sync Mode: On
[ INFO] [1592737731.332013888]: Device Sensors: 
[ INFO] [1592737731.332056879]: Stereo Module was found.
[ INFO] [1592737731.332084410]: RGB Camera was found.
[ INFO] [1592737731.332115521]: (Fisheye, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1592737731.332133025]: (Fisheye, 1) sensor isn't supported by current device! -- Skipping...
[ INFO] [1592737731.332149993]: (Fisheye, 2) sensor isn't supported by current device! -- Skipping...
[ INFO] [1592737731.332167308]: (Gyro, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1592737731.332198913]: (Accel, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1592737731.332223839]: (Pose, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1592737731.332261554]: Add Filter: pointcloud
[ INFO] [1592737731.332773513]: num_filters: 1
[ INFO] [1592737731.332794290]: Setting Dynamic reconfig parameters.
[ INFO] [1592737736.420996503]: Done Setting Dynamic reconfig parameters.
[ INFO] [1592737736.453942615]: depth stream is enabled - width: 640, height: 480, fps: 30, Format: Z16
[ INFO] [1592737736.454177015]: infra1 stream is enabled - width: 640, height: 480, fps: 30, Format: Y8
[ INFO] [1592737736.454369599]: infra2 stream is enabled - width: 640, height: 480, fps: 30, Format: Y8
[ INFO] [1592737736.480470936]: color stream is enabled - width: 640, height: 480, fps: 30, Format: RGB8
[ INFO] [1592737736.480541575]: setupPublishers...
[ INFO] [1592737736.482982664]: Expected frequency for depth = 30.00000
[ INFO] [1592737736.511934989]: Expected frequency for infra1 = 30.00000
[ INFO] [1592737736.528097942]: Expected frequency for infra2 = 30.00000
[ INFO] [1592737736.545916098]: Expected frequency for color = 30.00000
[ INFO] [1592737736.563226905]: setupStreams...
[ INFO] [1592737736.665048363]: insert Depth to Stereo Module
[ INFO] [1592737736.665149768]: insert Color to RGB Camera
[ INFO] [1592737736.665180744]: insert Infrared to Stereo Module
[ INFO] [1592737736.665208481]: insert Infrared to Stereo Module
[ INFO] [1592737736.920489321]: SELECTED BASE:Depth, 0
[ INFO] [1592737736.974401737]: RealSense Node Is Up!
 21/06 13:08:57,038 WARNING [139829572531968] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 21/06 13:08:57,099 WARNING [139829572531968] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 21/06 13:08:57,181 WARNING [139829572531968] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 21/06 13:08:57,264 WARNING [139829572531968] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 21/06 13:08:57,345 WARNING [139829572531968] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 21/06 13:08:57,406 WARNING [139829572531968] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
[ WARN] [1592737737.432580112]: Hardware Notification:USB SCP overflow,1.59274e+12,Error,Hardware Error
 21/06 13:08:57,467 WARNING [139829572531968] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 21/06 13:08:58,123 WARNING [139829538961152] (uvc-device.cpp:664) interrupt event received: 1, 3, 0, 7, 0, 23, 
[ WARN] [1592737738.453935939]: Hardware Notification:IR stream start failure,1.59274e+12,Error,Hardware Error
 21/06 13:08:58,943 WARNING [139829538961152] (uvc-device.cpp:664) interrupt event received: 1, 3, 0, 7, 0, 12, 
[ WARN] [1592737739.475562008]: Hardware Notification:USB REC overflow,1.59274e+12,Error,Hardware Error
 21/06 13:08:59,505 ERROR [139828750440192] (uvc-streamer.cpp:106) uvc streamer watchdog triggered on endpoint: 130
[camera/realsense2_camera_manager-2] process has died [pid 11502, exit code -11, cmd /opt/ros/melodic/lib/nodelet/nodelet manager __name:=realsense2_camera_manager __log:=/home/eslam/.ros/log/83eda49a-b3af-11ea-aac9-64006afb8a06/camera-realsense2_camera_manager-2.log].
log file: /home/eslam/.ros/log/83eda49a-b3af-11ea-aac9-64006afb8a06/camera-realsense2_camera_manager-2*.log
[camera/realsense2_camera-3] process has finished cleanly
log file: /home/eslam/.ros/log/83eda49a-b3af-11ea-aac9-64006afb8a06/camera-realsense2_camera-3*.log
^C[rosout-1] killing on exit
[rosout-1] escalating to SIGTERM
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
eslam@root:~$

**Comment by Eslamrady42** [comment]
@doronhi  all I want to know what does it mean??!

[camera/realsense2_camera_manager-1] process has died [pid 6305, exit code -11, cmd /opt/ros/melodic/lib/nodelet/nodelet manager __name:=realsense2_camera_manager __log:=/home/eslam/.ros/log/d76349ea-b3b4-11ea-a4de-64006afb8a06/camera-realsense2_camera_manager-1.log].
log file: /home/eslam/.ros/log/d76349ea-b3b4-11ea-a4de-64006afb8a06/camera-realsense2_camera_manager-1*.log

**Comment by Alex-Beh** [comment]
@Eslamrady42 Hello, I am facing the same issue with you. May I know did you solve that?

**Comment by Eslamrady42** [comment]
> @Eslamrady42 Hello, I am facing the same issue with you. May I know did you solve that?

Didn’t solve it yet I’m waiting for the solution from @RealSenseCustomerSupport 
@MartyG-RealSense 
@doronhi

**Comment by Alex-Beh** [comment]
Set `enable_infra2` to false in `rs_rgbd.launch` seem will stop the error. However, I don't know whether this is a proper solution or not.

**Comment by Eslamrady42** [comment]
> Set `enable_infra2` to false in `rs_rgbd.launch` seem will stop the error. However, I don't know whether this is a proper solution or not.

It’s the same result nothing changed.

**Comment by Alex-Beh** [comment]
Maybe you can try run `realsense-viewer` and update to the latest firmware.
https://github.com/IntelRealSense/librealsense/blob/master/doc/distribution_linux.md#installing-the-packages

**Comment by Eslamrady42** [comment]
> Maybe you can try run `realsense-viewer` and update to the latest firmware.
> 
> https://github.com/IntelRealSense/librealsense/blob/master/doc/distribution_linux.md#installing-the-packages

That what I have SDK 2.35.2

**Comment by Eslamrady42** [comment]
Solved by using Ubuntu 16 and ROS Kinetic

**Comment by Steven-ZY** [comment]
@Eslamrady42 I have the same question, how do you solve it? Thanks in advance. [Hardware Notification:Depth stream start ]failure,1.60683e+12,Error,Hardware Error
