### ISSUE TITLE
How to turn 3D point cloud on?

### ISSUE THREAD

**Issue by Joechencc** [realsenseai/realsense-ros#1254]
I launch the camera with following command:
roslaunch realsense2_camera rs_camera.launch filters:=pointcloud 

But when I transfer the point cloud obtained to x,y,z coordinate. I will always have 0 z value which looks like a 2D pointcloud. I wonder why this happens

Sample Output:
[ INFO] [1592848575.149751606]: out_x:-0.102187
[ INFO] [1592848575.150255193]: out_y:413.696472
[ INFO] [1592848575.150657276]: out_z:0.000000

Code Sample:
sensor_msgs::PointCloud2Iterator<double> out_x(*outMsg, "x");
for (size_t i = 0; i < msg->height * msg->width; ++i, ++out_x, ++out_y, ++out_z,++in_x, ++in_y, ++in_z)
	{
		*out_x = *in_x;
		*out_y = *in_y;
		*out_z = *in_z;
		ROS_INFO("out_x:%lf",out_x[0]);
		ROS_INFO("out_y:%lf",out_y[0]);
		ROS_INFO("out_z:%lf",out_z[0]);
	}

And fixed frame is set related to the origin:

#setup the fixed frame
rosrun tf static_transform_publisher 0 0 0 0 0 0 1 map my_frame 10

#create the relative framework between camera and fix_frame
rosrun tf static_transform_publisher 0.0 0.0 0.0 0.0 0.0 0.0 camera_depth_optical_frame map 100

**Comment by MartyG-RealSense** [comment]
Hi @Joechencc   do you get any depth if you leave out your fixed-frame statement and set it up like the instructions in the link below, please:

https://github.com/IntelRealSense/librealsense/issues/6451#issuecomment-643961366

**Comment by Joechencc** [comment]
Yeah. That is what I got before. Is this the 3D point cloud?

![image](https://user-images.githubusercontent.com/55113116/85432020-55388500-b550-11ea-902f-c0a29fdb017e.png)

Because once I subscribe the pointcloud2 , and I print out x,y,z coordinates of the pointcloud.  Z= 0

Should I use Realsense SDK to obtain the pointcloud2 coordinate? Like https://dev.intelrealsense.com/docs/rs-pointcloud

**Comment by MartyG-RealSense** [comment]
Yes, that is a 3D point cloud that is displayed in the center panel.

You do not need to use Librealsense SDK programs such as **rs-pointcloud** to obtain the pointcloud2 coordinate.  Librealsense applications and applications running in the RealSense ROS wrapper are separate and do not affect each other.

It looks as though the publishing of pointcloud2 and the Image are fine.  

The link below looks like a good reference in regard to using a RealSense camera to get XYZ from pointcloud2:

https://answers.ros.org/question/310996/how-to-get-xyz-and-rgb-of-each-pixel-from-a-sensormsg-image/

**Comment by Joechencc** [comment]
With the link you provided,  fixed-frame setup has error popped up actually. 

IntelRealSense/librealsense#6451 (comment)

[ERROR] [1592942324.062232575]: Ignoring transform for child_frame_id "camera_depth_optical_frame" from authority "unknown_publisher" because of a nan value in the transform (0.000000 0.000000 0.000000) (nan nan nan nan)

Current TF map looks like this:
![image](https://user-images.githubusercontent.com/55113116/85455120-99854e80-b56b-11ea-9045-5187d5f4c0f9.png)

Fixed Frame [map] does not exist

**Comment by MartyG-RealSense** [comment]
There was a previous RealSense ROS case where this error occurred.

https://github.com/IntelRealSense/realsense-ros/issues/1153#issuecomment-615204193

**Comment by Joechencc** [comment]
Is that the order wrong?

The example said "rosrun tf static_transform_publisher 0 0 0 0 0 0 0 map camera_depth_optical_frame 100" which links the map to camera_depth_optical_frame. However, map is fixed frame, it already has a parent base_link in this case.

Should it be the other way round 
"rosrun tf static_transform_publisher 0.0 0.0 0.0 0.0 0.0 0.0 camera_depth_optical_frame map 100" which the camera linked to the fixed frame.

**Comment by MartyG-RealSense** [comment]
The question is somewhat beyond my current ROS knowledge, as I am a ROS generalist rather than a specialist.  I wonder though whether fixed_frame should be set in RViz to **camera_link** instead of map, like in the RealSense ROS documentation's example use of **roslaunch realsense2_camera rs_camera.launch filters:=pointcloud**?

https://github.com/IntelRealSense/realsense-ros#rgbd-point-cloud

**Comment by Joechencc** [comment]
Thank you. It helps a lot! I have changed the relative fix frame .  It is kind of working.

**Comment by MartyG-RealSense** [comment]
Great news - thanks for the update!

**Comment by MartyG-RealSense** [comment]
Hi @Joechencc   Do you require further assistance with this case please, or can it be closed?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
