### ISSUE TITLE
Frames 

### ISSUE THREAD

**Issue by dan11003** [realsenseai/realsense-ros#1257]
Hello vision folks,
When using align_depth:=true, is the point cloud transformed into the same coordinate frame as the color image?

We're currently evaluating an extrinsic multi source calibration procedure. We have a few cameras detecting ArUco Markers poses in camera frames. We then use optimization find the extrinsic parameter between cameras that minimize the distance between the observed poses. The minimized error (based in rgb images) is very small (mm). However when projecting the point cloud colored by the image in the world there is a systematic alignment error in the colored point cloud despite that align_depth is set  to  true. To summarize cam-to-cam seems fine, depth-to-depth has systematic errors.

Any ideas?

**Comment by MartyG-RealSense** [comment]
Hi @dan11003   I researched your case extensively and considered various possibilities.  If you are using a D435 or D435i camera, the problem could be the difference in size of the field of view (FOV) of the depth and color on the D435 models.  The color FOV is smaller than the depth FOV on the D435 models (the D415 and the new D455 depth cameras have the same FOV for depth and color).

In Librealsense, a difference in FOV would be taken care of by aligning the depth to the color FOV size. 
 
The RealSense ROS documentation says though: "The depth FOV and the texture FOV are not similar.  By default, pointcloud is limited to the section of depth containing the texture.  You can have a full depth to pointcloud, coloring the regions beyond the texture with zeros, by setting **allow_no_texture_points** to true".

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
