### ISSUE TITLE
Adding rs2::frameset getter

### ISSUE THREAD

**Issue by titouanlh** [realsenseai/realsense-ros#1258]
Hi,

I would like to add a function in the base_realsense_node to retrieve a rs2::frameset with one depth frame and one color frame.
For now I have made something like this :
```
  cfg_.enable_stream(RS2_STREAM_DEPTH);
  cfg_.enable_stream(RS2_STREAM_COLOR);
  rs2::pipeline_profile profile = p_.start(cfg_);
...
// My "getter" fuction :
rs2::frameset visionsub::getFrameset(){
  rs2::frameset data = p_.wait_for_frames();
  rs2::frameset aligned_set = align_to_.process(data);
  return aligned_set;
}
```
But I would like to get the camera's ROS topic published as well (using the ROS realsense node)... so I think the best way to get both functionality would be implementing my getter inside the base_realsense_node, but I can't figure out how to achieve this.
Any idea ?
Thank's !

**Comment by MartyG-RealSense** [comment]
In the link below, @doronhi suggests accessing camera images from the function **BaseRealSenseNode::frame_callback** if you do not want to get the images by subscribing to topics published by the RealSense ROS wrapper.

https://github.com/IntelRealSense/realsense-ros/issues/787#issuecomment-500383618

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.

**Comment by titouanlh** [comment]
Sorry for my late reply, thank you very much for your answer.

**Comment by MartyG-RealSense** [comment]
You are very welcome @titouanlh   :)
