### ISSUE TITLE
An exception has been thrown: The requested pixel format 'W10 ' is not natively supported by the Linux kernel and likely requires a patch!

### ISSUE THREAD

**Issue by TingyangChen** [realsenseai/realsense-ros#1259]

**Comment by MartyG-RealSense** [comment]
Hi @TingyangChen   Two different ways to fix this error are offered in the link below.

https://github.com/IntelRealSense/librealsense/issues/4794#issuecomment-532558814

**Comment by TingyangChen** [comment]
@MartyG-RealSense Thanks! I have fixed the problem by following the instruction in the link https://github.com/IntelRealSense/librealsense/issues/4794#issuecomment-532558814

**Comment by MartyG-RealSense** [comment]
Great news - thanks so much for the update!

Is it okay to close this case now if you have found the solution, please?
