### ISSUE TITLE
Get_device_time_ms()took too long (more then 2 mScecs)

### ISSUE THREAD

**Issue by Jenny0420** [realsenseai/realsense-ros#1262]
camera : intel realsense D435
ros kinetic + ubuntu 16.04 LTS
my librealsense already done ,when i run "realsense-viewer",i can get the RGB Picture and Depth
**And my realsense- ros already done yet,in rviz i can get the image like this**
![22](https://user-images.githubusercontent.com/43374977/85943330-fadd6100-b961-11ea-8a52-4a266ee2e9d0.png)

**but when i run "roslaunch realsense2_camera rs_rgbd.launch"
i have got an error,like this:**

![3](https://user-images.githubusercontent.com/43374977/85943409-79d29980-b962-11ea-9033-f949fbc75096.png)

**when i run the "raulmur/ORB_SLAM2",i can't get the image,like this**

![11](https://user-images.githubusercontent.com/43374977/85943456-ca49f700-b962-11ea-820a-7294f265b6ae.png)
 
**Thanks for any help !!**

**Comment by MartyG-RealSense** [comment]
Please make sure you have the **rgbd** package for ROS Kinetic installed by using the instruction below:

**sudo apt install ros-kinetic-rgbd-launch**

**Comment by Jenny0420** [comment]
@MartyG-RealSense 
thanks,and i'm sure my '**ros-kinetic-rgbdd-launch**' was  the last vision
when i run '**realsense-viewer**',i got a warn 
![warn](https://user-images.githubusercontent.com/43374977/85979343-de4d3180-ba12-11ea-861d-d61201843fa9.png)
Maybe my two rules caused this problem.

**Comment by MartyG-RealSense** [comment]
If you have multiple udev rules then guidance is provided in the link below about which one is safe to remove.

https://github.com/IntelRealSense/librealsense/issues/6153#issuecomment-605687547

**Comment by Jenny0420** [comment]
i  followed the guidence and remove the rule"**60-librealsense2-udev-rules.rules**"
and then in "realsense-viewer" is ok ,no error,no warn.
but when i run "**roslaunch realsense2_camera rs_rgbd.launch**"
i got a new error
![error1](https://user-images.githubusercontent.com/43374977/85990173-32acdd00-ba24-11ea-9e09-e4437920bd75.png)

**Comment by MartyG-RealSense** [comment]
@Jenny0420   The guidance was that the rule under 60-librealsense2-udev-rules.rules was the one that should **not** have been removed because it breaks Debian.  The one that should have been removed is the one under the **etc** folder.

**Comment by Jenny0420** [comment]
oh...sorry .
it means that i need to clean all and rebuild from scratch.

**Comment by MartyG-RealSense** [comment]
Before doing that, you could try rebuilding the udev rules with this:

**sudo apt-get install librealsense2-dkms**

**Comment by Jenny0420** [comment]
the 'librealsense-dkms' was the last vision
maybe i can use
'**sudo cp config/60-librealsense2-udev-rules.rules /lib/udev/rules.d/**'
and remove the another one ??

**Comment by Jenny0420** [comment]
the 'librealsense2-dkms'was the last vision

**Comment by MartyG-RealSense** [comment]
Your knowledge of udev rules installation is probably better than mine!  If you are going to have to do a fresh install anyway if it does not work, you may as well try it.

**Comment by Jenny0420** [comment]
i have tired and it doesn't work .i try to remove all (realsense SDK , ros ,realsense-ros)
and do a freash install .
thanks

**Comment by MartyG-RealSense** [comment]
Good luck!

**Comment by Jenny0420** [comment]
@MartyG-RealSense 
i have already rebuild the **realsense SDK2** and **ros kinetic**
And i want to see some image by **rviz** and when i run 
**'roslaunch realsense2_camera rs_camera.launch'**
i got an error,like this:
![warn1](https://user-images.githubusercontent.com/43374977/86219351-a7168600-bbb4-11ea-93e8-d82dfe491877.png)

this is a new warn i've never met before.

and in rviz when i choose the topic ,i found that the **"depth_registered"** is gone,i can't see the pointcloud2 image
![gone](https://user-images.githubusercontent.com/43374977/86219991-8b5faf80-bbb5-11ea-8891-db49f33f3690.png)

**Comment by MartyG-RealSense** [comment]
Hi @Jenny0420   On Ubuntu, support for frame metadata has to be patched in if you are building from source.

https://dev.intelrealsense.com/docs/frame-metadata#section-os-support

An exception to this is if you build from source using the **backend** method, which requires an internet connection.  Metadata support is then included in the build.  The backend installation method is described in the link below.

https://github.com/IntelRealSense/librealsense/issues/6710#issuecomment-650611442

Looking at your log extract though, it does not seem that an absence of metadata has "killed" the launch process.

The link below describes how to get an RGBD pointcloud with **pointcloud2** and display it in RViz by setting Fixed Frame to **camera_link.**

https://github.com/IntelRealSense/realsense-ros#rgbd-point-cloud

**Comment by MartyG-RealSense** [comment]
Hi @Jenny0420   Do you still require assistance with this case please, or can it be closed?   Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
