### ISSUE TITLE
L515 URDF

### ISSUE THREAD

**Issue by lauesa** [realsenseai/realsense-ros#1263]
Does Intel have an URDF for the L515 available for use?

**Comment by MartyG-RealSense** [comment]
Apologies for the delay in responding.  I checked the URDF page of the latest RealSense ROS wrapper version at the time of writing this (version **2.2.14**) and there is not a URDF xacro file listed for the L515 yet.

https://github.com/IntelRealSense/realsense-ros/tree/development/realsense2_description/urdf

**Comment by lauesa** [comment]
That was my finding as well. Are there plans to add a URDF xacro file for the L515 in the near future (2 weeks)?

**Comment by MartyG-RealSense** [comment]
I am not involved in development.  As wrapper version 2.2.14 only just came out though, it seems unlikely within that time-scale.

**Comment by lauesa** [comment]
Thanks. I'll check back in periodically to see if it has been added.

**Comment by doronhi** [comment]
I'm looking into it.

**Comment by doronhi** [comment]
Added urdf for L515 in version 3.1.2 for eloquent and in version 2.2.20 for ROS1.
