### ISSUE TITLE
ROS2 Foxy proper release 

### ISSUE THREAD

**Issue by doisyg** [realsenseai/realsense-ros#1270]
Repost from: https://github.com/intel/ros2_intel_realsense/issues/133

Hello,
Now that ROS2 LTS Foxy is out, many companies are considering to switch for real to ROS2. What's the planned effort for the realsense wrapper ? It seems that most of the development effort is focused on this ROS1 wrapper. 
Shouldn't the ROS2 repo (https://github.com/intel/ros2_intel_realsense)  be hosted on this organization and maintained by the same people?
Is there any development timeline and a release target date ?

**Comment by doronhi** [comment]
Hello,
We feel the same way. I don't have a specific target date yet but work is already underway.
Since librealsense2 still not officially supports Ubuntu 20.04, the first realsense2_wrapper for ROS2 will be for eloquent (Ubuntu 18.04).

**Comment by doisyg** [comment]
Good to know.
For info, we are using librealsense2 (deb install) on Ubuntu 20.04 + the ROS1 wrapper without any specific issue (compiled from src under ROS noetic)

**Comment by allenh1** [comment]
Any update on this? And (slightly off topic) is there a plan to get the T265 to work with ROS 2?

**Comment by doronhi** [comment]
Covid19 shuffled my plans but still we managed to release a ROS2 version. Currently only for eloquent. This version include the same support for T265 as the ROS1 wrapper.
You can download it from: https://github.com/IntelRealSense/realsense-ros/tree/eloquent

**Comment by allenh1** [comment]
> This version include the same support for T265 as the ROS1 wrapper.

Fantastic news! Thanks!

**Comment by liushuya7** [comment]
Can this eloquent package be run on ROS2 Foxy? I built it and run the camera node, everything seems working fine except there is no image showing from the camera topic.
See [my post](https://github.com/IntelRealSense/realsense-ros/issues/1336#issuecomment-733466270) in Issue #1336
