### ISSUE TITLE
t265 stop working 

### ISSUE THREAD

**Issue by sunrentao** [realsenseai/realsense-ros#1272]
Hello, I meet this problem : 
<pre>[ INFO] [1594210456.747540676]: RealSense Node Is Up!
[ INFO] [1594210456.748100458]: Subscribing to in_odom topic: /odom
 08/07 14:15:31,468 WARNING [139999377049344] (messenger-libusb.cpp:66) bulk_transfer returned error, endpoint: 0x2, error: No such device, err. num: 19
 08/07 14:15:31,468 ERROR [139999377049344] (tm-device.cpp:2036) Bulk request error RS2_USB_STATUS_NO_DEVICE
 08/07 14:15:31,873 WARNING [139999368656640] (messenger-libusb.cpp:66) bulk_transfer returned error, endpoint: 0x2, error: No such device, err. num: 19
 08/07 14:15:31,873 ERROR [139999368656640] (tm-device.cpp:2036) Bulk request error RS2_USB_STATUS_NO_DEVICE
 08/07 14:15:32,162 ERROR [139999402227456] (tm-device.cpp:1345) Stream transfer failed, exiting
 08/07 14:15:32,163 ERROR [139999402227456] (tm-device.cpp:1263) Interrupt transfer failed, exiting
 08/07 14:15:36,751 WARNING [139999104222976] (messenger-libusb.cpp:66) bulk_transfer returned error, endpoint: 0x2, error: No such device, err. num: 19
 08/07 14:15:36,752 ERROR [139999104222976] (tm-device.cpp:2036) Bulk request error RS2_USB_STATUS_NO_DEVICE
^C[map_to_odom-4] killing on exit
[map_server-3] killing on exit
[camera/realsense2_camera-2] killing on exit
[camera/realsense2_camera_manager-1] killing on exit
save map
 08/07 14:15:40,427 WARNING [140000421422976] (messenger-libusb.cpp:66) bulk_transfer returned error, endpoint: 0x2, error: No such device, err. num: 19
 08/07 14:15:40,427 ERROR [140000421422976] (tm-device.cpp:2036) Bulk request error RS2_USB_STATUS_NO_DEVICE
 08/07 14:15:40,427 WARNING [140000421422976] (messenger-libusb.cpp:92) usb_request_queue returned error, endpoint: 131 error: No such device, number: 19
terminate called after throwing an instance of &apos;rs2::error&apos;
  what():  failed to submit request, error: RS2_USB_STATUS_OTHER
shutting down processing monitor...
... shutting down processing monitor complete
<b>done</b>
</pre>

I have this problem after I modify some code in base_realsense_node.cpp around line 756, I modify as 
<pre>
                _sensors[GYRO] = sensor;
                _sensors[ACCEL] = sensor;
                _sensors[POSE] = sensor;
                _sensors[FISHEYE1] = sensor;
                _sensors[FISHEYE2] = sensor;
                _sensors_callback[module_name] = multiple_message_callback_function;
                rs2::pose_sensor _pose_sensor (sensor.get());    
                _pose_sensors.push_back(_pose_sensor);
</pre>
this code used to save the map created by the camera. 
If you have any idea about this problem?

Thank you

**Comment by RealSenseSupport** [comment]
Is this issue happening on the latest release?

It is worth reviewing the specification update as outlined on the following page: https://dev.intelrealsense.com/docs/tracking-camera-t265
