### ISSUE TITLE
 L515 Incorrect imu Header Timestamps 

### ISSUE THREAD

**Issue by wangyuanbiubiubiu** [realsenseai/realsense-ros#1275]
I want to read the IMU data and image data of L515 laser camera. I find that the timestamp of the image is the timestamp of the system, while the timestamp of the IMU is the timestamp of the device. How should I fix this problem?
Below is my Launch file Settings：
![inter3](https://user-images.githubusercontent.com/42170618/87109240-b96c8000-c296-11ea-92dc-3ce215ead943.png)
Below is my log：
![inter1](https://user-images.githubusercontent.com/42170618/87109269-c9845f80-c296-11ea-8e5b-acf1e928923b.png)

**Comment by wangyuanbiubiubiu** [comment]
I have now checked the type of timestamp and found the following problems：
![inter_issue1](https://user-images.githubusercontent.com/42170618/87213751-c0a89200-c359-11ea-8636-99e1c290209a.png)
Output in terminal
![2020-07-11 09-32-12屏幕截图](https://user-images.githubusercontent.com/42170618/87213759-d8801600-c359-11ea-8001-a62da27ec223.png)

**Comment by RealSenseSupport** [comment]
Hi @wangyuanbiubiubiu 

I'm not sure I understand what you mean by you "found the following problems:"...

...but have you tried setting the *global_time_enabled* parameters to _true_ on both camera/motion_module and camera/rgb_camera? This should get you both timestamps in the same domain.

Thanks

**Comment by RealSenseSupport** [comment]
Hi,

Will you be needing further help with this? If we don’t hear from you in 7 days, this issue will be closed.

Thanks
