### ISSUE TITLE
Odometry of T265 is not being published when starting the default launch file from the development branch.

### ISSUE THREAD

**Issue by alessandromorra** [realsenseai/realsense-ros#1276]
OS: Ubuntu 18.04
Branch: `development` [default when installing]

I have tried to launch my T265 sensor via ROS like that:

```
roslaunch realsense2_camera rs_t265.launch 
```

Unfortunately, my `/camera/odom/sample` is not available:

```
$ rostopic echo /camera/odom/sample 
WARNING: topic [/camera/odom/sample] does not appear to be published yet
```

Only when I switch to this branch then it works: `2.2.14` [probably also others but I did not test them all]

I am not sure if this is a bug or a feature, just to let you guys know.

**Comment by droter** [comment]
OS: Ubuntu 16.04
Branch: development [default when installing]

Also seeing the same thing.  IMU and Gyro are publishing but no odom.

**Comment by FPSychotic** [comment]
same here...last version

**Comment by nilseuropa** [comment]
same here as well

**Comment by nilseuropa** [comment]
`      <arg name="enable_pose"              value="true"/>
`
is missing from the launch file

**Comment by doronhi** [comment]
I am sorry for paying attention so late.
As the line "<arg name="enable_pose"         default="true"/>" is now in the rs_t265.launch file, does it work now? Can this issue be closed?

**Comment by alessandromorra** [comment]
On version `2.2.22` it works. Form my side this issue can be closed.

**Comment by nilseuropa** [comment]
I can confirm that it works.
