### ISSUE TITLE
Remap T265 rostopics

### ISSUE THREAD

**Issue by sumitsarkar1** [realsenseai/realsense-ros#1277]
Hi..I am new to ROS..I need to remap T265 camera topics /camera/fisheye1/image_raw to /left/image_raw and /camera/fisheye1/camera_info to /left/camera_info. How do I achieve it with a launch file? Or do I need to modify the rs_t265.launch file.

**Comment by RealSenseSupport** [comment]
There are quite a bit of documentation in the repository that helps in configuring for ROS:  https://github.com/IntelRealSense/realsense-ros

Launch files and include files are good locations to look at
