### ISSUE TITLE
I install both method1 and method 2, and it cannot use...

### ISSUE THREAD

**Issue by EasternH** [realsenseai/realsense-ros#1290]
I have remove the method1 by using sudo apt-get remove , but maybe I lose something, what should I do.

**Comment by MartyG-RealSense** [comment]
Hi @EasternH    Can you tell me please the information below:

- Which RealSense camera you are using
-  Which computer or computing device you are using (PC, Jetson, Raspberry Pi, etc). 

-  Which operating system are you using (Windows, Linux, Raspbian, etc)   

Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
