### ISSUE TITLE
roslaunch realsense2_camera  not working 

### ISSUE THREAD

**Issue by taegyuahn** [realsenseai/realsense-ros#1292]
I use ubuntu 18.04 LTS on PC, ROS melodic and my device is LIDAR L515.

I followed these installation guide 

(Method2) https://github.com/IntelRealSense/realsense-ros#step-2-install-intel-realsense-ros-from-sources
https://github.com/IntelRealSense/librealsense/blob/master/doc/installation.md
https://github.com/IntelRealSense/librealsense/blob/master/doc/distribution_linux.md#installing-the-packages

and my realsense-ros version is 2.2.15 , librealsense 2.36.0
`realsense-viewer` is working but if I launch `roslaunch realsense2_camera rs_camera.launch` 
the terminal shows like this.
![image](https://user-images.githubusercontent.com/52451254/87750376-3cad4900-c836-11ea-900a-14104c442bff.png)

I tried to install realsense-ros version 2.2.14 and reinstalled ros melodic and everything in the installation guide
but roslauch doesn't works.
Anyone can help me?

**Comment by taegyuahn** [comment]
I solved this issue after installing libuvc in this page https://github.com/IntelRealSense/librealsense/blob/master/doc/libuvc_installation.md
but another issue happened...

![image](https://user-images.githubusercontent.com/52451254/87754705-7a16d400-c840-11ea-8924-d226df25fbef.png)

**Comment by doronhi** [comment]
I could not reproduce. I am very sorry as I believe it reflects a real issue.
The message of "control_transfer returned error" does not in itself implies a problem. It it known to appear a few times at the beginning of the node's run, as is the case that you show here, but unless it appears rapidly and constantly it seems to be dealt with by the driver. It is disturbing and is still under investigation

**Comment by manu-adina** [comment]
> I solved this issue after installing libuvc in this page https://github.com/IntelRealSense/librealsense/blob/master/doc/libuvc_installation.md
> but another issue happened...
> 
> ![image](https://user-images.githubusercontent.com/52451254/87754705-7a16d400-c840-11ea-8924-d226df25fbef.png)

I'm facing the exact same issue. I'm using VMware with Ubuntu 18.04, the device is working in the RealSense viewer just fine, but nothing on Rviz. I'm getting the same succession of warnings as shown in the screenshot as well.

**Comment by RealSenseSupport** [comment]
Hi @taegyuahn 

Is there anything else needed on this?

*If we don’t hear from you in 7 days, this issue will be closed.
