### ISSUE TITLE
L515 Portrait Resolution (480 x 640) Pointcloud is Rotated and Mirrored

### ISSUE THREAD

**Issue by pauldeee** [realsenseai/realsense-ros#1298]
Hi,

The L515 is listed as supporting several depth resolutions:
`Depth	  1024x768	@ 30Hz	   Z16
    Depth	  768x1024	@ 30Hz	   Z16
    Depth	  640x480 	@ 30Hz	   Z16
    Depth	  480x640 	@ 30Hz	   Z16`

When I attempt to use the "portrait" resolution 480 x 640 the point cloud appears to be rotated 90 degrees and mirrored. Is this the intended behavior?

In my launch file I specify:
`<arg name="depth_width" value="480"/>
        <arg name="depth_height" value="640"/>`

Might there be a different way to use the portrait resolutions that I am unaware of?

I'm using Ubuntu 16.04 and ROS Kinetic on NUC (PC) with librealsense deb packages version v2.36.0 and librealsense ros v2.2.15.

Regards

**Comment by blakely3dnm** [comment]
I see the same thing in realsense-viewer so I wonder if this is a firmware issue, as there is no way to unmirror a pointcloud by rotation or translation (without doing things in the 4th dimension)

**Comment by pauldeee** [comment]
The gentlest of bumps.

**Comment by RealSenseSupport** [comment]
Hi,

Yes this is expected behavior. Incidentally the plan is to deprecate these "flipped" resolutions so we'd recommend using the standard (landscape) ones .

Thanks

**Comment by blakely3dnm** [comment]
I was thinking it would be nice to have this setting to change from portrait to landscape orientations to better suit the environment as a robot is moving through a scene, without the need for actually rotating the sensor. I can see how perhaps the mirroring could be corrected downstream of realsense-ros but it would be unfortunate if the option to change orientation is done away with completely.

**Comment by RealSenseSupport** [comment]
Thank you @blakely3dnm .  We'll pass this feedback along to engineering.

FYI...I believe the rationale is that it's causing more confusion than helping. Incidentally the "flipped/rotated" resolutions is the native sensor data so we already perform a rotation/mirror to expose the standard (landscape) formats...and any further manipulation can be handled downstream on a use case basis.

Thanks

**Comment by RealSenseSupport** [comment]
Hi,

Will you be needing further help with this? If we don’t hear from you in 7 days, this issue will be closed.

Thanks
