### ISSUE TITLE
Intel D4XX controlling the Laser  Power problem

### ISSUE THREAD

**Issue by dingbaiyin** [realsenseai/realsense-ros#1300]
The main purpose is to adjust the power of the laster to the maximum before each picture is collected, and adjust the power to 0 after acquisition. After changing the control of Laster power, the program error "terminate called after throwing an instance of'rs2::error' was encountered when calling the controlling Laster power program
   what(): null pointer passed for argument "device"
It may be that there is a problem with my program, but I don't know how to eliminate it. Below is my relevant code pictures, please help me analyze where the problem is。
![cam_process_cpp](https://user-images.githubusercontent.com/40271689/88129538-edd32b00-cc0a-11ea-8352-de0f4f2c40f9.png)
![cam_process_hpp](https://user-images.githubusercontent.com/40271689/88129542-f0358500-cc0a-11ea-9c22-07afd75b1698.png)
![collecting picture](https://user-images.githubusercontent.com/40271689/88129545-f0ce1b80-cc0a-11ea-9524-843dd6647dcb.png)
![function2](https://user-images.githubusercontent.com/40271689/88129549-f1ff4880-cc0a-11ea-9362-2ed299eb6cbf.png)

**Comment by dingbaiyin** [comment]
The  error is reported when the program starts to call the ControlLasterPowerTo_Max() function or ControlLasterPowerTo_Min().Program error message  as the picture shows,
![error_information](https://user-images.githubusercontent.com/40271689/88138377-24677080-cc20-11ea-9d21-3cfbeb25c8dc.png)

**Comment by MartyG-RealSense** [comment]
Hi @dingbaiyin   If I were writing such a program myself then I would centralise all the camera configuration processes such as the **ctx** and **device** instructions at the top of one script.  In your current setup, you define the configuration once at the top of **cam_process.cpp** and then repeat the configuration instructions again in **ControlLasterPowerTo_Min** and  **ControlLasterPowerTo_Max**.  

Camera config instructions tend to be defined **before** the pipeline starts.  The program may not agree with these setup instructions being called once the pipeline has started.

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
