### ISSUE TITLE
Realsense camera launch fails after some time

### ISSUE THREAD

**Issue by akashatharv** [realsenseai/realsense-ros#1301]
Hi

I am using a realsense d435 camera on a Raspberry Pi4 with Raspbian buster 10 and ROS melodic. I am running the launch file rs_rgbd.launch for getting and visualizing the data, however after all the nodes have ran for about 30-45 seconds the terminal with the launch file stops working and my Pi becomes unresponsive after that.  Is there a reason why that's happening ?

**Comment by MartyG-RealSense** [comment]
Hi @akashatharv   Can you provide details of any warning / error messages that you have in the ROS log, please?   Thanks!

**Comment by akashatharv** [comment]
![image](https://user-images.githubusercontent.com/42795936/88195977-a9498e80-cc0e-11ea-8ca2-1357b4cbf755.png)

This is what I have . I am trying to SSH into the Pi using a PC . For some reason after some time none of my terminals that I have used to ssh into the Pi respond after some time.

**Comment by MartyG-RealSense** [comment]
If the **control_transfer returned** error is continuously generating then it indicates a communication problem with the device. 

https://github.com/IntelRealSense/realsense-ros/issues/1089#issuecomment-597074650

Do the messages start appearing in the log immediately after launch or 30 to 45 seconds into the streaming session, please?

**Comment by akashatharv** [comment]
They only appear at the beginning

**Comment by MartyG-RealSense** [comment]
Okay, thank you.   So it is the red errors that occur when streaming fails?

**Comment by akashatharv** [comment]
Yes

**Comment by MartyG-RealSense** [comment]
Which Librealsense version are you using, please?

**Comment by akashatharv** [comment]
I am using v2.34.0
Can you please also tell me what these errors mean 
ERROR [2499032080] (uvc-streamer.cpp:106) uvc streamer watchdog triggered on endpoint: 131
 ERROR [2563761168] (uvc-streamer.cpp:106) uvc streamer watchdog triggered on endpoint: 132

**Comment by MartyG-RealSense** [comment]
I guessed that you might have been using SDK 2.34.0, as 2.34.0 was particularly affected by the **get_device_time_ms()** error, both in Librealsense and the RealSense ROS wrapper.   Would it be possible to upgrade to a newer Librealsense and matching ROS wrapper version?

**Comment by akashatharv** [comment]
Okay let me try that. I will update the issue accordingly. Thank you for your help. Have a nice day!!

**Comment by MartyG-RealSense** [comment]
I look forward to your update.   Good luck!   :)

**Comment by akashatharv** [comment]
I updated both of them and now I am not getting any errors or warnings and the launch file is running all the nodes reliably for now. Thank you for your help!!

**Comment by MartyG-RealSense** [comment]
I'm very pleased that the recommendation worked for you - thanks so much for the update!
