### ISSUE TITLE
Question: how to launch `realsense-viewer` with `ros-kinetic-librealsense2` library installed using apt

### ISSUE THREAD

**Issue by hanzheteng** [realsenseai/realsense-ros#1309]
My current configuration: 
1. sudo apt install ros-kinetic-librealsense2     (version 2.36.0, [ros wiki here](http://wiki.ros.org/librealsense2))
2. git clone current 2.2.15 version of realsense-ros package and dependencies (e.g., ddynamic reconfiguration) and catkin_make in my own workspace (because I have to customize some roslaunch files). 

Question: I am not able to run `realsense-viewer` in the terminal. It seems like if I install librealsense2 using apt, the `realsense-viewer` is not installed system-wide. Do I have to install librealsense2 from source in order to use `realsense-viewer`?

**Comment by doronhi** [comment]
Yes. realsense-viewer is part of the package librealsense2-utils. It is not part of ros-kinetic-librealsense2.

**Comment by hanzheteng** [comment]
Thanks for the info. Closing this issue.
