### ISSUE TITLE
is 2.2.15 release added to ROS melodic binaries ? , when I do binary install of realsense_ros , it gives me 2.2.14 release

### ISSUE THREAD

**Issue by jediofgever** [realsenseai/realsense-ros#1311]

**Comment by doronhi** [comment]
A new distributions of ROS packages comes out every now and then.
version 2.2.15 was merged to rosdistro, see [PR#25786](https://github.com/ros/rosdistro/pull/25786).
You can watch for updates in the [ros-distro page](https://discourse.ros.org/tag/release)

**Comment by RealSenseSupport** [comment]
@jediofgever The binary should be released already. Did you get this through? Looking forward to your update.

**Comment by jediofgever** [comment]
@RealSenseSupport yes I pulled `2.2.15` this week so this issue can be closed, Thanks
