### ISSUE TITLE
d435i's left and right camera topics are not available 

### ISSUE THREAD

**Issue by arjunskumar** [realsenseai/realsense-ros#1316]
Below listed ROS Topics are not available with the latest release,
RealSense ROS v2.2.15
Built with LibRealSense v2.36.0

The same topics were available with the RealSense ROS v2.2.11

/camera/infra1/image_rect_raw
/camera/infra2/image_rect_raw

what's wrong with latest release?

My launch file is roslaunch realsense2_camera rs_camera.launch

**Comment by doronhi** [comment]
infra1 and infra2 streams are disabled by default since version 2.2.15. There is a comment in the release notes but perhaps it’s not emphasized enough.
Try setting “enable_infra1:=true" and "enable_infra2:=true”.

**Comment by arjunskumar** [comment]
@doronhi Thanks for the clarification. It worked
