### ISSUE TITLE
Detect if the realsense node has died or could not start

### ISSUE THREAD

**Issue by stevemartinov** [realsenseai/realsense-ros#1323]
Hi, I am using T265 camera and sometimes, the USB falls off and I cannot start my node. I have to replug the USB device and then the node starts again.
Is it possible to check the health status of the node so in the event that the node did not start, I can program to be replugged?

**Comment by doronhi** [comment]
I need some clarifications, if you please.
1. Usually, when you start the node and the device is not plugged in the node starts and prints a message every couple of seconds that the device is not found. When you then plug the device in, it creates an event and the node connects to the device automatically. So, why do you need to start the node again?
2. Sorry, I didn't understand the meaning behind "I can program to be replugged".

**Comment by RealSenseSupport** [comment]
Hi,

Will you be needing further help with this? If we don’t hear from you in 7 days, this issue will be closed.

Thanks
