### ISSUE TITLE
Toggling post-processing filters during runtime

### ISSUE THREAD

**Issue by rntatsuya** [realsenseai/realsense-ros#1325]
I am currently developing with a D415 on Ubuntu 18.04, and I was wondering if it is possible to toggle filters, such as temporal and hole_filling, on and off after running the `rs_camera` node. 

Is there a way to do this via dynamic reconfigure or would I have to relaunch the node every time I want to toggle the filters?

**Comment by MartyG-RealSense** [comment]
Hi @rntatsuya   Once a filter has been defined in the roslaunch statement, you should be able to configure its specific settings with dynamic reconfigure during runtime by using a **rosrun** instruction.

The link below has an example of scripting for doing so with the **Decimation** filter:

https://github.com/IntelRealSense/realsense-ros/issues/583

I don't know if they can be toggled on and off, though potentially you could set the Filter Magnitude to zero and achieve a similar effect to it being inactive.

**Comment by MartyG-RealSense** [comment]
Hi @rntatsuya   Do you still require assistance with this case, please?   Thanks!

**Comment by rntatsuya** [comment]
Hi @MartyG-RealSense 
I reached the conclusion that it is not possible to toggle the post-processing filters on/off with dynamic reconfigure, so what I ended up doing was to use the Python roslaunch API to start the camera nodes with/without filters every time I need to toggle the filters.

**Comment by MartyG-RealSense** [comment]
Hi @rntatsuya  Thanks for the update!
