### ISSUE TITLE
How to use realsense ros with networking

### ISSUE THREAD

**Issue by andaks** [realsenseai/realsense-ros#1331]
Please advice how to modify code to support realsense network camera?

https://dev.intelrealsense.com/docs/open-source-ethernet-networking-for-intel-realsense-depth-cameras

**Comment by MartyG-RealSense** [comment]
Hi @andaks   When the open-source ethernet networking white-paper mentions ROS, it has the number [10] beside it that refers to a guide listed in the references at the bottom of the paper for using 3 cameras across 2 computers:

https://github.com/IntelRealSense/realsense-ros/wiki/showcase-of-using-3-cameras-in-2-machines

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
