### ISSUE TITLE
Can I run realsense-ros on Windows Linux Subsystem Ubuntu 18.04?

### ISSUE THREAD

**Issue by cdor8** [realsenseai/realsense-ros#1339]
Hi,
I would like to know if I can run realsense-ros on WLS Ubuntu 18.04, I followed the instructions, but when I run realsense-viewer nothing happens.
Thank you.

**Comment by MartyG-RealSense** [comment]
Hi @cdor8  **realsense-viewer** is not a RealSense ROS program, it is a librealsense SDK program.  RealSense ROS is a ROS compatibility 'wrapper' for librealsense.

The RealSense Viewer program does not use ROS, and changing options in it does not affect the RealSense camera's behavior in ROS at all.

********************

Intel's guide to installing ROS Melodic on Windows Subsystem For Linux (WSL) states that as WSL is based on Ubuntu, the normal Ubuntu installation process for ROS can be used.

https://software.intel.com/content/www/us/en/develop/blogs/working-with-recorded-camera-data-from-realsense-d400-series.html

If that is the case, you should be able to use the RealSense ROS wrapper's instructions for installing Librealsense, ROS and the RealSense ROS wrapper.  As WSL is based on Ubuntu, use the **Ubuntu** versions of the instructions and not the Windows ones.

https://github.com/IntelRealSense/realsense-ros

**Comment by MartyG-RealSense** [comment]
Hi @cdor8   Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
