### ISSUE TITLE
D435i ros-wrapper unstable and crash base on jetson nano

### ISSUE THREAD

**Issue by sammar80** [realsenseai/realsense-ros#1340]
I appreciate if you could help I am using D435 with with ros and it is not stable on jetson nano I compiled the librealsense2 using CUDA also I followed the recommendation in similar issue
 https://github.com/IntelRealSense/realsense-ros/issues/1171 
and upgraded both the librealsense2 and the realsense-ros wrapper and still facing the same problem 

Ubuntu 18.04
ROS distro Melodic
librealsense2 ver 2.38.1.2169
realsense ros ver 2.2.16

**Comment by MartyG-RealSense** [comment]
Hi @sammar80   The librealsense version used should ideally be closely matched with the version recommended for a particular version of the ROS wrapper.  The recommended librealsense SDK version for wrapper 2.2.16 is **2.37.0**.  So results from using 2.38.1.2169 with the 2.2.16 ROS wrapper cannot be guaranteed.

Could you provide further details please, and a roslaunch log if possible, to help us to better understand the instability that you are experiencing with your Jetson Nano?   Thanks!

**Comment by sammar80** [comment]
Thank you @MartyG-RealSense  for your fast response I reinstalled the librealsense and realsense-ros wrapper versions as you mentioned 
I am still getting error please find attached ros logs 
[realsense-ros-logs.txt](https://github.com/IntelRealSense/realsense-ros/files/5099052/realsense-ros-logs.txt)

and this my launch file 
Note I am using depth images and pointcloud 
<launch>
  <arg name="serial_no"           default=""/>
  <arg name="usb_port_id"         default=""/>
  <arg name="device_type"         default=""/>
  <arg name="json_file_path"      default=""/>
  <arg name="camera"              default="camera"/>
  <arg name="tf_prefix"           default="$(arg camera)"/>
  <arg name="external_manager"    default="false"/>
  <arg name="manager"             default="realsense2_camera_manager"/>

  <arg name="fisheye_width"       default="640"/>
  <arg name="fisheye_height"      default="480"/>
  <arg name="enable_fisheye"      default="false"/>

  <arg name="depth_width"         default="640"/>
  <arg name="depth_height"        default="480"/>
  <arg name="enable_depth"        default="true"/>

  <arg name="infra_width"        default="640"/>
  <arg name="infra_height"       default="480"/>
  <arg name="enable_infra"        default="false"/>
  <arg name="enable_infra1"       default="false"/>
  <arg name="enable_infra2"       default="false"/>

  <arg name="color_width"         default="640"/>
  <arg name="color_height"        default="480"/>
  <arg name="enable_color"        default="true"/>

  <arg name="fisheye_fps"         default="15"/>
  <arg name="depth_fps"           default="15"/>
  <arg name="infra_fps"           default="15"/>
  <arg name="color_fps"           default="15"/>
  <arg name="gyro_fps"            default="50"/>
  <arg name="accel_fps"           default="50"/>
  <arg name="enable_gyro"         default="false"/>
  <arg name="enable_accel"        default="false"/>

  <arg name="enable_pointcloud"         default="true"/>
  <arg name="pointcloud_texture_stream" default="RS2_STREAM_COLOR"/>
  <arg name="pointcloud_texture_index"  default="0"/>

  <arg name="enable_sync"               default="false"/>
  <arg name="align_depth"               default="false"/>

  <arg name="publish_tf"                default="false"/>
  <arg name="tf_publish_rate"           default="0"/>

  <arg name="filters"                   default=""/>
  <arg name="clip_distance"             default="-2"/>
  <arg name="linear_accel_cov"          default="0.01"/>
  <arg name="initial_reset"             default="false"/>
  <arg name="unite_imu_method"          default=""/>
  <arg name="topic_odom_in"             default="odom_in"/>
  <arg name="calib_odom_file"           default=""/>
  <arg name="publish_odom_tf"           default="false"/>
  <arg name="allow_no_texture_points"   default="false"/>

  <group ns="$(arg camera)">
    <include file="$(find realsense2_camera)/launch/includes/nodelet.launch.xml">
      <arg name="tf_prefix"                value="$(arg tf_prefix)"/>
      <arg name="external_manager"         value="$(arg external_manager)"/>
      <arg name="manager"                  value="$(arg manager)"/>
      <arg name="serial_no"                value="$(arg serial_no)"/>
      <arg name="usb_port_id"              value="$(arg usb_port_id)"/>
      <arg name="device_type"              value="$(arg device_type)"/>
      <arg name="json_file_path"           value="$(arg json_file_path)"/>

      <arg name="enable_pointcloud"        value="$(arg enable_pointcloud)"/>
      <arg name="pointcloud_texture_stream" value="$(arg pointcloud_texture_stream)"/>
      <arg name="pointcloud_texture_index"  value="$(arg pointcloud_texture_index)"/>
      <arg name="enable_sync"              value="$(arg enable_sync)"/>
      <arg name="align_depth"              value="$(arg align_depth)"/>

      <arg name="fisheye_width"            value="$(arg fisheye_width)"/>
      <arg name="fisheye_height"           value="$(arg fisheye_height)"/>
      <arg name="enable_fisheye"           value="$(arg enable_fisheye)"/>

      <arg name="depth_width"              value="$(arg depth_width)"/>
      <arg name="depth_height"             value="$(arg depth_height)"/>
      <arg name="enable_depth"             value="$(arg enable_depth)"/>

      <arg name="color_width"              value="$(arg color_width)"/>
      <arg name="color_height"             value="$(arg color_height)"/>
      <arg name="enable_color"             value="$(arg enable_color)"/>

      <arg name="infra_width"              value="$(arg infra_width)"/>
      <arg name="infra_height"             value="$(arg infra_height)"/>
      <arg name="enable_infra"            value="$(arg enable_infra)"/>
      <arg name="enable_infra1"            value="$(arg enable_infra1)"/>
      <arg name="enable_infra2"            value="$(arg enable_infra2)"/>

      <arg name="fisheye_fps"              value="$(arg fisheye_fps)"/>
      <arg name="depth_fps"                value="$(arg depth_fps)"/>
      <arg name="infra_fps"                value="$(arg infra_fps)"/>
      <arg name="color_fps"                value="$(arg color_fps)"/>
      <arg name="gyro_fps"                 value="$(arg gyro_fps)"/>
      <arg name="accel_fps"                value="$(arg accel_fps)"/>
      <arg name="enable_gyro"              value="$(arg enable_gyro)"/>
      <arg name="enable_accel"             value="$(arg enable_accel)"/>

      <arg name="publish_tf"               value="$(arg publish_tf)"/>
      <arg name="tf_publish_rate"          value="$(arg tf_publish_rate)"/>

      <arg name="filters"                  value="$(arg filters)"/>
      <arg name="clip_distance"            value="$(arg clip_distance)"/>
      <arg name="linear_accel_cov"         value="$(arg linear_accel_cov)"/>
      <arg name="initial_reset"            value="$(arg initial_reset)"/>
      <arg name="unite_imu_method"         value="$(arg unite_imu_method)"/>
      <arg name="topic_odom_in"            value="$(arg topic_odom_in)"/>
      <arg name="calib_odom_file"          value="$(arg calib_odom_file)"/>
      <arg name="publish_odom_tf"          value="$(arg publish_odom_tf)"/>
      <arg name="allow_no_texture_points"  value="$(arg allow_no_texture_points)"/>
    </include>
  </group>
</launch>

**Comment by MartyG-RealSense** [comment]
I see in your log that you are experiencing continuous **control_transfer returned** warnings.  This indicates that there is a serious communication problem with the device.

Since wrapper version **2.2.15**, infra is set to False by default.  So if you need the infra streams then you should set them to True in your roslaunch statement.

Are you able to visualize the streams in RViz despite the continuous warnings?  If you can, this would indicate that they are being published correctly.

**Comment by sammar80** [comment]
Actually once I got these errors the images stop showing in rviz  and for the infra I leave it false to minimize the load on the program also sometimes when I run the lunch file the Nvidia shutdown

**Comment by MartyG-RealSense** [comment]
If you are using your own custom launch file, do you have the same problems with errors and no images in RViz if you generate a point cloud with the ROS wrapper's RGBD point cloud example that uses this launch statement:

**roslaunch realsense2_camera rs_camera.launch filters:=pointcloud**

https://github.com/IntelRealSense/realsense-ros#rgbd-point-cloud

**Comment by sammar80** [comment]
Thank you I will check the link and get back to you

**Comment by sammar80** [comment]
I tried the configurations from the link you sent but I am still facing the same errors please find the new ros logs
[realsense-ros-logs-1.txt](https://github.com/IntelRealSense/realsense-ros/files/5103735/realsense-ros-logs-1.txt)

**Comment by MartyG-RealSense** [comment]
Thank you very much for your tests.  Do you experience any problems with using the camera with librealsense programs such as the RealSense Viewer?  Or are the problems only in the ROS wrapper?

**Comment by sammar80** [comment]
It gives the same errors on realsense-viewer you check the depth images using the High accuracy presets 2D and 3D
![Screenshot at 2020-08-20 13-10-06](https://user-images.githubusercontent.com/36697148/90804480-cf477900-e309-11ea-90a5-33f593bdd897.png)
![Screenshot at 2020-08-20 13-16-44](https://user-images.githubusercontent.com/36697148/90804484-d1113c80-e309-11ea-8dd0-d45e276e4fa0.png)
[realsense-viewer logs.txt](https://github.com/IntelRealSense/realsense-ros/files/5104503/realsense-viewer.logs.txt)

**Comment by MartyG-RealSense** [comment]
I observe in the lower of the two kindly provided images above that there is an error about **multiple udev rules** having been installed (in the red box with white text in the top corner).  This can be a cause of problems and may indicate that more than one librealsense installation has been performed using both the Debian package installation method and the manual installation method.

https://github.com/IntelRealSense/librealsense/issues/6153

If you find udev rules at these two locations:

/lib/udev/rules.d/60-librealsense2-udev-rules.rules
/etc/udev/rules.d/99-realsense-libusb.rules

then it is recommended that **/etc/udev/rules.d/99-realsense-libusb.rules** is deleted, as deleting the other one can break the integrity of Debian packages.

**Comment by sammar80** [comment]
I removed the rules file as per your recommendation and I am still getting the same warring in realsesne-viewer logs also please check the depth image I have and advise if there is anyway to enhance the presets 
 
[realsense-viewer logs-2.txt](https://github.com/IntelRealSense/realsense-ros/files/5109620/realsense-viewer.logs-2.txt)
![Screenshot at 2020-08-21 11-21-33](https://user-images.githubusercontent.com/36697148/90907610-b6e76500-e3c2-11ea-9f84-01f4145b0846.png)

**Comment by MartyG-RealSense** [comment]
Eliminating a multiple udev warning is always worth doing, so it is a positive step in terms of helping to ensure overall stability of librealsense.

Have you tried reducing FPS in the Viewer further please (to 6 FPS) or increasing (to 30 FPS) and seeing if the warnings still occur?

You will likely get a much better image if you enable **Hole Filling Filter** in the Post Processing options of the Viewer.  Also try turning off **Spatial Filter**, as it can take a lot of time to process without the guarantee of making a significant difference.

**Comment by sammar80** [comment]
I am using 15 FPS because I got errors when I used 30FPS
and I don't use the spatial filters

**Comment by MartyG-RealSense** [comment]
Adding **initial_reset:=true** to the roslaunch instruction can also sometimes add improvement if you are not using it already.

May I confrm that you have set the FPS to 15 in your launch file args, as I do not see it in the launch file text that you kindly provided above.

**Comment by sammar80** [comment]
yes I am using 15 FPS . Sorry for that the comment is not taking the full file  
[rs_camera.txt](https://github.com/IntelRealSense/realsense-ros/files/5110397/rs_camera.txt)

**Comment by MartyG-RealSense** [comment]
Thanks very much for the log.  I see in the log that initial_reset is set to False.  Do you get any improvement if it is set to True so that the camera resets at the start of the launch process?

**Comment by sammar80** [comment]
Thank you I will try to set it to true and get back to you

**Comment by MartyG-RealSense** [comment]
Hi @sammar80   Do you have an update on your case for us please?   Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
