### ISSUE TITLE
Distance calculation

### ISSUE THREAD

**Issue by Rakesh-John** [realsenseai/realsense-ros#1341]
How can the distance to the detected object can be obtained as I have subscribed to the rostopic for rgb and depth image.Is there anything similar to depthframe.get_distance when using ros?I know the centre of the detection x&y in 2D from which how to find the depth(distance to the object)could you share some insights using "python" coding.
--

**Comment by MartyG-RealSense** [comment]
Hi @rakeshjohn123   An approach that I have typically seen is to get the 16-bit distance value (uint16) in mm from a depth topic - for example, **camera/depth/image_rect_raw** - and convert it to meters using **cv_bridge**.  A long discussion in the link below talks about the subject in terms of Python.

https://github.com/IntelRealSense/realsense-ros/issues/714

Within that discussion, a RealSense user posted their finished Python script on a comment as a text file.

https://github.com/IntelRealSense/realsense-ros/issues/714#issuecomment-561036465

**Comment by Rakesh-John** [comment]
The code mentioned in my_depth_subscriber.txt is converting into array and obtaining the depth. How can this be modified to obtain the distance to a particular pixel in the image with known x & y coordinates.

depth_image = bridge.imgmsg_to_cv2(ros_image, "passthrough")
        depth_array = np.array(depth_image, dtype=np.float32)
        center_idx = np.array(depth_array.shape) / 2
        print ('center depth:', depth_array[center_idx[0], center_idx[1]])
This gives the distance to the centre of the image. However how to obtain the distance of any other pixel.....

Instead I did this:
depth_image = bridge.imgmsg_to_cv2(ros_image, "passthrough")
        depth_array = np.array(depth_image, dtype=np.float32)
        print 'center depth:', depth_array[[cy], [cx]]

I can see the output. except for an error when there is no value obtained for cx, cy.... Is there any other alternative?

**Comment by MartyG-RealSense** [comment]
Sincere apologies that you did not receive a further comment from me on this case.   Do you still require assistance with it, please?

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
