### ISSUE TITLE
Calculation of calibration matrix

### ISSUE THREAD

**Issue by UditSinghParihar** [realsenseai/realsense-ros#1344]
Hello Sir,

1. I would like to know how the camera calibration matrix `K` is calculated which is being published in `/camera/color/camera_info` topic.   
2. I am using this roslaunch command: `roslaunch realsense2_camera rs_camera.launch align_depth:=true`.    
3. Are the camera parameters in that topic produced by the firmware or is it being calculated and calibrated online?  
4. And if it is produced by firmware then is it accurate enough or should we do our own calibration?  

Thanks

**Comment by MartyG-RealSense** [comment]
Hi @UditSinghParihar   I hope that the link below, which provides a formula for 'k', will be helpful to you.

https://github.com/IntelRealSense/realsense-ros/issues/709#issuecomment-479950687

The RealSense ROS wrapper's documentation says about align_depth: "If set to true, will publish additional topics with the all the images aligned to the depth image.  The topics are of the form: /camera/aligned_depth_to_color/image_raw etc".

https://github.com/IntelRealSense/realsense-ros/tree/development#aligned-depth-frames

I extensively researched your second question about how alignment is generated in the RealSense ROS wrapper but but not find a good reference, so I will refer that question to the wrapper developer @doronhi

**Comment by doronhi** [comment]
The parameters set into matrix K are the intrinsics parameters, derived directly from the firmware.
They are calibrated at the factory. As for them being accurate enough for you or to the possibility of calibration them yourself, I can refer you to [librealsense issue #2329](https://github.com/IntelRealSense/librealsense/issues/2329)

**Comment by UditSinghParihar** [comment]
Thanks for mentioning the link for circumstances when I need to calibrate and the calibration toolbox.
