### ISSUE TITLE
Timeline for Noetic support?

### ISSUE THREAD

**Issue by ben-green-kerro** [realsenseai/realsense-ros#1345]
Hi all, could anyone let me know when we are expecting release for ROS Noetic on 20.04? I tried building the ROS package from source and installing Bionic librealsense, but the closest I got was buggy pointclouds in RVIZ. All works fine on 18.04 obviously. Thanks all!

**Comment by MartyG-RealSense** [comment]
Hi @ben-green-kerro   The lack of official support for 20.04 in librealsense at the time of writing this complicates matters regarding to RealSense ROS wrapper support for 20.04.  An example is how the first ROS wrapper release for RO2 will be based on 18.04.

https://github.com/IntelRealSense/realsense-ros/issues/1270#issuecomment-655407233

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received and no further timeline information available to provide at the time of writing this.
