### ISSUE TITLE
Is that possible to run it on Ubuntu 20.04 at the moment?

### ISSUE THREAD

**Issue by QuanWuNCL** [realsenseai/realsense-ros#1347]
Hi

Can i run realsense-ros on Ubuntu 20.04 Noetic?

thank you

**Comment by MartyG-RealSense** [comment]
Hi @MiaoBaBaZuiShuai   I would refer you to the discussion in the link below.  Thank you.

https://github.com/IntelRealSense/realsense-ros/issues/1345

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
