### ISSUE TITLE
Realsense ros don't run with realsense LiDar L515

### ISSUE THREAD

**Issue by duclinhfetel** [realsenseai/realsense-ros#1348]
Hi everyone,

Im using realsense L515 for my project. I use realsense-ros package to run with realsense L515 is got the error below:
![image](https://user-images.githubusercontent.com/20751859/91119269-fc56ab80-e6bc-11ea-9097-9997c627237a.png)

Could anyone help me this problem?

```
cmd: roslaunch realsense2_camera rs_camera.launch align_depth:=true
CPU: Intel core i7 x64
OS: Ubuntu 18.04 
ROS: melodic
librealsense version: v2.38.1
realsense-ros: 2.2.16
```

**Comment by diogo-sr** [comment]
I have the exact same problem

```
CPU: Intel® Core™ i7-8565U CPU @ 1.80GHz × 8 
OS: Ubuntu 16.04 
ROS: kinetic
librealsense version: v2.38.1
realsense-ros: 2.2.16
```

However, I have no problems with viewing the depth on the `realsense-viewer`

**Comment by RealSenseSupport** [comment]
Hi,

We are able to reproduce this and are investigating. Do you see any *functional* issues per chance? The error is indeed being output but all streams appear to be operating as expected. Are you also experiencing this?

Thanks for catching.

**Comment by diogo-sr** [comment]
Hi,

I do not have any information being published on the depth topics.

**Comment by doronhi** [comment]
Found the error in librealsense. When requesting "depth" callback also receives "infrared" frames.
While waiting for a fix in librealsense, it can be bypassed, for now, if infrared is actually enabled.
Use the following flag:
`enable_infra=true`

or in the command line: `roslaunch realsense2_camera rs_camera.launch enable_infra:=true`

**Comment by uncleleer** [comment]
> Hi,
> 
> We are able to reproduce this and are investigating. Do you see any _functional_ issues per chance? The error is indeed being output but all streams appear to be operating as expected. Are you also experiencing this?
> 
> Thanks for catching.

hello, I have met the same problem while launching rs_rgbd.launch, I have found that neither _hardware align_ nor _software align_ works, rostopic _/camera/depth_registered/points_ has no data. And this is one of the _functional_ problem I think.

**Comment by doronhi** [comment]
> > Hi,
> > We are able to reproduce this and are investigating. Do you see any _functional_ issues per chance? The error is indeed being output but all streams appear to be operating as expected. Are you also experiencing this?
> > Thanks for catching.
> 
> hello, I have met the same problem while launching rs_rgbd.launch, I have found that neither _hardware align_ nor _software align_ works, rostopic _/camera/depth_registered/points_ has no data. And this is one of the _functional_ problem I think.

Did you try it out using my suggestion: add the flag `enable_infra:=true`

**Comment by bae9875** [comment]
I found that setting filters argument to true fixes this issue.

roslaunch rs_camera.launch filters:=true

**Comment by jinbae9875** [comment]
I have found that setting filters argument to pointcloud fixes this issue. It's going to output the same erroe but aligned depth to color topic will start publishing.

roslaunch rs_camera.launch filters:=pointcloud

**Comment by Si-lhouette** [comment]
add the flag enable_infra:=true didn't work for me.
I used:
    `roslaunch realsense2_camera rs_rgbd.launch enable_infra:=true`

It also has error:
    `An error has occurred during frame callback: map::at`

My Realsense SDK version is 2.39.0, and realsense-ros version is 2.2.17

I use Ubuntu16.04 with kinetic.

Appreciate any help.

**Comment by doronhi** [comment]
I thought the problem was fixed in librealsense2 version 2.39.0 but I could be mistaken, I didn't check yet.
However, my example used "rs_camera.launch". rs_rgbd.lauch  is missing the `enable_infra` option. You could add it to the file (in 2 places - copy from the rs_camera.launch file)

**Comment by Si-lhouette** [comment]
Thanks！！
I fixed it by adding the following in 'rs_rgbd.launch':
Add above `<arg name="enable_infra1"       default="false"/>`:
`<arg name="enable_infra"       default="true"/>`

Add above `<arg name="enable_infra1"            value="$(arg enable_infra1)"/>`:
`<arg name="enable_infra"            value="$(arg enable_infra)"/>`

**Comment by RealSenseSupport** [comment]
Glad that solved the issue @Si-lhouette.

@duclinhfetel ...will you be needing further help with this?

Thanks
