### ISSUE TITLE
ERROR after running command: roslaunch realsense2_camera rs_camera.launch

### ISSUE THREAD

**Issue by ChunYe173** [realsenseai/realsense-ros#1349]
Hi,

I got an error after running the command _roslaunch realsense2_camera rs_camera.launch_. I am using the Intel Realsense D435 on Ubuntu 16.04 ROS Kinetic. Attach is the picture of the error. Please kindly assisst. Thank you.

![Screenshot from 2020-08-25 17-59-45](https://user-images.githubusercontent.com/66294422/91161499-67c06d80-e6fd-11ea-9ad0-8961202f373a.png)

**Comment by MartyG-RealSense** [comment]
Hi @ChunYe173   Which version of librealsense and which version of the RealSense ROS wrapper are you using, please?

**Comment by ChunYe173** [comment]
Hi @MartyG-RealSense , I have attached a few pictures of the version of librealsense and RealSense ROS Wrapper

![Screenshot from 2020-08-26 10-52-59](https://user-images.githubusercontent.com/66294422/91250231-1494fc00-e78b-11ea-9b01-4eb23d5a2bd6.png)

![Screenshot from 2020-08-26 10-56-48](https://user-images.githubusercontent.com/66294422/91250236-165ebf80-e78b-11ea-9a63-cd4f657643ff.png)

**Comment by MartyG-RealSense** [comment]
It looks as though you are using librealsense SDK version **2.36.0** and RealSense ROS version **2.2.16**.  If you have 2.36.0 installed, the recommended ROS wrapper version to match with it is **2.2.15**.  This is because 2.2.16 is targeted at SDK version 2.37.0.

**Comment by ChunYe173** [comment]
Thanks for the solution. Installing ROS wrapper of version 2.2.15 solve my problem. For now, I can run the command _roslaunch realsense2_camera rs_camera.launch_ successfully as shown in the attach picture. I am trying to disable auto_exposure_priority controls through the RGB section of the controls in the dynamic_reconfigure interface to publish frame rate higher than 30 fps. The dynamic_reconfigure interface will shut down automatically once I click on the rgb_camera section (shown in the picture below) and the terminal running command _rosrun rqt_reconfigure rqt_reconfigure_ will return the error as shown in the picture below. Please kindly assists. Thank you.

![Screenshot from 2020-08-27 11-16-35](https://user-images.githubusercontent.com/66294422/91380914-b898a900-e858-11ea-9664-38da4ccd2224.png)

![WhatsApp Image 2020-08-27 at 11 22 28 AM](https://user-images.githubusercontent.com/66294422/91380962-cd753c80-e858-11ea-92b1-5fd46ddcad62.jpeg)

![Screenshot from 2020-08-27 11-16-51](https://user-images.githubusercontent.com/66294422/91380970-d2d28700-e858-11ea-83e7-96e892c4e2f4.png)

**Comment by MartyG-RealSense** [comment]
Dynamic Reconfigure options can also be set with a **rosparam** instruction in the launch file if you only need to set the option once at start-up.  In the link below, Doronhi the RealSense ROS wrapper developer highlights an example of changing RGB options on the 400 Series cameras.  

https://github.com/IntelRealSense/realsense-ros/issues/1354#issuecomment-681126057

You should be able to set auto-exposure priority status by substituting the dynamic-reconfigure parameter name for auto-exposure priority into the rosparam code provided in the link.  

I believe that the parameter name for RGB auto-exposure priority is **rs435_color_auto_exposure_priority**

So the launch file rosparam code would likely look like this:

`<rosparam>`
`  /camera/rgb_camera/rs435_color_auto_exposure_priority: false`
`</rosparam>`

**Comment by ChunYe173** [comment]
Thanks @MartyG-RealSense for the solution. It is very helpful. Thanks for your time. I will close this issue

**Comment by MartyG-RealSense** [comment]
I'm pleased it was helpful to you - thanks for the update!
