### ISSUE TITLE
F200 Depth Image with multiple images

### ISSUE THREAD

**Issue by rarrais** [realsenseai/realsense-ros#135]
### System Configuration

| Version | Your Configuration |
| :-- | :-- |
| Operating System | Ubuntu 14.04.5 LTS |
| Kernel | 4.4.0-42-generic |
| Backend | video4linux |
| ROS | indigo |
| ROS RealSense | 1.4.0 |
| librealsense | 0.9.1 |
| Camera Type-Firmware | 2.60.0.0 |

---
### Expected Behavior

We were expecting a depth image that were not multiplied as shown in the "Actual Behaviour". Also, the PointCloud2 points do not appear correctly. 

We are using the default configuration and the default launch file. We also tried to do some testing with turning on the point cloud generation and the PointCloud2 generated point cloud did not appeared right also. We suspect that this is related with the odd depth image we are observing. 

Can someone give us some input on what we might be doing wrong?
### Actual Behavior

Check the screenshots 

![f200](https://cloud.githubusercontent.com/assets/2287246/19514860/100d953c-95ed-11e6-9af8-b3e97335d8e9.png)
### Steps to Reproduce

After installation, 

`roscore`

`roslaunch realsense_camera f200_nodelet_default.launch`

`rviz`

**Comment by reaganlo** [comment]
@rarrais We were not able to reproduce this issue. One reason could be that "librealsense" and its corresponding udev rules and patches were not installed/applied correctly. Could you please try installing the latest librealsense and realsense_camera packages by following the instructions at http://wiki.ros.org/realsense_camera

Also, we recommend not to use the native pointcloud of the nodelet. Instead, generate the pointcloud using **rgbd_launch** package. I am attaching a sample launch file for the F200 camera that generates an rgbd pointcloud. [f200_nodelet_rgbd.launch.txt](https://github.com/intel-ros/realsense/files/559485/f200_nodelet_rgbd.launch.txt)

After launching the attached file:
- For depth image, subscribe to **/camera/depth/image_raw**
- For color image, subscribe to **/camera/rgb/image_raw**
- For rgbd pointcloud, subscribe to **/camera/depth_registered/points**

Also attaching a screenshot of how the images typically look like in rviz
![issue135](https://cloud.githubusercontent.com/assets/12738189/19823511/c175dffa-9d1d-11e6-8a75-821302db2bf6.png)

**Comment by rarrais** [comment]
Dear @reaganlo ,

We managed to configure the camera following your advice. The problem was indeed related with a bad installation of "librealsense". Our point cloud in RVIz looks good now!

Thank you very much for your assistance. 

(You can close the issue)

Best regards,
Rafael Arrais

**Comment by weili7** [comment]
@rarrais do u mind to share the system configuration for your success build? Having similar problem right now. Thank

**Comment by rarrais** [comment]
@weili7 I apologize, but I do not have this system nor its configuration anymore. The experiment was done back in 2016. Nevertheless, I remember managing to have it working following the suggestion on this thread.
