### ISSUE TITLE
How to set Depth Unit in ROS environment to Minimum 

### ISSUE THREAD

**Issue by sonumathur** [realsenseai/realsense-ros#1360]
In the realsense SDK we can set the depth value under control section. 
**Under the 'Controls' section of the Viewer's side-panel options there is a setting called 'Depth Units' whose values are in millimeters (meters / 1000).**
![image](https://user-images.githubusercontent.com/60248559/91641098-dffd9a80-ea3f-11ea-8c04-96a04292e20b.png)

Can this value be changed in ROS environment .....? How

**Comment by MartyG-RealSense** [comment]
Hi @sonumathur   The depth unit scale cannot be changed in the RealSense ROS wrapper.  Doronhi the wrapper developer explains why in the link below.

https://github.com/IntelRealSense/realsense-ros/issues/277#issuecomment-525676873
