### ISSUE TITLE
Some topics not publishing

### ISSUE THREAD

**Issue by miajl** [realsenseai/realsense-ros#1365]
I am using a D435i and when I run

roslaunch realsense2_camera rs_camera.launch unite_imu_method:=linear_interpolation 

I am missing some of the topics that are supposed to be there. I particularly want /camera/imu, /camera/infra1/image_rect_raw and /camera/infra2/image_rect_raw

I have verified in realsense viewer that each of the IR cameras work but I was unsure how to test that the imu functions.

Here is the result of rostopic list
![image](https://user-images.githubusercontent.com/48295666/92275468-28440f00-eebd-11ea-9967-1eb2c9573b26.png)

How do I get these topics?

**Comment by MartyG-RealSense** [comment]
Hi @miajl  If you are using ROS wrapper **2.2.15** or newer, the infra, fisheye, IMU and pose streams are set to **False** by default.  It is mentioned in the release notes for 2.2.15.  It is understandable if you did not see it though.   Please set the stream types that you need to True in your roslaunch statement or in the launch file.

https://github.com/IntelRealSense/realsense-ros/releases/tag/2.2.15

For example, to enable infra1 and infra2 from the roslaunch statement:

**roslaunch realsense2_camera rs_camera.launch unite_imu_method:=linear_interpolation enable_infra1:=true enable_infra2:=true**

If you are using ROS wrapper version 2.2.15 or newer, do you get the infra topics once they are set to true in the roslaunch statement, please?

**Comment by miajl** [comment]
The above worked to get infra1 and infra2. I needed to add enable_gyro:=true and enable_accel:=true to get camera/imu

**Comment by MartyG-RealSense** [comment]
Thanks very much for the update!
