### ISSUE TITLE
Sub paragraph mistype for 'unite_imu_method' in README.md

### ISSUE THREAD

**Issue by bigbellmercy** [realsenseai/realsense-ros#1367]
In '[README.md](https://github.com/IntelRealSense/realsense-ros/blob/development/README.md)', the two paragraphs for 'linear_interpolation' and 'copy' should be indented under 'unite_imu_method' paragraph because they are options for it.

**Comment by MartyG-RealSense** [comment]
Thanks very much for highlighting that, @bigbellmercy - I will tag the RealSense ROS wrapper developer @doronhi into this discussion to draw attention to your report.

**Comment by bigbellmercy** [comment]
Thanks! Another option ‘none’ may be inserted on that.

**Comment by MartyG-RealSense** [comment]
Tagging a reminder for @doronhi about this documentation-related question.   Thanks!

**Comment by doronhi** [comment]
Thanks for bringing it to my attention and for the reminders. Done.

**Comment by MartyG-RealSense** [comment]
Thanks so much @doronhi   I will close this case now as you are aware of the case and have acted on it.  Thanks again!
