### ISSUE TITLE
t265 + d435i poor performance

### ISSUE THREAD

**Issue by rafa-chao** [realsenseai/realsense-ros#1372]
Environment:
Ubuntu 18.04, kernel 5.4.0-47 generic
Intel Nuc Apollo lake J3455 8GB RAM
Rosdistro: melodic
ros version 1.14.6
realsense ros v2.2.15
librealsense v2.36.0
d435i firmware 05.12.6
t265 firmware 0.2.0.951
-----------------------------------------
Hi All,

I have been working with realsense for the last year, to be honest, 11 months. I began using jetson nano, and I was able to make the system work up to:
librealsense v2.29.0
realsense-ros v2.2.9
ros version 1.14.3

In june, due to the impossibility and complexity to make realsense run in nvidia platform, I decide to move to a NUC intel CPU system, believing that the performance of the realsense cameras were to improve as long as I was going to install newer software and firmware versions.

As you can read at the beginning of this email, in July I updated the software to what is indicated. Now, I will explain you my experience with realsense.

I have built an outdoor 4WD robot, 80cm x 80 cm, 65 kg weight, and 1kW power, with a 2 kW battery, using ROS system.

t265 gets lost pretty easily. It is true I am not using any other sensor to locate the robot in the map, but to be honest, the robot is an outdoor robot, and sometimes, the wheels are spinning "in the air", so I thought encoders were useless for outdoor environments. The speed I am moving the robot is very, very, very low, just to make sure the robot doesn`t get lost. Odometry is not working fine, speed is less than 0.1 m/s

d435i is nearly the same. I am not using the internal IMU of this camera, just the t265. Today, I was astonished....

I took the robot to a "covered car parking", with led light in the roof. I was creating a map using rtabmap, and the camera were registering "black pixels" (which means, obstacles) where there were nothing, and whatsmore, the led roof light was reflecting in the floor, and the camera were registering "soft gray colour" (which means, empty space non registered)....

Actually, when I update intelrealsense software, I compile the source code, trying to improve and to use all the indications I have read in the github.... But there are hundreds... 

Dorodni, can you help me in some way?
- What can I install to help t265 to have a robust odometry system? I cannot install encoders at this point of the project, i need something else.

- Is there any updated guide, instructions, manual or whatever, to be sure that when we install a new realsense source code, it is going to work fine?

Thanks a lot for all your effort, I would like to add any other feedback if you want, but really, I would like to make the cameras work properly.

Best,

**Comment by RealSenseSupport** [comment]
Hi,

Thanks for highlighting this issue. At this time we have moved our focus to our next generation of products and consequentially will not be addressing this T265 issue.

Thanks
