### ISSUE TITLE
Raspberry Pi4B install librealsense-ros error

### ISSUE THREAD

**Issue by dingbaiyin** [realsenseai/realsense-ros#1375]
I encountered an error when installing realsense-ros on the Raspberry Pi 4B, which cannot be resolved at present.
The installation reference link is as follows：
http://wiki.ros.org/ROSberryPi/Installing%20ROS%20Kinetic%20on%20the%20Raspberry%20Pi
Problems encountered when running the 3.22（Resolving Dependencies with rosdep） command
As shown in the picture 1：
![librealsense-ros_error1](https://user-images.githubusercontent.com/40271689/92888040-8fc30700-f447-11ea-883d-bc8db5366d03.png)
Picture 2 is the error report details：
![librealsense-ros_error2](https://user-images.githubusercontent.com/40271689/92888090-994c6f00-f447-11ea-8a6b-fc1932e9a73f.png)
Please provide some suggestions to solve the installation librealsense-ros problem,thank you very much .

**Comment by dingbaiyin** [comment]
There is a problem with librealsense2.38.1, and Intel camera cannot be called normally. It is fine to replace it with librealsense2.36.0. I created a new issue about librealsense-ros and closed the issue。
Thank you very much.

**Comment by MartyG-RealSense** [comment]
Hi @dingbaiyin   The **eleccelerator** guide for installing Librealsense and ROS on Pi 4 and Raspbian Buster lists some of the errors that users of the **ROSberryPi** ROS installation guide might encounter and ways to fix them.

https://eleccelerator.com/wiki/index.php?title=Raspbian_Buster_ROS_RealSense

The guide then provides guidance about installing librealsense and realsense-ros:

**librealsense**
https://eleccelerator.com/wiki/index.php?title=Raspbian_Buster_ROS_RealSense#Installing_librealsense

**realsense-ros**
https://eleccelerator.com/wiki/index.php?title=Raspbian_Buster_ROS_RealSense#Installing_ROS_Package:_realsense-ros

**Comment by MartyG-RealSense** [comment]
Hi @dingbaiyin   Do you require further assistance with this case, please?  Thanks!

**Comment by dingbaiyin** [comment]
No,thanks.

**Comment by MartyG-RealSense** [comment]
@dingbaiyin   Thanks for the update!
