### ISSUE TITLE
Problems of using USB2.0 in d435 and d415 cameras #D400

### ISSUE THREAD

**Issue by Shame-fight** [realsenseai/realsense-ros#1384]
I have a question: can d415 or d435 use USB2.0 on NVIDIA Jetson nano? I need to use the camera to range the detected target, but I only have USB 2.0 interface.Thank everyone for their suggestions and ideas.

**Comment by RealSenseSupport** [comment]
Hi @Shame-fight 

Can you please elaborate on 

> "I only have USB 2.0 interface"

D415,D435 and Jetson Nano support USB 3, and it's not so clear what USB 2.0 interface do you mean.

Thank you!

**Comment by RealSenseSupport** [comment]
@Shame-fight

Do you still need help with this question?

**Comment by RealSenseSupport** [comment]
Hi,

Will you be needing further help with this? If we don’t hear from you in 7 days, this issue will be closed.

Thanks
