### ISSUE TITLE
Issue when trying to catkin_make/ catkin build

### ISSUE THREAD

**Issue by vi-ca** [realsenseai/realsense-ros#1404]
We are following the tutorial to set up the realsense camera for ROS melodic using Ubuntu 18. We initially stumbled at catkin_make clean - where the packages aren't being built - here is the error

CMake Error at /opt/ros/melodic/share/cv_bridge/cmake/cv_bridgeConfig.cmake:113 (message):

 Project 'cv_bridge' specifies '/usr/include/opencv' as an include dir,

 which is not found. It does neither exist as an absolute directory nor in

 '${{prefix}}//usr/include/opencv'. Check the issue tracker

 'https://github.com/ros-perception/vision_opencv/issues' and consider

 creating a ticket if the problem has not been reported yet.

 Call Stack (most recent call first):

 /opt/ros/melodic/share/catkin/cmake/catkinConfig.cmake:76 (find_package)

 realsense-ros/realsense2_camera/CMakeLists.txt:11 (find_package)

we then restarted and attempted using catkin build from an internet suggestion, which left us with an incompatible python version where we ended up changing the python version to suit (2.7 to 3) 
but it still seems to default to python 2 and keeps trying to access the python 2 ros library [error below]

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/62139828/93573291-4724c400-f9da-11ea-9a82-8d02986229a1.png)

this is another overall error we keep having 

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/62139828/93573453-7dfada00-f9da-11ea-864f-d2e9521fc604.png)

please help to troubleshoot all these errors, we aren't sure where to go next

**Comment by MartyG-RealSense** [comment]
Hi @vi-ca   I have not personally seen the CMake Error that you quoted during librealsense cases.  My research into your question indicated that a very similar error has occurred to somebody else using ROS though.  Their solution was to make a small modification to the **cv_bridgeConfig.cmake** file,

https://stackoverflow.com/questions/37274190/how-to-link-opencv-to-ros-indigo-catkin-with-cmake-ubuntu-14-04/37296083#37296083

Although it worked for the ROS user in that case, it was commented that it may not be the **correct** way to handle the problem.  A fresh installation of everything to make sure there are no conflicts with previous installations may be the right way to handle the problem.  I have never heard of this particular problem during a RealSense ROS setup, which indicates that it may certainly be an abnormal situation that a fresh install from the beginning may rectify.
