### ISSUE TITLE
L515 Gap Between Depth and Color Images

### ISSUE THREAD

**Issue by jinbae9875** [realsenseai/realsense-ros#1405]
Hi, below is an experiment I did with L515 and an egg. The edge tracing of the egg is taken from the rgb image corresponding to each of the colorized rgb-aligned depth images.
![image](https://user-images.githubusercontent.com/47039403/93624379-437b4800-f9ae-11ea-9f89-b8d1bd60d847.png)

0
![L0](https://user-images.githubusercontent.com/47039403/93624246-13cc4000-f9ae-11ea-9528-0de2292ec829.png)
1
![L1](https://user-images.githubusercontent.com/47039403/93624247-13cc4000-f9ae-11ea-981a-e49762488d9d.png)
2
![L2](https://user-images.githubusercontent.com/47039403/93624249-13cc4000-f9ae-11ea-9c8a-d7f504333c84.png)
3
![L3](https://user-images.githubusercontent.com/47039403/93624250-1464d680-f9ae-11ea-8c5f-64ae3da881d1.png)
4
![L4](https://user-images.githubusercontent.com/47039403/93624251-1464d680-f9ae-11ea-8bd3-0622ff2c2d3e.png)
5
![L5](https://user-images.githubusercontent.com/47039403/93624252-1464d680-f9ae-11ea-80ae-97a360bfc457.png)
6
![L6](https://user-images.githubusercontent.com/47039403/93624253-1464d680-f9ae-11ea-8a2f-4377cffa46ac.png)
7
![L7](https://user-images.githubusercontent.com/47039403/93624254-1464d680-f9ae-11ea-80fc-d7e4130c0d41.png)
8
![L8](https://user-images.githubusercontent.com/47039403/93624256-14fd6d00-f9ae-11ea-9ff7-6c553a1fe5bc.png)

As you can see, the shots taken at an angle from the camera (the ones not at the center) have a significant lateral gap between the depth image and its equivalent rgb image. I've tried the same experiment using D435 and Kinect but they don't seem to have the same issue. What do you think is causing this issue? Is anyone else experiencing the same problem?

**Comment by RealSenseSupport** [comment]
Hi @jinbae9875 

Is there anyway you can provide the recordings/bag file using the RealSense Viewer of your experiment?  Also provide all streams - IR, Depth, RGB and Confidence in your recording?

*If we don’t hear from you in 7 days, this issue will be closed.

**Comment by zhongxiangzju** [comment]
Hi, I encountered the same issue which is that the depth image is not aligned well with color image after set "align_depth"               
 to "true" in rs_camera.launch. Is it a bug?
