### ISSUE TITLE
organized point cloud from d415

### ISSUE THREAD

**Issue by roboticsai** [realsenseai/realsense-ros#1406]
How can i get the organized point cloud from d415?

**Comment by MartyG-RealSense** [comment]
Hi @roboticsai   Using **rs_rgbd.launch** should provide you with an organized point cloud.

https://github.com/IntelRealSense/realsense-ros/issues/893

**Comment by MartyG-RealSense** [comment]
Hi @roboticsai   Do you still require assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
