### ISSUE TITLE
PointCloud2 ROS with Realsense cannot detect camera output

### ISSUE THREAD

**Issue by vi-ca** [realsenseai/realsense-ros#1416]
Hi,
Please help with this new issue we're having - when we run rosrun rviz rviz and open up the PointCloud2 viewer, we get this issue: 
<img width="698" alt="Screen Shot 2020-09-23 at 5 46 18 pm" src="https://user-images.githubusercontent.com/62139828/93982827-19b68c80-fdc5-11ea-895f-afceb571d4d9.png">

We searched online and came to the verdict that there are missing tf links which can be fixed via this command: rosrun tf static_transform_publisher 0.0 0.0 0.0 0.0 0.0 0.0 map 1 100
which gives us more errors that differ: 
<img width="704" alt="Screen Shot 2020-09-23 at 5 43 30 pm" src="https://user-images.githubusercontent.com/62139828/93983138-86ca2200-fdc5-11ea-8441-12af32fd0069.png">

but when running rosrun tf view_frames this is the output with the static transform command 
<img width="851" alt="Screen Shot 2020-09-23 at 5 45 33 pm" src="https://user-images.githubusercontent.com/62139828/93983228-a19c9680-fdc5-11ea-96f6-983a339fc93b.png">

Please help figure out where we could be having issues, there aren't many of these online from what we've searched. Thank you in advance!

environment: 
ROS Melodic 
Ubuntu 18 
trying to integrate the RealSense D435 using this link (not all of it, but the running bit) https://idorobotics.com/2018/11/02/integrating-the-intel-realsense-d435-with-ros/

**Comment by MartyG-RealSense** [comment]
Hi @vi-ca   Are you able to visualize a pointcloud in RViz with **PointCloud2** if you follow the example in the ROS wrapper documentation please, setting Fixed Frame to **camera_link** instead of 'map'.

https://github.com/IntelRealSense/realsense-ros#point-cloud

**Comment by MartyG-RealSense** [comment]
Hi @vi-ca   Do you still require assistance with this case, please?   Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
