### ISSUE TITLE
Create 2D map

### ISSUE THREAD

**Issue by Tien-203** [realsenseai/realsense-ros#1421]
Hi, I'm beginer. I'm trying to code on jupyter notebook to create a 2D map from data of the Realsense D435i, can you give me some instruction for that?

**Comment by MartyG-RealSense** [comment]
Hi @intel-user   Intel has a Jupyter notebook Python tutorial for using data from a pre-recorded **bag file** of camera data to generate an RGB image and a depth image and then align them.   This may provide the basis for what you want to achieve.

https://github.com/IntelRealSense/librealsense/blob/jupyter/notebooks/distance_to_object.ipynb
