### ISSUE TITLE
WiFi shutdown with Pi4 and T265

### ISSUE THREAD

**Issue by CeccAnd** [realsenseai/realsense-ros#1433]
Hello

I had installed Realsense for ROS to my Raspberry Pi 4. With the camera T265 launched, I saw that WiFi collapsed.

Anyone with the same experience?

Thanks. Regards.

**Comment by RealSenseSupport** [comment]
Hi @CeccAnd 

Is there anything else needed on this thread?  We are not sure why this would happen.

*If we don’t hear from you in 7 days, this issue will be closed.

**Comment by CeccAnd** [comment]
Hello,

I changed Pi4 to more powerful PC. Solved this issue.

Thanks.

Andrea

Il gio 29 ott 2020, 19:13 RealSenseSupport <notifications@github.com> ha
scritto:

**Comment by RealSenseSupport** [comment]
Hi,

Will you be needing further help with this?

*If we don’t hear from you in 7 days, this issue will be closed.*

Thanks
