### ISSUE TITLE
Android Phone//Rasberry Pi

### ISSUE THREAD

**Issue by shuixing85** [realsenseai/realsense-ros#1434]
Hi All,
ordered an L515 and cannot wait to do a first point scan.

Just wondering is there any android phone recommended to work with L515 camera?
I understand that Rasberry pi would be an option, but coding is a little bit far for me, just thinking to download a Dot3D to an android phone and connect to the camera, would be an easy way for me.

any comments will be appreciated,

**Comment by RealSenseSupport** [comment]
Hi,

Will you be needing further help with this? You should be able to use any android device but Dot3D has some recommendations that might be helpful as well:

https://desk.zoho.com/portal/dotproduct/en/kb/articles/recommendedtablets

Thanks

*If we don’t hear from you in 7 days, this issue will be closed.*
