### ISSUE TITLE
D435i ros on Raspberry4B

### ISSUE THREAD

**Issue by HeadReaper-hc** [realsenseai/realsense-ros#1436]
Hello:
My platform is Raspberry4B with Ubuntu Mate 20.04, and ROS version is neotic.
After installing librealsense and realsense-ros, I run the command `roslaunch realsense2_camera rs_camera.launch` and every thing is ok, but when I turn on the `enable_gyro` and `enable_accel`, the following error is displayed, is there any way to solve this problem?

... logging to /home/hc/.ros/log/2e604e3a-0b64-11eb-b152-819f8ba77156/roslaunch-hc-3945.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://hc:35431/

SUMMARY
========

PARAMETERS
 * /camera/realsense2_camera/accel_fps: 250
 * /camera/realsense2_camera/accel_frame_id: camera_accel_frame
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: False
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/allow_no_texture_points: False
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/calib_odom_file: 
 * /camera/realsense2_camera/clip_distance: -2.0
 * /camera/realsense2_camera/color_fps: 30
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: 480
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: 640
 * /camera/realsense2_camera/depth_fps: 30
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: 480
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: 640
 * /camera/realsense2_camera/device_type: 
 * /camera/realsense2_camera/enable_accel: True
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye1: False
 * /camera/realsense2_camera/enable_fisheye2: False
 * /camera/realsense2_camera/enable_fisheye: False
 * /camera/realsense2_camera/enable_gyro: True
 * /camera/realsense2_camera/enable_infra1: False
 * /camera/realsense2_camera/enable_infra2: False
 * /camera/realsense2_camera/enable_infra: False
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_pose: False
 * /camera/realsense2_camera/enable_sync: False
 * /camera/realsense2_camera/filters: 
 * /camera/realsense2_camera/fisheye1_frame_id: camera_fisheye1_f...
 * /camera/realsense2_camera/fisheye1_optical_frame_id: camera_fisheye1_o...
 * /camera/realsense2_camera/fisheye2_frame_id: camera_fisheye2_f...
 * /camera/realsense2_camera/fisheye2_optical_frame_id: camera_fisheye2_o...
 * /camera/realsense2_camera/fisheye_fps: 30
 * /camera/realsense2_camera/fisheye_frame_id: camera_fisheye_frame
 * /camera/realsense2_camera/fisheye_height: 480
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: 640
 * /camera/realsense2_camera/gyro_fps: 400
 * /camera/realsense2_camera/gyro_frame_id: camera_gyro_frame
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/imu_optical_frame_id: camera_imu_optica...
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra_fps: 30
 * /camera/realsense2_camera/infra_height: 480
 * /camera/realsense2_camera/infra_width: 640
 * /camera/realsense2_camera/initial_reset: False
 * /camera/realsense2_camera/json_file_path: 
 * /camera/realsense2_camera/linear_accel_cov: 0.01
 * /camera/realsense2_camera/odom_frame_id: camera_odom_frame
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/pose_frame_id: camera_pose_frame
 * /camera/realsense2_camera/pose_optical_frame_id: camera_pose_optic...
 * /camera/realsense2_camera/publish_odom_tf: True
 * /camera/realsense2_camera/publish_tf: True
 * /camera/realsense2_camera/rosbag_filename: 
 * /camera/realsense2_camera/serial_no: 
 * /camera/realsense2_camera/tf_publish_rate: 0.0
 * /camera/realsense2_camera/topic_odom_in: odom_in
 * /camera/realsense2_camera/unite_imu_method: linear_interpolation
 * /camera/realsense2_camera/usb_port_id: 
 * /rosdistro: noetic
 * /rosversion: 1.15.8

NODES
  /camera/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)

auto-starting new master
process[master]: started with pid [3953]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 2e604e3a-0b64-11eb-b152-819f8ba77156
process[rosout-1]: started with pid [3963]
started core service [/rosout]
process[camera/realsense2_camera_manager-2]: started with pid [3970]
process[camera/realsense2_camera-3]: started with pid [3971]
[ INFO] [1602381050.457308475]: Initializing nodelet with 4 worker threads.
[ INFO] [1602381050.864792345]: RealSense ROS v2.2.17
[ INFO] [1602381050.864939882]: Built with LibRealSense v2.39.0
[ INFO] [1602381050.865008012]: Running with LibRealSense v2.39.0
[ INFO] [1602381050.920647660]:  
[ INFO] [1602381051.011825289]: Device with serial number 841612071794 was found.

[ INFO] [1602381051.012001437]: Device with physical ID /sys/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb2/2-2/2-2:1.0/video4linux/video0 was found.
[ INFO] [1602381051.012077808]: Device with name Intel RealSense D435I was found.
[ INFO] [1602381051.013357882]: Device with port number 2-2 was found.
[ INFO] [1602381051.028202715]: getParameters...
[ INFO] [1602381051.181538289]: setupDevice...
[ INFO] [1602381051.181658863]: JSON file is not provided
[ INFO] [1602381051.181730808]: ROS Node Namespace: camera
[ INFO] [1602381051.181823752]: Device Name: Intel RealSense D435I
[ INFO] [1602381051.181895771]: Device Serial No: 841612071794
[ INFO] [1602381051.181969715]: Device physical port: /sys/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb2/2-2/2-2:1.0/video4linux/video0
[ INFO] [1602381051.182075160]: Device FW version: 05.10.13.00
[ INFO] [1602381051.182131493]: Device Product ID: 0x0B3A
[ INFO] [1602381051.182174123]: Enable PointCloud: Off
[ INFO] [1602381051.182217826]: Align Depth: Off
[ INFO] [1602381051.182274900]: Sync Mode: Off
[ INFO] [1602381051.182547011]: Device Sensors: 
[ INFO] [1602381051.226224252]: Stereo Module was found.
 11/10 09:50:51,228 WARNING [281472711278960] (backend-v4l2.cpp:1267) Pixel format 36315752-1a66-a242-9065-d01814a likely requires patch for fourcc code RW16!
[ INFO] [1602381051.318895678]: RGB Camera was found.
[ INFO] [1602381051.322219771]: Motion Module was found.
[ INFO] [1602381051.322396474]: num_filters: 0
[ INFO] [1602381051.322464234]: Setting Dynamic reconfig parameters.
[ INFO] [1602381051.481434808]: Done Setting Dynamic reconfig parameters.
[ INFO] [1602381051.483208233]: depth stream is enabled - width: 640, height: 480, fps: 30, Format: Z16
[ INFO] [1602381051.484914474]: color stream is enabled - width: 640, height: 480, fps: 30, Format: RGB8
[ INFO] [1602381051.485210733]: setupPublishers...
[ INFO] [1602381051.492490808]: Expected frequency for depth = 30.00000
[ INFO] [1602381051.607569493]: Expected frequency for color = 30.00000
[ INFO] [1602381051.690743585]: Start publisher IMU
[ INFO] [1602381051.694641252]: setupStreams...
[ INFO] [1602381051.697384789]: insert Depth to Stereo Module
[ INFO] [1602381051.697574289]: insert Color to RGB Camera
[ INFO] [1602381051.697701530]: insert Gyro to Motion Module
[ INFO] [1602381051.697783882]: insert Accel to Motion Module
 11/10 09:50:51,775 WARNING [281472711278960] (ds5-motion.cpp:480) IMU Calibration is not available, default intrinsic and extrinsic will be used.
 11/10 09:50:51,799 WARNING [281468949500272] (backend-hid.h:48) write_fs_attribute with gyro_3d-dev1 failed. The specified path /sys/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb2/2-2/2-2:1.5/0003:8086:0B3A.0007/HID-SENSOR-200076.2.auto/iio:device1/trigger/current_trigger is not valid
 _**_11/10 09:50:51,800 ERROR [281472711278960] (types.h:313) Failed to open scan_element /sys/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb2/2-2/2-2:1.5/0003:8086:0B3A.0007/HID-SENSOR-200076.2.auto/iio:device1/scan_elements/in_anglvel_x_en Last Error: Permission denied_**
 **11/10 09:50:51,801 ERROR [281472711278960] (backend-hid.cpp:969) Hid device is busy!**
**[ERROR] [1602381051.802102881]: An exception has been thrown: Failed to open scan_element /sys/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb2/2-2/2-2:1.5/0003:8086:0B3A.0007/HID-SENSOR-200076.2.auto/iio:device1/scan_elements/in_anglvel_x_en Last Error: Permission denied
terminate called after throwing an instance of 'rs2::backend_error'
  what():  Failed to open scan_element /sys/devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb2/2-2/2-2:1.5/0003:8086:0B3A.0007/HID-SENSOR-200076.2.auto/iio:device1/scan_elements/in_anglvel_x_en Last Error: Permission denied**_
[camera/realsense2_camera_manager-2] process has died [pid 3970, exit code -6, cmd /opt/ros/noetic/lib/nodelet/nodelet manager __name:=realsense2_camera_manager __log:=/home/hc/.ros/log/2e604e3a-0b64-11eb-b152-819f8ba77156/camera-realsense2_camera_manager-2.log].
log file: /home/hc/.ros/log/2e604e3a-0b64-11eb-b152-819f8ba77156/camera-realsense2_camera_manager-2*.log
[camera/realsense2_camera-3] process has finished cleanly
log file: /home/hc/.ros/log/2e604e3a-0b64-11eb-b152-819f8ba77156/camera-realsense2_camera-3*.log
^C[rosout-1] killing on exit
[master] killing on exit
^C^C^Cshutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by MartyG-RealSense** [comment]
Hi @HeadReaper-hc   In a past case of the **Failed to open scan_element** error with the RealSense ROS wrapper and D435i when using **roslaunch realsense2_camera rs_camera.launch**, a RealSense team member suggests checking the **udev rules**:

https://github.com/IntelRealSense/librealsense/issues/3242#issuecomment-464775017

**Comment by HeadReaper-hc** [comment]
> Hi @HeadReaper-hc In a past case of the **Failed to open scan_element** error with the RealSense ROS wrapper and D435i when using **roslaunch realsense2_camera rs_camera.launch**, a RealSense team member suggests checking the **udev rules**:
> 
> [IntelRealSense/librealsense#3242 (comment)](https://github.com/IntelRealSense/librealsense/issues/3242#issuecomment-464775017)
Thankyou for your reply, that's really helpful, my problem have been solved.

**Comment by MartyG-RealSense** [comment]
Great news @HeadReaper-hc - thanks for the update!

**Comment by MartyG-RealSense** [comment]
Closing case due to solution achieved and no further comments received.
