### ISSUE TITLE
Depth cutoff adjust in SLAM?

### ISSUE THREAD

**Issue by Andyshen555** [realsenseai/realsense-ros#1442]
It seems there is a depth cutoff when running opensource_tracking.launch. I wonder how we should adjust that, since rviz / rtabmap is using more info to match its visual odom than what we see in the point cloud.

**Comment by MartyG-RealSense** [comment]
Hi @Andyshen555  As a starting point, you could test whether the camera is being permitted to observe depth values as far as possible by setting the launch flag **clip_distance** to a value of 10 (representing the default maximum depth sensing range in meters of the 400 Series cameras).  This flag removes from the depth image all values above a given value in meters.

**Comment by Andyshen555** [comment]
Thank you. I believe problem has been solved.

**Comment by MartyG-RealSense** [comment]
Great to hear @Andyshen555 - thanks very much for the update!
