### ISSUE TITLE
D435i align_depth colorizer

### ISSUE THREAD

**Issue by sunghoya1** [realsenseai/realsense-ros#1452]
i used rs_aligned_depth.launch 
roslaunch realsense2_camera rs_aligned_depth.launch filters:=colorizer

the default depth image works fine, but the aligned depth image does not work in rqt with the following error:
![Screenshot from 2020-10-16 21-44-12](https://user-images.githubusercontent.com/72979882/96260158-9837d000-0ff9-11eb-999c-778761b098d5.png)

I think this is probably conversion problem from U16C1->U8C3 
How to solve it? 
regar

**Comment by MartyG-RealSense** [comment]
Hi @sunghoya1   May I confirm the steps that you are using before you encounter the errors.   Is it like this:

**roslaunch realsense2_camera rs_aligned_depth.launch filters:=colorizer
rosrun rqt_reconfigure rqt_reconfigure**

If this is the method that you are using, do you experience the errors if you do not use **filters:=colorizer** in the roslaunch instruction?

**Comment by sunghoya1** [comment]
@MartyG-RealSense 
If filters:=colorizer is not used, it works fine with a black and white.

**Comment by MartyG-RealSense** [comment]
Let's try a different approach to launch to get an aligned and colorized image, please.

**roslaunch realsense2_camera rs_camera.launch align_depth:=true filters:=colorizer**

**Comment by doronhi** [comment]
This is a bug. Colorizer filter was not applied to aligned images.
Fixed in #1455

**Comment by MartyG-RealSense** [comment]
Thanks very much for the information and the PR @doronhi   👍

**Comment by sunghoya1** [comment]
@doronhi  @MartyG-RealSense 
It works perfectly. Thank you for your hard work
