### ISSUE TITLE
The nodelet_plugins.xml is unnecessary for ROS2

### ISSUE THREAD

**Issue by atinfinity** [realsenseai/realsense-ros#1457]
There is a `nodelet_plugins.xml` in `realsense2_camera` package.  
https://github.com/IntelRealSense/realsense-ros/tree/3.1.1/realsense2_camera

But, I think that `nodelet_plugins.xml` is unnecessary for ROS2.

**Comment by RealSenseSupport** [comment]
@doronhi Could you please check this? Thanks!

**Comment by RealSenseSupport** [comment]
@atinfinity  Thanks for your input! nodelet_plugins.xml is now removed in ROS2 branch andhttps://github.com/IntelRealSense/realsense-ros/tree/eloquent/realsense2_camera 
Can we close this issue? Thanks!

**Comment by atinfinity** [comment]
@RealSenseSupport Thank you for your support!

> Can we close this issue?

Yes. So, I closed this issue.
