### ISSUE TITLE
 Data loss when using rosbag record

### ISSUE THREAD

**Issue by Grandzxw** [realsenseai/realsense-ros#1458]
I want to record the three topic: color/depth/imu, but when I use rosbag record, the data of image will lost, what’s the problem??

**Comment by MartyG-RealSense** [comment]
Hi @Grandzxw   Do you mean that you are missing some frames compared to how many frames you think the bag should contain, please?

Or do you have some streams missing completely from the recording, such as IMU data?

**Comment by Grandzxw** [comment]
> Hi @Grandzxw Do you mean that you are missing some frames compared to how many frames you think the bag should contain, please?
> 
> Or do you have some streams missing completely from the recording, such as IMU data?

YES,  it lost a lot of frames

**Comment by Grandzxw** [comment]
> YES, it lost a lot of frames

 It lost a lot of depth frames

**Comment by MartyG-RealSense** [comment]
Thank you very much for the confirmation.  What frames per second (FPS) speed are you recording at, please?  And are you recording on a PC computer or a board such as a Jetson?

**Comment by Grandzxw** [comment]
> Thank you very much for the confirmation. What frames per second (FPS) speed are you recording at, please? And are you recording on a PC computer or a board such as a Jetson?

I record on PC. And the depth frame is at 6Hz, the color frame is 10Hz. So it lost much data. They were at 30 Hz.

**Comment by Grandzxw** [comment]
> Thank you very much for the confirmation. What frames per second (FPS) speed are you recording at, please? And are you recording on a PC computer or a board such as a Jetson?

Do you know how to solve it？

**Comment by MartyG-RealSense** [comment]
I believe that you are saying that you had color and depth at 30 FPS but they were being slowed a lot to 6 FPS for depth and 10 for color.  Is that correct, please?

If it is and you are also using align_depth = true, please make align_depth false to see whether it corrects your FPS speed.

**Comment by MartyG-RealSense** [comment]
Hi @Grandzxw   Do you still require assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
