### ISSUE TITLE
package needs to depend on "bc"

### ISSUE THREAD

**Issue by tripzero** [realsenseai/realsense-ros#147]
### System Configuration
Please complete Your Configuration detail below. Refer to the BKC at [Configuration](../realsense_camera/README.md#configuration).

| Version               | Your Configuration   |
|:--------------------- |:---------------------|
| Operating System      | ubuntu 16.04 server                |
| Kernel                | 4.4.0-21-generic               |
| ROS                   | kinetic                    |
| ROS RealSense         | 1.6.0                |
| librealsense          | ?.?.?                |
| Camera Type-Firmware  | ?-?.?.?.?            |

---

### Expected Behavior

Package installs and kernel module builds

### Actual Behavior

Building kernel fails because missing "bc" command.  bc is not installed by default on ubuntu-server:

[snip]
  CHK     include/generated/bounds.h
  UPD     include/generated/bounds.h
  CHK     include/generated/timeconst.h
/bin/sh: 1: bc: not found
Kbuild:66: recipe for target 'include/generated/timeconst.h' failed
make[2]: *** [include/generated/timeconst.h] Error 127
Makefile:1003: recipe for target 'prepare0' failed
make[1]: *** [prepare0] Error 2
Makefile:520: recipe for target '__build_one_by_one' failed
make: *** [__build_one_by_one] Error 2

Building module:
cleaning build area....
make KERNELRELEASE=4.4.0-21-generic -C /var/lib/dkms/uvcvideo/1.1.1-3-realsense/build/linux-src M=drivers/media/usb/uvc/....(bad exit status: 2)
ERROR: Cannot create report: [Errno 17] File exists: '/var/crash/ros-kinetic-librealsense.0.crash'
Error! Bad return status for module build on kernel: 4.4.0-21-generic (x86_64)

### Steps to Reproduce

* install ubuntu-server 16.04
* apt install ros-kinetic-realsense-camera

**Comment by mdhorn** [comment]
currently only supporting ubuntu-desktop
