### ISSUE TITLE
Supported ROS Distributions

### ISSUE THREAD

**Issue by ranjitkathiriya** [realsenseai/realsense-ros#1494]
Hey there,

In the real-sense package is also providing support with new ros noetic version as well?

If Yes, Can you please provide some tutorials, documentation that I can look at before starting the integration? I have never integrated real sense with ros so. I am more comfortable with Python.

Thanks,

**Comment by MartyG-RealSense** [comment]
Hi @ranjitkathiriya  A Noetic version of the RealSense ROS wrapper is planned for December 2020 if all goes well, according to **doronhi** the wrapper developer.

https://github.com/IntelRealSense/realsense-ros/issues/1423#issuecomment-702108336

In the meantime, some RealSense ROS users have succeeded in building the wrapper from **source code** on Noetic.  For example, the link below contains an installation guide from somebody who did so on Ubuntu 20.04.

https://answers.ros.org/question/363889/intel-realsens-on-ubuntu-2004-ros-noetic-installation-desription/

One of the best sources of official documentation is the front page of the RealSense ROS GitHub site.  You can find much useful information if you scroll down the page.

https://github.com/IntelRealSense/realsense-ros

Below is a link to a ROS D435i SLAM tutorial:

https://github.com/IntelRealSense/realsense-ros/wiki/SLAM-with-D435i

A few more tutorials can be found in a list in a side-panel at this tutorial page.

![image](https://user-images.githubusercontent.com/41145062/98711915-88ec3e00-237d-11eb-806d-9bb1da1dd516.png)

**Comment by ranjitkathiriya** [comment]
Thanks for helping me out

**Comment by MartyG-RealSense** [comment]
You are very wecome   :)

**Comment by ranjitkathiriya** [comment]
Hi Marty,

I have followed these steps everything working perfectly. Even I am able to see the video in rviz.
.
https://answers.ros.org/question/363889/intel-realsens-on-ubuntu-2004-ros-noetic-installation-desription/

But I am not able to get D435i No PointCloud2 for that.

![Screenshot from 2020-11-19 09-14-43](https://user-images.githubusercontent.com/12687608/99677782-1ac40d00-2a48-11eb-8c68-061654ca376c.png)
![Screenshot from 2020-11-19 09-16-44](https://user-images.githubusercontent.com/12687608/99677806-1f88c100-2a48-11eb-8972-17666ec5e2e9.png)


Thanks
