### ISSUE TITLE
problem with librealsense version check

### ISSUE THREAD

**Issue by mjsobrep** [realsenseai/realsense-ros#1497]
I am having a problem with the version check from #1278. I am getting:

[ INFO] [1605119322.475257345]: RealSense ROS v2.2.18
[ INFO] [1605119322.475280472]: Built with LibRealSense v2.38.1
[ INFO] [1605119322.475454807]: Running with LibRealSense v2.39.0
[ WARN] [1605119322.475552420]: ***************************************************
[ WARN] [1605119322.475594147]: ** mjs: running with a different librealsense version **
[ WARN] [1605119322.475649595]: ** than the one the wrapper was compiled with!   **
[ WARN] [1605119322.475685700]: ***************************************************

However, I am building with 2.39.0. I have 2.39.0 installed (according to realsense viewer). I added a line to the cmake to print the version: `message(STATUS "Found LibRealSense Version: ${realsense2_VERSION}")` which prints: `-- Found LibRealSense Version: 2.39.0` at build time. And just to make sure that I am running and building what I think I am, I dropped my initials into the warning message in the source files, which prints out when running (seen above). Any thoughts on what may be causing this?

**Comment by MartyG-RealSense** [comment]
Hi @mjsobrep   Did you build the 2.2.18 wrapper originally with SDK 2.38.1 and then upgrade librealsense to 2.39.0 at a later date after the wrapper had been built, please?  If you did, I would recommend rebuilding the ROS wrapper so that it builds on SDK 2.39.0.

**Comment by mjsobrep** [comment]
I believe I have already done a clean build with 2.39.0, see above.

**Comment by MartyG-RealSense** [comment]
Can you confirm that on your clean build, you built librealsense 2.39.0 first and then ROS wrapper 2.2.18 second please?

**Comment by doronhi** [comment]
Could it be that you have realsense2_camera installed from debian package also? Try adding a message of your own to the realsense2_camera code to make sure you indeed running the app that you build.

**Comment by mjsobrep** [comment]
@MartyG-RealSense I am not building librealsense, using the debian packages for that. 2.39.0 is installed prior to buidling the realsense-ros packages

@doronhi I don't think so. To check, I added my initials to the error printout (see first message). Is there another place that I should be adding a printout?

**Comment by MartyG-RealSense** [comment]
@mjsobrep   Did you install the wrapper with packages using **Method 1** of the wrapper's installation instructions?

https://github.com/IntelRealSense/realsense-ros#method-1-the-ros-distribution

With this method, librealsense and the ROS wrapper are both installed at the same time.  But the librealsense version in these packages may not be the latest one.  

So if you installed SDK 2.39.0 first with packages and then used wrapper installation Method 1, I could foresee how SDK 2.38.1 could get installed with the wrapper and you could end up with two SDK versions on your computer.

**Comment by mjsobrep** [comment]
@MartyG-RealSense I use method 2. But one thing that comes to mind is that maybe when I use rosdep: `rosdep install --from-paths ~/catkin_ws/src/[...some package that depends on realsense...]/ --ignore-src -r -y` something gets off. However, Prior to building the realsense-ros package, if I run realsense-viewer, it says v2.39.0 and cmake reports that it is using v2.39.0 (as noted in the original post).

How is it possible for cmake to report one thing then at runtime for there to be another?

**Comment by MartyG-RealSense** [comment]
The advice in this past case about a version mismatch may be helpful.

https://github.com/IntelRealSense/realsense-ros/issues/950

**Comment by mjsobrep** [comment]
@MartyG-RealSense Thanks, you are right, there was another realsense version: `ros-melodic-librealsense2`. I'm pretty sure that I did not install that myself, so I am thinking that it came from rosdep seeing `  <exec_depend>realsense2_camera</exec_depend>
` in a package.xml. after uninstalling that, I am good. I am still not clear on why that was being used instead of the package that cmake was finding. Here is what I had installed before:

```

ii  librealsense2:amd64                          2.39.0-0~realsense0.3571                         amd64        Intel(R) RealSense(tm) Cross Platform API - runtime
hi  librealsense2-dbg:amd64                      2.39.0-0~realsense0.3571                         amd64        Intel(R) RealSense(tm) Camera Capture API - debug symbols
hi  librealsense2-dev:amd64                      2.39.0-0~realsense0.3571                         amd64        Intel(R) RealSense(tm) Camera Capture API - development files
ii  librealsense2-dkms                           1.3.14-0ubuntu1                                  all          Modified kernel modules for librealsense2
ii  librealsense2-gl:amd64                       2.39.0-0~realsense0.3571                         amd64        Intel(R) RealSense(tm) - GLSL-enabled extensions
ii  librealsense2-net:amd64                      2.39.0-0~realsense0.3571                         amd64        Intel(R) RealSense(tm) - Network Bridge extension
ii  librealsense2-udev-rules:amd64               2.39.0-0~realsense0.3571                         amd64        Intel(R) RealSense(tm) Camera Capture API - udev rules
hi  librealsense2-utils:amd64                    2.39.0-0~realsense0.3571                         amd64        Intel(R) RealSense(tm) Camera Capture API - utils and demos
ii  ros-melodic-librealsense2                    2.38.1-1bionic.20200915.132851                   amd64        Library for capturing data from the Intel(R) RealSense(TM) SR300, D400 Depth cameras and T2xx Tracking devices.

```
after uninstalling ros-melodic-librealsense2, everything works as expected.

**Comment by MartyG-RealSense** [comment]
Great to hear @mjsobrep  - thanks for the update!

**Comment by MartyG-RealSense** [comment]
Hi @mjsobrep   Is it okay to close this issue now please if you have had a satisfactory outcome?   Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
