### ISSUE TITLE
How to improve depth and color alignment performance of L515?

### ISSUE THREAD

**Issue by zhongxiangzju** [realsenseai/realsense-ros#1499]
Hi,

I found that depth and color streams from L515 are not aligned well. Is there a solution to improve the alignment performance?
![color_image](https://user-images.githubusercontent.com/38032220/98950858-7bc57f80-2534-11eb-9fea-b437b7c4f7c9.png)
![depth_image](https://user-images.githubusercontent.com/38032220/98950861-7d8f4300-2534-11eb-8b48-2faf30c26108.png)

**Comment by xiaotaw** [comment]
how did you get the aligned color and depth images？

**Comment by RealSenseSupport** [comment]
Hi,

Will you be needing further help with this?

*If we don’t hear from you in 7 days, this issue will be closed.*

Thanks
