### ISSUE TITLE
allow for selecting cameras by ethernet instead of USB for ROS/ROS2 Drivers and Launch Files

### ISSUE THREAD

**Issue by wegunterjr** [realsenseai/realsense-ros#1501]
I was pointed to an effort to get the Realsense 455 camera on ethernet instead of USB (cable management, industrial connections, etc, etc), and wondering if  it is possible to have the ROS driver look for the ethernet address instead of the USB Port?

https://dev.intelrealsense.com/docs/open-source-ethernet-networking-for-intel-realsense-depth-cameras

**Comment by MartyG-RealSense** [comment]
Hi @wegunterjr   I researched your question and located a discussion from July 2020 where someone used ethernet with realsense2_camera by configuring **ROS_MASTER_URI** and **ROS_IP**.

https://answers.ros.org/question/357185/intel-realsense-nodelets-running-with-remote-roscore-are-dying-bond-broken/

**Comment by doronhi** [comment]
Hi @wegunterjr ,
Currently it is not possible with realsense2_camera. I didn't try it yet but I can give you a starting point.
librealsense2 has a package called librealsense2-net. You can install it or build it from code using the BUILD_NETWORK_DEVICE flag in the cmake file. Best description of the package, it's interface and usage can be found in the [depth-camera-over-ethernet-whitepaper](https://dev.intelrealsense.com/docs/open-source-ethernet-networking-for-intel-realsense-depth-cameras#section-3-sdk-integration).
realsense2_camera does not support this extension. Out of the top of my head, the gap is not so great. One will have to add a parameter for the IP-address to be used and update the context within realsense_node_factory.cpp accordingly.
It's currently not in my scope but if this direction is indeed useful to you, I think many will be happy to hear about your experience.

**Comment by MartyG-RealSense** [comment]
Hi @wegunterjr   Do you require further assistance with this case, please?   Thanks!

**Comment by wegunterjr** [comment]
I am finishing up my sprint but will spin this up again in a week!
Thanks for the suggestions!!!  I am excited to try them.


Walter Gunter
"The world has the habit of making room for the man whose actions show that
he knows where he is going.”  - Napoleon Hill

**Comment by MartyG-RealSense** [comment]
Thanks so much for the update @wegunterjr  - good luck!

**Comment by MartyG-RealSense** [comment]
Adding a note to keep this case open for a further time period.

**Comment by MartyG-RealSense** [comment]
Hi @wegunterjr  Do you have an update about this case that you can provide, please?    Thanks!

**Comment by wegunterjr** [comment]
not yet - got distracted with another part of the system.  Jumping back on this soon.

**Comment by MartyG-RealSense** [comment]
Okay, thanks for the update!

**Comment by MartyG-RealSense** [comment]
Adding a note to keep this case open for a further time period.

**Comment by MartyG-RealSense** [comment]
Adding a note to keep this case open for a further time period.

**Comment by MartyG-RealSense** [comment]
Hi @wegunterjr   Do you have an update about this case that you can provide, please? Thanks!

**Comment by wegunterjr** [comment]
Still using it in its default setup case.  Thinking of trying a couple of things today and this next week.  I will update as soon as I make progress.

**Comment by MartyG-RealSense** [comment]
Thanks very much @wegunterjr for the update.   Good luck!

**Comment by MartyG-RealSense** [comment]
Hi @wegunterjr   Do you have an update about this case that you can provide, please?   Thanks!

**Comment by wegunterjr** [comment]
Ha..I literally just put it in the new sprint starting today.   Let me see
what I can do.

**Comment by MartyG-RealSense** [comment]
Hi @wegunterjr Do you have an update about this case that you can provide, please? Thanks!

**Comment by MartyG-RealSense** [comment]
Hi @wegunterjr Do you have an update about this case that you can provide, please?  This case will be closed in 7 days if we do not hear from you.  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
