### ISSUE TITLE
D435i No PointCloud2 and Map in rviz

### ISSUE THREAD

**Issue by ranjitkathiriya** [realsenseai/realsense-ros#1511]
Hi Marty,

I have followed these steps everything working perfectly. Even I am able to see the video in rviz.
.
https://answers.ros.org/question/363889/intel-realsens-on-ubuntu-2004-ros-noetic-installation-desription/

But I am not able to get D435i No PointCloud2 for and map also as I can see in this link :: https://github.com/IntelRealSense/realsense-ros/wiki/SLAM-with-D435i

![Screenshot from 2020-11-19 09-14-43](https://user-images.githubusercontent.com/12687608/99677782-1ac40d00-2a48-11eb-8c68-061654ca376c.png)
![Screenshot from 2020-11-19 09-16-44](https://user-images.githubusercontent.com/12687608/99677806-1f88c100-2a48-11eb-8972-17666ec5e2e9.png)

Thanks

**Comment by MartyG-RealSense** [comment]
Hi @ranjitkathiriya   Since ROS wrapper 2.2.15 onward (which was published some time after the D435i SLAM guide), the IMU topics are disabled by default.  You can enable them in the roslaunch instruction by adding the commands below to the end of your roslaunch instruction:

**enable_accel:=true enable_gyro:=true**

Another example of setting up a point cloud in RViz is in the ROS wrapper documentation:

https://github.com/IntelRealSense/realsense-ros#point-cloud

**Comment by ranjitkathiriya** [comment]
Hi Marty,

Thanks for the reply I have tried the following way then also it is not working for me. I will attach screenshot for firing the command, and add a map and my rviz environment. It will be helpful for you to troubleshoot the problem.



![Screenshot from 2020-11-20 03-51-19](https://user-images.githubusercontent.com/12687608/99780254-3977e180-2ae4-11eb-8448-b732278d01fb.png)
![Screenshot from 2020-11-20 03-51-32](https://user-images.githubusercontent.com/12687608/99780264-3d0b6880-2ae4-11eb-9838-27c77001f7fd.png)

![1](https://user-images.githubusercontent.com/12687608/99780232-30871000-2ae4-11eb-8e3a-fba484dffdd6.png)



Thanks,
Ranjit

**Comment by MartyG-RealSense** [comment]
What results do you get if you change Fixed Frame from 'map' to **camera_link** like the ROS wrapper's point cloud example does in its RViz image, please?

![image](https://user-images.githubusercontent.com/41145062/99822337-fc930580-2b4a-11eb-9f5d-92b4d44f74e6.png)

**Comment by ranjitkathiriya** [comment]
Thank you so much again It is working doe me.

**Comment by MartyG-RealSense** [comment]
Great news - thanks!
