### ISSUE TITLE
Unable to publish Point Cloud from compressed Image

### ISSUE THREAD

**Issue by NRutigliano** [realsenseai/realsense-ros#1512]
Hi everyone,
in the interest of a SLAM project realized in ROS, I am currently trying to develop a system that can merge depth data on a ground server. These data are produced by D435 cameras mounted on multiple robots. I would like to fuse them and produce a Point Cloud.
My first idea was to do that by sending a compressed image through a Wi-Fi connection. On the server, I decompress the image, convert it into a depth image and use it to produce a Point Cloud. By doing this for all the robots, I will have multiple point clouds to fuse to get a global one.
In order to do this, I was basically following the whitepaper at [**this link**](https://dev.intelrealsense.com/docs/depth-image-compression-by-colorization-for-intel-realsense-depth-cameras#section-3-2-depth-image-recovery-from-colorized-depth-images-in-c).
Anyway, I didn't use the code provided in the paper references, but I started to write my own package.
So far, I managed to send the image topic /camera/depth/image_rect_raw/compressed in my network, I'm able to decompress the image and I developed a node to make the conversion to depth image and then to publish the point cloud. Anyway, if the decompression and the point cloud generation works like a charm, the conversion from colorized image to depth image keeps giving me problems and I cannot figure it out.

Therefore, here's my question(s):

- I would like to make this approach work, so is anyone able to tell me what I'm doing wrong?

- Has anyone already developed such a problem? How did you do it? Any suggestions, no matter what, could be very helpful.

Thank you!

Here's the code:
1. Python node to decompress the image: 
```

#!/usr/bin/env python2
#from _future_ import print_function
import sys, time
import cv2
import numpy as np
import roslib
import rospy
import message_filters
from cv_bridge import CvBridge, CvBridgeError
from sensor_msgs.msg import Image, CompressedImage, CameraInfo
from std_msgs.msg import String, Header
from std_msgs.msg import Float32MultiArray
from transforms3d.euler import euler2mat, mat2euler
from transforms3d.axangles import axangle2mat

class Decompressor:


	# Try to tune the queue_size value. Maybe increase it up to the frequency.	

	def __init__(self):
        	'''Initialize ros publisher, ros subscriber'''
        	# topic where we publish
        	self.image_pub  = rospy.Publisher("/output/image", Image,queue_size=1)

		self.bridge = CvBridge()
		
        	# subscribed Topic
        	self.subscriber = rospy.Subscriber("/camera/depth/image_rect_raw/compressed",
 CompressedImage,self.callback,queue_size=1)
		
	def callback(self,ros_data):

		image_np = self.bridge.compressed_imgmsg_to_cv2(ros_data,"bgr8")

        	out_img = self.bridge.cv2_to_imgmsg(image_np,"bgr8")
		out_img.header = ros_data.header
		#self.image_pub.publish(self.bridge.cv2_to_imgmsg(image_np,"rgb8"))
		self.image_pub.publish(out_img)		
		
class passthrough_class:
	def __init__(self):
		self.info_pub  = rospy.Publisher("/output/camera_info", CameraInfo,queue_size=1)
		self.info_sub = rospy.Subscriber("/camera/depth/camera_info", CameraInfo,self.callback,queue_size=1)
	def callback(self,data):
		self.info_pub.publish(data)

def main(args):
	'''Initializes and cleanup ros node'''
    	rospy.init_node('Decompressor', anonymous=True)
	ic = Decompressor()
	pt = passthrough_class()

    	try:
        	rospy.spin()
    	except KeyboardInterrupt:
        	print "Shutting down ROS Image converter module"
#    	cv2.destroyAllWindows()

if __name__ == '__main__':
	main(sys.argv)
```

2. C++ node to convert the image in Point Cloud:
 ```
#include <ros/ros.h>
#include <image_transport/image_transport.h>
#include <cv_bridge/cv_bridge.h>
#include <sensor_msgs/image_encodings.h>
#include <sensor_msgs/Image.h>
#include <sensor_msgs/CameraInfo.h>
#include <sensor_msgs/PointCloud2.h>
#include <sensor_msgs/point_cloud2_iterator.h>
#include <std_msgs/String.h>
#include <pcl_ros/point_cloud.h>
#include <pcl_ros/publisher.h>
#include <pcl_conversions/pcl_conversions.h>
#include <pcl/point_cloud.h>
#include <pcl/point_types.h>
#include <pcl/filters/voxel_grid.h>
#include <opencv2/imgproc/imgproc.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/imgproc.hpp>
#include <opencv2/highgui.hpp>
#include <opencv2/imgcodecs/imgcodecs.hpp>
#include <opencv2/imgcodecs.hpp>
#include <opencv2/core/core.hpp>
#include <opencv2/core.hpp>
#include <vector>
#include <Eigen/Eigen>
#include <iostream>
#include <thread>
#include <chrono>
#include <fstream>
#include <string>
#include <atomic>
#include <opencv2/opencv.hpp>
#include <boost/thread.hpp>

static const std::string OPENCV_WINDOW = "Depth image *10";	// SHOW IMAGE

class ImageConverter
{
  ros::NodeHandle nh_;
  image_transport::ImageTransport it_;
  image_transport::Subscriber image_sub_;
  image_transport::Publisher image_pub_;
  ros::Publisher cloud_pub = nh_.advertise<sensor_msgs::PointCloud2> ("/converter/depth/points", 1);
public:
  ImageConverter()
    : it_(nh_)
  {
   // Subscribe colorized Image and publish depth Image

   image_sub_ = it_.subscribe("/output/image", 1, &ImageConverter::imageCb, this);
   image_pub_ = it_.advertise("/converter/depth/image", 1);
   cv::namedWindow(OPENCV_WINDOW);	// SHOW IMAGE
  }

  ~ImageConverter()
  {
    cv::destroyWindow(OPENCV_WINDOW);	// SHOW IMAGE
  }

  unsigned short RGBtoD(unsigned char r, unsigned char g, unsigned char b)
  {
   // Conversion from RGB color to quantized depth values. Configured for Hue colorization method.

	if(b+g+r < 255) //255 128
	{
		return 0;
	}
	else if (r >= g && r >= b)
	{
		if (g >= b)
		{	
			return g - b;
		}
		else
		{
			return (g - b) + 1529; //1529 1535
		}
	}
	else if (g >= r && g >= b)
	{
		return b - r + 510; //510 512
	}
	else if (b >= g && b >= r)
  	{
		return r - g + 1020; //1020 1024
	}
  }


  void ColorizedDepthToDepth(cv::Mat& color_mat, cv::Mat& depth_mat)
  {
   // Convert Colorized Image to quantized Depth Image
   // Image size
   int _width =848 ;
   int _height = 480;
   bool is_disparity = false;
   // Min and Max depth range for the camera. Value is in meters
   float min_depth = 0.29; // to avoid depth inversion, it’s offset from 0.3 to 0.29.
   float max_depth = 16.0; // 64.0
   float min_disparity = 1.0f / max_depth;
   float max_disparity = 1.0f / min_depth;
   // This is a scale value. It is technically acquired from the camera laser. Here it's imported from realsense-viewer
   float depth_units = 0.0010;

   unsigned short hue_value = 0; // from 0 to 255 * 6-1 = 0-1529 by Hue colorization

   auto in = reinterpret_cast<const unsigned char*>(color_mat.data);	// Input Image matrix
   auto out = reinterpret_cast<unsigned short*>(depth_mat.data);	// Output Image matrix

   for (int i = 0; i < _height; i++)
   {
    for (int j = 0; j < _width; j++)
    {
     unsigned char R = *in++;
     unsigned char G = *in++;
     unsigned char B = *in++;
     unsigned short hue_value = RGBtoD(R, G, B);

     if(hue_value > 0)
     {
      if(!is_disparity)
      {
       unsigned short z_value = static_cast<unsigned short>((min_depth + (max_depth - min_depth) * hue_value / 1529.0f) / depth_units + 0.5f); //1529
       *out++ = z_value;
      }
      else
      {
       float disp_value = min_disparity + (max_disparity - min_disparity) * hue_value / 1529.0;//1529
       *out++ = static_cast<unsigned short>((1.0f / disp_value)/depth_units + 0.5);
      }
     }
     else
     {
      *out++ = 0;
     }
    }
   }
  }
  void ComputePointCloud(cv::Mat& depth_mat, std::vector<float>& point_cloud)
  {
   float depth_units = 0.0010;
   point_cloud.clear();
   for (int y = 0; y < 480; y++)
   {
    for (int x = 0; x < 848; x++)
    {
     auto depth_value = depth_mat.at<unsigned short>(y, x);
     if (depth_value > 0)
     {
      point_cloud.push_back(depth_value * (x - 419.7328186035156) / 424.0969543457031 * depth_units * 1000.0f );	//* 1000.0f
      point_cloud.push_back(depth_value * (y - 237.46710205078125) / 424.0969543457031 * depth_units * 1000.0f );//* 1000.0f
      point_cloud.push_back((float)depth_value * depth_units * 1000.0f );//* 1000.0f
     }
    }
   }
  }


  void imageCb(const sensor_msgs::ImageConstPtr& msg)
  {
    cv_bridge::CvImagePtr cv_ptr;	// Subscribed Image Declaration.
    try
    {

      cv_ptr = cv_bridge::toCvCopy(msg, sensor_msgs::image_encodings::RGB8);	// Subscribed Image assigned.
      auto depth_mat = cv::Mat(cv::Size(848,480), CV_16U).setTo(0);		// Depth Image declaration.
      ColorizedDepthToDepth(cv_ptr->image,depth_mat); 				// Conversion. (cv_ptr->image extracts cv::Mat from message)
    	
       // Update GUI Window
      cv::imshow(OPENCV_WINDOW, depth_mat*10);	// SHOW IMAGE
      cv::waitKey(3);	// SHOW IMAGE
      

	// PointCloud2 Message generation

	std::vector<float> point_cloud;
	
	ComputePointCloud(depth_mat,point_cloud);

	std::vector<float> points;
	float depth_scale = 0.0010;
	Eigen::Matrix3f K;
	Eigen::Matrix3f invK;
	K << 424.0969543457031, 0.0, 419.7328186035156, 0.0, 424.0969543457031, 237.46710205078125, 0.0, 0.0, 1.0;
	invK = K.inverse();	

	for (int i=0;i<depth_mat.rows;i++)
	{
	 const unsigned short* row_ptr = depth_mat.ptr<unsigned short>(i);
	 for (int j=0;j<depth_mat.cols;j++)
	 {
	  unsigned short id = row_ptr[j];
	  if(id!=0)
	  {
	   float d=depth_scale*id;
           Eigen::Vector3f image_point(j*d,i*d,d);
           Eigen::Vector3f camera_point=invK*image_point; //*0.50f
	   points.push_back(camera_point.x());
	   points.push_back(camera_point.y());
	   points.push_back(camera_point.z());
	  }
	 }
	}

	int n_points = points.size();
	sensor_msgs::PointCloud2 cloud_msg;
	sensor_msgs::PointCloud2Modifier modifier(cloud_msg);
	modifier.setPointCloud2Fields(3, "x", 1, sensor_msgs::PointField::UINT16, "y", 1, sensor_msgs::PointField::UINT16,"z", 1, sensor_msgs::PointField::UINT16); //FLOAT32
	modifier.setPointCloud2FieldsByString(1, "xyz");
	modifier.resize(n_points);
	sensor_msgs::PointCloud2Iterator<float> iter_x(cloud_msg, "x");
	sensor_msgs::PointCloud2Iterator<float> iter_y(cloud_msg, "y");
	sensor_msgs::PointCloud2Iterator<float> iter_z(cloud_msg, "z");
	cloud_msg.height = 1;
	cloud_msg.width = n_points;
	cloud_msg.header.frame_id = msg->header.frame_id;
	cloud_msg.header.seq = msg->header.seq;
	cloud_msg.header.stamp = msg->header.stamp;
    	
	for(size_t i=0; i<n_points/3; ++i, ++iter_x, ++iter_y, ++iter_z)
	{
	 *iter_x = points[3*i+0];
	 *iter_y = points[3*i+1];
	 *iter_z = points[3*i+2];
	 //std::cerr << *iter_x << " " << *iter_y << " " << *iter_z << std::endl;	// It display x,y,z points' coordinates on terminal.
	}

	cloud_pub.publish(cloud_msg);
	//std::cerr << ".";
    }    
	    catch (cv_bridge::Exception& e)
    {
      ROS_ERROR("cv_bridge exception: %s", e.what());
      return;
    }
  }
};

int main(int argc, char** argv)
{
  ros::init(argc, argv, "image_converter");
  ImageConverter ic;
  ros::spin();
  return 0;
}


```

**Comment by MartyG-RealSense** [comment]
Hi @NRutigliano    I recall a past case where someone was having problems with extracting compressed images in ROS.  It was suggested to them that they may be publishing the decompressed images on the same topic as the originals.  So it may be worth checking that as a first step in this investigation.

https://answers.ros.org/question/298180/extracting-compressed-image-data-from-bag-file-results-in-doubled-up-or-dropped-frames/

******************

As a side-note: although your preference is a ROS-based solution, you may also be interested in a multi-camera ethernet network system developed by the CONIX Research Center at Carnegie Mellon that can stitch point clouds from up to 20 RealSense 400 Series cameras, each one on its own computer.

https://github.com/conix-center/pointcloud_stitching

**Comment by NRutigliano** [comment]
Hi @MartyG-RealSense
Thanks for your fast reply, I checked the links. For what concerns the first one, I don't have a problem with the topic name, as you can see in the code that I posted early. Moreover, the issues with my package do not lie in extracting compressed images, but in converting a decompressed, colorized image into a depth grayscale image, as in the image below. 
![9429424-fig-1](https://user-images.githubusercontent.com/56929171/99944641-87eedf80-2d73-11eb-9b7d-dc35b6b8dda6.jpg)
The reason I opened the issue in the first place is that the colorized image on the camera side and the colorized image that I got once I decompressed the _**compressedImage**_ topic looks exactly the same, hence I figured out that the conversion should work just fine. But it doesn't.
I also started to check the second link, I might find something useful there, even if for what I read it appears that this package works when the NUCs are connected via ethernet.
Anyway, If I solve my issue, I will immediately write a comment here and let you know. In the meantime, if you have other suggestions, I would be very happy to hear it.
Thank you!

**Comment by MartyG-RealSense** [comment]
There was a past case where a RealSense user provided details of the point cloud streaming with compression method that they used successfully (see the linked comment and the comments beneath it). 

https://github.com/IntelRealSense/librealsense/issues/6535#issuecomment-647186213

Their method produced the images shown below.

![image](https://user-images.githubusercontent.com/41145062/99955749-c4730900-2d7c-11eb-83ae-cf2fcd2fe74b.png)

There is also a non-RealSense white paper that Intel published about high quality volumetric streaming of compressed camera data.

https://www.intel.com/content/dam/www/public/us/en/documents/white-papers/v2-volumetric-vod-streaming-whitepaper.pdf

The simplest way to reduce bandwidth though would be to use a lower resolution and / or FPS speed if possible, which may mean that you may not need to use a compressed topic at all.  To illustrate this point, Intel's multiple camera white paper has charts that provide estimates of bandwidth usage in a range of different streaming configurations with 1 or more cameras on the same computer when the camera is connected to a USB hub or directly to the computer.

https://dev.intelrealsense.com/docs/multiple-depth-cameras-configuration#section-2-multi-camera-considerations

**Comment by NRutigliano** [comment]
Ok thanks, I think I have enough material to investigate. I will try not to use the compressed topic. Still, I don't get why the colorization method doesn't work. Anyway, I'll let you know how it goes. Thanks, again.

**Comment by NRutigliano** [comment]
UPDATE:
I managed to improve the quality of the reconstructed depth image, therefore the Point cloud. To achieve this I double-checked all the post-processing filters used in the camera and by reconfiguring the parameter **_histogram equalization_** to false in the colorizer filter, the reconstructed depth image has gotten way better. Anyway, I think it's possible to do better, so I will keep trying. I will update as soon as I get new results

**Comment by MartyG-RealSense** [comment]
Great to hear that you achieved improvement.  Thanks for sharing details of the method that worked for you, and please do update further after your new tests.   Good luck!

**Comment by MartyG-RealSense** [comment]
Hi @NRutigliano   Do you require further assistance with this case, please?   Thanks!

**Comment by NRutigliano** [comment]
Hi @MartyG-RealSense, I can take care of it by myself now. Thanks!

**Comment by MartyG-RealSense** [comment]
Great to hear @NRutigliano  - thanks very much for the update!
