### ISSUE TITLE
D435i process die after update

### ISSUE THREAD

**Issue by dtquoc97** [realsenseai/realsense-ros#1513]
Hi,
I have just updated realsense SDK v2.40.0 and then I reinstall realsense-ros.
When I run roslaunch realsense2_camera rs_camera.launch, I receive 

![Screenshot from 2020-11-19 23-26-16](https://user-images.githubusercontent.com/74728706/99695681-6ca87980-2ac0-11eb-8f51-56c64aa2f943.png)

Thanks

**Comment by MartyG-RealSense** [comment]
Hi @dtquoc97   Did you build from packages using **Method 1** of the ROS wrapper installation instructions, please?

https://github.com/IntelRealSense/realsense-ros#method-1-the-ros-distribution

 If so, I would recommend using Method 2 (building the ROS wrapper from source code) for the moment in case the packages are not yet updated to SDK 2.40.0, as this SDK version was only released yesterday.  If SDK 2.40.0 is already installed, skip to Step 2 of Method 2 to install the RealSense ROS wrapper 2.2.20 from source:

https://github.com/IntelRealSense/realsense-ros#step-2-install-intel-realsense-ros-from-sources

**Comment by dtquoc97** [comment]
@MartyG-RealSense 
After update SDK, I try to run Slam with D435i but it don't receive point cloud. So reinstall ROS wrapper from source and get this problem,
There is a issue  i have two rule in etc/udev/ and lib/udev, so i remove one in etc/udev. Does it have any problem?

**Comment by MartyG-RealSense** [comment]
The **etc** rule is the one that can be removed safely to solve the **multiple udev rules** warning.  The **lib** rule should not be removed, as doing so can break the linkages of Debian packages.

**Comment by dtquoc97** [comment]
I just install ROS wrapper in another workspace but it still not working

**Comment by MartyG-RealSense** [comment]
What errors do you receive now please?

**Comment by dtquoc97** [comment]
Although I used method 2 to build, this problem has not been resolved. 
I try to run with older version of SDK and ROS wrapper on another PC, it have the same problem.

I think it may be relate to camera's firmware. 
After update SDK and connect with camera, it ask me update firmware and i saw this error after run enable_accel:=true enable_gyro:=true  to resolved issue https://github.com/IntelRealSense/realsense-ros/issues/1511

**Comment by MartyG-RealSense** [comment]
The problem in that link was solved:

https://github.com/IntelRealSense/realsense-ros/issues/1511#issuecomment-731260035

**Comment by dtquoc97** [comment]
The problem was not caused by realsense-ros. I uninstall realsense SDK and install it again instead update.

Thank for your support

**Comment by MartyG-RealSense** [comment]
Thanks very much @dtquoc97 for the update!
