### ISSUE TITLE
How to get RGB Depth stream in python ROS

### ISSUE THREAD

**Issue by ranjitkathiriya** [realsenseai/realsense-ros#1514]
Hi @doronhi,

Actually, I am getting RGB-D from the stream but it is in black color can you please help me with that here I am posting my code and Image of the output.

```
#!/usr/bin/env python3
import rospy
from sensor_msgs.msg import Image
from cv_bridge import CvBridge 
import cv2
import numpy as np
 
def callback(data):
  br = CvBridge()
  rospy.loginfo("receiving video frame")
  current_frame = br.imgmsg_to_cv2(data)
  cv_image_array = np.array(current_frame, dtype = np.dtype('f8'))
  cv_image_norm = cv2.normalize(cv_image_array, cv_image_array, 0, 1, cv2.NORM_MINMAX)
  cv2.imshow("camera", cv_image_norm)
  print(cv_image_norm.shape)
  cv2.waitKey(1)
      
def receive_message():
  rospy.init_node('video_sub_py', anonymous=True)
  rospy.Subscriber('/camera/aligned_depth_to_color/image_raw', Image, callback)
  rospy.spin()
  cv2.destroyAllWindows()
  
if __name__ == '__main__':
  receive_message()
```

![Screenshot from 2020-11-19 11-45-24](https://user-images.githubusercontent.com/12687608/99696533-cc6d3900-2a5c-11eb-8e91-4b32868e8bae.png)

Thank you so much for the help

**Comment by MartyG-RealSense** [comment]
Hi @ranjitkathiriya   I wonder if you need to define a Colorizer filter in your ROS launch.

https://github.com/IntelRealSense/realsense-ros/issues/501

**Comment by ranjitkathiriya** [comment]
Thanks, Solved::

by running this ros command:
roslaunch realsense2_camera rs_camera.launch enable_pointcloud:=true filters:=colorizer align_depth:=true

**Comment by MartyG-RealSense** [comment]
Great news, thanks for the update!
