### ISSUE TITLE
Only shows depth topics.

### ISSUE THREAD

**Issue by konnoeric** [realsenseai/realsense-ros#1516]
I launched "roslaunch realsense2_camera rs_camera.launch" and it shows only depth topics. How can I see RGB and Lidar pointcloud topics?
I am using Intel RealSense L515. Ubuntu 18.04.5 LTS.  Intel® Core™ i5-4590 CPU.
![Screenshot from 2020-11-20 19-05-26](https://user-images.githubusercontent.com/74105724/99787897-aed6c700-2b63-11eb-8dc6-083226c7991e.png)

**Comment by doronhi** [comment]
It could help if you published the log of the realsense2_camera node. It looks like using parameter enable_color:=false. To publish a pointcloud you'll have to set enable_pointcloud:=true either in the command line on in the rs_camera.launch file.

**Comment by RealSenseSupport** [comment]
Hi @konnoeric 

Is there anything else you need on this thread?

*If we don’t hear from you in 7 days, this issue will be closed.
