### ISSUE TITLE
/camera/depth/image_rect_raw to depth values

### ISSUE THREAD

**Issue by miajl** [realsenseai/realsense-ros#1524]
Hello, I am having trouble figuring out how to convert the images on /camera/depth/image_rect_raw to actual depth values. I know that for a 16bit depth, one unit is 1 mm, but ros image data is made of uint8. How does that change the conversion?

**Comment by MartyG-RealSense** [comment]
Hi @miajl   One approach that a RealSense user applied successfully was to convert the **/camera/depth/image_rect_raw** image to an OpenCV image using **cv_bridge** and then obtain the depth value using a **double distance** calculation.

https://answers.ros.org/question/299888/using-a-depth-map/

Another couple of examples of using cv_bridge to get the depth value from /camera/depth/image_rect_raw can be foud in the lnks below:

https://github.com/IntelRealSense/realsense-ros/issues/436

https://github.com/IntelRealSense/realsense-ros/issues/714

**Comment by yuzhou42** [comment]
Hi @miajl, the following method works for me.

```Python
import rospy
from cv_bridge import CvBridge, CvBridgeError
import sensor_msgs.msg  
import numpy as np
from PIL import Image
i = 0
root='/home/yu'
def convert_depth_image(ros_image):
    bridge = CvBridge()
    global i
    depth_image = bridge.imgmsg_to_cv2(ros_image, desired_encoding="passthrough")
    depth_array = np.array(depth_image, dtype=np.float32)
    im = Image.fromarray(depth_array)
    im = im.convert("L")
    idx = str(i).zfill(4)
    im.save(root+"/depth/frame{index}.png".format(index = idx))
    i += 1
    print("depth_idx: ", i)

def pixel2depth():
    rospy.init_node('pixel2depth',anonymous=True)
    rospy.Subscriber("/camera/aligned_depth_to_color/image_raw", sensor_msgs.msg.Image,callback=convert_depth_image, queue_size=10)
    rospy.spin()

if __name__ == '__main__':
    pixel2depth()
```

Hope it helps!

Yu

**Comment by MartyG-RealSense** [comment]
Hi @yuzhou42   Thanks so much for your help with the question of @miajl and contributing your script for RealSense community members to benefit from in future    :)

**Comment by yuzhou42** [comment]
@MartyG-RealSense  You're welcome! Glad it helps  ^_^

**Comment by doronhi** [comment]
Thanks @yuzhou42 . For future reference, users can also check out the following python script included in this package: [show_center_depth.py](https://github.com/IntelRealSense/realsense-ros/blob/development/realsense2_camera/scripts/show_center_depth.py). It demonstrates subscribing to depth image and depth camera info topics and extracting depth and 3D position in camera's coordinates.

**Comment by miajl** [comment]
Would doing this get the correct depth values? It looks right when I plot it but I want to make sure.

```
bridge = CvBridge()
cv_img = bridge.imgmsg_to_cv2(ros_img, "passthrough")
depth_array = np.array(cv_img, dtype=np.uint16)*0.001
```

**Comment by MartyG-RealSense** [comment]
Hi @doronhi   Can you take a look at the question above from @miajl please?   Thanks!

**Comment by MartyG-RealSense** [comment]
Hi @miajl    Did you find a solution to your question above, please?

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.

**Comment by deadln** [comment]
> Would doing this get the correct depth values? It looks right when I plot it but I want to make sure.
> 
> ```
> 
> ```

Better use 0.1 multiplier
