### ISSUE TITLE
Unable to run opensource_tracking example on Jetson Nano

### ISSUE THREAD

**Issue by arjunskumar** [realsenseai/realsense-ros#1532]
While running the opensource_tracking.launch, i'm getting failed to meet update rate warning. 
Any idea how can I run RTAB on Jetson Nano

**Comment by MartyG-RealSense** [comment]
Hi @arjunskumar  Which librealsense version and RealSense ROS wrapper version are you using please?   Thanks!

**Comment by arjunskumar** [comment]
@MartyG-RealSense Librealsense Version 2.31 and Realsense ROS wrapper version 2.2.0

**Comment by MartyG-RealSense** [comment]
It is important to match the ROS wrapper version as closely as possible with the specific librealsense SDK recommended on the Releases page for the wrapper.  For ROS wrapper 2.2.20, librealsense **2.40.0** should be used with it.

https://github.com/IntelRealSense/realsense-ros/releases/tag/2.2.20

Once librealsense 2.40.0 is installed, the RealSense ROS wrapper should be rebuilt using wrapper version 2.2.20.

**Comment by MartyG-RealSense** [comment]
Hi @arjunskumar   Do you require further assistance with this case, please?   Thanks!

**Comment by arjunskumar** [comment]
@MartyG-RealSense I have tested with Jetson TX2 by building realsense SDK from source, and its working. I will update you once I  switch to Jetson Nano.

**Comment by MartyG-RealSense** [comment]
Thanks very much for the update @arjunskumar - I look forward to your next update!

**Comment by MartyG-RealSense** [comment]
Adding a note to keep this case open for a further time period.

**Comment by MartyG-RealSense** [comment]
Adding a note to keep this case open for a further time period.

**Comment by arjunskumar** [comment]
@MartyG-RealSense The error was because of opencv installation that comes with Jetson Nano. I had to reinstall the opencv and now its working.

**Comment by MartyG-RealSense** [comment]
Great to hear that you solved the problem - thanks very much for the update!
