### ISSUE TITLE
Is there any new ROS2 Foxy Wrapper?

### ISSUE THREAD

**Issue by Ultraopxt** [realsenseai/realsense-ros#1537]
I installed librealsense2 with latest source code.It works good when I open realsense-viewer(V2.40.0).But  after :
sudo apt-get install ros-foxy-librealsense2
I run my code on ros-foxy:when call librealsense2,it always gives error:Frame didn't arrive within 15000.
And after that I checked by open realsense-viewer: and the versin became V2.34.0,and got error:no frame received.
It is related to ROS2 Foxy Wrapper?
(my camera is d435i)
Any help?Thanks

**Comment by MartyG-RealSense** [comment]
Hi @qingweihk   As you are using the **sudo apt-get install ros-foxy-librealsense2** command, it looks as though you are using the ROS wrapper from the link below:

https://github.com/intel/ros2_intel_realsense/tree/refactor

The ROS2 wrappers on the **/Intel/** GitHub were produced by developers on the main Intel Github, not the RealSense ROS GitHub, and the two sites are not connected.  The /Intel/ GitHub wrappers are no longer updated and so can not be guaranteed to work with the newest librealsense SDK versions and RealSense camera models.  The RealSense ROS GitHub's **Eloquent branch** should be used instead with ROS2 if possible.

https://github.com/IntelRealSense/realsense-ros/tree/eloquent

Support for Foxy is a stated goal for the RealSense ROS wrapper.  For now though, it is officially targeted at ROS2 **Eloquent**.

https://github.com/IntelRealSense/librealsense/issues/5825#issuecomment-669031717

**Comment by MartyG-RealSense** [comment]
Hi @qingweihk   Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
