### ISSUE TITLE
All the warnings that you get seem to be caused by the low power up board. They just mean missing frames. You can try reducing the resolution to have a better frame rate or disable some of the sensors if you don't need them (If you don't use infra2 for example, set `enable_infra2:=false`. It may save some CPU.

### ISSUE THREAD

**Issue by ranjitkathiriya** [realsenseai/realsense-ros#1546]
All the warnings that you get seem to be caused by the low power up board. They just mean missing frames. You can try reducing the resolution to have a better frame rate or disable some of the sensors if you don't need them (If you don't use infra2 for example, set `enable_infra2:=false`. It may save some CPU.

_Originally posted by @doronhi in https://github.com/IntelRealSense/realsense-ros/issues/715#issuecomment-479855525_

1) How to reduce resolution in ros??

**Comment by MartyG-RealSense** [comment]
Hi @ranjitkathiriya   You can edit the **arg** conditions in a launch file to alter the resolution of a stream type by changing the **width** and the **length** values of the depth, color, infra, etc.  For example, setting **color_width** to 640 and **color_length** to 480 for a color resolution of 640x480 .

An example of a launch file with arg conditions is shown in the link below:

https://github.com/IntelRealSense/realsense-ros/issues/1293#issuecomment-660018701

![image](https://user-images.githubusercontent.com/41145062/101204667-7c00f880-3664-11eb-8c34-0fdd27b85a73.png)

The details of the resolution that is set in the launch file should be shown in the details of the launch log during roslaunch.

![image](https://user-images.githubusercontent.com/41145062/101204052-88d11c80-3663-11eb-8bba-43b3f58090fd.png)

**Comment by ranjitkathiriya** [comment]
Thanks for Help!!
