### ISSUE TITLE
The imu data after calibration(D435i)

### ISSUE THREAD

**Issue by Phz-1995** [realsenseai/realsense-ros#1550]
Hello, 

I'm planning to get the imu data (D435i) from realsense-ros. I have done the imu calibration using the official script **rs-imu-calibration.py** and save the result to device. My question is: Is the data I got from realsense-ros calibrated?  As in [https://github.com/IntelRealSense/librealsense/issues/7103](url) mentioned, 
there is a **Motion correction button** in realsense viewer, which can correct the IMU data. I have no idea if this correction is based on the calibration result and this correction is only limited in realsense viewer and not included in realsense-ros. In that case, the data I got  from realsense-ros is still the original one and the calibration is meaningless.
Thanks.

**Comment by MartyG-RealSense** [comment]
Closed as a duplicate of https://github.com/IntelRealSense/librealsense/issues/7935
