### ISSUE TITLE
I want to publish rgb data and depth data in one msg

### ISSUE THREAD

**Issue by Hiroaki-K4** [realsenseai/realsense-ros#1553]
Hi.
I think that realsense-ros publishes rgb data and depth data in separate topics, but I want to publish a message that contains rgb data and depth in one topic.
So I have a question. How can rgb data and depth data taken at the same moment be paired? Is it a frame_id or a timestamp?
In my experiments, I feel that depth is published faster. I tried to save rgb data and depth data with frame_id and timestamp in the file name respectively. Then, the timestamp was different in the same frame_id of rgb data and depth data.
Thanks!

**Comment by MartyG-RealSense** [comment]
Hi @Hiroaki-K4   The option that is closest to what you are seeking is likely to be the **align_depth** option.  The RealSense ROS documentation states that it "gathers closest frames of different sensors, infrared, color and depth, to be sent with the same timetag.  This happens automatically when such filters as pointcloud are enabled".

Although the aligned streams are not all in one topic, it should achieve the aim of making the timestamps for depth and color the same.  You can enable align_depth in your roslaunch instruction by adding the command below onto the end of the instruction:

**align_depth:=true**

**Comment by Hiroaki-K4** [comment]
ok. thank you.
I will change align_depth and  use messege_filters.
