### ISSUE TITLE
Is there a parameter to remove the acceleration of gravity from the accelerometer?

### ISSUE THREAD

**Issue by Schloern93** [realsenseai/realsense-ros#1565]
Hello,

I am trying to track the position of my robot with the t265. To do this, I would have to remove the offset acc values of the sensors which result from the earth's gravity.
What is the best way to do this?

**Comment by j-corvo** [comment]
Hello, 
I want to do the same thing but with the models D455 and D435i. Have you found a way to remove the gravity's acceleration?
