### ISSUE TITLE
rgb and ir topic

### ISSUE THREAD

**Issue by fw-timku** [realsenseai/realsense-ros#157]
| Version               | Your Configuration   |
|:--------------------- |:---------------------|
| Operating System      | Ubuntu 16.04.1 LTS |
| Kernel                         | 4.4.0-47-generic |
| ROS                           | kinetic |
| ROS RealSense         | 1.5.0 |
| librealsense                | 1.11.0 |
| Camera Type-Firmware  | 1.0.71.06 |

I would like to know is the published topic (using the r200 default nodelet) for the rgb (camera/color/image_raw) and ir (camera/ir/image_raw and camera/ir2/image_raw) stream factory calibrated and rectified ?

**Comment by reaganlo** [comment]
The depth and ir streams are factory calibrated and rectified. The color stream is only factory calibrated.
