### ISSUE TITLE
The requested device with  is NOT found

### ISSUE THREAD

**Issue by Haitham96** [realsenseai/realsense-ros#1573]
Hi,

Im trying to start the camera node by ROS using: `roslaunch realsense2_camera rs_camera.launch`.

and i connected my **D435** camera through usb to the computer.

I am using Ubunto **18.04**.

and this is the error:

... logging to /home/haitham/.ros/log/17f6f94a-3fea-11eb-a4ad-40b0760db710/roslaunch-cggc-corsair270r-29192.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://cggc-corsair270r:37045/

SUMMARY
========

PARAMETERS
 * /camera/realsense2_camera/accel_fps: 250
 * /camera/realsense2_camera/accel_frame_id: camera_accel_frame
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: False
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/allow_no_texture_points: False
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/calib_odom_file: 
 * /camera/realsense2_camera/clip_distance: -2.0
 * /camera/realsense2_camera/color_fps: 30
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: 480
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: 640
 * /camera/realsense2_camera/depth_fps: 30
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: 480
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: 640
 * /camera/realsense2_camera/device_type: 
 * /camera/realsense2_camera/enable_accel: False
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye1: False
 * /camera/realsense2_camera/enable_fisheye2: False
 * /camera/realsense2_camera/enable_fisheye: False
 * /camera/realsense2_camera/enable_gyro: False
 * /camera/realsense2_camera/enable_infra1: False
 * /camera/realsense2_camera/enable_infra2: False
 * /camera/realsense2_camera/enable_infra: False
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_pose: False
 * /camera/realsense2_camera/enable_sync: False
 * /camera/realsense2_camera/filters: 
 * /camera/realsense2_camera/fisheye1_frame_id: camera_fisheye1_f...
 * /camera/realsense2_camera/fisheye1_optical_frame_id: camera_fisheye1_o...
 * /camera/realsense2_camera/fisheye2_frame_id: camera_fisheye2_f...
 * /camera/realsense2_camera/fisheye2_optical_frame_id: camera_fisheye2_o...
 * /camera/realsense2_camera/fisheye_fps: 30
 * /camera/realsense2_camera/fisheye_frame_id: camera_fisheye_frame
 * /camera/realsense2_camera/fisheye_height: 480
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: 640
 * /camera/realsense2_camera/gyro_fps: 400
 * /camera/realsense2_camera/gyro_frame_id: camera_gyro_frame
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/imu_optical_frame_id: camera_imu_optica...
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra_fps: 30
 * /camera/realsense2_camera/infra_height: 480
 * /camera/realsense2_camera/infra_rgb: False
 * /camera/realsense2_camera/infra_width: 640
 * /camera/realsense2_camera/initial_reset: False
 * /camera/realsense2_camera/json_file_path: 
 * /camera/realsense2_camera/linear_accel_cov: 0.01
 * /camera/realsense2_camera/odom_frame_id: camera_odom_frame
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/pose_frame_id: camera_pose_frame
 * /camera/realsense2_camera/pose_optical_frame_id: camera_pose_optic...
 * /camera/realsense2_camera/publish_odom_tf: True
 * /camera/realsense2_camera/publish_tf: True
 * /camera/realsense2_camera/rosbag_filename: 
 * /camera/realsense2_camera/serial_no: 
 * /camera/realsense2_camera/tf_publish_rate: 0.0
 * /camera/realsense2_camera/topic_odom_in: odom_in
 * /camera/realsense2_camera/unite_imu_method: 
 * /camera/realsense2_camera/usb_port_id: 
 * /rosdistro: melodic
 * /rosversion: 1.14.10

NODES
  /camera/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)

ROS_MASTER_URI=http://localhost:11311

process[camera/realsense2_camera_manager-1]: started with pid [29207]
process[camera/realsense2_camera-2]: started with pid [29208]
[ INFO] [1608156657.205609619]: Initializing nodelet with 20 worker threads.
[ INFO] [1608156657.285736696]: RealSense ROS v2.2.20
[ INFO] [1608156657.285764753]: Built with LibRealSense v2.40.0
[ INFO] [1608156657.285774122]: Running with LibRealSense v2.40.0
[ INFO] [1608156657.307395607]:  
 17/12 00:10:57,315 ERROR [140637143815936] (handle-libusb.h:51) failed to open usb interface: 0, error: RS2_USB_STATUS_ACCESS
 17/12 00:10:57,315 ERROR [140637246904064] (sensor.cpp:512) acquire_power failed: failed to set power state
 17/12 00:10:57,316 WARNING [140637246904064] (rs.cpp:306) null pointer passed for argument "device"
[ WARN] [1608156657.316388961]: Device 1/1 failed with exception: failed to set power state
[ERROR] [1608156657.316423905]: The requested device with  is NOT found. Will Try again.

How i can fix it?

Thanks

**Comment by Haitham96** [comment]
I followed some github issues and i did the following:
i removed the filies in **/etc/udev**.
and also i added the file `99-realsense-libusb.rules` to `/etc/udev/rules.d/`.
and also i tried to relaunch roslaunch with fps:=6/15/30 with **initial_reset:=true**, and i got these errors:

... logging to /home/haitham/.ros/log/17f6f94a-3fea-11eb-a4ad-40b0760db710/roslaunch-cggc-corsair270r-23417.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://cggc-corsair270r:37933/

SUMMARY
========

PARAMETERS
 * /camera/realsense2_camera/accel_fps: 250
 * /camera/realsense2_camera/accel_frame_id: camera_accel_frame
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: False
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/allow_no_texture_points: False
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/calib_odom_file: 
 * /camera/realsense2_camera/clip_distance: -2.0
 * /camera/realsense2_camera/color_fps: 15
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: 480
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: 640
 * /camera/realsense2_camera/depth_fps: 15
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: 480
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: 640
 * /camera/realsense2_camera/device_type: 
 * /camera/realsense2_camera/enable_accel: False
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye1: False
 * /camera/realsense2_camera/enable_fisheye2: False
 * /camera/realsense2_camera/enable_fisheye: False
 * /camera/realsense2_camera/enable_gyro: False
 * /camera/realsense2_camera/enable_infra1: False
 * /camera/realsense2_camera/enable_infra2: False
 * /camera/realsense2_camera/enable_infra: False
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_pose: False
 * /camera/realsense2_camera/enable_sync: False
 * /camera/realsense2_camera/filters: 
 * /camera/realsense2_camera/fisheye1_frame_id: camera_fisheye1_f...
 * /camera/realsense2_camera/fisheye1_optical_frame_id: camera_fisheye1_o...
 * /camera/realsense2_camera/fisheye2_frame_id: camera_fisheye2_f...
 * /camera/realsense2_camera/fisheye2_optical_frame_id: camera_fisheye2_o...
 * /camera/realsense2_camera/fisheye_fps: 30
 * /camera/realsense2_camera/fisheye_frame_id: camera_fisheye_frame
 * /camera/realsense2_camera/fisheye_height: 480
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: 640
 * /camera/realsense2_camera/gyro_fps: 400
 * /camera/realsense2_camera/gyro_frame_id: camera_gyro_frame
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/imu_optical_frame_id: camera_imu_optica...
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra_fps: 15
 * /camera/realsense2_camera/infra_height: 480
 * /camera/realsense2_camera/infra_rgb: False
 * /camera/realsense2_camera/infra_width: 640
 * /camera/realsense2_camera/initial_reset: True
 * /camera/realsense2_camera/json_file_path: 
 * /camera/realsense2_camera/linear_accel_cov: 0.01
 * /camera/realsense2_camera/odom_frame_id: camera_odom_frame
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/pose_frame_id: camera_pose_frame
 * /camera/realsense2_camera/pose_optical_frame_id: camera_pose_optic...
 * /camera/realsense2_camera/publish_odom_tf: True
 * /camera/realsense2_camera/publish_tf: True
 * /camera/realsense2_camera/rosbag_filename: 
 * /camera/realsense2_camera/serial_no: 
 * /camera/realsense2_camera/tf_publish_rate: 0.0
 * /camera/realsense2_camera/topic_odom_in: odom_in
 * /camera/realsense2_camera/unite_imu_method: 
 * /camera/realsense2_camera/usb_port_id: 
 * /rosdistro: melodic
 * /rosversion: 1.14.10

NODES
  /camera/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)

ROS_MASTER_URI=http://localhost:11311

process[camera/realsense2_camera_manager-1]: started with pid [23432]
process[camera/realsense2_camera-2]: started with pid [23433]
[ INFO] [1608199540.875593689]: Initializing nodelet with 20 worker threads.
[ INFO] [1608199540.965012321]: RealSense ROS v2.2.20
[ INFO] [1608199540.965041200]: Built with LibRealSense v2.40.0
[ INFO] [1608199540.965051524]: Running with LibRealSense v2.40.0
[ INFO] [1608199540.989942928]:  
[ INFO] [1608199541.158593984]: Device with serial number 727212070786 was found.

[ INFO] [1608199541.158650608]: Device with physical ID 2-2-23 was found.
[ INFO] [1608199541.158668300]: Device with name Intel RealSense D435 was found.
[ INFO] [1608199541.159335571]: Device with port number 2-2 was found.
[ INFO] [1608199541.159371683]: Device USB type: 3.2
[ INFO] [1608199541.159408946]: Resetting device...
[ INFO] [1608199547.190622492]:  
[ INFO] [1608199547.377176572]: Device with serial number 727212070786 was found.

[ INFO] [1608199547.377236481]: Device with physical ID 2-2-24 was found.
[ INFO] [1608199547.377253013]: Device with name Intel RealSense D435 was found.
[ INFO] [1608199547.377760218]: Device with port number 2-2 was found.
[ INFO] [1608199547.377790624]: Device USB type: 3.2
[ INFO] [1608199547.380913069]: getParameters...
[ INFO] [1608199547.431564701]: setupDevice...
[ INFO] [1608199547.431618294]: JSON file is not provided
[ INFO] [1608199547.431642196]: ROS Node Namespace: camera
[ INFO] [1608199547.431692572]: Device Name: Intel RealSense D435
[ INFO] [1608199547.431764545]: Device Serial No: 727212070786
[ INFO] [1608199547.431790032]: Device physical port: 2-2-24
[ INFO] [1608199547.431814038]: Device FW version: 05.12.08.200
[ INFO] [1608199547.431846179]: Device Product ID: 0x0B07
[ INFO] [1608199547.431877099]: Enable PointCloud: Off
[ INFO] [1608199547.431907218]: Align Depth: Off
[ INFO] [1608199547.431935814]: Sync Mode: Off
[ INFO] [1608199547.431998483]: Device Sensors: 
[ INFO] [1608199547.456769536]: Stereo Module was found.
[ INFO] [1608199547.482836779]: RGB Camera was found.
[ INFO] [1608199547.482917481]: num_filters: 0
[ INFO] [1608199547.482945698]: Setting Dynamic reconfig parameters.
[ INFO] [1608199547.907654673]: Done Setting Dynamic reconfig parameters.
[ INFO] [1608199547.908683269]: depth stream is enabled - width: 640, height: 480, fps: 15, Format: Z16
[ INFO] [1608199547.909866499]: color stream is enabled - width: 640, height: 480, fps: 15, Format: RGB8
[ INFO] [1608199547.909911116]: setupPublishers...
[ INFO] [1608199547.913862624]: Expected frequency for depth = 15.00000
[ INFO] [1608199547.962035188]: Expected frequency for color = 15.00000
[ INFO] [1608199547.995078402]: setupStreams...
[ INFO] [1608199548.017066119]: insert Depth to Stereo Module
[ INFO] [1608199548.017160535]: insert Color to RGB Camera
 17/12 12:05:48,081 WARNING [139939245168384] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
[ INFO] [1608199548.131936251]: SELECTED BASE:Depth, 0
[ INFO] [1608199548.146044193]: RealSense Node Is Up!
 17/12 12:05:48,267 WARNING [139939245168384] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 17/12 12:05:48,317 WARNING [139939245168384] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 17/12 12:05:48,368 WARNING [139939245168384] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 17/12 12:05:48,418 WARNING [139939245168384] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 17/12 12:05:48,469 WARNING [139939245168384] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 17/12 12:05:48,519 WARNING [139939245168384] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 17/12 12:05:48,570 WARNING [139939245168384] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 17/12 12:05:48,620 WARNING [139939245168384] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 17/12 12:05:48,670 WARNING [139939245168384] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 17/12 12:05:48,721 WARNING [139939245168384] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 17/12 12:05:48,771 WARNING [139939245168384] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 17/12 12:05:48,822 WARNING [139939245168384] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 17/12 12:05:48,872 WARNING [139939245168384] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 17/12 12:05:48,922 WARNING [139939245168384] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 17/12 12:05:48,973 WARNING [139939245168384] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 17/12 12:05:49,023 WARNING [139939245168384] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 17/12 12:05:49,074 WARNING [139939245168384] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 17/12 12:05:49,124 WARNING [139939245168384] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 17/12 12:05:49,175 WARNING [139939245168384] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 17/12 12:05:49,225 WARNING [139939245168384] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 17/12 12:05:49,275 WARNING [139939245168384] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 17/12 12:05:49,326 WARNING [139939245168384] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 17/12 12:05:49,376 WARNING [139939245168384] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 17/12 12:05:49,427 WARNING [139939245168384] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 17/12 12:05:49,478 WARNING [139939245168384] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 17/12 12:05:49,529 WARNING [139939245168384] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
[ WARN] [1608199549.908950836]: Hardware Notification:Depth stream start failure,1.6082e+12,Error,Hardware Error
 17/12 12:05:54,589 WARNING [139939245168384] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 17/12 12:05:58,152 ERROR [139938481825536] (ds5-options.cpp:86) Asic Temperature value is not valid!
 17/12 12:05:59,153 ERROR [139938481825536] (ds5-options.cpp:86) Asic Temperature value is not valid!
 17/12 12:06:00,154 ERROR [139938481825536] (ds5-options.cpp:86) Asic Temperature value is not valid!




How i can fix it?

**Comment by MartyG-RealSense** [comment]
Case closed as it is being handled at https://github.com/IntelRealSense/realsense-ros/issues/1510
