### ISSUE TITLE
Noetic Release

### ISSUE THREAD

**Issue by fmessmer** [realsenseai/realsense-ros#1577]
sorry, for opening yet another "Noetic Release" issue

I might be missing something, but `realsense2_camera` and `realsense2_description` are still not released into `noetic` - only `librealsense` is released
at least they are not available - neither `main` nor `testing`
http://repositories.ros.org/status_page/ros_noetic_default.html?q=realsense

there have been numerous issues before, but all of them were already closed - **without the packages being released**
- https://github.com/IntelRealSense/realsense-ros/issues/1214
- https://github.com/IntelRealSense/realsense-ros/issues/1423

**Comment by MartyG-RealSense** [comment]
Hi @fmessmer   Official support for ROS1 Noetic was added to the RealSense ROS wrapper in wrapper version **2.2.20**.

https://github.com/IntelRealSense/realsense-ros/releases/tag/2.2.20

**Comment by fmessmer** [comment]
I got that from the related issues...question remains whether `realsense2_camera` package will become available as debian package?
I saw it has been proposed to `rosdistro`
https://github.com/ros/rosdistro/pull/27503
and is part of the distribution file: https://github.com/ros/rosdistro/blob/2934872ef1a23e33e3e0776b20787f726bad6b6f/noetic/distribution.yaml#L4554-L4572

but it cannot be installed because the jobs are failing:
http://build.ros.org/view/Nsrc_uF/job/Nsrc_uF__realsense2_camera__ubuntu_focal__source/

last build log:
http://build.ros.org/view/Nsrc_uF/job/Nsrc_uF__realsense2_camera__ubuntu_focal__source/lastBuild/console

**Comment by MartyG-RealSense** [comment]
I will refer the above question about Debian packages for 2.2.20 to @doronhi the wrapper developer then, as I am not involved in the development side of RealSense.

**Comment by mirkocomparetti-synesis** [comment]
Hello, this will be useful for us as well.

Thanks!

**Comment by doronhi** [comment]
The failing debian build is a very important issue and hopefully will be attended very shortly.

**Comment by dgrnbrg** [comment]
This package is also important to us, as Realsense is supported on noetic (according to intel docs).

**Comment by fmessmer** [comment]
I see a new tag [`2.2.21`](https://github.com/IntelRealSense/realsense-ros/releases/tag/2.2.21) has been created which requires `librealsense2` in version `2.41.0` - will this combination be successfully released into `noetic`?
can someone give a status update or timeline/roadmap for the successful release of `realsense2_camera` into `noetic`?

**Comment by MartyG-RealSense** [comment]
Hi @fmessmer   I will refer your question to @doronhi the RealSense ROS wrapper developer.

**Comment by doronhi** [comment]
librealsense2 version 2.41.0 and realsense2_camera version 2.2.21 are in the process of being released into noetic.
These are the PRs, waiting to be merged and released:
https://github.com/ros/rosdistro/pull/27865
https://github.com/ros/rosdistro/pull/27868

**Comment by MartyG-RealSense** [comment]
Hi @fmessmer   Do you require further assistance with this case, please?  Thanks!

**Comment by fmessmer** [comment]
thanks, @doronhi @MartyG-RealSense 
I'll close this issue once the next noetic sync went through and the packages become available in `main`

**Comment by 8ke8** [comment]
Are syncs typically monthly?  I'm waiting on this one to go through as well

**Comment by fmessmer** [comment]
no clear cycle for the releases....but they are announced here: https://discourse.ros.org/c/release/16/l/latest

**Comment by VincentPelletier1** [comment]
Marking the method 1 as "not working on Noetic" would be a pleasant addition until the solution is pushed.

To those still looking to install the package:
I had success installing and running the package with a simple git clone and catkin_make.

**Comment by MartyG-RealSense** [comment]
Great to hear that your installation in https://github.com/IntelRealSense/realsense-ros/issues/1636 was successful @Plopao

**Comment by fmessmer** [comment]
the packages are also already available in the `ros-testing` repository...it's really just missing a sync...

**Comment by 8ke8** [comment]
There's a sync scheduled for tomorrow apparently

**Comment by fmessmer** [comment]
:point_right: https://discourse.ros.org/t/preparing-for-noetic-sync-2021-01-22/18570 :tada:

**Comment by fmessmer** [comment]
sync is out and thus the packages are available for noetic
thanks
