### ISSUE TITLE
Undistortion color image D455

### ISSUE THREAD

**Issue by Alamoris** [realsenseai/realsense-ros#1580]
I have tried undistorting a color image from a D455 camera and cannot determine if this is necessary. Visually, it is not clear whether these images need to be undistorted, since they already look straight. Topic: /camera/color/image_raw
Does a color camera have such small distortion coefficients that it is imperceptible to the eye, or are they already straightened?

**Comment by MartyG-RealSense** [comment]
Hi @Alamoris   I used **rs-enumerate-devices -c** to check the calibration details of the D455.  It reported that the **Inverse Brown-Conrady** distortion model is used for the color stream profiles.

![image](https://user-images.githubusercontent.com/41145062/102609448-69d29000-4123-11eb-8e97-46a973706a1c.png)

Information about the Inverse Brown-Conrady distortion model can be found in the RealSense **Projection** documentation.

https://dev.intelrealsense.com/docs/projection-in-intel-realsense-sdk-20#section-distortion-models

Information about the coefficients is provided by Dorodnic the RealSense SDK Manager in the discussion in the link below:

https://github.com/IntelRealSense/librealsense/issues/1430#issuecomment-375945916

A notable difference between D455 and D415 / D435 in my tests was that the color coefficients were all zero on D415 and D435, but non-zero on D455 (as shown in the image above).

**Comment by MartyG-RealSense** [comment]
Hi @Alamoris   Do you require further assistance with this case, please?   Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
