### ISSUE TITLE
topic of realsense l515 loss a lot of data !

### ISSUE THREAD

**Issue by zhongxiangzju** [realsenseai/realsense-ros#1582]
Hi, I try to record rgbd images of a moving object using realsense l515. After I launch sensor using
`roslaunch realsense2_camera rs_camera.launch`, topics are listed. But the frame rate is not matched with my setting which is 30 fps. Here is a screenshot of ros output.
![realsense l515 error](https://user-images.githubusercontent.com/38032220/102623224-24db4780-417d-11eb-8a4d-e546e0e316d1.png)
Is it a bug ?

**Comment by zhongxiangzju** [comment]
Name of the subscribed topic is `/camera/aligned_depth_to_color/image_raw`, and output is from `rostopic hz /camera/aligned_depth_to_color/image_raw`

**Comment by doronhi** [comment]
It seems by the realsense2_camera log that exposure time value is set to 2000. That is 200(milliseconds) which means approximately 5 images per second.

**Comment by xiaotaw** [comment]
@zhongxiangzju  I got 14 Hz with exposure time = 2000, and 27 Hz with exposure time = 166.

**Comment by RealSenseSupport** [comment]
Hi,

Will you be needing further help with this?

*If we don’t hear from you in 7 days, this issue will be closed.*

Thanks
