### ISSUE TITLE
T265 Wrong coordinate frame movement

### ISSUE THREAD

**Issue by iamsavva** [realsenseai/realsense-ros#1585]
I am using T265 cameras in ROS, and I have an odd relationship between the `odom_frame` and the `pose_frame`.

`odom_frame` is static, seems to be chosen based on gravity. When I pull up rviz and select `odom_frame` as fixed frame, blue (z) axis of the `odom_frame` is pointing out of the plane. Originally, with the T265 camera on the table vertically, `odom_frame` and `pose_frame` coincide.

according to this image from [this dev site](https://dev.intelrealsense.com/docs/depth-and-tracking-cameras-alignment):
![](https://files.readme.io/29080d9-Tracking_Depth_fixture_image.png)

x-axis should be towards the right camera. However, if I move the camera in this direction, in rviz the `pose_frame` moves in the (-y) direction (opposite of the green arrow) relative to the `odom_frame`. Shouldn't it move in the x axis though, along the red arrow?

If I move the camera up (which according to the image is positive y) in rviz `pose_frame` moves in positive z.
If I move the camera back (which according to the image is positive z) in rviz `pose_frame` moves in negative x.

Am I missing something? My tf tree is untouched, I only `roslaunch` the camera with `rs_t265.launch`. Would appreciate any help!

**Comment by iamsavva** [comment]
These observations are compliant with REP-103, but not the images provided on all intel websites. I guess this has been updated at some point to match ROS conventions?

**Comment by RealSenseSupport** [comment]
Hi,

I believe you are correct. The images are probably outdated. Thanks for catching this.

Will you be needing further help with this?

Thanks

**Comment by iamsavva** [comment]
> Hi,
> 
> I believe you are correct. The images are probably outdated. Thanks for catching this.
> 
> Will you be needing further help with this?
> 
> Thanks

no, that's all, I'm closing the issue, thank you. But it would be quite useful if somebody was to at least link to this issue or make a note on those old posts that the data there is outdated.
