### ISSUE TITLE
Synchronized depth, rgb and pointcloud

### ISSUE THREAD

**Issue by alex-stonebridge** [realsenseai/realsense-ros#1594]
Hi, need to get depth rgb and pointcloud of the same frame. So if I know pixel coordinates in RGB image I will need to know a depth in this pixel and its pointcloud index. 
Which is the best way to do that?
Depth and RGB settings are set to 640x480 both. I have switched on "enable_sync", "align_depth" and "pointcloud" in filters, then probably I should subscribe, using TimeSynchronizer to:
/camera/aligned_depth_to_color/image_raw, 
/camera/color/image_raw, 
/camera/depth/color/points 
But in this case, will pointcloud message be based on align_depth topic? Will my pixels be 1-to-1 from all 3 topics?

**Comment by MartyG-RealSense** [comment]
Hi @alex-stonebridge   The link below states that if the **rs_rgbd.launch** roslaunch method is used then the pointcloud provided by it will be created by the **aligned_depth_to_color** topic and the **color** topic.   

https://github.com/IntelRealSense/realsense-ros/issues/277#issuecomment-363117777

The roslaunch command for rs_rgbd.launch in the RealSense ROS wrapper would be:

**roslaunch realsense2_camera rs_rgbd.launch**

The link below describes the difference between pointclouds generated with **rs_camera** and with **rs_rgbd**.

https://github.com/IntelRealSense/realsense-ros/issues/893
