### ISSUE TITLE
Simulate the working of Realsense l515

### ISSUE THREAD

**Issue by Charan-Karthikeyan** [realsenseai/realsense-ros#1595]
I am trying to create a simulation with the realsense l515 in gazebo and rviz. I cannot see a point cloud data or RGBD for them when I launch the file in rviz. Can someone please point me in the right direction to simulate the workings of the sensor.

Any help would be appreciated

**Comment by RealSenseSupport** [comment]
Hi @Charan-Karthikeyan 

There are quite a bit of discussion with regards to Gazebo with the D400 cameras that may point you in the right direction for L515 here:  https://github.com/IntelRealSense/realsense-ros/issues/1453#issuecomment-736557949

*If we don’t hear from you in 7 days, this issue will be closed.
