### ISSUE TITLE
realsense2_camera: Cannot locate rosdep definition for [ament_lint_common]

### ISSUE THREAD

**Issue by paddygoat** [realsenseai/realsense-ros#1598]
Description:	Ubuntu 20.04.1 LTS
ROS2 Eloquent

tegwyn@tegwyn-CF-H2AS01EDA:~/ros2_ws$ rosdep update
reading in sources list data from /etc/ros/rosdep/sources.list.d
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/osx-homebrew.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/base.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/python.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/rosdep/ruby.yaml
Hit https://raw.githubusercontent.com/ros/rosdistro/master/releases/fuerte.yaml
Query rosdistro index https://raw.githubusercontent.com/ros/rosdistro/master/index-v4.yaml
Skip end-of-life distro "ardent"
Skip end-of-life distro "bouncy"
Skip end-of-life distro "crystal"
Add distro "dashing"
Skip end-of-life distro "eloquent"
Add distro "foxy"
Skip end-of-life distro "groovy"
Skip end-of-life distro "hydro"
Skip end-of-life distro "indigo"
Skip end-of-life distro "jade"
Add distro "kinetic"
Skip end-of-life distro "lunar"
Add distro "melodic"
Add distro "noetic"
Add distro "rolling"
updated cache in /home/tegwyn/.ros/rosdep/sources.cache
tegwyn@tegwyn-CF-H2AS01EDA:~/ros2_ws$ rosdep install -i --from-path src --rosdistro $ROS_DISTRO -y
WARNING: ROS_PYTHON_VERSION is unset. Defaulting to 3
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
realsense2_camera: Cannot locate rosdep definition for [ament_lint_common]
realsense2_description: Cannot locate rosdep definition for [ament_lint_common]
realsense2_camera_msgs: Cannot locate rosdep definition for [ament_lint_common]
tegwyn@tegwyn-CF-H2AS01EDA:~/ros2_ws$

**Comment by MartyG-RealSense** [comment]
Hi @paddygoat    Given that you are using Ubuntu **20.04** instead of 18.04, would it be possible for you to upgrade your ROS2 version from Eloquent to **Foxy**?   I ask this because the first RealSense ROS2 wrapper for Foxy and Ubuntu 20.04 has just been released for use with librealsense **2.41.0**.

https://github.com/IntelRealSense/realsense-ros/releases/tag/3.1.3

https://github.com/IntelRealSense/realsense-ros/tree/foxy

**Comment by paddygoat** [comment]
Yes, I was kind of hoping that this would be the solution. Many thanks @MartyG-RealSense

**Comment by paddygoat** [comment]
Hi @MartyG-RealSense  !!!
I installed and tested ROS2 Foxy.
Followed instructions to install wrapper: 
Step 3: Install Intel® RealSense™ ROS2 wrapper from Sources
Re-boot.
Colcon build fail:

tegwyn@tegwyn-CF-H2AS01EDA:~/ros2_ws_foxy$ colcon build
Starting >>> realsense2_camera_msgs
Finished <<< realsense2_camera_msgs [1.26s]                     
Starting >>> realsense2_camera
Starting >>> realsense2_description
Finished <<< realsense2_description [0.31s]                           
--- stderr: realsense2_camera                         
CMake Warning at CMakeLists.txt:102 (find_package):
  Could not find a configuration file for package "realsense2" that is
  compatible with requested version "2.41.0".

  The following configuration files were considered but not accepted:

    /opt/realsense/lib/cmake/realsense2/realsense2Config.cmake, version: 2.40.0
    /usr/local/lib/cmake/realsense2/realsense2Config.cmake, version: 2.40.0

CMake Error at CMakeLists.txt:104 (message):
  
   Intel RealSense SDK 2.0 is missing, please install it from https://github.com/IntelRealSense/librealsense/releases

---
Failed   <<< realsense2_camera [3.62s, exited with code 1]

Summary: 2 packages finished [5.47s]
  1 package failed: realsense2_camera
  1 package had stderr output: realsense2_camera
tegwyn@tegwyn-CF-H2AS01EDA:~/ros2_ws_foxy$ 

Looks like I need to upgrade to Intel® RealSense™ SDK 2.0 (v2.41.0). How do i do this please?

**Comment by MartyG-RealSense** [comment]
Hi @paddygoat   Could you tell me the computer or computing device that you are using please so that I can advise the appropriate installation method for librealsense 2.41.0? For example, if you are using a PC then you can build librealsense for Ubuntu 20.04 using the instructions in the link below.

https://github.com/IntelRealSense/librealsense/blob/master/doc/distribution_linux.md

Once the new librealsense version has been installed then you should rebuild the RealSense ROS2 Foxy wrapper.

**Comment by paddygoat** [comment]
@MartyG-RealSense  .... I am using a Panosonic CF-H2 PC running Ubuntu 20.04.
I used the link : https://github.com/IntelRealSense/librealsense/blob/master/doc/distribution_linux.md to install librealsense 2.40.0 with no problems and tested ok.
The problem I now have is that it needs to be upgraded to librealsense 2.41.0 for compatibility with ROS2 and Ubuntu 20.04 and  librealsense 2.41.0 is only in '**pre-release**' and not '**release**'. I'm not expert with Github, so need to know how to upgrade using the pre-release please !!!!
Many thanks and happy new year.

**Comment by MartyG-RealSense** [comment]
You can build librealsense 2.41.0 with **CMake** from source code instead of packages using the **RSUSB** installation method.  This method requires an internet connection but is not dependent on Linux versions or kernel versions and does not require patching.

Instructions for the RSUSB method can be found in the link below.

https://github.com/IntelRealSense/librealsense/issues/6964#issuecomment-707501049

For installation on your PC, use the instruction below for step 5 to install librealsense without including Python and CUDA support.

**cmake ../ -DFORCE_RSUSB_BACKEND=ON  -DCMAKE_BUILD_TYPE=release -DBUILD_EXAMPLES=true -DBUILD_GRAPHICAL_EXAMPLES=true** 

Only go as far as Step 6 for a non-Python build.

**Comment by MartyG-RealSense** [comment]
Hi @paddygoat  Do you require further assistance with this case, please?   Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.

**Comment by jhordanhiro** [comment]
Hey I have a similar error 
 Ubuntu 20.04.6 LTS
ROS2  foxy ,  ROS NOETIC 
Intel RealSense Viewer v2.54.1
Camera  ' Intel Real Sense D405 
i am trying to follow this : 

https://ryostudy.com/2023/01/21/realsense-d405-topic%E3%82%92ros1-rviz%E3%81%AB%E3%81%A6%E8%A1%A8%E7%A4%BA%E3%81%99%E3%82%8B/#Realsense 

- Realsense viewer works normally , but folling this https://github.com/IntelRealSense/realsense-ros#legacy . i have that error  
- 
user@user-HP-Laptop-15-dw0xxx:~/librealsense$ rosdep install -i --from-path src --rosdistro $ROS_DISTRO --skip-keys=librealsense2 -y
#All required rosdeps installed successfully

user@user-HP-Laptop-15-dw0xxx:~/librealsense$ colcon build
Starting >>> librealsense2
--- stderr: librealsense2                              
/sbin/ldconfig.real: Can't create temporary cache file /etc/ld.so.cache~: Permission denied
/sbin/ldconfig.real: Can't create temporary cache file /etc/ld.so.cache~: Permission denied
CMake Error at tools/realsense-viewer/cmake_install.cmake:69 (file):
  file INSTALL cannot set permissions on
  "/home/user/Documents/librealsense2/presets": Operation not permitted.
Call Stack (most recent call first):
  tools/cmake_install.cmake:50 (include)
  cmake_install.cmake:131 (include)


---
Failed   <<< librealsense2 [1.33s, exited with code 1]

Summary: 0 packages finished [3.77s]
  1 package failed: librealsense2
  1 package had stderr output: librealsense2

**Comment by MartyG-RealSense** [comment]
Hi @jhordanhiro  The ROS wrapper link that you posted leads to the ROS2 version of the RealSense ROS wrapper.  If you are using ROS1 Noetic then you should build the ROS1 wrapper at the link below.

https://github.com/IntelRealSense/realsense-ros/tree/ros1-legacy

However, the official ROS1 wrapper does not support D405 (the ROS2 wrapper for Humble and Iron does).  There is a custom 'forked' version of the wrapper with D405 support created by a RealSense user at the link below.

https://github.com/rjwb1/realsense-ros/tree/development

It is also possible to modify the official ROS1 wrapper to add D405 support using a method described at https://github.com/IntelRealSense/realsense-ros/issues/2582#issuecomment-1371133133
