### ISSUE TITLE
show_center_depth.py pixel point.

### ISSUE THREAD

**Issue by junhui519** [realsenseai/realsense-ros#1608]
Hi, this show_center_depth.py works well. And as far as I know, this shows the distance between the closest point of the image. But I want to fix the point of pixel at the middle of the image. What should I change to make it out?

**Comment by MartyG-RealSense** [comment]
Hi @junhui519   The use of the word 'center' in the script name **show_center_depth.py** suggests to me that it is reading the depth value at the center of the camera's view.   @doronhi can clarify whether this is the case.

The Python depth script provided in the **my_depth_subscriber.txt** file in the link below may also be useful to you.

https://github.com/IntelRealSense/realsense-ros/issues/714#issuecomment-561036465
