### ISSUE TITLE
ROI on infra and RGB images

### ISSUE THREAD

**Issue by aorait** [realsenseai/realsense-ros#1612]
Hello,
I want to obtain an ROI (Region of Interest) in the infra and RGB images from the camera instead of the entire image. I am aware that we can do this using opencv but I am looking for a solution at the firmware level as this would reduce the overall data produced. 

Is there a dynamic reconfigure parameter which supports this? I saw there exists Auto exposure ROI params but I want to crop the field of view as well.

**Comment by doronhi** [comment]
None of the realsense devices support that option.

**Comment by aorait** [comment]
Ok thanks
