### ISSUE TITLE
Fail to make infrared camera stream in RGB for D455

### ISSUE THREAD

**Issue by wwtinwhu** [realsenseai/realsense-ros#1615]
Hello,  my launch code is as follows.
`roslaunch realsense2_camera rs_camera.launch enable_infra:=true infra_rgb:=true`
There are two problems. First,  infrared image is not in RGB,  still in infrared mode. Second, there is  one infrared image output, the topic is /camera/infra/image_raw. What I want is /camera/infra1/image_rect_raw and /camera/infra2/image_rect_raw.  
Ask for help, thanks!

**Comment by MartyG-RealSense** [comment]
Hi @wwtinwhu   The RealSense ROS wrapper documentation states for **infra_rgb** that "This feature is only supported by Realsense sensors with RGB streams available from the infra cameras".

On the D455 model, it must have firmware version **5.12.8.200** or newer installed in order for the RGB8 color mode to be available from the left infrared imager. 

https://github.com/IntelRealSense/librealsense/issues/7897#issuecomment-736370516

Do you have firmware **5.12.8.200** or newer installed in your camera please?

**Comment by wwtinwhu** [comment]
> Hi @wwtinwhu The RealSense ROS wrapper documentation states for **infra_rgb** that "This feature is only supported by Realsense sensors with RGB streams available from the infra cameras".
> 
> On the D455 model, it must have firmware version **5.12.8.200** or newer installed in order for the RGB8 color mode to be available from the left infrared imager.
> 
> [IntelRealSense/librealsense#7897 (comment)](https://github.com/IntelRealSense/librealsense/issues/7897#issuecomment-736370516)
> 
> Do you have firmware **5.12.8.200** or newer installed in your camera please?

Hi @MartyG-RealSense , I checked the firmware version of my D455 in the Intel RealSense Viewer. The version is 05.12.10.00. So the answer is yes.

**Comment by MartyG-RealSense** [comment]
Thanks very much for the information.

Reading the documentation on the front page of the RealSense ROS wrapper, it seems that **/camera/infra/image_raw** is a topic that is used on the L515 camera model.  So otherwise, I believe that the separate **infra1** and **infra2** topics would be used for a model such as D455.

If the color is coming from the left infrared sensor then I would expect **infra1** to be the appropriate topic to use.

/camera/infra1/camera_info
/camera/infra1/image_rect_raw

What image do you get if you visualize **/camera/infra1/image_rect_raw** after having enabled infra_rgb please?

**Comment by wwtinwhu** [comment]
> Thanks very much for the information.
> 
> Reading the documentation on the front page of the RealSense ROS wrapper, it seems that **/camera/infra/image_raw** is a topic that is used on the L515 camera model. So otherwise, I believe that the separate **infra1** and **infra2** topics would be used for a model such as D455.
> 
> If the color is coming from the left infrared sensor then I would expect **infra1** to be the appropriate topic to use.
> 
> /camera/infra1/camera_info
> /camera/infra1/image_rect_raw
> 
> What image do you get if you visualize **/camera/infra1/image_rect_raw** after having enabled infra_rgb please?

Yes, you are right. Separate infra1 and infra2 topics can be used for a model for D455.  When I tried code as follows, I can get the topic /camera/infra1/image_rect_raw and /camera/infra2/image_rect_raw.
`roslaunch realsense2_camera rs_camera.launch enable_infra1:=true enable_infra2:=true` 
And visualization is like this. 
![realsense](https://user-images.githubusercontent.com/28035224/104028828-293ad380-5204-11eb-84f1-cbdce57e4b43.png)
By the way, Are this two images in infrared mode? I think it is more like in gray mode.
However, when I tried code as follows, these two topics are not shown.
`roslaunch realsense2_camera rs_camera.launch enable_infra1:=true enable_infra2:=true infra_rgb:=true`

**Comment by MartyG-RealSense** [comment]
The way I read the instructions is that your original roslaunch instruction is correct, using **enable_infra** instead of individually enabling infra1 and infra2:

**roslaunch realsense2_camera rs_camera.launch enable_infra:=true infra_rgb:=true**

But try visualizing **/camera/infra1/image_rect_raw** in RViz after using that roslaunch instruction.

**Comment by wwtinwhu** [comment]
> The way I read the instructions is that your original roslaunch instruction is correct, using **enable_infra** instead of individually enabling infra1 and infra2:
> 
> **roslaunch realsense2_camera rs_camera.launch enable_infra:=true infra_rgb:=true**
> 
> But try visualizing **/camera/infra1/image_rect_raw** in RViz after using that roslaunch instruction.

That's the problem. I was mentioned in the first floor. When I tried code as follows, as the instructions.
`roslaunch realsense2_camera rs_camera.launch enable_infra:=true infra_rgb:=true`
There is no topic named /camera/infra1/image_rect_raw or /camera/infra2/image_rect_raw. The topic shown related to it is /camera/infra/image_raw. I suppose this is a bug for the D455. 
But for the current use, I can use the code as follows to get the stereo image in infrared mode.
`roslaunch realsense2_camera rs_camera.launch enable_infra1:=true enable_infra2:=true`.

------------------------------------------------------------------------------------------------------------------------
For the another question you haven't answered me @MartyG-RealSense . Why this infrared image look more like in the gray mode?

**Comment by MartyG-RealSense** [comment]
It is normal for infrared to be greyscale in the default **Y8** infrared format.  On devices where color from the left infrared imager is supported (D415 and D455), color modes such as **RGB8** can be used for images with color in them.

Looking through the wrapper release notes, it states the following information in the notes for RealSense ROS wrapper **2.2.20** from November 2020:

**get rgb stream from infrared sensor (applies to D415) - use infra_rgb parameter.**

It only mentions support of the infra_rgb parameter for D415 and not D455.

**Comment by wwtinwhu** [comment]
> It is normal for infrared to be greyscale in the default **Y8** infrared format. On devices where color from the left infrared imager is supported (D415 and D455), color modes such as **RGB8** can be used for images with color in them.
> 
> Looking through the wrapper release notes, it states the following information in the notes for RealSense ROS wrapper **2.2.20** from November 2020:
> 
> **get rgb stream from infrared sensor (applies to D415) - use infra_rgb parameter.**
> 
> It only mentions support of the infra_rgb parameter for D415 and not D455.

I get the two points  you mentioned. Thank you very much for your patient answer.  Looking forward to the new version that supports getting rgb stream from infrared sensor for D455.  Would you mind informing me when it's done ?  then, I will close this issue.

**Comment by MartyG-RealSense** [comment]
I will highlight this case to @doronhi the RealSense ROS wrapper developer.

Hi @doronhi  Would it be possible for the **infra_rgb** parameter to support D455 in a future wrapper update now that D455 has support for color from the left infrared imager with firmware **5.12.8.200** and newer?

**Comment by wwtinwhu** [comment]
> I will highlight this case to @doronhi the RealSense ROS wrapper developer.
> 
> Hi @doronhi Would it be possible for the **infra_rgb** parameter to support D455 in a future wrapper update now that D455 has support for color from the left infrared imager with firmware **5.12.8.200** and newer?

Thanks! @MartyG-RealSense @doronhi

**Comment by doronhi** [comment]
It seems there is a confusion here.
First, there is no difference in the wrapper, regarding this aspect at least, between D415 and D455. The feature works for both cameras. (Tested with Ubuntu 16, ROS kinetic)
As can be seen when running `rs-enumerate-devices` the infrared sensor with RGB is "Infrared" for example, the line:
`Infrared	  640x480	@ 30Hz	   RGB8`
as opposed to the "Infrared1", "Infrared2" sensors for Y8 and Y16 formats, as seen in the printed line:
 `Infrared 1	  640x480	@ 30Hz	   Y8`

That is why when referring to the rgb format of the infrared sensor we omit the sensor's index and also why you get the "rgb" image in the `/camera/infra/image_raw` topic and the Y8 format in the `/camera/infra1/camera_info` and `/camera/infra2/camera_info` topics.

Regarding the issues you describe in your first post:
1. The topic `/camera/infra/image_raw` comes from the same physical sensor as `/camera/infra1/image_raw`.
2. The image is in RGB format but not as pretty as the image from the RGB sensor. You can also see them in the `realsense-viewer`

**Comment by wwtinwhu** [comment]
> It seems there is a confusion here.
> First, there is no difference in the wrapper, regarding this aspect at least, between D415 and D455. The feature works for both cameras. (Tested with Ubuntu 16, ROS kinetic)
> As can be seen when running `rs-enumerate-devices` the infrared sensor with RGB is "Infrared" for example, the line:
> `Infrared 640x480 @ 30Hz RGB8`
> as opposed to the "Infrared1", "Infrared2" sensors for Y8 and Y16 formats, as seen in the printed line:
> `Infrared 1 640x480 @ 30Hz Y8`
> 
> That is why when referring to the rgb format of the infrared sensor we omit the sensor's index and also why you get the "rgb" image in the `/camera/infra/image_raw` topic and the Y8 format in the `/camera/infra1/camera_info` and `/camera/infra2/camera_info` topics.
> 
> Regarding the issues you describe in your first post:
> 
> 1. The topic `/camera/infra/image_raw` comes from the same physical sensor as `/camera/infra1/image_raw`.
> 2. The image is in RGB format but not as pretty as the image from the RGB sensor. You can also see them in the `realsense-viewer`

Thanks for your explanation @doronhi . I get that.  But I find another problem that why the color of the light is strange in RGB8 mode? 
![2021-01-12 21-50-23 的屏幕截图](https://user-images.githubusercontent.com/28035224/104323884-ad9d9700-5521-11eb-8628-cb0ca5ebb4fa.png)

**Comment by MartyG-RealSense** [comment]
Hi @wwtinwhu    That coloration of the lights has been encountered by another RealSense user in RGB8 mode on D455:

https://github.com/IntelRealSense/librealsense/issues/7934#issuecomment-741612769

**Comment by wwtinwhu** [comment]
> Hi @wwtinwhu That coloration of the lights has been encountered by another RealSense user in RGB8 mode on D455:
> 
> [IntelRealSense/librealsense#7934 (comment)](https://github.com/IntelRealSense/librealsense/issues/7934#issuecomment-741612769)

Thanks.
