### ISSUE TITLE
Is the value of depth_scale invariant?

### ISSUE THREAD

**Issue by Hiroaki-K4** [realsenseai/realsense-ros#1616]
Hi!
I have a question about depth_scale. If I continue to use the same realsense, will the depth_scale value change? I use realsense D455.
As a result of the following processing, I get a value of 0.0010000000474974513 for depth_scale every time.
```
profile = pipeline.start(config)
depth_scale = profile.get_device().first_depth_sensor().get_depth_scale()
```
Thanks!

**Comment by MartyG-RealSense** [comment]
Hi @Hiroaki-K4   The depth unit scale (with a default value of **0.001**) remains fixed unless its scale value is deliberately altered (for example, to 0.0001).

**Comment by Hiroaki-K4** [comment]
@MartyG-RealSense 
ok. Thank you!
