### ISSUE TITLE
Question about frame_id

### ISSUE THREAD

**Issue by Hiroaki-K4** [realsenseai/realsense-ros#1622]
Hi!
I'm using rgb data from / camera / color / image_raw. The frame_id in the header is always camera_colo_optical_frame. I want the order in which the images were created as frame_id. For example, the first is 001 and the second is 002. Is there a way to set the frame_id like this?
Thanks!

**Comment by doronhi** [comment]
No, there isn't.
That is not the purpose of frame_id in ROS.

**Comment by Hiroaki-K4** [comment]
ok. I understood. Thanks.
