### ISSUE TITLE
Problem running roslaunch 

### ISSUE THREAD

**Issue by eltonhcchan** [realsenseai/realsense-ros#1623]
I've tried to run roslaunch and got the following errors.

c:\catkin_ws>roslaunch realsense2_camera rs_camera.launch filters:=pointcloud
... logging to C:\Users\Elton\.ros\log\d205d730-5679-11eb-bb36-842afdc7fec3\roslaunch-HP-13408.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.
started roslaunch server http://127.0.0.1:49320/

SUMMARY
========

PARAMETERS
 * /camera/realsense2_camera/accel_fps: 250
 * /camera/realsense2_camera/accel_frame_id: camera_accel_frame
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: False
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/allow_no_texture_points: False
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/calib_odom_file:
 * /camera/realsense2_camera/clip_distance: -2.0
 * /camera/realsense2_camera/color_fps: 30
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: 480
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: 640
 * /camera/realsense2_camera/confidence_fps: 30
 * /camera/realsense2_camera/confidence_height: 480
 * /camera/realsense2_camera/confidence_width: 640
 * /camera/realsense2_camera/depth_fps: 30
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: 480
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: 640
 * /camera/realsense2_camera/device_type:
 * /camera/realsense2_camera/enable_accel: False
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_confidence: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye1: False
 * /camera/realsense2_camera/enable_fisheye2: False
 * /camera/realsense2_camera/enable_fisheye: False
 * /camera/realsense2_camera/enable_gyro: False
 * /camera/realsense2_camera/enable_infra1: False
 * /camera/realsense2_camera/enable_infra2: False
 * /camera/realsense2_camera/enable_infra: False
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_pose: False
 * /camera/realsense2_camera/enable_sync: False
 * /camera/realsense2_camera/filters: pointcloud
 * /camera/realsense2_camera/fisheye1_frame_id: camera_fisheye1_f...
 * /camera/realsense2_camera/fisheye1_optical_frame_id: camera_fisheye1_o...
 * /camera/realsense2_camera/fisheye2_frame_id: camera_fisheye2_f...
 * /camera/realsense2_camera/fisheye2_optical_frame_id: camera_fisheye2_o...
 * /camera/realsense2_camera/fisheye_fps: 30
 * /camera/realsense2_camera/fisheye_frame_id: camera_fisheye_frame
 * /camera/realsense2_camera/fisheye_height: 480
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: 640
 * /camera/realsense2_camera/gyro_fps: 400
 * /camera/realsense2_camera/gyro_frame_id: camera_gyro_frame
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/imu_optical_frame_id: camera_imu_optica...
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra_fps: 30
 * /camera/realsense2_camera/infra_height: 480
 * /camera/realsense2_camera/infra_rgb: False
 * /camera/realsense2_camera/infra_width: 640
 * /camera/realsense2_camera/initial_reset: False
 * /camera/realsense2_camera/json_file_path:
 * /camera/realsense2_camera/linear_accel_cov: 0.01
 * /camera/realsense2_camera/odom_frame_id: camera_odom_frame
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/pose_frame_id: camera_pose_frame
 * /camera/realsense2_camera/pose_optical_frame_id: camera_pose_optic...
 * /camera/realsense2_camera/publish_odom_tf: True
 * /camera/realsense2_camera/publish_tf: True
 * /camera/realsense2_camera/rosbag_filename:
 * /camera/realsense2_camera/serial_no:
 * /camera/realsense2_camera/tf_publish_rate: 0.0
 * /camera/realsense2_camera/topic_odom_in: odom_in
 * /camera/realsense2_camera/unite_imu_method:
 * /camera/realsense2_camera/usb_port_id:
 * /rosdistro: noetic
 * /rosversion: 1.15.9

NODES
  /camera/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)

auto-starting new master
process[master]: started with pid [11972]
ROS_MASTER_URI=http://127.0.0.1:11311
setting /run_id to d205d730-5679-11eb-bb36-842afdc7fec3
process[rosout-1]: started with pid [16044]
started core service [/rosout]
process[camera/realsense2_camera_manager-2]: started with pid [2928]
process[camera/realsense2_camera-3]: started with pid [1892]
[ INFO] [1610636681.996377300]: Initializing nodelet with 8 worker threads.
**[ERROR] [1610636682.763418900]: Failed to load nodelet [/camera/realsense2_camera] of type [realsense2_camera/RealSenseNodeFactory] even after refreshing the cache: Failed to load library C:/catkin_ws/devel\bin/realsense2_camera.dll. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = C:/catkin_ws/devel\bin/realsense2_camera.dll)
[ERROR] [1610636682.763808200]: The error before refreshing the cache was: Failed to load library C:/catkin_ws/devel\bin/realsense2_camera.dll. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = C:/catkin_ws/devel\bin/realsense2_camera.dll)**
[FATAL] [1610636682.767714000]: Failed to load nodelet '/camera/realsense2_camera` of type `realsense2_camera/RealSenseNodeFactory` to manager `realsense2_camera_manager'
←[31m[camera/realsense2_camera-3] process has died [pid 1892, exit code 4294967295, cmd c:\opt\ros\noetic\x64\lib\nodelet\nodelet.exe load realsense2_camera/RealSenseNodeFactory realsense2_camera_manager __name:=realsense2_camera __log:=C:\Users\username\.ros\log\d205d730-5679-11eb-bb36-842afdc7fec3\camera-realsense2_camera-3.log].
log file: C:\Users\username\.ros\log\d205d730-5679-11eb-bb36-842afdc7fec3\camera-realsense2_camera-3*.log←[0m
^C
c:\catkin_ws>
c:\catkin_ws>[camera/realsense2_camera_manager-2] killing on exit
SUCCESS: The process with PID 2928 (child process of PID 13408) has been terminated.
[rosout-1] killing on exit
SUCCESS: The process with PID 16044 (child process of PID 13408) has been terminated.
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

Anyone knows how to fix it? Anyone can successfully running ROS wrapper on Windows 10?

I am using realsense2_camera 2.2.21 and librealsense2 2.40 from vcpkg

**Comment by MartyG-RealSense** [comment]
Hi @eltonhcchan   I researched your question and located a past case that had the same process-ending fatal error that you experienced when the pointcloud filter was used.

**Failed to load nodelet '/camera/realsense2_cameraof typerealsense2_camera/RealSenseNodeFactoryto managerrealsense2_camera_manager'
←[31m[camera/realsense2_camera-3] process has died**

**Doronhi** the RealSense ROS developer provides advice about this problem in point number '3' of the comment linked to below (skip past points 1 and 2).

https://github.com/IntelRealSense/realsense-ros/issues/648#issuecomment-469277045

I would recommend building librealsense on Windows using the automated installer file in the **Assets** file list on the SDK **Releases** page if possible, as doing so with vcpkg is known to have problems for some RealSense users.

If you are using RealSense ROS wrapper version **2.2.21** then it is recommended to match it to librealsense version **2.41.0** instead of the 2.40.0 version that you are currently using.  If you need to use librealsense 2.40.0 then please match it to RealSense ROS wrapper version **2.2.20**.

https://github.com/IntelRealSense/librealsense/releases/tag/v2.41.0

If you reinstall librealsense then you will need to rebuild the RealSense ROS wrapper afterward.

If you need to install librealsense with vcpkg because the installer file is not an option for you then I will point you to guidance for doing so successfully.

![image](https://user-images.githubusercontent.com/41145062/104631386-1442c200-5694-11eb-8e49-679734876f5a.png)

**Comment by eltonhcchan** [comment]
@MartyG-RealSense  oh yes, I installed librealsense v2.40.0 from vcpkg, but using RealSense ROS wrapper version 2.2.21.  As vcpkg is not yet updated to v2.41.0, are there any other method to install it?

**Comment by MartyG-RealSense** [comment]
If you are using Windows then the method mentioned above of downloading and running an installer file from the librealsense SDK's **Releases** page is the easiest and most problem-free way to install.

The SDK can also be built from source code on Windows with **CMake**.

https://github.com/IntelRealSense/librealsense/blob/master/doc/installation_windows.md

The majority of that installation guide involves a method for adding metadata support.  This section may be skipped though, as metadata support can be easily added from within the RealSense Viewer program instead.

**Comment by eltonhcchan** [comment]
@MartyG-RealSense , I choose to install the SDK using Windows installer. However, when I run the "catkin_make clean", the following errors are encountered.

-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
CMake Error at realsense-ros/realsense2_camera/CMakeLists.txt:41 (find_package):
  Could not find a package configuration file provided by "realsense2" with
  any of the following names:

    realsense2Config.cmake
    realsense2-config.cmake

  Add the installation prefix of "realsense2" to CMAKE_PREFIX_PATH or set
  "realsense2_DIR" to a directory containing one of the above files.  If
  "realsense2" provides a separate development package or SDK, be sure it has
  been installed.

I've tried to add path in the CMakeLists.txt but there is no cmake file in "C:\Program Files (x86)\Intel RealSense SDK 2.0". It seems have to use the master source and setup realsense2 as you mentioned in your link. Unfortunately, I still encountered above path definition problem. Further, I've tried to add path in the CMakeLists file but not work. What is missing? Please advise.

**Comment by MartyG-RealSense** [comment]
I had a past ROS installation case with the **Could not find a package configuration file provided by "realsense2" with
any of the following names** error on Windows in November 2020.  The **catkin_make clean** instruction has caused problems for others too, and on Linux as well.

https://github.com/IntelRealSense/realsense-ros/issues/1520#issuecomment-733179265

In the above link, the solution that the RealSense user found to get it working was to input the command below:

**rosdep install --from-paths src --ignore-src -r -y**

It looks as though that command would be input **before** inputting catkin_make clean

And then after **catkin_make clean** the subsequent instructions to input on Windows would be:

**catkin_make -DCATKIN_ENABLE_TESTING=False -DCMAKE_BUILD_TYPE=Release
catkin_make install
devel\setup.bat**

Typically, building the RealSense ROS wrapper from source seems to be the solution to this error for a number of people, though you are already doing that.  A contributor in the link below offered the advice that deleting the **build** folder in the catkin_ws and then re-running **catkin_make** worked for them.

https://github.com/IntelRealSense/realsense-ros/issues/280

**Comment by eltonhcchan** [comment]
@MartyG-RealSense 

It seems the rosdep install command revealed the fact that there is no definition of librealsense for Windows

c:\catkin_ws>rosdep install --from-paths c:\catkin_ws\src --ignore-src -r -y
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
realsense2_camera: No definition of [librealsense2] for OS [windows]
Continuing to install resolvable dependencies...
#All required rosdeps installed successfully

I've tried to run catkin_make clean but still it cannot find the realsense cmake files. This problem was not seen when using vcpkg to install librealsense.

**Comment by MartyG-RealSense** [comment]
I located a past case where this error occurred.

https://github.com/IntelRealSense/realsense-ros/issues/808

It sounds as though it is referring to the **package based** method of installing librealsense and the RealSense ROS wrapper together (**Method 1**) rather than building the wrapper from source code (**Method 2**, the method you have used).

Given that the wrapper installation instructions make reference to a choice between building librealsense with vcpkg or by building it from source code, I wonder if building librealsense from source code using CMake may work out better than using the Windows automated installer file.

********************

Otherwise, if you have previously been successful in installing SDK 2.40.0 with vcpkg, perhaps you could return to that method and use RealSense ROS wrapper version **2.2.20** with it (the wrapper verson compatible with SDK 2.40.0).

https://github.com/IntelRealSense/realsense-ros/releases/tag/2.2.20

**Comment by eltonhcchan** [comment]
@MartyG-RealSense thx for your help. I've different combinations but still it cannot find the .make files. I think there may be some path definition missing. May try again later.

**Comment by MartyG-RealSense** [comment]
Okay, please keep me updated.  Good luck!

**Comment by MartyG-RealSense** [comment]
Hi @eltonhcchan  Do you have an update that you can provide about this case, please?   Thanks!

**Comment by eltonhcchan** [comment]
@MartyG-RealSense I think I will try it later. BTW, I've found RTAP-Map working with L515 but need to lower the firmware.

**Comment by MartyG-RealSense** [comment]
Thanks very much for the information @eltonhcchan  - good luck!

**Comment by MartyG-RealSense** [comment]
Hi @eltonhcchan  Do you require further assistance with this case, please?   Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.

**Comment by sivaeinfo** [comment]
Hi, Actually my project is deep object pose estimation from (https://github.com/yehengchen/DOPE-ROS-D435) for object and human hand. For that I have tried, the below packages. Now I am facing few errors which I listed here
![Screenshot from 2021-05-04 02-14-17](https://user-images.githubusercontent.com/72197828/116966608-97f1e000-ac7e-11eb-9514-b51f04d7dabe.png)
![Screenshot from 2021-05-04 02-14-33](https://user-images.githubusercontent.com/72197828/116966612-99230d00-ac7e-11eb-9fd2-4891c2e3cc87.png)
![Screenshot from 2021-05-04 02-14-39](https://user-images.githubusercontent.com/72197828/116966614-9a543a00-ac7e-11eb-8478-93af361eb357.png)


.
![Screenshot from 2021-05-04 02-14-14](https://user-images.githubusercontent.com/72197828/116966598-91636880-ac7e-11eb-8306-56ab0b30e025.png)

===================================================
Errors are 
--------------------------------------
i) roslaunch realsense2_camera rs_rgbd.launch  # Publishes RGB images to `/camera/color/image_raw`

process[camera/realsense2_camera_manager-1]: started with pid [3429]
process[camera/realsense2_camera-2]: started with pid [3430]
process[camera/color_rectify_color-3]: started with pid [3431]
process[camera/points_xyzrgb_hw_registered-4]: started with pid [3436]
[ INFO] [1620108763.382160336]: Initializing nodelet with 8 worker threads.
[ INFO] [1620108763.525868202]: RealSense ROS v2.2.7
[ INFO] [1620108763.525912472]: Running with LibRealSense v2.44.0
[ INFO] [1620108763.782599190]: getParameters...
[ INFO] [1620108763.829140477]: setupDevice...
[ INFO] [1620108763.829192188]: JSON file is not provided
[ INFO] [1620108763.829239499]: ROS Node Namespace: camera
[ INFO] [1620108763.829274609]: Device Name: Intel RealSense D435I
[ INFO] [1620108763.829299691]: Device Serial No: 923322073096
[ INFO] [1620108763.829319932]: Device FW version: 05.12.13.50
[ INFO] [1620108763.829349756]: Device Product ID: 0x0B3A
[ INFO] [1620108763.829367252]: Enable PointCloud: Off
[ INFO] [1620108763.829380406]: Align Depth: On
[ INFO] [1620108763.829404377]: Sync Mode: On
[ INFO] [1620108763.829524892]: Device Sensors: 
[ INFO] [1620108763.829617426]: Stereo Module was found.
[ INFO] [1620108763.829658363]: RGB Camera was found.
[ INFO] [1620108763.829740886]: Motion Module was found.
[ INFO] [1620108763.829818176]: (Fisheye, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1620108763.829846209]: (Fisheye, 1) sensor isn't supported by current device! -- Skipping...
[ INFO] [1620108763.829882602]: (Fisheye, 2) sensor isn't supported by current device! -- Skipping...
[ INFO] [1620108763.829919924]: (Pose, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1620108763.829949349]: Setting Dynamic reconfig parameters.
/opt/ros/melodic/lib/nodelet/nodelet: symbol lookup error: /home/bit/catkin_ws/devel/lib//librealsense2_camera.so: undefined symbol: _ZN20ddynamic_reconfigure19DDynamicReconfigure16registerVariableIiEEvRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEET_RKN5boost8functionIFvSA_EEES9_SA_SA_S9_
[camera/realsense2_camera_manager-1] process has died [pid 3429, exit code 127, cmd /opt/ros/melodic/lib/nodelet/nodelet manager __name:=realsense2_camera_manager __log:=/home/bit/.ros/log/9b9f0040-ac9f-11eb-9fb1-d4bed9944d8b/camera-realsense2_camera_manager-1.log].
log file: /home/bit/.ros/log/9b9f0040-ac9f-11eb-9fb1-d4bed9944d8b/camera-realsense2_camera_manager-1*.log
[camera/points_xyzrgb_hw_registered-4] process has finished cleanly
log file: /home/bit/.ros/log/9b9f0040-ac9f-11eb-9fb1-d4bed9944d8b/camera-points_xyzrgb_hw_registered-4*.log
[camera/realsense2_camera-2] process has finished cleanly
log file: /home/bit/.ros/log/9b9f0040-ac9f-11eb-9fb1-d4bed9944d8b/camera-realsense2_camera-2*.log

------------------------
ii) roslaunch dope dope.launch [config:=/path/to/my_config.yaml]  # Config file is optional; default is `config_pose.yaml`

process[dope-1]: started with pid [3678]
Traceback (most recent call last):
  File "/home/bit/catkin_ws/src/Deep_Object_Pose/nodes/dope", line 19, in <module>
    import tf.transformations
  File "/opt/ros/melodic/lib/python2.7/dist-packages/tf/__init__.py", line 30, in <module>
    from tf2_ros import TransformException as Exception, ConnectivityException, LookupException, ExtrapolationException
  File "/opt/ros/melodic/lib/python2.7/dist-packages/tf2_ros/__init__.py", line 38, in <module>
    from tf2_py import *
  File "/opt/ros/melodic/lib/python2.7/dist-packages/tf2_py/__init__.py", line 38, in <module>
    from ._tf2 import *
ImportError: dynamic module does not define module export function (PyInit__tf2)
[dope-1] process has died [pid 3678, exit code 1, cmd /home/bit/catkin_ws/src/Deep_Object_Pose/nodes/dope __name:=dope __log:=/home/bit/.ros/log/9b9f0040-ac9f-11eb-9fb1-d4bed9944d8b/dope-1.log].
log file: /home/bit/.ros/log/9b9f0040-ac9f-11eb-9fb1-d4bed9944d8b/dope-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done
bit@bit-OptiPlex-990:~$

**Comment by MartyG-RealSense** [comment]
Hi @sivaeinfo   It is important to match a particular RealSense ROS wrapper version as closely as possible with the librealsense version listed on that wrapper version's release notes.  Your log indicates that you are using the very old ROS wrapper version 2.2.7 with the recent librealsense version 2.44.0.

For librealsense 2.44.0, ROS wrapper version **2.2.24** should be built for it.

https://github.com/IntelRealSense/realsense-ros/releases/tag/2.2.24

**Comment by sivaeinfo** [comment]
Hi @MartyG-RealSense Will you explain how do I update the ROS wrapper 2.2.7 to ROS wrapper 2.2.2 in my package. Also how can I find the current ROS wrapper version in my linux system.

**Comment by sivaeinfo** [comment]
Hi, Please help me to identify the ddynamic_reconfigure for ROS melodic.

**Comment by MartyG-RealSense** [comment]
@sivaeinfo  Could you try using the command below please to install ddynamic_reconfigure for Melodic:

**sudo apt-get update apt-get install ros-melodic-ddynamic-reconfigure**

**Comment by sivaeinfo** [comment]
Will you explain how do I update the ROS wrapper 2.2.7 to ROS wrapper 2.2.2 in my package. Also how can I find the current ROS wrapper version in my linux system.

**Comment by MartyG-RealSense** [comment]
@sivaeinfo  I believe that you can upgrade by deleting the whole catkin workspace (**/catkin_ws**) and then following the wrapper installation instructions to create the /catkin_ws workspace folder again and build the wrapper within it.

The currently installed ROS wrapper version is indicated in the second half of the roslaunch log, below the line 'Initializing nodelet with 8 worker threads'.

![image](https://user-images.githubusercontent.com/41145062/117036459-5eac8500-acfd-11eb-9541-aa760b3bfc05.png)

**Comment by sivaeinfo** [comment]
I have made all the procedure in this package (https://github.com/yehengchen/DOPE-ROS-D435/tree/6125a8453c922892f9eac7faf8011661d52c875c). It works fine upto this steps.
----------------
**Installing Realsense-ros
catkin workspace
mkdir -p ~/catkin_ws/src
cd ~/catkin_ws/src/
Download realsense-ros pkg
git clone https://github.com/IntelRealSense/realsense-ros.git
cd realsense-ros/
git checkout `git tag | sort -V | grep -P "^\d+\.\d+\.\d+" | tail -1`
cd ..
----------------
Installing Realsense-ros
catkin workspace
mkdir -p ~/catkin_ws/src
cd ~/catkin_ws/src/
Download realsense-ros pkg
git clone https://github.com/IntelRealSense/realsense-ros.git
cd realsense-ros/
git checkout `git tag | sort -V | grep -P "^\d+\.\d+\.\d+" | tail -1`
cd ..
------------
Download ddynamic_reconfigure
cd src
git clone https://github.com/pal-robotics/ddynamic_reconfigure/tree/kinetic-devel
cd ..
cd src
git clone git clone https://github.com/ros/dynamic_reconfigure.git  (ROS Melodic)
cd ..**
=============================
After I have entered this command. I have received following error.

**Pkg installation
catkin_init_workspace
cd ..
catkin_make clean**
===================================error==================================
ialab@ialab-OptiPlex-9010:~/obdet_ws1$ catkin_make clean
Base path: /home/ialab/obdet_ws1
Source space: /home/ialab/obdet_ws1/src
Build space: /home/ialab/obdet_ws1/build
Devel space: /home/ialab/obdet_ws1/devel
Install space: /home/ialab/obdet_ws1/install
####
#### Running command: "cmake /home/ialab/obdet_ws1/src -DCATKIN_DEVEL_PREFIX=/home/ialab/obdet_ws1/devel -DCMAKE_INSTALL_PREFIX=/home/ialab/obdet_ws1/install -G Unix Makefiles" in "/home/ialab/obdet_ws1/build"
####
-- Using CATKIN_DEVEL_PREFIX: /home/ialab/obdet_ws1/devel
-- Using CMAKE_PREFIX_PATH: /home/ialab/obdet_ws/devel;/home/ialab/turtle_ws/devel;/home/ialab/train_ws/devel;/home/ialab/moveit_ws/devel;/opt/ros/melodic
-- This workspace overlays: /home/ialab/turtle_ws/devel;/home/ialab/train_ws/devel;/home/ialab/moveit_ws/devel;/opt/ros/melodic
-- Found PythonInterp: /usr/bin/python2 (found suitable version "2.7.17", minimum required is "2") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python2
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/ialab/obdet_ws1/build/test_results
-- Found gtest sources under '/usr/src/googletest': gtests will be built
-- Found gmock sources under '/usr/src/googletest': gmock will be built
-- Found PythonInterp: /usr/bin/python2 (found version "2.7.17") 
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.7.29
-- BUILD_SHARED_LIBS is on
-- BUILD_SHARED_LIBS is on
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 5 packages in topological order:
-- ~~  - realsense2_camera_msgs (plain cmake)
-- ~~  - realsense2_description (plain cmake)
-- ~~  - dynamic_reconfigure
-- ~~  - realsense2_camera (plain cmake)
-- ~~  - dope
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CMake Error at /opt/ros/melodic/share/catkin/cmake/catkin_workspace.cmake:100 (message):
  This workspace contains non-catkin packages in it, and catkin cannot build
  a non-homogeneous workspace without isolation.  Try the
  'catkin_make_isolated' command instead.
Call Stack (most recent call first):
  CMakeLists.txt:69 (catkin_workspace)


-- Configuring incomplete, errors occurred!
See also "/home/ialab/obdet_ws1/build/CMakeFiles/CMakeOutput.log".
See also "/home/ialab/obdet_ws1/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed
=========================================error end=============================
How can I rectify this error.

**Comment by MartyG-RealSense** [comment]
The installation of **ddynamic_reconfigure** looks like where the installation process may start going wrong.  It may be easier to install it using a sudo instruction instead:

Edit: I see that I suggested that method earlier in the discussion.

https://github.com/IntelRealSense/realsense-ros/issues/1623#issuecomment-832030692

So as far as I am aware, if you have already installed ddynamic_reconfigure with a sudo instruction then you should not need to install it again with a git cloning.

![image](https://user-images.githubusercontent.com/41145062/117184005-245fe800-add0-11eb-99ee-40206d6b7f14.png)
