### ISSUE TITLE
ROS, Missing frames when using D435 and multiple devices problems

### ISSUE THREAD

**Issue by BIGFatming** [realsenseai/realsense-ros#1632]
Here are some basic information: We use two Realsense D435 cameras, both of the devices connect to a same industrial PC. The OS is Ubuntu 16.04. We run this command in terminal to launch the cameras:

"roslaunch realsense2_camera rs_multiple_devices.launch serial_no_camera1:=909512070754 serial_no_camera2:=819612073319"

we run this comment to record images and form a rosbag:

"record /camera1/color/image_raw/compressed /camera1/depth/ime_rect_raw/compressedDepth /camera1/infra1/image_rect_raw/compressed /camera1/infra2/image_rect_raw/compressed /camera2/color/image_raw/compressed /camera2/depth/image_rect_raw/compressedDepth /camera2/infra1/image_rect_raw/compressed /camera2/infra2/image_rect_raw/compressed -O 'bag_name'.bag"

We did not changes any default parameter of the cameras.

We find problems when we check the recorded data, we decomposed the rosbag and extracted every images it contains. The FPS of the RGB images is only 15 (supposed to be 30) while the infra images can reach the 30FPS, but the FPS of the depth images is too low. As the following pictures show.
![rgb](https://user-images.githubusercontent.com/73275810/105122065-7b3afd80-5b10-11eb-9190-cf9743477c78.PNG)
PIC1. the time stamp show the RGB FPS is only 15
![红外](https://user-images.githubusercontent.com/73275810/105122234-cf45e200-5b10-11eb-8d0b-be54e00d2ebb.PNG)
PIC2. the infra can reach 30 FPS
![深度](https://user-images.githubusercontent.com/73275810/105122278-e258b200-5b10-11eb-85c0-f923836cd002.PNG)
PIC3. FPS of depth is horrible......

Additionally, the time stamp of two cameras is different, the PIC4 and PIC5 show this problem.
![rgb](https://user-images.githubusercontent.com/73275810/105122570-6a3ebc00-5b11-11eb-9a71-c3dad6db704a.PNG)
PIC4 The images captured by camera1
![rgb2](https://user-images.githubusercontent.com/73275810/105122578-6d39ac80-5b11-11eb-833e-7877549f813f.PNG)
PIC5 The images captured by camera2

SO, what causes the problem of FPS?
AND, what causes the problem of time stamp? Are there any method to make multiple devices work synchronously？

**Comment by MartyG-RealSense** [comment]
Hi @BIGFatming   A constant FPS can be enforced in two ways:

-  Disabling auto-exposure and setting manual exposure within a certain range.

https://github.com/IntelRealSense/librealsense/issues/1957#issuecomment-400715579

- Enabling auto-exposure and disabling the **Auto-Exposure Priority**

Auto-Exposure Priority can be enabled and disabled in ROS with a **rosparam** using the details in the link below,

https://github.com/IntelRealSense/realsense-ros/issues/1349#issuecomment-681695259

The link below features a case where a RealSense ROS user used these methods successfully to maintain FPS at 30 instead of it reducing to 15.

https://github.com/IntelRealSense/realsense-ros/issues/1357

In regard to timestamps in your multicam setup, the case in the link below may be a useful reference.  The RealSense ROS user in that discussion had a multicam system and was experiencing erratic timestamps.   It was recommended to them that they set **global timestamps** to False.

https://github.com/IntelRealSense/librealsense/issues/8003

**Comment by BIGFatming** [comment]
I will try exposure settings and give a feedback ASAP. 
I checked some closed issues about timestamp, and saw #1451 mentioned a master-slave setting, I wonder if it works.

**Comment by BIGFatming** [comment]
@MartyG-RealSense

 I disabled the auto_exposure_priority and the FPS of RGB images has reached 30. **BUT, the FPS of depth images is still <10**. 

Additionally, I set the **global timestamps to false** but the timestamps of two cameras is still different. I also **set inter_cam_sync_mode to 1(Master) for camera1 and 2(Slave) for camera2**, but still not working. I wonder if multiple cameras can really capture the images at the same time, which means the images captured by different cameras has corresponding timestamps.

**Comment by BIGFatming** [comment]
@MartyG-RealSense 
I checked the website https://dev.intelrealsense.com/docs/multiple-depth-cameras-configuration you mentioned in #1454. Accroding to the website and your comment, if I need to **buy the wire to hardware sync the devices and also set the inter_cam_sync_mode to master and slave** so that I can make two devices work simultaneously?

**Comment by BIGFatming** [comment]
@MartyG-RealSense 
I checked the website https://dev.intelrealsense.com/docs/multiple-depth-cameras-configuration you mentioned in #1451 . Accroding to the website and your comment, if I need to buy the wire to hardware sync the devices and also set the inter_cam_sync_mode to master and slave so that I can make two devices work simultaneously?

**Comment by MartyG-RealSense** [comment]
Hi @BIGFatming   If you experience problems when using **roslaunch realsense2_camera rs_multiple_devices.launch** and specifying serial numbers, an alternate approach to ROS multicam on the same computer is to use **roslaunch realsense2_camera rs_camera.launch** and set up a separate terminal for each camera.  This process is described in Intel's ROS multiple camera tutorial:

https://www.intelrealsense.com/how-to-multiple-camera-setup-with-ros/

There is also a version of the tutorial for 3 cameras across 2 computers:

https://github.com/IntelRealSense/realsense-ros/wiki/showcase-of-using-3-cameras-in-2-machines

The **-all** condition of rosbag record can record data from all published topics.

http://wiki.ros.org/rosbag/Commandline#rosbag_record

The Inter Cam Sync Mode can be set from within ROS if you wish to sync the timestamp of slave cameras to the timing of a master camera, as described in the link in https://github.com/IntelRealSense/realsense-ros/issues/1451 that you referenced earlier.

You would need to assemble sync cabling though if you wish to physically connect the cameras together, as described in the multiple camera white paper.

A more recent reference document for multiple camera sync is the **External Synchronization (Genlock)** white paper:

https://dev.intelrealsense.com/docs/external-synchronization-of-intel-realsense-depth-cameras

**Comment by BIGFatming** [comment]
@MartyG-RealSense 
Thank you and I am a bit clear about the Synchronization stuff. Now I am going to focus on the problem of the FPS of depth images.
I will try "roslaunch realsense2_camera rs_camera.launch" to setup two cameras separately and give you a feedback ASAP.

**Comment by MartyG-RealSense** [comment]
Thanks very much @BIGFatming - I look forward to your test feedback.  Good luck!

**Comment by BIGFatming** [comment]
@MartyG-RealSense 
The experiment results that using "roslaunch realsense2_camera rs_camera.launch" to setup two cameras separately is useless, the FPS of depth images is still <10.
And I also find out that the RGB images FPS is lowered to 15 although I have set the auto_exposure_priotiry to false, I also tried to use "roslaunch realsense2_camera rs_multiple_devices.launch" to launch just like what I did last time, but nothing changed. That is extremely weird since this problem should be solved last time! The differences between experiments this time and last time is when I launch the camera, there is a warning: 

WARNING: disk usage in log directory [/home/sti/.ros/log] is over 1GB. It's recommended that you use the 'rosclean' command.

might it be the reason why the RGB images frequency has been lowerd?

**Comment by MartyG-RealSense** [comment]
I am not aware of the 1GB disk usage message having an impact on FPS.

FPS may halve or drop further than half if depth-color alignment is being performed, though I cannot see any alignment being done in your project.  

Going back to your opening message, I see that you are recording compressed depth.  I recall a case from November 2020 where a RealSense ROS user was experiencing extreme delay when using compression.

https://github.com/IntelRealSense/realsense-ros/issues/1484

Some RealSense ROS users have also gained stability by setting **enable_sync:=true** in their roslaunch instruction.  The RealSense ROS wrapper documentation states that enable_sync "gathers the closest frames of different sensors, infra red, color and depth, to be sent with the same timetag". 

Given that your opening message shows that you are using infrared, color and depth, it may be worth trying this setting if you are not using it already.

**Comment by BIGFatming** [comment]
@MartyG-RealSense 
Thanks for your suggestion, I set the **enable_sync:=true**, now I can get frames of different topics return with same timestamps.
I also checked the #1484 and set /camera/depth/image_rect_raw/compressedDepth/png_level to 1, now the depth_fps reaches 30.

Now, the only unsolved issue is the RGB_fps, it is still around 15. I set /camera/color/image_rect_raw/compressed/png_level to 1 and it dose not work. I have noticed that you mentioned a **compress_rate setting** in #1484 but I did not find it in launch documents and "rosrun rqt_reconfigure rqt_reconfigure", could you tell me how to change this setting in detail?

**Comment by MartyG-RealSense** [comment]
Greatto hear that you made progress @BIGFatming 

My research of the `<param name="compressed_rate"  type="double" value="$(arg rate)"/> `line mentioned in https://github.com/IntelRealSense/realsense-ros/issues/1484 suggests that it is usually used exactly in that form, and implemented with the following steps:

1.  Edit the launch file and in the section of the file with **<arg>** instructions, add this line:

**<arg name="rate"  default="5"/>**

Change the rate value from '5' to whatever you want it to be.

2.  Then in the section of the launch file with **<param>** instructions, add this line:

**<param name="compressed_rate"  type="double" value="$(arg rate)"/>**

This line substitutes into the bracket the value of the **rate** arg that you defined earlier in the launch file in step 1.

***************

Since you achieved 30 FPS for RGB by disabling **Auto-Exposure Priority**, I would suggest using that False setting again for Auto-Exposure Priority if you are not currently using it, remembering that **Auto Exposure** should be True.

**Comment by BIGFatming** [comment]
@MartyG-RealSense 
Sorry, but actually I cannot see the lines you want me to add, maybe the Github's problem.
But I do some experiments, and it seems that problems have solved, **temporary...**
I add these lines at the end of realsense2_camera rs_camera.launch document, just before "< / launch>"(I have to add blank to make it visible, I may figured out what happened to those lines you provided)

![image](https://user-images.githubusercontent.com/73275810/105793041-61dbfa80-5fc3-11eb-9b20-9a91eed3b709.png)

since one of the cameras has been taken by another group, I can only test one.
And here is the messages show in the terminal:

PARAMETERS
 * /cam_2/auto_exposure: True
 * /cam_2/auto_exposure_priority: False
 * /cam_2/depth/image_rect_raw/compressedDepth/png_level: 1
 * /cam_2/realsense2_camera/accel_fps: 250
 * /cam_2/realsense2_camera/accel_frame_id: cam_2_accel_frame
 * /cam_2/realsense2_camera/accel_optical_frame_id: cam_2_accel_optic...
 * /cam_2/realsense2_camera/align_depth: False
 * /cam_2/realsense2_camera/aligned_depth_to_color_frame_id: cam_2_aligned_dep...
 * /cam_2/realsense2_camera/aligned_depth_to_fisheye1_frame_id: cam_2_aligned_dep...
 * /cam_2/realsense2_camera/aligned_depth_to_fisheye2_frame_id: cam_2_aligned_dep...
 * /cam_2/realsense2_camera/aligned_depth_to_fisheye_frame_id: cam_2_aligned_dep...
 * /cam_2/realsense2_camera/aligned_depth_to_infra1_frame_id: cam_2_aligned_dep...
 * /cam_2/realsense2_camera/aligned_depth_to_infra2_frame_id: cam_2_aligned_dep...
 * /cam_2/realsense2_camera/allow_no_texture_points: False
 * /cam_2/realsense2_camera/base_frame_id: cam_2_link
 * /cam_2/realsense2_camera/calib_odom_file: 
 * /cam_2/realsense2_camera/clip_distance: -2.0
 * /cam_2/realsense2_camera/color_fps: 30
 * /cam_2/realsense2_camera/color_frame_id: cam_2_color_frame
 * /cam_2/realsense2_camera/color_height: 480
 * /cam_2/realsense2_camera/color_optical_frame_id: cam_2_color_optic...
 * /cam_2/realsense2_camera/color_width: 640
 * /cam_2/realsense2_camera/depth_fps: 30
 * /cam_2/realsense2_camera/depth_frame_id: cam_2_depth_frame
 * /cam_2/realsense2_camera/depth_height: 480
 * /cam_2/realsense2_camera/depth_optical_frame_id: cam_2_depth_optic...
 * /cam_2/realsense2_camera/depth_width: 640
 * /cam_2/realsense2_camera/device_type: 
 * /cam_2/realsense2_camera/enable_accel: False
 * /cam_2/realsense2_camera/enable_color: True
 * /cam_2/realsense2_camera/enable_depth: True
 * /cam_2/realsense2_camera/enable_fisheye1: False
 * /cam_2/realsense2_camera/enable_fisheye2: False
 * /cam_2/realsense2_camera/enable_fisheye: False
 * /cam_2/realsense2_camera/enable_gyro: False
 * /cam_2/realsense2_camera/enable_infra1: True
 * /cam_2/realsense2_camera/enable_infra2: True
 * /cam_2/realsense2_camera/enable_infra: True
 * /cam_2/realsense2_camera/enable_pointcloud: False
 * /cam_2/realsense2_camera/enable_pose: False
 * /cam_2/realsense2_camera/enable_sync: True
 * /cam_2/realsense2_camera/filters: 
 * /cam_2/realsense2_camera/fisheye1_frame_id: cam_2_fisheye1_frame
 * /cam_2/realsense2_camera/fisheye1_optical_frame_id: cam_2_fisheye1_op...
 * /cam_2/realsense2_camera/fisheye2_frame_id: cam_2_fisheye2_frame
 * /cam_2/realsense2_camera/fisheye2_optical_frame_id: cam_2_fisheye2_op...
 * /cam_2/realsense2_camera/fisheye_fps: 30
 * /cam_2/realsense2_camera/fisheye_frame_id: cam_2_fisheye_frame
 * /cam_2/realsense2_camera/fisheye_height: 480
 * /cam_2/realsense2_camera/fisheye_optical_frame_id: cam_2_fisheye_opt...
 * /cam_2/realsense2_camera/fisheye_width: 640
 * /cam_2/realsense2_camera/gyro_fps: 400
 * /cam_2/realsense2_camera/gyro_frame_id: cam_2_gyro_frame
 * /cam_2/realsense2_camera/gyro_optical_frame_id: cam_2_gyro_optica...
 * /cam_2/realsense2_camera/imu_optical_frame_id: cam_2_imu_optical...
 * /cam_2/realsense2_camera/infra1_frame_id: cam_2_infra1_frame
 * /cam_2/realsense2_camera/infra1_optical_frame_id: cam_2_infra1_opti...
 * /cam_2/realsense2_camera/infra2_frame_id: cam_2_infra2_frame
 * /cam_2/realsense2_camera/infra2_optical_frame_id: cam_2_infra2_opti...
 * /cam_2/realsense2_camera/infra_fps: 30
 * /cam_2/realsense2_camera/infra_height: 480
 * /cam_2/realsense2_camera/infra_width: 640
 * /cam_2/realsense2_camera/initial_reset: False
 * /cam_2/realsense2_camera/json_file_path: 
 * /cam_2/realsense2_camera/linear_accel_cov: 0.01
 * /cam_2/realsense2_camera/odom_frame_id: cam_2_odom_frame
 * /cam_2/realsense2_camera/pointcloud_texture_index: 0
 * /cam_2/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /cam_2/realsense2_camera/pose_frame_id: cam_2_pose_frame
 * /cam_2/realsense2_camera/pose_optical_frame_id: cam_2_pose_optica...
 * /cam_2/realsense2_camera/publish_odom_tf: True
 * /cam_2/realsense2_camera/publish_tf: True
 * /cam_2/realsense2_camera/rosbag_filename: 
 * /cam_2/realsense2_camera/serial_no: 819612073319
 * /cam_2/realsense2_camera/tf_publish_rate: 0.0
 * /cam_2/realsense2_camera/topic_odom_in: odom_in
 * /cam_2/realsense2_camera/unite_imu_method: 
 * /cam_2/realsense2_camera/usb_port_id: 
 * /rosdistro: kinetic
 * /rosversion: 1.12.14

Now I can get 30FPS RGB images, but I need to check if it works under multiple devices situation.
Maybe next time I launch cameras and after that I find out everything is useless, just like what I have experienced, hope that will not happen again.
Anyway, thanks for your assistance.

**Comment by MartyG-RealSense** [comment]
Oh yes, GItHub does not show scripting that is within arrow brackets unless formatted as a code quote.  I prefer bolding because of its better visibility.  The line was `<param name="compressed_rate"  type="double" value="$(arg rate)"/>`.  Sorry about that.

Please do let me know how your tests go once you have multiple cameras again.  Good luck!

**Comment by BIGFatming** [comment]
@MartyG-RealSense 
The test goes well, images from each topic share same timestamps, and the frequency reaches 30. I think it is time to close the issue.
But there is an episode I think is worth reporting. At the beginning, I launch cameras using  **roslaunch realsense2_camera rs_multiple_devices.launch** then those problems happen again: lowered frequency, messy timestamps... so I close the process and then launch only one camera using **realsense2_camera rs_camera.launch** just like what I did yesterday. However, the RGB images frequency is lowered to 15, and this problem should be solved yesterday. So I totally restart the ros process by restarting the **roscore**. This time, I launch cameras separately in two terminals using **realsense2_camera rs_camera.launch** and everything is well, no problems ever happen again.
Anyway, again, Thanks for your patient assist.

**Comment by MartyG-RealSense** [comment]
Thanks so much for your detailed test feedback that will benefit other readers of this case!  It is great to hear of your success.  :)

As suggested, I will close this case as you are satisfied with the outcome.  Thanks again.
