### ISSUE TITLE
Unable to locate package (ROS Noetic)

### ISSUE THREAD

**Issue by VincentPelletier1** [realsenseai/realsense-ros#1636]
### Hello there! 
I've been trying to install the realsense-ros package from the command line using  the 

`sudo apt-get install ros-$ROS_VER-realsense2-camera` command 

(and yes, I did an `export ROS_VER=noetic` beforehand to load the variable).

However, I'm getting this error:
`Unable to locate package ros-noetic-realsense2-camera`

Any ideas?

**Comment by MartyG-RealSense** [comment]
Hi @Plopao   As a starting point in investigating your case, may I confirm that you have installed ROS Noetic on Ubuntu **20.04** before attempting to install the RealSense ROS wrapper with **Method 1**?  Thanks!

**Comment by VincentPelletier1** [comment]
Yes I did! I'm about to try installing it with the other methods, but I'd prefer method 1 by far since it's a lot easier to install.

**Comment by MartyG-RealSense** [comment]
I recalled this recent case about Noetic package availability, with feedback in it from @doronhi the RealSense ROS wrapper developer.

https://github.com/IntelRealSense/realsense-ros/issues/1577
