### ISSUE TITLE
The requested device with serial number xxx and device name containing xx is NOT found. Will Try again.

### ISSUE THREAD

**Issue by joguiguma** [realsenseai/realsense-ros#1638]
I try to run https://github.com/IntelRealSense/realsense-ros/tree/occupancy-mapping/occupancy  using my laptop, ubuntu 18 and ros melodic. I have T265 and  D435i

Running:
source devel/setup.bash
roslaunch occupancy occupancy_live_rviz.launch

There are two errors:

 21/01 21:46:54,032 ERROR [140533704140544] (handle-libusb.h:95) failed to claim usb interface: 0, error: RS2_USB_STATUS_BUSY
 21/01 21:46:54,032 ERROR [140533704140544] (types.h:313) Unable to open device interface
 21/01 21:46:54,032 WARNING [140533704140544] (rs.cpp:306) null pointer passed for argument "device"
[ WARN] [1611283614.032974241]: Device 2/2 failed with exception: Unable to open device interface
[ERROR] [1611283614.033007845]: The requested device with serial number T265_SN and device name containing t265 is NOT found. Will Try again.
[ INFO] [1611283614.035876474]: Device with serial number 925122110642 was found.

[ INFO] [1611283614.035915640]: Device with physical ID 2-3-3 was found.
[ INFO] [1611283614.035932578]: Device with name Intel RealSense T265 was found.
[ INFO] [1611283614.036276561]: Device with port number 2-3 was found.
[ERROR] [1611283614.132034334]: The requested device with serial number D400_SN and device name containing d4.5 is NOT found. Will Try again.

When I run realsense.viewer both realsense are with good connection. 

What can I do?

**Comment by joguiguma** [comment]
Ful terminal is:

roslaunch occupancy occupancy_live_rviz.launch
... logging to /home/joguiguma/.ros/log/c665ed5e-5cd4-11eb-b4ce-38baf8333bf5/roslaunch-joguiguma-Latitude-7490-4072.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://192.168.1.106:39271/

SUMMARY
========

PARAMETERS
 * /DepthOfInterestMax: 2.0
 * /DepthOfInterestMin: 0.2
 * /HeightOfInterestMax: 0.05
 * /HeightOfInterestMin: -0.05
 * /d400/realsense2_camera/accel_fps: 0
 * /d400/realsense2_camera/accel_frame_id: d400_accel_frame
 * /d400/realsense2_camera/accel_optical_frame_id: d400_accel_optica...
 * /d400/realsense2_camera/align_depth: True
 * /d400/realsense2_camera/aligned_depth_to_color_frame_id: d400_aligned_dept...
 * /d400/realsense2_camera/aligned_depth_to_fisheye1_frame_id: d400_aligned_dept...
 * /d400/realsense2_camera/aligned_depth_to_fisheye2_frame_id: d400_aligned_dept...
 * /d400/realsense2_camera/aligned_depth_to_fisheye_frame_id: d400_aligned_dept...
 * /d400/realsense2_camera/aligned_depth_to_infra1_frame_id: d400_aligned_dept...
 * /d400/realsense2_camera/aligned_depth_to_infra2_frame_id: d400_aligned_dept...
 * /d400/realsense2_camera/allow_no_texture_points: False
 * /d400/realsense2_camera/base_frame_id: d400_link
 * /d400/realsense2_camera/calib_odom_file: 
 * /d400/realsense2_camera/clip_distance: -2.0
 * /d400/realsense2_camera/color_fps: 30
 * /d400/realsense2_camera/color_frame_id: d400_color_frame
 * /d400/realsense2_camera/color_height: 480
 * /d400/realsense2_camera/color_optical_frame_id: d400_color_optica...
 * /d400/realsense2_camera/color_width: 640
 * /d400/realsense2_camera/confidence_fps: 30
 * /d400/realsense2_camera/confidence_height: 480
 * /d400/realsense2_camera/confidence_width: 640
 * /d400/realsense2_camera/depth_fps: 30
 * /d400/realsense2_camera/depth_frame_id: d400_depth_frame
 * /d400/realsense2_camera/depth_height: 480
 * /d400/realsense2_camera/depth_optical_frame_id: d400_depth_optica...
 * /d400/realsense2_camera/depth_width: 640
 * /d400/realsense2_camera/device_type: d4.5
 * /d400/realsense2_camera/enable_accel: False
 * /d400/realsense2_camera/enable_color: True
 * /d400/realsense2_camera/enable_confidence: True
 * /d400/realsense2_camera/enable_depth: True
 * /d400/realsense2_camera/enable_fisheye1: False
 * /d400/realsense2_camera/enable_fisheye2: False
 * /d400/realsense2_camera/enable_fisheye: False
 * /d400/realsense2_camera/enable_gyro: False
 * /d400/realsense2_camera/enable_infra1: False
 * /d400/realsense2_camera/enable_infra2: False
 * /d400/realsense2_camera/enable_infra: False
 * /d400/realsense2_camera/enable_pointcloud: False
 * /d400/realsense2_camera/enable_pose: False
 * /d400/realsense2_camera/enable_sync: False
 * /d400/realsense2_camera/filters: pointcloud
 * /d400/realsense2_camera/fisheye1_frame_id: d400_fisheye1_frame
 * /d400/realsense2_camera/fisheye1_optical_frame_id: d400_fisheye1_opt...
 * /d400/realsense2_camera/fisheye2_frame_id: d400_fisheye2_frame
 * /d400/realsense2_camera/fisheye2_optical_frame_id: d400_fisheye2_opt...
 * /d400/realsense2_camera/fisheye_fps: 30
 * /d400/realsense2_camera/fisheye_frame_id: d400_fisheye_frame
 * /d400/realsense2_camera/fisheye_height: 0
 * /d400/realsense2_camera/fisheye_optical_frame_id: d400_fisheye_opti...
 * /d400/realsense2_camera/fisheye_width: 0
 * /d400/realsense2_camera/gyro_fps: 0
 * /d400/realsense2_camera/gyro_frame_id: d400_gyro_frame
 * /d400/realsense2_camera/gyro_optical_frame_id: d400_gyro_optical...
 * /d400/realsense2_camera/imu_optical_frame_id: d400_imu_optical_...
 * /d400/realsense2_camera/infra1_frame_id: d400_infra1_frame
 * /d400/realsense2_camera/infra1_optical_frame_id: d400_infra1_optic...
 * /d400/realsense2_camera/infra2_frame_id: d400_infra2_frame
 * /d400/realsense2_camera/infra2_optical_frame_id: d400_infra2_optic...
 * /d400/realsense2_camera/infra_fps: 30
 * /d400/realsense2_camera/infra_height: 480
 * /d400/realsense2_camera/infra_rgb: False
 * /d400/realsense2_camera/infra_width: 640
 * /d400/realsense2_camera/initial_reset: False
 * /d400/realsense2_camera/json_file_path: 
 * /d400/realsense2_camera/linear_accel_cov: 0.01
 * /d400/realsense2_camera/odom_frame_id: d400_odom_frame
 * /d400/realsense2_camera/pointcloud_texture_index: 0
 * /d400/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /d400/realsense2_camera/pose_frame_id: d400_pose_frame
 * /d400/realsense2_camera/pose_optical_frame_id: d400_pose_optical...
 * /d400/realsense2_camera/publish_odom_tf: True
 * /d400/realsense2_camera/publish_tf: True
 * /d400/realsense2_camera/rosbag_filename: 
 * /d400/realsense2_camera/serial_no: D400_SN
 * /d400/realsense2_camera/tf_publish_rate: 0.0
 * /d400/realsense2_camera/topic_odom_in: d400/odom_in
 * /d400/realsense2_camera/unite_imu_method: none
 * /d400/realsense2_camera/usb_port_id: 
 * /resolution: 0.03
 * /rosdistro: melodic
 * /rosversion: 1.14.10
 * /t265/realsense2_camera/accel_fps: 0
 * /t265/realsense2_camera/accel_frame_id: t265_accel_frame
 * /t265/realsense2_camera/accel_optical_frame_id: t265_accel_optica...
 * /t265/realsense2_camera/align_depth: False
 * /t265/realsense2_camera/aligned_depth_to_color_frame_id: t265_aligned_dept...
 * /t265/realsense2_camera/aligned_depth_to_fisheye1_frame_id: t265_aligned_dept...
 * /t265/realsense2_camera/aligned_depth_to_fisheye2_frame_id: t265_aligned_dept...
 * /t265/realsense2_camera/aligned_depth_to_fisheye_frame_id: t265_aligned_dept...
 * /t265/realsense2_camera/aligned_depth_to_infra1_frame_id: t265_aligned_dept...
 * /t265/realsense2_camera/aligned_depth_to_infra2_frame_id: t265_aligned_dept...
 * /t265/realsense2_camera/allow_no_texture_points: False
 * /t265/realsense2_camera/base_frame_id: t265_link
 * /t265/realsense2_camera/calib_odom_file: 
 * /t265/realsense2_camera/clip_distance: -1.0
 * /t265/realsense2_camera/color_fps: 30
 * /t265/realsense2_camera/color_frame_id: t265_color_frame
 * /t265/realsense2_camera/color_height: 480
 * /t265/realsense2_camera/color_optical_frame_id: t265_color_optica...
 * /t265/realsense2_camera/color_width: 640
 * /t265/realsense2_camera/confidence_fps: 30
 * /t265/realsense2_camera/confidence_height: 480
 * /t265/realsense2_camera/confidence_width: 640
 * /t265/realsense2_camera/depth_fps: 30
 * /t265/realsense2_camera/depth_frame_id: t265_depth_frame
 * /t265/realsense2_camera/depth_height: 480
 * /t265/realsense2_camera/depth_optical_frame_id: t265_depth_optica...
 * /t265/realsense2_camera/depth_width: 640
 * /t265/realsense2_camera/device_type: t265
 * /t265/realsense2_camera/enable_accel: False
 * /t265/realsense2_camera/enable_color: True
 * /t265/realsense2_camera/enable_confidence: True
 * /t265/realsense2_camera/enable_depth: True
 * /t265/realsense2_camera/enable_fisheye1: False
 * /t265/realsense2_camera/enable_fisheye2: False
 * /t265/realsense2_camera/enable_fisheye: False
 * /t265/realsense2_camera/enable_gyro: False
 * /t265/realsense2_camera/enable_infra1: False
 * /t265/realsense2_camera/enable_infra2: False
 * /t265/realsense2_camera/enable_infra: False
 * /t265/realsense2_camera/enable_pointcloud: False
 * /t265/realsense2_camera/enable_pose: True
 * /t265/realsense2_camera/enable_sync: False
 * /t265/realsense2_camera/filters: 
 * /t265/realsense2_camera/fisheye1_frame_id: t265_fisheye1_frame
 * /t265/realsense2_camera/fisheye1_optical_frame_id: t265_fisheye1_opt...
 * /t265/realsense2_camera/fisheye2_frame_id: t265_fisheye2_frame
 * /t265/realsense2_camera/fisheye2_optical_frame_id: t265_fisheye2_opt...
 * /t265/realsense2_camera/fisheye_fps: 30
 * /t265/realsense2_camera/fisheye_frame_id: t265_fisheye_frame
 * /t265/realsense2_camera/fisheye_height: 0
 * /t265/realsense2_camera/fisheye_optical_frame_id: t265_fisheye_opti...
 * /t265/realsense2_camera/fisheye_width: 0
 * /t265/realsense2_camera/gyro_fps: 0
 * /t265/realsense2_camera/gyro_frame_id: t265_gyro_frame
 * /t265/realsense2_camera/gyro_optical_frame_id: t265_gyro_optical...
 * /t265/realsense2_camera/imu_optical_frame_id: t265_imu_optical_...
 * /t265/realsense2_camera/infra1_frame_id: t265_infra1_frame
 * /t265/realsense2_camera/infra1_optical_frame_id: t265_infra1_optic...
 * /t265/realsense2_camera/infra2_frame_id: t265_infra2_frame
 * /t265/realsense2_camera/infra2_optical_frame_id: t265_infra2_optic...
 * /t265/realsense2_camera/infra_fps: 30
 * /t265/realsense2_camera/infra_height: 480
 * /t265/realsense2_camera/infra_rgb: False
 * /t265/realsense2_camera/infra_width: 640
 * /t265/realsense2_camera/initial_reset: False
 * /t265/realsense2_camera/json_file_path: 
 * /t265/realsense2_camera/linear_accel_cov: 0.01
 * /t265/realsense2_camera/odom_frame_id: t265_odom_frame
 * /t265/realsense2_camera/pointcloud_texture_index: 0
 * /t265/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /t265/realsense2_camera/pose_frame_id: t265_pose_frame
 * /t265/realsense2_camera/pose_optical_frame_id: t265_pose_optical...
 * /t265/realsense2_camera/publish_odom_tf: True
 * /t265/realsense2_camera/publish_tf: True
 * /t265/realsense2_camera/rosbag_filename: 
 * /t265/realsense2_camera/serial_no: T265_SN
 * /t265/realsense2_camera/tf_publish_rate: 0.0
 * /t265/realsense2_camera/topic_odom_in: odom_in
 * /t265/realsense2_camera/unite_imu_method: none
 * /t265/realsense2_camera/usb_port_id: 

NODES
  /
    occupancy_node (occupancy/occupancy_node)
    rviz (rviz/rviz)
    t265_to_d400 (tf/static_transform_publisher)
  /d400/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)
  /t265/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)

auto-starting new master
process[master]: started with pid [4095]
ROS_MASTER_URI=http://192.168.1.106:11311

setting /run_id to c665ed5e-5cd4-11eb-b4ce-38baf8333bf5
process[rosout-1]: started with pid [4106]
started core service [/rosout]
process[t265/realsense2_camera_manager-2]: started with pid [4109]
process[t265/realsense2_camera-3]: started with pid [4110]
process[d400/realsense2_camera_manager-4]: started with pid [4111]
process[d400/realsense2_camera-5]: started with pid [4112]
process[t265_to_d400-6]: started with pid [4117]
process[occupancy_node-7]: started with pid [4118]
process[rviz-8]: started with pid [4134]
[ INFO] [1611335450.600208026]: Initializing nodelet with 8 worker threads.
[ INFO] [1611335450.601039830]: Initializing nodelet with 8 worker threads.
[ INFO] [1611335453.147399945]: RealSense ROS v2.2.21
[ INFO] [1611335453.147452178]: Built with LibRealSense v2.40.0
[ INFO] [1611335453.147477723]: Running with LibRealSense v2.41.0
[ WARN] [1611335453.147501218]: ***************************************************
[ WARN] [1611335453.147519133]: ** running with a different librealsense version **
[ WARN] [1611335453.147535264]: ** than the one the wrapper was compiled with!   **
[ WARN] [1611335453.147551353]: ***************************************************
[ INFO] [1611335453.161788116]:  
[ INFO] [1611335453.166957371]: Device with serial number 912112073155 was found.

[ INFO] [1611335453.166992214]: Device with physical ID /sys/devices/pci0000:00/0000:00:14.0/usb2/2-4/2-4:1.0/video4linux/video0 was found.
[ INFO] [1611335453.167011059]: Device with name Intel RealSense D435I was found.
[ INFO] [1611335453.167434543]: Device with port number 2-4 was found.
[ INFO] [1611335453.178664913]: Device with serial number 925122110642 was found.

[ INFO] [1611335453.178717621]: Device with physical ID 2-3-3 was found.
[ INFO] [1611335453.178742121]: Device with name Intel RealSense T265 was found.
[ INFO] [1611335453.179436671]: Device with port number 2-3 was found.
[ERROR] [1611335453.278459956]: The requested device with serial number D400_SN and device name containing d4.5 is NOT found. Will Try again.
[ INFO] [1611335453.731723038]: RealSense ROS v2.2.21
[ INFO] [1611335453.731757715]: Built with LibRealSense v2.40.0
[ INFO] [1611335453.731772420]: Running with LibRealSense v2.41.0
[ WARN] [1611335453.731795592]: ***************************************************
[ WARN] [1611335453.731810970]: ** running with a different librealsense version **
[ WARN] [1611335453.731825576]: ** than the one the wrapper was compiled with!   **
[ WARN] [1611335453.731839670]: ***************************************************
[ INFO] [1611335453.740823883]:  
[ INFO] [1611335453.745188802]: Device with serial number 912112073155 was found.

[ INFO] [1611335453.745218485]: Device with physical ID /sys/devices/pci0000:00/0000:00:14.0/usb2/2-4/2-4:1.0/video4linux/video0 was found.
[ INFO] [1611335453.745232369]: Device with name Intel RealSense D435I was found.
[ INFO] [1611335453.745536033]: Device with port number 2-4 was found.
[ INFO] [1611335453.752423204]: Device with serial number 925122110642 was found.

[ INFO] [1611335453.752485524]: Device with physical ID 2-3-3 was found.
[ INFO] [1611335453.752511676]: Device with name Intel RealSense T265 was found.
[ INFO] [1611335453.752874208]: Device with port number 2-3 was found.
[ERROR] [1611335453.850843871]: The requested device with serial number T265_SN and device name containing t265 is NOT found. Will Try again.
^C[rviz-8] killing on exit
[occupancy_node-7] killing on exit
[t265_to_d400-6] killing on exit
[d400/realsense2_camera-5] killing on exit
[d400/realsense2_camera_manager-4] killing on exit
[t265/realsense2_camera-3] killing on exit
[t265/realsense2_camera_manager-2] killing on exit
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by doronhi** [comment]
You should set the parameters "serial_no_camera1" and "serial_no_camera2". They are still in their "example" form:
"T265_SN" and "D400_SN".

Try:
```
roslaunch occupancy occupancy_live_rviz.launch serial_no_camera1:=<Your T265 serial number> serial_no_camera2:=<Your D435 serial number>
```
Or modify the "occupancy/launch/cameras.launch" file accordingly.

**Comment by joguiguma** [comment]
> You should set the parameters "serial_no_camera1" and "serial_no_camera2". They are still in their "example" form:
> "T265_SN" and "D400_SN".
> 
> Try:
> 
> ```
> roslaunch occupancy occupancy_live_rviz.launch serial_no_camera1:=<Your T265 serial number> serial_no_camera2:=<Your D435 serial number>
> ```
> 
> Or modify the "occupancy/launch/cameras.launch" file accordingly.

The problem was fixed modifying  "occupancy/launch/cameras.launch" introducing  the serial of both cameras. Thank you very much.
