### ISSUE TITLE
Aligned depth D435

### ISSUE THREAD

**Issue by alex-stonebridge** [realsenseai/realsense-ros#1647]
Hello, I use a D435 camera. I have a camera stream and I want to get exact 1-to-1 depth and color frames. To do that, I use rs_camera.launch file with align_depth and enable_sync set to true. Then I subscribe to /camera/aligned_depth_to_color/image_raw and to /camera/color/image_raw using TimeSynchronizer. That seems to be working, but is it a right way?
Later, I want to calculate object coordinates  (x,y,z) in camera frame. To do that, I guess I will need to know some intrinsic and extrinsic parameters. However, I have quite a lot different topics listed below. Which of them would be better to use?
/camera/aligned_depth_to_color/camera_info
/camera/color/camera_info
/camera/depth/camera_info
/camera/extrinsics/depth_to_color

**Comment by MartyG-RealSense** [comment]
Hi @alex-stonebridge  The method of alignment that you described seems to be consistent with the procedures that I have observed in use by other RealSense ROS users who are performing this kind of alignment.

If you would like to compare your method with other approaches to achieving the desired goal, the link below leads to a tutorial for creating an **RGB-D** point cloud using the aligned depth topic.

https://idorobotics.com/2018/11/02/integrating-the-intel-realsense-d435-with-ros/

Another approach to generating an RGB-D point cloud is in the link below, which also describes a method for retrieving the 3D position of each color pixel by going over the **aligned_depth_to_color** topic:

https://github.com/IntelRealSense/realsense-ros/issues/277

https://github.com/IntelRealSense/realsense-ros/issues/277#issuecomment-363117777
