### ISSUE TITLE
Aligned Depth Cloud error - not representative of Real World space

### ISSUE THREAD

**Issue by derektan95** [realsenseai/realsense-ros#1660]
Hi @doronhi and @MartyG-RealSense, 

I recently performed a calibration using `realsense-viewer` to improve my depth data from my Intel Realsense d435i. I used the following to obtain my depth cloud. 

`roslaunch -realsense2_camera rs_camera.launch align_depth:=true`

The red lines corresponds to laser scan from a 2d lidar that is very accurate. As expected, the depth cloud from `raw depth` topic lines up with the lidar scan well. 

![camera_depth_raw](https://user-images.githubusercontent.com/48535336/106453809-d089ee00-64c4-11eb-8711-186ca4690da1.png)

Unfortunately, I observed something strange. When I subscribed to `aligned_depth_to_color` topic, the depth cloud seemed stretched out and very unaligned: 

![camera_depth_aligned_to_cam](https://user-images.githubusercontent.com/48535336/106454026-22cb0f00-64c5-11eb-8346-6e9cbf8399f7.png)

Both images are taken at exactly the same spot. Any insights to why there is such an error? I need the `aligned_depth_to_color` data to be both aligned to my RGB image, and yet representative of real world space. Thanks. 

-Derek

**Comment by MartyG-RealSense** [comment]
Hi @derektan95   It looks as though the depth is being aligned to the size of the color field of view (FOV), which is a smaller size than the depth FOV on the D435 and D435i camera models.  

The D415 and D455 camera models have the same FOV size for both depth and color,

**Comment by derektan95** [comment]
Ah i see. I must have gotten some configuration wrong. I will look into it. Thank you so much!

**Comment by MartyG-RealSense** [comment]
Thanks very much @derektan95 for the update - good luck!
