### ISSUE TITLE
Is there a way to reset parameters to default?

### ISSUE THREAD

**Issue by sisaha9** [realsenseai/realsense-ros#1662]
I was using dynamic_rqt_reconfigure to change some parameters for the camera around. However I realized that I didn't create a backup of the intial default parameters. Is there a way to reset to that?

**Comment by MartyG-RealSense** [comment]
Hi @sisaha9   I hope that the discussion in the link below will be helpful to you.

https://github.com/IntelRealSense/realsense-ros/issues/609
