### ISSUE TITLE
Defining extrinsics between multiple cameras and T265

### ISSUE THREAD

**Issue by NorwegianPi** [realsenseai/realsense-ros#1671]
Hi,
I am currently working in integrating a D435 and L515 with a T265 and RTABMAP in ROS. 
I have a 3d printed mount holding all three cameras in a fixed relative position. 
I need to specify the transform between the cameras.
Is there a preferred way to do this? Checker board scanning or based on measurements?

**Comment by doronhi** [comment]
I think this is a general ROS question. Not a realsense one.
I guess a Checker board scanning method would be better because very small inaccuracies in measuring the mount, might be important.
