### ISSUE TITLE
This package on a slave PC

### ISSUE THREAD

**Issue by alex-stonebridge** [realsenseai/realsense-ros#1675]
Hello, I have a master PC and a slave PC with D435 cam. PCs could be connected via Ethernet/Wi-Fi and my goal is to work with camera topics on the slave PC. At the same time slave PCs should exchange some other topics with the master PC. However, when I have roscore working on the master PC, launch files from this package are not working. Is there any way to have this package working and keep two PCs communicating via ros topics?

**Comment by MartyG-RealSense** [comment]
Hi @alex-stonebridge  Have you seen Intel's ROS tutorial **Showcase of using 3 cameras in 2 machines** please?  In that guide, the first of two computers has separate terminals for roscore and for the camera(s).  On the second machine, it has one terminal for the single camera attached to it and communicates with the first computer using a **ROS_MASTER_URI** ID number of that first computer that is placed one the same line as the roslaunch instruction, preceding it.

In the guide's example, if the first computer has the ROS_MASTER_URI **perclnx319** then the single line of instruction that is input into the terminal of the second computer could be:

`export ROS_MASTER_URI=http://perclnx319:11311 roslaunch realsense2_camera rs_camera.launch camera:=cam_3 serial_no:=725112060487 filters:=spatial,temporal,pointcloud`

https://github.com/IntelRealSense/realsense-ros/wiki/showcase-of-using-3-cameras-in-2-machines
