### ISSUE TITLE
Enabling Occlusion Invalidation l515

### ISSUE THREAD

**Issue by apoorvcn47** [realsenseai/realsense-ros#1679]
Hi,
I am using L515 with ROS2 Foxy driver. I believe Occlusion Invalidation is disabled in my case. I am not sure how to enable it
![rviz_screenshot_2021_02_08-10_40_09](https://user-images.githubusercontent.com/8816380/107242967-8e980500-69fa-11eb-9efe-fae7f60103a6.png)

**Comment by RealSenseSupport** [comment]
Hi @apoorvcn47 

I'm not familiar with specific setting for invalidate occlusion in ROS2.  Did you by chance figure out what was needed?

https://dev.intelrealsense.com/docs/projection-texture-mapping-and-occlusion-with-intel-realsense-depth-cameras?_ga=2.58804653.1807786935.1613978068-1479303487.1578600965

**Comment by apoorvcn47** [comment]
I did not yet

**Comment by doronhi** [comment]
`ros2 param set /camera/camera l500_depth_sensor.invalidation_bypass true`

**Comment by apoorvcn47** [comment]
Thanks That helped
