### ISSUE TITLE
Depth registered pointcloud in ROS2

### ISSUE THREAD

**Issue by joelbudu** [realsenseai/realsense-ros#1680]
Is it possible to get depth registered pointcloud in the ROS2 branches (eloquent, foxy)?
It seems the feature is not available but is present in ROS1 in [rs_rgbd.launch](https://github.com/IntelRealSense/realsense-ros/blob/development/realsense2_camera/launch/rs_rgbd.launch)

**Comment by MartyG-RealSense** [comment]
Hi @joelbudu   My understanding is that a depth registered pointcloud is a **textured pointcloud** that has RGB aligned to depth.  

I researched your question extensively but could not find a clear example in the RealSense ROS2 wrapper for achieving a point cloud that was exactly described as depth-registered or aligned.

The documentation of the **Foxy** branch of the RealSense ROS2 wrapper suggests that applying a **pointcloud** filter will add a pointcloud topic **/camera/depth/color/points** that has texturing.

https://github.com/IntelRealSense/realsense-ros/tree/foxy#available-parameters

![image](https://user-images.githubusercontent.com/41145062/107374802-e8262f80-6adf-11eb-95a3-7d9cbb897756.png)

An example of a ROS2 launch instruction I found that includes a pointcloud filter definition is below:

**ros2 run realsense2_camera realsense2_camera --ros-args -p filters:=pointcloud**

**Comment by doronhi** [comment]
Hi @joelbudu , Could you please explain what is the difference between "depth registered pointcloud" and the organized pointcloud available now in realsense2_camera (foxy)?

**Comment by MartyG-RealSense** [comment]
Hi @doronhi   The old deprecated Intel ROS2 wrapper for Dashing supported a mode that it described as **Depth Aligned (i.e. Depth Registered) Point Cloud** that acted as my start point for trying to work out what 'depth registered' meant, and other sources seemed to concur that it referred to mapping RGB texturing to a depth point cloud.

https://github.com/intel/ros2_intel_realsense#visualize-depth-aligned-ie-depth-registered-point-cloud

Using the point cloud filter of the current ROS2 Foxy wrapper was the closest method that I could find to the old Dashing solution for producing a textured cloud in the current ROS2 wrapper, though you can likely suggest an alternative method.  :)

**Comment by joelbudu** [comment]
@MartyG-RealSense Yes the old ROS2 wrapper published a Depth registered point cloud topic to a topic like /camera/aligned_depth_to_color/color/points.
The difference is that the Depth aligned pointcould uses the FOV of the colour sensor to create the pointcloud with a 1 to 1 mapping. 
@doronhi  The organized pointcloud available in foxy uses the FOV of the depth sensor and would only publish the points within the frame that correspond to a texture/colour point.

**Comment by doronhi** [comment]
Hi @joelbudu , I think I see what you mean.
If I understand you correctly, you would like to use the aligned_depth_to_color image as a base for the ordered pointcloud.
This feature does not exist in the wrapper.

It is a little tricky to implement correctly in the current code structure since aligning the depth image to the color image happens only after the pointcloud is built and only locally in the "publishAlignedDepthToOthers" function.
As an immediate solution you could copy the section aligning the depth image [base_realsense_node.cpp, lines 1025-1044](https://github.com/IntelRealSense/realsense-ros/blob/eca337fd4dd4b1f7fd2cfd41290befbcb8daab5a/realsense2_camera/src/base_realsense_node.cpp#L1025) with `stream_type=RS2_STREAM_COLOR` and apply it before the filters are applied [line 1643](https://github.com/IntelRealSense/realsense-ros/blob/eca337fd4dd4b1f7fd2cfd41290befbcb8daab5a/realsense2_camera/src/base_realsense_node.cpp#L1643)
The reference is to the eloquent branch as I figured this is your current branch.
I didn't try it so I'm pretty sure some complications will arise.

**Comment by joelbudu** [comment]
Dear @doronhi. Thanks for the pointer on this. I did indeed attempt this approach unsuccessfully yesterday, as you mentioned I was getting an error saying the alignment to the color frame couldn't be performed. I do not have a full understanding on the underlying SDK and how this library works in totality so it was quite challenging.

Please let me when you are able to do some work on this. Thanks

**Comment by MartyG-RealSense** [comment]
Hi @doronhi   Could you assist @joelbudu with the question above please?  Thanks!

**Comment by doronhi** [comment]
Hi @joelbudu 
The original decision to warp the color image to the depth image when creating a pointcloud and not the other way around came from the idea that it is more important to keep the depth information accurate than the color information.
I can think of 2 solutions to your problem.
1. Create the pointcloud from the warped depth image and the original color image.
2. Publish a "color-to-depth-aligned-image". You could then do all the color-image work on the warped color image and have it aligned with the pointcloud.
Neither option is currently in the work plan. The second option seems more straightforward from the wrapper's perspective.

Please let me know if it seems that it would benefit you and I'll see how and if I promote any of them.

**Comment by joelbudu** [comment]
Thanks for the response @doronhi.

First of all, the feature I'm requesting is available in the ROS1 branches of this repository via [rs_rgbd.launch](https://github.com/IntelRealSense/realsense-ros/blob/development/realsense2_camera/launch/rs_rgbd.launch). The only issue is that it isn't available in the ROS2 versions. It seems to be using some form of nodelet using the underlying realsense library. Is it possible to have this in ROS2?

It would definitely be of great benefit if the feature is available in ROS2 for this repo, in terms of the solutions you mentioned, option 1 would be more preferable since that is consistent with the current and deprecated library. 

Thanks for your assistance.

**Comment by doronhi** [comment]
Hi @joelbudu 
[rgbd_launch](https://github.com/ros-drivers/rgbd_launch) is not a RealSense package. You could apply in its repository for ROS2 support but I have no way of helping in that direction.
As for realsense2_camera publishing an ordered pointcloud aligned with the color image, I have put it on the list for review. There is, as for now, no timeline defined. It is tracked internally as "DSO-16639"

**Comment by joelbudu** [comment]
@doronhi Thank you very much for working on this.

**Comment by charlielito** [comment]
I think this feature is very important. My team moved from Dashing to Foxy because Intel said that this was the official repo with full support and features, so it is a little sad that this isn't implemented yet :/

**Comment by charlielito** [comment]
@joelbudu I managed to have a temporal working version for the d435i camera. I tried to port the logic from the dashing wrapper for aligning the point cloud. I just replaced this line https://github.com/IntelRealSense/realsense-ros/blob/foxy/realsense2_camera/src/base_realsense_node.cpp#L1749

with:

```c++
    rs2::align align_to_color_ = rs2::align(RS2_STREAM_COLOR);
    rs2::pointcloud pc_;
    auto aligned_frameset = align_to_color_.process(frameset);
    auto depth = aligned_frameset.get_depth_frame();
    rs2::points points_ = pc_.calculate(depth);
    auto color_frame = frameset.get_color_frame();
    publishDensePointCloud(points_, color_frame, t);
```

And had to copy the method `publishDensePointCloud` from https://github.com/intel/ros2_intel_realsense/blob/dashing/realsense_ros/src/rs_d435.cpp#L315 with some minor changes of names to match the new names (for example the publisher), and also define this new method signature in `base_realsense_node.h`.


<details>
<summary>publishDensePointCloud </summary>
<p>

```c++
void BaseRealSenseNode::publishDensePointCloud(const rs2::points& points, const rs2::video_frame& color_frame,
                                               const rclcpp::Time& time)
{
    const rs2::vertex* vertex = points.get_vertices();

    if (!_node.get_node_options().use_intra_process_comms())
    {
        sensor_msgs::msg::PointCloud2::SharedPtr pc_msg = std::make_shared<sensor_msgs::msg::PointCloud2>();
        // debug
        // RCLCPP_INFO(node_->get_logger(), "timestamp: %f, address: %p", t.seconds(),
        // reinterpret_cast<std::uintptr_t>(pc_msg.get()));
        //
        pc_msg->header.stamp = time;
        pc_msg->header.frame_id = DEFAULT_COLOR_OPTICAL_FRAME_ID;
        pc_msg->width = color_frame.get_width();
        pc_msg->height = color_frame.get_height();
        pc_msg->point_step = 3 * sizeof(float) + 3 * sizeof(uint8_t);
        pc_msg->row_step = pc_msg->point_step * pc_msg->width;
        pc_msg->is_dense = true;

        sensor_msgs::PointCloud2Modifier modifier(*pc_msg);
        modifier.setPointCloud2FieldsByString(2, "xyz", "rgb");

        sensor_msgs::PointCloud2Iterator<float> iter_x(*pc_msg, "x");
        sensor_msgs::PointCloud2Iterator<float> iter_y(*pc_msg, "y");
        sensor_msgs::PointCloud2Iterator<float> iter_z(*pc_msg, "z");
        sensor_msgs::PointCloud2Iterator<uint8_t> iter_r(*pc_msg, "r");
        sensor_msgs::PointCloud2Iterator<uint8_t> iter_g(*pc_msg, "g");
        sensor_msgs::PointCloud2Iterator<uint8_t> iter_b(*pc_msg, "b");

        int channel_num = color_frame.get_bytes_per_pixel();
        uint8_t* color_data = (uint8_t*)color_frame.get_data();

        for (size_t pnt_idx = 0; pnt_idx < pc_msg->width * pc_msg->height; pnt_idx++)
        {
            *iter_x = vertex[pnt_idx].x;
            *iter_y = vertex[pnt_idx].y;
            *iter_z = vertex[pnt_idx].z;

            *iter_r = color_data[pnt_idx * channel_num];
            *iter_g = color_data[pnt_idx * channel_num + 1];
            *iter_b = color_data[pnt_idx * channel_num + 2];
            ++iter_x;
            ++iter_y;
            ++iter_z;
            ++iter_r;
            ++iter_g;
            ++iter_b;
        }
        // pointcloud_pub_->publish(*pc_msg);
        _pointcloud_publisher->publish(*pc_msg);
    }
    else
    {
        sensor_msgs::msg::PointCloud2::UniquePtr pc_msg = std::make_unique<sensor_msgs::msg::PointCloud2>();
        // debug
        // RCLCPP_INFO(node_->get_logger(), "timestamp: %f, address: %p", t.seconds(),
        // reinterpret_cast<std::uintptr_t>(pc_msg.get()));
        //
        pc_msg->header.stamp = time;
        pc_msg->header.frame_id = DEFAULT_COLOR_OPTICAL_FRAME_ID;
        pc_msg->width = color_frame.get_width();
        pc_msg->height = color_frame.get_height();
        pc_msg->point_step = 3 * sizeof(float) + 3 * sizeof(uint8_t);
        pc_msg->row_step = pc_msg->point_step * pc_msg->width;
        pc_msg->is_dense = true;

        sensor_msgs::PointCloud2Modifier modifier(*pc_msg);
        modifier.setPointCloud2FieldsByString(2, "xyz", "rgb");

        sensor_msgs::PointCloud2Iterator<float> iter_x(*pc_msg, "x");
        sensor_msgs::PointCloud2Iterator<float> iter_y(*pc_msg, "y");
        sensor_msgs::PointCloud2Iterator<float> iter_z(*pc_msg, "z");
        sensor_msgs::PointCloud2Iterator<uint8_t> iter_r(*pc_msg, "r");
        sensor_msgs::PointCloud2Iterator<uint8_t> iter_g(*pc_msg, "g");
        sensor_msgs::PointCloud2Iterator<uint8_t> iter_b(*pc_msg, "b");

        int channel_num = color_frame.get_bytes_per_pixel();
        uint8_t* color_data = (uint8_t*)color_frame.get_data();

        for (size_t pnt_idx = 0; pnt_idx < pc_msg->width * pc_msg->height; pnt_idx++)
        {
            *iter_x = vertex[pnt_idx].x;
            *iter_y = vertex[pnt_idx].y;
            *iter_z = vertex[pnt_idx].z;

            *iter_r = color_data[pnt_idx * channel_num];
            *iter_g = color_data[pnt_idx * channel_num + 1];
            *iter_b = color_data[pnt_idx * channel_num + 2];
            ++iter_x;
            ++iter_y;
            ++iter_z;
            ++iter_r;
            ++iter_g;
            ++iter_b;
        }
        // pointcloud_pub_->publish(std::move(pc_msg));
        _pointcloud_publisher->publish(std::move(pc_msg));
    }
}
```


</p>
</details>

I don't know how efficient this workaround is or if its the way to do it :thinking:  but it is working

**Comment by MartyG-RealSense** [comment]
Thanks very much @charlielito for sharing your method with the RealSense ROS community!

**Comment by joelbudu** [comment]
@charlielito nice work there, I resorted to using the rgbd-launch package in melodic and getting the streams through a ROS1 bridge to ROS2.

For my use case, for an alternative workaround, I found it simpler to try to add support for L515 in the https://github.com/intel/ros2_intel_realsense library. It's fairly trivial to add (the only difference is the number of infrared sensors from the D400 series). I may upload it to my fork if I'm able to complete it

**Comment by doronhi** [comment]
Please check out #1806. It targets ROS2.

**Comment by joelbudu** [comment]
@doronhi Many thanks for working on #1806. Looks really good to me. When is it likely to be merged in please?

**Comment by doronhi** [comment]
Thanks.
The plan is to merge it soon, before the next release - 1-2 weeks tops.

**Comment by charlielito** [comment]
https://github.com/IntelRealSense/realsense-ros/pull/1806 already implemented this. This could be closed

**Comment by MartyG-RealSense** [comment]
As @charlielito referenced, https://github.com/IntelRealSense/realsense-ros/pull/1806 was added in ROS2 wrapper **3.1.6**.  I will therefore close this case.

![image](https://user-images.githubusercontent.com/41145062/122666863-b87ee680-d1a7-11eb-8bc2-d215c78f3af5.png)
