### ISSUE TITLE
ROS, L515 Lower frame rate for Depth image.

### ISSUE THREAD

**Issue by sokhealy** [realsenseai/realsense-ros#1712]
Hi, 
it looks like the minimum frame for the depth image on the L515 is 30 FPS,
Is there a way to lower that to 5 FPS?

**Comment by RealSenseSupport** [comment]
Hi @sokhealy 

The expected and provide frame rate is 30fps.  There is no option to change or lower this frame rate.

**Comment by Giggus** [comment]
Is it still the case?
