### ISSUE TITLE
Problem getting D435i adapted with Kimera-Semantics

### ISSUE THREAD

**Issue by mohammad-h-b** [realsenseai/realsense-ros#1713]
Hi,
I wonder if you let me know whether my issues (https://github.com/MIT-SPARK/Kimera-VIO-ROS/issues/128) and (https://github.com/MIT-SPARK/Kimera-VIO-ROS/issues/129) are due to the my librealsense version (2.2.21)? I tried to upgradre it but don't know how to do so. I have SDK v2.42.

Output:
```
[ INFO] [1613973170.871260270]: Initializing nodelet with 16 worker threads.
[ INFO] [1613973170.937235805]: RealSense ROS v2.2.21
[ INFO] [1613973170.937257022]: Built with LibRealSense v2.41.0
[ INFO] [1613973170.937264973]: Running with LibRealSense v2.41.0
```
![29](https://user-images.githubusercontent.com/43095906/108668958-16c1e400-74aa-11eb-9077-1fb7c46125c4.png)

Please give also the following information:

Operating system and version (e.g. Ubuntu 16.04 or Windows 10): Ubuntu 18.04
Did you change the source code? (yes / no): no

**Comment by MartyG-RealSense** [comment]
Hi @mohammad-h-b   If you are following the official Kimera-VIO-ROS instructions for D435i in the link below, they are currently out of date.  The RealSense ROS wrapper now requires that the IMU topics are enabled in its roslaunch instruction using **enable_gyro:=true enable_accel:=true** as they are disabled by default from wrapper version 2.2.15 onward (July 2020).

https://github.com/MIT-SPARK/Kimera-VIO-ROS/blob/master/docs/hardware_setup.md

Adapting the Kimera-VIO-ROS launch instruction, it would now be:

**roslaunch realsense2_camera rs_camera.launch enable_gyro:=true enable_accel:=true unite_imu_method:=linear_interpolation**

It is also worth mentioning that if you have updated the librealsense version since the last time that you built the RealSense ROS wrapper then the wrapper should be rebuilt.  It is recommended to use wrapper version **2.2.22** with librealsense version **2.42.0**.

**Comment by mohammad-h-b** [comment]
Hi @MartyG-RealSense Thanks for your answer. I'll definitely use the adapted launch file for Kimera-VIO-ROS. Regarding the wrapper, could you please let me know how I can get wrapper version 2.2.22 with librealsense version 2.42.0 working? When I run `realsense-viewer` it opens up v2.42.0 (as shown in the screenshot) but when I do `catkin build` in my `catkin_ws` and relaunch the camera node, it still reports:
```
[ INFO] [1613982438.367514029]: RealSense ROS v2.2.21
[ INFO] [1613982438.367535096]: Built with LibRealSense v2.41.0
[ INFO] [1613982438.367543429]: Running with LibRealSense v2.41.0
```

**Comment by MartyG-RealSense** [comment]
There is not a problem with using librealsense 2.41.0 and wrapper 2.2.21 together.  

If you wish to try 2.42.0 though: as this SDK version is new at the time of writing this, I would recommend installing wrapper 2.2.22 by building it from source code with **Method 2** (i.e build librealsense first and then build 2.2.22 secondly with Method 2).

https://github.com/IntelRealSense/realsense-ros#method-2-the-realsense-distribution

If you installed librealsense and the ROS wrapper together with packages using **Method 1** then the installation packages may still be using 2.41.0 due to the current newness of SDK 2.42.0.  Building the wrapper from source with Method 2 means that you can use a new RealSense ROS wrapper version as soon as it is released.

**Comment by mohammad-h-b** [comment]
Thank you so much @MartyG-RealSense !
So for now I stick to librealsense 2.41.0 and wrapper 2.2.21 together.
I've also tried the new launch file **`roslaunch realsense2_camera rs_camera.launch enable_gyro:=true enable_accel:=true unite_imu_method:=linear_interpolation`**. I am no longer getting erros in (https://github.com/MIT-SPARK/Kimera-VIO-ROS/issues/129) but still running `roslaunch kimera_vio_ros kimera_vio_ros_realsense_IR.launch
` generates all zero values as in (https://github.com/MIT-SPARK/Kimera-VIO-ROS/issues/128) and there is no visulization in rviz.

Could you please let me know about that?

Output:
```
(base) mohammad@mohammad:~/catkin_ws$ roslaunch kimera_vio_ros kimera_vio_ros_realsense_IR.launch
... logging to /home/mohammad/.ros/log/16adb76e-74eb-11eb-8f79-c8e2658ec50b/roslaunch-mohammad-11572.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://mohammad:39771/

SUMMARY
========

PARAMETERS
 * /kimera_vio_ros/kimera_vio_ros_node/base_link_frame_id: base_link
 * /kimera_vio_ros/kimera_vio_ros_node/left_cam_frame_id: left_cam
 * /kimera_vio_ros/kimera_vio_ros_node/map_frame_id: map
 * /kimera_vio_ros/kimera_vio_ros_node/mono_ransac_threshold: 30
 * /kimera_vio_ros/kimera_vio_ros_node/online_run: True
 * /kimera_vio_ros/kimera_vio_ros_node/params_folder_path: /home/mohammad/ca...
 * /kimera_vio_ros/kimera_vio_ros_node/position_det_threshold: 0.3
 * /kimera_vio_ros/kimera_vio_ros_node/right_cam_frame_id: right_cam
 * /kimera_vio_ros/kimera_vio_ros_node/stereo_ransac_threshold: 20
 * /kimera_vio_ros/kimera_vio_ros_node/use_lcd: False
 * /kimera_vio_ros/kimera_vio_ros_node/use_online_cam_params: False
 * /kimera_vio_ros/kimera_vio_ros_node/velocity_det_threshold: 0.1
 * /kimera_vio_ros/kimera_vio_ros_node/world_frame_id: world
 * /kimera_vio_ros/posegraph_viewer/frame_id: world
 * /rosdistro: melodic
 * /rosversion: 1.14.10
 * /use_sim_time: False

NODES
  /
    velo_link_broadcaster (tf/static_transform_publisher)
  /kimera_vio_ros/
    kimera_vio_ros_node (kimera_vio_ros/kimera_vio_ros_node)
    posegraph_viewer (pose_graph_tools/visualizer_node)

ROS_MASTER_URI=http://localhost:11311

process[kimera_vio_ros/kimera_vio_ros_node-1]: started with pid [11588]
process[kimera_vio_ros/posegraph_viewer-2]: started with pid [11589]
process[velo_link_broadcaster-3]: started with pid [11590]
[ INFO] [1613984132.290383413]: Initializing pose graph visualizer
I0222 03:55:32.432449 11588 RegularVioBackEnd.cpp:114] Using Regular VIO backend.
I0222 03:55:32.432530 11588 PipelineModule.h:449] MISO Pipeline Module: Display has no output queue registered.
I0222 03:55:32.432626 11588 Pipeline.cpp:479] Pipeline Modules launched (parallel_run set to 1).
I0222 03:55:32.432745 11588 KimeraVioRos.cpp:117] Statistics
-----------                                  #	Log Hz	{avg     +- std    }	[min,max]
Mesher [ms]                             	    0	
VioBackEnd [ms]                         	    0	
VioFrontEnd [ms]                        	    0	
Visualizer [ms]                         	    0	
backend_input_queue Size [#]            	    0	
data_provider_left_frame_queue Size [#] 	    0	
data_provider_right_frame_queue Size [#]	    0	
display_input_queue Size [#]            	    0	
mesher_backend Size [#]                 	    0	
mesher_frontend Size [#]                	    0	
stereo_frontend_input_queue Size [#]    	    0	
visualizer_backend_queue Size [#]       	    0	
visualizer_frontend_queue Size [#]      	    0	
visualizer_mesher_queue Size [#]        	    0	
I0222 03:55:32.432826 11614 Pipeline.h:199] Spinning Kimera-VIO.
I0222 03:55:33.432844 11588 KimeraVioRos.cpp:117] Statistics
```

**Comment by MartyG-RealSense** [comment]
Given that Kimera makes use of infrared, the lack of data may be related to the same issue as the IMU topics.  The **infra** topics are also disabled by default from wrapper 2.2.15 onwards.  So to ensure that the infrared topics are enabled, please add the instructions below to the roslaunch instruction too:

**enable_infra1:=true enable_infra2:=true**

**Comment by mohammad-h-b** [comment]
Thank @MartyG-RealSense I've added the intsctructions but still get zero values. Also when I run `roslaunch realsense2_camera rs_camera.launch enable_gyro:=true enable_accel:=true unite_imu_method:=linear_accel_cov` I get these warnings as well:
```
22/02 11:56:08,911 WARNING [140615801349888] (backend-v4l2.cpp:1775) Invalid md size: bytes used =  0 ,start offset=10
```
Please note that for the `unite_imu_method` it only has the option `linear_accel_cov` not the `linear_interpolation`.

![32](https://user-images.githubusercontent.com/43095906/108742084-5964da00-7505-11eb-9a1c-c8f1ba7849fa.png)

**Comment by MartyG-RealSense** [comment]
This is a rare error that has only seemed to occur with librealsense 2.41.0.  It was apparently fixed in **2.42.0**.

https://github.com/IntelRealSense/librealsense/issues/8154#issuecomment-767175826

**Comment by mohammad-h-b** [comment]
I see. So is there any fix for the zero values I'm getting?

**Comment by MartyG-RealSense** [comment]
In the **Testing** section of the Kimera instructions, are you launching each instruction in its own separate ROS terminal as specified by the first line of this section, please?

https://github.com/MIT-SPARK/Kimera-VIO-ROS/blob/master/docs/hardware_setup.md#testing

**Comment by mohammad-h-b** [comment]
Yes, I followed all the instructions each in separate terminals:

![101](https://user-images.githubusercontent.com/43095906/108746927-ececd980-750a-11eb-95b5-3fb475472f5c.png)
![102](https://user-images.githubusercontent.com/43095906/108746929-ed857000-750a-11eb-90c4-f786adc0b591.png)
![103](https://user-images.githubusercontent.com/43095906/108746930-ed857000-750a-11eb-9a73-f63440bf6081.png)
![104](https://user-images.githubusercontent.com/43095906/108746931-ee1e0680-750a-11eb-9cbb-b27b9a6f3acd.png)
![105](https://user-images.githubusercontent.com/43095906/108746933-ee1e0680-750a-11eb-900d-47ad8979ca5e.png)
![106](https://user-images.githubusercontent.com/43095906/108746936-eeb69d00-750a-11eb-8094-f516b84c108d.png)
![107](https://user-images.githubusercontent.com/43095906/108746937-eeb69d00-750a-11eb-822b-d122b5e80dfb.png)
![108](https://user-images.githubusercontent.com/43095906/108746938-eeb69d00-750a-11eb-9db1-ad8f86282a68.png)
![109](https://user-images.githubusercontent.com/43095906/108746940-ef4f3380-750a-11eb-87a7-f8307b888dfd.png)
![110](https://user-images.githubusercontent.com/43095906/108746941-ef4f3380-750a-11eb-9cf3-c43eb24fb9bf.png)

**Comment by MartyG-RealSense** [comment]
The above images indicate that librealsense 2.42.0 has been installed but the ROS wrapper has not been rebuilt afterwards.  After a change of librealsense version, the ROS wrapper has to be built again.

![image](https://user-images.githubusercontent.com/41145062/108754259-9e0c6780-753d-11eb-9664-da644364f42e.png)

It is also worth bearing in mind that the more common approach to using SLAM with RealSense D435i is to do so with Intel's own D435i SLAM guide. 

https://github.com/IntelRealSense/realsense-ros/wiki/SLAM-with-D435i

**Comment by mohammad-h-b** [comment]
That's right. I did a whole `caktkin build` in my `catkin_ws` but not sure why it still generates that warning.

**Comment by MartyG-RealSense** [comment]
If you get a version conflict when building in the catkin workspace, I would suggest deleting the catkin workspace and creating a new workspace to build the wrapper in to see whether that makes a difference.

**Comment by mohammad-h-b** [comment]
Thanks @MartyG-RealSense I deleted the catkin workspace and built the wrapper in the new one. Now the warning is gone; however, I'm still getting zero values even with `roslaunch realsense2_camera rs_camera.launch enable_gyro:=true enable_accel:=true enable_infra1:=true enable_infra2:=true unite_imu_method:=linear_interpolation`

**Comment by MartyG-RealSense** [comment]
I wonder whether the continued zero-values are related to calibration of the D435i IMU, and whether the IMU needs to first have a calibration written to the camera hardware using Intel's Python-based IMU calibration tool before using it with Kimera.

https://dev.intelrealsense.com/docs/imu-calibration-tool-for-intel-realsense-depth-camera

Also, it may be that the sub-categories of calibration in point 3 of the Kimera instructions need to be performed in addition to the D435i details that Kimera already has, if you have not already carried out these sub-tasks.

https://github.com/MIT-SPARK/Kimera-VIO-ROS/blob/master/docs/hardware_setup.md

![image](https://user-images.githubusercontent.com/41145062/108893015-7df5aa80-7608-11eb-9d58-191c31f6ee07.png)

**Comment by mohammad-h-b** [comment]
Thanks for the tip!

I'll look into using Intel's Python-based IMU calibration tool.

Regarding the sub-categories of calibration in point 3 of the Kimera instructions, it's mentioned that they are not needed to be done if you want to use the default calibration and launch files. I am using the exact same camera they've used (D435i), so I'm not sure if I need to carry them out.

**Comment by MartyG-RealSense** [comment]
Hi @mohammad-h-b   Do you require further assistance with this case, please?  Thanks!

**Comment by mohammad-h-b** [comment]
Hi @MartyG-RealSense Still I couldn't get it running on my system :(

**Comment by MartyG-RealSense** [comment]
A member of the Kimera forums suggested testing with a bag file instead of live data to see whether there is a problem with Kimera instead of the camera:

https://github.com/MIT-SPARK/Kimera-VIO-ROS/issues/24#issuecomment-625397783

**Comment by mohammad-h-b** [comment]
I just tested kimera with the given rosbag file and it works fine. So I guess the problem is with my D435i, although `realsense-viewer` brings up the camera and it works fine.

**Comment by MartyG-RealSense** [comment]
On the Kimera-VIO-ROS, another D435i user used the details in the link below in their roslaunch file, a modification of kimera_vio_ros_realsense_IR.launch.  They set **online** mode to True in the launch file to use live D435i camera data with `<arg name="online" default="True" />`

https://github.com/MIT-SPARK/Kimera-VIO-ROS/issues/92#issuecomment-698313394

**Comment by mohammad-h-b** [comment]
Thanks @MartyG-RealSense I already set that parameter to true, no success. Anyway, how can I run the Kimera-Semantics in Gazebo? There I could put a sample camera and see how it works.

**Comment by MartyG-RealSense** [comment]
I researched your question.  I could not find an example of gazebo use with Kimera, though somebody else had asked about it.

https://github.com/MIT-SPARK/Kimera-VIO-ROS/issues/119

**Comment by MartyG-RealSense** [comment]
Hi @mohammad-h-b  Do you require further assistance with this case, please?   Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
