### ISSUE TITLE
How to use the topic '/camera/color/Image_raw/compressed' in ROS2 Foxy

### ISSUE THREAD

**Issue by JaehyunShim** [realsenseai/realsense-ros#1720]
Hi, 

I found a similar question in ROS1 in this  https://github.com/IntelRealSense/realsense-ros/issues/1641, but what about ROS2 Foxy? It seems it hasn't been implemented yet. Please advise if I am wrong about this point. 

Jaehyun

**Comment by doronhi** [comment]
following the installation of `ros-foxy-compressed-image-transport`

I can see the following additional topic:
camera/depth/image_rect_raw/compressed

but no:
/camera/color/image_raw/compressed

I also see the message "Failed to load plugin image_transport/compressed_pub, error string: parameter 'format' has already been declared"
Based on #1530 it seems there is an issue with foxy version of image_transport.
