### ISSUE TITLE
Problem in creating a 2D map

### ISSUE THREAD

**Issue by mohammad-h-b** [realsenseai/realsense-ros#1721]
Hi,
I've made the following point cloud but when running `rosrun map_server map_saver map:=/rtabmap/proj_map –f my_map_1` while I'm playing back my rosbag, I get the following message and it saves an incomple map. Could you please help me with that?

```
(base) mohammad@mohammad:~$ rosrun map_server map_saver -f map:=/rtabmap/proj_map my_map_1
[ INFO] [1614183445.487625035]: Waiting for the map
[ INFO] [1614183445.750561386]: Received a 120 X 159 map @ 0.050 m/pix
[ INFO] [1614183445.750589096]: Writing map occupancy data to my_map_1.pgm
[ INFO] [1614183445.751070031]: Writing map occupancy data to my_map_1.yaml
[ INFO] [1614183445.751157548]: Done
```

Saved point cloud:
![36](https://user-images.githubusercontent.com/43095906/109032549-c312ee80-7693-11eb-867a-5a5a1071c373.png)

Savede incomplde 2D map:
![37](https://user-images.githubusercontent.com/43095906/109032641-d920af00-7693-11eb-9cb2-237c81401ac1.png)

**Comment by MartyG-RealSense** [comment]
Hi @mohammad-h-b   The SLAM D435i guide does not guarantee to provide a 2D map that is a close duplication of the point cloud, but instead "something like" it.

For example, the image below shows side by side the point cloud image and the 2D map version of it, which is noticably simpler in detail.

![image](https://user-images.githubusercontent.com/41145062/109045706-ce820c00-76cb-11eb-9027-df18044288e1.png)

I note that your 2D map is zoomed in at 134%.  Do you see more of the image if you zoom out to 100%?

![image](https://user-images.githubusercontent.com/41145062/109048121-9b8d4780-76ce-11eb-934e-21b485ef5bf3.png)

**Comment by mohammad-h-b** [comment]
Thanks @MartyG-RealSense Zooming out doesn't give anymore detail. A simple 2D map is also good. I would like to know if I can extract the 2D map from the `rtabmap.db` file. Besides, why `rosrun map_server map_saver map:=/rtabmap/proj_map –f my_map_1` command doesn't save the 2D map while playing back the rosbag? Should I set any further settings in rviz?

![38](https://user-images.githubusercontent.com/43095906/109050756-c3b58000-76a7-11eb-81d8-4a3169af8678.png)

Something like this helps as well:
https://answers.ros.org/question/217097/export-2d-map-from-rviz-andor-rtab-map/
![image](https://user-images.githubusercontent.com/43095906/109052190-57d41700-76a9-11eb-8b91-ca2bdb88fe8f.png)

**Comment by MartyG-RealSense** [comment]
I found the same link about extracting a 2D map from RTABMAP that you did.

As that discussion is from 2015, I found an alternative reference that is more modern (2019) and seems to confirm the method used in the 2015 article.

https://answers.ros.org/question/316634/trouble-exporting-map-from-rtab-map/

I also researched your question about having to wait until the bag finishes before extracting the map.  It seems to be accepted practice in ROS to do so (not just in RealSense) in order to ensure that the data finishes being processed before it is extracted.

**Comment by MartyG-RealSense** [comment]
Hi @mohammad-h-b  Do you require further assistance with this case, please?   Thanks!

**Comment by mohammad-h-b** [comment]
Hi @MartyG-RealSense No thanks, I'm good.

**Comment by MartyG-RealSense** [comment]
Great, thanks very much @mohammad-h-b for the update!
