### ISSUE TITLE
Detecting house window with Realsesne D435i

### ISSUE THREAD

**Issue by Oburshan** [realsenseai/realsense-ros#1722]
Hey, i am trying to use my drone to enter my room's window with D435i, 
If someone used the depth image / point cloud for this kind of mission and can 
give some insights and techniques that will be helpful it will be great.
Thanks!

**Comment by MartyG-RealSense** [comment]
Hi @Oburshan  A simple way to provide directions to a drone would be to use a **fiducial marker** image for the drone to target.  The RealSense-using medical drones of **Everdrone** can use this method for directing their drones' landing.

https://www.intelrealsense.com/everdrone/

Such tags have also been used with RealSense 400 Series cameras by the automated drone boat project **Roboat** to direct a drone boat towards tags on the docks, which is the kind of forward-facing camera view that might be involved in flying through a window.

https://support.intelrealsense.com/hc/en-us/community/posts/360034814013-Update-on-RealSense-equipped-robot-roboat-autonomous-boats
