### ISSUE TITLE
d435i camera imu sync issue

### ISSUE THREAD

**Issue by snakehaihai** [realsenseai/realsense-ros#1735]
Hi 
I`m currently having issue running with 3/Mar/2021 realsense-ros build

The image and imu are completely out of sync. 

And is there any chance some 1 added the wrong digit at the wrong place e.g first 2 of the nsec should be at secs?

![image](https://user-images.githubusercontent.com/6070995/109802447-cc372900-7c5a-11eb-87ef-b74d3b40faf1.png)
![image](https://user-images.githubusercontent.com/6070995/109803305-dc9bd380-7c5b-11eb-9361-231cf88082f4.png)

**Comment by MartyG-RealSense** [comment]
Hi @snakehaihai   As a starting point in investigating your case, could you try setting **global time** to False please by adding the instruction below to the end of your roslaunch instruction to see whether that improves your results:

**global_time_enabled:=false**

**Comment by snakehaihai** [comment]
> Hi @snakehaihai As a starting point in investigating your case, could you try setting **global time** to False please by adding the instruction below to the end of your roslaunch instruction to see whether that improves your results:
> 
> **global_time_enabled:=false**

Just comeback from lab. will try it tmr

**Comment by snakehaihai** [comment]
Just a quick update. I tried on my friend's PC which loaded with i7+  41 version of librealsense and there is no such issue. so likely this is tie to tx2 + 42 version of librealsense issue.

**Comment by snakehaihai** [comment]
> Hi @snakehaihai As a starting point in investigating your case, could you try setting **global time** to False please by adding the instruction below to the end of your roslaunch instruction to see whether that improves your results:
> 
> **global_time_enabled:=false**

I tried to launch it. still no effect 

![image](https://user-images.githubusercontent.com/6070995/109896119-620a9c80-7ccb-11eb-89d6-a5ab80ffba80.png)

**Comment by snakehaihai** [comment]
hi
I`m using 41 now but with tx2. but the imu header timestamp is still count at the wrong position 
![image](https://user-images.githubusercontent.com/6070995/109902685-c03c7d00-7cd5-11eb-8f73-6f6858c61559.png)

**Comment by snakehaihai** [comment]
changing base_realsense_node.cpp code solved issue. There is a time stamp logic error in the code, i didn't manage to identify it. I just solve it by giving the time at publisher. 

![image](https://user-images.githubusercontent.com/6070995/109909798-b28cf480-7ce1-11eb-9fc2-2b3dc2602768.png)

**Comment by snakehaihai** [comment]
sry.. still can not. just realize that the time are totally not sync and none-peroidc. with the modification on the code. this is the result
![image](https://user-images.githubusercontent.com/6070995/109911316-cbe37000-7ce4-11eb-96f8-7fa1764a5947.png)

without modifying the code. the time look like this 

![image](https://user-images.githubusercontent.com/6070995/109911379-f3d2d380-7ce4-11eb-8273-a9dab6114f70.png)


i already set sync to be true and set "copy" in the unite flag

**Comment by snakehaihai** [comment]
I tried it on DJI manifold 2C / i7 NUC. both 41 and 42 version works without any time sync issue. 

So the issue only ties with DJI manifold 2G/TX2 based platform. likely due to some error during the patch for the kernel.


Ill try to remove the kernel delay for the arm based platform and see how. I remember had problem with VN 100 as well for arm. remove kernel delay helped

**Comment by MartyG-RealSense** [comment]
Thanks very much for the information @snakehaihai - I look forward to an update after your kernel delay tests.   Good luck!

**Comment by snakehaihai** [comment]
no luck. not the kernel delay issue as other IMUs.  The only possibility is to upgrade L4T version but DJI mf2G does not have other higher L4T options.

**Comment by MartyG-RealSense** [comment]
There have been a couple of past cases where setting global time to false OR performing an initial_reset to reset the camera at launch have not improved timing, but performing BOTH global time = false and initial_reset have worked.  In other words, adding this to the end of the roslaunch instruction:

**global_time_enabled:=false initial_reset:=true**

**Comment by MartyG-RealSense** [comment]
Hi @snakehaihai  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
