### ISSUE TITLE
D435i - how to get stereo mono image without ir markers?

### ISSUE THREAD

**Issue by gitsr-sys** [realsenseai/realsense-ros#1740]
I would like to try VIO with two mono images from D435i.

But I can see IR markers on images.
Is there any _arg_ to disable it for stereo mono images?

**Comment by MartyG-RealSense** [comment]
Hi @srnetsr   Could you try disabling the IR emitter with a rosparam, please?

```
<rosparam>
/camera/stereo_module/emitter_enabled: false
</rosparam>
```

**Comment by gitsr-sys** [comment]
Thank you, @MartyG-RealSense 
`$ rosparam list`
I cannot find any parameter of `emitter_enabled`

I am just testing with `rs_camera.launch` file in the realsense-ros package.
Can you advise more specifically?

**Comment by MartyG-RealSense** [comment]
A rosparam instruction would be manually added to the contents of the launch file, in-between `<rosparam>` and `</rosparam>`  (the start and end points of the rosparam section).

I believe that if the file does not currently contain `<rosparam>` and `</rosparam>` definitions then you should paste the entire code block into the file.

```
<rosparam>
/camera/stereo_module/emitter_enabled: false
</rosparam>
```

Alternatively, you could test the instruction by adding **emitter_enabled:=false** to the end of your roslaunch instruction instead:

**roslaunch realsense2_camera rs_camera.launch emitter_enabled:=false**

**Comment by gitsr-sys** [comment]
Hi @MartyG-RealSense ,
I think something wrong.

When I run `$ roslaunch realsense2_camera rs_camera_test.launch emitter_enabled:=false`
```
$ rostopic echo /camera/stereo_module/parameter_updates
bools: 
  - 
    name: "enable_auto_exposure"
    value: True
  - 
    name: "error_polling_enabled"
    value: True
  - 
    name: "output_trigger_enabled"
    value: False
  - 
    name: "emitter_on_off"
    value: False
  - 
    name: "global_time_enabled"
    value: True
  - 
    name: "emitter_always_on"
    value: False
  - 
    name: "hdr_enabled"
    value: False
ints: 
  - 
    name: "exposure"
    value: 8500
  - 
    name: "gain"
    value: 16
  - 
    name: "visual_preset"
    value: 0
  - 
    name: "emitter_enabled"
    value: 1
  - 
    name: "frames_queue_size"
    value: 16
  - 
    name: "sequence_name"
    value: 0
  - 
    name: "sequence_size"
    value: 2
  - 
    name: "sequence_id"
    value: 0
strs: []
doubles: 
  - 
    name: "laser_power"
    value: 150.0
groups: 
  - 
    name: "Default"
    state: True
    id: 0
    parent: 0
---

```

In rviz. The camera is still showing the IR as shown in the following screen capture
![ir](https://user-images.githubusercontent.com/36079398/110566425-05b9d980-811e-11eb-9eea-f174bdc8ab84.png)

Also, I added 
```
  <rosparam>
  /camera/stereo_module/emitter_enabled: false
  </rosparam>
```
in the launch file.
And 
```
$ rosparam get /camera/stereo_module/emitter_enabled
false
```
But still, the camera output is like the same above.

Can you double check the way to disable IR emitter?

**Comment by MartyG-RealSense** [comment]
There was a previous case where the emitter was turning on after launch even though it had been correctly set to false using the commands that I provided above.

https://github.com/IntelRealSense/realsense-ros/issues/1379

The solution by the RealSense user in that case was to "disable the emitter in the base node itself by default".

**Comment by MartyG-RealSense** [comment]
Hi @srnetsr  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
