### ISSUE TITLE
In L515, point cloud topic is not published if 'enable_color' is set to 'false'

### ISSUE THREAD

**Issue by bigbellmercy** [realsenseai/realsense-ros#1744]
Hello, I report a bug (or question).

### Problem
When using L515, the point cloud topic, `/camera/depth/color/points`, is not published if the parameter `enable_color` is set to `false`, though the color topic, `/camera/color/image_raw` is independent to the point cloud topic.

### Environment
x86 desktop and Jetson Nano both
Ubuntu 18.04
ROS melodic
L515 firmware v1.5.4.1
realsense-ros v2.2.22 and v2.2.17 both
librealsense2 v2.42.0

### Build
For Jetson Nano, I've built `librealsense2` SDK and `realsense-ros` package all from source codes as written in #1289 and succeeded. Thanks.

**Comment by RealSenseSupport** [comment]
Thanks for identifying this.  We will have take a look at it.

**Comment by doronhi** [comment]
The default texture for the pointcloud is color so if color is disabled, the pointcloud can't be created.
You didn't attach the log but I expect it contains a warning message: "No stream match for pointcloud chosen texture Process - Color"
You can have a pointcloud without texture by specifying pointcloud->stream_filter->ANY (using rqt_reconfigure or by adding the appropriate lines to the launch file. See other issues for examples of modifying dynamic parameters in the launch file)

**Comment by bigbellmercy** [comment]
Thanks @doronhi ! That revelation is quite useful :+1: When I changed in launch file from `RS2_STREAM_COLOR` to `RS2_STREAM_ANY` the texture became turned off and its point cloud output became faster than before. Thanks!
(`enable_color` seems to be meaningless..)

**Comment by bigbellmercy** [comment]
Additionally inform that this error happens in recent versions:
```
[ INFO] [1617955751.376607034]: RealSense ROS v2.2.23
[ INFO] [1617955751.376851694]: Built with LibRealSense v2.43.0
[ INFO] [1617955751.376994836]: Running with LibRealSense v2.43.0
```

**Comment by doronhi** [comment]
> Additionally inform that this error happens in recent versions:
> 
> ```
> [ INFO] [1617955751.376607034]: RealSense ROS v2.2.23
> [ INFO] [1617955751.376851694]: Built with LibRealSense v2.43.0
> [ INFO] [1617955751.376994836]: Running with LibRealSense v2.43.0
> ```
This is not an error.

**Comment by RealSenseSupport** [comment]
Hi,

Will you be needing further help with this?

*If we don’t hear from you in 7 days, this issue will be closed.*

Thanks

**Comment by bigbellmercy** [comment]
No. Ok to close this. Thanks.
