### ISSUE TITLE
how to measure true FOV in different resolution

### ISSUE THREAD

**Issue by zhangzhouyuan** [realsenseai/realsense-ros#1754]
In Intel-RealSense-D400-Series-Datasheet-June-2020.pdf page 62 tell us: Due to mechanical tolerances of +/-5%, Max and Min FOV values can vary from lens to lens and module to module by ~ +/- 3 degrees.

Have any way to measure true FOV ?

**Comment by MartyG-RealSense** [comment]
Hi @zhangzhouyuan   In the link below, the Chief Technology Officer of the RealSense Group at Intel (agrunnet) provides advice on how to calculate the FOV using maths:

https://github.com/IntelRealSense/librealsense/issues/4179#issuecomment-500860874

**Comment by MartyG-RealSense** [comment]
Hi @zhangzhouyuan  Do you require further assistance with this case, please?  Thanks!

**Comment by zhangzhouyuan** [comment]
ye， we already resolved ，Thanks

**Comment by MartyG-RealSense** [comment]
Thanks very much @zhangzhouyuan for the update!
