### ISSUE TITLE
Vertical Black Bars in Depth Images from L515 on Jetson NX

### ISSUE THREAD

**Issue by BhavyanshM** [realsenseai/realsense-ros#1762]
Hello, 

The image below shows the black vertical bars showing up on L515 depth maps. This issue was verified using two completely separate L515 units tested individually. The problem only arises when using the L515 is used on Jetson using the official instructions ([Jetson-Lib-Realsense](https://github.com/IntelRealSense/librealsense/blob/master/doc/installation_jetson.md)). The sensors work fine on other x86 systems. Could you please suggest a fix to this, or a direction for what could be causing it? The L515 is connected to a Jetson NX and using the following versions of software:

Firmware Version: 1.5.4.1
Librealsense Version: 2.41.0
Realsense ROS version: 2.2.22

![Realsense_L515_VerticalBars](https://user-images.githubusercontent.com/15614868/111547509-48476b80-8747-11eb-99d0-5e79020c38c5.png)

Here is the log generated by realsense-ros node:
$ roslaunch realsense2_camera rs_camera.launch filters:=pointcloud
... logging to /home/jetson/.ros/log/526aa7d6-8769-11eb-af84-a0369f501aa6/roslaunch-jetson-nx-13880.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://localhost:37923/

SUMMARY
========

PARAMETERS
 * /camera/realsense2_camera/accel_fps: -1
 * /camera/realsense2_camera/accel_frame_id: camera_accel_frame
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: False
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/allow_no_texture_points: False
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/calib_odom_file: 
 * /camera/realsense2_camera/clip_distance: -2.0
 * /camera/realsense2_camera/color_fps: -1
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: -1
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: -1
 * /camera/realsense2_camera/confidence_fps: -1
 * /camera/realsense2_camera/confidence_height: -1
 * /camera/realsense2_camera/confidence_width: -1
 * /camera/realsense2_camera/depth_fps: -1
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: -1
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: -1
 * /camera/realsense2_camera/device_type: 
 * /camera/realsense2_camera/enable_accel: False
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_confidence: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye1: False
 * /camera/realsense2_camera/enable_fisheye2: False
 * /camera/realsense2_camera/enable_fisheye: False
 * /camera/realsense2_camera/enable_gyro: False
 * /camera/realsense2_camera/enable_infra1: False
 * /camera/realsense2_camera/enable_infra2: False
 * /camera/realsense2_camera/enable_infra: False
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_pose: False
 * /camera/realsense2_camera/enable_sync: False
 * /camera/realsense2_camera/filters: pointcloud
 * /camera/realsense2_camera/fisheye1_frame_id: camera_fisheye1_f...
 * /camera/realsense2_camera/fisheye1_optical_frame_id: camera_fisheye1_o...
 * /camera/realsense2_camera/fisheye2_frame_id: camera_fisheye2_f...
 * /camera/realsense2_camera/fisheye2_optical_frame_id: camera_fisheye2_o...
 * /camera/realsense2_camera/fisheye_fps: -1
 * /camera/realsense2_camera/fisheye_frame_id: camera_fisheye_frame
 * /camera/realsense2_camera/fisheye_height: -1
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: -1
 * /camera/realsense2_camera/gyro_fps: -1
 * /camera/realsense2_camera/gyro_frame_id: camera_gyro_frame
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/imu_optical_frame_id: camera_imu_optica...
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra_fps: -1
 * /camera/realsense2_camera/infra_height: -1
 * /camera/realsense2_camera/infra_rgb: False
 * /camera/realsense2_camera/infra_width: -1
 * /camera/realsense2_camera/initial_reset: False
 * /camera/realsense2_camera/json_file_path: 
 * /camera/realsense2_camera/linear_accel_cov: 0.01
 * /camera/realsense2_camera/odom_frame_id: camera_odom_frame
 * /camera/realsense2_camera/ordered_pc: False
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/pose_frame_id: camera_pose_frame
 * /camera/realsense2_camera/pose_optical_frame_id: camera_pose_optic...
 * /camera/realsense2_camera/publish_odom_tf: True
 * /camera/realsense2_camera/publish_tf: True
 * /camera/realsense2_camera/rosbag_filename: 
 * /camera/realsense2_camera/serial_no: 
 * /camera/realsense2_camera/tf_publish_rate: 0.0
 * /camera/realsense2_camera/topic_odom_in: odom_in
 * /camera/realsense2_camera/unite_imu_method: 
 * /camera/realsense2_camera/usb_port_id: 
 * /rosdistro: melodic
 * /rosversion: 1.14.10

NODES
  /camera/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)

ROS_MASTER_URI=http://localhost:11311/

process[camera/realsense2_camera_manager-1]: started with pid [13889]
process[camera/realsense2_camera-2]: started with pid [13890]
[ INFO] [1616020788.096154551]: Initializing nodelet with 6 worker threads.
[ INFO] [1616020788.397370604]: RealSense ROS v2.2.22
[ INFO] [1616020788.397523118]: Built with LibRealSense v2.41.0
[ INFO] [1616020788.397604847]: Running with LibRealSense v2.41.0
[ INFO] [1616020788.438010375]:  
[ INFO] [1616020788.509193255]: Device with serial number f0172470 was found.

[ INFO] [1616020788.509411722]: Device with physical ID /sys/devices/3610000.xhci/usb2/2-3/2-3.3/2-3.3:1.0/video4linux/video4 was found.
[ INFO] [1616020788.509501804]: Device with name Intel RealSense L515 was found.
[ INFO] [1616020788.511697388]: Device with port number 2-3.3 was found.
[ INFO] [1616020788.511896815]: Device USB type: 3.2
[ INFO] [1616020788.516191055]: getParameters...
[ INFO] [1616020788.658047976]: setupDevice...
[ INFO] [1616020788.658226762]: JSON file is not provided
[ INFO] [1616020788.658343116]: ROS Node Namespace: camera
[ INFO] [1616020788.658514479]: Device Name: Intel RealSense L515
[ INFO] [1616020788.658616656]: Device Serial No: f0172470
[ INFO] [1616020788.658700465]: Device physical port: /sys/devices/3610000.xhci/usb2/2-3/2-3.3/2-3.3:1.0/video4linux/video4
[ INFO] [1616020788.658777426]: Device FW version: 01.05.04.01
[ INFO] [1616020788.658898324]: Device Product ID: 0x0B64
[ INFO] [1616020788.658998134]: Enable PointCloud: On
[ INFO] [1616020788.659123448]: Align Depth: Off
[ INFO] [1616020788.659225721]: Sync Mode: On
[ INFO] [1616020788.659462781]: Device Sensors: 
[ INFO] [1616020788.662960432]: L500 Depth Sensor was found.
[ INFO] [1616020788.671637169]: RGB Camera was found.
[ INFO] [1616020788.672352700]: Motion Module was found.
[ INFO] [1616020788.672487422]: Add Filter: pointcloud
[ INFO] [1616020788.674168055]: num_filters: 1
[ INFO] [1616020788.674291641]: Setting Dynamic reconfig parameters.
[ INFO] [1616020788.797898691]: Done Setting Dynamic reconfig parameters.
[ INFO] [1616020788.799443385]: depth stream is enabled - width: 640, height: 480, fps: 30, Format: Z16
[ INFO] [1616020788.803686584]: color stream is enabled - width: 1280, height: 720, fps: 30, Format: RGB8
[ INFO] [1616020788.804079646]: setupPublishers...
[ INFO] [1616020788.811206152]: Expected frequency for depth = 30.00000
[ INFO] [1616020788.894330425]: Expected frequency for color = 30.00000
[ INFO] [1616020788.942158975]: setupStreams...
[ INFO] [1616020788.996053663]: insert Depth to L500 Depth Sensor
[ INFO] [1616020788.996292290]: insert Color to RGB Camera
[ INFO] [1616020789.021263765]: SELECTED BASE:Depth, 0
 17/03 17:39:49,184 WARNING [546782540160] (l500-depth.cpp:455) UVC metadata payloads are not available for stream . Please refer to installation chapter for details.
[ INFO] [1616020789.217575795]: RealSense Node Is Up!
[ WARN] [1616020789.374082724]: Frame metadata isn't available! (frame_timestamp_domain = RS2_TIMESTAMP_DOMAIN_SYSTEM_TIME)
 17/03 17:39:50,334 WARNING [546882257280] (l500-depth.cpp:455) UVC metadata payloads are not available for stream . Please refer to installation chapter for detail

**Comment by calvertdw** [comment]
This issue was actually caused by interference from OptiTrack motion capture sensors in the same space as the L515. Turning them off and the L515 data is fixed. This does not vary with CPU architecture.
