### ISSUE TITLE
Camera extrinsics between T265 and D435i on 3d printed mount

### ISSUE THREAD

**Issue by kaushikbalasundar** [realsenseai/realsense-ros#1768]
I have a tracking camera attached to depth camera on a 3d printed mount, and I want to determine their extrinsics. I am aware that the rs-enumerate tool is supposed provide the extrinsics, but I couldn't find any examples of its usage.

**Comment by RealSenseSupport** [comment]
@kaushikbalasundar Please note that rs-enumerate tool can only provide the extrinsic of either D435i or T265. It can't provide the extrinsic between them two. You need look for some method to calibrate and read the extrinsic between them, such as vicalib.

**Comment by kaushikbalasundar** [comment]
Got it, thank you
