### ISSUE TITLE
Unable to recieve two pointclouds from two D435s on same nodelet manager

### ISSUE THREAD

**Issue by Scott-Duncan** [realsenseai/realsense-ros#1770]
**The Bug**

When using the ros-wrapper for the realsense cameras, we've attempted to run two d435's at the same time on the same nodelet manager (one D435 & one D435i). Both cameras are able to publish an RGB image and a depth image if that's all that is set, but any attempt to have the cameras publish a point cloud at the same time results in one of the two cameras not publishing any data. This was also attempted using two separate nodelet managers and the same error occurred. 

Both cameras transmit data on the real sense viewer. Both the librealsense and ros-realsense library were built from source and are the most recent versions at current date. 

**Device information**
    OS: Ubuntu
    OS version: 18.04
    CPU: Jetson Xavier
    Intel Realsense D435 camera
    Intel Realsense D435i camera

Attached are the realsense config files in txt format. The camera names, node names and serial numbers are set through launch files based on those in this repo
[dual_camera.launch.txt](https://github.com/IntelRealSense/realsense-ros/files/6184230/dual_camera.launch.txt)
[rs_camera_2.launch.txt](https://github.com/IntelRealSense/realsense-ros/files/6184231/rs_camera_2.launch.txt)

**Comment by MartyG-RealSense** [comment]
Hello, Intel have a tutorial for operating two 400 Series cameras attached to the same machine but launched in separate ROS terminals to generate individual point clouds and align them.  Does this tutorial help with your poblem, please?

https://github.com/IntelRealSense/realsense-ros/wiki/Showcase-of-using-2-cameras

**Comment by MartyG-RealSense** [comment]
Hi @2137254d  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
