### ISSUE TITLE
L515 - Control transfer returned error

### ISSUE THREAD

**Issue by htawadegetample** [realsenseai/realsense-ros#1771]
Hello Everyone,
I am seeing the "Control transfer returned error" printed every second for l515 camera. I installed from source and used RSUSB_BACKEND flag during compilation. I have used initial_reset=true during launch. I am getting point cloud and image data.
I am running the l515 using ROS melodic on ubuntu 18.04 using a docker container. The kernel version is 5.4.0-67-generic. Following are the logs.

Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://10.100.0.1:40529/

SUMMARY
========

PARAMETERS
 * /camera_0/realsense2_camera/accel_fps: 250
 * /camera_0/realsense2_camera/accel_frame_id: camera_0_accel_frame
 * /camera_0/realsense2_camera/accel_optical_frame_id: camera_0_accel_op...
 * /camera_0/realsense2_camera/align_depth: False
 * /camera_0/realsense2_camera/aligned_depth_to_color_frame_id: camera_0_aligned_...
 * /camera_0/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_0_aligned_...
 * /camera_0/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_0_aligned_...
 * /camera_0/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_0_aligned_...
 * /camera_0/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_0_aligned_...
 * /camera_0/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_0_aligned_...
 * /camera_0/realsense2_camera/allow_no_texture_points: False
 * /camera_0/realsense2_camera/base_frame_id: camera_0_link
 * /camera_0/realsense2_camera/calib_odom_file: 
 * /camera_0/realsense2_camera/clip_distance: -2.0
 * /camera_0/realsense2_camera/color_fps: 30
 * /camera_0/realsense2_camera/color_frame_id: camera_0_color_frame
 * /camera_0/realsense2_camera/color_height: 480
 * /camera_0/realsense2_camera/color_optical_frame_id: camera_0_color_op...
 * /camera_0/realsense2_camera/color_width: 640
 * /camera_0/realsense2_camera/confidence_fps: 30
 * /camera_0/realsense2_camera/confidence_height: 480
 * /camera_0/realsense2_camera/confidence_width: 640
 * /camera_0/realsense2_camera/depth_fps: 30
 * /camera_0/realsense2_camera/depth_frame_id: camera_0_depth_frame
 * /camera_0/realsense2_camera/depth_height: 240
 * /camera_0/realsense2_camera/depth_optical_frame_id: camera_0_depth_op...
 * /camera_0/realsense2_camera/depth_width: 320
 * /camera_0/realsense2_camera/device_type: 
 * /camera_0/realsense2_camera/enable_accel: False
 * /camera_0/realsense2_camera/enable_color: True
 * /camera_0/realsense2_camera/enable_confidence: True
 * /camera_0/realsense2_camera/enable_depth: True
 * /camera_0/realsense2_camera/enable_fisheye1: False
 * /camera_0/realsense2_camera/enable_fisheye2: False
 * /camera_0/realsense2_camera/enable_fisheye: False
 * /camera_0/realsense2_camera/enable_gyro: False
 * /camera_0/realsense2_camera/enable_infra1: False
 * /camera_0/realsense2_camera/enable_infra2: False
 * /camera_0/realsense2_camera/enable_infra: False
 * /camera_0/realsense2_camera/enable_pointcloud: True
 * /camera_0/realsense2_camera/enable_pose: False
 * /camera_0/realsense2_camera/enable_sync: False
 * /camera_0/realsense2_camera/filters: pointcloud
 * /camera_0/realsense2_camera/fisheye1_frame_id: camera_0_fisheye1...
 * /camera_0/realsense2_camera/fisheye1_optical_frame_id: camera_0_fisheye1...
 * /camera_0/realsense2_camera/fisheye2_frame_id: camera_0_fisheye2...
 * /camera_0/realsense2_camera/fisheye2_optical_frame_id: camera_0_fisheye2...
 * /camera_0/realsense2_camera/fisheye_fps: 30
 * /camera_0/realsense2_camera/fisheye_frame_id: camera_0_fisheye_...
 * /camera_0/realsense2_camera/fisheye_height: 480
 * /camera_0/realsense2_camera/fisheye_optical_frame_id: camera_0_fisheye_...
 * /camera_0/realsense2_camera/fisheye_width: 640
 * /camera_0/realsense2_camera/gyro_fps: 400
 * /camera_0/realsense2_camera/gyro_frame_id: camera_0_gyro_frame
 * /camera_0/realsense2_camera/gyro_optical_frame_id: camera_0_gyro_opt...
 * /camera_0/realsense2_camera/imu_optical_frame_id: camera_0_imu_opti...
 * /camera_0/realsense2_camera/infra1_frame_id: camera_0_infra1_f...
 * /camera_0/realsense2_camera/infra1_optical_frame_id: camera_0_infra1_o...
 * /camera_0/realsense2_camera/infra2_frame_id: camera_0_infra2_f...
 * /camera_0/realsense2_camera/infra2_optical_frame_id: camera_0_infra2_o...
 * /camera_0/realsense2_camera/infra_fps: 30
 * /camera_0/realsense2_camera/infra_height: 480
 * /camera_0/realsense2_camera/infra_rgb: False
 * /camera_0/realsense2_camera/infra_width: 640
 * /camera_0/realsense2_camera/initial_reset: True
 * /camera_0/realsense2_camera/json_file_path: /home/hrishikesh/...
 * /camera_0/realsense2_camera/linear_accel_cov: 0.01
 * /camera_0/realsense2_camera/odom_frame_id: camera_0_odom_frame
 * /camera_0/realsense2_camera/pointcloud_texture_index: 0
 * /camera_0/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera_0/realsense2_camera/pose_frame_id: camera_0_pose_frame
 * /camera_0/realsense2_camera/pose_optical_frame_id: camera_0_pose_opt...
 * /camera_0/realsense2_camera/publish_odom_tf: True
 * /camera_0/realsense2_camera/publish_tf: True
 * /camera_0/realsense2_camera/rosbag_filename: 
 * /camera_0/realsense2_camera/serial_no: 
 * /camera_0/realsense2_camera/tf_publish_rate: 0.0
 * /camera_0/realsense2_camera/topic_odom_in: odom_in
 * /camera_0/realsense2_camera/unite_imu_method: 
 * /camera_0/realsense2_camera/usb_port_id: 
 * /camera_0_name: camera_0
 * /num_of_cameras: 1
 * /rosdistro: melodic
 * /rosversion: 1.14.10

NODES
  /camera_0/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)

auto-starting new master
process[master]: started with pid [64]
ROS_MASTER_URI=http://10.100.0.1:11311

setting /run_id to cfbff10a-8b42-11eb-b698-60f262176df8
process[rosout-1]: started with pid [75]
started core service [/rosout]
process[camera_0/realsense2_camera_manager-2]: started with pid [82]
[ INFO] [1616440464.242237900]: Initializing nodelet with 16 worker threads.
process[camera_0/realsense2_camera-3]: started with pid [83]
[ INFO] [1616440464.386733860]: RealSense ROS v2.2.21
[ INFO] [1616440464.386757997]: Built with LibRealSense v2.42.0
[ INFO] [1616440464.386768676]: Running with LibRealSense v2.42.0
[ INFO] [1616440464.403703311]:  
 22/03 19:14:24,513 WARNING [139797083449088] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
[ INFO] [1616440465.147239271]: Device with serial number f0233130 was found.

[ INFO] [1616440465.147270259]: Device with physical ID 5-2.4-10 was found.
[ INFO] [1616440465.147288907]: Device with name Intel RealSense L515 was found.
[ INFO] [1616440465.149370176]: Device with port number 5-2.4 was found.
[ INFO] [1616440465.149395119]: Device USB type: 2.1
[ WARN] [1616440465.149408126]: Device f0233130 is connected using a 2.1 port. Reduced performance is expected.
[ INFO] [1616440465.149439869]: Resetting device...
[ INFO] [1616440471.165152338]:  
 22/03 19:14:31,261 WARNING [139796798228224] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
[ INFO] [1616440471.841247653]: Device with serial number f0233130 was found.

[ INFO] [1616440471.841275325]: Device with physical ID 5-2.4-11 was found.
[ INFO] [1616440471.841282622]: Device with name Intel RealSense L515 was found.
[ INFO] [1616440471.842293258]: Device with port number 5-2.4 was found.
[ INFO] [1616440471.842327696]: Device USB type: 2.1
[ WARN] [1616440471.842355130]: Device f0233130 is connected using a 2.1 port. Reduced performance is expected.
[ INFO] [1616440471.844078030]: getParameters...
[ INFO] [1616440471.871101883]: setupDevice...
 22/03 19:14:32,169 WARNING [139796798228224] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
[ INFO] [1616440472.459764414]: JSON file is loaded! (/home/hrishikesh/catkin_ws/src/PlatformVision/config/l515_camera_config.json)
[ INFO] [1616440472.459906977]: ROS Node Namespace: camera_0
[ INFO] [1616440472.459959056]: Device Name: Intel RealSense L515
[ INFO] [1616440472.460004961]: Device Serial No: f0233130
[ INFO] [1616440472.460068865]: Device physical port: 5-2.4-11
[ INFO] [1616440472.460132119]: Device FW version: 01.05.04.01
[ INFO] [1616440472.460171561]: Device Product ID: 0x0B64
[ INFO] [1616440472.460208111]: Enable PointCloud: On
[ INFO] [1616440472.460288637]: Align Depth: Off
[ INFO] [1616440472.460348854]: Sync Mode: On
[ INFO] [1616440472.461066284]: Device Sensors: 
[ INFO] [1616440472.496212634]: L500 Depth Sensor was found.
[ INFO] [1616440472.516272746]: RGB Camera was found.
[ INFO] [1616440472.516587177]: Motion Module was found.
[ INFO] [1616440472.516950176]: Add Filter: pointcloud
[ INFO] [1616440472.518156323]: num_filters: 1
[ INFO] [1616440472.518197756]: Setting Dynamic reconfig parameters.
[ INFO] [1616440472.883946327]: Done Setting Dynamic reconfig parameters.
[ INFO] [1616440472.885009840]: depth stream is enabled - width: 320, height: 240, fps: 30, Format: Z16
[ INFO] [1616440472.886478590]: color stream is enabled - width: 640, height: 480, fps: 30, Format: RGB8
[ WARN] [1616440472.886653020]: Given stream configuration is not supported by the device!  Stream: Confidence, Stream Index: 0, Width: 640, Height: 480, FPS: 30, Format: None
[ INFO] [1616440472.886743768]: setupPublishers...
[ INFO] [1616440472.893600417]: Expected frequency for depth = 30.00000
[ INFO] [1616440472.956843910]: Expected frequency for color = 30.00000
[ INFO] [1616440472.979632769]: setupStreams...
[ INFO] [1616440473.002963848]: insert Depth to L500 Depth Sensor
[ INFO] [1616440473.003167843]: insert Color to RGB Camera
 22/03 19:14:33,299 WARNING [139796798228224] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
[ INFO] [1616440473.307428513]: SELECTED BASE:Depth, 0
 22/03 19:14:33,349 WARNING [139796798228224] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 22/03 19:14:33,401 WARNING [139796798228224] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
[ INFO] [1616440473.456672468]: RealSense Node Is Up!
 22/03 19:14:34,011 WARNING [139796798228224] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 22/03 19:14:34,354 WARNING [139796798228224] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 22/03 19:14:34,407 WARNING [139796798228224] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 22/03 19:14:35,609 WARNING [139796798228224] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 22/03 19:14:38,064 WARNING [139796798228224] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 22/03 19:14:39,318 WARNING [139796798228224] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 22/03 19:14:40,574 WARNING [139796798228224] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 22/03 19:14:41,828 WARNING [139796798228224] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 22/03 19:14:43,082 WARNING [139796798228224] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 22/03 19:14:44,335 WARNING [139796798228224] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 22/03 19:14:45,588 WARNING [139796798228224] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 22/03 19:14:46,841 WARNING [139796798228224] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 22/03 19:14:49,299 WARNING [139796798228224] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 22/03 19:14:50,553 WARNING [139796798228224] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 22/03 19:14:51,806 WARNING [139796798228224] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61

**Comment by RealSenseSupport** [comment]
Hi @htawadegetample 

You mention using docker container, are you able to see if you get the same error outside of using a docker container?
Also is there a reason why you're using RSUSB?

**Comment by htawadegetample** [comment]
> Hi @htawadegetample
> 
> You mention using docker container, are you able to see if you get the same error outside of using a docker container?
> Also is there a reason why you're using RSUSB?

@RealSenseSupport I tried without the docker container and the issue persists. 
The reason for using RSUSB is that initially I was getting "Failed to query (GET_CUR) UVC control 1 on unit 3: -32" on my dmesg logs. This was similar to [issue7099](https://github.com/IntelRealSense/librealsense/issues/7099) to which the solution mentioned by @MartyG-RealSense was [issue6368](https://github.com/IntelRealSense/librealsense/issues/6368#issuecomment-636316279). This worked for me but then that led to the current issue.

**Comment by RealSenseSupport** [comment]
Are you experiencing any actual functionality problems or just the messages? There's a good discussion here with one of our RealSense engineers related to the control_transfer error messages that might be useful.

https://github.com/IntelRealSense/realsense-ros/issues/1162

Thanks

**Comment by htawadegetample** [comment]
> Are you experiencing any actual functionality problems or just the messages? There's a good discussion here with one of our RealSense engineers related to the control_transfer error messages that might be useful.
> 
> #1162
> 
> Thanks

**Comment by htawadegetample** [comment]
@RealSenseSupport there are no functionality issues. But it spams the logs.

**Comment by Schweizliu** [comment]
> Are you experiencing any actual functionality problems or just the messages? There's a good discussion here with one of our RealSense engineers related to the control_transfer error messages that might be useful.
> 
> #1162
> 
> Thanks

I found that using the download source code compilation method git clone https://github.com/IntelRealSense/realsense-ros Run roslaunch realsene2_ Camera rs_ (messenger library. cpp: 42) control will not appear when camera. launch_ Transfer returned error, and when I use another direct download method: sudo apt-get install ros-noetic-realsense2-camera, the above warning will appear, and modifying any parameters is useless

**Comment by MartyG-RealSense** [comment]
Hi @Schweizliu  If you have used the **sudo apt-get install ros-noetic-realsense2-camera** installation instruction after having already installed the librealsense SDK then you may have installed librealsense twice and have a conflict between the multiple librealsense versions.  This is because the sudo apt-get instruction installs both librealsense and the RealSense ROS wrapper from packages at the same time.  So if librealsense was installed first and then sudo apt-get was used then a second installation of librealsense would be created.

**Comment by MartyG-RealSense** [comment]
Hi @Schweizliu  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
