### ISSUE TITLE
Auto Shutdown after launching 

### ISSUE THREAD

**Issue by loguna123** [realsenseai/realsense-ros#1781]
Hi,

When i launch my real sense D435i using "rs_camera.launch", it runs for a few seconds and shutdown giving me a  message:"process has finished cleanly" on the terminal.

**Comment by MartyG-RealSense** [comment]
Hi @loguna123  As a starting point in investigating your case, could you try adding the instruction below to the end of your roslaunch instruction to see whether it improves your situation, please?  The command performs a reset of the camera at launch:

**initial_reset:=true**

**Comment by MartyG-RealSense** [comment]
Hi @loguna123  Do you require further assistance with this case, please?  Thanks!

**Comment by loguna123** [comment]
Hi, 
Thanks for helping me.

**Comment by MartyG-RealSense** [comment]
You are very welcome @loguna123 - thanks for the update!
