### ISSUE TITLE
Can't appear the picture

### ISSUE THREAD

**Issue by fanfanchifan** [realsenseai/realsense-ros#179]
### System Configuration

| Version               | Your Configuration   |
|:--------------------- |:---------------------|
| Operating System      | Ubuntu 14.04.5 LTS           |
| Kernel                | 4.4.0-57-generic        |
| ROS                   | indigo                  |
| ROS RealSense         | 1.6.0            |
| librealsense          | 1.11.1             |
| Camera Type-Firmware  | Intel RealSense R200           |

---

### Expected Behavior
I'm a rookie to use ros and the realsense,I want to use the realsense to appear the picture. I don't know what next to do.

### Actual Behavior
 
`... logging to /home/turtlebot/.ros/log/3bfc6642-cd8c-11e6-9613-58fb84a27597/roslaunch-zero-turtlebot-8760.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://192.168.1.107:42609/

SUMMARY
========

PARAMETERS
 * /camera/driver/base_frame_id: camera_link
 * /camera/driver/camera_type: R200
 * /camera/driver/color_frame_id: camera_rgb_frame
 * /camera/driver/color_optical_frame_id: camera_rgb_optica...
 * /camera/driver/depth_frame_id: camera_depth_frame
 * /camera/driver/depth_optical_frame_id: camera_depth_opti...
 * /camera/driver/fisheye_frame_id: camera_fisheye_frame
 * /camera/driver/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/driver/imu_frame_id: camera_imu_frame
 * /camera/driver/imu_optical_frame_id: camera_imu_optica...
 * /camera/driver/ir2_frame_id: camera_ir2_frame
 * /camera/driver/ir2_optical_frame_id: camera_ir2_optica...
 * /camera/driver/ir_frame_id: camera_ir_frame
 * /camera/driver/ir_optical_frame_id: camera_ir_optical...
 * /camera/driver/serial_no: 
 * /camera/driver/usb_port_id: 
 * /rosdistro: indigo
 * /rosversion: 1.11.20

NODES
  /camera/
    camera_nodelet_manager (nodelet/nodelet)
    driver (nodelet/nodelet)

auto-starting new master
process[master]: started with pid [8772]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 3bfc6642-cd8c-11e6-9613-58fb84a27597
process[rosout-1]: started with pid [8785]
started core service [/rosout]
process[camera/camera_nodelet_manager-2]: started with pid [8794]
process[camera/driver-3]: started with pid [8798]
[ INFO] [1482991287.231899598]: Initializing nodelet with 4 worker threads.
[ INFO] [1482991287.526225348]: /camera/driver - Detected the following cameras:
				- Serial No: 2431002873, USB Port ID: 2-2, Name: Intel RealSense R200, Camera FW: 1.0.72.06
[ INFO] [1482991287.526339826]: /camera/driver - Connecting to camera with Serial No: 2431002873, USB Port ID: 2-2
[ INFO] [1482991288.075202524]: /camera/driver - Setting static camera options
[ INFO] [1482991288.082955446]: /camera/driver - Enabling Color in preset mode
[ INFO] [1482991288.083319663]: /camera/driver - Enabling Depth in preset mode
[ INFO] [1482991288.083489728]: /camera/driver - Enabling IR in preset mode
[ INFO] [1482991288.083593191]: /camera/driver - Enabling IR2 in preset mode
[ INFO] [1482991288.083697028]: /camera/driver - Starting camera
[ INFO] [1482991288.116028070]: /camera/driver - Publishing camera transforms
[ INFO] [1482991288.116268265]: /camera/driver - Setting dynamic camera options (r200_dc_preset=5)
[ INFO] [1482991288.861557091]: /camera/driver - Initializing Depth Control Preset to 5
[ INFO] [1482991288.861640551]: /camera/driver - NOTICE: Individual Depth Control values set by params will be ignored; set r200_dc_preset=-1 to override.
[ INFO] [1482991290.437718892]: /camera/driver - Setting dynamic camera options

`

### Steps to Reproduce
roslaunch realsense_camera r200_nodelet_default.launch

**Comment by mdhorn** [comment]
First step, update to the latest versions of the realsense package:
`sudo apt-get update`
`sudo apt-get upgrade`

Next, you should probably look through some of the ROS Tutorials to get an understanding of how ROS works:
http://wiki.ros.org/ROS/StartGuide

After going through some of the Tutorials from the Start Guide, you'll see that command you ran launches the realsense camera node and it will be publishing image data.
To view the image data you can use RVIZ:
`rosrun rviz rviz -d $(rospack find realsense_camera)/rviz/realsense_default.rviz`
or just use the image view:
`rosrun image_view image_view image:=/camera/color/image_raw`

There is a RealSense specific Tutorial here:
http://wiki.ros.org/realsense_camera/Tutorials
Review the end of this Developer journey on using RVIZ or image viewer:
https://01.org/developerjourney/installing-ubutnu-1404-lts-intel-realsense-robotic-development-kit

That should get you started.
