### ISSUE TITLE
How to get distance in ROS?

### ISSUE THREAD

**Issue by Ryoga723** [realsenseai/realsense-ros#1790]
Hello,

I would like to get distance from realsense camera to object more accurately.
Now I use infomation of topic which is named /camera/depth/image_rect_raw/compressed.

And I use this command to get distance.
distance = 0.001*cv_ptr->image.at<u_int16_t>(cv_ptr->image.rows, cv_ptr->image.cols);

But in realsense viewer which is built by realsense-viewer command, the stereo module give me more accurate infomation of distance.
 I want to use this data in ROS. And I don't know how to get it.

Please help me with my problem.

**Comment by MartyG-RealSense** [comment]
Hi @Ryoga723   The discussion in the link below suggests a range of different approaches to obtaining the distance in ROS.

https://github.com/IntelRealSense/realsense-ros/issues/1524

Within that discussion, **Doronhi** the RealSense ROS wrapper developer suggests using a script called **show_center_depth.py**

https://github.com/IntelRealSense/realsense-ros/issues/1524#issuecomment-735353329

**Comment by MartyG-RealSense** [comment]
Hi @Ryoga723  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
