### ISSUE TITLE
why I get nothing when I echo '/camera/aligned_depth_to_color/image_raw'

### ISSUE THREAD

**Issue by Zixin-Tang** [realsenseai/realsense-ros#1795]
hello,

I try to get the depth image from realsense d435i, so I conduct the commands below:

`roslaunch realsense2_camera rs_rgbd.launch`

when I echo topic `/camera/color/image_raw`, I get data successfully.

However, when I echo topic `/camera/aligned_depth_to_color/image_raw`, nothing output.

Could you tell me what causes this problem and how to solve it?

**Comment by MartyG-RealSense** [comment]
Hi @wozxfdha  Did you include the term **align_depth:=true** in your roslaunch instruction to publish additional topics aligned to the depth, please?

**roslaunch realsense2_camera rs_rgbd.launch align_depth:=true**

**Comment by Zixin-Tang** [comment]
@MartyG-RealSense  Thanks for your reply.

After I conduct `roslaunch realsense2_camera rs_rgbd.launch align_depth:=true`

The problem still exists.

**Comment by Zixin-Tang** [comment]
@MartyG-RealSense  More details are below.

> `$ roslaunch realsense2_camera rs_rgbd.launch align_depth:=true
... logging to /home/robot/.ros/log/7a274b0a-984c-11eb-94b9-5cc5d4d4302d/roslaunch-robot-ThinkPad-T440p-11154.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://robot-ThinkPad-T440p:35935/

SUMMARY
========

PARAMETERS
 * /camera/realsense2_camera/accel_fps: 250
 * /camera/realsense2_camera/accel_frame_id: camera_accel_frame
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: True
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/allow_no_texture_points: False
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/calib_odom_file: 
 * /camera/realsense2_camera/clip_distance: -1.0
 * /camera/realsense2_camera/color_fps: 30
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: 480
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: 640
 * /camera/realsense2_camera/depth_fps: 30
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: 480
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: 640
 * /camera/realsense2_camera/device_type: 
 * /camera/realsense2_camera/enable_accel: True
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye1: True
 * /camera/realsense2_camera/enable_fisheye2: True
 * /camera/realsense2_camera/enable_fisheye: True
 * /camera/realsense2_camera/enable_gyro: True
 * /camera/realsense2_camera/enable_infra1: True
 * /camera/realsense2_camera/enable_infra2: True
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_sync: True
 * /camera/realsense2_camera/filters: 
 * /camera/realsense2_camera/fisheye1_frame_id: camera_fisheye1_f...
 * /camera/realsense2_camera/fisheye1_optical_frame_id: camera_fisheye1_o...
 * /camera/realsense2_camera/fisheye2_frame_id: camera_fisheye2_f...
 * /camera/realsense2_camera/fisheye2_optical_frame_id: camera_fisheye2_o...
 * /camera/realsense2_camera/fisheye_fps: 30
 * /camera/realsense2_camera/fisheye_frame_id: camera_fisheye_frame
 * /camera/realsense2_camera/fisheye_height: 480
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: 640
 * /camera/realsense2_camera/gyro_fps: 400
 * /camera/realsense2_camera/gyro_frame_id: camera_gyro_frame
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/imu_optical_frame_id: camera_imu_optica...
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra_fps: 30
 * /camera/realsense2_camera/infra_height: 480
 * /camera/realsense2_camera/infra_width: 640
 * /camera/realsense2_camera/initial_reset: False
 * /camera/realsense2_camera/json_file_path: 
 * /camera/realsense2_camera/linear_accel_cov: 0.01
 * /camera/realsense2_camera/odom_frame_id: camera_odom_frame
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/pose_frame_id: camera_pose_frame
 * /camera/realsense2_camera/pose_optical_frame_id: camera_pose_optic...
 * /camera/realsense2_camera/publish_odom_tf: True
 * /camera/realsense2_camera/publish_tf: True
 * /camera/realsense2_camera/rosbag_filename: 
 * /camera/realsense2_camera/serial_no: 
 * /camera/realsense2_camera/tf_publish_rate: 0.0
 * /camera/realsense2_camera/topic_odom_in: camera/odom_in
 * /camera/realsense2_camera/unite_imu_method: none
 * /camera/realsense2_camera/usb_port_id: 
 * /rosdistro: kinetic
 * /rosversion: 1.12.17

NODES
  /camera/
    color_rectify_color (nodelet/nodelet)
    points_xyzrgb_hw_registered (nodelet/nodelet)
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)

auto-starting new master
process[master]: started with pid [11164]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 7a274b0a-984c-11eb-94b9-5cc5d4d4302d
process[rosout-1]: started with pid [11178]
started core service [/rosout]
process[camera/realsense2_camera_manager-2]: started with pid [11195]
process[camera/realsense2_camera-3]: started with pid [11196]
process[camera/color_rectify_color-4]: started with pid [11197]
process[camera/points_xyzrgb_hw_registered-5]: started with pid [11199]
[ INFO] [1617873980.693380468]: Initializing nodelet with 8 worker threads.
[ INFO] [1617873980.752476128]: RealSense ROS v2.2.12
[ INFO] [1617873980.752507384]: Running with LibRealSense v2.31.0
[ INFO] [1617873981.210952607]:  
 08/04 17:26:21,233 WARNING [140056416257792] (types.cpp:49) hwmon command 0x4f failed. Error type: No data to return (-21).
[ INFO] [1617873981.234772171]: Device with serial number 014122070717 was found.

[ INFO] [1617873981.234832275]: Device with physical ID /sys/devices/pci0000:00/0000:00:14.0/usb3/3-3/3-3.1/3-3.1:1.0/video4linux/video0 was found.
[ INFO] [1617873981.234850061]: Device with name Intel RealSense D435I was found.
[ INFO] [1617873981.236789161]: Device with port number 3-3.1 was found.
[ INFO] [1617873981.243936084]: getParameters...
[ INFO] [1617873981.306531833]: setupDevice...
[ INFO] [1617873981.306580767]: JSON file is not provided
[ INFO] [1617873981.306609878]: ROS Node Namespace: camera
[ INFO] [1617873981.306643090]: Device Name: Intel RealSense D435I
[ INFO] [1617873981.306661030]: Device Serial No: 014122070717
[ INFO] [1617873981.306682631]: Device physical port: /sys/devices/pci0000:00/0000:00:14.0/usb3/3-3/3-3.1/3-3.1:1.0/video4linux/video0
[ INFO] [1617873981.306700701]: Device FW version: 05.12.09.00
[ INFO] [1617873981.306716637]: Device Product ID: 0x0B3A
[ INFO] [1617873981.306732445]: Enable PointCloud: Off
[ INFO] [1617873981.306755592]: Align Depth: On
[ INFO] [1617873981.306769228]: Sync Mode: On
[ INFO] [1617873981.307153105]: Device Sensors: 
[ INFO] [1617873981.307383858]: Stereo Module was found.
[ INFO] [1617873981.307440445]: RGB Camera was found.
[ INFO] [1617873981.307466159]: Motion Module was found.
[ INFO] [1617873981.307508681]: (Fisheye, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1617873981.307527760]: (Fisheye, 1) sensor isn't supported by current device! -- Skipping...
[ INFO] [1617873981.307542977]: (Fisheye, 2) sensor isn't supported by current device! -- Skipping...
[ INFO] [1617873981.307560337]: (Pose, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1617873981.307739763]: num_filters: 0
[ INFO] [1617873981.307755871]: Setting Dynamic reconfig parameters.
[ INFO] [1617873981.371390619]: Done Setting Dynamic reconfig parameters.
[ INFO] [1617873981.376538297]: depth stream is enabled - width: 640, height: 480, fps: 30, Format: Z16
[ INFO] [1617873981.376768588]: infra1 stream is enabled - width: 640, height: 480, fps: 30, Format: Y8
[ WARN] [1617873981.376838221]: Given stream configuration is not supported by the device!  Stream: Infrared, Stream Index: 2, Width: 640, Height: 480, FPS: 30
[ INFO] [1617873981.383317661]: color stream is enabled - width: 640, height: 480, fps: 30, Format: RGB8
[ INFO] [1617873981.385382014]: setupPublishers...
[ INFO] [1617873981.388424572]: Expected frequency for depth = 30.00000
[ INFO] [1617873981.419272256]: Expected frequency for infra1 = 30.00000
[ INFO] [1617873981.447672667]: Expected frequency for aligned_depth_to_infra1 = 30.00000
[ INFO] [1617873981.474283177]: Expected frequency for color = 30.00000
[ INFO] [1617873981.499003461]: Expected frequency for aligned_depth_to_color = 30.00000
[ INFO] [1617873981.530063942]: setupStreams...
[ INFO] [1617873981.531578677]: insert Depth to Stereo Module
[ INFO] [1617873981.531833953]: insert Color to RGB Camera
[ INFO] [1617873981.531888972]: insert Infrared to Stereo Module
[ INFO] [1617873981.531926102]: insert Gyro to Motion Module
[ INFO] [1617873981.531963565]: insert Accel to Motion Module
[ INFO] [1617873981.567776507]: SELECTED BASE:Depth, 0
[ INFO] [1617873981.583534475]: RealSense Node Is Up!
 08/04 17:26:21,671 WARNING [140056039118592] (sensor.cpp:962) HID timestamp not found, switching to Host timestamps.
 08/04 17:26:21,707 WARNING [140055662294784] (ds5-timestamp.cpp:76) UVC metadata payloads not available. Please refer to the installation chapter for details.
 08/04 17:26:22,011 WARNING [140056019859200] (ds5-timestamp.cpp:76) UVC metadata payloads not available. Please refer to the installation chapter for details.`

**Comment by Zixin-Tang** [comment]
I figure it out.

This problem is caused by the usb port, when I plug it to usb3.0 port, it is solved (I use usb2.0 port before).

**Comment by MartyG-RealSense** [comment]
Great to hear that you found a solution @wozxfdha - thanks for the update!
