### ISSUE TITLE
L515 Intrinsic Parameters

### ISSUE THREAD

**Issue by MBaranPeker** [realsenseai/realsense-ros#1817]
hi, I am trying to get camera intrinsic parameters by subscribing camera_info topic. But I am facing with a problem, whenever I change resolution in the rs_camera.xml file the parameters doesn't change. It only shows intrinsic parameters for 1280*720 resolution. When ros_wrapper runs I can see it runs with new resolution but Intrinsic parameters are always the same.
I will be so happy if anybody can help me on this. Thanks

**Comment by RealSenseSupport** [comment]
Hi @MBaranPeker 

Does this only happen in ROS?  You're looking for RGB intrinsic I'm assuming.  The L515 camera supports 3 RGB resolutions 1920x1080, 1280x720, 960x540.  Are you trying some other resolution?
Running rs-enumerate-devices -c will provide you with intrinsic information.

**Comment by doronhi** [comment]
Which ROS distribution do you use please?
When I try I see different values in the *camera_info* topic when I run with different resolutions.
Are you sure you manage to change the resolution? Take a look at [librealsense #8971](https://github.com/IntelRealSense/librealsense/issues/8971)

**Comment by MBaranPeker** [comment]
@doronhi thank you for your answer. Melodic. Actually I have followed librealsense before cahnging the resolution did not work anyway i handeled that in another way
