### ISSUE TITLE
Set auto exposure upper limit

### ISSUE THREAD

**Issue by yorumun** [realsenseai/realsense-ros#1821]
Is it possible to limit the color exposure when Auto Exposure is enabled?
I want to reduce blur when the subject is moving at night.

Thanks.

**Comment by MartyG-RealSense** [comment]
Hi @yorumun  If you are using ROS, you could try using a **Region of Interest (ROI)** for the RGB auto-exposure.  The documentation link below states that this can be done with **/camera/rgb_camera/auto_exposure_roi/**

https://dev.intelrealsense.com/docs/ros-wrapper#section-d-400-stereo-depth-cameras

The link below provides an example of setting the RGB ROI in ROS with a rosparam in the launch file.

https://github.com/IntelRealSense/realsense-ros/issues/900#issuecomment-547261460

You should also be able to set the RGB ROI dynamically with rqt_reconfigure during runtime if you need different ROI settings for day and night.

**Comment by yorumun** [comment]
Hi @MartyG-RealSense  Thanks for the reply.
Sorry for the lack of explanation.

I am using ROS and I am using dynamic_reconfigure to set the ROI.
However, I am having trouble with blurring.
So I would like to set the upper limit of the exposure value.
Is there any good way to do this?

**Comment by MartyG-RealSense** [comment]
I understood your meaning and suggested an RGB ROI as a means of controlling the pixel intensity whilst auto-exposure is enabled.

In regard to reducing blurring, could you tell me which camera model you are using please?

**Comment by yorumun** [comment]
I understand. Thank you very much.

I am using a D455.

**Comment by MartyG-RealSense** [comment]
You could try setting **Auto-Exposure Priority** to false. When auto-exposure is enabled and auto-exposure priority is disabled, a constant FPS should be enforced instead of the FPS being able to vary depending upon exposure.

https://github.com/IntelRealSense/realsense-ros/issues/1349#issuecomment-681695259

**Comment by yorumun** [comment]
I tried that setting, but it caused blurring.
I set image size is 1280 x 720 and FPS is 30.

Can I set maximum exposure time value?
Dose "RS2_OPTION_AUTO_EXPOSURE_LIMIT" option disable in D455?

**Comment by MartyG-RealSense** [comment]
The documentation for **RS2_OPTION_AUTO_EXPOSURE_LIMIT** states that its default value is '0', which means that the full exposure range is used by default.  

https://intelrealsense.github.io/librealsense/doxygen/rs__option_8h.html#a8b9c011f705cfab20c7eaaa7a26040e2ac11001971364b90b542941e51ebb911a

**Comment by yorumun** [comment]
I understand.
I want to change the value of the maximum exposure time.

So I would like to know if it is possible to change this value in realsense-ros.

If not, I would like to know if I can change "RS2_OPTION_AUTO_EXPOSURE_LIMIT" directly.
When I tried to change the value with the following code, `RuntimeError: object doesn't support option #85` occurred.

```
import pyrealsense2 as rs

pipeline = rs.pipeline()
config = rs.config()
config.enable_stream(rs.stream.depth, 1280, 720, rs.format.z16, 30)
config.enable_stream(rs.stream.color, 1280, 720, rs.format.bgr8, 30)

profile = pipeline.start(config)

sensor = profile.get_device().first_color_sensor()

sensor.set_option(rs.option.enable_auto_exposure, True)
sensor.set_option(rs.option.auto_exposure_limit, 100)
```

**Comment by MartyG-RealSense** [comment]
It looks as though **RS2_OPTION_AUTO_EXPOSURE_LIMIT** is a depth sensor option rather than a color sensor one.

https://github.com/IntelRealSense/librealsense/blob/master/src/ds5/ds5-device.cpp#L982

I cannot think of a way to enforce limits on **color** exposure whilst color auto-exposure is enabled.

**Comment by MartyG-RealSense** [comment]
Hi @yorumun  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.

**Comment by patrickwasp** [comment]
@yorumun did you ever find a work around for this?
