### ISSUE TITLE
Dashing StaticTransformBroadcaster late subscription

### ISSUE THREAD

**Issue by daziFR** [realsenseai/realsense-ros#1823]
Hi,

I'm testing of 3.1.5 single wrapper supporting Dashing, Eloquent and Foxy. 
There is an issue with late subscriber (rviz), with warning for fixed frame: "No tf data. Actual error: Frame [map] does not exist". Fixed frame cannot be changed.

More information is already given in the: https://github.com/IntelRealSense/librealsense/issues/8863

There was a solution for this problem for old, obsolete ROS2 wrapper supporting Dashing.

Can you comment on this? I've tried to integrate this old fix and it does work, but maybe there is another approach.

Thank You.

**Comment by MartyG-RealSense** [comment]
Thanks very much @daziFR for your report.

@doronhi   Could you comment on this case please?  Thanks!

**Comment by doronhi** [comment]
Hi @daziFR , thanks for the elaborate description.
I think the [solution for this problem for old, obsolete ROS2 wrapper](https://github.com/intel/ros2_intel_realsense/pull/87) is already incorporated into this wrapper using the **tf_publish_rate** option. Try adding **tf_publish_rate:=1.0**

**Comment by MartyG-RealSense** [comment]
Hi @daziFR  Do you require further assistance with this case, please?  Thanks!

**Comment by daziFR** [comment]
Hi @MartyG-RealSense and @doronhi . I've tried setting the **tf_publish_rate:=1.0** and it works with late subscription. Topic can be closed. Thanks.

**Comment by MartyG-RealSense** [comment]
Great to hear that you were successful @daziFR - thanks very much for the update!
