### ISSUE TITLE
Pointcloud with no texture?

### ISSUE THREAD

**Issue by JeremieBourque1** [realsenseai/realsense-ros#1834]
Hi,

Is it possible for the d455 to publish the pointcloud without any texture (just XYZ) in order to cut down on the size of the cloud?

Thanks

**Comment by MartyG-RealSense** [comment]
Hi @JeremieBourque1   My understanding is that a texture-free point cloud can be generated by editing the launch file arg **pointcloud_texture_stream** to be defined as **RS2_STREAM_ANY** instead of RS2_STREAM_COLOR

https://github.com/IntelRealSense/realsense-ros/blob/development/realsense2_camera/launch/rs_camera.launch#L46

If you do not want to edit the launch file then you could add the instruction **pointcloud_texture_stream:=RS2_STREAM_ANY** to the end of an **rs_camera** roslaunch instruction:

For example:

**roslaunch realsense2_camera rs_camera.launch filters:=pointcloud pointcloud_texture_stream:=RS2_STREAM_ANY**

**Comment by JeremieBourque1** [comment]
I tried it and using RS2_STREAM_ANY replaces the `rgb` field by the `intensity` field but the bandwith used by the topic is the same for both so I am not getting the size reduction I was hoping for

**Comment by MartyG-RealSense** [comment]
If you do not need color, do you see improvement in overall bandwidth usage if you add **enable_color:=false** to the roslaunch instruction to not publish the color topic?

**roslaunch realsense2_camera rs_camera.launch filters:=pointcloud pointcloud_texture_stream:=RS2_STREAM_ANY enable_color:=false**

**Comment by JeremieBourque1** [comment]
Disabling color didn't have an impact on the bandwith

**Comment by MartyG-RealSense** [comment]
Is reducing the resolution or FPS speed of the depth topic an option for you, please?

**Comment by doronhi** [comment]
Hi @JeremieBourque1 
Setting the flag **pointcloud_texture_stream:=RS2_STREAM_ANY** as @MartyG-RealSense mentions should have reduced the BW. There is a bug regarding this and I just push #1842 to fix it.
However, when testing you should consider the fact that by default, a pointcloud with color texture covers only the FOV (field-of-view) where color points are available which is smaller than the FOV of the depth sensor. So by requesting a pointcloud without texture you get a pointcloud that covers more space and therefore may be larger than the one with color texture.
A valid comparison will be to also add the flag **allow_no_texture_points:=true** - then you will compare the same number of points and see the true difference in the BW (That is, after applying #1842).
Also, I would like to point out that the 3 coordinate values, x, y, z are allocated with 4 bytes each. The texture is allocated with 4 bytes per pixel. The expected reduction in size is therefore around 25%.

**Comment by JeremieBourque1** [comment]
I tried with the latest commit and with `allow_no_texture_points:=true` but I am actually getting a higher BW when using `RS2_STREAM_ANY`.
With `RS2_STREAM_COLOR` I am getting around 200 MB/s while with `RS2_STREAM_ANY` I am getting 225 MB/s.
I am using `rostopic bw` to measure the bandwith.

**Comment by doronhi** [comment]
I wonder if that has something to do with a ceiling of bandwidth. Could you try with lower fps? Also, it may be easier to compare when using **ordered_pc:=true** as the size should remain constant between frames.

**Comment by MartyG-RealSense** [comment]
Hi @JeremieBourque1  Do you require further assistance with this case, please?  Thanks!

**Comment by mszuyx** [comment]
Hi, @doronhi @MartyG-RealSense 

- I followed a similar launch setting for d455 and I also find almost no difference between RS2_STREAM_ANY / RS2_STREAM_COLOR in terms of BW ("ANY" can reduce ~ 3% of BW, according to rostopic bw). I found someone suggest using uncolored pointcloud will consume more CPU: https://answers.ros.org/question/308978/intel-realsense-d435-pointcloud2-without-rgb/  I not sure how to fact check this, can you elaborate on this topic a little?

**(Update, after re-pull from the latest repo, the reduction is ~20%, my bad, the previous test must have done in an version without the fix in https://github.com/IntelRealSense/realsense-ros/pull/1842)**

- In short, I hope to have two separate streams of data, pointcloud and RGB. Therefore, I need to set the "enable_color" to be true. My objective is to create an OctoMap based on the pointcloud stream (the texture of the pointcloud does not matter) while being able to do some classification work with the RGB stream. In this use case, what is the best practice?

- Also, how much would the "ordered_pc" option impact the processing speed?

Big thank you!

My launch parameters are attached here:
```
<launch>
  <arg name="serial_no"           default=""/>
  <arg name="usb_port_id"         default=""/>
  <arg name="device_type"         default="d455"/>
  <arg name="json_file_path"      default=""/>
  <arg name="camera"              default="d455"/>
  <arg name="tf_prefix"           default="$(arg camera)"/>
  <arg name="external_manager"    default="false"/>
  <arg name="manager"             default="realsense2_camera_manager"/>
  <arg name="output"              default="screen"/>

  <arg name="fisheye_width"       default="-1"/>
  <arg name="fisheye_height"      default="-1"/>
  <arg name="enable_fisheye"      default="false"/>

  <arg name="depth_width"         default="848"/>
  <arg name="depth_height"        default="480"/>
  <arg name="enable_depth"        default="true"/>

  <arg name="confidence_width"    default="-1"/>
  <arg name="confidence_height"   default="-1"/>
  <arg name="enable_confidence"   default="true"/>
  <arg name="confidence_fps"      default="-1"/>

  <arg name="infra_width"         default="1280"/>
  <arg name="infra_height"        default="720"/>
  <arg name="enable_infra"        default="false"/>
  <arg name="enable_infra1"       default="false"/>
  <arg name="enable_infra2"       default="false"/>
  <arg name="infra_rgb"           default="false"/>

  <arg name="color_width"         default="-1"/>
  <arg name="color_height"        default="-1"/>
  <arg name="enable_color"        default="true"/>

  <arg name="fisheye_fps"         default="-1"/>
  <arg name="depth_fps"           default="30"/>
  <arg name="infra_fps"           default="30"/>
  <arg name="color_fps"           default="-1"/>
  <arg name="gyro_fps"            default="-1"/>
  <arg name="accel_fps"           default="-1"/>
  <arg name="enable_gyro"         default="false"/>
  <arg name="enable_accel"        default="false"/>

  <arg name="enable_pointcloud"         default="true"/>
  <arg name="pointcloud_texture_stream" default="RS2_STREAM_ANY"/>
  <arg name="pointcloud_texture_index"  default="0"/>
  <arg name="allow_no_texture_points"   default="true"/>
  <arg name="ordered_pc"                default="true"/>

  <arg name="enable_sync"               default="true"/>
  <arg name="align_depth"               default="true"/>

  <arg name="publish_tf"                default="true"/>
  <arg name="tf_publish_rate"           default="0"/>

  <arg name="filters"                   default="spatial,temporal,pointcloud"/>
  <arg name="clip_distance"             default="-2"/>
  <arg name="linear_accel_cov"          default="0.01"/>
  <arg name="initial_reset"             default="false"/>
  <arg name="unite_imu_method"          default=""/>
  <arg name="topic_odom_in"             default="odom_in"/>
  <arg name="calib_odom_file"           default=""/>
  <arg name="publish_odom_tf"           default="true"/>

  <arg name="stereo_module/exposure/1"  default="7500"/>
  <arg name="stereo_module/gain/1"      default="16"/>
  <arg name="stereo_module/exposure/2"  default="1"/>
  <arg name="stereo_module/gain/2"      default="16"/>
  
  
  <group ns="$(arg camera)">
    <include file="$(find realsense2_camera)/launch/includes/nodelet.launch.xml">
      <arg name="tf_prefix"                value="$(arg tf_prefix)"/>
      <arg name="external_manager"         value="$(arg external_manager)"/>
      <arg name="manager"                  value="$(arg manager)"/>
      <arg name="output"                   value="$(arg output)"/>
      <arg name="serial_no"                value="$(arg serial_no)"/>
      <arg name="usb_port_id"              value="$(arg usb_port_id)"/>
      <arg name="device_type"              value="$(arg device_type)"/>
      <arg name="json_file_path"           value="$(arg json_file_path)"/>

      <arg name="enable_pointcloud"        value="$(arg enable_pointcloud)"/>
      <arg name="pointcloud_texture_stream" value="$(arg pointcloud_texture_stream)"/>
      <arg name="pointcloud_texture_index"  value="$(arg pointcloud_texture_index)"/>
      <arg name="enable_sync"              value="$(arg enable_sync)"/>
      <arg name="align_depth"              value="$(arg align_depth)"/>

      <arg name="fisheye_width"            value="$(arg fisheye_width)"/>
      <arg name="fisheye_height"           value="$(arg fisheye_height)"/>
      <arg name="enable_fisheye"           value="$(arg enable_fisheye)"/>

      <arg name="depth_width"              value="$(arg depth_width)"/>
      <arg name="depth_height"             value="$(arg depth_height)"/>
      <arg name="enable_depth"             value="$(arg enable_depth)"/>

      <arg name="confidence_width"         value="$(arg confidence_width)"/>
      <arg name="confidence_height"        value="$(arg confidence_height)"/>
      <arg name="enable_confidence"        value="$(arg enable_confidence)"/>
      <arg name="confidence_fps"           value="$(arg confidence_fps)"/>

      <arg name="color_width"              value="$(arg color_width)"/>
      <arg name="color_height"             value="$(arg color_height)"/>
      <arg name="enable_color"             value="$(arg enable_color)"/>

      <arg name="infra_width"              value="$(arg infra_width)"/>
      <arg name="infra_height"             value="$(arg infra_height)"/>
      <arg name="enable_infra"             value="$(arg enable_infra)"/>
      <arg name="enable_infra1"            value="$(arg enable_infra1)"/>
      <arg name="enable_infra2"            value="$(arg enable_infra2)"/>
      <arg name="infra_rgb"                value="$(arg infra_rgb)"/>

      <arg name="fisheye_fps"              value="$(arg fisheye_fps)"/>
      <arg name="depth_fps"                value="$(arg depth_fps)"/>
      <arg name="infra_fps"                value="$(arg infra_fps)"/>
      <arg name="color_fps"                value="$(arg color_fps)"/>
      <arg name="gyro_fps"                 value="$(arg gyro_fps)"/>
      <arg name="accel_fps"                value="$(arg accel_fps)"/>
      <arg name="enable_gyro"              value="$(arg enable_gyro)"/>
      <arg name="enable_accel"             value="$(arg enable_accel)"/>

      <arg name="publish_tf"               value="$(arg publish_tf)"/>
      <arg name="tf_publish_rate"          value="$(arg tf_publish_rate)"/>

      <arg name="filters"                  value="$(arg filters)"/>
      <arg name="clip_distance"            value="$(arg clip_distance)"/>
      <arg name="linear_accel_cov"         value="$(arg linear_accel_cov)"/>
      <arg name="initial_reset"            value="$(arg initial_reset)"/>
      <arg name="unite_imu_method"         value="$(arg unite_imu_method)"/>
      <arg name="topic_odom_in"            value="$(arg topic_odom_in)"/>
      <arg name="calib_odom_file"          value="$(arg calib_odom_file)"/>
      <arg name="publish_odom_tf"          value="$(arg publish_odom_tf)"/>
      <arg name="stereo_module/exposure/1" value="$(arg stereo_module/exposure/1)"/>
      <arg name="stereo_module/gain/1"     value="$(arg stereo_module/gain/1)"/>
      <arg name="stereo_module/exposure/2" value="$(arg stereo_module/exposure/2)"/>
      <arg name="stereo_module/gain/2"     value="$(arg stereo_module/gain/2)"/>

      <arg name="allow_no_texture_points"  value="$(arg allow_no_texture_points)"/>
      <arg name="ordered_pc"               value="$(arg ordered_pc)"/>
      
    </include>
    <rosparam>  
      /d455/rgb_camera/auto_exposure_priority : False
    </rosparam>
  </group>

</launch>
```

**Comment by MartyG-RealSense** [comment]
Hi @mszuyx   Apologies for the late response.  Do you still require assistance with your question, please?  Thanks!

**Comment by mszuyx** [comment]
Yes, can you simply make some comments on the following topics:

"using uncolored pointcloud will consume more CPU"

"how much would the "ordered_pc" option impact the processing speed?"

Thank you !!

**Comment by MartyG-RealSense** [comment]
1.  I could not find any references that backed up the claim in the provided link that using RS2_STREAM_ANY would result in a doubling of the number of point cloud points and hence an increase in CPU usage.

2.  I do not have information about how the **ordered_pc** setting in the RealSense ROS wrapper impacts processing speed, so I will refer that to @doronhi

**Comment by doronhi** [comment]
Based on [the D435 spec](https://www.intelrealsense.com/wp-content/uploads/2020/06/Intel-RealSense-D400-Series-Datasheet-June-2020.pdf) the Depth FOV HD is 87x58 degrees (page 55), and the Color FOV is 69x42 degrees. The depth image covers an area approximately 1.74 times larger than the color image. 
The pointcloud is built around the depth image. When we use the *RS2_STREAM_COLOR* flag, we force the pointcloud to consist of only 1/1.74 of the points we have in the depth image.

Pointing a D435 camera such that the pointcloud seems to be pretty filled, I see the followings:
with *RS2_STREAM_COLOR*: around 196018 points, each takes 20 bytes -> message size: ~3920360
with *RS2_STREAM_ANY*: around 386548 points of 16 bytes -> message size: ~6184768
The number of points we have when no color is needed is about twice the number when color is not. 
The size rate, in this case, is 6184768 / 3920360 = 1.57, meaning that without color we get a message size around 1.5 times larger than with colors. In other scenarios, the numbers will vary but doubling the number of points sometimes seems possible.

My measurements show about twice the CPU usage when using texture. Considering the fact that the number of points created by librealsense2 and need to be scanned through is the same, color or not, **I don't see why using RS2_STREAM_ANY should result in an increase in CPU besides what it takes to pack and send larger messages**.

When using **ordered_pc** the size of the message is fixed. In the previous example, I used a depth resolution of 848x480 yielding an image of 407040 points. Although many of them have invalid values that is still the number of points in the pointcloud2 message. In other scenarios, where we are not looking at an almost completely filled image, the ordered pointcloud will still be of size 407040 points while the unordered pointcloud will contain much less. 

**The same amount of points are being scanned through, regardless of the pointcloud being ordered or not, so the processing time and CPU usage are about the same.** Packing, sending, and receiving larger messages naturally takes more time and BW.

**Comment by mszuyx** [comment]
@doronhi Thank you for your detailed & professional answer! :  ) I think other developers will benefit a lot from reading this post!

**Comment by doronhi** [comment]
Thanks :)

**Comment by MartyG-RealSense** [comment]
Hi @JeremieBourque1  Do you require further assistance with this case, please?  Thanks!

**Comment by JeremieBourque1** [comment]
Thank you!
