### ISSUE TITLE
Intel RealSense D455 not publishing infrared images

### ISSUE THREAD

**Issue by federicochiesa** [realsenseai/realsense-ros#1845]
I have an Intel RealSense D455 and it's not publishing on the ```infra1``` and ```infra2``` topics, so I can't get the infrared cameras' video feed from ROS, while I can see it perfectly through ```realense-viewer```.
How can I solve this?

**Comment by MartyG-RealSense** [comment]
Hi @federicochiesa  Could you try adding the instructions below to the end of your roslaunch instruction please to enable and publish the infrared topics:

**enable_infra1:=true enable_infra2:=true**

For example:

**roslaunch realsense2_camera rs_camera.launch enable_infra1:=true enable_infra2:=true**

**Comment by MartyG-RealSense** [comment]
Hi @federicochiesa  Do you require further assistance with this case, please?  Thanks!

**Comment by federicochiesa** [comment]
Thank you, that did it!

**Comment by MartyG-RealSense** [comment]
Great news @federicochiesa - thanks for the update!
