### ISSUE TITLE
Filtering Edge Noise Points

### ISSUE THREAD

**Issue by senoa95** [realsenseai/realsense-ros#1855]
Hello, 
I am using an L515 with ROS Melodic. I am having issues filtering out noise points that occur at the edge of objects. The noise levels in realsense-viewer is a lot less compared to what I see in rviz. Please see the comparison in the pictures. I have posted the side images to demonstrate. I am using the ROS default launch params to get the camera publishing in ROS.
![image](https://user-images.githubusercontent.com/31670663/117515831-68382600-af65-11eb-86fb-a40aa0d1472f.png)
realsense-viewer
![image](https://user-images.githubusercontent.com/31670663/117515885-8c940280-af65-11eb-9358-757eb4fe5ad1.png)
rviz - axis is the camera pose. the noise points are the scattered ones on the side of the object. Here is a better view
![image](https://user-images.githubusercontent.com/31670663/117515953-b816ed00-af65-11eb-9941-d9ce12dcbd38.png)

**Comment by RealSenseSupport** [comment]
In the RealSense Viewer there are some performance settings that may be turned on that smooths out the processing.  You can have a look in the settings menu similiar to the image here

![Screenshot 2021-05-26 154458](https://user-images.githubusercontent.com/63821679/119740907-92308a00-be39-11eb-808d-517ae5793fc7.png)

The GLSL settings could be turned on in your configuration setup.  See if you turn off these settings if there is any effect on the image generated.

**Comment by senoa95** [comment]
I did some checking and it appears that the noise was induced by config changes that I had in the ros node launch file. I tried the default launch file and the results are much better. Thank you everyone for checking and the responses.
 
Closing this issue.
