### ISSUE TITLE
Question: Ros2 vs Foxy branches

### ISSUE THREAD

**Issue by charlielito** [realsenseai/realsense-ros#1862]
What's the difference between foxy and ros2 branches? Can ros2 branch be used with ros2 foxy distribution? I ask because recent PRs only are merged into ros2 branch

**Comment by MartyG-RealSense** [comment]
Hi @charlielito  Up until ROS2 wrapper 3.1.5 there were two separate RealSense ROS2 wrappers for Eloquent and Foxy.  From wrapper version 3.1.5 onwards the individual wrappers were combined into a single wrapper that supports Eloquent and Foxy, and additionally Dashing too.  So yes, you can use Foxy with the **ros2** branch.

https://github.com/IntelRealSense/realsense-ros/tree/ros2

**Comment by charlielito** [comment]
Nice! Thank you!!
