### ISSUE TITLE
do we have something similar to rs2_deproject_pixel_to_point in ROS

### ISSUE THREAD

**Issue by yuan0623** [realsenseai/realsense-ros#1865]
Hi,

I'm trying to obtain the 3D coordinates of a certain pixel using ROS topic `/camera/aligned_depth_to_color/image_raw`. 
I have the pixel coordinate (x_p, y_p) and the distance value of (x_p, y_p) obtained through `/camera/aligned_depth_to_color/image_raw`. My question is: Do we have anything similar to `rs2_deproject_pixel_to_point` in ROS wrapper so I can directly obtain the 3D coordinate? Which topic should I use to obtain `intrinsics`? Many thanks!

Best
Yuan

**Comment by MartyG-RealSense** [comment]
Hi @yuan0623   I hope that the links below will be helpful to you in developing a solution for obtaining 3D depth coordinates using **camera/aligned_depth_to_color/image_raw** and accessing intrinsics.

https://github.com/IntelRealSense/realsense-ros/issues/714
https://github.com/IntelRealSense/realsense-ros/issues/709

**Comment by ravijo** [comment]
@yuan0623 

I think you have already found the answer based on the given references above. However, if you are still looking, please read the following.

I made a ROS package to do the same. Please check it out [ros_openpose](https://github.com/ravijo/ros_openpose).

I think what you are looking for is available inside the [ros_openpose](https://github.com/ravijo/ros_openpose) repository [here](https://github.com/ravijo/ros_openpose/blob/1c3dd67584e7ff4842d2021b76ae245b77615812/include/ros_openpose/cameraReader.hpp#L109-L145).

Cheers!

**Comment by MartyG-RealSense** [comment]
Thanks very much @ravijo for your assistance to @yuan0623   :)

**Comment by ravijo** [comment]
@MartyG-RealSense: Thanks for the kind words. It's my pleasure to help others.

**Comment by yuan0623** [comment]
> @yuan0623
> 
> I think you have already found the answer based on the given references above. However, if you are still looking, please read the following.
> 
> I made a ROS package to do the same. Please check it out [ros_openpose](https://github.com/ravijo/ros_openpose).
> 
> I think what you are looking for is available inside the [ros_openpose](https://github.com/ravijo/ros_openpose) repository [here](https://github.com/ravijo/ros_openpose/blob/1c3dd67584e7ff4842d2021b76ae245b77615812/include/ros_openpose/cameraReader.hpp#L109-L145).
> 
> Cheers!

Hi Ravijo,

Thanks for your help, I will try to use your package.

Best
Yuan
