### ISSUE TITLE
No cuda capable device is detected 

### ISSUE THREAD

**Issue by sivaeinfo** [realsenseai/realsense-ros#1874]
Actually i have tried to use the dope package in https://github.com/yehengchen/DOPE-ROS-D435

I have installed require packages and dependencies.
In this, they have given two command.
1.roslaunch realsense2_camera rs_rgbd.launch
2. roslaunch dope dope.launch

The second command gives following error
![IMG-20210518-WA0020.jpeg](https://user-images.githubusercontent.com/72197828/118624422-25612400-b797-11eb-9980-997264032850.jpeg)![IMG-20210518-WA0020.jpeg](https://user-images.githubusercontent.com/72197828/118624453-2d20c880-b797-11eb-99c6-b52360932907.jpeg)

Please help me in detail to sort out this issues.
I am using NVDIA 430.108 driver with autoinstall command. Have installed cuda and cuda toolkit as well.

**Comment by MartyG-RealSense** [comment]
Hi @sivaeinfo   May I first confirm that you have a computer or computing device that is equipped with an Nvidia graphics GPU processor component.  This could include an **Nvida Jetson** board, or a computer that has an Nvidia graphics chip or plug-in video card.  CUDA requires that the computer has an Nvidia GPU component, as it does not support non-Nvidia GPUs.

**Comment by sivaeinfo** [comment]
I am having computer system with Nvidia GT218 GeForce 210. I have uninstalled nividia driver 430 and reinstalling using the command (ref: https://askubuntu.com/questions/1105090/cant-change-to-nvidia-proprietary-driver-ubuntu-18-04)

sudo ubuntu-drivers autoinstall

It shows another error 

![Screenshot from 2021-05-18 18-57-00](https://user-images.githubusercontent.com/72197828/118660088-7f033600-b80b-11eb-8164-61191cb29b16.png)
![Screenshot from 2021-05-18 18-57-06](https://user-images.githubusercontent.com/72197828/118660099-832f5380-b80b-11eb-955c-2cec04a22a72.png)

**Comment by MartyG-RealSense** [comment]
This is technically an Ubuntu / Nvidia problem rather than a RealSense one.

However, if driver autoinstall failed and the driver that the 210 uses is **430** then you could try installing a specific driver with the command below:

**sudo apt install nvidia-driver-430**

**Comment by sivaeinfo** [comment]
I have install driver using
sudo apt install nvidia-driver-430
I want to install cuda 9.2 or more to match my pytorch.
I am not able to find proper way to install cuda 9.2 or more
https://medium.com/@aspiring1/installing-cuda-toolkit-10-0-and-cudnn-for-deep-learning-with-tensorflow-gpu-on-ubuntu-18-04-lts-f7e968b24c98

I think nvidia 430 GeForce 210 is not cuda enabled.
Do i need to use some other graphics card?
Does jetson nano support for implementing Dope packages?

**Comment by MartyG-RealSense** [comment]
GeForce 210 is listed in specifications as having CUDA support, with 16 CUDA cores.  The official Nvidia specification page for the 210 is at the link below.

https://video-nvidia.com/en-us/series_200/nvidia-geforce-210.html

The **340** driver supports GeForce 200 Series, including 210.

https://www.nvidia.com/Download/driverResults.aspx/81761/en-us

![image](https://user-images.githubusercontent.com/41145062/118808874-dc49c680-b8a1-11eb-82a8-de5b172b22bc.png)

I researched the question of 210 supporting modern CUDA versions.  The popular opinion was that 210 was too weak and that a more modern Nvidia graphics card should be used.  This may not be practical though if your computer is old too.

Using a Jetson Nano may be a solution though, as it would have a more modern Nvidia graphics chip (its GPU has 128 cores).

https://developer.nvidia.com/embedded/jetson-nano-developer-kit

A person who wanted to use CUDA 9 on Nano was told by an Nvidia forum moderator though that Nano only supported CUDA 10.

https://forums.developer.nvidia.com/t/jetson-nano-install-different-version-of-cuda/72475

**Comment by MartyG-RealSense** [comment]
Hi @sivaeinfo  Do you require further assistance with this case, please?  Thanks!

**Comment by sivaeinfo** [comment]
Hi @MartyG-RealSense I will ask you query Once I updated my hardware (GPU or JETSON nano)

**Comment by MartyG-RealSense** [comment]
Okay, thanks very much @sivaeinfo for the update - good luck!
