### ISSUE TITLE
NX+D455，Motion Module probelm

### ISSUE THREAD

**Issue by liangchen97** [realsenseai/realsense-ros#1877]
Running commands with d455 on Ubuntu 18.04

roslaunch realsense2_ camera rs_ camera.launch

Error returned

Hardware Not ification:Motion Module Failure, 1.62133e + 12, error, hardware error or hardware not ification:Motion Module force pause,1.6214e+12,Error,Hardware Error

IMU related topics are missing in topic list

**Comment by liangchen97** [comment]
Here are some details
/nvidia@nvidia-desktop:~$ roslaunch realsense2_camera rs_camera.launch
... logging to /home/nvidia/.ros/log/761997da-b7b3-11eb-9e72-d8c0a650ee07/roslaunch-nvidia-desktop-17436.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://nvidia-desktop:41941/

SUMMARY
========

PARAMETERS
 * /camera/realsense2_camera/accel_fps: -1
 * /camera/realsense2_camera/accel_frame_id: camera_accel_frame
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: True
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/allow_no_texture_points: False
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/calib_odom_file: 
 * /camera/realsense2_camera/clip_distance: -2.0
 * /camera/realsense2_camera/color_fps: -1
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: -1
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: -1
 * /camera/realsense2_camera/confidence_fps: -1
 * /camera/realsense2_camera/confidence_height: -1
 * /camera/realsense2_camera/confidence_width: -1
 * /camera/realsense2_camera/depth_fps: -1
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: -1
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: -1
 * /camera/realsense2_camera/device_type: 
 * /camera/realsense2_camera/enable_accel: False
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_confidence: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye1: False
 * /camera/realsense2_camera/enable_fisheye2: False
 * /camera/realsense2_camera/enable_fisheye: False
 * /camera/realsense2_camera/enable_gyro: False
 * /camera/realsense2_camera/enable_infra1: False
 * /camera/realsense2_camera/enable_infra2: False
 * /camera/realsense2_camera/enable_infra: False
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_pose: False
 * /camera/realsense2_camera/enable_sync: True
 * /camera/realsense2_camera/filters: 
 * /camera/realsense2_camera/fisheye1_frame_id: camera_fisheye1_f...
 * /camera/realsense2_camera/fisheye1_optical_frame_id: camera_fisheye1_o...
 * /camera/realsense2_camera/fisheye2_frame_id: camera_fisheye2_f...
 * /camera/realsense2_camera/fisheye2_optical_frame_id: camera_fisheye2_o...
 * /camera/realsense2_camera/fisheye_fps: -1
 * /camera/realsense2_camera/fisheye_frame_id: camera_fisheye_frame
 * /camera/realsense2_camera/fisheye_height: -1
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: -1
 * /camera/realsense2_camera/gyro_fps: -1
 * /camera/realsense2_camera/gyro_frame_id: camera_gyro_frame
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/imu_optical_frame_id: camera_imu_optica...
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra_fps: 30
 * /camera/realsense2_camera/infra_height: 480
 * /camera/realsense2_camera/infra_rgb: False
 * /camera/realsense2_camera/infra_width: 848
 * /camera/realsense2_camera/initial_reset: False
 * /camera/realsense2_camera/json_file_path: 
 * /camera/realsense2_camera/linear_accel_cov: 0.01
 * /camera/realsense2_camera/odom_frame_id: camera_odom_frame
 * /camera/realsense2_camera/ordered_pc: False
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/pose_frame_id: camera_pose_frame
 * /camera/realsense2_camera/pose_optical_frame_id: camera_pose_optic...
 * /camera/realsense2_camera/publish_odom_tf: True
 * /camera/realsense2_camera/publish_tf: True
 * /camera/realsense2_camera/rosbag_filename: 
 * /camera/realsense2_camera/serial_no: 
 * /camera/realsense2_camera/stereo_module/exposure/1: 7500
 * /camera/realsense2_camera/stereo_module/exposure/2: 1
 * /camera/realsense2_camera/stereo_module/gain/1: 16
 * /camera/realsense2_camera/stereo_module/gain/2: 16
 * /camera/realsense2_camera/tf_publish_rate: 0.0
 * /camera/realsense2_camera/topic_odom_in: odom_in
 * /camera/realsense2_camera/unite_imu_method: 
 * /camera/realsense2_camera/usb_port_id: 
 * /rosdistro: melodic
 * /rosversion: 1.14.10

NODES
  /camera/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)

auto-starting new master
process[master]: started with pid [17491]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 761997da-b7b3-11eb-9e72-d8c0a650ee07
process[rosout-1]: started with pid [17585]
started core service [/rosout]
process[camera/realsense2_camera_manager-2]: started with pid [17603]
process[camera/realsense2_camera-3]: started with pid [17610]
[ INFO] [1621326701.498773778]: Initializing nodelet with 6 worker threads.
[ INFO] [1621326701.962204293]: RealSense ROS v2.3.0
[ INFO] [1621326701.962345284]: Built with LibRealSense v2.45.0
[ INFO] [1621326701.962424068]: Running with LibRealSense v2.45.0
[ INFO] [1621326702.026687339]:  
[ INFO] [1621326702.228950346]: Device with serial number 046122251287 was found.

[ INFO] [1621326702.229108553]: Device with physical ID 2-3.2-3 was found.
[ INFO] [1621326702.229178569]: Device with name Intel RealSense D455 was found.
[ INFO] [1621326702.231148290]: Device with port number 2-3.2 was found.
[ INFO] [1621326702.231272386]: Device USB type: 3.2
[ INFO] [1621326702.238313195]: getParameters...
[ INFO] [1621326702.400416559]: setupDevice...
[ INFO] [1621326702.400571247]: JSON file is not provided
[ INFO] [1621326702.400734062]: ROS Node Namespace: camera
[ INFO] [1621326702.400831246]: Device Name: Intel RealSense D455
[ INFO] [1621326702.400978125]: Device Serial No: 046122251287
[ INFO] [1621326702.401086829]: Device physical port: 2-3.2-3
[ INFO] [1621326702.401220557]: Device FW version: 05.12.06.00
[ INFO] [1621326702.401343692]: Device Product ID: 0x0B5C
[ INFO] [1621326702.401418956]: Enable PointCloud: Off
[ INFO] [1621326702.401495660]: Align Depth: On
[ INFO] [1621326702.401562988]: Sync Mode: On
[ INFO] [1621326702.401780715]: Device Sensors: 
[ INFO] [1621326702.443505472]: Stereo Module was found.
[ INFO] [1621326702.492008703]: RGB Camera was found.
[ INFO] [1621326702.493119771]: Motion Module was found.
[ INFO] [1621326702.493337562]: (Confidence, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1621326702.494883541]: num_filters: 1
[ INFO] [1621326702.495029813]: Setting Dynamic reconfig parameters.
 18/05 16:31:42,833 WARNING [547734151552] (messenger-libusb.cpp:42) control_transfer returned error, index: 300, error: No data available, number: 3d
[ INFO] [1621326703.077501161]: Done Setting Dynamic reconfig parameters.
[ INFO] [1621326703.079696034]: depth stream is enabled - width: 848, height: 480, fps: 30, Format: Z16
[ INFO] [1621326703.083616117]: color stream is enabled - width: 1280, height: 720, fps: 30, Format: RGB8
[ INFO] [1621326703.087475209]: setupPublishers...
[ INFO] [1621326703.104432658]: Expected frequency for depth = 30.00000
[ WARN] [1621326704.091268727]: Hardware Notification:Motion Module failure,1.62133e+12,Error,Hardware Error
[ INFO] [1621326704.153039604]: Expected frequency for color = 30.00000
[ INFO] [1621326704.217991878]: Expected frequency for aligned_depth_to_color = 30.00000
[ INFO] [1621326704.282879449]: setupStreams...
[ INFO] [1621326704.309444165]: insert Depth to Stereo Module
[ INFO] [1621326704.309615269]: insert Color to RGB Camera   o998
[ INFO] [1621326704.444131963]: RealSense Node Is Up!
[ WARN] [1621326704.547723635]: 
 18/05 16:31:44,549 WARNING [547734151552] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 18/05 16:31:44,599 WARNING [547734151552] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 18/05 16:31:44,651 WARNING [547734151552] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 18/05 16:31:44,802 WARNING [547734151552] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 18/05 16:31:44,852 WARNING [547734151552] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 18/05 16:31:45,004 WARNING [547734151552] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 18/05 16:31:45,054 WARNING [547734151552] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 18/05 16:31:45,206 WARNING [547734151552] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 18/05 16:31:45,682 ERROR [547118023040] (uvc-streamer.cpp:106) uvc streamer watchdog triggered on endpoint: 132
 18/05 16:31:46,048 WARNING [547734151552] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 18/05 16:31:46,099 WARNING [547734151552] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 18/05 16:31:46,252 WARNING [547734151552] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 18/05 16:31:46,303 WARNING [547734151552] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 18/05 16:31:52,358 WARNING [547734151552] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 18/05 16:31:55,411 WARNING [547734151552] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 18/05 16:32:20,482 WARNING [547734151552] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 18/05 16:32:24,536 WARNING [547734151552] (messenger-libusb.cpp:42) control_transfer returned error, index: 300, error: Resource temporarily unavailable, number: b
 18/05 16:32:37,600 WARNING [547734151552] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 18/05 16:32:54,665 WARNING [547734151552] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 18/05 16:32:59,720 WARNING [547734151552] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 18/05 16:33:05,777 WARNING [547734151552] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11

**Comment by liangchen97** [comment]
vidia@nvidia-desktop:~$ roslaunch realsense2_camera rs_camera.launch
... logging to /home/nvidia/.ros/log/b96ea40c-b863-11eb-8f2f-d8c0a650ee07/roslaunch-nvidia-desktop-1610.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://nvidia-desktop:42523/

SUMMARY
========

PARAMETERS
 * /camera/realsense2_camera/accel_fps: -1
 * /camera/realsense2_camera/accel_frame_id: camera_accel_frame
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: True
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/allow_no_texture_points: False
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/calib_odom_file: 
 * /camera/realsense2_camera/clip_distance: -2.0
 * /camera/realsense2_camera/color_fps: -1
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: -1
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: -1
 * /camera/realsense2_camera/confidence_fps: -1
 * /camera/realsense2_camera/confidence_height: -1
 * /camera/realsense2_camera/confidence_width: -1
 * /camera/realsense2_camera/depth_fps: -1
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: -1
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: -1
 * /camera/realsense2_camera/device_type: 
 * /camera/realsense2_camera/enable_accel: False
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_confidence: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye1: False
 * /camera/realsense2_camera/enable_fisheye2: False
 * /camera/realsense2_camera/enable_fisheye: False
 * /camera/realsense2_camera/enable_gyro: False
 * /camera/realsense2_camera/enable_infra1: False
 * /camera/realsense2_camera/enable_infra2: False
 * /camera/realsense2_camera/enable_infra: False
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_pose: False
 * /camera/realsense2_camera/enable_sync: True
 * /camera/realsense2_camera/filters: 
 * /camera/realsense2_camera/fisheye1_frame_id: camera_fisheye1_f...
 * /camera/realsense2_camera/fisheye1_optical_frame_id: camera_fisheye1_o...
 * /camera/realsense2_camera/fisheye2_frame_id: camera_fisheye2_f...
 * /camera/realsense2_camera/fisheye2_optical_frame_id: camera_fisheye2_o...
 * /camera/realsense2_camera/fisheye_fps: -1
 * /camera/realsense2_camera/fisheye_frame_id: camera_fisheye_frame
 * /camera/realsense2_camera/fisheye_height: -1
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: -1
 * /camera/realsense2_camera/gyro_fps: -1
 * /camera/realsense2_camera/gyro_frame_id: camera_gyro_frame
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/imu_optical_frame_id: camera_imu_optica...
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra_fps: 30
 * /camera/realsense2_camera/infra_height: 480
 * /camera/realsense2_camera/infra_rgb: False
 * /camera/realsense2_camera/infra_width: 848
 * /camera/realsense2_camera/initial_reset: False
 * /camera/realsense2_camera/json_file_path: 
 * /camera/realsense2_camera/linear_accel_cov: 0.01
 * /camera/realsense2_camera/odom_frame_id: camera_odom_frame
 * /camera/realsense2_camera/ordered_pc: False
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/pose_frame_id: camera_pose_frame
 * /camera/realsense2_camera/pose_optical_frame_id: camera_pose_optic...
 * /camera/realsense2_camera/publish_odom_tf: True
 * /camera/realsense2_camera/publish_tf: True
 * /camera/realsense2_camera/rosbag_filename: 
 * /camera/realsense2_camera/serial_no: 
 * /camera/realsense2_camera/stereo_module/exposure/1: 7500
 * /camera/realsense2_camera/stereo_module/exposure/2: 1
 * /camera/realsense2_camera/stereo_module/gain/1: 16
 * /camera/realsense2_camera/stereo_module/gain/2: 16
 * /camera/realsense2_camera/tf_publish_rate: 0.0
 * /camera/realsense2_camera/topic_odom_in: odom_in
 * /camera/realsense2_camera/unite_imu_method: 
 * /camera/realsense2_camera/usb_port_id: 
 * /rosdistro: melodic
 * /rosversion: 1.14.10

NODES
  /camera/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)

auto-starting new master
process[master]: started with pid [1658]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to b96ea40c-b863-11eb-8f2f-d8c0a650ee07
process[rosout-1]: started with pid [1679]
started core service [/rosout]
process[camera/realsense2_camera_manager-2]: started with pid [1684]
process[camera/realsense2_camera-3]: started with pid [1687]
[ INFO] [1621402405.966287128]: Initializing nodelet with 6 worker threads.
[ INFO] [1621402406.276751956]: RealSense ROS v2.3.0
[ INFO] [1621402406.276889238]: Built with LibRealSense v2.45.0
[ INFO] [1621402406.276976599]: Running with LibRealSense v2.45.0
[ INFO] [1621402406.332299481]:  
[ INFO] [1621402406.640984542]: Device with serial number 046122251287 was found.

[ INFO] [1621402406.641161472]: Device with physical ID 2-3.2-3 was found.
[ INFO] [1621402406.641272674]: Device with name Intel RealSense D455 was found.
[ INFO] [1621402406.643808482]: Device with port number 2-3.2 was found.
[ INFO] [1621402406.643912707]: Device USB type: 3.2
[ INFO] [1621402406.650243380]: getParameters...
[ INFO] [1621402406.800854935]: setupDevice...
[ INFO] [1621402406.801024409]: JSON file is not provided
[ INFO] [1621402406.801147899]: ROS Node Namespace: camera
[ INFO] [1621402406.801267164]: Device Name: Intel RealSense D455
[ INFO] [1621402406.801356798]: Device Serial No: 046122251287
[ INFO] [1621402406.801436895]: Device physical port: 2-3.2-3
[ INFO] [1621402406.801513408]: Device FW version: 05.12.06.00
[ INFO] [1621402406.801832420]: Device Product ID: 0x0B5C
[ INFO] [1621402406.801994118]: Enable PointCloud: Off
[ INFO] [1621402406.802118631]: Align Depth: On
[ INFO] [1621402406.802184360]: Sync Mode: On
[ INFO] [1621402406.802375019]: Device Sensors: 
[ INFO] [1621402406.840151853]: Stereo Module was found.
[ INFO] [1621402406.873706553]: RGB Camera was found.
[ INFO] [1621402406.874571012]: Motion Module was found.
[ INFO] [1621402406.874811591]: (Confidence, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1621402406.876364859]: num_filters: 1
[ INFO] [1621402406.876493981]: Setting Dynamic reconfig parameters.
[ INFO] [1621402407.404387056]: Done Setting Dynamic reconfig parameters.
[ INFO] [1621402407.406507147]: depth stream is enabled - width: 848, height: 480, fps: 30, Format: Z16
[ INFO] [1621402407.408383715]: color stream is enabled - width: 1280, height: 720, fps: 30, Format: RGB8
[ INFO] [1621402407.412266485]: setupPublishers...
[ INFO] [1621402407.429280430]: Expected frequency for depth = 30.00000
[ WARN] [1621402408.416962638]: Hardware Notification:Motion Module force pause,1.6214e+12,Error,Hardware Error
[ INFO] [1621402408.467724790]: Expected frequency for color = 30.00000
[ INFO] [1621402408.528112441]: Expected frequency for aligned_depth_to_color = 30.00000
[ INFO] [1621402408.593906368]: setupStreams...
[ INFO] [1621402408.618243895]: insert Depth to Stereo Module
[ INFO] [1621402408.618522651]: insert Color to RGB Camera
[ INFO] [1621402408.722678124]: SELECTED BASE:Depth, 0
[ INFO] [1621402408.751175096]: RealSense Node Is Up!
[ WARN] [1621402408.845624590]: 
 19/05 13:33:28,847 WARNING [547717366144] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 19/05 13:33:28,897 WARNING [547717366144] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 19/05 13:33:29,049 WARNING [547717366144] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 19/05 13:33:29,200 WARNING [547717366144] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 19/05 13:33:29,251 WARNING [547717366144] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 19/05 13:33:29,987 ERROR [547242471808] (uvc-streamer.cpp:106) uvc streamer watchdog triggered on endpoint: 132
 19/05 13:33:30,108 WARNING [547717366144] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 19/05 13:33:30,201 WARNING [547717366144] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 19/05 13:33:30,252 WARNING [547717366144] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61

**Comment by liangchen97** [comment]
my firmware version is 05.12.06.00. 
and min FW Version is 05.12.13.50.
My question is should I update the firmware? If so, to what version?

**Comment by MartyG-RealSense** [comment]
Hi @liangchen97  The IMU topics (gyro and accel) are disabled by default.  You can enable them by adding the commands below to the end of your roslaunch instruction:

**enable_gyro:=true enable_accel:=true**

For example:

**roslaunch realsense2_camera rs_camera.launch enable_gyro:=true enable_accel:=true**

**control_transfer returned** warnngs can be safely ignored if there are only a small number of them at launch, or they generate at a rate of 1 or 2 per minute after launch.  They are only a problem if they generate continuously, which can be an indication of a serious communication problem with the device.

If you are experiencing continuously generating **control_transfer returned** warnings, you could first try adding **initial_reset:=true** to your roslaunch instruction to perform a reset of the camera at launch:

**roslaunch realsense2_camera rs_camera.launch enable_gyro:=true enable_accel:=true initial_reset:=true**

**Comment by liangchen97** [comment]
The problem is solved! 

The warning disappears after "rs-fw-update"updates the firmware to 05.12.13.50

Then run roslaunch realsense 2_ camera rs_ camera.launch enable_ gyro:=true enable_ Accel: = true, I found IMU_ info

Thank you for your efficient and useful reply

**Comment by MartyG-RealSense** [comment]
You are very welcome @liangchen97 - that is excellent news.  Thanks for the update!

**Comment by MartyG-RealSense** [comment]
Case closed due to solution achieved and no further comments received.
