### ISSUE TITLE
ROS wrapper input parameters: D435i

### ISSUE THREAD

**Issue by Nick-Kou** [realsenseai/realsense-ros#1881]
I am trying to adjust the width and height parameters on launch in attempt to decrease the number of points published for each sensor_msgs/PointCloud2.msg.

Ubuntu 20.04
ROS noetic

nikolas@nikolas-SYS-5039A-I:~$ roslaunch realsense2_camera rs_camera.launch filters:=pointcloud depth_width:=320 infra_width:=320 color_width:=320 depth_height:=240 infra_height:=240 color_height:=240
... logging to /home/nikolas/.ros/log/f68d63f2-b8a2-11eb-b100-9fc7fe01b9f1/roslaunch-nikolas-SYS-5039A-I-58267.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://nikolas-SYS-5039A-I:41601/

SUMMARY
========

PARAMETERS
 * /camera/realsense2_camera/accel_fps: -1
 * /camera/realsense2_camera/accel_frame_id: camera_accel_frame
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: False
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/allow_no_texture_points: False
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/calib_odom_file: 
 * /camera/realsense2_camera/clip_distance: -2.0
 * /camera/realsense2_camera/color_fps: -1
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: 240
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: 320
 * /camera/realsense2_camera/confidence_fps: -1
 * /camera/realsense2_camera/confidence_height: -1
 * /camera/realsense2_camera/confidence_width: -1
 * /camera/realsense2_camera/depth_fps: -1
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: 240
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: 320
 * /camera/realsense2_camera/device_type: 
 * /camera/realsense2_camera/enable_accel: False
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_confidence: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye1: False
 * /camera/realsense2_camera/enable_fisheye2: False
 * /camera/realsense2_camera/enable_fisheye: False
 * /camera/realsense2_camera/enable_gyro: False
 * /camera/realsense2_camera/enable_infra1: False
 * /camera/realsense2_camera/enable_infra2: False
 * /camera/realsense2_camera/enable_infra: False
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_pose: False
 * /camera/realsense2_camera/enable_sync: False
 * /camera/realsense2_camera/filters: pointcloud
 * /camera/realsense2_camera/fisheye1_frame_id: camera_fisheye1_f...
 * /camera/realsense2_camera/fisheye1_optical_frame_id: camera_fisheye1_o...
 * /camera/realsense2_camera/fisheye2_frame_id: camera_fisheye2_f...
 * /camera/realsense2_camera/fisheye2_optical_frame_id: camera_fisheye2_o...
 * /camera/realsense2_camera/fisheye_fps: -1
 * /camera/realsense2_camera/fisheye_frame_id: camera_fisheye_frame
 * /camera/realsense2_camera/fisheye_height: -1
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: -1
 * /camera/realsense2_camera/gyro_fps: -1
 * /camera/realsense2_camera/gyro_frame_id: camera_gyro_frame
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/imu_optical_frame_id: camera_imu_optica...
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra_fps: 30
 * /camera/realsense2_camera/infra_height: 240
 * /camera/realsense2_camera/infra_rgb: False
 * /camera/realsense2_camera/infra_width: 320
 * /camera/realsense2_camera/initial_reset: False
 * /camera/realsense2_camera/json_file_path: 
 * /camera/realsense2_camera/linear_accel_cov: 0.01
 * /camera/realsense2_camera/odom_frame_id: camera_odom_frame
 * /camera/realsense2_camera/ordered_pc: False
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/pose_frame_id: camera_pose_frame
 * /camera/realsense2_camera/pose_optical_frame_id: camera_pose_optic...
 * /camera/realsense2_camera/publish_odom_tf: True
 * /camera/realsense2_camera/publish_tf: True
 * /camera/realsense2_camera/rosbag_filename: 
 * /camera/realsense2_camera/serial_no: 
 * /camera/realsense2_camera/stereo_module/exposure/1: 7500
 * /camera/realsense2_camera/stereo_module/exposure/2: 1
 * /camera/realsense2_camera/stereo_module/gain/1: 16
 * /camera/realsense2_camera/stereo_module/gain/2: 16
 * /camera/realsense2_camera/tf_publish_rate: 0.0
 * /camera/realsense2_camera/topic_odom_in: odom_in
 * /camera/realsense2_camera/unite_imu_method: 
 * /camera/realsense2_camera/usb_port_id: 
 * /rosdistro: noetic
 * /rosversion: 1.15.11

NODES
  /camera/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)

ROS_MASTER_URI=http://localhost:11311

process[camera/realsense2_camera_manager-1]: started with pid [58286]
process[camera/realsense2_camera-2]: started with pid [58287]
[ INFO] [1621429606.569570908]: Initializing nodelet with 20 worker threads.
[ INFO] [1621429606.643457110]: RealSense ROS v2.2.24
[ INFO] [1621429606.643488228]: Built with LibRealSense v2.44.0
[ INFO] [1621429606.643499025]: Running with LibRealSense v2.44.0
[ INFO] [1621429606.669514314]:  
[ INFO] [1621429606.929636268]: Device with serial number 102122071816 was found.

[ INFO] [1621429606.929696714]: Device with physical ID 2-3-6 was found.
[ INFO] [1621429606.929714768]: Device with name Intel RealSense D435I was found.
[ INFO] [1621429606.930297685]: Device with port number 2-3 was found.
[ INFO] [1621429606.930335623]: Device USB type: 3.2
[ INFO] [1621429606.933768825]: getParameters...
[ INFO] [1621429606.970564486]: setupDevice...
[ INFO] [1621429606.970610415]: JSON file is not provided
[ INFO] [1621429606.970629643]: ROS Node Namespace: camera
[ INFO] [1621429606.970658573]: Device Name: Intel RealSense D435I
[ INFO] [1621429606.970680880]: Device Serial No: 102122071816
[ INFO] [1621429606.970703166]: Device physical port: 2-3-6
[ INFO] [1621429606.970720490]: Device FW version: 05.12.13.50
[ INFO] [1621429606.970743671]: Device Product ID: 0x0B3A
[ INFO] [1621429606.970765423]: Enable PointCloud: On
[ INFO] [1621429606.970786513]: Align Depth: Off
[ INFO] [1621429606.970808312]: Sync Mode: On
[ INFO] [1621429606.970870932]: Device Sensors: 
[ INFO] [1621429606.991462380]: Stereo Module was found.
[ INFO] [1621429607.003019745]: RGB Camera was found.
[ INFO] [1621429607.003212090]: Motion Module was found.
[ INFO] [1621429607.003253199]: (Confidence, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1621429607.003275580]: Add Filter: pointcloud
[ INFO] [1621429607.003752059]: num_filters: 1
[ INFO] [1621429607.003778416]: Setting Dynamic reconfig parameters.
[ WARN] [1621429607.373638454]: Param '/camera/stereo_module/auto_exposure_limit' has value 0 that is not in range [1, 165000]. Removing this parameter from dynamic reconfigure options.
[ WARN] [1621429607.385426252]: Param '/camera/stereo_module/auto_gain_limit' has value 0 that is not in range [16, 248]. Removing this parameter from dynamic reconfigure options.
[ INFO] [1621429607.434412975]: Done Setting Dynamic reconfig parameters.
[ INFO] [1621429607.435393166]: depth stream is enabled - width: 848, height: 480, fps: 30, Format: Z16
[ INFO] [1621429607.437647181]: color stream is enabled - width: 1280, height: 720, fps: 30, Format: RGB8
[ INFO] [1621429607.437707715]: setupPublishers...
[ INFO] [1621429607.440721735]: Expected frequency for depth = 30.00000
[ INFO] [1621429607.475907680]: Expected frequency for color = 30.00000
[ INFO] [1621429607.494954042]: setupStreams...
[ INFO] [1621429607.505955725]: insert Depth to Stereo Module
[ INFO] [1621429607.506057258]: insert Color to RGB Camera
 19/05 09:06:47,559 WARNING [139929002690304] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
[ INFO] [1621429607.610282468]: SELECTED BASE:Depth, 0
[ INFO] [1621429607.621806457]: RealSense Node Is Up!
[ WARN] [1621429607.680588139]: 
 19/05 09:06:47,681 WARNING [139929002690304] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 19/05 09:06:47,731 WARNING [139929002690304] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 19/05 09:06:47,985 WARNING [139929002690304] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 19/05 09:06:48,035 WARNING [139929002690304] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61

**Comment by Nick-Kou** [comment]
It seems as after I insert the desired parameters for height and width the depth and color stream ignore the input parameters, as they are enabled with higher resolution:

[ INFO] [1621429607.435393166]: depth stream is enabled - width: 848, height: 480, fps: 30, Format: Z16
[ INFO] [1621429607.437647181]: color stream is enabled - width: 1280, height: 720, fps: 30, Format: RGB8

I was wondering if there is any parameter or setting I can configure to reduce the number of points in each sensor_msgs/PointCloud2.msg.

**Comment by MartyG-RealSense** [comment]
Hi @Nick-Kou   From ROS wrapper 2.2.22 onwards, three factors must be specified in the roslaunch instruction to define a custom configuration - width, height and **FPS**.

If three factors are not provided then the custom configuration is deemed invalid and the default stream settings of the particular camera model are applied.

The **infra** topics are also disabled by default since wrapper version 2.2.15, so should be enabled in the roslaunch with **enable_infra:=true**

According to the data sheet document for the 400 Series cameras, the resolution 320x240 is only supported on the **RGB** stream.  A minimum resolution supported by RGB, depth and infrared is **424x240**

![image](https://user-images.githubusercontent.com/41145062/118838094-50459800-b8bd-11eb-9dec-4bdd7822488c.png)

Overall, your roslaunch instruction may therefore look something like the one below:

**roslaunch realsense2_camera rs_camera.launch filters:=pointcloud enable_infra:=true depth_width:=424 infra_width:=424 color_width:=424 depth_height:=240 infra_height:=240 color_height:=240 depth_fps:=30.0 color_fps:=30.0 infra_fps:=30.0**

If you need to enable IMU topics (accel and gyro) at sone point then you should add the further commands below to the roslaunch instruction:

**enable_accel:=true enable_gyro:=true**

It is also worth noting that use of a **decimation** filter can reduce depth scene complexity, as highlighted in the RealSense ROS wrapper documentation extract below.

![image](https://user-images.githubusercontent.com/41145062/118839458-66078d00-b8be-11eb-8f80-27f85dc90716.png)

The link below may also be a useful reference for applying a decimation filter in RealSense ROS.

https://github.com/IntelRealSense/realsense-ros/issues/583

**Comment by Nick-Kou** [comment]
Thank you! After launching the following command:

roslaunch realsense2_camera rs_camera.launch filters:=pointcloud enable_infra:=true depth_width:=424 infra_width:=424 color_width:=424 depth_height:=240 infra_height:=240 color_height:=240 depth_fps:=30.0 color_fps:=30 infra_fps:=30

The number of points per message decreased significantly. Also, a temperature warning I was getting before, doesn't show anymore, so it is safe to say this configuration resolved those issues. However, I still receive this warning at least twice a minute: WARNING [140415365805824] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61

For example:

nikolas@nikolas-SYS-5039A-I:~$ roslaunch realsense2_camera rs_camera.launch filters:=pointcloud depth_width:=424 color_width:=424 depth_height:=240 color_height:=240 depth_fps:=30 color_fps:=30
... logging to /home/nikolas/.ros/log/2c4dc12a-b8d6-11eb-b100-9fc7fe01b9f1/roslaunch-nikolas-SYS-5039A-I-66637.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://nikolas-SYS-5039A-I:41183/

SUMMARY
========

PARAMETERS
 * /camera/realsense2_camera/accel_fps: -1
 * /camera/realsense2_camera/accel_frame_id: camera_accel_frame
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: False
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/allow_no_texture_points: False
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/calib_odom_file: 
 * /camera/realsense2_camera/clip_distance: -2.0
 * /camera/realsense2_camera/color_fps: 30
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: 240
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: 424
 * /camera/realsense2_camera/confidence_fps: -1
 * /camera/realsense2_camera/confidence_height: -1
 * /camera/realsense2_camera/confidence_width: -1
 * /camera/realsense2_camera/depth_fps: 30
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: 240
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: 424
 * /camera/realsense2_camera/device_type: 
 * /camera/realsense2_camera/enable_accel: False
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_confidence: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye1: False
 * /camera/realsense2_camera/enable_fisheye2: False
 * /camera/realsense2_camera/enable_fisheye: False
 * /camera/realsense2_camera/enable_gyro: False
 * /camera/realsense2_camera/enable_infra1: False
 * /camera/realsense2_camera/enable_infra2: False
 * /camera/realsense2_camera/enable_infra: False
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_pose: False
 * /camera/realsense2_camera/enable_sync: False
 * /camera/realsense2_camera/filters: pointcloud
 * /camera/realsense2_camera/fisheye1_frame_id: camera_fisheye1_f...
 * /camera/realsense2_camera/fisheye1_optical_frame_id: camera_fisheye1_o...
 * /camera/realsense2_camera/fisheye2_frame_id: camera_fisheye2_f...
 * /camera/realsense2_camera/fisheye2_optical_frame_id: camera_fisheye2_o...
 * /camera/realsense2_camera/fisheye_fps: -1
 * /camera/realsense2_camera/fisheye_frame_id: camera_fisheye_frame
 * /camera/realsense2_camera/fisheye_height: -1
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: -1
 * /camera/realsense2_camera/gyro_fps: -1
 * /camera/realsense2_camera/gyro_frame_id: camera_gyro_frame
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/imu_optical_frame_id: camera_imu_optica...
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra_fps: 30
 * /camera/realsense2_camera/infra_height: 480
 * /camera/realsense2_camera/infra_rgb: False
 * /camera/realsense2_camera/infra_width: 848
 * /camera/realsense2_camera/initial_reset: False
 * /camera/realsense2_camera/json_file_path: 
 * /camera/realsense2_camera/linear_accel_cov: 0.01
 * /camera/realsense2_camera/odom_frame_id: camera_odom_frame
 * /camera/realsense2_camera/ordered_pc: False
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/pose_frame_id: camera_pose_frame
 * /camera/realsense2_camera/pose_optical_frame_id: camera_pose_optic...
 * /camera/realsense2_camera/publish_odom_tf: True
 * /camera/realsense2_camera/publish_tf: True
 * /camera/realsense2_camera/rosbag_filename: 
 * /camera/realsense2_camera/serial_no: 
 * /camera/realsense2_camera/stereo_module/exposure/1: 7500
 * /camera/realsense2_camera/stereo_module/exposure/2: 1
 * /camera/realsense2_camera/stereo_module/gain/1: 16
 * /camera/realsense2_camera/stereo_module/gain/2: 16
 * /camera/realsense2_camera/tf_publish_rate: 0.0
 * /camera/realsense2_camera/topic_odom_in: odom_in
 * /camera/realsense2_camera/unite_imu_method: 
 * /camera/realsense2_camera/usb_port_id: 
 * /rosdistro: noetic
 * /rosversion: 1.15.11

NODES
  /camera/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)

ROS_MASTER_URI=http://localhost:11311

process[camera/realsense2_camera_manager-1]: started with pid [66651]
process[camera/realsense2_camera-2]: started with pid [66652]
[ INFO] [1621451806.809240211]: Initializing nodelet with 20 worker threads.
[ INFO] [1621451806.872573557]: RealSense ROS v2.2.24
[ INFO] [1621451806.872599074]: Built with LibRealSense v2.44.0
[ INFO] [1621451806.872608561]: Running with LibRealSense v2.44.0
[ INFO] [1621451806.901767223]:  
[ INFO] [1621451807.098060017]: Device with serial number 102122071816 was found.

[ INFO] [1621451807.098140718]: Device with physical ID 2-3-7 was found.
[ INFO] [1621451807.098171250]: Device with name Intel RealSense D435I was found.
[ INFO] [1621451807.098972150]: Device with port number 2-3 was found.
[ INFO] [1621451807.099021783]: Device USB type: 3.2
[ INFO] [1621451807.101857827]: getParameters...
[ INFO] [1621451807.151527710]: setupDevice...
[ INFO] [1621451807.151572642]: JSON file is not provided
[ INFO] [1621451807.151595113]: ROS Node Namespace: camera
[ INFO] [1621451807.151616887]: Device Name: Intel RealSense D435I
[ INFO] [1621451807.151639691]: Device Serial No: 102122071816
[ INFO] [1621451807.151661881]: Device physical port: 2-3-7
[ INFO] [1621451807.151693225]: Device FW version: 05.12.13.50
[ INFO] [1621451807.151720874]: Device Product ID: 0x0B3A
[ INFO] [1621451807.151747938]: Enable PointCloud: On
[ INFO] [1621451807.151770027]: Align Depth: Off
[ INFO] [1621451807.151795125]: Sync Mode: On
[ INFO] [1621451807.151860184]: Device Sensors: 
[ INFO] [1621451807.171265519]: Stereo Module was found.
[ INFO] [1621451807.179159759]: RGB Camera was found.
[ INFO] [1621451807.179334388]: Motion Module was found.
[ INFO] [1621451807.179369709]: (Confidence, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1621451807.179388366]: Add Filter: pointcloud
[ INFO] [1621451807.179870418]: num_filters: 1
[ INFO] [1621451807.179896016]: Setting Dynamic reconfig parameters.
[ WARN] [1621451807.563945553]: Param '/camera/stereo_module/auto_exposure_limit' has value 0 that is not in range [1, 165000]. Removing this parameter from dynamic reconfigure options.
[ WARN] [1621451807.576048087]: Param '/camera/stereo_module/auto_gain_limit' has value 0 that is not in range [16, 248]. Removing this parameter from dynamic reconfigure options.
[ INFO] [1621451807.626461958]: Done Setting Dynamic reconfig parameters.
[ INFO] [1621451807.626875718]: depth stream is enabled - width: 424, height: 240, fps: 30, Format: Z16
[ INFO] [1621451807.627238211]: color stream is enabled - width: 424, height: 240, fps: 30, Format: RGB8
[ INFO] [1621451807.627272450]: setupPublishers...
[ INFO] [1621451807.630209629]: Expected frequency for depth = 30.00000
[ INFO] [1621451807.659949501]: Expected frequency for color = 30.00000
[ INFO] [1621451807.689798345]: setupStreams...
[ INFO] [1621451807.701047289]: insert Depth to Stereo Module
[ INFO] [1621451807.701127082]: insert Color to RGB Camera
[ INFO] [1621451807.755367357]: SELECTED BASE:Depth, 0
[ INFO] [1621451807.764177302]: RealSense Node Is Up!
[ WARN] [1621451807.884445975]: 
 19/05 15:16:47,885 WARNING [140415365805824] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 19/05 15:16:47,935 WARNING [140415365805824] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 19/05 15:16:47,986 WARNING [140415365805824] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 19/05 15:16:48,037 WARNING [140415365805824] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 19/05 15:16:48,088 WARNING [140415365805824] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 19/05 15:16:48,138 WARNING [140415365805824] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 19/05 15:16:48,189 WARNING [140415365805824] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 19/05 15:16:48,240 WARNING [140415365805824] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 19/05 15:16:48,290 WARNING [140415365805824] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 19/05 15:16:48,341 WARNING [140415365805824] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 19/05 15:16:48,392 WARNING [140415365805824] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 19/05 15:16:48,544 WARNING [140415365805824] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 19/05 15:16:48,594 WARNING [140415365805824] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 19/05 15:16:48,746 WARNING [140415365805824] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 19/05 15:16:48,796 WARNING [140415365805824] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 19/05 15:17:41,791 WARNING [140415365805824] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 19/05 15:18:31,878 WARNING [140415365805824] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 19/05 15:18:31,928 WARNING [140415365805824] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 19/05 15:19:08,006 WARNING [140415365805824] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 19/05 15:19:50,085 WARNING [140415365805824] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 19/05 15:19:50,136 WARNING [140415365805824] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 19/05 15:19:52,188 WARNING [140415365805824] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 19/05 15:19:52,238 WARNING [140415365805824] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 19/05 15:19:53,289 WARNING [140415365805824] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 19/05 15:19:53,340 WARNING [140415365805824] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 19/05 15:19:54,391 WARNING [140415365805824] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 19/05 15:19:54,442 WARNING [140415365805824] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 19/05 15:19:59,496 WARNING [140415365805824] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 19/05 15:19:59,547 WARNING [140415365805824] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 19/05 15:20:03,599 WARNING [140415365805824] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 19/05 15:20:03,650 WARNING [140415365805824] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 19/05 15:20:04,701 WARNING [140415365805824] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 19/05 15:20:04,752 WARNING [140415365805824] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 19/05 15:20:44,832 WARNING [140415365805824] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61

**Comment by MartyG-RealSense** [comment]
Great to hear that you had success @Nick-Kou 

If the **control_transfer returned** warning only appears at a rate of once or twice per minute after launch then it is safe to ignore it.

**Comment by Nick-Kou** [comment]
Thank you

**Comment by MartyG-RealSense** [comment]
Hi @Nick-Kou  Do you require further assistance with this case, please?  Thanks!

**Comment by Nick-Kou** [comment]
Hi, @MartyG-RealSense  everything is resolved thanks.

**Comment by MartyG-RealSense** [comment]
Excellent to hear, @Nick-Kou - I will therefore close this case.  Thanks again!
