### ISSUE TITLE
what can i operate with IMU data and D435?

### ISSUE THREAD

**Issue by SU1997** [realsenseai/realsense-ros#1883]
there is no T265 camera. But i have  imu data and a D435i camera,how to edit the source code to correctly run?

**Comment by SU1997** [comment]
here are the ros topics:
/GLxxBatteryCmd
/GLxxBatteryMsg_msg
/SaveImage
/action_key_frame_lists
/adjust_status
/avoid_area
/avoid_mode
/avoid_status
/barcode_timeout
/battery
/battery_info
/behavior_status
/calib_process
/ceil_barc
/ceil_barc_offset
/ceil_barc_timeout
/charging_status
/cmd/zynq_cmd
/cmd_board
/cmd_vel
/cmd_vel_manual
/component_test
/config_robot_info
/control_action_mode
/control_mode
/diagnostics
/drivers/realsense/accel/imu_info0
/drivers/realsense/depth/camera_info0
/drivers/realsense/depth/image_rect_raw0
/drivers/realsense/depth/image_rect_raw0/compressed
/drivers/realsense/depth/image_rect_raw0/compressed/parameter_descriptions
/drivers/realsense/depth/image_rect_raw0/compressed/parameter_updates
/drivers/realsense/depth/image_rect_raw0/compressedDepth
/drivers/realsense/depth/image_rect_raw0/compressedDepth/parameter_descriptions
/drivers/realsense/depth/image_rect_raw0/compressedDepth/parameter_updates
/drivers/realsense/depth/image_rect_raw0/theora
/drivers/realsense/depth/image_rect_raw0/theora/parameter_descriptions
/drivers/realsense/depth/image_rect_raw0/theora/parameter_updates
/drivers/realsense/extrinsics/depth_to_infra10
/drivers/realsense/extrinsics/depth_to_infra20
/drivers/realsense/extrinsics/depth_to_robot0
/drivers/realsense/geekvision_realsense_manager/bond
/drivers/realsense/gyro/imu_info0
/drivers/realsense/imu0
/drivers/realsense/infra1/camera_info0
/drivers/realsense/infra1/image_rect_raw0
/drivers/realsense/infra1/image_rect_raw0/compressed
/drivers/realsense/infra1/image_rect_raw0/compressed/parameter_descriptions
/drivers/realsense/infra1/image_rect_raw0/compressed/parameter_updates
/drivers/realsense/infra1/image_rect_raw0/compressedDepth
/drivers/realsense/infra1/image_rect_raw0/compressedDepth/parameter_descriptions
/drivers/realsense/infra1/image_rect_raw0/compressedDepth/parameter_updates
/drivers/realsense/infra1/image_rect_raw0/theora
/drivers/realsense/infra1/image_rect_raw0/theora/parameter_descriptions
/drivers/realsense/infra1/image_rect_raw0/theora/parameter_updates
/drivers/realsense/infra2/camera_info0
/drivers/realsense/infra2/image_rect_raw0
/drivers/realsense/infra2/image_rect_raw0/compressed
/drivers/realsense/infra2/image_rect_raw0/compressed/parameter_descriptions
/drivers/realsense/infra2/image_rect_raw0/compressed/parameter_updates
/drivers/realsense/infra2/image_rect_raw0/compressedDepth
/drivers/realsense/infra2/image_rect_raw0/compressedDepth/parameter_descriptions
/drivers/realsense/infra2/image_rect_raw0/compressedDepth/parameter_updates
/drivers/realsense/infra2/image_rect_raw0/theora
/drivers/realsense/infra2/image_rect_raw0/theora/parameter_descriptions
/drivers/realsense/infra2/image_rect_raw0/theora/parameter_updates
/drivers/realsense/motion_module0/parameter_descriptions
/drivers/realsense/motion_module0/parameter_updates
/drivers/realsense/rgb_camera0/parameter_descriptions
/drivers/realsense/rgb_camera0/parameter_updates
/drivers/realsense/rs_config0
/drivers/realsense/rs_status
/drivers/realsense/rs_status/camera0
/drivers/realsense/stereo_module/auto_exposure_roi0/parameter_descriptions
/drivers/realsense/stereo_module/auto_exposure_roi0/parameter_updates
/drivers/realsense/stereo_module0/parameter_descriptions
/drivers/realsense/stereo_module0/parameter_updates
/error_code
/fault_sound
/feature_detected
/feature_map
/feature_matching_res
/feedback/pallet_detection
/feedback/signal_status
/filted_point_cloud
/forklift_work_status
/galaxy_nodelet_manager/bond
/geekplus_mapping/map
/geekplus_mapping/png_with_map_info
/geekplusbot_amcl/landmark_list
/geekplusbot_amcl/lane_line_list
/geekslam_localization_node/active_map_ack
/geekslam_localization_node/active_map_ready
/geekvision/galaxy/extrinsic
/geekvision/galaxy/homography
/geekvision/galaxy/img
/geekvision/galaxy/img/compressed
/geekvision/galaxy/img/compressed/parameter_descriptions
/geekvision/galaxy/img/compressed/parameter_updates
/geekvision/galaxy/img/compressedDepth
/geekvision/galaxy/img/compressedDepth/parameter_descriptions
/geekvision/galaxy/img/compressedDepth/parameter_updates
/geekvision/galaxy/img/theora
/geekvision/galaxy/img/theora/parameter_descriptions
/geekvision/galaxy/img/theora/parameter_updates
/geekvision/galaxy/intrinsic
/geekvision/galaxy/serial
/geekvision/galaxy/status
/geekvision/lane/lane
/geekvision/lane/status
/get_log_message
/global_match_window
/global_points
/goal_pose
/ground_barc
/ground_barc_map_marker
/imu
/imu_angle
/imu_info
/initialLocalization
/initialpose
/joy
/landmark_map_marker
/led_task_status
/ligth_test
/localization_mode
/localization_status
/log_message_res
/log_msg
/map
/map_file_list
/map_metadata
/map_update
/map_updates
/master_system_info
/mission_log
/mission_status
/module_status
/motor_info
/move_base/current_goal
/move_base/goal
/move_base_simple/goal
/move_state
/network_status
/odom
/odom_dist
/overweight_status
/pallet_center_distance
/pallet_recognition
/perception/freespace_detection/fs_status
/perception/freespace_detection/point_cloud0
/perception/freespace_detection/point_cloud1
/perception/lane_detect/lane
/perception/lane_detection/lane
/perception/tag_detection/Tag
/perception/tag_detection/TagCorners1
/perception/tag_detection/Tag_status
/perception/tag_detection/detect_tag_image1
/perception/tag_detection/detect_tag_image1/compressed
/perception/tag_detection/detect_tag_image1/compressed/parameter_descriptions
/perception/tag_detection/detect_tag_image1/compressed/parameter_updates
/perception/tag_detection/detect_tag_image1/compressedDepth
/perception/tag_detection/detect_tag_image1/compressedDepth/parameter_descriptions
/perception/tag_detection/detect_tag_image1/compressedDepth/parameter_updates
/perception/tag_detection/detect_tag_image1/theora
/perception/tag_detection/detect_tag_image1/theora/parameter_descriptions
/perception/tag_detection/detect_tag_image1/theora/parameter_updates
/plan_mode
/points_map
/points_marker
/rack_info
/radar
/recog_status
/reflector
/reflector_pose
/res_board
/robot_path
/robot_pose
/robot_status
/roller_command_from_Mission
/roller_command_from_RMS
/roller_command_from_USER
/roller_event_to_RMS
/rosout
/rosout_agg
/scan
/scan2
/scan_b
/scan_b_1
/scan_base
/scan_lb
/scan_lb_1
/scan_lf
/scan_lf_1
/scan_rb
/scan_rb_1
/server_mission
/shelf_info
/sick_tim561/parameter_descriptions
/sick_tim561/parameter_updates
/sound
/static_map_info
/submap_list
/switch_localization_mode
/sync_map_info
/sync_submap
/synchronized_points
/system_state
/target_map
/task4server
/task_action
/task_log
/task_status
/temp_path
/test_submap_map
/tf
/tf_static
/tmp_path
/unbalance_load_status
/updateFeatureMap
/updates_command
/updates_result
/vis_barc
/visualization_marker
/visualization_points
/vxslam_manager/bond
/waypoints
/weigh_reset
/window_points

**Comment by MartyG-RealSense** [comment]
Hi @SU1997  Could you tell me more please about the problem that you are having?

For example, if you have a **D435i** camera and the IMU topics (accel and gyro) are not publishing then they can be published by adding the commands below onto the end of your roslaunch instruction.

**enable_gyro:=true enable_accel:=true**

For example:

**roslaunch realsense2_camera rs_camera.launch enable_gyro:=true enable_accel:=true**

If it were a D435 camera that you have then IMU information cannot be obtained from that camera model because it does not have an IMU component inside it.

**Comment by SU1997** [comment]
> Hi @SU1997 Could you tell me more please about the problem that you are having?
> 
> For example, if you have a **D435i** camera and the IMU topics (accel and gyro) are not publishing then they can be published by adding the commands below onto the end of your roslaunch instruction.
> 
> **enable_gyro:=true enable_accel:=true**
> 
> For example:
> 
> **roslaunch realsense2_camera rs_camera.launch enable_gyro:=true enable_accel:=true**
> 
> If it were a D435 camera that you have then IMU information cannot be obtained from that camera model because it does not have an IMU component inside it.

thank you for your reply, i have D435i camera and recorded both depth data and imu data.
but the source code use T265 and D400 default,so my question is where to edit the source code to  match my data?
here is my rosbag info:

types:       nav_msgs/Odometry      [cd5e73d190d741a2f92e81eda573aca7]
             sensor_msgs/CameraInfo [c9a58c1b0b154e0e6da7578cb991d214]
             sensor_msgs/Image      [060021388200f6f0f447d0fcd9c64743]
             sensor_msgs/Imu        [6a62c6daae103f4ff57a132d6f95cec2]
             tf2_msgs/TFMessage     [94810edda583a504dfda3829e70d7eec]
topics:      /drivers/realsense/depth/camera_info0         909 msgs    : sensor_msgs/CameraInfo
             /drivers/realsense/depth/image_rect_raw0      909 msgs    : sensor_msgs/Image     
             /drivers/realsense/imu0                     11856 msgs    : sensor_msgs/Imu       
             /drivers/realsense/infra1/camera_info0        909 msgs    : sensor_msgs/CameraInfo
             /drivers/realsense/infra1/image_rect_raw0     907 msgs    : sensor_msgs/Image     
             /drivers/realsense/infra2/camera_info0        907 msgs    : sensor_msgs/CameraInfo
             /drivers/realsense/infra2/image_rect_raw0     907 msgs    : sensor_msgs/Image     
             /geekvision/galaxy/img                        605 msgs    : sensor_msgs/Image     
             /imu                                         3017 msgs    : sensor_msgs/Imu       
             /odom                                        3017 msgs    : nav_msgs/Odometry     
             /tf                                          9901 msgs    : tf2_msgs/TFMessage     (5 connections)
             /tf_static                                      1 msg     : tf2_msgs/TFMessage

**Comment by MartyG-RealSense** [comment]
I am unable to answer questions related to the T265, and answered this case because your message said "there is no T265 camera". I can continue with the case though if it only involves the D435i. 

I do not understand your question about modifying the source code to match your data.   Could you provide more information about what you are trying to achieve, please?

**Comment by SU1997** [comment]
> I am unable to answer questions related to the T265, and answered this case because your message said "there is no T265 camera". I can continue with the case though if it only involves the D435i.
> 
> I do not understand your question about modifying the source code to match your data. Could you provide more information about what you are trying to achieve, please?

yes,i mean i only have D435i,and i think i should change some settings in the source code and build it again.

**Comment by MartyG-RealSense** [comment]
Thanks very much @SU1997 for the update - please let me know the outcome of your next build.  Good luck!

**Comment by MartyG-RealSense** [comment]
Hi @SU1997  Do you have an update about this case that you can provide, please?  Thanks!

**Comment by SU1997** [comment]
> Hi @SU1997 Do you have an update about this case that you can provide, please? Thanks!

thanks and i have solved this problem. im a rookie in ros, this took me several days to solve it but fortunately it works finally.thank you for your patiently reply.

**Comment by MartyG-RealSense** [comment]
It is great to hear @SU1997 that you developed a solution.  :)

As your issue is solved, I will close this case.  Thanks again!
