### ISSUE TITLE
Pointcloud missing color on the sides

### ISSUE THREAD

**Issue by ivadimi** [realsenseai/realsense-ros#1890]
**Description**
Pointcloud, visualized in rviz, has some missing or incorrect color on a side and a bit at the bottom.
![example](https://user-images.githubusercontent.com/81099128/119145758-39807c00-ba4a-11eb-914d-cfb6feae660d.png)

**Launch file snippet**
`<include file="$(find realsense2_camera)/launch/rs_camera.launch">
<arg name="json_file_path" value="/home/user/catkin_ws/src/package/cfg/HighResHighAccuracyPreset.json"/>
<arg name="filters" value="pointcloud,temporal,spatial" />
<arg name="clip_distance" value="0.5" />
</include> `

What could be the potential cause of this? Thank you in advance.

**Comment by MartyG-RealSense** [comment]
Hi @ivadimi   The RealSense ROS wrapper has a pointcloud filter setting called **allow_no_texture_points** that has the following description:

**************

The depth FOV and the texture FOV are not similar.  By default, pointcloud is limited to the section of depth containing the texture.  You can have a full depth to pointcloud, coloring the regions beyond the texture with zeros, by setting allow_no_texture_points to true.

**********

Could you try setting **allow_no_texture_points** to True, please by adding the command below to your roslaunch instruction:

**allow_no_texture_points:=true**

It is also worth mentioning that if you feel that you lose excessive detail from the image by using the High Accuracy preset then the **Medium Density** preset may help, as it provides a balance between accuracy and the amount of detail on the image.

**Comment by ivadimi** [comment]
Hi @MartyG-RealSense .Thank you for your answer.

Unfortunately, I've already tried setting allow_no_texture_points to true and it didn't result in any change.
I will be able to try again on Tuesday and report again, in case it suddenly works.

**Comment by MartyG-RealSense** [comment]
Okay, I look forward to continuing the case with you when you are ready.  Good luck!

**Comment by ivadimi** [comment]
Just in case, I did a gold factory reset (for camera) and updated to latest ros-wrapper version.

Here is an updated snippet of a launch file and the corresponding results.
`    <include file="$(find realsense2_camera)/launch/rs_camera.launch"> 
        <arg name="json_file_path" value="$(arg HighResMedDensityPreset)"/>
        <arg name="filters" value="pointcloud,temporal,spatial" />
        <arg name="ordered_pc" value="true"/>
        <arg name="clip_distance" value="0.5" />
        <arg name="allow_no_texture_points" value="true"/>
    </include> `

![error](https://user-images.githubusercontent.com/81099128/119479836-54f0cd00-bd51-11eb-9afe-19b4dd70b967.png)

I've also tried setting "ordered_pc" to true. It produced the following result: (now the texture flickers as opposed to being static)

![test](https://user-images.githubusercontent.com/81099128/119480388-e6603f00-bd51-11eb-80d8-b0c9509bbe4c.gif)

Setting "alighed_depth" to true produces the desired result.

![align](https://user-images.githubusercontent.com/81099128/119494733-ec5e1c00-bd61-11eb-8d26-108f1eaefc1b.png)

However I am not sure whether aligning depth to color will result in any distance measurement inaccuracies to the pointcloud.

**Comment by MartyG-RealSense** [comment]
In general, aligning depth to color can have a positive influence on depth measurement, as it makes it easier to distinguish background pixels from foreground pixels.

**Comment by ivadimi** [comment]
The problems are fixed. Thank you for the support @MartyG-RealSense . Closing the issue.

**Comment by MartyG-RealSense** [comment]
Excellent news - thanks very much @ivadimi for the update!
