### ISSUE TITLE
remote view of RGB l515 stream

### ISSUE THREAD

**Issue by AndreV84** [realsenseai/realsense-ros#1891]
how would play on remote rviz the rgb of l515?
Thanks

**Comment by RealSenseSupport** [comment]
@AndreV84 

Can you help us understand a bit more your issue here?  L515 RGB stream should be available.

**Comment by AndreV84** [comment]
how would we connect from rviz  to remote l515 RGB steam? Thanks

**Comment by MartyG-RealSense** [comment]
Hi @AndreV84  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
