### ISSUE TITLE
Using default NodeHandle instead of private NodeHandle for setting parameters

### ISSUE THREAD

**Issue by Marenix** [realsenseai/realsense-ros#1894]
Hi. I've been going over the code for the wrapper, and noticed that in base_realsense_node.cpp in function publishTopics, you're giving function registerDynamicReconfigCb _node_handle (which is a default node handle). This function basically goes on to setting parameters. What I'm wondering is why you used a public node handle? As far as I know, it's recommended to use a private node handle when working with parameters, so I'm curious if there's a reason you used a public node handle specifically?

**Comment by doronhi** [comment]
No reason that I am aware of. This is an old part of the code. If I am convinced there is a good enough reason to change I'll change.

**Comment by Marenix** [comment]
It would make setting default parameters from .launch file like this possible (also, adding the appropriate lines in nodelet.launch.xml):
![rs_camera1](https://user-images.githubusercontent.com/39246140/119614798-00a42680-bdff-11eb-9a17-2e6b7bd5456a.png)
![rs_camera2](https://user-images.githubusercontent.com/39246140/119614806-03068080-bdff-11eb-85ed-4884413ab386.png)

It might not be that important for dynamic parameters (like exposure in my example), since they can be set after the streams start, but the problem is with parameters like inter_cam_sync_mode which can't be set once the streams start. 
I tested the default code with this .launch file and parameters weren't changed (looked at the stream in rviz just to make sure the inter_cam_sync_mode wasn't set):
![rqt1](https://user-images.githubusercontent.com/39246140/119616128-8d031900-be00-11eb-94ba-c7d597628f4a.png)
![rviz1](https://user-images.githubusercontent.com/39246140/119616147-8ffe0980-be00-11eb-9e1d-1415d31217cf.png)

Then I changed to a private node handle in function publishTopics(passing _pnh to functions called in publishTopics instead of _node_handle), and the parameters were set (exposure to 500 and inter_cam_sync_mode to 4, no image in rviz):
![rqt2](https://user-images.githubusercontent.com/39246140/119616697-34804b80-be01-11eb-95b4-fb7d393d8c19.png)
![rviz2](https://user-images.githubusercontent.com/39246140/119616831-5bd71880-be01-11eb-893d-71a7e7d35192.png)

**Comment by doronhi** [comment]
That sounds very interesting. Could you submit a PR so I could test it more thoroughly?
It might take me a little while to get around to it but it sounds important.

**Comment by Marenix** [comment]
I submitted a [PR#1901](https://github.com/IntelRealSense/realsense-ros/pull/1901).

**Comment by RealSenseSupport** [comment]
@Marenix I saw you closed https://github.com/IntelRealSense/realsense-ros/pull/1901. Can this ticket also be closed? Thanks!

**Comment by Marenix** [comment]
Yes, it can be closed. Thanks.
