### ISSUE TITLE
Dependencies not installed properly

### ISSUE THREAD

**Issue by Ingenious-Doc** [realsenseai/realsense-ros#1896]
Whenever I run the following command:
`sudo apt-get install ros-$ROS_DISTRO-realsense2-camera`

it doesn't install the librealsense2 library and only install the realsense camera package. I try to find the package using roscd command, but it doesn't autocomplete and doesn't find the package...

**Comment by MartyG-RealSense** [comment]
Hi @Ingenious-Doc   Are there any error messages that are generated by the package installation, please?  If there are, could you post a log here.  Thanks!

**Comment by MartyG-RealSense** [comment]
Hi @Ingenious-Doc   Do you require further assistance with this case, please?  Thanks!

**Comment by Ingenious-Doc** [comment]
yes, let me show you

**Comment by MartyG-RealSense** [comment]
Hi @Ingenious-Doc   Can you provide information about the further help that you need, please?  Thanks very much.

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
