### ISSUE TITLE
select a pixel and obtain an information about that pixel

### ISSUE THREAD

**Issue by ranjitkathiriya** [realsenseai/realsense-ros#1898]
Hello there,

I am having a 3D coordinate of a pixel in a point cloud and I want to get a pose, colour and other details of that pixel is that possible?

```
x: -0.6432073622208151
y: -1.5460235599754877
z: 0.26247830094070435
```

**Comment by MartyG-RealSense** [comment]
Hi @ranjitkathiriya  Getting pose in ROS with a RealSense camera such as D435 tends to be complicated, with the most well-known RealSense-using solution **DOPE** making use of Unreal Engine 4 and an Nvidia data-set.

https://github.com/yehengchen/DOPE-ROS-D435
https://github.com/avinashsen707/AUBOi5-D435-ROS-DOPE

A simpler approach is described in the link below, which is a ROS pose project in Python for using RealSense to predict the pose of a cube and track it by its color.

https://by-the-w3i.github.io/2019/10/06/ColorBlockTracking/

In regard to obtaining other types of information in ROS with RealSense: although the link below is not about the subject of pose, it does describe how to generate an **XYZRGBI** point cloud with **intensity** information.

https://github.com/IntelRealSense/realsense-ros/issues/1046
