### ISSUE TITLE
Wires and Cables in lidar-camera-l515-multi-camera-setup white paper

### ISSUE THREAD

**Issue by jieunko** [realsenseai/realsense-ros#1900]
Hello 
Now I am following white paper of https://dev.intelrealsense.com/docs/lidar-camera-l515-multi-camera-setup
can you tell me the all the cables and wires you used?

**Comment by RealSenseSupport** [comment]
@jieunko 

We do provide some information regarding parts used in the whitepaper although we do not provide all wires that were used.  Our cables were produced in house but are not special and wires can be found online that should work sufficiently.
