### ISSUE TITLE
Jetson nano Fps of topics and IMU direction  / D435i

### ISSUE THREAD

**Issue by Majed-Alsubaie** [realsenseai/realsense-ros#1911]
Hi i have a weird  issue where i set topics to be published with 15 FPS but that does not work and topics published with 2  , 15 and 30 hz

`roslaunch realsense2_camera rs_camera.launch align_depth:=true unite_imu_method:="linear_interpolation" enable_gyro:=true enable_accel:=true color_fps:=15 infra_fps:=15 depth_fps:=15 color_width:=1280 color_height:=720 depth_width:=848 depth_height:=480 initial_reset:=true
... logging to /home/kfupm/.ros/log/53ecfde0-c49d-11eb-a067-0242cc161f6e/roslaunch-kfupm-desktop-29817.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://kfupm-desktop:39893/

SUMMARY
========

PARAMETERS
 * /camera/realsense2_camera/accel_fps: -1
 * /camera/realsense2_camera/accel_frame_id: camera_accel_frame
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: True
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/allow_no_texture_points: False
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/calib_odom_file: 
 * /camera/realsense2_camera/clip_distance: -2.0
 * /camera/realsense2_camera/color_fps: 15
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: 720
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: 1280
 * /camera/realsense2_camera/confidence_fps: -1
 * /camera/realsense2_camera/confidence_height: -1
 * /camera/realsense2_camera/confidence_width: -1
 * /camera/realsense2_camera/depth_fps: 15
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: 480
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: 848
 * /camera/realsense2_camera/device_type: 
 * /camera/realsense2_camera/enable_accel: True
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_confidence: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye1: False
 * /camera/realsense2_camera/enable_fisheye2: False
 * /camera/realsense2_camera/enable_fisheye: False
 * /camera/realsense2_camera/enable_gyro: True
 * /camera/realsense2_camera/enable_infra1: False
 * /camera/realsense2_camera/enable_infra2: False
 * /camera/realsense2_camera/enable_infra: False
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_pose: False
 * /camera/realsense2_camera/enable_sync: False
 * /camera/realsense2_camera/filters: 
 * /camera/realsense2_camera/fisheye1_frame_id: camera_fisheye1_f...
 * /camera/realsense2_camera/fisheye1_optical_frame_id: camera_fisheye1_o...
 * /camera/realsense2_camera/fisheye2_frame_id: camera_fisheye2_f...
 * /camera/realsense2_camera/fisheye2_optical_frame_id: camera_fisheye2_o...
 * /camera/realsense2_camera/fisheye_fps: -1
 * /camera/realsense2_camera/fisheye_frame_id: camera_fisheye_frame
 * /camera/realsense2_camera/fisheye_height: -1
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: -1
 * /camera/realsense2_camera/gyro_fps: -1
 * /camera/realsense2_camera/gyro_frame_id: camera_gyro_frame
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/imu_optical_frame_id: camera_imu_optica...
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra_fps: 15
 * /camera/realsense2_camera/infra_height: 480
 * /camera/realsense2_camera/infra_rgb: False
 * /camera/realsense2_camera/infra_width: 848
 * /camera/realsense2_camera/initial_reset: True
 * /camera/realsense2_camera/json_file_path: 
 * /camera/realsense2_camera/linear_accel_cov: 0.01
 * /camera/realsense2_camera/odom_frame_id: camera_odom_frame
 * /camera/realsense2_camera/ordered_pc: False
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/pose_frame_id: camera_pose_frame
 * /camera/realsense2_camera/pose_optical_frame_id: camera_pose_optic...
 * /camera/realsense2_camera/publish_odom_tf: True
 * /camera/realsense2_camera/publish_tf: True
 * /camera/realsense2_camera/rosbag_filename: 
 * /camera/realsense2_camera/serial_no: 
 * /camera/realsense2_camera/stereo_module/exposure/1: 7500
 * /camera/realsense2_camera/stereo_module/exposure/2: 1
 * /camera/realsense2_camera/stereo_module/gain/1: 16
 * /camera/realsense2_camera/stereo_module/gain/2: 16
 * /camera/realsense2_camera/tf_publish_rate: 0.0
 * /camera/realsense2_camera/topic_odom_in: odom_in
 * /camera/realsense2_camera/unite_imu_method: linear_interpolation
 * /camera/realsense2_camera/usb_port_id: 
 * /rosdistro: melodic
 * /rosversion: 1.14.11

NODES
  /camera/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)

auto-starting new master
process[master]: started with pid [29830]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 53ecfde0-c49d-11eb-a067-0242cc161f6e
process[rosout-1]: started with pid [29843]
started core service [/rosout]
process[camera/realsense2_camera_manager-2]: started with pid [29860]
process[camera/realsense2_camera-3]: started with pid [29861]
[ INFO] [1622746559.247822729]: Initializing nodelet with 4 worker threads.
[ INFO] [1622746559.569588748]: RealSense ROS v2.3.0
[ INFO] [1622746559.569681874]: Built with LibRealSense v2.45.0
[ INFO] [1622746559.569757395]: Running with LibRealSense v2.45.0
[ INFO] [1622746559.633680638]:  
[ INFO] [1622746559.861682043]: Device with serial number 021122070718 was found.

[ INFO] [1622746559.861770221]: Device with physical ID 2-1.3-16 was found.
[ INFO] [1622746559.861956421]: Device with name Intel RealSense D435I was found.
[ INFO] [1622746559.863274608]: Device with port number 2-1.3 was found.
[ INFO] [1622746559.863421848]: Device USB type: 3.2
[ INFO] [1622746559.863498984]: Resetting device...
[ INFO] [1622746565.906105011]:  
 03/06 21:56:06,114 WARNING [547331498368] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
[ INFO] [1622746566.175790249]: Device with serial number 021122070718 was found.

[ INFO] [1622746566.175887021]: Device with physical ID 2-1.3-17 was found.
[ INFO] [1622746566.175938376]: Device with name Intel RealSense D435I was found.
[ INFO] [1622746566.177096926]: Device with port number 2-1.3 was found.
[ INFO] [1622746566.177178593]: Device USB type: 3.2
[ INFO] [1622746566.183772706]: getParameters...
[ INFO] [1622746566.452629763]: setupDevice...
[ INFO] [1622746566.452771066]: JSON file is not provided
[ INFO] [1622746566.452850129]: ROS Node Namespace: camera
[ INFO] [1622746566.452913046]: Device Name: Intel RealSense D435I
[ INFO] [1622746566.452983724]: Device Serial No: 021122070718
[ INFO] [1622746566.453042578]: Device physical port: 2-1.3-17
[ INFO] [1622746566.453106225]: Device FW version: 05.12.13.50
[ INFO] [1622746566.453160965]: Device Product ID: 0x0B3A
[ INFO] [1622746566.453212736]: Enable PointCloud: Off
[ INFO] [1622746566.453262476]: Align Depth: On
[ INFO] [1622746566.453316851]: Sync Mode: On
[ INFO] [1622746566.454752539]: Device Sensors: 
[ INFO] [1622746566.487928835]: Stereo Module was found.
[ INFO] [1622746566.532476624]: RGB Camera was found.
[ INFO] [1622746566.533609028]: Motion Module was found.
[ INFO] [1622746566.533742258]: (Confidence, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1622746566.534594504]: num_filters: 1
[ INFO] [1622746566.534681484]: Setting Dynamic reconfig parameters.
 03/06 21:56:06,947 WARNING [547331498368] (messenger-libusb.cpp:42) control_transfer returned error, index: 300, error: No data available, number: 3d
 03/06 21:56:07,023 WARNING [547331498368] (messenger-libusb.cpp:42) control_transfer returned error, index: 300, error: No data available, number: 3d
[ WARN] [1622746567.087069877]: Param '/camera/stereo_module/auto_exposure_limit' has value 0 that is not in range [1, 165000]. Removing this parameter from dynamic reconfigure options.
 03/06 21:56:07,088 WARNING [547331498368] (messenger-libusb.cpp:42) control_transfer returned error, index: 300, error: No data available, number: 3d
[ WARN] [1622746567.151871260]: Param '/camera/stereo_module/auto_gain_limit' has value 0 that is not in range [16, 248]. Removing this parameter from dynamic reconfigure options.
[ INFO] [1622746567.295487725]: Done Setting Dynamic reconfig parameters.
[ INFO] [1622746567.296972268]: depth stream is enabled - width: 848, height: 480, fps: 15, Format: Z16
[ INFO] [1622746567.298724156]: color stream is enabled - width: 1280, height: 720, fps: 15, Format: RGB8
[ INFO] [1622746567.301618814]: gyro stream is enabled - fps: 200
[ INFO] [1622746567.301721314]: accel stream is enabled - fps: 63
[ INFO] [1622746567.301798503]: setupPublishers...
[ INFO] [1622746567.314296202]: Expected frequency for depth = 15.00000
[ INFO] [1622746567.391901329]: Expected frequency for color = 15.00000
[ INFO] [1622746567.453483884]: Expected frequency for aligned_depth_to_color = 15.00000
[ INFO] [1622746567.515394619]: Start publisher IMU
[ INFO] [1622746567.520004602]: setupStreams...
[ INFO] [1622746567.532267977]: insert Depth to Stereo Module
[ INFO] [1622746567.532479542]: insert Color to RGB Camera
[ INFO] [1622746567.532621366]: insert Gyro to Motion Module
[ INFO] [1622746567.532706366]: insert Accel to Motion Module
 03/06 21:56:07,546 WARNING [547776082304] (ds5-motion.cpp:473) IMU Calibration is not available, default intrinsic and extrinsic will be used.
[ WARN] [1622746567.574712522]: 
[ WARN] [1622746567.575735186]: frame's time domain is HARDWARE_CLOCK. Timestamps may reset periodically.
 03/06 21:56:07,662 WARNING [547331498368] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
[ INFO] [1622746567.713474731]: SELECTED BASE:Depth, 0
[ INFO] [1622746567.764041889]: RealSense Node Is Up!
 03/06 21:56:07,852 WARNING [547331498368] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 03/06 21:56:07,902 WARNING [547331498368] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 03/06 21:56:07,953 WARNING [547331498368] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 03/06 21:56:08,003 WARNING [547331498368] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 03/06 21:56:08,187 WARNING [547331498368] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 03/06 21:56:08,237 WARNING [547331498368] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 03/06 21:56:08,288 WARNING [547331498368] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
[ WARN] [1622746568.296460663]: Hardware Notification:Motion Module failure,1.62275e+12,Error,Hardware Error
 03/06 21:56:08,339 WARNING [547331498368] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 03/06 21:56:08,490 WARNING [547331498368] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 03/06 21:56:08,540 WARNING [547331498368] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 03/06 21:56:08,692 WARNING [547331498368] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 03/06 21:56:08,742 WARNING [547331498368] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 03/06 21:56:08,893 WARNING [547331498368] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 03/06 21:56:08,944 WARNING [547331498368] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 03/06 21:56:09,094 WARNING [547331498368] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 03/06 21:56:09,145 WARNING [547331498368] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 03/06 21:58:19,804 WARNING [547331498368] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
`

`kfupm@kfupm-desktop:~$ rostopic hz /camera/depth/image_rect_raw
subscribed to [/camera/depth/image_rect_raw]
average rate: 50.755
	min: 0.001s max: 0.517s std dev: 0.09390s window: 30
average rate: 35.564
	min: 0.001s max: 0.575s std dev: 0.11713s window: 64
average rate: 32.955
	min: 0.001s max: 0.575s std dev: 0.11602s window: 89
average rate: 31.725
	min: 0.001s max: 0.575s std dev: 0.11815s window: 119
average rate: 30.778
	min: 0.001s max: 0.575s std dev: 0.12047s window: 149
average rate: 28.408
	min: 0.001s max: 0.575s std dev: 0.12563s window: 168
average rate: 30.099
	min: 0.001s max: 0.575s std dev: 0.12254s window: 196
average rate: 29.821
	min: 0.001s max: 0.575s std dev: 0.12361s window: 228
average rate: 29.738
	min: 0.001s max: 0.575s std dev: 0.12384s window: 260
average rate: 28.630
	min: 0.001s max: 0.575s std dev: 0.12689s window: 284
average rate: 29.478
	min: 0.001s max: 0.575s std dev: 0.12509s window: 309
^Caverage rate: 29.358
	min: 0.001s max: 0.575s std dev: 0.12480s window: 330
kfupm@kfupm-desktop:~$ rostopic hz /camera/aligned_depth_to_color/image_raw
subscribed to [/camera/aligned_depth_to_color/image_raw]
no new messages
average rate: 1.818
	min: 0.533s max: 0.567s std dev: 0.01699s window: 3
average rate: 1.783
	min: 0.533s max: 0.592s std dev: 0.02176s window: 5
average rate: 1.799
	min: 0.533s max: 0.592s std dev: 0.01909s window: 7
average rate: 1.819
	min: 0.530s max: 0.592s std dev: 0.01962s window: 9
average rate: 1.828
	min: 0.530s max: 0.592s std dev: 0.01852s window: 11
average rate: 1.831
	min: 0.530s max: 0.592s std dev: 0.01784s window: 12
average rate: 1.836
	min: 0.530s max: 0.592s std dev: 0.01677s window: 14
^Cno new messages
kfupm@kfupm-desktop:~$ rostopic hz /camera/color/image_raw
subscribed to [/camera/color/image_raw]
average rate: 22.171
	min: 0.015s max: 0.433s std dev: 0.10369s window: 16
average rate: 17.792
	min: 0.015s max: 0.433s std dev: 0.12101s window: 33
average rate: 16.772
	min: 0.015s max: 0.433s std dev: 0.12571s window: 50
average rate: 15.021
	min: 0.015s max: 0.435s std dev: 0.13444s window: 60
average rate: 16.010
	min: 0.015s max: 0.448s std dev: 0.12967s window: 75
average rate: 15.746
	min: 0.015s max: 0.500s std dev: 0.13204s window: 93
average rate: 15.287
	min: 0.015s max: 0.500s std dev: 0.13422s window: 107
^C
average rate: 15.603
	min: 0.015s max: 0.500s std dev: 0.13260s window: 110
`

**the main issue is that the /camera/aligned_depth_to_color/image_raw publisheds with low rate 1.8 hz  ** and please notice  /camera/depth/image_rect_raw published with 30 hz .
This issue appears when i use Jetson nano and all work fine when i use my laptop 

The second issue is that the IMU topic give me y-diraction to ground instead of z or neg-z 

`linear_acceleration: 
  x: 0.00724035618121
  y: -8.98433915158
  z: 2.00167468906
linear_acc`

**Comment by MartyG-RealSense** [comment]
Hi @Majed-Alsubaie  You have defined **infra_fps** in the roslaunch instruction but not infra_height and infra_width.  The missing height and width definitions could cause the custom configuration to be identified as invalid, and the default configuration of the particular camera model being used to be applied instead.

Also, the infra topics need to be enabled as they are disabled by default.  They can be enabled with **infra1_enabled:=true infra2_enabled:=true**

Please try the roslaunch instruction below.

**roslaunch realsense2_camera rs_camera.launch align_depth:=true enable_gyro:=true enable_accel:=true unite_imu_method:="linear_interpolation" color_width:=1280 color_height:=720 color_fps:=15 infra1_enabled:=true infra2_enabled:=true infra_fps:=15 depth_width:=848 depth_height:=480 depth_fps:=15 initial_reset:=true**

**Comment by Majed-Alsubaie** [comment]
Hello @MartyG-RealSense ,
The issue is not related to the Infra topics.
Actually i am not looking for  Infra topics and i include **infra_fps:=15**  by mistake.
Still the **/camera/aligned_depth_to_color/image_raw** published with low rate (2 hz ) where the expected rate 15 hz


Thanks

**Comment by Majed-Alsubaie** [comment]
` roslaunch realsense2_camera rs_camera.launch align_depth:=true  color_width:=1280 color_height:=720 color_fps:=15 depth_width:=848 depth_height:=480 depth_fps:=15 initial_reset:=true
`
LED TO  :

**rostopic hz /camera/aligned_depth_to_color/image_raw = 
average rate: 5.147
	min: 0.042s max: 0.636s std dev: 0.04236s window: 691**

**rostopic hz /camera/color/image_raw =
average rate: 13.833
	min: 0.014s max: 0.172s std dev: 0.07426s window: 12

**


**rostopic hz /camera/depth/image_rect_raw =
average rate: 6.693
	min: 0.001s max: 0.221s std dev: 0.07990s window: 59

**

**Comment by MartyG-RealSense** [comment]
Alignment is a processing-intensive operation, so the capabilities of your computer / computing device may have a bearing on performance.  

Next, could you try disabling in ROS an option called **Auto-Exposure Priority** please.  If Auto-Exposure is enabled and the RGB option **Auto-Exposure Priority** is disabled then it should force the FPS to be maintained at a constant rate.  For example, if depth and color have both been set to 15 FPS then both streams should be forced to run at 15 FPS instead of the FPS rate varying.

https://github.com/IntelRealSense/realsense-ros/issues/1349#issuecomment-681695259

**Comment by Majed-Alsubaie** [comment]
@MartyG-RealSense ,Thanks
I think the problem related to the POWER. because Jetson Nano's USB is not providing enough power .
And I solved it by using Powered-USB hub [https://www.amazon.com/gp/product/B00DQFGH80/ref=ewc_pr_img_4?smid=ATVPDKIKX0DER&th=1](url).
However, i notice sometime the camera instead of taking the power from USB-Hub , it absorbed the power from Jetson Nano  port.
So any idea how to force camera to use USB-HUB's power ?

and yes please can you  comment on the second issue where the IMU topic consider the Y-direction to the ground/down

**Comment by MartyG-RealSense** [comment]
I have not heard of a device being able to draw power from a port other than the one that it is connected to.  I researched the subject and it suggested that if a powered hub's mains power is turned off or cut off then a device may be able to continue on the computer power if it is not a high power-drawing device such as an external hard disk drive or recordable dvd drive.  

I do not know of any (easy) method to fix that if the electricity supply to the powered hub is inactive.  Conceivably if there was an issue with the stability of the local mains electricity supply then you could add an Uninterruptible Power Supply (UPS) pack to your computer system that instantly kicks in to provide power when the mains power fails.  It may not be worth the expense though unless a problem with the local power supply is confirmed and it is critically important that power is not drawn from the Jetson.

The Y-accel IMU value is not related to z-distance (depth).  It is a measurement of downward acceleration under the force of the Earth's gravity.

**Comment by MartyG-RealSense** [comment]
Hi @Majed-Alsubaie  Do you require further assistance with this case, please?  Thanks!

**Comment by Majed-Alsubaie** [comment]
Hi @MartyG-RealSense ,,Thanks and sorry for responding late.
I did disable  Auto-Exposure Priority and enable Auto-Exposure , still i got  :
`rostopic hz /camera/depth/image_rect_raw
subscribed to [/camera/depth/image_rect_raw]
	min: 0.001s max: 0.528s std dev: 0.12417s window: 141
average rate: 27.254
	min: 0.001s max: 0.528s std dev: 0.12394s window: 171
average rate: 27.381
	min: 0.001s max: 0.528s std dev: 0.12387s window: 201
`
For /camera/color/image_raw , i got it with 15fps but depth not yet

**Comment by MartyG-RealSense** [comment]
If you are still using **align_depth:=true** are you able to acheve 15 FPS for both if you remove align_depth:=true from the roslaunch instruction?

**Comment by Majed-Alsubaie** [comment]
@MartyG-RealSense .
i have just tried ,,,Yes i am able to achieve constant 15 FPS when i disable **align_depth:=true **

**Comment by Majed-Alsubaie** [comment]
For Alignment , In  Realsense-Viewer ,I Believe GPU is used so it works fine
But In ROS wrapper is not , so  Alignment processing done using CPU with low FPS
How can i make ROS wrapper used GPU ,(Build  it with CUDA) ?
I am using Jetson Nano , **OpenCv 4.5.1  | compile cuda YES**

**Comment by MartyG-RealSense** [comment]
**Doronhi** the RealSense ROS wrapper developer comments about CUDA in ROS in the link below.  

https://github.com/IntelRealSense/realsense-ros/issues/1177#issuecomment-674291080

My understanding of that discussion is that Doronhi advises that the RealSense ROS Debian packages do not include CUDA support.  CUDA support can instead be built in librealsense using **-DBUILD_WITH_CUDA=true**, as mentioned in the instructions on Intel's Jetson installation page.

https://github.com/IntelRealSense/librealsense/blob/master/doc/installation_jetson.md

**********

The link below is the case of a Jetson user who achieved 30 FPS when using align_depth:=true if they disabled auto-exposure and set a manual exposure within a certain range.

https://github.com/IntelRealSense/realsense-ros/issues/1357

Disabling auto-exposure and setting a manual exposure value within a certain range is a known alternative to the FPS enforcemement method of enabled auto-exposure and disabled auto-exposure priority.  The maths of selecting an exposure value are described by a RealSense team member in the link below.

https://github.com/IntelRealSense/librealsense/issues/1957#issuecomment-400715579

**Comment by Majed-Alsubaie** [comment]
Hi, Thanks @MartyG-RealSense 
i have a good news after succeed  on building ROS wrapper with CUDA. All my issues disappeared
I think All jetson's users should install  ROS wrapper with CUDA.
Thank you again 
+I would  like to suggest  using ENU convention with IMU in ROS wrapper.

**Comment by MartyG-RealSense** [comment]
That is excellent news @Majed-Alsubaie - thanks very much for the update and your suggestions for Jetson users  :)
