### ISSUE TITLE
[QUESTION] Load config from realsense viewer

### ISSUE THREAD

**Issue by RGring** [realsenseai/realsense-ros#1919]
In the realsense viewer, I can save the settings in a *json file. Is it possible to load these settings to the ros node?
If not, what is the best way to set default values for the settings in dynamic_reconfigure? When I set it in them in the ros-param server, these parameters disappear in the dynamic reconfigure.

Thanks in advance!

**Comment by MartyG-RealSense** [comment]
Hi @RGring   Once you have created a json file, you can load it in ROS using a **json_file_path** instruction in the roslaunch instruction or within the launch file.  Some examples are provided below.

**roslaunch (provide an absolute file path to the json)**
`roslaunch realsense2_camera rs_camera.launch json_file_path:=/path/to/config/DefaultPreset_viewer.json`

**launch file parameter**
`<arg name="json_file_path"      default="/custom.json"/>`

**Comment by MartyG-RealSense** [comment]
Hi @RGring  Do you require further assistance with this case, please?  Thanks!
