### ISSUE TITLE
roslaunch error

### ISSUE THREAD

**Issue by Y-pandaman** [realsenseai/realsense-ros#1922]
hello, when I run `roslaunch realsense2_camera rs_camera.launch `, it showed that error, I use ubuntu 18.04, and I did not change something.

`SUMMARY
========

PARAMETERS
 * /camera/realsense2_camera/accel_fps: -1
 * /camera/realsense2_camera/accel_frame_id: camera_accel_frame
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: False
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/allow_no_texture_points: False
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/calib_odom_file: 
 * /camera/realsense2_camera/clip_distance: -2.0
 * /camera/realsense2_camera/color_fps: -1
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: -1
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: -1
 * /camera/realsense2_camera/confidence_fps: -1
 * /camera/realsense2_camera/confidence_height: -1
 * /camera/realsense2_camera/confidence_width: -1
 * /camera/realsense2_camera/depth_fps: -1
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: -1
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: -1
 * /camera/realsense2_camera/device_type: 
 * /camera/realsense2_camera/enable_accel: False
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_confidence: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye1: False
 * /camera/realsense2_camera/enable_fisheye2: False
 * /camera/realsense2_camera/enable_fisheye: False
 * /camera/realsense2_camera/enable_gyro: False
 * /camera/realsense2_camera/enable_infra1: False
 * /camera/realsense2_camera/enable_infra2: False
 * /camera/realsense2_camera/enable_infra: False
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_pose: False
 * /camera/realsense2_camera/enable_sync: False
 * /camera/realsense2_camera/filters: 
 * /camera/realsense2_camera/fisheye1_frame_id: camera_fisheye1_f...
 * /camera/realsense2_camera/fisheye1_optical_frame_id: camera_fisheye1_o...
 * /camera/realsense2_camera/fisheye2_frame_id: camera_fisheye2_f...
 * /camera/realsense2_camera/fisheye2_optical_frame_id: camera_fisheye2_o...
 * /camera/realsense2_camera/fisheye_fps: -1
 * /camera/realsense2_camera/fisheye_frame_id: camera_fisheye_frame
 * /camera/realsense2_camera/fisheye_height: -1
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: -1
 * /camera/realsense2_camera/gyro_fps: -1
 * /camera/realsense2_camera/gyro_frame_id: camera_gyro_frame
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/imu_optical_frame_id: camera_imu_optica...
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra_fps: 30
 * /camera/realsense2_camera/infra_height: 480
 * /camera/realsense2_camera/infra_rgb: False
 * /camera/realsense2_camera/infra_width: 848
 * /camera/realsense2_camera/initial_reset: False
 * /camera/realsense2_camera/json_file_path: 
 * /camera/realsense2_camera/linear_accel_cov: 0.01
 * /camera/realsense2_camera/odom_frame_id: camera_odom_frame
 * /camera/realsense2_camera/ordered_pc: False
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/pose_frame_id: camera_pose_frame
 * /camera/realsense2_camera/pose_optical_frame_id: camera_pose_optic...
 * /camera/realsense2_camera/publish_odom_tf: True
 * /camera/realsense2_camera/publish_tf: True
 * /camera/realsense2_camera/rosbag_filename: 
 * /camera/realsense2_camera/serial_no: 
 * /camera/realsense2_camera/stereo_module/exposure/1: 7500
 * /camera/realsense2_camera/stereo_module/exposure/2: 1
 * /camera/realsense2_camera/stereo_module/gain/1: 16
 * /camera/realsense2_camera/stereo_module/gain/2: 16
 * /camera/realsense2_camera/tf_publish_rate: 0.0
 * /camera/realsense2_camera/topic_odom_in: odom_in
 * /camera/realsense2_camera/unite_imu_method: 
 * /camera/realsense2_camera/usb_port_id: 
 * /rosdistro: melodic
 * /rosversion: 1.14.11

NODES
  /camera/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)

auto-starting new master
process[master]: started with pid [4137]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to c54b3928-c81e-11eb-a7c2-7c2a31b60314
process[rosout-1]: started with pid [4155]
started core service [/rosout]
process[camera/realsense2_camera_manager-2]: started with pid [4162]
process[camera/realsense2_camera-3]: started with pid [4163]
[ INFO] [1623132005.775277888]: Initializing nodelet with 8 worker threads.
[ INFO] [1623132005.901916427]: RealSense ROS v2.3.0
[ INFO] [1623132005.901942109]: Built with LibRealSense v2.45.0
[ INFO] [1623132005.901952564]: Running with LibRealSense v2.45.0
[ INFO] [1623132005.934067788]:  
[ INFO] [1623132006.164352077]: Device with serial number 912112070774 was found.

[ INFO] [1623132006.164423835]: Device with physical ID 2-1-16 was found.
[ INFO] [1623132006.164455347]: Device with name Intel RealSense D435I was found.
[ INFO] [1623132006.165242835]: Device with port number 2-1 was found.
[ INFO] [1623132006.165301185]: Device USB type: 3.2
[ INFO] [1623132006.168306974]: getParameters...
[ INFO] [1623132006.239857805]: setupDevice...
[ INFO] [1623132006.239880961]: JSON file is not provided
[ INFO] [1623132006.239890751]: ROS Node Namespace: camera
[ INFO] [1623132006.239908516]: Device Name: Intel RealSense D435I
[ INFO] [1623132006.239927455]: Device Serial No: 912112070774
[ INFO] [1623132006.239945638]: Device physical port: 2-1-16
[ INFO] [1623132006.239963878]: Device FW version: 05.12.14.50
[ INFO] [1623132006.239982823]: Device Product ID: 0x0B3A
[ INFO] [1623132006.240002863]: Enable PointCloud: Off
[ INFO] [1623132006.240021241]: Align Depth: Off
[ INFO] [1623132006.240040983]: Sync Mode: Off
[ INFO] [1623132006.240089532]: Device Sensors: 
[ INFO] [1623132006.254918091]: Stereo Module was found.
[ INFO] [1623132006.263328713]: RGB Camera was found.
[ INFO] [1623132006.263645521]: Motion Module was found.
[ INFO] [1623132006.263715950]: (Confidence, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1623132006.263758708]: num_filters: 0
[ INFO] [1623132006.263775310]: Setting Dynamic reconfig parameters.
/opt/ros/melodic/lib/nodelet/nodelet: symbol lookup error: /home/wty/d435_ws/devel/lib//librealsense2_camera.so: undefined symbol: _ZN20ddynamic_reconfigure19DDynamicReconfigureC1ERKN3ros10NodeHandleE
[camera/realsense2_camera_manager-2] process has died [pid 4162, exit code 127, cmd /opt/ros/melodic/lib/nodelet/nodelet manager __name:=realsense2_camera_manager __log:=/home/wty/.ros/log/c54b3928-c81e-11eb-a7c2-7c2a31b60314/camera-realsense2_camera_manager-2.log].
log file: /home/wty/.ros/log/c54b3928-c81e-11eb-a7c2-7c2a31b60314/camera-realsense2_camera_manager-2*.log
[camera/realsense2_camera-3] process has finished cleanly
log file: /home/wty/.ros/log/c54b3928-c81e-11eb-a7c2-7c2a31b60314/camera-realsense2_camera-3*.log
`

**Comment by MartyG-RealSense** [comment]
Hi @Y-pandaman   In a discussion about the symbol error involving **_ZN20ddynamic_reconfigure1** it is advised that it may be caused by having more than one instance of **ddynamic_reconfigure** installed on your computer.

https://github.com/IntelRealSense/realsense-ros/issues/838

https://github.com/IntelRealSense/realsense-ros/issues/838#issuecomment-508970423

**Comment by MartyG-RealSense** [comment]
Hi @Y-pandaman  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
