### ISSUE TITLE
Initializing nodelet with 4 worker threads.

### ISSUE THREAD

**Issue by sazzath** [realsenseai/realsense-ros#1928]
![image](https://user-images.githubusercontent.com/72601348/121790457-d82e7180-cbdf-11eb-8ed0-089706704fea.png)

Anyone can help me belongs to this Error !!! 

Best Regards 
Sazzath Hossain 
Phobne +352661315657

**Comment by MartyG-RealSense** [comment]
Hi @sazzath  Could you provide information about the questions below please?

-  What computer / computing device are you using please?   (PC, Raspberry Pi, Jetson, etc).  
-   Which RealSense camera model are you using?  
-   Which RealSense SDK (librealsense) version and RealSense ROS wrapper version are you using?

It would be very useful if you could post the text of a roslaunch log into a comment,  Thanks!

**Comment by MartyG-RealSense** [comment]
Hi @sazzath  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
