### ISSUE TITLE
エラーについて

### ISSUE THREAD

**Issue by mayo233** [realsenseai/realsense-ros#1935]
[ WARN] [1623998395.256886791]: Given stream configuration is not supported by the device!  Stream: Depth, Stream Index: 0, Width: -1, Height: -1, FPS: -1
[ WARN] [1623998395.260388435]: Given stream configuration is not supported by the device!  Stream: Color, Stream Index: 0, Width: -1, Height: -1, FPS: -1
[ INFO] [1623998395.260723471]: num_filters: 0
[ INFO] [1623998395.260761839]: SELECTED BASE:Depth, 0
 roslaunch realsense2_camera rs_camera.launchと立ち上げると上のようなエラーが表示されてリアルセンスの接続が切れます。この場合、どうしたら良いでしょうか

**Comment by MartyG-RealSense** [comment]
Translation from Japanese: "When you start up, the above error is displayed and the RealSense connection is disconnected.  What should I do in this case?"

Hello @mayo233  It is unusual that this error happened.  The launch process should have automatically used the default stream configuration of the particular RealSense camera model that you own.  Please try using the roslaunch instruction below to see if it works.

**roslaunch realsense2_camera rs_camera.launch depth_width:=640 depth_height:=480 depth_fps:=30**

**************

こんにちは@ mayo233このエラーが発生したのは珍しいことです。 起動プロセスでは、所有している特定のRealSenseカメラモデルのデフォルトのストリーム構成が自動的に使用されているはずです。 以下のroslaunch命令を使用して、機能するかどうかを確認してください。

**roslaunch realsense2_camera rs_camera.launch depth_width:=640 depth_height:=480 depth_fps:=30**

**Comment by mayo233** [comment]
[camera/realsense2_camera_manager-1] process has died [pid 17746, exit code 127, cmd /opt/ros/melodic/lib/nodelet/nodelet manager __name:=realsense2_camera_manager __log:=/home/suzukamayo/.ros/log/fb6f53f0-d006-11eb-9c9c-c0b6f9c7d913/camera-realsense2_camera_manager-1.log].
log file: /home/suzukamayo/.ros/log/fb6f53f0-d006-11eb-9c9c-c0b6f9c7d913/camera-realsense2_camera_manager-1*.log

**Comment by mayo233** [comment]
[camera/realsense2_camera_manager-1] process has died [pid 17746, exit code 127, cmd /opt/ros/melodic/lib/nodelet/nodelet manager __name:=realsense2_camera_manager __log:=/home/suzukamayo/.ros/log/fb6f53f0-d006-11eb-9c9c-c0b6f9c7d913/camera-realsense2_camera_manager-1.log].
log file: /home/suzukamayo/.ros/log/fb6f53f0-d006-11eb-9c9c-c0b6f9c7d913/camera-realsense2_camera_manager-1*.log
ddynamic_reconfigureをzip関数で落としてcatkin_makeをした結果、上のようなエラーが表示されるようになりました。どうしたらよいでしょうか

**Comment by MartyG-RealSense** [comment]
I will handle the above question at https://github.com/IntelRealSense/realsense-ros/issues/1936

***********

上記の質問は https://github.com/IntelRealSense/realsense-ros/issues/1936 で処理します

**Comment by MartyG-RealSense** [comment]
Case closed due to question being handled at https://github.com/IntelRealSense/realsense-ros/issues/1936
