### ISSUE TITLE
エラーについて

### ISSUE THREAD

**Issue by mayo233** [realsenseai/realsense-ros#1936]
[camera/realsense2_camera_manager-1] process has died [pid 17746, exit code 127, cmd /opt/ros/melodic/lib/nodelet/nodelet manager __name:=realsense2_camera_manager __log:=/home/suzukamayo/.ros/log/fb6f53f0-d006-11eb-9c9c-c0b6f9c7d913/camera-realsense2_camera_manager-1.log].
log file: /home/suzukamayo/.ros/log/fb6f53f0-d006-11eb-9c9c-c0b6f9c7d913/camera-realsense2_camera_manager-1*.log
ddynamic_reconfigureをzip関数で落としてcatkin_makeをした結果、上のようなエラーが表示されるようになりました。どうしたらよいでしょうか

**Comment by mayo233** [comment]
Setting Dynamic reconfig parameters.
/opt/ros/melodic/lib/nodelet/nodelet: symbol lookup error: /home/suzukamayo/ros_ws/lidar/whill_ws/devel/lib//librealsense2_camera.so: undefined symbol: _ZN20ddynamic_reconfigure19DDynamicReconfigureC1ERKN3ros10NodeHandleE
と表示されます

**Comment by MartyG-RealSense** [comment]
"As a result of dropping ddynamic_reconfigure with the zip function and doing catkin_make, the above error is displayed.  What should I do?"

If you are having problems with installing ddynamic_reconfigure for Melodic, could you try to install it using the instruction below please?

**sudo apt-get update apt-get install ros-melodic-ddynamic-reconfigure**

******************

Melodicのddynamic_reconfigureのインストールで問題が発生した場合は、以下の手順を使用してインストールしてみてください。

**sudo apt-get update apt-get install ros-melodic-ddynamic-reconfigure**

**Comment by MartyG-RealSense** [comment]
Regarding this error:

**undefined symbol: _ZN20ddynamic_reconfigure**

It can indicate that more than one installation of ddynamic_reconfigure is on your computer.

https://github.com/IntelRealSense/realsense-ros/issues/838

![image](https://user-images.githubusercontent.com/41145062/122564501-54d8aa00-d03d-11eb-82a1-58c4a7e418fd.png)

*****************

このエラーについて：

**undefined symbol: _ZN20ddynamic_reconfigure**

これは、ddynamic_reconfigureの複数のインストールがコンピューターにあることを示している可能性があります。

https://github.com/IntelRealSense/realsense-ros/issues/838

**Comment by MartyG-RealSense** [comment]
Hello, do you require further assistance with this problem please?  Thank you!

こんにちは、この問題についてさらにサポートが必要ですか？ ありがとうございました！

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.

コメントがないため、ケースはクローズされました。
