### ISSUE TITLE
intel430i

### ISSUE THREAD

**Issue by yaley302** [realsenseai/realsense-ros#1941]
hello,
 current realsense2_camera do not support camera types for intel430i.How do i solve the problem?

**Comment by MartyG-RealSense** [comment]
Hi @yaley302  Cases involving **D430i** are highly rare, with it only having appeared on RealSense forums a few times when the RGB sensor of a D435i model was not being detected.   

Can you confirm if you have a D435i like the camera in the image below please?

![image](https://user-images.githubusercontent.com/41145062/122772645-7df87500-d29f-11eb-9be8-b5746ccfd248.png)

**Comment by yaley302** [comment]
I have a D435i like the camera.Unsupported device! Product ID:0x0B4B

**Comment by doronhi** [comment]
If you have a D435i that identifies as a D430i, it is likely that the connector to the RGB unit inside is disconnected. I think you can validate by running `rs-enumerate-devices` and see that no Color streams are available. 
Consult @RealSenseSupport as to how to proceed.

**Comment by MartyG-RealSense** [comment]
Thanks very much @doronhi 

@yaley302  The advice of @doronhi is correct that the RGB sensor may become undetectable to the firmware due to a detached internal cable.  

In the very small number of past cases where a D435 has been recognized as a D430, downgrading the firmware driver to an older version and then re-upgrading it fixed the issue in a couple of cases where it was not the internal RGB cable that was responsible.  If an internal cable detachment was responsible though then updating the firmware would have no effect.

**Comment by MartyG-RealSense** [comment]
Hi @yaley302  Do you have an update that you can provide about this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.

**Comment by fiorano10** [comment]
This is not really a solution, is there way to get the wrapper to recognize the D430 device and throw an error only if color stream is being enabled?

**Comment by MartyG-RealSense** [comment]
The presence or absence of a color sensor could be checked using code like the highlighted Python scripting at the link below.

https://github.com/IntelRealSense/librealsense/blob/master/wrappers/python/examples/opencv_pointcloud_viewer.py#L73-L80

You could also check for a specific camera name using **RS2_INFO_CAMERA_NAME** like in the C++ script at https://github.com/IntelRealSense/librealsense/issues/2219#issuecomment-412899468 that checks whether the camera name is D415 and does not allow the program to run if the attached camera is not a D415.

**Comment by xiaomengfang** [comment]
Is there a version of ROS wrapper support D430i?

**Comment by MartyG-RealSense** [comment]
Hi @fangxiaomeng0830   No, D430i is just a way to identify a D435i camera when there is a problem with detecting its RGB sensor.  It is not a proper RealSense camera model.

In the ROS wrapper, a workaround for an absent RGB sensor would be to use infrared as a texture instead of the RGB image.
