### ISSUE TITLE
Kernel support 5.8.0

### ISSUE THREAD

**Issue by padhupradheep** [realsenseai/realsense-ros#1946]
Hey I see that the current kernel support is uptil 5.4, are there any plans for new releases which supports kernels such as 5.8?

**Comment by MartyG-RealSense** [comment]
Hi @padhupradheep  Kernel 5.8 support was added in librealsense version **2.47.0**, the latest version at the time of writing this.

![image](https://user-images.githubusercontent.com/41145062/123127204-f5fea080-d441-11eb-9f56-4eb42755a7f6.png)

![image](https://user-images.githubusercontent.com/41145062/123127358-1cbcd700-d442-11eb-9da1-d93c4fbf1846.png)

**Comment by padhupradheep** [comment]
Thanks!
