### ISSUE TITLE
Frame rate drop when recording rosbag (D455)

### ISSUE THREAD

**Issue by ghost** [realsenseai/realsense-ros#1947]
I'm seeing a huge frame rate drop when recording RGBD images from D455 (with `rosbag record -a`).

When I start the recording, rate drops from 30fps to less than 15fps with lag and jumps.

When I stop recording framerate goes up again.

Here the launch parameters:

    <include file="$(find realsense2_camera)/launch/rs_camera.launch">
        <arg name="align_depth" value="true"/>
        <arg name="linear_accel_cov" value="1.0"/>
        <arg name="enable_pointcloud"  value="false"/>
    </include>

**Comment by MartyG-RealSense** [comment]
Hi @guglielmodev  What computer or computing device are you using, please (PC, Nvidia Jetson, Raspberry Pi, etc).  Thanks!

**Comment by MartyG-RealSense** [comment]
Hi @guglielmodev  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.

**Comment by ghost** [comment]
Sorry @MartyG-RealSense , I missed the notification for your reply.

I'm using an Ubuntu PC. When I record only RGB and depth the issue disappears.

**Comment by MartyG-RealSense** [comment]
No problem at all @guglielmodev - thanks very much for the update. 

As you are using **rosbag record -a** to record all currently active topics, which other topics apart from RGB and depth do you have enabled that cause the lag that is not present when only depth and RGB are published, please?

**Comment by ghost** [comment]
Thank you @MartyG-RealSense 

With `rosbag record -a` the camera has lot of lagging and framerate goes below 15hz, when I stop recording it recovers. Also the exposure starts to oscillate and make the image glow in violet colors.

The recorded topics are the ones enabled by the above launch file:

```
/camera/align_to_color/parameter_descriptions
/camera/align_to_color/parameter_updates
/camera/aligned_depth_to_color/camera_info
/camera/aligned_depth_to_color/image_raw
/camera/aligned_depth_to_color/image_raw/compressed
/camera/aligned_depth_to_color/image_raw/compressed/parameter_descriptions
/camera/aligned_depth_to_color/image_raw/compressed/parameter_updates
/camera/aligned_depth_to_color/image_raw/compressedDepth
/camera/aligned_depth_to_color/image_raw/compressedDepth/parameter_descriptions
/camera/aligned_depth_to_color/image_raw/compressedDepth/parameter_updates
/camera/color/camera_info
/camera/color/image_raw
/camera/depth/camera_info
/camera/depth/image_rect_raw
/camera/extrinsics/depth_to_color
/camera/motion_module/parameter_descriptions
/camera/motion_module/parameter_updates
/camera/realsense2_camera_manager/bond
/camera/rgb_camera/auto_exposure_roi/parameter_descriptions
/camera/rgb_camera/auto_exposure_roi/parameter_updates
/camera/rgb_camera/parameter_descriptions
/camera/rgb_camera/parameter_updates
/camera/stereo_module/auto_exposure_roi/parameter_descriptions
/camera/stereo_module/auto_exposure_roi/parameter_updates
/camera/stereo_module/parameter_descriptions
/camera/stereo_module/parameter_updates
```

I'm sure the trigger is recording these and not /tf or other topics because the issue appears also if I subscribe to this list

```
rosbag record  /camera/aligned_depth_to_color/image_raw /camera/stereo_module/auto_exposure_roi/parameter_updates \
/camera/aligned_depth_to_color/image_raw/compressedDepth /camera/rgb_camera/parameter_updates /camera/aligned_depth_to_color/image_raw/compressed/parameter_descriptions \
 /camera/depth/image_rect_raw /camera/realsense2_camera_manager/bond /camera/depth/camera_info /camera/stereo_module/parameter_descriptions /camera/color/image_raw \
/camera/extrinsics/depth_to_color /camera/rgb_camera/auto_exposure_roi/parameter_updates /camera/stereo_module/parameter_updates /camera/aligned_depth_to_color/image_raw \
/compressedDepth/parameter_updates /camera/motion_module/parameter_descriptions /camera/rgb_camera/auto_exposure_roi/parameter_descriptions /camera/color/camera_info /camera \
/motion_module/parameter_updates /camera/aligned_depth_to_color/camera_info /camera/aligned_depth_to_color/image_raw/compressed/parameter_updates /camera/rgb_camera \
/parameter_descriptions /camera/align_to_color/parameter_updates /camera/stereo_module/auto_exposure_roi/parameter_descriptions /camera/aligned_depth_to_color/image_raw/compressed \
/camera/aligned_depth_to_color/image_raw/compressedDepth/parameter_descriptions /camera/align_to_color/parameter_descriptions
```

**Comment by MartyG-RealSense** [comment]
How does it perform if you trim down the list of recorded topics, such as removing all the **aligned and compressed image** topics except /camera/aligned_depth_to_color/camera_info and /camera/aligned_depth_to_color/image_raw

![image](https://user-images.githubusercontent.com/41145062/124623622-08ca9980-de74-11eb-80e8-09a9cf249e12.png)
