### ISSUE TITLE
 Hardware Notification:Motion Module failure,1.62506e+12,Error,Hardware Error

### ISSUE THREAD

**Issue by zheng-xiao** [realsenseai/realsense-ros#1960]
Hi
I have a problem about the hardware.
There is the issue:

roslaunch realsense2_camera rs_camera.launch initial_reset:=true
... logging to /home/zxn/.ros/log/ae0c2040-d978-11eb-8185-08beac02483f/roslaunch-zxn-pc-9410.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://zxn-pc:36211/

SUMMARY
========

PARAMETERS
 * /camera/realsense2_camera/accel_fps: -1
 * /camera/realsense2_camera/accel_frame_id: camera_accel_frame
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: False
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/allow_no_texture_points: False
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/calib_odom_file: 
 * /camera/realsense2_camera/clip_distance: -2.0
 * /camera/realsense2_camera/color_fps: -1
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: -1
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: -1
 * /camera/realsense2_camera/confidence_fps: -1
 * /camera/realsense2_camera/confidence_height: -1
 * /camera/realsense2_camera/confidence_width: -1
 * /camera/realsense2_camera/depth_fps: -1
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: -1
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: -1
 * /camera/realsense2_camera/device_type: 
 * /camera/realsense2_camera/enable_accel: True
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_confidence: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye1: False
 * /camera/realsense2_camera/enable_fisheye2: False
 * /camera/realsense2_camera/enable_fisheye: False
 * /camera/realsense2_camera/enable_gyro: True
 * /camera/realsense2_camera/enable_infra1: True
 * /camera/realsense2_camera/enable_infra2: True
 * /camera/realsense2_camera/enable_infra: True
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_pose: False
 * /camera/realsense2_camera/enable_sync: True
 * /camera/realsense2_camera/filters: 
 * /camera/realsense2_camera/fisheye1_frame_id: camera_fisheye1_f...
 * /camera/realsense2_camera/fisheye1_optical_frame_id: camera_fisheye1_o...
 * /camera/realsense2_camera/fisheye2_frame_id: camera_fisheye2_f...
 * /camera/realsense2_camera/fisheye2_optical_frame_id: camera_fisheye2_o...
 * /camera/realsense2_camera/fisheye_fps: -1
 * /camera/realsense2_camera/fisheye_frame_id: camera_fisheye_frame
 * /camera/realsense2_camera/fisheye_height: -1
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: -1
 * /camera/realsense2_camera/gyro_fps: -1
 * /camera/realsense2_camera/gyro_frame_id: camera_gyro_frame
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/imu_optical_frame_id: camera_imu_optica...
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra_fps: 30
 * /camera/realsense2_camera/infra_height: 480
 * /camera/realsense2_camera/infra_rgb: False
 * /camera/realsense2_camera/infra_width: 848
 * /camera/realsense2_camera/initial_reset: True
 * /camera/realsense2_camera/json_file_path: 
 * /camera/realsense2_camera/linear_accel_cov: 0.01
 * /camera/realsense2_camera/odom_frame_id: camera_odom_frame
 * /camera/realsense2_camera/ordered_pc: False
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/pose_frame_id: camera_pose_frame
 * /camera/realsense2_camera/pose_optical_frame_id: camera_pose_optic...
 * /camera/realsense2_camera/publish_odom_tf: True
 * /camera/realsense2_camera/publish_tf: True
 * /camera/realsense2_camera/rosbag_filename: 
 * /camera/realsense2_camera/serial_no: 
 * /camera/realsense2_camera/stereo_module/exposure/1: 7500
 * /camera/realsense2_camera/stereo_module/exposure/2: 1
 * /camera/realsense2_camera/stereo_module/gain/1: 16
 * /camera/realsense2_camera/stereo_module/gain/2: 16
 * /camera/realsense2_camera/tf_publish_rate: 0.0
 * /camera/realsense2_camera/topic_odom_in: odom_in
 * /camera/realsense2_camera/unite_imu_method: copy
 * /camera/realsense2_camera/usb_port_id: 
 * /rosdistro: melodic
 * /rosversion: 1.14.10

NODES
  /camera/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)

ROS_MASTER_URI=http://localhost:11311

process[camera/realsense2_camera_manager-1]: started with pid [9425]
process[camera/realsense2_camera-2]: started with pid [9426]
[ INFO] [1625060299.179914353]: Initializing nodelet with 16 worker threads.
[ INFO] [1625060299.210315646]: RealSense ROS v2.3.0
[ INFO] [1625060299.210341433]: Built with LibRealSense v2.45.0
[ INFO] [1625060299.210354682]: Running with LibRealSense v2.45.0
[ INFO] [1625060299.232353855]:  
 30/06 21:38:19,342 WARNING [140208441120512] (messenger-libusb.cpp:42) control_transfer returned error, index: 300, error: No data available, number: 3d
[ INFO] [1625060299.525646276]: Device with serial number 046322251510 was found.

[ INFO] [1625060299.525735410]: Device with physical ID 2-5-9 was found.
[ INFO] [1625060299.525778082]: Device with name Intel RealSense D455 was found.
[ INFO] [1625060299.527146812]: Device with port number 2-5 was found.
[ INFO] [1625060299.527226731]: Device USB type: 3.2
[ INFO] [1625060299.527287173]: Resetting device...
[ INFO] [1625060305.549368097]:  
[ INFO] [1625060305.696931472]: Device with serial number 046322251510 was found.

[ INFO] [1625060305.696956153]: Device with physical ID 2-5-10 was found.
[ INFO] [1625060305.696965407]: Device with name Intel RealSense D455 was found.
[ INFO] [1625060305.697126780]: Device with port number 2-5 was found.
[ INFO] [1625060305.697139397]: Device USB type: 3.2
[ INFO] [1625060305.698168723]: getParameters...
[ INFO] [1625060305.720550292]: setupDevice...
[ INFO] [1625060305.720565673]: JSON file is not provided
[ INFO] [1625060305.720575295]: ROS Node Namespace: camera
[ INFO] [1625060305.720584690]: Device Name: Intel RealSense D455
[ INFO] [1625060305.720593041]: Device Serial No: 046322251510
[ INFO] [1625060305.720601440]: Device physical port: 2-5-10
[ INFO] [1625060305.720611124]: Device FW version: 05.12.14.50
[ INFO] [1625060305.720620632]: Device Product ID: 0x0B5C
[ INFO] [1625060305.720629287]: Enable PointCloud: Off
[ INFO] [1625060305.720637616]: Align Depth: Off
[ INFO] [1625060305.720645717]: Sync Mode: On
[ INFO] [1625060305.720671559]: Device Sensors: 
[ INFO] [1625060305.737743207]: Stereo Module was found.
[ INFO] [1625060305.745364075]: RGB Camera was found.
[ INFO] [1625060305.745536669]: Motion Module was found.
[ INFO] [1625060305.745560046]: (Confidence, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1625060305.745576789]: num_filters: 0
[ INFO] [1625060305.745589514]: Setting Dynamic reconfig parameters.
 30/06 21:38:26,045 WARNING [140207890343680] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 30/06 21:38:26,109 WARNING [140207890343680] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 30/06 21:38:26,172 WARNING [140207890343680] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
[ WARN] [1625060306.310539903]: Param '/camera/stereo_module/auto_exposure_limit' has value 0 that is not in range [1, 165000]. Removing this parameter from dynamic reconfigure options.
[ WARN] [1625060306.323166105]: Param '/camera/stereo_module/auto_gain_limit' has value 0 that is not in range [16, 248]. Removing this parameter from dynamic reconfigure options.
[ INFO] [1625060306.354625335]: Done Setting Dynamic reconfig parameters.
[ INFO] [1625060306.354937886]: depth stream is enabled - width: 848, height: 480, fps: 30, Format: Z16
[ WARN] [1625060306.355001181]: Given stream configuration is not supported by the device!  Stream: Infrared, Stream Index: 0, Width: 848, Height: 480, FPS: 30, Format: Y8
[ INFO] [1625060306.355146497]: infra1 stream is enabled - width: 848, height: 480, fps: 30, Format: Y8
[ INFO] [1625060306.355294470]: infra2 stream is enabled - width: 848, height: 480, fps: 30, Format: Y8
[ INFO] [1625060306.355970913]: color stream is enabled - width: 1280, height: 720, fps: 30, Format: RGB8
[ INFO] [1625060306.355987987]: gyro stream is enabled - fps: 200
[ INFO] [1625060306.355997910]: accel stream is enabled - fps: 63
[ INFO] [1625060306.356008338]: setupPublishers...
[ INFO] [1625060306.357097625]: Expected frequency for depth = 30.00000
[ INFO] [1625060306.408809325]: Expected frequency for infra1 = 30.00000
[ INFO] [1625060306.416850065]: Expected frequency for infra2 = 30.00000
[ INFO] [1625060306.424859607]: Expected frequency for color = 30.00000
[ INFO] [1625060306.432907181]: Start publisher IMU
[ INFO] [1625060306.433749831]: setupStreams...
[ INFO] [1625060306.465491959]: insert Depth to Stereo Module
[ INFO] [1625060306.465517612]: insert Color to RGB Camera
[ INFO] [1625060306.465527300]: insert Infrared to Stereo Module
[ INFO] [1625060306.465536836]: insert Infrared to Stereo Module
[ INFO] [1625060306.465546501]: insert Gyro to Motion Module
[ INFO] [1625060306.465554789]: insert Accel to Motion Module
[ WARN] [1625060306.478714861]: 
[ WARN] [1625060306.478757761]: frame's time domain is HARDWARE_CLOCK. Timestamps may reset periodically.
 30/06 21:38:26,476 WARNING [140208466298624] (ds5-motion.cpp:473) IMU Calibration is not available, default intrinsic and extrinsic will be used.
 30/06 21:38:26,509 WARNING [140207890343680] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 30/06 21:38:26,559 WARNING [140207890343680] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 30/06 21:38:26,609 WARNING [140207890343680] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
[ INFO] [1625060306.660707606]: SELECTED BASE:Depth, 0
[ INFO] [1625060306.692552579]: RealSense Node Is Up!
 30/06 21:38:26,737 WARNING [140207890343680] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 30/06 21:38:26,787 WARNING [140207890343680] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 30/06 21:38:26,939 WARNING [140207890343680] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 30/06 21:38:26,989 WARNING [140207890343680] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 30/06 21:38:27,049 WARNING [140207890343680] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 30/06 21:38:27,101 WARNING [140207890343680] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 30/06 21:38:27,151 WARNING [140207890343680] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 30/06 21:38:27,202 WARNING [140207890343680] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
[ WARN] [1625060307.355472326]: Hardware Notification:Motion Module failure,1.62506e+12,Error,Hardware Error

**Comment by MartyG-RealSense** [comment]
Hi @zheng-xiao  It looks as though you are enabling and publishing every stream type available (depth, color, infrared 1 & 2, gyro and accel).  This could place a burden on the USB system of the computer / computing device being used with the camera.

Which computer / computing device are you using, please (PC, Nvidia Jetson, Raspberry Pi, etc)

**Comment by MartyG-RealSense** [comment]
Hi @zheng-xiao  Do you require further assistance with this case, please?  Thanks!

**Comment by zheng-xiao** [comment]
Yes，
I don't solve it.
And I find another issue. When I record a rosbag, the topic called /camera/infra1/image_rect_raw will lose frame. If I play the rosbag, the image is not smooth.
If you can solve my issue, I will be verygrateful.
Thanks.
















At 2021-07-07 14:52:10, "MartyG-RealSense" ***@***.***> wrote:

Hi @zheng-xiao Do you require further assistance with this case, please? Thanks!

**Comment by MartyG-RealSense** [comment]
Which topics are you recording to a bag please?  Are you recording particular topics, or recording all currently available topics using **rosbag record -a** or **rosbag record --all** ?

**Comment by zheng-xiao** [comment]
Hi ，
Thank you for answering my question. I use three topics include /camera/infra1/image_rect_raw, /camera/infra2/image_rect_raw,/camera/imu. And I record the rosbag using rosbag record -a.
















At 2021-07-07 21:15:02, "MartyG-RealSense" ***@***.***> wrote:

Whic topics are you recording to a bag please? Are you recording particular topics, or recording all currently available topics using rosbag record -a or rosbag record --all ?

**Comment by MartyG-RealSense** [comment]
Could you try limiting the rosbag record command to these three specific topics instead of using the '--all' command please to see whether it improves performance?

**rosbag record /camera/infra1/image_rect_raw /camera/infra2/image_rect_raw /camera/imu**

**Comment by zheng-xiao** [comment]
Hi,
Thanks. I solve it.
















At 2021-07-08 01:44:56, "MartyG-RealSense" ***@***.***> wrote:

Could you try limiting the rosbag record command to these three specific topics instead of using the '--all' command please to see whether it improves performance?

rosbag record /camera/infra1/image_rect_raw /camera/infra2/image_rect_raw /camera/imu

**Comment by MartyG-RealSense** [comment]
Great news @zheng-xiao that you found a solution - thanks for the update!

**Comment by MartyG-RealSense** [comment]
Case closed due to solution achieved and no further comments received.
