### ISSUE TITLE
ORB-SLAM3 Mono_Inertial mode does not work properly with RealSense D455 for image and IMU data acquisition

### ISSUE THREAD

**Issue by liangchen97** [realsenseai/realsense-ros#1969]
Mono_Inertial mode does not work properly with RealSense D455 for image and IMU data acquisition

I made sure that I had ORB-SLAM3 installed correctly and that the Euroc dataset was running properly.Now I need to use RealSense D455 to run ORB-SLAM3's MONO mode and MONO_INERTIAL mode
We calibrate the D455 camera parameters, modify the topic in the code, and edit the YAML file

%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
Camera.type: "PinHole"

# Camera calibration and distortion parameters (OpenCV) 
Camera.fx: 638.1018216271331
Camera.fy: 638.3300728549654
Camera.cx: 629.4728680757129
Camera.cy: 375.5517788016263

Camera.k1: -0.05529716280253562
Camera.k2: 0.04869113994652115
Camera.p1: -0.0012081319997317495
Camera.p2: 0.000948771411746312

Camera.width: 1280
Camera.height: 720 

# Camera frames per second 
Camera.fps: 20.0

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1000

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#---------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500

I can run Mono mode as normal.So I also calibrated the IMU foreign parameters using kalibr and edited the YAML file as follows:

%YAML:1.0

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
Camera.type: "PinHole"

# Camera calibration and distortion parameters (OpenCV) 
Camera.fx: 638.1018216271331
Camera.fy: 638.3300728549654
Camera.cx: 629.4728680757129
Camera.cy: 375.5517788016263

Camera.k1: -0.05529716280253562
Camera.k2: 0.04869113994652115
Camera.p1: -0.0012081319997317495
Camera.p2: 0.000948771411746312

# Camera resolution
Camera.width: 1280
Camera.height: 720 

# Camera frames per second 
Camera.fps: 20.0

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Transformation from camera to body-frame (imu)
Tbc: !!opencv-matrix
   rows: 4
   cols: 4
   dt: f
   data: [0.99999368, -0.00211361, -0.00285705, 0.02947189,
         0.00208701, 0.99995474, -0.00928254, -0.00822922,
         0.00287654, 0.00927652, 0.99995283, 0.02332212,
         0.0, 0.0, 0.0, 1.0]

# IMU noise
IMU.NoiseGyro: 0.00201078376608 #1.6968e-04 
IMU.NoiseAcc: 0.0170676352326 #2.0e-3
IMU.GyroWalk: 1.33363959029e-05 
IMU.AccWalk: 0.000377325109439 # 3e-03
IMU.Frequency: 200

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1000 # 1000

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1
Viewer.GraphLineWidth: 0.9
Viewer.PointSize:2
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3
Viewer.ViewpointX: 0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -3.5 # -1.8
Viewer.ViewpointF: 500

The command line results are as follows:

nvidia@nvidia-desktop:~/catkin_ws/src/ORB_SLAM3$ rosrun ORB_SLAM3 Mono_Inertial /home/nvidia/catkin_ws/src/ORB_SLAM3/Vocabulary/ORBvoc.txt  /home/nvidia/catkin_ws/src/ORB_SLAM3/Examples/Monocular-Inertial/d455.yaml

ORB-SLAM3 Copyright (C) 2017-2020 Carlos Campos, Richard Elvira, Juan J. Gómez, José M.M. Montiel and Juan D. Tardós, University of Zaragoza.
ORB-SLAM2 Copyright (C) 2014-2016 Raúl Mur-Artal, José M.M. Montiel and Juan D. Tardós, University of Zaragoza.
This program comes with ABSOLUTELY NO WARRANTY;
This is free software, and you are welcome to redistribute it
under certain conditions. See LICENSE.txt.

Input sensor was set to: Monocular-Inertial

Loading ORB Vocabulary. This could take a while...
Vocabulary loaded!

Creation of new map with id: 0
Creation of new map with last KF id: 0
Seq. Name: 

Camera Parameters: 
- Camera: Pinhole
- fx: 638.102
- fy: 638.33
- cx: 629.473
- cy: 375.552
- k1: -0.0552972
- k2: 0.0486911
- p1: -0.00120813
- p2: 0.000948771
- fps: 20
- color order: RGB (ignored if grayscale)

ORB Extractor Parameters: 
- Number of Features: 1000
- Scale Levels: 8
- Scale Factor: 1.2
- Initial Fast Threshold: 20
- Minimum Fast Threshold: 7

Left camera to Imu Transform (Tbc): 
[0.99999368, -0.0020870101, -0.0028765399, 0.029521611;
 0.00211361, 0.99995476, -0.0092765205, -0.0080747996;
 0.0028570499, 0.0092825396, 0.99995285, 0.0233132;
 0, 0, 0, 1]

IMU frequency: 200 Hz
IMU gyro noise: 0.00201078 rad/s/sqrt(Hz)
IMU gyro walk: 1.33364e-05 rad/s^2/sqrt(Hz)
IMU accelerometer noise: 0.0170676 m/s^2/sqrt(Hz)
IMU accelerometer walk: 0.000377325 m/s^3/sqrt(Hz)

-------------------------------------
First KF:0; Map init KF:0
New Map created with 101 points
Point distribution in KeyFrame: left-> 101 --- right-> 0
build optimization graph
start optimization
end optimization
IMU in Map 0 is initialized
RESETING FRAME!!!
Fail to track local map!
IMU is not or recently initialized. Reseting active map...
SYSTEM-> Reseting active map in monocular case
LM: Active map reset recieved
LM: Active map reset, waiting...
LM: Reseting current map in Local Mapping...
LM: End reseting Local Mapping...
LM: Reset free the mutex
LM: Active map reset, Done!!!
mnFirstFrameId = 101
mnInitialFrameId = 0
23 Frames set to lost
First KF:13; Map init KF:0
New Map created with 89 points
Point distribution in KeyFrame: left-> 89 --- right-> 0
build optimization graph
start optimization
end optimization
IMU in Map 0 is initialized
Fail to track local map!
IMU is not or recently initialized. Reseting active map...
SYSTEM-> Reseting active map in monocular case
LM: Active map reset recieved
LM: Active map reset, waiting...
LM: Reseting current map in Local Mapping...
LM: End reseting Local Mapping...
LM: Reset free the mutex
LM: Active map reset, Done!!!
mnFirstFrameId = 180
mnInitialFrameId = 123
43 Frames set to lost
First KF:24; Map init KF:13
New Map created with 101 points
Point distribution in KeyFrame: left-> 101 --- right-> 0
build optimization graph
start optimization
end optimization
IMU in Map 0 is initialized
Fail to track local map!
IMU is not or recently initialized. Reseting active map...
SYSTEM-> Reseting active map in monocular case
LM: Active map reset recieved
LM: Active map reset, waiting...
LM: Reseting current map in Local Mapping...
LM: End reseting Local Mapping...
LM: Reset free the mutex
LM: Active map reset, Done!!!
mnFirstFrameId = 222
mnInitialFrameId = 199
67 Frames set to lost
First KF:35; Map init KF:24
New Map created with 77 points
Point distribution in KeyFrame: left-> 77 --- right-> 0
Fail to track local map!
IMU is not or recently initialized. Reseting active map...
SYSTEM-> Reseting active map in monocular case
LM: Active map reset recieved
LM: Active map reset, waiting...
LM: Reseting current map in Local Mapping...
LM: End reseting Local Mapping...
LM: Reset free the mutex
LM: Active map reset, Done!!!
mnFirstFrameId = 250
mnInitialFrameId = 245
69 Frames set to lost

It seems that ORB-SLAM3 has been unable to detect feature points and occasionally initializes soon after detecting and calculating the path, thus losing the result
![cam+imu](https://user-images.githubusercontent.com/55865784/124437853-1287ca80-ddaa-11eb-8e5e-dd01aeb22bb5.png)

**Comment by MartyG-RealSense** [comment]
Hi @liangchen97  There are very few references for using ORB-SLAM3 with a D455 at the time of writing this.  There was a case in the link below where a RealSense D455 user extracted feature points using **Monocular + IMU** data.

https://github.com/IntelRealSense/librealsense/issues/8899

**Comment by liangchen97** [comment]
I have seen this, my external parameters are calibrated with Kalibr, can be sure that there is no problem, I do not know if the author of this problem successfully run Mono + IMU

**Comment by MartyG-RealSense** [comment]
As mentioned, there are a limited number of other references about using ORB-SLAM3 with RealSense.   I translated an article on the subject into English (though it involves D435i rather than D455) and have attached the PDF to this message.

[ORB-SLAM3_RealSense.pdf](https://github.com/IntelRealSense/realsense-ros/files/6765571/ORB-SLAM3_RealSense.pdf)

An ORB-SLAM3 RealSense discussion about Mono-Inertial (again using D435i) is also at the link below.

https://github.com/UZ-SLAMLab/ORB_SLAM3/issues/67

This one is about the RealSense T265 Tracking Camera but discusses causes of feature loss:

https://github.com/UZ-SLAMLab/ORB_SLAM3/issues/28

Hopefully one of these resources will provide some useful insights about obtaining feature points.

**Comment by MartyG-RealSense** [comment]
Hi @liangchen97  Do you require further assistance with this case, please?  Thanks!

**Comment by liangchen97** [comment]
No thanks. I will update if there is new progress

**Comment by MartyG-RealSense** [comment]
Okay, thanks very much.  I will close the case but you are welcome to leave further comments or start a new issue when you make progress.  Good luck!
