### ISSUE TITLE
RealSense D455 Depth Image issue

### ISSUE THREAD

**Issue by swiz23** [realsenseai/realsense-ros#1971]
Hi, I'm working wiith a RealSense D455 camera on Ubuntu 18.04.5 with ROS Melodic. I'm using tag 2.2.20 with librealsense 2.40.

When subscribing to the /camera/depth/image_rect_raw topic, I get depth images similar to the one below.

![Screenshot from 2021-07-08 00-48-46](https://user-images.githubusercontent.com/31753673/124864186-7bc43500-df86-11eb-81d4-80427f8b096c.png)

![Screenshot from 2021-07-08 00-48-17](https://user-images.githubusercontent.com/31753673/124864637-453aea00-df87-11eb-9512-7e3f0d85056a.png)

![Screenshot from 2021-07-08 00-47-39](https://user-images.githubusercontent.com/31753673/124864700-600d5e80-df87-11eb-8419-5acacb810851.png)

The issue is that there appears to be a lot of white dots specifically on a narrow vertical strip along the left-hand side of the image. No matter where I point the camera, those dots (more or less of them) are there. Why is that happening? To clarify, I'm not pointing the camera at anything too close which might cause issues.

**Comment by MartyG-RealSense** [comment]
Hi @swiz23   As a starting point in investigating your case, could you test whether the dot pattern from the IR emitter is leaking nto the depth image please?

A way to do this would be:

1.  Open the dynamic_reconfigure interface by inputting the line below into the ROS terminal after the roslaunch completes: 

**rosrun rqt_reconfigure rqt_reconfigure**

dynamic_reconfigure is available in the ROS wrapper (Kinetic, Melodic, Noetic) and enables the changing of camera values during runtime.

2.  Select the **stereo_module** category in the side-panel of the dynamic-reconfigure interface.

![image](https://user-images.githubusercontent.com/41145062/124919995-c4afd400-dfee-11eb-85da-765dc7a27b76.png)

3.  In the stereo_module options, find the **laser_power** option and reduce its value.  

Does the visibility of the dots at the side of the image reduce as the laser_power value is reduced?

**Comment by swiz23** [comment]
Tried that, and it actually gets worse as you go down - granted I don't have the best lighting in my apartment though so that's kind of expected.

**Comment by MartyG-RealSense** [comment]
It is expected that depth image quality decreases as Laser Power is reduced.  The purpose of the test was to determine whether the white dots became less visible as the Laser Power value was decreased.   Do the dots noticably change as Laser Power reduces, please?

**Comment by swiz23** [comment]
No, they do not become less visible as I decrease the laser power.

Something else to note is that the left-hand side of the depth image appears jagged while on the right side - it's a nice vertical 'line'. I've included an image below without normalizing - just for contrast purposes.

![Screenshot from 2021-07-08 11-34-15](https://user-images.githubusercontent.com/31753673/124950704-a6db7280-dfe0-11eb-83e4-872b55a37ee5.png)

**Comment by MartyG-RealSense** [comment]
It is normal for the far-left edge of the depth image to be jagged to some extent and sometimes have some noise within it.  This area is called the **Invalid Depth Band**.  Pages 68-69 of the current edition of the data sheet document for the 400 Series cameras have information about this phenomenon.

https://dev.intelrealsense.com/docs/intel-realsense-d400-series-product-family-datasheet

![image](https://user-images.githubusercontent.com/41145062/124956754-35b3b380-e010-11eb-9057-1ebe19b28d07.png)

**Comment by swiz23** [comment]
So I don't have to worry about the white dots on the left-hand side since it's inside the invalid depth band region?

**Comment by MartyG-RealSense** [comment]
Whilst it may look a little untidy when there is visible noise inside that far-left border area beyond the jagged edge, it is a region of no depth data and so shouldn't have an impact on the depth results within the main image.
