### ISSUE TITLE
How can I get information equal to realsense-viewer?

### ISSUE THREAD

**Issue by Ryoga723** [realsenseai/realsense-ros#1972]
Hello.

I would like to use rgb image and depth information to complete my task in ROS.
Now I get rgb information which is published as /camera/color/image_raw and depth information which is published as /camera/aligned_depth_to_color/image_raw by below command.

roslaunch realsense2_camera rs_rgbd.launch align_depth:=true

But then, I think information in realsense-viewer is more accutate than this information.
How can I use information in realsense-viewer in ROS?

Thank you for your helping.

**Comment by MartyG-RealSense** [comment]
Hi @Ryoga723  Live camera data that is being streamed in the RealSense Viewer tool cannot be accessed by the RealSense ROS wrapper.    

You may be able to achieve a configuration that is closer to that of the Viewer by exporting a **json** camera configuration file from the Viewer using the json export button near the top of the Viewer's options side-panel and then loading that json file into the ROS wrapper during launch.

![image](https://user-images.githubusercontent.com/41145062/124899315-e5206400-dfd7-11eb-864a-73f6fac174e7.png)
