### ISSUE TITLE
Realsense D435, Pointcloud2 does not have any colour in Realsense viewer

### ISSUE THREAD

**Issue by vanerkz** [realsenseai/realsense-ros#1978]
<img width="960" alt="rs1" src="https://user-images.githubusercontent.com/84112168/125251219-a9640200-e329-11eb-8a66-86b7455978a5.png">

<img width="960" alt="rs2" src="https://user-images.githubusercontent.com/84112168/125251505-f7790580-e329-11eb-8355-d58425264504.png">

Hi, I have the problem shown above. Pointcloud2 does not have any colour, it is fully grey. I have tried different methods to solve the problem above but yet I still have the same problem. Both depth and RGB is working as shown above. 

anyone encounter this problem before ? Thank you !

**Comment by MartyG-RealSense** [comment]
Hi @vanerkz  The 3D image in your Viewer does not look like a typical **textured pointcloud** where the RGB image is mapped to the depth points.   It resembles a mis-colored depth only cloud.

Could you try disabling the two **GLSL** settings in the Viewer's settings interface if they are enabled please, using the instructions in the link below to do so, and see whether it makes a positive difference to the point cloud in 3D mode? 

https://github.com/IntelRealSense/librealsense/issues/8110#issuecomment-754705023

**Comment by vanerkz** [comment]
Hi, I have disable both GLSL setting. However, I still have the same problem.

**Comment by MartyG-RealSense** [comment]
Does the point cloud update correctly if you go to the **Texture** option at the top of the Viewer window and toggle between the depth and color settings?

![image](https://user-images.githubusercontent.com/41145062/125263465-f4b2ec00-e2fa-11eb-9688-fe85b3ef852b.png)

Also, may I confirm that you are not using the RealSense ROS wrapper at the same time that you are using the Viewer?  The Viewer and the ROS wrapper are not designed to be used together simultaneously.

**Comment by vanerkz** [comment]
<img width="960" alt="rs4" src="https://user-images.githubusercontent.com/84112168/125266004-f3ec7b00-e337-11eb-8b74-745195b61e4d.png">
<img width="960" alt="rs5" src="https://user-images.githubusercontent.com/84112168/125266009-f51da800-e337-11eb-9d6a-b4e17a0d379d.png">

I have tried to toggle between the texture option. It does change between the options. 
I did not use ROS wrapper at the same time. However, I also faced the same problem when I uses ROS wrapper. It does not show any pointcloud2 in rivz.

**Comment by MartyG-RealSense** [comment]
If you are pointing the camera at the curtains during your toggle test, it still does not look as though it is displaying the RGB detail correctly when selecting the Color option.

in regard to ROS, are you using **roslaunch realsense2_camera rs_camera.launch filters:=pointcloud** as your roslaunch instruction like in the ROS wrapper's pointcloud example in the link below?

roslaunch realsense2_camera rs_camera.launch filters:=pointcloud

**Comment by vanerkz** [comment]
The below are the output
SUMMARY
========

PARAMETERS
 * /camera/realsense2_camera/accel_fps: -1
 * /camera/realsense2_camera/accel_frame_id: camera_accel_frame
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: False
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/allow_no_texture_points: False
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/calib_odom_file: 
 * /camera/realsense2_camera/clip_distance: -2.0
 * /camera/realsense2_camera/color_fps: -1
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: -1
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: -1
 * /camera/realsense2_camera/confidence_fps: -1
 * /camera/realsense2_camera/confidence_height: -1
 * /camera/realsense2_camera/confidence_width: -1
 * /camera/realsense2_camera/depth_fps: -1
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: -1
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: -1
 * /camera/realsense2_camera/device_type: 
 * /camera/realsense2_camera/enable_accel: False
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_confidence: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye1: False
 * /camera/realsense2_camera/enable_fisheye2: False
 * /camera/realsense2_camera/enable_fisheye: False
 * /camera/realsense2_camera/enable_gyro: False
 * /camera/realsense2_camera/enable_infra1: False
 * /camera/realsense2_camera/enable_infra2: False
 * /camera/realsense2_camera/enable_infra: False
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_pose: False
 * /camera/realsense2_camera/enable_sync: False
 * /camera/realsense2_camera/filters: pointcloud
 * /camera/realsense2_camera/fisheye1_frame_id: camera_fisheye1_f...
 * /camera/realsense2_camera/fisheye1_optical_frame_id: camera_fisheye1_o...
 * /camera/realsense2_camera/fisheye2_frame_id: camera_fisheye2_f...
 * /camera/realsense2_camera/fisheye2_optical_frame_id: camera_fisheye2_o...
 * /camera/realsense2_camera/fisheye_fps: -1
 * /camera/realsense2_camera/fisheye_frame_id: camera_fisheye_frame
 * /camera/realsense2_camera/fisheye_height: -1
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: -1
 * /camera/realsense2_camera/gyro_fps: -1
 * /camera/realsense2_camera/gyro_frame_id: camera_gyro_frame
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/imu_optical_frame_id: camera_imu_optica...
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra_fps: -1
 * /camera/realsense2_camera/infra_height: -1
 * /camera/realsense2_camera/infra_rgb: False
 * /camera/realsense2_camera/infra_width: -1
 * /camera/realsense2_camera/initial_reset: False
 * /camera/realsense2_camera/json_file_path: 
 * /camera/realsense2_camera/linear_accel_cov: 0.01
 * /camera/realsense2_camera/odom_frame_id: camera_odom_frame
 * /camera/realsense2_camera/ordered_pc: False
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/pose_frame_id: camera_pose_frame
 * /camera/realsense2_camera/pose_optical_frame_id: camera_pose_optic...
 * /camera/realsense2_camera/publish_odom_tf: True
 * /camera/realsense2_camera/publish_tf: True
 * /camera/realsense2_camera/rosbag_filename: 
 * /camera/realsense2_camera/serial_no: 
 * /camera/realsense2_camera/tf_publish_rate: 0.0
 * /camera/realsense2_camera/topic_odom_in: odom_in
 * /camera/realsense2_camera/unite_imu_method: 
 * /camera/realsense2_camera/usb_port_id: 
 * /rosdistro: melodic
 * /rosversion: 1.14.10

NODES
  /camera/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)

auto-starting new master
process[master]: started with pid [4007]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to f8799d5a-e2f7-11eb-8bbd-0024d7098ccc
process[rosout-1]: started with pid [4018]
started core service [/rosout]
process[camera/realsense2_camera_manager-2]: started with pid [4025]
process[camera/realsense2_camera-3]: started with pid [4026]
[ INFO] [1626084023.658222022]: Initializing nodelet with 4 worker threads.
[ INFO] [1626084023.909166014]: RealSense ROS v2.3.0
[ INFO] [1626084023.909219683]: Built with LibRealSense v2.45.0
[ INFO] [1626084023.909261616]: Running with LibRealSense v2.45.0
[ INFO] [1626084023.938588656]:  
[ INFO] [1626084023.966850564]: Device with serial number 909512071631 was found.

[ INFO] [1626084023.966964900]: Device with physical ID /sys/devices/pci0000:00/0000:00:1c.3/0000:0c:00.0/usb4/4-1/4-1:1.0/video4linux/video2 was found.
[ INFO] [1626084023.967035289]: Device with name Intel RealSense D435 was found.
[ INFO] [1626084023.968055441]: Device with port number 4-1 was found.
[ INFO] [1626084023.968168786]: Device USB type: 3.2
[ INFO] [1626084023.972147348]: getParameters...
[ INFO] [1626084024.037186112]: setupDevice...
[ INFO] [1626084024.037258016]: JSON file is not provided
[ INFO] [1626084024.037321412]: ROS Node Namespace: camera
[ INFO] [1626084024.037353414]: Device Name: Intel RealSense D435
[ INFO] [1626084024.037380100]: Device Serial No: 909512071631
[ INFO] [1626084024.037423173]: Device physical port: /sys/devices/pci0000:00/0000:00:1c.3/0000:0c:00.0/usb4/4-1/4-1:1.0/video4linux/video2
[ INFO] [1626084024.037456978]: Device FW version: 05.12.14.50
[ INFO] [1626084024.037485244]: Device Product ID: 0x0B07
[ INFO] [1626084024.037512563]: Enable PointCloud: On
[ INFO] [1626084024.037538494]: Align Depth: Off
[ INFO] [1626084024.037563344]: Sync Mode: On
[ INFO] [1626084024.037628013]: Device Sensors: 
[ INFO] [1626084024.043376995]: Stereo Module was found.
[ INFO] [1626084024.052497892]: RGB Camera was found.
[ INFO] [1626084024.052583144]: (Confidence, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1626084024.052735998]: Add Filter: pointcloud
[ INFO] [1626084024.053370608]: num_filters: 1
[ INFO] [1626084024.053414316]: Setting Dynamic reconfig parameters.
[ WARN] [1626084024.143063700]: Param '/camera/stereo_module/auto_exposure_limit' has value 0 that is not in range [1, 165000]. Removing this parameter from dynamic reconfigure options.
[ WARN] [1626084024.145404539]: Param '/camera/stereo_module/auto_gain_limit' has value 0 that is not in range [16, 248]. Removing this parameter from dynamic reconfigure options.
[ INFO] [1626084024.181720215]: Done Setting Dynamic reconfig parameters.
[ INFO] [1626084024.182881406]: depth stream is enabled - width: 848, height: 480, fps: 30, Format: Z16
[ INFO] [1626084024.184090015]: color stream is enabled - width: 640, height: 480, fps: 30, Format: RGB8
[ INFO] [1626084024.184194439]: setupPublishers...
[ INFO] [1626084024.190743844]: Expected frequency for depth = 30.00000
[ INFO] [1626084024.228344343]: Expected frequency for color = 30.00000
[ INFO] [1626084024.248694676]: setupStreams...
[ INFO] [1626084024.251835471]: insert Depth to Stereo Module
[ INFO] [1626084024.251915671]: insert Color to RGB Camera
[ INFO] [1626084024.272747010]: SELECTED BASE:Depth, 0
[ INFO] [1626084024.288344672]: RealSense Node Is Up!
[ WARN] [1626084024.394158319]:

**Comment by vanerkz** [comment]
If I run realsense2_camera rs_d435_camera_with_model.launch. I cant see any pointcloud2 in rivz. 

robot@robot:~$ roslaunch realsense2_camera rs_d435_camera_with_model.launch 
... logging to /home/robot/.ros/log/34080a00-e2f8-11eb-8bbd-0024d7098ccc/roslaunch-robot-4223.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
WARNING: disk usage in log directory [/home/robot/.ros/log] is over 1GB.
It's recommended that you use the 'rosclean' command.

xacro: in-order processing became default in ROS Melodic. You can drop the option.
started roslaunch server http://localhost:46353/

SUMMARY
========

PARAMETERS
 * /camera/realsense2_camera/accel_fps: 250
 * /camera/realsense2_camera/accel_frame_id: camera_accel_frame
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: False
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/allow_no_texture_points: False
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/calib_odom_file: 
 * /camera/realsense2_camera/clip_distance: -2.0
 * /camera/realsense2_camera/color_fps: 30
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: 480
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: 640
 * /camera/realsense2_camera/confidence_fps: 30
 * /camera/realsense2_camera/confidence_height: 480
 * /camera/realsense2_camera/confidence_width: 640
 * /camera/realsense2_camera/depth_fps: 30
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: 240
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: 424
 * /camera/realsense2_camera/device_type: 
 * /camera/realsense2_camera/enable_accel: False
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_confidence: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye1: False
 * /camera/realsense2_camera/enable_fisheye2: False
 * /camera/realsense2_camera/enable_fisheye: False
 * /camera/realsense2_camera/enable_gyro: False
 * /camera/realsense2_camera/enable_infra1: False
 * /camera/realsense2_camera/enable_infra2: False
 * /camera/realsense2_camera/enable_infra: True
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_pose: False
 * /camera/realsense2_camera/enable_sync: False
 * /camera/realsense2_camera/filters: pointcloud
 * /camera/realsense2_camera/fisheye1_frame_id: camera_fisheye1_f...
 * /camera/realsense2_camera/fisheye1_optical_frame_id: camera_fisheye1_o...
 * /camera/realsense2_camera/fisheye2_frame_id: camera_fisheye2_f...
 * /camera/realsense2_camera/fisheye2_optical_frame_id: camera_fisheye2_o...
 * /camera/realsense2_camera/fisheye_fps: 30
 * /camera/realsense2_camera/fisheye_frame_id: camera_fisheye_frame
 * /camera/realsense2_camera/fisheye_height: 480
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: 640
 * /camera/realsense2_camera/gyro_fps: 400
 * /camera/realsense2_camera/gyro_frame_id: camera_gyro_frame
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/imu_optical_frame_id: camera_imu_optica...
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra_fps: 30
 * /camera/realsense2_camera/infra_height: 480
 * /camera/realsense2_camera/infra_rgb: True
 * /camera/realsense2_camera/infra_width: 640
 * /camera/realsense2_camera/initial_reset: False
 * /camera/realsense2_camera/json_file_path: 
 * /camera/realsense2_camera/linear_accel_cov: 0.01
 * /camera/realsense2_camera/odom_frame_id: camera_odom_frame
 * /camera/realsense2_camera/ordered_pc: False
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/pose_frame_id: camera_pose_frame
 * /camera/realsense2_camera/pose_optical_frame_id: camera_pose_optic...
 * /camera/realsense2_camera/publish_odom_tf: False
 * /camera/realsense2_camera/publish_tf: True
 * /camera/realsense2_camera/rosbag_filename: 
 * /camera/realsense2_camera/serial_no: 
 * /camera/realsense2_camera/tf_publish_rate: 0.0
 * /camera/realsense2_camera/topic_odom_in: odom_in
 * /camera/realsense2_camera/unite_imu_method: 
 * /camera/realsense2_camera/usb_port_id: 
 * /robot_description: <?xml version="1....
 * /rosdistro: melodic
 * /rosversion: 1.14.10

NODES
  /
    robot_state_publisher (robot_state_publisher/robot_state_publisher)
    rviz (rviz/rviz)
  /camera/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)

auto-starting new master
process[master]: started with pid [4246]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 34080a00-e2f8-11eb-8bbd-0024d7098ccc
process[rosout-1]: started with pid [4263]
started core service [/rosout]
process[camera/realsense2_camera_manager-2]: started with pid [4270]
process[camera/realsense2_camera-3]: started with pid [4271]
process[robot_state_publisher-4]: started with pid [4276]
process[rviz-5]: started with pid [4278]
[ INFO] [1626084124.007029091]: Initializing nodelet with 4 worker threads.
[ INFO] [1626084124.266352823]: RealSense ROS v2.3.0
[ INFO] [1626084124.266403387]: Built with LibRealSense v2.45.0
[ INFO] [1626084124.266458125]: Running with LibRealSense v2.45.0
[ INFO] [1626084124.294847593]:  
[ INFO] [1626084124.319827407]: Device with serial number 909512071631 was found.

[ INFO] [1626084124.319907997]: Device with physical ID /sys/devices/pci0000:00/0000:00:1c.3/0000:0c:00.0/usb4/4-1/4-1:1.0/video4linux/video2 was found.
[ INFO] [1626084124.320015408]: Device with name Intel RealSense D435 was found.
[ INFO] [1626084124.320445755]: Device with port number 4-1 was found.
[ INFO] [1626084124.320486973]: Device USB type: 3.2
[ INFO] [1626084124.321898509]: getParameters...
[ INFO] [1626084124.322498474]: Infrared RGB stream enabled
[ INFO] [1626084124.375986121]: setupDevice...
[ INFO] [1626084124.376036355]: JSON file is not provided
[ INFO] [1626084124.376059774]: ROS Node Namespace: camera
[ INFO] [1626084124.376084638]: Device Name: Intel RealSense D435
[ INFO] [1626084124.376114812]: Device Serial No: 909512071631
[ INFO] [1626084124.376169226]: Device physical port: /sys/devices/pci0000:00/0000:00:1c.3/0000:0c:00.0/usb4/4-1/4-1:1.0/video4linux/video2
[ INFO] [1626084124.376214232]: Device FW version: 05.12.14.50
[ INFO] [1626084124.376256304]: Device Product ID: 0x0B07
[ INFO] [1626084124.376288961]: Enable PointCloud: On
[ INFO] [1626084124.376375485]: Align Depth: Off
[ INFO] [1626084124.376400862]: Sync Mode: On
[ INFO] [1626084124.376469632]: Device Sensors: 
[ INFO] [1626084124.381110919]: Stereo Module was found.
[ INFO] [1626084124.388773905]: RGB Camera was found.
[ INFO] [1626084124.388871894]: (Infrared, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1626084124.388905624]: (Confidence, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1626084124.389063735]: Add Filter: pointcloud
[ INFO] [1626084124.389738825]: num_filters: 1
[ INFO] [1626084124.389786066]: Setting Dynamic reconfig parameters.
[ WARN] [1626084124.458867475]: Param '/camera/stereo_module/auto_exposure_limit' has value 0 that is not in range [1, 165000]. Removing this parameter from dynamic reconfigure options.
[ WARN] [1626084124.460777485]: Param '/camera/stereo_module/auto_gain_limit' has value 0 that is not in range [16, 248]. Removing this parameter from dynamic reconfigure options.
[ INFO] [1626084124.480285374]: Done Setting Dynamic reconfig parameters.
[ INFO] [1626084124.480695156]: depth stream is enabled - width: 424, height: 240, fps: 30, Format: Z16
[ INFO] [1626084124.481141335]: color stream is enabled - width: 640, height: 480, fps: 30, Format: RGB8
[ INFO] [1626084124.481184816]: setupPublishers...
[ INFO] [1626084124.484863116]: Expected frequency for depth = 30.00000
[ INFO] [1626084124.512936888]: Expected frequency for color = 30.00000
[ INFO] [1626084124.531511673]: setupStreams...
[ INFO] [1626084124.535434556]: insert Depth to Stereo Module
[ INFO] [1626084124.535516328]: insert Color to RGB Camera
[ INFO] [1626084124.553308427]: SELECTED BASE:Depth, 0
[ INFO] [1626084124.563054403]: RealSense Node Is Up!
[ERROR] [1626084124.582088042]: Ignoring transform for child_frame_id "camera_color_frame" from authority "unknown_publisher" because of an invalid quaternion in the transform (0.000000 -0.500000 0.000000 0.000000)
[ WARN] [1626084124.670303541]: 
[ INFO] [1626084125.199959831]: publishing unordered pointcloud.

**Comment by MartyG-RealSense** [comment]
The launch file **rs_d435_camera_with_model.launch** has not been updated for years.  If you are aiming to generate a point cloud in the RealSense ROS wrapper with a 400 Series camera (like your D435) then I would recommend using the **rs_camera** or **rs_rgbd** launch files that have been updated much more recently.

Could you post an image of your RViz screen please after having launched with **roslaunch realsense2_camera rs_camera.launch filters:=pointcloud**

**Comment by MartyG-RealSense** [comment]
Hi @vanerkz  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
