### ISSUE TITLE
Exception was thrown during user callback

### ISSUE THREAD

**Issue by nuyhead-hwang** [realsenseai/realsense-ros#1979]
Hello.

We are testing d-435i with autonomous drone.

In 'void BaseRealSenseNode::frame_callback' function, We added below line to check Laser status in EMITTER ON/OFF mode.

'int emitter_state = (int)frame.get_frame_metadata(RS2_FRAME_METADATA_FRAME_EMITTER_MODE)';

However, I got the runtime error 'ERROR [140615779022592] (source.cpp:130) Exception was thrown during user callback' .

Is there a way to check the laser status?  

thank you.

**Comment by MartyG-RealSense** [comment]
Hi @vislero   In the link below, **Doronhi** the RealSense ROS wrapper suggests a method (quoted below) to log the emitter status to a RealSense ROS user who was using emitter on-off.

https://github.com/IntelRealSense/realsense-ros/issues/1379#issuecomment-698104504

***************

There is currently no way to log emitter status using ROS.  You could do the following.  Add the following line inside the **publishFrame()** function:

```
auto projector_state = f.get_frame_metadata(RS2_FRAME_METADATA_FRAME_LASER_POWER_MODE);
ROS_INFO_STREAM("projector_state : " << projector_state);
```

****************

The publishFrame() function to place this additional line in is located within **base_realsense_node.cpp**:

https://github.com/IntelRealSense/realsense-ros/blob/de64e737c6a9de4ec70d89a18fe68b526c1460f5/realsense2_camera/src/base_realsense_node.cpp#L2170

**Comment by nuyhead-hwang** [comment]
Thank you for your kind reply.

We followed your instruction as figure below.

![Screenshot from 2021-07-12 20-13-20](https://user-images.githubusercontent.com/69630044/125278496-c9a5b800-e34d-11eb-9253-fbc240ac90a4.png)

And we got the same error.

By the way, we are testing on the configuration below.

librealsense : v.2.48.0
realsense-ros : v.2.3.0
device firmware : 05.12.14.50

And when we tested the older versions of librealsense (v.2.45.0) and realsense-ros, this error did not occur.

**Comment by MartyG-RealSense** [comment]
ROS wrapper 2.3.0 is designed for librealsense 2.45.0.  A wrapper should ideally be matched as closely as possible with the librealsense version listed on a particular wrapper version's release notes.  The ideal wrapper match for librealsense SDK 2.48.0 when using ROS1 is wrapper **2.3.1**. 

https://github.com/IntelRealSense/realsense-ros/releases/tag/2.3.1

If you wish to stay with 2.45.0 for now, wrapper 2.3.0 is the ideal match for it.

**Comment by nuyhead-hwang** [comment]
Thank you.

We updated the version of realsense-ros from 2.3.0 to 2.3.1.
Now the function is works !

However the message "An error has occurred during frame callback" is occur from below code.
https://github.com/IntelRealSense/realsense-ros/blob/09a263a311542b6521f0389490b6df4484b18191/realsense2_camera/src/base_realsense_node.cpp#L1760-L1763

is this normal?

**Comment by MartyG-RealSense** [comment]
At the beginning of this case you had added a line to the frame_callback function that was generating an error.  Did you remove that original line after adding the new code to the publishFrame() function please?

https://github.com/IntelRealSense/realsense-ros/issues/1979#issue-941819970

**Comment by nuyhead-hwang** [comment]
yes of course. 
the f.get_frame_metadata is only in the publishFrame function.

**Comment by MartyG-RealSense** [comment]
If you are using Ubuntu, which **kernel** version are you using, please?

**Comment by nuyhead-hwang** [comment]
I am using Ubuntu 18.04 (5.4.0-77-generic)

**Comment by MartyG-RealSense** [comment]
Thank you.  Is there any further information that accompanies the **An error has occurred during frame callback** message?  Here are the two most common examples of such messages from roslaunch logs in past cases.

******************

An error has occurred during frame callback: **Error occurred during execution of the processing block!**
An error has occurred during frame callback: **Time is out of dual 32-bit range**

*******************

Are you experiencing either of these messages, please?

**Doronhi** the RealSense ROS wrapper developer has previously said about the **processing block** type of message in another case: "From what I understand, the problem is that the filters don't keep up with the frames, due to computer load.  A new image cannot be pushed to the still full queue and therefore it is missing when the filter is called to process it.  Then the exception is issued".

**Comment by nuyhead-hwang** [comment]
I only get the error message "An error has occurred during frame callback:" like the picture below.

![Screenshot from 2021-07-15 17-46-38](https://user-images.githubusercontent.com/69630044/125758513-ddaa5770-3ae2-479a-891d-b929d98cdd53.png)

And, after updating realsense ros version 2.3.0 to 2.3.1, the image is published, but the error message is remained.
When i checked this problem in Jetson-nano-xavier using the same version of SDK and ROS wrapper, the result was same(same error message).

**Comment by MartyG-RealSense** [comment]
As the emitter status polling is working and the checkerboard image is apparently working too, I suspect that these messages are simply harmless timing hiccups where the hardware was not ready at the particular instant that the emitter was polled.  For example, an 'Asic Temperature value is not valid!' message is sometimes seen in RealSense ROS when the camera temperature is polled, followed by a normal temperature reading.

**Comment by MartyG-RealSense** [comment]
As the emitter status polling is working and the checkerboard image is apparently working too, I suspect that these messages are simply harmless timing hiccups where the sensor was not ready at the particular instant that it was polled.  For example, these kind of messages are sometimes seen in RealSense ROS when polling the camera temperature, resulting in an 'Asic Temperature value is not valid!' message, followed by a normal temperature reading.

**Comment by nuyhead-hwang** [comment]
Ok, I see.
Thank you so far.
