### ISSUE TITLE
How to get camera's projector/asic temperature using this package?

### ISSUE THREAD

**Issue by JoshuaSiy** [realsenseai/realsense-ros#1982]
Hello,
I would like to inquire if it is possible to obtain the camera's ASIC temperature using this package? I asked because I am unsure where to find the source code where pipelines and configurations are included.  I would also like to ask :: Given that this package is actively running, can we make another program(either in Python or C++)  to obtain the camera's projector/asic temperature?

**Comment by MartyG-RealSense** [comment]
Hi @JoshuaSiy   ASIC, Projector and Motion Module temperatures are published by the RealSense ROS wrapper's **/diagnostics** topic.  This feature was added in August 2019.

https://github.com/IntelRealSense/realsense-ros/releases/tag/2.2.8

**Comment by JoshuaSiy** [comment]
Oh, we just have to wait a few seconds for it to show up. Thank you very much.
