### ISSUE TITLE
Slam with l515 and t265?

### ISSUE THREAD

**Issue by aditdoshi333** [realsenseai/realsense-ros#1984]
Hello,

I am trying to use l515 with rtabmap_ros for the slam. I am happy with the map generation part but the odometry is not up to the mark. I am thinking to add t265 for better tracking but a bit confused as l515 is also with IMU. Will t265 improves the performance?

**Comment by RealSenseSupport** [comment]
@aditdoshi333 Do you still need support on this? Looking forward to your update. Thanks!

**Comment by RealSenseSupport** [comment]
@aditdoshi333 Could you please update? Please note that the ticket will be closed if we still don't get update from your side in another 7 days. Thanks!

**Comment by RealSenseSupport** [comment]
@aditdoshi333 Sorry that we didn't get update from you for weeks and this ticket will be closed at this point. Please feel free to create new ticket if you still have questions or issues. Thanks!
