### ISSUE TITLE
Using RealSense d435i IMU to improve Robot Odometry

### ISSUE THREAD

**Issue by BrooklynBoy21** [realsenseai/realsense-ros#1992]
I have a problem using imu from realsense d435i camera. I want to fuse IMU data with wheel odometry on a custom robot with **robot_localization**. 

The problem that IMU frame is not coincident with robot base_footprint. I mean axes rotated and this could cause the problem with localization. I will attach screenshot to help understand the problem.

![Screenshot from 2021-07-21 16-10-33](https://user-images.githubusercontent.com/43908482/126495053-ba677605-6ccc-45a4-afaa-d9ee268196fe.png)

**Comment by MartyG-RealSense** [comment]
Hi @BrooklynBoy21  Is the information in the link below helpful in answering your question, please?

https://answers.ros.org/question/326273/d435i-realsense-and-robot_localization/

**Comment by BrooklynBoy21** [comment]
Hi @MartyG-RealSense no(

**Comment by BrooklynBoy21** [comment]
I have tried set param odom_frame_id to my odometry frame, but it didn't help

**Comment by MartyG-RealSense** [comment]
There was a user of the RealSense T265 (which has the same IMU component as the D435i) that shared advice on how they linked up to robot_localization

https://github.com/IntelRealSense/realsense-ros/issues/749#issuecomment-843086654

**Comment by BrooklynBoy21** [comment]
@MartyG-RealSense I wrote comment there.
But the solution provided in that topic is slightly different problem. I am using IMU, not visual odometry.

**Comment by MartyG-RealSense** [comment]
The subject of wheel odometry is honestly one that I am not familiar with, so the advice that I can provide on the subject is limited, regretfully.  The research paper in the link below, which discusses D435i and wheel odometry with ROS, may be worth looking at though.

https://www.researchgate.net/publication/348413335_Survey_and_Experimental_Comparison_of_RGB-D_Indoor_Robot_Navigation_Methods_Supported_by_ROS_and_Their_Expansion_via_Fusion_with_Wheel_Odometry_and_IMU_Data

Apologies that I cannot be of more help on this particular occasion.

**Comment by MartyG-RealSense** [comment]
Hi @BrooklynBoy21  Do you have an update about this case that you can provide, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Hi @BrooklynBoy21  Do you require further assistance with this case, please?  Thanks!

**Comment by BrooklynBoy21** [comment]
@MartyG-RealSense Hi, I postponed a little bit this problem and work on another things right now. 
I will try some other solutions, so for now I think the issue can be closed.

Thank you

**Comment by MartyG-RealSense** [comment]
You are very welcome @BrooklynBoy21 - thanks for the update, and please do feel free to create a new case on this forum when you are ready to resume work on your D435i odometry project if you have further questions.  Good luck!
