### ISSUE TITLE
©rostopic list

### ISSUE THREAD

**Issue by aatb-ch** [realsenseai/realsense-ros#1994]

**Comment by MartyG-RealSense** [comment]
Hi @aatb-ch  Could you provide more information about what you want to know please?  Thanks!

As you mention in the title, you can obtain a full list of the topics supported on a particular RealSense camera model by inputting the command **rostopic list** into your ROS terminal.  For example, the RealSense ROS wrapper documentation has a list of some of the topics published by a **D435i** camera model.

https://github.com/IntelRealSense/realsense-ros#published-topics

**Comment by aatb-ch** [comment]
haha, I'm so sorry I typed on the wrong keyboard while setting up my Jetson Nano while reading issues.. you can delete this one!

**Comment by MartyG-RealSense** [comment]
No problem at all - thanks for the update   :)
