### ISSUE TITLE
unable to install realsenseSDK on windows-ROS 

### ISSUE THREAD

**Issue by 05anu** [realsenseai/realsense-ros#1997]
facing bellow error while executing the command :
**catkin_make -DCATKIN_ENABLE_TESTING=False -DCMAKE_BUILD_TYPE=Release**

Error:
NMAKE : fatal error U1077: & #39;&quot;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\bin\HostX64\x64\nmake.exe&quot;& #39; :
return code & #39;0x2& #39;
Invoking &quot;nmake&quot; failed

kindly suggest the solution for above error

**Comment by MartyG-RealSense** [comment]
Hi @05anu  The link below has a past case of the nmake error when installing RealSense ROS on Windows using the command **catkin_make -DCATKIN_ENABLE_TESTING=False -DCMAKE_BUILD_TYPE=Release**

https://github.com/IntelRealSense/realsense-ros/issues/1520#issuecomment-736220023

A workaround that worked for that particular user was to use the following command:

**rosdep install --from-paths src --ignore-src -r -y**

**Comment by 05anu** [comment]
ok.. can you please tell me that how to use this command... 
instead of using   **catkin_make -DCATKIN_ENABLE_TESTING=False -DCMAKE_BUILD_TYPE=Release ** 
I should use this command or what? request you to tell me the exact process....

**Comment by MartyG-RealSense** [comment]
My understanding is that you navigate to the catkin workspace folder with **cd ~/catkin_ws/src/** and then run the rosdep command from that folder:

**rosdep install --from-paths src --ignore-src -r -y**

**Comment by MartyG-RealSense** [comment]
Hi @05anu  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.

**Comment by 05anu** [comment]
As you mentioned above i have followed all instructions getting bellow error.

 **rosdep : error: Unsupported command install--from-paths**

**Comment by MartyG-RealSense** [comment]
Did you put a space between install and --from please?

**rosdep install --from-paths src --ignore-src -r -y**

**Comment by 05anu** [comment]
yes

**Comment by MartyG-RealSense** [comment]
Are you running the rosdep command whilst in the catkin workspace folder **/catkin_ws**

**Comment by 05anu** [comment]
Yes

**Comment by MartyG-RealSense** [comment]
Further research found that the **Invoking "nmake" failed** error in your opening message of this discussion has been reported a lot with installing ROS on Windows in general and so is a problem that is not specific to the RealSense ROS wrapper.

The RealSense ROS wrapper documentation recommends following the instructions in the link below to install ROS on Windows as a step **before** beginning installation of the wrapper.

https://wiki.ros.org/Installation/Windows

![image](https://user-images.githubusercontent.com/41145062/131108529-99f9c721-ac22-4612-a3e6-ff2a72382ce2.png)

Did you follow the instructions in this link to install ROS on Windows before beginning the wrapper installation, please?
