### ISSUE TITLE
Cmake cannot find "realsense2"

### ISSUE THREAD

**Issue by konnoeric** [realsenseai/realsense-ros#2002]
I installed SDK2.0 and it works well since I can run realsense-viewer. So installing SDK2.0 should be no problem according to the screen shot below.
![Screenshot from 2021-07-28 16-44-02](https://user-images.githubusercontent.com/74105724/127288435-97364a3a-2a9a-49da-b38a-99830ea90243.png)

I am using Ubuntu18.04 and ROS melodic but could not `catkin_make clear` and the error message below was shown. What should I do with this issue?

> -- +++ processing catkin package: 'realsense2_camera'
-- ==> add_subdirectory(realsense-ros/realsense2_camera)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
CMake Warning at realsense-ros/realsense2_camera/CMakeLists.txt:44 (find_package):
  By not providing "Findrealsense2.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "realsense2", but CMake did not find one.
Could not find a package configuration file provided by "realsense2"
 (requested version 2.48.0) with any of the following names:
    realsense2Config.cmake
    realsense2-config.cmake
Add the installation prefix of "realsense2" to CMAKE_PREFIX_PATH or set
  "realsense2_DIR" to a directory containing one of the above files.  If
  "realsense2" provides a separate development package or SDK, be sure it has
  been installed.
CMake Error at realsense-ros/realsense2_camera/CMakeLists.txt:48 (message):
     Intel RealSense SDK 2.0 is missing, please install it from https://github.com/IntelRealSense/librealsense/releases
-- Configuring incomplete, errors occurred!
See also "/home/project/catkin_ws/build/CMakeFiles/CMakeOutput.log".
See also "/home/project/catkin_ws/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed

**Comment by MartyG-RealSense** [comment]
Hi @konnoeric  May I first confirm that you used **catkin_make clean** and not 'make clear' please?  Thanks!

**Comment by konnoeric** [comment]
Yes I am sorry it was my type miss. I did catkin_make clean.

**Comment by MartyG-RealSense** [comment]
So you are using Ubuntu and you have installed the RealSense SDK (librealsense) and ROS Melodic.  You are then attempting to install the RealSense ROS wrapper using **Method 2** to build it from source code.  

Can you confirm please that the following steps were then followed.

1.  Ensure that you have the Melodic version of **dynamic_reconfigure** installed.  This can be done using the command below.

**sudo apt install ros-melodic-ddynamic-reconfigure**

2.  Create the catkin workspace and then navigate to it with these commands.

**mkdir -p ~/catkin_ws/src
cd ~/catkin_ws/src/**

3.  Whilst in the **/catkin_ws/src/** folder, clone the latest RealSense ROS version into the src folder with the commands below, making sure to include the 'cd ..' command at the end to navigate out of the src folder.

**git clone https://github.com/IntelRealSense/realsense-ros.git
cd realsense-ros/
git checkout `git tag | sort -V | grep -P "^2.\d+\.\d+" | tail -1`
cd ..**

4.  I believe at this point you should be in the **/catkin_ws/src** folder after having performed the 'cd ..' command.  Input the list of commands below.

**catkin_init_workspace
cd ..
catkin_make clean
catkin_make -DCATKIN_ENABLE_TESTING=False -DCMAKE_BUILD_TYPE=Release
catkin_make install**

5.  If you do not encounter problems with the above commands, finish the installation process by inputting these commands:

**echo "source ~/catkin_ws/devel/setup.bash" >> ~/.bashrc
source ~/.bashrc**

**Comment by konnoeric** [comment]
Thank you very much. Yes, this is the exact process I have done. 

And when I did `catkin_init_workspace` at Step4, I encountered error code saying that I have done this process before. But I have to see and check again when I come back home because I am not sure.

Is this the actual problem? Because the error message was shown when I executed `catkin_make clear`, which you can see at the very top of this conversation, saying that I need to pass something to Cmakefile. 

So do I actually have to execute `catkin_init_workspace` without any error message? because 

> It will create the CMakeLists.txt file (actually it just create a symbolic link in the src folder of your workspace pointing to CMakeLists.txt -> /opt/ros/groovy/share/catkin/cmake/toplevel.cmake in the case you're using groovy).

according to [this question to ROS answers.](https://answers.ros.org/question/187084/what-does-the-command-catkin_init_workspace-do/)

**Comment by MartyG-RealSense** [comment]
It is necessary to use **catkin_init_workspace**

Some RealSense users have had problems in the past with the **git checkout** command that comes immediately before the catkin_init_workspace command though.  Another way to input this command is to use a simpler version based on the ROS wrapper version number.  For example, if ROS wrapper 2.3.0 was being used then you would use this git checkout command:

**git checkout 2.3.0**

**Comment by konnoeric** [comment]
Sorry I found that there is an error when I execute `git checkout git tag | sort -V | grep -P "^2.\d+\.\d+" | tail -1` .

error code:
> error: pathspec 'git' did not match any file(s) known to git.
error: pathspec 'tag' did not match any file(s) known to git.

So as you said, I should execute `git checkout 2.3.0 git tag | sort -V | grep -P "^2.\d+\.\d+" | tail -1` is it correct?

Though, I dont know how to see the version of the ROS wrapper I got so would you please teach me?

**Comment by MartyG-RealSense** [comment]
You would only need to do **git checkout <version number>** - for example, git checkout 2.3.0 if you are building ROS wrapper 2.3.0 from source code.  Change '2.3.0' to whatever the version number is of the wrapper that you are installing.  You only need the version number in this shortcut version because the purpose of the git tag is to auto-find the number without needing to know it.

In regard to the git pathspec error, apparently there are ' ' quotation marks surrounding the command that did not get displayed when I listed the instruction earlier.  Sorry about that.  It was because when a sentence with ' ' quotation marks is posted in a comment, it is mis-formatted by GitHub.  Please refer back to the original Method 2 instructions for the correct line.

https://github.com/IntelRealSense/realsense-ros#step-2-install-intel-realsense-ros-from-sources

**Comment by konnoeric** [comment]
Thank you very much. I got this message when I typed in 

git checkout  `git tag | sort -V | grep -P "^2.\d+\.\d+" | tail -1`
※sorry I dont know how to correctly show the command including quotation mark but I did with those quotation mark.

message after executing the command above:
> Note: checking out '2.3.1'.
You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.
If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:
  git checkout -b <new-branch-name>
HEAD is now at 09a263a 2.3.1

So is this ok to move on next ? Because when I enter `cd ..` and then `catkin_init_workspace`, the message I got is 

> File "/home/project/catkin_ws/src/CMakeLists.txt" already exists

is this doing ok?

**Comment by MartyG-RealSense** [comment]
As far as I am aware, the **You are in 'detached HEAD' state** message is not something to be concerned about.

There is the option of deleting the whole **catkin_ws** catkin workspace folder and beginning the ROS wrapper installation process from the beginning if you feel that there is a problem.  Before doing so though, it may be worth skipping to the next step after **catkin_init_workspace** to see whether you are now able to successfully initiate the instruction catkin_make clean

**cd ..
catkin_make clean
catkin_make -DCATKIN_ENABLE_TESTING=False -DCMAKE_BUILD_TYPE=Release
catkin_make install**

**Comment by konnoeric** [comment]
Thank you. Actually I tried executing until `catkin_make install ` and I am now able to visualise images on Rviz. 

But I cannot see any pointclouds. Is there anything I should care before visualising pointclouds? If needed, I can provide screen shots of my screen after I come back home.

**Comment by MartyG-RealSense** [comment]
What method are you using to visualize a pointcloud in RViz, please?  Is it like **roslaunch realsense2_camera rs_camera.launch filters:=pointcloud**

https://github.com/IntelRealSense/realsense-ros#point-cloud

**Comment by MartyG-RealSense** [comment]
Hi @konnoeric  Do you require further assistance with this case, please?  Thanks!

**Comment by konnoeric** [comment]
Sorry for being late. I was quite busy these days. So I was just using `roslaunch realsense2_camera rs_camera.launch`, no filters option.

**Comment by MartyG-RealSense** [comment]
Thanks very much for the information.  Regarding your earlier statement "I cannot see any pointclouds.  Is there anything I should care before visualising pointclouds?" ... a **pointcloud** filter needs to be defined in the launch in order for a pointcloud to be rendered by the RealSense ROS wrapper, like the process described in https://github.com/IntelRealSense/realsense-ros#point-cloud

**Comment by MartyG-RealSense** [comment]
Hi @konnoeric  Do you have an update about this case that you can provide, please?  Thanks!

**Comment by tky1026** [comment]
Assuming you install from [Linux Debian Installation Guide](https://github.com/IntelRealSense/librealsense/blob/master/doc/distribution_linux.md#installing-the-packages).

Probably would require to install `librealsense2-dev` also, by doing `sudo apt-get install librealsense2-dev`.

This fix my issue `Could not find a package configuration file provided by "realsense2"` when `catkin_make clean`.

**Comment by MartyG-RealSense** [comment]
Thanks very much @tky1026 for your advice to @konnoeric   :)

**Comment by konnoeric** [comment]
Thank you very much @tky1026 , @MartyG-RealSense . I would like to try your advices and will tell you the results by this weekend.

**Comment by konnoeric** [comment]
So was able to view pointclouds by adding option you mentioned. Thank you very much for your kind corporation. It's all ok. You can close this case.

**Comment by MartyG-RealSense** [comment]
Great to hear that you were successful, @konnoeric - thanks very much for the update!  As suggested, I will close the case.
