### ISSUE TITLE
Record rosbag from d435i only when moves

### ISSUE THREAD

**Issue by aditdoshi333** [realsenseai/realsense-ros#2003]
Hello,

So for a use case, I want to automate the process of rosbag recording from realsense d435i but only when it moves. Is there any possibility to do this? If yes any light would be appreciated.

**Comment by MartyG-RealSense** [comment]
Hi @aditdoshi333   A good starting point for investigating fine-control over start and stop of rosbag recording in ROS may be the package **remote_rosbag_record** which was released in 2020.

http://wiki.ros.org/remote_rosbag_record

**Comment by MartyG-RealSense** [comment]
Hi @aditdoshi333  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
