### ISSUE TITLE
ROS published registered point cloud has significantly higher registration error than ccp-example cloud

### ISSUE THREAD

**Issue by skohlbr** [realsenseai/realsense-ros#201]
### System Configuration

| Version               | Your Configuration   |
|:--------------------- |:---------------------| 
| Operating System      | "Ubuntu 16.04.1 LTS"          |
| Kernel                | 4.4.0-59-generic              |
| ROS                   |  kinetic      |
| ROS RealSense         | 1.6.1               |
| librealsense          | 1.11.1                |
| Camera Type-Firmware  | Name: Intel RealSense R200, Camera FW: 1.0.72.06            |

---

### Expected Behavior

The ROS published point cloud on the `/camera/depth_registered/points` topic should have comparable registration error to the one that is shown in the `cpp-pointcloud` example

### Actual Behavior

The cloud published on the `/camera/depth_registered/points` has visibly higher registration error than the one provided by the example code. See provided example images below. The ones with blue background are from the cpp-pointcloud example, the ones with grey background from rviz. Fingers are colored correctly for the example, while they are mostly white when holding them horizontal for the ROS cloud. This indicates a registration offset along the vertical axis between depth and rgb image.

![cpp_pointcloud_fingers_horizontal](https://cloud.githubusercontent.com/assets/205963/22368768/9538021c-e488-11e6-9d58-e516ece9de03.png)
![cpp_pointcloud_fingers_vertical](https://cloud.githubusercontent.com/assets/205963/22368767/9537c7b6-e488-11e6-9795-e37ead959b72.png)

![ros_pointcloud_fingers_horizontal](https://cloud.githubusercontent.com/assets/205963/22368777/a8ca3570-e488-11e6-9310-393161ab86f8.png)
![ros_pointcloud_fingers_vertical](https://cloud.githubusercontent.com/assets/205963/22368778/a8cc23ee-e488-11e6-934e-045a2084708b.png)

#### ROS cloud:
Install realsense camera from .debs
<pre>
sudo apt-get install ros-kinetic-realsense-camera
</pre>
Run launch file
<pre>
roslaunch realsense_camera r200_nodelet_rgbd.launch 
</pre>
Look at point cloud in rviz

#### cpp-poincloud example cloud

Clone librealsense repo and build with example as per https://github.com/IntelRealSense/librealsense/blob/master/doc/installation.md

Navigate to `build/devel/lib/librealsense` and start `./cpp-pointcloud`

**Comment by skohlbr** [comment]
Looks like #184 might be the culprit here.

**Comment by mdhorn** [comment]
We are looking into #184

**Comment by skohlbr** [comment]
@mattcurfman @mdhorn  is this on Intel's radar still? It's been 6 months and multiple people reporting calibration issues with the R200 and ROS drivers even before that (this issue, #233, #184, #30).

**Comment by skohlbr** [comment]
So I did some more digging. The back-projected point cloud in the RGB image using the rviz Camera Display (both image_color and image_rect_color) has the color of points exactly match up. This actually is bad though, as the registration error between color and depth  means that the depth image (and thus point cloud) is off by the ~9 pixels reported previously.

You can clearly see the side of the box I pointed the camera at being colored red (see cloud at bottom of the screenshot), which it should not be.
![r200_reg_error](https://user-images.githubusercontent.com/205963/29239556-857f6d6a-7f51-11e7-81cc-2c9e39b1180f.png)


For comparison, the same scene running `cpp-tutorial-3-pointcloud ` which essentially looks perfect:
![r200_cpp_tutorial](https://user-images.githubusercontent.com/205963/29239568-c411431e-7f51-11e7-85e0-b843e73ada24.png)

**Comment by skohlbr** [comment]
So I reactivated the native points stream and registration of color vs. points looks good (as expected). Reprojection into the RGB image shows an offset though, so what is broken is very likely the calibration values for the RGB camera:

![native_stream](https://user-images.githubusercontent.com/205963/29241793-f9f690a4-7f80-11e7-85b8-bbc73808e8dd.png)

From https://github.com/IntelRealSense/librealsense/blob/v1.12.1/doc/projection.md#r200 we know that the **rectified** color stream has no rotation wrt to the depth frames. But in the driver the plain **non-rectified** color stream is used so far, while all rotation components used in calibration are just set to identity (see https://github.com/intel-ros/realsense/blob/indigo-devel/realsense_camera/src/base_nodelet.cpp#L1061, https://github.com/intel-ros/realsense/blob/indigo-devel/realsense_camera/src/base_nodelet.cpp#L735).

Working theory is that two approaches should be feasible:

- Use the rectified color stream. In that case, the identity rotation is correct.

- Continue using the non-rectified stream. In that case, the frame rotations need to be set correctly. Also, for this to work, rectification of the RGB stream has to be done in "ROS world". I'm not sure if the modified calibration model used for the R200 RGB camera is compatible with the cv camera model used by the nodelets.

**Comment by skohlbr** [comment]
So I managed to vastly improve things by using the rectified stream calibration instead of the standard unrectified stream one. Here's a screenshot using this approach:

![using_rect_calibration](https://user-images.githubusercontent.com/205963/29244245-a7d89fbe-7fb3-11e7-9321-9b8b4e42a12c.png)

Created a PR for this change (#261). This is still somewhat inconsistent as the rectified camera stream is not used consistently, but the results are vastly better than the previously completely unacceptable 9 pixel offset.

**Comment by icarpis** [comment]
Fixed by #261
