### ISSUE TITLE
How to generate a point cloud from the color map and the depth map

### ISSUE THREAD

**Issue by Lai-dongdong** [realsenseai/realsense-ros#2013]
Hi, how to generate a point cloud from the color map and the depth map, my purpose is to map the marked color map to the point cloud

**Comment by MartyG-RealSense** [comment]
Hi @Lai-dongdong  Would the textured pointcloud tutorial linked to below in the RealSense ROS wrapper documentation meet your needs, please?

https://github.com/IntelRealSense/realsense-ros#point-cloud

**Comment by MartyG-RealSense** [comment]
Hi @Lai-dongdong  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
