### ISSUE TITLE
ROS2 with L515: message rates from ROS nodes greatly reduced, system seems bottlenecked

### ISSUE THREAD

**Issue by AndyZe** [realsenseai/realsense-ros#2023]
We have a relatively powerful but little older desktop PC (Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz, 8 threads). When running the L515 we find that overall ROS message rates are greatly reduced and the system seems overloaded as a whole. For example, streaming position commands to the robot arm drops from 500 Hz to ~12 Hz!

I will try to provide as much information as I can below. **Any suggestions to improve performance?** From what I understand, fps of L515 cameras cannot be reduced.

(Likely related to #1850)

ROS2 Foxy
Only one RealSense L515 and one UR5e robot connected, no other significant devices
Camera config attached.
System monitor with CPU load and Network bandwidth snapshot attached. Note, all CPU loads are around 70-90%.
NIC speed is 1 Gbps (so we're nowhere close to that)
realsense-ros commit fa28b6f6  (June 24 2021)
librealsense2 version 2.48.0-0~realsense0.4976
NVidia driver version 470.57.02

[realsense.launch.py.txt](https://github.com/IntelRealSense/realsense-ros/files/6940956/realsense.launch.py.txt)

![system_monitor](https://user-images.githubusercontent.com/11284393/128403786-e0668d1e-2141-44ee-a583-63d2e2c79280.png)

**Comment by MartyG-RealSense** [comment]
Hi @AndyZe   Yes, the L515 lidar depth camera model only supports an FPS of 30 for depth and infrared streams.

I see that you are using the **rs_launch.py** launch file.  Can you tell me the full roslaunch instruction that you used, please?

Also, would it be possible to provide the launch log that was generated in the terminal during roslaunch?  Thanks!

**Comment by AndyZe** [comment]
Hi Marty, the launch log stuff pertaining to RealSense is attached. Also attached the result of `ros2 param dump /wrist_l515/wrist_l515`  (our wrist camera node name).
[ros2_param_dump.txt](https://github.com/IntelRealSense/realsense-ros/files/6951321/ros2_param_dump.txt)
[L515_launch_log.txt](https://github.com/IntelRealSense/realsense-ros/files/6951322/L515_launch_log.txt)

I'm not gonna attach the whole launch file b/c it's huge, but here are the L515 params we set:

>     wrist_l515_launch = IncludeLaunchDescription(
>         get_launch_file("moveit_studio_agent", "launch/realsense.launch.py"),
>         launch_arguments={
>             "enable_pointcloud": "true",
>             "device_type": "l515",
>             "camera_name": "wrist_l515",
>             "base_frame_id": "wrist_l515_link",
>             "depth_frame_id": "wrist_l515_depth_frame",
>             "depth_optical_frame_id": "wrist_l515_depth_optical_frame",
>             "color_frame_id": "wrist_l515_color_frame",
>             "color_optical_frame_id": "wrist_l515_color_optical_frame",
>         }.items(),
>     )

**Comment by MartyG-RealSense** [comment]
Do you see any improvement in performance if you launch **moveit_studio_agent** and **realsense.launch.py** in two separate ROS terminals instead of with a 'get_launch_file' launch instruction?

**Comment by AndyZe** [comment]
It seems like this is mostly fixed by building in Release mode. Sorry to bother you. (Will re-open if it becomes an issue again.)

**Comment by MartyG-RealSense** [comment]
It's no trouble at all   :)   Please do feel free to re-open at a later date if you have follow-up questions.   Thanks for the update!

**Comment by bbferka** [comment]
If anyone reads this thread because of high CPU consumption while using L515 cameras, we had a similar issue: extremely poor performance using ROS2 on same hardware where ROS1 drivers were performing well. Turned out to be a bug in here: https://github.com/ros-perception/image_transport_plugins/blob/foxy-devel/compressed_depth_image_transport/src/compressed_depth_publisher.cpp#L68  since setting the PNG compression level does not work as is currently implemented and will always default to 9;
