### ISSUE TITLE
some warnning when use d435i

### ISSUE THREAD

**Issue by SongJ11** [realsenseai/realsense-ros#2025]
After I use d435i to execute realsense viewer, some warnings appear. Why？
such as:
WARNING [139766324201216] (backend-v4l2.cpp:1358) Pixel format 36315752-1a66-a242-9065-d01814a likely requires patch for fourcc code RW16!
 WARNING [139766105855744] (backend-hid.cpp:715) HID set_power 1 failed for /sys/devices/pci0000:00/0000:00:14.0/usb4/4-2/4-2:1.5/0003:8086:0B3A.0003/HID-SENSOR-200076.3.auto/iio:device0/buffer/enable
WARNING [139765882025728](sensor.cpp:985) HID timestamp not found, switching to Host timestamps.
WARNING [139765202544384] (ds5-auto-calibration.cpp:340) hwmon command 0x80( 3 0 0 0 ) failed (response -7= HW not ready)

**Comment by MartyG-RealSense** [comment]
Hi @SongJ11  May I first ask the questions below, please.

-  Are you using Windows or Linux, please?

-  If you are using Linux, did you build the librealsense SDK from Debian packages or from source code?

-  If you built the librealsense SDK from source code, did you patch the kernel using the command below?

**./scripts/patch-realsense-ubuntu-lts.sh**

**Comment by SongJ11** [comment]
> Hi @SongJ11 May I first ask the questions below, please.
> 
>     * Are you using Windows or Linux, please?
> 
>     * If you are using Linux, did you build the librealsense SDK from Debian packages or from source code?
> 
>     * If you built the librealsense SDK from source code, did you patch the kernel using the command below?
> 
> 
> **./scripts/patch-realsense-ubuntu-lts.sh**



I use Linux. If I use. / scripts / patch-realsense-ubuntu-lts.sh, how should I solve it

**Comment by SongJ11** [comment]
> > Hi @SongJ11 May I first ask the questions below, please.
> > ```
> > * Are you using Windows or Linux, please?
> > 
> > * If you are using Linux, did you build the librealsense SDK from Debian packages or from source code?
> > 
> > * If you built the librealsense SDK from source code, did you patch the kernel using the command below?
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **./scripts/patch-realsense-ubuntu-lts.sh**
> 
> I use Linux. If I use. / scripts / patch-realsense-ubuntu-lts.sh, how should I solve it
    I use the librealsense SDK

**Comment by SongJ11** [comment]
> If you are using Linux, did you build the librealsense SDK from Debian packages or from source code

I use source code to build librealsense SDK

**Comment by MartyG-RealSense** [comment]
The error **Pixel format ... likely requires patch for fourcc code RW16!** may be caused by an unpatched kernel.  Please go to the root directory of your librealsense source code folder (the 'librealsense' one with the list of files) and input the command **./scripts/patch-realsense-ubuntu-lts.sh**

![image](https://user-images.githubusercontent.com/41145062/128594778-785dbf0e-f0a2-4c64-bbd4-124b18467689.png)

**Comment by SongJ11** [comment]
> The error **Pixel format ... likely requires patch for fourcc code RW16!** may be caused by an unpatched kernel. Please go to the root directory of your librealsense source code folder (the 'librealsense' one with the list of files) and input the command **./scripts/patch-realsense-ubuntu-lts.sh**
> 
> ![image](https://user-images.githubusercontent.com/41145062/128594778-785dbf0e-f0a2-4c64-bbd4-124b18467689.png)

OK,I will try it,thanks.

**Comment by MartyG-RealSense** [comment]
Hi @SongJ11  Do you require further assistance with this case, please?  Thanks!

**Comment by SongJ11** [comment]
> Hi @SongJ11 Do you require further assistance with this case, please? Thanks!

yes,I have solved those warnings using your method.Thanks you again.

**Comment by MartyG-RealSense** [comment]
Excellent news that a solution has been achieved, @SongJ11 - thanks for the update.  As the problem has been solved, I will close the case.  Thanks again!
