### ISSUE TITLE
there is no any info update, after the info is RealSense Node Is Up!

### ISSUE THREAD

**Issue by casso1993** [realsenseai/realsense-ros#2029]
casso@casso-Lenovo-Legion-R7000P2021H:~$ roslaunch realsense2_camera rs_camera.launch
... logging to /home/casso/.ros/log/f1e917ba-f8fd-11eb-af7c-8d8d8c4b9429/roslaunch-casso-Lenovo-Legion-R7000P2021H-4693.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://casso-Lenovo-Legion-R7000P2021H:36119/

SUMMARY
========

PARAMETERS
 * /camera/realsense2_camera/accel_fps: -1
 * /camera/realsense2_camera/accel_frame_id: camera_accel_frame
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: False
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/allow_no_texture_points: False
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/calib_odom_file: 
 * /camera/realsense2_camera/clip_distance: -2.0
 * /camera/realsense2_camera/color_fps: -1
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: -1
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: -1
 * /camera/realsense2_camera/confidence_fps: -1
 * /camera/realsense2_camera/confidence_height: -1
 * /camera/realsense2_camera/confidence_width: -1
 * /camera/realsense2_camera/depth_fps: -1
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: -1
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: -1
 * /camera/realsense2_camera/device_type: 
 * /camera/realsense2_camera/enable_accel: False
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_confidence: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye1: False
 * /camera/realsense2_camera/enable_fisheye2: False
 * /camera/realsense2_camera/enable_fisheye: False
 * /camera/realsense2_camera/enable_gyro: False
 * /camera/realsense2_camera/enable_infra1: False
 * /camera/realsense2_camera/enable_infra2: False
 * /camera/realsense2_camera/enable_infra: False
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_pose: False
 * /camera/realsense2_camera/enable_sync: False
 * /camera/realsense2_camera/filters: 
 * /camera/realsense2_camera/fisheye1_frame_id: camera_fisheye1_f...
 * /camera/realsense2_camera/fisheye1_optical_frame_id: camera_fisheye1_o...
 * /camera/realsense2_camera/fisheye2_frame_id: camera_fisheye2_f...
 * /camera/realsense2_camera/fisheye2_optical_frame_id: camera_fisheye2_o...
 * /camera/realsense2_camera/fisheye_fps: -1
 * /camera/realsense2_camera/fisheye_frame_id: camera_fisheye_frame
 * /camera/realsense2_camera/fisheye_height: -1
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: -1
 * /camera/realsense2_camera/gyro_fps: -1
 * /camera/realsense2_camera/gyro_frame_id: camera_gyro_frame
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/imu_optical_frame_id: camera_imu_optica...
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra_fps: 30
 * /camera/realsense2_camera/infra_height: 480
 * /camera/realsense2_camera/infra_rgb: False
 * /camera/realsense2_camera/infra_width: 848
 * /camera/realsense2_camera/initial_reset: False
 * /camera/realsense2_camera/json_file_path: 
 * /camera/realsense2_camera/linear_accel_cov: 0.01
 * /camera/realsense2_camera/odom_frame_id: camera_odom_frame
 * /camera/realsense2_camera/ordered_pc: False
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/pose_frame_id: camera_pose_frame
 * /camera/realsense2_camera/pose_optical_frame_id: camera_pose_optic...
 * /camera/realsense2_camera/publish_odom_tf: True
 * /camera/realsense2_camera/publish_tf: True
 * /camera/realsense2_camera/rosbag_filename: 
 * /camera/realsense2_camera/serial_no: 
 * /camera/realsense2_camera/stereo_module/exposure/1: 7500
 * /camera/realsense2_camera/stereo_module/exposure/2: 1
 * /camera/realsense2_camera/stereo_module/gain/1: 16
 * /camera/realsense2_camera/stereo_module/gain/2: 16
 * /camera/realsense2_camera/tf_publish_rate: 0.0
 * /camera/realsense2_camera/topic_odom_in: odom_in
 * /camera/realsense2_camera/unite_imu_method: 
 * /camera/realsense2_camera/usb_port_id: 
 * /rosdistro: noetic
 * /rosversion: 1.15.11

NODES
  /camera/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)

ROS_MASTER_URI=http://localhost:11311

process[camera/realsense2_camera_manager-1]: started with pid [4707]
process[camera/realsense2_camera-2]: started with pid [4708]
[ INFO] [1628505563.901212986]: Initializing nodelet with 16 worker threads.
[ INFO] [1628505564.121521478]: RealSense ROS v2.3.1
[ INFO] [1628505564.121562942]: Built with LibRealSense v2.48.0
[ INFO] [1628505564.121578159]: Running with LibRealSense v2.48.0
[ INFO] [1628505564.150621532]:  
[ INFO] [1628505564.331717578]: Device with serial number 117122250984 was found.

[ INFO] [1628505564.331766999]: Device with physical ID /sys/devices/pci0000:00/0000:00:08.1/0000:06:00.4/usb4/4-2/4-2:1.0/video4linux/video2 was found.
[ INFO] [1628505564.331777121]: Device with name Intel RealSense D455 was found.
[ INFO] [1628505564.332031416]: Device with port number 4-2 was found.
[ INFO] [1628505564.332064363]: Device USB type: 3.2
[ INFO] [1628505564.335675519]: getParameters...
[ INFO] [1628505564.370768082]: setupDevice...
[ INFO] [1628505564.370801448]: JSON file is not provided
[ INFO] [1628505564.370812337]: ROS Node Namespace: camera
[ INFO] [1628505564.370831464]: Device Name: Intel RealSense D455
[ INFO] [1628505564.370840399]: Device Serial No: 117122250984
[ INFO] [1628505564.370851846]: Device physical port: /sys/devices/pci0000:00/0000:00:08.1/0000:06:00.4/usb4/4-2/4-2:1.0/video4linux/video2
[ INFO] [1628505564.370867622]: Device FW version: 05.12.14.50
[ INFO] [1628505564.370882351]: Device Product ID: 0x0B5C
[ INFO] [1628505564.370911947]: Enable PointCloud: Off
[ INFO] [1628505564.370922976]: Align Depth: Off
[ INFO] [1628505564.370931562]: Sync Mode: Off
[ INFO] [1628505564.371019515]: Device Sensors: 
[ INFO] [1628505564.392253527]: Stereo Module was found.
 09/08 18:39:24,392 WARNING [140461805139712] (backend-v4l2.cpp:1358) Pixel format 36315752-1a66-a242-9065-d01814a likely requires patch for fourcc code RW16!
[ INFO] [1628505564.406035643]: RGB Camera was found.
[ INFO] [1628505564.406837199]: Motion Module was found.
[ INFO] [1628505564.406888994]: (Confidence, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1628505564.406910004]: num_filters: 0
[ INFO] [1628505564.406920894]: Setting Dynamic reconfig parameters.
[ WARN] [1628505564.545873922]: Param '/camera/stereo_module/auto_exposure_limit' has value 0 that is not in range [1, 165000]. Removing this parameter from dynamic reconfigure options.
[ WARN] [1628505564.546742490]: Param '/camera/stereo_module/auto_gain_limit' has value 0 that is not in range [16, 248]. Removing this parameter from dynamic reconfigure options.
[ WARN] [1628505564.556572598]: Param '/camera/rgb_camera/power_line_frequency' has value 3 that is not in the enum { {50Hz: 1} {60Hz: 2} {Disabled: 0} }. Removing this parameter from dynamic reconfigure options.
[ INFO] [1628505564.561471982]: Done Setting Dynamic reconfig parameters.
[ INFO] [1628505564.562311651]: depth stream is enabled - width: 848, height: 480, fps: 30, Format: Z16
[ INFO] [1628505564.563065740]: color stream is enabled - width: 1280, height: 720, fps: 30, Format: RGB8
[ INFO] [1628505564.563118233]: setupPublishers...
[ INFO] [1628505564.565667744]: Expected frequency for depth = 30.00000
[ INFO] [1628505564.597460476]: Expected frequency for color = 30.00000
[ INFO] [1628505564.619764509]: setupStreams...
[ INFO] [1628505564.671870054]: insert Depth to Stereo Module
[ INFO] [1628505564.671991093]: insert Color to RGB Camera
[ INFO] [1628505564.745337142]: SELECTED BASE:Depth, 0
[ INFO] [1628505564.765437402]: RealSense Node Is Up!
[ WARN] [1628505565.026751199]:

**Comment by MartyG-RealSense** [comment]
Hi @casso1993  I cannot see anything obvious in your kindly provided log that would prevent any data at all from being published.

I note the warning message **likely requires patch for fourcc code RW16!**, which could indicate that the Linux kernel has not been patched if you installed the librealsense SDK from source code.

To display the camera data in ROS, you can 'visualize' it with the **RViz** interface, which can be run by inputting the command **rosrun rviz rviz** in your ROS terminal.  Are you able to see any camera information if you run RViz with this command, please?

**Comment by MartyG-RealSense** [comment]
Hi @casso1993  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
