### ISSUE TITLE
R200 camera nodelet manager process has died

### ISSUE THREAD

**Issue by y27choi** [realsenseai/realsense-ros#203]
### System Configuration
Please complete Your Configuration detail below. Refer to the BKC at [Configuration](../realsense_camera/README.md#configuration).

| Version               | Your Configuration   |
|:--------------------- |:---------------------|
| Operating System      | Ubuntu 14.04.4 LTS |
| Kernel                | 4.4.0-47-generic|
| ROS                   | indigo                    |
| ROS RealSense         | 1.5.0               |
| librealsense          | 1.11.0               |
| Camera Type-Firmware  | R200-1.0.72.06            |

### Expected Behavior
/camera/driver can successfully update the dynamic settings of the camera.

### Actual Behavior
It doesn't happen every time, but I've seen it happen often enough to notice. When I disable depth_camera using dynamic_reconfigure service call ("set_parameter"), and enable it back right after, it throws out the error message (see below) and the nodelet manager crashes.
```
[ INFO] [1486525217.725395391]: /camera/driver - Stopping camera
[ INFO] [1486525218.253660335]: /camera/driver - Enabling Depth in manual mode
[ INFO] [1486525218.253774217]: /camera/driver - Enabling IR in manual mode
[ INFO] [1486525218.253866257]: /camera/driver - Enabling IR2 in manual mode
[ INFO] [1486525218.253936991]: /camera/driver - Starting camera
[ INFO] [1486525218.326540724]: /camera/driver - Setting dynamic camera options
[ERROR] [1486525223.303488718]: /camera/driver - Error calling rs_wait_for_frames ( device:0x133c088 ): 
Timeout waiting for frames. 
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::lock_error> >'
  what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument
[camera_nodelet_manager-1] process has died [pid 4689, exit code -6, cmd /opt/ros/indigo/lib/nodelet/nodelet manager __name:=camera_nodelet_manager __log:=/tmp/90b3746a-ed84-11e6-968d-b8aeedea3ef7/camera_nodelet_manager-1.log].
```

### Steps to Reproduce
1) Launch a single nodelet manager for two cameras.
2) Enable/disable the depth camera by calling a ROS service ("set_parameter")
3) After repeating step 2) for a while, the nodelet manager will crash.

**Camera settings used for both cameras:**

    camera_type: "R200"
    enable_depth: true
    enable_color: true
    enable_pointcloud: false
    enable_tf: false
    mode: "manual"
    color_width: 1920
    color_height: 1080
    color_fps: 30
    depth_width: 480
    depth_height: 360
    depth_fps: 30
    r200_depth_units: 1000
    r200_depth_clamp_min: 0
    r200_depth_clamp_max: 65535
    r200_depth_control_estimate_median_decrement: 5
    r200_depth_control_estimate_median_increment: 5
    r200_depth_control_median_threshold: 180
    r200_depth_control_score_minimum_threshold: 26
    r200_depth_control_score_maximum_threshold: 430
    r200_depth_control_texture_count_threshold: 7
    r200_depth_control_texture_difference_threshold: 60
    r200_depth_control_second_peak_threshold: 55
    r200_depth_control_neighbor_threshold: 35
    r200_depth_control_lr_threshold: 12

**Comment by mdhorn** [comment]
Please update to the latest releases and retest.
`sudo apt-get update`
`sudo apt-get upgrade`
librealsense should be 1.12.0 for Indigo
realsense_camera should be 1.7.0  for Indigo

**Comment by mdhorn** [comment]
Closing due to no response.

**Comment by mga0** [comment]
I have exactly the same issue with two SR300 in a nodelet.


### System Configuration

| Version               | Your Configuration   |
|:--------------------- |:---------------------|
| Operating System      | Ubuntu 16.04            |
| Kernel                | 4.4.0-83-generic               |
| ROS                   | kinetic                    |
| ROS RealSense         |     1.8.0            |
| librealsense          | 1.12.1               |
| Camera Type-Firmware  | SR300 3.15.0.0            |

---


### Expected Behavior

Switching off and on the IR projector of two Realsense SR300 using dynamic reconfiguration


### Actual Behavior

Nodelet crashes after 3-5 successful switch off/on procedures.

> [ INFO] [1499072586.160897330]: /camera/driver - Setting dynamic camera options
> [ INFO] [1499072586.216745451]: /camera/driver - Stopping camera
> [ INFO] [1499072586.226933855]: /camera/driver - Enabling Depth in manual mode
> [ INFO] [1499072586.227052865]: /camera/driver - Starting camera
> [ INFO] [1499072588.137289066]: /camera/driver - Setting dynamic camera options
> [ERROR] [1499072591.233984291]: /camera/driver - Error calling rs_wait_for_frames ( device:0x1ea3820 ): 
> Timeout waiting for frames. 



### Steps to Reproduce

1. Launch two SR300s with the following file: roslaunch 

```
<!-- Launch file for using multiple RealSense R200 cameras -->
<launch>

  <arg name="camera_1"              default="camera_L" />
  <arg name="camera_1_camera_type"  default="SR300"    /> <!-- Type of camera -->
  <arg name="camera_1_serial_no"    default="617205xxxxx"   />
  <arg name="camera_1_usb_port_id"  default=""        /> <!-- USB "Bus#-Port#" -->

  <arg name="camera_2"              default="camera_C" />
  <arg name="camera_2_camera_type"  default="SR300"    /> <!-- Type of camera -->
  <arg name="camera_2_serial_no"    default="620202xxxxx"   />
  <arg name="camera_2_usb_port_id"  default=""        /> <!-- USB "Bus#-Port#" -->

  <arg name="enable_depth"      default="false" />
  <arg name="enable_color"      default="true" />
  <arg name="color_fps"         default="10" />
  <arg name="color_width"       default="1280" />
  <arg name="color_height"      default="720" />
  <arg name="depth_fps"         default="10" />
  <arg name="depth_width"       default="640" />
  <arg name="depth_height"      default="480" />
  <arg name="mode"              default="manual" />
  <arg name="enable_tf"         default="false" />

  <param name="$(arg camera_1)/driver/enable_depth"      type="bool" value="$(arg enable_depth)" />
  <param name="$(arg camera_1)/driver/enable_color"      type="bool" value="$(arg enable_color)" />
  <param name="$(arg camera_1)/driver/enable_tf"         type="bool" value="$(arg enable_tf)" />
  <param name="$(arg camera_1)/driver/mode"              type="str"  value="$(arg mode)" />
  <param name="$(arg camera_1)/driver/depth_width"       type="int"  value="$(arg depth_width)" />
  <param name="$(arg camera_1)/driver/depth_height"      type="int"  value="$(arg depth_height)" />
  <param name="$(arg camera_1)/driver/color_width"       type="int"  value="$(arg color_width)" />
  <param name="$(arg camera_1)/driver/color_height"      type="int"  value="$(arg color_height)" />
  <param name="$(arg camera_1)/driver/depth_fps"         type="int"  value="$(arg depth_fps)" />
  <param name="$(arg camera_1)/driver/color_fps"         type="int"  value="$(arg color_fps)" />

  <param name="$(arg camera_2)/driver/enable_depth"      type="bool" value="$(arg enable_depth)" />
  <param name="$(arg camera_2)/driver/enable_color"      type="bool" value="$(arg enable_color)" />
  <param name="$(arg camera_2)/driver/enable_tf"         type="bool" value="$(arg enable_tf)" />
  <param name="$(arg camera_2)/driver/mode"              type="str"  value="$(arg mode)" />
  <param name="$(arg camera_2)/driver/depth_width"       type="int"  value="$(arg depth_width)" />
  <param name="$(arg camera_2)/driver/depth_height"      type="int"  value="$(arg depth_height)" />
  <param name="$(arg camera_2)/driver/color_width"       type="int"  value="$(arg color_width)" />
  <param name="$(arg camera_2)/driver/color_height"      type="int"  value="$(arg color_height)" />
  <param name="$(arg camera_2)/driver/depth_fps"         type="int"  value="$(arg depth_fps)" />
 
  <arg name="manager" value="camera_nodelet_manager" /> <!-- Single nodelet manager for all cameras -->
  <node pkg="nodelet" type="nodelet" name="$(arg manager)" args="manager" output="screen"/>

 <group ns="$(arg camera_1)">
    <include file="$(find realsense_camera)/launch/includes/nodelet.launch.xml">
      <arg name="manager"      value="/$(arg manager)" />
      <arg name="camera"       value="$(arg camera_1)" />
      <arg name="camera_type"  value="$(arg camera_1_camera_type)" />
      <arg name="serial_no"    value="$(arg camera_1_serial_no)" />
      <arg name="usb_port_id"  value="$(arg camera_1_usb_port_id)" />
    </include>
  </group>

 <group ns="$(arg camera_2)">
    <include file="$(find realsense_camera)/launch/includes/nodelet.launch.xml">
      <arg name="manager"      value="/$(arg manager)" />
      <arg name="camera"       value="$(arg camera_2)" />
      <arg name="camera_type"  value="$(arg camera_2_camera_type)" />
      <arg name="serial_no"    value="$(arg camera_2_serial_no)" />
      <arg name="usb_port_id"  value="$(arg camera_2_usb_port_id)" />
    </include>
  </group>

</launch>
```
2. Run several times OFF and ON (code only for OFF provided):

 ```
  dynamic_reconfigure::ReconfigureRequest srv_req_off;
  dynamic_reconfigure::ReconfigureResponse srv_resp;
  dynamic_reconfigure::IntParameter off_param;
  dynamic_reconfigure::BoolParameter depth_off_param;

  dynamic_reconfigure::Config conf_off;

  off_param.name = "f200_laser_power";
  off_param.value = 0;
  depth_off_param.name = "enable_depth";
  depth_off_param.value = false;
  conf_off.ints.push_back(off_param);
  conf_off.bools.push_back(depth_off_param);

  srv_req_off.config = conf_off;

  // switch off IR projector
  bool succ = ros::service::call(camera + "driver/set_parameters", srv_req_off, srv_resp);
```

**Comment by delmottea** [comment]
I got the same problem (also with two sr300).
This problem happen only with ros, I have no problem switching on and off the laser when using directly librealsense outside ros.
The only solution we found until now was to use a small servo-motor to occlude mechanically the laser projector

**Comment by mga0** [comment]
I would like to see that ticket reopened, @mdhorn. Since our issue affect SR300s, not R200s, should we open a new ticket for this? I only have a time frame of one month to contribute to this project.
