### ISSUE TITLE
how to publish pointcloud without RGB information and how to modify launch file

### ISSUE THREAD

**Issue by zhangamao** [realsenseai/realsense-ros#2041]

**Comment by MartyG-RealSense** [comment]
Hi @zhangamao   I hope that the information in the link below will answer your question.

https://github.com/IntelRealSense/realsense-ros/issues/1834

As described in the discussion, the pointcloud texture setting can be defined in the roslaunch instruction without having to edit the launch file.

If you need to edit the launch file then you should be able to do so with a text editor program, such as **Notepad** in Windows or **gedit** in Ubuntu.

**Comment by MartyG-RealSense** [comment]
Hi @zhangamao  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
