### ISSUE TITLE
Cannot read launch params for D455(eg: stereo_module/auto_exposure_limit)

### ISSUE THREAD

**Issue by vzhr** [realsenseai/realsense-ros#2042]
when I use D455, I had a warnning: " _Param '/camera/realsense2_camera/stereo_module/auto_exposure_limit' has value 0 outside the range [1, 165000]. Removing this parameter from dynamic reconfigure options._".
Then I add  param "_stereo_module/auto_exposure_limit_" in _nodelet.launch.xml_ file,  I still had this warnning, but have this param: /camera/stereo_module/auto_exposure_limit.
I think this was caused by ros namespace, so I check codes and find this in _base_realsense_node.cpp_:

```
void BaseRealSenseNode::publishTopics()
{
    getParameters();
    setupDevice();
    setupFilters();
    registerHDRoptions();
    registerDynamicReconfigCb(_node_handle); //here
    setupErrorCallback();
    enable_devices();
    setupPublishers();
    setupStreams();
    SetBaseStream();
    registerAutoExposureROIOptions(_node_handle); //here
    publishStaticTransforms();
    publishIntrinsics();
    startMonitoring();
    ROS_INFO_STREAM("RealSense Node Is Up!");
}
```
Then I change `_node_handle` to `_pnh`
```
void BaseRealSenseNode::publishTopics()
{
    getParameters();
    setupDevice();
    setupFilters();
    registerHDRoptions();
    registerDynamicReconfigCb(_pnh); //here
    setupErrorCallback();
    enable_devices();
    setupPublishers();
    setupStreams();
    SetBaseStream();
    registerAutoExposureROIOptions(_pnh); //here
    publishStaticTransforms();
    publishIntrinsics();
    startMonitoring();
    ROS_INFO_STREAM("RealSense Node Is Up!");
}
```

stereo_module params (eg: stereo_module/auto_exposure_limit,  stereo_module/auto_gain_limit) loaded correctly.

Is this a bug? May this help.

**Comment by MartyG-RealSense** [comment]
Hi @vzhr  This warning appears in most RealSense ROS users' launch logs and therefore is not something to be concerned about and I would not consider it to be a bug.

When the feature was added in librealsense SDK version **2.42.0**, the SDK release notes provided the following description about it.

***********

Auto-Exposure and Gain max limits for IR sensors.  The new APIs set the effective upper bound for Exposure and Gain values for Depth Auto-Exposure.  This allows to control and limit the changes in FPS rate while enabling for AE auto-adjustments.  Requires FW5.12.11.0 or later.

**********

Thanks very much for sharing your method for enabling it in ROS with the RealSense ROS community!

**Comment by vzhr** [comment]
> Hi @vzhr This warning appears in most RealSense ROS users' launch logs and therefore is not something to be concerned about and I would not consider it to be a bug.
> 
> When the feature was added in librealsense SDK version **2.42.0**, the SDK release notes provided the following description about it.
> 
> Auto-Exposure and Gain max limits for IR sensors. The new APIs set the effective upper bound for Exposure and Gain values for Depth Auto-Exposure. This allows to control and limit the changes in FPS rate while enabling for AE auto-adjustments. Requires FW5.12.11.0 or later.
> 
> Thanks very much for sharing your method for enabling it in ROS with the RealSense ROS community!
You're very welcome,  @MartyG-RealSense.  I'm pleased that this could help!

**Comment by vzhr** [comment]
> Hi @vzhr This warning appears in most RealSense ROS users' launch logs and therefore is not something to be concerned about and I would not consider it to be a bug.
> 
> When the feature was added in librealsense SDK version **2.42.0**, the SDK release notes provided the following description about it.
> 
> Auto-Exposure and Gain max limits for IR sensors. The new APIs set the effective upper bound for Exposure and Gain values for Depth Auto-Exposure. This allows to control and limit the changes in FPS rate while enabling for AE auto-adjustments. Requires FW5.12.11.0 or later.
> 
> Thanks very much for sharing your method for enabling it in ROS with the RealSense ROS community!

You're very welcome,  @MartyG-RealSense.  I'm pleased that this could help!

**Comment by MartyG-RealSense** [comment]
@vzhr  Do you require further assistance with this case after kindly providing your solution?   Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
