### ISSUE TITLE
Machine shutdown after launching D435 

### ISSUE THREAD

**Issue by sammar80** [realsenseai/realsense-ros#2046]
Hi , I'm using D435 on nvidia jetson nano with ros-melodic what I'm facing is that once I launch the rs_camera.launch the machine shutdown I tired several sdk versions and the same issue happens when I plug the camera using the provided type-C cable for USB 3 . I appreciate if anyone can help with this problem 
librealsense ver : 2.45.0
realsense-ros ver : 2.3.0
camera firmware : 5.12.13.50

**Comment by MartyG-RealSense** [comment]
Hi @sammar80   Could you paste the launch log from your roslaunch into a comment below, please?  Thanks!

**Comment by sammar80** [comment]
Hi @MartyG-RealSense  , this is all what I get before the nvidia shutdown
... logging to /home/optimus/.ros/log/a5646b7e-041a-11ec-ae8b-d03745187cad/roslaunch-Autobot-8223.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.
]2;/home/optimus/catkin_ws/src/realsense-ros/realsense2_camera/launch/rs_camera.launch
[1mstarted roslaunch server http://Autobot:35413/[0m

SUMMARY
========

PARAMETERS
 * /camera/realsense2_camera/accel_fps: -1
 * /camera/realsense2_camera/accel_frame_id: camera_accel_frame
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: False
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/allow_no_texture_points: False
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/calib_odom_file: 
 * /camera/realsense2_camera/clip_distance: -2.0
 * /camera/realsense2_camera/color_fps: 30
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: 480
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: 640
 * /camera/realsense2_camera/confidence_fps: -1
 * /camera/realsense2_camera/confidence_height: -1
 * /camera/realsense2_camera/confidence_width: -1
 * /camera/realsense2_camera/depth_fps: 30
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: 480
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: 640
 * /camera/realsense2_camera/device_type: 
 * /camera/realsense2_camera/enable_accel: False
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_confidence: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye1: False
 * /camera/realsense2_camera/enable_fisheye2: False
 * /camera/realsense2_camera/enable_fisheye: False
 * /camera/realsense2_camera/enable_gyro: False
 * /camera/realsense2_camera/enable_infra1: False
 * /camera/realsense2_camera/enable_infra2: False
 * /camera/realsense2_camera/enable_infra: False
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_pose: False
 * /camera/realsense2_camera/enable_sync: False
 * /camera/realsense2_camera/filters: 
 * /camera/realsense2_camera/fisheye1_frame_id: camera_fisheye1_f...
 * /camera/realsense2_camera/fisheye1_optical_frame_id: camera_fisheye1_o...
 * /camera/realsense2_camera/fisheye2_frame_id: camera_fisheye2_f...
 * /camera/realsense2_camera/fisheye2_optical_frame_id: camera_fisheye2_o...
 * /camera/realsense2_camera/fisheye_fps: -1
 * /camera/realsense2_camera/fisheye_frame_id: camera_fisheye_frame
 * /camera/realsense2_camera/fisheye_height: -1
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: -1
 * /camera/realsense2_camera/gyro_fps: -1
 * /camera/realsense2_camera/gyro_frame_id: camera_gyro_frame
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/imu_optical_frame_id: camera_imu_optica...
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra_fps: 30
 * /camera/realsense2_camera/infra_height: 480
 * /camera/realsense2_camera/infra_rgb: False
 * /camera/[33m[ WARN] [1629727382.205630974]: Param '/camera/stereo_module/auto_exposure_limit' has value 0 that is not in range [1, 165000]. Removing this parameter from dynamic reconfigure options.[0m
[33m[ WARN] [1629727382.219615496]: Param '/camera/stereo_module/auto_gain_limit' has value 0 that is not in range [16, 248]. Removing this parameter from dynamic reconfigure options.[0m
[0m[ INFO] [1629727372.815104773]: Initializing nodelet with 4 worker threads.[0m
[0m[ INFO] [1629727374.427416637]: RealSense ROS v2.3.0[0m
[0m[ INFO] [1629727374.427486535]: Built with LibRealSense v2.45.0[0m
[0m[ INFO] [1629727374.427533203]: Running with LibRealSense v2.45.0[0m
[0m[ INFO] [1629727374.489475086]:  [0m
[0m[ INFO] [1629727374.884059066]: Device with serial number 819112071033 was found.
[0m
[0m[ INFO] [1629727374.884141257]: Device with physical ID 2-1.3-3 was found.[0m
[0m[ INFO] [1629727374.885160668]: Device with name Intel RealSense D435 was found.[0m
[0m[ INFO] [1629727374.888717773]: Device with port number 2-1.3 was found.[0m
[0m[ INFO] [1629727374.890394551]: Device USB type: 3.2[0m
[0m[ INFO] [1629727374.891220883]: Resetting device...[0m
[0m[ INFO] [1629727380.947203464]:  [0m
[0m[ INFO] [1629727381.193609034]: Device with serial number 819112071033 was found.
[0m
[0m[ INFO] [1629727381.193699714]: Device with physical ID 2-1.3-5 was found.[0m
[0m[ INFO] [1629727381.193810187]: Device with name Intel RealSense D435 was found.[0m
[0m[ INFO] [1629727381.196604238]: Device with port number 2-1.3 was found.[0m
[0m[ INFO] [1629727381.196880913]: Device USB type: 3.2[0m
[0m[ INFO] [1629727381.209854885]: getParameters...[0m
[0m[ INFO] [1629727381.671189067]: setupDevice...[0m
[0m[ INFO] [1629727381.671371000]: JSON file is not provided[0m
[0m[ INFO] [1629727381.671564287]: ROS Node Namespace: camera[0m
[0m[ INFO] [1629727381.671706323]: Device Name: Intel RealSense D435[0m
[0m[ INFO] [1629727381.671782368]: Device Serial No: 819112071033[0m
[0m[ INFO] [1629727381.671819713]: Device physical port: 2-1.3-5[0m
[0m[ INFO] [1629727381.671853255]: Device FW version: 05.12.13.50[0m
[0m[ INFO] [1629727381.671890600]: Device Product ID: 0x0B07[0m
[0m[ INFO] [1629727381.672005448]: Enable PointCloud: Off[0m
[0m[ INFO] [1629727381.672128785]: Align Depth: Off[0m
[0m[ INFO] [1629727381.672247852]: Sync Mode: Off[0m
[0m[ INFO] [1629727381.672533382]: Device Sensors: [0m
[0m[ INFO] [1629727381.711875778]: Stereo Module was found.[0m
[0m[ INFO] [1629727381.758973953]: RGB Camera was found.[0m
[0m[ INFO] [1629727381.759100519]: (Confidence, 0) sensor isn't supported by current device! -- Skipping...[0m
[0m[ INFO] [1629727381.759163907]: num_filters: 0[0m
[0m[ INFO] [1629727381.759216825]: Setting Dynamic reconfig parameters.[0m
[0m[ INFO] [1629727382.327280696]: Done Setting Dynamic reconfig parameters.[0m
[0m[ INFO] [1629727382.328490632]: depth stream is enabled - width: 640, height: 480, fps: 30, Format: Z16[0m
[0m[ INFO] [1629727382.329796247]: color stream is enabled - width: 640, height: 480, fps: 30, Format: RGB8[0m
[0m[ INFO] [1629727382.329886250]: setupPublishers...[0m
[0m[ INFO] [1629727382.346657894]: Expected frequency for depth = 30.00000[0m
[0m[ INFO] [1629727382.494310970]: Expected frequency for color = 30.00000[0m
[0m[ INFO] [1629727382.584277099]: setupStreams...[0m
[0m[ INFO] [1629727382.607547446]: insert Depth to Stereo Module[0m
[0m[ INFO] [1629727382.607655940]: insert Color to RGB Camera[0m
 23/08 10:03:02,682 WARNING [546928845184] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
[33m[ WARN] [1629727382.807105559]: [0m
[0m[ INFO] [1629727382.733614449]: SELECTED BASE:Depth, 0[0m
[0m[ INFO] [1629727382.791572757]: RealSense Node Is Up![0m
 23/08 10:03:02,809 WARNING [546928845184] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 23/08 10:03:02,861 WARNING [546928845184] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 23/08 10:03:02,914 WARNING [546928845184] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 23/08 10:03:02,965 WARNING [546928845184] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 23/08 10:03:03,108 WARNING [546928845184] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 23/08 10:03:03,159 WARNING [546928845184] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 23/08 10:03:03,210 WARNING [546928845184] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 23/08 10:03:03,262 WARNING [546928845184] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 23/08 10:03:03,316 WARNING [546928845184] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 23/08 10:03:03,471 WARNING [546928845184] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 23/08 10:03:03,522 WARNING [546928845184] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 23/08 10:03:03,675 WARNING [546928845184] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 23/08 10:03:03,726 WARNING [546928845184] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61

**Comment by MartyG-RealSense** [comment]
Thank you very much for the log.  As you are not defining a custom configuration in the roslaunch instruction, have you edited the rs_camera launch file to change its default settings, please?

**Comment by sammar80** [comment]
yes I reduced the depth and the color width to 640 here is my launch file , it was working before I upgrade sdk and the realsense ros to the new 
[rs_camera.txt](https://github.com/IntelRealSense/realsense-ros/files/7032754/rs_camera.txt)

**Comment by sammar80** [comment]
hey @MartyG-RealSense  this shutdown issue also happening when I'm running the realsense-viewer

**Comment by MartyG-RealSense** [comment]
I can't see anything in your custom launch file configuration that would cause a problem.   And as you mention, the RealSense Viewer is causing you shutdown problems too.

What method did you use to install the librealsense SDK and the RealSense ROS wrapper, please?

**Comment by sammar80** [comment]
I follow the build from source instructions for the sdk and I used catkin build for the ros wrapper I tried for the last 3 days many sdk ,ros wrapper and firmware versions using the "sudo apt install " command and also build from source but nothing is working 
https://github.com/IntelRealSense/librealsense/blob/master/doc/installation.md

**Comment by MartyG-RealSense** [comment]
If you are patching the kernel then I wonder whether the problem is occurring at that point, since Jetson has its own L4T-based patching script on Intel's Jetson installation instructions page.

https://dev.intelrealsense.com/docs/nvidia-jetson-tx2-installation#section-building-from-source-using-native-backend

Some Jetson users take the approach of building librealsense from source on Nano using the **RSUSB backend** method, which requires an internet connection but is not dependent on Linux versions or kernel versions and does not require patching.  An RSUSB installation guide that has often worked for Nano users is in the link below

https://github.com/IntelRealSense/librealsense/issues/6964#issuecomment-707501049

**Comment by sammar80** [comment]
Thank you ,I will try that and get back to you

**Comment by sammar80** [comment]
Hi I followed the steps from the links you sent but nothing solves the problem

**Comment by MartyG-RealSense** [comment]
I recalled that there was a past case at https://github.com/IntelRealSense/realsense-ros/issues/1340#issuecomment-676759207 where a computer was shutting down after the launch of a RealSense program.  This case belonged to you and did not have a solution at the end of it.  So can you confirm that you are experiencing the same problem as that previous case, please?

**Comment by sammar80** [comment]
No it is not the same case ,  in my case the nvidia keeps shutting down whenever I launch realsense_ros or run realsense-viewer

**Comment by MartyG-RealSense** [comment]
I have handled a couple of past cases where a Jetson shuts down and reboots immediately after a launch but it is highly rare.  My understanding is that it is related to power supply (specifically, the camera drawing more power than the board can cope with).  

The link below has an example of a case where a Nano was slowing to a crawl or crashing when using the Viewer and roslaunch.  They were powering their board from the micro USB connection but their crashes cleared up when they switched to a 5v 4A power supply.

https://www.jetsonhacks.com/2019/05/16/jetson-nano-realsense-depth-camera/

Intel's own official Jetson instructions for RealSense recommend enabling the barrel jack connector on the Nano.

https://github.com/IntelRealSense/librealsense/blob/master/doc/installation_jetson.md

The barrel jack reference in the instructions recommends looking at the link below:

https://www.jetsonhacks.com/2019/04/10/jetson-nano-use-more-power/

**Comment by sammar80** [comment]
Thank you for the links I checked and I'm using the max power for jetson nano . I installed the sdk and ros wrapper again and they are working only if I'm not using the USB 3 cable 

here is the cpu utilizations when running the camera using USB3 cable
![d435_shutdown_issue](https://user-images.githubusercontent.com/36697148/130664421-7c034e81-b6bd-4188-8fb3-0fac397abdba.png)

logs for camera using USB2 cable
[realsense-ros-log.txt](https://github.com/IntelRealSense/realsense-ros/files/7041114/realsense-ros-log.txt)

**Comment by MartyG-RealSense** [comment]
Your CPU usage percentage is high.  As you are using a Jetson board, when you built librealsense from source did you include the build flag **-DBUILD_WITH_CUDA=true** in the CMake build instruction in order to build the librealense SDK with **CUDA** GPU support?

**Comment by sammar80** [comment]
No currently I installed the precompiled librealsense SDK using these commands 
sudo apt-get install librealsense2-utils
sudo apt-get install librealsense2-dev

**Comment by MartyG-RealSense** [comment]
Thank you.  You mention above that it only works when using a USB2 cable and not with a USB3 cable (hence your providing of a text-file log obtained with a USB2 cable).  I have handled a couple of past cases where this has occurred.

  Is your USB 3 cable a Type C to C (a micro-sized connector on each end) instead of a Type A to Type C (a full-size USB connector on one end to connect to the computer and a micro-sized connector on the other end to plug into the camera).  A RealSense team member advises in https://github.com/IntelRealSense/librealsense/issues/4166#issuecomment-500374449 that some C-to-C cables only provide USB 3 capability in one direction.

**Comment by sammar80** [comment]
I'm using the camera original USB 3 cable type A to Type C

**Comment by MartyG-RealSense** [comment]
I researched the issue on the Nvidia developer forums.  Typically in a case where the Jetson shuts down after commencing streaming, users were referred by forum staff to the **power supply considerations for Jetson Nano** web-page in the link below.

https://forums.developer.nvidia.com/t/power-supply-considerations-for-jetson-nano-developer-kit/71637

**Comment by sammar80** [comment]
Thank you I will see the recommendations from  the link 
@MartyG-RealSense  I really appreciate your supoort

**Comment by MartyG-RealSense** [comment]
Hi @sammar80  Do you have an update about this case that you can provide, please?  Thanks!

**Comment by sammar80** [comment]
Hi @MartyG-RealSense I used a visual preset and disable the  auto exposure the d435 camera is working now with the USB3 cable but the issue now is that it is flickering a lot

**Comment by MartyG-RealSense** [comment]
Thanks very much for the update.  Are you using the camera in a location with ceiling strip lights?

**Comment by sammar80** [comment]
No I am using it in a normal room light and the camera is parallel to the ground

**Comment by MartyG-RealSense** [comment]
Are there manual depth and RGB exposure defined in the visual preset file, please?  The default depth exposure value of the D435 is **8500** and the default RGB exposure is **156**.  If manual exposures are not defined in the preset file then the camera should be using the default values automatically.

**Comment by sammar80** [comment]
I am using the default exposure values for the depth and rgb I just disable the auto exposure

**Comment by MartyG-RealSense** [comment]
Is it the depth or the RGB that is flickering?

**Comment by sammar80** [comment]
sorry @MartyG-RealSense  for the late reply both are flickering but the RGB is flickering more this issue happens when I'm using the ros wrappers but the camera is not flickering  when I use realsense-viewer

**Comment by MartyG-RealSense** [comment]
And the Jetson shuts down again if you re-enable auto-exposure **and** use the visual preset?

**Comment by sammar80** [comment]
yes

**Comment by MartyG-RealSense** [comment]
Did you build the RealSense ROS wrapper from packages (**Method 1**) or from source code (**Method 2**)?

If you did build from source with Method 2: when you have tried different SDK versions, have you rebuilt the wrapper each time that you have changed the librealsense version?  This is something that is necessary to do each time the librealsense version is changed if building the wrapper from source with Method 2. 

It is also important to bear in mind that a particular RealSense ROS wrapper version should ideally be matched with a specific librealsense version listed in the release notes for that wrapper version.  So using different librealsense versions with wrapper version 2.3.0 would have negative consequences, since wrapper 2.3.0 is designed specifically for librealsense 2.45.0.

********

May I also ask whether you are applying different settings (such as auto-exposure enabled / disabled) using the roslaunch instruction or the launch file contents, or whether you are changing settings in the dynamic reconfigure interface after launch.  

https://github.com/IntelRealSense/realsense-ros#set-camera-controls-using-dynamic-reconfigure-params

**Comment by sammar80** [comment]
initially I was trying to build both the librealsense and ros wrapper form source and I was using the compatible versions but eventually I ends up with method 1 using the installation commands  and I got the latest versions (sdk 2.49.0 and ros wrapper 2.3.1 those are the available releases using method 1 )

and for the settings I'm disabling the auto-exposure from realsense-viewer and export the settings then load them through my roslaunch file

**Comment by MartyG-RealSense** [comment]
I reviewed the whole case from the beginning again to look for fresh insights but we have already covered most possibiities.

-  Your Jetson is the only one that I have encountered that shuts itself down when using RealSense, like in your other case at https://github.com/IntelRealSense/realsense-ros/issues/1340#issuecomment-676759207

-  I cannot think of a reason why simply having auto-exposure enabled would make enough difference to the power draw of the camera to cause it to shut down due to insufficient power available.

-  However, in general Jetsons can certainly shut themselves down.  The two main causes are insufficient power or excessive temperature on the Jetson board (e.g the cooling fan is not running fast enough).

-  We covered the power supply aspect in https://github.com/IntelRealSense/realsense-ros/issues/2046#issuecomment-904721016

-  You could try setting the Jetson's fan to run at full speed with the command below to help rule out a temperature related shutdown.

**sudo sh -c 'echo 255 > /sys/devices/pwm-fan/target_pwm'**

**Comment by sammar80** [comment]
Thanks @MartyG-RealSense  I will try the fan settings but this is strange because it was working fine before I upgrad to the new versions of the sdk and ros wrappers

**Comment by MartyG-RealSense** [comment]
You could also test whether there is a problem with the json file exported from the Viewer by using the pre-made **DefaultPreset_D435.json** json file from the Visual Presets documentation, which sets auto-exposure to True.  If the Jetson does not shut down when using that file, it could suggest that there is a problem in your Viewer-exported json.

https://github.com/IntelRealSense/librealsense/wiki/D400-Series-Visual-Presets#preset-table
https://raw.githubusercontent.com/wiki/IntelRealSense/librealsense/d400_presets/DefaultPreset_D435.json

**Comment by sammar80** [comment]
I tried the default presets and also other presets from the link and the same problem is occurring as long the auto exposure is enabled

**Comment by MartyG-RealSense** [comment]
Does enabling just one auto-exposure cause the shutdown, or does it only occur if both auto-exposures are enabled?  For example, if you had RGB auto-exposure enabled but depth exposure disabled, does it still shut down?

**Comment by sammar80** [comment]
it happens when both auto-exposures are enabled but when the depth auto-exposure is disabled and the RGB exposure is enabled it works fine with flickering

**Comment by MartyG-RealSense** [comment]
Thanks for the information.  Does it have the same behavior (works but flickers) if depth auto-exposure is enabled and RGB exposure is disabled?

**Comment by sammar80** [comment]
I didn't try this combination but when I disable both it doesn't work

**Comment by MartyG-RealSense** [comment]
Next, could you try using the rosparam code below to disable a setting called **Auto-Exposure Priority** in the launch file.  This is a separate setting from RGB Auto-Exposure.

When Auto-Exposure is enabled and Auto-Exposure Priority is disabled, the SDK tries to enforce a constant FPS speed instead of allowing FPS to vary.

```
<rosparam>
/camera/rgb_camera/rs435_color_auto_exposure_priority: false
</rosparam>
```

**Comment by sammar80** [comment]
So I should enable the depth auto-exposure and set this parameter in the roslaunch ,is that correct?

**Comment by MartyG-RealSense** [comment]
I suggest setting the parameter in the launch and then testing with depth auto-exposure **disabled** and RGB exposure enabled first (given that enabling depth auto-exposure usually causes a shutdown).  If it does not make a difference, try it again with both depth and RGB auto-exposure enabled.

**Comment by sammar80** [comment]
Thank you @MartyG-RealSense I tried the parameter with auto-exposure disabled/enabled  for the depth and jetson nano didn't shutdown when I enable the depth auto-exposure and it also fixed the depth image flickering still the RGB image flickers

**Comment by MartyG-RealSense** [comment]
Great to hear that you made progress!  Does the flicker of the RGB reduce if you set the color FPS in the launch to **60** instead of 30 and leave depth FPS on 30?  Doing so should help to compensate for the slower speed of the 'rolling' shutter on the D435's RGB sensor compared to the D435 depth sensor's faster 'global' shutter.

**Comment by MartyG-RealSense** [comment]
Hi @sammar80  Do you require further assistance with this case, please?  Thanks!

**Comment by sammar80** [comment]
Hi @MartyG-RealSense sorry for the delayed reply I tried to change the RGB FPS to 60 from the roslaunch file but it doesn't take effect it remains 30 fps

**Comment by MartyG-RealSense** [comment]
In order for a custom configuration to be valid, it must provide three factors - width, height and FPS.  Otherwise, the custom configuration is deemed invalid by the launch and the default stream configuration of the particular camera model is used instead.

Are you able to obtain 60 FPS color if you use the roslaunch instruction below, please?

**roslaunch realsense2_camera rs_camera.launch depth_width:=640 depth_height:=480 depth_fps:=30 color_width:=640 color_height:=480 color_fps:=60**

**Comment by sammar80** [comment]
Thank you very much @MartyG-RealSense that worked fine and the RGB is not flickering any more

**Comment by MartyG-RealSense** [comment]
That's great news, @sammar80 - thanks for the update!   :)

**Comment by sammar80** [comment]
Yes finally  it works fine , thank you @MartyG-RealSense  for your patience and time :)

**Comment by MartyG-RealSense** [comment]
Case closed due to solution achieved and no further comments received.
