### ISSUE TITLE
on the registered depth image from D415 and D435

### ISSUE THREAD

**Issue by ahar** [realsenseai/realsense-ros#2047]
Hi,

I have a basic query. I am using D435 and D415 cameras. If I want to obtain a registered depth image topic, will it be fine to use `rs_camera.launch` only or I need to use `rs_rgbd.launch`? The question is also in connection with using the package [rtabmap_ros](http://wiki.ros.org/rtabmap_ros) that expects registered depth image. Also, how do I verify whether the depth image that I am viewing in `rviz` is registered or not? 

I understand that these questions may sound boring to you, but I need to clear out my doubts.

cheers,

**Comment by MartyG-RealSense** [comment]
Hi @Angit16   Your questions are not boring at all   :)

The term **registered depth** is not used very commonly on this support forum.  My understanding is that it refers to aligning depth to color.  Is that what you are aiming to achieve, please?

If you do wish to perform depth-color alignment with rs_camera.launch then you can set **align_depth** to True in your roslaunch instruction.

**roslaunch realsense2_camera rs_camera.launch align_depth:=true**

When align_depth is True, the additional topics below are published:

/camera/aligned_depth_to_color/image_raw 
/camera/aligned_depth_to_color/camera_info

If you have set RViz to render **/camera/aligned_depth_to_color/image_raw** then you can feel assured that you are publishing depth-color aligned data.

**Comment by ahar** [comment]
Many thanks for the quick response.

Yes, I was trying to mean the same, aligning depth with color. Also, from L96-97 of `rs_rgbd.launch`, `depth_registered` argument is declared. I am trying to relate the same with the registered depth image on `/depth/image` topic from [rtabmap_ros](http://wiki.ros.org/rtabmap_ros).  Can you please confirm if they are the same? Also, how do I find the difference between 
`/camera/aligned_depth_to_color/image_raw`  and ` /camera/depth/image_rect_raw`? They seem to be visibly very similar to each other.

**Comment by MartyG-RealSense** [comment]
As the topic names suggest, **/camera/depth/image_rect_raw** contains purely depth data, whilst **/camera/aligned_depth_to_color/image_raw** is a topic containing color data that is aligned to depth that is only published when align_depth is set to True.

If you literally wanted to compare these two topics to each other using ROS to find differences between them then I do not know of a method for doing so.  The only suggestion that my research could find was to compare them using **message_filters**

https://answers.ros.org/question/321357/testing-node-that-compares-two-topics/

In regard to your rtabmap_ros **/depth/image** topic and relating it to the depth data from D435, the discussion in the link below would seem to be relevant to that question.

https://github.com/introlab/rtabmap_ros/issues/318

**Comment by ahar** [comment]
thank you, it is much clearer now.

**Comment by ahar** [comment]
Hi,
I checked all the published topics upon running `roslaunch realsense2_camera rs_camera.luanch depth_aligned:=true`.It does not work for a gazebo simulation; rather only works when the hardware is connected. Please let me know, if that is not the case. Secondly, the topic `/camera/aligned_depth_to_color/image_raw` (image) when viewed in rviz does not show any color content in it, except the depth image in gray scale. Am I missing something?

**Comment by MartyG-RealSense** [comment]
Hi @Angit16  It is possible to use Gazebo simulation with RealSense ROS.  The links below will hopefully be helpful to you.

https://github.com/rickstaa/realsense-ros-gazebo
https://github.com/IntelRealSense/realsense-ros/issues/1453#issuecomment-736557949

**Comment by MartyG-RealSense** [comment]
Hi @Angit16  Do you require further assistance with this case, please?  Thanks!

**Comment by ahar** [comment]
@MartyG-RealSense no thanks. I'm closing it.

**Comment by MartyG-RealSense** [comment]
Thanks very much @Angit16 for the update!
