### ISSUE TITLE
Add a script for restarting the USB device

### ISSUE THREAD

**Issue by AndyZe** [realsenseai/realsense-ros#205]
We are using our RealSense on a mobile robot platform, which means long cables and lots of motion. The cameras often crash, so we found it convenient to write a C program that finds and restarts all R200 cameras without power cycling them. (It might be more convenient if it were a Python script, but I was in a hurry to get this done and found a decent C template online.) Let me know if this is of interest and where to put it and I'll do a PR. Otherwise, hopefully it inspires something similar.

[reset_r200.c.txt](https://github.com/intel-ros/realsense/files/795138/reset_r200.c.txt)

**Comment by AndyZe** [comment]
To test it, compile:
$ cc reset_r200.c -o reset_r200

Make it executable:
$ chmod +x reset_r200

**Comment by AndyZe** [comment]
Adding a line to kill all zombie R200 processes, based on the process name "nodelet."
[reset_r200.c.txt](https://github.com/intel-ros/realsense/files/815434/reset_r200.c.txt)

**Comment by mattcurfman** [comment]
Hi @AndyZe, it is not normal for R200 cameras to crash, but acknowledge that USB3 devices are more sensitive to long cables, etc.  I'd recommend including your reset utility as a .cpp file in the 'src' directory, and adding the required commands to the CMakeLists.txt file to build it as a standalone reset utility.
