### ISSUE TITLE
IR camera topics not publishing for D415

### ISSUE THREAD

**Issue by ahar** [realsenseai/realsense-ros#2053]
Hello,
 with reference to [this](https://github.com/introlab/rtabmap_ros/issues/565#issuecomment-815762643) link, I tried to obtain IR data from D415 camera. However, I find the following warnings:

`(backend-v4l2.cpp:1358) Pixel format 20303157-0000-0010-8000-00aa003 likely requires patch for fourcc code W10 !`
`(backend-v4l2.cpp:1358) Pixel format 36315752-1a66-a242-9065-d01814a likely requires patch for fourcc code RW16!`
Then,
` 29/08 17:45:11,965 WARNING [139843700741888] (backend-v4l2.cpp:1122) Frames didn't arrived within 5 seconds
`
Also, nothing is publishing on the IR camera topics. Following are the specifications of my OS kernel and other relevant stuff.

ubuntu kernel : 5.4.0-80-generic
librealsense: V2.48

Would you suggest what could be the possible issue here?

thank you,

**Comment by MartyG-RealSense** [comment]
Hi @Angit16  The warning **Pixel format ... likely requires patch for fourcc code W10** suggests that the Ubuntu kernel needs to be patched.  If you built the librealsense SDK from source code and did not patch the kernel, section **4.  Build and apply patched kernel modules** of the SDK source code compilation instructions in the link below explains how to do so for the Ubuntu version that you are using.

https://github.com/IntelRealSense/librealsense/blob/master/doc/installation.md

In regard to the IR topics, if you are attempting to publish those topics in the RealSense ROS wrapper then you can enable them by adding the commands below to your roslaunch instruction:

**enable_infra1:=true enable_infra2:=true**

For example:

**roslaunch realsense2_camera rs_camera.launch enable_infra1:=true enable_infra2:=true**

**Comment by ahar** [comment]
Hello  @MartyG-RealSense 

Thank you for your response. I followed all the steps you mentioned before, already. However, just for my own satisfaction tested it on another system and it worked there. So, I may need to reinstall the kernel patch once again, on the previous system.
One more thing, I noticed that whenever IRs were enabled the depth topic was not getting published. Is it desired?

cheers,

**Comment by MartyG-RealSense** [comment]
Thanks very much @Angit16 for the update.  

Enabling the infrared topics should not prevent the depth topic from being published.

**Comment by ahar** [comment]
Hi @MartyG-RealSense I checked, the depth topics are not publishing when IRs are enabled.

**Comment by MartyG-RealSense** [comment]
There is another case of this problem occurring in https://github.com/IntelRealSense/realsense-ros/issues/1377#issuecomment-693465427

In that particular case the non-publishing of depth was found to be caused by setting different resolutions for the depth and IR topics.  Are you also setting different resolutions for depth and IR, please?

**Comment by ahar** [comment]
resolutions aka width and height of color, depth, and iR are all set the same respectively. 640 x 480

**Comment by MartyG-RealSense** [comment]
Does the launch define height, width **and** FPS for color, depth and IR inside the launch file or in the roslaunch instruction?  If custom definitions for width and height were set but a definition for FPS was not provided then the custom configuration would be deemed invalid and the default configuration of that particular camera model would be applied instead.

**Comment by ahar** [comment]
For convenience, put up the `rs_camera.launch` [here](https://drive.google.com/file/d/1hM-j9kv6179PW-9tQw2m7kFNySg2qlju/view?usp=sharing). The `nodelet.launch.xml` is given [here](https://drive.google.com/file/d/1qfhtftsnDMRKsKrE_aywxpO3EgbbMAjp/view?usp=sharing).

**Comment by MartyG-RealSense** [comment]
Please try the launch instruction below to override the stream definitions in the launch file and enable infra1 and infra2 and set all three stream types to 640x480 and 30 FPS.

**roslaunch realsense2_camera rs_camera.launch depth_width:=640 depth_height:=480 depth_fps:=30 color_width:=640 color_height:=480 color_fps:=30 enable_infra1:=true enable_infra2:=true infra1_width:=640 infra1_height:=480 infra1_fps:=30 infra2_width:=640 infra2_height:=480 infra2_fps:=30**

**Comment by ahar** [comment]
thank you so much, it works. Also, separately checked that the resolution was fine, but the frame rates had to be mentioned explicitly, and passing them works too.

**Comment by MartyG-RealSense** [comment]
You are very welcome, @Angit16 - great to hear that it worked for you   :)
