### ISSUE TITLE
low fps on jetson board

### ISSUE THREAD

**Issue by Jaelly** [realsenseai/realsense-ros#2054]
Xavier Jetson NX / realsense D435i

Hi 
I try checking fps on Xavier with realsense2_camera

I ran roslaunch realsense2_camera rs_rgbd.launch, and I saw color/lmage_raw on the other PC.
But, i got really really low fps. 
How can i enhance the fps?

**Comment by MartyG-RealSense** [comment]
Hi @Jaelly  As you mention seeing the color image on the other PC, are you using a networking connection such as **ssh** to connect remotely from your PC to a Jetson Xavier with the D435i camera attached to it, please?

If you are using networking, slowdown can sometimes occur, especially if using wireless networking (WLAN / wi-fi), as described in the case https://github.com/IntelRealSense/realsense-ros/issues/2052 from this week.

Can you also confirm please that you have installed support for RGBD launch mode if you are using ROS Kinetic, Melodic or Noetic.

**ROS Kinetic**
sudo apt-get install ros-kinetic-rgbd-launch

**ROS Melodic**
sudo apt-get install ros-melodic-rgbd-launch

**ROS Noetic**
sudo apt-get install ros-noetic-rgbd-launch

**Comment by Jaelly** [comment]
Well, I used without ssh. I just match ip address on bash.
And, I have to make without wire on robot, so I used Wifi.

I also had installed RGBD launch.

**Comment by MartyG-RealSense** [comment]
Do you see a positive difference if you turn off wi-fi power saving in Ubuntu with the command below:

**iw dev wlan0 set power_save off**

**Comment by MartyG-RealSense** [comment]
Hi @Jaelly  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.

**Comment by shubham300ska** [comment]
> 

Hi,
I have same issue, I tried With  ssh also. I lunch-roslaunch realsense2_camera rs_camera.launch ,If I rostopic hz  /camera/color/image_raw then -no new messages and launch rviz with command -rosrun rviz rviz i got Image but is in Slow  image status in rviz is 1 image after 9 or 10 second 
![rviz](https://user-images.githubusercontent.com/76483135/149948065-2595fdb8-85e3-4b17-a6a0-73a39ce8a6e6.PNG)

**Comment by MartyG-RealSense** [comment]
Hi @shubham300ska  There was a recent case at https://github.com/IntelRealSense/realsense-ros/issues/2182 where a Jetson NX user could not receive any messages from /camera/color/image_raw when using an ssh connection.

My understanding of the comment https://github.com/IntelRealSense/realsense-ros/issues/2182#issuecomment-989158769 in that discussion is that the RealSense user in the case attributed the problem to use of Ubuntu 20.04 and therefore decided to wait for Nvidia to release a JetPack version that would support Ubuntu 20.04.

Which Ubuntu version are you using, please?
