### ISSUE TITLE
Adding RealSense cameras to transformation tree

### ISSUE THREAD

**Issue by nima-negarandeh** [realsenseai/realsense-ros#2059]
Hi everyone,
I am using ROS Foxy together with D435 and T265 cameras.
I want to add the URDF models of cameras to my main URDF file to build the transformation tree using tf2 and state publisher. I should add that I am working on an actual robot, not a simulation.
How can I do this? Appreciate any help and comment.

**Comment by RealSenseSupport** [comment]
@NimaNGRD I think this question is more related to ROS2. Could you please try to seek more support from ROS2 project? Thanks!

**Comment by RealSenseSupport** [comment]
@NimaNGRD If no other questions this ticket will be closed in 7 days. Thanks!

**Comment by RealSenseSupport** [comment]
@NimaNGRD Since no other questions from your side, we closed this ticket now. Thanks!
