### ISSUE TITLE
/usr/local/lib/librealsense2.so.2.45.0  file does not exist.

### ISSUE THREAD

**Issue by liangchen97** [realsenseai/realsense-ros#2063]
hi,
I have installed librealsense v.2.49.0, and realsense-viewer v2.49.0 runs normally,
but when I follow https://github.com/IntelRealSense/realsense-ros installation instructions,
an error is reported after I run catkin_make :

/usr/local/lib/librealsense2.so.2.45.0
 but this file does not exist.
```nvidia@nvidia-desktop:~/catkin_ws1$ catkin_make clean
Base path: /home/nvidia/catkin_ws1
Source space: /home/nvidia/catkin_ws1/src
Build space: /home/nvidia/catkin_ws1/build
Devel space: /home/nvidia/catkin_ws1/devel
Install space: /home/nvidia/catkin_ws1/install
####
#### Running command: "make cmake_check_build_system" in "/home/nvidia/catkin_ws1/build"
####
-- Using CATKIN_DEVEL_PREFIX: /home/nvidia/catkin_ws1/devel
-- Using CMAKE_PREFIX_PATH: /home/nvidia/catkin_ws/devel;/opt/ros/melodic
-- This workspace overlays: /home/nvidia/catkin_ws/devel;/opt/ros/melodic
-- Using PYTHON_EXECUTABLE: /usr/bin/python2
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: False
-- catkin 0.7.29
-- BUILD_SHARED_LIBS is on
-- BUILD_SHARED_LIBS is on
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 2 packages in topological order:
-- ~~  - realsense2_description
-- ~~  - realsense2_camera
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin package: 'realsense2_description'
-- ==> add_subdirectory(realsense-ros/realsense2_description)
-- +++ processing catkin package: 'realsense2_camera'
-- ==> add_subdirectory(realsense-ros/realsense2_camera)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
CMake Error at /usr/local/lib/cmake/realsense2/realsense2Targets.cmake:92 (message):
  The imported target "realsense2::realsense2" references the file

     "/usr/local/lib/librealsense2.so.2.45.0"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/usr/local/lib/cmake/realsense2/realsense2Targets.cmake"

  but not all the files it references.

Call Stack (most recent call first):
  /usr/local/lib/cmake/realsense2/realsense2Config.cmake:35 (include)
  realsense-ros/realsense2_camera/CMakeLists.txt:44 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/nvidia/catkin_ws1/build/CMakeFiles/CMakeOutput.log".
See also "/home/nvidia/catkin_ws1/build/CMakeFiles/CMakeError.log".
Makefile:1484: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 1
Invoking "make cmake_check_build_system" failed
nvidia@nvidia-desktop:~/catkin_ws1$ 
```
I did delete /usr/local/lib/librealsense2.so.2.45.0
Because after the latest realsense-ros is compiled, there is an API mismatch problem when running (2.45.0and2.49.0)
But I don't understand why the latest ralsense-ros also needs librealsense2.so.2.45.0
What should I do to run realsense-ros under librealsense2.so.2.49.0?

**Comment by MartyG-RealSense** [comment]
Hi @liangchen97   Can you confirm please if you used the instruction **catkin_make clean** as the wrapper instructions specify instead of just 'catkin_make', please?

**Comment by liangchen97** [comment]
Sorry i didn't make it clear.I use catkin_make clean.

**Comment by MartyG-RealSense** [comment]
Thank you for the clarification.  Had you installed SDK 2.45.0 on your computer on a previous occasion before installing 2.49.0 now?

**Comment by liangchen97** [comment]
yes ,but i don't need it now.Did I not delete it cleanly?

**Comment by MartyG-RealSense** [comment]
Did you install the 2.45.0 librealsense SDK with Debian packages?  If so, all librealsense related packages can be uninstalled with the command below.

**dpkg -l | grep "realsense" | cut -d " " -f 3 | xargs sudo dpkg --purge**

**Comment by liangchen97** [comment]
Unfortunately, since I am using nvidia jetson nx, I used the installation script to build the 2.45.0 librealsense SDK before
```
./buildPatchedKernel.sh
./installLibrealsense.sh 
```

**Comment by MartyG-RealSense** [comment]
It looks as though the JetsonHacks method of building with **installLibrealsense.sh** installs the Debian packages, so using the method in https://github.com/IntelRealSense/realsense-ros/issues/2063#issuecomment-913565379 to remove all packages containing the word 'realsense' may still work.

https://github.com/JetsonHacksNano/installLibrealsense/blob/master/installLibrealsense.sh

**Comment by liangchen97** [comment]
I used this command
```dpkg -l | grep "realsense" | cut -d " " -f 3 | xargs sudo dpkg --purge```
 but the problem still exists,   it still links to /usr/local/lib/librealsense2.so.2.45.0 file whitch does not exist.

**Comment by liangchen97** [comment]
My problem is very similar to this issue #1674
The method delete your catkin workspace and create a new one to build in does not work
![Screenshot from 2021-09-06 21-08-46](https://user-images.githubusercontent.com/55865784/132223940-699f0144-d5ae-45b8-abb3-d0efc7d5cf0b.png)

**Comment by MartyG-RealSense** [comment]
The official recommended procedure in the RealSense ROS documentation has the following steps.

1.  Install the librealsense SDK on Jetson using Intel's own Jetson installation guide.

https://github.com/IntelRealSense/librealsense/blob/master/doc/installation_jetson.md

2.  Install the RealSense ROS wrapper from source code with **Method 2.**

https://github.com/IntelRealSense/realsense-ros#step-2-install-intel-realsense-ros-from-sources

You have apparently already successfully achieved step 1 using your own choice of librealsense installation method, as you have said that 2.49.0 is working correctly for you.   And if you are using catkin_make then you are apparently already using Method 2.

There is a complication at this point.  Ideally the RealSense ROS wrapper should be matched with a specific librealsense version that is listed in the wrapper's release notes.  But there is not a ROS wrapper version available for librealsense 2.49.0, as very occasionally a wrapper version is not created for a certain librealsense SDK version.  

At the time of writing this, the latest wrapper version is designed for librealsense 2.48.0.  Using the ROS wrapper designed for 2.48.0 (ROS wrapper version 2.3.1) with 2.49.0 may be possible but not ideal.  The ideal situation would be to have librealsense 2.48.0 installed instead.  Given the complications of installing on Jetson though, it may not be worth the risk of changing librealsense version and causing something to break when it is currently working correctly.

The most straightforward solution to the ROS wrapper installation problem may unfortunately be to just wipe the entire installation (both Ubuntu and librealsense / ROS) and start with a fresh install of the OS that has never had librealsense installed.  But even then, there would still not be a ROS wrapper version available currently that will match with librealsense 2.49.0.

**Comment by liangchen97** [comment]
Thanks for your reply, I understand, I want to try librealsense 2.48.0 and ROS wrapper version 2.3.1 first, because there are some other important files on the device

**Comment by liangchen97** [comment]
I am sorry that I still report the same error under librealsense 2.48.0 version
```
CMake Error at /usr/local/lib/cmake/realsense2/realsense2Targets.cmake:92 (message):
  The imported target "realsense2::realsense2" references the file

     "/usr/local/lib/librealsense2.so.2.45.0"

  but this file does not exist.  Possible reasons include:

  * The file was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and contained

     "/usr/local/lib/cmake/realsense2/realsense2Targets.cmake"
```
Is there any other way besides starting over?

**Comment by MartyG-RealSense** [comment]
Aside from https://github.com/IntelRealSense/realsense-ros/issues/1674 that you linked to earlier in this discussion, the problem is also discussed in https://github.com/IntelRealSense/realsense-ros/issues/832

In that discussion, **Doronhi** the RealSense ROS wrapper developer suggests in https://github.com/IntelRealSense/realsense-ros/issues/832#issuecomment-507995602 to update the librealsense packages with **sudo apt update && sudo apt upgrade**

**Comment by liangchen97** [comment]
I have solved this problem, it seems to be a problem with this command (or the command corresponding to other versions)
```
git checkout `git tag | sort -V | grep -P "^2.\d+\.\d+" | tail -1
```
When i use
```git checkout version number```
After that, there will be no errors

**Comment by MartyG-RealSense** [comment]
Great news @liangchen97 that you resolved your problem - thanks for the update!

**Comment by MartyG-RealSense** [comment]
Case closed due to solution achieved and no further comments received.

**Comment by SherlinSynthicaR** [comment]
Hello MartyG,
while make.. it says lrealsense cannot be found in /usr/bin/ld..
what to do? the realsense.so files seems to be missing.
thank you.

**Comment by MartyG-RealSense** [comment]
Hi @Sashraa   If you are attempting to install librealsense from source code on a Jetson board then the instructions for doing so at https://github.com/IntelRealSense/librealsense/issues/6964#issuecomment-707501049 may be helpful.

Alternatively, you could use the **installLibrealsense.sh** build script at the JetsonHacks website to build the SDK on Jetson from packages instead of source code

https://github.com/jetsonhacks/installRealSenseSDK#installlibrealsensesh

**Comment by SherlinSynthicaR** [comment]
No, I am using bananapi

**Comment by MartyG-RealSense** [comment]
Okay, let's try installing from a build script with the **libuvc backend** installation method at the link below.  That method tends to work well with Pi devices.

https://github.com/IntelRealSense/librealsense/blob/master/doc/libuvc_installation.md

**Comment by SherlinSynthicaR** [comment]
thank you soo much
will try it.

**Comment by SherlinSynthicaR** [comment]
CMake will not be able to correctly generate this project.
this is the error in installing

**Comment by SherlinSynthicaR** [comment]
make: *** [Makefile:149: all] Error 2
this is the error for  ./libuvc_installation.sh
only 55% was built..

**Comment by SherlinSynthicaR** [comment]
kindly suggest on what to do...Thank you

**Comment by MartyG-RealSense** [comment]
If the libuvc backend method does not work then there is a more modern procedure for achieving the same goal that can have a greater chance of success, though it is a little more complicated.  Instructions for building the SDK with the RSUSB backend using CMake by setting the build flag **-DFORCE_RSUSB_BACKEND=true** can be found at https://github.com/IntelRealSense/librealsense/issues/9931#issuecomment-964289692
