### ISSUE TITLE
Problems about "WARNING [139710362011392] (messenger-libusb.cpp:42) control_transfer returned error"

### ISSUE THREAD

**Issue by caobingquan6** [realsenseai/realsense-ros#2069]
My hardware and software are：raspberry pi b4; L515; ubuntu18.04; ros-melodic; librealsense v2.48.0.
I compiled and installed the librealsense source code according to the official installation.md.
I turned on the color camera and depth camera, and obtained point cloud data.

Then I found that when running the ros driver, the following warnings always appear, and the warnings are always generated when the program is running. How can I solve it? What are the consequences of this warning?

It should be noted that this warning will always appear with a certain frequency. The same situation also appeared in my laptop.

The warning is as following:

setting /run_id to ba77cd4c-10a6-11ec-a3d4-e86f3871657f
process[rosout-1]: started with pid [7022]
started core service [/rosout]
process[camera/realsense2_camera_manager-2]: started with pid [7029]
process[camera/realsense2_camera-3]: started with pid [7030]
[ INFO] [1631106882.794241011]: Initializing nodelet with 4 worker threads.
[ INFO] [1631106882.891239873]: RealSense ROS v2.3.1
[ INFO] [1631106882.891274598]: Built with LibRealSense v2.48.0
[ INFO] [1631106882.891290207]: Running with LibRealSense v2.48.0
[ INFO] [1631106882.924400277]:  
 08/09 21:14:42,951 WARNING [139845863200512] (messenger-libusb.cpp:42) control_transfer returned error, index: 300, error: No data available, number: 3d
[ INFO] [1631106883.049419644]: Device with serial number f1230092 was found.

[ INFO] [1631106883.049459559]: Device with physical ID 2-2-3 was found.
[ INFO] [1631106883.049473956]: Device with name Intel RealSense L515 was found.
[ INFO] [1631106883.049884657]: Device with port number 2-2 was found.
[ INFO] [1631106883.049908040]: Device USB type: 3.2
[ INFO] [1631106883.051801826]: getParameters...
[ INFO] [1631106883.106639406]: setupDevice...
[ INFO] [1631106883.106707644]: JSON file is not provided
[ INFO] [1631106883.106745365]: ROS Node Namespace: camera
[ INFO] [1631106883.106788225]: Device Name: Intel RealSense L515
[ INFO] [1631106883.106824313]: Device Serial No: f1230092
[ INFO] [1631106883.106863256]: Device physical port: 2-2-3
[ INFO] [1631106883.106899695]: Device FW version: 01.05.04.01
[ INFO] [1631106883.106935953]: Device Product ID: 0x0B64
[ INFO] [1631106883.106970177]: Enable PointCloud: On
[ INFO] [1631106883.107005373]: Align Depth: Off
[ INFO] [1631106883.107038746]: Sync Mode: On
[ INFO] [1631106883.107133133]: Device Sensors: 
[ INFO] [1631106883.123225313]: L500 Depth Sensor was found.
[ INFO] [1631106883.126527553]: RGB Camera was found.
[ INFO] [1631106883.126653039]: Motion Module was found.
[ INFO] [1631106883.126690469]: Add Filter: pointcloud
[ INFO] [1631106883.127176321]: num_filters: 1
[ INFO] [1631106883.127194696]: Setting Dynamic reconfig parameters.
[ INFO] [1631106883.338576506]: Done Setting Dynamic reconfig parameters.
[ INFO] [1631106883.338917316]: depth stream is enabled - width: 320, height: 240, fps: 30, Format: Z16
[ INFO] [1631106883.340377397]: color stream is enabled - width: 1280, height: 720, fps: 15, Format: RGB8
[ INFO] [1631106883.340438822]: setupPublishers...
[ INFO] [1631106883.343222428]: Expected frequency for depth = 30.00000
[ INFO] [1631106883.382565179]: Expected frequency for color = 15.00000
[ INFO] [1631106883.400003937]: setupStreams...
 08/09 21:14:43,411 WARNING [139845863200512] (messenger-libusb.cpp:42) control_transfer returned error, index: 300, error: No data available, number: 3d
[ INFO] [1631106883.471990612]: insert Depth to L500 Depth Sensor
[ INFO] [1631106883.472088967]: insert Color to RGB Camera
 08/09 21:14:43,474 WARNING [139845863200512] (messenger-libusb.cpp:42) control_transfer returned error, index: 300, error: No data available, number: 3d
 08/09 21:14:43,526 WARNING [139845863200512] (messenger-libusb.cpp:42) control_transfer returned error, index: 300, error: No data available, number: 3d
 08/09 21:14:43,578 WARNING [139845863200512] (messenger-libusb.cpp:42) control_transfer returned error, index: 300, error: No data available, number: 3d
[ INFO] [1631106883.743460129]: SELECTED BASE:Depth, 0
 08/09 21:14:43,759 WARNING [139845863200512] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 08/09 21:14:43,809 WARNING [139845863200512] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 08/09 21:14:43,860 WARNING [139845863200512] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
[ INFO] [1631106883.860519883]: RealSense Node Is Up!
[ WARN] [1631106883.937940720]: 
[ WARN] [1631106883.938005541]: frame's time domain is HARDWARE_CLOCK. Timestamps may reset periodically.
 08/09 21:14:44,211 WARNING [139845863200512] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 08/09 21:14:44,914 WARNING [139845863200512] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 08/09 21:14:46,165 WARNING [139845863200512] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 08/09 21:14:47,416 WARNING [139845863200512] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 08/09 21:14:48,667 WARNING [139845863200512] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 08/09 21:14:49,918 WARNING [139845863200512] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 08/09 21:14:51,168 WARNING [139845863200512] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 08/09 21:14:52,419 WARNING [139845863200512] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 08/09 21:14:53,670 WARNING [139845863200512] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 08/09 21:14:54,921 WARNING [139845863200512] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61

**Comment by MartyG-RealSense** [comment]
Hi @caobingquan6   If the **control_transfer returned** warning is generated a small number of times during launch and then stops, or appears at a rate of once or twice per minute after launch, then it can be safely ignored.  If it generates continuously though then this can indicate that there is a serious communication problem with the device.

Sometimes the warning will generate continuously but data is published normally without negative consequences.  Again, the warning can be ignored if that is the case.

Reducing FPS may reduce the number of warnings that occur.  Please try the pointcloud-enabled roslaunch instruction below that sets both depth and color to 640x480 at 30 FPS.

**roslaunch realsense2_camera rs_camera.launch filters:=pointcloud depth_width:=640 depth_height:=480 depth_fps:=30 color_width:=640 color_height:=480 color_fps:=30**

**Comment by MartyG-RealSense** [comment]
Hi @caobingquan6  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
