### ISSUE TITLE
How to set emitter_enabled to 0?

### ISSUE THREAD

**Issue by abylikhsanov** [realsenseai/realsense-ros#2090]
Hi,

How can I set to 0 the emitter_enabled parameter to 0? (To turn off the emitter completely)
I tried to do:

`<param name="stereo_module/emitter_enabled" type="bool" value="false" />` , but it does not seem to work.

After investigating your code, it seems that there is simply no option for that:
https://github.com/IntelRealSense/realsense-ros/blob/development/realsense2_camera/src/base_realsense_node.cpp#L568

Should I just add options for turning off the emitter there?

I am using ROS Noetic.

**Comment by MartyG-RealSense** [comment]
Hi @abylikhsanov  **Doronhi** the RealSense ROS wrapper developer says in https://github.com/IntelRealSense/realsense-ros/issues/817#issuecomment-813382924 that emitter_enabled needs to be set to '0' instead of 'false' now.

**Comment by stevemartinov** [comment]
Even after setting:
`<param name="stereo_module/emitter_enabled" type="int" value="0" />
`
But it does not seem to work. Did you make it work @abylikhsanov?

**Comment by MartyG-RealSense** [comment]
Hi @abylikhsanov and @stevemartinov  Do either of you require further assistance with this subject, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
