### ISSUE TITLE
roslaunch realsense2_camera  rs_rgbd.launch  rs2::wrong_api_call_sequence_error

### ISSUE THREAD

**Issue by zhangtao7750** [realsenseai/realsense-ros#2092]
when i run roslaunch realsense2_camera  rs_rgbd.launch 
![image](https://user-images.githubusercontent.com/38513722/135204547-9c7b3a0e-5c9b-4e06-80cf-f255ba30fb70.png)
I already rebuild system but still show same error   
looking for help  thanks

**Comment by MartyG-RealSense** [comment]
Hi @zhangtao7750  Have you installed support for RGBD launch mode?  If not and you are using Linux then this can be performed with the instruction below depending on which ROS branch you are using:

**Kinetic**
sudo apt-get install ros-kinetic-rgbd-launch 

**Melodic**
sudo apt-get install ros-melodic-rgbd-launch

**Noetic**
sudo apt-get install ros-noetic-rgbd-launch

Also, which librealsense SDK and RealSense ROS wrapper versions are you using with your D455, please?

**Comment by MartyG-RealSense** [comment]
Hi @zhangtao7750  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
