### ISSUE TITLE
_d415 aluminum material is not loaded on rviz

### ISSUE THREAD

**Issue by ghost** [realsenseai/realsense-ros#2093]
On branch foxy, the _d415 does not load the aluminum material

![image](https://user-images.githubusercontent.com/90186250/135244277-6d175168-ef35-4ed0-8b2e-af0e857e6632.png)

**Comment by MartyG-RealSense** [comment]
Hi @tnajjar  Is this model from the models supplied with the RealSense ROS2 wrapper, please?

https://github.com/IntelRealSense/realsense-ros/tree/ros2/realsense2_description/meshes

**Comment by ghost** [comment]
Hi, sorry I mispoke, I did not clone branch foxy, I have ros-foxy-realsense2-description. To reproduce simply install the package and run ros2 launch realsense2_description view_model.launch.py model:=test_d415_camera.urdf.xacro, you should get the red camera, meaning that the material is not loaded.
To answer your question, I'm not sure if ros-foxy-realsense2-description uses the meshes from the ros2 branch or the foxy branch but you probably know that.

**Comment by MartyG-RealSense** [comment]
I will highlight your issue to **Doronhi** the RealSense ROS wrapper developer.  Thanks for the report!

**Comment by doronhi** [comment]
Thanks for noticing and reporting. Fixed in #2098.

**Comment by ghost** [comment]
Was just about to open a PR, lgtm, thanks a lot!

**Comment by MartyG-RealSense** [comment]
Hi @tnajjar  Do you require further assistance with this case, please?  Thanks!

**Comment by tonynajjar** [comment]
It should be fixed with the PR @doronhi linked. Would just like to know when is it expected to be merged and consequently when should the patch be available via apt?

**Comment by MartyG-RealSense** [comment]
@tonynajjar  I have passed your follow-up question above to @doronhi

**Comment by doronhi** [comment]
I merged it now. I was looking to have some approvement really.
Regarding the debian, Librealsense2 version 2.50.0 is due in about 2 weeks. The release for realsense-ros should follow closely.

**Comment by ghost** [comment]
Oh sorry didn't know you were waiting for an approval. Anyway thanks a lot
