### ISSUE TITLE
Turtlebot3 simulation with D435

### ISSUE THREAD

**Issue by ChenJiajun0011** [realsenseai/realsense-ros#2109]
Hi, everyone. This is my first issue in github:P. I am quite a freshman in ROS. I am now combining the turtlebot3 pi with D435 in the simulation environment(Gazebo). I spent days trying to figure out how to change the publishing topics from D435. Actually, I am running the demo from this link: https://github.com/takanotume24/turtlebot3_simulations
How could I get other topics for example like "aligned_depth_to_color". Because I want to find a detected object in this aligned depth to color frame and output the depth of its center. I hope I have explained my question well. Thanks for helping!

**Comment by MartyG-RealSense** [comment]
Hi @ChenJiajun0011   There is an interesting looking RealSense Gazebo plugin for D435 and D435i in the link below that combines the RealSense ROS wrapper and a Gazebo plugin in a single package to enable use with both real and simulated cameras.

https://github.com/rickstaa/realsense-ros-gazebo

The incorporation of the RealSense ROS wrapper may suggest that the **align_depth** command which provides aligned depth topics may be accessible in a Gazebo simulation.  I have not used this plugin, so cannot confirm in advance whether it supports alignment in Gazebo simulation.

The author of this Gazebo project provides a link to a YouTube explanation video in https://github.com/IntelRealSense/realsense-ros/issues/1453#issuecomment-736557949

*************

An alternative approach in https://github.com/IntelRealSense/realsense-ros/issues/714#issuecomment-681320162 by a user of a RealSense Gazebo plugin that did not support align_depth was to set the horizntal field of view (FOV) of the depth and RGB cameras to the same value (probably doing this in their simulation).

**Comment by ChenJiajun0011** [comment]
@MartyG-RealSense Thanks for your sources! when I use an actual camera, I can use the command `aligned_color_frame = aligned_frames.get_color_frame() aligned_depth_frame = aligned_frames.get_depth_frame()` to finish object detection in the aligned color frame and find out the object center distance in the aligned depth frame.
When it comes to the simulation environment, it seems that we could use the command "roslaunch realsense2_camera rs_camera.launch align_depth:=true" to turn on the aligned_depth_to_color topics when we only launch a single D435 model, but there is no way to set this align_depth topics to be true when we combine the D435 model together with a robot in the Gazebo. Right?

**Comment by MartyG-RealSense** [comment]
My knowledge of Gazebo is admittedly limited.   If your problem is getting the simulated D435 camera to move with the simulated robot, I wonder whether you could attach the two models together in the Gazebo simulation using the instructions in the link below.

http://gazebosim.org/tutorials/?tut=add_laser

**Comment by ChenJiajun0011** [comment]
> My knowledge of Gazebo is admittedly limited. If your problem is getting the simulated D435 camera to move with the simulated robot, I wonder whether you could attach the two models together in the Gazebo simulation using the instructions in the link below.
> 
> http://gazebosim.org/tutorials/?tut=add_laser

Hi @MartyG-RealSense really appreciate your help. I think I may try to set the FOV of the RGB and Depth cameras to the same value. Since I can use the align_depth in a real camera, it would not be a big problem to make this compromise in the simulation environment.

**Comment by MartyG-RealSense** [comment]
Hi @ChenJiajun0011  Do you have an update about this case that you can provide, please?  Thanks!

**Comment by ChenJiajun0011** [comment]
Hi @MartyG-RealSense Nothing else, thanks a lot.

**Comment by MartyG-RealSense** [comment]
You are very welcome, @ChenJiajun0011 - thanks very much for the update!
