### ISSUE TITLE
Error with realsense-ros

### ISSUE THREAD

**Issue by JimXu1989** [realsenseai/realsense-ros#2110]
Thanks for the great work, but I meet some error:
... logging to /home/jim/.ros/log/25ee4844-2a65-11ec-9a28-3d93e8db1d26/roslaunch-jim-AERO-15-X9-1037297.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://jim-AERO-15-X9:42805/

SUMMARY
========

PARAMETERS
 * /camera/realsense2_camera/accel_fps: -1
 * /camera/realsense2_camera/accel_frame_id: camera_accel_frame
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: False
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/allow_no_texture_points: False
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/calib_odom_file: 
 * /camera/realsense2_camera/clip_distance: -2.0
 * /camera/realsense2_camera/color_fps: -1
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: -1
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: -1
 * /camera/realsense2_camera/confidence_fps: -1
 * /camera/realsense2_camera/confidence_height: -1
 * /camera/realsense2_camera/confidence_width: -1
 * /camera/realsense2_camera/depth_fps: -1
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: -1
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: -1
 * /camera/realsense2_camera/device_type: 
 * /camera/realsense2_camera/enable_accel: False
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_confidence: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye1: False
 * /camera/realsense2_camera/enable_fisheye2: False
 * /camera/realsense2_camera/enable_fisheye: False
 * /camera/realsense2_camera/enable_gyro: False
 * /camera/realsense2_camera/enable_infra1: False
 * /camera/realsense2_camera/enable_infra2: False
 * /camera/realsense2_camera/enable_infra: False
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_pose: False
 * /camera/realsense2_camera/enable_sync: False
 * /camera/realsense2_camera/filters: 
 * /camera/realsense2_camera/fisheye1_frame_id: camera_fisheye1_f...
 * /camera/realsense2_camera/fisheye1_optical_frame_id: camera_fisheye1_o...
 * /camera/realsense2_camera/fisheye2_frame_id: camera_fisheye2_f...
 * /camera/realsense2_camera/fisheye2_optical_frame_id: camera_fisheye2_o...
 * /camera/realsense2_camera/fisheye_fps: -1
 * /camera/realsense2_camera/fisheye_frame_id: camera_fisheye_frame
 * /camera/realsense2_camera/fisheye_height: -1
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: -1
 * /camera/realsense2_camera/gyro_fps: -1
 * /camera/realsense2_camera/gyro_frame_id: camera_gyro_frame
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/imu_optical_frame_id: camera_imu_optica...
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra_fps: 30
 * /camera/realsense2_camera/infra_height: 480
 * /camera/realsense2_camera/infra_rgb: False
 * /camera/realsense2_camera/infra_width: 848
 * /camera/realsense2_camera/initial_reset: False
 * /camera/realsense2_camera/json_file_path: 
 * /camera/realsense2_camera/linear_accel_cov: 0.01
 * /camera/realsense2_camera/odom_frame_id: camera_odom_frame
 * /camera/realsense2_camera/ordered_pc: False
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/pose_frame_id: camera_pose_frame
 * /camera/realsense2_camera/pose_optical_frame_id: camera_pose_optic...
 * /camera/realsense2_camera/publish_odom_tf: True
 * /camera/realsense2_camera/publish_tf: True
 * /camera/realsense2_camera/rosbag_filename: 
 * /camera/realsense2_camera/serial_no: 
 * /camera/realsense2_camera/stereo_module/exposure/1: 7500
 * /camera/realsense2_camera/stereo_module/exposure/2: 1
 * /camera/realsense2_camera/stereo_module/gain/1: 16
 * /camera/realsense2_camera/stereo_module/gain/2: 16
 * /camera/realsense2_camera/tf_publish_rate: 0.0
 * /camera/realsense2_camera/topic_odom_in: odom_in
 * /camera/realsense2_camera/unite_imu_method: 
 * /camera/realsense2_camera/usb_port_id: 
 * /rosdistro: noetic
 * /rosversion: 1.15.13

NODES
  /camera/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)

auto-starting new master
process[master]: started with pid [1037359]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 25ee4844-2a65-11ec-9a28-3d93e8db1d26
process[rosout-1]: started with pid [1037403]
started core service [/rosout]
process[camera/realsense2_camera_manager-2]: started with pid [1037410]
process[camera/realsense2_camera-3]: started with pid [1037411]
[ INFO] [1633937446.799375527]: Initializing nodelet with 12 worker threads.
[ INFO] [1633937446.943692041]: RealSense ROS v2.3.1
[ INFO] [1633937446.943876396]: Built with LibRealSense v2.48.0
[ INFO] [1633937446.944006667]: Running with LibRealSense v2.48.0
[ INFO] [1633937446.990277839]:  
[ INFO] [1633937447.212530948]: Device with serial number 838212074467 was found.

[ INFO] [1633937447.212626507]: Device with physical ID 2-3-5 was found.
[ INFO] [1633937447.212665692]: Device with name Intel RealSense D435 was found.
[ INFO] [1633937447.213737587]: Device with port number 2-3 was found.
[ INFO] [1633937447.213815279]: Device USB type: 3.2
[ INFO] [1633937447.219534596]: getParameters...
[ INFO] [1633937447.294973571]: setupDevice...
[ INFO] [1633937447.295002344]: JSON file is not provided
[ INFO] [1633937447.295041036]: ROS Node Namespace: camera
[ INFO] [1633937447.295051712]: Device Name: Intel RealSense D435
[ INFO] [1633937447.295059652]: Device Serial No: 838212074467
[ INFO] [1633937447.295104588]: Device physical port: 2-3-5
[ INFO] [1633937447.295119209]: Device FW version: 05.12.15.50
[ INFO] [1633937447.295127775]: Device Product ID: 0x0B07
[ INFO] [1633937447.295135524]: Enable PointCloud: Off
[ INFO] [1633937447.295156660]: Align Depth: Off
[ INFO] [1633937447.295190449]: Sync Mode: Off
[ INFO] [1633937447.295239861]: Device Sensors: 
[ INFO] [1633937447.310856634]: Stereo Module was found.
[ INFO] [1633937447.318487537]: RGB Camera was found.
[ INFO] [1633937447.318522361]: (Confidence, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1633937447.318536816]: num_filters: 0
[ INFO] [1633937447.318547371]: Setting Dynamic reconfig parameters.
[ WARN] [1633937447.765089121]: Param '/camera/stereo_module/auto_exposure_limit' has value 0 that is not in range [1, 165000]. Removing this parameter from dynamic reconfigure options.
[ WARN] [1633937447.778158550]: Param '/camera/stereo_module/auto_gain_limit' has value 0 that is not in range [16, 248]. Removing this parameter from dynamic reconfigure options.
[ INFO] [1633937447.813698466]: Done Setting Dynamic reconfig parameters.
[ INFO] [1633937447.814150867]: depth stream is enabled - width: 848, height: 480, fps: 30, Format: Z16
[ INFO] [1633937447.814604051]: color stream is enabled - width: 640, height: 480, fps: 30, Format: RGB8
[ INFO] [1633937447.814620460]: setupPublishers...
[ INFO] [1633937447.816106797]: Expected frequency for depth = 30.00000
[ INFO] [1633937447.838723856]: Expected frequency for color = 30.00000
[ INFO] [1633937447.855072071]: setupStreams...
[ INFO] [1633937447.877337273]: insert Depth to Stereo Module
[ INFO] [1633937447.877464302]: insert Color to RGB Camera
[ INFO] [1633937447.976790550]: SELECTED BASE:Depth, 0
[ INFO] [1633937447.985952011]: RealSense Node Is Up!
[ WARN] [1633937448.097216085]: 
 11/10 15:30:48,098 WARNING [140479542728448] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 11/10 15:30:48,148 WARNING [140479542728448] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 11/10 15:30:48,200 WARNING [140479542728448] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 11/10 15:30:48,369 WARNING [140479542728448] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61

No gui show up, after I run: roslaunch realsense2_camera rs_camera.launch, it seems the sensor already been detected.
How should I do to solve this problem? Thanks a lot!

**Comment by MartyG-RealSense** [comment]
Hi @JimXu1989  Have you entered the command **rosrun rviz rviz** into the ROS terminal to launch RViz to see the data rendered visually, please?

**Comment by MartyG-RealSense** [comment]
Hi @JimXu1989  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
