### ISSUE TITLE
parameter base_frame_id not changing coordinates

### ISSUE THREAD

**Issue by ExordiumAndTerminus** [realsenseai/realsense-ros#2118]
Hello,

I can't figure out how to change the coordinate frame for the imu for my d435i.  I saw in the Read Me that the parameter 'base_frame_id' is supposed to 'defines the frame_id all static transformations refers to.'  However, when I change the orientation of the 'base_frame_id' using my robot's xacro file, the coordinates remain the same, no matter what rotation I apply to the 'base_frame_id'.  I would like the z axis to be the axis displaying the acceleration due to gravity, vs the y as it is right now.  Can this be done or is there a bug I am unaware of?

Edit: to clarify: I am referring to when doing a rostopic echo /camera/imu, the linear acceleration is permanently in the 'y' axis, no matter what I set the base_frame_id orientation to.  Shouldn't this change when the base_frame_id is changed to a different orientation??

Thanks!
- Max

**Comment by MartyG-RealSense** [comment]
Hi @ExordiumAndTerminus  I am not aware of an occasion when acceleration under gravity has been represented by anything other than Y.

In https://github.com/IntelRealSense/librealsense/issues/4391#issuecomment-515894672 a RealSense team member advises that IMU acceleration values do not have a relation to orientation, which is based on gyro velocities.

**Comment by MartyG-RealSense** [comment]
Hi @ExordiumAndTerminus  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
