### ISSUE TITLE
can't find /camera/infra topic

### ISSUE THREAD

**Issue by Hcnaeg** [realsenseai/realsense-ros#2120]
hi, I'm using the realsense realsense ros v2.3.1/librealsense 2.49.0/D435i/ubuntu 20.04, but when I use rostopic list command, I can't find the following topic, which is expeted as some blogs indicated:

/camera/infra1/camera_info
/camera/infra1/image_rect_raw
/camera/infra2/camera_info
/camera/infra2/image_rect_raw

I've set enable-infra1 and enable-infra2 to true, but it dosen't work.
I'm a beginner in realsense-ros, please leave a comment if more info needed

**Comment by MartyG-RealSense** [comment]
Hi @Hcnaeg   Can you confirm please whether the infrared topics are published if you use the roslaunch instruction below.

**roslaunch realsense2_camera rs_camera.launch enable_infra1:=true enable_infra2:=true**

**infra2** is not available on a USB 2.1 camera connection as it requires USB 3.

**Comment by Hcnaeg** [comment]
I reinstalled realsense-ros and then the I could find the expected topic..maybe I did something wrong at the first installation. @MartyG-RealSense thank you!

**Comment by MartyG-RealSense** [comment]
You are very welcome, @Hcnaeg - it's great to hear that you solved the issue.  Thanks for the update!
