### ISSUE TITLE
How to fix the frame in PontCloud2..?

### ISSUE THREAD

**Issue by pinnakarahul** [realsenseai/realsense-ros#2124]
I am using Radar.
My problem is in Global Status I am getting error in fixed frame as show in figure..
![image](https://user-images.githubusercontent.com/29915801/137890156-b7748317-4f30-43d1-b1f1-164f7f48da9e.jpeg)

**Comment by MartyG-RealSense** [comment]
Hi @pinnakarahul  Can you confirm whether the 'radar' camera that you are using is the **RealSense L515** camera model please?

If it is a RealSense camera model with an IMU component, such as the L515, then does the Fixed Frame issue become resolved if you enable the IMU gyro and accel topics by adding the commands below onto the end of your roslaunch instruction?

**enable_gyro:=true enable_accel:=true**

For example:

**roslaunch realsense2_camera opensource_tracking.launch enable_gyro:=true enable_accel:=true**

**Comment by pinnakarahul** [comment]
Thank you for response @MartyG-RealSense 
In my case no camera is used.
I had only  radar.

**Comment by MartyG-RealSense** [comment]
As there is not a RealSense camera involved, I wonder whether a general guide to using a radar with RViz may be more suitable for you, such as the guide published by ROS in the link below where Fixed Frame is set to **odom**

https://navigation.ros.org/setup_guides/sensors/setup_sensors.html

**Comment by pinnakarahul** [comment]
The following is my code..
can you suggest any changes.? 


#!/usr/bin/env python3
import rospy
from continental_radar_ros.msg import Cluster_1_General
from sensor_msgs import point_cloud2
from sensor_msgs.msg import PointCloud2, PointField
from std_msgs.msg import Header
import struct

fields = [PointField('x', 0, PointField.FLOAT32, 1),
          PointField('y', 4, PointField.FLOAT32, 1),
          PointField('z', 8, PointField.FLOAT32, 1),
          PointField('rgba', 12, PointField.UINT32, 1)]

def suscriber(msg):
    header = Header()
    header.frame_id = "map"
    points = []
    r = int((msg.Cluster_RCS+64)*2)
    g = int((msg.Cluster_RCS+64)*2)
    b = int((msg.Cluster_RCS+64)*2)
    a = 255
    #print(r, g, b, a)
    rgb = struct.unpack('I', struct.pack('BBBB', b, g, r, a))[0]
    #print hex(rgb)
    points.append([msg.Cluster_DistLong, msg.Cluster_DistLat,0,rgb])
    pc2 = point_cloud2.create_cloud(header, fields, points)
    pc2.header.stamp = rospy.Time.now()
    pub.publish(pc2)
    

if __name__ == '__main__':
    rospy.init_node('radar_pointCloud2_converter')
    pub = rospy.Publisher("point_cloud2", PointCloud2, queue_size=10)
    rospy.Subscriber('/Cluster_1_General',Cluster_1_General,suscriber)
    while not rospy.is_shutdown():
        rospy.sleep(1.0)

**Comment by MartyG-RealSense** [comment]
As RealSense cameras are not involved in your project, I do not have advice that I can provide about your project unfortunately.  The **ROS Answers** official ROS support forum will be a better place to post your question.

https://answers.ros.org/questions/

**Comment by MartyG-RealSense** [comment]
Case closed due to ROS Answers being the appropriate support location.
