### ISSUE TITLE
How to change the ordered_pc parameter after launch?

### ISSUE THREAD

**Issue by DanielSchimpf** [realsenseai/realsense-ros#2126]
Hello,

For my application, I need to use the ordered point cloud at the beginning, but then want to switch to the unordered one because of the color alignment.

I can switch between ordered and unordered at launch by using these launch settings. 
```
    <include file="$(find realsense2_camera)/launch/rs_camera.launch">
    <arg name="filters" value="pointcloud" />
    <arg name="ordered_pc" value="false" />
      </include>
```
But I don't know how to switch after I launched.

I have seen that dynamic configure can be used by I was not able to get it to work. The "`/camera/pointcloud/set_parameters`" service does not know the parameter ordered_pc. None of the other "`/camera/.../set_parameters`" services worked either.

This is the command I tried: `rosrun dynamic_reconfigure dynparam set /camera/pointcloud ordered_pc false`

Can someone show me how to do it correctly?

Thanks!

**Comment by MartyG-RealSense** [comment]
Hi @DanielSchimpf  If you open the visual interface for dynamic reconfigure with the command **rosrun rqt_reconfigure rqt_reconfigure** then can the ordered_pc option be found by expanding open the /camera/depth option to **/camera/depth/color/points** (since that is the topic created by using the pointcloud filter).

![image](https://user-images.githubusercontent.com/41145062/138086361-49bb02be-f070-4959-8a7b-b30fa3c46c6f.png)

**Comment by DanielSchimpf** [comment]
Thanks for the quick reply.
I cannot find an option for ordered_pc under the depth or point cloud header (see screenshot below) or any of the other headers.
![image](https://user-images.githubusercontent.com/35684514/138107974-491c51df-a1c0-4765-8306-d64e58629bf8.png)

**Comment by MartyG-RealSense** [comment]
Thanks very much @DanielSchimpf for checking.  I will highlight your case to **Doronhi** the RealSense ROS wrapper developer to seek their advice.

**Comment by doronhi** [comment]
Hi @DanielSchimpf ,
The current implementation does not offer the option to change ordered_pc during runtime. From a glimpse in the code, I don't see a significate reason that prevents such an option, the parameter is just not exposed that way.
Could you elaborate on your needs and the issue with the color alignment?

**Comment by MartyG-RealSense** [comment]
Hi @DanielSchimpf  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
