### ISSUE TITLE
Reading camera parameters from a file ROS Melodic

### ISSUE THREAD

**Issue by j-corvo** [realsenseai/realsense-ros#2130]
Hello,

I'm currently using a six camera setup plugged in a jetson AGX xavier, running ubuntu 18.04 with ROS Melodic. I would like to know if it's possible to have a separate yaml file to be loaded on a launch file, for each camera where I can tweak the parameters.
I know it's possible in ROS2 but I'm not sure about ROS1.

Thanks in advance for your help!

**Comment by MartyG-RealSense** [comment]
Hi @rythm07  The link below has a tutorial about using yaml files in ROS1 Melodic.

https://roboticsbackend.com/ros-param-yaml-format/

The section of the guide about loading yaml into a launch file is here:

https://roboticsbackend.com/ros-param-yaml-format/#In_a_launch_file

**Comment by j-corvo** [comment]
Yes, thanks a lot for your insight, but my question is if it's possible to load a yaml file when launching your cameras, like when launching the rs_camera.launch for example?

**Comment by MartyG-RealSense** [comment]
What I was suggesting is whether you can load a yaml file when performing rs_camera.launch by editing the rs_camera.launch file with a text editor tool to create a custom version of it that includes the 'file' rosparam referenced in the guide that I linked to.

`<rosparam file="$(find my_custom_package)/config/my_params.yaml" />`

**Comment by j-corvo** [comment]
Oh ok sorry, I didn't understand what you've said but now I understand! I will do it then.
Thanks a lot for your help!
