### ISSUE TITLE
should foxy and ros2 branches merge?

### ISSUE THREAD

**Issue by JHPHELAN** [realsenseai/realsense-ros#2133]
The ros2 and foxy branches are similar but different.  Should they be the same?

RealSense ros2 wrapper: foxy vs ros2

**foxy**
https://github.com/IntelRealSense/realsense-ros/tree/foxy
This branch is 132 commits ahead, 207 commits behind development.
This version supports ROS2 foxy on Ubuntu 20.04.
Install ROS2 foxy, on Ubuntu 20.04.
	sudo apt install ros-$ROS_DISTRO-ros-base		**_[I want ros-desktop]_**
Step 2: Install librealsense2:
	Install from Debian Package - In that case treat yourself as a developer. Make sure you follow the instructions to also install librealsense2-dev and librealsense-dkms packages.       **_[the directions aren't clear as to how to do this]_**
Or
	Build from sources by downloading the latest Intel® RealSense™ SDK 2.0 and follow the instructions under Linux Installation

Step 3: Install Intel® RealSense™ ROS2 wrapper from Sources
	Same as ros2

**ros2**
https://github.com/IntelRealSense/realsense-ros/tree/ros2
This branch is 244 commits ahead, 207 commits behind development.
This version supports ROS2 Dashing, Eloquent and Foxy.
Install ROS2 Dashing, on Ubuntu 18.04 or ROS2 Foxy, on Ubuntu 20.04
There are 2 sources to install realsense2_camera from:
	Method 1: The ROS distribution:
		sudo apt-get install ros-$ROS_DISTRO-realsense2-camera
		This will install both realsense2_camera and its dependents, including librealsense2 library and matching udev-rules.
	The version of librealsense2 is almost always behind the one availeable in RealSense™ official repository.
or
	Method 2: The RealSense™ distribution:
	Step 1: Install the latest Intel® RealSense™ SDK 2.0
		Install librealsense2 debian package:
			Jetson users - use the Jetson Installation Guide
			Otherwise, install from Linux Debian Installation Guide
			In that case treat yourself as a developer. Make sure you follow the instructions to also install librealsense2-dev and librealsense2-dkms packages.
		Or
			Build from sources by downloading the latest Intel® RealSense™ SDK 2.0 and follow the instructions under Linux Installation
_**[Jumps here from Step 1 to Step 3]**_
Step 3: Install Intel® RealSense™ ROS2 wrapper from Sources
	same as foxy

**Comment by MartyG-RealSense** [comment]
Hi @JHPHELAN  From ROS2 wrapper version **3.1.5** in March 2021, Dashing, Eloquent and Foxy are supported with a single wrapper (previously, there were two separate wrappers for Eloquent and Foxy).  Support for Galactic and Rolling was added in **3.2.2**.  This ROS2 wrapper is linked to from the front page of the wrapper documentation.

![image](https://user-images.githubusercontent.com/41145062/138646864-b33c8438-ee29-4007-a93a-1bc451639966.png)

The **ROS2** wrapper is therefore the one that should be used and not the older Foxy wrapper and so there is no need for a merge.

**Comment by MartyG-RealSense** [comment]
Hi @JHPHELAN  Do you require further assistance with this case, please?  Thanks!

**Comment by JHPHELAN** [comment]
@MartyG-RealSense 
I don't need any assistance but it seems if the ros2 branch supersedes the foxy branch that the foxy branch should be eliminated.

**Comment by MartyG-RealSense** [comment]
The old deprecated wrapper was created by a different group of developers to the current wrapper and it is part of the main Intel GitHub rather than the 'RealSense ROS' GitHub that the current wrapper is hosted on.  As far as I am aware, the administrator of the current RealSense ROS GitHub does not have administrative powers over the old one.

**Comment by MartyG-RealSense** [comment]
Hi @JHPHELAN  Do you require further assistance with this case, please?  Thanks!

**Comment by JHPHELAN** [comment]
@MartyG-RealSense Not on this one, thanks!

**Comment by MartyG-RealSense** [comment]
Thanks very much @JHPHELAN for the update!  As you do not require further assistance, I will close this case.  Thanks again!

**Comment by Bart-van-Ingen** [comment]
Hi Marty G,

From this thread I am getting the feeling that you are confusing the **branch** of this repo OP is referring to called 'foxy' and the deprecated intel realsense repo  ([https://github.com/intel/ros2_intel_realsense](https://github.com/intel/ros2_intel_realsense)).

Considering this, is it preferential to use the foxy release (build 3.2.0) of this repo when using ros2 foxy, opposed to using the ros2 branch of this repo?

**Comment by MartyG-RealSense** [comment]
Hi @Bart-van-Ingen   Reading through the whole case in a single sitting, it does seem as though the question was about the old Foxy branch of the current ROS2 wrapper.  Thanks very much for pointing this out.

![image](https://user-images.githubusercontent.com/41145062/141781070-16d73d12-f28a-41e9-9709-8051aab4a5e3.png)

The **ros2** branch is the most recent wrapper.  There used to be individual wrappers for different ROS2 versions but now there is a single wrapper for Dashing, Eloquent, Foxy, Rolling and Galactic and so I recommend using that single unified wrapper.  If you look at the older dedicated Foxy branch, you can see that the files have not been updated for some months.

![image](https://user-images.githubusercontent.com/41145062/141781872-7a8dbf61-ae80-4be8-9b7b-fc33a1dec4b2.png)

**Comment by Bart-van-Ingen** [comment]
No problem! thanks for answering.

**Comment by doronhi** [comment]
I just removed the deprecated foxy branch to save future misunderstandings.
