### ISSUE TITLE
Some errors  about   " roslaunch realsense2_camera rs_camera.launch"

### ISSUE THREAD

**Issue by zw-nuist-176** [realsenseai/realsense-ros#2134]
bug1、
```
[camera/realsense2_camera_manager-2] process has died [pid 30838, exit code 127, cmd /opt/ros/melodic/lib/nodelet/nodelet manager __name:=realsense2_camera_manager __log:=/home/z/.ros/log/8c7e9934-359a-11ec-a575-b8c385483d7d/camera-realsense2_camera_manager-2.log].
log file: /home/z/.ros/log/8c7e9934-359a-11ec-a575-b8c385483d7d/camera-realsense2_camera_manager-2*.log
![2021-10-25 21-17-19 的屏幕截图](https://user-images.githubusercontent.com/73625146/138710010-e73dd6a3-bdb9-4b24-8dde-5ac8164d07bb.png)
![2021-10-25 22-01-17 的屏幕截图](https://user-images.githubusercontent.com/73625146/138710022-635501a4-ceda-4c19-85f7-039ec926d072.png)
![2021-10-25 22-01-25 的屏幕截图](https://user-images.githubusercontent.com/73625146/138710024-e316e239-a941-4dec-aa3e-3fb41d63ad1c.png)
![2021-10-25 22-01-28 的屏幕截图](https://user-images.githubusercontent.com/73625146/138710030-25aa5772-db6c-4fc3-b4a0-7f895df3f1e0.png)
![2021-10-25 22-02-03 的屏幕截图](https://user-images.githubusercontent.com/73625146/138710035-d2f4a291-997a-4850-93b2-bfba54662726.png)

```
The version is correct. See the screenshot for specific problems. I hope to get your help.
wish you can slove my issues.

**Comment by MartyG-RealSense** [comment]
Hi @zw-nuist-176  The error **undefined symbol: _ZN20ddynamic_reconfigure** can indicate that more than one installation of **ddynamic_reconfigure** is present on your computer, as described in https://github.com/IntelRealSense/realsense-ros/issues/838

Performing a clean build like in https://github.com/IntelRealSense/realsense-ros/issues/838#issuecomment-817294116 is the solution that RealSense ROS users have typically reported as resolving this problem.

For easy reference, I have posted below the image of your error that you kindly provided.

![image](https://user-images.githubusercontent.com/41145062/138716871-7ad59b19-b43d-4426-a378-6d5109449090.png)

**Comment by zw-nuist-176** [comment]
@MartyG-RealSense
 Thank you for your help. I deleted it and recompiled it. It can run normally. Thank you very much。

**Comment by MartyG-RealSense** [comment]
You are very welcome, @zw-nuist-176 - thanks very much for the update about your success!

**Comment by MartyG-RealSense** [comment]
Case closed due to solution achieved and no further comments received.
