### ISSUE TITLE
No message passing through rosout from rs_launch.py

### ISSUE THREAD

**Issue by JamesChooWK** [realsenseai/realsense-ros#2139]
Hi, I recently discovered that when I launched the `rs_launch.py` file. No logs message are passing into the `/rosout `topic, however, I can see all the messages showing on the terminal like what I show below.
![Screenshot from 2021-10-26 16-38-04](https://user-images.githubusercontent.com/46285293/138901943-ab67f6ec-a4e8-41e3-b131-c1354ba55555.png)

This is wired for me because normally when the node is set in the debug mode, all the logs messages will pass through `/rosout` and I can use `rqt_console` to view the log message.

My question is, is there any method or way that I can make the log message passes through `/rosout`? so that I can bag them using rosbag.

OS:Ubuntu 20.04
ROS: Foxy

Thanks!

**Comment by MartyG-RealSense** [comment]
Hi @JamesChooWK  There was a recent Foxy case at https://github.com/ros-visualization/rqt_console/issues/35 where messages were not getting through to RQT.  The ROS user in that case concluded that it was related to QOS, and they  found that creating a custom QOS enabled RQT to capture all missing messages.

They experienced the problem during high message loads, so it may be worth testing with a lower resolution such as 640x480 instead of 1280x720 to see whether this enables the messages to be captured in rosout.

**Comment by JamesChooWK** [comment]
Hi, here are the updates from my testing. 

1. I have played with the QOS setting at the rqt_console and also on the launch file of Realsense (parameter inside the rs_launch.py) but still get no luck. 
2. I have also tried to lower down the frame rate and frame size, but also still see nothing on rqt_console.

I used the launch file (rs_launch.py) in both the trail. I can see all the topics via the terminal using `ros2 topic list` and able to see the images in the topic message using rqt. However, the message from the logger (ROS_INFO_STREAM etc.) will still only appears on my terminal and not on the rqt console.

**Comment by MartyG-RealSense** [comment]
Are there any messages on the topic **/rosout_agg** that publishes an aggregated feed of the logging messages?

http://wiki.ros.org/rosout#A.2Frosout_agg

**Comment by JamesChooWK** [comment]
Correct if I'm wrong, but I don't think ros2 has the /rosout_gg.

**Comment by MartyG-RealSense** [comment]
You can check whether /rosout_agg is available on ROS2 by listing the topics with **ros2 topic list**

**Comment by JamesChooWK** [comment]
I launched the rs_launch.py file and run the `ros2 topic list` on another terminal and there isn't any `/rosout_agg` topic shown. The only topics that are shown are:
/color/camera_info
/color/image_raw
/depth/camera_info
/depth/image_rect_raw
/extrinsics/depth_to_color
/parameter_events
/rosout
/tf
/tf_static

**Comment by MartyG-RealSense** [comment]
Okay, thank you @JamesChooWK for checking.  I will highlight your case to **Doronhi** the RealSense ROS wrapper developer to seek their advice.  Thanks very much for your patience.

**Comment by JamesChooWK** [comment]
@MartyG-RealSense , I found a workaround to get the logs into the `/rosout` topic. The workaround approach is to replace the logger at line 93 of `base_realsense_node.cpp`. From `_logger(rclcpp::get_logger("RealSenseCameraNode")),` into `_logger(node.get_logger()),` . From my understanding, by doing this the BaseRealSenseNode class will use the logger from the node and instead of using the new logger. I doubled confirm with my rqt console that with this approach all logs can be seen on the rqt but the downside is that the name of the logger is no more "RealSenseCameraNode". 
I hope this might give a hint to help fix the problem.

**Comment by MartyG-RealSense** [comment]
Thanks so much @JamesChooWK  for sharing your workaround with myself, @doronhi and the RealSense ROS community!  :)

**Comment by doronhi** [comment]
Hi @JamesChooWK ,
Your workaround seems great to me. It just needs to be implemented in several more places in the code.
Regarding the logger name not being "RealSenseCameraNode" but instead being the node's name, do you think it matters?
If not, would you care to submit a PR?

**Comment by JamesChooWK** [comment]
Hi @doronhi, 
I can submit a PR, there is no problem with that. But do you know where are the other places in the code that have to be changed? Or, I just submit only the changes that I know?
Regarding the name of the logger, I'm just not sure whether changing it, will it break the code and I'm not catching it.

**Comment by doronhi** [comment]
I searched the code for 'rclcpp::get_logger("RealSenseCameraNode")' and found 4 occurrences.
I would replace them all, according to your suggestion, with "get_logger()".
I also don't see it breaking anything so please carry on submitting the PR. If any objections will come up we'll see whether this should be merged or not.

**Comment by MartyG-RealSense** [comment]
Hi @JamesChooWK  Do you have an update about this case that you can provide, please?  Thanks!

**Comment by JamesChooWK** [comment]
Hi @MartyG-RealSense , yes I have made a PR #2154  to the ros2 branch. I just have a quick look on it, there is an error that causes the ci to fail.

**Comment by MartyG-RealSense** [comment]
Thanks very much @JamesChooWK for creating the PR!  I have added an **Enhancement** tag to this case to highlight that it should be kept open whilst your PR is active.

**Comment by JamesChooWK** [comment]
This is PR ticket #2154.

**Comment by doronhi** [comment]
The error is caused because the wrapper depends on librealsense2 v2.50.0 which, due to technicalities, is not yet available for the CI in a debian form. Nothing to worry about.

**Comment by JamesChooWK** [comment]
@doronhi , does this means that I just wait for the PR to get approved at the moment?

**Comment by doronhi** [comment]
Hi @JamesChooWK ,
Sorry, yes. There is nothing you need to do now. I will merge it shortly.

**Comment by MartyG-RealSense** [comment]
As the pull request linked to this case was merged into the ROS wrapper on Nov 23 2021, I will close this case.  Thanks again @JamesChooWK for your report and your PR!
