### ISSUE TITLE
Ros topic frequency not as the set value

### ISSUE THREAD

**Issue by LilyGinger** [realsenseai/realsense-ros#2142]
I use the SDK for D435i. However, the frequency of /camera/color/image_raw is not as I set (30Hz) but much lower (13Hz or 18Hz). What may influence it and How can we make the frequency stable? 
Thanks for your time!

**Comment by MartyG-RealSense** [comment]
Hi @jjjmmmxxx  You could first try using the command below in the ROS terminal after launch has completed to disable RGB auto-exposure and set a manual RGB exposure value.  This will help to determine whether RGB auto-exposure might be causing your color FPS value to vary.

**rosrun dynamic_reconfigure dynparam set /camera/rgb_camera exposure 150**

**Comment by LilyGinger** [comment]
Thanks alot. 
I run the command, and the rostopic hz is now 18hz, but still not the 30Hz as I set in the launch file.

**Comment by MartyG-RealSense** [comment]
Are you running a depth stream as well as a color stream please, or only a color stream?

**Comment by LilyGinger** [comment]
Both depth and color stream.

**Comment by MartyG-RealSense** [comment]
Thanks very much.  If you have both depth and RGB streams active then you could therefore next try enforcing a constant FPS rate by disabling an RGB option called **Auto-Exposure Priority** (which is a separate option from Auto-Exposure).  For this option, RGB auto-exposure should be enabled, so do not use the manual color exposure command that I mentioned above.

Here is a rosparam instruction that can be edited into the launch file to disable Auto-Exposure Priority.

```
<rosparam>
/camera/rgb_camera/rs435_color_auto_exposure_priority: false
</rosparam>
```

Alternatively, you could test it quickly by finding the option in the RGB section of the visual interface of dynamic reconfigure and unticking it to disable it.  The visual interface can be accessed by inputting the ROS terminal command **rosrun rqt_reconfigure rqt_reconfigure** after roslaunch has successfully completed.

![image](https://user-images.githubusercontent.com/41145062/139227541-fb6b0f3e-8d90-4f98-9751-5cf2be5d2930.png)

**Comment by MartyG-RealSense** [comment]
Hi @jjjmmmxxx  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.

**Comment by LilyGinger** [comment]
Sorry for not responding... I set the auto_exposure_priority as false in rqt_reconfigure. However, the frequency is still not 30Hz as I set. Sometimes it can reach 27hz and sometimes its just 23Hz. Is there other things I can do to fix it?

**Comment by MartyG-RealSense** [comment]
Hi @jjjmmmxxx  When you set auto-exposure priority to false in rqt_reconfigure, is auto-exposure set to True?  This is a requirement for enforcing a constant FPS with this method: auto-exposure = true, auto-exposure priority = false
