### ISSUE TITLE
No color topic in ros

### ISSUE THREAD

**Issue by zxl5344** [realsenseai/realsense-ros#2152]
HI, I am using a L515 camera. I run **roslaunch realsense2_camera rs_camera.launch** in this repo and I only get topic in depth. 
[](ur
![Screenshot from 2021-11-10 10-53-30](https://user-images.githubusercontent.com/79371762/141146908-5b87bf3d-71c2-435d-bc7c-949028681f0b.png)
l)

How do I get all topic?

**Comment by MartyG-RealSense** [comment]
Hi @zxl5344  Are you able to receive the color topic if you unplug the USB cable from the base of the camera, turn the micro-sized connector around the opposite way and re-insert it into the base of the camera (USB Type-C cables are two-way insertion on the micro sized end).

**Edit:** I see that you have already tried a cable reversal without success in your other case in https://github.com/IntelRealSense/librealsense/issues/9931

Do you still receive no color topic if you add **initial_reset:=true** to your roslaunch instruction to reset the camera at launch?

**roslaunch realsense2_camera rs_camera.launch initial_reset:=true**

**Comment by zxl5344** [comment]
No, I still only get topic depth. My camera should work well since I can see RGB and depth when I run **realsense-viewer**.

**Comment by MartyG-RealSense** [comment]
In https://github.com/IntelRealSense/realsense-ros/issues/1523 a RealSense ROS user with an L515 had a similar problem with the color topic not being published.  

Whilst https://github.com/IntelRealSense/realsense-ros/issues/1523 mentions that 640x480 color is not supported on L515, that reference is now out of date as support for color 640x480 and 640x360  was added in L515 firmware version **1.5.8.1**.  That support would no longer be present though if the camera firmware had been downgraded to an earlier firmware version.

May I ask whether you have edited the rs_launch file to specify a custom resolution for color instead of letting the default color resolution be chosen automatically by the ROS launch? 

You also mentioned in your other L515 case in https://github.com/IntelRealSense/librealsense/issues/9931 that the camera was only being detected as USB 2.1 in the Viewer.  Could you also check whether the camera is being mis-detected as USB 2.1 in the ROS launch, please?  You can do this by finding a line called **Device USB Type** in the launch log in the ROS terminal.  If the camera is being detected as 2.1 then it will say '2.1' instead of '3.2'.

![image](https://user-images.githubusercontent.com/41145062/141290672-297851db-a1e7-495d-a6bb-8f8e71605fee.png)

**Comment by zxl5344** [comment]
No, I didn't edit it.

Yes, it is being detected as 2.1

**Comment by zxl5344** [comment]
I checked my log and I found there is not "color stream is enabled" even "enable_color: True". 

... logging to /home/zxl5344/.ros/log/af44d6bc-42fc-11ec-9209-ef9a2ee492f5/roslaunch-E5-ME-L-KAFI11-177380.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://E5-ME-L-KAFI11:40449/

SUMMARY
========

PARAMETERS
 * /camera/realsense2_camera/accel_fps: -1
 * /camera/realsense2_camera/accel_frame_id: camera_accel_frame
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: False
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/allow_no_texture_points: False
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/calib_odom_file: 
 * /camera/realsense2_camera/clip_distance: -2.0
 * /camera/realsense2_camera/color_fps: -1
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: -1
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: -1
 * /camera/realsense2_camera/confidence_fps: -1
 * /camera/realsense2_camera/confidence_height: -1
 * /camera/realsense2_camera/confidence_width: -1
 * /camera/realsense2_camera/depth_fps: -1
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: -1
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: -1
 * /camera/realsense2_camera/device_type: 
 * /camera/realsense2_camera/enable_accel: False
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_confidence: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye1: False
 * /camera/realsense2_camera/enable_fisheye2: False
 * /camera/realsense2_camera/enable_fisheye: False
 * /camera/realsense2_camera/enable_gyro: False
 * /camera/realsense2_camera/enable_infra1: False
 * /camera/realsense2_camera/enable_infra2: False
 * /camera/realsense2_camera/enable_infra: False
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_pose: False
 * /camera/realsense2_camera/enable_sync: False
 * /camera/realsense2_camera/filters: 
 * /camera/realsense2_camera/fisheye1_frame_id: camera_fisheye1_f...
 * /camera/realsense2_camera/fisheye1_optical_frame_id: camera_fisheye1_o...
 * /camera/realsense2_camera/fisheye2_frame_id: camera_fisheye2_f...
 * /camera/realsense2_camera/fisheye2_optical_frame_id: camera_fisheye2_o...
 * /camera/realsense2_camera/fisheye_fps: -1
 * /camera/realsense2_camera/fisheye_frame_id: camera_fisheye_frame
 * /camera/realsense2_camera/fisheye_height: -1
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: -1
 * /camera/realsense2_camera/gyro_fps: -1
 * /camera/realsense2_camera/gyro_frame_id: camera_gyro_frame
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/imu_optical_frame_id: camera_imu_optica...
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra_fps: 30
 * /camera/realsense2_camera/infra_height: 480
 * /camera/realsense2_camera/infra_rgb: False
 * /camera/realsense2_camera/infra_width: 848
 * /camera/realsense2_camera/initial_reset: False
 * /camera/realsense2_camera/json_file_path: 
 * /camera/realsense2_camera/linear_accel_cov: 0.01
 * /camera/realsense2_camera/odom_frame_id: camera_odom_frame
 * /camera/realsense2_camera/ordered_pc: False
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/pose_frame_id: camera_pose_frame
 * /camera/realsense2_camera/pose_optical_frame_id: camera_pose_optic...
 * /camera/realsense2_camera/publish_odom_tf: True
 * /camera/realsense2_camera/publish_tf: True
 * /camera/realsense2_camera/rosbag_filename: 
 * /camera/realsense2_camera/serial_no: 
 * /camera/realsense2_camera/stereo_module/exposure/1: 7500
 * /camera/realsense2_camera/stereo_module/exposure/2: 1
 * /camera/realsense2_camera/stereo_module/gain/1: 16
 * /camera/realsense2_camera/stereo_module/gain/2: 16
 * /camera/realsense2_camera/tf_publish_rate: 0.0
 * /camera/realsense2_camera/topic_odom_in: odom_in
 * /camera/realsense2_camera/unite_imu_method: 
 * /camera/realsense2_camera/usb_port_id: 
 * /rosdistro: noetic
 * /rosversion: 1.15.13

NODES
  /camera/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)

auto-starting new master
process[master]: started with pid [177414]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to af44d6bc-42fc-11ec-9209-ef9a2ee492f5
process[rosout-1]: started with pid [177446]
started core service [/rosout]
process[camera/realsense2_camera_manager-2]: started with pid [177453]
process[camera/realsense2_camera-3]: started with pid [177454]
[ INFO] [1636641359.142943615]: Initializing nodelet with 12 worker threads.
[ INFO] [1636641359.269030175]: RealSense ROS v2.3.1
[ INFO] [1636641359.269067798]: Built with LibRealSense v2.49.0
[ INFO] [1636641359.269090002]: Running with LibRealSense v2.49.0
[ INFO] [1636641359.321749077]:  
 11/11 09:35:59,480 WARNING [140081192064768] (messenger-libusb.cpp:42) control_transfer returned error, index: 300, error: No data available, number: 3d
 11/11 09:35:59,561 WARNING [140081192064768] (messenger-libusb.cpp:42) control_transfer returned error, index: 300, error: No data available, number: 3d
 11/11 09:35:59,616 WARNING [140081192064768] (messenger-libusb.cpp:42) control_transfer returned error, index: 300, error: No data available, number: 3d
 11/11 09:35:59,671 WARNING [140081192064768] (messenger-libusb.cpp:42) control_transfer returned error, index: 300, error: No data available, number: 3d
[ INFO] [1636641359.760876749]: Device with serial number f1230435 was found.

[ INFO] [1636641359.760909250]: Device with physical ID 1-4-26 was found.
[ INFO] [1636641359.760920338]: Device with name Intel RealSense L515 was found.
[ INFO] [1636641359.761201888]: Device with port number 1-4 was found.
[ INFO] [1636641359.761221159]: Device USB type: 2.1
[ WARN] [1636641359.761236419]: Device f1230435 is connected using a 2.1 port. Reduced performance is expected.
[ INFO] [1636641359.762640602]: getParameters...
[ INFO] [1636641359.793034872]: setupDevice...
[ INFO] [1636641359.793056574]: JSON file is not provided
[ INFO] [1636641359.793067441]: ROS Node Namespace: camera
[ INFO] [1636641359.793078807]: Device Name: Intel RealSense L515
[ INFO] [1636641359.793088188]: Device Serial No: f1230435
[ INFO] [1636641359.793097421]: Device physical port: 1-4-26
[ INFO] [1636641359.793109327]: Device FW version: 01.05.08.01
[ INFO] [1636641359.793119921]: Device Product ID: 0x0B64
[ INFO] [1636641359.793130951]: Enable PointCloud: Off
[ INFO] [1636641359.793142123]: Align Depth: Off
[ INFO] [1636641359.793151593]: Sync Mode: Off
[ INFO] [1636641359.793178545]: Device Sensors: 
[ INFO] [1636641359.807964066]: L500 Depth Sensor was found.
[ INFO] [1636641359.812690918]: RGB Camera was found.
[ INFO] [1636641359.812780241]: Motion Module was found.
[ INFO] [1636641359.812803235]: num_filters: 0
[ INFO] [1636641359.812817640]: Setting Dynamic reconfig parameters.
[ INFO] [1636641360.023355174]: Done Setting Dynamic reconfig parameters.
[ INFO] [1636641360.023538228]: depth stream is enabled - width: 320, height: 240, fps: 30, Format: Z16
[ INFO] [1636641360.023580293]: setupPublishers...
[ INFO] [1636641360.025604311]: Expected frequency for depth = 30.00000
[ INFO] [1636641360.047690474]: setupStreams...
[ INFO] [1636641360.058582122]: insert Depth to L500 Depth Sensor
[ INFO] [1636641360.075958496]: SELECTED BASE:Depth, 0
[ INFO] [1636641360.076116352]: RealSense Node Is Up!
 11/11 09:36:00,076 WARNING [140081192064768] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 11/11 09:36:00,126 WARNING [140081192064768] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 11/11 09:36:00,178 WARNING [140081192064768] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 11/11 09:36:00,481 WARNING [140081192064768] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 11/11 09:36:00,735 WARNING [140081192064768] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 11/11 09:36:01,130 WARNING [140081192064768] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
[ WARN] [1636641361.166008924]: 
[ WARN] [1636641361.166123813]: frame's time domain is HARDWARE_CLOCK. Timestamps may reset periodically.
 11/11 09:36:01,698 WARNING [140081192064768] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 11/11 09:36:02,383 WARNING [140081192064768] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
 11/11 09:36:03,635 WARNING [140081192064768] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61
^C 11/11 09:36:04,887 WARNING [140081192064768] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: No data available, number: 61

**Comment by MartyG-RealSense** [comment]
Does the color stream become enabled if you enable it in the roslaunch instruction:

**roslaunch realsense2_camera rs_camera.launch enable_color:=true**

**Comment by zxl5344** [comment]
No, "color stream" is still missing

**Comment by MartyG-RealSense** [comment]
As you intend to buy a new USB cable as mentioned in https://github.com/IntelRealSense/librealsense/issues/9931#issuecomment-966474815 - shall we come back to this question after you have had the opportunity to see whether a cable change makes a difference?  Thanks!

**Comment by zxl5344** [comment]
Thank you. I will update it once I got the new data cable

**Comment by zxl5344** [comment]
Hi, I tried my new cable.  Although i still have "11:12:14 [Warn] /home/zxl5344/Realsense SDK/librealsense-2.49.0/src/libusb/messenger-libusb.cpp:42 - control_transfer returned error, index: 768, error: No data available, number: 61", all camera function looks working well so far.

**Comment by MartyG-RealSense** [comment]
Excellent news, @zxl5344 - thanks for the update!

If you are receiving the **control_transfer returned** warning only a small number of times during launch and then they stop, or they occur one or two times a minute after launch, then this warning can be safely ignored.  Likewise, if the topics are being published correctly in RViz despite the warnings being generated regularly after launch and performance does not seem to be degraded then the warnings can also be disregarded in that situation.

**Comment by karanpandyaa** [comment]
I had the same issue, it got solved with: 
**roslaunch realsense2_camera rs_aligned_depth.launch**

**Comment by hesic73** [comment]
> I had the same issue, it got solved with: **roslaunch realsense2_camera rs_aligned_depth.launch**

Thanks! I'm using a L515, and this works for me!
