### ISSUE TITLE
Convert PCD file to other format

### ISSUE THREAD

**Issue by ranjitkathiriya** [realsenseai/realsense-ros#2159]
Hello there,

I have generated SLAM of the environment via this link https://github.com/IntelRealSense/realsense-ros/wiki/SLAM-with-D435i, It was easy to generate with the given steps thanks for it.

Now, my question is I have exported .pcd file from the bag file as given in the above link. I have pcd file and I want to convert pcd file to other formats (.off, .stl, .ply, etc) is there any way to convert it. I want this (.off or .stl) format for point cloud shape classification. 

Thanks in advance for the help!

**Comment by MartyG-RealSense** [comment]
Hi @ranjitkathiriya  If you would prefer to write your own solution, a Python guide in the link below about exporting pcd data as .ply, .obj, .stl or .gltf may provide useful insights.

https://towardsdatascience.com/5-step-guide-to-generate-3d-meshes-from-point-clouds-with-python-36bad397d8ba

**Comment by ranjitkathiriya** [comment]
Thanks
