### ISSUE TITLE
realsense_person not woking - person tracking with R200 realsense camera

### ISSUE THREAD

**Issue by ziggBee30** [realsenseai/realsense-ros#216]
### System Configuration
Please complete Your Configuration detail below. Refer to the BKC at [Configuration](../realsense_person/README.md#configuration).

| Version               | Your Configuration   |
|:--------------------- |:---------------------|
| Operating System      | 16.04              |
| Kernel                | ?-?-?                |
| ROS                   | kinetic                    |
| ROS RealSense         | realsense_person              |
| librealsense          | ?.?.?                |
| Camera Type-Firmware  | R200             |

-
hello 
i cloned realsense_person from mattcurfman repository, and by just doing catkin_make on the that,, i am getting a lot of errors,,, i am using R200 camera, and it should not be difficult to get the result from realsense_person.

please some one try to run realsense_person and please tell if you guys are able to run it or not.

also, doest any one know any person tracking compatible with R200 realsense camera.??
please suggest,
~ thanks

**Comment by mdhorn** [comment]
I'm sorry, but this repository is not the realsense_person work.
Also, as mentioned before, the original repository was pulled down because it relies on proprietary software which is not yet released.
