### ISSUE TITLE
Foxy branch removal

### ISSUE THREAD

**Issue by nkalupahana** [realsenseai/realsense-ros#2160]
Why was the foxy branch deleted? [Foxy is still the established ROS2 LTS](https://www.ros.org/), and will be until mid next year. Anyone using ROS2 right now in any mission-critical system will be using Foxy since it's LTS, and not Galactic/Rolling, so having this branch there is critical.

**Comment by MartyG-RealSense** [comment]
Hi @nkalupahana   **Doronhi** the RealSense ROS wrapper developer provides a statement about the removal in https://github.com/IntelRealSense/realsense-ros/issues/2133#issuecomment-969854602

The Foxy wrapper is deprecated.  The **ros2** wrapper branch instead provides a single unified wrapper for all ROS2 versions, including Foxy.

![image](https://user-images.githubusercontent.com/41145062/141942950-3e8a5a98-334b-48f6-a997-3e9335ce7e10.png)
