### ISSUE TITLE
Could not transform from [camera_color_optical_frame] to [camera_link]

### ISSUE THREAD

**Issue by utkarsh867** [realsenseai/realsense-ros#2165]
### System specifications
Camera: D455 (Firmware: 05.13.00.50)
ROS2: Dashing
Computer: NVIDIA Jetson Xavier NX
Branch: `tag 3.2.2`

### Issue
I run the demo pointcloud using:
```
ros2 launch realsense2_camera demo_pointcloud_launch.py
```
When rviz2 opens, I get the RGB image from the camera, but I do not get the pointcloud.

There is an error in PointCloud2 Transform as below 

![image](https://user-images.githubusercontent.com/19630580/142141962-4d8e03d0-e43e-4d3a-a2ad-82264fd6a1c3.png)

I later checked the TF to check if I had the frames. But it is empty.
![image](https://user-images.githubusercontent.com/19630580/142142408-48f4b019-e8e5-40c3-ac04-52ffc711b04d.png)

At this point, I'm almost certain I'm missing something in my process. Does anyone know why these frames may be missing and how I can get them to work?

**Comment by MartyG-RealSense** [comment]
Hi @utkarsh867  Given that you are using a Jetson Xavier NX, you may be experiencing the same problems that other NX users have had with pointcloud generation in the RealSense ROS wrapper.  https://github.com/IntelRealSense/realsense-ros/issues/1967 has more information about this.

An NX user in https://github.com/IntelRealSense/realsense-ros/issues/1967#issuecomment-954814317 found that they could obtain a pointcloud when using the earlier librealsense SDK version 2.43.0.

Please test whether you can generate a pointcloud using the alternative ROS2 roslaunch instruction below.

**ros2 launch realsense2_camera rs_launch.py enable_pointcloud:=true device_type:=d435**

**Comment by MartyG-RealSense** [comment]
Hi @utkarsh867  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
