### ISSUE TITLE
rosdep install errors: "Ignoring environment", "cannot locate..."

### ISSUE THREAD

**Issue by JHPHELAN** [realsenseai/realsense-ros#2173]
@doronhi @MartyG-RealSense 
Having prev. installed the latest Librealsense 2.50 successfully from source via:
[https://github.com/IntelRealSense/librealsense/blob/master/doc/libuvc_installation.md](url)
and with successful realsense-viewer
I'm attempting to install the ROS_wrapper working from:
[https://github.com/IntelRealSense/realsense-ros/tree/ros2](url)
I get to Step 4: Install dependencies:
`rosdep install -i --from-path src --rosdistro $_ros_dist --skip-keys=librealsense2 -y`
then get these errors:

> WARNING: given --rosdistro --skip-keys=librealsense2 but ROS_DISTRO is "foxy". Ignoring environment.
> WARNING: ROS_PYTHON_VERSION is unset. Defaulting to 3.  
> ERROR: the following packages/stacks could not have their rosdep keys resolved
> to system dependencies:
> realsense2_description: Cannot locate rosdep definition for [xacro]
> realsense2_camera: Cannot locate rosdep definition for [diagnostic_updater]

What's happening here?
Jim P.
[2021.11.21 rosdep install FAIL .pdf](https://github.com/IntelRealSense/realsense-ros/files/7577380/2021.11.21.rosdep.install.FAIL.pdf)

**Comment by doronhi** [comment]
It seems like a bug in the documentation. Please try replace `$_ros_dist` with `$ROS_DISTRO`. i.e.
Try out the following command: `rosdep install -i --from-path src --rosdistro $ROS_DISTRO --skip-keys=librealsense2 -y`

**Comment by MartyG-RealSense** [comment]
@doronhi   Thanks very much for your help for @JHPHELAN   :)

**Comment by JHPHELAN** [comment]
@doronhi @MartyG-RealSense 
I made the correction above and install progressed ok.
We may  have finally stumbled on a workable path to:
Intel RealSense Depth Camera D455 / ROS2_Wrapper / RealSense 2.50 via libuvc / ROS2 foxy / Ubuntu 20.04 / Raspberry Pi 4b 4G
There are still some issues, see attached, but this is real progress!
Thank you both!
Jim P
[2021.11.22 ROS_Wrapper success.pdf](https://github.com/IntelRealSense/realsense-ros/files/7585624/2021.11.22.ROS_Wrapper.success.pdf)

**Comment by MartyG-RealSense** [comment]
Excellent news @JHPHELAN - thanks very much for the update   :)

**Comment by MartyG-RealSense** [comment]
Hi @JHPHELAN  Do you require further assistance with this case, please?  Thanks!

**Comment by JHPHELAN** [comment]
@MartyG-RealSense 
Not on this, it's good.  Thanks!
JHP

**Comment by MartyG-RealSense** [comment]
Thanks very much @JHPHELAN - as you are satisfied with the outcome, I will close this case.  Thanks again!

**Comment by lifangyan16** [comment]
> @doronhi @MartyG-RealSense Having prev. installed the latest Librealsense 2.50 successfully from source via: [https://github.com/IntelRealSense/librealsense/blob/master/doc/libuvc_installation.md](url) and with successful realsense-viewer I'm attempting to install the ROS_wrapper working from: [https://github.com/IntelRealSense/realsense-ros/tree/ros2](url) I get to Step 4: Install dependencies: `rosdep install -i --from-path src --rosdistro $_ros_dist --skip-keys=librealsense2 -y` then get these errors:
> 
> > WARNING: given --rosdistro --skip-keys=librealsense2 but ROS_DISTRO is "foxy". Ignoring environment.
> > WARNING: ROS_PYTHON_VERSION is unset. Defaulting to 3.
> > ERROR: the following packages/stacks could not have their rosdep keys resolved
> > to system dependencies:
> > realsense2_description: Cannot locate rosdep definition for [xacro]
> > realsense2_camera: Cannot locate rosdep definition for [diagnostic_updater]
> 
> What's happening here? Jim P. [2021.11.21 rosdep install FAIL .pdf](https://github.com/IntelRealSense/realsense-ros/files/7577380/2021.11.21.rosdep.install.FAIL.pdf)

i use ros2(https://github.com/IntelRealSense/realsense-ros/tree/ros2) and meet this bug . use ros1(https://github.com/IntelRealSense/realsense-ros).

**Comment by JHPHELAN** [comment]
@lifangyan16 
I don't think using ROS for a ROS2 environment will work.
I believe I got it a bit further along, although never perfectly.  See attached.
[2021.11.22 ROS_Wrapper success.pdf](https://github.com/IntelRealSense/realsense-ros/files/7787111/2021.11.22.ROS_Wrapper.success.pdf)
