### ISSUE TITLE
I have  running with a different librealsense version  [ WARN] [1638100292.566477829]: than the one the wrapper was compiled with!   error please solve this :(

### ISSUE THREAD

**Issue by BamBamBap** [realsenseai/realsense-ros#2179]
Below is  my spec.

OS : ubuntu 18.08 
CPU : Intel® Core™ i5-9400F CPU @ 2.90GHz × 6 
GPU : GTX 1050 
Camera : realsense L515
USB : 3.2 

Two warnings appear when the code is executed. can you solve it?

Below is the full code

kim@kim:~$ roslaunch realsense2_camera rs_camera.launch 
... logging to /home/kim/.ros/log/8762b40a-5041-11ec-bcb2-40b076dd2030/roslaunch-kim-28393.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://kim:41495/

SUMMARY
========

PARAMETERS
 * /camera/realsense2_camera/accel_fps: -1
 * /camera/realsense2_camera/accel_frame_id: camera_accel_frame
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: False
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/allow_no_texture_points: False
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/calib_odom_file: 
 * /camera/realsense2_camera/clip_distance: -2.0
 * /camera/realsense2_camera/color_fps: -1
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: -1
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: -1
 * /camera/realsense2_camera/confidence_fps: -1
 * /camera/realsense2_camera/confidence_height: -1
 * /camera/realsense2_camera/confidence_width: -1
 * /camera/realsense2_camera/depth_fps: -1
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: -1
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: -1
 * /camera/realsense2_camera/device_type: 
 * /camera/realsense2_camera/enable_accel: False
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_confidence: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye1: False
 * /camera/realsense2_camera/enable_fisheye2: False
 * /camera/realsense2_camera/enable_fisheye: False
 * /camera/realsense2_camera/enable_gyro: False
 * /camera/realsense2_camera/enable_infra1: False
 * /camera/realsense2_camera/enable_infra2: False
 * /camera/realsense2_camera/enable_infra: False
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_pose: False
 * /camera/realsense2_camera/enable_sync: False
 * /camera/realsense2_camera/filters: 
 * /camera/realsense2_camera/fisheye1_frame_id: camera_fisheye1_f...
 * /camera/realsense2_camera/fisheye1_optical_frame_id: camera_fisheye1_o...
 * /camera/realsense2_camera/fisheye2_frame_id: camera_fisheye2_f...
 * /camera/realsense2_camera/fisheye2_optical_frame_id: camera_fisheye2_o...
 * /camera/realsense2_camera/fisheye_fps: -1
 * /camera/realsense2_camera/fisheye_frame_id: camera_fisheye_frame
 * /camera/realsense2_camera/fisheye_height: -1
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: -1
 * /camera/realsense2_camera/gyro_fps: -1
 * /camera/realsense2_camera/gyro_frame_id: camera_gyro_frame
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/imu_optical_frame_id: camera_imu_optica...
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra_fps: 30
 * /camera/realsense2_camera/infra_height: 480
 * /camera/realsense2_camera/infra_rgb: False
 * /camera/realsense2_camera/infra_width: 848
 * /camera/realsense2_camera/initial_reset: False
 * /camera/realsense2_camera/json_file_path: 
 * /camera/realsense2_camera/linear_accel_cov: 0.01
 * /camera/realsense2_camera/odom_frame_id: camera_odom_frame
 * /camera/realsense2_camera/ordered_pc: False
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/pose_frame_id: camera_pose_frame
 * /camera/realsense2_camera/pose_optical_frame_id: camera_pose_optic...
 * /camera/realsense2_camera/publish_odom_tf: True
 * /camera/realsense2_camera/publish_tf: True
 * /camera/realsense2_camera/reconnect_timeout: 6.0
 * /camera/realsense2_camera/rosbag_filename: 
 * /camera/realsense2_camera/serial_no: 
 * /camera/realsense2_camera/stereo_module/exposure/1: 7500
 * /camera/realsense2_camera/stereo_module/exposure/2: 1
 * /camera/realsense2_camera/stereo_module/gain/1: 16
 * /camera/realsense2_camera/stereo_module/gain/2: 16
 * /camera/realsense2_camera/tf_publish_rate: 0.0
 * /camera/realsense2_camera/topic_odom_in: odom_in
 * /camera/realsense2_camera/unite_imu_method: 
 * /camera/realsense2_camera/usb_port_id: 
 * /camera/realsense2_camera/wait_for_device_timeout: -1.0
 * /rosdistro: melodic
 * /rosversion: 1.14.12

NODES
  /camera/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)

auto-starting new master
process[master]: started with pid [28403]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 8762b40a-5041-11ec-bcb2-40b076dd2030
process[rosout-1]: started with pid [28414]
started core service [/rosout]
process[camera/realsense2_camera_manager-2]: started with pid [28421]
process[camera/realsense2_camera-3]: started with pid [28422]
[ INFO] [1638100292.300039561]: Initializing nodelet with 6 worker threads.
[ INFO] [1638100292.566212908]: RealSense ROS v2.3.2
[ INFO] [1638100292.566305925]: Built with LibRealSense v2.48.0
[ INFO] [1638100292.566357463]: Running with LibRealSense v2.50.0
**[ WARN] [1638100292.566401124]: ***************************************************
[ WARN] [1638100292.566443667]: ** running with a different librealsense version 
[ WARN] [1638100292.566477829]: ** than the one the wrapper was compiled with!   
[ WARN] [1638100292.566509771]: *****************************************************
[ INFO] [1638100292.614127892]:**  
[ INFO] [1638100292.850432875]: Device with serial number f0220517 was found.

[ INFO] [1638100292.850533504]: Device with physical ID /sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/video4linux/video2 was found.
[ INFO] [1638100292.850577279]: Device with name Intel RealSense L515 was found.
[ INFO] [1638100292.851647782]: Device with port number 2-5 was found.
[ INFO] [1638100292.851726694]: Device USB type: 3.2
[ INFO] [1638100292.856115683]: getParameters...
[ INFO] [1638100292.991875753]: setupDevice...
[ INFO] [1638100292.991908200]: JSON file is not provided
[ INFO] [1638100292.991932126]: ROS Node Namespace: camera
[ INFO] [1638100292.991952865]: Device Name: Intel RealSense L515
[ INFO] [1638100292.991965824]: Device Serial No: f0220517
[ INFO] [1638100292.991976817]: Device physical port: /sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/video4linux/video2
[ INFO] [1638100292.991990787]: Device FW version: 01.05.08.01
[ INFO] [1638100292.992004735]: Device Product ID: 0x0B64
[ INFO] [1638100292.992014564]: Enable PointCloud: Off
[ INFO] [1638100292.992023523]: Align Depth: Off
[ INFO] [1638100292.992031791]: Sync Mode: Off
[ INFO] [1638100292.992069633]: Device Sensors: 
[ INFO] [1638100292.992498855]: L500 Depth Sensor was found.
[ INFO] [1638100292.994329362]: RGB Camera was found.
[ INFO] [1638100292.994455687]: Motion Module was found.
[ INFO] [1638100292.994484483]: num_filters: 0
[ INFO] [1638100292.994503169]: Setting Dynamic reconfig parameters.
[ INFO] [1638100293.125993687]: Done Setting Dynamic reconfig parameters.
[ INFO] [1638100293.126720811]: depth stream is enabled - width: 640, height: 480, fps: 30, Format: Z16
[ INFO] [1638100293.128958697]: color stream is enabled - width: 1280, height: 720, fps: 30, Format: RGB8
[ INFO] [1638100293.129012897]: setupPublishers...
[ INFO] [1638100293.132673219]: Expected frequency for depth = 30.00000
[ INFO] [1638100293.179301007]: Expected frequency for color = 30.00000
[ INFO] [1638100293.210955546]: setupStreams...
[ INFO] [1638100293.284895868]: SELECTED BASE:Depth, 0
[ INFO] [1638100293.482309817]: RealSense Node Is Up!
[ WARN] [1638100293.487623468]: 
**[ WARN] [1638100293.487746927]: frame's time domain is HARDWARE_CLOCK. Timestamps may reset periodically.**
^C[camera/realsense2_camera-3] killing on exit
[camera/realsense2_camera_manager-2] killing on exit
^C^C^C[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

**Comment by MartyG-RealSense** [comment]
Hi @BamBamBap   When you change your librealsense SDK version and you have built the RealSense ROS wrapper from source code, you must then build the wrapper again after librealsense has been updated.  Rebuilding wrapper 2.3.2 should make the warning disappear, since that wrapper version is the correct match for librealsense 2.50.0.

**Comment by BamBamBap** [comment]
Yes I solved! but...
How do I fix this error? 

"frame's time domain is HARDWARE_CLOCK. Timestamps may reset periodically."

can you solve it?

**Comment by MartyG-RealSense** [comment]
This warning can occur because the **global timestamp** is disabled by default on the L515 camera model.  **Doronhi** the RealSense ROS wrapper developer offers code in https://github.com/IntelRealSense/realsense-ros/issues/1607#issuecomment-760128960 that you can add to the launch file to enable global time on the L515 model.

Alternatively, you could try enabling global time by adding the command **global_time_enabled:=true** to your roslaunch instruction.  For example:

**roslaunch realsense2_camera rs_camera.launch global_time_enabled:=true**

**Comment by BamBamBap** [comment]
roslaunch realsense2_camera rs_camera.launch global_time_enabled:=true
Unfortunately this solution didn't work for me..
I'll try #1607

**Comment by BamBamBap** [comment]
I tried #1607.
Is it correct to come out like this?
Below is my code

kim@kim:~$ roslaunch realsense2_camera rs_camera.launch 
... logging to /home/kim/.ros/log/b54683b8-50ca-11ec-900f-40b076dd2030/roslaunch-kim-10202.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://kim:34945/

SUMMARY
========

PARAMETERS
 * /camera/l500_depth_sensor/global_time_enabled: True
 * /camera/motion_module/global_time_enabled: True
 * /camera/realsense2_camera/accel_fps: -1
 * /camera/realsense2_camera/accel_frame_id: camera_accel_frame
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: False
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/allow_no_texture_points: False
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/calib_odom_file: 
 * /camera/realsense2_camera/clip_distance: -2.0
 * /camera/realsense2_camera/color_fps: -1
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: -1
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: -1
 * /camera/realsense2_camera/confidence_fps: -1
 * /camera/realsense2_camera/confidence_height: -1
 * /camera/realsense2_camera/confidence_width: -1
 * /camera/realsense2_camera/depth_fps: -1
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: -1
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: -1
 * /camera/realsense2_camera/device_type: 
 * /camera/realsense2_camera/enable_accel: False
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_confidence: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye1: False
 * /camera/realsense2_camera/enable_fisheye2: False
 * /camera/realsense2_camera/enable_fisheye: False
 * /camera/realsense2_camera/enable_gyro: False
 * /camera/realsense2_camera/enable_infra1: False
 * /camera/realsense2_camera/enable_infra2: False
 * /camera/realsense2_camera/enable_infra: False
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_pose: False
 * /camera/realsense2_camera/enable_sync: False
 * /camera/realsense2_camera/filters: 
 * /camera/realsense2_camera/fisheye1_frame_id: camera_fisheye1_f...
 * /camera/realsense2_camera/fisheye1_optical_frame_id: camera_fisheye1_o...
 * /camera/realsense2_camera/fisheye2_frame_id: camera_fisheye2_f...
 * /camera/realsense2_camera/fisheye2_optical_frame_id: camera_fisheye2_o...
 * /camera/realsense2_camera/fisheye_fps: -1
 * /camera/realsense2_camera/fisheye_frame_id: camera_fisheye_frame
 * /camera/realsense2_camera/fisheye_height: -1
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: -1
 * /camera/realsense2_camera/gyro_fps: -1
 * /camera/realsense2_camera/gyro_frame_id: camera_gyro_frame
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/imu_optical_frame_id: camera_imu_optica...
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra_fps: 30
 * /camera/realsense2_camera/infra_height: 480
 * /camera/realsense2_camera/infra_rgb: False
 * /camera/realsense2_camera/infra_width: 848
 * /camera/realsense2_camera/initial_reset: False
 * /camera/realsense2_camera/json_file_path: 
 * /camera/realsense2_camera/linear_accel_cov: 0.01
 * /camera/realsense2_camera/odom_frame_id: camera_odom_frame
 * /camera/realsense2_camera/ordered_pc: False
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/pose_frame_id: camera_pose_frame
 * /camera/realsense2_camera/pose_optical_frame_id: camera_pose_optic...
 * /camera/realsense2_camera/publish_odom_tf: True
 * /camera/realsense2_camera/publish_tf: True
 * /camera/realsense2_camera/reconnect_timeout: 6.0
 * /camera/realsense2_camera/rosbag_filename: 
 * /camera/realsense2_camera/serial_no: 
 * /camera/realsense2_camera/stereo_module/exposure/1: 7500
 * /camera/realsense2_camera/stereo_module/exposure/2: 1
 * /camera/realsense2_camera/stereo_module/gain/1: 16
 * /camera/realsense2_camera/stereo_module/gain/2: 16
 * /camera/realsense2_camera/tf_publish_rate: 0.0
 * /camera/realsense2_camera/topic_odom_in: odom_in
 * /camera/realsense2_camera/unite_imu_method: 
 * /camera/realsense2_camera/usb_port_id: 
 * /camera/realsense2_camera/wait_for_device_timeout: -1.0
 * /camera/rgb_camera/global_time_enabled: True
 * /rosdistro: melodic
 * /rosversion: 1.14.12

NODES
  /camera/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)

auto-starting new master
process[master]: started with pid [10213]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to b54683b8-50ca-11ec-900f-40b076dd2030
process[rosout-1]: started with pid [10224]
started core service [/rosout]
process[camera/realsense2_camera_manager-2]: started with pid [10231]
process[camera/realsense2_camera-3]: started with pid [10232]
[ INFO] [1638159210.360923554]: Initializing nodelet with 6 worker threads.
[ INFO] [1638159210.546221517]: RealSense ROS v2.3.2
[ INFO] [1638159210.546311224]: Built with LibRealSense v2.50.0
[ INFO] [1638159210.546364919]: Running with LibRealSense v2.50.0
[ INFO] [1638159210.594591888]:  
[ INFO] [1638159210.936849280]: Device with serial number f0220517 was found.

[ INFO] [1638159210.936944872]: Device with physical ID /sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/video4linux/video2 was found.
[ INFO] [1638159210.937002533]: Device with name Intel RealSense L515 was found.
[ INFO] [1638159210.938062486]: Device with port number 2-5 was found.
[ INFO] [1638159210.938137661]: Device USB type: 3.2
[ INFO] [1638159210.942696503]: getParameters...
[ INFO] [1638159211.049619975]: setupDevice...
[ INFO] [1638159211.049659578]: JSON file is not provided
[ INFO] [1638159211.049677883]: ROS Node Namespace: camera
[ INFO] [1638159211.049694890]: Device Name: Intel RealSense L515
[ INFO] [1638159211.049708077]: Device Serial No: f0220517
[ INFO] [1638159211.049724532]: Device physical port: /sys/devices/pci0000:00/0000:00:14.0/usb2/2-5/2-5:1.0/video4linux/video2
[ INFO] [1638159211.049744274]: Device FW version: 01.05.08.01
[ INFO] [1638159211.049762528]: Device Product ID: 0x0B64
[ INFO] [1638159211.049775681]: Enable PointCloud: Off
[ INFO] [1638159211.049800698]: Align Depth: Off
[ INFO] [1638159211.049821031]: Sync Mode: Off
[ INFO] [1638159211.049861823]: Device Sensors: 
[ INFO] [1638159211.050403442]: L500 Depth Sensor was found.
[ INFO] [1638159211.052968718]: RGB Camera was found.
[ INFO] [1638159211.053143660]: Motion Module was found.
[ INFO] [1638159211.053183292]: num_filters: 0
[ INFO] [1638159211.053204601]: Setting Dynamic reconfig parameters.
[ INFO] [1638159211.102423243]: Done Setting Dynamic reconfig parameters.
[ INFO] [1638159211.103002134]: depth stream is enabled - width: 640, height: 480, fps: 30, Format: Z16
[ INFO] [1638159211.104781835]: color stream is enabled - width: 1280, height: 720, fps: 30, Format: RGB8
[ INFO] [1638159211.104824125]: setupPublishers...
[ INFO] [1638159211.107759886]: Expected frequency for depth = 30.00000
[ INFO] [1638159211.142701598]: Expected frequency for color = 30.00000
[ INFO] [1638159211.166188832]: setupStreams...
[ INFO] [1638159211.270347675]: SELECTED BASE:Depth, 0
[ INFO] [1638159211.418952266]: RealSense Node Is Up!
[ WARN] [1638159211.445907806]:

**Comment by MartyG-RealSense** [comment]
I cannot see any problems in the log.  Have you run RViz with the instruction **rosrun rviz rviz** to visually view the camera data, please?

**Comment by BamBamBap** [comment]
I was wrong! Works great when the camera is working! Thank you, it seems to have worked out, thank you very much

**Comment by MartyG-RealSense** [comment]
That's great to hear that your camera is working correctly, @BamBamBap - thanks very much for the update!

**Comment by MartyG-RealSense** [comment]
Case closed due to successful outcome achieved and no further comments received.
