### ISSUE TITLE
control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11

### ISSUE THREAD

**Issue by mintnguyenn** [realsenseai/realsense-ros#2189]
Hello, I am running ' roslaunch realsense2_camera rs_camera.launch ' with Realsense D435, and I face the error like

started roslaunch server http://hpomen15:42523/

SUMMARY
========

PARAMETERS
 * /camera/realsense2_camera/accel_fps: -1
 * /camera/realsense2_camera/accel_frame_id: camera_accel_frame
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: False
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/allow_no_texture_points: False
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/calib_odom_file: 
 * /camera/realsense2_camera/clip_distance: -2.0
 * /camera/realsense2_camera/color_fps: -1
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: -1
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: -1
 * /camera/realsense2_camera/confidence_fps: -1
 * /camera/realsense2_camera/confidence_height: -1
 * /camera/realsense2_camera/confidence_width: -1
 * /camera/realsense2_camera/depth_fps: -1
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: -1
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: -1
 * /camera/realsense2_camera/device_type: 
 * /camera/realsense2_camera/enable_accel: False
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_confidence: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye1: False
 * /camera/realsense2_camera/enable_fisheye2: False
 * /camera/realsense2_camera/enable_fisheye: False
 * /camera/realsense2_camera/enable_gyro: False
 * /camera/realsense2_camera/enable_infra1: False
 * /camera/realsense2_camera/enable_infra2: False
 * /camera/realsense2_camera/enable_infra: False
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_pose: False
 * /camera/realsense2_camera/enable_sync: False
 * /camera/realsense2_camera/filters: 
 * /camera/realsense2_camera/fisheye1_frame_id: camera_fisheye1_f...
 * /camera/realsense2_camera/fisheye1_optical_frame_id: camera_fisheye1_o...
 * /camera/realsense2_camera/fisheye2_frame_id: camera_fisheye2_f...
 * /camera/realsense2_camera/fisheye2_optical_frame_id: camera_fisheye2_o...
 * /camera/realsense2_camera/fisheye_fps: -1
 * /camera/realsense2_camera/fisheye_frame_id: camera_fisheye_frame
 * /camera/realsense2_camera/fisheye_height: -1
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: -1
 * /camera/realsense2_camera/gyro_fps: -1
 * /camera/realsense2_camera/gyro_frame_id: camera_gyro_frame
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/imu_optical_frame_id: camera_imu_optica...
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra_fps: 30
 * /camera/realsense2_camera/infra_height: 480
 * /camera/realsense2_camera/infra_rgb: False
 * /camera/realsense2_camera/infra_width: 848
 * /camera/realsense2_camera/initial_reset: False
 * /camera/realsense2_camera/json_file_path: 
 * /camera/realsense2_camera/linear_accel_cov: 0.01
 * /camera/realsense2_camera/odom_frame_id: camera_odom_frame
 * /camera/realsense2_camera/ordered_pc: False
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/pose_frame_id: camera_pose_frame
 * /camera/realsense2_camera/pose_optical_frame_id: camera_pose_optic...
 * /camera/realsense2_camera/publish_odom_tf: True
 * /camera/realsense2_camera/publish_tf: True
 * /camera/realsense2_camera/reconnect_timeout: 6.0
 * /camera/realsense2_camera/rosbag_filename: 
 * /camera/realsense2_camera/serial_no: 
 * /camera/realsense2_camera/stereo_module/exposure/1: 7500
 * /camera/realsense2_camera/stereo_module/exposure/2: 1
 * /camera/realsense2_camera/stereo_module/gain/1: 16
 * /camera/realsense2_camera/stereo_module/gain/2: 16
 * /camera/realsense2_camera/tf_publish_rate: 0.0
 * /camera/realsense2_camera/topic_odom_in: odom_in
 * /camera/realsense2_camera/unite_imu_method: 
 * /camera/realsense2_camera/usb_port_id: 
 * /camera/realsense2_camera/wait_for_device_timeout: -1.0
 * /rosdistro: noetic
 * /rosversion: 1.15.13

NODES
  /camera/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)

auto-starting new master
process[master]: started with pid [24830]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 688d39a8-57d3-11ec-b821-fdca958e8a17
process[rosout-1]: started with pid [24840]
started core service [/rosout]
process[camera/realsense2_camera_manager-2]: started with pid [24847]
process[camera/realsense2_camera-3]: started with pid [24848]
[ INFO] [1638932605.263833876]: Initializing nodelet with 12 worker threads.
[ INFO] [1638932605.353631981]: RealSense ROS v2.3.2
[ INFO] [1638932605.353669137]: Built with LibRealSense v2.48.0
[ INFO] [1638932605.353681010]: Running with LibRealSense v2.50.0
[ WARN] [1638932605.353693023]: ***************************************************
[ WARN] [1638932605.353704477]: ** running with a different librealsense version **
[ WARN] [1638932605.353714394]: ** than the one the wrapper was compiled with!   **
[ WARN] [1638932605.353728293]: ***************************************************
[ INFO] [1638932605.382311798]:  
[ INFO] [1638932605.618799565]: Device with serial number 817612071347 was found.

[ INFO] [1638932605.618860117]: Device with physical ID 2-2-2 was found.
[ INFO] [1638932605.618886308]: Device with name Intel RealSense D435 was found.
[ INFO] [1638932605.619536881]: Device with port number 2-2 was found.
[ INFO] [1638932605.619569287]: Device USB type: 3.2
[ INFO] [1638932605.622548373]: getParameters...
[ INFO] [1638932605.654497116]: setupDevice...
[ INFO] [1638932605.654531897]: JSON file is not provided
[ INFO] [1638932605.654545097]: ROS Node Namespace: camera
[ INFO] [1638932605.654557529]: Device Name: Intel RealSense D435
[ INFO] [1638932605.654570590]: Device Serial No: 817612071347
[ INFO] [1638932605.654582044]: Device physical port: 2-2-2
[ INFO] [1638932605.654592590]: Device FW version: 05.13.00.50
[ INFO] [1638932605.654604463]: Device Product ID: 0x0B07
[ INFO] [1638932605.654618291]: Enable PointCloud: Off
[ INFO] [1638932605.654628837]: Align Depth: Off
[ INFO] [1638932605.654640152]: Sync Mode: Off
[ INFO] [1638932605.654672628]: Device Sensors: 
[ INFO] [1638932605.764430081]: Stereo Module was found.
[ INFO] [1638932605.776536811]: RGB Camera was found.
[ INFO] [1638932605.776588773]: (Confidence, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1638932605.776610773]: num_filters: 0
[ INFO] [1638932605.776624043]: Setting Dynamic reconfig parameters.
[ INFO] [1638932608.623933744]: Done Setting Dynamic reconfig parameters.
[ INFO] [1638932608.624522857]: depth stream is enabled - width: 848, height: 480, fps: 30, Format: Z16
[ INFO] [1638932608.625076839]: color stream is enabled - width: 640, height: 480, fps: 30, Format: RGB8
[ INFO] [1638932608.625190611]: setupPublishers...
[ INFO] [1638932608.627963035]: Expected frequency for depth = 30.00000
[ INFO] [1638932608.658138438]: Expected frequency for color = 30.00000
[ INFO] [1638932608.674053411]: setupStreams...
 08/12 14:03:28,954 WARNING [139669442389760] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
[ INFO] [1638932609.004707118]: SELECTED BASE:Depth, 0
[ INFO] [1638932609.015824615]: RealSense Node Is Up!
[ WARN] [1638932609.072511401]: 
 08/12 14:03:29,073 WARNING [139669442389760] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 08/12 14:03:29,123 WARNING [139669442389760] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 08/12 14:03:29,173 WARNING [139669442389760] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 08/12 14:03:29,306 WARNING [139669442389760] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 08/12 14:03:29,356 WARNING [139669442389760] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 08/12 14:03:29,406 WARNING [139669442389760] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 08/12 14:04:36,627 WARNING [139669442389760] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 08/12 14:04:41,681 WARNING [139669442389760] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 08/12 14:04:42,254 ERROR [139668747962112] (ds5-options.cpp:88) Asic Temperature value is not valid!
 08/12 14:04:43,257 ERROR [139668747962112] (ds5-options.cpp:88) Asic Temperature value is not valid!
 08/12 14:04:44,260 ERROR [139668747962112] (ds5-options.cpp:88) Asic Temperature value is not valid!
 08/12 14:05:18,368 ERROR [139668747962112] (ds5-options.cpp:88) Asic Temperature value is not valid!
 08/12 14:05:19,371 ERROR [139668747962112] (ds5-options.cpp:88) Asic Temperature value is not valid!
 08/12 14:05:20,374 ERROR [139668747962112] (ds5-options.cpp:88) Asic Temperature value is not valid!
 08/12 14:24:27,609 WARNING [139669442389760] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 08/12 14:24:27,659 WARNING [139669442389760] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11

Thanks for your help!

**Comment by MartyG-RealSense** [comment]
Hi @mintnguyenn  If you are receiving the **control_transfer returned** warning only several times during launch and then they stop, or they occur one or two times a minute after launch, then this warning can be safely ignored. You can check in RViz to see whether the topics are being published correctly despite the warnings.  

If this warning is generating continuously though then it can indicate a serious communication problem with the device.

Please try using the custom launch instruction below to set depth and color both to 640x480 and 15 FPS to see whether this reduces the frequency of the warnings.  

**roslaunch realsense2_camera rs_camera.launch depth_width:=640 depth_height:=480 depth_fps:=15 color_width:=640 color_height:=480 color_fps:=15**

**Comment by mintnguyenn** [comment]
Hi @MartyG-RealSense , the WARNING occur pretty much, but it does not affect the quality of rostopic. I think I still can capture the image via callback. But when I run with realsense-viewer, the stream quality is pretty bad, like Full HD with 6fps, and a couple of errors occurred. I think the problem is the SDK version, or something like that, because the rviz can stream pretty well.

**Comment by MartyG-RealSense** [comment]
Ah yes, I see in the log that you have a mismatch between the librealsense version and wrapper version.  

![image](https://user-images.githubusercontent.com/41145062/145400656-0753a7e5-9338-4811-ab31-0813d92a9256.png)

It looks as though you first installed librealsense 2.48.0 and built ROS wrapper version 2.3.2.  Then librealsense was updated to 2.50.0, which is the correct SDK version to match to wrapper 2.50.0.  This is because a particular wrapper version should ideally be matched as closely as possible with a specific librealsense version listed in the wrapper release notes.

![image](https://user-images.githubusercontent.com/41145062/145401476-5db7a277-5569-47c7-a9a9-efe123f30b31.png)

![image](https://user-images.githubusercontent.com/41145062/145401215-f9d61c7b-2a33-4646-b6fd-39d18bbed36b.png)

However, once the librealsense version has been changed (for example, upgrading from 2.48.0 to 2.50.0) then the ROS wrapper has to be built again afterwards.  Then the log message about the mismatch will disappear and it should display the following:

```
RealSense ROS v2.3.2
Built with LibRealSense v2.50.0
Running with LibRealSense v2.50.0
```

**Comment by MartyG-RealSense** [comment]
Hi @mintnguyenn  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
