### ISSUE TITLE
Camera orientation of D435i in ROS

### ISSUE THREAD

**Issue by EhrazImam** [realsenseai/realsense-ros#2190]
Hi I am trying to run Robot localization but when i am moving upward the i am getting values in -y while it should be on z...How can i change the orientation of camera so i can get the exact position of robot.

**Comment by MartyG-RealSense** [comment]
Hi @EhrazImam   The D435i coordinate axes are described in the link below, where Z (depth) is forward, Y+ is downward and Y- is upward.

https://github.com/IntelRealSense/librealsense/blob/master/doc/d435i.md#sensor-origin-and-coordinate-system

I note that you have already seen https://github.com/IntelRealSense/realsense-ros/issues/1176 that discusses this issue.

If performing a static transform as a RealSense user in https://github.com/IntelRealSense/realsense-ros/issues/1176 suggested does not work for you, the link below suggests an alternative approach of changing the camera position / orientation in **RViz** and saving the configuration.

https://answers.ros.org/question/339109/how-to-change-the-cameras-view-in-rviz-in-the-begin/

You may also be interested in an adaptation of Intel's D435i SLAM guide that adds localization and the ability to track and display relative position.

https://shinkansan.github.io/2019-UGRP-DPoom/SLAM

**Comment by EhrazImam** [comment]
Hi @MartyG-RealSense Thanx for your quick reply..
Already tried it but still same issue

**Comment by MartyG-RealSense** [comment]
https://github.com/IntelRealSense/realsense-ros/issues/1099#issuecomment-658101736 may be relevant to your situation.  In it, **Doronhi** the RealSense ROS wrapper developer suggests applying a multiplication to convert to standard ROS frame_id (X-forward, Y-left, Z-up).

**Comment by EhrazImam** [comment]
> [#1099 (comment)](https://github.com/IntelRealSense/realsense-ros/issues/1099#issuecomment-658101736) may be relevant to your situation. In it, **Doronhi** the RealSense ROS wrapper developer suggests applying a multiplication to convert to standard ROS frame_id (X-forward, Y-left, Z-up).

The multiplication @doronhi he's talking about is already in the code but nothing helped...please let me know any other method of changing the orientation of camera

**Comment by MartyG-RealSense** [comment]
I do not personally have a further suggestion to make, unfortunately.

Wehn you say that you are doing robot localization, do you mean that you are literally using the ROS **robot_localization** package, please?

http://wiki.ros.org/robot_localization

**Comment by bhaskar-glitch** [comment]
> I do not personally have a further suggestion to make, unfortunately.
> 
> Wehn you say that you are doing robot localization, do you mean that you are literally using the ROS **robot_localization** package, please?
> 
> http://wiki.ros.org/robot_localization

No! I'm using **VINS_FUSION**(https://github.com/pjrambo/VINS-Fusion-gpu) with d435i and I'm only using stereo camera of d435i not the imu of it!

**Comment by MartyG-RealSense** [comment]
I researched your question extensively in regard to using z as the up-down position (non IMU) in VINS-FUSION instead of y but could find no guidance unfortunately.

**Comment by MartyG-RealSense** [comment]
Hi @bhaskar-glitch  Do you require further assistance with this case, please?  Thanks!

**Comment by bhaskar-glitch** [comment]
> Hi @bhaskar-glitch Do you require further assistance with this case, please? Thanks!

How can I extract imu values of realsense d435i externally using GPIO pins...??

**Comment by MartyG-RealSense** [comment]
Hi @bhaskar-glitch  You will not be able to obtain stream data from the GPIO pins, as described in https://github.com/IntelRealSense/librealsense/issues/10049

**Comment by MartyG-RealSense** [comment]
Hi @bhaskar-glitch  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
