### ISSUE TITLE
How to get transformation of d455 from its IMU?

### ISSUE THREAD

**Issue by victorll998** [realsenseai/realsense-ros#2195]
Hello there,

I have been noticing that d455 has the same IMU unit as d435i. I would like to know if there is any interface can generate d455's transformation in ROS.

I tried to set unite_imu_method to copy or linear_interpolation so as to get fused IMU data and publish odom tf frame in ROS. But little did I proceed to get a new topic with IMU data or transformation. 

Any suggestion about it would be helpful.

---
I'm using realsense-ros 2.42 on my Ubuntu 20.04 machine.

**Comment by MartyG-RealSense** [comment]
Hi @victorll998  Does the information provided in https://github.com/IntelRealSense/realsense-ros/issues/1449#issuecomment-711675699 about obtaining the gyro transform with **rosrun tf tf_echo camera_depth_optical_frame camera_gyro_optical_frame** answer your question, please?

**Comment by victorll998** [comment]
Yes, that's what I'm looking for at the moment.

Could you also have a look if the launch parameter unite_imu_method works for your machine?

**Comment by MartyG-RealSense** [comment]
In the rs_camera launch file, the IMU 'gyro' and 'accel' topics are disabled by default.  Have you added the commands below to your roslaunch instruction to enable publishing of the IMU topics, please?

**enable_gyro:=true enable_accel:=true**

For example:

**roslaunch realsense2_camera rs_camera.launch enable_gyro:=true enable_accel:=true unite_imu_method:=linear_interpolation**

**Comment by victorll998** [comment]
I found my mistake of wrong substitution args. 

I fixed it and now I can see the new IMU topic, but there is no new IMU topic message. I am not sure if it is working.

--- 
SUMMARY
========

PARAMETERS
 * /d455/passthrough_x/filter_field_name: x
 * /d455/passthrough_x/filter_limit_max: 2
 * /d455/passthrough_x/filter_limit_min: -2
 * /d455/passthrough_x/filter_limit_negative: False
 * /d455/passthrough_z/filter_field_name: z
 * /d455/passthrough_z/filter_limit_max: 6
 * /d455/passthrough_z/filter_limit_min: 0.4
 * /d455/passthrough_z/filter_limit_negative: False
 * /d455/realsense2_camera/accel_fps: 0
 * /d455/realsense2_camera/accel_frame_id: d455_accel_frame
 * /d455/realsense2_camera/accel_optical_frame_id: d455_accel_optica...
 * /d455/realsense2_camera/align_depth: True
 * /d455/realsense2_camera/aligned_depth_to_color_frame_id: d455_aligned_dept...
 * /d455/realsense2_camera/aligned_depth_to_fisheye1_frame_id: d455_aligned_dept...
 * /d455/realsense2_camera/aligned_depth_to_fisheye2_frame_id: d455_aligned_dept...
 * /d455/realsense2_camera/aligned_depth_to_fisheye_frame_id: d455_aligned_dept...
 * /d455/realsense2_camera/aligned_depth_to_infra1_frame_id: d455_aligned_dept...
 * /d455/realsense2_camera/aligned_depth_to_infra2_frame_id: d455_aligned_dept...
 * /d455/realsense2_camera/allow_no_texture_points: False
 * /d455/realsense2_camera/base_frame_id: d455_link
 * /d455/realsense2_camera/calib_odom_file: 
 * /d455/realsense2_camera/clip_distance: -1.0
 * /d455/realsense2_camera/color_fps: 15
 * /d455/realsense2_camera/color_frame_id: d455_color_frame
 * /d455/realsense2_camera/color_height: 720
 * /d455/realsense2_camera/color_optical_frame_id: d455_color_optica...
 * /d455/realsense2_camera/color_width: 1280
 * /d455/realsense2_camera/confidence_fps: 30
 * /d455/realsense2_camera/confidence_height: 480
 * /d455/realsense2_camera/confidence_width: 640
 * /d455/realsense2_camera/depth_fps: 15
 * /d455/realsense2_camera/depth_frame_id: d455_depth_frame
 * /d455/realsense2_camera/depth_height: 720
 * /d455/realsense2_camera/depth_optical_frame_id: d455_depth_optica...
 * /d455/realsense2_camera/depth_width: 1280
 * /d455/realsense2_camera/device_type: d455
 * /d455/realsense2_camera/enable_accel: True
 * /d455/realsense2_camera/enable_color: True
 * /d455/realsense2_camera/enable_confidence: True
 * /d455/realsense2_camera/enable_depth: True
 * /d455/realsense2_camera/enable_fisheye1: False
 * /d455/realsense2_camera/enable_fisheye2: False
 * /d455/realsense2_camera/enable_fisheye: False
 * /d455/realsense2_camera/enable_gyro: True
 * /d455/realsense2_camera/enable_infra1: False
 * /d455/realsense2_camera/enable_infra2: False
 * /d455/realsense2_camera/enable_infra: False
 * /d455/realsense2_camera/enable_pointcloud: False
 * /d455/realsense2_camera/enable_pose: False
 * /d455/realsense2_camera/enable_sync: False
 * /d455/realsense2_camera/filters: pointcloud
 * /d455/realsense2_camera/fisheye1_frame_id: d455_fisheye1_frame
 * /d455/realsense2_camera/fisheye1_optical_frame_id: d455_fisheye1_opt...
 * /d455/realsense2_camera/fisheye2_frame_id: d455_fisheye2_frame
 * /d455/realsense2_camera/fisheye2_optical_frame_id: d455_fisheye2_opt...
 * /d455/realsense2_camera/fisheye_fps: 30
 * /d455/realsense2_camera/fisheye_frame_id: d455_fisheye_frame
 * /d455/realsense2_camera/fisheye_height: 0
 * /d455/realsense2_camera/fisheye_optical_frame_id: d455_fisheye_opti...
 * /d455/realsense2_camera/fisheye_width: 0
 * /d455/realsense2_camera/gyro_fps: 0
 * /d455/realsense2_camera/gyro_frame_id: d455_gyro_frame
 * /d455/realsense2_camera/gyro_optical_frame_id: d455_gyro_optical...
 * /d455/realsense2_camera/imu_optical_frame_id: d455_imu_optical_...
 * /d455/realsense2_camera/infra1_frame_id: d455_infra1_frame
 * /d455/realsense2_camera/infra1_optical_frame_id: d455_infra1_optic...
 * /d455/realsense2_camera/infra2_frame_id: d455_infra2_frame
 * /d455/realsense2_camera/infra2_optical_frame_id: d455_infra2_optic...
 * /d455/realsense2_camera/infra_fps: 30
 * /d455/realsense2_camera/infra_height: 480
 * /d455/realsense2_camera/infra_rgb: False
 * /d455/realsense2_camera/infra_width: 640
 * /d455/realsense2_camera/initial_reset: False
 * /d455/realsense2_camera/json_file_path: 
 * /d455/realsense2_camera/linear_accel_cov: 0.01
 * /d455/realsense2_camera/odom_frame_id: d455_odom_frame
 * /d455/realsense2_camera/ordered_pc: False
 * /d455/realsense2_camera/pointcloud_texture_index: 0
 * /d455/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /d455/realsense2_camera/pose_frame_id: d455_pose_frame
 * /d455/realsense2_camera/pose_optical_frame_id: d455_pose_optical...
 * /d455/realsense2_camera/publish_odom_tf: True
 * /d455/realsense2_camera/publish_tf: True
 * /d455/realsense2_camera/rosbag_filename: 
 * /d455/realsense2_camera/serial_no: 043422252203
 * /d455/realsense2_camera/tf_publish_rate: 0.0
 * /d455/realsense2_camera/topic_odom_in: d455/odom_in
 * /d455/realsense2_camera/unite_imu_method: linear_interpolation
 * /d455/realsense2_camera/usb_port_id: 
 * /d455/rgb_camera/auto_exposure_priority: False
 * /d455/rgb_camera/auto_exposure_roi/bottom: 470
 * /d455/rgb_camera/auto_exposure_roi/left: 800
 * /d455/rgb_camera/auto_exposure_roi/right: 1000
 * /d455/rgb_camera/auto_exposure_roi/top: 250
 * /d455/rgb_camera/backlight_compensation: True
 * /d455/rgb_camera/enable_auto_exposure: True
 * /d455/rgb_camera/enable_white_balance: True
 * /d455/stereo_module/auto_exposure_roi/bottom: 470
 * /d455/stereo_module/auto_exposure_roi/left: 800
 * /d455/stereo_module/auto_exposure_roi/right: 1000
 * /d455/stereo_module/auto_exposure_roi/top: 250
 * /d455/stereo_module/emitter_always_on: False
 * /d455/stereo_module/enable_auto_exposure: True
 * /rosdistro: noetic
 * /rosversion: 1.15.11

NODES
  /d455/
    d455_manager (nodelet/nodelet)
    passthrough_x (nodelet/nodelet)
    passthrough_z (nodelet/nodelet)
    realsense2_camera (nodelet/nodelet)

auto-starting new master
process[master]: started with pid [57118]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 01506d6a-5c6e-11ec-861e-61fe221d364a
process[rosout-1]: started with pid [57130]
started core service [/rosout]
process[d455/d455_manager-2]: started with pid [57137]
process[d455/realsense2_camera-3]: started with pid [57138]
process[d455/passthrough_z-4]: started with pid [57139]
process[d455/passthrough_x-5]: started with pid [57140]
[ INFO] [2021-12-13 23:40:08]: Loading nodelet /d455/passthrough_z of type pcl/PassThrough to manager d455_manager with the following remappings:
[ INFO] [2021-12-13 23:40:08]: /d455/passthrough_z/input -> /d455/depth/color/points
[ INFO] [2021-12-13 23:40:08]: /d455/passthrough_z/output -> /d455/z/points
[ INFO] [2021-12-13 23:40:08]: waitForService: Service [/d455/d455_manager/load_nodelet] has not been advertised, waiting...
[ INFO] [2021-12-13 23:40:08]: Loading nodelet /d455/passthrough_x of type pcl/PassThrough to manager d455_manager with the following remappings:
[ INFO] [2021-12-13 23:40:08]: /d455/passthrough_x/input -> /d455/z/points
[ INFO] [2021-12-13 23:40:08]: /d455/passthrough_x/output -> /d455/range_filter/clouds
[ INFO] [2021-12-13 23:40:08]: waitForService: Service [/d455/d455_manager/load_nodelet] has not been advertised, waiting...
[ INFO] [2021-12-13 23:40:08]: Initializing nodelet with 8 worker threads.
[ INFO] [2021-12-13 23:40:08]: waitForService: Service [/d455/d455_manager/load_nodelet] is now available.
[ INFO] [2021-12-13 23:40:08]: waitForService: Service [/d455/d455_manager/load_nodelet] is now available.
[ INFO] [2021-12-13 23:40:08]: RealSense ROS v2.2.22
[ INFO] [2021-12-13 23:40:08]: Built with LibRealSense v2.42.0
[ INFO] [2021-12-13 23:40:08]: Running with LibRealSense v2.42.0
[ INFO] [2021-12-13 23:40:08]:  
[ INFO] [2021-12-13 23:40:08]: Device with serial number 043422252203 was found.

[ INFO] [2021-12-13 23:40:08]: Device with physical ID /sys/devices/pci0000:00/0000:00:0d.0/usb2/2-1/2-1:1.0/video4linux/video0 was found.
[ INFO] [2021-12-13 23:40:08]: Device with name Intel RealSense D455 was found.
[ INFO] [2021-12-13 23:40:08]: Device with port number 2-1 was found.
[ INFO] [2021-12-13 23:40:08]: Device USB type: 3.2
[ INFO] [2021-12-13 23:40:08]: getParameters...
[ INFO] [2021-12-13 23:40:08]: setupDevice...
[ INFO] [2021-12-13 23:40:08]: JSON file is not provided
[ INFO] [2021-12-13 23:40:08]: ROS Node Namespace: d455
[ INFO] [2021-12-13 23:40:08]: Device Name: Intel RealSense D455
[ INFO] [2021-12-13 23:40:08]: Device Serial No: 043422252203
[ INFO] [2021-12-13 23:40:08]: Device physical port: /sys/devices/pci0000:00/0000:00:0d.0/usb2/2-1/2-1:1.0/video4linux/video0
[ INFO] [2021-12-13 23:40:08]: Device FW version: 05.12.11.00
[ INFO] [2021-12-13 23:40:08]: Device Product ID: 0x0B5C
[ INFO] [2021-12-13 23:40:08]: Enable PointCloud: On
[ INFO] [2021-12-13 23:40:08]: Align Depth: On
[ INFO] [2021-12-13 23:40:08]: Sync Mode: On
[ INFO] [2021-12-13 23:40:08]: Device Sensors: 
[ INFO] [2021-12-13 23:40:08]: Stereo Module was found.
 14/12 10:40:08,793 WARNING [140343236376320] (backend-v4l2.cpp:1357) Pixel format 36315752-1a66-a242-9065-d01814a likely requires patch for fourcc code RW16!
[ INFO] [2021-12-13 23:40:08]: RGB Camera was found.
[ INFO] [2021-12-13 23:40:08]: Motion Module was found.
[ INFO] [2021-12-13 23:40:08]: (Confidence, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [2021-12-13 23:40:08]: Add Filter: pointcloud
[ INFO] [2021-12-13 23:40:08]: num_filters: 1
[ INFO] [2021-12-13 23:40:08]: Setting Dynamic reconfig parameters.
[ WARN] [2021-12-13 23:40:08]: Param '/d455/rgb_camera/power_line_frequency' has value 3 that is not in the enum { {50Hz: 1} {60Hz: 2} {Disabled: 0} }. Removing this parameter from dynamic reconfigure options.
[ INFO] [2021-12-13 23:40:08]: Done Setting Dynamic reconfig parameters.
[ INFO] [2021-12-13 23:40:08]: depth stream is enabled - width: 1280, height: 720, fps: 15, Format: Z16
[ INFO] [2021-12-13 23:40:08]: color stream is enabled - width: 1280, height: 720, fps: 15, Format: RGB8
[ INFO] [2021-12-13 23:40:08]: gyro stream is enabled - fps: 400
[ INFO] [2021-12-13 23:40:08]: accel stream is enabled - fps: 250
[ INFO] [2021-12-13 23:40:08]: setupPublishers...
[ INFO] [2021-12-13 23:40:08]: Expected frequency for depth = 15.00000
[ INFO] [2021-12-13 23:40:08]: Expected frequency for color = 15.00000
[ INFO] [2021-12-13 23:40:08]: Expected frequency for aligned_depth_to_color = 15.00000
[ INFO] [2021-12-13 23:40:08]: Start publisher IMU
[ INFO] [2021-12-13 23:40:08]: setupStreams...
[ INFO] [2021-12-13 23:40:09]: insert Depth to Stereo Module
[ INFO] [2021-12-13 23:40:09]: insert Color to RGB Camera
[ INFO] [2021-12-13 23:40:09]: insert Gyro to Motion Module
[ INFO] [2021-12-13 23:40:09]: insert Accel to Motion Module
 14/12 10:40:09,022 WARNING [140342611404544] (sensor.cpp:991) HID timestamp not found, switching to Host timestamps.
[ WARN] [2021-12-13 23:40:09]: Frame metadata isn't available! (frame_timestamp_domain = RS2_TIMESTAMP_DOMAIN_SYSTEM_TIME)
 14/12 10:40:09,043 WARNING [140342587229952] (backend-v4l2.cpp:1775) Invalid md size: bytes used =  0 ,start offset=10
 14/12 10:40:09,043 WARNING [140342587229952] (backend-v4l2.cpp:1775) Invalid md size: bytes used =  0 ,start offset=10
 14/12 10:40:09,043 WARNING [140342587229952] (backend-v4l2.cpp:1775) Invalid md size: bytes used =  0 ,start offset=10
[ INFO] [2021-12-13 23:40:09]: SELECTED BASE:Depth, 0
 14/12 10:40:09,043 WARNING [140342587229952] (backend-v4l2.cpp:1775) Invalid md size: bytes used =  0 ,start offset=10
 14/12 10:40:09,063 WARNING [140342571448064] (backend-v4l2.cpp:1775) Invalid md size: bytes used =  0 ,start offset=10
 14/12 10:40:09,063 WARNING [140342571448064] (backend-v4l2.cpp:1775) Invalid md size: bytes used =  0 ,start offset=10
 14/12 10:40:09,063 WARNING [140342571448064] (backend-v4l2.cpp:1775) Invalid md size: bytes used =  0 ,start offset=10
[ INFO] [2021-12-13 23:40:09]: RealSense Node Is Up!
 14/12 10:40:09,063 WARNING [140342571448064] (backend-v4l2.cpp:1775) Invalid md size: bytes used =  0 ,start offset=10
[ WARN] [2021-12-13 23:40:10]: Hardware Notification:Depth stream start failure,1.63944e+12,Error,Hardware Error
[ WARN] [2021-12-13 23:40:13]: This node/nodelet subscribes topics only when subscribed.
[ WARN] [2021-12-13 23:40:13]: This node/nodelet subscribes topics only when subscribed.

**Comment by MartyG-RealSense** [comment]
The log states that the IMU topics are being published, but you are experiencing the **Invalid md size: bytes used = 0 ,start offset=10** warning.  In https://github.com/IntelRealSense/realsense-ros/issues/1734 a couple of RealSense ROS users found that building librealsense from source code with the **V4L backend** (using the CMake build term **-DFORCE_LIBUVC=OFF**) resolved this warning.

**Comment by MartyG-RealSense** [comment]
Hi @victorll998  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
