### ISSUE TITLE
Point Cloud orientation 

### ISSUE THREAD

**Issue by bhaskar-glitch** [realsenseai/realsense-ros#2198]
Hi,
Im using realsense d435i and facing an issue with the point cloud of realsense of topic /camera/depth/color/points
in orientation of pointcloud is -y is upward...the problem is -y is facing toward z axis as in this picture
![IMG-20211217-WA0000](https://user-images.githubusercontent.com/77039416/146558696-ee7932b4-301c-485a-82f0-5f4a2768f535.jpg)

Please help

**Comment by MartyG-RealSense** [comment]
Hi @bhaskar-glitch   Is your question a continuation of the earlier case https://github.com/IntelRealSense/realsense-ros/issues/2190 about orientation that you commented on, please?

**Comment by bhaskar-glitch** [comment]
> Hi @bhaskar-glitch Is your question a continuation of the earlier case #2190 about orientation that you commented on, please?

Yah! Orientation problem is same but issue is different

**Comment by MartyG-RealSense** [comment]
I researched this issue extensively again but like in https://github.com/IntelRealSense/realsense-ros/issues/2190 the answer still seems to be to use a static transform.  You can see an example of this in a guide at the link below regarding the RealSense T265 Tracking camera (I know you are using D435i), where the T265's axes in its 'pose' coordinate system are Y up and Z forward and there is a static transform performed between the pose_frame_id and the base_frame_id of the camera.

https://www.ross-robotics.co.uk/news/intel-realsense-t265-tracking-camera-for-mobile-robotics-first-impressions

**Comment by MartyG-RealSense** [comment]
Hi @bhaskar-glitch  Do you require further assistance with this case, please?  Thanks!

**Comment by bhaskar-glitch** [comment]
> Hi @bhaskar-glitch Do you require further assistance with this case, please? Thanks!

 I haven't got any solution of the issue yet..let this issue opened so that anyone who knows the solution..will assist me

**Comment by MartyG-RealSense** [comment]
Okay, I will leave this case open for a further time period so that people can see it.  Thanks for the update.

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
