### ISSUE TITLE
(roslaunch realsense2_camera rs_camera.launch) have some warning 

### ISSUE THREAD

**Issue by gaoyi-2016** [realsenseai/realsense-ros#2208]
![2021-12-31 16-08-03屏幕截图](https://user-images.githubusercontent.com/80136256/147811471-927cc412-a803-4bc3-a062-9391041c4f06.png)

**Comment by MartyG-RealSense** [comment]
Hi @gaoyi-2016  You can ignore that warning as it is not something to be concerned about.  Power line frequency is a control for preventing image flickering.  It is typically used in locations where there are fluorescent lights such as ceiling strip lights whose flickering may cause disruption to the image.

**Comment by gaoyi-2016** [comment]
ok,thanks,but there is a problem i have 
sometimes /camera/aligned_depth_to_color/image_raw    and     /camera/color/image_raw  number is same,sometimes the number is different,can u help me
![2021-12-31 18-01-37屏幕截图](https://user-images.githubusercontent.com/80136256/147817614-7615ba47-117e-42f2-abb2-2f89868eca50.png)

**Comment by gaoyi-2016** [comment]
@MartyG-RealSense

**Comment by gaoyi-2016** [comment]
the problem is staying when using rosbag  data
![2021-12-31 18-17-11屏幕截图](https://user-images.githubusercontent.com/80136256/147817729-d567c194-03c3-469d-ba70-8bd93e8458bc.png)
![2021-12-31 18-01-37屏幕截图](https://user-images.githubusercontent.com/80136256/147817738-bcc6feca-350d-493b-9129-6a928f7df2e6.png)

**Comment by gaoyi-2016** [comment]
my  system is ubuntu18.04 , realsense2.40.0 , realsensense-ros-2.2.20
when i static d435i and reinforce usb cable,the number is same,
but when i move d435i and usb cable will be loose,the number is different,
i doubt my usb cable is not totally in the rabbet,
can u help me,thanks

**Comment by MartyG-RealSense** [comment]
If you consistently get the same number when not moving but the numbers vary if the cable moves, you could consider replacing the USB cable with a 'screw lock' one.  On the side of the camera there are small holes either side of the USB port for screwing a screw-lock connector in firmly, as shown in https://github.com/IntelRealSense/librealsense/issues/3118#issuecomment-456392939

**Comment by gaoyi-2016** [comment]
ok,i read your answer and think it will help me truely,thanks

**Comment by MartyG-RealSense** [comment]
You are very welcome, @gaoyi-2016   :)

If you do obtain a USB-C screw-lock cable, make sure that it is a **USB 3** cable as it is easy to mistakenly purchase a slower USB 2 USB-C cable.

**Comment by gaoyi-2016** [comment]
Ok,i have purchased a USB-C 3 screw-lock cable and i think it will help me.
its a good experience,i will keep supporting inter and hope tomorrow you have a lucky year.

**Comment by MartyG-RealSense** [comment]
Hi @gaoyi-2016  Do you require further assistance with this case, please?  Thanks!

**Comment by gaoyi-2016** [comment]
I am sorry to reply late.
I have solved this problem  in my another issue#10127,you could close this issue.
Thanks for your help.

**Comment by MartyG-RealSense** [comment]
Thanks very much @gaoyi-2016 for the update.  As you suggested, I will close the issue.  Thanks again!
