### ISSUE TITLE
rosrun pcl_ros pointcloud_to_pcd input:/camera/depth/color/points does not save files after roslaunch realsense2_camera demo_pointcloud.launch

### ISSUE THREAD

**Issue by Gaurav37** [realsenseai/realsense-ros#2209]
After I run 
``` roslaunch realsense2_camera demo_pointcloud.launch ```
Rviz opens with a pointcloud image
![Screenshot from 2021-12-31 18-49-12](https://user-images.githubusercontent.com/19994641/147841237-c3e50bf2-967c-428e-a10f-46fee6accd5a.png)
.

Then I run 
```
rosrun pcl_ros pointcloud_to_pcd input:/camera/depth/color/points
```
Output is 
[ INFO] [1640994236.548494422]: Saving as ASCII PCD
[ INFO] [1640994236.551086164]: Listening for incoming data on topic /input
Then nothing happens
I have to press Ctrl C and then I see no files generated.

**Comment by MartyG-RealSense** [comment]
Hi @Gaurav37  It looks as though your pointcloud_to_pcd command is missing an equals sign from its input.  Please try the command below.

**rosrun pcl_ros pointcloud_to_pcd input:=/camera/depth/color/points**

**Comment by Gaurav37** [comment]
Hey Thanks @MartyG-RealSense Apologies for silly mistake :)

**Comment by MartyG-RealSense** [comment]
No problem at all - thanks for the update!
