### ISSUE TITLE
RGB color distortion (D435i, python, opencv)

### ISSUE THREAD

**Issue by LightwishWONG** [realsenseai/realsense-ros#2214]
Recently I have been using realsense D435i camera in ROS to capture RGB images. I notice the RGB images received by D435i are generally more brighter and blurry than original ones, which leads to noticeable RGB distortion. RGBs of some pixels may even severely changed. But if I use my phone camera, this problem disappears. Below are codes, transmitted RGB images and received RGB images.

Codes:
```python
import rospy 
import message_filters 
import cv2, cv_bridge   #cv_bridge: bridge between ROS image and OpenCV image
import numpy as np
from sensor_msgs.msg import Image   # ROS image message format

def rxCallback(RGB, depth):
    bridge = cv_bridge.CvBridge() 
    RGB_frame = bridge.imgmsg_to_cv2(RGB, desired_encoding='bgr8')  # ROS image -> OpenCV image
    cv2.imshow('RGB_frame', RGB_frame)
    cv2.waitKey(1)


def rx_ros(): 
    # read image
    im_sub = message_filters.Subscriber('/camera/color/image_raw', Image)
    dep_sub = message_filters.Subscriber('/camera/depth/image_rect_raw', Image)

    timeSynchronizer = message_filters.ApproximateTimeSynchronizer([im_sub, dep_sub], 10, 0.5)
    timeSynchronizer.registerCallback(rxCallback)


if __name__ == '__main__': 
    rospy.init_node("rx_ros")    # create a node
    rx_ros()
    rospy.spin()
```

Transmitted image:
![Tx_0](https://user-images.githubusercontent.com/97330420/148636138-ee0e1a6e-2515-43c8-a548-078755a98877.png)

Received image:
![Rx_0](https://user-images.githubusercontent.com/97330420/148636143-369ba949-5088-4792-ae45-2f9216886632.png)

Should I change some configurations of D435i, like white-balancing or auto-explosure? Or how to do image processing for this problem? Could anyone help me solve it? Thanks!

**Comment by MartyG-RealSense** [comment]
Hi @LightwishWONG  That kind of change in color tint makes me think of white balance too.  Decreasing the white balance below its default value makes the tinting become progressively more blue, whilst increasing it above the default makes the colors brighter and warmer.

By default the white balance value should be **4600**.  You can check it by launching the ROS wrapper and then opening the **dynamic reconfigure** interface after launch to check the camera values during runtime.  The white balance should be under the **RGB** section of the dynamic reconfigure interface, as described in the wrapper's documentation about it in the link below.

https://github.com/IntelRealSense/realsense-ros#set-camera-controls-using-dynamic-reconfigure-params

**Comment by MartyG-RealSense** [comment]
Hi @LightwishWONG  Do you require further assistance with this case, please?  Thanks!

**Comment by LightwishWONG** [comment]
@MartyG-RealSense Sorry for my late reply. I don't require further assistance and I think this issue can be closed. Thank you for your kind attention!

**Comment by MartyG-RealSense** [comment]
You are very welcome, @LightwishWONG - thanks very much for the update!
