### ISSUE TITLE
Frame name doesn't change even the camera_name argument is passed

### ISSUE THREAD

**Issue by nmoduga** [realsenseai/realsense-ros#2223]
Hi, I ran rs_launch.py with camera_name as cam_1.
command: ros2 launch realsense2_camera rs_launch.py camera_name:=cam_1 
On ROS 2 FOXY, Ubuntu 20.04
I can see the topic names have changed to 
/cam_1/color/camera_info
/cam_1/color/image_raw
/cam_1/depth/camera_info
/cam_1/depth/image_rect_raw
/cam_1/extrinsics/depth_to_color

but the names of the frames are still same for ex. camera_link, camera_color_optical_frame etc
How can I get the frame names changed?

**Comment by MartyG-RealSense** [comment]
Hi @nmoduga  May I first confirm please whether you are expecting the **frame_id** names of the topics to be updated when defining 'cam_1', like in the image below?

![image](https://user-images.githubusercontent.com/41145062/149811560-4323a4e8-5aa4-4905-8198-12716beb465d.png)
![image](https://user-images.githubusercontent.com/41145062/149811841-96f25535-4bc5-47b7-b260-fadd2dab5b65.png)

**Comment by nmoduga** [comment]
HI @MartyG-RealSense ,
Yes, exactly.

**Comment by MartyG-RealSense** [comment]
Are you using a single camera or multiple cameras, please?  Custom camera names are typically used when there is more than one camera being defined, as described in the multiple camera section of the ROS2 wrapper documentation in the link below.

https://github.com/IntelRealSense/realsense-ros/tree/ros2#work-with-multiple-cameras

**Comment by nmoduga** [comment]
Actually, I'm using two cameras and want to run both separately in different terminals. By the way, I even tried the command from the above link with rs__multi_camera_launch.py but no success. I see topics for only one camera.
{/camera/color/camera_info
/camera/color/image_raw
/camera/depth/camera_info
/camera/depth/image_rect_raw
/camera/extrinsics/depth_to_color}

**Comment by MartyG-RealSense** [comment]
And you are including the unique serial number of each camera?  For example, there was a past case where the same serial number was being used for both cameras and so the details of only one camera were being used.

**Comment by nmoduga** [comment]
Yes, I included two different serial numbers.

**Comment by MartyG-RealSense** [comment]
I will highlight your problem to **Doronhi** the RealSense ROS wrapper developer.  Thanks very much for your patience!

**Comment by nmoduga** [comment]
Thank you @MartyG-RealSense :)

**Comment by doronhi** [comment]
What version of realsense2_camera do you have? An issue like the one you describe was reported for [ros2-beta](https://github.com/IntelRealSense/realsense-ros/tree/ros2-beta) version and was fixed in #2205
With version 3.2.3, after running `ros2 launch realsense2_camera rs_launch.py camera_name:=cam_1` in terminal 1 I see the following in terminal 2:
```
ros2 topic list

/cam_1/color/camera_info
/cam_1/color/image_raw
/cam_1/color/metadata
/cam_1/depth/camera_info
...
```

and
```
ros2 topic echo /cam_1/color/camera_info | grep frame_id

  frame_id: cam_1_color_optical_frame
  frame_id: cam_1_color_optical_frame
  frame_id: cam_1_color_optical_frame
  frame_id: cam_1_color_optical_frame
  frame_id: cam_1_color_optical_frame
...
```

**Comment by nmoduga** [comment]
Hi Doronhi,
The current version I'm using was installed in Oct 2021. I guess that's the previous version. I just upgraded it to the current version and all seems to be good now.
Thank you so much for the prompt support.

**Comment by doronhi** [comment]
It was my pleasure.
