### ISSUE TITLE
Support for rs2::net_device

### ISSUE THREAD

**Issue by imwhocodes** [realsenseai/realsense-ros#2233]
Hi

Would be possible to add support for rs2::net_device ([net device mode](https://dev.intelrealsense.com/docs/open-source-ethernet-networking-for-intel-realsense-depth-cameras)) to the nodelet launcher?

The [API](https://dev.intelrealsense.com/docs/open-source-ethernet-networking-for-intel-realsense-depth-cameras#section-3-4-sdk-examples) is the same, only difference is how you add the camera

Thanks

**Comment by MartyG-RealSense** [comment]
Hi @imwhocodes  Are you asking if it is possible to use **rs2::net_device** to access the networking system described in the white paper from a self-created script, please?  If you are then this has already been achieved in the librealsense SDK in cases such as the ones in the links below.
 
https://github.com/IntelRealSense/librealsense/issues/6376
https://github.com/IntelRealSense/librealsense/issues/8423
https://github.com/IntelRealSense/librealsense/issues/8766

If you have something else in mind, could you provide more information about what you are aiming to achieve, please?  

Given that you have posted your question on the RealSense ROS forum, are you asking about how to implement the networking system from the paper in ROS?

**Comment by MartyG-RealSense** [comment]
Hi @imwhocodes  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
