### ISSUE TITLE
Integrate an external IMU with L515. Due to [ERROR] [1643357795.449040888]: Overwriting previous data! Make sure IMU is published faster than data rate. (last image stamp buffered=1643357794.766366 and new one is 1643357794.766366, last imu stamp received=1643357794.751868)

### ISSUE THREAD

**Issue by HHendy69** [realsenseai/realsense-ros#2234]
I am trying the camera L515 with rtabmap. However, I think the IMU inside the camera isn't enough the Mapping, especially my platform is aerial and moves sometimes with high acceleration which isn't a problem for the odometry yet the IMU. I decided to use an external IMU with high rate to offset the effect of this problem. Nonetheless, I can't figure the transformation into camera_imu_optical_frame. I managed to get the internal IMU with internal IMU in the camera. But I need to provide a kind of "static_transform" which I really can't figure out! I tried the following but the the cloud is kind of flipped
![image](https://user-images.githubusercontent.com/45830803/151508873-79eddf23-b032-42f9-8bb6-28946b61b2a5.png)

External IMU rotation is expressed like that 

`  <node pkg="tf" type="static_transform_publisher" name="camera_aligned" args=" 0 0 0 -1.57 0 -1.57 /camera_link /camera_imu_optical_frame  500"/>`

Here (https://github.com/IntelRealSense/librealsense/tree/master/doc) I can only find information regarding D series and T. Yet I ain't sure what from L515.
 of course with internal camera IMU
I get the cloud ordinarily
![image](https://user-images.githubusercontent.com/45830803/151509281-674fb5a6-069d-479b-8623-a6d4640899cc.png)

My Question: How is the the IMU in l515 is built in? and How are its coordinates transformed into camera transformation. More precisely the transformation between camera_link frame and camera_imu_optical_frame frame.

By the way I get the following error from time to another when I use the internal IMU
[ERROR] [1643357795.449040888]: Overwriting previous data! Make sure IMU is published faster than data rate. (last image stamp buffered=1643357794.766366 and new one is 1643357794.766366, last imu stamp received=1643357794.751868)

**Comment by MartyG-RealSense** [comment]
Hi @hichamhendy  The L515 uses the **Bosch BMI085** IMU component.  Other IMU-equipped RealSense cameras (D435i, D455) have similarly used Bosch BMI components. The link below leads to technical information about the L515's BMI085.

https://www.bosch-sensortec.com/products/motion-sensors/imus/bmi085/

Although the Bosch data sheet quotes a sensitivity range between -+ 2g and -+ 16g, https://github.com/IntelRealSense/librealsense/issues/3991 disclosed that RealSense limits the supported sensitivity range to -+ 4g in the 400 Series IMU-equipped models.  I would assume that the same is true for the L515.

There is a case about the L515 and the **Overwriting previous data! Make sure IMU is published faster than data rate** error on the RTABMAP forum at https://github.com/introlab/rtabmap/issues/687 that may be a helpful reference.

A RealSense team member advises in https://github.com/IntelRealSense/librealsense/issues/8249 that the coordinate system information for the D435i model applies to the L515 too.

https://github.com/IntelRealSense/librealsense/blob/master/doc/d435i.md#sensor-origin-and-coordinate-system

**Comment by hichamhendy** [comment]
I fixed the IMU in the same way to get the linear acceleration with ENU-coordinates
![image](https://user-images.githubusercontent.com/45830803/151970946-7c037c67-6ded-45e6-9627-5d052f8dc1c8.png)

I also stream static tf using 
`<node pkg="tf" type="static_transform_publisher" name="camera_aligned" args="0 0 0 -1.571 0 -1.571 /camera_link /camera_imu_optical_frame  500"/>`
, which is identical to the original transform published from the realsense_driver. However, I get the map flipped on left side!!

**Comment by HHendy69** [comment]
I made it to align an external IMU with camera coordinates

`  <node pkg="tf" type="static_transform_publisher" name="camera_aligned" args="0 0 0 -1.571 0 -1.571 /camera_link /camera_imu_optical_frame  500"/>`
![image](https://user-images.githubusercontent.com/45830803/151979705-74addf5a-8094-424c-991e-0ea1ae7fc0ce.png)

One must reconfigure the IMU to stream on ENU and be aligned with internal IMU. Publish both parallel  till you get the correct alignment.

**Comment by MartyG-RealSense** [comment]
It's great news that you achieved a solution for aligning to an external IMU, @hichamhendy  - thanks so much for sharing the details with the RealSense ROS community!
