### ISSUE TITLE
(messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11

### ISSUE THREAD

**Issue by grafoteka** [realsenseai/realsense-ros#2248]
My hardware and software are：Jetson Nano 4GB; L515; ubuntu18.04; ros-melodic; librealsense v2.50.0.
I installed the packages and libraries with the official ros packages. 
```
$ sudo apt install ros-melodic-realsense2-camera
$ sudo apt install ros-melodic-realsense2-description
```

I can use the realsense-viewer without any problem.

Then I found that when running the ros driver, the following warnings always appear, and the warnings are always generated when the program is running. How can I solve it? What are the consequences of this warning?

It should be noted that this warning will always appear with a certain frequency (~ 1 sec). 

The warning is as following: 
`(messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11`

I have try with 30FPS, 15FPS and 6FPS, but I have the same the error with all the configurations. 

```
$ roslaunch realsense2_camera rs_camera.launch
... logging to /home/robotica/.ros/log/f05ae44c-8911-11ec-a457-6466b3258e07/roslaunch-robotica-jetson-1-15627.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://robotica-jetson-1:41971/

SUMMARY
========

PARAMETERS
 * /camera/realsense2_camera/accel_fps: -1
 * /camera/realsense2_camera/accel_frame_id: camera_accel_frame
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: False
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/allow_no_texture_points: False
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/calib_odom_file: 
 * /camera/realsense2_camera/clip_distance: -2.0
 * /camera/realsense2_camera/color_fps: -1
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: -1
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: -1
 * /camera/realsense2_camera/confidence_fps: -1
 * /camera/realsense2_camera/confidence_height: -1
 * /camera/realsense2_camera/confidence_width: -1
 * /camera/realsense2_camera/depth_fps: -1
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: -1
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: -1
 * /camera/realsense2_camera/device_type: 
 * /camera/realsense2_camera/enable_accel: False
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_confidence: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye1: False
 * /camera/realsense2_camera/enable_fisheye2: False
 * /camera/realsense2_camera/enable_fisheye: False
 * /camera/realsense2_camera/enable_gyro: False
 * /camera/realsense2_camera/enable_infra1: False
 * /camera/realsense2_camera/enable_infra2: False
 * /camera/realsense2_camera/enable_infra: False
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_pose: False
 * /camera/realsense2_camera/enable_sync: False
 * /camera/realsense2_camera/filters: 
 * /camera/realsense2_camera/fisheye1_frame_id: camera_fisheye1_f...
 * /camera/realsense2_camera/fisheye1_optical_frame_id: camera_fisheye1_o...
 * /camera/realsense2_camera/fisheye2_frame_id: camera_fisheye2_f...
 * /camera/realsense2_camera/fisheye2_optical_frame_id: camera_fisheye2_o...
 * /camera/realsense2_camera/fisheye_fps: -1
 * /camera/realsense2_camera/fisheye_frame_id: camera_fisheye_frame
 * /camera/realsense2_camera/fisheye_height: -1
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: -1
 * /camera/realsense2_camera/gyro_fps: -1
 * /camera/realsense2_camera/gyro_frame_id: camera_gyro_frame
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/imu_optical_frame_id: camera_imu_optica...
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra_fps: 30
 * /camera/realsense2_camera/infra_height: 480
 * /camera/realsense2_camera/infra_rgb: False
 * /camera/realsense2_camera/infra_width: 848
 * /camera/realsense2_camera/initial_reset: False
 * /camera/realsense2_camera/json_file_path: 
 * /camera/realsense2_camera/linear_accel_cov: 0.01
 * /camera/realsense2_camera/odom_frame_id: camera_odom_frame
 * /camera/realsense2_camera/ordered_pc: False
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/pose_frame_id: camera_pose_frame
 * /camera/realsense2_camera/pose_optical_frame_id: camera_pose_optic...
 * /camera/realsense2_camera/publish_odom_tf: True
 * /camera/realsense2_camera/publish_tf: True
 * /camera/realsense2_camera/reconnect_timeout: 6.0
 * /camera/realsense2_camera/rosbag_filename: 
 * /camera/realsense2_camera/serial_no: 
 * /camera/realsense2_camera/stereo_module/exposure/1: 7500
 * /camera/realsense2_camera/stereo_module/exposure/2: 1
 * /camera/realsense2_camera/stereo_module/gain/1: 16
 * /camera/realsense2_camera/stereo_module/gain/2: 16
 * /camera/realsense2_camera/tf_publish_rate: 0.0
 * /camera/realsense2_camera/topic_odom_in: odom_in
 * /camera/realsense2_camera/unite_imu_method: 
 * /camera/realsense2_camera/usb_port_id: 
 * /camera/realsense2_camera/wait_for_device_timeout: -1.0
 * /rosdistro: melodic
 * /rosversion: 1.14.12

NODES
  /camera/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)

auto-starting new master
process[master]: started with pid [15640]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to f05ae44c-8911-11ec-a457-6466b3258e07
process[rosout-1]: started with pid [15653]
started core service [/rosout]
process[camera/realsense2_camera_manager-2]: started with pid [15670]
process[camera/realsense2_camera-3]: started with pid [15671]
[ INFO] [1644347071.280782426]: Initializing nodelet with 4 worker threads.
[ INFO] [1644347071.592622560]: RealSense ROS v2.3.2
[ INFO] [1644347071.592714442]: Built with LibRealSense v2.50.0
[ INFO] [1644347071.592778717]: Running with LibRealSense v2.50.0
[ INFO] [1644347071.656555161]:  
 08/02 20:04:31,883 WARNING [547071455616] (messenger-libusb.cpp:42) control_transfer returned error, index: 300, error: Success, number: 0
 08/02 20:04:32,033 WARNING [547071455616] (messenger-libusb.cpp:42) control_transfer returned error, index: 300, error: Success, number: 0
 08/02 20:04:32,087 WARNING [547071455616] (messenger-libusb.cpp:42) control_transfer returned error, index: 300, error: Success, number: 0
 08/02 20:04:32,141 WARNING [547071455616] (messenger-libusb.cpp:42) control_transfer returned error, index: 300, error: Success, number: 0
[ INFO] [1644347072.272007216]: Device with serial number f1150256 was found.

[ INFO] [1644347072.272116911]: Device with physical ID 2-1.2-3 was found.
[ INFO] [1644347072.272199938]: Device with name Intel RealSense L515 was found.
[ INFO] [1644347072.273551548]: Device with port number 2-1.2 was found.
[ INFO] [1644347072.273642284]: Device USB type: 3.2
[ INFO] [1644347072.279223112]: getParameters...
[ INFO] [1644347072.546462549]: setupDevice...
[ INFO] [1644347072.546557400]: JSON file is not provided
[ INFO] [1644347072.546614539]: ROS Node Namespace: camera
[ INFO] [1644347072.546672148]: Device Name: Intel RealSense L515
[ INFO] [1644347072.546719964]: Device Serial No: f1150256
[ INFO] [1644347072.546776062]: Device physical port: 2-1.2-3
[ INFO] [1644347072.546821482]: Device FW version: 01.05.08.01
[ INFO] [1644347072.546866433]: Device Product ID: 0x0B64
[ INFO] [1644347072.546909509]: Enable PointCloud: Off
[ INFO] [1644347072.546952637]: Align Depth: Off
[ INFO] [1644347072.546997745]: Sync Mode: Off
[ INFO] [1644347072.547114524]: Device Sensors: 
[ INFO] [1644347072.637612288]: L500 Depth Sensor was found.
[ INFO] [1644347072.683273831]: RGB Camera was found.
[ INFO] [1644347072.683886897]: Motion Module was found.
[ INFO] [1644347072.683997374]: num_filters: 0
[ INFO] [1644347072.684063420]: Setting Dynamic reconfig parameters.
[ INFO] [1644347075.542863604]: Done Setting Dynamic reconfig parameters.
[ INFO] [1644347075.543942901]: depth stream is enabled - width: 640, height: 480, fps: 30, Format: Z16
[ INFO] [1644347075.546699403]: color stream is enabled - width: 1280, height: 720, fps: 30, Format: RGB8
[ INFO] [1644347075.546855039]: setupPublishers...
[ INFO] [1644347075.555228928]: Expected frequency for depth = 30.00000
[ INFO] [1644347075.666690457]: Expected frequency for color = 30.00000
[ INFO] [1644347075.760143751]: setupStreams...
 08/02 20:04:36,023 WARNING [547071455616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
[ INFO] [1644347076.060246190]: SELECTED BASE:Depth, 0
 08/02 20:04:36,073 WARNING [547071455616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 08/02 20:04:36,125 WARNING [547071455616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
[ INFO] [1644347076.180157141]: RealSense Node Is Up!
[ WARN] [1644347076.209516397]: 
[ WARN] [1644347076.209678804]: frame's time domain is HARDWARE_CLOCK. Timestamps may reset periodically.
 08/02 20:04:36,428 WARNING [547071455616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 08/02 20:04:36,579 WARNING [547071455616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 08/02 20:04:36,731 WARNING [547071455616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 08/02 20:04:37,076 WARNING [547071455616] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
```

**Comment by MartyG-RealSense** [comment]
Hi @grafoteka  If the message **messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11**  is generating continuously multiple times per second then it indicates a serious communication problem between the code and the device.

You could try adding **initial_reset:=true** to your roslaunch instruction if you have not done so already in order to reset the camera at launch to see whether it reduces the occurrence of the control_transfer returned messages.  For example:

**roslaunch realsense2_camera rs_camera.launch initial_reset:=true**

The L515 camera model only supports 30 FPS for depth and infrared.

If the camera data is able to be published correctly in the **RViz** interface without an apparent negative impact on performance despite continuously generating **control_transfer returned** warnings then the messages can be disregarded.

*****************

Also, may I ask whether you are using the official 1 meter USB cable that was supplied with the camera or a longer cable of your own choice, or a USB **C to C** cable instead of the USB A to C (full sized A, micro-sized C) that the official cable has. 

If you are using a long cable of your own choice (2 meters or more) then it is important that it is a high quality cable due to the high volume of data that a RealSense camera can transmit through the cable.

If it is a C to C type cable of your own choice then it is recommendable that it is one that can support 10Gbps of data transfer bandwidth.

**********

If your model of Jetson Nano has a **barrel jack** connector then Intel strongly recommends enabling it using the instructions in the link below to provide extra power.

https://www.jetsonhacks.com/2019/04/10/jetson-nano-use-more-power/

**********

Is there any difference if you unplug the micro-sized end of the USB cable from the base of the L515 camera, turn the connector around the other way and re-insert it into the camera base (USB-C cables are two-way insertion at the micro-sized end).

**Comment by grafoteka** [comment]
Hi @MartyG-RealSense , thank you for your detail answer. I will reply on your own.

> Hi @grafoteka If the message **messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11** is generating continuously multiple times per second then it indicates a serious communication problem between the code and the device.
> 
> You could try adding **initial_reset:=true** to your roslaunch instruction if you have not done so already in order to reset the camera at launch to see whether it reduces the occurrence of the control_transfer returned messages. For example:
> 
> **roslaunch realsense2_camera rs_camera.launch initial_reset:=true**

I have try to launch with this option, but still having the same error.
> 
> The L515 camera model only supports 30 FPS for depth and infrared.

Ok. Thank you for the info.

> If the camera data is able to be published correctly in the **RViz** interface without an apparent negative impact on performance despite continuously generating **control_transfer returned** warnings then the messages can be disregarded.
> 
> Also, may I ask whether you are using the official 1 meter USB cable that was supplied with the camera or a longer cable of your own choice, or a USB **C to C** cable instead of the USB A to C (full sized A, micro-sized C) that the official cable has.

I use the official cable.
 
> If your model of Jetson Nano has a **barrel jack** connector then Intel strongly recommends enabling it using the instructions in the link below to provide extra power.
> 
> https://www.jetsonhacks.com/2019/04/10/jetson-nano-use-more-power/
> 

I use a barrel jack and I have set in Ubuntu the power mode to the highest consumption, but I will check the jumper.

> Is there any difference if you unplug the micro-sized end of the USB cable from the base of the L515 camera, turn the connector around the other way and re-insert it into the camera base (USB-C cables are two-way insertion at the micro-sized end).

I will try this option, too.

**Comment by MartyG-RealSense** [comment]
Thanks very much @grafoteka - I look forward to hearing about the results of the jumper and cable connector reversal checks.

**Comment by grafoteka** [comment]
Hi @MartyG-RealSense, I have bad news.

- The jetson was correctly configure to use the barrel jack and the maximum power. I check the jumper and the command.
- Turning the cable didn't solve the problem.

Also, I have notice that with the realsense-viewer, the error is shown.

Finally, I try also installing the realsense2 udev rules, but still having the same error.

**Comment by MartyG-RealSense** [comment]
It sounds as though you installed librealsense and the RealSense ROS wrapper together from packages when you used **sudo apt install ros-melodic-realsense2-camera**

https://github.com/IntelRealSense/realsense-ros#method-1-the-ros-distribution

Can you confirm please that you did not install librealsense separately by another method before that.  If librealsense was installed separately first and then 'sudo apt install ros-melodic-realsense2-camera' was used, it would install librealsense a second time and may result in a conflict.

**Comment by grafoteka** [comment]
I have remove all the related installed to realsense (realsense-camera, realsense-description, librealsense). Then reboot the jetson nano. And after, reinstall with the method #1.

But when launching the realsense (`roslaunch realsense2_camera rs_camera.launch initial_reset:=true`) still having the same error:
`09/02 21:04:19,210 WARNING [546450690432] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11`

And there is also one warning message: `[ WARN] [1644437055.835520802]: 
[ WARN] [1644437055.835682423]: frame's time domain is HARDWARE_CLOCK. Timestamps may reset periodically.`

**Comment by MartyG-RealSense** [comment]
Is the camera data able to be viewed in the **RViz** interface despite the warnings?  RViz can be activated with the instruction **rosrun rviz rviz** after launch has completed with the message 'RealSense node is up'

**Comment by grafoteka** [comment]
Yes. I can visualize the realsense in Rviz, but the message still being published 

>

**Comment by MartyG-RealSense** [comment]
If you can visualize the camera data in RViz without degraded performance then the warnings can be safely ignored.

**Comment by grafoteka** [comment]
I can visualize only the depth cloud, not the point clouds 2. 
![image](https://user-images.githubusercontent.com/7115092/153289465-349e0b42-ce05-43b0-a229-ee63fcd9393c.png)

**Comment by MartyG-RealSense** [comment]
There is a known issue with enabling the pointcloud filter on Jetson boards specifically, such as missing color and FPS drops.  These problems typically do not occur when the pointcloud is not enabled.  There is extensive information about the issue at https://github.com/IntelRealSense/realsense-ros/issues/1967

A Nano user recently shared in that discussion a librealsense, ROS wrapper and firmware driver combination that worked for them at https://github.com/IntelRealSense/realsense-ros/issues/1967#issuecomment-1029789663

**Comment by grafoteka** [comment]
Hello @MartyG-RealSense, I have continue doing some tests, but I have detected one problem. The RealSense does not show any RGB picture. 

The topic `/camera/color/image_raw` is created, but no image is published, therefore it is not possible to use some packages like RTabMap. 

On the other hand, I have connected directly the RealSense to a desktop computer (intel x64) and it works correctly (even it shows the same error of this topic) the RGB image is shown. 

Do you know what can cause this problem in the RealSense?

Thank you

**Comment by MartyG-RealSense** [comment]
As mentioned above in https://github.com/IntelRealSense/realsense-ros/issues/2248#issuecomment-1034222668 - if you have the pointcloud filter enabled on Jetson then color may be missing and should return when the pointcloud filter is disabled.

**Comment by MartyG-RealSense** [comment]
Hi @grafoteka  Do you require further assistance with this case, please?  Thanks!

**Comment by grafoteka** [comment]
I'm stuck in how to create the GUI but the packages compiles correctly with your instructions.
