### ISSUE TITLE
Machine is frozen when I run and close wrapper many times.

### ISSUE THREAD

**Issue by kdhRGT** [realsenseai/realsense-ros#2249]
Hello!

Now I am using a D435 RGB-d camera for developing robot applications.

But I have a problem that sometimes, the machine is frozen when I restart the wrapper.

It looks ok when I just run the wrapper one or two times, but my machine is frozen if I run and close the wrapper pkg many times.

I am making a service robot, so sometimes it happens to close all of pkg.. 

And I wanna solve it for making a stable system.

Could you give me some advice for solving this problem?

I guess this problem happens because of a wrapper code problem or intel SDK 

I had experiments in Laptops and lattepanda(embedded board). But It happened same time.

I used the "rs_d435_camera_with_model.launch" using d435 camera sensor.

and here is how I install the intel SDK for d435 on below : 

```
echo 'deb http://realsense-hw-public.s3.amazonaws.com/Debian/apt-repo xenial main' | sudo tee /etc/apt/sources.list.d/realsense-public.list

sudo apt-key adv --keyserver keys.gnupg.net --recv-key 6F3EFCDE
sudo apt-key adv --keyserver hkp://keys.gnupg.net:80 --recv-key 6F3EFCDE


sudo apt-get update

sudo apt-get install librealsense2-dkms
sudo apt-get install librealsense2-utils
sudo apt-get install librealsense2-dev
sudo apt-get install librealsense2-dbg
```

realsense-viewer doesn't have a problem I guess...it looks ok

machine setting

ubuntu 18.04
ROS1 melodic

Thank you so much

Best regards.

**Comment by MartyG-RealSense** [comment]
Hi @kdhRGT  May I first ask which kernel version you are using, please?  

There was a recent case at https://github.com/IntelRealSense/librealsense/issues/10207 where a RealSense ROS user was experiencing OS freezes.  Their eventual solution that provided stability was to use kernel version **5.11.0-34-generic**

Support for kernel 5.11 was added to the librealsense SDK in version **2.50.0** by a patch provided by a RealSense user that was merged into librealsense.

**Comment by kdhRGT** [comment]
Thank you so much for your advice @MartyG-RealSense, that is what I was finding.

best regards

**Comment by MartyG-RealSense** [comment]
You are very welcome, @kdhRGT   :)
