### ISSUE TITLE
pointcloud for an rgb image

### ISSUE THREAD

**Issue by Chezhian531** [realsenseai/realsense-ros#2253]
I wish to generate pointcloud for an rgb image just like the example shown in https://github.com/IntelRealSense/realsense-ros using the comment 

roslaunch realsense2_camera rs_camera.launch filters:=pointcloud

Could you please suggest how can i achieve this?

I have ubuntu 18.04, intelrealsense D435i

**Comment by MartyG-RealSense** [comment]
Hi @Chezhian531  Once you have successfully launched RealSense ROS with that roslaunch instruction then you should be able to view the pointcloud by launching the RViz interface with the command **rosrun rviz rviz**

https://github.com/IntelRealSense/realsense-ros#point-cloud

![image](https://user-images.githubusercontent.com/41145062/153843647-16403796-7d41-41a7-83ae-638ddd074aa1.png)

**Comment by Chezhian531** [comment]
I dont get that output. I am attaching my rviz output her
![Screenshot from 2022-02-15 10-04-36](https://user-images.githubusercontent.com/99118186/154028810-7fb67779-9b49-4a0c-a775-fe3216309ed4.png)
e

**Comment by Chezhian531** [comment]
Also I want to generate such an output for the image I have, could you suggest some ways to do it?

**Comment by MartyG-RealSense** [comment]
Are you able to generate a point cloud if you use the **Add** button at the bottom of the RViz side-panel to add the topic **depth/color/points/PointCloud2**, as described at https://github.com/IntelRealSense/realsense-ros/issues/1605#issuecomment-754523910

**Comment by Chezhian531** [comment]
Yes I do, but is it possible to obtain point cloud for an image?

**Comment by MartyG-RealSense** [comment]
Do you mean converting a pre-made file into a pointcloud instead of using live camera data, please?  And if so, what kind of file would you be using (PNG image, bag file, ply pointcloud file, etc).

**Comment by Chezhian531** [comment]
yes exactly, a premade file. I want to get point cloud for a jpg image.

**Comment by MartyG-RealSense** [comment]
If you need to perform the image file to pointcloud conversion in ROS then I could not find much that offered this feature, though the ROS package in the link below may be a good place to start.

http://wiki.ros.org/pixel_2_3d

**Comment by MartyG-RealSense** [comment]
Hi @Chezhian531  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
