### ISSUE TITLE
I have a problem to subscribe depth image.

### ISSUE THREAD

**Issue by kdhRGT** [realsenseai/realsense-ros#2256]
Hello sir.

I am using a d435 rgb-d camera from realsense.

but I have a problem about subscribing "camera/aligned_depth_to_color/image_raw" this topic.

this is my code...

**Subscribe part.**

    message_filters::Subscriber<sensor_msgs::Image> * rgb_subscriber_ = new message_filters::Subscriber<sensor_msgs::Image> (n, "/camera/color/image_raw", 1);
    message_filters::Subscriber<sensor_msgs::Image> * depth_subscriber_ = new message_filters::Subscriber<sensor_msgs::Image> (n, "/camera/aligned_depth_to_color/image_raw", 1);

**call_back function**
```
void ImageCallback (const sensor_msgs::ImageConstPtr& msgRGB, const sensor_msgs::ImageConstPtr& msgD) {

  cv_bridge::CvImageConstPtr cv_ptrRGB;
  cv::Mat img;
  cv::Mat imDepth;

  try {
    cv_ptrRGB = cv_bridge::toCvShare(msgRGB);
    img = cv_ptrRGB->image;
    cv::imshow("RGB Image", cv_bridge::toCvShare(msgRGB, "bgr8")->image);
    cv::waitKey(30);

  } catch (cv_bridge::Exception& e) {
    ROS_ERROR("cv_bridge exception: %s", e.what());
    return;
  }

  cv_bridge::CvImageConstPtr cv_ptrD;

  try {

    cv_ptrD = cv_bridge::toCvShare(msgD);
    imDepth  = cv_bridge::toCvShare(msgD, "mono16")->image;//cv_ptrD->image;
    //cv::Mat depth_img = cv_bridge::toCvShare(msgD, "mono16")->image;

    //imDepth.convertTo(imDepth,CV_16UC1,1000);
    cv::imshow("Depth Image", imDepth);
    cv::waitKey(30);

  } catch (cv_bridge::Exception& e) {
      ROS_ERROR("cv_bridge exception: %s", e.what());
      return;
  }

}
```

I am successful to subscribe an RGB image... but now I am failed to convert to a depth image.

I think I am successful to subscribe depth images, but I don't know how I should convert them.

can you help me that how I should **convert sensor_msgs::ImageConstPtr** to **Mat** image?

thank you so much...

best regards

**Comment by MartyG-RealSense** [comment]
Hi @kdhRGT  The description of what you are attempting sounds similar to what a RealSense ROS user was doing in https://github.com/IntelRealSense/realsense-ros/issues/2106

**Comment by kdhRGT** [comment]
@MartyG-RealSense Thank you sir.

I found what i wanted it!

https://github.com/ros-perception/image_pipeline/blob/kinetic/depth_image_proc/src/nodelets/point_cloud_xyzrgb.cpp

thank you so much. this is same with me

**Comment by MartyG-RealSense** [comment]
You are very welcome, @kdhRGT - I'm pleased that I could help.  Thanks for the update!
