### ISSUE TITLE
Questions about subscribing to topics to collect and compare timestamps from MetaData.msg

### ISSUE THREAD

**Issue by joshuawillman** [realsenseai/realsense-ros#2258]
Hi,

I am currently working on a project that collects both color and depth data from a D435i and a L515. While the cameras are used for tasks in the project (such as localizing objects), both cameras use the launch parameter `align_depth:=True`. 

I am currently in the process of comparing timestamp information to ensure that RGB and Depth frames were taken at (roughly) the same moment in time. My first question is, after looking at the topics provided by realsense-ros, I don't see a metadata topic for `aligned_depth_to_color`. I only see metadata topics for `color` and `depth` which I subscribe to using the following lines:
```
rospy.Subscriber('/camera/color/metadata', Metadata, self._get_camera_rgb_meta_cb)
rospy.Subscriber('/camera/depth/metadata', Metadata, self._get_camera_depth_meta_cb) 
```
If no metadata topic is provided for `aligned_depth_to_color`, do the `depth` and `color` topics provide the correct information I need for comparing the color and depth frames? The answer may be obvious, but I just wanted verification. 

Simply printing out the metadata information provides me with the following msg data:
```
DEPTH METADATA header: 
  seq: 790
  stamp: 
    secs: 1645136438
    nsecs: 100392580
  frame_id: "camera_depth_optical_frame"
json_data: "{\"frame_number\":12862,\"clock_domain\":\"global_time\",\"frame_timestamp\":1645136438100.392578,\"\
  frame_counter\":12862,\"hw_timestamp\":454083433,\"sensor_timestamp\":454059884,\"\
  actual_exposure\":31979,\"gain_level\":24,\"auto_exposure\":1,\"time_of_arrival\"\
  :1645136438117,\"backend_timestamp\":0,\"actual_fps\":30,\"frame_laser_power\":150,\"\
  frame_laser_power_mode\":1,\"exposure_priority\":1,\"exposure_roi_left\":0,\"exposure_roi_right\"\
  :1279,\"exposure_roi_top\":0,\"exposure_roi_bottom\":719,\"frame_emitter_mode\"\
  :1,\"raw_frame_size\":1843200,\"gpio_input_data\":0,\"sequence_name\":0,\"sequence_id\"\
  :0,\"sequence_size\":0}"

COLOR METADATA header: 
  seq: 790
  stamp: 
    secs: 1645136438
    nsecs: 100729465
  frame_id: "camera_color_optical_frame"
json_data: "{\"frame_number\":12867,\"clock_domain\":\"global_time\",\"frame_timestamp\":1645136438100.729492,\"\
  frame_counter\":12867,\"hw_timestamp\":454083770,\"sensor_timestamp\":454083687,\"\
  auto_exposure\":1,\"time_of_arrival\":1645136438134,\"backend_timestamp\":0,\"actual_fps\"\
  :29,\"brightness\":0,\"contrast\":50,\"saturation\":64,\"sharpness\":50,\"auto_white_balance_temperature\"\
  :1,\"backlight_compensation\":0,\"hue\":0,\"gamma\":300,\"manual_white_balance\"\
  :4600,\"power_line_frequency\":3,\"low_light_compensation\":0,\"raw_frame_size\"\
  :1843200}"
```
Also, would it be better to use `seq` to compare frames since that refers to the sequence id, or should I also compare `secs` and `nsecs`?

Thanks for the help!

**Comment by MartyG-RealSense** [comment]
Hi @joshuawillman  Support for metadata publishing was added in ROS wrapper 2.3.2 and ROS2 wrapper 3.2.3.  **Doronhi** the RealSense ROS wrapper developer created a Python script for ROS called **echo_metadada.py** for printing the metadata information of a particular topic.

https://github.com/IntelRealSense/realsense-ros/blob/development/realsense2_camera/scripts/echo_metadada.py

As described by Doronhi in https://github.com/IntelRealSense/realsense-ros/issues/2231#issuecomment-1020066938 - the script can be launched from the ROS terminal by inputting an instruction such as this:

`python3 catkin_ws/src/realsense/realsense2_camera/scripts/echo_metadada.py /camera/infra1/metadata`
 
So if you wanted to try to access metadata for **/camera/aligned_depth_to_color/image_raw** and you are using align_depth:=True in your roslaunch instruction, is metadata for the aligned topic provided if you input the following command into the ROS terminal:

`python3 catkin_ws/src/realsense/realsense2_camera/scripts/echo_metadada.py /camera/aligned_depth_to_color/metadata`

**Comment by MartyG-RealSense** [comment]
Hi @joshuawillman  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
