### ISSUE TITLE
realsense d435i roslaunch realsense2_camera rs_camera.launch error

### ISSUE THREAD

**Issue by hyeonminseok** [realsenseai/realsense-ros#2264]
i have a relsense d435i camera. i want to work it Although realsense-viewer worked well but roslaunch realsense2_camera rs_camera.launch had error it is that..

seok@seok-ThinkPad-E15-Gen-3:~/catkin_ws/src$ roslaunch realsense2_camera rs_camera.launch
... logging to /home/seok/.ros/log/45e29308-97a2-11ec-b860-84a9386b66ed/roslaunch-seok-ThinkPad-E15-Gen-3-16646.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://seok-ThinkPad-E15-Gen-3:42815/

SUMMARY
========

PARAMETERS
 * /camera/realsense2_camera/accel_fps: -1
 * /camera/realsense2_camera/accel_frame_id: camera_accel_frame
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: False
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/allow_no_texture_points: False
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/calib_odom_file: 
 * /camera/realsense2_camera/clip_distance: -2.0
 * /camera/realsense2_camera/color_fps: -1
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: -1
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: -1
 * /camera/realsense2_camera/confidence_fps: -1
 * /camera/realsense2_camera/confidence_height: -1
 * /camera/realsense2_camera/confidence_width: -1
 * /camera/realsense2_camera/depth_fps: -1
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: -1
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: -1
 * /camera/realsense2_camera/device_type: 
 * /camera/realsense2_camera/enable_accel: False
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_confidence: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye1: False
 * /camera/realsense2_camera/enable_fisheye2: False
 * /camera/realsense2_camera/enable_fisheye: False
 * /camera/realsense2_camera/enable_gyro: False
 * /camera/realsense2_camera/enable_infra1: False
 * /camera/realsense2_camera/enable_infra2: False
 * /camera/realsense2_camera/enable_infra: False
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_pose: False
 * /camera/realsense2_camera/enable_sync: False
 * /camera/realsense2_camera/filters: 
 * /camera/realsense2_camera/fisheye1_frame_id: camera_fisheye1_f...
 * /camera/realsense2_camera/fisheye1_optical_frame_id: camera_fisheye1_o...
 * /camera/realsense2_camera/fisheye2_frame_id: camera_fisheye2_f...
 * /camera/realsense2_camera/fisheye2_optical_frame_id: camera_fisheye2_o...
 * /camera/realsense2_camera/fisheye_fps: -1
 * /camera/realsense2_camera/fisheye_frame_id: camera_fisheye_frame
 * /camera/realsense2_camera/fisheye_height: -1
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: -1
 * /camera/realsense2_camera/gyro_fps: -1
 * /camera/realsense2_camera/gyro_frame_id: camera_gyro_frame
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/imu_optical_frame_id: camera_imu_optica...
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra_fps: 30
 * /camera/realsense2_camera/infra_height: 480
 * /camera/realsense2_camera/infra_rgb: False
 * /camera/realsense2_camera/infra_width: 848
 * /camera/realsense2_camera/initial_reset: False
 * /camera/realsense2_camera/json_file_path: 
 * /camera/realsense2_camera/linear_accel_cov: 0.01
 * /camera/realsense2_camera/odom_frame_id: camera_odom_frame
 * /camera/realsense2_camera/ordered_pc: False
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/pose_frame_id: camera_pose_frame
 * /camera/realsense2_camera/pose_optical_frame_id: camera_pose_optic...
 * /camera/realsense2_camera/publish_odom_tf: True
 * /camera/realsense2_camera/publish_tf: True
 * /camera/realsense2_camera/reconnect_timeout: 6.0
 * /camera/realsense2_camera/rosbag_filename: 
 * /camera/realsense2_camera/serial_no: 
 * /camera/realsense2_camera/stereo_module/exposure/1: 7500
 * /camera/realsense2_camera/stereo_module/exposure/2: 1
 * /camera/realsense2_camera/stereo_module/gain/1: 16
 * /camera/realsense2_camera/stereo_module/gain/2: 16
 * /camera/realsense2_camera/tf_publish_rate: 0.0
 * /camera/realsense2_camera/topic_odom_in: odom_in
 * /camera/realsense2_camera/unite_imu_method: 
 * /camera/realsense2_camera/usb_port_id: 
 * /camera/realsense2_camera/wait_for_device_timeout: -1.0
 * /rosdistro: melodic
 * /rosversion: 1.14.12

NODES
  /camera/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)

auto-starting new master
process[master]: started with pid [16656]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 45e29308-97a2-11ec-b860-84a9386b66ed
process[rosout-1]: started with pid [16667]
started core service [/rosout]
process[camera/realsense2_camera_manager-2]: started with pid [16674]
process[camera/realsense2_camera-3]: started with pid [16675]
[ INFO] [1645948376.462821748]: Initializing nodelet with 12 worker threads.
[ INFO] [1645948376.566433697]: RealSense ROS v2.3.2
[ INFO] [1645948376.566504964]: Built with LibRealSense v2.50.0
[ INFO] [1645948376.566534831]: Running with LibRealSense v2.50.0
[ INFO] [1645948376.611264895]:  
[ INFO] [1645948376.893085934]: Device with serial number 102122071719 was found.

[ INFO] [1645948376.893185829]: Device with physical ID 2-2-3 was found.
[ INFO] [1645948376.893215380]: Device with name Intel RealSense D435I was found.
[ INFO] [1645948376.894766881]: Device with port number 2-2 was found.
[ INFO] [1645948376.894962940]: Device USB type: 3.2
[ INFO] [1645948376.899871119]: getParameters...
[ INFO] [1645948376.983830157]: setupDevice...
[ INFO] [1645948376.983896730]: JSON file is not provided
[ INFO] [1645948376.983921383]: ROS Node Namespace: camera
[ INFO] [1645948376.983949573]: Device Name: Intel RealSense D435I
[ INFO] [1645948376.983971910]: Device Serial No: 102122071719
[ INFO] [1645948376.983990740]: Device physical port: 2-2-3
[ INFO] [1645948376.984015658]: Device FW version: 05.13.00.50
[ INFO] [1645948376.984038655]: Device Product ID: 0x0B3A
[ INFO] [1645948376.984075503]: Enable PointCloud: Off
[ INFO] [1645948376.984097128]: Align Depth: Off
[ INFO] [1645948376.984119495]: Sync Mode: Off
[ INFO] [1645948376.984186240]: Device Sensors: 
[ INFO] [1645948377.076515876]: Stereo Module was found.
[ INFO] [1645948377.091406311]: RGB Camera was found.
[ INFO] [1645948377.091620067]: Motion Module was found.
[ INFO] [1645948377.091700755]: (Confidence, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1645948377.091752192]: num_filters: 0
[ INFO] [1645948377.091769919]: Setting Dynamic reconfig parameters.
[ INFO] [1645948380.181096910]: Done Setting Dynamic reconfig parameters.
[ INFO] [1645948380.182297166]: depth stream is enabled - width: 848, height: 480, fps: 30, Format: Z16
[ INFO] [1645948380.184352599]: color stream is enabled - width: 1280, height: 720, fps: 30, Format: RGB8
[ INFO] [1645948380.184483395]: setupPublishers...
[ INFO] [1645948380.187876196]: Expected frequency for depth = 30.00000
[ INFO] [1645948380.222650971]: Expected frequency for color = 30.00000
[ INFO] [1645948380.243257179]: setupStreams...
 27/02 16:53:00,435 WARNING [140571228698368] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
[ INFO] [1645948380.486490117]: SELECTED BASE:Depth, 0
[ INFO] [1645948380.508800009]: RealSense Node Is Up!
[ WARN] [1645948380.555121079]: 
 27/02 16:53:00,556 WARNING [140571228698368] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 27/02 16:53:00,606 WARNING [140571228698368] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 27/02 16:53:00,658 WARNING [140571228698368] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 27/02 16:53:01,011 WARNING [140571228698368] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 27/02 16:53:01,164 WARNING [140571228698368] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 27/02 16:53:01,214 WARNING [140571228698368] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 27/02 16:53:01,366 WARNING [140571228698368] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 27/02 16:53:01,417 WARNING [140571228698368] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 27/02 16:53:01,569 WARNING [140571228698368] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0

help me please i don't know what i should do

**Comment by MartyG-RealSense** [comment]
Hi @hyeonminseok   The **control_transfer returned** warnings in the log can be safely ignored if they are only appearing at the start of launch or appearing about once a minute instead of generating continuously.  If these warnings are generated continuously though then this may indicate a serious communication problem with the device.

Sometimes the topics may still be able to be correctly published in the **RViz** interface even if these messages appear.  If the camera data is being displayed correctly in RViz with no sign of degraded performance then again the warnings can be ignored.

Could you test please whether adding **initial_reset:=true** to your roslaunchh instruction to reset the camera at launch makes a positive difference, please?  For example:

**roslaunch realsense2_camera rs_camera.launch initial_reset:=true**

**Comment by hyeonminseok** [comment]
thank to your rapid reply
this is resolved

**Comment by MartyG-RealSense** [comment]
You are very welcome, @hyeonminseok - I'm pleased to hear that the problem was resolved.  I will therefore close this case.  Thanks very much!

**Comment by jrlearncode05** [comment]
Hello, I am also having this problem. I tried the "roslaunch realsense2_camera rs_camera.launch initial_reset:=true" command and it still results i the error "RLException: [rs_camera.launch] is neither a launch file in package [realsense2_camera] nor is [realsense2_camera] a launch file name
The traceback for the exception was written to the log file". May you tell me how to resolve this issue please?

**Comment by MartyG-RealSense** [comment]
Hi @jrlearncode05  Have you installed the RealSense SDK (librealsense2) and then the RealSense ROS1 wrapper, please?

The link below has a previous example of this error.

https://answers.ros.org/question/304600/realsense-ros-wont-start-with-roslaunch-realsense2_camera-rs_cameralaunch/

**Comment by rutledgejaniah** [comment]
Hi, yes I have installed both the librealsense2 and the RealSense ROS1 wrapper. I am also having trouble with "pyrealsense2" I tried pip installing it and building it from source.

**Comment by MartyG-RealSense** [comment]
@rutledgejaniah  Which method did you use to install librealsense2 and the RealSense ROS wrapper?

For example, if you installed librealsense2 first and then installed the wrapper with 'Method 1' ( the `sudo apt-get install ros-$ROS_DISTRO-realsense2-camera` command) then this command would install both librealsense2 and the wrapper at the same time.  If librealsense2 had already been installed then you could end up with two conflicting installations of librealsense2 on the same computer.
