### ISSUE TITLE
Jetson nano wrong measures

### ISSUE THREAD

**Issue by sergioar3143** [realsenseai/realsense-ros#2265]
Hello I am using Jetson nano and I am trying to segment the color of a ball, because I want to estimate the trajectory. The problem is that I have wrong measures. I have calibrated the camera many times and I still having the same problem. What can I do?

**Comment by MartyG-RealSense** [comment]
Hi @sergioar3143   The RealSense-compatible ball color segmentation and position detection project for ROS at the link below may be a helpful reference.

https://github.com/ctu-mrs/object_detect

If you used the **On-Chip** calibration tool then that will calibrate depth.  The RealSense SDK's **Dynamic Calibration** tool can perform a robust calibration of both depth and RGB.  If you have not already tried this tool, it can be installed on Linux by following the instructions on page 14 onwards of the tool's user guide.

https://www.intel.com/content/www/us/en/support/articles/000026723/emerging-technologies/intel-realsense-technology.html

**Comment by sergioar3143** [comment]
Thank you so much. I have one more question.
I calibrated the camera on windows  with the Dynamic calibrator at 0 grades like the first image, but I used the camera at 30 grades on the jetson nano like the second one, this could be a problem with the measures, couldn't it?

![0 grados](https://user-images.githubusercontent.com/21043709/156468589-cb8bc3c2-3899-4721-a674-5d0618d06383.jpg)
![30 grados](https://user-images.githubusercontent.com/21043709/156467817-7200da28-940c-4e67-bfc9-9694357b9ba2.jpg)

**Comment by MartyG-RealSense** [comment]
You should be fine.  30 degrees is the maximum that I would recommend tilting the camera.  You can go beyond 30 degrees but would risk introducing problems into the image.

**Comment by sergioar3143** [comment]
Okay, thank you so much.

**Comment by MartyG-RealSense** [comment]
Hi @sergioar3143  Do you require further assistance with this case, please?  Thanks!

**Comment by sergioar3143** [comment]
No, thank you

**Comment by MartyG-RealSense** [comment]
Thanks very much @sergioar3143 for the update!
