### ISSUE TITLE
Regarding camera_link frame orientation

### ISSUE THREAD

**Issue by Kaijun101** [realsenseai/realsense-ros#2266]
Hi @MartyG-RealSense,

Can I check with you whats is the coordinate frame (ENU, FRD, etc) for the camera_link?

**Comment by MartyG-RealSense** [comment]
Hi @Kaijun101  Doronhi the developer of the ROS wrapper once advised, "the **camera_link** frame was supposed to be some center point for all the other frames to relate to.  In the D400 series it is defined as the depth frame".  

You can define the world frame in the launch file, as described at https://github.com/IntelRealSense/realsense-ros/issues/1137#issue-585487777

![image](https://user-images.githubusercontent.com/41145062/156343761-31b9e81a-7f69-408f-a35d-5b9f87433218.png)

**Comment by MartyG-RealSense** [comment]
Hi @Kaijun101  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
