### ISSUE TITLE
Problems after installing Realsense SDK on ubuntu18.04(The realsense D455 camera is connected to the NX)

### ISSUE THREAD

**Issue by linchen2020** [realsenseai/realsense-ros#2267]
Hi everyone, after I installed Realsense SDK on ubuntu18.04, I had the problem shown in Fig.How to solve it next?

(
The error prompt message is:

 [Warn] /tmp/binarydeb/ros-melodic-librealsense2-2.50.0/src/libusb/messenger-libusb.cpp:42 - control_transfer returned error, index: 300, error: Success, number: 0

[Warn] /tmp/binarydeb/ros-melodic-librealsense2-2.50.0/src/libusb/messenger-libusb.cpp:42 - control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 [Error] /home/nvidia/toollib/librealsense-master/common/notifications.cpp:511 - Motion Module failure

)

(Remarks:

System:Ubuntu 18.04.5 LTS

Ros: melodic

Hardware platform uses NVIDIA Jetson NX with the specific configuration shown in Fig:

Camera: Realsense D455
)

![1](https://user-images.githubusercontent.com/62878348/156291456-3834d1dc-40cf-4f19-89d7-56c650b14d73.jpg)

**Comment by MartyG-RealSense** [comment]
Hi @linchen2020  There is a known issue with the RealSense Viewer where enabling all three stream categories (Depth, RGB and Motion Module) at the same time can cause frames to not be received.  There is no solution for this in the Viewer except to not enable all three stream types simultaneously.

The trigger for that particular problem is always the Motion Module, so it does not matter which order the stream types are enabled in as the problem may occur as soon as the Motion Module is enabled.  

Do you still experience this issue in the Viewer if you only enable Depth and RGB please?

It is possible to stream all three types (Depth RGB, IMU) simultaneously in the **rs-capture** SDK example program as it does not experience this problem.  

![image](https://user-images.githubusercontent.com/41145062/156347283-b117b2b4-6a19-4d2b-8cc8-143e24d27564.png)

It can also be worked around when creating your own program script by either using **callbacks** or by putting the streams on two separate pipelines (the IMU on one pipeline and depth + RGB on the other pipeline).

********

If you are using the RealSense ROS wrapper then you could try resetting the camera at launch by including **initial_reset:=true** in your roslaunch instruction if you are not doing so already.  For example:

**roslaunch realsense2_camera rs_camera.launch initial_reset:=true**

**Comment by linchen2020** [comment]
Hi, @[MartyG-RealSense](https://github.com/MartyG-RealSense), thank you very much for your answer. I have two questions to ask you at present.

1. Since I also need to use realsense ROS wapper, according to your reply, I input the instruction on this machine: roslaunch realsense 2_ camera rs_ camera. launch initial_ Reset: = true, but there is a problem, as shown in Figure 1. How to solve this problem?

2. When I built the environment of the first machine before, I also asked you some questions(Problems about VINS-FUSION configuration with Realsense D455 under NVIDIA NX (Issue #2217)). At that time, all the problems were solved after your guidance. But now, when I build the environment of the second machine (Jetson Xavier NX) in the same way, this unprecedented problem appears(one is that the realsense SDK is not running normally, and then the realsense is not running normally in ROS.). Did I ignore a certain key point? Please give me some advice. (these two machines have the same hardware structure, the same Ubuntu system and the same construction process. They are connected to the same camera realsense d455)

![0303-fg1](https://user-images.githubusercontent.com/62878348/156483427-ef349a44-cfa9-4f7f-9b09-e76430875552.jpg)

**Comment by MartyG-RealSense** [comment]
1.  Your image of the RealSense Viewer shows that it is reporting a **multiple udev rules** warning.  This can occur if the SDK has been built from both packages and source code on the same computer.

![image](https://user-images.githubusercontent.com/41145062/156586328-37ce550b-3558-4140-aac6-3c68129570bd.png)

The udev rules are responsible for device handling in Ubuntu.  This warning can easily be resolved by deleting the rule located at **/etc/udev/rules.d/99-realsense-libusb.rules** 

The other rule is located at **/lib/udev/rules.d/60-librealsense2-udev-rules.rules** and this one should not be deleted, otherwise it can break linkages to Debian packages.  A RealSense team member discusses this subject at https://github.com/IntelRealSense/librealsense/issues/6153#issuecomment-605687547

2.  Please remove the /etc udev rule and check whether you are still experiencing the problems described.

**Comment by MartyG-RealSense** [comment]
Hi @linchen2020  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
