### ISSUE TITLE
RGB and depth images off by 1 timestamp when generating pointcloud

### ISSUE THREAD

**Issue by helenol** [realsenseai/realsense-ros#228]
### System Configuration
| Version               | Your Configuration   |
|:--------------------- |:---------------------|
| Operating System      | OS X 10.11.2, but verified on Ubuntu 14.04 as well    |
| Kernel                | ?-?-?                |
| ROS                   | indigo                    |
| ROS RealSense         | 1.8.0                |
| librealsense          |    1.12.1             |
| Camera Type-Firmware  | zr300  |

---

### Expected Behavior
Color and depth are registered correctly to each other, even when moving the sensor.

### Actual Behavior
The color is always 1 frame behind the depth. This is because the pointcloud is only generated on receiving the depth image, which assumes that the color image always comes *before* the depth image. On our Z300, this is actually always the opposite: the color frame always comes directly *after* the depth frame, which means the frame sequence numbers (almost) never match when the pointcloud is generated, and the color is not registered properly to the depth, especially when moving the sensor or when objects are moving in the image.

### Suggested Fix
I've fixed this in our fork of the driver, please see this for a comparison:
https://github.com/intel-ros/realsense/compare/imu-data-cache...ethz-asl:feature/pointcloud_rgb_sync?expand=1

The general steps are:
* Track sequence number of all streams with `sequence_ids_[STREAM_COUNT]`
* Call `publishPCTopic()` from both color and depth frame callbacks
* Mutex lock both color and depth streams in `publishPCTopic()`
* Return from `publishPCTopic()` if the sequence numbers of the color and depth streams don't match (also controlled by new `ENFORCE_RGBD_SYNC` flag/param)

The only outstanding issue with this fix is if the color and depth stream frame rates don't match -- then the sequence IDs of the faster should be then divided by the difference in rates.

If this seems like a good solution, I can also isolate the changes (cut away the OS X compile fix, etc.) and make a PR.

**Comment by jlgarcia75** [comment]
Hello @helenol,

Thank you for working on this. Unfortunately, the ZR300 camera and its associated software are discontinued and no longer supported. Therefore, we are not accepting any more PRs.

All development has moved to the RealSense D400 series cameras on https://github.com/IntelRealSense/librealsense.

Best Regards,
Jesus
Intel Customer Support
