### ISSUE TITLE
ROS 2 Foxy/Galactic and topic_odom_in parameter

### ISSUE THREAD

**Issue by edgarcamilocamacho** [realsenseai/realsense-ros#2285]
* OS: Ubuntu 20.04
* ROS Distro: Foxy/Galactic
* Camera: T265
* librealsense version: 2.60.0
* rosrealsense version: 4.0.2

I'm trying to feed my T265 camera with the wheel odometry, but I don't find the `topic_odom_in` parameter when I launch the node (in rqt_reconfig or with `ros2 param list`).

Even if I add the parameter in the launchfile, the node doesn't subscribe to the wheels odom topic.

The functionality worked perfectly in ROS1.

**Comment by BCaran** [comment]
Have you solved this problem? I am having same issue
