### ISSUE TITLE
D435 optical frame orientation

### ISSUE THREAD

**Issue by antoineTK** [realsenseai/realsense-ros#2286]
Hi guys

I have noticed there are slight angular values in tranforms between camera_link and optical_frame, is this correct? (got a D435_camera_FWD prefix in screenshot below)

![Screenshot from 2022-03-15 18-25-53](https://user-images.githubusercontent.com/47737047/158436405-043d792f-e72e-42a0-9a9b-2b734d5ffd2f.png)

All other frames seem to be aligned or have 90° rotations on some axis. Only optical frame has those "weird" angles.

Would anyone know if that's how it's supposed to be?

**Comment by MartyG-RealSense** [comment]
Hi @antoineTK  My research of your question had findings that reflected your own, with rotations commonly being '0' or whole numbers such as 90 / 180, whilst a tf_echo comparison of camera_link and camera_color_frame on a D435i camera in https://github.com/IntelRealSense/realsense-ros/issues/2097 demonstrated similar values to yours.

**Comment by antoineTK** [comment]
got it, I guess it's normal then, had to check

thanks a lot @MartyG-RealSense !

**Comment by MartyG-RealSense** [comment]
Hi @antoineTK  Do you require further assistance with this case, please?  Thanks!

**Comment by antoineTK** [comment]
all good, thanks @MartyG-RealSense

**Comment by MartyG-RealSense** [comment]
Great, thanks very much @antoineTK for the update!  As you do not require further assistance, I will close this case.  Thanks again!
