### ISSUE TITLE
pointcloud not published in ROS2 Foxy

### ISSUE THREAD

**Issue by Yoshihito-M** [realsenseai/realsense-ros#2295]
- Infos
LibRealSense v2.50.0
ROS2 Foxy
ROS2 Foxy Wrapper build 4.0.4
Ubuntu 20.04　LTS
D455

- Ploblem
After launching
`ros2 launch realsense2_camera rs_launch.py filters:=pointcloud align_depth:=true`,

using ros2 topic list gives me the topics as follows:
`/camera/aligned_depth_to_color/camera_info
/camera/aligned_depth_to_color/image_raw
/camera/color/camera_info
/camera/color/image_raw
/camera/depth/camera_info
/camera/depth/image_rect_raw
/camera/depth/metadata
/camera/extrinsics/depth_to_color
/camera/imu
/parameter_events
/rosout
/tf_static`.

As shown above, the topics /camera/depth/color/points is not listed. 
In addition, when launching the launch file, the concerned WARN message is shown as follows:
`[WARN] could not set param: pointcloud.stream_index_filter with -1 Range: [-1, -2147483648]: 
parameter 'pointcloud.stream_index filter' could not be set: Parameter {} doesn't comply with integer range`.

I guess that that WARN message affects failure of the topics /camera/depth/color/points.
I would like to know how to fix 'pointcloud.stream_index filter'.

**Comment by MartyG-RealSense** [comment]
Hi @Yoshihito-M  Do you receive the same warnings in ROS2 wrapper 4.0.4 when enabling the pointcloud using the launch instruction below?

**ros2 launch realsense2_camera rs_launch.py align_depth:=true pointcloud.enable:=true**

**Comment by Yoshihito-M** [comment]
Hi @MartyG-RealSense 

Thank you for helpful advice.
/camera/depth/color/points could be listed by using the launch instruction .
However, another error message is shown as follows when displaying /camera/depth/color/points in Rviz2:
`No stream match for pointcloud chosen texture process - Color`.

**Comment by MartyG-RealSense** [comment]
The warning **No stream match for pointcloud chosen texture process - Color** can appear every time that there is an unavailable texture, likely because of a frame drop.  The point cloud will not be published in the frame that the message occurs.  Is the point cloud able to be generated in RViz2 even though the warning is appearing, please?

**Comment by Yoshihito-M** [comment]
@MartyG-RealSense 
The issue I mentioned above has been cleared up.
The important point to display /camera/depth/color/points in Rviz2 is plugging in PC into the power outlet while using Rviz2.
I guess that Rviz2 should not be used on battery-powered mode of PC.

As a result, I could solve my issue by your advices.
Thanks!!

**Comment by MartyG-RealSense** [comment]
I'm pleased to hear that you achieved a solution, @Yoshihito-M - thanks very much for the update!

**Comment by JMadhup** [comment]
hi @Yoshihito-M and @MartyG-RealSense,

I am using the D445 camera on the humble version of ROS2. The problem I am facing is that when I do a ros2 topic list, the /camera/depth/color/points topic is present but it seems no data is being published over it. I tried ros2 topic echo and also tried to visualize it in rviz2 but couldn't visualize the data or echo it in the terminal.

**Comment by MartyG-RealSense** [comment]
Hi @JMadhup  Are you including **pointcloud.enable:=true** in your launch instruction, please?

`ros2 launch realsense2_camera rs_launch.py pointcloud.enable:=true`

**Comment by JMadhup** [comment]
@MartyG-RealSense yes that is exactly the same command I am using. 
I have also tried using ros2 launch realsense2_camera rs_launch.py align_depth:=true pointcloud.enable:=true but the issue persists.

**Comment by MartyG-RealSense** [comment]
Which RealSense ROS wrapper and librealsense SDK versions are you using?

**Comment by JMadhup** [comment]
@MartyG-RealSense I am not sure how to check which version I am using. Could you assist me with how to check the version?

**Comment by JMadhup** [comment]
@MartyG-RealSense I am using librealsense version 2.51.1 and realsense ROS version 4.51.1

**Comment by MartyG-RealSense** [comment]
In the ROS2 wrapper, the align parameter is `align_depth.enable ` rather than align_depth.

I note that the `/camera/depth/color/points `topic is published in the list of topics but there are no messages.  This at least indicates that the topic is being created by pointcloud.enable. 

Are there still no messages if the launch is defined with a low depth and color resolution and FPS?

`ros2 launch realsense2_camera rs_launch.py depth_module.profile:=640x480x15 rgb_camera.profile:=640x480x15 pointcloud.enable:=true`

**Comment by JMadhup** [comment]
@MartyG-RealSense No. Launching with low FPS does not help

**Comment by MartyG-RealSense** [comment]
Which messages, if any, are published in the ROS launch log after **RealSense Node is Up** (the point in the log where launch is completed and the sesssion is now running).

**Comment by JMadhup** [comment]
@MartyG-RealSense 
[realsense2_camera_node-1] [WARN] [1688555081.354793351] [camera.camera]:
 is the only message after that

**Comment by MartyG-RealSense** [comment]
What method did you use to install librealsense and the ROS wrapper?  Did you install librealsense first and test that it worked successfully, and then install the wrapper secondly after that from source code with **colcon build**

**Comment by JMadhup** [comment]
@MartyG-RealSense 
I first built librealsense from source and tested that it worked successfully and then installed the ROS wrapper using apt

**Comment by MartyG-RealSense** [comment]
Let's check if the align function is able to publish aligned topics and messages are being generated.  If align also does not publish messages then it could suggest a problem with the ROS wrapper or the particular computer that the wrapper is being run on. 

`ros2 launch realsense2_camera rs_launch.py align_depth.enable:=true`

**Comment by JMadhup** [comment]
Hello @MartyG-RealSense,

Sorry for the late response, I got otherwise engaged.

I tried using the command that you specified and the align function **does** infact publish the aligned topic and messages are also being generated. I was able to visualize the image_raw message using the image_view package but the image was same as it is on the /camera/depth/image_rect_raw topic

**Comment by MartyG-RealSense** [comment]
What do the aligned topics look like in **RViz** instead of image_view?

**Comment by JMadhup** [comment]
@MartyG-RealSense 

The aligned topic has now also stopped generating any messages. I tried both with RViz and image_view

**Comment by MartyG-RealSense** [comment]
@JMadhup  Which computer you are using.  Is it a PC such as a laptop or desktop, or a computing board such as Raspberry Pi or Nvidia Jetson?

**Comment by JMadhup** [comment]
@MartyG-RealSense 
I am using a Raspberry Pi 4 running an installation of ubuntu desktop 22.04

**Comment by MartyG-RealSense** [comment]
Is the pointcloud published if you leave out the `align_depth` parameter from the launch, as the pointcloud should be generated even if align_depth is not set to True.

` ros2 launch realsense2_camera rs_launch.py pointcloud.enable:=true `

**Comment by ashBabu** [comment]
Raspbery Pi 4 (8 GB), Ubuntu 22.04, ROS2 humble, d435i

Launching realsense camera with the launch_arguments `"pointcloud.enable": "True"` on raspberry pi 4 will not publish pointclouds. This argument in fact slows down the publishing rate of depth images from the specified rate of 30 to around 8 Hz. However if the `pointcloud.enable` argument is removed, then the rate of publishing of depth images is at the specified 30 Hz itself and by using either the `plugin='rtabmap_util::PointCloudXYZ'` or [depth_image_proc](http://wiki.ros.org/depth_image_proc), the pointclouds could be published at around the same 30 Hz rate. I installed everything using apt. `sudo apt-get install ros-humble-realsense2*`. More details on how to launch  (for anyone interested) is available at [my blog](https://ashbabu.github.io/blog/2023/Obstacle-Detection-from-Pointclouds/)

**Comment by MartyG-RealSense** [comment]
Thanks so much @ashBabu for sharing your Pi pointcloud method with the RealSense community!

**Comment by anishk85** [comment]
Hi @MartyG-RealSense,
I’m using an Intel RealSense D415 on ROS 2 Humble running on a Jetson Nano. I launched rs_launch.py with the argument enable_pointcloud:=true, but I still don’t see the point cloud topic being published.

Could you please help me understand why this might be happening and what I should check to get the topic published correctly?
