### ISSUE TITLE
Does D455 has a magnetometer in IMU?

### ISSUE THREAD

**Issue by abylikhsanov** [realsenseai/realsense-ros#2300]
I am trying to perform a sensor fusion and I wonder if D455 has a magnetometer so reduce the drift?

**Comment by MartyG-RealSense** [comment]
Hi @abylikhsanov  The IMU component in RealSense camera models that are equipped with an IMU does not have a magnetometer.  It has a gyro and accelerometer.  It also does not have an internal calibration mechanism.  The IMU can instead be calibrated with a Python software tool and the calibration saved to storage in the camera hardware.

https://dev.intelrealsense.com/docs/imu-calibration-tool-for-intel-realsense-depth-camera
