### ISSUE TITLE
What is the difference between `filters=pointcloud` and `enable_pointcloud=true`?

### ISSUE THREAD

**Issue by jyang-cpr** [realsenseai/realsense-ros#2306]
I am wondering what the difference is between setting `filters=pointcloud` and `enable_pointcloud=true` in the camera launch files? It seems that setting either parameter will publish a pointcloud stream to the `/camera/depth/color/points`.  I have not tried setting both at the same time, but would that be redundant?

**Comment by MartyG-RealSense** [comment]
Hi @jyang-cpr  My understanding is that the command was originally **enable_pointcloud:=true** some years ago and then that command was deprecated and **filters=pointcloud** became the recommended instruction for enabling a pointcloud, though both commands produce the same result.  So using **filters=pointcloud** is recommended as the other term is deprecated.

**Comment by jyang-cpr** [comment]
That makes sense. Thanks.
