### ISSUE TITLE
How to convert 2D coordinates to 3D coordinates ?

### ISSUE THREAD

**Issue by BnHassan1998** [realsenseai/realsense-ros#2311]
I am using yolov3 with darknet to train and test my project.   how I can  convert 2D coordinates to 3D coordinates  to know the Z
 (depth )  . because I have to do localization for the objects

**Comment by MartyG-RealSense** [comment]
Hi @BnHassan1998  As you are using darknet, the **darknet_ros_3d** package that can calculate a 3D bounding box with a 3D position for each detected object may be an appropriate solution.

https://github.com/IntelligentRoboticsLabs/gb_visual_detection_3d

https://github.com/IntelligentRoboticsLabs/gb_visual_detection_3d/issues/15 discusses using a RealSense D435 camera with darknet_ros_3d, with the comment https://github.com/IntelligentRoboticsLabs/gb_visual_detection_3d/issues/15#issuecomment-620276472 in that discussion being particularly useful.

**Comment by BnHassan1998** [comment]
I have changed to Yolo v4. but is it ok if I use the normal images for my dataset, I am using only a software project so I don't have images taken by realsense camera so is it possible to do the conversion? to get the Z (depth) to do the localization

**Comment by BnHassan1998** [comment]
> Hi @BnHassan1998 As you are using darknet, the **darknet_ros_3d** package that can calculate a 3D bounding box with a 3D position for each detected object may be an appropriate solution.
> 
> https://github.com/IntelligentRoboticsLabs/gb_visual_detection_3d
> 
> [IntelligentRoboticsLabs/gb_visual_detection_3d#15](https://github.com/IntelligentRoboticsLabs/gb_visual_detection_3d/issues/15) discusses using a RealSense D435 camera with darknet_ros_3d, with the comment [IntelligentRoboticsLabs/gb_visual_detection_3d#15 (comment)](https://github.com/IntelligentRoboticsLabs/gb_visual_detection_3d/issues/15#issuecomment-620276472) in that discussion being particularly useful.

conversion

**Comment by MartyG-RealSense** [comment]
It sounds as though the task that you are trying to achieve with yolov4 and darknet (and ordinary RGB image files?) is similar to the one that somebody was asking in the link below about how to do (but had not yet achieved).

https://stackoverflow.com/questions/67640416/how-to-calculate-length-breadth-2d-dimensions-of-an-objet-using-darknet-and-r

Does the above case accurately describe your own project goals, please?

**Comment by MartyG-RealSense** [comment]
Hi @BnHassan1998  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
