### ISSUE TITLE
URDF for Intel D405

### ISSUE THREAD

**Issue by DimitrisKld** [realsenseai/realsense-ros#2317]
Hi, 

I would like to ask you if there is somewhere the URDF for the Intel D405 camera or if you are going to upload it soon. I checked the branches related to the ROS2 version, which is supported by Intel D405, but I could not find the URDF file. 

Thank you in advance.

**Comment by MartyG-RealSense** [comment]
Hi @DimitrisKld  New RealSense camera models do typically have URDF files for them added to the ROS wrapper over time, though I do not have information about plans for the release of a URDF for D405 for the ROS2 wrapper at the time of writing this.

**Comment by MartyG-RealSense** [comment]
Hi @DimitrisKld  Do you require further assistance with this case, please?  Thanks!

**Comment by DimitrisKld** [comment]
Hi @MartyG-RealSense , thank you for your response. No, I will follow the new releases in case this URDF file will be added.

**Comment by MartyG-RealSense** [comment]
Thanks very much @DimitrisKld for the update - I will close this case as you will be following the new releases.  Thanks again!

**Comment by MartyG-RealSense** [comment]
Hi again @DimitrisKld  I wanted to update you that the RealSense ROS developer team has advised me that the addition of a URDF for D405 is planned for a future wrapper release.

**Comment by weaponeer** [comment]
Also have been waiting for URDF/dae for the d405, any insight into when in the future these might be added to ros2-development?

**Comment by MartyG-RealSense** [comment]
Hi @weaponeer  There is currently not a time estimate available about implementation of a D405 URDF.  Any updates about it will be posted on https://github.com/IntelRealSense/realsense-ros/issues/2589 and so you will be automatically notified because you have left a comment there.  Thanks very much!

**Comment by SamerKhshiboun** [comment]
Hi @weaponeer 

> Also have been waiting for URDF/dae for the d405, any insight into when in the future these might be added to ros2-development?

While we are working to add D405 URDF, You can download the cad file of D405 from here:
https://www.intelrealsense.com/wp-content/uploads/2022/04/Intel_RealSense_D405_CAD_external.zip?_ga=2.95411544.577000463.1681198060-1846334074.1674552675

Then you can convert this STEP file to dae and stl files 
(I managed to download FreeCAD, and convert (File -> Export) these STEP file to .stl and .dae files)

You can import this dae file into your urdf.
For example:
```
<link name="my_link">
  <visual>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <mesh filename="path/to/my_file.dae"/>
    </geometry>
  </visual>
</link>
```

**Comment by MartyG-RealSense** [comment]
Hi @weaponeer  A URDF file for D405 has been added to the ros2-development wrapper - please see https://github.com/IntelRealSense/realsense-ros/pull/2953#event-11339930771

**Comment by weaponeer** [comment]
I see it there in ros2-development. 

Many Thanks!
