### ISSUE TITLE
Importing 3 different Realsense's into robot xacro fails. "material 'aluminum' already defined."

### ISSUE THREAD

**Issue by mkopack73** [realsenseai/realsense-ros#2338]
I have 3 different Realsense models on my robot (D455, a L515 and a T265). When I try to import the xacro from Realsense2_description into my robot model I get an error message saying that the material aluminum is already defined.

Looking at the xacro files for the D455 and the L515, they both import the materials.xacro file. So the second model import seems to be trying to do a second import of the materials.

Is there some way the camera xacro files can be set up to do a conditional import only if the materials aren't already defined? That way multiple models could be imported.

**Comment by MartyG-RealSense** [comment]
Hi @mkopack73  This issue was raised last month on this forum at https://github.com/IntelRealSense/realsense-ros/issues/2282

A RealSense ROS user created a Pull Request (PR) at https://github.com/IntelRealSense/realsense-ros/pull/2325 that suggested a fix.

**Comment by MartyG-RealSense** [comment]
Hi @mkopack73  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
