### ISSUE TITLE
D455 frames not published

### ISSUE THREAD

**Issue by MrOCW** [realsenseai/realsense-ros#2341]
Hi, initially installed librealsense via debian but built librealsense the manual way (https://github.com/IntelRealSense/librealsense/blob/master/doc/installation.md) as I encountered this error when I ran roslaunch realsense2_camera opensource_tracking.launch, rs_camera.launch also gave something similar
```
[ WARN] [1651861782.645117261]: Param '/camera/rgb_camera/power_line_frequency' has value 3 that is not in the enum { {50Hz: 1} {60Hz: 2} {Disabled: 0} }. Removing this parameter from dynamic reconfigure options.
[ INFO] [1651861782.650532277]: Done Setting Dynamic reconfig parameters.
[ INFO] [1651861782.650915955]: depth stream is enabled - width: 848, height: 480, fps: 30, Format: Z16
[ INFO] [1651861782.651775001]: color stream is enabled - width: 1280, height: 720, fps: 30, Format: RGB8
[ INFO] [1651861782.652533017]: setupPublishers...
[ INFO] [1651861782.654235890]: Expected frequency for depth = 30.00000
[ INFO] [1651861782.676849288]: Expected frequency for color = 30.00000
[ INFO] [1651861782.693968442]: Expected frequency for aligned_depth_to_color = 30.00000
[ INFO] [1651861782.711620033]: setupStreams...
[ INFO] [1651861782.721937388]: rtabmap 0.20.18 started...
[ INFO] [1651861782.918697137]: SELECTED BASE:Depth, 0
[ INFO] [1651861782.925413048]: RealSense Node Is Up!
[ WARN] [1651861783.650855109]: Hardware Notification:Depth stream start failure,1.65186e+12,Error,Hardware Error
(backend-v4l2.cpp:1127) Frames didn't arrived within 5 seconds
```
but failed at ./scripts/patch-realsense-ubuntu-lts.sh  (am on Ubuntu 20.04 running ROS Noetic)
```
Package required libusb-1.0-0-dev:  - found
Package required libssl-dev:  - found
Unsupported kernel version 5.13.0-40-generic . The Focal patches are maintained for Ubuntu LTS with kernel 5.4, 5.8, 5.11 only
```
carried on anyway, built from source and realsense-viewer works but i am still getting the same errors.
Also, the IMU doesnt seem to be publishing any information as well.

initial run of realsense-viewer works but when i disable and enable the RGB or stereo module, I get
![image](https://user-images.githubusercontent.com/67644448/167197871-f7e44bd5-ac4e-40af-ad47-550607911ae1.png)

**Comment by MartyG-RealSense** [comment]
Hi @MrOCW  Installing librealsense from both Debian packages and source code on the same computer should be avoided.  An example of the conflicts that can arise is the warning **Multiple realsense udev-rules were found!** that is caused by having two sets of udev device handling rules in two different folder locations.

In regard to the kernel version, although librealsense can work with unsupported kernels it increases the risk of unforseen consequences in regard to stability.  If you are unable to change your kernel version then building librealsense from source code with the **RSUSB backend** installation method may help.  An RSUSB build of librealsense bypasses the kernel.  It is therefore not dependent on Linux versions of kernel versions and does not require patching.

Another point to bear in mind if you have installed librealsense more than once is that each time you update librealsense, the RealSense ROS wrapper has to be built again afterwards if you did not install librealsense and the wrapper together from packages with **Method 1** of the wrapper's installation documentation.

**Comment by MrOCW** [comment]
@MartyG-RealSense Yup I got that so i removed the udev rule from the debian package and removed librealsense before building from source again. Not sure if I missed out on removing anything else.

Will try with the RSUSB backend and get back with the results! I've built the ROS wrapper from source

**Comment by MartyG-RealSense** [comment]
Thanks very much @MrOCW - I look forward to your next results.  Good luck!

**Comment by MrOCW** [comment]
@MartyG-RealSense 
I have built librealsense with 
cmake -DFORCE_RSUSB_BACKEND -DCMAKE_BUILD_TYPE=Release ..
sudo make uninstall && make clean && make && sudo make install
When i run realsense-viewer, I get
```
 08/05 00:15:52,385 WARNING [139944798451456] (messenger-libusb.cpp:42) control_transfer returned error, index: 300, error: Resource temporarily unavailable, number: b
 08/05 00:15:54,953 ERROR [139944437729024] (handle-libusb.h:51) failed to open usb interface: 0, error: RS2_USB_STATUS_ACCESS
 08/05 00:15:54,953 ERROR [139944897644288] (sensor.cpp:572) acquire_power failed: failed to set power state
 08/05 00:15:54,953 WARNING [139944897644288] (sensor.cpp:1173) Failed to add Backlight Compensation control for RGB Camera
 08/05 00:15:54,953 ERROR [139944437729024] (handle-libusb.h:51) failed to open usb interface: 0, error: RS2_USB_STATUS_ACCESS
 08/05 00:15:54,953 ERROR [139944897644288] (sensor.cpp:572) acquire_power failed: failed to set power state
 08/05 00:15:54,954 WARNING [139944897644288] (sensor.cpp:1173) Failed to add Brightness control for RGB Camera
 08/05 00:15:54,954 ERROR [139944437729024] (handle-libusb.h:51) failed to open usb interface: 0, error: RS2_USB_STATUS_ACCESS
 08/05 00:15:54,954 ERROR [139944897644288] (sensor.cpp:572) acquire_power failed: failed to set power state
 08/05 00:15:54,954 WARNING [139944897644288] (sensor.cpp:1173) Failed to add Contrast control for RGB Camera
 08/05 00:15:54,954 ERROR [139944437729024] (handle-libusb.h:51) failed to open usb interface: 0, error: RS2_USB_STATUS_ACCESS
 08/05 00:15:54,954 ERROR [139944897644288] (sensor.cpp:572) acquire_power failed: failed to set power state
 08/05 00:15:54,954 WARNING [139944897644288] (sensor.cpp:1173) Failed to add Exposure control for RGB Camera
 08/05 00:15:54,954 ERROR [139944437729024] (handle-libusb.h:51) failed to open usb interface: 0, error: RS2_USB_STATUS_ACCESS
 08/05 00:15:54,954 ERROR [139944897644288] (sensor.cpp:572) acquire_power failed: failed to set power state
 08/05 00:15:54,954 WARNING [139944897644288] (sensor.cpp:1173) Failed to add Gamma control for RGB Camera
 08/05 00:15:54,954 ERROR [139944437729024] (handle-libusb.h:51) failed to open usb interface: 0, error: RS2_USB_STATUS_ACCESS
 08/05 00:15:54,954 ERROR [139944897644288] (sensor.cpp:572) acquire_power failed: failed to set power state
 08/05 00:15:54,954 WARNING [139944897644288] (sensor.cpp:1173) Failed to add Hue control for RGB Camera
 08/05 00:15:54,954 ERROR [139944437729024] (handle-libusb.h:51) failed to open usb interface: 0, error: RS2_USB_STATUS_ACCESS
 08/05 00:15:54,954 ERROR [139944897644288] (sensor.cpp:572) acquire_power failed: failed to set power state
 08/05 00:15:54,954 WARNING [139944897644288] (sensor.cpp:1173) Failed to add Saturation control for RGB Camera
 08/05 00:15:54,954 ERROR [139944437729024] (handle-libusb.h:51) failed to open usb interface: 0, error: RS2_USB_STATUS_ACCESS
 08/05 00:15:54,954 ERROR [139944897644288] (sensor.cpp:572) acquire_power failed: failed to set power state
 08/05 00:15:54,954 WARNING [139944897644288] (sensor.cpp:1173) Failed to add Sharpness control for RGB Camera
 08/05 00:15:54,954 ERROR [139944437729024] (handle-libusb.h:51) failed to open usb interface: 0, error: RS2_USB_STATUS_ACCESS
 08/05 00:15:54,954 ERROR [139944897644288] (sensor.cpp:572) acquire_power failed: failed to set power state
 08/05 00:15:54,954 WARNING [139944897644288] (sensor.cpp:1173) Failed to add White Balance control for RGB Camera
 08/05 00:15:54,954 ERROR [139944437729024] (handle-libusb.h:51) failed to open usb interface: 0, error: RS2_USB_STATUS_ACCESS
 08/05 00:15:54,954 ERROR [139944897644288] (sensor.cpp:572) acquire_power failed: failed to set power state
 08/05 00:15:54,954 WARNING [139944897644288] (sensor.cpp:1173) Failed to add Enable Auto Exposure control for RGB Camera
 08/05 00:15:54,954 ERROR [139944437729024] (handle-libusb.h:51) failed to open usb interface: 0, error: RS2_USB_STATUS_ACCESS
 08/05 00:15:54,954 ERROR [139944897644288] (sensor.cpp:572) acquire_power failed: failed to set power state
 08/05 00:15:54,954 WARNING [139944897644288] (sensor.cpp:1173) Failed to add Enable Auto White Balance control for RGB Camera
```
the realsense-viewer hangs

**Comment by MrOCW** [comment]
ok sometimes it works after retrying a few times.. will make do with this for now.

**Comment by MartyG-RealSense** [comment]
Thanks very much. @MrOCW 

When you build from source with CMake, you should include the build flags below to build the graphical examples and tools, including realsense-viewer and support in the SDK for those graphical examples / tools.

**-DBUILD_EXAMPLES=true -DBUILD_GRAPHICAL_EXAMPLES=true**

For example:

**cmake ../  -DFORCE_RSUSB_BACKEND=true -DCMAKE_BUILD_TYPE=Release -DBUILD_EXAMPLES=true -DBUILD_GRAPHICAL_EXAMPLES=true**

Note that in the above command, DFORCE_RSUSB_BACKEND is set to true, whilst your own CMake instruction did not set a true / false status for it.
