### ISSUE TITLE
TF issue........when I try to launch....I'm getting below issue......how to fix this?

### ISSUE THREAD

**Issue by LOKAKSHAI** [realsenseai/realsense-ros#2346]
[ WARN] [1652095485.189156213]: Unable to transform object from frame 'camera_color_optical_frame' to planning frame 'world' (Could not find a connection between 'world' and 'camera_color_optical_frame' because they are not part of the same tree.Tf has two or more unconnected trees.)

**Comment by MartyG-RealSense** [comment]
Hi @LOKAKSHAI   My research of your question indicates that there have not been previous cases of similar errors related to RealSense.

Expanding the research to non-RealSense cases, a discussion on the official ROS support forum at the link below of a similar error may provide useful insights.

https://answers.ros.org/question/384687/unable-to-transform-object-from-namespaced-frame-nsbase_link-to-planning-frame-base_link/

**Comment by MartyG-RealSense** [comment]
Hi @LOKAKSHAI  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
