### ISSUE TITLE
Realsense Node is up, but there is WARN

### ISSUE THREAD

**Issue by Xue21** [realsenseai/realsense-ros#2359]
when I roslaunch realsense2_camera rs_camera,there are some questions as below.How can I resolve it?
[ WARN] [1653656916.153582437]: Param '/camera/rgb_camera/power_line_frequency' has value 3 that is not in the enum { {50Hz: 1} {60Hz: 2} {Disabled: 0} }. Removing this parameter from dynamic reconfigure options.

**Comment by MartyG-RealSense** [comment]
Hi @Xue21  You can ignore this warning as it occurs commonly in launches and does not usually have any consequences for the performance of the RealSense ROS wrapper.  The RealSense SDK's power line frequency option is typically only used when configuring the camera to have less depth image noise in locations with fluorescent lights such as ceiling strip lights that operate at particular frequencies (60 Hz in the Americas and 50 Hz in European regions).
