### ISSUE TITLE
depth image is not proper and have weired pattern or noise

### ISSUE THREAD

**Issue by ziggBee30** [realsenseai/realsense-ros#236]
### System Configuration
Please complete Your Configuration detail below. Refer to the BKC at [Configuration](../realsense_camera/README.md#configuration).

| Version               | Your Configuration   |
|:--------------------- |:---------------------|
| Operating System      | ubuntu              |
| Kernel                | 4.4.0-72-generic             |
| ROS                   | kinect                   |
| ROS RealSense         | realsense_camera             |
| Camera Type-Firmware  | r200           |

---

### Expected Behavior
there should now be any holes in the depth image . 

### Actual Behavior
the depth image is weired and seems not to be working as it should be ,, please help diagnose this problem as i am not able to use depth value properly because of this issue 
please take a look at the image below 

![depth_w](https://cloud.githubusercontent.com/assets/17492699/25142505/0327691e-245f-11e7-9ab2-bf93006a9881.png)

**Comment by ziggBee30** [comment]
@mdhorn

**Comment by mattcurfman** [comment]
the 'cpp-capture' utility shows R200 previews running at 640x480, which means that the R200 minimal depth it can see is 72cm (reference: https://github.com/IntelRealSense/librealsense/blob/master/doc/camera_specs.md).  What does it look like with your hand 72cm or farther?

At 320x240, the minimal depth is 32cm

**Comment by ziggBee30** [comment]
its better now , it was the same result with 72 cm or far but i did some setting change and luckily i got it to original depth clarity.. 
thanks  @mattcurfman
