### ISSUE TITLE
D435 camera strange phenomenon, a point cloud map

### ISSUE THREAD

**Issue by xiaopgaxiaopg** [realsenseai/realsense-ros#2368]
Under the system of 18.04, gazebo simulation D435 camera released point cloud data, the phenomenon is as follows, where the red box is abnormal, I converted the point cloud into Anotomap, the phenomenon was completely exposed, I want to seek help, how to remove the point cloud map in the red box in the point cloud environment, very much need your help, I have been stuck for a week。
![4](https://user-images.githubusercontent.com/99733467/172144917-df9810eb-b3b0-47b7-a7d5-c7d11e765dd8.png)
![2](https://user-images.githubusercontent.com/99733467/172144953-b0628d03-14ca-4469-afe4-0df9fda9a111.png)
![3](https://user-images.githubusercontent.com/99733467/172144969-f8caaa62-f79a-4d7c-a9d0-f3753596d8b2.png)

**Comment by MartyG-RealSense** [comment]
Hi @xiaopgaxiaopg  Is the 'wall' that you have marked with the block an area that exists in the real world or is it false depth data representing something that is not actually there, please?

**Comment by xiaopgaxiaopg** [comment]
This is the scene simulated in gazebo, not using the real d435, the scene in the picture below, this wall does not exist



---- Replied Message ----
| From | ***@***.***> |
| Date | 06/06/2022 20:27 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [IntelRealSense/realsense-ros] D435 camera strange phenomenon, a point cloud map (Issue #2368) |

Hi @xiaopgaxiaopg Is the 'wall' that you have marked with the block an area that exists in the real world or is it false depth data representing something that is not actually there, please?

**Comment by xiaopgaxiaopg** [comment]
This is the scene simulated in gazebo, and the real d435 is not used. In the scene in the figure below, this wall does not exist, it is the non-existent data represented by the depth data. In fact, in gazebo, I only put one cylinder, and the others are No, normally speaking, only the cylinder and the point cloud on the ground should be right



---- Replied Message ----
| From | ***@***.***> |
| Date | 06/06/2022 20:27 |
| To | ***@***.***> |
| Cc | ***@***.******@***.***> |
| Subject | Re: [IntelRealSense/realsense-ros] D435 camera strange phenomenon, a point cloud map (Issue #2368) |

Hi @xiaopgaxiaopg Is the 'wall' that you have marked with the block an area that exists in the real world or is it false depth data representing something that is not actually there, please?

**Comment by xiaopgaxiaopg** [comment]
> Hi @xiaopgaxiaopg Is the 'wall' that you have marked with the block an area that exists in the real world or is it false depth data representing something that is not actually there, please?

Dear sir, can you leave an email, I will provide you with the source code, you can test it directly.

**Comment by MartyG-RealSense** [comment]
I am not able to test customer source code on my computer, unfortunately.

If there is an area of depth detail that does not correspond to the real life scene then it may be because of a phenomenon called 'ghost noise'.  This may be because the camera may have been confused by some of the objects or surfaces in the real life scene.  Are you able to provide an RGB image of the scene so that I can see whether there are elements present that may be difficult for the camera to read accurately, please?

**Comment by xiaopgaxiaopg** [comment]
> I am not able to test customer source code on my computer, unfortunately.
> 
> If there is an area of depth detail that does not correspond to the real life scene then it may be because of a phenomenon called 'ghost noise'. This may be because the camera may have been confused by some of the objects or surfaces in the real life scene. Are you able to provide an RGB image of the scene so that I can see whether there are elements present that may be difficult for the camera to read accurately, please?

I need to save the scene in this picture, the projected image in this picture is projected by the rgb camera and can be closed, I tested. I suspect that the depth camera also carried out projection, but I didn't find the place to close, which is just a guess
![屏幕截图 2022-06-06 211355](https://user-images.githubusercontent.com/99733467/172167792-eb6a2c9b-4785-45d3-aece-f78b23322908.png)
<sensor name="${camera_name}color" type="camera">
        <camera name="${camera_name}">
          <horizontal_fov>${69.4*deg_to_rad}</horizontal_fov>
          <image>
.....
        </camera>
.....
        <visualize>0</visualize>
        
      </sensor>

**Comment by xiaopgaxiaopg** [comment]
> I am not able to test customer source code on my computer, unfortunately.
> 
> If there is an area of depth detail that does not correspond to the real life scene then it may be because of a phenomenon called 'ghost noise'. This may be because the camera may have been confused by some of the objects or surfaces in the real life scene. Are you able to provide an RGB image of the scene so that I can see whether there are elements present that may be difficult for the camera to read accurately, please?

In fact, the problem of reproducing is not complicated, just need to use the D435 camera to collect depth data in the gazebo environment, publish the depth topic /depth/point, and then view the topic of using pointcloud2 in Rviz

**Comment by MartyG-RealSense** [comment]
Is the problem that the projected RGB image is appearing on the depth image and you are unable to close it?

**Comment by xiaopgaxiaopg** [comment]
> Is the problem that the projected RGB image is appearing on the depth image and you are unable to close it?

I don't know, I can't determine the cause, I decided to change the camera

**Comment by xiaopgaxiaopg** [comment]
> Is the problem that the projected RGB image is appearing on the depth image and you are unable to close it?

Dear sir, I have a new idea, I feel that it should be the point cloud within the effective detection range of the clip parameter control, the point cloud projection perpendicular to the camera lens plane, that is, this projection is parallel to the camera plane, but I don't know how to turn off this projection, clip this parameter I can only search the farthest and closest distance at the moment, but I have not found the parameter that controls the projection
![image](https://user-images.githubusercontent.com/99733467/172287713-d662fc66-ba13-43ec-af5c-64a2136c940f.png)
![image](https://user-images.githubusercontent.com/99733467/172287746-1e81cca2-e382-4edb-a5ef-807aa3673210.png)

**Comment by xiaopgaxiaopg** [comment]
> Is the problem that the projected RGB image is appearing on the depth image and you are unable to close it?

![image](https://user-images.githubusercontent.com/99733467/172356519-af35672e-8e6d-4d71-952e-3a225ce8746d.png)
kinect v2 
![image](https://user-images.githubusercontent.com/99733467/172357089-4a7f7803-75f3-4dce-b50a-f32d9b1f8f82.png)

**Comment by MartyG-RealSense** [comment]
I researched your case again carefully.  I wonder whether your situation is similar to a MoveIt tutorial in the link below that shows how to extract a cylinder from a pointcloud and remove the points of the surface on which the pointcloud is resting.

https://ros-planning.github.io/moveit_tutorials/doc/perception_pipeline/perception_pipeline_tutorial.html#detecting-and-adding-object-as-collision-object

![image](https://user-images.githubusercontent.com/41145062/172364270-39604e03-4324-441c-a5e2-ef68311c63e1.png)

**Comment by xiaopgaxiaopg** [comment]
> I researched your case again carefully. I wonder whether your situation is similar to a MoveIt tutorial in the link below that shows how to extract a cylinder from a pointcloud and remove the points of the surface on which the pointcloud is resting.
> 
> https://ros-planning.github.io/moveit_tutorials/doc/perception_pipeline/perception_pipeline_tutorial.html#detecting-and-adding-object-as-collision-object



> I researched your case again carefully. I wonder whether your situation is similar to a MoveIt tutorial in the link below that shows how to extract a cylinder from a pointcloud and remove the points of the surface on which the pointcloud is resting.
> 
> https://ros-planning.github.io/moveit_tutorials/doc/perception_pipeline/perception_pipeline_tutorial.html#detecting-and-adding-object-as-collision-object
> 
> ![image](https://user-images.githubusercontent.com/41145062/172364270-39604e03-4324-441c-a5e2-ef68311c63e1.png)

Dear sir, the function I want to do is indeed the function in this tutorial, the similar to the wall in the figure I do not know how he appeared, looking at the phenomenon is indeed similar, in the previous message, I changed the camera still appeared the phenomenon of d435, I just contacted my friend, and provided the source code, please give them a test, will not appear my same phenomenon. Reply to mr. later. If it is convenient, I am willing to provide the source code of github's kinect, please sir run it personally.
https://github.com/wangxian4423/kinect_v2_udrf
The code needs to be tweaked, I have a good adjustment here, I hope Mr. provides a mailbox

**Comment by MartyG-RealSense** [comment]
I am not able to run code or tests or use ROS on my computer, unfortunately.  I can only advise about how to adjust your own system where possible.  My knowledge of Gazebo is very limited though so in this particular subject I can only point you to other references in the hope that they will be helpful.

https://github.com/ros-planning/moveit/issues/2374 is another example of problems with extracting a cylinder from a pointcloud with MoveIt.  Do you get any error messages in your terminal like the ones in this link?

Of the few cases I have seen in my research where people were trying to remove the pointcloud, they all seem to have experienced problems with it that they could not find a solution to.

**Comment by xiaopgaxiaopg** [comment]
> I am not able to run code or tests or use ROS on my computer, unfortunately. I can only advise about how to adjust your own system where possible. My knowledge of Gazebo is very limited though so in this particular subject I can only point you to other references in the hope that they will be helpful.
> 
> [ros-planning/moveit#2374](https://github.com/ros-planning/moveit/issues/2374) is another example of problems with extracting a cylinder from a pointcloud with MoveIt. Do you get any error messages in your terminal like the ones in this link?
> 
> Of the few cases I have seen in my research where people were trying to remove the pointcloud, they all seem to have experienced problems with it that they could not find a solution to.

Dear sir, my problem was solved, it should be a system problem, I reinstalled the ros system of 18.04 and everything became normal, thank you sir for your support and help these days.

**Comment by MartyG-RealSense** [comment]
You are very welcome.  That's excellent news to hear.   Thanks very much for the update!

**Comment by MartyG-RealSense** [comment]
Case closed due to solution achieved and no further comments received.
