### ISSUE TITLE
[camera/realsense2_camera_manager-2] process has died Cam died after running ros

### ISSUE THREAD

**Issue by tobiasonkes** [realsenseai/realsense-ros#2376]
Dear Sir and Madam,

Currently I have problems to use my Realsense camera. I pull the docker and would like to start with the single camera intrinsic calibration. For that I would like to run` roslaunch realsense2_camera rs_camera.launch`. Unfortunatily he didn't recognize the camera themself. I am able to see the cameraoutput via realsense-viewer. So the camera themself is definitely connect via usb3.2. I don't know what is the problem cuz like I understand when I using docker successfully I don't have to concentrate on the software part. Enclose I submit the shelloutputt.

`root@tobias-Latitude-5580:~# ls /dev/video*
/dev/video0  /dev/video2  /dev/video4  /dev/video6
/dev/video1  /dev/video3  /dev/video5  /dev/video7
root@tobias-Latitude-5580:~# roslaunch realsense2_camera rs_camera.launch enable_gyro:=true enable_accel:=true
... logging to /root/.ros/log/e7dd92d2-e96b-11ec-b371-f894c28bcba3/roslaunch-tobias-Latitude-5580-461.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://tobias-Latitude-5580:41791/

SUMMARY
========

PARAMETERS
 * /camera/realsense2_camera/accel_fps: 250
 * /camera/realsense2_camera/accel_frame_id: camera_accel_frame
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: False
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/allow_no_texture_points: False
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/calib_odom_file: 
 * /camera/realsense2_camera/clip_distance: -2.0
 * /camera/realsense2_camera/color_fps: 30
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: 480
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: 640
 * /camera/realsense2_camera/depth_fps: 30
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: 480
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: 640
 * /camera/realsense2_camera/device_type: 
 * /camera/realsense2_camera/enable_accel: True
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye1: True
 * /camera/realsense2_camera/enable_fisheye2: True
 * /camera/realsense2_camera/enable_fisheye: True
 * /camera/realsense2_camera/enable_gyro: True
 * /camera/realsense2_camera/enable_infra1: True
 * /camera/realsense2_camera/enable_infra2: True
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_sync: False
 * /camera/realsense2_camera/filters: 
 * /camera/realsense2_camera/fisheye1_frame_id: camera_fisheye1_f...
 * /camera/realsense2_camera/fisheye1_optical_frame_id: camera_fisheye1_o...
 * /camera/realsense2_camera/fisheye2_frame_id: camera_fisheye2_f...
 * /camera/realsense2_camera/fisheye2_optical_frame_id: camera_fisheye2_o...
 * /camera/realsense2_camera/fisheye_fps: 30
 * /camera/realsense2_camera/fisheye_frame_id: camera_fisheye_frame
 * /camera/realsense2_camera/fisheye_height: 480
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: 640
 * /camera/realsense2_camera/gyro_fps: 400
 * /camera/realsense2_camera/gyro_frame_id: camera_gyro_frame
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/imu_optical_frame_id: camera_imu_optica...
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra_fps: 30
 * /camera/realsense2_camera/infra_height: 480
 * /camera/realsense2_camera/infra_width: 640
 * /camera/realsense2_camera/initial_reset: False
 * /camera/realsense2_camera/json_file_path: 
 * /camera/realsense2_camera/linear_accel_cov: 0.01
 * /camera/realsense2_camera/odom_frame_id: camera_odom_frame
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/pose_frame_id: camera_pose_frame
 * /camera/realsense2_camera/pose_optical_frame_id: camera_pose_optic...
 * /camera/realsense2_camera/publish_odom_tf: True
 * /camera/realsense2_camera/publish_tf: True
 * /camera/realsense2_camera/rosbag_filename: 
 * /camera/realsense2_camera/serial_no: 
 * /camera/realsense2_camera/tf_publish_rate: 0.0
 * /camera/realsense2_camera/topic_odom_in: odom_in
 * /camera/realsense2_camera/unite_imu_method: 
 * /camera/realsense2_camera/usb_port_id: 
 * /rosdistro: melodic
 * /rosversion: 1.14.3

NODES
  /camera/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)

auto-starting new master
process[master]: started with pid [471]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to e7dd92d2-e96b-11ec-b371-f894c28bcba3
process[rosout-1]: started with pid [482]
started core service [/rosout]
process[camera/realsense2_camera_manager-2]: started with pid [489]
[ INFO] [1654941022.494273042]: Initializing nodelet with 4 worker threads.
process[camera/realsense2_camera-3]: started with pid [490]
[ INFO] [1654941023.228621475]: RealSense ROS v2.2.12
[ INFO] [1654941023.228724395]: Running with LibRealSense v2.32.1
[ INFO] [1654941023.257836505]:  
[ INFO] [1654941023.271107994]: Device with serial number 745412070908 was found.

[ INFO] [1654941023.271160466]: Device with physical ID /sys/devices/pci0000:00/0000:00:14.0/usb2/2-3/2-3:1.0/video4linux/video2 was found.
[ INFO] [1654941023.271183889]: Device with name Intel RealSense D435 was found.
[ INFO] [1654941023.271637300]: Device with port number 2-3 was found.
[ INFO] [1654941023.273931419]: getParameters...
[ INFO] [1654941023.323903834]: setupDevice...
[ INFO] [1654941023.323944352]: JSON file is not provided
[ INFO] [1654941023.324113927]: ROS Node Namespace: camera
[ INFO] [1654941023.324197304]: Device Name: Intel RealSense D435
[ INFO] [1654941023.324243602]: Device Serial No: 745412070908
[ INFO] [1654941023.324259604]: Device physical port: /sys/devices/pci0000:00/0000:00:14.0/usb2/2-3/2-3:1.0/video4linux/video2
[ INFO] [1654941023.324276919]: Device FW version: 05.13.00.50
[ INFO] [1654941023.324293342]: Device Product ID: 0x0B07
[ INFO] [1654941023.324308592]: Enable PointCloud: Off
[ INFO] [1654941023.324323726]: Align Depth: Off
[ INFO] [1654941023.324334976]: Sync Mode: Off
[ INFO] [1654941023.324373894]: Device Sensors: 
[ INFO] [1654941023.324416144]: Stereo Module was found.
[ INFO] [1654941023.324435135]: RGB Camera was found.
[ INFO] [1654941023.324466673]: (Fisheye, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1654941023.324482125]: (Fisheye, 1) sensor isn't supported by current device! -- Skipping...
[ INFO] [1654941023.324495997]: (Fisheye, 2) sensor isn't supported by current device! -- Skipping...
[ INFO] [1654941023.324507542]: (Gyro, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1654941023.324524409]: (Accel, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1654941023.324538558]: (Pose, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1654941023.324563272]: num_filters: 0
[ INFO] [1654941023.324577555]: Setting Dynamic reconfig parameters.
 11/06 09:50:23,340 WARNING [140628365657856] (types.cpp:49) hwmon command 0x7d failed. Error type: No data to return (-21).
terminate called after throwing an instance of 'rs2::invalid_value_error'
  what():  hwmon command 0x7d failed. Error type: No data to return (-21).
[camera/realsense2_camera_manager-2] process has died [pid 489, exit code -6, cmd /opt/ros/melodic/lib/nodelet/nodelet manager __name:=realsense2_camera_manager __log:=/root/.ros/log/e7dd92d2-e96b-11ec-b371-f894c28bcba3/camera-realsense2_camera_manager-2.log].
log file: /root/.ros/log/e7dd92d2-e96b-11ec-b371-f894c28bcba3/camera-realsense2_camera_manager-2*.log
[camera/realsense2_camera-3] process has finished cleanly
log file: /root/.ros/log/e7dd92d2-e96b-11ec-b371-f894c28bcba3/camera-realsense2_camera-3*.log
`

However when I run ` rs-enumerate-devices `. I got the respond that my camera is successfully connected. 

`root@tobias-Latitude-5580:~# rs-enumerate-devices                                               
Device info: 
    Name                          : 	Intel RealSense D435
    Serial Number                 : 	745412070908
    Firmware Version              : 	05.13.00.50
    Recommended Firmware Version  : 	05.12.02.100
    Physical Port                 : 	/sys/devices/pci0000:00/0000:00:14.0/usb2/2-3/2-3:1.0/video4linux/video2
    Debug Op Code                 : 	15
    Advanced Mode                 : 	YES
    Product Id                    : 	0B07
    Camera Locked                 : 	YES
    Usb Type Descriptor           : 	3.2
    Product Line                  : 	D400
    Asic Serial Number            : 	808513020640
    Firmware Update Id            : 	808513020640

Stream Profiles supported by Stereo Module
 Supported modes:
    stream       resolution      fps       format   
    Infrared 1	  1280x800	@ 30Hz	   Y8
    Infrared 2	  1280x800	@ 30Hz	   Y8
    Infrared 1	  1280x800	@ 25Hz	   Y16
    Infrared 2	  1280x800	@ 25Hz	   Y16
    Infrared 2	  1280x800	@ 15Hz	   Y16
    Infrared 1	  1280x800	@ 15Hz	   Y16
    Infrared 2	  1280x800	@ 15Hz	   Y8
    Infrared 1	  1280x800	@ 15Hz	   Y8
    Infrared 1	  1280x720	@ 30Hz	   Y8
    Infrared 2	  1280x720	@ 30Hz	   Y8
    Infrared 1	  1280x720	@ 15Hz	   Y8
    Infrared 2	  1280x720	@ 15Hz	   Y8
    Infrared 2	  1280x720	@ 6Hz	   Y8
    Infrared 1	  1280x720	@ 6Hz	   Y8
    Infrared 2	  848x480	@ 90Hz	   Y8
    Infrared 1	  848x480	@ 90Hz	   Y8
    Infrared 2	  848x480	@ 60Hz	   Y8
    Infrared 1	  848x480	@ 60Hz	   Y8
    Infrared 2	  848x480	@ 30Hz	   Y8
    Infrared 1	  848x480	@ 30Hz	   Y8
    Infrared 2	  848x480	@ 15Hz	   Y8
    Infrared 1	  848x480	@ 15Hz	   Y8
    Infrared 1	  848x480	@ 6Hz	   Y8
    Infrared 2	  848x480	@ 6Hz	   Y8
    Infrared 1	  848x100	@ 300Hz	   Y8
    Infrared 2	  848x100	@ 300Hz	   Y8
    Infrared 1	  848x100	@ 100Hz	   Y8
    Infrared 2	  848x100	@ 100Hz	   Y8
    Infrared 2	  640x480	@ 90Hz	   Y8
    Infrared 1	  640x480	@ 90Hz	   Y8
    Infrared 1	  640x480	@ 60Hz	   Y8
    Infrared 2	  640x480	@ 60Hz	   Y8
    Infrared 1	  640x480	@ 30Hz	   Y8
    Infrared 2	  640x480	@ 30Hz	   Y8
    Infrared 2	  640x480	@ 15Hz	   Y8
    Infrared 1	  640x480	@ 15Hz	   Y8
    Infrared 1	  640x480	@ 6Hz	   Y8
    Infrared 2	  640x480	@ 6Hz	   Y8
    Infrared 1	  640x400	@ 25Hz	   Y16
    Infrared 2	  640x400	@ 25Hz	   Y16
    Infrared 1	  640x400	@ 15Hz	   Y16
    Infrared 2	  640x400	@ 15Hz	   Y16
    Infrared 1	  640x360	@ 90Hz	   Y8
    Infrared 2	  640x360	@ 90Hz	   Y8
    Infrared 1	  640x360	@ 60Hz	   Y8
    Infrared 2	  640x360	@ 60Hz	   Y8
    Infrared 2	  640x360	@ 30Hz	   Y8
    Infrared 1	  640x360	@ 30Hz	   Y8
    Infrared 2	  640x360	@ 15Hz	   Y8
    Infrared 1	  640x360	@ 15Hz	   Y8
    Infrared 2	  640x360	@ 6Hz	   Y8
    Infrared 1	  640x360	@ 6Hz	   Y8
    Infrared 1	  480x270	@ 90Hz	   Y8
    Infrared 2	  480x270	@ 90Hz	   Y8
    Infrared 1	  480x270	@ 60Hz	   Y8
    Infrared 2	  480x270	@ 60Hz	   Y8
    Infrared 2	  480x270	@ 30Hz	   Y8
    Infrared 1	  480x270	@ 30Hz	   Y8
    Infrared 2	  480x270	@ 15Hz	   Y8
    Infrared 1	  480x270	@ 15Hz	   Y8
    Infrared 1	  480x270	@ 6Hz	   Y8
    Infrared 2	  480x270	@ 6Hz	   Y8
    Infrared 2	  424x240	@ 90Hz	   Y8
    Infrared 1	  424x240	@ 90Hz	   Y8
    Infrared 1	  424x240	@ 60Hz	   Y8
    Infrared 2	  424x240	@ 60Hz	   Y8
    Infrared 1	  424x240	@ 30Hz	   Y8
    Infrared 2	  424x240	@ 30Hz	   Y8
    Infrared 1	  424x240	@ 15Hz	   Y8
    Infrared 2	  424x240	@ 15Hz	   Y8
    Infrared 1	  424x240	@ 6Hz	   Y8
    Infrared 2	  424x240	@ 6Hz	   Y8
    Depth	  1280x720	@ 30Hz	   Z16
    Depth	  1280x720	@ 15Hz	   Z16
    Depth	  1280x720	@ 6Hz	   Z16
    Depth	  848x480	@ 90Hz	   Z16
    Depth	  848x480	@ 60Hz	   Z16
    Depth	  848x480	@ 30Hz	   Z16
    Depth	  848x480	@ 15Hz	   Z16
    Depth	  848x480	@ 6Hz	   Z16
    Depth	  848x100	@ 300Hz	   Z16
    Depth	  848x100	@ 100Hz	   Z16
    Depth	  640x480	@ 90Hz	   Z16
    Depth	  640x480	@ 60Hz	   Z16
    Depth	  640x480	@ 30Hz	   Z16
    Depth	  640x480	@ 15Hz	   Z16
    Depth	  640x480	@ 6Hz	   Z16
    Depth	  640x360	@ 90Hz	   Z16
    Depth	  640x360	@ 60Hz	   Z16
    Depth	  640x360	@ 30Hz	   Z16
    Depth	  640x360	@ 15Hz	   Z16
    Depth	  640x360	@ 6Hz	   Z16
    Depth	  480x270	@ 90Hz	   Z16
    Depth	  480x270	@ 60Hz	   Z16
    Depth	  480x270	@ 30Hz	   Z16
    Depth	  480x270	@ 15Hz	   Z16
    Depth	  480x270	@ 6Hz	   Z16
    Depth	  424x240	@ 90Hz	   Z16
    Depth	  424x240	@ 60Hz	   Z16
    Depth	  424x240	@ 30Hz	   Z16
    Depth	  424x240	@ 15Hz	   Z16
    Depth	  424x240	@ 6Hz	   Z16
    Depth	  256x144	@ 300Hz	   Z16
    Depth	  256x144	@ 90Hz	   Z16

Stream Profiles supported by RGB Camera
 Supported modes:
    stream       resolution      fps       format   
    Color	  1920x1080	@ 30Hz	   RGB8
    Color	  1920x1080	@ 30Hz	   Y16
    Color	  1920x1080	@ 30Hz	   BGRA8
    Color	  1920x1080	@ 30Hz	   RGBA8
    Color	  1920x1080	@ 30Hz	   BGR8
    Color	  1920x1080	@ 30Hz	   YUYV
    Color	  1920x1080	@ 15Hz	   RGB8
    Color	  1920x1080	@ 15Hz	   Y16
    Color	  1920x1080	@ 15Hz	   BGRA8
    Color	  1920x1080	@ 15Hz	   RGBA8
    Color	  1920x1080	@ 15Hz	   BGR8
    Color	  1920x1080	@ 15Hz	   YUYV
    Color	  1920x1080	@ 6Hz	   RGB8
    Color	  1920x1080	@ 6Hz	   Y16
    Color	  1920x1080	@ 6Hz	   BGRA8
    Color	  1920x1080	@ 6Hz	   RGBA8
    Color	  1920x1080	@ 6Hz	   BGR8
    Color	  1920x1080	@ 6Hz	   YUYV
    Color	  1280x720	@ 30Hz	   RGB8
    Color	  1280x720	@ 30Hz	   Y16
    Color	  1280x720	@ 30Hz	   BGRA8
    Color	  1280x720	@ 30Hz	   RGBA8
    Color	  1280x720	@ 30Hz	   BGR8
    Color	  1280x720	@ 30Hz	   YUYV
    Color	  1280x720	@ 15Hz	   RGB8
    Color	  1280x720	@ 15Hz	   Y16
    Color	  1280x720	@ 15Hz	   BGRA8
    Color	  1280x720	@ 15Hz	   RGBA8
    Color	  1280x720	@ 15Hz	   BGR8
    Color	  1280x720	@ 15Hz	   YUYV
    Color	  1280x720	@ 6Hz	   RGB8
    Color	  1280x720	@ 6Hz	   Y16
    Color	  1280x720	@ 6Hz	   BGRA8
    Color	  1280x720	@ 6Hz	   RGBA8
    Color	  1280x720	@ 6Hz	   BGR8
    Color	  1280x720	@ 6Hz	   YUYV
    Color	  960x540	@ 60Hz	   RGB8
    Color	  960x540	@ 60Hz	   Y16
    Color	  960x540	@ 60Hz	   BGRA8
    Color	  960x540	@ 60Hz	   RGBA8
    Color	  960x540	@ 60Hz	   BGR8
    Color	  960x540	@ 60Hz	   YUYV
    Color	  960x540	@ 30Hz	   RGB8
    Color	  960x540	@ 30Hz	   Y16
    Color	  960x540	@ 30Hz	   BGRA8
    Color	  960x540	@ 30Hz	   RGBA8
    Color	  960x540	@ 30Hz	   BGR8
    Color	  960x540	@ 30Hz	   YUYV
    Color	  960x540	@ 15Hz	   RGB8
    Color	  960x540	@ 15Hz	   Y16
    Color	  960x540	@ 15Hz	   BGRA8
    Color	  960x540	@ 15Hz	   RGBA8
    Color	  960x540	@ 15Hz	   BGR8
    Color	  960x540	@ 15Hz	   YUYV
    Color	  960x540	@ 6Hz	   RGB8
    Color	  960x540	@ 6Hz	   Y16
    Color	  960x540	@ 6Hz	   BGRA8
    Color	  960x540	@ 6Hz	   RGBA8
    Color	  960x540	@ 6Hz	   BGR8
    Color	  960x540	@ 6Hz	   YUYV
    Color	  848x480	@ 60Hz	   RGB8
    Color	  848x480	@ 60Hz	   Y16
    Color	  848x480	@ 60Hz	   BGRA8
    Color	  848x480	@ 60Hz	   RGBA8
    Color	  848x480	@ 60Hz	   BGR8
    Color	  848x480	@ 60Hz	   YUYV
    Color	  848x480	@ 30Hz	   RGB8
    Color	  848x480	@ 30Hz	   Y16
    Color	  848x480	@ 30Hz	   BGRA8
    Color	  848x480	@ 30Hz	   RGBA8
    Color	  848x480	@ 30Hz	   BGR8
    Color	  848x480	@ 30Hz	   YUYV
    Color	  848x480	@ 15Hz	   RGB8
    Color	  848x480	@ 15Hz	   Y16
    Color	  848x480	@ 15Hz	   BGRA8
    Color	  848x480	@ 15Hz	   RGBA8
    Color	  848x480	@ 15Hz	   BGR8
    Color	  848x480	@ 15Hz	   YUYV
    Color	  848x480	@ 6Hz	   RGB8
    Color	  848x480	@ 6Hz	   Y16
    Color	  848x480	@ 6Hz	   BGRA8
    Color	  848x480	@ 6Hz	   RGBA8
    Color	  848x480	@ 6Hz	   BGR8
    Color	  848x480	@ 6Hz	   YUYV
    Color	  640x480	@ 60Hz	   RGB8
    Color	  640x480	@ 60Hz	   Y16
    Color	  640x480	@ 60Hz	   BGRA8
    Color	  640x480	@ 60Hz	   RGBA8
    Color	  640x480	@ 60Hz	   BGR8
    Color	  640x480	@ 60Hz	   YUYV
    Color	  640x480	@ 30Hz	   RGB8
    Color	  640x480	@ 30Hz	   Y16
    Color	  640x480	@ 30Hz	   BGRA8
    Color	  640x480	@ 30Hz	   RGBA8
    Color	  640x480	@ 30Hz	   BGR8
    Color	  640x480	@ 30Hz	   YUYV
    Color	  640x480	@ 15Hz	   RGB8
    Color	  640x480	@ 15Hz	   Y16
    Color	  640x480	@ 15Hz	   BGRA8
    Color	  640x480	@ 15Hz	   RGBA8
    Color	  640x480	@ 15Hz	   BGR8
    Color	  640x480	@ 15Hz	   YUYV
    Color	  640x480	@ 6Hz	   RGB8
    Color	  640x480	@ 6Hz	   Y16
    Color	  640x480	@ 6Hz	   BGRA8
    Color	  640x480	@ 6Hz	   RGBA8
    Color	  640x480	@ 6Hz	   BGR8
    Color	  640x480	@ 6Hz	   YUYV
    Color	  640x360	@ 60Hz	   RGB8
    Color	  640x360	@ 60Hz	   Y16
    Color	  640x360	@ 60Hz	   BGRA8
    Color	  640x360	@ 60Hz	   RGBA8
    Color	  640x360	@ 60Hz	   BGR8
    Color	  640x360	@ 60Hz	   YUYV
    Color	  640x360	@ 30Hz	   RGB8
    Color	  640x360	@ 30Hz	   Y16
    Color	  640x360	@ 30Hz	   BGRA8
    Color	  640x360	@ 30Hz	   RGBA8
    Color	  640x360	@ 30Hz	   BGR8
    Color	  640x360	@ 30Hz	   YUYV
    Color	  640x360	@ 15Hz	   RGB8
    Color	  640x360	@ 15Hz	   Y16
    Color	  640x360	@ 15Hz	   BGRA8
    Color	  640x360	@ 15Hz	   RGBA8
    Color	  640x360	@ 15Hz	   BGR8
    Color	  640x360	@ 15Hz	   YUYV
    Color	  640x360	@ 6Hz	   RGB8
    Color	  640x360	@ 6Hz	   Y16
    Color	  640x360	@ 6Hz	   BGRA8
    Color	  640x360	@ 6Hz	   RGBA8
    Color	  640x360	@ 6Hz	   BGR8
    Color	  640x360	@ 6Hz	   YUYV
    Color	  424x240	@ 60Hz	   RGB8
    Color	  424x240	@ 60Hz	   Y16
    Color	  424x240	@ 60Hz	   BGRA8
    Color	  424x240	@ 60Hz	   RGBA8
    Color	  424x240	@ 60Hz	   BGR8
    Color	  424x240	@ 60Hz	   YUYV
    Color	  424x240	@ 30Hz	   RGB8
    Color	  424x240	@ 30Hz	   Y16
    Color	  424x240	@ 30Hz	   BGRA8
    Color	  424x240	@ 30Hz	   RGBA8
    Color	  424x240	@ 30Hz	   BGR8
    Color	  424x240	@ 30Hz	   YUYV
    Color	  424x240	@ 15Hz	   RGB8
    Color	  424x240	@ 15Hz	   Y16
    Color	  424x240	@ 15Hz	   BGRA8
    Color	  424x240	@ 15Hz	   RGBA8
    Color	  424x240	@ 15Hz	   BGR8
    Color	  424x240	@ 15Hz	   YUYV
    Color	  424x240	@ 6Hz	   RGB8
    Color	  424x240	@ 6Hz	   Y16
    Color	  424x240	@ 6Hz	   BGRA8
    Color	  424x240	@ 6Hz	   RGBA8
    Color	  424x240	@ 6Hz	   BGR8
    Color	  424x240	@ 6Hz	   YUYV
    Color	  320x240	@ 60Hz	   RGB8
    Color	  320x240	@ 60Hz	   Y16
    Color	  320x240	@ 60Hz	   BGRA8
    Color	  320x240	@ 60Hz	   RGBA8
    Color	  320x240	@ 60Hz	   BGR8
    Color	  320x240	@ 60Hz	   YUYV
    Color	  320x240	@ 30Hz	   RGB8
    Color	  320x240	@ 30Hz	   Y16
    Color	  320x240	@ 30Hz	   BGRA8
    Color	  320x240	@ 30Hz	   RGBA8
    Color	  320x240	@ 30Hz	   BGR8
    Color	  320x240	@ 30Hz	   YUYV
    Color	  320x240	@ 6Hz	   RGB8
    Color	  320x240	@ 6Hz	   Y16
    Color	  320x240	@ 6Hz	   BGRA8
    Color	  320x240	@ 6Hz	   RGBA8
    Color	  320x240	@ 6Hz	   BGR8
    Color	  320x240	@ 6Hz	   YUYV
    Color	  320x180	@ 60Hz	   RGB8
    Color	  320x180	@ 60Hz	   Y16
    Color	  320x180	@ 60Hz	   BGRA8
    Color	  320x180	@ 60Hz	   RGBA8
    Color	  320x180	@ 60Hz	   BGR8
    Color	  320x180	@ 60Hz	   YUYV
    Color	  320x180	@ 30Hz	   RGB8
    Color	  320x180	@ 30Hz	   Y16
    Color	  320x180	@ 30Hz	   BGRA8
    Color	  320x180	@ 30Hz	   RGBA8
    Color	  320x180	@ 30Hz	   BGR8
    Color	  320x180	@ 30Hz	   YUYV
    Color	  320x180	@ 6Hz	   RGB8
    Color	  320x180	@ 6Hz	   Y16
    Color	  320x180	@ 6Hz	   BGRA8
    Color	  320x180	@ 6Hz	   RGBA8
    Color	  320x180	@ 6Hz	   BGR8
    Color	  320x180	@ 6Hz	   YUYV
`

**Comment by MartyG-RealSense** [comment]
Hi @tobiasonkes  I note that your camera has firmware driver version **5.13.0.50** installed.  This is not ideal for use with librealsense SDK version 2.32.1.  This is because firmwares that are 5.12.8.200 or newer recommend SDK version **2.39.0** or newer due to internal changes in the firmware from 5.12.8.200 onwards.  

So for SDK versions before 2.39.0 the firmware version **5.12.7.100** is recommendable, as this was the final version before the internal firmware changes were implemented.

Please also try adding the command **initial_reset:=true** onto the end of your roslaunch instruction to see whether resetting the camera at launch improves the launch's reliability.

Also, if you want to perform a calibration of the camera intrinsics then you should not require ROS to do that, as the **On-Chip Calibration** tool available from the drop-down menu of the 'More' option in the RealSense Viewer side-panel can calibrate camera intrinsics.

![image](https://user-images.githubusercontent.com/41145062/173183927-31b06b77-f6db-431b-89b7-b925ee1eb710.png)

**Comment by tobiasonkes** [comment]
Thank you for you quick response. I was able to update the firmware and kind its solve my probleme. I would like to try out one or two things and then close the issue if I have no new one comming up

**Comment by MartyG-RealSense** [comment]
I'm pleased to hear that you made significant progress.  Good luck with your remaining tests!

**Comment by tobiasonkes** [comment]
Right now I have the issue 
`[ WARN] [1654948361.792477095]: Frame metadata isn't available! (frame_timestamp_domain = RS2_TIMESTAMP_DOMAIN_SYSTEM_TIME)
 11/06 11:52:42,076 WARNING [140368093886208] (ds5-timestamp.cpp:76) UVC metadata payloads not available. Please refer to the installation chapter for details.
`
Do you have any Idea why this error message is shown?

**Comment by MartyG-RealSense** [comment]
What method did you use to install the librealsense SDK, please?  If the SDK was built from source code but the kernel was not patched then the SDK would be missing support for hardware metadata.

If librealsense was installed from Debian packages or built from source code with the **RSUSB backend** method then hardware metadata support should be automatically included.

**Comment by tobiasonkes** [comment]
ok actually I use an docker container to run open p track. So I don't know it exactly. Like I understood is that if I run the cam now with the correct firmware it should working for all what openPtrack supose to run. 

https://github.com/IntelRealSense/realsense-ros/issues/803

In this issue I understand that I can ignore it right?

**Comment by MartyG-RealSense** [comment]
https://github.com/IntelRealSense/realsense-ros/issues/803 used to be true but support for the publishing of metadata topics was added recently in the RealSense ROS wrapper.  Hpwever, since you are using the old wrapper version 2.2.12, it would still be true that the wrapper that you are using was not publishing metadata topics.

Even before then though, having accurate metadata was important to some RealSense ROS users.  It depends whether metadata is important to your particular project.

**Comment by MartyG-RealSense** [comment]
Hi @tobiasonkes  Do you require further assistance with this case, please?  Thanks!

**Comment by tobiasonkes** [comment]
Thanks a lot now it working fine :). Just have been on Vocations recently.
Just want to ask if you have experience with openPtrack? Because They don't reply to my messages.

**Comment by MartyG-RealSense** [comment]
I have not had experience with it personally but there are some RealSense related discussions on their support forum at https://github.com/OpenPTrack/open_ptrack_v2/issues/51 and https://github.com/OpenPTrack/open_ptrack_v2/issues/54

**Comment by MartyG-RealSense** [comment]
Hi @tobiasonkes  As your project is working, do you require further assistance please or can this case be closed?  Thanks!
