### ISSUE TITLE
SLAM with L515: map not appearing,

### ISSUE THREAD

**Issue by sandilyasg** [realsenseai/realsense-ros#2378]
I am trying to follow the "[SLAM with RealSense™ D435i camera on ROS](https://github.com/IntelRealSense/realsense-ros/wiki/SLAM-with-D435i)" but with a L515. I followed the instructions exactly; RViz opens up but I do not see the SLAM map. I am running ROS noetic Ubuntu 20.04. What is the process for using the SLAM program on a L515 instead of D435i camera? Please help urgently, I have also included the log files.

[camera-realsense2_camera-2-stdout.log](https://github.com/IntelRealSense/realsense-ros/files/8896608/camera-realsense2_camera-2-stdout.log)
[ImuFilter-3-stdout.log](https://github.com/IntelRealSense/realsense-ros/files/8896609/ImuFilter-3-stdout.log)
[roslaunch-sandilya-XPS-13-9380-21142.log](https://github.com/IntelRealSense/realsense-ros/files/8896610/roslaunch-sandilya-XPS-13-9380-21142.log)
.

**Comment by MartyG-RealSense** [comment]
Hi @hunterlineage21  May I first confirm that you have enabled accel and gyro in your roslaunch instruction by adding the commands **enable_accel:=true enable_gyro:=true** to it.  The IMU topics were disabled by default in the RealSense ROS wrapper  some time after Intel's D435i SLAM guide was published.

`roslaunch realsense2_camera opensource_tracking.launch enable_accel:=true enable_gyro:=true`

Please also try unplugging the micro-sized end of the USB cable from the base of the L515 camera, turning the connector around the other way and re-inserting it into the base of the camera (USB Type-C cables are two way insertion at the micro-sized end).  Some L515 cameras can perform better when the connector is inserted in a particular one of the two available orientations.  If this does not make a difference to your launch problems then put the connector back to its original insertion direction.

**Comment by sandilyasg** [comment]
Thank you for getting back @MartyG-RealSense . I tried the command you suggested and also reversing the direction of the USB micro connector. The problem is that the map is showing now, but this time it shoots off to infinity, even though the camera is perfectly still. The camera frame in the map rotates and moves on its own further and further away from the origin such that it is not visible anymore, and a SLAM map is not being created.

**Comment by MartyG-RealSense** [comment]
Has your L515's IMU been calibrated with the Python IMU calibration tool at the link below?

https://dev.intelrealsense.com/docs/imu-calibration-tool-for-intel-realsense-depth-camera

The IMU component used in RealSense cameras does not have internal hardware calibration and must be calibrated with software.  An uncalibrated IMU may have a Y accel value that keeps changing even when the camera is stationary on a flat surface.

**Comment by sandilyasg** [comment]
Yes @MartyG-RealSense, I tried calibrating it and the problem still persists. Please help!

**Comment by MartyG-RealSense** [comment]
There is a RealSense ROS L515 SLAM project at the link below.

https://github.com/wh200720041/MMS_SLAM

It is a **Semantic SLAM** project, which usually means that it is SLAM that does not require use of the IMU.  In that project, they are using the **rs_camera.launch** launch file with a pointcloud filter enabled. 

**roslaunch realsense2_camera rs_camera.launch filters:=pointcloud**

It looks as though they are installing a package called **hector trajectory server** to visualize the trajectory in RViz.

http://wiki.ros.org/hector_trajectory_server

![image](https://user-images.githubusercontent.com/41145062/174037489-8f342dbf-c226-45ad-9663-756ae0b579bf.png)

With the rs_camera launch file, RViz would be opened with the command **rosrun rviz rviz**

*********************

If you would prefer to continue using the D435i SLAM guide method, could you provide answers to the following questions please.

1.  Your log indicates that you are using 'XPS-13' as your computer.  Is that the Dell XPS 13 laptop PC, please?

3.  Which librealsense SDK and RealSense ROS wrapper versions are you using?

**Comment by sandilyasg** [comment]
@MartyG-RealSense thank you for showing the Semantic SLAM resource. Majority of the code in that repository is written in C++ and I am trying to understand and use the algorithms in python, so I still want to try and use the D435i SLAM guide method.
Answers to your questions:
1. Yes I am using Dell XPS 13 laptop
2. I am using pyrealsense2 2.47.0.3313. How do I check what is the version of the RealSense ROS wrapper from my linux command line?

I am also trying to save the SLAM map point cloud such that I can replay it using RViz. I notice that most repositories are using a rosbag .bag file to save the point cloud and view it again in RViz. How do I achieve this using the D435i SLAM guide method, or another method for my L515?

Update: I looked at [this link ](https://support.intelrealsense.com/hc/en-us/community/posts/4407076814483-Extract-point-clouds-from-BAG-file-?page=1#community_comment_7053368228755) and I am having an issue with playing the recorded rosbag file. 

Also, for the question you asked: "If you would like to use a script to generate a point cloud from the bag in the RealSense SDK, which programming language would you be using (C++, Python, C#, etc)," I would like to try using C++ and Python. What options do I have? Thank you.

**Comment by MartyG-RealSense** [comment]
1.  Thanks very much for the confirmation of your computer model.

2.  The ROS wrapper version that you are using is displayed in the roslaunch log, when it is working correctly.  Please see if you can display it when using the rs_camera launch file.

![image](https://user-images.githubusercontent.com/41145062/174293723-533f62ac-2a57-4eac-9a6c-59caa77c1613.png)

I replied at your recorded rosbag link about the **Failed to meet update rate** error.

In regard to C++ and Python scripts for generating a pointcloud from a bag, you could use the official pointcloud example programs and set them to use a bag file as the data source instead of a live camera.

**C++**
https://github.com/IntelRealSense/librealsense/blob/master/examples/pointcloud/rs-pointcloud.cpp

**Python**
https://github.com/IntelRealSense/librealsense/blob/master/wrappers/python/examples/opencv_pointcloud_viewer.py

***********

You can set a bag as the data source by placing the **cfg.enable_device_from_file** instruction on the line before the pipeline start instruction.

**C++**
```
rs2::config cfg;
cfg.enable_device_from_file("test.bag");
pipe.start(cfg); 
```

**Python**
```
pipe = rs.pipeline()
cfg = rs.config()
cfg.enable_device_from_file("test.bag");
pipe.start(cfg)
```

**Comment by sandilyasg** [comment]
The ROS realsense version that I am using is: [ INFO] [1655493100.229075284]: **RealSense ROS v2.3.2**
Thank you for showing the C++ and Python resources. I will try them and revert. I was also wondering if you could help me with how to save the bag file using a Python script that is using OpenCV or Open3D to create a real time slam map? As in, is there a way to save the point cloud data coming from the L515, running from a Python script, in bag format?

Update: I tried the c++ and python examples and they worked perfectly (of course). I modified a copy of the python script for my use.

Important question: If possible, I am trying to avoid using ROS for my SLAM using L515 due to the heavy computational load. I found an easy-to-use SLAM package that does not need ROS called [BreezySLAM](https://github.com/simondlevy/BreezySLAM). While support exists for other LiDAR sensors, there seems to be none for any realsense cameras. Specifically, I am confused by how to create a a constructor that accepts Lidar parameters from the L515 camera in python. How do I solve this problem so that I can use my L515 with BreezySLAM? Thank you!

**Comment by MartyG-RealSense** [comment]
It looks as though the creator of BreezySLAM wrote scripts for specific lidar device models and placed them in the **examples** sub-folder of BreezySLAM.

https://github.com/simondlevy/BreezySLAM/tree/master/examples

![image](https://user-images.githubusercontent.com/41145062/174430954-31bb14df-883a-4f0e-a49e-6ba1a73aa487.png)

So you would presumably have to create a .py script file similar to the highlighted ones to add L515 support if it were possible to do so.  

As a possible alternative to BreezySLAM, the **RTABMAP** SLAM tool has a standalone version which can be used without ROS and has been demonstrated as working with L515.

http://introlab.github.io/rtabmap/

https://www.youtube.com/watch?v=e_KS3RHRwSE

There is also a ROS-based SLAM solution specifically for L515 here:

https://github.com/wh200720041/SSL_SLAM

**Comment by sandilyasg** [comment]
Thank you for the information. How do I use the [ROS-based SLAM solution specifically for L515](https://github.com/wh200720041/SSL_SLAM) with python? Would I have to create a new ros node that can let me create the SLAM map in python? I will also try creating a .py script for the BreezySLAM.

Going back to the "[SLAM with RealSense™ D435i camera on ROS](https://github.com/IntelRealSense/realsense-ros/wiki/SLAM-with-D435i)" problem, my IMU is calibrated and the map is showing now, but it keeps rotating away even though the L515 is stationary.

**Comment by MartyG-RealSense** [comment]
There is a Python version of SSL_SLAM worked on by the same developer at the link below.

https://github.com/wh200720041/MMS_SLAM

**Comment by MartyG-RealSense** [comment]
Hi @hunterlineage21  Do you require further assistance with this case, please?  Thanks!
