### ISSUE TITLE
realsense-ros automated rgb_camera settings

### ISSUE THREAD

**Issue by nath-partha** [realsenseai/realsense-ros#2389]
Is it possible to set autoexposure, gain, white balance and other rgb_camera settings for a camera[D435] color stream while executing a launch file or any similar single command method?

To note:
- the method needs to be generalisable to a multicamera and multiuse scenario so setting it manually for every session and every camera in rqt reconfigure isnt ideal

- something like a config file for rqt_reconfigure or a shell script to set the parameters automatically might be okay

Usecase:
- for dataset recording in multiview scenarios we would prefer to maintain uniform color and saturation over the stitched pointclouds and scene

Any and all suggestions welcome. 

TIA

**Comment by nath-partha** [comment]
I am able to save a config file of one rgb camera settings in rqt_reconfig and load it for all the other cameras, but we would prefer a more automated solution

**Comment by MartyG-RealSense** [comment]
Hi @parthapn98  Loading a **.yaml** configuration file from the launch file or the launch instruction that contains your settings may fit your needs.  Information about doing so can be found at the links below.

**ROS1**

https://roboticsbackend.com/ros-param-yaml-format/

**ROS2**

https://github.com/IntelRealSense/realsense-ros/issues/1640

https://github.com/IntelRealSense/realsense-ros/issues/2043#issuecomment-904345068

**Comment by nath-partha** [comment]
Hi @MartyG-RealSense 

Thanks for the quick reply,
Basically the following screenshot contains the params i want to modify or fix
![image](https://user-images.githubusercontent.com/77120537/175038546-7b9f51a8-fc58-4797-a8c1-4dceabdcdb7b.png)

However i donot see this params in the nodelet.launch.xml file
or even if I rosparam dump or rosparam list my active params.

Could you tell me where they should be set in the .xml file, and is it okay to add them by hand even if they are not present in the nodelet.xml file.

I can see the stereo module settings in the .xml but not the rgb_camera

[dumps.yaml.txt](https://github.com/IntelRealSense/realsense-ros/files/8958040/dumps.yaml.txt)
[nodelet.launch.xml.txt](https://github.com/IntelRealSense/realsense-ros/files/8958042/nodelet.launch.xml.txt)
[params.txt](https://github.com/IntelRealSense/realsense-ros/files/8958043/params.txt)

**Comment by MartyG-RealSense** [comment]
It sounds as though configuring the RGB settings in the launch file by adding them as **rosparam** instructions and not doing anything to the **nodelet.launch.xml** file contents may meet your needs.

For example, code for setting an RGB auto-exposure region of interest (ROI) is:

```
<rosparam>
  /camera/rgb_camera/auto_exposure_roi/left: 30
  /camera/rgb_camera/auto_exposure_roi/right: 350
</rosparam>
```

So once you know that any RGB-related option is likely to start with **/camera/rgb_camera/** then it becomes easier to define the list of RGB settings that you want to configure in the launch file and their values.

What makes things easier is that the rosparam parameter name should be the same as the rqt_reconfigure parameter name.  So if you look at the interface and see that the RGB control for auto-exposure is 'enable_auto_exposure' then you would use the same name for the rosparam equivalent.

```
<rosparam>
 /camera/rgb_camera/enable_auto_exposure: false
</rosparam>
```

Another example for auto_exposure_priority:

```
<rosparam>
 /camera/rgb_camera/auto_exposure_priority: false
</rosparam>
```

**********

You also have the option of not editing the launch file and instead setting the parameters in the roslaunch instruction (again using the same parameter names such as **enable_auto_exposure** and **auto_exposure_priority**, though it will make the roslaunch instruction very long.

**Comment by nath-partha** [comment]
Thank you!, we managed to get it working following your code

**Comment by MartyG-RealSense** [comment]
That's excellent news, @parthapn98 - thanks very much for the update!
