### ISSUE TITLE
Setting ROS_MASTER_URI crashes process

### ISSUE THREAD

**Issue by MrOCW** [realsenseai/realsense-ros#2395]
Hi,

librealsense v2.50.0
Realsense-ROS v2.3.2

I am running D455 on a Jetson Xavier AGX container using ROS Melodic. It runs fine when using the default localhost:11311. But when I set ROS_MASTER_URI=http://192.xxx.xxx.xxx, the node crashes a few seconds after starting.

**Comment by MartyG-RealSense** [comment]
Hi @MrOCW  Can you confirm whether you are using two computers?  

If you are then does it make a difference if you create two separate ROS terminals and launch **roscore** in one terminal and input the following command in the second terminal, similar to Intel's guide at the link below?

`export ROS_MASTER_URI=http://192.xxx.xxx.xxx roslaunch realsense2_camera rs_camera.launch`

https://github.com/IntelRealSense/realsense-ros/wiki/showcase-of-using-3-cameras-in-2-machines#terminal-1

**Comment by MartyG-RealSense** [comment]
Hi @MrOCW  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
