### ISSUE TITLE
What is the sensor_msgs::image_encodings::  of topic /camera/depth/image_rect_raw

### ISSUE THREAD

**Issue by JACKLiuDay** [realsenseai/realsense-ros#2402]
Hi, thank your for your great work of realsense. I want to convert /camera/depth/image_rect_raw to cv::Mat. So I need to know the sensor_msg::image_encodings.
like this      cv_ptr = cv_bridge::toCvCopy(msg, sensor_msgs::image_encodings::xxx);

**Comment by MartyG-RealSense** [comment]
Hi @JACKLiuDay  At https://github.com/IntelRealSense/realsense-ros/issues/436 a RealSense ROS user wrote a subscriber that reads messages from /camera/depth/image_rect_raw and then converts and displays them using cv_bridge. 

Another RealSense ROS user wrote their own conversion and display script in C++ at the link below.

https://answers.ros.org/question/299888/using-a-depth-map/

Are these references helpful to you, please?

**Comment by JACKLiuDay** [comment]
> Hi @JACKLiuDay At #436 a RealSense ROS user wrote a subscriber that reads messages from /camera/depth/image_rect_raw and then converts and displays them using cv_bridge.
> 
> Another RealSense ROS user wrote their own conversion and display script in C++ at the link below.
> 
> https://answers.ros.org/question/299888/using-a-depth-map/
> 
> Are these references helpful to you, please?

Wow, it helps me a lot. The encodings is sensor_msgs::image_encodings::TYPE_16UC1. Thank you so much.

**Comment by MartyG-RealSense** [comment]
You are very welcome.  I'm pleased that I could be of help.  :)
