### ISSUE TITLE
D405 Color stream

### ISSUE THREAD

**Issue by levmarki** [realsenseai/realsense-ros#2403]
Hello all,

I'm new with the D405 (worked before on D435 for a long time).
How can I get through ROS wrapper (I have Dashing right now) get the **color** stream from both cameras?
As I see it now, I can get only one camera **color** stream aside both camera "infra" stream, that comes - I guess - from the same cameras, but afrer RGB2Gray conversion.

Thank you in advance!

**Comment by MartyG-RealSense** [comment]
Hi @levmarki  RealSense camera models that support color from the infrared sensor (D405, D415, D455) only provide it on the left sensor, not both left and right.

**Comment by levmarki** [comment]
> Hi @levmarki  RealSense camera models that support color from the infrared sensor (D405, D415, D455) only provide it on the left sensor, not both left and right.

Thank you @MartyG-RealSense !
Is there some way to get it **not** using ROS? Through pyrealsense or some other way?
And another question, if I use only D401 cameras module, can I connect it through MIPI to Rpi/Jetson and have the both cameras together?

Thank you once more!

**Comment by MartyG-RealSense** [comment]
Color from right infrared is also not supported in the librealsense SDK and is therefore unavailable in pyrealsense2.

 Access to the camera sensors through MIPI is not supported at this time, unfortunately.

**Comment by levmarki** [comment]
> Color from right infrared is also not supported in the librealsense SDK and is therefore unavailable in pyrealsense2.
> 
>  Access to the camera sensors through MIPI is not supported at this time, unfortunately.

Ok, understood, thank you.

It this on plan to provide the access to both cameras in the future?
By the way, does the right camera have color channel at all?

**Comment by MartyG-RealSense** [comment]
I will enquire to my Intel RealSense colleagues about your question regarding the possibility of future support of both left and right color from infrared.

The right sensor has no RGB color.  It is possible to stream RGB8 from left infrared and RGB8 RGB on the D405, though they are the same viewpoint rather than one of the images being offset from the left infrared sensor position like Infra2 is. This is because the D405 does not have a separate RGB sensor component and RGB is instead provided from the depth sensor.

![image](https://user-images.githubusercontent.com/41145062/177934853-8f72cd7e-1542-4e30-af51-bc746ea2a103.png)

**Comment by levmarki** [comment]
Thank you, @MartyG-RealSense !
Looking forward for your's colleagues' answer.

**Comment by MartyG-RealSense** [comment]
Hi again @levmarki  My colleagues have informed me that there are no plans to add support for color from Infrared 2.  Thanks very much for your patience and understanding!

**Comment by levmarki** [comment]
Thank you, @MartyG-RealSense!
It was very informative and helpful!

**Comment by Zephyr69** [comment]
Very useful and important note on the D405!

**Comment by gcaccia1** [comment]
> Color from right infrared is also not supported in the librealsense SDK and is therefore unavailable in pyrealsense2.
> 
> Access to the camera sensors through MIPI is not supported at this time, unfortunately.

@MartyG-RealSense do you have any update on the possibility to access the D401 sensors through mipi?
Thanks,
Guido

**Comment by MartyG-RealSense** [comment]
Hi @gcaccia1  The only RealSense camera model that supports MIPI is the D457.

https://store.intelrealsense.com/buy-intel-realsense-depth-camera-d457.html
