### ISSUE TITLE
Out of Resources - even at 6fps with- happens only when point cloud turned on

### ISSUE THREAD

**Issue by altairve** [realsenseai/realsense-ros#2413]
Logs :: process[camera/realsense2_camera_manager-1]: started with pid [87427]
process[camera/realsense2_camera-2]: started with pid [87428]
[ INFO] [1657796441.533641795]: Initializing nodelet with 16 worker threads.
[ INFO] [1657796441.593392914]: RealSense ROS v2.3.2
[ INFO] [1657796441.593413879]: Built with LibRealSense v2.50.0
[ INFO] [1657796441.593424283]: Running with LibRealSense v2.50.0
[ INFO] [1657796441.610536917]:  
[ INFO] [1657796441.854735455]: Device with serial number 947122071216 was found.

[ INFO] [1657796441.854769987]: Device with physical ID 2-3-10 was found.
[ INFO] [1657796441.854781810]: Device with name Intel RealSense D435I was found.
[ INFO] [1657796441.855248090]: Device with port number 2-3 was found.
[ INFO] [1657796441.855277361]: Device USB type: 3.2
[ INFO] [1657796441.856545296]: getParameters...
[ INFO] [1657796441.877630392]: setupDevice...
 14/07 16:30:44,870 WARNING [139759328114432] (messenger-libusb.cpp:42) control_transfer returned error, index: 300, error: Resource temporarily unavailable, number: b
[ INFO] [1657796445.176884496]: JSON file is loaded! (/home/mowito/ros1_ws/src/vision_executive/config/middensitypreset.json)
[ INFO] [1657796445.176923885]: ROS Node Namespace: camera
[ INFO] [1657796445.176935168]: Device Name: Intel RealSense D435I
[ INFO] [1657796445.176942617]: Device Serial No: 947122071216
[ INFO] [1657796445.176950174]: Device physical port: 2-3-10
[ INFO] [1657796445.176958824]: Device FW version: 05.13.00.50
[ INFO] [1657796445.176968764]: Device Product ID: 0x0B3A
[ INFO] [1657796445.176980818]: Enable PointCloud: On
[ INFO] [1657796445.176994323]: Align Depth: On
[ INFO] [1657796445.177007244]: Sync Mode: On
[ INFO] [1657796445.177045316]: Device Sensors: 
[ INFO] [1657796445.257426993]: Stereo Module was found.
[ INFO] [1657796445.264798547]: RGB Camera was found.
[ INFO] [1657796445.264917043]: Motion Module was found.
[ INFO] [1657796445.264939103]: Add Filter: spatial
[ INFO] [1657796445.265287678]: Add Filter: temporal
[ INFO] [1657796445.265599576]: Add Filter: decimation
[ INFO] [1657796445.266071548]: Add Filter: pointcloud
[ INFO] [1657796445.266431653]: num_filters: 5
[ INFO] [1657796445.266448586]: Setting Dynamic reconfig parameters.
 14/07 16:30:46,142 WARNING [139759328114432] (messenger-libusb.cpp:42) control_transfer returned error, index: 300, error: Resource temporarily unavailable, number: b
[ INFO] [1657796448.341752896]: Done Setting Dynamic reconfig parameters.
[ INFO] [1657796448.342160021]: depth stream is enabled - width: 848, height: 480, fps: 6, Format: Z16
[ INFO] [1657796448.342578116]: color stream is enabled - width: 848, height: 480, fps: 6, Format: RGB8
[ INFO] [1657796448.343532219]: setupPublishers...
[ INFO] [1657796448.345171498]: Expected frequency for depth = 6.00000
[ INFO] [1657796448.366164745]: Expected frequency for color = 6.00000
[ INFO] [1657796448.379741623]: Expected frequency for aligned_depth_to_color = 6.00000
[ INFO] [1657796448.395235891]: setupStreams...
 14/07 16:30:48,542 WARNING [139759328114432] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
[ INFO] [1657796448.592957093]: SELECTED BASE:Depth, 0
[ INFO] [1657796448.597161149]: RealSense Node Is Up!
 14/07 16:30:48,735 WARNING [139759328114432] (messenger-libusb.cpp:42) control_transfer returned error, index: 300, error: Resource temporarily unavailable, number: b
[ WARN] [1657796448.935061043]: 
 14/07 16:30:48,935 WARNING [139759328114432] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 14/07 16:30:48,986 WARNING [139759328114432] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 14/07 16:30:49,036 WARNING [139759328114432] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 14/07 16:30:49,086 WARNING [139759328114432] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 14/07 16:30:49,137 WARNING [139759328114432] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 14/07 16:30:49,187 WARNING [139759328114432] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 14/07 16:30:49,238 WARNING [139759328114432] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 14/07 16:30:49,288 WARNING [139759328114432] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 14/07 16:30:49,338 WARNING [139759328114432] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 14/07 16:30:49,389 WARNING [139759328114432] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 14/07 16:30:49,439 WARNING [139759328114432] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
[ERROR] [1657796449.495429395]: An error has occurred during frame callback: Error occured during execution of the processing block! See the log for more info
 14/07 16:30:49,495 ERROR [139758554568448] (synthetic-stream.cpp:48) Exception was thrown during callback: Out of frame resources!
[ERROR] [1657796449.497562553]: An error has occurred during frame callback: Error occured during execution of the processing block! See the log for more info
 14/07 16:30:49,496 WARNING [139759328114432] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 14/07 16:30:49,497 ERROR [139758554568448] (synthetic-stream.cpp:48) Exception was thrown during callback: Out of frame resources!
 14/07 16:30:49,546 WARNING [139759328114432] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
[ERROR] [1657796449.616830619]: An error has occurred during frame callback: Error occured during execution of the processing block! See the log for more info
 14/07 16:30:49,616 ERROR [139758854125312] (synthetic-stream.cpp:48) Exception was thrown during callback: Out of frame resources!
[ERROR] [1657796449.783746682]: An error has occurred during frame callback: Error occured during execution of the processing block! See the log for more info
 14/07 16:30:49,783 ERROR [139758854125312] (synthetic-stream.cpp:48) Exception was thrown during callback: Out of frame resources!
[ERROR] [1657796449.950769674]: An error has occurred during frame callback: Error occured during execution of the processing block! See the log for more info
 14/07 16:30:49,950 ERROR [139758854125312] (synthetic-stream.cpp:48) Exception was thrown during callback: Out of frame resources!
[ERROR] [1657796450.117804575]: An error has occurred during frame callback: Error occured during execution of the processing block! See the log for more info
 14/07 16:30:50,117 ERROR [139758854125312] (synthetic-stream.cpp:48) Exception was thrown during callback: Out of frame resources!
[ERROR] [1657796450.284802354]: An error has occurred during frame callback: Error occured during execution of the processing block! See the log for more info
 14/07 16:30:50,284 ERROR [139758854125312] (synthetic-stream.cpp:48) Exception was thrown during callback: Out of frame resources!
[ERROR] [1657796450.451869935]: An error has occurred during frame callback: Error occured during execution of the processing block! See the log for more info
 14/07 16:30:50,451 ERROR [139758854125312] (synthetic-stream.cpp:48) Exception was thrown during callback: Out of frame resources!
[ERROR] [1657796450.618883067]: An error has occurred during frame callback: Error occured during execution of the processing block! See the log for more info
 14/07 16:30:50,618 ERROR [139758854125312] (synthetic-stream.cpp:48) Exception was thrown during callback: Out of frame resources!
[ERROR] [1657796450.785903534]: An error has occurred during frame callback: Error occured during execution of the processing block! See the log for more info
 14/07 16:30:50,785 ERROR [139758854125312] (synthetic-stream.cpp:48) Exception was thrown during callback:

**Comment by altairve** [comment]
@MartyG-RealSense  Hey can you please provide some help.

**Comment by MartyG-RealSense** [comment]
Hi @altairve  Thanks for your question.

1.  Does the number of warning messages reduce if you add **initial_reset:=true** to your roslaunch instruction if you are not using it already?  For example:

`roslaunch realsense2_camera rs_camera.launch initial_reset:=true`

2.  Which computer / computing device are you using (Raspberry Pi, Nvidia Jetson, desktop / laptop PC, etc).  

3.  Do the warnings still occur if 15 FPS is used instead of 6

**Comment by MartyG-RealSense** [comment]
Hi @altairve  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.

**Comment by BryanBetancurUR** [comment]
I'm having the same issue.
All topics work fine for a few seconds, later it shows `Exception was thrown during callback: Out of frame resources!` and topics stop publishing.
Do you know how can I fix it?

Required Info |  
-- | --
Camera Model | D435i
Operating System & Version | Jetson Linux with Jetpack 5.0.2 Ubuntu 20.04
Kernel Version (Linux Only) | 5.10.104-tegra
Platform | Jetson Orin
Device FW Version | 05.13.00.50
LibRealSense Version |  v2.51.1
RealSense ROS | v4.51.1
ros version | Galactic

Launch Params |  
-- | --
initial_reset | True
align_depth.enable | True
rgb_camera.profile |  '1280x720x30'
depth_module.profile | '1280x720x30'
pointcloud.enable | True,
Other Params | Default

**Comment by MartyG-RealSense** [comment]
Hi @BryanBetancurUR  There are known issues with the RealSense ROS wrapper regarding enabling pointcloud or align on Jetson boards specifically (desktop / laptop PCs are not affected by the issue).  If you do not enable pointcloud and align and the streams are published normally then you are likely affected by this Jetson-specific issue.

Is there an improvement in performance if the pointcloud filter is enabled and align is disabled?  When depth and RGB are enabled then the pointcloud filter will map RGB color onto the depth points anyway without having to enable alignment.

Information about installing librealsense and RealSense ROS for Orin and JetPack 5 can be found at https://github.com/IntelRealSense/realsense-ros/issues/2575#issuecomment-1381486539

Whilst the wrapper can work with JetPack 5 for streaming depth and color, JetPack 5.0.2 support will not be officially introduced until the next version of librealsense (likely numbered 2.54.0).

**Comment by BryanBetancurUR** [comment]
Hi Marty, Thanks for your quick response, unfortunately disabling the align and activating the poincloud filter still shows the same error and the topics do not publish. I use this new version for the utility to turn the stream on and off in order to save hardware resources but I think I'll have to go back to the old version. Thank you.

**Comment by MartyG-RealSense** [comment]
You are very welcome.
