### ISSUE TITLE
version

### ISSUE THREAD

**Issue by cvirxsc** [realsenseai/realsense-ros#2414]
Excuse me, is there a package that releases the realsense 2-camera of humble?

**Comment by MartyG-RealSense** [comment]
Hi @cvirxsc  Official support in the RealSense ROS2 wrapper for Humble is being worked on.  In the meantime, a RealSense ROS user recently shared at https://github.com/IntelRealSense/librealsense/issues/10439#issuecomment-1179519891 a method for patching the makefile to make the wrapper compatible with Humble.

**Edit:** The RealSense ROS wrapper development team added Humble support when building the ros2_beta wrapper version 4.0.4 from source code for Ubuntu 22.04 (Jammy).  There is not yet an option for building for Humble from packages at the time of writing this, though it is on the future roadmap.

**Comment by MartyG-RealSense** [comment]
Hi @cvirxsc  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
