### ISSUE TITLE
Python Dig Tutorial on point_cloud_registration not working 

### ISSUE THREAD

**Issue by Fyfth** [realsenseai/realsense-ros#2415]
I was following this tutorial : https://pythondig.com/r/python-package-uses-a-turtlebot-robot-with-an-intel-realsense-di-depth-camera-and-tries-to-create-point-clouds-of-gazebo-environments
I got to this command: rosdep install -i --from-path src --rosdistro $ROS_DISTRO -y
The code errored and said : ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
realsense2_description: Cannot locate rosdep definition for [catkin]
realsense2_camera: Cannot locate rosdep definition for [ddynamic_reconfigure]

I am quite new to this but I know this step is critical to progress down the tutorial. 

Thanks for helping in advance!

**Comment by MartyG-RealSense** [comment]
Hi @Fyfth  The official version of the ROS wrapper instructions for installing the ROS2 wrapper from source code recommend including a **--skip-keys** instruction.

**rosdep install -i --from-path src --rosdistro $_ros_dist --skip-keys=librealsense2 -y**

https://github.com/IntelRealSense/realsense-ros/tree/ros2#step-4-install-dependencies

**Comment by Fyfth** [comment]
Ok thanks I will follow the instructions on the official git repository! thx

**Comment by Fyfth** [comment]
Hello! I entered in the code and re done the tutorial once over but this time with the code provided. It still is not working. 

rosdep install -i --from-path src --rosdistro $_ros_dist --skip-keys=librealsense2 -y
WARNING: given --rosdistro --skip-keys=librealsense2 but ROS_DISTRO is "foxy". Ignoring environment.
WARNING: ROS_PYTHON_VERSION is unset. Defaulting to 3
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
realsense2_description: Cannot locate rosdep definition for [rosunit]
realsense2_camera: Cannot locate rosdep definition for [librealsense2]

Am I missing something? Thx for the patience

**Comment by MartyG-RealSense** [comment]
On another case where this problem occurred, the developer of the ROS wrapper suggested changing $_ros_dist to $ROS_DISTRO 

**rosdep install -i --from-path src --rosdistro $ROS_DISTRO --skip-keys=librealsense2 -y**

**Comment by MartyG-RealSense** [comment]
Hi @Fyfth  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
