### ISSUE TITLE
//// Submitted accidentally by someone else ////

### ISSUE THREAD

**Issue by dawidstezycki** [realsenseai/realsense-ros#242]

**Comment by johngardenier** [comment]
I solved this issue by increasing the depth fps to 30. At 10 fps the point cloud would sometimes be flat like you describe, sometimes it would jump around. Note that a flickering point cloud and depth image is solved by installing the uvcvideo driver kernel patches.

**Comment by ghost** [comment]
Hi John, thanks for your reply.

Both my depth_fps and rgb_fps were already set to 30 by default. I've tried to lower it to 10 fps by changing the arguments in a custom launch file, with no change for the shape of my point cloud.

Apart from that, in the installation instructions of librealsense (http://wiki.ros.org/librealsense#uvcvideo_Driver_Patches),
it says very briefly that a patch to uvcvideo is needed for other cameras than the R200.
Does someone know how I can download/install that patch ? (I've already done the Xenial kernel update as suggested).

Thanks.
