### ISSUE TITLE
`/camera/aligned_depth_to_color/image_raw` not published

### ISSUE THREAD

**Issue by Olimoyo** [realsenseai/realsense-ros#2426]
Hi,

I am running the following example:
`ros2 launch realsense2_camera rs_launch.py align_depth:=true`

The rgb image `/camera/color/image_raw` and the depth image `/camera/depth/image_rect_raw` are both published but not the aligned depth image `/camera/aligned_depth_to_color/image_raw`. 

I am on Ubuntu 20.04 with the kernel `5.14.0-1024-oem`. 

I installed the package using `sudo apt install ros-foxy-realsense2-camera`. 

Does anyone know why this is happening?

Thank you,
Oliver

**Comment by MartyG-RealSense** [comment]
Hi @Olimoyo  Which computer or computing device are you using, please (Raspberry Pi, Nvidia Jetson, desktop / laptop PC, etc)

**Comment by Olimoyo** [comment]
Hi @MartyG-RealSense, I am using a Thinkstation desktop. The realsense works (i.e., produces aligned depth images) with another almost identical desktop except that it has a different slightly bigger GPU and kernel `5.15.0-41-generic`.

**Comment by MartyG-RealSense** [comment]
Kernel versions newer than 5.13 have not been reported as being used with the RealSense SDK up until now, so there is no data about the performance of kernel versions > 5.13 with the SDK at the time of writing this.   An unofficial test patch that adds support for kernels 5.13 and 5.15 was recently released though at https://github.com/IntelRealSense/librealsense/issues/10439#issuecomment-1171965106

It is notable that the patch skips kernel 5.14.

**Comment by Olimoyo** [comment]
That's very helpful! I am going to try and test with kernel 5.15 and report back.

**Comment by Olimoyo** [comment]
I changed the kernel and that alone didn't fix it, but building from source did.

**Comment by MartyG-RealSense** [comment]
That's excellent to hear that you were successful, @Olimoyo - thanks very much for the update!

**Comment by omgaikwad08** [comment]
> That's very helpful! I am going to try and test with kernel 5.15 and report back.



> I changed the kernel and that alone didn't fix it, but building from source did.

Hi, I am facing exactly the same issue, can you please elaborate the procedure you followed to fix it.

I would really appreciate it.

Thanks,
Om
