### ISSUE TITLE
color_fps problem.

### ISSUE THREAD

**Issue by Janebek** [realsenseai/realsense-ros#2435]
Hi ! @MartyG-RealSense 

I'm trying to chang the color fps of my D435i using the command **" color_fps:= num "** , but I can not change it , it's default is 15 , and I can change it to 30 , but other numbers seem do not fit into this system . (I test them with rostopic hz)

I want to change it to 10fps , how can I do this ? 

Really looking forward to your reply! Much thanks!

**Comment by MartyG-RealSense** [comment]
Hi @Janebek  The data sheet document for the 400 Series cameras states that the FPS speeds that are supported for RGB on D435i are 6, 15 and 30, and also 60 if using 960x540 resolution or less (such as 848x480).

https://dev.intelrealsense.com/docs/intel-realsense-d400-series-product-family-datasheet

If you require.a specific speed in ROS that is not officially supported by a RealSense camera then you could investigate the possibility of achieving it with a **rate**, as described in the link below.

https://roboticsbackend.com/ros-rate-roscpy-roscpp/

**Comment by Janebek** [comment]
Thank you! I got it.

**Comment by MartyG-RealSense** [comment]
You are very welcome, @Janebek - thanks very much for the update!
