### ISSUE TITLE
How to convert depth image to laser scan in ros foxy?

### ISSUE THREAD

**Issue by pannatorn6395** [realsenseai/realsense-ros#2440]

**Comment by MartyG-RealSense** [comment]
Hi @pannatorn6395  Have you investigated using the ROS2 Foxy branch of **depthimage_to_laserscan** to convert a depth image to laser scan, please?

https://github.com/ros-perception/depthimage_to_laserscan/tree/foxy-devel

**Comment by pannatorn6395** [comment]
yes, @MartyG-RealSense I used it already but I don't know why depth image can't publish to laser scan and I can't change topic /depth.would you recommend, please
![image](https://user-images.githubusercontent.com/81004343/183118690-b848666c-e4e8-4776-830c-4cef52e967f8.png)

**Comment by MartyG-RealSense** [comment]
I have not personally used depthimage_to_laserscan, though in a past case about it I provided the following information regarding guidance for getting it working.

*********

If you have not been able to launch depthimage_to_laserscan, a guide in the link below for doing so with D435 and the RealSense ROS wrapper may be helpful.

https://programmersought.com/article/62234275154/

If you are able to launch it successfully, the RealSense ROS forum link at https://github.com/IntelRealSense/realsense-ros/issues/510 discusses use of depthimage_to_laserscan for mapping with D435.

***********

The original discussions about depthimage_to_laserscan that the above information originated from are at https://github.com/IntelRealSense/librealsense/issues/9272 and https://github.com/IntelRealSense/librealsense/issues/9294

**Comment by MartyG-RealSense** [comment]
Hi @pannatorn6395  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
