### ISSUE TITLE
Can't See\Access nearly any camera topics with ROS

### ISSUE THREAD

**Issue by DanielZamanski** [realsenseai/realsense-ros#2441]
I have installed both the SDK and the ROS-wrapper according to your support manuals. While I haven't gotten any error messages during the installation process and can view the camera's Input fine using the realsense-viewer software
![realSense Viewer](https://user-images.githubusercontent.com/101630887/183259337-62fe8467-326b-4c29-8ef2-ad7180ef992a.jpg)

, I'm running into trouble trying to run it via ROS.
When running the command 'roslaunch realsense2_camera rs_camera.launch' I get a very limited amount of topics when using 'rostopic list', with no camera information and no image.
![rostopic list](https://user-images.githubusercontent.com/101630887/183259358-4c20815f-9cda-4b19-9147-64d755f7739e.jpg)

Neither Rviz nor rqt_image_view detect them as well.
![rqt_ImageView](https://user-images.githubusercontent.com/101630887/183259368-472aa2da-2059-4f02-a7c1-dc0b66e4914b.jpg)
![rviz](https://user-images.githubusercontent.com/101630887/183259374-3c785084-88b1-44a2-8f16-bff604457c80.jpg)

 I've tried launching through different .launch files within the folder and while the results vary slightly I still get no image and little to no information. I've tried updating the drivers,re-installing and installing in a clean workspace and the problems persist. Thank you for your help.

**Comment by MartyG-RealSense** [comment]
Hi @DanielZamanski   Please try launching with the instruction below.

**roslaunch realsense2_camera rs_camera.launch enable_gyro:=true enable_accel:=true enable_fisheye1:=true enable_fisheye2:=true enable_pose:=true**

**Comment by DanielZamanski** [comment]
> Hi @DanielZamanski Please try launching with the instruction below.
> 
> **roslaunch realsense2_camera rs_camera.launch enable_gyro:=true enable_accel:=true enable_fisheye1:=true enable_fisheye2:=true enable_pose:=true**


Thank you for the fast response!
I've tried it, I now get the following warnings when running:
![roslaunch](https://user-images.githubusercontent.com/101630887/183402977-5b9e106d-ced4-453c-ab03-8f01d3d97142.png)

and while I do get more topics now, it still doesnt include most of the topics mentioned on the camera's github page and there's still no camera and image topic
![rostopiclist 2](https://user-images.githubusercontent.com/101630887/183403143-a66fe43c-0466-406e-89d7-264ab02103cf.png)

Also, when adding the new topics to RVIZ i get "Status:Error":
![rviz](https://user-images.githubusercontent.com/101630887/183403400-23396238-844c-4480-92c1-d8645b68af26.png)

**Comment by MartyG-RealSense** [comment]
There are some topics in the ROS wrapper documentation that you will not be able to obtain because a T265 does not have built-in depth sensing like the RealSense 400 Series models do.  It is intended that the T265 is used primarily for tracking and paired with a 400 Series camera near it (such as both on a mount together) if depth sensing is required.  

The topics that a T265 on its own can publish in the ROS wrapper are listed at the link below.

https://dev.intelrealsense.com/docs/ros-wrapper#t265-tracking-camera

Outside of the ROS wrapper, depth sensing can be simulated on T265 with the fisheye sensors using the Python example script at the link below but the results are not as accurate as a true depth-sensing 400 Series camera

https://github.com/IntelRealSense/librealsense/blob/master/wrappers/python/examples/t265_stereo.py

**Comment by DanielZamanski** [comment]
> There are some topics in the ROS wrapper documentation that you will not be able to obtain because a T265 does not have built-in depth sensing like the RealSense 400 Series models do. It is intended that the T265 is used primarily for tracking and paired with a 400 Series camera near it (such as both on a mount together) if depth sensing is required.
> 
> The topics that a T265 on its own can publish in the ROS wrapper are listed at the link below.
> 
> https://dev.intelrealsense.com/docs/ros-wrapper#t265-tracking-camera
> 
> Outside of the ROS wrapper, depth sensing can be simulated on T265 with the fisheye sensors using the Python example script at the link below but the results are not as accurate as a true depth-sensing 400 Series camera
> 
> https://github.com/IntelRealSense/librealsense/blob/master/wrappers/python/examples/t265_stereo.py


I'm still not getting most of the topics mentioned in that link. No Odometry, no camera info and no Image for example

**Comment by MartyG-RealSense** [comment]
What happens if you use either of the T265-specific roslaunch instructions provided by the wrapper?

roslaunch realsense2_camera rs_t265.launch

roslaunch realsense2_camera demo_t265.launch

**Comment by DanielZamanski** [comment]
> What happens if you use either of the T265-specific roslaunch instructions provided by the wrapper?
> 
> roslaunch realsense2_camera rs_t265.launch
> 
> roslaunch realsense2_camera demo_t265.launch

I get camera IMU and odometry, but still no camera info and no image. (Also no point cloud but I assume it's a matter of editing the launch input once everything else works)

**Comment by MartyG-RealSense** [comment]
Though your camera shows as being on a USB 3 connection in the RealSense Viewer image at the start of this issue, if the ROS wrapper's launch was detecting it as a USB 2.1 connection then the pose stream data would be available but fisheye images would not as they require USB 3.

https://github.com/IntelRealSense/librealsense/blob/master/doc/t265.md#what-are-the-system-requirements

Bearing in mind that some topics including fisheye are disabled by default, let's try the enabling instructions with the T265-specific launches.




roslaunch realsense2_camera rs_t265.launch enable_gyro:=true enable_accel:=true enable_fisheye1:=true enable_fisheye2:=true enable_pose:=true

roslaunch realsense2_camera demo_t265.launch enable_gyro:=true enable_accel:=true enable_fisheye1:=true enable_fisheye2:=true enable_pose:=true

**Comment by DanielZamanski** [comment]
> Though your camera shows as being on a USB 3 connection in the RealSense Viewer image at the start of this issue, if the ROS wrapper's launch was detecting it as a USB 2.1 connection then the pose stream data would be available but fisheye images would not as they require USB 3.
> 
> https://github.com/IntelRealSense/librealsense/blob/master/doc/t265.md#what-are-the-system-requirements
> 
> Bearing in mind that some topics including fisheye are disabled by default, let's try the enabling instructions with the T265-specific launches.
> 
> roslaunch realsense2_camera rs_t265.launch enable_gyro:=true enable_accel:=true enable_fisheye1:=true enable_fisheye2:=true enable_pose:=true
> 
> roslaunch realsense2_camera demo_t265.launch enable_gyro:=true enable_accel:=true enable_fisheye1:=true enable_fisheye2:=true enable_pose:=true

The same issue persists, unfortunately. 
I'm adding screenshots of the terminal output when I run the roslaunch command, maybe there's a settings issue or an error that I'm missing - 

![launch1](https://user-images.githubusercontent.com/101630887/183422990-9e159c33-db75-4152-8929-df4494ca9b17.png)
![launch2](https://user-images.githubusercontent.com/101630887/183423018-71ed9b7e-95d2-4437-85a7-0678d652a734.png)
![launch3](https://user-images.githubusercontent.com/101630887/183423033-0f14de96-57ac-402e-b078-2a99f5a2e3c3.png)

**Comment by MartyG-RealSense** [comment]
The 'image' in RViz usually refers to the RGB color image but the T265 does not have an RGB color sensor, just monochrome fisheye.

On the technical specification document for the T265 at the link below, it states **RGB Sensor: No**

https://ark.intel.com/content/www/us/en/ark/products/192742/intel-realsense-tracking-camera-t265.html

I wonder whether you could use the Add button above the image box to add the fisheye as the image.

**Comment by DanielZamanski** [comment]
> The 'image' in RViz usually refers to the RGB color image but the T265 does not have an RGB color sensor, just monochrome fisheye.
> 
> On the technical specification document for the T265 at the link below, it states **RGB Sensor: No**
> 
> https://ark.intel.com/content/www/us/en/ark/products/192742/intel-realsense-tracking-camera-t265.html

I should still be able to get Image, camera, pose graph and pointcloud topics. I've even tried switching for the D435 camera but I still get the same issue of a very limited amount of topics published

**Comment by MartyG-RealSense** [comment]
Okay, let's look at your SDK installation.  You are using librealsense SDK 2.50.0 and wrapper 2.3.2 which is the correct match and you are using ROS1 Noetic.

How did you install the SDK and wrapper on Ubuntu?  Did you install them separately (installing librealsense first and the ROS wrapper secondly after that) or did you install both librealsense and the wrapper at the same time from packages with apt-get install using the wrapper's **Method 1** instructions?

**Comment by DanielZamanski** [comment]
Method 2

**Comment by MartyG-RealSense** [comment]
Ok, so you installed the wrapper from source code after having first installed librealsense from packages or from source and had no problems with librealsense or the RealSense Viewer?

**Comment by DanielZamanski** [comment]
> Ok, so you installed the wrapper from source code after having first installed librealsense from packages or from source and had no problems with librealsense or the RealSense Viewer?

The realsense viewer seems to be working fine, it shows images from both cameras and tracks the camera correctly

EDIT: I've taken a look at the terminal while realsense-viewer is running, and while the program is working it shows the following errors:
![realsense_terminal4](https://user-images.githubusercontent.com/101630887/183568625-b316f4b1-11a9-4bc6-b636-7644fcdfb0b6.png)

now most of these are RGB related, which makes sense since the camera is monochrome, but some aren't and they say they're trying to access the librealsense2/presets  directory, and while the librealsense2 directory exists, it's empty (I've made sure it's not a permissions issue, the folder actually is empty)

**Comment by MartyG-RealSense** [comment]
Thanks very much for your continued patience!

When you are using the Viewer, do you also have a launch active in ROS or is realsense-viewer the only RealSense program that is using the camera?  If ROS is active, does running only realsense-viewer make a difference?

**Failed to set power state** typically means that the camera was unable to be accessed, perhaps because it is already busy because a stream has been started or because it could not be detected.

**Comment by MartyG-RealSense** [comment]
Hi @DanielZamanski  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.

**Comment by andreasbrecl** [comment]
@DanielZamanski were you able to solve this issue? I am currently experiencing the exact same problem with my D435 camera.

**Comment by Landau33** [comment]
same problem with neotic ros, t265, and no camera topics

**Comment by DanielZamanski** [comment]
> @DanielZamanski were you able to solve this issue? I am currently experiencing the exact same problem with my D435 camera.

Not really. When we switched from ROS1 to ROS2 it started working so maybe it's a ROS installation issue but I weren't able to figure it out.
