### ISSUE TITLE
Clarification on the reference frame of aligned depth images

### ISSUE THREAD

**Issue by Olimoyo** [realsenseai/realsense-ros#2444]
Hi,

Is the `/camera/aligned_depth_to_color/image_raw` topic's reference frame the RGB optical frame (i.e., `camera_color_optical_frame`)?

Thanks
Oliver

**Comment by MartyG-RealSense** [comment]
Hi @Olimoyo  When aligning, the stream type that you are aligning to should become the frame of reference.  So if aligning depth to color, the **color** system should be used.

**Comment by Olimoyo** [comment]
That makes sense, thanks!

**Comment by MartyG-RealSense** [comment]
You are very welcome, @Olimoyo - thanks very much for the update!
