### ISSUE TITLE
D435i and Release 4.0.4, Could not set param: pointcloud.stream_index_filter with -1

### ISSUE THREAD

**Issue by madgrizzle** [realsenseai/realsense-ros#2446]
Using the latest release (installed via apt), I receive this error message and cannot get a pointcloud to be produced.  I found this issue (that was closed) was "solved" from building from source and was going to try that out tonight until I saw this comment a few minutes ago.

_Originally posted by @youngday in https://github.com/IntelRealSense/realsense-ros/issues/2347#issuecomment-1211997078

I can try to build from source, but I would think doing so shouldn't be the "solution".

**Comment by MartyG-RealSense** [comment]
Hi @madgrizzle  I believe that the meaning of the comment was that building from source worked for that RealSense user but it would have been their preference to build from packages with apt-get if that install method had worked for them.

**Comment by madgrizzle** [comment]
Hmm.. I took the comment from @youngday the completely other way... I don't think either works for @youngday.

I, personally, haven't tried building from source.  All I know is the release has this issue.

**Comment by MartyG-RealSense** [comment]
Please do try a source code build if you have the opportunity to do so, as you mentioned in your opening comment that the issue **was "solved" from building from source** and so it should be worth trying yourself.

**Comment by madgrizzle** [comment]
I will try it, though I am curious as to why there would be a difference.

**Comment by youngday** [comment]
I compiled librealsensense with version 2.51 and librealsensense-ros with version 4.04,point cloud and image could get from rviz2, but the warn still print out ,I can use it first,waiting for the reason of this warn ,thanks .

**Comment by MartyG-RealSense** [comment]
Hi @madgrizzle  Do you require further assistance with this case, please?  Thanks!

**Comment by madgrizzle** [comment]
I still get the error message after building from source, but it still outputs point clouds.  Can this error message be ignored?

**Comment by MartyG-RealSense** [comment]
If the pointcloud appears to be performing well with no obvious negative effects despite frequently appearing log warnings then yes, the warnings can likely be safely ignored.

**Comment by MartyG-RealSense** [comment]
Hi @madgrizzle  Do you have an update about this case that you can provide, please?  Thanks!

**Comment by madgrizzle** [comment]
It "seems" to work even though I get the error message, though I would like to know what the error represents and why I get it, but I'll close nevertheless.
