### ISSUE TITLE
Roslaunch error

### ISSUE THREAD

**Issue by Userpc1010** [realsenseai/realsense-ros#2449]
Platform | Desktop
-- | --
OS | Ubuntu 20.04.4 LTS
Kernel Version | 5.15.0-46-generic
Camera Model | D455
SDK Version | 2.50.0
Firmware | 05.13.00.50
ROS Version | Noetic

<p dir="auto">I have installed the librealsense2 packages and realsense-ros. Then, I try to run <code class="notranslate">roslaunch realsense2_camera rs_camera.launch filters:=pointcloud</code>. I have here is my output.</p>

> sencis@sencis-desktop:~$ roslaunch realsense2_camera rs_camera.launch
> ... logging to /home/sencis/.ros/log/98aa1290-1d95-11ed-8548-23b1e1c3ce80/roslaunch-sencis-desktop-31191.log
> Checking log directory for disk usage. This may take a while.
> Press Ctrl-C to interrupt
> Done checking log file disk usage. Usage is <1GB.
> 
> started roslaunch server http://sencis-desktop:39683/
> 
> SUMMARY
> ========
> 
> PARAMETERS
>  * /camera/realsense2_camera/accel_fps: -1
>  * /camera/realsense2_camera/accel_frame_id: camera_accel_frame
>  * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
>  * /camera/realsense2_camera/align_depth: False
>  * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
>  * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_aligned_de...
>  * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_aligned_de...
>  * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
>  * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
>  * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
>  * /camera/realsense2_camera/allow_no_texture_points: False
>  * /camera/realsense2_camera/base_frame_id: camera_link
>  * /camera/realsense2_camera/calib_odom_file: 
>  * /camera/realsense2_camera/clip_distance: -2.0
>  * /camera/realsense2_camera/color_fps: -1
>  * /camera/realsense2_camera/color_frame_id: camera_color_frame
>  * /camera/realsense2_camera/color_height: -1
>  * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
>  * /camera/realsense2_camera/color_width: -1
>  * /camera/realsense2_camera/confidence_fps: -1
>  * /camera/realsense2_camera/confidence_height: -1
>  * /camera/realsense2_camera/confidence_width: -1
>  * /camera/realsense2_camera/depth_fps: -1
>  * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
>  * /camera/realsense2_camera/depth_height: -1
>  * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
>  * /camera/realsense2_camera/depth_width: -1
>  * /camera/realsense2_camera/device_type: 
>  * /camera/realsense2_camera/enable_accel: False
>  * /camera/realsense2_camera/enable_color: True
>  * /camera/realsense2_camera/enable_confidence: True
>  * /camera/realsense2_camera/enable_depth: True
>  * /camera/realsense2_camera/enable_fisheye1: False
>  * /camera/realsense2_camera/enable_fisheye2: False
>  * /camera/realsense2_camera/enable_fisheye: False
>  * /camera/realsense2_camera/enable_gyro: False
>  * /camera/realsense2_camera/enable_infra1: False
>  * /camera/realsense2_camera/enable_infra2: False
>  * /camera/realsense2_camera/enable_infra: False
>  * /camera/realsense2_camera/enable_pointcloud: False
>  * /camera/realsense2_camera/enable_pose: False
>  * /camera/realsense2_camera/enable_sync: False
>  * /camera/realsense2_camera/filters: 
>  * /camera/realsense2_camera/fisheye1_frame_id: camera_fisheye1_f...
>  * /camera/realsense2_camera/fisheye1_optical_frame_id: camera_fisheye1_o...
>  * /camera/realsense2_camera/fisheye2_frame_id: camera_fisheye2_f...
>  * /camera/realsense2_camera/fisheye2_optical_frame_id: camera_fisheye2_o...
>  * /camera/realsense2_camera/fisheye_fps: -1
>  * /camera/realsense2_camera/fisheye_frame_id: camera_fisheye_frame
>  * /camera/realsense2_camera/fisheye_height: -1
>  * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
>  * /camera/realsense2_camera/fisheye_width: -1
>  * /camera/realsense2_camera/gyro_fps: -1
>  * /camera/realsense2_camera/gyro_frame_id: camera_gyro_frame
>  * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
>  * /camera/realsense2_camera/imu_optical_frame_id: camera_imu_optica...
>  * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
>  * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
>  * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
>  * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
>  * /camera/realsense2_camera/infra_fps: 30
>  * /camera/realsense2_camera/infra_height: 480
>  * /camera/realsense2_camera/infra_rgb: False
>  * /camera/realsense2_camera/infra_width: 848
>  * /camera/realsense2_camera/initial_reset: False
>  * /camera/realsense2_camera/json_file_path: 
>  * /camera/realsense2_camera/linear_accel_cov: 0.01
>  * /camera/realsense2_camera/odom_frame_id: camera_odom_frame
>  * /camera/realsense2_camera/ordered_pc: False
>  * /camera/realsense2_camera/pointcloud_texture_index: 0
>  * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
>  * /camera/realsense2_camera/pose_frame_id: camera_pose_frame
>  * /camera/realsense2_camera/pose_optical_frame_id: camera_pose_optic...
>  * /camera/realsense2_camera/publish_odom_tf: True
>  * /camera/realsense2_camera/publish_tf: True
>  * /camera/realsense2_camera/reconnect_timeout: 6.0
>  * /camera/realsense2_camera/rosbag_filename: 
>  * /camera/realsense2_camera/serial_no: 
>  * /camera/realsense2_camera/stereo_module/exposure/1: 7500
>  * /camera/realsense2_camera/stereo_module/exposure/2: 1
>  * /camera/realsense2_camera/stereo_module/gain/1: 16
>  * /camera/realsense2_camera/stereo_module/gain/2: 16
>  * /camera/realsense2_camera/tf_publish_rate: 0.0
>  * /camera/realsense2_camera/topic_odom_in: odom_in
>  * /camera/realsense2_camera/unite_imu_method: 
>  * /camera/realsense2_camera/usb_port_id: 
>  * /camera/realsense2_camera/wait_for_device_timeout: -1.0
>  * /rosdistro: noetic
>  * /rosversion: 1.15.14
> 
> NODES
>   /camera/
>     realsense2_camera (nodelet/nodelet)
>     realsense2_camera_manager (nodelet/nodelet)
> 
> auto-starting new master
> process[master]: started with pid [31214]
> ROS_MASTER_URI=http://localhost:11311
> 
> setting /run_id to 98aa1290-1d95-11ed-8548-23b1e1c3ce80
> process[rosout-1]: started with pid [31238]
> started core service [/rosout]
> process[camera/realsense2_camera_manager-2]: started with pid [31245]
> process[camera/realsense2_camera-3]: started with pid [31246]
> [ INFO] [1660676387.810882239]: Initializing nodelet with 8 worker threads.
> [ INFO] [1660676388.160638032]: RealSense ROS v2.3.2
> [ INFO] [1660676388.160702968]: Built with LibRealSense v2.50.0
> [ INFO] [1660676388.160738213]: Running with LibRealSense v2.50.0
> [ INFO] [1660676388.197557533]:  
> [ INFO] [1660676388.215864032]: Device with serial number 215122253909 was found.
> 
> [ INFO] [1660676388.215912594]: Device with physical ID /sys/devices/pci0000:00/0000:00:04.0/0000:02:00.0/usb9/9-1/9-1:1.0/video4linux/video2 was found.
> [ INFO] [1660676388.215945235]: Device with name Intel RealSense D455 was found.
> [ INFO] [1660676388.216496221]: Device with port number 9-1 was found.
> [ INFO] [1660676388.216535757]: Device USB type: 3.2
> [ INFO] [1660676388.218538808]: getParameters...
> [ INFO] [1660676388.284900949]: setupDevice...
> [ INFO] [1660676388.284963428]: JSON file is not provided
> [ INFO] [1660676388.285004056]: ROS Node Namespace: camera
> [ INFO] [1660676388.285062346]: Device Name: Intel RealSense D455
> [ INFO] [1660676388.285109197]: Device Serial No: 215122253909
> [ INFO] [1660676388.285163431]: Device physical port: /sys/devices/pci0000:00/0000:00:04.0/0000:02:00.0/usb9/9-1/9-1:1.0/video4linux/video2
> [ INFO] [1660676388.285250028]: Device FW version: 05.13.00.50
> [ INFO] [1660676388.285304056]: Device Product ID: 0x0B5C
> [ INFO] [1660676388.285355723]: Enable PointCloud: Off
> [ INFO] [1660676388.285407440]: Align Depth: Off
> [ INFO] [1660676388.285462445]: Sync Mode: Off
> [ INFO] [1660676388.285560632]: Device Sensors: 
> [ INFO] [1660676388.300043646]: Stereo Module was found.
>  16/08 21:59:48,300 WARNING [139997039539968] (backend-v4l2.cpp:1387) Pixel format 36315752-1a66-a242-9065-d01814a likely requires patch for fourcc code RW16!
> [ INFO] [1660676388.312788827]: RGB Camera was found.
> [ INFO] [1660676388.313120472]: Motion Module was found.
> [ INFO] [1660676388.313170185]: (Confidence, 0) sensor isn't supported by current device! -- Skipping...
> [ INFO] [1660676388.313216953]: num_filters: 0
> [ INFO] [1660676388.313249451]: Setting Dynamic reconfig parameters.
> [ WARN] [1660676388.473539672]: Param '/camera/rgb_camera/power_line_frequency' has value 3 that is not in the enum { {50Hz: 1} {60Hz: 2} {Disabled: 0} }. Removing this parameter from dynamic reconfigure options.
> [ INFO] [1660676388.480632705]: Done Setting Dynamic reconfig parameters.
> /opt/ros/noetic/lib/nodelet/nodelet: symbol lookup error: /home/sencis/catkin_ws/devel/lib//librealsense2_camera.so: undefined symbol: _ZN2cv3MatC1EiiiRKNS_7Scalar_IdEE
> [camera/realsense2_camera_manager-2] process has died [pid 31245, exit code 127, cmd /opt/ros/noetic/lib/nodelet/nodelet manager __name:=realsense2_camera_manager __log:=/home/sencis/.ros/log/98aa1290-1d95-11ed-8548-23b1e1c3ce80/camera-realsense2_camera_manager-2.log].
> log file: /home/sencis/.ros/log/98aa1290-1d95-11ed-8548-23b1e1c3ce80/camera-realsense2_camera_manager-2*.log
> [camera/realsense2_camera-3] process has finished cleanly
> log file: /home/sencis/.ros/log/98aa1290-1d95-11ed-8548-23b1e1c3ce80/camera-realsense2_camera-3*.log

logs

`[0m[ INFO] [1660675524.714065073]: Loading nodelet /camera/realsense2_camera of type realsense2_camera/RealSenseNodeFactory to manager realsense2_camera_manager with the following remappings:[0m

[0m[ INFO] [1660675524.720699057]: waitForService: Service [/camera/realsense2_camera_manager/load_nodelet] has not been advertised, waiting...[0m

[0m[ INFO] [1660675524.764486542]: waitForService: Service [/camera/realsense2_camera_manager/load_nodelet] is now available.[0m

[0m[ INFO] [1660675553.507910827]: Bond broken, exiting[0m`

![Снимок экрана от 2022-08-16 22-27-12](https://user-images.githubusercontent.com/54418413/184965791-53034d0b-2e02-4873-91db-65362eb252aa.png)
![Снимок экрана от 2022-08-16 22-38-42](https://user-images.githubusercontent.com/54418413/184968080-8a0a9f40-196f-4a0b-a361-920495091e92.png)

**Comment by MartyG-RealSense** [comment]
Hi @Userpc1010  I note that you are using kernel version 5.15.  When installing librealsense from packages, the most recent kernel version supported is 5.4.

With a source code build of librealsense, the most recent officially supported kernels are 5.8 and 5.11.  An unofficial test patch that adds support for 5.13 and 5.15 kernels is available though at https://github.com/IntelRealSense/librealsense/issues/10439#issuecomment-1171965106

Alternatively, if you install librealsense and the ROS wrapper together at the same time from packages using the ROS wrapper's **Method 1** instructions then the build should be based on the **RSUSB backend**, which bypasses the kernel.  It is therefore not dependent on Linux versions or kernel versions and does not require patching.

https://github.com/IntelRealSense/realsense-ros#method-1-the-ros-distribution

*************

Before trying Method 1, you should first remove the previous librealsense package build and ROS wrapper source code build.

1.  Remove all packages on your computer with 'realsense' in their name using the instruction below to remove the librealsense package build.

`dpkg -l | grep "realsense" | cut -d " " -f 3 | xargs sudo dpkg --purge`

2.  Remove the ROS wrapper source code build by deleting the whole **catkin_ws/src** catkin workspace folder.

**Comment by Userpc1010** [comment]
i run sudo apt-get install ros-noetic-realsense2-camera and i have:

E: Unable to locate package ros-noetic-realsense2-camera
& E: Unable to locate package ros-noetic-realsense-camera
& E: Unable to locate package ros-$ROS_DISTRO-realsense2-camera
& E: Unable to locate package ros-noetic-realsense2-description

**Comment by MartyG-RealSense** [comment]
Are you experiencing the same errors today if you repeat the installation commands?

**Comment by Userpc1010** [comment]
Sorry I added this by mistake. Now I'm installing the library on Ubuntu 18.04.06 lts karnel 5.4 everything seems fine.

**Comment by MartyG-RealSense** [comment]
That's great to hear that progress seems to be successful for you!

**Comment by MartyG-RealSense** [comment]
Hi @Userpc1010  Do you require further assistance with this case, please?  Thanks!

**Comment by Userpc1010** [comment]
No thanks it's ok

**Comment by MartyG-RealSense** [comment]
Thanks very much @Userpc1010 for the update!  As you do not require further assistance, I will close this case.  Thanks again!
