### ISSUE TITLE
camera calibration parameters in d435i

### ISSUE THREAD

**Issue by adamanov** [realsenseai/realsense-ros#2456]
Hello,

I was wondering why  `rs-enumerate-devices -c` and `realsense-viewer` provides different camera calibration parameters, should not they be same? 

`rs-enumerate-devices -c`
```
 Intrinsic of "Color" / 1280x720 / {YUYV/RGB8/BGR8/RGBA8/BGRA8/Y16}
  Width:      	1280
  Height:     	720
  PPX:        	645.505981445312
  PPY:        	353.784606933594
  Fx:         	908.771240234375
  Fy:         	908.71630859375
  Distortion: 	Inverse Brown Conrady
  Coeffs:     	0  	0  	0  	0  	0  
  FOV (deg):  	70.31 x 43.22
  ```
![image](https://user-images.githubusercontent.com/53511072/186247266-9a097bf4-b119-47b2-bee5-717a31d22724.png)

all best

**Comment by MartyG-RealSense** [comment]
Hi @adamanov  Your rs-enumerate-devices listing is for the **Color** intrinsics.  The Camera Calibration window's data is for the **Depth** intrinsics.  Please check the Depth intrinsics for 1280x720 resolution to see whether they match with the Camera Calibration window's values.

As an example, below is a comparison of the values from my D455 at 1280x720 depth resolution.

![image](https://user-images.githubusercontent.com/41145062/186363510-63f7a239-cac1-4011-afc7-6085b167fe59.png)

![image](https://user-images.githubusercontent.com/41145062/186363582-310df42f-e7da-4214-8795-977ff1613891.png)

**Comment by adamanov** [comment]
> Hi @adamanov Your rs-enumerate-devices listing is for the **Color** intrinsics. The Camera Calibration window's data is for the **Depth** intrinsics. Please check the Depth intrinsics for 1280x720 resolution to see whether they match with the Camera Calibration window's values.
> 
> As an example, below is a comparison of the values from my D455 at 1280x720 depth resolution.
> 
> ![image](https://user-images.githubusercontent.com/41145062/186363510-63f7a239-cac1-4011-afc7-6085b167fe59.png)
> 
> ![image](https://user-images.githubusercontent.com/41145062/186363582-310df42f-e7da-4214-8795-977ff1613891.png)

Hey @MartyG-RealSense  thanks for you reply, Yeah they match perfectly :) Thanks

**Comment by MartyG-RealSense** [comment]
You are very welcome, @adamanov - thanks very much for the update!
