### ISSUE TITLE
Error with the format disparity16 R200

### ISSUE THREAD

**Issue by moecurlyhair** [realsenseai/realsense-ros#246]
### System Configuration
Please complete Your Configuration detail below. Refer to the BKC at [Configuration](../realsense_camera/README.md#configuration).

| Version               | Your Configuration   |
|:--------------------- |:---------------------|
| Operating System      | Ubuntu 16.04.2 LTS  |
| Kernel                |  |
| ROS                   | kinetic  |
| ROS RealSense         |    |
| librealsense          |   |
| Camera Type-Firmware  | Intel RealSense  R200         |

---

### Expected Behavior
I changed the depth image format to RS_FORMAT_DISPARITY16  in the realsense_camera r200_nodelet.cpp to get the disparity map, but i just get the values 0 and 255 and a weird picture. How can i get the disparity picture with the disparity values?

### Actual Behavior
I get this picture:
![disparitypic](https://user-images.githubusercontent.com/29372675/27029378-5ee2ae24-4f68-11e7-93ce-b6ada7b1a80f.png)
With the values for the topic /camera/depth/image_raw
![values1](https://user-images.githubusercontent.com/29372675/27029711-cf4358a2-4f69-11e7-9ace-f2f109b9508f.png)

Thank you!

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Close this issue for lack of activity. Please feel free to reopen if the issue is still relevant.
