### ISSUE TITLE
D435i huge bag size

### ISSUE THREAD

**Issue by macTracyHuang** [realsenseai/realsense-ros#2462]
hi, I am using D435i and try to record  it, 
I was wondering is it normal to have such a huge file?
the resolution is only 480 640, fps is 30. the file even not decrese when I change fps to 10..

![image](https://user-images.githubusercontent.com/62415378/187067246-536eec25-1164-41fa-ae69-4032c1a9d9ca.png)

or  any sugestion to lower the bag size? thx

**Comment by MartyG-RealSense** [comment]
Hi @macTracyHuang  Yes, it is normal for bag files to be very large.  Reducing the resolution can reduce bag file size, though in this case it may not be practical to reduce lower than 640x480.  You could try 480x270 if you are able to use a lower resolution.

If you recorded the bag file with **rosbag record** then you could use the **--split** command to automatically divide the bag into a set of smaller files during recording, as described at https://github.com/IntelRealSense/librealsense/issues/2424#issuecomment-423284173

**Comment by MartyG-RealSense** [comment]
Hi @macTracyHuang  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
