### ISSUE TITLE
Unit of the depth measuremnt in the depth image for D415

### ISSUE THREAD

**Issue by ahar** [realsenseai/realsense-ros#2464]
Hi,

I would like to know what is the unit of the depth image output,  i.e., for each depth encoded pixel, what is the depth measuring unit?

thank you,

**Comment by MartyG-RealSense** [comment]
Hi @ahar  The raw depth pixel value is a 16-bit value called **uint16_t**, whilst real-world 3D depth is expressed in meters.  

The depth in meters can be obtained either by multiplying the uint16_t value by the **depth unit scale** value of the particular RealSense camera model being used or by using the RealSense SDK programming instruction **get_distance()**

https://dev.intelrealsense.com/docs/projection-in-intel-realsense-sdk-20#depth-image-formats
