### ISSUE TITLE
is Y8 1280x800 stream rectified?

### ISSUE THREAD

**Issue by jwko1508** [realsenseai/realsense-ros#2465]
I tried to get Y16 1280x800 stream. but i get 
[WARN] [depth_fr.depth_fr]: Given stream configuration is not supported by the device!  Stream: Infrared, Stream Index: 0, Width: 1280, Height: 800, FPS: 15, Format: Y16

I can get Y8 1280x800 stream. It works.
Maybe perhaps, the stream logged as "Y8 1280x800" is actually "Y16 1280x800"?
If not, How can i get Y16 stream from ros2 driver?

setting
ubuntu 18.04
D455 
realsense-ros ros2 branch
only infra1 stream
15 fps
1280x800

**Comment by MartyG-RealSense** [comment]
Hi @jwko1508  Y8 is rectified, whilst Y16 is unrectified.

The RealSense ROS wrapper does not output Y16.  In the information below, a RealSense team member provides suggestions for editing the wrapper file **base_realsense_node.cpp** to attempt to enable it to provide Y16.  At the time of writing this there is not an alternative way to enable Y16 output from the ROS wrapper.

********

For a code update I suggest changing this line:

https://github.com/IntelRealSense/realsense-ros/blob/ddd6fe116859b960a59412538e91d085a368c871/realsense2_camera/src/base_realsense_node.cpp#L107

`_format[RS2_STREAM_INFRARED] = RS2_FORMAT_Y16;`

And if point cloud texture is needed, these lines should be updated too:

https://github.com/IntelRealSense/realsense-ros/blob/ddd6fe116859b960a59412538e91d085a368c871/realsense2_camera/src/base_realsense_node.cpp#L2180

https://github.com/IntelRealSense/realsense-ros/blob/ddd6fe116859b960a59412538e91d085a368c871/realsense2_camera/src/base_realsense_node.cpp#L2228

**Comment by MartyG-RealSense** [comment]
Hi @jwko1508  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
