### ISSUE TITLE
I got a warning message after update realsense-ros version

### ISSUE THREAD

**Issue by ghost** [realsenseai/realsense-ros#2472]
Dear IntelRealsense ROS team.
I use 2 l515 cameras in my robot system and I got a warning message "WARNING [547029492096] (backend-v4l2.cpp:1127) Frames didn't arrived within 5 seconds" after update realsense-ros version from 2.2.4 to 2.3.2
Can I delete or solve this problem?

PC : Jetson Xavier
OS : Ubuntu 18.04
librealsense version : 2.50.0
realsense-ros version : 2.3.2
USB type : 3.2
There are no case of pressed or twisted cable.

[ INFO] [1662515468.410336237]: Initializing nodelet with 8 worker threads.
[ INFO] [1662515469.128682758]: PlaneEstimationNodelet Constructor
[ INFO] [1662515469.129407054]: PlaneEstimationNodelet Constructor
[ INFO] [1662515469.374174203]: PlaneEstimationNodelet - onInit
[ INFO] [1662515469.375070739]: PlaneEstimationNodelet - onInit
[ INFO] [1662515469.408070798]: Initializing IMU Filter Nodelet
[ INFO] [1662515469.408324775]: Initializing IMU Filter Nodelet
[ INFO] [1662515469.408803959]: Starting ImuFilter
[ INFO] [1662515469.408965959]: Starting ImuFilter
[ INFO] [1662515469.423452381]: Using dt computed from message headers
[ INFO] [1662515469.424777344]: Using dt computed from message headers
[ INFO] [1662515469.466832473]: Imu filter gain set to 0.100000
[ INFO] [1662515469.466973959]: Gyro drift bias set to 0.000000
[ INFO] [1662515469.467040782]: Magnetometer bias values: 0.000000 0.000000 0.000000
[ INFO] [1662515469.468128569]: Imu filter gain set to 0.100000
[ INFO] [1662515469.468272232]: Gyro drift bias set to 0.000000
[ INFO] [1662515469.468334638]: Magnetometer bias values: 0.000000 0.000000 0.000000
[ INFO] [1662515469.930320615]: RealSense ROS v2.3.2
[ INFO] [1662515469.930434578]: Built with LibRealSense v2.50.0
[ INFO] [1662515469.930492376]: Running with LibRealSense v2.50.0
[ INFO] [1662515469.932047538]: RealSense ROS v2.3.2
[ INFO] [1662515469.932208001]: Built with LibRealSense v2.50.0
[ INFO] [1662515469.932312780]: Running with LibRealSense v2.50.0
[ INFO] [1662515469.985452748]:  
[ INFO] [1662515469.985679810]:  
[ INFO] [1662515470.353212875]: Device with serial number f0264493 was found.

[ INFO] [1662515470.353323478]: Device with physical ID /sys/devices/3610000.xhci/usb2/2-1/2-1:1.0/video4linux/video4 was found.
[ INFO] [1662515470.353369178]: Device with name Intel RealSense L515 was found.
[ INFO] [1662515470.356471401]: Device with port number 2-1 was found.
[ INFO] [1662515470.356651834]: Device USB type: 3.2
[ INFO] [1662515470.356815914]: Resetting device...
[ INFO] [1662515470.461817863]: Device with serial number f0264493 was found.

[ INFO] [1662515470.462011897]: Device with physical ID /sys/devices/3610000.xhci/usb2/2-1/2-1:1.0/video4linux/video4 was found.
[ INFO] [1662515470.462089665]: Device with name Intel RealSense L515 was found.
[ INFO] [1662515470.464204975]: Device with port number 2-1 was found.
[ INFO] [1662515470.722757188]: Device with serial number f0264703 was found.

[ INFO] [1662515470.723033119]: Device with physical ID /sys/devices/3610000.xhci/usb2/2-3/2-3:1.0/video4linux/video0 was found.
[ INFO] [1662515470.723182606]: Device with name Intel RealSense L515 was found.
[ INFO] [1662515470.724661022]: Device with port number 2-3 was found.
[ INFO] [1662515470.724911446]: Device USB type: 3.2
[ INFO] [1662515470.725089064]: Resetting device...
init
[ INFO] [1662515476.428789182]:  
[ INFO] [1662515476.692612291]: Device with serial number f0264493 was found.

[ INFO] [1662515476.693064108]: Device with physical ID /sys/devices/3610000.xhci/usb2/2-1/2-1:1.0/video4linux/video0 was found.
[ INFO] [1662515476.693150740]: Device with name Intel RealSense L515 was found.
[ INFO] [1662515476.694766149]: Device with port number 2-1 was found.
[ INFO] [1662515476.694888337]: Device USB type: 3.2
[ INFO] [1662515476.699618940]: getParameters...
[ INFO] [1662515476.752524547]:  
[ INFO] [1662515476.969347638]: setupDevice...
[ INFO] [1662515476.969548744]: JSON file is not provided
[ INFO] [1662515476.969735321]: ROS Node Namespace: service_visioncamera_right
[ INFO] [1662515476.969837314]: Device Name: Intel RealSense L515
[ INFO] [1662515476.969969614]: Device Serial No: f0264493
[ INFO] [1662515476.971400655]: Device physical port: /sys/devices/3610000.xhci/usb2/2-1/2-1:1.0/video4linux/video0
[ INFO] [1662515476.971906013]: Device FW version: 01.05.08.01
[ INFO] [1662515476.972154995]: Device Product ID: 0x0B64
[ INFO] [1662515476.972270878]: Enable PointCloud: On
[ INFO] [1662515476.972883701]: Align Depth: Off
[ INFO] [1662515476.973072582]: Sync Mode: On
[ INFO] [1662515476.974323191]: Device Sensors: 
[ INFO] [1662515476.979082437]: L500 Depth Sensor was found.
[ INFO] [1662515476.992370100]: RGB Camera was found.
[ INFO] [1662515476.993294792]: Motion Module was found.
[ INFO] [1662515476.993491001]: Add Filter: pointcloud
[ INFO] [1662515476.995826124]: num_filters: 1
[ INFO] [1662515476.996028734]: Setting Dynamic reconfig parameters.
[ INFO] [1662515477.013383374]: Device with serial number f0264493 was found.

[ INFO] [1662515477.013494552]: Device with physical ID /sys/devices/3610000.xhci/usb2/2-1/2-1:1.0/video4linux/video0 was found.
[ INFO] [1662515477.013566206]: Device with name Intel RealSense L515 was found.
[ INFO] [1662515477.014552310]: Device with port number 2-1 was found.
[ INFO] [1662515477.180938244]: Done Setting Dynamic reconfig parameters.
[ INFO] [1662515477.183961649]: depth stream is enabled - width: 640, height: 480, fps: 30, Format: Z16
[ INFO] [1662515477.187483563]: color stream is enabled - width: 960, height: 540, fps: 30, Format: RGB8
[ INFO] [1662515477.187752963]: gyro stream is enabled - fps: 400
[ INFO] [1662515477.187886959]: accel stream is enabled - fps: 400
[ INFO] [1662515477.188037213]: setupPublishers...
[ INFO] [1662515477.196862607]: Expected frequency for depth = 30.00000
[ INFO] [1662515477.283300231]: Device with serial number f0264703 was found.

[ INFO] [1662515477.283691338]: Device with physical ID /sys/devices/3610000.xhci/usb2/2-3/2-3:1.0/video4linux/video4 was found.
[ INFO] [1662515477.283852056]: Device with name Intel RealSense L515 was found.
[ INFO] [1662515477.285429349]: Device with port number 2-3 was found.
[ INFO] [1662515477.285712574]: Device USB type: 3.2
[ INFO] [1662515477.291589066]: Expected frequency for color = 30.00000
[ INFO] [1662515477.293270304]: getParameters...
[ INFO] [1662515477.383592946]: Start publisher IMU
[ INFO] [1662515477.389148961]: setupStreams...
[ INFO] [1662515477.548367728]: setupDevice...
[ INFO] [1662515477.548817816]: JSON file is not provided
[ INFO] [1662515477.549110226]: ROS Node Namespace: service_visioncamera_left
[ INFO] [1662515477.549240541]: Device Name: Intel RealSense L515
[ INFO] [1662515477.549336294]: Device Serial No: f0264703
[ INFO] [1662515477.549487924]: Device physical port: /sys/devices/3610000.xhci/usb2/2-3/2-3:1.0/video4linux/video4
[ INFO] [1662515477.549624800]: Device FW version: 01.05.08.01
[ INFO] [1662515477.549726921]: Device Product ID: 0x0B64
[ INFO] [1662515477.549847636]: Enable PointCloud: On
[ INFO] [1662515477.549943868]: Align Depth: Off
[ INFO] [1662515477.550087945]: Sync Mode: On
[ INFO] [1662515477.550608247]: Device Sensors: 
[ INFO] [1662515477.555530126]: L500 Depth Sensor was found.
[ INFO] [1662515477.564902577]: RGB Camera was found.
[ INFO] [1662515477.565535338]: Motion Module was found.
[ INFO] [1662515477.565693624]: Add Filter: pointcloud
[ INFO] [1662515477.567599618]: num_filters: 1
[ INFO] [1662515477.567708235]: Setting Dynamic reconfig parameters.
[ INFO] [1662515477.751355707]: Done Setting Dynamic reconfig parameters.
[ INFO] [1662515477.753652104]: depth stream is enabled - width: 640, height: 480, fps: 30, Format: Z16
[ INFO] [1662515477.756883848]: color stream is enabled - width: 960, height: 540, fps: 30, Format: RGB8
[ INFO] [1662515477.757142143]: gyro stream is enabled - fps: 400
[ INFO] [1662515477.757594792]: accel stream is enabled - fps: 400
[ INFO] [1662515477.757762806]: setupPublishers...
[ INFO] [1662515477.766450205]: Expected frequency for depth = 30.00000
[ INFO] [1662515477.853145388]: Expected frequency for color = 30.00000
[ INFO] [1662515477.932284633]: Start publisher IMU
[ INFO] [1662515477.936875314]: setupStreams...
 07/09 10:51:18,174 WARNING [547247604096] (ds5-motion.cpp:473) IMU Calibration is not available, default intrinsic and extrinsic will be used.
[ WARN] [1662515478.183018840]: 
[ WARN] [1662515478.183198279]: frame's time domain is HARDWARE_CLOCK. Timestamps may reset periodically.
[ INFO] [1662515478.188927872]: SELECTED BASE:Depth, 0
 07/09 10:51:18,217 WARNING [546853343616] (ds5-motion.cpp:473) IMU Calibration is not available, default intrinsic and extrinsic will be used.
[ INFO] [1662515478.231422107]: SELECTED BASE:Depth, 0
[ INFO] [1662515478.243775931]: First IMU message received.
[ INFO] [1662515478.253255837]: RealSense Node Is Up!
[ WARN] [1662515478.285877620]: 
[ WARN] [1662515478.286074661]: frame's time domain is HARDWARE_CLOCK. Timestamps may reset periodically.

**Comment by MartyG-RealSense** [comment]
Hi @RI-SMJ  I note that you are using Jetson Xavier as your computing device and have the pointcloud filter enabled.  There is a known issue for Jetson boards specifically that can cause problems when the pointcloud filter is enabled.  These issues could include very low FPS or missing color.  

For the ROS1 wrapper the best solution is currently to use librealsense **2.43.0** and ROS wrapper **2.2.23**.

You should be able to confirm whether you are experiencing the Jetson pointcloud problem simply by not enabling the pointcloud filter.  Then performance should be normal when the pointcloud is false.

*********

If you prefer to use SDK 2.50.0 and wrapper 2.3.2 then an alternative approach you could try is as follows:

1.  Install support for an **RGBD** type roslaunch by installing RGBD support for the ROS1 branch that you are using (Kinetic, Melodic or Noetic).

**Kinetic**
sudo apt-get install ros-kinetic-rgbd-launch

**Melodic**
sudo apt-get install ros-melodic-rgbd-launch

**Noetic**
sudo apt-get install ros-noetic-rgbd-launch

2.  Launch the RealSense ROS wrapper in RGBD mode with the roslaunch instruction below:

**roslaunch realsense2_camera rs_rgbd.launch**

**Comment by MartyG-RealSense** [comment]
Hi @RI-SMJ  Do you require further assistance with this case, please?  Thanks!

**Comment by ghost** [comment]
@MartyG-RealSense Thank you so much!! I will test again with the version you recommended as soon as possible.

**Comment by MartyG-RealSense** [comment]
You are very welcome, @RI-SMJ - thanks very much for the update!
