### ISSUE TITLE
ROS2 Humble: Install error about "rosdep"   

### ISSUE THREAD

**Issue by mat-macnica** [realsenseai/realsense-ros#2475]
Hello,

I tried to install realsense-ros2-wrapper on Jetson AGX Xavier NX based on below guide link.
https://github.com/IntelRealSense/realsense-ros/tree/ros2-beta#step-3-install-intel-realsense-ros2-wrapper-from-sources

Current Configuration:
  Jetson Jetson AGX Xavier NX with Jetpack 5.0.2 which is L4T 35.1
  with ROS2 Humble

I've succeed to run realsense-viewer already by librealsense2 build process on JetsonNX.
But I found Error like below in rosdep command; 
![image](https://user-images.githubusercontent.com/92834689/189597834-d5764324-47fe-458e-b95a-9c2e0e40ac47.png)

I also found "Support ROS2 Humble" comment below link;
I expect proper behavior with "ros2-beta branch" on Humble Environment.
https://github.com/IntelRealSense/realsense-ros/compare/development...ros2-beta
![image](https://user-images.githubusercontent.com/92834689/189598009-e9a61e44-f737-414d-b3b6-03d0de430b6d.png)

So, We would appreciate if you tell us how to solve this issue.
–
Best regards,

**Comment by MartyG-RealSense** [comment]
Hi @mat-macnica   There is information about installing for ROS2 Humble at https://github.com/IntelRealSense/librealsense/issues/10439#issuecomment-1186588624 and the comments below it.

https://github.com/IntelRealSense/realsense-ros/issues/2309#issuecomment-1085877405 suggests a method for resolving the **No definition of [xacro]** warning on Ubuntu 20.04 Focal.

**Comment by mat-macnica** [comment]
Hi,

Thank you very much for your kindness.
I really appreciate your help.

I'd like to check the behavior with your guide.

Best regards,

**Comment by MartyG-RealSense** [comment]
You are very welcome, @mat-macnica - thanks very much for the update!
