### ISSUE TITLE
align_depth makes depth framerate inconsistent 

### ISSUE THREAD

**Issue by SJ-YI** [realsenseai/realsense-ros#2480]
I have confirmed this on multiple machines. Enabling align_depth made a periodical lag (~1 sec every 10s)  on depth frame. 
RGB framerate is not (or not noticeably) affected. 

Anybody else suffered from this issue? Are there any fix? 

Thanks in advance.

**Comment by MartyG-RealSense** [comment]
Hi @SJ-YI  Depth-color alignment is a processing-intensive operation that will place a greater burden on the computer than when align_depth is not enabled.

Does the lag still occur if you add the instruction below to your roslaunch instruction?  If auto-exposure is enabled then disabling auto_exposure_priority should force the depth and RGB framerate to be maintained at a constant rate.

**auto_exposure_priority:=false**

For example:

**roslaunch realsense2_camera rs_camera.launch auto_exposure_priority:=false**

**Comment by MartyG-RealSense** [comment]
Hi @SJ-YI  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
