### ISSUE TITLE
Support of realsense for ROS2 is available? 

### ISSUE THREAD

**Issue by goyalvarun02** [realsenseai/realsense-ros#2484]
Hi ,

May I know if github of realsense for ROS 2 is available Please share the path .

or if not available May I know when can expect the ros2 of realsense.

Thanks

**Comment by MartyG-RealSense** [comment]
Hi @goyalvarun02   Yes, there is a ROS2 wrapper for RealSense.

https://github.com/IntelRealSense/realsense-ros/tree/ros2-beta

It supports ROS2 Humble, Rolling, Galactic, Foxy, Eloquent and Dashing.

**Comment by MartyG-RealSense** [comment]
Hi @goyalvarun02  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
