### ISSUE TITLE
No support for macOS yet? (M1 mac)

### ISSUE THREAD

**Issue by JinraeKim** [realsenseai/realsense-ros#2499]
Hi, I'm looking for using this on M1 mac.
Is there any way to use it? I cannot find any installation guide for mac.
It doesn't matter to use docker if needed.

**Comment by MartyG-RealSense** [comment]
Hi @JinraeKim  If you are seeking to install the librealsense SDK on Mac M1, there is a detailed step by step guide at the link below.

https://lightbuzz.com/realsense-macos/

Installation support for M1 is also provided by **brew install librealsense**

https://formulae.brew.sh/formula/librealsense

**Comment by JinraeKim** [comment]
> Hi @JinraeKim  If you are seeking to install the librealsense SDK on Mac M1, there is a detailed step by step guide at the link below.
> 
> https://lightbuzz.com/realsense-macos/
> 
> Installation support for M1 is also provided by **brew install librealsense**
> 
> https://formulae.brew.sh/formula/librealsense

Thanks for answering!
Then, what I have to do is to install librealsense SDK (probly through brew) and build the realsense ROS wrapper?

**Comment by MartyG-RealSense** [comment]
You are very welcome!

Yes, the librealsense SDK should be installed first and the RealSense ROS wrapper built secondly.

**Comment by JinraeKim** [comment]
> You are very welcome!
> 
> Yes, the librealsense SDK should be installed first and the RealSense ROS wrapper built secondly.

Sorry for keeping asking.
As I know, I can only install ROS2 on M1 Mac, not ROS(1).

Then, should I follow the instruction for ROS2 in this repo as well?
Or, is there any workaround for ROS(1) for this?


EDIT: Is there any full instruction for realsense-ros on Apple Silicon Mac...? hmm... Even if with docker

**Comment by MartyG-RealSense** [comment]
I researched your question but did not find an instance of running the ROS wrapper directly on MacOS.  You may need to use Ubuntu on your Mac in Docker or in a Virtual Machine (VM), as described for M1 in the guide at the link below.

https://yangrobotics.com/ubuntu-and-ros-setup-on-m1-macbook-air

The creator of the guide stated that they were able to use ROS1 Melodic on their M1 with Docker.

**Comment by JinraeKim** [comment]
I could also test ROS1 on my M1 mac with docker, but my concern is the use of Realsense tgt cuz it must be related to USB data stream as well.
Anyway, thanks for finding good references!

**Comment by MartyG-RealSense** [comment]
Hi @JinraeKim  Do you require further assistance with this case, please?  Thanks!

**Comment by JinraeKim** [comment]
> Hi @JinraeKim Do you require further assistance with this case, please? Thanks!

No, thanks! I'll close this issue with this comment.

**Comment by MartyG-RealSense** [comment]
Thanks very much @JinraeKim for the update!
