### ISSUE TITLE
UTM-30LX Mapping

### ISSUE THREAD

**Issue by lucas33620** [realsenseai/realsense-ros#2509]
Hello,
My goal would be to do mapping with the UTM-30LX Lidar.
The laser is displayed well in rviz when I select /scan and I select /laser in the Fixed Frame.
I created a robot on Rviz in urdf and I would like to retrieve the data from the topic / scan of my LIDAR to simulate it.
Could you please help me?
I can send you the files and codes if needed.
Thanks in advance
I used tutorial : [https://navigation.ros.org/setup_guides/sensors/setup_sensors.html#mapping-and-localization](url)

**Comment by MartyG-RealSense** [comment]
Hi @lucas33620  If your question does not involve RealSense depth camera products then the official ROS support forum **ROS Answers** would be a better place to post it.  Thanks!

https://answers.ros.org/questions/

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
