### ISSUE TITLE
Best Camera Parameter Setup of R200 for indoor/outdoor applications?

### ISSUE THREAD

**Issue by szx0112** [realsenseai/realsense-ros#251]
### System Configuration
Please complete Your Configuration detail below. Refer to the BKC at [Configuration](../realsense_camera/README.md#configuration).

| Version               | Your Configuration   |
|:--------------------- |:---------------------|
| Operating System      | Ubuntu 16.04              |
| Kernel                | ?-?-?                |
| ROS                   | Kinect                    |
| ROS RealSense         | Latest               |
| librealsense          | Latest                |
| Camera Type-Firmware  | Latest            |

My goal is 3D mapping for indoor and outdoor environment. So I want to have the r200 that can sense as far as possible but still can maintain certain level of accuracy and resolutions. I have tried several parameters: such as ir gain, exposure, resolution, frame rate as mentioned in the r200 manual but still cannot have a fully connected point cloud (The point cloud is always detached, results in rviz show below). 

![screenshot from 2017-07-07 20-45-38](https://user-images.githubusercontent.com/10392640/27981686-93243206-6355-11e7-967f-61c2afc3d93c.png)

Wondering if anyone have some successful cases and specific parameters that can share? Any comment is appreciate. Thanks.

**Comment by omershalev** [comment]
I don't think you should expect a fully connected pointcloud using R200. 
Still, you can get nice 3D-scanning by stitching pointclouds. [RTAB-map](http://wiki.ros.org/rtabmap) is such a 3D reconstruction ROS package - I have used it with R200 and got nice a 3D scan.
As for the parameters: based on my experience, the default ones are good enough for indoor scanning. You can see the parameters that I used for outdoor:
[outdoorParams.yaml.txt](https://github.com/intel-ros/realsense/files/1179674/outdoorParams.yaml.txt)
As a general comment, the significant parameters to play with for R200 are exposure and gain.
