### ISSUE TITLE
ros2-beta CMake error

### ISSUE THREAD

**Issue by ripdk12** [realsenseai/realsense-ros#2517]
I am trying to setup isaac ros on my Xavier NX (5.0.2) following this:
https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_visual_slam
Works great with the included rosbag example, however i want to test with my RealSense D435i camera, which is where i ran into some issues.

still within the same docker container:
I have built librealsense2 from source with the RSUSB backend (for some reason i was unable to build from deb package), and realsense-viewer works just fine, however when trying to build the realsense-ros wrapper for ros2 humble following this guide:
https://github.com/IntelRealSense/realsense-ros/tree/ros2-beta

i get the following error message at the colcon build step:
```
--- stderr: realsense2_camera          
CMake Error at /workspaces/isaac_ros-dev/install/realsense2_camera_msgs/share/realsense2_camera_msgs/cmake/ament_cmake_export_targets-extras.cmake:18 (message):
  Failed to find exported target names in
  '/workspaces/isaac_ros-dev/install/realsense2_camera_msgs/share/realsense2_camera_msgs/cmake/export_realsense2_camera_msgs__rosidl_generator_cExport.cmake'
Call Stack (most recent call first):
  /workspaces/isaac_ros-dev/install/realsense2_camera_msgs/share/realsense2_camera_msgs/cmake/realsense2_camera_msgsConfig.cmake:41 (include)
  CMakeLists.txt:96 (find_package)


---
Failed   <<< realsense2_camera [7.39s, exited with code 1]
```

Any clues what could cause this? Or any pointers as to how to get my D435i to work with isaac ros visual slam? Thanks:)

**Comment by MartyG-RealSense** [comment]
Hi @ripdk12  Are you using Ubuntu 20.04, please?  If you are, installing from packages on 20.04 for computing devices with an Arm architecture is not supported by the librealsense SDK unfortunately.  With 20.04 on Arm, librealsense should be built from source code instead, as you did.

In regard to Humble support, the RealSense **ros2_beta** ROS2 wrapper requires Ubuntu **22.04**.

![image](https://user-images.githubusercontent.com/41145062/197822969-8f0fdcbd-a878-43ad-a301-f84129977703.png)

Can you confirm which Ubuntu version you are using, please?

If you are using 22.04 then you can also assume that the above condition about not being able to perform a librealsense package installation on Arm / 20.04 will apply to 22.04 too.

**Comment by ripdk12** [comment]
Oh yeah you have a point, i'm using ubuntu 20.04. I'm not quite sure what is the best way forward. should i try to get the ros wrapper running in ros2 foxy instead, or is there another way to use the ros2 wrapper in a ros2 humble docker container?

**Comment by MartyG-RealSense** [comment]
If you installed the ROS2 wrapper for Humble then it would not have hardware metadata support at the time of writing this, as described by a RealSense ROS team member at https://github.com/IntelRealSense/librealsense/issues/10439#issuecomment-1186588624

You could certainly use Foxy with 20.04, though the ROS2 wrapper also supports Galactic for 20.04 which is newer than Foxy (the order of release is Foxy, Galactic, Humble).

Some people do run different Ubuntu versions in a Docker setup (such as 20.04 on the host and 18.04 on the RealSense ROS wrapper installation).  It may be easiest to use Galactic with 20.04.

**Comment by ripdk12** [comment]
I just realised that the current release of isaac ros only supports ros2 humble, which is why the provided docker image uses that version even on ubuntu 20.04. So i have the choice of either using another version of isaac ros, or try to find a way to build realsense on ros2 humble with ubuntu 20.04 as base.
Thanks for the help, I'll try to figure out how best to proceed from here.

**Comment by MartyG-RealSense** [comment]
You are very welcome.  Good luck!
