### ISSUE TITLE
how to decompress ros topics

### ISSUE THREAD

**Issue by WkangLiu** [realsenseai/realsense-ros#2529]
I get this error when I try to go around the images in the topic, it shows that I am using a compressed image, how do I decompress it?

You are very knowledgeable and I hope you can help.

`[ WARN] [1667305953.347796970]: [image_transport] It looks like you are trying to subscribe directly to a transport-specific image topic '/sensor/camera_backward/image_raw/compressed', in which case you will likely get a connection error. Try subscribing to the base topic '/sensor/camera_backward/image_raw' instead with parameter ~image_transport set to 'compressed' (on the command line, _image_transport:=compressed). See http://ros.org/wiki/image_transport for details.
`

**Comment by MartyG-RealSense** [comment]
Hi @WkangLiu  I have seen this message in an RTABMAP case at https://github.com/IntelRealSense/realsense-ros/issues/2017

Can you confirm whether you are also using RTABMAP, please?  Thanks!

**Comment by WkangLiu** [comment]
Thank you !!!!!

sorry, I don't use RTABMAP，I just want to extract the image data from the topics of the bag file.

**Comment by MartyG-RealSense** [comment]
My research indicates that if you wish to subscribe to the 'base topic' that does not have compression then the instruction below should be added to your launch instruction in the ROS terminal:

`_image_transport:=compressed`

For example:

**ROS1**
roslaunch realsense2_camera rs_camera.launch  _image_transport:=compressed

**ROS2**
ros2 launch realsense2_camera rs_launch.py _image_transport:=compressed

**Comment by WkangLiu** [comment]
Thank you!
I will try it, thanks to your help!

**Comment by MartyG-RealSense** [comment]
Hi @WkangLiu  Do you require further assistance with this case, please?  Thanks!

**Comment by WkangLiu** [comment]
I solve it.
Thank you!

**Comment by MartyG-RealSense** [comment]
You are very welcome.  Thanks very much for the update!  As you have achieved a solution, I will close this case.  Thanks again!

**Comment by trisha3290** [comment]
@WkangLiu can you please tell how did you solved it? I am using Rqt to get compressed image but getting the same warning as below

[ WARN] 1260927377.319546000: [image_transport] It looks like you are trying to subscribe directly to a transport-specific image topic '/image/compressed', in which case you will likely get a connection error. Try subscribing to the base topic '/image' instead with parameter ~image_transport set to 'compressed' (on the command line, _image_transport:=compressed). See http://ros.org/wiki/image_transport for details.
