### ISSUE TITLE
D455 cannot run depth at 30 HZ under ROS2

### ISSUE THREAD

**Issue by patrickpoirier51** [realsenseai/realsense-ros#2530]
Hello,

Just received a D455 as replacement for D435i for a SLAM system under ROS2

Launching with this command
ros2 launch realsense2_camera rs_launch.py align_depth:=true depth_width:=640 depth_height:=480 depth_fps:=30.0 color_width:=640 color_height:=480 color_fps:=30.0

**I have 30 hz with the D435i**
[realsense2_camera_node-1] [INFO] [1667324597.517171040] [camera.camera]: Open profile: stream_type: Depth(0), Format: Z16, Width: 848, Height: 480, FPS: 30
[realsense2_camera_node-1] [INFO] [1667324597.517365971] [camera.camera]: Stopping Sensor: RGB Camera
[realsense2_camera_node-1] [INFO] [1667324597.518914167] [camera.camera]: Starting Sensor: RGB Camera
[realsense2_camera_node-1] [INFO] [1667324597.523300218] [camera.camera]: Open profile: stream_type: Color(0), Format: RGB8, Width: 1280, Height: 720, FPS: 30
[realsense2_camera_node-1] [INFO] [1667324597.523956618] [camera.camera]: RealSense Node Is Up!

![image](https://user-images.githubusercontent.com/12484190/199302369-00e47560-4b27-4544-a2ee-e763ec656836.png)

**I have 15 hz with the D455**
[realsense2_camera_node-1] [INFO] [1667324924.660251453] [camera.camera]: Open profile: stream_type: Depth(0), Format: Z16, Width: 848, Height: 480, FPS: 30
[realsense2_camera_node-1] [INFO] [1667324924.660682043] [camera.camera]: Stopping Sensor: RGB Camera
[realsense2_camera_node-1] [INFO] [1667324924.711995876] [camera.camera]: Starting Sensor: RGB Camera
[realsense2_camera_node-1] [INFO] [1667324924.721774605] [camera.camera]: Open profile: stream_type: Color(0), Format: RGB8, Width: 1280, Height: 720, FPS: 30
[realsense2_camera_node-1] [INFO] [1667324924.723208133] [camera.camera]: RealSense Node Is Up!

![image](https://user-images.githubusercontent.com/12484190/199303377-960c4659-f82b-44bf-9170-093aeec1bcf3.png)

**Comment by MartyG-RealSense** [comment]
Hi @patrickpoirier51  It appears that the D455 launch is applying the default stream profile of the D455 instead of your custom configuration.  This may occur if a custom stream configuration is deemed by the launch to be invalid.  

Are you using the **ros2-development** wrapper (formerly called ros2_beta) with the D455, please?   If you are using this wrapper (current version 4.51.1) then the wrapper uses a different **profile** method of defining a custom stream configuration.  If you are using wrapper 4.51.1 then please try the launch instruction below to set depth and color to 640x480 at 30 FPS.

**ros2 launch realsense2_camera rs_launch.py depth_module.profile:=640x480x30 rgb_camera.profile:=640x480x30**

**Comment by patrickpoirier51** [comment]
Hello Marty,  Long time no talk

Same result

ros2 launch realsense2_camera rs_launch.py depth_module.profile:=640x480x30 rgb_camera.profile:=640x480x30

[realsense2_camera_node-1] [INFO] [1667331080.522461693] [camera.camera]: Open profile: stream_type: Depth(0), Format: Z16, Width: 640, Height: 480, FPS: 30
[realsense2_camera_node-1] [INFO] [1667331080.523328583] [camera.camera]: Stopping Sensor: RGB Camera
[realsense2_camera_node-1] [INFO] [1667331080.627025190] [camera.camera]: Starting Sensor: RGB Camera
[realsense2_camera_node-1] [INFO] [1667331080.637120267] [camera.camera]: Open profile: stream_type: Color(0), Format: RGB8, Width: 640, Height: 480, FPS: 30
[realsense2_camera_node-1] [INFO] [1667331080.637374921] [camera.camera]: RealSense Node Is Up!


ros2 topic hz /camera/depth/image_rect_raw
average rate: 10.278
	min: 0.066s max: 0.200s std dev: 0.05603s window: 13
average rate: 12.363
	min: 0.066s max: 0.200s std dev: 0.04112s window: 28
average rate: 13.169
	min: 0.066s max: 0.200s std dev: 0.03386s window: 43
average rate: 13.598
	min: 0.066s max: 0.200s std dev: 0.02944s window: 58
average rate: 13.879
	min: 0.066s max: 0.200s std dev: 0.02622s window: 74

**Comment by patrickpoirier51** [comment]
OK , I found it, looking at closed issue
https://github.com/IntelRealSense/realsense-ros/issues/2503

Enabling the auto exposure does the job
ros2 param set /camera/camera depth_module.enable_auto_exposure true

And it shows as an open issues as well here
https://github.com/IntelRealSense/realsense-ros/issues/2507


![image](https://user-images.githubusercontent.com/12484190/199324393-86217e56-6b21-43f3-80fc-29933e7372bd.png)

**Comment by MartyG-RealSense** [comment]
Great to hear that you found a solution.  Thanks very much for the update!

**Comment by MartyG-RealSense** [comment]
Case closed due to solution achieved and no further comments received.

**Comment by SamerKhshiboun** [comment]
see #2507 for more information about this issue.

**Comment by MartyG-RealSense** [comment]
Thanks very much @SamerKhshiboun for the update at https://github.com/IntelRealSense/realsense-ros/issues/2507

**Comment by SamerKhshiboun** [comment]
#2612

**Comment by MartyG-RealSense** [comment]
Hi @patrickpoirier51  Do you require further assistance after the fix implemented by @SamerKhshiboun at 
https://github.com/IntelRealSense/realsense-ros/pull/2612 and merged into the **ros2_development** ROS2 wrapper?  Thanks!

**Comment by patrickpoirier51** [comment]
That's OK , Thanks for the follow-up @MartyG-RealSense

**Comment by MartyG-RealSense** [comment]
You are very welcome - thanks very much!
