### ISSUE TITLE
How to get Color images and depth images which are taken at the same angle

### ISSUE THREAD

**Issue by Xue21** [realsenseai/realsense-ros#2538]
How cam I get  the color and  the depth image at the same time? I want the Color images and depth images which are taken at the same angle.

**Comment by MartyG-RealSense** [comment]
Hi @Xue21  Are you aiming to publish both depth and color streams in the RealSense ROS wrapper, please?  Or are you using the librealsense SDK?

**Comment by Xue21** [comment]
Hi@MartyG-RealSense I am using the librealsense SDK, and I do not want to turn on the laser.

**Comment by MartyG-RealSense** [comment]
Thanks very much for the confirmation.  Are you using C++ or Python language?

**Comment by Xue21** [comment]
Hi@MartyG-RealSense I am using Python

**Comment by MartyG-RealSense** [comment]
The pre-made librealsense Python example program **opencv_viewer_example.py** may provide what you are aiming to achieve if you wish to display separate depth and color images.

https://github.com/IntelRealSense/librealsense/blob/master/wrappers/python/examples/opencv_viewer_example.py

![image](https://user-images.githubusercontent.com/41145062/200863161-ef80d58b-273c-4a12-90d1-9e29f97ea588.png)

If you wish to align depth and color together into a single combined image then the example program **align_depth2color.py** could be used.

https://github.com/IntelRealSense/librealsense/blob/master/wrappers/python/examples/align-depth2color.py

![image](https://user-images.githubusercontent.com/41145062/200864762-93235849-d689-46d5-9b1b-f06bcb9b9299.png)

**Comment by Xue21** [comment]
Hi@MartyG-RealSense, Thanks very much.How can I save it as images or mp4?

**Comment by MartyG-RealSense** [comment]
A Python script at https://github.com/IntelRealSense/librealsense/issues/2731#issuecomment-529938267 saves depth and color into .avi video files.

A RealSense user at https://github.com/IntelRealSense/librealsense/issues/3658 shared an adaptation of align_depth2py they created that saves depth and color as .png images.

A couple of other Python approaches to exporting depth and color as .png images are at https://github.com/IntelRealSense/librealsense/issues/9448#issuecomment-883100431

**Comment by Xue21** [comment]
Hi@MartyG-RealSense,Thanks very much!

**Comment by MartyG-RealSense** [comment]
Hi @Xue21  Do you require further assistance with this case, please?  Thanks!
