### ISSUE TITLE
questions on realsense SR300, how to use the examples 

### ISSUE THREAD

**Issue by ghost** [realsenseai/realsense-ros#254]
### System Configuration
Please complete Your Configuration detail below. Refer to the BKC at [Configuration](../realsense_camera/README.md#configuration).

| Version               | Your Configuration   |
|:--------------------- |:---------------------|
| Operating System      | Ubuntu 14.04               |
| Kernel                | 4.4.0-81-generic                |
| ROS                   | indigo                  |
| ROS RealSense         | SR300                |
| librealsense          | I just installed it               |
| Camera Type-Firmware  | 3.15.0.0        |

---

---

Hey all, 

1. I wonder how can you run tutorials under librealsense/examples? I don't know how to do this in linux...I feel terrible for my programming skills. I have qtcreator installed.

Thank you

**Comment by omershalev** [comment]
I don't think this question is related to realsense-ROS but rather to librealsense.
Please refer to the [librealsene](https://github.com/IntelRealSense/librealsense) repository.
Specifically, follow the [installation guide](https://github.com/IntelRealSense/librealsense/blob/master/doc/installation.md). You don't have to use QTCreator. Make sure to run cmake with `DBUILD_EXAMPLES=true`.
Then you can simply launch any of the examples - the executable files are located under `/usr/local/bin`.

**Comment by dorodnic** [comment]
Hi @Thompson104 
Did you managed to get the examples running? 
I'm closing the issue for now, but please re-open it if you have any additional questions (ROS or librealsense related). We will be happy to assist :)
