### ISSUE TITLE
Ordering of the extrinsic rotation

### ISSUE THREAD

**Issue by geoeo** [realsenseai/realsense-ros#2543]
The rotation in the extrinsic message is defined as float[9]. 
But it does not state explicitly if its row major or column major.

Which one does the array in the extrinsic message represent?

Best,
Marc

**Comment by MartyG-RealSense** [comment]
Hi @geoeo  The official SDK documentation page link below states extrinsic rotation to be **column major**.

https://intelrealsense.github.io/librealsense/python_docs/_generated/pyrealsense2.extrinsics.html

**Comment by geoeo** [comment]
Thanks @MartyG-RealSense !

Thats a pretty obscure link. A mention of this in the Readme.md would be appreciated!

**Comment by MartyG-RealSense** [comment]
I will add a **Enhancement** label to this case to highlight it in the future to Intel RealSense colleagues responsible for documentation.  This case should be kept open but you do not need to take any further action.  Thanks again!

**Comment by SamerKhshiboun** [comment]
@MartyG-RealSense, the fix #2693 was merged. 
You can close this ticket

**Comment by MartyG-RealSense** [comment]
Thanks very much @SamerKhshiboun  :)
