### ISSUE TITLE
How to record a depth video with D415

### ISSUE THREAD

**Issue by Aziz1565** [realsenseai/realsense-ros#2546]
I'm looking to record a depth video of an object where I want to measure how this depth will vary with time, hence I need to record a video for a couple of minutes while having the depth information. Not sure if that is done through python or from the software itself.

Your help is greatly appreciated 

Regards,
Abdulaziz

**Comment by MartyG-RealSense** [comment]
Hi @Aziz1565  You could use the 'Record' button of the RealSense SDK's pre-made **RealSense Viewer** tool to record a video-like sequence to a **bag** format file and play it back in the Viewer or with a program script.  A bag file is like a video recording of camera data.

![image](https://user-images.githubusercontent.com/41145062/201927766-8b020c8f-c39f-4577-bc28-46c9f04decb5.png)

**Comment by Aziz1565** [comment]
> Hi @Aziz1565 You could use the RealSense SDK's pre-made **RealSense Viewer** tool's 'Record' button to record a video-like sequence to a **bag** format file and play it back in the Viewer or with a program script. A bag file is like a video recording of camera data.
> 
> ![image](https://user-images.githubusercontent.com/41145062/201927766-8b020c8f-c39f-4577-bc28-46c9f04decb5.png)

Thank you for your reply.
Yes but in that case, is it possible to get the value of the depth? as I can't extract them manually since it will be a 2 min video with multiple variation in the depth of the object.

**Comment by MartyG-RealSense** [comment]
If you move the mouse cursor over an area of the depth image then the depth value in meters of the coordinate that the cursor is hovered over will be displayed in the bottom corner of the Viewer window.  The depth value updates in real-time as the bag plays.

![image](https://user-images.githubusercontent.com/41145062/201930627-20e5d351-0865-469a-b7e2-4d63229a1e9a.png)

**Comment by Aziz1565** [comment]
> If you move the mouse cursor over an area of the depth image then the depth value in meters of the coordinate that the cursor is hovered over will be displayed in the bottom corner of the Viewer window. The depth value updates in real-time as the bag plays.
> 
> ![image](https://user-images.githubusercontent.com/41145062/201930627-20e5d351-0865-469a-b7e2-4d63229a1e9a.png)

Yes, but is there a way to store these values? since it is continuously changing and I want to obtain a series of depth (all the displayed values over the video length) so I can plot it vs. time later. 

Sorry for any inconvenience

**Comment by MartyG-RealSense** [comment]
It's no trouble at all.  You could convert the bag file to a textual **csv** file (a format compatible with databases and spreadsheets) using the SDK's **rs-convert** bag frame extraction tool.

https://github.com/IntelRealSense/librealsense/tree/master/tools/convert

**Comment by Aziz1565** [comment]
> It's no trouble at all. You could convert the bag file to a textual **csv** file (a format compatible with databases and spreadsheets) using the SDK's **rs-convert** bag frame extraction tool.
> 
> https://github.com/IntelRealSense/librealsense/tree/master/tools/convert

Thank you so much for your help.

Is there a video that can help me in understanding how to work with these tools? 

Again, Thank you for your help

**Comment by MartyG-RealSense** [comment]
You are very welcome!

A wide range of videos are available at the official RealSense YouTube channel.

https://www.youtube.com/c/IntelRealSense/videos

On that channel, an introductory video for the RealSense Viewer tool is here:

https://www.youtube.com/watch?v=BVM1wxE9x0E

**Comment by Aziz1565** [comment]
> You are very welcome!
> 
> A wide range of videos are available at the official RealSense YouTube channel.
> 
> https://www.youtube.com/c/IntelRealSense/videos
> 
> On that channel, an introductory video for the RealSense Viewer tool is here:
> 
> https://www.youtube.com/watch?v=BVM1wxE9x0E

Thank you. I'll check it out
