### ISSUE TITLE
[ROS2] Weird bug when enable pointcloud

### ISSUE THREAD

**Issue by gachiemchiep** [realsenseai/realsense-ros#2552]
Hello RealSensen team
@MartyG-RealSense 

I switch into ROS2 and a weird bug happen.
1. When enable pointcloud, the color and depth images are blurred. Look like it was processed by some filter
![image](https://user-images.githubusercontent.com/2300329/202604926-25d12f6b-8743-4992-b66c-126656a156ab.png)

2. When disable pointcloud, the color and depth images are fine. 
![image](https://user-images.githubusercontent.com/2300329/202605222-61ee3174-69a3-4fa1-bdd7-79d2dcd646c0.png)

Maybe some pointer using for creating pointcloud are messing up. 
Would you mind take a look at this and show me how to fix this problem.

Thank you.

**Comment by MartyG-RealSense** [comment]
Hi @gachiemchiep  What computing device / computer are you using, please (Raspberry Pi, Nvidia Jetson, desktop / laptop PC, etc).  Thanks!

**Comment by gachiemchiep** [comment]
@MartyG-RealSense 
Sorry. realsense is totally fine,  It is a bug in rviz. 
I stop displaying pointcloud then everything become normal again.

**Comment by MartyG-RealSense** [comment]
It's no trouble at all, @gachiemchiep - thanks very much for the update!
