### ISSUE TITLE
Trying to load custom config_file fails

### ISSUE THREAD

**Issue by xkaraman** [realsenseai/realsense-ros#2561]
I am trying to load a custom `config_file` for `realsense-ros` on ROS2 Humble installed from `apt install ros-humble-realsense2-camera`, ubuntu 22.04 but it fails.

Same occurs if building from source with
`git clone https://github.com/IntelRealSense/librealsense.git -b v2.51.1`
`git clone https://github.com/IntelRealSense/realsense-ros.git src/realsense-ros -b 4.51.1`

Error happens when launching like this:
`ros2 launch realsense2_camera rs_launch.py config_file:=/home/ros/realsense2.yaml`

Error is a bit cryptic, and can't get where the error exactly occurs and is:
`[ERROR] [launch]: Caught exception in launch (see debug for traceback): invalid syntax (<string>, line 1)` 

I tried providing even an empty yaml, error still occurs.

**Comment by SamerKhshiboun** [comment]
Hi @xkaraman,
please try wrapping your path with quotes as you can see in the rs_launch.py 
use both " and ' one inside the other, for example:
`ros2 launch realsense2_camera rs_launch.py config_file:="'/home/ros/realsense2.yaml'"
`

Let me know if this works.

**Comment by MartyG-RealSense** [comment]
Thanks so much @SamerKhshiboun for your assistance to @xkaraman  :)

**Comment by xkaraman** [comment]
Seems about right!! Thanks @SamerKhshiboun.
Is there a reason for it though? It's kind of counter-intuitive!

**Comment by MartyG-RealSense** [comment]
Hi @xkaraman  Do you require further assistance with this case, please?  Thanks!

**Comment by xkaraman** [comment]
No thanks @MartyG-RealSense. I will close this issue!

**Comment by MartyG-RealSense** [comment]
Thanks very much @xkaraman for the update!
