### ISSUE TITLE
can't able to open L515 camera

### ISSUE THREAD

**Issue by Daya-AWR1642** [realsenseai/realsense-ros#2567]
I followed installation guideline for Ubuntu 20.04  from:
https://github.com/IntelRealSense/realsense-ros#installation-instructions
when I run the "ros2 launch realsense2_camera rs_launch.py" this line in terminal I'm getting like this:

dayananda@dayananda-Inspiron-3501:~/ros2_ws$ ros2 launch realsense2_camera rs_launch.py
[INFO] [launch]: All log files can be found below /home/dayananda/.ros/log/2022-12-02-16-39-04-582379-dayananda-Inspiron-3501-5443
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [realsense2_camera_node-1]: process started with pid [5445]
[realsense2_camera_node-1] [INFO] [1669979344.917238612] [camera.camera]: RealSense ROS v4.51.1
[realsense2_camera_node-1] [INFO] [1669979344.917467097] [camera.camera]: Built with LibRealSense v2.51.1
[realsense2_camera_node-1] [INFO] [1669979344.917513965] [camera.camera]: Running with LibRealSense v2.51.1
[realsense2_camera_node-1] [INFO] [1669979345.157759419] [camera.camera]: Device with serial number f1321376 was found.
[realsense2_camera_node-1] 
[realsense2_camera_node-1] [INFO] [1669979345.157884946] [camera.camera]: Device with physical ID /sys/devices/pci0000:00/0000:00:14.0/usb2/2-2/2-2:1.0/video4linux/video2 was found.
[realsense2_camera_node-1] [INFO] [1669979345.157911647] [camera.camera]: Device with name Intel RealSense L515 was found.
[realsense2_camera_node-1] [INFO] [1669979345.158423800] [camera.camera]: Device with port number 2-2 was found.
[realsense2_camera_node-1] [INFO] [1669979345.158452760] [camera.camera]: Device USB type: 3.2
[realsense2_camera_node-1] [INFO] [1669979345.160756414] [camera.camera]: getParameters...
[realsense2_camera_node-1] [INFO] [1669979345.161212455] [camera.camera]: JSON file is not provided
[realsense2_camera_node-1] [INFO] [1669979345.161248280] [camera.camera]: Device Name: Intel RealSense L515
[realsense2_camera_node-1] [INFO] [1669979345.161273075] [camera.camera]: Device Serial No: f1321376
[realsense2_camera_node-1] [INFO] [1669979345.161291523] [camera.camera]: Device physical port: /sys/devices/pci0000:00/0000:00:14.0/usb2/2-2/2-2:1.0/video4linux/video2
[realsense2_camera_node-1] [INFO] [1669979345.161311069] [camera.camera]: Device FW version: 01.05.04.01
[realsense2_camera_node-1] [INFO] [1669979345.161331631] [camera.camera]: Device Product ID: 0x0B64
[realsense2_camera_node-1] [INFO] [1669979345.161350253] [camera.camera]: Sync Mode: Off
[realsense2_camera_node-1] [INFO] [1669979345.168578669] [camera.camera]: Set ROS param depth_module.profile to default: 640x480x30
[realsense2_camera_node-1] [INFO] [1669979345.170549777] [camera.camera]: Set ROS param rgb_camera.profile to default: 1280x720x30
[realsense2_camera_node-1] [INFO] [1669979345.170735904] [camera.camera]: Set ROS param gyro_fps to default: 100
[realsense2_camera_node-1] [INFO] [1669979345.170768514] [camera.camera]: Set ROS param accel_fps to default: 200
[realsense2_camera_node-1] [WARN] [1669979345.174431029] [camera.camera]: Could not set param: pointcloud.stream_index_filter with -1 Range: [-1, -2147483648]: parameter 'pointcloud.stream_index_filter' could not be set: Parameter {} doesn't comply with integer range.
[realsense2_camera_node-1] [INFO] [1669979345.174856031] [camera.camera]: Stopping Sensor: L500 Depth Sensor
[realsense2_camera_node-1] [INFO] [1669979345.176856616] [camera.camera]: Starting Sensor: L500 Depth Sensor
[realsense2_camera_node-1] [INFO] [1669979345.195438080] [camera.camera]: Open profile: stream_type: Confidence(0), Format: RAW8, Width: 640, Height: 480, FPS: 30
[realsense2_camera_node-1] [INFO] [1669979345.195519052] [camera.camera]: Open profile: stream_type: Infra(0), Format: Y8, Width: 640, Height: 480, FPS: 30
[realsense2_camera_node-1] [INFO] [1669979345.195532473] [camera.camera]: Open profile: stream_type: Depth(0), Format: Z16, Width: 640, Height: 480, FPS: 30
[realsense2_camera_node-1] [INFO] [1669979345.195733064] [camera.camera]: Stopping Sensor: RGB Camera
[realsense2_camera_node-1] [INFO] [1669979345.388084822] [camera.camera]: Starting Sensor: RGB Camera
[realsense2_camera_node-1] [INFO] [1669979345.394859170] [camera.camera]: Open profile: stream_type: Color(0), Format: RGB8, Width: 1280, Height: 720, FPS: 30
[realsense2_camera_node-1] [INFO] [1669979345.395600183] [camera.camera]: RealSense Node Is Up!
[realsense2_camera_node-1] [WARN] [1669979346.187190035] [camera.camera]: 
[realsense2_camera_node-1] [WARN] [1669979346.187275039] [camera.camera]: frame's time domain is HARDWARE_CLOCK. Timestamps may reset periodically.

But camera is not opening

**Comment by MartyG-RealSense** [comment]
Hi @Daya-AWR1642  You can first check whether the camera's topics are being published after launch has completed by inputting the command **ros2 topic list**

You could also try unplugging the micro-sized end of the USB cable from the base of the L515 camera, reversing the connector's orientation and plugging it back into the camera to see whether performance improves (USB-C cables are two-way insertion at the micro-sized end).

The warning about the HARDWARE_CLOCK may be occurring because on the L515 camera model, a feature called **global time** is disabled by default, whereas on 400 Series camera models global time is enabled by default.  If global time is disabled then hardware time is used for the camera's timestamps.

**Comment by Daya-AWR1642** [comment]
I got this 
dayananda@dayananda-Inspiron-3501:~/ros2_ws$ ros2 topic list
/parameter_events
/rosout

**Comment by MartyG-RealSense** [comment]
It is unusual that no camera topics are listed as you have no significant warning messages after the completion of launch with the **RealSense Node Is Up!** message, indicating that the launch was successful.

Can the camera display streams correctly in the RealSense Viewer tool?

**Comment by Daya-AWR1642** [comment]
yes, it will

**Comment by MartyG-RealSense** [comment]
Do the topics publish if you add **initial_reset:=true** to your launch instruction to reset the camera at launch?

`ros2 launch realsense2_camera rs_launch.py initial_reset:=true`

**Comment by Daya-AWR1642** [comment]
![Screenshot from 2022-12-03 15-37-27](https://user-images.githubusercontent.com/102849011/205435586-2f099062-9d97-413f-91e3-6cc0e5aee9a5.png)


But still not getting

**Comment by MartyG-RealSense** [comment]
Global time can be enabled by adding **global_time_enabled:=true** to your launch instruction.

Your camera's firmware driver is also somewhat old at version **1.5.4.1** and so I would recommend updating to version **1.5.8.1**, the newest version available for L515.  The update can be performed in the RealSense Viewer. 

https://dev.intelrealsense.com/docs/firmware-releases-l500#l500-series-firmware-downloads

**Comment by Daya-AWR1642** [comment]
![Screenshot from 2022-12-03 16-44-41](https://user-images.githubusercontent.com/102849011/205442224-1f835346-85b9-446d-81d7-07f2fae5bc4e.png)


still no

**Comment by MartyG-RealSense** [comment]
I cannot see anything in the logs that would indicate a problem with publishing the topics, and the camera works normally with the RealSense Viewer.

When you perform the ROS launch, is the ROS terminal the only program that you have open and you do not have any other RealSense programs such as the RealSense Viewer already running?

Did you also test reversing the USB connector as suggested earlier at https://github.com/IntelRealSense/realsense-ros/issues/2567#issuecomment-1335285691

**Comment by Daya-AWR1642** [comment]
Hi
I can launch camera through ros2
Thank you

**Comment by MartyG-RealSense** [comment]
You are very welcome.  Thanks very much for the confirmation that you can launch the camera in ROS2.

**Comment by MartyG-RealSense** [comment]
Hi @Daya-AWR1642  Do you require further assistance with this case, please?  Thanks!

**Comment by Daya-AWR1642** [comment]
No, Thanks

**Comment by MartyG-RealSense** [comment]
Thanks very much for the update!
