### ISSUE TITLE
Spinnaker SDK disconnects Realsense

### ISSUE THREAD

**Issue by samraise** [realsenseai/realsense-ros#2569]
I'm trying to use a Realsense D435i camera alongside a FLIR Blackfly. When I launch the [FLIR camera driver](https://github.com/ros-drivers/flir_camera_driver), the Realsense driver fails to locate the d435i with the following error:

```
 05/12 10:06:25,759 ERROR [281472258334960] (librealsense-exception.h:52) acquire: Cannot open '/dev/video0 Last Error: No such file or directory
 05/12 10:06:25,759 ERROR [281472258334960] (global_timestamp_reader.cpp:239) Error during time_diff_keeper polling: acquire: Cannot open '/dev/video0 Last Error: No such file or directory
 05/12 10:06:25,824 ERROR [281471969054960] (backend-v4l2.cpp:329) xioctl(VIDIOC_QBUF) failed when requesting new frame! fd: 22 error: No such device
 05/12 10:06:25,824 ERROR [281471969054960] (backend-v4l2.cpp:329) xioctl(VIDIOC_QBUF) failed when requesting new frame! fd: 27 error: No such device
 05/12 10:06:25,836 ERROR [281471814197488] (librealsense-exception.h:52) get_xu(...). xioctl(UVCIOC_CTRL_QUERY) failed Last Error: No such device
 05/12 10:06:25,836 ERROR [281471814197488] (librealsense-exception.h:52) get_xu(...). xioctl(UVCIOC_CTRL_QUERY) failed Last Error: No such device
 05/12 10:06:26,525 ERROR [281472023916784] (librealsense-exception.h:52) get_xu(...). xioctl(UVCIOC_CTRL_QUERY) failed Last Error: No such device
 05/12 10:06:26,525 ERROR [281472023916784] (error-handling.cpp:78) Error during polling error handler: get_xu(...). xioctl(UVCIOC_CTRL_QUERY) failed Last Error: No such device
 05/12 10:06:26,759 ERROR [281472258334960] (librealsense-exception.h:52) acquire: Cannot open '/dev/video0 Last Error: No such file or directory
 05/12 10:06:26,759 ERROR [281472258334960] (global_timestamp_reader.cpp:239) Error during time_diff_keeper polling: acquire: Cannot open '/dev/video0 Last Error: No such file or directory
```

Could I please get some help on how I might be able to resolve this?

**Comment by MartyG-RealSense** [comment]
Hi @samraise  **xioctl(UVCIOC_CTRL_QUERY** errors are typically related to a conflict with the Linux kernel.  If the librealsense SDK is built from source code with CMake using the **RSUSB backend** installation method then librealsense will bypass the kernel.  This means that the SDK is not dependent on Linux versions or kernel versions and does not require kernel patching.  Instructions for an RSUSB installation can be found at https://github.com/IntelRealSense/librealsense/issues/9931#issuecomment-964289692

**Comment by MartyG-RealSense** [comment]
Hi @samraise  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.

**Comment by drago314** [comment]
I am experiencing this issue as well. If I use the spinnaker library in c++ code, accessing a flir camera breaks all references my intel realsense depth camera. If I use the spinnaker library, the code which accesses the depth camera segfaults until I unplug and replug the depth camera, which means that I cannot use both cameras at once. @MartyG-RealSense

**Comment by drago314** [comment]
Update: @MartyG-RealSense 's comment of using a RSUSB installation fixed the problem and saved me another 7 hours of debugging. Thanks!

https://github.com/IntelRealSense/librealsense/issues/9931#issuecomment-964289692

**Comment by MartyG-RealSense** [comment]
Hi @drago314  It's great to hear that you were successful.  Thanks very much for the update!
