### ISSUE TITLE
Error while  roslaunch realsense2_camera rs_camera.launch

### ISSUE THREAD

**Issue by afdzxbrs** [realsenseai/realsense-ros#2570]
process[camera/realsense2_camera_manager-1]: started with pid [11637]
process[camera/realsense2_camera-2]: started with pid [11638]
[ INFO] [1670397875.637490240]: Initializing nodelet with 2 worker threads.
[ERROR] [1670397875.678261405]: Failed to load nodelet [/camera/realsense2_camera] of type [realsense2_camera/RealSenseNodeFactory] even after refreshing the cache: Could not find library corresponding to plugin realsense2_camera/RealSenseNodeFactory. Make sure the plugin description XML file has the correct name of the library and that the library actually exists.
[ERROR] [1670397875.678460964]: The error before refreshing the cache was: Could not find library corresponding to plugin realsense2_camera/RealSenseNodeFactory. Make sure the plugin description XML file has the correct name of the library and that the library actually exists.
[FATAL] [1670397875.685944977]: Failed to load nodelet '/camera/realsense2_camera` of type `realsense2_camera/RealSenseNodeFactory` to manager `realsense2_camera_manager'
[camera/realsense2_camera-2] process has died [pid 11638, exit code 255, cmd /opt/ros/melodic/lib/nodelet/nodelet load realsense2_camera/RealSenseNodeFactory realsense2_camera_manager __name:=realsense2_camera __log:=/home/ros/.ros/log/03eea404-75fb-11ed-be8b-e4aaea8a25d5/camera-realsense2_camera-2.log].
log file: /home/ros/.ros/log/03eea404-75fb-11ed-be8b-e4aaea8a25d5/camera-realsense2_camera-2*.log

**Comment by MartyG-RealSense** [comment]
Hi @afdzxbrs  Is the advice in the similar case at https://github.com/IntelRealSense/realsense-ros/issues/611 of help to you, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Hi @afdzxbrs  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
