### ISSUE TITLE
Camera's frame id should be configurable

### ISSUE THREAD

**Issue by nakai-omer** [realsenseai/realsense-ros#2571]
Hello,

After struggling to figure out why we are not getting correct transformations, we found that this lib forces the camera's link to be named `camera_link`, otherwise transformations aren't valid. In our case the camera's link is called `base_camera_link`, as we have multiple cameras. 
It will be very helpful for the camera's link to be configurable, so existing robot descriptions don't need to be re-written just because we changed our camera to a realsense one. Re-writing the urdf, also affects having to re-import the robot to tools like Isaac Sim, and redo all the sensor configurations there etc. This might also fix issues with multiples cameras and their transformations.

This is the relevant part of our tf tree:
![image](https://user-images.githubusercontent.com/108797279/206141299-87b15620-16b0-4523-a496-34ec7d3237a4.png)

**Comment by nakai-omer** [comment]
After some more investigation we found that there is an undocumented parameter called: `camera_name`, which affects frame ids prefix. This param is not mentioned at the documentation: https://dev.intelrealsense.com/docs/ros-wrapper, and only vaguely mentioned under `Please notice: if you are moving from RealSense [ROS2-legacy branch](https://github.com/IntelRealSense/realsense-ros/tree/ros2-legacy) to ROS2-development:` in the readme (which when not moving from ros2-legacy causes you to skip over it).

**Comment by MartyG-RealSense** [comment]
Hi @nakai-omer  As you are using multiple cameras, you may find it useful to use the ROS2 wrapper's **rs_multi_camera_launch.py** launch file for launching more than one camera so that the launch file takes care of naming the cameras.

https://github.com/IntelRealSense/realsense-ros/blob/ros2-development/realsense2_camera/launch/rs_multi_camera_launch.py

The ROS1 wrapper's equivalent multicam launch file is **rs_multiple_devices.launch**

https://github.com/IntelRealSense/realsense-ros/tree/ros1-legacy#work-with-multiple-cameras

**Comment by nakai-omer** [comment]
@MartyG-RealSense We are using a single camera, we just gave it a different link name, which is not `camera_link`, and we had to look through the code to figure out what to change the frame names in this package.

**Comment by MartyG-RealSense** [comment]
Whilst I am not aware of any current plans to create such a feature, I have set a **wait to close** label on this issue to keep it open.  Other RealSense ROS users are welcome to comment in support of adding such a feature if they believe that it would be advantageous to them.

**Comment by nakai-omer** [comment]
@MartyG-RealSense I think there is a misunderstanding. See my second comment please. It does exist, it is just not documented. There is `camera_name` param, that doesn't exist in the documentation, but exists in code. It needs to be added to https://dev.intelrealsense.com/docs/ros-wrapper

**Comment by MartyG-RealSense** [comment]
Thanks very much for the clarification.  You are correct that there is a short reference to `camera_name` in the ROS2 wrapper documentation section about moving from ros2_legacy.

![image](https://user-images.githubusercontent.com/41145062/207081207-94d8bb16-5e1d-41f6-930b-b231fc5d89b6.png)

I will highlight to the RealSense ROS team your request to make camera_name more prominent in the wrapper instructions.

**Comment by Nir-Az** [comment]
https://dev.intelrealsense.com/docs/ros-wrapper currently holds a list of examples and parameters for ROS1,
We are about to update this list for ROS2, with that we will address this issue as well.
Thanks for notifying

**Comment by MartyG-RealSense** [comment]
Hi @nakai-omer  Bearing in mind the advice from @Nir-Az in the above comment, do you require further assistance with this case please?  Thanks!

**Comment by nakai-omer** [comment]
@MartyG-RealSense no thanks a alot

**Comment by MartyG-RealSense** [comment]
You are very welcome, @nakai-omer - thanks very much for the update!
