### ISSUE TITLE
Depth image is not aliged to RGB image (ros2) 

### ISSUE THREAD

**Issue by jwson97** [realsenseai/realsense-ros#2573]
Hi, I am using 435i.
I'm trying to recognize an object and figure out the distance. 
I perform object detection on the rgb image and get the distance from the depth image. 
But RGB image is not aligned with Depth image. 

$ ros2 launch realsense2_camera rs_launch.py depth_module.profile:=848x480x15 rgb_camera.profile:=848x480x15 align_depth.enable:=true enable_sync:=true enable_gyro:=true enable_accel:=true 

In the first image, the location of the red dot is on edge of board, but in the depth image, points with the same coordinates is not on the edge of board.

![Screenshot from 2022-12-08 13-54-50](https://user-images.githubusercontent.com/42993434/206360531-9f59d913-bcc6-46af-bdc7-c4945142742a.png)

Did I miss some parameter setting?

**Comment by jwson97** [comment]
Sorry I solved it with rs.align.

**Comment by jwson97** [comment]
It published on different topic. It woks.

**Comment by MartyG-RealSense** [comment]
Thanks very much @jwson97 for the updates - it's excellent news that you succeeded!
