### ISSUE TITLE
Opensource Tracking

### ISSUE THREAD

**Issue by alvaropascuaI** [realsenseai/realsense-ros#2576]
Hi, I'm trying  to launch file opensource_tracking.launch, but i have error in ros topics i dont know if with only launch file all ready works or i need to launch something more? I follow next video but dont work in viewer, i change some topic but i dont know what i need to change more

![image](https://user-images.githubusercontent.com/97975075/207030460-cbe032b5-0ef8-4193-8972-ea1cce05efd2.png)

**Comment by MartyG-RealSense** [comment]
Hi @alvaropascuaI  Are you using a RealSense camera model that is equipped with an IMU (D435i, D455 or L515).

If you have one of these cameras, have you enabled the IMU topics please, as these are disabled by default in the RealSense ROS wrapper.

`roslaunch realsense2_camera opensource_tracking.launch enable_accel:=true enable_gyro:=true unite_imu_method:=linear_interpolation`

**Comment by alvaropascuaI** [comment]
I am using d435i, but if i launch with this command i have the same problem in topics i dont know what i need to put in configuration, i follow this [tutorial](https://www.youtube.com/watch?v=mguXtybmZv4), but dont generate map

**Comment by MartyG-RealSense** [comment]
Your image shows that a color image and a pointcloud are being generated in Rviz.  What are the ROS topic errors that you are receiving, please?

In the **Frames** section of the RViz options, did you untick all settings except **camera_link** and **map**

![image](https://user-images.githubusercontent.com/41145062/207042304-c20fd9b4-a3ee-49ea-89cb-32e6ad5a9cec.png)

**Comment by alvaropascuaI** [comment]
If i launch with this command `roslaunch realsense2_camera opensource_tracking.launch enable_accel:=true enable_gyro:=true unite_imu_method:=linear_interpolation` in terminal i have next error 
![image](https://user-images.githubusercontent.com/97975075/207043260-285c69e2-9d57-43a9-a080-950bae389e57.png)

In TF Frames i have next
![image](https://user-images.githubusercontent.com/97975075/207043437-e842cb2d-5575-48c3-bd0c-b65897ba6048.png)

**Comment by MartyG-RealSense** [comment]
Assuming that the video is based on Intel's D435i SLAM guide at the link below, did you install the prerequisite modules **rtabmap_ros**, **imu_filter_madgwick** and **robot_localization**

https://github.com/IntelRealSense/realsense-ros/wiki/SLAM-with-D435i

As mentioned above, when using this guide you should also untick everything under Frames except camera_link and map

**Comment by alvaropascuaI** [comment]
I install the modules of rtabmap_ros, imu_filter_madgwick and robot_localization and work worse than before in TF Frames i can check the same topics, and i have the next error in terminal, i try to install another time the realsense-ros-noetic but nothing

![image](https://user-images.githubusercontent.com/97975075/207049064-f40f9f71-8113-428e-824e-d271b5ea95ba.png)

**Comment by MartyG-RealSense** [comment]
A Noetic user of the SLAM guide at https://github.com/IntelRealSense/realsense-ros/issues/2494 experienced the same errors.  I suggested using the Noetic version of the modules instead of the original Kinetic ones in the guide.

****************

sudo apt-get install ros-noetic-robot-localization

sudo apt-get install ros-noetic-rtabmap-ros

sudo apt install ros-noetic-imu-filter-madgwick

**Comment by alvaropascuaI** [comment]
I launch your commands and i try another time to run opensource file but nothing.
If i launch camera instead of rviz already works but i think the only thing that i miss is the topic of MapCloud, you know how i can generate?

**Comment by MartyG-RealSense** [comment]
The **Viewing Map Data** section of the guide at the link below states that when running RTABmap in mapping mode, you can open rviz and add the **MapCloud** panel.  Then configure the listening topic as `/rtabmap/mapData` and activate the checkbox **Download map**.

https://admantium.medium.com/ros-simultaneous-mapping-and-localization-with-rtabmap-e527e6a6716

**Comment by alvaropascuaI** [comment]
How i can activate in camera D455 option of stereo with ros?

**Comment by MartyG-RealSense** [comment]
Could you provide more information please about what you mean about activating stereo with ROS?  Thanks!

**Comment by alvaropascuaI** [comment]
I want to launch this [file](https://github.com/introlab/rtabmap_ros/blob/ros2/launch/demo/demo_stereo_outdoor.launch) with camera D455 because i read [here](https://www.intel.es/content/www/es/es/products/sku/205847/intel-realsense-depth-camera-d455/specifications.html) he used a tecnology stereo but i think im confused
![Captura de pantalla de 2022-12-13 10-00-40](https://user-images.githubusercontent.com/97975075/207273377-8f34eeaa-d1ec-417d-bb85-728e25ab6e1c.png)

**Comment by MartyG-RealSense** [comment]
Thanks very much for the clarification.  This rtabmap_ros launch file can be launched with the instruction below.

`roslaunch rtabmap_ros demo_stereo_outdoor.launch`

This may be a situation though where you would need to launch the RealSense ROS wrapper first.

`roslaunch realsense2_camera opensource_tracking.launch enable_accel:=true enable_gyro:=true unite_imu_method:=linear_interpolation`

And then launch the rtabmap_ros launch file secondly after the RealSense ROS wrapper has completed launching.

`roslaunch rtabmap_ros demo_stereo_outdoor.launch`

**Comment by MartyG-RealSense** [comment]
Hi @alvaropascuaI  Do you require further assistance with this case, please?  Thanks!

**Comment by alvaropascuaI** [comment]
Sorry, I thought that I answered you, I deleted everything and then I installed everything again, but in rviz I see this
In tf frames I have the following, the map frame is missing
![image](https://user-images.githubusercontent.com/97975075/208383413-5cff8175-1761-4134-85b1-ea6ac55ae035.png)
![image](https://user-images.githubusercontent.com/97975075/208383458-b66bfbf0-289a-486d-af9e-497a38fd272c.png)

**Comment by MartyG-RealSense** [comment]
Fixed Frame is set to 'camera_link' instead of **map** like it was in your earlier image.

![image](https://user-images.githubusercontent.com/41145062/208385629-40f1b9ec-6c3b-4b05-a5b5-4aaa22a82103.png)

Once Fixed Frames is changed to 'map', it should appear in the Frames list.  Untick everything in that list except **camera_link** and **map**.

**Comment by alvaropascuaI** [comment]
I can launch the opensource.launch file with 1 camera but I want with 2 cameras but if I try to launch both cameras at the same time for the same issues but it breaks I don't know how can I launch 2 cameras with opensource.launch

**Comment by MartyG-RealSense** [comment]
Are you able to launch with two cameras if you have two seperate ROS terminals open (one for each camera) with the two cameras distinguished by their serial numbers and a defined camera name?

**Terminal 1**
`roslaunch realsense2_camera opensource_tracking.launch enable_accel:=true enable_gyro:=true unite_imu_method:=linear_interpolation camera:=cam_1 serial_no:= camera:=cam_1 serial_no:=<serial number of the first camera>`

**Terminal 2**
`roslaunch realsense2_camera rs_opensource_tracking.launch enable_accel:=true enable_gyro:=true unite_imu_method:=linear_interpolation camera:=cam_1 serial_no:= camera:=cam_2 serial_no:=<serial number of the second camera>`

**Comment by alvaropascuaI** [comment]
If I do that, I can start both cameras, but I don't know how I can use the opensource file to rebuild with 2 cameras, because I thought that if I send information from 2 cameras for the same themes, rviz can do the rebuild, because I don't know how. You can do the reconstruction with 2 cameras and save the map cloud, I can't think of anything else because I tried with RTABMAP but it doesn't work

**Comment by MartyG-RealSense** [comment]
In Intel's guide for creating a combined pointcloud from two cameras and displaying it in RViz, they also launch the cameras in separate ROS terminals.  

In Step 3 of the guide they publish a spatial connection between the cameras in a third ROS terminal (calling them cam_1_link and cam_2_link)..

Then in Step 4, in RViz they set Fixed Frame to the link name for it that was defined in Step 3 and add a topic from each camera.

```
Set “Fixed Frame” to “cam_1_link”
Add -> By topic -> /cam_1/depth/color/points/PointCloud2
Add -> By topic -> /cam_2/depth/color/points/PointCloud2
```

https://github.com/IntelRealSense/realsense-ros/wiki/Showcase-of-using-2-cameras

**Comment by alvaropascuaI** [comment]
Yes, i do the guide you told me but is only viewer and i need to generate a map cloud with 2 cameras, you understand me ?

**Comment by MartyG-RealSense** [comment]
Yes, I understand you.

I recall that a RealSense ROS user asked the Intel RealSense team member who was the developer of the RealSense ROS1 wrapper about the possibility of obtaining the orientations of two cameras using an edited version of opensource_tracking.launch for handling two cameras instead of one.  The wrapper creator responded to the question at https://github.com/IntelRealSense/realsense-ros/issues/1609#issuecomment-755169040

There was also another RealSense ROS user who attempted to adapt the D435i SLAM guide to use opensource_tracking.launch for two cameras and they did not succeed.

**Comment by alvaropascuaI** [comment]
I want to launch the open source file with saved topics in ROS 2 and convert them to ROS 1 in order to use the open source file with the rosbags-convert library but I get the following error

![image](https://user-images.githubusercontent.com/97975075/208660230-425f9a12-e27d-4e78-b49a-c035939076de.png)

**Comment by MartyG-RealSense** [comment]
The ROS2 to ROS1 / ROS1 to ROS2 message bridging project at https://github.com/ros2/ros1_bridge may be helpful for cross-communication between ROS2 and ROS1.

**Comment by alvaropascuaI** [comment]
In my ROS1 if I launch the file like this it works for me I wanted to leave the most basic to try to replicate it in ROS 2, I also launch the camera separately with the following command

ROS 1
`roslaunch realsense2_camera rs_camera.launch initial_reset:=true enable_pointcloud:=true align_depth:=true`
ROS 2
`ros2 launch realsense2_camera rs_launch.py initial_reset:=true enable_pointcloud:=true serial_no:=_153222070827 align_depth:=true`
![image](https://user-images.githubusercontent.com/97975075/208851683-468e841a-7bba-4212-9dd4-e4fe60b3a0ac.png)

and in ROS 2 for try to replicate the opensource file i launch next

`ros2 launch rtabmap_ros rtabmap.launch.py args:="--delete_db_on_start" rgb_topic:=/camera/color/image_raw depth_topic:=/camera/aligned_depth_to_color/image_raw camera_info_topic:=/camera/color/camera_info depth_camera_info_topic:=/camera/depth/camera_info rtabmapviz:=false rviz:=true`

when rviz open dont see nothing and i have the next 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/97975075/208860137-7f02887c-2f4f-40ac-9cd3-35cf6e5d3880.png)

**Comment by MartyG-RealSense** [comment]
I recalled that we have previously discussed the subject of replicating opensource_tracking in ROS2 in August 2022 at https://github.com/IntelRealSense/realsense-ros/issues/2434#issuecomment-1205115900 and you also had problems with RViz then too.

A few days ago at https://github.com/IntelRealSense/realsense-ros/issues/2574#issuecomment-1356723219 I suggested to another RealSense ROS user to use **slam_toolbox** for SLAM in ROS2.

**Comment by alvaropascuaI** [comment]
Yes, but in August i wanted launch with 1 camera to do reconstruction 3d and i found RTABMAP and works, but i need do it a reconstruction with 2 cameras and with RTABMAP i cant works

Regarding the slam_toolbox repository, it generates a 2D map for you and what I want is to generate a 3D map, even so, thank you very much

**Comment by MartyG-RealSense** [comment]
A discussion at https://github.com/introlab/rtabmap_ros/issues/459 about using two RealSense cameras with rtabmap_ros suggests that rtabmap_ros does not have dual camera support by default but can use multiple cameras if it is installed by cloning its source and catkin-make building it with the term **-DRTABMAP_SYNC_MULTI_RGBD=ON** included.

**Comment by MartyG-RealSense** [comment]
Hi @alvaropascuaI  Was the advice in the above comment helpful, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Hi @alvaropascuaI  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.

**Comment by alvaropascuaI** [comment]
Hi @MartyG-RealSense, I was on vacation, I finally used NerfStudio for the rebuild, I am able to generate cloud maps as the rgb camera images work fine, thanks for everything

**Comment by MartyG-RealSense** [comment]
That's great to hear that you achieved a solution, @alvaropascuaI - thanks very much for the update!
