### ISSUE TITLE
D435i cause system crash

### ISSUE THREAD

**Issue by huangdy11** [realsenseai/realsense-ros#2578]
when i use D435i camera :roalaunch realsense2_camera rs_rgbd.launch, or other launch files ,   it happens frequently that after running for a while ,ubuntu system suddenly crashes,  and nothing i can do but to shut the computer by force with  power button.
my system is 18.04

**Comment by MartyG-RealSense** [comment]
Hi @huangdy11  I recommend first checking for the possibility of a **memory leak**, which is where the computer's available memory capacity is progressively consumed over time until applications become unstable and may crash.  This check can be performed with an Ubuntu system monitoring tool such as **htop** whilst an application such as a launched ROS session is running.

**Comment by MartyG-RealSense** [comment]
Hi @huangdy11  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
