### ISSUE TITLE
Allow the wrapper to publish the aligned and the raw pointclouds simultaneusly

### ISSUE THREAD

**Issue by pepisg** [realsenseai/realsense-ros#2586]
I apologize in advance if this has already been asked

I was wandering if its possible to activate a pointcloud publisher for both the aligned and the raw depth streams simultaneously.

Currently it looks like only one pointcloud can be published (the aligned one if alignment is enabled and the raw otherwise) even if both depth images are available.

Thanks in advance for your help!

**Comment by MartyG-RealSense** [comment]
Hi @pepisg  I am not aware of a method of publishing two separate pointclouds (original and aligned) simultaneously from the same camera in the RealSense ROS wrapper, unfortunately.

**Comment by pepisg** [comment]
I'm sorry to hear that.
Is this something that could be easily implemented in the current architecture? would you be able to point me on the right direction on how to implement this?

**Comment by MartyG-RealSense** [comment]
It is possible to create and display two separate pointclouds (original and processed) in the librealsense SDK, like in the SDK's **rs-post-processing** C++ example at the link below.

https://github.com/IntelRealSense/librealsense/tree/master/examples/post-processing

In regard to ROS, the only approach that I can think of would be to convert depth data to a pointcloud with **depth_image_proc**.

http://wiki.ros.org/depth_image_proc

A pointcloud can be published via depth_image_proc by the RealSense ROS1 wrapper if the launch file **rs_rgbd.launch** is used, as described at https://github.com/IntelRealSense/realsense-ros/issues/2454#issuecomment-1221254065

**Comment by MartyG-RealSense** [comment]
Hi @pepisg  Was the advice in the above comment helpful to you, please?  Thanks!

**Comment by pepisg** [comment]
It was! Its a pity that the driver does not support this out of the box though, that would be something I would personally find very useful.

Thanks @MartyG-RealSense !

**Comment by MartyG-RealSense** [comment]
You are very welcome, @pepisg   :)

**Comment by MartyG-RealSense** [comment]
Hi @pepisg  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
