### ISSUE TITLE
D405 URDF Description

### ISSUE THREAD

**Issue by vonHartz** [realsenseai/realsense-ros#2589]
Hi everyone,

following up on #2317, there still seems to be no URDF description for the D405.
When will this be resolved?

Cheers

**Comment by MartyG-RealSense** [comment]
Hi @vonHartz  I will raise the issue with the RealSense ROS developer team.  Thanks very much for your question!

**Comment by MartyG-RealSense** [comment]
Hi @vonHartz  The RealSense ROS developer team has advised me that the addition of a URDF for D405 is planned for a future wrapper release.

**Comment by vonHartz** [comment]
Thanks for your reply @MartyG-RealSense 
Do you have an estimated release date?

**Comment by MartyG-RealSense** [comment]
I do not have a time estimate for implementation at the time of writing this, unfortunately.

**Comment by MartyG-RealSense** [comment]
As URDF for D405 is planned for a future release, I have added an **Enhancement** tag to this issue so that it is kept open.

**Comment by chavasse** [comment]
+1 for this

**Comment by weaponeer** [comment]
As well, ++

**Comment by SamerKhshiboun** [comment]
Hi @chavasse, @weaponeer, @vonHartz, 
While we are working to add D405 URDF, 
If you can work with dae / step / stl files, this is a good workaround for you:
You can download the cad file of D405 from [here](https://www.intelrealsense.com/wp-content/uploads/2022/04/Intel_RealSense_D405_CAD_external.zip?_ga=2.66583914.577000463.1681198060-1846334074.1674552675)

Then you can convert this STEP file to dae and stl files 
(I managed to download FreeCAD, and convert (File -> Export) these STEP file to .stl and .dae files)

You can import this dae file into your urdf.
For example:
```
<link name="my_link">
  <visual>
    <origin xyz="0 0 0" rpy="0 0 0"/>
    <geometry>
      <mesh filename="path/to/my_file.dae"/>
    </geometry>
  </visual>
</link>
```

**Comment by MartyG-RealSense** [comment]
Hi @chavasse @weaponeer and @vonHartz  Was the information in the above comment helpful to you, please?  Thanks!

**Comment by chavasse** [comment]
Hi @MartyG-RealSense not really, sorry!
The information needed is stored in the URDF model with the links and offsets between the mechanical fastening point(s) and camera frames to get accurate positioning. It's all information that is in the datasheet so we can work around it, but it's a bit clunky and should really be handled/published by this package.
Thanks

**Comment by MartyG-RealSense** [comment]
Hi @chavasse  No problem, thanks very much for your feedback!

**Comment by weaponeer** [comment]
Thanks for the suggestion, but same here -- as  chavasse mentioned.

**Comment by SuperN1ck** [comment]
Hey,
just a friendly ping. Are there any updates when this is planned to be released? This would be super helpful to have!
Cheers,
-Nick

**Comment by MartyG-RealSense** [comment]
Hi @SuperN1ck  Thanks very much for your query about a URDF for the D405.  I have highlighted your question to my colleagues on the RealSense ROS team.

**Comment by MartyG-RealSense** [comment]
Hi @SuperN1ck  The RealSense ROS team will take a look at the feature request for a D405 URDF to see what action to next take about it.

**Comment by Arun-Prasad-V** [comment]
Hi @vonHartz,  @chavasse, @weaponeer, @SuperN1ck,
A reference D405 URDF description is now available in `ros2-development` branch. Please refer the PR #2953.

Would really appreciate if you guys can try it out and let us know your feedback.
`ros2 launch realsense2_camera rs_d405_pointcloud_launch.py`

Thanks!

**Comment by MartyG-RealSense** [comment]
Hi everyone, have you been able to test the new URDF for the D405 camera model that is now available, please - see https://github.com/IntelRealSense/realsense-ros/issues/2589#issuecomment-1869631467

**Comment by MartyG-RealSense** [comment]
Case closed due to D405 URDF having been implemented and no further comments received.
