### ISSUE TITLE
D405 how to turn auto exposure on while using ros2 launch realsense2_camera rs_launch.py

### ISSUE THREAD

**Issue by EkamBehl** [realsenseai/realsense-ros#2598]
HI,
I've got a d405 camera .I  subscribed to /camera/color/image_rect_raw and couldn't do detection(was trying to detect chessboard corners  .I opened the image feed on realsense-viewer and it is all white due to lighting condition..The code works on the screenshot of the image after i turn auto exposure on in realsense-viewer.
Is the auto exposure on while running the launch file.If not,how do i turn it on?
i am running ros2 humble .
Thanks for any help

**Comment by MartyG-RealSense** [comment]
Hi @EkamBehl  Auto-exposure should be enabled by default in both the realsense-viewer tool and the ROS wrapper.

**Comment by EkamBehl** [comment]
Hi @MartyG-RealSense ,
For some reason the auto exposure is not on by default.
Is there a way to turn it on?
I've attached a few images one from rviz on the topic camera/colour/image_rect_raw
And one on real sense with auto exposure on:
![16739255126592560896709862844584](https://user-images.githubusercontent.com/62633992/212802373-bf0edbe0-14f2-428c-bc3c-33f0207b5a40.jpg)
![16739255373838255031301006107102](https://user-images.githubusercontent.com/62633992/212802465-a153a999-dff9-4e18-9068-5c3efa001eb2.jpg)

**Comment by Adum888** [comment]
as a preliminary workaround you can use rqt. The check-mark for auto-exposure will be active. Deactivate it and reactivate it. Looking at the infrar image (in Rviz) should confirm the change instantly.

**Comment by MartyG-RealSense** [comment]
Please try enabling the auto-exposure after launch during runtime with the ROS2 command below.

`ros2 param set /camera/camera depth_module.enable_auto_exposure true`

**Comment by EkamBehl** [comment]
@MartyG-RealSense thanks it worked!!

**Comment by MartyG-RealSense** [comment]
That's excellent to hear, @EkamBehl - thanks very much for the update!

**Comment by MartyG-RealSense** [comment]
Case closed due to solution achieved and no further comments received.

**Comment by Adum888** [comment]
How is this a sufficient solution?
a parameter not working when set during launch
Has to be set after launch (or depending on the initial configuration firstly turned false and then true again)
This is a mediocre workaround at best and not documented at all.
Edit: @EkamBehl  thank you for your tipp. It works and has to do until there is an actual fix

**Comment by MartyG-RealSense** [comment]
@Adum888  I will re-open the issue and keep it open so that other RealSense ROS users who may be experiencing a similar problem can add comments about it to this case.

**Comment by Adum888** [comment]
Thank you

**Comment by SamerKhshiboun** [comment]
See my comments in #2507 for more information.
The camera control of auto_exposure was turned off due other parameters in the launch file (e.g. depth_module.exposure.1)

**Comment by SamerKhshiboun** [comment]
#2612

**Comment by MartyG-RealSense** [comment]
Hi @EkamBehl and @Adum888  Do you require further assistance after the fix implemented by @SamerKhshiboun at 
https://github.com/IntelRealSense/realsense-ros/pull/2612 and merged into the **ros2_development** ROS2 wrapper?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.

**Comment by daichang01** [comment]
According to my attempts, commenting out the following can achieve automatic exposure
 {'name': 'depth_module.exposure.1',      'default': '7500', 'description': 'Depth module first exposure value. Used for hdr_merge filter'},
                           {'name': 'depth_module.gain.1',          'default': '16', 'description': 'Depth module first gain value. Used for hdr_merge filter'},
                           {'name': 'depth_module.exposure.2',      'default': '1', 'description': 'Depth module second exposure value. Used for hdr_merge filter'},
                           {'name': 'depth_module.gain.2',          'default': '16', 'description': 'Depth module second gain value. Used for hdr_merge filter'},
