### ISSUE TITLE
Does the L515 make the hardware synchronization among IMU, camera and LiDAR?

### ISSUE THREAD

**Issue by jiejie567** [realsenseai/realsense-ros#2609]
I think that L515 doesn't make the hardware synchronization. So how to do that?

**Comment by MartyG-RealSense** [comment]
Hi @jiejie567  Hardware synchronization on the L515 camera model has a different purpose to the sync system on the 400 Series cameras.  

Whilst hardware synchronization on the 400 Series aims to have cameras sync their timestamps to the timing of a master camera or an externally generated trigger signal, the L515 sync system reduces optical interference between multiple L515 cameras with overlapping fields of view by time-staggering when separate L515 cameras project light.  This process is described in the white-paper guide at the link below.

https://dev.intelrealsense.com/docs/lidar-camera-l515-multi-camera-setup

**Comment by jiejie567** [comment]
@MartyG-RealSense Thank you for reply. I think I don't convey myself clearly. I mean in one L515, whether the hardware synchronization among the camera module, IMU module, and LiDAR module is done?

**Comment by MartyG-RealSense** [comment]
Synchronization between sensors on the same camera is a different subject to hardware synchronization, yes.  On 400 Series cameras equipped with an IMU, each IMU data packet is timestamped using the depth sensor hardware clock to allow temporal synchronization between gyro, accel and depth frames.  As far as I am aware the same is true for the L515.

**Comment by jiejie567** [comment]
But in issue #1370 , it seems show that they are not synchronized in L515.

**Comment by MartyG-RealSense** [comment]
On the 400 Series models, a feature called **Global Time** that aligns device time and system time is enabled by default.  On the L515 model, Global Time is disabled by default.  In the discussion that you quoted, a RealSense team member recommends at https://github.com/IntelRealSense/realsense-ros/issues/1370#issuecomment-777276346 to try enabling Global Time.

**Comment by jiejie567** [comment]
hi @MartyG-RealSense , if a IMU message and a image message have the same timestamp, will they correspond to the same real time？

**Comment by MartyG-RealSense** [comment]
If IMU and image have the same timestamp then that timestamp should represent the best match between those different stream types that the SDK is able to provide.

**Comment by jiejie567** [comment]
![6c42357232724898b6f095551db2428](https://user-images.githubusercontent.com/57585288/215424393-22fcb406-8b43-4c5e-b688-fa92830a3602.jpg)
Hi, @MartyG-RealSense , what's more, I wonder that why the "Sync" button in the realsense-viewer is always gray？

**Comment by MartyG-RealSense** [comment]
The grayed-out Sync button is not related to hardware sync.  It controls if librealsense will try to bundle frames at software level.  In other words, it is a **software sync** button.  This button usually does not function though and so can be ignored.

**Comment by jiejie567** [comment]
Hi @MartyG-RealSense , I want to confirm whether the clock sources of IMU and other modules are unified.

**Comment by MartyG-RealSense** [comment]
An L515 will behave like the D435i camera model in terms of interactions between the IMU and other sensors.  And as mentioned above at https://github.com/IntelRealSense/realsense-ros/issues/2609#issuecomment-1407589580 the IMU of the D435i (a RealSense 400 Series camera) will have each data packet timestamped using the depth sensor hardware clock to allow temporal synchronization between gyro, accel and depth frames.

At https://github.com/IntelRealSense/librealsense/issues/8249 a RealSense team member also confirms that the coordinate systems of the IMU and depth sensors are aligned and that the L515 uses the same coordinate system as D435i.

**Comment by MartyG-RealSense** [comment]
Hi @jiejie567  Do you require further assistance with this case, please?  Thanks!
