### ISSUE TITLE
aligned_depth_to_color

### ISSUE THREAD

**Issue by gaoyi-2016** [realsenseai/realsense-ros#2618]
when i run "roslaunch realsense2_camera rs_camera.launch align_depth.enable:=true"

there is no topic named "aligned_depth_to_color"

can y solve it？

![2023-02-09 07-00-07屏幕截图](https://user-images.githubusercontent.com/80136256/217670890-50e8e6ee-38e4-4a45-9aca-023c0485e958.png)

**Comment by MartyG-RealSense** [comment]
Hi @gaoyi-2016  You are using **rs_camera.launch**, which is a ROS1 launch file.  `align_depth.enable` is a ROS2 wrapper instruction.  In the ROS1 wrapper, the instruction to enable alignment is **align_depth:=true**

`roslaunch realsense2_camera rs_camera.launch align_depth:=true`

**Comment by gaoyi-2016** [comment]
thanks very much, it helps me in time

**Comment by MartyG-RealSense** [comment]
Hi @gaoyi-2016  Do you require further assistance with this case, please? Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
