### ISSUE TITLE
Error when trying to use Realsense-ROS

### ISSUE THREAD

**Issue by pfcouto** [realsenseai/realsense-ros#2620]
@MartyG-RealSense 

I am following this guide https://github.com/IntelRealSense/realsense-ros/wiki/SLAM-with-D435i and I am having some issues. I am using Ubuntu 20.04 through distrobox (ON my machine I have fedora 37 and then I have a distro box with ubuntu 20.04 (this might be the cause of the error)).

Done all the steps until this one (https://github.com/IntelRealSense/realsense-ros) that outputs the error (second picture). As visible it is not entering the install folder. So in order to make it accessible I went and added the /install on the local_setup.bash (third image)
![image](https://user-images.githubusercontent.com/69256195/218220484-1aca9059-f401-4257-946d-32029fd2a27d.png)

![image](https://user-images.githubusercontent.com/69256195/218220556-76bf8693-a7ab-4bae-a060-0a0b7bb79ccc.png)

![image](https://user-images.githubusercontent.com/69256195/218220719-8d3c1442-4d82-42d2-96b8-00e911e8aa6a.png)
 
And then when I try to run the command `ros2 launch realsense2_camera opensource_tracking.launch` it outputs the following error. As visible it is accessing the install folder looking for the file and not the src folder to which I cloned your the github repo. Can you help out??? Thanks! By the way, I search the files looking for the opensource_tracking.launch file but didn't find it. Can you tell me its location? Thanks!

![image](https://user-images.githubusercontent.com/69256195/218220873-14947d3f-57f0-4fc2-a983-2759676aeaca.png)

The process to clone the repo was done in step 3

![image](https://user-images.githubusercontent.com/69256195/218221156-1a60cd6f-579d-43dc-8b7d-47930e3dabd9.png)

EDIT:

Created a VM with a fresh installation of Ubuntu 22.04 and got the same error. It is using the install folder, instead of the src one

![image](https://user-images.githubusercontent.com/69256195/218235717-4867fa61-3c53-4ff0-8f3d-057973488e68.png)

![image](https://user-images.githubusercontent.com/69256195/218235783-30c053f0-4cdc-4d85-86e9-95530ace744d.png)

**Comment by pfcouto** [comment]
OK. This file only is present in ROS1 branch.

I want to do a slam using only a D435i using ROS2. Can you guide me? 

And if it isn't possible, can you tell me the file to build the SLAM using ROS1 using only the D435i?

Thanks!

**Comment by MartyG-RealSense** [comment]
Hi @pfcouto  Of the limited number of available information resources about using SLAM with RealSense and ROS2, they have typically involved using a combination of **slam_toolbox** and **depthimage_to_laserscan**, as described at https://github.com/IntelRealSense/realsense-ros/issues/2387

**Comment by pfcouto** [comment]
OK. I will look into that. IN the mean time I was trying to use ROS1. As per the guide in https://github.com/IntelRealSense/realsense-ros/wiki/SLAM-with-D435i I ran the command `roslaunch realsense2_camera opensource_tracking.launch` and I can't see any output in RViz. I haven't personalize RViz like in the guide, However I would like to fix that error and provide the odometry. How can I do that?? If I run the command `roslaunch realsense2_camera rs_d435_camera_with_model.launch` I have the output shown in the second image. It is not the SLAM but it is the 3D (Image+depth) of the camera. What I need to do now is to create a SLAM using my D435i. Which steps should I do now to make it? Thanks!

![image](https://user-images.githubusercontent.com/69256195/218285304-0abc599e-d568-4b95-a69d-77c2417a8e2f.png)

![image](https://user-images.githubusercontent.com/69256195/218285441-8faa4aef-bd9a-4ef3-9688-57926d65650d.png)

**Comment by MartyG-RealSense** [comment]
Hi @pfcouto  The IMU gyro and accel topics are disabled by default in the ROS1 wrapper, so they should be enabled in the roslaunch instruction.  They were enabled by default at the time when the D435i SLAM guide was originally written, which is why the guide does not mention this.  

`roslaunch realsense2_camera opensource_tracking.launch enable_gyro:=true enable_accel:=true unite_imu_method:=linear_interpolation`

**Comment by pfcouto** [comment]
Hi. Tried the command and also personalized RViz like in https://github.com/IntelRealSense/realsense-ros/wiki/SLAM-with-D435i. I am still getting some error as shown in the pictures. One of them being the the same as before, about the ometry. And I still can't see the SLAM, do I have to enable more options? What should I do? Thanks!

![image](https://user-images.githubusercontent.com/69256195/218525331-f911d539-7644-453f-ae27-59e14efebd50.png)

![image](https://user-images.githubusercontent.com/69256195/218525497-3c9058b4-a181-4e2f-8559-5acfb3643d47.png)

![image](https://user-images.githubusercontent.com/69256195/218526716-adf284e6-7954-495f-9819-f380a6d353e4.png)

**Comment by pfcouto** [comment]
Managed to solve the first error evolving the octomap_rviz_plugin by running the command `sudo apt-get install ros-noetic-octomap-rviz-plugins`. I get the error about the odometry but not always, I believe that it is caused when I move the camera to fast. However, I still can't see the slam. When I activate the option `ColorOccupancyGrid` I can see a "SLAM" made with the depths (I believe), and when I enable map a 2D image also appears, but I can't find a way to show the SLAM. As shown in the picture 3 I get several warnings about time difference between RGB and Depth, can that cause  the problem? Also I sometimes get the error in picture 3 when I enable the option MapCloud.  Can you help? Thanks!

![image](https://user-images.githubusercontent.com/69256195/218529658-912762c2-23be-4d62-9c38-31698462521a.png)

![image](https://user-images.githubusercontent.com/69256195/218531575-55d646ee-68ac-4599-8773-7fd05c8aab23.png)

![image](https://user-images.githubusercontent.com/69256195/218531885-88f73b61-621a-41e0-b1c0-a068b1fb42d9.png)

**Comment by MartyG-RealSense** [comment]
In an **rtabmap_ros** support forum case at https://github.com/introlab/rtabmap_ros/issues/785#issuecomment-1196850676 that features this  "the time difference between rgb and depth frames is high" warning with a RealSense D435i, they suggest including **align_depth:=true** in the roslaunch instruction to align depth to color if depth and color are not using the same resolution.

**Comment by pfcouto** [comment]
Ok. I will add it. However, why can't I see the SLAM in RViz?

**Comment by pfcouto** [comment]
I think I managed to make it work. Thanks! However, I do have more questions. I found this code https://github.com/IntelRealSense/librealsense/blob/master/wrappers/python/examples/opencv_pointcloud_viewer.py that makes a point cloud. The thing is, I would like to inference on the RGB image, make detections (using YOLO or Mask), represent it as a 3D bounding box on a point cloud and make a SLAM with that point cloud. Meaning that I would have a SLAM with object detections represented as 3D Bounding boxes. Do you know if anyone as done this before, or do you know a way to guide me? I believe the main issues are how to create and represent a 3D bounding box and how to create a SLAM from the point clouds with the bounding boxes. One more thing, how do I implement hardware acceleration on the script from the link? There it is commented that better results can be achieved using hardware acceleration. Thanks!

**Comment by MartyG-RealSense** [comment]
The project at the link below may meet some of your needs of RealSense with YOLO, point clouds and SLAM.  It also makes use of Darknet.

https://github.com/Mazhichaoruya/Object-Detection-and-location-RealsenseD435

If you need **3D** bounding boxes then you could try using **darknet_ros_3d**

https://github.com/IntelligentRoboticsLabs/gb_visual_detection_3d

In regard to hardware acceleration, if you were using C++ language then you could use the RealSense SDK's **GLSL** feature to offload processing work for alignment, pointclouds, etc from the CPU onto the graphics GPU by changing RS2:: script instructions to RS2::GL::.  This will not work with the Python language though as pyrealsense2 scripts do not use RS2:: instructions.

https://github.com/IntelRealSense/librealsense/tree/master/examples/gl

If the program was being run on an Nvidia Jetson computing board then a RealSense pointcloud could take advantage of **CUDA** graphics acceleration.  CUDA only works with Nvidia graphics GPUs, like the one installed on Nvidia Jetson boards.

**Comment by MartyG-RealSense** [comment]
Hi @pfcouto  Do you require further assistance with this case, please?  Thanks!

**Comment by pfcouto** [comment]
I guess not. I will be closing this issue. Thanks!

**Comment by MartyG-RealSense** [comment]
You are very welcome, @pfcouto - thanks very much for the update!
