### ISSUE TITLE
Resource temporarily unavailable on Jetson Xavier Board

### ISSUE THREAD

**Issue by Mardank** [realsenseai/realsense-ros#2628]
Hey together,
I tried to install the realsense-ros wrapper on a Jetson Xavier board. Below you can find some general information about my setup.

- Jetson Xavier
- Ubuntu 18.04
- JetPack 4.6.3
- Realsense camera D435
- Version of LibRealSense v2.50.0
- Version of RealSense ROS v2.3.2
- ROS1 Melodic

I have been following the instructions in the comment of the following [Issue](https://github.com/IntelRealSense/librealsense/issues/6964#issuecomment-706643114) for installing LibRealSense  and the instructions for ROS1 on how to install RealSenseROS [from source](https://github.com/IntelRealSense/realsense-ros/tree/ros1-legacy#step-2-install-intel-realsense-ros-from-sources).

In the realsense-viewer the camera works as expected, but in the terminal I get the following Warning:
`15/02 15:14:43,719 WARNING [547764231968] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11`

Additionally after running `roslaunch realsense2_camera rs_camera.launch` it states that the resource is temporarily unavailable. The realsense-viewer is closed and the following output is generated.

Is there anything I can do to counteract against the issue?

Regards, Markus

```
dronelab2@ubuntu:~/catkin_ws$ roslaunch realsense2_camera rs_camera.launch
... logging to /home/dronelab2/.ros/log/5eb372a8-ad3b-11ed-a7db-48b02d5fd446/roslaunch-ubuntu-10780.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://ubuntu:41525/

SUMMARY
========

PARAMETERS
 * /camera/realsense2_camera/accel_fps: -1
 * /camera/realsense2_camera/accel_frame_id: camera_accel_frame
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: False
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/allow_no_texture_points: False
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/calib_odom_file: 
 * /camera/realsense2_camera/clip_distance: -2.0
 * /camera/realsense2_camera/color_fps: -1
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: -1
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: -1
 * /camera/realsense2_camera/confidence_fps: -1
 * /camera/realsense2_camera/confidence_height: -1
 * /camera/realsense2_camera/confidence_width: -1
 * /camera/realsense2_camera/depth_fps: -1
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: -1
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: -1
 * /camera/realsense2_camera/device_type: 
 * /camera/realsense2_camera/enable_accel: False
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_confidence: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye1: False
 * /camera/realsense2_camera/enable_fisheye2: False
 * /camera/realsense2_camera/enable_fisheye: False
 * /camera/realsense2_camera/enable_gyro: False
 * /camera/realsense2_camera/enable_infra1: False
 * /camera/realsense2_camera/enable_infra2: False
 * /camera/realsense2_camera/enable_infra: False
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_pose: False
 * /camera/realsense2_camera/enable_sync: False
 * /camera/realsense2_camera/filters: 
 * /camera/realsense2_camera/fisheye1_frame_id: camera_fisheye1_f...
 * /camera/realsense2_camera/fisheye1_optical_frame_id: camera_fisheye1_o...
 * /camera/realsense2_camera/fisheye2_frame_id: camera_fisheye2_f...
 * /camera/realsense2_camera/fisheye2_optical_frame_id: camera_fisheye2_o...
 * /camera/realsense2_camera/fisheye_fps: -1
 * /camera/realsense2_camera/fisheye_frame_id: camera_fisheye_frame
 * /camera/realsense2_camera/fisheye_height: -1
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: -1
 * /camera/realsense2_camera/gyro_fps: -1
 * /camera/realsense2_camera/gyro_frame_id: camera_gyro_frame
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/imu_optical_frame_id: camera_imu_optica...
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra_fps: 30
 * /camera/realsense2_camera/infra_height: 480
 * /camera/realsense2_camera/infra_rgb: False
 * /camera/realsense2_camera/infra_width: 848
 * /camera/realsense2_camera/initial_reset: False
 * /camera/realsense2_camera/json_file_path: 
 * /camera/realsense2_camera/linear_accel_cov: 0.01
 * /camera/realsense2_camera/odom_frame_id: camera_odom_frame
 * /camera/realsense2_camera/ordered_pc: False
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/pose_frame_id: camera_pose_frame
 * /camera/realsense2_camera/pose_optical_frame_id: camera_pose_optic...
 * /camera/realsense2_camera/publish_odom_tf: True
 * /camera/realsense2_camera/publish_tf: True
 * /camera/realsense2_camera/reconnect_timeout: 6.0
 * /camera/realsense2_camera/rosbag_filename: 
 * /camera/realsense2_camera/serial_no: 
 * /camera/realsense2_camera/stereo_module/exposure/1: 7500
 * /camera/realsense2_camera/stereo_module/exposure/2: 1
 * /camera/realsense2_camera/stereo_module/gain/1: 16
 * /camera/realsense2_camera/stereo_module/gain/2: 16
 * /camera/realsense2_camera/tf_publish_rate: 0.0
 * /camera/realsense2_camera/topic_odom_in: odom_in
 * /camera/realsense2_camera/unite_imu_method: 
 * /camera/realsense2_camera/usb_port_id: 
 * /camera/realsense2_camera/wait_for_device_timeout: -1.0
 * /rosdistro: melodic
 * /rosversion: 1.14.13

NODES
  /camera/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)

auto-starting new master
process[master]: started with pid [10790]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 5eb372a8-ad3b-11ed-a7db-48b02d5fd446
process[rosout-1]: started with pid [10803]
started core service [/rosout]
process[camera/realsense2_camera_manager-2]: started with pid [10820]
process[camera/realsense2_camera-3]: started with pid [10821]
[ INFO] [1676470604.601407444]: Initializing nodelet with 4 worker threads.
[ INFO] [1676470604.875170737]: RealSense ROS v2.3.2
[ INFO] [1676470604.875277618]: Built with LibRealSense v2.50.0
[ INFO] [1676470604.875339666]: Running with LibRealSense v2.50.0
[ INFO] [1676470604.949719201]:  
[ INFO] [1676470605.309621323]: Device with serial number 213322073036 was found.

[ INFO] [1676470605.309796332]: Device with physical ID 2-3.3-3 was found.
[ INFO] [1676470605.309864685]: Device with name Intel RealSense D435 was found.
[ INFO] [1676470605.311282740]: Device with port number 2-3.3 was found.
[ INFO] [1676470605.311384405]: Device USB type: 3.2
[ INFO] [1676470605.318718140]: getParameters...
[ INFO] [1676470605.619320776]: setupDevice...
[ INFO] [1676470605.619475241]: JSON file is not provided
[ INFO] [1676470605.619530953]: ROS Node Namespace: camera
[ INFO] [1676470605.619653098]: Device Name: Intel RealSense D435
[ INFO] [1676470605.619744810]: Device Serial No: 213322073036
[ INFO] [1676470605.619821579]: Device physical port: 2-3.3-3
[ INFO] [1676470605.619896267]: Device FW version: 05.13.00.50
[ INFO] [1676470605.619943276]: Device Product ID: 0x0B07
[ INFO] [1676470605.619998828]: Enable PointCloud: Off
[ INFO] [1676470605.620043980]: Align Depth: Off
[ INFO] [1676470605.620085932]: Sync Mode: Off
[ INFO] [1676470605.620242349]: Device Sensors: 
[ INFO] [1676470605.722397521]: Stereo Module was found.
[ INFO] [1676470605.764554643]: RGB Camera was found.
[ INFO] [1676470605.764771636]: (Confidence, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1676470605.764873141]: num_filters: 0
[ INFO] [1676470605.764945877]: Setting Dynamic reconfig parameters.
[ INFO] [1676470609.579902245]: Done Setting Dynamic reconfig parameters.
[ INFO] [1676470609.581479182]: depth stream is enabled - width: 848, height: 480, fps: 30, Format: Z16
[ INFO] [1676470609.582849269]: color stream is enabled - width: 640, height: 480, fps: 30, Format: RGB8
[ INFO] [1676470609.583537529]: setupPublishers...
[ INFO] [1676470609.593757232]: Expected frequency for depth = 30.00000
[ INFO] [1676470609.711519462]: Expected frequency for color = 30.00000
[ INFO] [1676470609.807935049]: setupStreams...
 15/02 15:16:50,064 WARNING [546727518592] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
[ INFO] [1676470610.115190997]: SELECTED BASE:Depth, 0
[ INFO] [1676470610.172058693]: RealSense Node Is Up!
[ WARN] [1676470610.184185734]: 
 15/02 15:16:50,185 WARNING [546727518592] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 15/02 15:16:50,236 WARNING [546727518592] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 15/02 15:16:50,287 WARNING [546727518592] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 15/02 15:16:50,530 WARNING [546727518592] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 15/02 15:16:50,581 WARNING [546727518592] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 15/02 15:16:50,633 WARNING [546727518592] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 15/02 15:16:50,684 WARNING [546727518592] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 15/02 15:16:50,835 WARNING [546727518592] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 15/02 15:16:50,885 WARNING [546727518592] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 15/02 15:16:51,037 WARNING [546727518592] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 15/02 15:16:51,087 WARNING [546727518592] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
^C[camera/realsense2_camera-3] killing on exit
[camera/realsense2_camera_manager-2] killing on exit
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
```

**Comment by MartyG-RealSense** [comment]
Hi @Mardank  Please first try adding **initial_reset:=true** to your roslaunch instruction to reset the camera at launch in order to see whether this resolves your **control_transfer returned** warnings.

I note in your specification listing at the top of this issue that your JetPack version is listed as 6.1.3.  The newest JetPack version is only 5.1 at the time of writing this.

**Comment by Mardank** [comment]
Hi @MartyG-RealSense, thanks for the fast response.
I tried to run is with the option ` initial_reset:=true`. Unfortunately I encounter the same Warnings.
Thanks for noticing, I corrected it to the correct version of JetPack.

[realsense-ros-output.txt](https://github.com/IntelRealSense/realsense-ros/files/10744436/realsense-ros-output.txt)

**Comment by MartyG-RealSense** [comment]
The RealSense SDK officially supports JetPack 4.6 when used with Ubuntu 18.04, so there does not seem to be a problem there.  

Your ROS wrapper version 2.50.0 is also correctly matched with ROS wrapper 2.3.2.

Pointcloud and align_depth are set to false, so they will not be causing problems.

Sometimes the **control_transfer returned** warning will repeat continuously and the topics will still be published normally and appear in the RViz interface without apparent negative effects.  Are you able to visualize the depth and color streams normally in RViz despite the warnings, please?

**Comment by MartyG-RealSense** [comment]
Hi @Mardank  Do you require further assistance with this case, please?  Thanks!

**Comment by Mardank** [comment]
Hey @MartyG-RealSense, yes, most likely I still need further assistance. Unfortunately, I haven't been able to do more testing until now. Sorry for the delay!

**Comment by MartyG-RealSense** [comment]
It's no trouble at all.  Please let me know when you are ready to resume the discussion and I will be happy to help. Good luck!

**Comment by Mardank** [comment]
Hey, I'm actually able to visualize the stream of the camera in `RViz` and also in `rqt_image_viewer`. So can I assume that it will work or will there be any restrictions to the usage of the ros_realsense ROS wrapper?

![realsense_rviz](https://user-images.githubusercontent.com/14231479/221822944-63c0e7ce-1219-4be1-8d32-3ef4001980b0.png)

**Comment by MartyG-RealSense** [comment]
The RealSense ROS wrapper is basically publishing ROS topics containing camera data that can be viewed in RViz and rqt_image_viewer.  

The wrapper may not support every possible feature that people can think of, but it can publish depth, infrared, color and IMU topics.

**Comment by Mardank** [comment]
Okay, thanks for the help!
One more question: As our aim is to build a small car which is navigating autonomously, is there a SLAM project you would recommend to use with the this setup?

**Comment by MartyG-RealSense** [comment]
Intel provide a D435i SLAM project for the ROS1 wrapper at the link below.

https://github.com/IntelRealSense/realsense-ros/wiki/SLAM-with-D435i

This project would not be suitable for the D435 camera model though as it does not have an IMU component.  So that will limit your options in regard to choice of SLAM solutions.  A popular one that can work with D435 and can be used with or without IMU is **ORB_SLAM3**

https://github.com/UZ-SLAMLab/ORB_SLAM3

An example of a discussion about use of D435 with ORB-SLAM3 is at https://github.com/UZ-SLAMLab/ORB_SLAM3/issues/192

**Comment by MartyG-RealSense** [comment]
Hi @Mardank  Do you require further assistance with this case, please?  Thanks!

**Comment by Mardank** [comment]
No, I don't think so. But if I do, I will open a new issue or write here again. Thank you very much for the help!

**Comment by MartyG-RealSense** [comment]
You are very welcome, I am pleased that I could help.  Thanks very much for the update!

**Comment by zhihou7** [comment]
Hi, I suffer from a similar issue on Ubuntu 20.04. Could you help me solve it? 

The error message after I add "initial_reset:=true" is: (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0

Btw, in my case, Rivz screen is not started, and the command got stuck in the error message.

Best,

**Comment by MartyG-RealSense** [comment]
Hi @zhihou7  Does the launch behave normally in RViz if you do not add initial_reset to the launch instruction?  If there is not a problem with the launch then it is not necessary to reset it.

**Comment by zhihou7** [comment]
@MartyG-RealSense, the launch fails in RViz with roslaunch realsense2_camera rs_camera.launch with the similar error.

**Comment by zhihou7** [comment]
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://xxx:37691/

SUMMARY
========

PARAMETERS
 * /camera/realsense2_camera/accel_fps: -1
 * /camera/realsense2_camera/accel_frame_id: camera_accel_frame
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: False
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/allow_no_texture_points: False
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/calib_odom_file:
 * /camera/realsense2_camera/clip_distance: -2.0
 * /camera/realsense2_camera/color_fps: -1
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: -1
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: -1
 * /camera/realsense2_camera/confidence_fps: -1
 * /camera/realsense2_camera/confidence_height: -1
 * /camera/realsense2_camera/confidence_width: -1
 * /camera/realsense2_camera/depth_fps: -1
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: -1
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: -1
 * /camera/realsense2_camera/device_type:
 * /camera/realsense2_camera/enable_accel: False
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_confidence: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye1: False
 * /camera/realsense2_camera/enable_fisheye2: False
 * /camera/realsense2_camera/enable_fisheye: False
 * /camera/realsense2_camera/enable_gyro: False
 * /camera/realsense2_camera/enable_infra1: False
 * /camera/realsense2_camera/enable_infra2: False
 * /camera/realsense2_camera/enable_infra: False
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_pose: False
 * /camera/realsense2_camera/enable_sync: False
 * /camera/realsense2_camera/filters:
 * /camera/realsense2_camera/fisheye1_frame_id: camera_fisheye1_f...
 * /camera/realsense2_camera/fisheye1_optical_frame_id: camera_fisheye1_o...
 * /camera/realsense2_camera/fisheye2_frame_id: camera_fisheye2_f...
 * /camera/realsense2_camera/fisheye2_optical_frame_id: camera_fisheye2_o...
 * /camera/realsense2_camera/fisheye_fps: -1
 * /camera/realsense2_camera/fisheye_frame_id: camera_fisheye_frame
 * /camera/realsense2_camera/fisheye_height: -1
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: -1
 * /camera/realsense2_camera/gyro_fps: -1
 * /camera/realsense2_camera/gyro_frame_id: camera_gyro_frame
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/imu_optical_frame_id: camera_imu_optica...
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra_fps: 30
 * /camera/realsense2_camera/infra_height: 480
 * /camera/realsense2_camera/infra_rgb: False
 * /camera/realsense2_camera/infra_width: 848
 * /camera/realsense2_camera/initial_reset: False
 * /camera/realsense2_camera/json_file_path:
 * /camera/realsense2_camera/linear_accel_cov: 0.01
 * /camera/realsense2_camera/odom_frame_id: camera_odom_frame
 * /camera/realsense2_camera/ordered_pc: False
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/pose_frame_id: camera_pose_frame
 * /camera/realsense2_camera/pose_optical_frame_id: camera_pose_optic...
 * /camera/realsense2_camera/publish_odom_tf: True
 * /camera/realsense2_camera/publish_tf: True
 * /camera/realsense2_camera/reconnect_timeout: 6.0
 * /camera/realsense2_camera/rosbag_filename:
 * /camera/realsense2_camera/serial_no:
 * /camera/realsense2_camera/stereo_module/exposure/1: 7500
 * /camera/realsense2_camera/stereo_module/exposure/2: 1
 * /camera/realsense2_camera/stereo_module/gain/1: 16
 * /camera/realsense2_camera/stereo_module/gain/2: 16
 * /camera/realsense2_camera/tf_publish_rate: 0.0
 * /camera/realsense2_camera/topic_odom_in: odom_in
 * /camera/realsense2_camera/unite_imu_method:
 * /camera/realsense2_camera/usb_port_id:
 * /camera/realsense2_camera/wait_for_device_timeout: -1.0
 * /rosdistro: noetic
 * /rosversion: 1.16.0

NODES
  /camera/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)

ROS_MASTER_URI=http://localhost:11311

process[camera/realsense2_camera_manager-1]: started with pid [1266109]
process[camera/realsense2_camera-2]: started with pid [1266110]
[ INFO] [1713769100.728393648]: Initializing nodelet with 20 worker threads.
[ INFO] [1713769100.807978565]: RealSense ROS v2.3.2
[ INFO] [1713769100.808010901]: Built with LibRealSense v2.50.0
[ INFO] [1713769100.808029616]: Running with LibRealSense v2.50.0
[ INFO] [1713769100.839260442]:
[ INFO] [1713769101.094146598]: Device with serial number 239722071238 was found.

[ INFO] [1713769101.094253441]: Device with physical ID 2-9-5 was found.
[ INFO] [1713769101.094298739]: Device with name Intel RealSense D435I was found.
[ INFO] [1713769101.095406155]: Device with port number 2-9 was found.
[ INFO] [1713769101.095520838]: Device USB type: 3.2
[ INFO] [1713769101.099090387]: getParameters...
[ INFO] [1713769101.132442904]: setupDevice...
[ INFO] [1713769101.132461905]: JSON file is not provided
[ INFO] [1713769101.132468189]: ROS Node Namespace: camera
[ INFO] [1713769101.132477205]: Device Name: Intel RealSense D435I
[ INFO] [1713769101.132483393]: Device Serial No: 239722071238
[ INFO] [1713769101.132488793]: Device physical port: 2-9-5
[ INFO] [1713769101.132494459]: Device FW version: 05.13.00.55
[ INFO] [1713769101.132499741]: Device Product ID: 0x0B3A
[ INFO] [1713769101.132504553]: Enable PointCloud: Off
[ INFO] [1713769101.132510333]: Align Depth: Off
[ INFO] [1713769101.132516409]: Sync Mode: Off
[ INFO] [1713769101.132540772]: Device Sensors:
[ INFO] [1713769101.250793572]: Stereo Module was found.
[ INFO] [1713769101.261977942]: RGB Camera was found.
[ INFO] [1713769101.262146130]: Motion Module was found.
[ INFO] [1713769101.262177538]: (Confidence, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1713769101.262204203]: num_filters: 0
[ INFO] [1713769101.262219611]: Setting Dynamic reconfig parameters.
[ INFO] [1713769104.205329860]: Done Setting Dynamic reconfig parameters.
[ INFO] [1713769104.205689285]: depth stream is enabled - width: 848, height: 480, fps: 30, Format: Z16
[ INFO] [1713769104.206561420]: color stream is enabled - width: 1280, height: 720, fps: 30, Format: RGB8
[ INFO] [1713769104.206585701]: setupPublishers...
[ INFO] [1713769104.207759505]: Expected frequency for depth = 30.00000
[ INFO] [1713769104.221967472]: Expected frequency for color = 30.00000
[ INFO] [1713769104.229695166]: setupStreams...
 22/04 14:58:24,396 WARNING [139959255676672] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
[ INFO] [1713769104.447187652]: SELECTED BASE:Depth, 0
[ INFO] [1713769104.450315077]: RealSense Node Is Up!
[ WARN] [1713769104.516629106]:
 22/04 14:58:24,517 WARNING [139959255676672] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 22/04 14:58:24,567 WARNING [139959255676672] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 22/04 14:58:24,618 WARNING [139959255676672] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 22/04 14:58:24,778 WARNING [139959255676672] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 22/04 14:58:24,828 WARNING [139959255676672] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 22/04 14:58:24,979 WARNING [139959255676672] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 22/04 14:58:25,130 WARNING [139959255676672] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 22/04 14:58:25,281 WARNING [139959255676672] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 22/04 14:58:25,331 WARNING [139959255676672] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11

**Comment by MartyG-RealSense** [comment]
@zhihou7  Which methods did you use to install the librealsense SDK and RealSense ROS1 wrapper, please?

One approach is to install librealsense and the ROS1 wrapper separately, with the SDK installed first and the wrapper secondly afterwards.

Another approach is to use the command below to install librealsense and the ROS1 wrapper from packages together at the same time.

`sudo apt-get install ros-$ROS_DISTRO-realsense2-camera`

With the apt-get method it is important that librealsense has not already been installed before the command is run, as you could then end up with two conflicting installations of librealsense on the same computer.
