### ISSUE TITLE
Intel RealSense R200 poor details in the depth stream

### ISSUE THREAD

**Issue by dottantgal** [realsenseai/realsense-ros#263]
### System Configuration
Please complete Your Configuration detail below. Refer to the BKC at [Configuration](../realsense_camera/README.md#configuration).

| Version               | Your Configuration   |
|:--------------------- |:---------------------|
| Operating System      | Ubuntu 16.04.3 LTS                |
| Kernel                | 4.4.0-93-generic                |
| ROS                   | kinetic                    |
| ROS RealSense         | 1.8.0                |
| librealsense          | 1.12.1               |
| Camera Type-Firmware  | 1.0.72.10          |

---
#### How to collect Configuration Data
*This section can be deleted before submission.*

| Version               | Method |
|:--------------------- |:------------ |
| Operating System      | `grep DISTRIB_DESCRIPTION /etc/*elease*` or `lsb_release -d` |
| Kernel                | `uname -r` |
| ROS                   | `rosversion -d` |
| ROS RealSense         | `rosversion realsense_camera` |
| librealsense          | `rosversion librealsense` |
| Camera Type-Firmware  | View the ROS log from running nodelet |

---

We have developed a ROS package to perform face detection on Ubuntu 16.04 system with ROS Kinetic. At the beginning we used the Asus Xtion Pro Live with its “openni” ROS wrapper and we didn’t get any problem to reach our goals ragardless the indoor environment, cause the depth stream of that device is rich of informations. Later we switched to the Intel RealSense R200 with its “realsense_camera” ROS wrapper with which has been highlighted a significant deterioration of the depth stream quality which does not allow us to perform face detection tasks like in the case of the Xtion, but only under certain conditions. We took the depth with different methods, always getting the same results where the depth stream results full of black holes also for point over surfaces at the same distances from the device. We are having this using directly the librealsense library by creating an ad-hoc ROS wrapper, as well as using the already available ROS "realsense_camera" wrapper.
Is there a way to pick up a clear depth image as seen from the screenshots available here in the library repository https://github.com/IntelRealSense/librealsense/blob/master/doc/stepbystep/resources/Image_Depth.png?
Attached there are three screenshots just to compare the different details of the depth streams from the two devices we used: the first twos related to the RealSense and the last one related to the Xtion.

![realsensedepth1](https://user-images.githubusercontent.com/6942095/30033214-48f0e486-919a-11e7-81a0-236056e7149d.png)
![realsensedepth2](https://user-images.githubusercontent.com/6942095/30033216-48f46318-919a-11e7-920c-2089ad73ba22.png)
![xtiondepth](https://user-images.githubusercontent.com/6942095/30033215-48f2fdde-919a-11e7-953e-6657fa2c0411.png)

**Comment by dorodnic** [comment]
This seems like a limitation of the R200 camera. The D400 series significantly improves fill-rate, resolution and accuracy, but in general different depth solutions will offer different depth characteristics. The ROS wrapper is only designed to expose depth data.
