### ISSUE TITLE
ROS2 reset service

### ISSUE THREAD

**Issue by weeshal** [realsenseai/realsense-ros#2635]
Hey, there has already been an issue submitted and closed pertaining to the reset service being removed in ros2 but I recently made the discovery that there is a reset function in the node class, that is not tied to anything.
https://github.com/IntelRealSense/realsense-ros/blob/4073f1513ab9e359a3541d37a22a7ae055981414/realsense2_camera/src/base_realsense_node.cpp#L171-L175
Could anyone help me understand why this exists and why it cannot be used with a ros2 service? I would be happy to contribute and test it out if that was possible. Thanks.

**Comment by MartyG-RealSense** [comment]
Hi @weeshal  I checked the circumstances under which this error message "Performing Hardware Reset" is generated.  It appears to be a means of resetting the camera automatically immediately after the following warning occurs in the launch log.

`Hardware Notification:RT IC2 Config error,1.60452e+12,Error,Hardware Error`

 So it is apparently an automated recovery mechanism rather than a service that is designed to be called by the user as a service.

**Comment by weeshal** [comment]
What prevents it from being used as a service called by the user? I mainly ask because it was available to us in ROS1.

**Comment by MartyG-RealSense** [comment]
For future reference, the previously submitted issue about a ROS2 reset service is at https://github.com/IntelRealSense/realsense-ros/issues/2593

I will highlight your question to the RealSense ROS developer team.

**Comment by MartyG-RealSense** [comment]
My colleagues on the RealSense ROS developer team thought that a ROS2 reset service was a good idea and they said that they plan to add it in the near future.

**Comment by weeshal** [comment]
That's great! Thanks for that information. Do you happen to have an idea of what the timeline for that is? It would be very helpful to plan out when we could expect to have that service available, and what might be worth developing in the meantime to workaround it.

**Comment by MartyG-RealSense** [comment]
"The near future" is the only time estimate that is currently available.  I do apologize.

At https://github.com/IntelRealSense/realsense-ros/issues/2593#issuecomment-1422881896 I made a suggestion about trying to stop and start all sensors as an alternative to resetting the camera.  Would that be a possibility for you?

**Comment by MartyG-RealSense** [comment]
Hi @weeshal  Was the suggestion about stopping and starting all sensors as an alternative to a camera reset helpful to you, please?  Thanks!

**Comment by weeshal** [comment]
Hey Marty, will try that out

**Comment by weeshal** [comment]
It is not available in the ros2-development branch @MartyG-RealSense  FYI

**Comment by MartyG-RealSense** [comment]
It is a supported service though in the previous ROS2 wrapper - now renamed **ros2-legacy** but still usable - if it is an option for you to use that older wrapper.

https://github.com/IntelRealSense/realsense-ros/tree/ros2-legacy#available-services

**Comment by MartyG-RealSense** [comment]
Hi @weeshal  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.

**Comment by PrasRsRos** [comment]
ROS2 reset service was implemented and merged: 
https://github.com/IntelRealSense/realsense-ros/tree/ros2-development?tab=readme-ov-file#hw_reset

**Comment by MartyG-RealSense** [comment]
Thanks so much for the information, @PrasRsRos   :)
