### ISSUE TITLE
405 urdf and mesh

### ISSUE THREAD

**Issue by chavasse** [realsenseai/realsense-ros#2636]
Currently, the library supports the D405 in ROS 2, however, there isn't a correct urdf model or mesh.

Are there plans to add support for this in the near future with all of the correct transforms?

Thanks,

**Comment by MartyG-RealSense** [comment]
Hi @chavasse  A D405 URDF is planned by the RealSense ROS developer team for implementation in a future release of the ROS wrapper.  I do not have a time estimate that I can provide, unfortunately.

**Comment by MartyG-RealSense** [comment]
Hi @chavasse  Bearing in mind the comment above, do you require further assistance with this case please?  Thanks!

**Comment by chavasse** [comment]
Ideally, we would have an accurate TF model for the camera mounting to the camera frame included with the package as none of the others that we are forced to use are correct.

This issue is actually a duplicate of this issue, apologies, I did search before but didn't find it previously:
https://github.com/IntelRealSense/realsense-ros/issues/2589

**Comment by MartyG-RealSense** [comment]
No need for apologies  :)   If you leave a comment on https://github.com/IntelRealSense/realsense-ros/issues/2589 then you will be notified of any updates about a D405 URDF that are posted there.

**Comment by MartyG-RealSense** [comment]
Hi @chavasse  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
