### ISSUE TITLE
Realsense camera imu vs microstrain imu sensor

### ISSUE THREAD

**Issue by futuristic2023** [realsenseai/realsense-ros#2639]
Can you tell me which imu sensor [camparsion] would be recommened for using the robot for RT, BOPT devices ,AMR

**Comment by MartyG-RealSense** [comment]
Hi @shivangi-futuristicbots  I can only provide information about the built-in IMU of RealSense cameras and not external IMU products created by companies other than Intel and so cannot offer a comparison.

**Comment by MartyG-RealSense** [comment]
Hi @shivangi-futuristicbots  Bearing in mind the comment above, do you require further assistance with this case please?  Thanks!

**Comment by futuristic2023** [comment]
No, thanks for everything

**Comment by MartyG-RealSense** [comment]
You are very welcome.  As you do not require further assistance with this case, I will close it.  Thanks again!
