### ISSUE TITLE
Realsense Ros Gazebo - D435 - Image Saver Issue

### ISSUE THREAD

**Issue by Narasimmavinay** [realsenseai/realsense-ros#2640]
Hi,

I am using the D435 realsense camera in Gazebo environment to capture images.

I am using the image saver service to save images but I get an error related to "plumb bob" distortion model. While checking the issues I found that in the camera_info topic of the camera the distortion coefficient matrix D is empty "D:[ ]".

I am wondering is there a provision to add a D matrix into the camera_info topic so that I can use the image saver service.

Kindly help me with this.

Thanks in advance.

**Comment by MartyG-RealSense** [comment]
Hi @Narasimmavinay  The only past case on this support forum that discusses plumb bob is at https://github.com/IntelRealSense/realsense-ros/issues/2458

The link below suggests a method for setting a value for D in sensor_msgs::CameraInfo

https://answers.ros.org/question/283828/set-value-for-distortion-coefficient-in-camerainfo/

**Comment by Narasimmavinay** [comment]
Thanks got it.
