### ISSUE TITLE
/camera/imu topic not published by Intel RealSense Depth Camera D435f on Ubuntu 20.04 Noetic

### ISSUE THREAD

**Issue by skye221** [realsenseai/realsense-ros#2643]
Hi, 
I am using the Intel® RealSense™ Depth Camera D435f with ROS Noetic on Ubuntu 20.04. When I launch the camera using `roslaunch realsense2_camera rs_camera.launch enable_infra1:=true enable_infra2:=true enable_accel:=true enable_gyro:=true unite_imu_method:=linear_interpolation,` the /camera/imu is not published. Instead, I see the following error message: 

![Screenshot from 2023-03-05 21-56-16](https://user-images.githubusercontent.com/37255728/223009110-8e745ea3-c4e0-41f2-9d96-f22c8e0b6891.png)

I have attached an image of the rostopic list command output showing that /camera/imu is not listed.

Is there anything else that I need to do to enable the IMU on the D435f camera on Ubuntu 20.04 Noetic? Thanks
![Screenshot from 2023-03-05 21-24-33](https://user-images.githubusercontent.com/37255728/223005287-229bbc99-433b-48c1-b21c-2ff2cbfc1cbb.png)

**Comment by MartyG-RealSense** [comment]
Hi @skye221  The D435f is not equipped with an IMU component unfortunately.  The 'f' stands for 'filter'.  It is an IMU-less **D435** camera with sensors that are equipped with a filter that blocks visible light frequencies from entering them and allows only higher near-infrared frequencies through.

The D435 model that has an IMU is the **D435i**.  The D455 model is also equipped with one.

**Comment by MartyG-RealSense** [comment]
Hi @skye221  Do you require further assistance with this case, please?  Thanks!

**Comment by skye221** [comment]
No, thank you.

**Comment by MartyG-RealSense** [comment]
Thanks very much for the update!
