### ISSUE TITLE
ros1 wrapper for windows catkin build error  

### ISSUE THREAD

**Issue by lilweary** [realsenseai/realsense-ros#2647]
hello, i am trying to build ros wrapper on windows env for ros melodic. i am using realsense sdk 2.50.0 and the realsense2_camera package from  ros1-legacy. i encouter the following error after using the following commnads . please help me resolve this error 

cd ~/catkin_ws/src/
  - catkin_init_workspace
  - cd ..
  - rosdep install --from-paths src --ignore-src -r -y
                  ERROR: the following packages/stacks could not have their rosdep keys resolved
                to system dependencies:
                realsense2_camera: No definition of [librealsense2] for OS [windows]
                Continuing to install resolvable dependencies...
                #All required rosdeps installed successfully
 
 - catkin_make clean
 
  - catkin_make -DCATKIN_ENABLE_TESTING=False -DCMAKE_BUILD_TYPE=Release  
[ 83%] Building CXX object realsense2_camera/CMakeFiles/realsense2_camera.dir/src/base_realsense_node.cpp.obj
cl : Command line warning D9002 : ignoring unknown option '-std=c++11'
base_realsense_node.cpp
C:\opt\ros\melodic\x64\include\cv_bridge/cv_bridge.h(396): warning C4267: 'return': conversion from 'size_t' to 'uint32_t', possible loss of data
C:\catkin_ws\src\realsense2_camera\include\constants.h(98): warning C4305: 'initializing': truncation from 'double' to 'float'
C:\opt\ros\melodic\x64\include\sensor_msgs/impl/point_cloud2_iterator.h(122): warning C4267: '=': conversion from 'size_t' to 'sensor_msgs::PointCloud2_<std::allocator<void>>::_width_type', possible loss of data
C:\opt\ros\melodic\x64\include\sensor_msgs/impl/point_cloud2_iterator.h(123): warning C4267: '=': conversion from 'size_t' to 'sensor_msgs::PointCloud2_<std::allocator<void>>::_row_step_type', possible loss of data
C:\opt\ros\melodic\x64\include\sensor_msgs/impl/point_cloud2_iterator.h(126): warning C4267: '=': conversion from 'size_t' to 'sensor_msgs::PointCloud2_<std::allocator<void>>::_height_type', possible loss of data
C:\opt\ros\melodic\x64\include\sensor_msgs/impl/point_cloud2_iterator.h(129): warning C4267: '=': conversion from 'size_t' to 'sensor_msgs::PointCloud2_<std::allocator<void>>::_width_type', possible loss of data
C:\opt\ros\melodic\x64\include\sensor_msgs/impl/point_cloud2_iterator.h(130): warning C4267: '=': conversion from 'size_t' to 'sensor_msgs::PointCloud2_<std::allocator<void>>::_row_step_type', possible loss of data
C:\catkin_ws\src\realsense2_camera\src\base_realsense_node.cpp(292): warning C4305: 'initializing': truncation from 'double' to 'float'
C:\catkin_ws\src\realsense2_camera\src\base_realsense_node.cpp(561): error C2065: 'RS2_OPTION_SEQUENCE_ID': undeclared identifier
C:\catkin_ws\src\realsense2_camera\src\base_realsense_node.cpp(632): error C2065: 'RS2_OPTION_SEQUENCE_SIZE': undeclared identifier
C:\catkin_ws\src\realsense2_camera\src\base_realsense_node.cpp(635): error C2065: 'RS2_OPTION_SEQUENCE_ID': undeclared identifier
C:\catkin_ws\src\realsense2_camera\src\base_realsense_node.cpp(654): error C2065: 'RS2_OPTION_SEQUENCE_ID': undeclared identifier
C:\catkin_ws\src\realsense2_camera\src\base_realsense_node.cpp(655): error C2065: 'RS2_OPTION_HDR_ENABLED': undeclared identifier
C:\catkin_ws\src\realsense2_camera\src\base_realsense_node.cpp(1248): error C2039: 'hdr_merge': is not a member of 'rs2'
C:\opt\ros\melodic\x64\tools\vcpkg\installed\x64-windows\include\librealsense2\hpp/rs_serializable_device.hpp(10): note: see declaration of 'rs2'
C:\catkin_ws\src\realsense2_camera\src\base_realsense_node.cpp(1248): error C2065: 'hdr_merge': undeclared identifier
C:\catkin_ws\src\realsense2_camera\src\base_realsense_node.cpp(1248): error C2672: 'std::make_shared': no matching overloaded function found
C:\catkin_ws\src\realsense2_camera\src\base_realsense_node.cpp(1248): error C2974: 'std::make_shared': invalid template argument for '_Ty', type expected
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\memory(2725): note: see declaration of 'std::make_shared'
C:\catkin_ws\src\realsense2_camera\src\base_realsense_node.cpp(1248): error C2440: '<function-style-cast>': cannot convert from 'const char [10]' to 'realsense2_camera::NamedFilter'
C:\catkin_ws\src\realsense2_camera\src\base_realsense_node.cpp(1248): note: No constructor could take the source type, or constructor overload resolution was ambiguous
C:\catkin_ws\src\realsense2_camera\src\base_realsense_node.cpp(1248): error C2661: 'std::vector<realsense2_camera::NamedFilter,std::allocator<realsense2_camera::NamedFilter>>::insert': no overloaded function takes 1 arguments
C:\catkin_ws\src\realsense2_camera\src\base_realsense_node.cpp(1250): error C2039: 'sequence_id_filter': is not a member of 'rs2'
C:\opt\ros\melodic\x64\tools\vcpkg\installed\x64-windows\include\librealsense2\hpp/rs_serializable_device.hpp(10): note: see declaration of 'rs2'
C:\catkin_ws\src\realsense2_camera\src\base_realsense_node.cpp(1250): error C2065: 'sequence_id_filter': undeclared identifier
C:\catkin_ws\src\realsense2_camera\src\base_realsense_node.cpp(1250): error C2672: 'std::make_shared': no matching overloaded function found
C:\catkin_ws\src\realsense2_camera\src\base_realsense_node.cpp(1250): error C2974: 'std::make_shared': invalid template argument for '_Ty', type expected
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\memory(2725): note: see declaration of 'std::make_shared'
C:\catkin_ws\src\realsense2_camera\src\base_realsense_node.cpp(1250): error C2440: '<function-style-cast>': cannot convert from 'const char [19]' to 'realsense2_camera::NamedFilter'
C:\catkin_ws\src\realsense2_camera\src\base_realsense_node.cpp(1250): note: No constructor could take the source type, or constructor overload resolution was ambiguous
C:\catkin_ws\src\realsense2_camera\src\base_realsense_node.cpp(1250): error C2661: 'std::vector<realsense2_camera::NamedFilter,std::allocator<realsense2_camera::NamedFilter>>::insert': no overloaded function takes 1 arguments
C:\catkin_ws\src\realsense2_camera\src\base_realsense_node.cpp(2301): warning C4267: '=': conversion from 'size_t' to 'sensor_msgs::PointCloud2_<std::allocator<void>>::_width_type', possible loss of data
NMAKE : fatal error U1077: 'C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\cl.exe' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.
Invoking "nmake" failed

**Comment by MartyG-RealSense** [comment]
Hi @lilweary  **cd ~/catkin_ws/src/** is a Linux installation instruction for creating the catkin workspace folder rather than a Windows instruction.

Can you confirm please if you are installing the ROS wrapper directly in Windows, or whether you are using the **Windows Subsystem for Linux (WSL2)** and installing on Linux from within Windows, please?

**Comment by lilweary** [comment]
hi @MartyG-RealSense i am using it directly in windows .  and worskspace directory is set to c:/catkin_ws and ros is installed uaing the guide frow wiki at c:/opt directory.
i have installed the librealsense sdk on C:\opt\ros\melodic\x64\tools\vcpkg using vcpkg instructions and i have also installed the sdk using downloadable .exe

**Comment by MartyG-RealSense** [comment]
Using the ros1-legacy installation instructions for Windows from here:

https://github.com/IntelRealSense/realsense-ros/tree/ros1-legacy#step-2-install-intel-realsense-ros-from-sources

1.  Install the librealsense SDK (which you have done)

2.  Install ROS.

3.  Create the catkin workspace directory at c:\catkin_ws\src

mkdir c:\catkin_ws\src
cd c:\catkin_ws\src

4.  Clone the RealSense ROS wrapper into catkin_ws/src/ and then change to the realsense-ros directory.

git clone https://github.com/IntelRealSense/realsense-ros.git
cd realsense-ros/

5.  When installing on Windows, the **git checkout** instruction (which is used to find the wrapper version number) is usually where problems are encountered because Windows does not understand the tag commands.  A workaround is to specify the version number directly instead of using the search tags.  the command below should locate ROS1 wrapper version 2.3.2, the newest one available.

**git checkout 2.3.2**

6.  Input the following series of commands, making sure to input all **cd ..** directory change commands so that you end up navigated to the correct directory.

cd ..
catkin_init_workspace
cd ..
catkin_make clean
catkin_make -DCATKIN_ENABLE_TESTING=False -DCMAKE_BUILD_TYPE=Release
catkin_make install

7.  Finally, input the command below.

devel\setup.bat

**Comment by MartyG-RealSense** [comment]
Hi @lilweary  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
