### ISSUE TITLE
Support for ROS2

### ISSUE THREAD

**Issue by ohshout** [realsenseai/realsense-ros#265]
Hi friends,

I wonder if there's any plan of having ROS2 realsense camera packages? I'm specifically looking for using the R200 camera on Ubuntu with ROS2 on the Intel Aero board.

And how hard you think it would be to port the realsense ROS1 packages to ROS2? Any forseeable obstacle? Want to hear some thoughts from you experts :)

Thanks a lot!
Tom.

**Comment by ohshout** [comment]
I found this guide to migrate from ROS1 to ROS2: https://github.com/ros2/ros2/wiki/Migration-Guide
Do you think this applies to realsense package as well?

**Comment by testkit** [comment]
Realsense ROS2 migration is in progress, we target to get it ready in 3 weeks or so, but it's for D400 serials camera not R200. (I hesitate to say it supports SR300 since we only verified with D400 serials cameras)

**Comment by ghost** [comment]
@testkit  Hi, have you done that ?

**Comment by testkit** [comment]
Finally, it's published at https://github.com/intel/ros2_intel_realsense.
