### ISSUE TITLE
realsense2_camera complilation error

### ISSUE THREAD

**Issue by Shillin123** [realsenseai/realsense-ros#2650]
Hi, after using command: catkin_make -DCATKIN_ENABLE_TESTING=False -DCMAKE_BUILD_TYPE=Release
I encounter this problem, can you please help to solve it? 

[ 70%] Built target realsense2_camera_generate_messages
[ 82%] Building CXX object realsense-ros/realsense2_camera/CMakeFiles/realsense2_camera.dir/src/base_realsense_node.cpp.o
[ 82%] Building CXX object realsense-ros/realsense2_camera/CMakeFiles/realsense2_camera.dir/src/framos_realsense_node_factory.cpp.o
In file included from /opt/ros/noetic/include/librealsense2/hpp/rs_sensor.hpp:8,
                 from /opt/ros/noetic/include/librealsense2/hpp/rs_device.hpp:8,
                 from /opt/ros/noetic/include/librealsense2/hpp/rs_record_playback.hpp:8,
                 from /opt/ros/noetic/include/librealsense2/hpp/rs_context.hpp:8,
                 from /opt/ros/noetic/include/librealsense2/rs.hpp:9,
                 from /home/franka/cam_fi/src/realsense-ros/realsense2_camera/src/../include/../include/realsense_node_factory.h:12,
                 from /home/franka/cam_fi/src/realsense-ros/realsense2_camera/src/../include/base_realsense_node.h:6,
                 from /home/franka/cam_fi/src/realsense-ros/realsense2_camera/src/base_realsense_node.cpp:1:
/opt/ros/noetic/include/librealsense2/hpp/rs_frame.hpp: In lambda function:
/opt/ros/noetic/include/librealsense2/hpp/rs_frame.hpp:1047:58: warning: comparison of integer expressions of different signedness: ‘int’ and ‘const size_t’ {aka ‘const long unsigned int’} [-Wsign-compare]
 1047 |                         frm.get_profile().stream_index() == index) f = frm;
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
/opt/ros/noetic/include/librealsense2/hpp/rs_frame.hpp: In lambda function:
/opt/ros/noetic/include/librealsense2/hpp/rs_frame.hpp:1069:58: warning: comparison of integer expressions of different signedness: ‘int’ and ‘const size_t’ {aka ‘const long unsigned int’} [-Wsign-compare]
 1069 |                         frm.get_profile().stream_index() == index) f = frm;
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
/opt/ros/noetic/include/librealsense2/hpp/rs_frame.hpp: In lambda function:
/opt/ros/noetic/include/librealsense2/hpp/rs_frame.hpp:1091:58: warning: comparison of integer expressions of different signedness: ‘int’ and ‘const size_t’ {aka ‘const long unsigned int’} [-Wsign-compare]
 1091 |                         frm.get_profile().stream_index() == index) f = frm;
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
In file included from /opt/ros/noetic/include/librealsense2/hpp/rs_sensor.hpp:8,
                 from /opt/ros/noetic/include/librealsense2/hpp/rs_device.hpp:8,
                 from /opt/ros/noetic/include/librealsense2/hpp/rs_record_playback.hpp:8,
                 from /opt/ros/noetic/include/librealsense2/hpp/rs_context.hpp:8,
                 from /opt/ros/noetic/include/librealsense2/rs.hpp:9,
                 from /home/franka/cam_fi/src/realsense-ros/realsense2_camera/src/../include/../include/realsense_node_factory.h:12,
                 from /home/franka/cam_fi/src/realsense-ros/realsense2_camera/src/../include/framos_realsense_node_factory.h:6,
                 from /home/franka/cam_fi/src/realsense-ros/realsense2_camera/src/framos_realsense_node_factory.cpp:4:
/opt/ros/noetic/include/librealsense2/hpp/rs_frame.hpp: In lambda function:
/opt/ros/noetic/include/librealsense2/hpp/rs_frame.hpp:1047:58: warning: comparison of integer expressions of different signedness: ‘int’ and ‘const size_t’ {aka ‘const long unsigned int’} [-Wsign-compare]
 1047 |                         frm.get_profile().stream_index() == index) f = frm;
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
/opt/ros/noetic/include/librealsense2/hpp/rs_frame.hpp: In lambda function:
/opt/ros/noetic/include/librealsense2/hpp/rs_frame.hpp:1069:58: warning: comparison of integer expressions of different signedness: ‘int’ and ‘const size_t’ {aka ‘const long unsigned int’} [-Wsign-compare]
 1069 |                         frm.get_profile().stream_index() == index) f = frm;
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
/opt/ros/noetic/include/librealsense2/hpp/rs_frame.hpp: In lambda function:
/opt/ros/noetic/include/librealsense2/hpp/rs_frame.hpp:1091:58: warning: comparison of integer expressions of different signedness: ‘int’ and ‘const size_t’ {aka ‘const long unsigned int’} [-Wsign-compare]
 1091 |                         frm.get_profile().stream_index() == index) f = frm;
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
/home/franka/cam_fi/src/realsense-ros/realsense2_camera/src/framos_realsense_node_factory.cpp: In member function ‘void realsense2_camera::FramosRealSenseNodeFactory::setRs2CliArgs()’:
/home/franka/cam_fi/src/realsense-ros/realsense2_camera/src/framos_realsense_node_factory.cpp:106:10: error: ‘rs2::d400e’ has not been declared
  106 |     rs2::d400e::cli_arg carg;
      |          ^~~~~
/home/franka/cam_fi/src/realsense-ros/realsense2_camera/src/framos_realsense_node_factory.cpp:108:5: error: ‘carg’ was not declared in this scope
  108 |     carg.argc = 0;
      |     ^~~~
/home/franka/cam_fi/src/realsense-ros/realsense2_camera/src/framos_realsense_node_factory.cpp:125:14: error: ‘rs2::d400e’ has not been declared
  125 |         rs2::d400e::set_cli_args(carg);
      |              ^~~~~
/home/franka/cam_fi/src/realsense-ros/realsense2_camera/src/framos_realsense_node_factory.cpp: In member function ‘void realsense2_camera::FramosRealSenseNodeFactory::setDeviceFilterList()’:
/home/franka/cam_fi/src/realsense-ros/realsense2_camera/src/framos_realsense_node_factory.cpp:131:17: error: ‘rs2_d400e_filter’ was not declared in this scope
  131 |     std::vector<rs2_d400e_filter> filter_list;
      |                 ^~~~~~~~~~~~~~~~
/home/franka/cam_fi/src/realsense-ros/realsense2_camera/src/framos_realsense_node_factory.cpp:131:33: error: template argument 1 is invalid
  131 |     std::vector<rs2_d400e_filter> filter_list;
      |                                 ^
/home/franka/cam_fi/src/realsense-ros/realsense2_camera/src/framos_realsense_node_factory.cpp:131:33: error: template argument 2 is invalid
/home/franka/cam_fi/src/realsense-ros/realsense2_camera/src/framos_realsense_node_factory.cpp:132:21: error: expected ‘;’ before ‘filter’
  132 |     rs2_d400e_filter filter;
      |                     ^~~~~~~
      |                     ;
/home/franka/cam_fi/src/realsense-ros/realsense2_camera/src/framos_realsense_node_factory.cpp:133:5: error: ‘filter’ was not declared in this scope; did you mean ‘rs2::filter’?
  133 |     filter.serial_range.begin = 0;
      |     ^~~~~~
      |     rs2::filter
In file included from /opt/ros/noetic/include/librealsense2/hpp/rs_sensor.hpp:9,
                 from /opt/ros/noetic/include/librealsense2/hpp/rs_device.hpp:8,
                 from /opt/ros/noetic/include/librealsense2/hpp/rs_record_playback.hpp:8,
                 from /opt/ros/noetic/include/librealsense2/hpp/rs_context.hpp:8,
                 from /opt/ros/noetic/include/librealsense2/rs.hpp:9,
                 from /home/franka/cam_fi/src/realsense-ros/realsense2_camera/src/../include/../include/realsense_node_factory.h:12,
                 from /home/franka/cam_fi/src/realsense-ros/realsense2_camera/src/../include/framos_realsense_node_factory.h:6,
                 from /home/franka/cam_fi/src/realsense-ros/realsense2_camera/src/framos_realsense_node_factory.cpp:4:
/opt/ros/noetic/include/librealsense2/hpp/rs_processing.hpp:361:11: note: ‘rs2::filter’ declared here
  361 |     class filter : public processing_block, public filter_interface
      |           ^~~~~~
/home/franka/cam_fi/src/realsense-ros/realsense2_camera/src/framos_realsense_node_factory.cpp:142:21: error: request for member ‘push_back’ in ‘filter_list’, which is of non-class type ‘int’
  142 |         filter_list.push_back(filter);
      |                     ^~~~~~~~~
/home/franka/cam_fi/src/realsense-ros/realsense2_camera/src/framos_realsense_node_factory.cpp:148:21: error: request for member ‘push_back’ in ‘filter_list’, which is of non-class type ‘int’
  148 |         filter_list.push_back(filter);
      |                     ^~~~~~~~~
/home/franka/cam_fi/src/realsense-ros/realsense2_camera/src/framos_realsense_node_factory.cpp:151:21: error: request for member ‘size’ in ‘filter_list’, which is of non-class type ‘int’
  151 |     if (filter_list.size() > 0) {
      |                     ^~~~
/home/franka/cam_fi/src/realsense-ros/realsense2_camera/src/framos_realsense_node_factory.cpp:152:14: error: ‘rs2::d400e’ has not been declared
  152 |         rs2::d400e::set_device_filter_list(filter_list);
      |              ^~~~~
/home/franka/cam_fi/src/realsense-ros/realsense2_camera/src/base_realsense_node.cpp: In member function ‘void realsense2_camera::BaseRealSenseNode::publishPointCloud(rs2::points, const ros::Time&, const rs2::frameset&)’:
/home/franka/cam_fi/src/realsense-ros/realsense2_camera/src/base_realsense_node.cpp:2165:29: error: ‘find_if’ was not declared in this scope
 2165 |         texture_frame_itr = find_if(frameset.begin(), frameset.end(), [&texture_source_id, &available_formats] (rs2::frame f)
      |                             ^~~~~~~
/home/franka/cam_fi/src/realsense-ros/realsense2_camera/src/base_realsense_node.cpp:2165:29: note: suggested alternatives:
In file included from /usr/include/c++/9/algorithm:62,
                 from /usr/include/boost/smart_ptr/shared_ptr.hpp:39,
                 from /usr/include/boost/shared_ptr.hpp:17,
                 from /opt/ros/noetic/include/class_loader/class_loader.hpp:36,
                 from /opt/ros/noetic/include/pluginlib/./class_list_macros.hpp:40,
                 from /opt/ros/noetic/include/pluginlib/class_list_macros.h:35,
                 from /home/franka/cam_fi/src/realsense-ros/realsense2_camera/src/../include/../include/realsense_node_factory.h:6,
                 from /home/franka/cam_fi/src/realsense-ros/realsense2_camera/src/../include/base_realsense_node.h:6,
                 from /home/franka/cam_fi/src/realsense-ros/realsense2_camera/src/base_realsense_node.cpp:1:
/usr/include/c++/9/bits/stl_algo.h:3960:5: note:   ‘std::find_if’
 3960 |     find_if(_InputIterator __first, _InputIterator __last,
      |     ^~~~~~~
In file included from /usr/include/boost/mpl/find.hpp:17,
                 from /usr/include/boost/mpl/aux_/contains_impl.hpp:20,
                 from /usr/include/boost/mpl/contains.hpp:20,
                 from /usr/include/boost/math/policies/policy.hpp:10,
                 from /usr/include/boost/math/policies/error_handling.hpp:21,
                 from /usr/include/boost/math/special_functions/round.hpp:14,
                 from /opt/ros/noetic/include/ros/time.h:58,
                 from /opt/ros/noetic/include/ros/console.h:39,
                 from /opt/ros/noetic/include/nodelet/nodelet.h:40,
                 from /home/franka/cam_fi/src/realsense-ros/realsense2_camera/src/../include/../include/realsense_node_factory.h:7,
                 from /home/franka/cam_fi/src/realsense-ros/realsense2_camera/src/../include/base_realsense_node.h:6,
                 from /home/franka/cam_fi/src/realsense-ros/realsense2_camera/src/base_realsense_node.cpp:1:
/usr/include/boost/mpl/find_if.hpp:32:8: note:   ‘boost::mpl::find_if’
   32 | struct find_if
      |        ^~~~~~~
make[2]: *** [realsense-ros/realsense2_camera/CMakeFiles/realsense2_camera.dir/build.make:76：realsense-ros/realsense2_camera/CMakeFiles/realsense2_camera.dir/src/framos_realsense_node_factory.cpp.o] 错误 1
make[2]: *** 正在等待未完成的任务....
make[2]: *** [realsense-ros/realsense2_camera/CMakeFiles/realsense2_camera.dir/build.make:89：realsense-ros/realsense2_camera/CMakeFiles/realsense2_camera.dir/src/base_realsense_node.cpp.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:1485：realsense-ros/realsense2_camera/CMakeFiles/realsense2_camera.dir/all] 错误 2
make: *** [Makefile:130：all] 错误 2
Invoking "make -j8 -l8" failed

**Comment by MartyG-RealSense** [comment]
Hi @Shillin123  The command `catkin_make -DCATKIN_ENABLE_TESTING=False -DCMAKE_BUILD_TYPE=Release` is known to cause problems when installing the RealSense ROS wrapper on Windows.  It is caused by **-DCATKIN_ENABLE_TESTING=False** but setting it to True instead of False can cause a different error to occur.  

Examples of past cases where this problem is discussed are https://github.com/IntelRealSense/realsense-ros/issues/1797 and https://github.com/IntelRealSense/realsense-ros/issues/2280

There is not a clear solution for this issue, though a couple of RealSense ROS users affected by it reported that the problem disappeared if they used an older version of the ROS wrapper.  For one of those users at https://github.com/IntelRealSense/realsense-ros/issues/2280#issuecomment-1411759588 ROS1 wrapper **2.2.22** worked for them.  The correct librealsense SDK match for that wrapper version is **2.42.0**.

The majority of RealSense ROS users use Linux instead of Windows and so do not experience this problem with -DCATKIN_ENABLE_TESTING=False.

**Comment by Shillin123** [comment]
Thanks, I solved it!

**Comment by MartyG-RealSense** [comment]
That's excellent news, @Shillin123 - thanks very much for the update!

**Comment by MartyG-RealSense** [comment]
Case closed due to solution achieved and no further comments received.
