### ISSUE TITLE
ENU frame

### ISSUE THREAD

**Issue by futuristic2023** [realsenseai/realsense-ros#2657]
how to view the enu frame i followed the previous issues related to it but it not helping
can you please share this how to view enu frame

**Comment by MartyG-RealSense** [comment]
Hi @shivangi-futuristicbots  Considering your earlier issue at https://github.com/IntelRealSense/realsense-ros/issues/2642 I wonder if the question is actually 'How to view odometry'.  If it is then the link below provides guidance about viewing odometry in Rviz.

http://wiki.ros.org/rviz/DisplayTypes/Odometry

**Comment by futuristic2023** [comment]
i meant robot_localization assumes an ENU frame for all IMU data, so is this set by default or do i have to set it as a parameter?

**Comment by MartyG-RealSense** [comment]
In the ROS map convention information at the link below, it states that when defining coordinate frames with respect to a global reference like the earth, the default should be to align the x-axis east, y-axis north, and the z-axis up at the origin of the coordinate frame.  This convention is **ENU**, which stands for East, North, Up.  

East is X, North is Y and Up is Z.

My understanding is that by default ROS uses **FLU** (Forward, Left, Up) where X is forward, Y is left and Z is up), as confirmed by the creator of the RealSense ROS1 wrapper at https://github.com/IntelRealSense/realsense-ros/issues/1099#issuecomment-658101736

**Comment by MartyG-RealSense** [comment]
Hi @shivangi-futuristicbots  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
