### ISSUE TITLE
Camera SR300: Pointcloud ignores black objects and /camera/depth_registered/points fails to get updated at times

### ISSUE THREAD

**Issue by Janani-Mohan** [realsenseai/realsense-ros#266]
### System Configuration

| Version               | Your Configuration   |
|:--------------------- |:---------------------|
| Operating System      | Ubuntu 14.04               |
| Kernel                | 4.4.0-93-generic               |
| ROS                   | Indigo                    |
| ROS RealSense         | 1.8.0            |
| librealsense          | 1.12.1                |
| Camera Type-Firmware  | 3.21.0.0            |

### Expected Behavior
Pointcloud should show black objects. Depth image should be according to the depth of object in the frame and not on the color of the object. 

### Actual Behavior
Pointcloud data ignores black objects. Depth image for black objects is also weird (its completely black).
Kindly find the images below which shows the problem clearly.

![out](https://user-images.githubusercontent.com/22061186/30556244-24b842b0-9c78-11e7-8efd-b5381548d286.png)

![out1](https://user-images.githubusercontent.com/22061186/30556252-29ccfb10-9c78-11e7-9618-91051fa1d33a.png)

### Steps to Reproduce
roslaunch realsense_camera sr300_nodelet_rgbd.launch
rosrun rviz rviz with the rviz configuration

**Has anybody faced a similar issue ? Is this a limitation of camera hardware ? Another issue is at times the pointcloud fails to get updated. I am working on a project to develop a 3D mesh using Intel Realsense from depth image. But the mesh fails to capture black objects and pointcloud data which I need for detecting objects also fails to capture black object.**

Any support offered would be great!!

Thanks,
Janani

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Close this issue for lack of activity. Please feel free to reopen if the issue is still relevant.
