### ISSUE TITLE
Noetic + openCV/librealsense built with CUDA

### ISSUE THREAD

**Issue by arpaterson** [realsenseai/realsense-ros#2662]
Regarding building the wrapper for noetic (v2.3.2) over OpenCV + CUDA and librealsense (v2.50.0) + native USB + CUDA (from source).

It is already known that OpenCV is not linked properly (possibly just later versions of OpenCV).

Is it possible for the noetic branch of realsense-ros to get a fix for this?
Or a single commit branch containing the changes to CMakeLists.txt?

That would make it easier to use as a submodule. Currently I am manually editing CMakeLists.txt after checkout, for lack of knowing a better way to do that.

**Comment by MartyG-RealSense** [comment]
Hi @arpaterson  Development of the ROS1 wrapper (Kinetic, Melodic, Noetic) has ceased and the wrapper is now called **ros1-legacy**.  The focus of RealSense ROS development is now on the **ros2-development** ROS2 wrapper.

There is the ability for RealSense ROS users to create a custom **fork** version of the ROS1 wrapper to host on their own GitHub account and make an edit to that forked version themselves.

https://github.com/IntelRealSense/realsense-ros/tree/ros1-legacy

![image](https://user-images.githubusercontent.com/41145062/225752729-9a7017e8-f588-4389-9a4a-9ad167060fd2.png)

**Comment by MartyG-RealSense** [comment]
Hi @arpaterson  Do you require further assistance with this case, please?  Thanks!

**Comment by arpaterson** [comment]
No, thank you for your help.

**Comment by MartyG-RealSense** [comment]
Thanks very much for the update!  As you do not require further assistance, I will close this case.  Thanks again!
