### ISSUE TITLE
RSO2 Dynamic reconfigure for RGB camera parameters (D455/D457)

### ISSUE THREAD

**Issue by ruthvik92** [realsenseai/realsense-ros#2663]
Hello,
I am using a D455 with ROS2, I would like to get hold of an example that shows how to set RGB camera parameters dynamically. 
I have a simple subscriber python code that subscribes to RGB and Depth topics. I would like to modify this code to adjust the RGB camera parameters before I save an image to disk. 

ROS2 - Humble
Ubuntu - 22.04.2
Real sense drivers - 2.53.1

**Comment by MartyG-RealSense** [comment]
Hi @ruthvik92  ROS2 does not have dynamic_reconfigure.  It instead uses **rqt_reconfigure** to dynamically change parameters.  https://github.com/IntelRealSense/realsense-ros/issues/2565 demonstrates changing parameters with `ros2 run rqt_reconfigure rqt_reconfigure`

At https://github.com/IntelRealSense/realsense-ros/issues/345#issuecomment-374880904 a RealSense user discusses importing dynamic_reconfigure in a ROS Python script in ROS1 and setting parameters. I could not find a similar example for ROS2 to confirm whether that procedure was adaptable for import of **rqt_reconfigure** in Humble with a Python script though, unfortunately.

**Comment by MartyG-RealSense** [comment]
Hi @ruthvik92  Do you require further assistance with this case, please? Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
