### ISSUE TITLE
Trigger new release for Indigo and Kinetic

### ISSUE THREAD

**Issue by fmessmer** [realsenseai/realsense-ros#267]
Dear package maintainers,

since the last release (1.8.0) several features and fixes (in particular #244 and #259) have been added to this repo that we would need to release our own repos.
Do you intend to trigger a new release - for both Indigo and Kinetic - some time soon?
Thanks!

**Comment by fmessmer** [comment]
Hi guys,
any intention on triggering a new release for this repo?
is there anything blocking a new release atm?
Thanks

**Comment by fmessmer** [comment]
@icarpis @dorodnic 
we are still in need of a new release for indigo and kinetic due to the launch file renaming - which is blocking our release of `cob_robots`...do you see any chance in releasing this update before christmas?

**Comment by icarpis** [comment]
Hello @ipa-fxm, a new version of RealSense ROS 1 for indigo and kinetic will be released soon but I can't guarantee that it will be before Christmas.

**Comment by icarpis** [comment]
New version of RealSense ROS 1 for indigo and kinetic is [available](http://repositories.ros.org/status_page/ros_kinetic_default.html?q=realsense)
