### ISSUE TITLE
[ROS1] Pointcloud topic not publishing anything ROS melodic

### ISSUE THREAD

**Issue by IsaiahOdunze** [realsenseai/realsense-ros#2670]
I am trying to visualize pointcloud data using command "roslaunch realsense2_camera rs_camera.launch filters:=pointcloud" , yet nothing appears. I even try to echo the topic, but it seems like nothing is being published. Nothing shows up in RViz either. I am using a jetson nano to run this ROS package. On my Laptop running Ubuntu 20.04, the same camera works, and it even has the same output. Are there specific parameters needed to run the packages on a jetson nano or in Ubuntu 18.04?

Kernel Version: 4.9.140-tegra

Below is the output when running.

'''
titanauv@titanauv-desktop:/opt/ros/melodic/share/realsense2_camera/launch$ roslaunch rs_camera.launch filters:=pointcloud
... logging to /home/titanauv/.ros/log/b951de90-cce7-11ed-b4e2-00044beabd6b/roslaunch-titanauv-desktop-19325.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://titanauv-desktop:45187/

SUMMARY
========

PARAMETERS
 * /camera/realsense2_camera/accel_fps: -1
 * /camera/realsense2_camera/accel_frame_id: camera_accel_frame
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: False
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/allow_no_texture_points: False
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/calib_odom_file: 
 * /camera/realsense2_camera/clip_distance: -2.0
 * /camera/realsense2_camera/color_fps: -1
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: -1
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: -1
 * /camera/realsense2_camera/confidence_fps: -1
 * /camera/realsense2_camera/confidence_height: -1
 * /camera/realsense2_camera/confidence_width: -1
 * /camera/realsense2_camera/depth_fps: -1
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: -1
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: -1
 * /camera/realsense2_camera/device_type: 
 * /camera/realsense2_camera/enable_accel: False
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_confidence: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye1: False
 * /camera/realsense2_camera/enable_fisheye2: False
 * /camera/realsense2_camera/enable_fisheye: False
 * /camera/realsense2_camera/enable_gyro: False
 * /camera/realsense2_camera/enable_infra1: False
 * /camera/realsense2_camera/enable_infra2: False
 * /camera/realsense2_camera/enable_infra: False
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_pose: False
 * /camera/realsense2_camera/enable_sync: False
 * /camera/realsense2_camera/filters: pointcloud
 * /camera/realsense2_camera/fisheye1_frame_id: camera_fisheye1_f...
 * /camera/realsense2_camera/fisheye1_optical_frame_id: camera_fisheye1_o...
 * /camera/realsense2_camera/fisheye2_frame_id: camera_fisheye2_f...
 * /camera/realsense2_camera/fisheye2_optical_frame_id: camera_fisheye2_o...
 * /camera/realsense2_camera/fisheye_fps: -1
 * /camera/realsense2_camera/fisheye_frame_id: camera_fisheye_frame
 * /camera/realsense2_camera/fisheye_height: -1
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: -1
 * /camera/realsense2_camera/gyro_fps: -1
 * /camera/realsense2_camera/gyro_frame_id: camera_gyro_frame
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/imu_optical_frame_id: camera_imu_optica...
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra_fps: 30
 * /camera/realsense2_camera/infra_height: 480
 * /camera/realsense2_camera/infra_rgb: False
 * /camera/realsense2_camera/infra_width: 848
 * /camera/realsense2_camera/initial_reset: False
 * /camera/realsense2_camera/json_file_path: 
 * /camera/realsense2_camera/linear_accel_cov: 0.01
 * /camera/realsense2_camera/odom_frame_id: camera_odom_frame
 * /camera/realsense2_camera/ordered_pc: False
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/pose_frame_id: camera_pose_frame
 * /camera/realsense2_camera/pose_optical_frame_id: camera_pose_optic...
 * /camera/realsense2_camera/publish_odom_tf: True
 * /camera/realsense2_camera/publish_tf: True
 * /camera/realsense2_camera/reconnect_timeout: 6.0
 * /camera/realsense2_camera/rosbag_filename: 
 * /camera/realsense2_camera/serial_no: 
 * /camera/realsense2_camera/stereo_module/exposure/1: 7500
 * /camera/realsense2_camera/stereo_module/exposure/2: 1
 * /camera/realsense2_camera/stereo_module/gain/1: 16
 * /camera/realsense2_camera/stereo_module/gain/2: 16
 * /camera/realsense2_camera/tf_publish_rate: 0.0
 * /camera/realsense2_camera/topic_odom_in: odom_in
 * /camera/realsense2_camera/unite_imu_method: 
 * /camera/realsense2_camera/usb_port_id: 
 * /camera/realsense2_camera/wait_for_device_timeout: -1.0
 * /rosdistro: melodic
 * /rosversion: 1.14.13

NODES
  /camera/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)

auto-starting new master
process[master]: started with pid [19339]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to b951de90-cce7-11ed-b4e2-00044beabd6b
process[rosout-1]: started with pid [19353]
started core service [/rosout]
process[camera/realsense2_camera_manager-2]: started with pid [19370]
process[camera/realsense2_camera-3]: started with pid [19371]
[ INFO] [1679953117.184135567]: Initializing nodelet with 4 worker threads.
[ INFO] [1679953118.203568213]: RealSense ROS v2.3.2
[ INFO] [1679953118.203660037]: Built with LibRealSense v2.50.0
[ INFO] [1679953118.203782487]: Running with LibRealSense v2.50.0
[ INFO] [1679953118.284916471]:  
[ INFO] [1679953118.673225000]: Device with serial number 843112071279 was found.

[ INFO] [1679953118.673335783]: Device with physical ID 2-1.1-3 was found.
[ INFO] [1679953118.673380523]: Device with name Intel RealSense D435I was found.
[ INFO] [1679953118.674777266]: Device with port number 2-1.1 was found.
[ INFO] [1679953118.674867788]: Device USB type: 3.2
[ INFO] [1679953118.682389583]: getParameters...
[ INFO] [1679953118.984208776]: setupDevice...
[ INFO] [1679953118.984302059]: JSON file is not provided
[ INFO] [1679953118.984360394]: ROS Node Namespace: camera
[ INFO] [1679953118.984422270]: Device Name: Intel RealSense D435I
[ INFO] [1679953118.984477479]: Device Serial No: 843112071279
[ INFO] [1679953118.984530397]: Device physical port: 2-1.1-3
[ INFO] [1679953118.984578314]: Device FW version: 05.14.00.00
[ INFO] [1679953118.984621700]: Device Product ID: 0x0B3A
[ INFO] [1679953118.984663836]: Enable PointCloud: On
[ INFO] [1679953118.984706754]: Align Depth: Off
[ INFO] [1679953118.984749515]: Sync Mode: On
[ INFO] [1679953118.984887225]: Device Sensors: 
[ INFO] [1679953119.099061354]: Stereo Module was found.
[ INFO] [1679953119.158830547]: RGB Camera was found.
[ INFO] [1679953119.159637644]: Motion Module was found.
[ INFO] [1679953119.159871450]: (Confidence, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1679953119.159972598]: Add Filter: pointcloud
[ INFO] [1679953119.161570021]: num_filters: 1
[ INFO] [1679953119.161672574]: Setting Dynamic reconfig parameters.
hwmon command 0x80( 5 0 0 0 ) failed (response -7= HW not ready)
hwmon command 0x80( 5 0 0 0 ) failed (response -7= HW not ready)
hwmon command 0x80( 5 0 0 0 ) failed (response -7= HW not ready)
hwmon command 0x80( 5 0 0 0 ) failed (response -7= HW not ready)
[ INFO] [1679953124.234398678]: Done Setting Dynamic reconfig parameters.
[ INFO] [1679953124.235833806]: depth stream is enabled - width: 848, height: 480, fps: 30, Format: Z16
[ INFO] [1679953124.238505622]: color stream is enabled - width: 1280, height: 720, fps: 30, Format: RGB8
[ INFO] [1679953124.238628020]: setupPublishers...
[ INFO] [1679953124.251494593]: Expected frequency for depth = 30.00000
[ INFO] [1679953124.390698104]: Expected frequency for color = 30.00000
[ INFO] [1679953124.486515096]: setupStreams...
 27/03 14:38:44,719 WARNING [547769409920] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
[ INFO] [1679953124.769968661]: SELECTED BASE:Depth, 0
[ INFO] [1679953124.819065225]: RealSense Node Is Up!
[ WARN] [1679953124.841117162]: 
 27/03 14:38:44,842 WARNING [547769409920] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 27/03 14:38:44,892 WARNING [547769409920] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 27/03 14:38:44,943 WARNING [547769409920] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 27/03 14:38:45,185 WARNING [547769409920] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 27/03 14:38:45,235 WARNING [547769409920] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 27/03 14:38:45,387 WARNING [547769409920] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
[ INFO] [1679953150.160858702]: publishing unordered pointcloud.
[ WARN] [1679953150.813787104]: No stream match for pointcloud chosen texture Process - Color
'''

**Comment by MartyG-RealSense** [comment]
Hi @IsaiahOdunze  The warning **No stream match for pointcloud chosen texture Process - Color** means that the color stream is dropping frames.

The warning **control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11** indicates that there is a communication problem between the camera and the computer / computing device.  

There are known issues with using the pointcloud filter on Jetson boards specifically.  A workaround in ROS1 is to use the **rs_rgbd.launch** launch file instead of rs_camera.launch.

You will first need to install support for an RGBD launch in Melodic by using the instruction below in the Ubuntu terminal.

`sudo apt-get install ros-melodic-rgbd-launch`

Then perform the rs_rgbd launch.

**roslaunch realsense2_camera rs_rgbd.launch**

With this launch file there is no need to enable the pointcloud filter with `filters:=pointcloud`.  It will automatically generate a point cloud that is published at **depth_image_proc**

**Comment by IsaiahOdunze** [comment]
Thank you, that fixed my problem. @MartyG-RealSense  I have one more question if you don't mind. Is there a way to configure the launch files to only publish pointcloud data, or do you always have to run the camera to run the point cloud? I see that Linux abstracts the realsense camera into three video files (/dev/video0 , /dev/video1, and /dev/video2) and I was wondering if it was possible to only publish point cloud data but not raw camera feed. I want to use the camera feed in another application and it would be easier if it wasn't publishing here. If this is not possible, then this issues branch can be closed. Thanks again!

**Comment by MartyG-RealSense** [comment]
The /video channels will only stream raw camera data, unfortunately.

As you suggested, I will close this issue as only raw data can be provided by the /video channels.  Thanks!
