### ISSUE TITLE
Is there a topic or method to change the max points generated in a pointcloud in realsense D435, 455?

### ISSUE THREAD

**Issue by Gaurav37** [realsenseai/realsense-ros#2671]

**Comment by MartyG-RealSense** [comment]
Hi @Gaurav37  There is not a setting in the RealSense ROS wrapper for defining a maximum number of points in a pointlcoud, though you may be able to reduce its density by setting the **ordered_pc** parameter to true in your launch instruction.

**ROS1**
`roslaunch realsense2_camera rs_camera.launch filters:=pointcloud ordered_pc:=true`

**ROS2**
`ros2 launch realsense2_camera rs_launch.py pointcloud.enable = true pointcloud.ordered_pc=true`
