### ISSUE TITLE
update exposure during camera running via ROS

### ISSUE THREAD

**Issue by robopassio** [realsenseai/realsense-ros#2673]
Hi,

Any way to update exposure during camera running via ROS topics corresponding to
```
sensor = profile.get_device().first_color_sensor()
sensor.set_option(rs.option.enable_auto_exposure, True)
sensor.set_option(rs.option.auto_exposure_limit, 100)
sensor.set_option(rs.option.exposure, exposure_number)
```

**Comment by MartyG-RealSense** [comment]
Hi @robopassio  When auto_exposure is true, the camera's exposure value does not update.  If you are using ROS1 (Kinetic, Melodic, Noetic) then you could disable auto_exposure and set a manual exposure value during runtime with **dynamic_reconfigure** instructions.

For example, to disable auto_exposure and set RGB exposure in ROS1:

```
rosrun dynamic_reconfigure dynparam set /camera/stereo_module enable_auto_exposure 0
rosrun dynamic_reconfigure dynparam set /camera/rgb_camera exposure 100
```

I recommend not using auto_exposure_limit as it has been reported by RealSense users in a number of cases to not work and returns an error.  An example of such a report is at  https://github.com/IntelRealSense/librealsense/issues/10241
