### ISSUE TITLE
Error running with Opencv 4.7.0

### ISSUE THREAD

**Issue by BryanBetancur** [realsenseai/realsense-ros#2678]
Hello, I upgrade to Opencv 4.7.0 but when camera starts to stream it shows the next one error:

`[ERROR] [1680291461.550072783] [CompressedPublisher]: OpenCV(4.7.0) /root/opencv/modules/imgcodecs/src/loadsave.cpp:1145: error: (-2:Unspecified error) in function 'bool cv::imencode(const String&, cv::InputArray, std::vector&, const std::vector&)'`

`> Encoding 'params' must be key-value pairs:`
`> '(params.size() & 1) == 0'`
`> where`
`> 'params.size()' is 3`

Do you know how to handle it? Thank you.

**Comment by BryanBetancur** [comment]
I did debug to your code and the problem is when it publish, so I thing it should be a problem with image_transport or cv_bridge.

**Comment by MartyG-RealSense** [comment]
Thanks very much @BryanBetancur for the update!
