### ISSUE TITLE
enable l515 depth filter

### ISSUE THREAD

**Issue by robopassio** [realsenseai/realsense-ros#2682]
Hi,

Is there anyway to enable filtering of depth data using ros command to obtain similar result like [here](https://github.com/IntelRealSense/librealsense/tree/development/examples/post-processing)?
There is a line in rs_rgbd.launch file:
```
      <arg name="filters"                  value="$(arg filters)"/>
```
is this related to my scope or what should I do to enable?

**Comment by MartyG-RealSense** [comment]
Hi @robopassio  It is possible to enable post-processing filters in the RealSense ROS wrapper (though it does not support all of the filters that are available in librealsense).  However, the L515 camera model only supports the **Temporal** depth post-processing filter and the **Decimation** RGB post-processing filter for downsampling the resolution.

I cannot recall a previous case of these filters being used with L515 in the ROS wrapper.  

https://github.com/IntelRealSense/realsense-ros/issues/583 though provides advice about configuring the Decimation filter, by first adding `filters:=decimation` to the roslaunch instruction and then configuring the filter's **magnitude** setting with a rosrun instruction during runtime after launch has completed.

Adding` filters:=temporal` to the roslaunch instruction should enable the temporal filter for depth whilst https://github.com/IntelRealSense/realsense-ros/issues/501#issuecomment-479014599 has an example of defining it as an arg in the launch file.

**Comment by robopassio** [comment]
Thanks @MartyG-RealSense! is there any way to configurate parameters of the `temporal` filter during running? which ros topic I can communicate to?

**Comment by MartyG-RealSense** [comment]
The Intel RealSense developer who created the ROS1 wrapper advises at https://github.com/IntelRealSense/realsense-ros/issues/742#issuecomment-720295533 how to get a list of parameters for the temporal filter.

**Comment by MartyG-RealSense** [comment]
Hi @robopassio  Do you require further assistance with this case, please?  Thanks!
