### ISSUE TITLE
Infrared sensor topic 

### ISSUE THREAD

**Issue by futuristic2023** [realsenseai/realsense-ros#2687]
Hi @MartyG-RealSense,

I work through therealsense topic list , i am able to find the following topic list but i also want the infrared image with it:

**

> /camera/color/camera_info
> /camera/color/image_raw
> /camera/color/metadata
> /camera/depth/camera_info
> /camera/depth/color/points
> /camera/depth/image_rect_raw
> /camera/depth/metadata
> /camera/extrinsics/depth_to_color
> /camera/imu
> /parameter_events
> /rosout

**

command line to run this: `ros2 launch realsense2_camera rs_launch.py depth_module.profile:=1280x720x30 pointcloud.enable:=true
`

**Comment by MartyG-RealSense** [comment]
Hi @shivangi-futuristicbots  In the RealSense ROS wrapper the infrared topics are disabled by default.  

https://github.com/IntelRealSense/realsense-ros/blob/ros2-development/realsense2_camera/launch/rs_launch.py#L38-L39

Please try adding the commands below onto the end of your launch instruction to enable them.

`enable_infra1:=true enable_infra2:=true`

**Comment by futuristic2023** [comment]
Thank You @MartyG-RealSense
