### ISSUE TITLE
timeout error while doing roslaunch

### ISSUE THREAD

**Issue by guancongyi** [realsenseai/realsense-ros#269]
I tried to build realsense camera from source on Ubuntu 16.04(kinetic). After doing everything, I connect the camera and run "roslaunch realsense_camera r200_nodelet_default.launch" It gives me a timeout error with a warning:

 
SUMMARY
========

PARAMETERS
 * /camera/driver/base_frame_id: camera_link
 * /camera/driver/camera_type: R200
 * /camera/driver/color_fps: 30
 * /camera/driver/color_frame_id: camera_rgb_frame
 * /camera/driver/color_optical_frame_id: camera_rgb_optica...
 * /camera/driver/depth_frame_id: camera_depth_frame
 * /camera/driver/depth_optical_frame_id: camera_depth_opti...
 * /camera/driver/fisheye_frame_id: camera_fisheye_frame
 * /camera/driver/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/driver/imu_frame_id: camera_imu_frame
 * /camera/driver/imu_optical_frame_id: camera_imu_optica...
 * /camera/driver/ir2_frame_id: camera_ir2_frame
 * /camera/driver/ir2_optical_frame_id: camera_ir2_optica...
 * /camera/driver/ir_frame_id: camera_ir_frame
 * /camera/driver/ir_optical_frame_id: camera_ir_optical...
 * /camera/driver/mode: manual
 * /camera/driver/serial_no: 
 * /camera/driver/usb_port_id: 
 * /rosdistro: kinetic
 * /rosversion: 1.12.7

NODES
  /camera/
    driver (nodelet/nodelet)
    nodelet_manager (nodelet/nodelet)

auto-starting new master
process[master]: started with pid [7902]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to cf77e09e-ad20-11e7-966d-48f8b380865b
process[rosout-1]: started with pid [7917]
started core service [/rosout]
process[camera/nodelet_manager-2]: started with pid [7934]
process[camera/driver-3]: started with pid [7935]
[ INFO] [1507574210.562657059]: Initializing nodelet with 4 worker threads.
[ INFO] [1507574210.992610837]: /camera/driver - Detected the following camera:
				- Serial No: 2361004113, USB Port ID: 2-1, Name: Intel RealSense R200, Camera FW: 1.0.72.10
 **[ WARN] [1507574210.992785561]: /camera/driver - Detected unvalidated firmware:
				- 2361004113's current camera firmware is 1.0.72.10, Validated camera firmware is 1.0.72.06**
[ INFO] [1507574210.992981121]: /camera/driver - Connecting to camera with Serial No: 2361004113, USB Port ID: 2-1
[ INFO] [1507574213.854753145]: /camera/driver - Setting static camera options
[ INFO] [1507574213.897164539]: /camera/driver - Enabling Depth in manual mode
[ INFO] [1507574213.898080782]: /camera/driver - Enabling Color in manual mode
[ INFO] [1507574213.898999063]: /camera/driver - Starting camera
[ INFO] [1507574213.933744261]: /camera/driver - Publishing camera transforms (/tf_static)
[ INFO] [1507574213.934727257]: /camera/driver - Setting dynamic camera options (r200_dc_preset=5)
[ INFO] [1507574214.769626115]: /camera/driver - Initializing Depth Control Preset to 5
[ INFO] [1507574217.980569925]: /camera/driver - Setting dynamic camera options
**[ERROR] [1507574219.915329004]: /camera/driver - Error calling rs_wait_for_frames ( device:0xb5b660 ): 
Timeout waiting for frames.** 

[camera/nodelet_manager-2] process has finished cleanly
log file: /home/upboard/.ros/log/cf77e09e-ad20-11e7-966d-48f8b380865b/camera-nodelet_manager-2*.log
[camera/driver-3] process has finished cleanly
log file: /home/upboard/.ros/log/cf77e09e-ad20-11e7-966d-48f8b380865b/camera-driver-3*.log

I am confused for a long time, I would be grateful if anyone answers.

**Comment by jlgarcia75** [comment]
Hello @guancongyi,

The timeout error is usually related to the USB port on the system that the camera is connected to. Try connecting the camera to other USB3 ports or use a powered USB 3 HUB. Also, test the camera on another system.

Regards,
Jesus
Intel Customer Support

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Close this issue for lack of activity. Please feel free to reopen if the issue is still relevant.
