### ISSUE TITLE
How to alternate emitter pattern,toggled on/off on per-frame basis in d435i?

### ISSUE THREAD

**Issue by kao-yang** [realsenseai/realsense-ros#2690]
How to alternate emitter pattern,toggled on/off on per-frame basis in d435i?Just like realsense_viewer.
![issuse](https://user-images.githubusercontent.com/57090523/231407002-72800483-436e-4545-a2fa-c50a218bfa87.png)

I want to use both stero images while emitter off (for SLAM) and depth images while emitter on (depth images are more accurate). I found this option in realsense_view, so how do I implement it in realsense_ros?

**Comment by MartyG-RealSense** [comment]
Hi @kao-yang  In the RealSense ROS wrapper you should be able to enable per-frame alternating of the emitter by adding the command below to the end of your ROS launch instruction.

`emitter_on_off:=true`

If you are using ROS1 (Kinetic, Melodic, Noetic) then you could also try enabling the emitter on-off during runtime after launch with the command below.

`rosrun dynamic_reconfigure dynparam set /camera0/stereo_module emitter_on_off 1`

**Comment by MartyG-RealSense** [comment]
Hi @kao-yang  Do you require further assistance with this case, please?  Thanks!

**Comment by kao-yang** [comment]
> Hi @kao-yang Do you require further assistance with this case, please? Thanks!

It works!Thanks for your help!

**Comment by MartyG-RealSense** [comment]
That's excellent news that you succeeded.  Thanks very much for the update!
