### ISSUE TITLE
ros2 launch error

### ISSUE THREAD

**Issue by futuristic2023** [realsenseai/realsense-ros#2692]
Hi **@MartyG-RealSense,** 

i need to resolve some error that encounters when i run the realsense camera:

![Screenshot from 2023-04-13 09-59-40](https://user-images.githubusercontent.com/117429661/231655133-82e8a5bf-c875-4a7f-9bca-d1b466e73853.png)

**Comment by MartyG-RealSense** [comment]
Hi @shivangi-futuristicbots  The red **auto_exposure_limit** and **auto_gain_limit** errors usually occur if using librealsense 2.51.1 with firmware driver version **5.14.0.0**.  5.14 has some changes to auto_exposure_limit and auto_gain_limit in it that cause errors unless used with SDK 2.53.1 as 5.14 is the recommended firmware for that version.  The log lists that your firmware version is indeed 5.14.0.0.

![image](https://user-images.githubusercontent.com/41145062/231802729-a6c1d522-7ce6-47bf-888e-b540d8281942.png)

For SDK 2.51.1, firmware **5.13.0.50** should be installed in the camera and then these errors should disappear.

**Comment by futuristic2023** [comment]
Hi @MartyG-RealSense, Thanks for the reply but i want to ask how to install the SDK 2.51.1 firware 5.13.0.50 , 
i followed  the guildlines provided in the [SDK](https://github.com/IntelRealSense/librealsense/blob/master/doc/distribution_linux.md#installing-the-packages) ibut there is no  version specification provided during the time of installation.

**Comment by MartyG-RealSense** [comment]
If you are able to use the RealSense Viewer tool then you can install a specific firmware version by downloading it as a .bin file from the list on the firmware releases page.

https://dev.intelrealsense.com/docs/firmware-releases#section-d400-series-firmware-downloads

Then go to the **More** option near the top of the Viewer's options side-panel and select the **Update Firmware** option from its drop-down menu. This will cause a file selector window to pop up. Select the firmware .bin folder from the location on your computer that you downloaded it to and then the firmware update will commence.

![image](https://user-images.githubusercontent.com/41145062/127628286-bfeba1b5-c408-4b29-8a5e-681076ecd362.png)

If you are not able to use the RealSense Viewer tool then you can instead use the **rs-fw-update** tool with a specific firmware .bin file.

https://github.com/IntelRealSense/librealsense/tree/master/tools/fw-update

**Comment by MartyG-RealSense** [comment]
Hi @shivangi-futuristicbots   Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
