### ISSUE TITLE
Managing the Enabling and Disabling of Published Topics.

### ISSUE THREAD

**Issue by Llavrih** [realsenseai/realsense-ros#2697]
Is there a method to selectively disable topics that are not required for my specific application while using ROS Noetic or potentially transitioning to ROS2? I am utilizing two D435f cameras, and the only topics necessary for my use case are /cam_1/depth/color/points and /cam_2/depth/color/points. The primary objective of this modification is to minimize CPU consumption.

**Comment by MartyG-RealSense** [comment]
Hi @Llavrih  It is possible to **unsubscribe** from topics.

As you likely need depth and color enabled to publish the depth/color/points topics, and the Infrared and IMU topics are aready disabled by default in the ROS wrapper, there is not likely to be a significant gain to be made from unsubscribing from the remaining published topics, such as /diagnostics

You could reduce CPU usage if you had an Nvidia Jetson computing board, as RealSense supports acceleration of point cloud generation with **CUDA** support for the Nvidia graphics GPU on the Jetson, offloading work from the CPU onto the GPU.

**Comment by Llavrih** [comment]
At the moment, I'm subscribed to only those two topics. I'm working with Python and Open3D to process point clouds, and I'm particularly interested in reducing my CPU usage. Unfortunately, Open3D doesn't support working on CUDA, so I can't take advantage of GPU acceleration.

**Comment by MartyG-RealSense** [comment]
You could try an **RGBD** launch in ROS1 with the **rs_rgbd.launch** launch file to see whether it has better performance.

To use rs_rgbd, you should first install support for an RGBD launch by using the instruction below in the Ubuntu terminal.

`sudo apt-get install ros-noetic-rgbd-launch`

Once support for an RGBD launch is installed, use the roslaunch command below in the ROS terminal.

`roslaunch realsense2_camera rs_rgbd.launch`

rs_rgbd.launch should by default generate a point cloud that is published at **depth_image_proc** - you do not need to enable the pointcloud filter like you do in an rs_camera launch.

**Comment by Llavrih** [comment]
Okay thanks for help @MartyG-RealSense , I'm gonna try this.

**Comment by MartyG-RealSense** [comment]
Hi @Llavrih  Do you require further assistance with this case, please?  Thanks!

**Comment by Llavrih** [comment]
Hi @MartyG-RealSense. We can close the topic. However, this would be a nice feature especially for less powerful computers.

**Comment by MartyG-RealSense** [comment]
I researched the issue of unsubscription further but was unable to find a simple method of unsubscribing, as it apparently usually involves writing a ROS node script in C++ or Python to do so.  For example:

https://itecnote.com/tecnote/c-unsubscribe-from-a-topic-and-subscribe-from-a-new-one-runtime-c-ros/

It seems that disabling a topic's **display** in RViz by un-ticking a checkbox also unsubscribes it.

http://docs.ros.org/en/fuerte/api/rviz/html/classrviz_1_1Display.html
