### ISSUE TITLE
Temperamental failures

### ISSUE THREAD

**Issue by lkm1321** [realsenseai/realsense-ros#270]
### System Configuration
|Operating System | Ubuntu 16.04.3 LTS (inside docker)|
|Kernel | 4.4.67-yocto-standard (Aero-Poky 1.4.0)|
|Aero Compute board BIOS|Aero-01.00.12_Prod|
|ROS | kinetic| 
|ROS RealSense | 1.8.0|
|librealsense | 1.12.1|
|Camera Type | Intel RealSense R200|
|Camera Firmware | 1.0.71.06|

### Expected Behavior
When I launch roslaunch realsense_camera r200_nodelet_rgbd.launch, I should get images on all topics. 

### Actual Behavior
/camera/ir /camera/ir2 /camera/depth topics fail temperamentally. When it fails, /camera/ir and /camera/ir2 have no data at all (i.e. rostopic echo returns nothing, rostopic hz returns no new messages). /camera/depth returns 0 in every pixel. The failure is persistent over a single launch. I.e. on a new launch instance, it may be fine.. 

### Steps to Reproduce
Not sure. 

### Question
What is the default behaviour when no ir stream is being received? Is there any disparity/depth conversion happening in librealsense or is it done on the ASIC inside realsense? I understand this kind of 'temperamental' error is hard to fix, but it would be nice to be notified when this is happening.

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Close this issue for lack of activity. Please feel free to reopen if the issue is still relevant.
