### ISSUE TITLE
ROS realsense D455 error & how to setup realsense tf in urdf 

### ISSUE THREAD

**Issue by TapleFlib** [realsenseai/realsense-ros#2700]
I'm working on a project using Techman Robot arm tm5-700 , I add my tool and camera model to their urdf and the respective tf. Problems :
1. I add a camera_link named camera in urdf and the tf is at the center of it (not the lens) , then I launch the moveit config for the robot arm and launch my realsense camera. Then the error appears in tf.
![image](https://user-images.githubusercontent.com/130976648/232443875-333e4dff-ee1b-46de-a812-19bace260ae9.png)

2. should I add tf for every frame that shows error in tf ? and should I set the tf to be at the center of the lens like the following picture?
![image](https://user-images.githubusercontent.com/130976648/232443994-0128a249-7326-428d-9a77-dbbf8296296a.png)

**Comment by MartyG-RealSense** [comment]
Hi @TapleFlib  The location on the camera of camera_link is discussed at https://github.com/IntelRealSense/realsense-ros/pull/1124 and confirms the center of the lens.

Regarding configuring TFs, i do not have information about that particular subject unfortunately.

**Comment by TapleFlib** [comment]
Got it, Thankyou very much !

**Comment by TapleFlib** [comment]
Do you know which link should I add to the robot arm urdf file as tf ? is it camera_link? or the base_link? (of the D455)

![image](https://user-images.githubusercontent.com/130976648/232720683-e7fb3129-ff89-493e-9738-ebebe24e04ab.png)

**Comment by MartyG-RealSense** [comment]
If you are linking a RealSense URDF camera model to a robot arm then I believe that **base_link** should be used, as the tripod thread at the base_link position is a camera mounting point.

**Comment by TapleFlib** [comment]
Sorry, one more question, the realsense urdf file is complicated as it includes few other files, which file should I include in my robot arm urdf file? I'm quite new to any of these things. Thanks in advance

![image](https://user-images.githubusercontent.com/130976648/232776237-4eefcdf6-53ae-48ae-ae8e-9603b8b6a425.png)

**Comment by TapleFlib** [comment]
@MartyG-RealSenseby the way, if I use base_link as the camera link to the robot arm urdf, will it work? cause from the first picture (I'll send it again) there are only 5 links that appear in tf not including base_link.

command : roslaunch realsense2_camera rs_camera.launch (is there better launch file to get depth value other than this?)

![image](https://user-images.githubusercontent.com/130976648/232783407-6fc720b6-ac8a-4391-87f2-ea85fe3b90a0.png)

**Comment by MartyG-RealSense** [comment]
Typically when using a RealSense URDF file, the launch file **rs_d435_camera_with_model.launch** will be used instead of rs_camera.launch.

If you are using a D455 instead of a D435 then you would likely have to edit the launch file to point to the D455 URDF instead of the D435 one, changing test_d435_camera.urdf.xacro to **test_d455_camera.urdf.xacro** 

https://github.com/IntelRealSense/realsense-ros/blob/ros1-legacy/realsense2_camera/launch/rs_d435_camera_with_model.launch#L107

**Comment by TapleFlib** [comment]
Sorry If my question is not clear enough, I mean I want to add the RealSense camera as a link in an existing urdf file. How to add the model ?

robot arm model urdf file :
![image](https://user-images.githubusercontent.com/130976648/232794304-5c015308-1800-47a7-8f57-d61b5f7850f2.png)

**Comment by MartyG-RealSense** [comment]
The question is outside of my ROS knowledge, unfortunately.  However, the link below about modifying a URDF file to add a RealSense camera to the end-effector of a robot arm might provide some useful insights though.

https://answers.gazebosim.org/question/24989/adding-intel-camera-to-robot-end-effector/?answer=24999#post-id-24999

**Comment by TapleFlib** [comment]
Got it, I added it already, thanks.
Hopefully last question : 
1. which roslaunch should I launch for horizontal pick and place project ? should I make my own launch file ? I found that some topic are not available on the other launch file. 
![image](https://user-images.githubusercontent.com/130976648/232856483-88a5917e-cd63-4502-b24a-b518d5c9de34.png)
2. If I want to change the resolution of the depth image, where should I change it ? the launch file ? it says depthcloud in rviz topic but the file said infra (848 x 480 size)

rviz/moveit that said depthcloud : 
![image](https://user-images.githubusercontent.com/130976648/232858224-79e22b37-c6a9-443f-a8d2-c09c79023ad0.png)

rs_camera.launch file that says infra 848 x 480: 
![image](https://user-images.githubusercontent.com/130976648/232857552-9729e7f5-eb7a-4f04-b5c6-fc0ed78d5014.png)

**Comment by MartyG-RealSense** [comment]
1.  rs_camera.launch should be fine for most applications.  If you have missing topics such as infrared and IMU (gyro and accel) then you can enable them by adding the commands below to your roslaunch instruction.

`enable_infra1:=true enable_infra2:=true enable_gyro:=true enable_accel:=true unite_imu_method:=linear_interpolation`

For example:

`roslaunch realsense2_camera rs_camera.launch enable_infra1:=true enable_infra2:=true enable_gyro:=true enable_accel:=true unite_imu_method:=linear_interpolation`

3.  You can either change the resolution in the launch file or configure a custom resolution in the roslaunch instruction.  For example in the ROS1 wrapper:

`roslaunch realsense2_camera rs_camera.launch depth_width:=848 depth_height:=480 depth_fps:=30 `

You must define values for three factors - width, height and FPS - for each type of stream that you use.  If all three factors are not defined then the launch will decide that the custom configuration is invalid and apply the default stream profile of the camera instead.  On a D455 this would be 848x480 depth and 1280x720 color.

**Comment by TapleFlib** [comment]
I will try, thankyou so much ! It's really helpful
