### ISSUE TITLE
[D435i & D455] Realsense-Multicam not working

### ISSUE THREAD

**Issue by jesusramondovale** [realsenseai/realsense-ros#2701]
Hi!

I'm working on a Raspberry Pi 4 (4GB RAM) with Ubuntu Server 22.04 LTS and ROS2-Humble Hawksbill installed.
I got both cameras (D455 and D435i) working perfectly *by separate* with your Realsense-ROS code.  

But, when I try to run both cameras at the same time (*ros2 launch realsense2_camera rs_multilaunch.py*) I got the next errors: 

`[ERROR] [1677764449.638660672] [camera2.camera2]: ./src/rs_node_setup.cpp:344:An exception has been thrown: xioctl(VIDIOC_S_FMT) failed Last Error: Device or resource busy
[realsense2_camera_node-2]                                                                                                                                                            
[ERROR] [1677764449.638942815] [camera2.camera2]: Error updating the sensors: xioctl(VIDIOC_S_FMT) failed Last Error: Device or resource busy
`

I achieved to make both work at the same time by using the single launch with serial_no parameter, but the problem is that both cameras publish the video images on the same topic (/camera/XXXX/YYYY) and you can see the image changing quickly and randomly between two cameras, all in the same view of the same topic, but I want to see each image separately, on different topics.

Could anyone give me some help with this? Thank you so much!

**Comment by MartyG-RealSense** [comment]
Hi @jesusramondovale  Does the problem still occur if you distinguish the cameras by name and device type in the rs_multi_camera_launch.py instruction?

`ros2 launch realsense2_camera rs_multi_camera_launch.py camera_name1:=D435 camera_name2:=D455 device_type1:=d435 device_type2:=d455`

**Comment by jesusramondovale** [comment]
Yes! Now both cameras work perfectly on different topics (/D435 and /D455) 

Thank you so much!

PD: I would edit the tutorial guide and include that command line.

**Comment by MartyG-RealSense** [comment]
You are very welcome.  I'm pleased that I could help  :)
