### ISSUE TITLE
How to display detected object 3D coordinate marker in rviz using Realsense D455

### ISSUE THREAD

**Issue by TapleFlib** [realsenseai/realsense-ros#2706]
How to display marker and get the position in 3D space of detected object using D455?
I want it to be like this video : https://www.youtube.com/watch?v=iJWHRW7sZW8
Are there example code for this?

**Comment by MartyG-RealSense** [comment]
Hi @TapleFlib  You could use **darknet_ros** - which uses YOLO v3 - in combination with **darknet_ros_3d** to obtain the 3D coordinate.  darknet_ros is run first to obtain 2D information and then darknet_ros_3d is run secondly to obtain 3D information.

**Comment by TapleFlib** [comment]
I'll try Thankyou !

**Comment by TapleFlib** [comment]
Is it enough to only use darknet_ros_3d without darknet_ros ? or both are required ? I'm planning to send the position of object to robot arm.

**Comment by MartyG-RealSense** [comment]
I have not personally used darknet_ros but a RealSense user at https://github.com/IntelligentRoboticsLabs/gb_visual_detection_3d/issues/15#issuecomment-634574521 stated that they were able to launch darknet_ros_3d without launching darknet_ros first.

**Comment by TapleFlib** [comment]
I see, thank you !
