### ISSUE TITLE
Waiting for image in rviz using darknet_ros

### ISSUE THREAD

**Issue by TapleFlib** [realsenseai/realsense-ros#2708]
Waiting for image when I already run the cam driver, darknet launch, and rviz.
launching files :

- camera : roslaunch realsense2_camera rs_camera.launch
- darknet : roslaunch darknet_ros yolo_v3.launch
- rviz : rviz

Ros : noetic

![image](https://user-images.githubusercontent.com/130976648/234055356-e098ce81-2d91-4f89-9994-4644c5641f8a.png)

![image](https://user-images.githubusercontent.com/130976648/234055212-814cb2b5-6f08-430b-8540-bc96bbb76154.png)

**Comment by TapleFlib** [comment]
Just now it worked but only if I switch between /camera/color/image_raw and /darknet_ros/detection_image topic and it only run once with good fps, 0.1 fps for the rest 

![image](https://user-images.githubusercontent.com/130976648/234059513-fbb926ae-0094-479a-bfff-99f7a5aade11.png)

**Comment by MartyG-RealSense** [comment]
Hi @TapleFlib  I could only find a couple of issues where an FPS of 0.1 in darknet_ros is mentioned.  In the best of those references, it is suggested that CUDA graphics support might not be enabled in the makefile of darknet_ros.

CUDA requires an Nvidia GPU like the one on Nvidia Jetson computing boards.

![image](https://user-images.githubusercontent.com/41145062/234249514-3c0d0719-7715-40b1-a34c-7473456d94d1.png)

**Comment by MartyG-RealSense** [comment]
Hi @TapleFlib  Do you require further assistance with this case, please?  Thanks!

**Comment by TapleFlib** [comment]
I'm using amd so this might not help me, I used my friend's laptop with nvidia and it didn't lag, thankyou !

**Comment by MartyG-RealSense** [comment]
Thanks very much for the update.  RealSense 400 Series cameras should work with any Intel or Arm processor.  In the small number of cases where RealSense users reported using AMD processors, AMD Ryzen Threadripper processors were reported to be able to work with the cameras whilst non-Threadripper AMD ones did not.

**Comment by TapleFlib** [comment]
thanks for the info !
