### ISSUE TITLE
Qlp;['

### ISSUE THREAD

**Issue by jake5452** [realsenseai/realsense-ros#271]
### System Configuration
Please complete Your Configuration detail below. Refer to the BKC at [Configuration](../realsense_camera/README.md#configuration).

| Version               | Your Configuration   |
|:--------------------- |:---------------------|
| Operating System      | ? ? ?                |
| Kernel                | ?-?-?                |
| ROS                   | ?                    |
| ROS RealSense         | ?.?.?                |
| librealsense          | ?.?.?                |
| Camera Type-Firmware  | ?-?.?.?.?            |

---
#### How to collect Configuration Data
*This section can be deleted before submission.*

| Version               | Method |
|:--------------------- |:------------ |
| Operating System      | `grep DISTRIB_DESCRIPTION /etc/*elease*` or `lsb_release -d` |
| Kernel                | `uname -r` |
| ROS                   | `rosversion -d` |
| ROS RealSense         | `rosversion realsense_camera` |
| librealsense          | `rosversion librealsense` |
| Camera Type-Firmware  | View the ROS log from running nodelet |

---

**Comment by icarpis** [comment]
Hello @jake5452 , please provide some informative data.
