### ISSUE TITLE
Core Dump if serial_no not given

### ISSUE THREAD

**Issue by danielhonies** [realsenseai/realsense-ros#2711]
https://github.com/IntelRealSense/realsense-ros/blob/ros2-development/realsense2_camera/src/realsense_node_factory.cpp 

Line 277 throws error: 

std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::reference std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::front() [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>; reference = char&]: Assertion '!empty()' failed.

if no serial number is given.

**Comment by MartyG-RealSense** [comment]
Hi @danielhonies  What is the **ros2 launch** instruction that you are using, please?

Can you confirm if your launch instruction works if you add the serial number to the launch instruction, putting an underscore ( _ ) in front of the serial number.  For example:

`ros2 launch realsense2_camera rs_launch.py serial_no:=_123456789`

**Comment by danielhonies** [comment]
ros2 run realsense2_camera realsense2_camera_node throws the error

ros2 run realsense2_camera realsense2_camera_node  --ros-args -p serial_no:=_123456789 works

However I think this should be fixed in code by checking for _serial_no to not be empty. This could be due to us using a newer compiler (gcc12).

**Comment by danielhonies** [comment]
I can get a PR ready if you want.

**Comment by MartyG-RealSense** [comment]
You are very welcome to contribute a PR.  :)

The wrapper can be launched either with **ros2 run** or with **ros2 launch**.  Is your project able to use ros2 launch, and if so have you tried launching without a serial number using `ros2 launch realsense2_camera rs_launch.py` please?

**Comment by danielhonies** [comment]
ros2 launch realsense2_camera rs_launch.py throws the same error

**Comment by MartyG-RealSense** [comment]
I have not seen this problem reported before.

**Comment by danielhonies** [comment]
Yes the behaviour for calling string.front() for empty strings might have changed with compilers recently and the default ros2 setup still uses an older compiler.

**Comment by danielhonies** [comment]
as can be seen in the reference: https://en.cppreference.com/w/cpp/string/basic_string/front the behaviour is undefined for empty strings. Therefore we should check it.

**Comment by MartyG-RealSense** [comment]
Thanks so much for the PR at https://github.com/IntelRealSense/realsense-ros/pull/2713  :)

As this issue is associated with the PR, I have added an **Enhancement** label to it so that the issue is kept open.

**Comment by Nir-Az** [comment]
Hi all.
The fix PR have been merged.
Thanks for the fix.
