### ISSUE TITLE
Is it possible to visualize tf of the detected object relative to camera?

### ISSUE THREAD

**Issue by TapleFlib** [realsenseai/realsense-ros#2714]
Is it possible to visualize tf of the object relative to camera? I want it to be like this video : [https://www.youtube.com/watch?v=iJWHRW7sZW8](https://github.com/IntelligentRoboticsLabs/gb_visual_detection_3d/issues/url)

**Comment by MartyG-RealSense** [comment]
Hi @TapleFlib  Perhaps the ROS **Deep Object Pose (DOPE)** project at the link below could meet your requirements.

https://github.com/pauloabelha/Deep_Object_Pose

**Comment by TapleFlib** [comment]
I'll try it thankyou !
