### ISSUE TITLE
ROS 2 - Unorganised PointCloud Data

### ISSUE THREAD

**Issue by peterdavidfagan** [realsenseai/realsense-ros#2715]
Hi there, 

I am working off the `ros2-development` branch at the moment. Currently I am getting unorganised pointcloud data which has been an issue for using this data in OpenCV.

I saw the following issue exists https://github.com/IntelRealSense/realsense-ros/issues/851, this seems to have been addressed in ROS 1 with the `ordered_pc` parameter. Is there an equivalent in ROS 2? I didn't see it from initial inspections.

**Comment by MartyG-RealSense** [comment]
Hi @peterdavidfagan  The **ros2-development** wrapper has ordered_pc too.  It is enabled by setting **pointcloud.ordered_pc** to true.

**Comment by peterdavidfagan** [comment]
Thanks @MartyG-RealSense just spotted it and was going to close this issue. Thanks for the quick response.

**Comment by peterdavidfagan** [comment]
@MartyG-RealSense 

![Alt Text](https://media4.giphy.com/media/ZfK4cXKJTTay1Ava29/giphy.gif?cid=ecf05e470al8og8zz3nfj4wfn4nieakh25h1rflwnrxk8pf3&ep=v1_gifs_search&rid=giphy.gif&ct=g)

**Comment by MartyG-RealSense** [comment]
You are very welcome!  :)
