### ISSUE TITLE
SLAM with D435i

### ISSUE THREAD

**Issue by matuzawa1** [realsenseai/realsense-ros#2720]
How can I get the coordinates of the trajectory of the camera_link?

**Comment by MartyG-RealSense** [comment]
Hi @matuzawa1  The D435i does not have the in-built ability to track its own trajectory.  However,  at the link below a RealSense user created an adaptation of Intel's D435i SLAM guide that added localization with RTABMAP, obtaining the relative position from a recorded pointcloud map and plotting the camera's trajectory with matplotlib.  Does this guide meet your needs, please?

https://shinkansan.github.io/2019-UGRP-DPoom/SLAM

![image](https://user-images.githubusercontent.com/41145062/235340864-501123af-bc6c-4695-baca-313893c89719.png)

**Comment by MartyG-RealSense** [comment]
Hi @matuzawa1  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
