### ISSUE TITLE
Pointcloud2 doesn't appear in rviz 

### ISSUE THREAD

**Issue by TapleFlib** [realsenseai/realsense-ros#2723]
I installed realsense sdk and wrapper on another laptop with ubuntu 20.04, but when I open pointcloud2 topic on rviz, it says hardware error, depth stream ... I forgot the error cause it's on my friends' laptop, I follow the same step as what I did on my own laptop, but it didn't work on my friends' laptop. 
note : he installed the wrapper using sudo command before, will it be the problem?  if yes , how to uninstall the wrapper installed with sudo?

**Comment by MartyG-RealSense** [comment]
Hi @TapleFlib  If your friend had already installed the wrapper with the sudo command then that will have installed both the librealsense SDK and the ROS wrapper from packages at the same time.  If you then installed the SDK and wrapper youself later then it is possible that there are two SDK installations that are conflicting with each other.

If you also used the sudo command then you could try removing all RealSense related packages from the computer by inputting the command below into the Ubuntu terminal, and then repeating the SDK and wrapper installation with sudo.

`dpkg -l | grep "realsense" | cut -d " " -f 3 | xargs sudo dpkg --purge`

**Comment by TapleFlib** [comment]
I'll try it thanks !
