### ISSUE TITLE
Given aligned_depth_to_color topic is not available how to align depth to color?

### ISSUE THREAD

**Issue by alonsnir** [realsenseai/realsense-ros#2728]
Ubuntu 22.04 with 5.15.0-71-generic kernel
Ros Humble
librealsense2 debian package installed from Intel servers
ROS2 wrapper Option 1: Install debian package from ROS servers

Now when I run as following aligned_depth_to_color is not available
`ros2 run realsense2_camera realsense2_camera_node --ros-args --remap align_depth:=true`

```
ros2 topic list
/color/camera_info
/color/image_raw
/color/metadata
/depth/camera_info
/depth/image_rect_raw
/depth/metadata
/extrinsics/depth_to_color
/extrinsics/depth_to_infra1
/extrinsics/depth_to_infra2
/imu
/infra1/camera_info
/infra1/image_rect_raw
/infra1/metadata
/infra2/camera_info
/infra2/image_rect_raw
/infra2/metadata
/parameter_events
/rosout
/tf_static
```
As shown above aligned_depth_to_color is not listed, for that I have opened #2727

Any idea how to align? I would like to be able to align even if I manage to make realsense2_camera_node publish the missing topic.

Thanks

**Comment by MartyG-RealSense** [comment]
Issue closed due to question being handled at https://github.com/IntelRealSense/realsense-ros/issues/2727
