### ISSUE TITLE
how to reslove this problem

### ISSUE THREAD

**Issue by nxtx2** [realsenseai/realsense-ros#2732]
jeston nx  :With realsense ros driver installed, Ubuntu 1804 has no usb or NIC driver (no WIFI)

**Comment by MartyG-RealSense** [comment]
Hi @nxtx2  Which method did you use to install the librealsense SDK and the RealSense ROS wrapper, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Hi @nxtx2  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
