### ISSUE TITLE
realsense d435i unsupported device! 

### ISSUE THREAD

**Issue by fomboo** [realsenseai/realsense-ros#2738]
I want to subscribe to topics infra1 and infra2, but they are not in rostopic list when I run roslaunch, how to solve the problem?
//
rosdistro: noetic 
ubuntu20.04
RealSense ROS v2.3.2
LibRealSense v2.50.0
Running with LibRealSense v2.50.0
//
SUMMARY
========

PARAMETERS
 * /camera/realsense2_camera/accel_fps: -1
 * /camera/realsense2_camera/accel_frame_id: camera_accel_frame
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: False
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/allow_no_texture_points: False
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/calib_odom_file: 
 * /camera/realsense2_camera/clip_distance: -2.0
 * /camera/realsense2_camera/color_fps: -1
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: -1
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: -1
 * /camera/realsense2_camera/confidence_fps: -1
 * /camera/realsense2_camera/confidence_height: -1
 * /camera/realsense2_camera/confidence_width: -1
 * /camera/realsense2_camera/depth_fps: -1
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: -1
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: -1
 * /camera/realsense2_camera/device_type: 
 * /camera/realsense2_camera/enable_accel: True
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_confidence: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye1: False
 * /camera/realsense2_camera/enable_fisheye2: False
 * /camera/realsense2_camera/enable_fisheye: True
 * /camera/realsense2_camera/enable_gyro: True
 * /camera/realsense2_camera/enable_infra1: True
 * /camera/realsense2_camera/enable_infra2: True
 * /camera/realsense2_camera/enable_infra: True
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_pose: False
 * /camera/realsense2_camera/enable_sync: True
 * /camera/realsense2_camera/filters: 
 * /camera/realsense2_camera/fisheye1_frame_id: camera_fisheye1_f...
 * /camera/realsense2_camera/fisheye1_optical_frame_id: camera_fisheye1_o...
 * /camera/realsense2_camera/fisheye2_frame_id: camera_fisheye2_f...
 * /camera/realsense2_camera/fisheye2_optical_frame_id: camera_fisheye2_o...
 * /camera/realsense2_camera/fisheye_fps: -1
 * /camera/realsense2_camera/fisheye_frame_id: camera_fisheye_frame
 * /camera/realsense2_camera/fisheye_height: -1
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: -1
 * /camera/realsense2_camera/gyro_fps: -1
 * /camera/realsense2_camera/gyro_frame_id: camera_gyro_frame
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/imu_optical_frame_id: camera_imu_optica...
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra_fps: 30
 * /camera/realsense2_camera/infra_height: 480
 * /camera/realsense2_camera/infra_rgb: True
 * /camera/realsense2_camera/infra_width: 848
 * /camera/realsense2_camera/initial_reset: False
 * /camera/realsense2_camera/json_file_path: 
 * /camera/realsense2_camera/linear_accel_cov: 0.01
 * /camera/realsense2_camera/odom_frame_id: camera_odom_frame
 * /camera/realsense2_camera/ordered_pc: False
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/pose_frame_id: camera_pose_frame
 * /camera/realsense2_camera/pose_optical_frame_id: camera_pose_optic...
 * /camera/realsense2_camera/publish_odom_tf: True
 * /camera/realsense2_camera/publish_tf: True
 * /camera/realsense2_camera/reconnect_timeout: 6.0
 * /camera/realsense2_camera/rosbag_filename: 
 * /camera/realsense2_camera/serial_no: 
 * /camera/realsense2_camera/stereo_module/exposure/1: 7500
 * /camera/realsense2_camera/stereo_module/exposure/2: 1
 * /camera/realsense2_camera/stereo_module/gain/1: 16
 * /camera/realsense2_camera/stereo_module/gain/2: 16
 * /camera/realsense2_camera/tf_publish_rate: 0.0
 * /camera/realsense2_camera/topic_odom_in: odom_in
 * /camera/realsense2_camera/unite_imu_method: linear_interpolation
 * /camera/realsense2_camera/usb_port_id: 
 * /camera/realsense2_camera/wait_for_device_timeout: -1.0
 * /rosdistro: noetic
 * /rosversion: 1.16.0

NODES
  /camera/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)

auto-starting new master
process[master]: started with pid [34549]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 208280b0-f169-11ed-9ddc-95332878e074
process[rosout-1]: started with pid [34559]
started core service [/rosout]
process[camera/realsense2_camera_manager-2]: started with pid [34566]
process[camera/realsense2_camera-3]: started with pid [34567]
[ INFO] [1683966934.230118501]: Initializing nodelet with 8 worker threads.
[ INFO] [1683966934.310034351]: RealSense ROS v2.3.2
[ INFO] [1683966934.310063440]: Built with LibRealSense v2.50.0
[ INFO] [1683966934.310072785]: Running with LibRealSense v2.50.0
[ INFO] [1683966934.335656394]:  
[ INFO] [1683966934.611629394]: Device with serial number 040322070486 was found.

[ INFO] [1683966934.611691469]: Device with physical ID 4-3-2 was found.
[ INFO] [1683966934.611729658]: Device with name Intel RealSense D435I was found.
[ INFO] [1683966934.612789501]: Device with port number 4-3 was found.
[ INFO] [1683966934.612854815]: Device USB type: 3.2
[ INFO] [1683966934.616887040]: getParameters...
[ INFO] [1683966934.618206447]: Infrared RGB stream enabled
[ INFO] [1683966934.659194391]: setupDevice...
[ INFO] [1683966934.659231804]: JSON file is not provided
[ INFO] [1683966934.659243684]: ROS Node Namespace: camera
[ INFO] [1683966934.659257269]: Device Name: Intel RealSense D435I
[ INFO] [1683966934.659269533]: Device Serial No: 040322070486
[ INFO] [1683966934.659280253]: Device physical port: 4-3-2
[ INFO] [1683966934.659291347]: Device FW version: 05.14.00.00
[ INFO] [1683966934.659305849]: Device Product ID: 0x0B3A
[ INFO] [1683966934.659316900]: Enable PointCloud: Off
[ INFO] [1683966934.659326896]: Align Depth: Off
[ INFO] [1683966934.659335688]: Sync Mode: On
[ INFO] [1683966934.659390451]: Device Sensors: 
[ INFO] [1683966934.778545177]: Stereo Module was found.
[ INFO] [1683966934.795654731]: RGB Camera was found.
[ INFO] [1683966934.795890025]: Motion Module was found.
[ INFO] [1683966934.795946037]: (Infrared, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1683966934.795959015]: (Fisheye, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1683966934.795997226]: (Confidence, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1683966934.796058519]: num_filters: 0
[ INFO] [1683966934.796079046]: Setting Dynamic reconfig parameters.
hwmon command 0x80( 5 0 0 0 ) failed (response -7= HW not ready)
hwmon command 0x80( 5 0 0 0 ) failed (response -7= HW not ready)
hwmon command 0x80( 5 0 0 0 ) failed (response -7= HW not ready)
hwmon command 0x80( 5 0 0 0 ) failed (response -7= HW not ready)
[ INFO] [1683966937.954528150]: Done Setting Dynamic reconfig parameters.
[ INFO] [1683966937.955171671]: depth stream is enabled - width: 848, height: 480, fps: 30, Format: Z16
[ WARN] [1683966937.955234103]: Given stream configuration is not supported by the device!  Stream: Infrared, Stream Index: 1, Width: 848, Height: 480, FPS: 30, Format: RGB8
[ WARN] [1683966937.955284891]: Given stream configuration is not supported by the device!  Stream: Infrared, Stream Index: 2, Width: 848, Height: 480, FPS: 30, Format: RGB8
[ INFO] [1683966937.956404317]: color stream is enabled - width: 1280, height: 720, fps: 30, Format: RGB8
[ INFO] [1683966937.956440484]: gyro stream is enabled - fps: 200
[ INFO] [1683966937.956454655]: accel stream is enabled - fps: 63
[ INFO] [1683966937.956478829]: setupPublishers...
[ INFO] [1683966937.958563245]: Expected frequency for depth = 30.00000
[ INFO] [1683966937.984087729]: Expected frequency for color = 30.00000
[ INFO] [1683966938.002864624]: Start publisher IMU
[ INFO] [1683966938.003639699]: setupStreams...
 13/05 04:35:38,151 WARNING [140128695817984] (ds5-motion.cpp:473) IMU Calibration is not available, default intrinsic and extrinsic will be used.
[ WARN] [1683966938.427173558]: 
[ WARN] [1683966938.427265169]: frame's time domain is HARDWARE_CLOCK. Timestamps may reset periodically.
 13/05 04:35:38,536 WARNING [140128467019520] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
[ INFO] [1683966938.586494915]: SELECTED BASE:Depth, 0
[ INFO] [1683966938.593885904]: RealSense Node Is Up!

**Comment by MartyG-RealSense** [comment]
Hi @fomboo  I see that infra1 and infra2 are set to True in your launch but "Given stream configuration is not supported by the device".  As your D435i is detected as being on a USB 3 connection in the log, the configuration that you defined should be available.

Please try setting **enable_infra** to False but keeping enable_infra1 and enable_infra2 as True.  Does doing so make a difference?

The infrared is trying to publish in RGB8 format in your log when it should be Y8. The D435i model does not support RGB8 on infrared, which is 'RGB color from the left infrared sensor'.  This makes me think that enable_infra = true is involved in this.

```
[ WARN] [1683966937.955234103]: Given stream configuration is not supported by the device! Stream: Infrared, Stream Index: 1, Width: 848, Height: 480, FPS: 30, Format: RGB8
[ WARN] [1683966937.955284891]: Given stream configuration is not supported by the device! Stream: Infrared, Stream Index: 2, Width: 848, Height: 480, FPS: 30, Format: RGB8
```

**Comment by fomboo** [comment]
UMMARY
========

PARAMETERS
 * /camera/realsense2_camera/accel_fps: -1
 * /camera/realsense2_camera/accel_frame_id: camera_accel_frame
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: False
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/allow_no_texture_points: False
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/calib_odom_file: 
 * /camera/realsense2_camera/clip_distance: -2.0
 * /camera/realsense2_camera/color_fps: -1
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: -1
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: -1
 * /camera/realsense2_camera/confidence_fps: -1
 * /camera/realsense2_camera/confidence_height: -1
 * /camera/realsense2_camera/confidence_width: -1
 * /camera/realsense2_camera/depth_fps: -1
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: -1
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: -1
 * /camera/realsense2_camera/device_type: 
 * /camera/realsense2_camera/enable_accel: True
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_confidence: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye1: False
 * /camera/realsense2_camera/enable_fisheye2: False
 * /camera/realsense2_camera/enable_fisheye: True
 * /camera/realsense2_camera/enable_gyro: True
 * /camera/realsense2_camera/enable_infra1: True
 * /camera/realsense2_camera/enable_infra2: True
 * /camera/realsense2_camera/enable_infra: False
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_pose: False
 * /camera/realsense2_camera/enable_sync: True
 * /camera/realsense2_camera/filters: 
 * /camera/realsense2_camera/fisheye1_frame_id: camera_fisheye1_f...
 * /camera/realsense2_camera/fisheye1_optical_frame_id: camera_fisheye1_o...
 * /camera/realsense2_camera/fisheye2_frame_id: camera_fisheye2_f...
 * /camera/realsense2_camera/fisheye2_optical_frame_id: camera_fisheye2_o...
 * /camera/realsense2_camera/fisheye_fps: -1
 * /camera/realsense2_camera/fisheye_frame_id: camera_fisheye_frame
 * /camera/realsense2_camera/fisheye_height: -1
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: -1
 * /camera/realsense2_camera/gyro_fps: -1
 * /camera/realsense2_camera/gyro_frame_id: camera_gyro_frame
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/imu_optical_frame_id: camera_imu_optica...
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra_fps: 30
 * /camera/realsense2_camera/infra_height: 480
 * /camera/realsense2_camera/infra_rgb: True
 * /camera/realsense2_camera/infra_width: 848
 * /camera/realsense2_camera/initial_reset: False
 * /camera/realsense2_camera/json_file_path: 
 * /camera/realsense2_camera/linear_accel_cov: 0.01
 * /camera/realsense2_camera/odom_frame_id: camera_odom_frame
 * /camera/realsense2_camera/ordered_pc: False
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/pose_frame_id: camera_pose_frame
 * /camera/realsense2_camera/pose_optical_frame_id: camera_pose_optic...
 * /camera/realsense2_camera/publish_odom_tf: True
 * /camera/realsense2_camera/publish_tf: True
 * /camera/realsense2_camera/reconnect_timeout: 6.0
 * /camera/realsense2_camera/rosbag_filename: 
 * /camera/realsense2_camera/serial_no: 
 * /camera/realsense2_camera/stereo_module/exposure/1: 7500
 * /camera/realsense2_camera/stereo_module/exposure/2: 1
 * /camera/realsense2_camera/stereo_module/gain/1: 16
 * /camera/realsense2_camera/stereo_module/gain/2: 16
 * /camera/realsense2_camera/tf_publish_rate: 0.0
 * /camera/realsense2_camera/topic_odom_in: odom_in
 * /camera/realsense2_camera/unite_imu_method: linear_interpolation
 * /camera/realsense2_camera/usb_port_id: 
 * /camera/realsense2_camera/wait_for_device_timeout: -1.0
 * /rosdistro: noetic
 * /rosversion: 1.16.0

NODES
  /camera/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)

auto-starting new master
process[master]: started with pid [40430]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 22bbbf88-f18f-11ed-9ddc-95332878e074
process[rosout-1]: started with pid [40440]
started core service [/rosout]
process[camera/realsense2_camera_manager-2]: started with pid [40447]
process[camera/realsense2_camera-3]: started with pid [40448]
[ INFO] [1683983258.825143300]: Initializing nodelet with 8 worker threads.
[ INFO] [1683983258.909993052]: RealSense ROS v2.3.2
[ INFO] [1683983258.910015944]: Built with LibRealSense v2.50.0
[ INFO] [1683983258.910039471]: Running with LibRealSense v2.50.0
[ INFO] [1683983258.934140513]:  
[ INFO] [1683983259.197345434]: Device with serial number 040322070486 was found.

[ INFO] [1683983259.197441975]: Device with physical ID 4-3-2 was found.
[ INFO] [1683983259.197476148]: Device with name Intel RealSense D435I was found.
[ INFO] [1683983259.198501138]: Device with port number 4-3 was found.
[ INFO] [1683983259.198586020]: Device USB type: 3.2
[ INFO] [1683983259.203559661]: getParameters...
[ INFO] [1683983259.206046257]: Infrared RGB stream enabled
[ INFO] [1683983259.245275113]: setupDevice...
[ INFO] [1683983259.245326624]: JSON file is not provided
[ INFO] [1683983259.245348431]: ROS Node Namespace: camera
[ INFO] [1683983259.245374263]: Device Name: Intel RealSense D435I
[ INFO] [1683983259.245396511]: Device Serial No: 040322070486
[ INFO] [1683983259.245409306]: Device physical port: 4-3-2
[ INFO] [1683983259.245421861]: Device FW version: 05.14.00.00
[ INFO] [1683983259.245433808]: Device Product ID: 0x0B3A
[ INFO] [1683983259.245444116]: Enable PointCloud: Off
[ INFO] [1683983259.245454989]: Align Depth: Off
[ INFO] [1683983259.245465282]: Sync Mode: On
[ INFO] [1683983259.245548861]: Device Sensors: 
[ INFO] [1683983259.360458092]: Stereo Module was found.
[ INFO] [1683983259.384668455]: RGB Camera was found.
[ INFO] [1683983259.384977894]: Motion Module was found.
[ INFO] [1683983259.385036968]: (Fisheye, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1683983259.385061692]: (Confidence, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1683983259.385104147]: num_filters: 0
[ INFO] [1683983259.385137178]: Setting Dynamic reconfig parameters.
hwmon command 0x80( 5 0 0 0 ) failed (response -7= HW not ready)
hwmon command 0x80( 5 0 0 0 ) failed (response -7= HW not ready)
hwmon command 0x80( 5 0 0 0 ) failed (response -7= HW not ready)
hwmon command 0x80( 5 0 0 0 ) failed (response -7= HW not ready)
[ INFO] [1683983262.739109568]: Done Setting Dynamic reconfig parameters.
[ INFO] [1683983262.739682983]: depth stream is enabled - width: 848, height: 480, fps: 30, Format: Z16
[ WARN] [1683983262.739756416]: Given stream configuration is not supported by the device!  Stream: Infrared, Stream Index: 1, Width: 848, Height: 480, FPS: 30, Format: RGB8
[ WARN] [1683983262.739803315]: Given stream configuration is not supported by the device!  Stream: Infrared, Stream Index: 2, Width: 848, Height: 480, FPS: 30, Format: RGB8
[ INFO] [1683983262.740878431]: color stream is enabled - width: 1280, height: 720, fps: 30, Format: RGB8
[ INFO] [1683983262.740915212]: gyro stream is enabled - fps: 200
[ INFO] [1683983262.740931581]: accel stream is enabled - fps: 63
[ INFO] [1683983262.740956725]: setupPublishers...
[ INFO] [1683983262.743301431]: Expected frequency for depth = 30.00000
[ INFO] [1683983262.773589031]: Expected frequency for color = 30.00000
[ INFO] [1683983262.790984169]: Start publisher IMU
[ INFO] [1683983262.791642955]: setupStreams...
 13/05 09:07:42,931 WARNING [140459467532032] (ds5-motion.cpp:473) IMU Calibration is not available, default intrinsic and extrinsic will be used.
[ WARN] [1683983263.247671788]: 
 13/05 09:07:43,329 WARNING [140459238217472] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
[ INFO] [1683983263.379761508]: SELECTED BASE:Depth, 0
[ INFO] [1683983263.390360843]: RealSense Node Is Up!
 13/05 09:07:43,451 WARNING [140459238217472] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 13/05 09:07:43,502 WARNING [140459238217472] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11

**Comment by fomboo** [comment]
~$ rostopic list
/camera/accel/imu_info
/camera/color/camera_info
/camera/color/image_raw
/camera/color/image_raw/compressed
/camera/color/image_raw/compressed/parameter_descriptions
/camera/color/image_raw/compressed/parameter_updates
/camera/color/image_raw/compressedDepth
/camera/color/image_raw/compressedDepth/parameter_descriptions
/camera/color/image_raw/compressedDepth/parameter_updates
/camera/color/image_raw/theora
/camera/color/image_raw/theora/parameter_descriptions
/camera/color/image_raw/theora/parameter_updates
/camera/color/metadata
/camera/depth/camera_info
/camera/depth/image_rect_raw
/camera/depth/image_rect_raw/compressed
/camera/depth/image_rect_raw/compressed/parameter_descriptions
/camera/depth/image_rect_raw/compressed/parameter_updates
/camera/depth/image_rect_raw/compressedDepth
/camera/depth/image_rect_raw/compressedDepth/parameter_descriptions
/camera/depth/image_rect_raw/compressedDepth/parameter_updates
/camera/depth/image_rect_raw/theora
/camera/depth/image_rect_raw/theora/parameter_descriptions
/camera/depth/image_rect_raw/theora/parameter_updates
/camera/depth/metadata
/camera/extrinsics/depth_to_color
/camera/gyro/imu_info
/camera/imu
/camera/motion_module/parameter_descriptions
/camera/motion_module/parameter_updates
/camera/realsense2_camera_manager/bond
/camera/rgb_camera/auto_exposure_roi/parameter_descriptions
/camera/rgb_camera/auto_exposure_roi/parameter_updates
/camera/rgb_camera/parameter_descriptions
/camera/rgb_camera/parameter_updates
/camera/stereo_module/auto_exposure_roi/parameter_descriptions
/camera/stereo_module/auto_exposure_roi/parameter_updates
/camera/stereo_module/parameter_descriptions
/camera/stereo_module/parameter_updates
/diagnostics
/rosout
/rosout_agg
/tf
/tf_static

**Comment by fomboo** [comment]
: (

**Comment by fomboo** [comment]
dont know why stream configuration is not supported LOL 
[ WARN] [1683983262.739756416]: Given stream configuration is not supported by the device!  Stream: Infrared, Stream Index: 1, Width: 848, Height: 480, FPS: 30, Format: RGB8
[ WARN] [1683983262.739803315]: Given stream configuration is not supported by the device!  Stream: Infrared, Stream Index: 2, Width: 848, Height: 480, FPS: 30, Format: RGB8
[ INFO] [1683983262.740878431]: color stream is enabled - width: 1280, height: 720, fps: 30, Format: RGB8

**Comment by fomboo** [comment]
Dont know why stream configuration is not supported
[ WARN] [1683983262.739756416]: Given stream configuration is not supported by the device! Stream: Infrared, Stream Index: 1, Width: 848, Height: 480, FPS: 30, Format: RGB8
[ WARN] [1683983262.739803315]: Given stream configuration is not supported by the device! Stream: Infrared, Stream Index: 2, Width: 848, Height: 480, FPS: 30, Format: RGB8
[ INFO] [1683983262.740878431]: color stream is enabled - width: 1280, height: 720, fps: 30, Format: RGB8

**Comment by fomboo** [comment]
<img width="1046" alt="image" src="https://github.com/IntelRealSense/realsense-ros/assets/132741755/ea7ed86d-473c-4bb1-be53-7cb29b4c35b4">

**Comment by MartyG-RealSense** [comment]
Next, please add to your roslaunch instruction **infra_rgb:=false** to make sure that the launch is not trying to use the infrared sensors for RGB instead of infrared.

**Comment by fomboo** [comment]
thank uuuuuuuuuuuuuuu   QAQ
<img width="421" alt="image" src="https://github.com/IntelRealSense/realsense-ros/assets/132741755/6230506d-3ba0-45b8-890d-b1b01d37d23f">

**Comment by MartyG-RealSense** [comment]
You are very welcome.  :)

**Comment by fomboo** [comment]
Emm one more question，my vins_fusion node is closed ，how to activate it？

<img width="739" alt="image" src="https://github.com/IntelRealSense/realsense-ros/assets/132741755/a281e1cd-0a06-4d9e-8d81-a5d6e5465884">
<img width="708" alt="image" src="https://github.com/IntelRealSense/realsense-ros/assets/132741755/0722f118-7bcb-4d98-9e15-fdc1e7f8d69b">

**Comment by MartyG-RealSense** [comment]
I am not familiar with fast_drone_250, unfortunately.  

https://github.com/ZJU-FAST-Lab/Fast-Drone-250

It does have an English language instruction guide though that covers the same steps as the instructions on the front page of the fast_drone_250 repository.

https://github.com/ZJU-FAST-Lab/Fast-Drone-250/blob/master/readme_en.md

It does not explain though how to use fast_drone_250.launch.

There is a guide to using a RealSense camera with VINS and fast_drone_250 here:

https://blog.csdn.net/weixin_41967369/article/details/125183678

I have posted below images of an English translated version captured from my browser.

![image](https://github.com/IntelRealSense/realsense-ros/assets/41145062/4d447e91-78fc-4fe9-a1c1-c027704d048d)

![image](https://github.com/IntelRealSense/realsense-ros/assets/41145062/c4c3819d-f7b8-4cc4-a7cb-74e0b64de611)

![image](https://github.com/IntelRealSense/realsense-ros/assets/41145062/304a2f6f-d7a2-4202-8dbd-ba7f93092476)

**Comment by fomboo** [comment]
okkk, thank u anyway : )
