### ISSUE TITLE
noise speckles on sr300

### ISSUE THREAD

**Issue by smaassen** [realsenseai/realsense-ros#274]
This is following up issue #50 where noise speckles in the depth image was discussed for the r200. That issue was closed with the solution being presented in #106.

However this only applies for the r200. Now, with the sr300  i get also noise speckles ,see picture below

https://polybox.ethz.ch/index.php/s/49Yi87CXNtf7P35

 (even if they are quite less severe than those presented in #50). I mainly wanted to check if other people are experiencing the same problem and if someone came up with a solution.

I tried to reduce the speckles via the pcl median filter, however the loss of detail is far too severe for the application (object recognition). I was wondering if someone got good results with a nearest neighbor approach or something else, without loosing to much detail on the rest of the point cloud

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Close this issue for lack of activity. Please feel free to reopen if the issue is still relevant.
