### ISSUE TITLE
Need to restart pc to display pointcloud2 sometimes

### ISSUE THREAD

**Issue by TapleFlib** [realsenseai/realsense-ros#2744]
My RViz sometimes doesn't display pointcloud2. It has been around a month, but today it doesn't display pointcloud2 in RViz even after I restart my laptop which works for a month before.

**Comment by TapleFlib** [comment]
I test it on another laptop and it works normally.

**Comment by MartyG-RealSense** [comment]
Hi @TapleFlib  If you are using the ROS1 wrapper, are you able to display a pointcloud on the affected laptop if you use the instructions at the link below?

https://github.com/IntelRealSense/realsense-ros/tree/ros1-legacy#point-cloud

**Comment by MartyG-RealSense** [comment]
Hi @TapleFlib  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
