### ISSUE TITLE
How to align depth-color images that were not aligned at ros2 bag acquisition

### ISSUE THREAD

**Issue by lifeisgood-ai** [realsenseai/realsense-ros#2746]
Hello

I am wondering how to align depth images to color images from a ros2 bag in which images were not aligned at acquisition.

The acquisition process was : 
* launch with  `ros2 launch realsense2_camera rs_launch.py depth_module.profile:=848x480x30 rgb_camera.profile:=848x480x30`
* record with `ros2 bag record /camera/color/camera_info /camera/color/image_raw /camera/color/metadata /camera/depth/camera_info /camera/depth/image_rect_raw /camera/depth/metadata  mybag`
* topics acquired are `/camera/color/image_raw` and `/camera/depth/image_rect_raw` which are not aligned...
* camera is RS D435

Is there a way to get them aligned ? 

Thank you

**Comment by MartyG-RealSense** [comment]
Hi @lifeisgood-ai  Do you have the option of re-recording the bag with depth-color alignment enabled this time by adding **align_depth.enable:=true** to your launch instruction?

`ros2 launch realsense2_camera rs_launch.py depth_module.profile:=848x480x30 rgb_camera.profile:=848x480x30 align_depth.enable:=true`

**Comment by lifeisgood-ai** [comment]
Hi @MartyG-RealSense, thanks for your quick answer

I cannot re-record from the source. You suggest to "replay" the bag file with the option align_depth set, is that right ? 

In the command `ros2 launch realsense2_camera rs_launch.py depth_module.profile:=848x480x30 rgb_camera.profile:=848x480x30 align_depth.enable:=true` I don't see how I would replay the same bag file.

I could play the bag again `ros2 play`and run `ros2 record` but I do no see how I could pass the align_depth option ?

**Comment by MartyG-RealSense** [comment]
I asked if you could re-record the bag with align_depth.enable in case you still had the D435 camera available.

The RealSense ROS2 wrapped has a command called **rosbag_filename** that should enable you to use the topics in the bag file in the launch instead of a live camera.  There are two ways for loading rosbag file:

Command line - `ros2 run realsense2_camera realsense2_camera_node -p rosbag_filename:="/full/path/to/rosbag.bag"`

Launch file - set the **rosbag_filename** parameter with the bag's full path - see the `realsense2_camera/launch/rs_launch.py` launch file as a reference.

I would speculate (not certain) that if the parameter **align_depth.enable** is set to true in one of these launch methods then it would align individual depth and color topics stored in the bag.

**Comment by lifeisgood-ai** [comment]
Great I will try it and let you know! 

I guess I can extrapolate to multi_cameras the same way.

**Comment by lifeisgood-ai** [comment]
I tried but I get a warning, no topic is published. It looks like it is waiting  to get a real camera connected 

[WARN] [1684746044.491967233] [camera]: No RealSense devices were found! 

I set the full path to the command with the syntax provided.
Should I add some extra configurable_parameters (as described in rs_launch.py) to the command line ?

FYI my bag file was created using rs_multi_camera_launch.py and 3 cameras.

**Comment by MartyG-RealSense** [comment]
There are not any past examples to refer to regarding rosbag_filename being used with the multiple camera launch file, unfortunately.  

What happens if you use rs_multi_camera_launch.py as your launch instruction and add the rosbag_filename parameter and its bagfile path to the instruction?

**Comment by lifeisgood-ai** [comment]
Launching with a ros bag created from 3 cameras :

`ros2 launch realsense2_camera rs_multi_camera_launch.py align_depth:=true  rosbag_filename:=/home/lg/ros2_ws/3cams_bag/`

I get the following warnings:

> [realsense2_camera_node-1]  22/05 16:54:11,948 WARNING [140264803108416] (backend-hid.cpp:1203) Failed to read busnum/devnum. Custom HID Device Path: /sys/bus/platform/drivers/hid_sensor_custom/HID-SENSOR-2000e1.11.auto (reepated multiple times)
> [realsense2_camera_node-3] [WARN] [1684767251.959739127] [camera3.camera3]: No RealSense devices were found!
> [realsense2_camera_node-2] [WARN] [1684767251.965779918] [camera2.camera2]: No RealSense devices were found!
> [realsense2_camera_node-1] [WARN] [1684767251.966782926] [camera1.camera1]: No RealSense devices were found!
> 

whereas with a 1 camera bag with rs_launch.py with 

`ros2 launch realsense2_camera rs_launch.py align_depth:=true  rosbag_filename:=/home/lg/ros2_ws/1cam_bag/`

i get the following error 

> [realsense2_camera_node-1] [ERROR] [1684765892.538787404] [camera.camera]: An exception has been thrown: /home/lg/ros2_ws/src/realsense-ros/realsense2_camera/src/realsense_node_factory.cpp:342:Failed to resolve request. Request to enable_device_from_file("/home/lg/ros2_ws/1cam_bag/") was invalid, Reason: Failed to create ros reader: Error reading version line

**Comment by MartyG-RealSense** [comment]
I have highlighted your issue to the RealSense ROS developer team to seek their advice.  Thanks very much for your patience!

**Comment by MartyG-RealSense** [comment]
My colleagues have provided the following information.

***********

The RealSense ROS wrapper supports playback from rosbag, but it is the rosbag recorded with the SDK's API or tools, like the RealSense Viewer.  My understanding is that it’s not fully compatible with the bag files recorded with the ROS recorder (rosbag record).

With rosbag playback, the actual camera hardware device is not needed.  You just purely playback the recorded frames from the rosbag file.

So the general process is:

1)	With the RealSense Viewer or apps programmed with the SDK API, record the ros bag file.

2)	Then use the ROS wrapper to playback the recorded bag file.  Specify the full path in command line or in the launch file.
               
`ros2 launch realsense2_camera rs_launch.py rosbag_filename:="/home/gwen/Documents/20230522_135057.bag"`

3)	It can then perform alignment if needed.
              
`ros2 launch realsense2_camera rs_launch.py rosbag_filename:="/home/gwen/Documents/20230522_135057.bag" align_depth.enable:=true`

The rosbag recording in the SDK is separated for each camera, so for multiple cameras, each camera playback will need to specify its own bag file.

**Comment by lifeisgood-ai** [comment]
I get it but this cannot be applied to this case as the bag file was not created with _RealSense Viewer or apps programmed with the SDK API_.

If there is a trick to read a non SDK created bag file I would be very pleased to know. Otherwise the issue can be closed.

Thank you for your feedback and detailed answer.

**Comment by MartyG-RealSense** [comment]
The rosbag format of bag files recorded in the RealSense SDK has some differences to bag files recorded in ROS with rosbag record, as described at https://github.com/IntelRealSense/librealsense/issues/3020

The only possible workaround that I know of is a C++ program called **rosbag reader** at https://github.com/IntelRealSense/librealsense/issues/2215 that parses rosbag messages directly instead of using the RealSense pipeline.

**Comment by MartyG-RealSense** [comment]
Hi @lifeisgood-ai  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
