### ISSUE TITLE
IMU Calibration is not available, default intrinsic and extrinsic will be used [D435i]

### ISSUE THREAD

**Issue by 10179013** [realsenseai/realsense-ros#2749]
When I run：
`roslaunch realsense2_camera rs_camera.launch \
    unite_imu_method:="linear_interpolation" \
    enable_gyro:=true \
     enable_accel:=true`
There is a warning: 
IMU Calibration is not available, default intrinsic and extrinsic will be used [D435i]
How can I solve it?

**Comment by MartyG-RealSense** [comment]
Calibrating the IMU is optional and will not prevent accel and gyro data from being published if you do not perform calibration.  If you wish to perform an IMU calibration and save it to the camera hardware then you can do so with the Python tool at the link below.

**Calibration tool**
https://github.com/IntelRealSense/librealsense/tree/master/tools/rs-imu-calibration

**User guide (PDF document)**
https://dev.intelrealsense.com/docs/imu-calibration-tool-for-intel-realsense-depth-camera

When an IMU is calibrated, the Y Accel value will be closer to its ideal value of 9.80.  An uncalibrated IMU may have a less accurate Y-accel value between 9.4 and 9.6.  Calibration also makes the Y-accel value more stable when the camera is stationary on a flat surface.

**Comment by MartyG-RealSense** [comment]
Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
