### ISSUE TITLE
Make FOV and resolution independant

### ISSUE THREAD

**Issue by doisyg** [realsenseai/realsense-ros#275]
| Version               | Your Configuration   |
|:--------------------- |:---------------------|
| Operating System      | Ubuntun 16.04.3                |
| Kernel                | 4.10           |
| ROS                   |kinetic                    |
| ROS RealSense         |  1.8.0            |
| librealsense          | 1.12.1            |
| Camera Type-Firmware  | 1.0.72.06        |

---

I would like to use the maximum FOV of the color stream of my R200, but I can only access it all by opening it with the max resolution (1920x1080). I cannot find a way to get the full FOV at lower resolution, which is important for us as with 2  R200 connected to a Skylake NUC, CPU resources are sparse. Is that possible or are we limited by the firmware of the r200?

**Comment by jlgarcia75** [comment]
Hello @doisyg,

I don't know if it's possible to make the resolution and FOV independent in any depth camera. This article has a good explanation for it: http://www.imaginativeuniversal.com/blog/2015/09/15/the-problem-with-comparing-depth-camera-resolutions/.

Regards,
Jesus
Intel Customer Support

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Close this issue for lack of activity. Please feel free to reopen if the issue is still relevant.
