### ISSUE TITLE
Hardware Notification:Depth stream start failure,,Error,Hardware Error【D435i】

### ISSUE THREAD

**Issue by 10179013** [realsenseai/realsense-ros#2752]
D435i、ubutnu18.04
When I run：
`roslaunch realsense2_camera rs_camera.launch \ unite_imu_method:="linear_interpolation" \ enable_gyro:=true \ enable_accel:=true`
There is a warning:
` 25/05 09:30:02,892 ERROR [139958664611584] (uvc-streamer.cpp:106) uvc streamer watchdog triggered on endpoint: 132
[ WARN] [1684978295.716470682]: Hardware Notification:Depth stream start failure,1.68498e+12,Error,Hardware Error`
How can I solve it?

**Comment by MartyG-RealSense** [comment]
Case closed due to issue being handled at https://github.com/IntelRealSense/realsense-ros/issues/2751
