### ISSUE TITLE
How should I trigger the D405 and the D435i synchronously in ros1？

### ISSUE THREAD

**Issue by kao-yang** [realsenseai/realsense-ros#2763]
I have read white paper of [Multi-Camera configurations](https://dev.intelrealsense.com/docs/multiple-depth-cameras-configuration),but the D405 cam seems no synchronous interface.

**Comment by MartyG-RealSense** [comment]
Hi @kao-yang  You are correct, the D405 camera model does not have a set of hardware sync pins, unfortunately.  

On RealSense 400 Series cameras such as D405 and D435i, **Global Time** is enabled by default though and it will calculate a common timestamp between multiple cameras.  Please see https://github.com/IntelRealSense/librealsense/pull/3909 for further details.  

Global Time requires hardware metadata support to be enabled.  It is enabled if building the librealsense SDK from packages or from source code with CMake with the **RSUSB backend** installation method.  If building from source code and not using the RSUSB installation method, a kernel patch script should be applied to add hardware metadata support.

**Comment by MartyG-RealSense** [comment]
Hi @kao-yang  Do you require further assistance with this case, please?  Thanks!

**Comment by kao-yang** [comment]
Thanks.As d405 can not triggered with d435i synchronously,I may do this in program.

**Comment by MartyG-RealSense** [comment]
Thank you.  Do you need help with developing such a program, please?

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
