### ISSUE TITLE
Windows10 Build Fails: colcon build TypeError 

### ISSUE THREAD

**Issue by hpeng-kcl** [realsenseai/realsense-ros#2768]
Hi, I am here to seek some help for ROS2 colcon error in Windows 10. I was trying to run the tutorial in ROS2 "Using colcon to build packages" , while I input the command "colcon build --symlink-install --merge-install", the command window shows the error:

"Summary: 16 packages finished [5min 45s] 7 packages had stderr output: examples_rclpy_executors examples_rclpy_minimal_action_client examples_rclpy_minimal_action_server examples_rclpy_minimal_client examples_rclpy_minimal_publisher examples_rclpy_minimal_service examples_rclpy_minimal_subscriber WNDPROC return value cannot be converted to LRESULT TypeError: WPARAM is simple, so must be an int object (got NoneType)"

I was trying to solve this "WNDPROC return value cannot be converted to LRESULT TypeError: WPARAM is simple, so must be an int object (got NoneType)", but didn't find a way out, can you please give me some resolution or hints to fix this?

**Comment by MartyG-RealSense** [comment]
Hi @hpeng-kcl  The RealSense ROS2 wrapper is difficult to get working successfully on Windows 10 and can involve multiple steps and file installations.  The best reference for doing so is at https://github.com/IntelRealSense/realsense-ros/issues/2660

**Comment by hpeng-kcl** [comment]
> 

Hi Marty! Thank you so much for reply the issue! I have resolved the issue by using another installer to reinstall the ROS2 in win10 and win11, now both win10 and win11 are working well.

**Comment by MartyG-RealSense** [comment]
That's excellent news that you achieved a solution, @hpeng-kcl - thanks very much for the update!

**Comment by MartyG-RealSense** [comment]
Case closed due to solution achieved and no further comments received.
