### ISSUE TITLE
About the structured light problem of D435i model camera

### ISSUE THREAD

**Issue by kao-yang** [realsenseai/realsense-ros#2781]
I use this code in launch to alternate turn on light emitter.
```
<node pkg="dynamic_reconfigure" type="dynparam" name="dynparam" output="screen" args="set /camera/stereo_module emitter_on_off 1" />
```
 Then use `frame_emitter_mode` in the corresponding `Metadata` topic to determine whether emitter is on. However, on my two D435i cameras, `frame_emitter_mode` is different. One camera 0 means emitter is on, while the other camera 1 means emitter is on. I used the ros1 system and used apt-get to install the ros package for realsens.

**Comment by MartyG-RealSense** [comment]
Hi @kao-yang  The D435 is not a structured light camera, where a pattern of bars is projected onto the scene.  It is instead a **stereo depth** camera, which constructs the depth image from left and right infrared images.

Are you using both D435i cameras at the same time?  If you are, are you launching them in separate ROS terminal windows with individual camera names, as advised in the ROS1 wrapper's multi camera launch documentation at the link below, please?

https://github.com/IntelRealSense/realsense-ros/tree/ros1-legacy#work-with-multiple-cameras

**Comment by MartyG-RealSense** [comment]
Hi @kao-yang  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
