### ISSUE TITLE
Realsense R200 on raspberry pi2

### ISSUE THREAD

**Issue by Dhivin** [realsenseai/realsense-ros#279]
SUMMARY
========

PARAMETERS
 * /camera/camera_nodelet_manager/num_worker_threads: 4
 * /camera/depth_rectify_depth/interpolation: 0
 * /camera/disparity_depth/max_range: 4.0
 * /camera/disparity_depth/min_range: 0.5
 * /camera/disparity_registered_sw/max_range: 4.0
 * /camera/disparity_registered_sw/min_range: 0.5
 * /camera/driver/base_frame_id: camera_link
 * /camera/driver/camera_type: R200
 * /camera/driver/color_fps: 30
 * /camera/driver/color_frame_id: camera_rgb_frame
 * /camera/driver/color_height: 480
 * /camera/driver/color_optical_frame_id: camera_rgb_optica...
 * /camera/driver/color_width: 640
 * /camera/driver/depth_fps: 30
 * /camera/driver/depth_frame_id: camera_depth_frame
 * /camera/driver/depth_height: 360
 * /camera/driver/depth_optical_frame_id: camera_depth_opti...
 * /camera/driver/depth_width: 480
 * /camera/driver/enable_color: True
 * /camera/driver/enable_depth: True
 * /camera/driver/enable_fisheye: False
 * /camera/driver/enable_imu: False
 * /camera/driver/enable_ir2: True
 * /camera/driver/enable_ir: True
 * /camera/driver/enable_pointcloud: False
 * /camera/driver/enable_tf: True
 * /camera/driver/ir2_frame_id: camera_ir2_frame
 * /camera/driver/ir_frame_id: camera_ir_frame
 * /camera/driver/mode: manual
 * /camera/driver/serial_no: 
 * /camera/driver/usb_port_id: 
 * /camera/points_xyzrgb_sw_registered/queue_size: 100
 * /rosdistro: kinetic
 * /rosversion: 1.12.7

NODES
  /camera/
    camera_nodelet_manager (nodelet/nodelet)
    depth_metric (nodelet/nodelet)
    depth_metric_rect (nodelet/nodelet)
    depth_points (nodelet/nodelet)
    depth_rectify_depth (nodelet/nodelet)
    depth_registered_sw_metric_rect (nodelet/nodelet)
    disparity_depth (nodelet/nodelet)
    disparity_registered_sw (nodelet/nodelet)
    driver (nodelet/nodelet)
    ir_rectify_ir (nodelet/nodelet)
    points_xyzrgb_sw_registered (nodelet/nodelet)
    register_depth_rgb (nodelet/nodelet)
    rgb_debayer (nodelet/nodelet)
    rgb_rectify_color (nodelet/nodelet)
    rgb_rectify_mono (nodelet/nodelet)

ROS_MASTER_URI=http://localhost:11311

core service [/rosout] found
process[camera/camera_nodelet_manager-1]: started with pid [1965]
process[camera/driver-2]: started with pid [1966]
process[camera/rgb_debayer-3]: started with pid [1967]
process[camera/rgb_rectify_mono-4]: started with pid [1969]
process[camera/rgb_rectify_color-5]: started with pid [1980]
process[camera/ir_rectify_ir-6]: started with pid [1989]
process[camera/depth_rectify_depth-7]: started with pid [2003]
process[camera/depth_metric_rect-8]: started with pid [2011]
process[camera/depth_metric-9]: started with pid [2019]
process[camera/depth_points-10]: started with pid [2029]
process[camera/register_depth_rgb-11]: started with pid [2037]
process[camera/points_xyzrgb_sw_registered-12]: started with pid [2053]
process[camera/depth_registered_sw_metric_rect-13]: started with pid [2066]
process[camera/disparity_depth-14]: started with pid [2082]
process[camera/disparity_registered_sw-15]: started with pid [2096]
[ INFO] [1511980703.632140936]: Initializing nodelet with 4 worker threads.
[ERROR] [1511980708.623243341]: /camera/driver - No cameras detected!
[ERROR] [1511980708.624803183]: /camera/driver - Error calling rs_create_context ( api_version:11201 ): 
uvcvideo kernel module is not loaded 

[FATAL] [1511980709.033301286]: Failed to load nodelet '/camera/ir_rectify_ir` o

This is the error that i get. Is there anyway around it? Raspberrypi2 has only USB 2.0 . Does the Realsense R200 require USB 3.0 to work?

**Comment by icarpis** [comment]
Hello @Dhivin, [RealSense R200](https://ark.intel.com/products/92256/Intel-RealSense-Camera-R200) camera supports only USB3 interface.
