### ISSUE TITLE
How to visualize fov

### ISSUE THREAD

**Issue by TapleFlib** [realsenseai/realsense-ros#2790]
H:87±3 / V:58±1 /D:95±3 this is the FOV of Realsense D455 , but I'm not sure how to visualize it , I draw an abstract of how I think it is visualized : 
![image](https://github.com/IntelRealSense/realsense-ros/assets/130976648/d2424f91-a81c-43b1-8e40-af5ec26a7c04)
is this correct?

**Comment by MartyG-RealSense** [comment]
Hi @TapleFlib  The shape of your D455 drawing is consistent with one provided by another RealSense user for the D435i model.

![image](https://github.com/IntelRealSense/realsense-ros/assets/41145062/defae53b-2cf4-41e9-b329-5d8a4434302e)

An FOV drawing from page 83 of the current edition of the official data sheet document for the 400 Series cameras is presented like this:

![image](https://github.com/IntelRealSense/realsense-ros/assets/41145062/5a4b0c12-3a3f-4a76-86a7-18717b35b7d8)

![image](https://github.com/IntelRealSense/realsense-ros/assets/41145062/ee683e7e-f43b-4096-a326-e53c5c82b670)

**Comment by TapleFlib** [comment]
I see thankyou so much !

**Comment by tonynajjar** [comment]
Hey @MartyG-RealSense, this is probably not the right place to ask for this but I don't know where else. Could you put in a feature request to include the accurate FOV visualization in the CAD files? It would help people position their cameras on their robots  for maximum "coverage"

**Comment by MartyG-RealSense** [comment]
Hi @tonynajjar  A request for a change has a greater chance of being considered if a popular demand from users for that change is demonstrated.  I would therefore recommend posting your request as a new issue by clicking the green 'New Issue' button on the front page of the main librealsense support forum, and then we keep it open for a while to see if other RealSense users comment to add their voice of support for the feature.

https://github.com/IntelRealSense/librealsense/issues
