### ISSUE TITLE
realsense-ros 4.53?

### ISSUE THREAD

**Issue by ggsd-ddup** [realsenseai/realsense-ros#2801]
Hi ! Is there a package for realsense-ros with version number 4.53? Applicable to realsense SDK with version 2.53.1
https://github.com/IntelRealSense/librealsense/releases/tag/v2.53.1

**Comment by MartyG-RealSense** [comment]
Hi @hfdlwt  There was not a ROS wrapper version published for 2.53.1.  There are versions for SDK 2.51.1 (wrapper 4.51.1) and 2.54.1 (wrapper 4.54.1).

**Comment by MartyG-RealSense** [comment]
Hi @hfdlwt  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
