### ISSUE TITLE
compatible librealsense with the latest realsense-ros wrapper?

### ISSUE THREAD

**Issue by kenloumixx** [realsenseai/realsense-ros#2804]
Hello,
May I ask if the latest [librealsense](https://github.com/IntelRealSense/librealsense) is compatible with the [latest realsense-ros wrapper](https://github.com/IntelRealSense/realsense-ros/releases/tag/4.54.1)?

**Comment by MartyG-RealSense** [comment]
Hi @kenloumixx  You can match the current latest librealsense **2.54.1** with the current latest ROS2 wrapper **4.54.1**.

If you are using ROS1 then you should use librealsense 2.51.1 with wrapper 2.3.2.

**Comment by kenloumixx** [comment]
@MartyG-RealSense Thank you for the response :)
