### ISSUE TITLE
visual parameter preset defined in realsense-viewer but not in realsense-2.0.1 package

### ISSUE THREAD

**Issue by poripsa** [realsenseai/realsense-ros#281]
### System Configuration
Please complete Your Configuration detail below. Refer to the BKC at [Configuration](../realsense_camera/README.md#configuration).

| Version               | Your Configuration   |
|:--------------------- |:---------------------|
| Operating System      |Ubuntu 16.04.3 LTS |
| Kernel                | 4.4.0-101-generic |
| ROS                   |kinetic |
| ROS realsense_ros_camera         | 2.0.1|
| ROS RealSense         | 1.8.0|
| LibRealSense         | 2.8.1| >>used by realsense_ros_camera
| librealsense          | 1.12.1|
| Camera Type-Firmware  | 05.08.14.00 |

**Comment by poripsa** [comment]
![screenshot from 2017-12-11 19-40-37](https://user-images.githubusercontent.com/19162244/33862997-3897c7b8-deab-11e7-80af-1da3691c3f92.png)

**Comment by poripsa** [comment]
How can the visual preset parameter be modified in the ros launch file (or anywhere else) so that it loads when camera is launched

**Comment by icarpis** [comment]
Hello @poripsa, currently visual presets cannot be modified by RealSense ROS wrapper or Launch file. we will implement it in the next release.
For a workaround you can change the visual preset using 'realsense-viewer' tool and then use the ROS wrapper/Launch file. Please note that in order to set a new preset you should streaming with Depth.
Modify a new preset will remains as long as the camera stay connected to the computer.

**Comment by poripsa** [comment]
Will the same preset be applied when the camera is reconnected or after start up of computer? How can i save the settings and pull them up as required?

**Comment by icarpis** [comment]
No, when the camera is reconnected the default preset is loaded. You can use the 'realsense-viewer' tool to save and load camera settings using JSON file.
![image](https://user-images.githubusercontent.com/17433152/34072799-9ddb2630-e296-11e7-904b-a536288fb17c.png)

The JSON file contains the applied preset and camera controls.

**Comment by poripsa** [comment]
Hey I am looking to set this up for my project. Any pointers you could give me? So far I see the rosnode just publishes the set (by preset) frames.

**Comment by shaun-edwards** [comment]
Addressed in #289.  This issue can be closed now.

**Comment by stevensu1838** [comment]
Hi all,

Can the visual preset parameter be modified in the ros launch file (or anywhere else) so that it loads when camera is launched yet or not? 
I am having the linked [issue](https://github.com/IntelRealSense/realsense-ros/issues/892)
