### ISSUE TITLE
!Using the rqt_image_view command does not display the image

### ISSUE THREAD

**Issue by EGOIST5** [realsenseai/realsense-ros#2819]
I use one terminal to enter "roslaunch realsense2_camera rs_camera.launch" command, and then another terminal to enter "rqt_image_view" command, but the expected results are not displayed.
![1](https://github.com/IntelRealSense/realsense-ros/assets/81228631/d7fd98b0-0228-41a4-a264-f315e243c9e4)
![2](https://github.com/IntelRealSense/realsense-ros/assets/81228631/f8bbbc07-2466-43b4-9d65-db39200569a4)

Before I enter the rqt_image_view command, the first terminal only shows the information up to malloc(): invalid size(unsorted).

**Comment by EGOIST5** [comment]
Here are the details：
wzy@ubuntu:~/Fast-Drone-250-master$ roslaunch realsense2_camera rs_camera.launch
... logging to /home/wzy/.ros/log/656d624a-2967-11ee-9fb2-845cf326b7db/roslaunch-ubuntu-7185.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://ubuntu:39287/

SUMMARY
========

PARAMETERS
 * /camera/realsense2_camera/accel_fps: 250
 * /camera/realsense2_camera/accel_frame_id: camera_accel_frame
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: False
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/allow_no_texture_points: False
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/calib_odom_file: 
 * /camera/realsense2_camera/clip_distance: -2.0
 * /camera/realsense2_camera/color_fps: 30
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: 480
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: 640
 * /camera/realsense2_camera/confidence_fps: 30
 * /camera/realsense2_camera/confidence_height: 480
 * /camera/realsense2_camera/confidence_width: 640
 * /camera/realsense2_camera/depth_fps: 30
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: 480
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: 640
 * /camera/realsense2_camera/device_type: 
 * /camera/realsense2_camera/enable_accel: False
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_confidence: False
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye1: False
 * /camera/realsense2_camera/enable_fisheye2: False
 * /camera/realsense2_camera/enable_fisheye: False
 * /camera/realsense2_camera/enable_gyro: False
 * /camera/realsense2_camera/enable_infra1: True
 * /camera/realsense2_camera/enable_infra2: True
 * /camera/realsense2_camera/enable_infra: True
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_pose: False
 * /camera/realsense2_camera/enable_sync: False
 * /camera/realsense2_camera/filters: 
 * /camera/realsense2_camera/fisheye1_frame_id: camera_fisheye1_f...
 * /camera/realsense2_camera/fisheye1_optical_frame_id: camera_fisheye1_o...
 * /camera/realsense2_camera/fisheye2_frame_id: camera_fisheye2_f...
 * /camera/realsense2_camera/fisheye2_optical_frame_id: camera_fisheye2_o...
 * /camera/realsense2_camera/fisheye_fps: 30
 * /camera/realsense2_camera/fisheye_frame_id: camera_fisheye_frame
 * /camera/realsense2_camera/fisheye_height: 480
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: 640
 * /camera/realsense2_camera/gyro_fps: 400
 * /camera/realsense2_camera/gyro_frame_id: camera_gyro_frame
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/imu_optical_frame_id: camera_imu_optica...
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra_fps: 30
 * /camera/realsense2_camera/infra_height: 480
 * /camera/realsense2_camera/infra_rgb: False
 * /camera/realsense2_camera/infra_width: 640
 * /camera/realsense2_camera/initial_reset: False
 * /camera/realsense2_camera/json_file_path: 
 * /camera/realsense2_camera/linear_accel_cov: 0.01
 * /camera/realsense2_camera/odom_frame_id: camera_odom_frame
 * /camera/realsense2_camera/ordered_pc: False
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/pose_frame_id: camera_pose_frame
 * /camera/realsense2_camera/pose_optical_frame_id: camera_pose_optic...
 * /camera/realsense2_camera/publish_odom_tf: True
 * /camera/realsense2_camera/publish_tf: True
 * /camera/realsense2_camera/reconnect_timeout: 6.0
 * /camera/realsense2_camera/rosbag_filename: 
 * /camera/realsense2_camera/serial_no: 
 * /camera/realsense2_camera/stereo_module/exposure/1: 7500
 * /camera/realsense2_camera/stereo_module/exposure/2: 1
 * /camera/realsense2_camera/stereo_module/gain/1: 16
 * /camera/realsense2_camera/stereo_module/gain/2: 16
 * /camera/realsense2_camera/tf_publish_rate: 0.0
 * /camera/realsense2_camera/topic_odom_in: odom_in
 * /camera/realsense2_camera/unite_imu_method: 
 * /camera/realsense2_camera/usb_port_id: 
 * /camera/realsense2_camera/wait_for_device_timeout: -1.0
 * /rosdistro: noetic
 * /rosversion: 1.16.0

NODES
  /camera/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)

auto-starting new master
process[master]: started with pid [7203]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 656d624a-2967-11ee-9fb2-845cf326b7db
process[rosout-1]: started with pid [7222]
started core service [/rosout]
process[camera/realsense2_camera_manager-2]: started with pid [7229]
process[camera/realsense2_camera-3]: started with pid [7230]
[ INFO] [1690123458.144332559]: Initializing nodelet with 4 worker threads.
[ INFO] [1690123458.388992236]: RealSense ROS v2.3.2
[ INFO] [1690123458.389121161]: Built with LibRealSense v2.50.0
[ INFO] [1690123458.389220358]: Running with LibRealSense v2.50.0
[ INFO] [1690123458.470935446]:  
[ INFO] [1690123458.588867320]: Device with serial number 242622070583 was found.

[ INFO] [1690123458.589515239]: Device with physical ID /sys/devices/platform/3610000.xhci/usb2/2-3/2-3.3/2-3.3:1.0/video4linux/video0 was found.
[ INFO] [1690123458.589910268]: Device with name Intel RealSense D435I was found.
[ INFO] [1690123458.591959719]: Device with port number 2-3.3 was found.
[ INFO] [1690123458.592446298]: Device USB type: 3.2
[ INFO] [1690123458.610641569]: getParameters...
[ INFO] [1690123458.774243260]: setupDevice...
[ INFO] [1690123458.774371865]: JSON file is not provided
[ INFO] [1690123458.774451063]: ROS Node Namespace: camera
[ INFO] [1690123458.774626130]: Device Name: Intel RealSense D435I
[ INFO] [1690123458.774693841]: Device Serial No: 242622070583
[ INFO] [1690123458.774795342]: Device physical port: /sys/devices/platform/3610000.xhci/usb2/2-3/2-3.3/2-3.3:1.0/video4linux/video0
[ INFO] [1690123458.774907307]: Device FW version: 05.15.00.02
[ INFO] [1690123458.774995497]: Device Product ID: 0x0B3A
[ INFO] [1690123458.775057767]: Enable PointCloud: Off
[ INFO] [1690123458.775162628]: Align Depth: Off
[ INFO] [1690123458.775220643]: Sync Mode: Off
[ INFO] [1690123458.775470076]: Device Sensors: 
[ INFO] [1690123458.837267283]: Stereo Module was found.
[ INFO] [1690123458.912239443]: RGB Camera was found.
[ INFO] [1690123458.914805904]: Motion Module was found.
[ INFO] [1690123458.915107336]: (Infrared, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1690123458.915229669]: num_filters: 0
[ INFO] [1690123458.915362082]: Setting Dynamic reconfig parameters.
hwmon command 0x80( 5 0 0 0 ) failed (response -7= HW not ready)
hwmon command 0x80( 5 0 0 0 ) failed (response -7= HW not ready)
hwmon command 0x80( 5 0 0 0 ) failed (response -7= HW not ready)
hwmon command 0x80( 5 0 0 0 ) failed (response -7= HW not ready)
[ WARN] [1690123459.118051978]: Param '/camera/rgb_camera/power_line_frequency' has value 3 that is not in the enum { {50Hz: 1} {60Hz: 2} {Disabled: 0} }. Removing this parameter from dynamic reconfigure options.
[ INFO] [1690123459.142008956]: Done Setting Dynamic reconfig parameters.
[ INFO] [1690123459.145867255]: depth stream is enabled - width: 640, height: 480, fps: 30, Format: Z16
[ INFO] [1690123459.147070392]: infra1 stream is enabled - width: 640, height: 480, fps: 30, Format: Y8
[ INFO] [1690123459.148351383]: infra2 stream is enabled - width: 640, height: 480, fps: 30, Format: Y8
[ INFO] [1690123459.152430509]: color stream is enabled - width: 640, height: 480, fps: 30, Format: RGB8
[ INFO] [1690123459.152613992]: setupPublishers...
[ INFO] [1690123459.166119849]: Expected frequency for depth = 30.00000
[ INFO] [1690123459.177305287]: Expected frequency for infra1 = 30.00000
[ INFO] [1690123459.184509195]: Expected frequency for infra2 = 30.00000
[ INFO] [1690123459.194210447]: Expected frequency for color = 30.00000
[ INFO] [1690123459.205493290]: setupStreams...
[ INFO] [1690123459.409072864]: SELECTED BASE:Depth, 0
[ INFO] [1690123459.452754161]: RealSense Node Is Up!
[ WARN] [1690123459.490632153]: 
malloc(): invalid size (unsorted)
[camera/realsense2_camera_manager-2] process has died [pid 7229, exit code -6, cmd /opt/ros/noetic/lib/nodelet/nodelet manager __name:=realsense2_camera_manager __log:=/home/wzy/.ros/log/656d624a-2967-11ee-9fb2-845cf326b7db/camera-realsense2_camera_manager-2.log].
log file: /home/wzy/.ros/log/656d624a-2967-11ee-9fb2-845cf326b7db/camera-realsense2_camera_manager-2*.log
[camera/realsense2_camera-3] process has finished cleanly
log file: /home/wzy/.ros/log/656d624a-2967-11ee-9fb2-845cf326b7db/camera-realsense2_camera-3*.log

**Comment by EGOIST5** [comment]
I did some more experiments：use "roslaunch realsense2_camera rs_camera.launch filters:=pointcloud" command,then also use  "rqt_image_view" command.
here are the details：wzy@ubuntu:~/Fast-Drone-250-master$ roslaunch realsense2_camera rs_camera.launch filters:=pointcloud
... logging to /home/wzy/.ros/log/e0b08896-2968-11ee-8ad7-845cf326b7db/roslaunch-ubuntu-10738.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://ubuntu:40803/

SUMMARY
========

PARAMETERS
 * /camera/realsense2_camera/accel_fps: 250
 * /camera/realsense2_camera/accel_frame_id: camera_accel_frame
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: False
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/allow_no_texture_points: False
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/calib_odom_file: 
 * /camera/realsense2_camera/clip_distance: -2.0
 * /camera/realsense2_camera/color_fps: 30
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: 480
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: 640
 * /camera/realsense2_camera/confidence_fps: 30
 * /camera/realsense2_camera/confidence_height: 480
 * /camera/realsense2_camera/confidence_width: 640
 * /camera/realsense2_camera/depth_fps: 30
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: 480
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: 640
 * /camera/realsense2_camera/device_type: 
 * /camera/realsense2_camera/enable_accel: False
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_confidence: False
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye1: False
 * /camera/realsense2_camera/enable_fisheye2: False
 * /camera/realsense2_camera/enable_fisheye: False
 * /camera/realsense2_camera/enable_gyro: False
 * /camera/realsense2_camera/enable_infra1: True
 * /camera/realsense2_camera/enable_infra2: True
 * /camera/realsense2_camera/enable_infra: True
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_pose: False
 * /camera/realsense2_camera/enable_sync: False
 * /camera/realsense2_camera/filters: pointcloud
 * /camera/realsense2_camera/fisheye1_frame_id: camera_fisheye1_f...
 * /camera/realsense2_camera/fisheye1_optical_frame_id: camera_fisheye1_o...
 * /camera/realsense2_camera/fisheye2_frame_id: camera_fisheye2_f...
 * /camera/realsense2_camera/fisheye2_optical_frame_id: camera_fisheye2_o...
 * /camera/realsense2_camera/fisheye_fps: 30
 * /camera/realsense2_camera/fisheye_frame_id: camera_fisheye_frame
 * /camera/realsense2_camera/fisheye_height: 480
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: 640
 * /camera/realsense2_camera/gyro_fps: 400
 * /camera/realsense2_camera/gyro_frame_id: camera_gyro_frame
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/imu_optical_frame_id: camera_imu_optica...
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra_fps: 30
 * /camera/realsense2_camera/infra_height: 480
 * /camera/realsense2_camera/infra_rgb: False
 * /camera/realsense2_camera/infra_width: 640
 * /camera/realsense2_camera/initial_reset: False
 * /camera/realsense2_camera/json_file_path: 
 * /camera/realsense2_camera/linear_accel_cov: 0.01
 * /camera/realsense2_camera/odom_frame_id: camera_odom_frame
 * /camera/realsense2_camera/ordered_pc: False
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/pose_frame_id: camera_pose_frame
 * /camera/realsense2_camera/pose_optical_frame_id: camera_pose_optic...
 * /camera/realsense2_camera/publish_odom_tf: True
 * /camera/realsense2_camera/publish_tf: True
 * /camera/realsense2_camera/reconnect_timeout: 6.0
 * /camera/realsense2_camera/rosbag_filename: 
 * /camera/realsense2_camera/serial_no: 
 * /camera/realsense2_camera/stereo_module/exposure/1: 7500
 * /camera/realsense2_camera/stereo_module/exposure/2: 1
 * /camera/realsense2_camera/stereo_module/gain/1: 16
 * /camera/realsense2_camera/stereo_module/gain/2: 16
 * /camera/realsense2_camera/tf_publish_rate: 0.0
 * /camera/realsense2_camera/topic_odom_in: odom_in
 * /camera/realsense2_camera/unite_imu_method: 
 * /camera/realsense2_camera/usb_port_id: 
 * /camera/realsense2_camera/wait_for_device_timeout: -1.0
 * /rosdistro: noetic
 * /rosversion: 1.16.0

NODES
  /camera/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)

auto-starting new master
process[master]: started with pid [10755]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to e0b08896-2968-11ee-8ad7-845cf326b7db
process[rosout-1]: started with pid [10765]
started core service [/rosout]
process[camera/realsense2_camera_manager-2]: started with pid [10772]
process[camera/realsense2_camera-3]: started with pid [10773]
[ INFO] [1690124094.453090587]: Initializing nodelet with 4 worker threads.
[ INFO] [1690124094.667301491]: RealSense ROS v2.3.2
[ INFO] [1690124094.667569275]: Built with LibRealSense v2.50.0
[ INFO] [1690124094.667675038]: Running with LibRealSense v2.50.0
[ INFO] [1690124094.754496216]:  
[ INFO] [1690124094.825166878]: Device with serial number 242622070583 was found.

[ INFO] [1690124094.825351588]: Device with physical ID /sys/devices/platform/3610000.xhci/usb2/2-3/2-3.3/2-3.3:1.0/video4linux/video0 was found.
[ INFO] [1690124094.825426118]: Device with name Intel RealSense D435I was found.
[ INFO] [1690124094.826808817]: Device with port number 2-3.3 was found.
[ INFO] [1690124094.826940789]: Device USB type: 3.2
[ INFO] [1690124094.848446861]: getParameters...
[ INFO] [1690124095.025827729]: setupDevice...
[ INFO] [1690124095.025975925]: JSON file is not provided
[ INFO] [1690124095.026043191]: ROS Node Namespace: camera
[ INFO] [1690124095.026150267]: Device Name: Intel RealSense D435I
[ INFO] [1690124095.026352481]: Device Serial No: 242622070583
[ INFO] [1690124095.026603561]: Device physical port: /sys/devices/platform/3610000.xhci/usb2/2-3/2-3.3/2-3.3:1.0/video4linux/video0
[ INFO] [1690124095.027465571]: Device FW version: 05.15.00.02
[ INFO] [1690124095.027558918]: Device Product ID: 0x0B3A
[ INFO] [1690124095.027617192]: Enable PointCloud: On
[ INFO] [1690124095.027672745]: Align Depth: Off
[ INFO] [1690124095.027896848]: Sync Mode: On
[ INFO] [1690124095.028554181]: Device Sensors: 
[ INFO] [1690124095.089656829]: Stereo Module was found.
[ INFO] [1690124095.157078775]: RGB Camera was found.
[ INFO] [1690124095.160469440]: Motion Module was found.
[ INFO] [1690124095.161512576]: (Infrared, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1690124095.162219766]: Add Filter: pointcloud
[ INFO] [1690124095.174002144]: num_filters: 1
[ INFO] [1690124095.174606867]: Setting Dynamic reconfig parameters.
hwmon command 0x80( 5 0 0 0 ) failed (response -7= HW not ready)
hwmon command 0x80( 5 0 0 0 ) failed (response -7= HW not ready)
hwmon command 0x80( 5 0 0 0 ) failed (response -7= HW not ready)
hwmon command 0x80( 5 0 0 0 ) failed (response -7= HW not ready)
[ WARN] [1690124095.422168468]: Param '/camera/rgb_camera/power_line_frequency' has value 3 that is not in the enum { {50Hz: 1} {60Hz: 2} {Disabled: 0} }. Removing this parameter from dynamic reconfigure options.
[ INFO] [1690124095.464771187]: Done Setting Dynamic reconfig parameters.
[ INFO] [1690124095.474752615]: depth stream is enabled - width: 640, height: 480, fps: 30, Format: Z16
[ INFO] [1690124095.476771333]: infra1 stream is enabled - width: 640, height: 480, fps: 30, Format: Y8
[ INFO] [1690124095.480661724]: infra2 stream is enabled - width: 640, height: 480, fps: 30, Format: Y8
[ INFO] [1690124095.484594741]: color stream is enabled - width: 640, height: 480, fps: 30, Format: RGB8
[ INFO] [1690124095.484878494]: setupPublishers...
[ INFO] [1690124095.493085403]: Expected frequency for depth = 30.00000
[ INFO] [1690124095.504608605]: Expected frequency for infra1 = 30.00000
[ INFO] [1690124095.513521039]: Expected frequency for infra2 = 30.00000
[ INFO] [1690124095.522568454]: Expected frequency for color = 30.00000
[ INFO] [1690124095.537292779]: setupStreams...
[ INFO] [1690124095.720481072]: SELECTED BASE:Depth, 0
[ INFO] [1690124095.771990945]: RealSense Node Is Up!
[ WARN] [1690124095.807110906]: 
free(): invalid pointer
[camera/realsense2_camera_manager-2] process has died [pid 10772, exit code -6, cmd /opt/ros/noetic/lib/nodelet/nodelet manager __name:=realsense2_camera_manager __log:=/home/wzy/.ros/log/e0b08896-2968-11ee-8ad7-845cf326b7db/camera-realsense2_camera_manager-2.log].
log file: /home/wzy/.ros/log/e0b08896-2968-11ee-8ad7-845cf326b7db/camera-realsense2_camera_manager-2*.log
[camera/realsense2_camera-3] process has finished cleanly
log file: /home/wzy/.ros/log/e0b08896-2968-11ee-8ad7-845cf326b7db/camera-realsense2_camera-3*.log

**Comment by MartyG-RealSense** [comment]
Hi @EGOIST5  The only previous report of the **malloc(): invalid size (unsorted)** problem with RealSense ROS is at https://github.com/IntelRealSense/realsense-ros/issues/2656

In that particular issue, I suggested performing a clean wipe and reinstall at https://github.com/IntelRealSense/realsense-ros/issues/2656#issuecomment-1467883440 in case the librealsense SDK had been installed on the computer more than once, and a clean reinstall made the `malloc(): invalid size (unsorted) `problem disappear.

**Comment by EGOIST5** [comment]
Thanks for your answer, I have successfully solved the problem

**Comment by MartyG-RealSense** [comment]
You are very welcome.  It's excellent to hear that you achieved a solution.  Thanks very much for the update!
