### ISSUE TITLE
IMU coordinate frame in ZR300

### ISSUE THREAD

**Issue by tuandle** [realsenseai/realsense-ros#282]
| Version               | Your Configuration   |
|:--------------------- |:---------------------|
| Operating System      | Ubuntu 16.04.3 LTS                |
| Kernel                | 4.10.0-42-generic               |
| ROS                   | Kinetic                   |
| ROS RealSense         | 1.8.0               |
| librealsense          | 1.12.1                |
| Camera Type-Firmware  | 2.0.71.8            |

Hi,
I have a question regarding the coordinate's frame of the IMU in ZR300. 
I couldn't find any reference to this coordinate in the device's documentation. I wonder if there were any information available?
Thank you for your help!

**Comment by icarpis** [comment]
The following image describes the coordinates of ZR300 Gyroscope and Accelerometer sensors.
![image](https://user-images.githubusercontent.com/17433152/34095394-ed0b10e6-e3d9-11e7-8b48-3990bb9f13f3.png)

Accelerometer axes: the positive x-axis points to the right, the positive y-axis points down and the positive z-axis points forward.
The gyrosocpe axes is around the accelerometer axes respectively.

**Comment by tuandle** [comment]
Hi @icarpis ,
Thank you for your clarification!
Best,
Tuan
