### ISSUE TITLE
noise

### ISSUE THREAD

**Issue by derekhe89** [realsenseai/realsense-ros#283]
Hello,i want to know noise parameter which geted form sdk is contious or  dispersed？

**Comment by icarpis** [comment]
Hello @derekhe89, what do you mean by 'noise parameter' ?

**Comment by derekhe89** [comment]
The noise parameter is the noise_variances and the bias_variances.

**Comment by derekhe89** [comment]
I want konw the contious noise_density and random_walk of gyroscope and accelerometer,but i don't know how to get that . Is the noise_variances is noise_density and the bias_variances is random_walk?@ icarpis

**Comment by icarpis** [comment]
The ROS wrapper publish the IMU calibration info in order to calibrate the IMU (Accel/Gyro). Please take a look at this issue #256 .

**Comment by derekhe89** [comment]
Thank you for your answer. The issue you gave me just explain the scale、 cross axis and bias, but i want to know the contious noise_density and random_walk of gyroscope and accelerometer. @icarpis

**Comment by icarpis** [comment]
These parameters could be found in this [issue](https://github.com/IntelRealSense/librealsense/issues/798).
If you still have more questions about the ZR300 IMU sensor please consider to post a question in that issue.
