### ISSUE TITLE
Realsense d435 Bad Quality

### ISSUE THREAD

**Issue by gurselturkeri** [realsenseai/realsense-ros#2831]
Hi, I would like to use d435 for object detection but quality is really bad. Is there any settings to better quality.
![Screenshot from 2023-08-01 10-26-26](https://github.com/IntelRealSense/realsense-ros/assets/68682737/71cbc30f-a5a7-48a2-9a99-22db15973599)

**Comment by MartyG-RealSense** [comment]
Hi @gurselturkeri  You could try maximizing the RGB **Sharpness** to make the objects clearer, like in the example of Python code for doing so at https://github.com/IntelRealSense/librealsense/issues/12030#issuecomment-1647640046

**Comment by gurselturkeri** [comment]
> Hi @gurselturkeri You could try maximizing the RGB **Sharpness** to make the objects clearer, like in the example of Python code for doing so at [IntelRealSense/librealsense#12030 (comment)](https://github.com/IntelRealSense/librealsense/issues/12030#issuecomment-1647640046)

How can I do that with using CLI? Is it correct?: `roslaunch realsense2_camera rs_camera.launch sharpness:=100`

**Comment by MartyG-RealSense** [comment]
That instruction should work for setting the sharpness parameter.  You could also set it by loading a **json** camera configuration file into the launch, either by defining a **json_file_path** inside the launch file or by setting json_file_path in the roslaunch instruction.

**Comment by MartyG-RealSense** [comment]
Hi @gurselturkeri   Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
