### ISSUE TITLE
 how to trigger D435i camera via MCU

### ISSUE THREAD

**Issue by gyt290811** [realsenseai/realsense-ros#2833]
hi,
Do you know how to trigger D435i camera via MCU? We are trying to fix this issue out. According to the official documentation, the camera only facing realsense cameras.
But these don't meet our requirements, so I'd like to ask if you have any solutions for this? For example, modify some places in the SDK so that the camera can be triggered externally。

Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to duplcate of https://github.com/IntelRealSense/librealsense/issues/12064
