### ISSUE TITLE
reset camera

### ISSUE THREAD

**Issue by ggsd-ddup** [realsenseai/realsense-ros#2835]
Hello everyone ！ I have a question about multiple camera such as D435 and T265 ， Someone knows how to restart one of the cameras when they are all running ？

**Comment by MartyG-RealSense** [comment]
Hi @hfdlwt  A C++ hardware reset script at https://github.com/IntelRealSense/librealsense/issues/9287#issuecomment-867826974 will cycle through all attached cameras.

If a specific camera in a set of multiple cameras needs to be reset then https://github.com/IntelRealSense/librealsense/issues/5428 describes how to perform this in Python using a camera serial number.

**Comment by ggsd-ddup** [comment]
Thank you for your prompt reply @MartyG-RealSense ，Can the camera continue to work after hardware restart, or does it need to restart the launch file （realsense_camera manger node）

**Comment by MartyG-RealSense** [comment]
Although a reset will disconnect the camera and then re-connect it, my understanding is that a current session will continue if reconnection is achieved within a time period of 5 seconds.  If it takes longer than 5 seconds to re-establish the connection after disconnection then the connection 'times out' (hence the well known error message 'Frame didn't arrive within 5000').

A typical reset of the camera will complete within 3 seconds.

It is certainly possible to reset the camera during a ROS launch without restarting the launch when using the **initial_reset:=true** parameter.

**Comment by ggsd-ddup** [comment]
Thanks again @MartyG-RealSense , Are you talking about manually restarting the camera? What I want is to automatically restart the camera through a trigger condition in the program.

**Comment by MartyG-RealSense** [comment]
That code will automatically restart the camera when the script is launched.  You can though nest a **hardware_reset()** instruction within an If code block so that if certain conditions are met then the reset command within the If condition is triggered.

**Comment by MartyG-RealSense** [comment]
Hi @ggsd-ddup   Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
