### ISSUE TITLE
Malloc(): memory corruption

### ISSUE THREAD

**Issue by qiyueliuhuo23** [realsenseai/realsense-ros#2838]
I was using `roslaunch realsense2_camera rs_camera.launch initial_reset:=true`，the node was fine. But when I start my own script with cmds `rosrun yolox yolox_hat.py`, in yolox_hat.py I get the raw img from realsense camera and process them to detect safety helmet, and **Malloc(): memory corruption** occurred.
I am using :
realsense D435i
Ubuntu 18.04 5.4.0-150-generic
ros-melodic

Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://zt-System-Product-Name:45477/

SUMMARY
========

PARAMETERS
 * /camera/realsense2_camera/accel_fps: -1
 * /camera/realsense2_camera/accel_frame_id: camera_accel_frame
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: True
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/allow_no_texture_points: False
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/calib_odom_file:
 * /camera/realsense2_camera/clip_distance: -2.0
 * /camera/realsense2_camera/color_fps: -1
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: -1
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: -1
 * /camera/realsense2_camera/confidence_fps: -1
 * /camera/realsense2_camera/confidence_height: -1
 * /camera/realsense2_camera/confidence_width: -1
 * /camera/realsense2_camera/depth_fps: -1
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: -1
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: -1
 * /camera/realsense2_camera/device_type:
 * /camera/realsense2_camera/enable_accel: False
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_confidence: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye1: False
 * /camera/realsense2_camera/enable_fisheye2: False
 * /camera/realsense2_camera/enable_fisheye: False
 * /camera/realsense2_camera/enable_gyro: False
 * /camera/realsense2_camera/enable_infra1: False
 * /camera/realsense2_camera/enable_infra2: False
 * /camera/realsense2_camera/enable_infra: False
 * /camera/realsense2_camera/enable_pointcloud: True
 * /camera/realsense2_camera/enable_pose: False
 * /camera/realsense2_camera/enable_sync: True
 * /camera/realsense2_camera/filters:
 * /camera/realsense2_camera/fisheye1_frame_id: camera_fisheye1_f...
 * /camera/realsense2_camera/fisheye1_optical_frame_id: camera_fisheye1_o...
 * /camera/realsense2_camera/fisheye2_frame_id: camera_fisheye2_f...
 * /camera/realsense2_camera/fisheye2_optical_frame_id: camera_fisheye2_o...
 * /camera/realsense2_camera/fisheye_fps: -1
 * /camera/realsense2_camera/fisheye_frame_id: camera_fisheye_frame
 * /camera/realsense2_camera/fisheye_height: -1
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: -1
 * /camera/realsense2_camera/gyro_fps: -1
 * /camera/realsense2_camera/gyro_frame_id: camera_gyro_frame
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/imu_optical_frame_id: camera_imu_optica...
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra_fps: 30
 * /camera/realsense2_camera/infra_height: 480
 * /camera/realsense2_camera/infra_rgb: False
 * /camera/realsense2_camera/infra_width: 848
 * /camera/realsense2_camera/initial_reset: True
 * /camera/realsense2_camera/json_file_path:
 * /camera/realsense2_camera/linear_accel_cov: 0.01
 * /camera/realsense2_camera/odom_frame_id: camera_odom_frame
 * /camera/realsense2_camera/ordered_pc: False
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/pose_frame_id: camera_pose_frame
 * /camera/realsense2_camera/pose_optical_frame_id: camera_pose_optic...
 * /camera/realsense2_camera/publish_odom_tf: True
 * /camera/realsense2_camera/publish_tf: True
 * /camera/realsense2_camera/reconnect_timeout: 6.0
 * /camera/realsense2_camera/rosbag_filename:
 * /camera/realsense2_camera/serial_no:
 * /camera/realsense2_camera/stereo_module/exposure/1: 7500
 * /camera/realsense2_camera/stereo_module/exposure/2: 1
 * /camera/realsense2_camera/stereo_module/gain/1: 16
 * /camera/realsense2_camera/stereo_module/gain/2: 16
 * /camera/realsense2_camera/tf_publish_rate: 0.0
 * /camera/realsense2_camera/topic_odom_in: odom_in
 * /camera/realsense2_camera/unite_imu_method:
 * /camera/realsense2_camera/usb_port_id:
 * /camera/realsense2_camera/wait_for_device_timeout: -1.0
 * /rosdistro: melodic
 * /rosversion: 1.14.13

NODES
  /camera/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)

ROS_MASTER_URI=http://localhost:11311

process[camera/realsense2_camera_manager-1]: started with pid [31457]
process[camera/realsense2_camera-2]: started with pid [31458]
[ INFO] [1691554139.217310731]: Initializing nodelet with 12 worker threads.
[ INFO] [1691554139.303812838]: RealSense ROS v2.3.2
[ INFO] [1691554139.303834749]: Built with LibRealSense v2.54.1
[ INFO] [1691554139.303843213]: Running with LibRealSense v2.54.1
[ INFO] [1691554139.319078821]:  
[ INFO] [1691554139.379982502]: Device with serial number 108322071393 was found.

[ INFO] [1691554139.380044051]: Device with physical ID /sys/devices/pci0000:00/0000:00:14.0/usb2/2-1/2-1:1.0/video4linux/video0 was found.
[ INFO] [1691554139.380069901]: Device with name Intel RealSense D435I was found.
[ INFO] [1691554139.380549873]: Device with port number 2-1 was found.
[ INFO] [1691554139.380582124]: Device USB type: 3.2
[ INFO] [1691554139.380609505]: Resetting device...
[ INFO] [1691554145.428960409]:  
[ INFO] [1691554145.451559336]: Device with serial number 108322071393 was found.

[ INFO] [1691554145.451651920]: Device with physical ID /sys/devices/pci0000:00/0000:00:14.0/usb2/2-1/2-1:1.0/video4linux/video0 was found.
[ INFO] [1691554145.451694423]: Device with name Intel RealSense D435I was found.
[ INFO] [1691554145.452536736]: Device with port number 2-1 was found.
[ INFO] [1691554145.452587428]: Device USB type: 3.2
[ INFO] [1691554145.462323211]: getParameters...
[ INFO] [1691554145.492018845]: setupDevice...
[ INFO] [1691554145.492036603]: JSON file is not provided
[ INFO] [1691554145.492042357]: ROS Node Namespace: camera
[ INFO] [1691554145.492062276]: Device Name: Intel RealSense D435I
[ INFO] [1691554145.492070336]: Device Serial No: 108322071393
[ INFO] [1691554145.492081044]: Device physical port: /sys/devices/pci0000:00/0000:00:14.0/usb2/2-1/2-1:1.0/video4linux/video0
[ INFO] [1691554145.492091147]: Device FW version: 5.12.15.50
[ INFO] [1691554145.492109242]: Device Product ID: 0x0B3A
[ INFO] [1691554145.492123438]: Enable PointCloud: On
[ INFO] [1691554145.492132076]: Align Depth: On
[ INFO] [1691554145.492140320]: Sync Mode: On
[ INFO] [1691554145.492232877]: Device Sensors:
[ INFO] [1691554145.497078292]: Stereo Module was found.
 09/08 12:09:05,497 WARNING [140257123104512] (backend-v4l2.cpp:1855) Pixel format 36315752-1a66-a242-9065-d01814a likely requires patch for fourcc code RW16!
[ INFO] [1691554145.514633801]: RGB Camera was found.
[ INFO] [1691554145.515083317]: Motion Module was found.
[ INFO] [1691554145.515119317]: (Confidence, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1691554145.516060319]: Add Filter: pointcloud
[ INFO] [1691554145.518210730]: num_filters: 2
[ INFO] [1691554145.518229976]: Setting Dynamic reconfig parameters.
[ WARN] [1691554145.580951988]: Param '/camera/rgb_camera/power_line_frequency' has value 3 that is not in the enum { {50Hz: 1} {60Hz: 2} {Disabled: 0} }. Removing this parameter from dynamic reconfigure options.
[ INFO] [1691554145.592524797]: Done Setting Dynamic reconfig parameters.
[ INFO] [1691554145.593198938]: depth stream is enabled - width: 848, height: 480, fps: 30, Format: Z16
[ INFO] [1691554145.594381994]: color stream is enabled - width: 1280, height: 720, fps: 30, Format: RGB8
[ INFO] [1691554145.595648935]: setupPublishers...
[ INFO] [1691554145.596680994]: Expected frequency for depth = 30.00000
[ INFO] [1691554145.615433196]: Expected frequency for color = 30.00000
[ INFO] [1691554145.627591887]: Expected frequency for aligned_depth_to_color = 30.00000
[ INFO] [1691554145.636753815]: setupStreams...
[ INFO] [1691554145.689390808]: SELECTED BASE:Depth, 0
[ INFO] [1691554145.697231321]: RealSense Node Is Up!
[ WARN] [1691554145.807888568]:
[ WARN] [1691554146.593384728]: Hardware Notification:Left MIPI error,1.69155e+12,Error,Hardware Error
malloc(): memory corruption
[camera/realsense2_camera_manager-1] process has died [pid 31457, exit code -6, cmd /opt/ros/melodic/lib/nodelet/nodelet manager __name:=realsense2_camera_manager __log:=/home/zt/.ros/log/3317c870-366a-11ee-baf1-581122d9af9c/camera-realsense2_camera_manager-1.log].
log file: /home/zt/.ros/log/3317c870-366a-11ee-baf1-581122d9af9c/camera-realsense2_camera_manager-1*.log
[camera/realsense2_camera-2] process has finished cleanly
log file: /home/zt/.ros/log/3317c870-366a-11ee-baf1-581122d9af9c/camera-realsense2_camera-2*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done

And the log in master.log are:
[rosmaster.master][INFO] 2023-08-09 12:40:14,652: publisherUpdate[/debug/image] -> http://zt-System-Product-Name:44049/ []
[rosmaster.master][INFO] 2023-08-09 12:40:14,654: publisherUpdate[/rosout] -> http://zt-System-Product-Name:44575/ ['http://zt-System-Product-Name:44049/', 'http://zt-System-Product-Name:35205/']: sec=0.00, result=[1, '', 0]
[rosmaster.master][INFO] 2023-08-09 12:40:14,654: publisherUpdate[/debug/image] -> http://zt-System-Product-Name:44049/ []: sec=0.00, exception=[Errno 111] Connection refused
[rosmaster.threadpool][ERROR] 2023-08-09 12:40:14,654: Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosmaster/threadpool.py", line 218, in run
    result = cmd(*args)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosmaster/master_api.py", line 210, in publisher_update_task
    ret = xmlrpcapi(api).publisherUpdate('/master', topic, pub_uris)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1311, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1459, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 1095, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 898, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 860, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 837, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

**Comment by MartyG-RealSense** [comment]
Hi @qiyueliuhuo23  ROS1 wrapper 2.3.2 should be used with librealsense version **2.51.1** and camera firmware version **5.13.0.50** instead of librealsense 2.54.1 and firmware 5.12.15.50.   

I note though that you were able to launch successfully with 2.54.1 / 5.12.15.50.

Are you starting your yolox script first and launching the ROS wrapper secondly afterwards?  If you are, does it make a difference if you launch the ROS wrapper first and your yolox script second?

**Comment by qiyueliuhuo23** [comment]
So is there a guide or something to teach me how to uninstall the librealsense and change the firmware with a lower version?
And I start the ROS wrapper first and then I start my yolox script later trying to get RGB raw img from the topic that rs_camera.launch published etc. /camera/color/image_raw. 
And I think let you know how I install the librealsense SDK maybe helpful, Here is how I install the librealsense SDK :

1. get source code
`git clone https://github.com/IntelRealSense/librealsense`
`cd librealsense`
2. install dependencies
`sudo apt-get install libudev-dev pkg-config libgtk-3-dev`
`sudo apt-get install libusb-1.0-0-dev pkg-config`
`sudo apt-get install libglfw3-dev`
`sudo apt-get install libssl-dev`
3. install permission scripts
`sudo cp config/99-realsense-libusb.rules /etc/udev/rules.d/`
`sudo udevadm control --reload-rules && udevadm trigger`
4. compile soucre code from github and install
`mkdir build`
`cd build`
`cmake ../ -DBUILD_EXAMPLES=true`
`make`
`sudo make install`

Thanks for replying me!

**Comment by MartyG-RealSense** [comment]
Your librealsense source code installation procedure looks fine.

To remove a previous librealsense source code installation, go to the 'build' folder of that installation and input the instruction below.

`sudo make uninstall && make clean`

*********

In regard to changing the firmware version, if the flag `-DBUILD_GRAPHICAL_EXAMPLES=true `is not included in your CMake build instruction then graphics support and graphics-based tools and examples will not be built, meaning that the RealSense Viewer tool cannot be used to change the firmware (which is the easiest method of doing it).  

Instead, you will need to use the text-based **rs-fw-update** tool which should be included in your librealsense build because you included the `-DBUILD_EXAMPLES=true` flag to include text-based tools and examples.

https://github.com/IntelRealSense/librealsense/tree/master/tools/fw-update

The first step would be to visit the firmware archive page and download to your computer the firmware **.bin** file for the particular firmware version to update to (5.13.0.50, which has a .bin file named **Signed_Image_UVC_5_13_0_50.bin**.

https://dev.intelrealsense.com/docs/firmware-releases

Then launch the rs-fw-update tool with the command **rs-fw-update -l**

This will list the details of your camera, including its serial number which must be noted down.

Once you have the serial number, input the command below to update the firmware version of the camera to 5.13.0.50.

`rs-fw-update -s [serial number] -f Signed_Image_UVC_5_13_0_50.bin`

For example, if the serial number was 725112060411:

`rs-fw-update -s 725112060411 -f Signed_Image_UVC_5_13_0_50.bin`

**Comment by qiyueliuhuo23** [comment]
Thanks for teaching me how to uninstall librealsense and change fireware version. Follow your comments, I got the ROS1 wrapper  2.3.2 with librealsense version 2.51.1 and camera firmware version 5.13.0.50, but I got the same Malloc(): memory corruption as before.
Here is how I start my yolox script:
1. First terminal: `ros core`
2. Second terminal: `roslaunch realsense2_camera rs_camera.launch initial_reset:=true`
3. Third terminal: `rosrun yolox_ros yolox_hat.py`

The second terminal works fine before I type the command in third terminal.
After I type the command `rosrun yolox_ros yolox_hat.py`, the second terminal got  **Malloc(): memory corruption** 
Here are the log in second terminal:

>Checking log directory for disk usage. This may take a while.
>Press Ctrl-C to interrupt
>Done checking log file disk usage. Usage is <1GB.
>
>started roslaunch server http://zt-System-Product-Name:35991/
>
>SUMMARY
>========
>
>PARAMETERS
> * /camera/realsense2_camera/accel_fps: -1
>* /camera/realsense2_camera/accel_frame_id: camera_accel_frame
> * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
>* /camera/realsense2_camera/align_depth: True
> * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
> * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_aligned_de...
> * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_aligned_de...
> * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
> * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
> * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
> * /camera/realsense2_camera/allow_no_texture_points: False
> * /camera/realsense2_camera/base_frame_id: camera_link
> * /camera/realsense2_camera/calib_odom_file:
> * /camera/realsense2_camera/clip_distance: -2.0
> * /camera/realsense2_camera/color_fps: -1
> * /camera/realsense2_camera/color_frame_id: camera_color_frame
> * /camera/realsense2_camera/color_height: -1
> * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
> * /camera/realsense2_camera/color_width: -1
> * /camera/realsense2_camera/confidence_fps: -1
> * /camera/realsense2_camera/confidence_height: -1
> * /camera/realsense2_camera/confidence_width: -1
> * /camera/realsense2_camera/depth_fps: -1
> * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
> * /camera/realsense2_camera/depth_height: -1
> * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
> * /camera/realsense2_camera/depth_width: -1
> * /camera/realsense2_camera/device_type:
> * /camera/realsense2_camera/enable_accel: False
> * /camera/realsense2_camera/enable_color: True
> * /camera/realsense2_camera/enable_confidence: True
> * /camera/realsense2_camera/enable_depth: True
> * /camera/realsense2_camera/enable_fisheye1: False
> * /camera/realsense2_camera/enable_fisheye2: False
> * /camera/realsense2_camera/enable_fisheye: False
> * /camera/realsense2_camera/enable_gyro: False
> * /camera/realsense2_camera/enable_infra1: False
> * /camera/realsense2_camera/enable_infra2: False
> * /camera/realsense2_camera/enable_infra: False
> * /camera/realsense2_camera/enable_pointcloud: True
> * /camera/realsense2_camera/enable_pose: False
> * /camera/realsense2_camera/enable_sync: True
> * /camera/realsense2_camera/filters:
> * /camera/realsense2_camera/fisheye1_frame_id: camera_fisheye1_f...
> * /camera/realsense2_camera/fisheye1_optical_frame_id: camera_fisheye1_o...
> * /camera/realsense2_camera/fisheye2_frame_id: camera_fisheye2_f...
> * /camera/realsense2_camera/fisheye2_optical_frame_id: camera_fisheye2_o...
> * /camera/realsense2_camera/fisheye_fps: -1
> * /camera/realsense2_camera/fisheye_frame_id: camera_fisheye_frame
> * /camera/realsense2_camera/fisheye_height: -1
> * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
> * /camera/realsense2_camera/fisheye_width: -1
> * /camera/realsense2_camera/gyro_fps: -1
> * /camera/realsense2_camera/gyro_frame_id: camera_gyro_frame
> * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
> * /camera/realsense2_camera/imu_optical_frame_id: camera_imu_optica...
> * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
> * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
> * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
> * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
> * /camera/realsense2_camera/infra_fps: 30
> * /camera/realsense2_camera/infra_height: 480
> * /camera/realsense2_camera/infra_rgb: False
> * /camera/realsense2_camera/infra_width: 848
> * /camera/realsense2_camera/initial_reset: True
> * /camera/realsense2_camera/json_file_path:
> * /camera/realsense2_camera/linear_accel_cov: 0.01
> * /camera/realsense2_camera/odom_frame_id: camera_odom_frame
> * /camera/realsense2_camera/ordered_pc: False
> * /camera/realsense2_camera/pointcloud_texture_index: 0
> * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
> * /camera/realsense2_camera/pose_frame_id: camera_pose_frame
> * /camera/realsense2_camera/pose_optical_frame_id: camera_pose_optic...
> * /camera/realsense2_camera/publish_odom_tf: True
> * /camera/realsense2_camera/publish_tf: True
> * /camera/realsense2_camera/reconnect_timeout: 6.0
> * /camera/realsense2_camera/rosbag_filename:
> * /camera/realsense2_camera/serial_no:
> * /camera/realsense2_camera/stereo_module/exposure/1: 7500
> * /camera/realsense2_camera/stereo_module/exposure/2: 1
> * /camera/realsense2_camera/stereo_module/gain/1: 16
> * /camera/realsense2_camera/stereo_module/gain/2: 16
> * /camera/realsense2_camera/tf_publish_rate: 0.0
> * /camera/realsense2_camera/topic_odom_in: odom_in
> * /camera/realsense2_camera/unite_imu_method:
> * /camera/realsense2_camera/usb_port_id:
> * /camera/realsense2_camera/wait_for_device_timeout: -1.0
> * /rosdistro: melodic
> * /rosversion: 1.14.13

>NODES
> /camera/
>   realsense2_camera (nodelet/nodelet)
>    realsense2_camera_manager (nodelet/nodelet)
>
>ROS_MASTER_URI=http://zt-System-Product-Name:11311
>
>process[camera/realsense2_camera_manager-1]: started with pid [23923]
>process[camera/realsense2_camera-2]: started with pid [23924]
>[ INFO] [1691670080.640062880]: Initializing nodelet with 12 worker threads.
>[ INFO] [1691670080.716349953]: RealSense ROS v2.3.2
>[ INFO] [1691670080.716373915]: Built with LibRealSense v2.51.1
>[ INFO] [1691670080.716382074]: Running with LibRealSense v2.51.1
>[ INFO] [1691670080.730833353]:  
>[ INFO] [1691670080.847351938]: Device with serial number 108322071393 was found.
>
>[ INFO] [1691670080.847404495]: Device with physical ID /sys/devices/pci0000:00/0000:00:14.0/usb2/2-1/2->1:1.0/video4linux/video0 was found.
>[ INFO] [1691670080.847435931]: Device with name Intel RealSense D435I was found.
>[ INFO] [1691670080.847868396]: Device with port number 2-1 was found.
>[ INFO] [1691670080.847900245]: Device USB type: 3.2
>[ INFO] [1691670080.847938380]: Resetting device...
>[ INFO] [1691670086.938909205]:  
>[ INFO] [1691670087.053365423]: Device with serial number 108322071393 was found.
>
>[ INFO] [1691670087.053409254]: Device with physical ID /sys/devices/pci0000:00/0000:00:14.0/usb2/2-1/2->1:1.0/video4linux/video0 was found.
>[ INFO] [1691670087.053419639]: Device with name Intel RealSense D435I was found.
>[ INFO] [1691670087.053690394]: Device with port number 2-1 was found.
>[ INFO] [1691670087.053705543]: Device USB type: 3.2
>[ INFO] [1691670087.057145165]: getParameters...
>[ INFO] [1691670087.078606894]: setupDevice...
>[ INFO] [1691670087.078619145]: JSON file is not provided
>[ INFO] [1691670087.078625583]: ROS Node Namespace: camera
>[ INFO] [1691670087.078636238]: Device Name: Intel RealSense D435I
>[ INFO] [1691670087.078641563]: Device Serial No: 108322071393
>[ INFO] [1691670087.078648106]: Device physical port: /sys/devices/pci0000:00/0000:00:14.0/usb2/2-1/2->1:1.0/video4linux/video0
>[ INFO] [1691670087.078654937]: Device FW version: 05.13.00.50
>[ INFO] [1691670087.078661358]: Device Product ID: 0x0B3A
>[ INFO] [1691670087.078671691]: Enable PointCloud: On
>[ INFO] [1691670087.078677463]: Align Depth: On
>[ INFO] [1691670087.078683781]: Sync Mode: On
>[ INFO] [1691670087.078741356]: Device Sensors:
>[ INFO] [1691670087.083375407]: Stereo Module was found.
> 10/08 20:21:27,083 WARNING [140580471084800] (backend-v4l2.cpp:1444) Pixel format 36315752-1a66-a242-9065-d01814a >likely requires patch for fourcc code RW16!
>[ INFO] [1691670087.094883396]: RGB Camera was found.
>[ INFO] [1691670087.095241269]: Motion Module was found.
>[ INFO] [1691670087.095258044]: (Confidence, 0) sensor isn't supported by current device! -- Skipping...
>[ INFO] [1691670087.096097515]: Add Filter: pointcloud
>[ INFO] [1691670087.097959540]: num_filters: 2
>[ INFO] [1691670087.097977212]: Setting Dynamic reconfig parameters.
>[ WARN] [1691670087.403065453]: Param '/camera/rgb_camera/power_line_frequency' has value 3 that is not in the enum { >>{50Hz: 1} {60Hz: 2} {Disabled: 0} }. Removing this parameter from dynamic reconfigure options.
[> INFO] [1691670087.411086089]: Done Setting Dynamic reconfig parameters.
>[ INFO] [1691670087.411676717]: depth stream is enabled - width: 848, height: 480, fps: 30, Format: Z16
>[ INFO] [1691670087.412837660]: color stream is enabled - width: 1280, height: 720, fps: 30, Format: RGB8
>[ INFO] [1691670087.414236381]: setupPublishers...
>[ INFO] [1691670087.416081785]: Expected frequency for depth = 30.00000
>[ INFO] [1691670087.441834841]: Expected frequency for color = 30.00000
>[ INFO] [1691670087.449782549]: Expected frequency for aligned_depth_to_color = 30.00000
>[ INFO] [1691670087.456295817]: setupStreams...
>[ INFO] [1691670087.519406711]: SELECTED BASE:Depth, 0
>[ INFO] [1691670087.539117316]: RealSense Node Is Up!
>[ WARN] [1691670087.603168344]:
>malloc(): memory corruption
>[camera/realsense2_camera_manager-1] process has died [pid 23923, exit code -6, cmd /opt/ros/melodic/lib/nodelet/nodelet >manager __name:=realsense2_camera_manager __log:=/home/zt/.ros/log/c0d8fb8a-3777-11ee-9672-581122d9af9c/camera->realsense2_camera_manager-1.log].
>log file: /home/zt/.ros/log/c0d8fb8a-3777-11ee-9672-581122d9af9c/camera-realsense2_camera_manager-1*.log
>[camera/realsense2_camera-2] process has finished cleanly
>log file: /home/zt/.ros/log/c0d8fb8a-3777-11ee-9672-581122d9af9c/camera-realsense2_camera-2*.log
>all processes on machine have died, roslaunch will exit
>shutting down processing monitor...
>... shutting down processing monitor complete
>done

After I change the librealsense SDK to 2.51.1 and camera firmware version to 5.13.0.50, I cannot got the right execution of `roslaunch realsense2_camera rs_camera.launch initial_reset:=true` with a different error. Then I open the folder of ROS1 wrapper and type `catkin_make`, then I can got the **Malloc(): memory corruption** as before.
So do you have any suggestion for me to solve the error of **Malloc(): memory corruption** ? Any suggestion will be very helpful!

**Comment by MartyG-RealSense** [comment]
This next suggestion may not be directly related to your yolox problem but is worth noting.  The log warning **Pixel format ... likely requires patch for fourcc code RW16!** indicates that your computer's 5.4 kernel may not have had a librealsense **patch** applied to it if librealsense was built from source code.  The patch enables librealsense to provide **hardware metadata** and can make the librealsense build more stable.

If librealsense was built from source code and kernel 5.4 has not been patched then it can be patched by running a librealsense patch script called `./scripts/patch-realsense-ubuntu-lts.sh`

*******

I also note that you are using ROS1 Melodic but the only branch of YOLOX-ROS that apparently supports ROS1 is a **Noetic** one and the rest support ROS2 branches Foxy and Humble (which is its default branch).

https://github.com/Ar-Ray-code/YOLOX-ROS/tree/noetic

In addition, it requires a computer with an **Nvidia** graphic GPU (such as an Nvidia Jetson computing board) so that it can use **CUDA**.  

I could not find in the instructions the **rosrun yolox_ros** command that you used.  The ROS1 instructions instead suggest using a **roslaunch** instruction to activate it, such as `yolox_ros_py demo_yolox_s.launch`

https://github.com/Ar-Ray-code/YOLOX-ROS/tree/noetic#demo 

I peformed a search on the internet for the exact term "rosrun yolox_ros" and there were no results, suggesting that it is not a usual method of launching a yolox script.

**Comment by qiyueliuhuo23** [comment]
Thanks for giving me several suggestions. After 2 days effort, I rollback the version of my project with no errors.  Because the project works fine with no errors at first, but someone not me changed the msg and the Malloc error appears. 
**This experience told us the importance of version controll.** 
Anyway, thanks for your answers @MartyG-RealSense, I appreciate those advices and wish you have a good day!

**Comment by MartyG-RealSense** [comment]
You are very welcome, @qiyueliuhuo23 - thanks very much for the update!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
