### ISSUE TITLE
Point cloud not published in rs_camera file

### ISSUE THREAD

**Issue by furkancetiny** [realsenseai/realsense-ros#2848]
I can't get pointcloud output even though I set `enable_pointcloud=true` in rs_camera file. Can you help about the reason?

System: Ubuntu 20.04 (Jetson Nano Orin)
ROS_DISTRO: Noetic

**Comment by MartyG-RealSense** [comment]
Hi @furkancetiny  Is a pointcloud generated if you set it as a **filter** in the rs_camera.launch roslaunch instruction, please?

`roslaunch realsense2_camera rs_camera.launch filters:=pointcloud`

**Comment by furkancetiny** [comment]
Unfortunately, it did not form a point cloud. Issue `/camera/color/image_raw`  stopped publishing

**Comment by MartyG-RealSense** [comment]
If enabling a pointcloud in rs_camera.launch is not working then an alternative method of generating one in ROS1 is an **RGBD** launch.

To perform this type of launch, support for it in Noetic must be installed with the command below.

`sudo apt-get install ros-noetic-rgbd-launch`

Once the support is installed, use the **rs_rgbd.launch** file, which has pointcloud enabled by default.

`roslaunch realsense2_camera rs_rgbd.launch `

The pointcloud will be published at **depth_image_proc**

**Comment by furkancetiny** [comment]
A topic named `camera/depth_registered/points` has been published, but I couldn't get a printout in the rviz environment.

**Comment by MartyG-RealSense** [comment]
So you are unable to view `camera/depth_registered/points` if you set it as the topic in RViz like in https://github.com/IntelRealSense/realsense-ros/issues/553

What is your librealsense SDK and RealSense ROS1 wrapper versions please?  It should be librealsense **2.51.1** and ROS1 wrapper **2.3.2**.  The camera firmware driver version should be **5.13.0.50**.

**Comment by furkancetiny** [comment]
I'm working on the rtabmap package. For this package I need the `/camera/color/image_raw` and `/camera/depth/color/points` topics. When one topic publish, the other does not. But I want both to stream.


ROS version: 2.3.2
Librealsense version: 2.50.0
Driver version: 5.13.00.50

**Comment by MartyG-RealSense** [comment]
2.50.0 and firmware 5.13.0.50 are fine for use with wrapper 2.3.2.

What happens if you launch **opensource_tracking.launch**?  This launch file has settings for rtabmap and also imports the settings of rs_camera, making it two launch files in one.

`roslaunch realsense2_camera opensource_tracking.launch filters:=pointcloud`

**Comment by MartyG-RealSense** [comment]
Hi @furkancetiny  Do you require further assistance with this case, please?  Thanks!

**Comment by furkancetiny** [comment]
I'm sorry for the late reply. `roslaunch realsense2_camera opensource_tracking.launch filters:=pointcloud` When I ran this command, I was able to get pointcloud output via `/voxel_cloud`. 

I don't need help right now. Thank you.

**Comment by MartyG-RealSense** [comment]
It's no problem at all.  I'm pleased to hear that you were able to achieve a pointcloud.  As you do not requre further assistance, I will close this case.  Thanks again!
