### ISSUE TITLE
Is a D455 depth image aligned with its corresponded undistorted color image or the original color image?

### ISSUE THREAD

**Issue by yanmingzou** [realsenseai/realsense-ros#2867]
On D455, the published RGB color images are with distortions.  If the parameter align_depth.enable is set true, what are the images the depth images are aligned with? The published color image or the un-distorted color image? Thanks a lot.

**Comment by MartyG-RealSense** [comment]
Hi @yanmingzou  On D455 the depth image will be aligned with the image from the RGB sensor that is published on the color topic and has a distortion model applied to it.

**Comment by yanmingzou** [comment]
Thanks Marty.
So if I undistort the color image, I also need to undistort the depth image to keep the pixel correspondence between color and depth image. Am I right?

**Comment by MartyG-RealSense** [comment]
If align_depth is used then librealsense's **align processing block** will automatically adjust for differences between the depth and color streams when the two streams are mapped together into a single aligned image.

**Comment by MartyG-RealSense** [comment]
Hi @yanmingzou  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further commemts received.
