### ISSUE TITLE
Does D455 support to change publish frequency of a given topic?

### ISSUE THREAD

**Issue by Eric-Ho-Matrix** [realsenseai/realsense-ros#2871]
Hey, is that possible to change /camera/infra2/image_rect_raw topic publish frequency?
This topic is now published as about 30 Hz, I want to reduce to about 15 Hz.

**Comment by MartyG-RealSense** [comment]
Hi @Eric-Ho-Matrix  If you are using ROS1 then you could define a custom configuration for infra2 in the roslaunch instruction.  For example:

`roslaunch realsense2_camera rs_camera.launch infra2_width:=640 infra2_height:=480 infra2_fps:=15`

If you are using ROS2 then use the launch instruction below to set depth, infra1 and infra2 to 15 FPS, as it uses a different stream customization mechanism to the ROS1 wrapper.  For example:

`ros2 launch realsense2_camera rs_launch.py depth_module.profile:=640x480x15`

**Comment by MartyG-RealSense** [comment]
Hi @Eric-Ho-Matrix  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
