### ISSUE TITLE
Cannot run the camera node.

### ISSUE THREAD

**Issue by leelening** [realsenseai/realsense-ros#2885]
Get the following error when run `roslaunch realsense2_camera rs_camera.launch`
![image](https://github.com/IntelRealSense/realsense-ros/assets/8867086/ece25589-4497-4551-bf45-ad2d1c8c4b94)

**Comment by MartyG-RealSense** [comment]
Hi @leelening   There is a past case of the **Make sure that you are calling the pluginlib_export_class macro** error at https://github.com/IntelRealSense/realsense-ros/issues/2216

RealSense users who commented on that case seemed to be having a problem with more than one version of librealsense installed on their computer.  Performing a removal and then a reinstall of librealsense 2.50.0 fixed the problem (using librealsense 2.51.1 should be fine too).  If you are using Noetic then the ROS wrapper version used with 2.50.0 or 2.51.1 should be **2.3.2**.

**Comment by leelening** [comment]
I think my case is that I installed the latest version (2.54) instead of 2.50.0. Now it works.

**Comment by MartyG-RealSense** [comment]
That's excellent news that it is working now, @leelening - thanks very much for the update!

**Comment by leelening** [comment]
When I install 2.50.0, I do not have the librealsense2-utils installed. Correct me if I am wrong, but the realsense-viewer is included in that package. When I try to install librealsense2-utils=2.50.0, it seems that that dependency is 2.54 of librealsense2.

**Comment by MartyG-RealSense** [comment]
Whether you have realsense-viewer or not depends on the method that was used to install librealsense.

When installing librealsense from packages, the tools and examples (including realsense-viewer) are installed when the utils package is installed with the instruction `sudo apt-get install librealsense2-utils`

When building librealsense from source code with CMake, realsense-viewer will be included in the SDK build if the CMake build instruction contains the flag `-DBUILD_GRAPHICAL_EXAMPLES=TRUE`

If librealsense 2.50.0 and the ROS1 wrapper are installed from packages at the same time using the instruction `sudo apt-get install ros-$ROS_DISTRO-realsense2-camera` then realsense-viewer is not included in the librealsense installation.
