### ISSUE TITLE
how to get position from the l515

### ISSUE THREAD

**Issue by naorwaiss** [realsenseai/realsense-ros#2887]
hi, i got L515 and try to get position from this camera to connect is to my drone 
i try use ros2 but i didn`t find topic that provide me pos data or the imu data at list 
thanks 

```
/opt/ros/foxy/bin/ros2:6: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  from pkg_resources import load_entry_point
/camera/color/camera_info
/camera/color/image_raw
/camera/color/metadata
/camera/depth/camera_info
/camera/depth/color/points
/camera/depth/image_rect_raw
/camera/depth/metadata
/camera/extrinsics/depth_to_color
/camera/infra/camera_info
/camera/infra/image_raw
/camera/infra/metadata
/parameter_events
/rosout
/tf
/tf_static
```

**Comment by MartyG-RealSense** [comment]
Hi @naorwaiss  The IMU topics are disabled by default in the RealSense ROS wrapper.  To enable and publish them to the **/imu** topic, please try the launch instruction below.

`ros2 launch realsense2_camera rs_launch.py enable_gyro:=true enable_accel:=true unite_imu_method:=2`

**Comment by naorwaiss** [comment]
i try to find it at ```ros2 topic list``` and didnt find it 
at the rviz2 nothing is move 
can help with this ?

**Comment by MartyG-RealSense** [comment]
The IMU topic published when using the unite_imu_method parameter should be **/camera/imu**

Are the separate 'gyro' and 'accel' topics listed?

**Comment by MartyG-RealSense** [comment]
Hi @naorwaiss  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
