### ISSUE TITLE
Unable to get Aligned Point cloud even when Aligned depth is enabled.

### ISSUE THREAD

**Issue by minku1219** [realsenseai/realsense-ros#2896]
Hi, I am working on a pose estimation pipeline and it requires a Ordered Pointcloud aligned with rgb.
While using realsense d435 and d455 i have observed that when enabling the ordered_pc flag to true it gives point cloud that is not aligned to rgb.
I have attached a screenshot which mentions that when using aligned depth you will get the pointcloud in fram of aligned depth. But mine is shifted.

Any help is appreciated @RealSenseSupport  
![Screenshot from 2023-10-06 13-17-58](https://github.com/IntelRealSense/realsense-ros/assets/68742521/dc486950-6111-422c-aa8a-d8f62b129ac1)

**Comment by MartyG-RealSense** [comment]
Hi @minku1219  Is a depth-color aligned pointcloud generated correctly with ordered_pc = true if you do **not** use align_depth:=true?  RGB should be mapped to a depth pointcloud when RGB is enabled and the pointcloud filter is used.

`ros2 launch realsense2_camera rs_launch.py depth_module.profile:=1280x720x30 rgb_camera.profile:=1280x720x30 pointcloud.enable:=true pointcloud.ordered_pc:=true`

**Comment by adamwhats** [comment]
Looks like this the same issue as #2595?

**Comment by MartyG-RealSense** [comment]
@adamwhats  The case of @minku1219 does look similar to https://github.com/IntelRealSense/realsense-ros/issues/2595 though the RealSense ROS developer team created a fix for the alignment issue in that case - see https://github.com/IntelRealSense/realsense-ros/pull/2775

However, the RealSense user in that case did not provide feedback about whether the fix had resolved their issue.

**Comment by MartyG-RealSense** [comment]
Hi @minku1219  Do you have an update about this case that you can provide, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Hi @minku1219 and @adamwhats  Do either of you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
