### ISSUE TITLE
Dropping of depth frames within few seconds

### ISSUE THREAD

**Issue by minku1219** [realsenseai/realsense-ros#2897]
Hi,
I am using realsense d415 and d455 for my ros2 applications.
While working with the camera, I have observed that the depth frames does'nt seems to appear after 2-3 minutes itself.

My current SDK version is 2.54.1
And ROS Wrapper is 4.54.1
Ubuntu 22.04
ROS2 Humble

**Comment by MartyG-RealSense** [comment]
Hi @minku1219  Does performance improve if you add **initial_reset:=true** to your launch instruction to reset the camera at launch, please?

**Comment by MartyG-RealSense** [comment]
Hi @minku1219  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
