### ISSUE TITLE
Camera stops publishing frame due to an unknown issue

### ISSUE THREAD

**Issue by minku1219** [realsenseai/realsense-ros#2898]
Hi,
I am using d415 and d455 for my ros2 applications
I have faced an unknown error and due to which my camera stops working.
this error comes after subscribing to frames 3-4 times.
After 3 or 4 subscription this error comes and camera stops publishing frames.
There seems to be no data when visualizing in RQT and even when doing topic echo.
![WhatsApp Image 2023-10-06 at 1 21 23 PM](https://github.com/IntelRealSense/realsense-ros/assets/68742521/b3c2ee6f-ae5c-4bbd-bfbf-b9dabffb3afc)

Ubuntu 22.04
ROS2 humble
SDK verison 2.54.1
ROS Wrapper version 4.54.1

**Comment by MartyG-RealSense** [comment]
Hi @minku1219  I note from the log that the warning **Given stream configuration is not supported by the device** occurs a couple of times when the publishing of the streams is being initiated and it rejects the configuration and uses the default stream settings of the camera instead.  This suggests that a custom stream configuration was defined but the launch decided that it was invalid.

What happens please if you use the launch instruction below?

`ros2 launch realsense2_camera rs_launch.py depth_module.profile:=640x480x30 rgb_camera.profile:=640x480x30`

If **depth_module.profile** is defined then it should enable the depth stream and the infrared streams.  **rgb_camera.profile** enables the RGB stream.

**Comment by MartyG-RealSense** [comment]
Hi @minku1219   Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
