### ISSUE TITLE
Add D400 support

### ISSUE THREAD

**Issue by AndyZe** [realsenseai/realsense-ros#290]
Is there any plan to add D400 support? Would like to know before buying one.

**Comment by icarpis** [comment]
Hello @AndyZe, [RealSense ROS 2.0](https://github.com/intel-ros/realsense/releases/tag/2.0.1) supports Intel RealSense [D415](https://click.intel.com/intelr-realsensetm-depth-camera-d415.html) and [D435](https://click.intel.com/intelr-realsensetm-depth-camera-d435.html) cameras.

**Comment by AndyZe** [comment]
OK, cool. You guys might want to update the [wiki](http://wiki.ros.org/RealSense) and your [forum](https://communities.intel.com/message/514554#514554). I don't think anybody knows about the ROS support atm.
