### ISSUE TITLE
[ROS2] D455 unable to start with depth auto exposure when outdoors

### ISSUE THREAD

**Issue by drapado** [realsenseai/realsense-ros#2907]
Hi using this command:
```bash
ros2 launch realsense2_camera rs_launch.py serial_no:="'318122302162'" camera_name:=D455_top initial_reset:=true enable_color:=true enable_depth:=true depth_module.enable_auto_exposure:=true pointcloud.enable:=true depth_module.profile:=848x480x30 rgb_camera.profile:=848x480x30 pointcloud.ordered_pc:=true align_depth.enable:=true  depth_module.hdr_enabled:=true
```
both of my D455 cameras don't start in depth auto-exposure mode when outdoors (they do when indoors). The infrared images are completely overblown. I also get this warning: `[realsense2_camera_node-1] [WARN] [1697538565.749702035] [D455_top.D455_top]: re-enable the stream for the change to take effect.`

How can I solve it?

**Comment by MartyG-RealSense** [comment]
Hi @drapado  The launch command that you used did not display in the opening message above.  Could you repeat it please?  Thanks!

**Comment by drapado** [comment]
Hi, I updated the original message (I forgot to add a new line before the actual code). You should see it now.

**Comment by MartyG-RealSense** [comment]
Thanks very much for the update!

I note that you have **hdr_enabled** set to true.  If HDR is true then auto-exposure becomes false, as auto-exposure cannot be used with HDR mode.  

Perhaps auto-exposure also becomes false indoors but it is not as noticable indoors under artificial lighting as it would be outdoors in variable lighting conditions.

**Comment by drapado** [comment]
It also happens while using `depth_module.hdr_enabled:=false`. 

I was using `depth_module.hdr_enabled:=true` as a workaround that I found to partially solve the issue. The work around is:
1. If I'd first run the node with hdr enabled (original shared command), I'd see a quick continuous switching between a overexposed depth (default exposure 7500) and good quality depth (default second exposure 1). Those are the default values at [rs_launch.py](https://github.com/IntelRealSense/realsense-ros/blob/8834e3491bbd9c82b310e9eff9bda69ed023b469/realsense2_camera/launch/rs_launch.py#L52) lines 52 and 54
2. Cancel the previous launch node and run it again with hdr disabled:
```bash
ros2 launch realsense2_camera rs_launch.py serial_no:="'318122302162'" camera_name:=D455_top initial_reset:=true enable_color:=true enable_depth:=true depth_module.enable_auto_exposure:=true pointcloud.enable:=true depth_module.profile:=848x480x30 rgb_camera.profile:=848x480x30 pointcloud.ordered_pc:=true align_depth.enable:=true  depth_module.hdr_enabled:=false
```
Using this workaround, sometimes I'd get a good auto-exposure after the second step.

In the end, for consistency I enabled manual exposure for both cameras:
```bash
ros2 launch realsense2_camera rs_launch.py serial_no:="'318122302162'" camera_name:=D455_top initial_reset:=true enable_color:=true enable_depth:=true depth_module.enable_auto_exposure:=false pointcloud.enable:=true depth_module.profile:=848x480x15 rgb_camera.profile:=848x480x15 pointcloud.ordered_pc:=true align_depth.enable:=true  depth_module.exposure:=120
```

**Comment by MartyG-RealSense** [comment]
Thanks very much for your detailed feedback.  Given that HDR mode does not use auto-exposure because it alternates between two different exposure values, using manual exposure is the most suitable approach.

**Comment by drapado** [comment]
Hi @MartyG-RealSense, re-tested indoors right now. The depth auto_exposure mode doesn't start automatically as it should. After using the following command:
```bash
ros2 launch realsense2_camera rs_launch.py serial_no:="'318122302479'" \
camera_name:=D455_bottom \
initial_reset:=true \
enable_color:=true \
enable_depth:=true \
depth_module.enable_auto_exposure:=true \
pointcloud.enable:=true \
depth_module.profile:=848x480x30 \
rgb_camera.profile:=848x480x30 \
pointcloud.ordered_pc:=true \
align_depth.enable:=true
```

If I run `ros2 param get /D455_bottom/D455_bottom depth_module.auto_exposure_mode`, I get `Boolean value is: False`.

This shouldn't be happening right?

**Comment by MartyG-RealSense** [comment]
That is correct, if `depth_module.enable_auto_exposure:=true` is used in the launch instruction then depth auto-exposure should be enabled after launch has completed.

Auto-exposure can disable automatically if HDR mode is enabled or the exposure or gain value is changed.

**Comment by drapado** [comment]
Any idea on how can this be solved? Is there a parameter wrongly configured in the default rs_launch.py? I believe HDR is disabled by default

**Comment by MartyG-RealSense** [comment]
There is not anything in rs_launch.py that should be disabling auto-exposure (which is enabled by default) and HDR is disabled by default.  

https://github.com/IntelRealSense/realsense-ros/blob/ros2-development/realsense2_camera/launch/rs_launch.py#L51

What is the auto-exposure status from **ros2 param get** if you launch with **ros2 run** instead of a launch file, please?

`ros2 run realsense2_camera realsense2_camera_node --ros-args -p initial_reset:=true -p depth_module.enable_auto_exposure:=true -p serial_no:="'318122302479'"`

**Comment by drapado** [comment]
I'll try it this evening or tomorrow morning. I don't have the cameras with me right now.

**Comment by MartyG-RealSense** [comment]
Okay, thanks very much for the update.  I look forward to your next report.  Good luck!

**Comment by drapado** [comment]
Using
```bash
ros2 run realsense2_camera realsense2_camera_node --ros-args -p initial_reset:=true -p depth_module.enable_auto_exposure:=true -p serial_no:="'318122302479'"
```
also launch with auto-exposure disable. Running:
```bash
ros2 param get /camera depth_module.auto_exposure_mode
```
also returns: `Boolean value is: False`

**Comment by MartyG-RealSense** [comment]
Have you tried using **param set** instead of param get to set auto_exposure_enabled to true?

`ros2 param set /camera depth_module.auto_exposure_enabled 1`

**Comment by drapado** [comment]
Running the provide command doesn't work:
```bash
> ros2 param set /camera depth_module.auto_exposure_enabled 1
Setting parameter failed: parameter 'depth_module.auto_exposure_enabled' cannot be set because it was not declared
```

If I run the following:
```bash
> ros2 param set /camera depth_module.auto_exposure_mode true
Set parameter successful
```
However, in the terminal running the node I get:
```bash
Failed to set value: setting this option during streaming is not allowed!
```
Using 1 instead of true doesn't work:
```bash
Failed to set value: parameter 'depth_module.auto_exposure_mode' has invalid type: expected [bool] got [integer]
Failed to set value: setting this option during streaming is not allowed!
```

**Comment by MartyG-RealSense** [comment]
Thank you for the information.

Next, please try holding your hand over the front of the D455 to block its lenses when you are launching it.  This will help to eliminate the possibility that something in the environment is causing the auto-exposure to disengage when launch has completed.

**Comment by drapado** [comment]
Still, both of my D455 start with depth auto-exposure disabled when a hand is in front of the lens

**Comment by MartyG-RealSense** [comment]
There was a past case at https://github.com/IntelRealSense/realsense-ros/issues/2507#issuecomment-1411214372 where auto-exposure was disabled in the ROS2 wrapper.  A RealSense team member investigated it and found that a **depth_module.exposure.1** line in the rs_launch.py launch file that set depth exposure to '1' was disabling auto-exposure at launch.  This is because when a manual exposure value is set, auto-exposure automatically disables.

https://github.com/IntelRealSense/realsense-ros/blob/ros2-development/realsense2_camera/launch/rs_launch.py#L52

The RealSense team member discusses this at https://github.com/IntelRealSense/realsense-ros/issues/2507#issuecomment-1411214372

They suggested in that past case to try the following launch command:

`ros2 run realsense2_camera realsense2_camera_node --ros-args -p enable_color:=true -p enable_infra1:=false -p enable_infra2:=false`

**Comment by drapado** [comment]
Thanks for the information, unfortunately that command doesn't solve the issue neither.

The other issue is still open, was it solved?

**Comment by MartyG-RealSense** [comment]
That past issue is closed because the commenters on it were satisfied that they did not require further assistance.

**Comment by MartyG-RealSense** [comment]
Hi @drapado  Has there been any progress made with this problem or do you require further assistance, please?  Thanks!

**Comment by drapado** [comment]
Can you replicate the issue?

**Comment by MartyG-RealSense** [comment]
I am not able to replicate the issue, unfortunately.

**Comment by drapado** [comment]
Hi @MartyG-RealSense, then I'm closing the issue for now. I'll create a clean ubuntu install and try again. If the issue persist, or if I gain further insights into it I'll re-open it.

Thanks for the help!

**Comment by MartyG-RealSense** [comment]
You are very welcome.  Thanks very much for your patience and understanding!
