### ISSUE TITLE
Wifi not working once realsense node starts

### ISSUE THREAD

**Issue by AnveshSK** [realsenseai/realsense-ros#2910]
@MartyG-RealSense 

My plan is to use VIO using IntelRealsense - D435i. i use realsense-ros for the images and imu data. I have my custom launch file using which I access the infra and imu data. I use ssh to connect to my xavier over personal hotspot. But the moment I run realsense-ros, the ssh freezes i.e. the wifi disconnects. But if I disconnect the d435i or stop realsense-ros launch file, the ssh works again i.e. the wifi reconnects.

My streams are:
Infra1
infra2
Imu (linear interpolation)

I use, 
Libsense - 2.48.0
Built using 
"Building from Source using Native Backend" and with this issue as reference "Unable to read IMU data on the D435i
#10304"
realsense-ros - 2.3.1

System details:
Companion = Xavier NX 
Release = 4.9.201-tegra
L4T = 32.5.2
Jetpack = 4.5.1
OpenCV : 3.4.1 built with CUDA (10.2.89)

**Comment by MartyG-RealSense** [comment]
Hi @AnveshSK  If your wi-fi hardware makes use of infrared then the RealSense camera could be interfering with it when enabled.  400 Series cameras do not interfere with each other but can interfere with non-RealSense devices nearby that use infrared.  Past examples of interference have included an infrared sensor on a door control panel, a card reader and a wireless mouse adaptor.

**Comment by MartyG-RealSense** [comment]
Hi @AnveshSK  Do you require further assistance with this case, please?  Thanks!

**Comment by AnveshSK** [comment]
@MartyG-RealSense 
Yeah. You're correct as soon as I remove the wireless keyboard/mouse dongle, other usb3 connected devices work again.
Thanks

**Comment by AnveshSK** [comment]
@MartyG-RealSense
Yeah. You're correct as soon as I remove the wireless keyboard/mouse dongle, other usb3 connected devices work again.
Thanks

**Comment by MartyG-RealSense** [comment]
You are very welcome.  It's excellent to hear that removal of the wireless dongle resolved your issue.  Thanks very much for the update!
