### ISSUE TITLE
How do I add the installation prefix of librealsense2 to a catkin package? ROS/librealsense

### ISSUE THREAD

**Issue by benny-mt** [realsenseai/realsense-ros#2932]
Hi! I'm new to ROS and the such and I'm trying to create a catkin pkg that depends on librealsense. I can't wrap my head around how I can add this dependency to my package's CMakeLists.txt file.

I'm using Ubuntu 20.04 and ROS noetic

This is the error I get when I enter the "catkin_make" in my home/flickyicky/myNode directory.
```
-- Could NOT find librealsense2 (missing: librealsense2_DIR)
-- Could not find the required component 'librealsense2'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/noetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by "librealsense2"
  with any of the following names:

    librealsense2Config.cmake
    librealsense2-config.cmake

  Add the installation prefix of "librealsense2" to CMAKE_PREFIX_PATH or set
  "librealsense2_DIR" to a directory containing one of the above files.  If
  "librealsense2" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  myPkg/CMakeLists.txt:10 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/flickyicky/myNode/build/CMakeFiles/CMakeOutput.log".
See also "/home/flickyicky/myNode/build/CMakeFiles/CMakeError.log".
make: *** [Makefile:320: cmake_check_build_system] Error 1
Invoking "make cmake_check_build_system" failed

``` 

I know I have to add the installation prefix into the CMakeLists.txt file, however I don't know how to go about doing so.

I added librealsense2 to the find_package line like so:
```
find_package(catkin REQUIRED COMPONENTS roscpp rospy std_msgs genmsg librealsense2)
``` 
However, that doesn't seem to be enough. I assume I need to add the directory to librealsense on the CMakeLists file, that being
```
home/flickyicky/realsense
``` 
However I don't know how to go about it. What's the correct command? What specific folder inside realsense do I need to link? I've found X and Y syntax online from official documentation and from other people asking similar questions, however I don't really know what to use and how to use it.

**Comment by MartyG-RealSense** [comment]
Hi @benny-mt   https://github.com/IntelRealSense/librealsense/issues/4277#issuecomment-505242118 and https://github.com/IntelRealSense/realsense-ros/issues/303 may be helpful references.

**Comment by MartyG-RealSense** [comment]
Hi @benny-mt  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
