### ISSUE TITLE
ZR300 Data Sync Question

### ISSUE THREAD

**Issue by baloothebear** [realsenseai/realsense-ros#294]
Hi,

I am working with the ZR300 camera and using this ROS driver and I have a question about the data synchronization.

Specifically I am interested in using the color, depth and IMU sensors. 

Are the timestamps from the ROS messages of these sensors recorded with respect to the same clock on the device? I am referring to the timestamps reported in the header fields of the topics:

/camera/color/image_raw
/camera/depth/image_raw
/camera/imu/data_raw

 Otherwise, how is the synchronization done?

Thanks

**Comment by jlgarcia75** [comment]
Hello @baloothebear,

The sensors are synchronized to the same reference clock.  See the [ZR300 datasheet](https://www.intel.com/content/www/us/en/support/articles/000023563/emerging-technologies/intel-realsense-technology.html) for more information.

Regards,
Jesus
Intel Customer Support

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]
