### ISSUE TITLE
Ubable to transform PointCloud in rviz

### ISSUE THREAD

**Issue by Karin-Sugi** [realsenseai/realsense-ros#2974]
Hi, I'm trying to show PointCloud taken by fixed camera in rviz, but "Ubable to transform" is returned. I use realsense 435i and ros melodic.

In details, i placed two models (realsense camera and robot) in rviz. The camera detects robot's position with apriltag and all rocations are saved with tf2. I'd like to see PointCloud data with those models, but the rviz returns `Ubable to transform [/camera_depth_optical_frame] to [world]`.

However, when i check the tree with rqt, the `camera_depthoptical_frame` is connected to the `world` as you can see the image below...  Do you have any idea??
  
Actually, I've already checked both PointCloud is published correctly and all tf tree (including robot) is connected. Also, both works fine when i run it independently.

![Screenshot from 2024-01-17 21-24-42](https://github.com/IntelRealSense/realsense-ros/assets/79965944/e0284651-f9a4-42d9-962d-76d0dd36347d)

**Comment by MartyG-RealSense** [comment]
Hi @Karin-Sugi  Are you using the RealSense ROS wrapper launch file **rs_camera.launch** with Melodic please?

If you are using rs_camera,launch, what happens if you set the launch file parameter **publish_tf** to False by adding the command **publish_tf:=false** to your roslaunch instruction?

**Comment by Karin-Sugi** [comment]
Hi, thanks for your quick reply!

I set publish_tf false, but it doesn't work. My launch file is below. I run realsense by including `rs_camera.launch`. Also, both robot_description and camera_description are loaded by rviz.
```
<?xml version="1.0" encoding="UTF-8"?>
<launch>
  <!-- configure camera input -->
  <arg name="camera" default="camera" />
  <arg name="camera_name" default="/$(arg camera)/color" />
  <arg name="image_topic" default="image_raw" />
  <arg name="queue_size" default="1" />

  <!-- apriltag_ros continuous detection node -->
  <node pkg="apriltag_ros" type="apriltag_ros_continuous_node" name="apriltag_ros_continuous_node" clear_params="true" output="screen" launch-prefix="$(arg launch_prefix)">
    <!-- Remap topics -->
    <remap from="image_rect" to="$(arg camera_name)/$(arg image_topic)" />
    <remap from="camera_info" to="$(arg camera_name)/camera_info" />
    <param name="publish_tag_detections_image" type="bool" value="true" /><!-- default: false -->
    <param name="queue_size" type="int" value="$(arg queue_size)" />

    <!-- load parameters (incl. tag family, tags, etc.) -->
    <rosparam command="load" file="$(find hauser_localization)/config/settings.yaml"/>
    <rosparam command="load" file="$(find hauser_localization)/config/tags.yaml"/>
  </node>

 <!-- run realsense with point cloud -->
  <include file="$(find realsense2_camera)/launch/rs_camera.launch">
    <arg name="camera" value="$(arg camera)" />
    <arg name="filters" value="pointcloud"/>
    <arg name="publish_tf" value="false"/>
    <!-- <arg name="unite_imu_method" value="linear_interpolation"/>
    <arg name="enable_gyro" value="true"/>
    <arg name="enable_accel" value="true"/> -->
  </include>

  <!-- Show on rviz -->
  <include file="$(find hauser_viz)/launch/rviz/multi_robots.launch">
    <arg name="camera_name" value="$(arg camera_name)" />
  </include>
 
  <!-- Calcurate robot attitude -->
  <node pkg="hauser_localization" type="tags_center" name="tags_center" output="screen" />
  <node pkg="hauser_localization" type="tag2robot" name="tag2robot" output="screen" />

```

Actually, I found another strange message in rviz as you can see in following image. It says `Transform OK` and `Failed to transform`. What do they mean??
![Screenshot from 2024-01-18 11-23-35](https://github.com/IntelRealSense/realsense-ros/assets/79965944/f04874bb-7c47-4b14-a879-cc32de0938fb)
 to`

Thanks in advance,
Karin

**Comment by Karin-Sugi** [comment]
Hi, when i delete camera_description, new warning message was returned on terminal saying `[ WARN] [1705547684.766363468]: Invalid argument "/camera_depth_optical_frame" passed to canTransform argument source_frame in tf2 frame_ids cannot start with a '/' like:`.

The ` / ` on the top causes this problem? Then, how can i fix it?

**Comment by MartyG-RealSense** [comment]
I do not know the answers to these questions unfortunately as my knowledge of TF is limited, and I carried out extensive research but could not find much relevant information either.  I'm very sorry.

A person in a case with a non-RealSense camera at the link below suggested dealing with a missing transform between /world and /camera_depth_optical_frame by creating a **static transform publisher**.

https://groups.google.com/g/moveit-users/c/KCIPoSP3dB0/m/hkul9NqTBAAJ

**Comment by MartyG-RealSense** [comment]
Hi @Karin-Sugi  Bearing in mind the comment above, do you require further assistance with this case please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
