### ISSUE TITLE
D455 URDF

### ISSUE THREAD

**Issue by anath93** [realsenseai/realsense-ros#2975]
| Camera Model                       | D455                          
| Firmware Version                   |  5.15.1                         
| Operating System & Version |   Ubuntu 20.04  | 
| Kernel Version (Linux Only)    |  5.15-rt                                                                     
| Platform                                 | Nvidia Jetson Orin                           
| Librealsense SDK Version       |  2.55.0                                                    
| Segment			         | Robot                           
| ROS Distro			         |  Galactic                                         
| RealSense ROS Wrapper Version   |  4.54.1                                            

### Issue Description
I am trying to add D455 URDF to my model, but don't think the offsets are right, what is the origin point on this camera as camera link in rviz is show towards RGB sensor but considering that the offset is wrong, please see image below 

![image](https://github.com/IntelRealSense/realsense-ros/assets/130472005/6b11675e-0726-4f0e-8c50-3e31d3ba199b)

![image](https://github.com/IntelRealSense/realsense-ros/assets/130472005/9fce3625-1002-4d99-a80b-e9563a44e5b5)

![image](https://github.com/IntelRealSense/realsense-ros/assets/130472005/973056ed-d2cd-4568-a5ab-e8028310596a)

**Comment by MartyG-RealSense** [comment]
Hi @anath93  The origin of depth is the center-line of the left infrared sensor.  The physical position of the RGB sensor can differ though depending on the camera model.  

For example, on the D415 model the RGB sensor is on the right end of the front of the camera, and on D455 it is near to the center of the camera's front.  The left infrared sensor on D455 is on the right end.  

So the axes on the end of the camera in your image above represent the depth origin on D455.

<img width="399" alt="image" src="https://github.com/IntelRealSense/realsense-ros/assets/41145062/564333a2-b43d-4454-a058-7020e6824b04">

**Comment by anath93** [comment]
@MartyG-RealSense Is this red circled the origin for adding URDF ?

![image](https://github.com/IntelRealSense/realsense-ros/assets/130472005/5d835eae-c05e-41bf-b220-fcb706a37a38)

**Comment by MartyG-RealSense** [comment]
The circled sensor is the D455's RGB sensor.  camera_link is the left infrared sensor (on the end of the camera right-side on D455).

**Comment by anath93** [comment]
@MartyG-RealSense Thank you for confirming that, so this is below 

![image](https://github.com/IntelRealSense/realsense-ros/assets/130472005/34abbd73-af90-4fab-9d82-39f001578063)

Is it the middle of the camera or is there any offset from the glass ?

**Comment by MartyG-RealSense** [comment]
In the D455 URDF file, the origin of the **mesh** is stated as being between the two infrared camera axes.  As the right infrared sensor is on the left end, that position would likely correspond to the camera center.

https://github.com/IntelRealSense/realsense-ros/blob/ros2-development/realsense2_description/urdf/_d455.urdf.xacro#L76

**Comment by anath93** [comment]
@MartyG-RealSense Thank you !
