### ISSUE TITLE
Understanding signal processing of L515

### ISSUE THREAD

**Issue by Daya-AWR1642** [realsenseai/realsense-ros#2976]
Hi 
I had completed my experiment with L515 and wanted to understand the signal processing of L515. Still, unfortunately, very few publications used L515, and none of them explained the mathematical processing of Lidar Signal processing. 

I want the mathematical model reference 
can you please

**Comment by MartyG-RealSense** [comment]
Hi @Daya-AWR1642  There is not a mathematical reference available to precisely describe the signal processing of the L515 camera model.  However, the official User Guide PDF document for the L515 camera model  - **L515_User_Guide_v1.0.pdf** - may be a helpful reference to better understand the L515's principles.  It can be downloaded as a PDF from the link below.

https://support.intelrealsense.com/hc/en-us/articles/360051646094-Intel-RealSense-LiDAR-Camera-L515-User-Guide

**Comment by Daya-AWR1642** [comment]
Yeah, I knew this. Can you please suggest any IEEE papers, please

**Comment by MartyG-RealSense** [comment]
The most suitable IEEE paper referencing the L515 that I could find is this one:

https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=10122518

The fastest way to find all of the L515 sections of the paper is to do a find operation on the browser page for the search term 'l515'.

**Comment by Daya-AWR1642** [comment]
Haa, I have gone through this already. Anyway, thank you for your response. I'll try my own.

**Comment by Daya-AWR1642** [comment]
Hi,
I have a few doubts about L515
1) is this direct detection lidar or coherent detection lidar?
(I guess is direct detection)
2) can I assume L515 getting processed like 

![image](https://github.com/IntelRealSense/realsense-ros/assets/102849011/a80a5c01-5587-46eb-afba-f6d928c15eb5)
![image](https://github.com/IntelRealSense/realsense-ros/assets/102849011/5cf64ace-1ab5-45af-a03c-e255f00c0da5)
![image](https://github.com/IntelRealSense/realsense-ros/assets/102849011/7e1b12be-bc06-434f-9f20-14123f9ed969)
![image](https://github.com/IntelRealSense/realsense-ros/assets/102849011/9a4e7288-3c8c-4bdb-8bb9-6985a7a2f10e)
![image](https://github.com/IntelRealSense/realsense-ros/assets/102849011/7c04d5d2-96a6-443b-b195-749552e43906)

**Comment by MartyG-RealSense** [comment]
Detailed information about the operating principles of the L515 model (which is now retired from the RealSense product range) is not available and so it is unfortunately not possible to provide confident answers to the above questions.

However, the L515 data sheet document provides the following description:

"The MEMS is used to scan the IR laser beam over the entire field of view (FOV).  The L515 vision ASIC will process the data from the reflected beam captured by the photodiode and will output a depth point representing the accurate distance of a specific point in the scene from the camera".

This description makes it sound like L515 is based on **direct** detection (measuring amplitude changes of the reflected light) rather than coherent (measuring changes in the phase of the reflected light).  I do not have the technical information to confirm this for certain though.

**Comment by MartyG-RealSense** [comment]
Hi @Daya-AWR1642  Do you require further assistance with this case, please?  Thanks!

**Comment by Daya-AWR1642** [comment]
No thank you, our team completed and submitted a research paper with L515.
And Special thank you for assisting each time.

**Comment by MartyG-RealSense** [comment]
You are very welcome.  I'm pleased that I could help.  Thanks very much for the update!

**Comment by ram-bhaskara** [comment]
Is L515 a direct or indirect time of flight sensor?

**Comment by MartyG-RealSense** [comment]
@ram-bhaskara  To quote the official data sheet document for L515:

*********

L515 has a MEMS, an IR photodiode, an RGB imager, a MEMS controller, and a vison ASIC.  The MEMS is used to scan the IR laser beam over the entire field of view (FOV).  The L515 vision ASIC will process the data from the reflected beam captured by the photodiode and will output a depth point representing the accurate distance of a specific point in the scene from the camera.

**********

It sounds as though it meets the definition of a direct lidar in the diagrams above.

**Comment by ram-bhaskara** [comment]
L515 is a DToF sensor: https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=10122518&tag=1
They too talk about pulse repetition rate: https://www.mouser.com/datasheet/2/612/Intel_RealSense_LiDAR_L515_Datasheet_Rev002-1713847.pdf?srsltid=AfmBOoqhvM40GX4ZP0t6wMS5b2aWtmTumu-ZiJHV7Qdqpt78lL24Kmz6

**Comment by MartyG-RealSense** [comment]
Thanks very much @ram-bhaskara for the link to the IEEE paper.
