### ISSUE TITLE
realsense-ros-2.3.1 not building on raspi-4

### ISSUE THREAD

**Issue by ta-jetson** [realsenseai/realsense-ros#2978]
----------------------------------------------------------------------------------------------------

| Required Info                         |                                                                |
|---------------------------------|------------------------------------------- |
| Camera Model                       | { D400, T200 } | 
| Operating System & Version |   Linux (Ubuntu 20) | 
| Kernel Version (Linux Only)    |  5.4.0-1100-raspi                                        | 
| Platform                                 |Raspberry Pi -4 model B+ |
| SDK Version                            |  2.48.0                        |  
|ROS           | Noetic |

### Issue Description

Hey @MartyG-RealSense , 
Hope you're doing well.
I am trying to build realsense-ros 2.3.1 and librealsense 2.48.0 to use my realsense cameras [D435i and T265] on raspi-4. While the librealsense worked and I can successfully use my realsense-viewer as well as pyrealsense2 (thanks to your help with my issue  : Not able to use pyrealsense2. "No Module named pyrealsense2" #12377 ).
Building realsense-ros-2.3.1 has issues. These are the steps I followed :

mkdir ~/catkin_realsenseros_ws/src
cd ~/catkin_realsenseros_ws/src

Here I extracted the realsense-ros-2.3.1.zip from realsense-ros releases and  tried two approaches :
Approach -1:
cd ..
catkin build realsense2_camera -DCATKIN_ENABLE_TESTING=False -DCMAKE_BUILD_TYPE=Release -j1

Approach-2:
catkin_init_workspace
cd ..
catkin_make clean
catkin_make -DCATKIN_ENABLE_TESTING=False -DCMAKE_BUILD_TYPE=Release

Both gave the same error as below:
user@raspberrypi:~/catkin_realsense_ws$ catkin build realsense2_camera -DCATKIN_ENABLE_TESTING=False -DCMAKE_BUILD_TYPE=Release

--------------------------------------------------------------------------------------------------------------------------------------

Profile:                     default
Extending:             [env] /opt/ros/noetic
Workspace:                   /home/user/catkin_realsense_ws

Build Space:        [exists] /home/user/catkin_realsense_ws/build
Devel Space:        [exists] /home/user/catkin_realsense_ws/devel
Install Space:      [unused] /home/user/catkin_realsense_ws/install
Log Space:         [missing] /home/user/catkin_realsense_ws/logs
Source Space:       [exists] /home/user/catkin_realsense_ws/src
DESTDIR:            [unused] None

Devel Space Layout:          linked
Install Space Layout:        None

Additional CMake Args:       -DCATKIN_ENABLE_TESTING=False -DCMAKE_BUILD_TYPE=Release
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False

Buildlisted Packages:        None
Skiplisted Packages:         None

Workspace configuration appears valid.

NOTE: Forcing CMake to run for each package.

[build] Found 2 packages in 0.0 seconds.                                       
[build] Updating package table.                                                
Starting  >>> catkin_tools_prebuild                                            
Finished  <<< catkin_tools_prebuild                [ 3.9 seconds ]             
Starting  >>> realsense2_camera                                                
_______________________________________________________________________________________________
Errors     << realsense2_camera:make /home/user/catkin_realsense_ws/logs/realsense2_camera/build.make.000.log
In file included from /opt/ros/noetic/include/librealsense2/hpp/rs_sensor.hpp:8,
                 from /opt/ros/noetic/include/librealsense2/hpp/rs_device.hpp:8,
                 from /opt/ros/noetic/include/librealsense2/hpp/rs_record_playback.hpp:8,
                 from /opt/ros/noetic/include/librealsense2/hpp/rs_context.hpp:8,
                 from /opt/ros/noetic/include/librealsense2/rs.hpp:9,
                 from /home/user/catkin_realsense_ws/src/realsense-ros-2.3.1/realsense2_camera/include/../include/realsense_node_factory.h:12,
                 from /home/user/catkin_realsense_ws/src/realsense-ros-2.3.1/realsense2_camera/include/base_realsense_node.h:6,
                 from /home/user/catkin_realsense_ws/src/realsense-ros-2.3.1/realsense2_camera/src/../include/t265_realsense_node.h:3,
                 from /home/user/catkin_realsense_ws/src/realsense-ros-2.3.1/realsense2_camera/src/t265_realsense_node.cpp:1:
/opt/ros/noetic/include/librealsense2/hpp/rs_frame.hpp: In lambda function:
/opt/ros/noetic/include/librealsense2/hpp/rs_frame.hpp:1047:58: warning: comparison of integer expressions of different signedness: ‘int’ and ‘const size_t’ {aka ‘const unsigned int’} [-Wsign-compare]
 1047 |                         frm.get_profile().stream_index() == index) f = frm;
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
/opt/ros/noetic/include/librealsense2/hpp/rs_frame.hpp: In lambda function:
/opt/ros/noetic/include/librealsense2/hpp/rs_frame.hpp:1069:58: warning: comparison of integer expressions of different signedness: ‘int’ and ‘const size_t’ {aka ‘const unsigned int’} [-Wsign-compare]
 1069 |                         frm.get_profile().stream_index() == index) f = frm;
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
/opt/ros/noetic/include/librealsense2/hpp/rs_frame.hpp: In lambda function:
/opt/ros/noetic/include/librealsense2/hpp/rs_frame.hpp:1091:58: warning: comparison of integer expressions of different signedness: ‘int’ and ‘const size_t’ {aka ‘const unsigned int’} [-Wsign-compare]
 1091 |                         frm.get_profile().stream_index() == index) f = frm;
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
In file included from /opt/ros/noetic/include/librealsense2/hpp/rs_sensor.hpp:8,
                 from /opt/ros/noetic/include/librealsense2/hpp/rs_device.hpp:8,
                 from /opt/ros/noetic/include/librealsense2/hpp/rs_record_playback.hpp:8,
                 from /opt/ros/noetic/include/librealsense2/hpp/rs_context.hpp:8,
                 from /opt/ros/noetic/include/librealsense2/rs.hpp:9,
                 from /home/user/catkin_realsense_ws/src/realsense-ros-2.3.1/realsense2_camera/src/../include/realsense_node_factory.h:12,
                 from /home/user/catkin_realsense_ws/src/realsense-ros-2.3.1/realsense2_camera/src/realsense_node_factory.cpp:4:
/opt/ros/noetic/include/librealsense2/hpp/rs_frame.hpp: In lambda function:
/opt/ros/noetic/include/librealsense2/hpp/rs_frame.hpp:1047:58: warning: comparison of integer expressions of different signedness: ‘int’ and ‘const size_t’ {aka ‘const unsigned int’} [-Wsign-compare]
 1047 |                         frm.get_profile().stream_index() == index) f = frm;
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
/opt/ros/noetic/include/librealsense2/hpp/rs_frame.hpp: In lambda function:
/opt/ros/noetic/include/librealsense2/hpp/rs_frame.hpp:1069:58: warning: comparison of integer expressions of different signedness: ‘int’ and ‘const size_t’ {aka ‘const unsigned int’} [-Wsign-compare]
 1069 |                         frm.get_profile().stream_index() == index) f = frm;
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
/opt/ros/noetic/include/librealsense2/hpp/rs_frame.hpp: In lambda function:
/opt/ros/noetic/include/librealsense2/hpp/rs_frame.hpp:1091:58: warning: comparison of integer expressions of different signedness: ‘int’ and ‘const size_t’ {aka ‘const unsigned int’} [-Wsign-compare]
 1091 |                         frm.get_profile().stream_index() == index) f = frm;
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
In file included from /opt/ros/noetic/include/librealsense2/hpp/rs_sensor.hpp:8,
                 from /opt/ros/noetic/include/librealsense2/hpp/rs_device.hpp:8,
                 from /opt/ros/noetic/include/librealsense2/hpp/rs_record_playback.hpp:8,
                 from /opt/ros/noetic/include/librealsense2/hpp/rs_context.hpp:8,
                 from /opt/ros/noetic/include/librealsense2/rs.hpp:9,
                 from /home/user/catkin_realsense_ws/src/realsense-ros-2.3.1/realsense2_camera/src/../include/../include/realsense_node_factory.h:12,
                 from /home/user/catkin_realsense_ws/src/realsense-ros-2.3.1/realsense2_camera/src/../include/base_realsense_node.h:6,
                 from /home/user/catkin_realsense_ws/src/realsense-ros-2.3.1/realsense2_camera/src/base_realsense_node.cpp:1:
/opt/ros/noetic/include/librealsense2/hpp/rs_frame.hpp: In lambda function:
/opt/ros/noetic/include/librealsense2/hpp/rs_frame.hpp:1047:58: warning: comparison of integer expressions of different signedness: ‘int’ and ‘const size_t’ {aka ‘const unsigned int’} [-Wsign-compare]
 1047 |                         frm.get_profile().stream_index() == index) f = frm;
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
/opt/ros/noetic/include/librealsense2/hpp/rs_frame.hpp: In lambda function:
/opt/ros/noetic/include/librealsense2/hpp/rs_frame.hpp:1069:58: warning: comparison of integer expressions of different signedness: ‘int’ and ‘const size_t’ {aka ‘const unsigned int’} [-Wsign-compare]
 1069 |                         frm.get_profile().stream_index() == index) f = frm;
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
/opt/ros/noetic/include/librealsense2/hpp/rs_frame.hpp: In lambda function:
/opt/ros/noetic/include/librealsense2/hpp/rs_frame.hpp:1091:58: warning: comparison of integer expressions of different signedness: ‘int’ and ‘const size_t’ {aka ‘const unsigned int’} [-Wsign-compare]
 1091 |                         frm.get_profile().stream_index() == index) f = frm;
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
In file included from /opt/ros/noetic/include/nodelet/nodelet.h:40,
                 from /home/user/catkin_realsense_ws/src/realsense-ros-2.3.1/realsense2_camera/src/../include/../include/realsense_node_factory.h:7,
                 from /home/user/catkin_realsense_ws/src/realsense-ros-2.3.1/realsense2_camera/src/../include/base_realsense_node.h:6,
                 from /home/user/catkin_realsense_ws/src/realsense-ros-2.3.1/realsense2_camera/src/base_realsense_node.cpp:1:
/home/user/catkin_realsense_ws/src/realsense-ros-2.3.1/realsense2_camera/src/base_realsense_node.cpp: In member function ‘void realsense2_camera::BaseRealSenseNode::frame_callback(rs2::frame)’:
/home/user/catkin_realsense_ws/src/realsense-ros-2.3.1/realsense2_camera/src/base_realsense_node.cpp:1652:27: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 14 has type ‘uint64_t’ {aka ‘long long unsigned int’} [-Wformat=]
 1652 |                 ROS_DEBUG("Frameset contain (%s, %d, %s %d) frame. frame_number: %llu ; frame_TS: %f ; ros_TS(NSec): %lu",
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1653 |                             rs2_stream_to_string(stream_type), stream_index, rs2_format_to_string(stream_format), stream_unique_id, frame.get_frame_number(), frame_time, t.toNSec());
      |                                                                                                                                                                           ~~~~~~~~~~
      |                                                                                                                                                                                   |
      |                                                                                                                                                                                   uint64_t {aka long long unsigned int}
/opt/ros/noetic/include/ros/console.h:351:165: note: in definition of macro ‘ROSCONSOLE_PRINT_AT_LOCATION_WITH_FILTER’
  351 |     ::ros::console::print(filter, __rosconsole_define_location__loc.logger_, __rosconsole_define_location__loc.level_, __FILE__, __LINE__, __ROSCONSOLE_FUNCTION__, __VA_ARGS__)
      |                                                                                                                                                                     ^~~~~~~~~~~
/opt/ros/noetic/include/ros/console.h:390:7: note: in expansion of macro ‘ROSCONSOLE_PRINT_AT_LOCATION’
  390 |       ROSCONSOLE_PRINT_AT_LOCATION(__VA_ARGS__); \
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/ros/noetic/include/ros/console.h:575:35: note: in expansion of macro ‘ROS_LOG_COND’
  575 | #define ROS_LOG(level, name, ...) ROS_LOG_COND(true, level, name, __VA_ARGS__)
      |                                   ^~~~~~~~~~~~
/opt/ros/noetic/include/rosconsole/macros_generated.h:58:24: note: in expansion of macro ‘ROS_LOG’
   58 | #define ROS_DEBUG(...) ROS_LOG(::ros::console::levels::Debug, ROSCONSOLE_DEFAULT_NAME, __VA_ARGS__)
      |                        ^~~~~~~
/home/user/catkin_realsense_ws/src/realsense-ros-2.3.1/realsense2_camera/src/base_realsense_node.cpp:1652:17: note: in expansion of macro ‘ROS_DEBUG’
 1652 |                 ROS_DEBUG("Frameset contain (%s, %d, %s %d) frame. frame_number: %llu ; frame_TS: %f ; ros_TS(NSec): %lu",
      |                 ^~~~~~~~~
/home/user/catkin_realsense_ws/src/realsense-ros-2.3.1/realsense2_camera/src/base_realsense_node.cpp:1652:120: note: format string is defined here
 1652 |                 ROS_DEBUG("Frameset contain (%s, %d, %s %d) frame. frame_number: %llu ; frame_TS: %f ; ros_TS(NSec): %lu",
      |                                                                                                                      ~~^
      |                                                                                                                        |
      |                                                                                                                        long unsigned int
      |                                                                                                                      %llu
In file included from /opt/ros/noetic/include/nodelet/nodelet.h:40,
                 from /home/user/catkin_realsense_ws/src/realsense-ros-2.3.1/realsense2_camera/src/../include/../include/realsense_node_factory.h:7,
                 from /home/user/catkin_realsense_ws/src/realsense-ros-2.3.1/realsense2_camera/src/../include/base_realsense_node.h:6,
                 from /home/user/catkin_realsense_ws/src/realsense-ros-2.3.1/realsense2_camera/src/base_realsense_node.cpp:1:
/home/user/catkin_realsense_ws/src/realsense-ros-2.3.1/realsense2_camera/src/base_realsense_node.cpp:1685:27: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 13 has type ‘uint64_t’ {aka ‘long long unsigned int’} [-Wformat=]
 1685 |                 ROS_DEBUG("Frameset contain (%s, %d, %s) frame. frame_number: %llu ; frame_TS: %f ; ros_TS(NSec): %lu",
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1686 |                             rs2_stream_to_string(stream_type), stream_index, rs2_format_to_string(stream_format), f.get_frame_number(), frame_time, t.toNSec());
      |                                                                                                                                                     ~~~~~~~~~~
      |                                                                                                                                                             |
      |                                                                                                                                                             uint64_t {aka long long unsigned int}
/opt/ros/noetic/include/ros/console.h:351:165: note: in definition of macro ‘ROSCONSOLE_PRINT_AT_LOCATION_WITH_FILTER’
  351 |     ::ros::console::print(filter, __rosconsole_define_location__loc.logger_, __rosconsole_define_location__loc.level_, __FILE__, __LINE__, __ROSCONSOLE_FUNCTION__, __VA_ARGS__)
      |                                                                                                                                                                     ^~~~~~~~~~~
/opt/ros/noetic/include/ros/console.h:390:7: note: in expansion of macro ‘ROSCONSOLE_PRINT_AT_LOCATION’
  390 |       ROSCONSOLE_PRINT_AT_LOCATION(__VA_ARGS__); \
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/ros/noetic/include/ros/console.h:575:35: note: in expansion of macro ‘ROS_LOG_COND’
  575 | #define ROS_LOG(level, name, ...) ROS_LOG_COND(true, level, name, __VA_ARGS__)
      |                                   ^~~~~~~~~~~~
/opt/ros/noetic/include/rosconsole/macros_generated.h:58:24: note: in expansion of macro ‘ROS_LOG’
   58 | #define ROS_DEBUG(...) ROS_LOG(::ros::console::levels::Debug, ROSCONSOLE_DEFAULT_NAME, __VA_ARGS__)
      |                        ^~~~~~~
/home/user/catkin_realsense_ws/src/realsense-ros-2.3.1/realsense2_camera/src/base_realsense_node.cpp:1685:17: note: in expansion of macro ‘ROS_DEBUG’
 1685 |                 ROS_DEBUG("Frameset contain (%s, %d, %s) frame. frame_number: %llu ; frame_TS: %f ; ros_TS(NSec): %lu",
      |                 ^~~~~~~~~
/home/user/catkin_realsense_ws/src/realsense-ros-2.3.1/realsense2_camera/src/base_realsense_node.cpp:1685:117: note: format string is defined here
 1685 |                 ROS_DEBUG("Frameset contain (%s, %d, %s) frame. frame_number: %llu ; frame_TS: %f ; ros_TS(NSec): %lu",
      |                                                                                                                   ~~^
      |                                                                                                                     |
      |                                                                                                                     long unsigned int
      |                                                                                                                   %llu
In file included from /opt/ros/noetic/include/nodelet/nodelet.h:40,
                 from /home/user/catkin_realsense_ws/src/realsense-ros-2.3.1/realsense2_camera/src/../include/../include/realsense_node_factory.h:7,
                 from /home/user/catkin_realsense_ws/src/realsense-ros-2.3.1/realsense2_camera/src/../include/base_realsense_node.h:6,
                 from /home/user/catkin_realsense_ws/src/realsense-ros-2.3.1/realsense2_camera/src/base_realsense_node.cpp:1:
/home/user/catkin_realsense_ws/src/realsense-ros-2.3.1/realsense2_camera/src/base_realsense_node.cpp:1739:23: warning: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 12 has type ‘uint64_t’ {aka ‘long long unsigned int’} [-Wformat=]
 1739 |             ROS_DEBUG("Single video frame arrived (%s, %d). frame_number: %llu ; frame_TS: %f ; ros_TS(NSec): %lu",
      |                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1740 |                         rs2_stream_to_string(stream_type), stream_index, frame.get_frame_number(), frame_time, t.toNSec());
      |                                                                                                                ~~~~~~~~~~
      |                                                                                                                        |
      |                                                                                                                        uint64_t {aka long long unsigned int}
/opt/ros/noetic/include/ros/console.h:351:165: note: in definition of macro ‘ROSCONSOLE_PRINT_AT_LOCATION_WITH_FILTER’
  351 |     ::ros::console::print(filter, __rosconsole_define_location__loc.logger_, __rosconsole_define_location__loc.level_, __FILE__, __LINE__, __ROSCONSOLE_FUNCTION__, __VA_ARGS__)
      |                                                                                                                                                                     ^~~~~~~~~~~
/opt/ros/noetic/include/ros/console.h:390:7: note: in expansion of macro ‘ROSCONSOLE_PRINT_AT_LOCATION’
  390 |       ROSCONSOLE_PRINT_AT_LOCATION(__VA_ARGS__); \
      |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/opt/ros/noetic/include/ros/console.h:575:35: note: in expansion of macro ‘ROS_LOG_COND’
  575 | #define ROS_LOG(level, name, ...) ROS_LOG_COND(true, level, name, __VA_ARGS__)
      |                                   ^~~~~~~~~~~~
/opt/ros/noetic/include/rosconsole/macros_generated.h:58:24: note: in expansion of macro ‘ROS_LOG’
   58 | #define ROS_DEBUG(...) ROS_LOG(::ros::console::levels::Debug, ROSCONSOLE_DEFAULT_NAME, __VA_ARGS__)
      |                        ^~~~~~~
/home/user/catkin_realsense_ws/src/realsense-ros-2.3.1/realsense2_camera/src/base_realsense_node.cpp:1739:13: note: in expansion of macro ‘ROS_DEBUG’
 1739 |             ROS_DEBUG("Single video frame arrived (%s, %d). frame_number: %llu ; frame_TS: %f ; ros_TS(NSec): %lu",
      |             ^~~~~~~~~
/home/user/catkin_realsense_ws/src/realsense-ros-2.3.1/realsense2_camera/src/base_realsense_node.cpp:1739:113: note: format string is defined here
 1739 |             ROS_DEBUG("Single video frame arrived (%s, %d). frame_number: %llu ; frame_TS: %f ; ros_TS(NSec): %lu",
      |                                                                                                               ~~^
      |                                                                                                                 |
      |                                                                                                                 long unsigned int
      |                                                                                                               %llu
/home/user/catkin_realsense_ws/src/realsense-ros-2.3.1/realsense2_camera/src/base_realsense_node.cpp: In member function ‘void realsense2_camera::BaseRealSenseNode::publishPointCloud(rs2::points, const ros::Time&, const rs2::frameset&)’:
/home/user/catkin_realsense_ws/src/realsense-ros-2.3.1/realsense2_camera/src/base_realsense_node.cpp:2165:29: error: ‘find_if’ was not declared in this scope
 2165 |         texture_frame_itr = find_if(frameset.begin(), frameset.end(), [&texture_source_id, &available_formats] (rs2::frame f)
      |                             ^~~~~~~
/home/user/catkin_realsense_ws/src/realsense-ros-2.3.1/realsense2_camera/src/base_realsense_node.cpp:2165:29: note: suggested alternatives:
In file included from /usr/include/c++/9/algorithm:62,
                 from /usr/include/boost/smart_ptr/shared_ptr.hpp:39,
                 from /usr/include/boost/shared_ptr.hpp:17,
                 from /opt/ros/noetic/include/class_loader/class_loader.hpp:36,
                 from /opt/ros/noetic/include/pluginlib/./class_list_macros.hpp:40,
                 from /opt/ros/noetic/include/pluginlib/class_list_macros.h:35,
                 from /home/user/catkin_realsense_ws/src/realsense-ros-2.3.1/realsense2_camera/src/../include/../include/realsense_node_factory.h:6,
                 from /home/user/catkin_realsense_ws/src/realsense-ros-2.3.1/realsense2_camera/src/../include/base_realsense_node.h:6,
                 from /home/user/catkin_realsense_ws/src/realsense-ros-2.3.1/realsense2_camera/src/base_realsense_node.cpp:1:
/usr/include/c++/9/bits/stl_algo.h:3960:5: note:   ‘std::find_if’
 3960 |     find_if(_InputIterator __first, _InputIterator __last,
      |     ^~~~~~~
In file included from /usr/include/boost/mpl/find.hpp:17,
                 from /usr/include/boost/mpl/aux_/contains_impl.hpp:20,
                 from /usr/include/boost/mpl/contains.hpp:20,
                 from /usr/include/boost/math/policies/policy.hpp:10,
                 from /usr/include/boost/math/policies/error_handling.hpp:21,
                 from /usr/include/boost/math/special_functions/round.hpp:14,
                 from /opt/ros/noetic/include/ros/time.h:58,
                 from /opt/ros/noetic/include/ros/console.h:39,
                 from /opt/ros/noetic/include/nodelet/nodelet.h:40,
                 from /home/user/catkin_realsense_ws/src/realsense-ros-2.3.1/realsense2_camera/src/../include/../include/realsense_node_factory.h:7,
                 from /home/user/catkin_realsense_ws/src/realsense-ros-2.3.1/realsense2_camera/src/../include/base_realsense_node.h:6,
                 from /home/user/catkin_realsense_ws/src/realsense-ros-2.3.1/realsense2_camera/src/base_realsense_node.cpp:1:
/usr/include/boost/mpl/find_if.hpp:32:8: note:   ‘boost::mpl::find_if’
   32 | struct find_if
      |        ^~~~~~~
make[2]: *** [CMakeFiles/realsense2_camera.dir/build.make:76: CMakeFiles/realsense2_camera.dir/src/base_realsense_node.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:246: CMakeFiles/realsense2_camera.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
cd /home/user/catkin_realsense_ws/build/realsense2_camera; catkin build --get-env realsense2_camera | catkin env -si  /usr/bin/make --jobserver-auth=3,4; cd -

...............................................................................................
Failed     << realsense2_camera:make               [ Exited with code 2 ]                      
Failed    <<< realsense2_camera                    [ 52.3 seconds ]                            
[build] Summary: 1 of 2 packages succeeded.                                                    
[build]   Ignored:   1 packages were skipped or are skiplisted.                                
[build]   Warnings:  None.                                                                     
[build]   Abandoned: None.                                                                     
[build]   Failed:    1 packages failed.                                                        
[build] Runtime: 56.2 seconds total.                                                           
[build] Note: Workspace packages have changed, please re-source setup files to use them.

I tried again by adding these lines to the CMakelists.txt of realsense2_camera:
set(CMAKE_CXX_STANDARD_14)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
add_compile_options(-std=c++14)

No change (Same error). 
Could you (@MartyG-RealSense ) please suggest on how to proceed?

**Comment by MartyG-RealSense** [comment]
Hi @ta-jetson  The T265 camera model is no longer supported by Intel, so I can only assist in relation to D435i.

The **eleccelerator** guide at the link below for installing the RealSense ROS1 wrapper on Raspberry Pi 4 may be a helpful reference.

https://eleccelerator.com/wiki/index.php?title=Raspbian_Buster_ROS_RealSense#Installing_ROS_Package:_realsense-ros

If you wish to install a specific wrapper version with **git checkout** then you can replace the tags with a version number.

`git checkout v2.3.1`

**Comment by ta-jetson** [comment]
Hey @MartyG-RealSense , 
I was following the reference you provided and tried to checkout v2.3.1. I got the following error.

-----------------------------------------------

tsalla@raspberrypi:catkin_realsense_ws/src$ cd realsense-ros/
tsalla@raspberrypi:catkin_realsense_ws/src/realsense-ros$ git checkout v2.3.1
error: pathspec 'v2.3.1' did not match any file(s) known to git

**Comment by MartyG-RealSense** [comment]
'v2.3.1' is apparently still a valid tag.  

<img width="276" alt="image" src="https://github.com/IntelRealSense/realsense-ros/assets/41145062/913dd4a8-612c-435f-9575-a4bb67ab2d09">

Let's try it this way:

<img width="129" alt="image" src="https://github.com/IntelRealSense/realsense-ros/assets/41145062/ed2335b8-f1ce-4d7d-a19e-35332f31b149">

**Comment by ta-jetson** [comment]
Hey @MartyG-RealSense , 

This is what git checkout gave me

git checkout `git tag v2.3.1`
Your branch is up to date with 'origin/ros2-development'.

I want ROS1, not ROS2. Nevertheless I followed the documentation until catkin_make and got the following error:

~/catkin_realsense_ws$ catkin_make -DCATKIN_ENABLE_TESTING=False -DCMAKE_BUILD_TYPE=Release
Base path: /home/tsalla/catkin_realsense_ws
Source space: /home/tsalla/catkin_realsense_ws/src
Build space: /home/tsalla/catkin_realsense_ws/build
Devel space: /home/tsalla/catkin_realsense_ws/devel
Install space: /home/tsalla/catkin_realsense_ws/install
####
#### Running command: "cmake /home/tsalla/catkin_realsense_ws/src -DCATKIN_ENABLE_TESTING=False -DCMAKE_BUILD_TYPE=Release -DCATKIN_DEVEL_PREFIX=/home/tsalla/catkin_realsense_ws/devel -DCMAKE_INSTALL_PREFIX=/home/tsalla/catkin_realsense_ws/install -G Unix Makefiles" in "/home/tsalla/catkin_realsense_ws/build"
####
-- The C compiler identification is GNU 9.4.0
-- The CXX compiler identification is GNU 9.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using CATKIN_DEVEL_PREFIX: /home/tsalla/catkin_realsense_ws/devel
-- Using CMAKE_PREFIX_PATH: /opt/ros/noetic
-- This workspace overlays: /opt/ros/noetic
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.8.10", minimum required is "3") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python3
-- Using Debian Python package layout
-- Found PY_em: /usr/lib/python3/dist-packages/em.py  
-- Using empy: /usr/lib/python3/dist-packages/em.py
-- Using CATKIN_ENABLE_TESTING: False
-- catkin 0.8.10
-- BUILD_SHARED_LIBS is on
-- BUILD_SHARED_LIBS is on
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 3 packages in topological order:
-- ~~  - realsense2_camera_msgs (plain cmake)
-- ~~  - realsense2_description (plain cmake)
-- ~~  - realsense2_camera (plain cmake)
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
CMake Error at /opt/ros/noetic/share/catkin/cmake/catkin_workspace.cmake:100 (message):
  This workspace contains non-catkin packages in it, and catkin cannot build
  a non-homogeneous workspace without isolation.  Try the
  'catkin_make_isolated' command instead.
Call Stack (most recent call first):
  CMakeLists.txt:69 (catkin_workspace)


-- Configuring incomplete, errors occurred!
See also "/home/tsalla/catkin_realsense_ws/build/CMakeFiles/CMakeOutput.log".
Invoking "cmake" failed

**Comment by MartyG-RealSense** [comment]
It may be necessary to install the latest available ROS1 version, 2.3.2, though it is not ideal as it was intended for use with the next librealsense version after 2.48.0, which was 2.50.0.

First, delete the entire **catkin_ws\src** catkin workspace folder to ensure that any previous ROS wrapper installation is removed.

Then do this:

<img width="378" alt="image" src="https://github.com/IntelRealSense/realsense-ros/assets/41145062/9471a50c-7df2-4511-b88c-92297a23f449">

**Comment by ta-jetson** [comment]
Hey @MartyG-RealSense ,

Thank you, your suggestion helped. 

Solution to issue:
I just followed the documentation in Intel Realsense ROS [https://github.com/IntelRealSense/realsense-ros/tree/ros1-legacy](url), with the branch ROS1-legacy.

Thanks again @MartyG-RealSense

**Comment by MartyG-RealSense** [comment]
That's great to hear, @ta-jetson - thanks very much for the update!
