### ISSUE TITLE
WARN：frame's time domain is HARDWARE_CLOCK. Timestamps may reset periodically

### ISSUE THREAD

**Issue by liujun0808** [realsenseai/realsense-ros#2980]
----------------------------------------------------------------------------------------------------

| Required Info                         |                                                                                         |
|---------------------------------|------------------------------------------------------------ |
| Camera Model                       | { D435i  }                          | 
| Firmware Version                   | 5.13.0.55                         | 
| Operating System & Version |   Ubuntu 20.04  | 
| Kernel Version (Linux Only)    |  5.15.0-91-generic                                                                       | 
| Platform                                 | PC                           |
| Librealsense SDK Version       |  V2.50.0                                                   | 
| Language                               | opencv/C++        | 
| Segment			         |  Robot                            | 
| ROS Distro			         | noetic                                           | 

### Issue Description
**When I start roslaunch realsense2_camera rs_aligned_depth.launch， this warning is displayed.
I summarized three questions：
1.As the title says.
2.When I start, sometimes this warning appears:
[ WARN] [1706017395.885509102]: Hardware Notification:Depth stream start failure,1.70602e+12,Error,Hardware Error
[ WARN] [1706017396.886610191]: Hardware Notification:Depth stream start failure,1.70602e+12,Error,Hardware Error
[ WARN] [1706017398.888700026]: Hardware Notification:IR stream start failure,1.70602e+12,Error,Hardware Error
3.Also, when I read the depth of a certain pixel in the depth map, it displays 0, but sometimes the depth value is displayed normally.Is this related to question one?**
Thank you for your reply！

**### When I start roslaunch realsense2_camera rs_aligned_depth.launch, this warning is displayed, and the startup information is as follows:**
... logging to /home/liujun/.ros/log/56dfc21c-b9f5-11ee-a085-d318c774b767/roslaunch-ubuntu-175368.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://ubuntu:38677/

summary
========

PARAMETERS
 * /camera/realsense2_camera/accel_fps: 250
 * /camera/realsense2_camera/accel_frame_id: camera_accel_frame
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: True
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/allow_no_texture_points: False
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/calib_odom_file: 
 * /camera/realsense2_camera/clip_distance: -1.0
 * /camera/realsense2_camera/color_fps: 30
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: 480
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: 640
 * /camera/realsense2_camera/confidence_fps: 30
 * /camera/realsense2_camera/confidence_height: 480
 * /camera/realsense2_camera/confidence_width: 640
 * /camera/realsense2_camera/depth_fps: 30
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: 480
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: 640
 * /camera/realsense2_camera/device_type: 
 * /camera/realsense2_camera/enable_accel: True
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_confidence: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye1: False
 * /camera/realsense2_camera/enable_fisheye2: False
 * /camera/realsense2_camera/enable_fisheye: True
 * /camera/realsense2_camera/enable_gyro: True
 * /camera/realsense2_camera/enable_infra1: True
 * /camera/realsense2_camera/enable_infra2: True
 * /camera/realsense2_camera/enable_infra: False
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_pose: False
 * /camera/realsense2_camera/enable_sync: True
 * /camera/realsense2_camera/filters: 
 * /camera/realsense2_camera/fisheye1_frame_id: camera_fisheye1_f...
 * /camera/realsense2_camera/fisheye1_optical_frame_id: camera_fisheye1_o...
 * /camera/realsense2_camera/fisheye2_frame_id: camera_fisheye2_f...
 * /camera/realsense2_camera/fisheye2_optical_frame_id: camera_fisheye2_o...
 * /camera/realsense2_camera/fisheye_fps: 30
 * /camera/realsense2_camera/fisheye_frame_id: camera_fisheye_frame
 * /camera/realsense2_camera/fisheye_height: 480
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: 640
 * /camera/realsense2_camera/gyro_fps: 400
 * /camera/realsense2_camera/gyro_frame_id: camera_gyro_frame
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/imu_optical_frame_id: camera_imu_optica...
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra_fps: 30
 * /camera/realsense2_camera/infra_height: 480
 * /camera/realsense2_camera/infra_rgb: False
 * /camera/realsense2_camera/infra_width: 640
 * /camera/realsense2_camera/initial_reset: False
 * /camera/realsense2_camera/json_file_path: 
 * /camera/realsense2_camera/linear_accel_cov: 0.01
 * /camera/realsense2_camera/odom_frame_id: camera_odom_frame
 * /camera/realsense2_camera/ordered_pc: False
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/pose_frame_id: camera_pose_frame
 * /camera/realsense2_camera/pose_optical_frame_id: camera_pose_optic...
 * /camera/realsense2_camera/publish_odom_tf: True
 * /camera/realsense2_camera/publish_tf: True
 * /camera/realsense2_camera/reconnect_timeout: 6.0
 * /camera/realsense2_camera/rosbag_filename: 
 * /camera/realsense2_camera/serial_no: 
 * /camera/realsense2_camera/stereo_module/exposure/1: 7500
 * /camera/realsense2_camera/stereo_module/exposure/2: 1
 * /camera/realsense2_camera/stereo_module/gain/1: 16
 * /camera/realsense2_camera/stereo_module/gain/2: 16
 * /camera/realsense2_camera/tf_publish_rate: 0.0
 * /camera/realsense2_camera/topic_odom_in: camera/odom_in
 * /camera/realsense2_camera/unite_imu_method: none
 * /camera/realsense2_camera/usb_port_id: 
 * /camera/realsense2_camera/wait_for_device_timeout: -1.0
 * /rosdistro: noetic
 * /rosversion: 1.16.0

NODES
  /camera/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)

auto-starting new master
process[master]: started with pid [175376]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 56dfc21c-b9f5-11ee-a085-d318c774b767
process[rosout-1]: started with pid [175387]
started core service [/rosout]
process[camera/realsense2_camera_manager-2]: started with pid [175394]
process[camera/realsense2_camera-3]: started with pid [175395]
[ INFO] [1706017387.820923196]: Initializing nodelet with 2 worker threads.
[ INFO] [1706017387.918641207]: RealSense ROS v2.3.2
[ INFO] [1706017387.918685899]: Built with LibRealSense v2.50.0
[ INFO] [1706017387.918698656]: Running with LibRealSense v2.50.0
[ INFO] [1706017387.956471501]:  
[ INFO] [1706017388.232489089]: Device with serial number 243522070611 was found.

[ INFO] [1706017388.232589208]: Device with physical ID 4-1-5 was found.
[ INFO] [1706017388.232600408]: Device with name Intel RealSense D435I was found.
[ INFO] [1706017388.232990050]: Device with port number 4-1 was found.
[ INFO] [1706017388.233047540]: Device USB type: 3.2
[ INFO] [1706017388.236090513]: getParameters...
[ INFO] [1706017388.315684253]: setupDevice...
[ INFO] [1706017388.315725720]: JSON file is not provided
[ INFO] [1706017388.315736501]: ROS Node Namespace: camera
[ INFO] [1706017388.315747182]: Device Name: Intel RealSense D435I
[ INFO] [1706017388.315754351]: Device Serial No: 243522070611
[ INFO] [1706017388.315761746]: Device physical port: 4-1-5
[ INFO] [1706017388.315784307]: Device FW version: 05.13.00.55
[ INFO] [1706017388.315792859]: Device Product ID: 0x0B3A
[ INFO] [1706017388.315927281]: Enable PointCloud: Off
[ INFO] [1706017388.315951372]: Align Depth: On
[ INFO] [1706017388.315959523]: Sync Mode: On
[ INFO] [1706017388.315994894]: Device Sensors: 
[ INFO] [1706017388.371227588]: Stereo Module was found.
[ INFO] [1706017388.392370265]: RGB Camera was found.
[ INFO] [1706017388.392714893]: Motion Module was found.
[ INFO] [1706017388.392978088]: (Fisheye, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1706017388.393153728]: (Confidence, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1706017388.393719814]: num_filters: 1
[ INFO] [1706017388.393807428]: Setting Dynamic reconfig parameters.
[ INFO] [1706017390.407800692]: Done Setting Dynamic reconfig parameters.
[ INFO] [1706017390.408315964]: depth stream is enabled - width: 640, height: 480, fps: 30, Format: Z16
[ INFO] [1706017390.408508689]: infra1 stream is enabled - width: 640, height: 480, fps: 30, Format: Y8
[ INFO] [1706017390.408689726]: infra2 stream is enabled - width: 640, height: 480, fps: 30, Format: Y8
[ INFO] [1706017390.410402686]: color stream is enabled - width: 640, height: 480, fps: 30, Format: RGB8
[ INFO] [1706017390.420424660]: gyro stream is enabled - fps: 400
[ WARN] [1706017390.422596636]: No mathcing profile found for accel with fps=250
[ WARN] [1706017390.422900030]: Using default profile instead.
[ INFO] [1706017390.423113860]: accel stream is enabled - fps: 100
[ INFO] [1706017390.423416991]: setupPublishers...
[ INFO] [1706017390.428083677]: Expected frequency for depth = 30.00000
[ INFO] [1706017390.468550877]: Expected frequency for infra1 = 30.00000
[ INFO] [1706017390.493762867]: Expected frequency for infra2 = 30.00000
[ INFO] [1706017390.517955730]: Expected frequency for color = 30.00000
[ INFO] [1706017390.548213320]: Expected frequency for aligned_depth_to_color = 30.00000
[ INFO] [1706017390.622374580]: setupStreams...
 23/01 21:43:10,755 WARNING [140294838286080] (ds5-motion.cpp:473) IMU Calibration is not available, default intrinsic and extrinsic will be used.
[ WARN] [1706017393.883773129]: 
[ WARN] [1706017393.883839744]: frame's time domain is HARDWARE_CLOCK. Timestamps may reset periodically.
 23/01 21:43:14,059 WARNING [140294813107968] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
[ INFO] [1706017394.110357958]: SELECTED BASE:Depth, 0
[ INFO] [1706017394.122630743]: RealSense Node Is Up!
 23/01 21:43:14,179 WARNING [140294813107968] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 23/01 21:43:14,230 WARNING [140294813107968] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 23/01 21:43:14,382 WARNING [140294813107968] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 23/01 21:43:14,433 WARNING [140294813107968] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 23/01 21:43:14,483 WARNING [140294813107968] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 23/01 21:43:14,534 WARNING [140294813107968] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 23/01 21:43:14,585 WARNING [140294813107968] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 23/01 21:43:14,636 WARNING [140294813107968] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 23/01 21:43:14,687 WARNING [140294813107968] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 23/01 21:43:14,705 ERROR [140294234306304] (uvc-streamer.cpp:106) uvc streamer watchdog triggered on endpoint: 130
 23/01 21:43:14,738 WARNING [140294813107968] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 23/01 21:43:14,789 WARNING [140294813107968] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 23/01 21:43:14,840 WARNING [140294813107968] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 23/01 21:43:14,891 WARNING [140294813107968] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 23/01 21:43:14,942 WARNING [140294813107968] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 23/01 21:43:14,993 WARNING [140294813107968] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 23/01 21:43:15,043 WARNING [140294813107968] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 23/01 21:43:15,052 ERROR [140294209128192] (uvc-streamer.cpp:106) uvc streamer watchdog triggered on endpoint: 131
 23/01 21:43:15,095 WARNING [140294813107968] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 23/01 21:43:15,146 WARNING [140294813107968] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 23/01 21:43:15,197 WARNING [140294813107968] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 23/01 21:43:15,248 WARNING [140294813107968] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 23/01 21:43:15,299 WARNING [140294813107968] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 23/01 21:43:15,349 WARNING [140294813107968] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 23/01 21:43:15,401 WARNING [140294813107968] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 23/01 21:43:15,452 WARNING [140294813107968] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 23/01 21:43:15,503 WARNING [140294813107968] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 23/01 21:43:15,554 WARNING [140294813107968] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 23/01 21:43:15,606 WARNING [140294813107968] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 23/01 21:43:15,859 WARNING [140294813107968] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
[ WARN] [1706017395.885509102]: Hardware Notification:Depth stream start failure,1.70602e+12,Error,Hardware Error
 23/01 21:43:15,910 WARNING [140294813107968] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 23/01 21:43:16,063 WARNING [140294813107968] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 23/01 21:43:16,114 WARNING [140294813107968] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
[ WARN] [1706017396.886610191]: Hardware Notification:Depth stream start failure,1.70602e+12,Error,Hardware Error
[ WARN] [1706017398.888700026]: Hardware Notification:IR stream start failure,1.70602e+12,Error,Hardware Error

**Comment by MartyG-RealSense** [comment]
Hi @liujun0808  The aligned_depth launch file is very out of date as it has not been updated for over 5 years at the time of writing this.  Please instead try the launch instruction below to achieve a depth-color aligned image.

`roslaunch realsense2_camera rs_camera.launch align_depth:=true`

In regard to the depth of a pixel, it may appear as '0' sometimes or return a depth value if the depth values in that area of the image are fluctuating, with depth information appearing and disappearing depending on how well the camera can read the depth of real-world areas in the scene that the camera is observing.

**Comment by liujun0808** [comment]
> Hi @liujun0808 The aligned_depth launch file is very out of date as it has not been updated for over 5 years at the time of writing this. Please instead try the launch instruction below to achieve a depth-color aligned image.
> 
> `roslaunch realsense2_camera rs_camera.launch align_depth:=true`
> 
> In regard to the depth of a pixel, it may appear as '0' sometimes or return a depth value if the depth values in that area of the image are fluctuating, with depth information appearing and disappearing depending on how well the camera can read the depth of real-world areas in the scene that the camera is observing.

Thank you for your reply. I took your suggestion and the second problem was solved after successful startup, but the first problem still exists. Will this warning have any adverse effects?

**Comment by MartyG-RealSense** [comment]
If a **control_transfer returned** message is generating continuously in the log then it has the potential to cause slowdown, but if performance does not seem to be negatively impacted by the messages then it is safe to ignore them.

**Comment by liujun0808** [comment]
> If a **control_transfer returned** message is generating continuously in the log then it has the potential to cause slowdown, but if performance does not seem to be negatively impacted by the messages then it is safe to ignore them.

OK, thank you for your reply, the **control_transfer** returned messages are not continuously output during use, they only appear in large numbers when started.

**Comment by MartyG-RealSense** [comment]
If the messages stop generating after launch then it is fine to ignore them.

**Comment by liujun0808** [comment]
> If the messages stop generating after launch then it is fine to ignore them.

OK, I understand, thank you again!

**Comment by MartyG-RealSense** [comment]
Hi @liujun0808  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
