### ISSUE TITLE
Health Check?

### ISSUE THREAD

**Issue by ghost** [realsenseai/realsense-ros#2986]
I have a question about realsense. Is the realsense has a health check topic or something?

I think that we should check the frame delayed or something else...
As soon as can repeat ASAP plz! Have a great day!

**Comment by MartyG-RealSense** [comment]
Hi @taeyeonggim  The RealSense ROS wrapper publishes a **/diagnostics** topic.  The /diagnostics topic includes information regarding the device temperatures and actual frequency of the enabled streams.

**Comment by ghost** [comment]
@MartyG-RealSense 
First of all, thanks for the answer, is it possible to get that information using the pyrealsense2 library, and if so, do you have any example code?

**Comment by MartyG-RealSense** [comment]
There is not an all-in-one equivalent to the /diagnostics topic in pyrealsense2 but you can retrieve the information.

https://github.com/IntelRealSense/librealsense/issues/866 discusses retrieving the ASIC and Projector temperatures with Python code.

You can retrieve the frames per second (FPS) with the camera metadata parameter **ACTUAL_FPS**.  Or you could attempt to calculate the number of dropped frames.  https://github.com/IntelRealSense/librealsense/issues/6202 should be a helpful Python reference for both of these methods.

**Comment by ghost** [comment]
Thank you for your quick response!!! I was able to resolve the issue thanks to you! Have a great day! @MartyG-RealSense 
Please close the issue if you saw this comment!
![개추](https://github.com/IntelRealSense/realsense-ros/assets/131626914/93dad223-ad48-4603-9f1f-9c76e56885c9)

**Comment by MartyG-RealSense** [comment]
You are very welcome.  I'm pleased that I could help.  :)
