### ISSUE TITLE
QOS Setting Pointcloud

### ISSUE THREAD

**Issue by anath93** [realsenseai/realsense-ros#2995]
----------------------------------------------------------------------------------------------------

| Required Info                         |                                                                                         |
|---------------------------------|------------------------------------------------------------ |
| Camera Model                       | { D455 }                          | 
| Firmware Version                   | 5.15.1                          | 
| Operating System & Version |   { Ubuntu 20.04 } | 
| Kernel Version (Linux Only)    | 5.15                                                                     | 
| Platform                                 | Jetson AGX Orin                           |
| Segment			         |  {Robot }                             | 
| ROS Distro			         |  Galactic                                           | 
| RealSense ROS Wrapper Version   |  4.54.1                                                 | 

### Issue Description
Pointcloud QOS not getting applied:

I looked into previous issues, unable to change the QoS on pointcloud data
![image](https://github.com/IntelRealSense/realsense-ros/assets/130472005/70f6d8bb-d187-42d3-8357-9bcf99300bbe)

![image](https://github.com/IntelRealSense/realsense-ros/assets/130472005/79d61e84-33f1-4003-b974-151a355f031a)

https://github.com/IntelRealSense/realsense-ros/issues/1827

Unless forced to Sensor_data the pointcloud QoS does not change :

![image](https://github.com/IntelRealSense/realsense-ros/assets/130472005/2cf2296f-da2a-45a7-9a35-c28da339afca)

**Comment by MartyG-RealSense** [comment]
Hi @anath93  Can the QoS mode be successfully set to a mode other than SENSOR_DATA by defining it in the launch instruction if you are not doing so already, please?

`ros2 launch realsense2_camera rs_launch.py pointcloud.enable:=true depth_qos:=SYSTEM_DEFAULT`

**Comment by anath93** [comment]
@MartyG-RealSense I tried that couple days ago, it does not work by setting in the launch file.

**Comment by MartyG-RealSense** [comment]
And it also does not change the setting if you launch with **ros2 run** instead of ros2 launch?

`ros2 run realsense2_camera realsense2_camera_node --ros-args -p pointcloud.enable:=true -p depth_qos:=SYSTEM_DEFAULT`

**Comment by anath93** [comment]
@MartyG-RealSense  No it does not.

**Comment by MartyG-RealSense** [comment]
If you are able to successfully set **SENSOR_DATA** then can that mode meet your needs or do you require a different mode such as SYSTEM_DEFAULT, please?

**Comment by anath93** [comment]
Yes that solves the issue, its just a simple bug. Manually changing in the .h file and building the workspace works. But would be better if that could be linked to 'depth_qos' .

**Comment by MartyG-RealSense** [comment]
There was a recent Pull Request (PR) at https://github.com/IntelRealSense/realsense-ros/pull/2936 where another RealSense ROS user was unable to change the QoS in the launch file, and members of the RealSense ROS development team responded to them.

**Comment by anath93** [comment]
I see this is under ros2-development, but I am on 4.54.1, before I try and spend time on this, is this going to work for 4.54.1 ? meaning is there yaml parser in the source code side ?

**Comment by MartyG-RealSense** [comment]
ros2_development is the name of the Master branch of the RealSense ROS2 wrapper.

Older versions of the wrapper already support the import of yaml configuration files.

**Comment by anath93** [comment]
@MartyG-RealSense for 4.54.1, I got this info and maybe helpful from the person I am working with over NDA, the parameter is 'pointcloud.pointcloud_qos' for pointcloud qos.

**Comment by MartyG-RealSense** [comment]
@anath93  Thanks so much for sharing!
