### ISSUE TITLE
Can't get all the topics as specified in the README.md 

### ISSUE THREAD

**Issue by FalakFatima11** [realsenseai/realsense-ros#3002]
| Required Info                         |                                                                                         |
|---------------------------------|------------------------------------------------------------ |
| Camera Model                       |D435i                         | 
| Firmware Version | 5.15.1.0 |
| Operating System & Version |   Ubuntu 20 | 
| Kernel Version (Linux Only)    |  Linux 5.15.0-94-generic x86_64
                                                                       | 
| Platform                                 | PC                        |
| Librealsense SDK Version       |  { 2.54.2 }                                                    | 
| Language                               |  {C/opencv/pcl/python  }       | 
| Segment			         |  {Robot}                             | 
| ROS Distro			         |  {Noetic}                                           | 
| RealSense ROS Wrapper Version   |  {ROS-1 Legacy}                                                  | 

### Issue Description
I can't get all the topics as mentioned in the readme.md file when I run rs_camera.launch, like the ones related to gyro and IMU
![Screenshot from 2024-02-11 12-34-51](https://github.com/IntelRealSense/realsense-ros/assets/142772681/913d5daa-d323-4082-a6b5-e22818f46839)
![Screenshot from 2024-02-11 12-35-07](https://github.com/IntelRealSense/realsense-ros/assets/142772681/0c155df3-e941-4c79-8eea-bb1913da8e49)
![Screenshot from 2024-02-11 12-35-10](https://github.com/IntelRealSense/realsense-ros/assets/142772681/03e42da3-d4ca-4d65-b3b2-117c2eeb9d8b)

**Comment by MartyG-RealSense** [comment]
Hi @FalakFatima11  Some topics, including accel, gyro and infrared, are disabled by default in the launch file. You can enable them in the launch instruction.

`enable_infra1:=true enable_infra2:=true enable_gyro:=true enable_accel:=true`

To combine the accel and gyro topics together into the `/imu` topic, use `unite_imu_method:=linear_interpolation` for the ROS1 legacy wrapper and`unite_imu_method:=2`for the ROS2 wrapper.

**Comment by MartyG-RealSense** [comment]
Hi @FalakFatima11  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
