### ISSUE TITLE
Align_depth large latency

### ISSUE THREAD

**Issue by maladzenkau** [realsenseai/realsense-ros#3004]
Hello,

To make object detection i am trying to access depth information of the pixel which is a center of a bounding box. I was using _/color/image_raw_ for detection and then _/aligned_depth_to_color/image_raw_ for the depth estimation. It works well, but align_depth filter dramatically decreases the latency of the object detection pipeline for 40-50ms, so i am trying to find the way how to access the depth information of the only one pixel.

I have looked into the Realsense Wrapper code and didn't realize how **align_depth** works. Is it possible to apply the same method to one known pixel from the color sensor? Or is it possible to derive some `color pixel  to color sensor Intrinsic transformation ->  color sensor  to depth sensor Extrinsic transformation - > depth sensor to depth pixel Intrinsic transformation?`
Any help will be appreciated...

**Comment by MartyG-RealSense** [comment]
Hi @45kmh  In the RealSense SDK (librealsense) you can obtain depth information for a single color pixel coordinate with the instruction **rs2_project_color_pixel_to_depth_pixel**.

There is not an equivalent command in the RealSense ROS wrapper for converting a color pixel to a depth pixel, but there is a Python **node script** called 'show_center_depth.py' for the wrapper that provides the depth value at a single **depth** coordinate.  By default this coordinate is the center of the image.

**ROS1**
https://github.com/IntelRealSense/realsense-ros/blob/ros1-legacy/realsense2_camera/scripts/show_center_depth.py

**ROS2**
https://github.com/IntelRealSense/realsense-ros/blob/ros2-development/realsense2_camera/scripts/show_center_depth.py

If an **Nvidia Jetson** single-board computer is used to run the ROS wrapper then the processing burden of align_depth can be reduced by enabling the SDK's **CUDA** support to offload processing of alignment from the CPU onto the Jetson's Nvidia graphics GPU.

**Comment by maladzenkau** [comment]
Thanks a lot @MartyG-RealSense, everything works pretty well now!

**Comment by MartyG-RealSense** [comment]
You are very welcome, @45kmh - thanks very much for the update!
