### ISSUE TITLE
intelrealsenseD415（Given depth profile is not supported by current device!）

### ISSUE THREAD

**Issue by ccempathy** [realsenseai/realsense-ros#301]
I have installed Intel® RealSense™ SDK 2.0 (build 2.9.1) successfully and there is no problem installing ROS Wrapper for Intel® RealSense™ Devices.But there existed a question that "Given depth profile is not supported by current device!" when I was testing. I have been confused about the question for a long time .Look forward to your help .Thanks a lot!

![2018-01-31 20-42-34](https://user-images.githubusercontent.com/32675546/35623715-892f0a30-06c7-11e8-8419-8e8e08400955.png)

**Comment by icarpis** [comment]
Hello @ccempathy, could you please provide the whole output?
Also, which Launch file are you using? have you modified it?

**Comment by ccempathy** [comment]
Hi @icarpis, I don't modified the launch file . I just make it according to source code and the whole output is below.

![2018-01-31 20-54-45](https://user-images.githubusercontent.com/32675546/35624450-f55b0afe-06c9-11e8-8420-daedc1a1477c.png)
![2018-01-31 20-55-04](https://user-images.githubusercontent.com/32675546/35624452-f58bc932-06c9-11e8-8bcb-522b9e0182d3.png)

**Comment by icarpis** [comment]
It looks that the camera has recognized as USB2 device (Device Product ID: 0AD6).
Have you connected it to USB3 port? if yes, could you please check again with another USB cable?

**Comment by ccempathy** [comment]
I connect the camera to USB3 now and I try to make it connect the another port.But it still show the problem and I can open the camera by realsenseviwer .

**Comment by icarpis** [comment]
please post the output of `lsusb` while the camera connected to USB3 port.

**Comment by ccempathy** [comment]
Ok!Those are the two ports' results of my computer.

![2018-01-31 21-55-06](https://user-images.githubusercontent.com/32675546/35626824-df5fc4d0-06d1-11e8-8415-9bbcd7e13b0e.png)

**Comment by ccempathy** [comment]
@icarpis  I compiled the source code of ros wrapper (2.0.2) you uploaded just now. But when I ran the launch file it still showed the 2.0.1 of version.
![2018-01-31 22-12-44](https://user-images.githubusercontent.com/32675546/35627442-e267e6e2-06d3-11e8-81ce-7f49da0284b4.png)

**Comment by icarpis** [comment]
@ccempathy, sorry for this issue, I've fixed it. please take it again from [here](https://github.com/intel-ros/realsense/tree/2.0.2).

**Comment by icarpis** [comment]
Regarding the `lsusb` output, it seems that both ports aren't USB3 compliance.
You can check which USB version the USB controller is supported by typing `lsusb -t`.

**Comment by ccempathy** [comment]
This is the output by typing lsusb -t below.The camera is connected to the port belong to bus 002 and it shows that the port on the bus 002 is USB 3.0 .
![2018-02-01 10-57-45](https://user-images.githubusercontent.com/32675546/35659136-93af23aa-073f-11e8-9c41-f31e5151b765.png)

**Comment by icarpis** [comment]
The 5 GB/s speed claimed by **Bus 02** means that it's a **USB3** interface and in other hand, the 480 MB/s speed claimed by **Bus 01**  means that it's a **USB2** interface .

**Comment by ccempathy** [comment]
Now it can work succesfully.It is the 2.0 connecting line that result in the question.Thanks a lot for your help!

**Comment by ccempathy** [comment]
@icarpis My camera is functioning correctly in the RealSense Viewer software that comes with the RealSense SDK 2.0.The detection picture is as follows.And i can run the order 'roslaunch realsense_ros_camera rs_camera.launch' to get the rgb picture.But When i run the order 'roslaunch realsense_ros_camera rs_rgbd.launch' to try to get pointcloud data. It fails and shows the mistake as follows. 
/home/tju/Pictures/Screenshot from 2018-03-06 20:40:56.png

**Comment by ccempathy** [comment]
@icarpis   My camera is functioning correctly in the RealSense Viewer software  that comes with the RealSense SDK 2.0.The detection picture is as  follows.And i can run the order 'roslaunch realsense_ros_camera  rs_camera.launch' to get the rgb picture.But When i run the order  'roslaunch realsense_ros_camera rs_rgbd.launch' to try to get pointcloud  data. It fails and shows the mistake as follows.
--
![screenshot from 2018-03-06 20 40 56](https://user-images.githubusercontent.com/32675546/37252584-41bd3856-255e-11e8-9112-e8526625a674.png)

**Comment by MengNan-Li** [comment]
@ccempathy Eval command is used in ROS Kinetic, not available for indigo version
