### ISSUE TITLE
D435i on Jetson Orin Nano (No devices found)

### ISSUE THREAD

**Issue by Genozen** [realsenseai/realsense-ros#3015]
| Required Info                         |                                                                                         |
|---------------------------------|------------------------------------------------------------ |
| Camera Model                       | { D435i }                          | 
| Firmware Version                   |                        | 
| Operating System & Version |   Jetpack 6 + Ubuntu 22.04 | 
| Kernel Version (Linux Only)    |  5.15.122-tegra                                                                       | 
| Platform                                 | Jetson Orin Nano 8Gb Dev Kit                          |
| Librealsense SDK Version       |  { 2? }                                                    | 
| ROS Distro			         |  {Humble}                                           | 
| RealSense ROS Wrapper Version   |  {most up-to-date one}                                                  | 

### Issue Description

Hi, I've tried to follow the Jetson installation guide in this link: https://github.com/IntelRealSense/realsense-ros
but encountered some issues, so I decided to just do:
`sudo apt install ros-humble-realsense2*`
`sudo apt install ros-humble-realsense2-*`

Which succeeded, and after `sourc /opt/ros/humble/setup.bash` I was able to run:
`ros2 launch realsense2_camera rs_launch.py`

but get `No RealSense devices were found`

I checked `rs-enumerate-devices` and no devices in list
I checked `lsusb` and see that RealSense is recognized in the USB list...

Any suggestions?

**Comment by MartyG-RealSense** [comment]
Hi @Genozen  It sounds as though you followed the Option 1 procedure (sudo apt install) and then performed Option 2.  Options 1 and 2 are two different methods of installation (package and source code respectively).  Only one or the other should be used but not both methods.

If you created a **/ros2_ws/src** catkin workspace folder as part of the Method 2 installation procedure, could you delete that entire folder please to remove the source code install of the wrapper and then try launching again to see what happens.

**Comment by MartyG-RealSense** [comment]
Hi @Genozen  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
