### ISSUE TITLE
Error building realsense2_camera : Could not find a package configuration file provided by   "diagnostic_updater"

### ISSUE THREAD

**Issue by shrutic12** [realsenseai/realsense-ros#3016]
----------------------------------------------------------------------------------------------------

| Required Info                         |                                                                                         |
|---------------------------------|------------------------------------------------------------ |
| Camera Model                       | { D435i }                          | 

| Operating System & Version |   { Ubuntu 22.04 } | 
| ROS Distro			         |  Humble                                         | 
| RealSense ROS Wrapper Version   |  {4.51.1, 4.54.1, etc..}                                                  | 

### Issue Description
Hello, I have clones the realsense - ros repository as a submodule into my workspace. Hwevevr when I build I have the following issue : 

![Screenshot from 2024-02-22 15-04-24](https://github.com/IntelRealSense/realsense-ros/assets/115753016/ece63a99-268a-4535-9ede-2592f0326270)

Any help would be great!

**Comment by MartyG-RealSense** [comment]
Hi @shrutic12  Is your issue resolved if you install **diagnostic-updater** for Humble using the command below, please?

`sudo apt-get install ros-humble-diagnostic-updater`

**Comment by MartyG-RealSense** [comment]
Hi @shrutic12  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
