### ISSUE TITLE
No point cloud?

### ISSUE THREAD

**Issue by j5207** [realsenseai/realsense-ros#302]
Hi all:
When I'm trying to roslaunch the point cloud by typing:
`roslaunch realsense_ros_camera rs_rgbd.launch`
The point cloud doesn't appear and nothing showing up.
The terminal looks like this:
![screenshot from 2018-01-31 18-59-01](https://user-images.githubusercontent.com/33009871/35654009-d4c24890-06b8-11e8-961d-416b182089c4.png)
Also the camera works well with realsense-viewer
I'm using Ubuntu 16.04 with Kinetic, Realsense D415, and librealsense-2.91 and realsense-2.02
It would be really helpful if anyone could help me out.

Thanks for time

**Comment by icarpis** [comment]
Hello @j5207, running the `rs_rgbd.launch` by itself is not enough to visualize the RGBD. this Launch file is actually publishing the [ROS topics](http://wiki.ros.org/Topics) of RGBD point-cloud and the other available streams. One way to visualize the point-cloud is by using [RViz](http://wiki.ros.org/rviz) tool as the following:
1. Open Terminal and type `roslaunch realsense_ros_camera rs_rgbd.launch`
2. Open another Terminal and type `rviz`
3. Click on the `Add` button at the left bottom of the RViz window.
4. Click on the `By topic` tab.
5. Choose `pointcloud2` under `depth_registered` -> `points` and click `OK`

![screenshot from 2018-02-01 11-04-14](https://user-images.githubusercontent.com/17433152/35670057-e4e0448e-073f-11e8-8604-1bda524035c5.png)

**Comment by j5207** [comment]
@icarpis Thanks!
