### ISSUE TITLE
 symbol lookup error: /home/jetson/catkin_ws/devel/lib//librealsense2_camera.so: undefined symbol: _ZN2cv3MatC1Ev

### ISSUE THREAD

**Issue by tanu-04** [realsenseai/realsense-ros#3020]
I was trying setting up intel realsense but while :
but whilew trying to start camera node-
roslaunch realsense2_camera rs_camera.launch:
i got the error given below:

along with it while running (realsense-viewer) cli I am just getting stereo and motion data not the RGB one!
it says no frames recieved !
are these interelated and how to solve this issue?

----------------------------------------------------------------------------------------------------

| Required Info                         |                                                                                         |
|---------------------------------|------------------------------------------------------------ |
| Camera Model                       | {  D435i  }                          | 
| Firmware Version                   | (Open RealSense Viewer --> Click info)                          | 
| Operating System & Version |   { Jetson NANO 4.6.4 ubuntu 20.04} | 
| Kernel Version (Linux Only)    |  4.9                                                              | 
| Platform                                 | NVIDIA Jetson                            |
| Librealsense SDK Version       |  { 2.0}                                                    | 
| Language                               |  { }         | 
| Segment			         |  {-}                           | 
| ROS Distro			         |  {ROS NOETIC. }                                           | 
| RealSense ROS Wrapper Version   |  {}                                                  | 

### Issue Description
 symbol lookup error: /home/jetson/catkin_ws/devel/lib//librealsense2_camera.so: undefined symbol: _ZN2cv3MatC1Ev
[ INFO] [1708698737.307749078]: Done Setting Dynamic reconfig parameters.
/opt/ros/noetic/lib/nodelet/nodelet: symbol lookup error: /home/jetson/catkin_ws/devel/lib//librealsense2_camera.so: undefined symbol: _ZN2cv3MatC1Ev
[camera/realsense2_camera_manager-2] process has died [pid 17289, exit code 127, cmd /opt/ros/noetic/lib/nodelet/nodelet manager __name:=realsense2_camera_manager __log:=/home/jetson/.ros/log/54f5efdc-d258-11ee-a0d9-0f05411355b2/camera-realsense2_camera_manager-2.log].
log file: /home/jetson/.ros/log/54f5efdc-d258-11ee-a0d9-0f05411355b2/camera-realsense2_camera_manager-2*.log

**Comment by MartyG-RealSense** [comment]
Hi @tanu-04  This particular error can be complicated to resolve, unfortunately.  A Jetson user who was also using Noetic and experienced the same error shared their solution at https://github.com/IntelRealSense/realsense-ros/issues/2467#issuecomment-1268417031

Please ensure that the RealSense Viewer and the ROS wrapper are not being run at the same time.

**Comment by MartyG-RealSense** [comment]
Hi @tanu-04  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
