### ISSUE TITLE
multiple rs-435i cameras damaged/stopped.

### ISSUE THREAD

**Issue by wendwosenbb** [realsenseai/realsense-ros#3034]
----------------------------------------------------------------------------------------------------

| Required Info                         |                                                                                         |
|---------------------------------|------------------------------------------------------------ |
| Camera Model                       | { D405 / D415 / D435 / **D435i** / D455 / D457 }                          | 
| Firmware Version                   | (Open RealSense Viewer --> Click info)                          | 
| Operating System & Version |   { Win (10/11) / **Linux (Ubuntu 18/20/22)** / MacOS } | 
| Kernel Version (Linux Only)    |  (e.g. 5.15)                                                                       | 
| Platform                                 | **PC**/Raspberry Pi/ NVIDIA Jetson / etc..                           |
| Segment			         |  {**Robot**/Smartphone/VR/AR/others }                             | 
| ROS Distro			         |  {Iron/**Humble**/Rolling/etc.. }                                           | 
| RealSense ROS Wrapper Version   |  {4.51.1, **4.54.1**, etc..}                                                  | 

@MartyG-RealSense  
This is the 5th time rs-435i camera got damaged/stopped working after connecting to usb-c port on nuc-11 compute. 

The only way to safely use the camera is to plug it through usb hub that connects to nuc-11.

we measured the voltage on the usb-c port of nuc-11 it spikes to 8v and that seemed to damaged our cameras.

It has been costly.  Is there any particular limitation  that I am not aware of or restriction on usb-c port usage.

**Comment by wendwosenbb** [comment]
rs-435i camera was working until yesterday, when someone unplugged the usbc port form the usb-hub and plugged it to nuc--11 directly, that damage the camera. 

[realsense2_camera_node-1] [INFO] [1709661829.164238045] [stereo_camera.stereo_camera]: RealSense ROS v4.54.1
[realsense2_camera_node-1] [INFO] [1709661829.164372114] [stereo_camera.stereo_camera]: Built with LibRealSense v2.54.1
[realsense2_camera_node-1] [INFO] [1709661829.164390854] [stereo_camera.stereo_camera]: Running with LibRealSense v2.54.1
[realsense2_camera_node-1] [WARN] [1709661829.173163914] [stereo_camera.stereo_camera]: No RealSense devices were found!
[realsense2_camera_node-1] [WARN] [1709661835.180983763] [stereo_camera.stereo_camera]: No RealSense devices were found!
[realsense2_camera_node-1] [WARN] [1709661841.190699589] [stereo_camera.stereo_camera]: No RealSense devices were found!

also, rs-enumerate-devices 

**No device detected. Is it plugged in?**

**Comment by MartyG-RealSense** [comment]
Hi @wendwosenbb  Thanks very much for the information.  Under normal conditions RealSense cameras should not be damaged at all by unplugging them from one port and inserting them into another.  

I note that you have measured an 8v spike on the USB port of your NUC-11.  I am not aware of past reports of damage to RealSense cameras in this way, though my research of USB power spikes in general indicates that it can damage the USB port on electronic devices.

Have you tested the camera with a different USB cable to establish whether possible damage is In the cable rather than the camera's micro USB port?  Have you also tried having the USB cable inserted into the camera in both directions (USB-C cables are two-way insertion at the micro sized end).

**Comment by MartyG-RealSense** [comment]
Hi @wendwosenbb  Do you require further assistance with this case, please?  Thanks!

**Comment by wendwosenbb** [comment]
No. thank you for you quick response.

**Comment by MartyG-RealSense** [comment]
You are very welcome.  As you do not require further assistance, I will close this case.  Thanks again!
