### ISSUE TITLE
Does it support ROS2 Foxy version?

### ISSUE THREAD

**Issue by LHZ-code** [realsenseai/realsense-ros#3036]
why???
if("$ENV{ROS_DISTRO}" STREQUAL "humble")
  message(STATUS "Build for ROS2 Humble")
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DHUMBLE")
  set(SOURCES "${SOURCES}" src/ros_param_backend.cpp)
elseif("$ENV{ROS_DISTRO}" STREQUAL "iron")
  message(STATUS "Build for ROS2 Iron")
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DIRON")
  set(SOURCES "${SOURCES}" src/ros_param_backend.cpp)
elseif("$ENV{ROS_DISTRO}" STREQUAL "rolling")
  message(STATUS "Build for ROS2 Rolling")
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DROLLING")
  set(SOURCES "${SOURCES}" src/ros_param_backend.cpp)
else()

colcon build
Starting >>> realsense2_camera_msgs
Finished <<< realsense2_camera_msgs [2.35s]                     
Starting >>> realsense2_camera
Starting >>> realsense2_description              
Finished <<< realsense2_description [1.43s]                                                  
--- stderr: realsense2_camera                          
CMake Error at CMakeLists.txt:167 (message):
  Unsupported ROS Distribution: foxy

make: *** [Makefile:742：cmake_check_build_system] 错误 1
---
Failed   <<< realsense2_camera [2.64s, exited with code 2]

Summary: 2 packages finished [12.3s]
  1 package failed: realsense2_camera
  1 package had stderr output: realsense2_camera

**Comment by MartyG-RealSense** [comment]
Hi @LHZ-code  The 4.54.1 version of the RealSense ROS2 wrapper only supports Humble and Iron.  

If you need to use Foxy then a possible option that you could investigate is to build an older **forked** version of 4.54.1 that was created by RealSense ROS users before Foxy support was removed from the official version of the 4.54.1 wrapper.  https://github.com/IntelRealSense/realsense-ros/issues/2852#issuecomment-1687644669 has more information about this.

**Comment by MartyG-RealSense** [comment]
Hi @LHZ-code  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
