### ISSUE TITLE
WARNING [139770164401920] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11

### ISSUE THREAD

**Issue by Avinaashmani** [realsenseai/realsense-ros#3047]
I am using an Intel Realsense 455, with SDK 5.0 and FW 2.13. I am getting this error message on my terminal when i use with real-sense viewer and with ROS (Noetic). 

Could any one assist me sorting this issue.

----------------------------------------------------------------------------------------------------

| Required Info                         |                                                                                         |
|---------------------------------|------------------------------------------------------------ |
| Camera Model                      D455                        | 
| Firmware Version                   | (Open RealSense Viewer --> Click info)                          | 
| Operating System & Version | Ubuntu 20.04 (Focal) along with ROS noetic.                                                                   | 
| Platform                                 | PC                     |

**Comment by MartyG-RealSense** [comment]
Hi @Avinaashmani  Can you check your SDK and firmware version numbers please?  SDK versions start with the number 2 and firmwares with the number 5.  For example, if you wanted to use ROS1 Noetic with the RealSense ROS wrapper then the following configuration should be used.

SDK: 2.50.0 or 2.51.1
ROS wrapper: 2.3.2
Firmware: 5.13.0.50

In regard to the `control_transfer returned` message, it indicates a commuication problem between the camera and the computer / computing device, such as a USB cable or port problem.  Sometimes RViz can still display streams correctly though even when control_transfer returned messages are generating continuously in the log.

Are you able to successfully enable streams in the RealSense Viewer tool despite the terminal warnings?

**Comment by Avinaashmani** [comment]
I did, and I made sure they all match.

**Comment by MartyG-RealSense** [comment]
Can you view the ROS depth and color streams in RViz even when `control_transfer returned` messages are generating in the log?  Or is there no data published?

**Comment by MartyG-RealSense** [comment]
Hi @Avinaashmani  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
