### ISSUE TITLE
publish_static_tf mixing axes

### ISSUE THREAD

**Issue by piotrpolatowski** [realsenseai/realsense-ros#305]
Hello,

I am curious why in `publish_static_tf` translation values are mixed, instead of assigning `x` or `trans.x`,`y` to `trans.y`, `z` to `trans.z`.

`void BaseRealSenseNode::publish_static_tf` line: 907
```
...
    msg.transform.translation.x = trans.z;
    msg.transform.translation.y = -trans.x;
    msg.transform.translation.z = -trans.y;
...
```
The first intuitive guess would be that `x` axis goes along image width (left to right), `y` along height (top to bottom) and `z` facing front. However the trick with swapping values changes that.

My initial guess was that flipping axes is a trick applying rotation, however if it was actually rotation the quaternion should also be rotated.

**Comment by icarpis** [comment]
Hello @piotrpolatowski, the idea by doing this is to convert the axes system from the ROS standard axes system into optical frame axes system. see below 
![drawing1](https://user-images.githubusercontent.com/17433152/36248285-9fdc5c46-123f-11e8-8511-be1d798f1397.png)

You can find more details at the following link: [Coordinate Conventions](http://www.ros.org/reps/rep-0103.html#coordinate-frame-conventions)

**Comment by piotrpolatowski** [comment]
@icarpis Thank you for the link with details. I misunderstood the original ROS Axes system.
