### ISSUE TITLE
Read realsense Images form ros2 

### ISSUE THREAD

**Issue by MessiahAbE** [realsenseai/realsense-ros#3055]
User
Hello,
I have connected a RealSense camera to a Raspberry Pi. When I try to use it with a remote PC, the frequency of retrieved images is low(around 1 ). Is there a way to increase it?

**Comment by MartyG-RealSense** [comment]
Hi @MessiahAbE  Are you using a wired or wireless connection to communicate between the remote PC and the Pi with the camera attached, please?

**Comment by MartyG-RealSense** [comment]
Hi @MessiahAbE  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
