### ISSUE TITLE
RPi5 + ROS2 + realsense2_camera = No RealSense devices were found

### ISSUE THREAD

**Issue by chrismatthieu** [realsenseai/realsense-ros#3065]
I'm trying to get either a D435 or D455 RealSense Camera running on Raspberry Pi 5 (latest Bookwork OS release) and ROS2. Everything installs correctly but "No RealSense devices were found" errors displays using D435 or D455.

Here's my setup:

Raspberry Pi 5 with Debian Bookworm OS
https://docs.ros.org/en/iron/How-To-Guides/Installing-on-Raspberry-Pi.html 

https://docs.ros.org/en/iron/How-To-Guides/Using-Python-Packages.html
docker pull ros 
sudo docker run -it --rm ros

ROS RealSense: https://github.com/IntelRealSense/realsense-ros?tab=readme-ov-file 
sudo apt update 
sudo apt install ros-humble-realsense2-camera
apt pkg list | grep “real”

^ returns:
realsense2_camera
realsense2_camera_msgs

Next I run:
ros2 launch realsense2_camera rs_launch.py

^ returns:
https://gist.github.com/chrismatthieu/ce404568c474af2368b651205f7a0b18

**Comment by MartyG-RealSense** [comment]
Hi @chrismatthieu  Does it make a difference if you add **--privileged** to your Docker instruction, please?

`sudo docker run -it --privileged --rm ros`

**Comment by chrismatthieu** [comment]
That worked!  Thank you :)

**Comment by MartyG-RealSense** [comment]
It's great to hear that the --priviliged setting worked for you.  Thanks very much for the update!

**Comment by MaimonidesA** [comment]
Hi everyone, I tried the same but with the D435i and the ' --privileged ' flag doesn't do the trick, anyone have any idea ?
My Docker file --  
```
FROM ros:humble-ros-base

RUN sudo apt-get update \ 
    && apt-get install -y \
    nano \
    vim \
    && rm -rf /var/lib/apt/lists/*

# Installing rviz2
RUN sudo apt-get update \ 
    && apt-get install -y \
    ros-humble-rviz2 ros-humble-rqt \
    && rm -rf /var/lib/apt/lists/*

# Install Nav2 packages
RUN apt-get update && apt-get install -y \
   ros-$ROS_DISTRO-navigation2 \
   ros-$ROS_DISTRO-nav2-bringup \
   ros-$ROS_DISTRO-robot-localization \
   ros-$ROS_DISTRO-slam-toolbox \
   && rm -rf /var/lib/apt/lists/*

# Install realsense2 joint-state-publisher xacro packages
RUN apt-get update && apt-get install -y \
   ros-$ROS_DISTRO-realsense2-camera \
   ros-$ROS_DISTRO-joint-state-publisher-gui \
   ros-$ROS_DISTRO-xacro \
   && rm -rf /var/lib/apt/lists/*

# Example of copying a file
COPY config/ /site_config/

# Create a non-root user
ARG USERNAME=ros
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN groupadd --gid $USER_GID $USERNAME \
  && useradd -s /bin/bash --uid $USER_UID --gid $USER_GID -m $USERNAME \
  && mkdir /home/$USERNAME/.config && chown $USER_UID:$USER_GID /home/$USERNAME/.config

# Set up sudo
RUN apt-get update \
  && apt-get install -y sudo \
  && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME\
  && chmod 0440 /etc/sudoers.d/$USERNAME \
  && rm -rf /var/lib/apt/lists/*

# Copy the entrypoint and bashrc scripts so we have 
# our container's environment set up correctly
COPY entrypoint.sh /entrypoint.sh
COPY bashrc /home/${USERNAME}/.bashrc

# Set up entrypoint and default command
ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]
CMD ["bash"]
```
My run command --
```
$ docker run --name ros2_humble  \
-h ros2dk  \
-v /home/antonio-pi/Antonio/:/antonio_ws --network host \
-v /tmp/.X11-unix:/tmp/.X11-unix \
-e DISPLAY=$DISPLAY \ 
-v /home/cooneo/Desktop/pico_ws \
--device /dev/gpiomem \
--device /dev/i2c-1 \
--device /dev/ttyACM0  \
--device /dev/ttyUSB0  \
--privileged  -it --rm antonio-ros 
```


Bash output -- ![Screenshot 2024-04-04 155437](https://github.com/IntelRealSense/realsense-ros/assets/132435078/75836f91-5557-4c64-b28a-916824ebbbaf)

**Comment by chrismatthieu** [comment]
Here’s my working docker container: https://hub.docker.com/r/chrismatthieu/rpi5-ros2-realsense2On Apr 4, 2024, at 6:18 AM, MaimonidesA ***@***.***> wrote:﻿
Hi everyone, I tried the same but with the D435i and the ' --privileged ' flag doesn't do the trick, anyone have any idea ?
My Docker file --
FROM ros:humble-ros-base

RUN sudo apt-get update \ 
    && apt-get install -y \
    nano \
    vim \
    && rm -rf /var/lib/apt/lists/*

# Installing rviz2
RUN sudo apt-get update \ 
    && apt-get install -y \
    ros-humble-rviz2 ros-humble-rqt \
    && rm -rf /var/lib/apt/lists/*

# Install Nav2 packages
RUN apt-get update && apt-get install -y \
   ros-$ROS_DISTRO-navigation2 \
   ros-$ROS_DISTRO-nav2-bringup \
   ros-$ROS_DISTRO-robot-localization \
   ros-$ROS_DISTRO-slam-toolbox \
   && rm -rf /var/lib/apt/lists/*

# Install realsense2 joint-state-publisher xacro packages
RUN apt-get update && apt-get install -y \
   ros-$ROS_DISTRO-realsense2-camera \
   ros-$ROS_DISTRO-joint-state-publisher-gui \
   ros-$ROS_DISTRO-xacro \
   && rm -rf /var/lib/apt/lists/*

# Example of copying a file
COPY config/ /site_config/

# Create a non-root user
ARG USERNAME=ros
ARG USER_UID=1000
ARG USER_GID=$USER_UID

RUN groupadd --gid $USER_GID $USERNAME \
  && useradd -s /bin/bash --uid $USER_UID --gid $USER_GID -m $USERNAME \
  && mkdir /home/$USERNAME/.config && chown $USER_UID:$USER_GID /home/$USERNAME/.config

# Set up sudo
RUN apt-get update \
  && apt-get install -y sudo \
  && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME\
  && chmod 0440 /etc/sudoers.d/$USERNAME \
  && rm -rf /var/lib/apt/lists/*

# Copy the entrypoint and bashrc scripts so we have 
# our container's environment set up correctly
COPY entrypoint.sh /entrypoint.sh
COPY bashrc /home/${USERNAME}/.bashrc

# Set up entrypoint and default command
ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]
CMD ["bash"]

My run command --
$ docker run --name ros2_humble  \
-h ros2dk  \
-v /home/antonio-pi/Antonio/:/antonio_ws --network host \
-v /tmp/.X11-unix:/tmp/.X11-unix \
-e DISPLAY=$DISPLAY \ 
-v /home/cooneo/Desktop/pico_ws \
--device /dev/gpiomem \
--device /dev/i2c-1 \
--device /dev/ttyACM0  \
--device /dev/ttyUSB0  \
--privileged  -it --rm antonio-ros 

Bash output -- Screenshot.2024-04-04.155437.png (view on web)

**Comment by MaimonidesA** [comment]
> Here’s my working docker container: https://hub.docker.com/r/chrismatthieu/rpi5-ros2-realsense2On Apr 4, 2024, at 6:18 AM, 

Hey sorry to bother, can't open the link, thank you very much for the respond.

**Comment by chrismatthieu** [comment]
https://hub.docker.com/r/chrismatthieu/rpi5-ros2-realsense2

**Comment by tedlin0913** [comment]
@chrismatthieu Brother, could you please share your Dockerfile? thank you.

**Comment by chrismatthieu** [comment]
Here you go :)


https://hub.docker.com/repository/docker/chrismatthieu/rpi5-ros2-realsense2/general￼
hub.docker.com

**Comment by tedlin0913** [comment]
Thank you so much for the response, however, can't open the link, got 404.

**Comment by chrismatthieu** [comment]
Try this link - https://hub.docker.com/r/chrismatthieu/rpi5-ros2-realsense2

**Comment by matbeedotcom** [comment]
can you share the dockerfile contents, I cant view the source dockerfile
