### ISSUE TITLE
RuntimeError: Frame didn't arrive within 5000  | intel realsense 435i

### ISSUE THREAD

**Issue by Muhammadjunaidmalik1** [realsenseai/realsense-ros#3080]
Hi ! 
I am using intel real sense camera with python wrapper. I am using official cable provided by intel to connect the camera to my laptop. Although its working for lower resolution. I need 1280 x 720 configuration for my application. But when i run : 

`cfg.enable_stream(rs.stream.color, 1280,720,rs.format.bgr8, 30)`

I am getting this error. I am getting this error even with low frame rate (i have tried 10 and 15). 

```
    frame = pipe.wait_for_frames()
RuntimeError: Frame didn't arrive within 5000

```

Looking forward for you kind response.

Best regards,
Muhammad Junaid

----------------------------------------------------------------------------------------------------

| Required Info                         |                                                                                         |
|---------------------------------|------------------------------------------------------------ |
| Camera Model                       | D435i                       | 
| Firmware Version                   | 5.13.0.50                          | 
| Operating System & Version | Ubuntu 20                                                                    | 
| Kernel Version (Linux Only)    |  (e.g. 5.4)                                                                       | 
| Platform                                 | PC with intel corei7 (7th gen)                     |
| Librealsense SDK Version       | 2.54.2.0                                                    | 
| Language                               |  python          | 
| Segment			         |  AR                             |

**Comment by MartyG-RealSense** [comment]
Hi @Muhammadjunaidmalik1  If you have a D435i then you can also use 1280x720 at 6 FPS.  Does the error still occur at 6 FPS please?

**Comment by MartyG-RealSense** [comment]
Hi @Muhammadjunaidmalik1  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
