### ISSUE TITLE
video frame dropped ,video and metadata buffers inconsistency

### ISSUE THREAD

**Issue by Zhangyogoe** [realsenseai/realsense-ros#3083]
D455,ros2 launch realsense2_camera rs_launch.py报错video frame dropped ,video and metadata buffers inconsistency

**Comment by MartyG-RealSense** [comment]
Hello, do you have the same problems if you launch with **ros2 run** instead of ros2 launch, please?

`ros2 run realsense2_camera realsense2_camera_node`

**Comment by MartyG-RealSense** [comment]
Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
