### ISSUE TITLE
ROS 2 Image Display Issues 

### ISSUE THREAD

**Issue by ekfrckato** [realsenseai/realsense-ros#3099]
* Before opening a new issue, we wanted to provide you with some useful suggestions (Click "Preview" above for a better view):

    * Consider checking our ROS RealSense Wrapper documentation [README](https://github.com/IntelRealSense/realsense-ros/blob/ros2-development/README.md).
    * Have you looked in our [Discussions](https://github.com/IntelRealSense/realsense-ros/discussions)?
    * Try [searching our GitHub Issues](https://github.com/IntelRealSense/realsense-ros/issues) (open and closed) for a similar issue.

* All users are welcomed to report bugs, ask questions, suggest or request enhancements and generally feel free to open new issue, even if they haven't followed any of the suggestions above :)

----------------------------------------------------------------------------------------------------

| Required Info                         |                                                                                         |
|---------------------------------|------------------------------------------------------------ |
| Camera Model                       | D415   | 
| Firmware Version                   | 5.15.1 | 
| Operating System & Version |   Linux | 
| Kernel Version (Linux Only)    |  6.5.0  | 
| Platform                                 | PC      |
| Librealsense SDK Version       |  { 2.55.1 }            | 
| Language                               | python   | 
| Segment			         |  Robot                       | 
| ROS Distro			         |  humble         | 
| RealSense ROS Wrapper Version   |                                              | 

### Issue Description

Until yesterday, everything was working fine. However, starting today, I can no longer load images through the Realsense SDK.

I confirmed that the Realsense camera is working properly in the viewer, so it does not seem to be a device recognition issue. When I open the Realsense camera, I use this command:
`ros2 launch realsense2_camera rs_launch.py clip_distance:=1.0 spatial_filter.enable:=true temporal_filter.enable:=true decimation_filter.enable:=true enable_color:=true rgb_camera.profile:=1280x720x30 initial_reset:=true enable_depth:=true`
The node reports that it has opened successfully.

> ros2 launch realsense2_camera rs_launch.py clip_distance:=1.0 spatial_filter.enable:=true temporal_filter.enable:=true decimation_filter.enable:=true enable_color:=true rgb_camera.profile:=1280x720x30 initial_reset:=true enable_depth:=true
> [INFO] [launch]: All log files can be found below /home/cae/.ros/log/2024-05-11-19-33-01-649451-cae-H310M-HD3-2-0-68974
> [INFO] [launch]: Default logging verbosity is set to INFO
> [INFO] [realsense2_camera_node-1]: process started with pid [68976]
> [realsense2_camera_node-1] [INFO] [1715423581.887592835] [camera.camera]: RealSense ROS v4.54.1
> [realsense2_camera_node-1] [INFO] [1715423581.887670466] [camera.camera]: Built with LibRealSense v2.54.1
> [realsense2_camera_node-1] [INFO] [1715423581.887681546] [camera.camera]: Running with LibRealSense v2.54.1
> [realsense2_camera_node-1] [INFO] [1715423581.894249109] [camera.camera]: Device with serial number 953122060800 was found.
> [realsense2_camera_node-1]
> [realsense2_camera_node-1] [INFO] [1715423581.894279728] [camera.camera]: Device with physical ID /sys/devices/pci0000:00/0000:00:14.0/usb2/2-4/2-4:1.0/video4linux/video0 was found.
> [realsense2_camera_node-1] [INFO] [1715423581.894288416] [camera.camera]: Device with name Intel RealSense D415 was found.
> [realsense2_camera_node-1] [INFO] [1715423581.894409219] [camera.camera]: Device with port number 2-4 was found.
> [realsense2_camera_node-1] [INFO] [1715423581.894419880] [camera.camera]: Device USB type: 3.2
> [realsense2_camera_node-1] [INFO] [1715423581.894426146] [camera.camera]: Resetting device...
> [realsense2_camera_node-1] [INFO] [1715423588.116330290] [camera.camera]: Device with serial number 953122060800 was found.
> [realsense2_camera_node-1]
> [realsense2_camera_node-1] [INFO] [1715423588.116373647] [camera.camera]: Device with physical ID /sys/devices/pci0000:00/0000:00:14.0/usb2/2-4/2-4:1.0/video4linux/video0 was found.
> [realsense2_camera_node-1] [INFO] [1715423588.116397398] [camera.camera]: Device with name Intel RealSense D415 was found.
> [realsense2_camera_node-1] [INFO] [1715423588.116554126] [camera.camera]: Device with port number 2-4 was found.
> [realsense2_camera_node-1] [INFO] [1715423588.116578986] [camera.camera]: Device USB type: 3.2
> [realsense2_camera_node-1] [INFO] [1715423588.117181349] [camera.camera]: getParameters...
> [realsense2_camera_node-1] [INFO] [1715423588.117447030] [camera.camera]: JSON file is not provided
> [realsense2_camera_node-1] [INFO] [1715423588.117460090] [camera.camera]: Device Name: Intel RealSense D415
> [realsense2_camera_node-1] [INFO] [1715423588.117479723] [camera.camera]: Device Serial No: 953122060800
> [realsense2_camera_node-1] [INFO] [1715423588.117485276] [camera.camera]: Device physical port: /sys/devices/pci0000:00/0000:00:14.0/usb2/2-4/2-4:1.0/video4linux/video0
> [realsense2_camera_node-1] [INFO] [1715423588.117491169] [camera.camera]: Device FW version: 5.15.1
> [realsense2_camera_node-1] [INFO] [1715423588.117498433] [camera.camera]: Device Product ID: 0x0AD3
> [realsense2_camera_node-1] [INFO] [1715423588.117504003] [camera.camera]: Sync Mode: Off
> [realsense2_camera_node-1] [INFO] [1715423588.221869563] [camera.camera]: Set Exposure.1 to 7500
> [realsense2_camera_node-1] [INFO] [1715423588.227236094] [camera.camera]: Set ROS param depth_module.profile to default: 1280x720x30
> [realsense2_camera_node-1] [INFO] [1715423588.239298170] [camera.camera]: Stopping Sensor: Depth Module
> [realsense2_camera_node-1] [INFO] [1715423588.239431235] [camera.camera]: Stopping Sensor: RGB Camera
> [realsense2_camera_node-1] [INFO] [1715423588.242747110] [camera.camera]: Starting Sensor: Depth Module
> [realsense2_camera_node-1] [INFO] [1715423588.266254736] [camera.camera]: Open profile: stream_type: Depth(0), Format: Z16, Width: 1280, Height: 720, FPS: 30
> [realsense2_camera_node-1] [INFO] [1715423588.277959139] [camera.camera]: Starting Sensor: RGB Camera
> [realsense2_camera_node-1] [INFO] [1715423588.280561062] [camera.camera]: Open profile: stream_type: Color(0), Format: RGB8, Width: 1280, Height: 720, FPS: 30
> [realsense2_camera_node-1] [INFO] [1715423588.282000750] [camera.camera]: RealSense Node Is Up!
> [realsense2_camera_node-1] [WARN] [1715423588.352309782] [camera.camera]:
> 

To test whether the image is being received correctly, I enter `ros2 run image_tools showimage image:=/camera/color/image_raw` in another terminal window, and it outputs the following:

> :~$ ros2 run image_tools showimage image:=/camera/color/image_raw
> [WARN] [1715422644.252381392] [rcl]: Found remap rule 'image:=/camera/color/image_raw'. This syntax is deprecated. Use '--ros-args --remap image:=/camera/color/image_raw' instead.
> [INFO] [1715422644.381085594] [showimage]: Subscribing to topic 'image'

I think there is a problem in receiving the message. When I enter
`ros2 topic echo /camera/color/image_raw`
it only displays a blank space and there is no response.

Yesterday, I was working and changed the version of setuptools to 58.2.0 using` pip install setuptools==58.2.0 `because I encountered a 'setup.py' error during colcon build. There were alerts about version conflicts with OpenCV and TensorFlow, but I thought it would not affect my current task, which involves processing depth data through Realsense. Indeed, everything worked fine even after changing the version yesterday. I'm not sure if this is the cause of the issue, but it's the only change I made.

Today, in an attempt to resolve the issue, I upgraded the Realsense SDK, and the current version is as specified above. Please help! 😭

**Comment by MartyG-RealSense** [comment]
Hi @ekfrckato  You should continue to use librealsense 2.54.1 with ROS wrapper 4.54.1, as there is not a wrapper for librealsense 2.55.1 at the time of writing this.  Ideally the librealsense version that should be used is the one listed in the release notes for a specific ROS wrapper verison.

Whenever the librealsense version is changed, the ROS wrapper needs to be built again.

**Comment by ekfrckato** [comment]
Then, how can i change the version? 
I did `dpkg -l | grep "realsense" | cut -d " " -f 3 | xargs sudo dpkg --purge`

`sudo mkdir -p /etc/apt/keyrings
curl -sSf https://librealsense.intel.com/Debian/librealsense.pgp | sudo tee /etc/apt/keyrings/librealsense.pgp > /dev/null`

`echo "deb [signed-by=/etc/apt/keyrings/librealsense.pgp] https://librealsense.intel.com/Debian/apt-repo 'lsb_release -cs' main" | \
sudo tee /etc/apt/sources.list.d/librealsense.list
sudo apt-get update`

and tried this `sudo apt-get install librealsense2-utils=2.54.1~0realsnese0.9591` 
> E: Version '2.54.1~0realsnese0.9591' for 'librealsense2-utils' was not found

`sudo apt-get install librealsense2-utils=2.54.1~0realsnese.tbd`
> E: Version '2.54.1~0realsnese.tbd' for 'librealsense2-utils' was not found


I am following this https://github.com/IntelRealSense/librealsense/blob/master/doc/distribution_linux.md and [#10526](https://github.com/IntelRealSense/librealsense/issues/10526). so confused which file has to be installed.

**Comment by MartyG-RealSense** [comment]
If you are trying to install a specific version from packages then it is more difficult than building from a source code folder for a particular version.  It involves using the command **apt-cache showpkg librealsense2** to find the names of the packages for that version.  More information about this can be found at https://github.com/IntelRealSense/librealsense/issues/5773#issuecomment-581477785

The two compulsory packages that need to be installed are librealsense2-dkms and librealsense2-utils

**Comment by ekfrckato** [comment]
Yes, I already found the packages.
  librealsense2-gl,librealsense2 2.54.1-0~realsense.9591
  librealsense2-dbg,librealsense2 2.54.1-0~realsense.9591
  librealsense2-utils,librealsense2 2.54.1-0~realsense.9591
  librealsense2-dev,librealsense2 2.54.1-0~realsense.9591
  librealsense2-gl,librealsense2 2.54.1-0~realsense.9588
  librealsense2-utils,librealsense2 2.54.1-0~realsense.9588
  librealsense2-dev,librealsense2 2.54.1-0~realsense.9588
  librealsense2-dbg,librealsense2 2.54.1-0~realsense.9588
but -dkms file isn't there.

and `sudo apt-get install librealsense2-utils=2.54.1~0realsnese0.9591` didn't work.

It seems like I'm unable to install it properly despite having a lot of resources. However, I'm having trouble understanding even with the references. I apologize for the inconvenience.

**Comment by ekfrckato** [comment]
I successfully changed the version. After running `sudo apt-get clean`, I installed the packages using the command `sudo apt-get install librealsense2-utils=2.54.1-0~realsense.9591 librealsense2=2.54.1-0~realsense.9591 librealsense2-gl=2.54.1-0~realsense.9591`

**Comment by MartyG-RealSense** [comment]
That's great to hear that you were successful with the version change!

**Comment by ekfrckato** [comment]
There's a new issue. I confirmed that the RealSense SDK 2.54.1 is installed and the RealSense camera is recognized properly using `realsense-viewer`. Since you mentioned that a ROS wrapper build was necessary after installing the SDK, I ran the following command in my ROS2 workspace:
`:~/ros2_ws$ colcon build --symlink-install`

But then I encountered this error:

> --- stderr: realsense2_camera_msgs
> failed to create symbolic link '/home/cae/ros2_ws/build/realsense2_camera_msgs/ament_cmake_python/realsense2_camera_msgs/realsense2_camera_msgs' because existing path cannot be removed: Is a directory
> gmake[2]: *** [CMakeFiles/ament_cmake_python_symlink_realsense2_camera_msgs.dir/build.make:70: CMakeFiles/ament_cmake_python_symlink_realsense2_camera_msgs] Error 1
> gmake[1]: *** [CMakeFiles/Makefile2:421: CMakeFiles/ament_cmake_python_symlink_realsense2_camera_msgs.dir/all] Error 2
> gmake[1]: *** Waiting for unfinished jobs....
> gmake: *** [Makefile:146: all] Error 2
> Failed <<< realsense2_camera_msgs [3.08s, exited with code 2]
> 
> Summary: 3 packages finished [3.41s]
> 1 package failed: realsense2_camera_msgs
> 1 package had stderr output: realsense2_camera_msgs
> 2 packages not processed

So I tried to reinstall the realsense2 package. **I removed the realsense-ros package from the ros2_ws** folder and deleted everything related to realsense in the build. I was following the installation for Ubuntu from this link:
https://github.com/IntelRealSense/realsense-ros?tab=readme-ov-file#installation-on-ubuntu 
But when I ran colcon build, it said **'Intel RealSense SDK 2.0 is missing.'** Wasn't the SDK installed correctly?
![Screenshot from 2024-05-12 18-07-41](https://github.com/IntelRealSense/realsense-ros/assets/94157543/de01c4c8-895e-479f-919c-dc466133161c)

**Comment by MartyG-RealSense** [comment]
In the Ubuntu installation instructions, did you use the **Option 1: Install debian package from ROS servers** instructions before then doing **Option 2: Install from source** afterwards?

When building the wrapper from source with these instructions, you are meant to ignore the Option 1 section and only do the tasks in Option 2.

**Comment by ekfrckato** [comment]
Unfortunately, despite not having executed Option 1 when I initially posted my question, an error still occurred. Later, due to my mistake, I executed Option 1 and then Option 2, but the same error persists. If executing Option 1 caused something to go awry, I would like to uninstall and reinstall everything. Is there a way to completely remove the above wrapper? I would also like to seek further advice on resolving this issue. Thank you for your help.

**Comment by ekfrckato** [comment]
![Screenshot from 2024-05-13 00-05-02](https://github.com/IntelRealSense/realsense-ros/assets/94157543/8a46810e-66ab-4110-b5d8-6c7cd82de8f4)

When I executed Option 2, an error occurred during the Install dependencies section. Should I delete that file and reinstall it?
> ERROR: default sources list file already exists:
> 	/etc/ros/rosdep/sources.list.d/20-default.list

**Comment by MartyG-RealSense** [comment]
RealSense SDK and wrapper installations based on DKMS package files can be removed from the computer with the purge instruction you mentioned earlier.

`dpkg -l | grep "realsense" | cut -d " " -f 3 | xargs sudo dpkg --purge`

If the ROS wrapper was built from source code then completely deleting the **/ros2_ws/src/** catkin workspace folder will remove it.

If the RealSense SDK was built with CMake with a source code folder then go to its 'librealsense > build' folder and from the build directory perform the command below to uninstall the SDK and clean up CMake.

**sudo make uninstall && make clean**

Advice for dealing with this rosdep error can be found at https://github.com/IntelRealSense/librealsense/issues/10562

In that case, the RealSense user deleted the sources file list as the text of the error suggested but then found that they had the same error.  What worked for them was to uninstall rosdep with the command below:

`sudo rm /etc/ros/rosdep/sources.list.d/20-default.list`

Then when they repeated the ROS wrapper installation process, they were able to reinstall the rosdep dependency with `sudo rosdep init`

**Comment by ekfrckato** [comment]
I think I had **a problem with the source.list and installing a specific version of the realsense SDK.** 

**First,** by **deleting the rosdep source.list and reinstalling rosdep** as you mentioned
(`sudo rm /etc/ros/rosdep/sources.list.d/20-default.list`) ,
> ERROR: default sources list file already exists:
> /etc/ros/rosdep/sources.list.d/20-default.list

the error mentioned above was resolved. 

**Secondly,** there was still the same realsense missing issue during the `colcon build`, but this was resolved by **setting the PATH.**

The colcon build command I tried to solve the second problem was:
`colcon build --symlink-install --packages-select realsense2_camera_msgs --cmake-clean-cache`
This worked normally, but it printed the following along with a path warning:

> If a package in a merged underlay workspace is overridden and it installs headers, then all packages in the overlay must sort their include directories by workspace order. Failure to do so may result in build failures or undefined behavior at runtime.
> If the overridden package is used by another package in any underlay, then the overriding package in the overlay must be API and ABI compatible or undefined behavior at runtime may occur.
> 
> If you understand the risks and want to override a package anyways, add the following to the command line:
> --allow-overriding realsense2_camera_msgs
> 
> This may be promoted to an error in a future release of colcon-override-check.
> 

And colcon build also did not work due to the same missing error.
So the second method I tried involved the following two commands:

```
export COLCON_PREFIX_PATH=/home/<usrname>/ros2_ws/install:$COLCON_PREFIX_PATH
export CMAKE_PREFIX_PATH=/home/<usrname>/vcpkg/installed/x64-linux/share/realsense2:$CMAKE_PREFIX_PATH
```
By specifying the SDK's path through these two commands,` colcon build `now works properly.


Actually the colcon prefix path warning still appears, stating 

> [0.366s] colcon.colcon_core.prefix_path.colcon WARNING The path '/home/cae/ros2_ws/src/install' in the environment variable COLCON_PREFIX_PATH doesn't exist. 

However, aside from this one path warning, there are no more issues with building.

**Comment by ekfrckato** [comment]
I think the ros-realsense package was built successfully. However, as shown in the picture below, I still can't tell what data is being published in the topic.
![Screenshot from 2024-05-13 19-03-53](https://github.com/IntelRealSense/realsense-ros/assets/94157543/b81758bb-abd5-46d2-b6c8-d446e1d8b044)

**Comment by MartyG-RealSense** [comment]
I cannot tell what is in the above echo of camera/color/image_raw.

Can the streams be displayed in RViz?

**Comment by ekfrckato** [comment]
**My goal is to receive depth data published by realsense-ros from a package I created.** I want to process depth data for a specific location. However, the code I wrote in my package is unable to display the data using imshow. It's hard to say it's a code issue, as it's the same code I've always used.

So, I wanted to check if the realsense-ros package is properly transmitting depth data and raw image data. To do this, I adopted the commands `ros2 run image_tools showimage image:=/camera/color/image_raw `and` ros2 topic echo /camera/color/image_raw` from the photo above. **If this is the wrong method of verification, what other method could I adopt?** Thanks as always for your help.

**Comment by MartyG-RealSense** [comment]
I would agree that a topic echo such as `ros2 topic echo /camera/color/image_raw` is a correct way of quickly checking whether messages are being published on a topic.  Once the publishing of data on the topic is confirmed then I would recommend trying to display the topic in RViz to confirm that there is a visual output.

**Comment by ekfrckato** [comment]
I checked that the topic's image is displayed correctly through Rviz. Does this mean there is no issue with the msg output? Then, is it possible that the only problem is with the code that receives my msg? I haven't modified that particular Python file.. I'm not sure what steps to take next..

**Comment by MartyG-RealSense** [comment]
If the topic's image is displayed correctly in RViz then the message output is likely to be okay.

Sometimes the log can indicate that there is a problem, such as warnings about data transfer, but RViz is able to display the streams correctly despite the log warnings.  So there is not necessarily a fault in your code.

**Comment by MartyG-RealSense** [comment]
Hi @ekfrckato  Do you require further assistance with this case, please?  Thanks!

**Comment by ekfrckato** [comment]
I haven't solved the problem yet. I'll try again and reply if there's any problem or progress.

**Comment by MartyG-RealSense** [comment]
Okay, thanks very much for the update.  Good luck!

**Comment by ekfrckato** [comment]
I've solved my problem. It was a very simple issue and my mistake. For some reason, it seems that I modified the topic path of the code that was working well. Originally, it worked well when using `/camera/camera/depth/image_rect_raw`, but the issue was that I was subscribing to the `/camera/depth/image_rect_raw depth_image` topic.... Thank you so much for all the help during this time.

**Comment by MartyG-RealSense** [comment]
You are very welcome.  It's great to hear that you found a solution.  Thanks very much for the update!

**Comment by MartyG-RealSense** [comment]
Case closed due to solution achieved and no further comments received.
