### ISSUE TITLE
d415 cnanot work

### ISSUE THREAD

**Issue by xgdgxb** [realsenseai/realsense-ros#310]
![screenshot from 2018-02-10 13-27-28](https://user-images.githubusercontent.com/7876012/36058895-2e39e120-0e67-11e8-91e6-4d1b7d9cd058.png)

**Comment by xgdgxb** [comment]
@argretzi

**Comment by icarpis** [comment]
Hello @xgdgxb, could you please post the output of `lsusb` while the D415 is connected ?

**Comment by xgdgxb** [comment]
thank you, it is because the I used USB2.0 at the first time , when I used USB3.0, it works well!
@icarpis
