### ISSUE TITLE
Announcement: RealSense ROS wrapper 4.55.1 now available

### ISSUE THREAD

**Issue by MartyG-RealSense** [realsenseai/realsense-ros#3113]
Hi everyone,

Version **4.55.1** of the RealSense ROS wrapper is now available.

https://github.com/IntelRealSense/realsense-ros/releases/tag/4.55.1

**Comment by tonynajjar** [comment]
It doesn't specify the "Supported RealSense SDK" and "Supported Devices", could you specify? Thanks

**Comment by MartyG-RealSense** [comment]
Typically, the naming of the wrapper reflects the librealsense version it is designed to work with.  For example, wrapper 4.54.1 = SDK 2.54.1.  So wrapper 4.55.1 will be for SDK 2.55.1.

The wrapper supports RealSense 400 Series cameras (such as D415, D435, D435i, D435f, D435if, D455, D455f, D456, D457).  From SDK 2.55.1 onwards though, the L515 and SR300 camera models are no longer supported.

**Comment by tonynajjar** [comment]
Thanks for the answer, this practically means that librealsense and realsense-ros always have to be upgraded together? It isn't possible e.g. to use librealsense 2.54.2 with realsenes-ros 4.55.1?

**Comment by MartyG-RealSense** [comment]
As a general rule, if a new SDK version only has a small number of changes from the previous version then you can risk using the new version with a wrapper meant for the previous one.  For example, 2.54.2 was mostly bug-fixes rather than new features and so it still works with wrapper 4.54.1.  

However, 2.55.1 has extensive feature and API changes and so a new wrapper designed specifically for it is the best choice.

**Comment by jesusramondovale** [comment]
Is it now availablevia apt-get install? Keeps giving me the 4.54 on Ubuntu 22.04 LTS jammy amd64

**Comment by MartyG-RealSense** [comment]
@jesusramondovale  The wrapper repository lists the current package version as 2.55.1.

https://index.ros.org/p/realsense2_camera/

The latest version of the wrapper should always be able to be built from source code with **colcon build** if problems with the package version are experienced.

**Comment by tonynajjar** [comment]
Hello,

One more piece of feedback, it would be nice if in the release notes, the breaking changes would be documented + what action the users should take. As an example, in this [PR](https://github.com/IntelRealSense/realsense-ros/commit/0ca251087a5a5879e3bda86de6871eb8b5f5404c), the parameter `rgb_camera.profile` was renamed to `rgb_camera.color_profile` which breaks the user configuration set for the previous version **silently**.

I found this one but I don't know what else I'm missing which might cause silent bugs in the future.

**Comment by MartyG-RealSense** [comment]
Hi @tonynajjar  The ROS wrapper release notes are usually meticulous in their detail.  Whilst it is possible for omissions to occur on rare occasions, in general their documentation of changes is highly reliable.  I appreciate you raising the point.

**Comment by tonynajjar** [comment]
I agree they are detailed, the PR i mentioned was not ommited, it is in fact mentioned [here](https://github.com/IntelRealSense/realsense-ros/releases#:~:text=Support%20for%20selecting%20profile%20for%20each%20stream_type%20by%20%40Arun%2DPrasad%2DV%20in%20%233052), my point is not that the Release Notes are lacking, just that it would be helpful to have a Migration Guide i.e. understand which changes in the release notes require a change from the user's configuration. See [Nav2's migration guides](https://docs.nav2.org/migration/index.html) as an example.

**Comment by MartyG-RealSense** [comment]
I will pass your feedback about breaking issues to the RealSense ROS development team.
