### ISSUE TITLE
Can D435 or D455 be used in a MOOS environment?

### ISSUE THREAD

**Issue by WencaiShan** [realsenseai/realsense-ros#3116]
Hello, sorry to bother you. I want to purchase the D435 or D455. Can these two products be used in a MOOS environment?

**Comment by MartyG-RealSense** [comment]
Hi @WencaiShan  It's no trouble at all.  The MIT Marine Autonomy Lab shares details at the link below of a MOOS driver for RealSense cameras and the librealsense2 SDK.

https://oceanai.mit.edu/swarmbox/pmwiki/pmwiki.php?n=Manifest.PRealSense

There is also a PDF paper about a maritime robot project using RealSense D435 and MOOS.

https://robonation.org/app/uploads/sites/2/2022/10/RX22_TDR_NYCU.pdf

**Comment by MartyG-RealSense** [comment]
Hi @WencaiShan  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
