### ISSUE TITLE
The requested device with serial number f0232572 is NOT found. Will Try again. L515

### ISSUE THREAD

**Issue by agonzat** [realsenseai/realsense-ros#3122]
----------------------------------------------------------------------------------------------------

| Required Info                         |                                                                                         |
|---------------------------------|------------------------------------------------------------ |
| Camera Model                       |  L515                       | 
| Firmware Version                   | 1.5.8.1                       | 
| Operating System & Version |  Ubuntu 22.04.4 LTS | 
| Kernel Version (Linux Only)    |  5.15.153-rt75                                         | 
| Platform                                 | PC                         |
| Librealsense SDK Version       |  2.53.1                                                   | 
| Language                               |  c++         | 
| Segment			         |  Robot                            | 
| ROS Distro			         |  Humble                                    | 
| RealSense ROS Wrapper Version   |  4.55.1                                             | 

### Issue Description

I have a setup with 2 different realsense cameras, but I get the following error:

![image](https://github.com/IntelRealSense/realsense-ros/assets/1889312/1f931898-bbcb-45df-99d6-8162036b9a85)

Using realsense-viewer, I can see both:

![image](https://github.com/IntelRealSense/realsense-ros/assets/1889312/d7b5b9b7-ef4f-47f2-a30b-6cd983ea09d8)

I have tried to launch the single camera alone but the error remains the same

**Comment by MartyG-RealSense** [comment]
Hi @agonzat  RealSense ROS2 wrapper 4.55.1 has removed support for L515 as it is a retired camera model.  L515 support has been removed in the 2.55.1 librealsense SDK.  L515 support was also removed from wrapper 4.54.1.  Please see https://github.com/IntelRealSense/realsense-ros/pull/2841 for further information.

There was not a ROS wrapper created for the 2.53.1 version of librealsense that you are using.  Wrapper 4.51.1 is likely to be the closest working match to 2.53.1 if you are using an L515 and do not want to change your librealsense installation.

**Comment by MartyG-RealSense** [comment]
Hi @agonzat  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
