### ISSUE TITLE
When can a version with "rolling" support be released?

### ISSUE THREAD

**Issue by 987640673** [realsenseai/realsense-ros#3136]
* Before opening a new issue, we wanted to provide you with some useful suggestions (Click "Preview" above for a better view):

    * Consider checking our ROS RealSense Wrapper documentation [README](https://github.com/IntelRealSense/realsense-ros/blob/ros2-development/README.md).
    * Have you looked in our [Discussions](https://github.com/IntelRealSense/realsense-ros/discussions)?
    * Try [searching our GitHub Issues](https://github.com/IntelRealSense/realsense-ros/issues) (open and closed) for a similar issue.

* All users are welcomed to report bugs, ask questions, suggest or request enhancements and generally feel free to open new issue, even if they haven't followed any of the suggestions above :)

----------------------------------------------------------------------------------------------------

| Required Info                         |                                                                                         |
|---------------------------------|------------------------------------------------------------ |
| Camera Model                       | D435i                          | 
| Firmware Version                   | (Open RealSense Viewer --> Click info)                          | 
| Operating System & Version |   Linux (Ubuntu 24) | 
| Kernel Version (Linux Only)    |  6.8                                                                      | 
| Platform                                 | Raspberry Pi                          |
| Librealsense SDK Version       |  { 2.<?>.<?> }                                                    | 
| Language                               |  python      | 
| Segment			         |  Robot                            | 
| ROS Distro			         |  Rolling                                          | 
| RealSense ROS Wrapper Version   |  {4.51.1, 4.54.1, etc..}                                                  | 

### Issue Description
When can a version with "rolling" support be released?

**Comment by MartyG-RealSense** [comment]
Rolling is supported in the ROS2 wrapper if you build it from source code.  The quote below is from the release notes for wrapper 4.54.1.

https://github.com/IntelRealSense/realsense-ros/releases/tag/4.54.1

![image](https://github.com/IntelRealSense/realsense-ros/assets/41145062/dd664a6c-55a1-4bee-bb8c-3ddb5fa35ec5)

**Comment by MartyG-RealSense** [comment]
Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
