### ISSUE TITLE
"package 'realsense2_camera' not found

### ISSUE THREAD

**Issue by alonsnir** [realsenseai/realsense-ros#3142]
----------------------------------------------------------------------------------------------------

| Required Info                         |                                                                                         |
|---------------------------------|------------------------------------------------------------ |
| Camera Model                       | D435                       | 
| Firmware Version                   | 5.14.0                          | 
| Operating System & Version |   Linux (Ubuntu 22) | 
| Kernel Version (Linux Only)    |  6.5.0-41-generic                                                                     | 
| Platform                                 | PC                        |
| Librealsense SDK Version       |  2.2                                                    | 
| Language                               |  python         | 
| Segment			         |  Robot                             | 
| ROS Distro			         |  Humble                                           | 

### "package 'realsense2_camera' not found
Option 2: Install librealsense2 (without graphical tools and examples) debian package from ROS servers (Foxy EOL distro is not supported by this option):

`sudo apt install ros-humble-librealsense2*`

Then the error:
```
ros2 launch realsense2_camera rs_launch.py depth_module.depth_profile:=1280x720x15 rgb_camera.color_profile:=1280x720x15 align_depth.enable:=True
Package 'realsense2_camera' not found: "package 'realsense2_camera' not found, searching: ['/opt/ros/humble']"

```

**Comment by MartyG-RealSense** [comment]
Hi @alonsnir  Is this the same problem that you described at https://github.com/IntelRealSense/realsense-ros/issues/3139#issuecomment-2191631794 please or a different issue?

**Comment by alonsnir** [comment]
Hi @MartyG-RealSense it's sort of the same, as that's the same hardware spec, but I'm trying to get it to work with the default Ubuntu 22.04 kernels 6.5, so the OS setup is different

**Comment by MartyG-RealSense** [comment]
`sudo apt install ros-humble-librealsense2*` should install the current latest 2.55.1 version of the librealsense SDK from the rOS server.  2.55.1 supports kernel 6.5. 

I note that the camera firmware driver version listed at the top of this case is 5.14.  That firmware was designed for librealsense version 2.53.1.  If you have librealsense 2.55.1 installed then your firmware driver needs to be **5.16.0.1**.

**Comment by alonsnir** [comment]
I suggest to ignore camera firmware at this point, as I get this error when, intentionally, no camera been connected.
See [Step 2, Option 2](https://github.com/IntelRealSense/realsense-ros?tab=readme-ov-file#option-2-install-librealsense2-without-graphical-tools-and-examples-debian-package-from-ros-servers-foxy-eol-distro-is-not-supported-by-this-option), same is [Step 3, option 1](https://github.com/IntelRealSense/realsense-ros?tab=readme-ov-file#option-1-install-debian-package-from-ros-servers-foxy-eol-distro-is-not-supported-by-this-option)
after completing all three steps librealsense and the the wrapper should be installed, while I'm getting that error message:
```
ros2 launch realsense2_camera rs_launch.py depth_module.depth_profile:=1280x720x15 rgb_camera.color_profile:=1280x720x15 align_depth.enable:=True
Package 'realsense2_camera' not found: "package 'realsense2_camera' not found, searching: ['/opt/ros/humble']"
```

**Comment by MartyG-RealSense** [comment]
When installing with the **sudo apt install** method, only the two installation instructions below should be used after the Ubuntu sources have been configured with the instructions at http://wiki.ros.org/Installation/Ubuntu/Sources

**1.  Install librealsense2**
`sudo apt install ros-humble-librealsense2*`

**2.  Install ROS2 wrapper**
`sudo apt install ros-humble-realsense2-*`

**********

Source code and apt package builds of librealsense should not be made on the same computer, as you could end up with more than one librealsense installation, with conflicts between the two.

**Comment by alonsnir** [comment]
Ubuntu sources been configured before installing

---
This is a fresh setup, no build from sources here

**Comment by MartyG-RealSense** [comment]
Do librealsense's text-based tools behave correctly even if the ROS wrapper has the package error?  For example, are you able to run **rs-enumerate-devices** to obtain information about the camera?

**Comment by MartyG-RealSense** [comment]
Hi @alonsnir  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
