### ISSUE TITLE
running multiple cameras

### ISSUE THREAD

**Issue by Roboticom314** [realsenseai/realsense-ros#316]
If I connect multiple cameras and try to run with default launch arguments, I see that realsense detects multiple cameras and suggests specifying the serial number and usb number to connect. If I run the following command I am able to connect to one of the cameras.

`roslaunch realsense_camera zr300_nodelet_rgbd.launch serial_no:=4444444444 usb_port_id:=2-4-2`

(where 4444444444 is some real serial number)

However, if I try to run a launch to attach to a second camera on the same machine it never seems to work. I even updated the  launch to include the camera (namespace) as in:

`roslaunch realsense_camera zr300_nodelet_rgbd.launch serial_no:=4444444444 usb_port_id:=2-4-2 camera:=cam1`

and

`roslaunch realsense_camera zr300_nodelet_rgbd.launch serial_no:=5555555555 usb_port_id:=2-5-2 camera:=cam2`

The seemingly most significant errors at the start of the second camera are:

> [ERROR] [1518734414.621475686]: /cam2/driver - No cameras detected!
> [ERROR] [1518734414.621502048]: /cam2/driver - Error calling rs_create_context ( api_version:11201 ): 
> libusb_claim_interface(...) returned LIBUSB_ERROR_BUSY 

If I run either one of the above launch files individually, they both work fine.

If I run the `get_debug_info.launch` I get:

> |Version | Your Configuration | 
> |:----------|:----------| 
> |Operating System | Ubuntu 16.04.3 LTS|
> |Kernel | 4.4.0-112-generic|
> |ROS | kinetic| 
> |ROS RealSense | 1.8.1|
> |librealsense | 1.12.1|
> |Camera Type-Firmware | Error detecting cameras |

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Close this issue for lack of activity. Please feel free to reopen if the issue is still relevant.
