### ISSUE TITLE
Error while building the ROS Wrapepr for Framos D435e Camera. 

### ISSUE THREAD

**Issue by KaushalkumarPatel** [realsenseai/realsense-ros#3160]
----------------------------------------------------------------------------------------------------

| Required Info                         |                                                                                         |
|---------------------------------|------------------------------------------------------------ |
| Camera Model                       | Framos D435e                         |                       | 
| Operating System & Version |   Linux 20.04 | 
| Kernel Version (Linux Only)    |  5.15.0-113-generic                                                                     | 
| Platform                                 | PC x86_64                           |
| Librealsense SDK Version       |  2.50.12                                                     |        | 
| Segment			         |  Robot                              | 
| ROS Distro			         |  Noetic                                          |                                                  | 

### Issue Description

I am trying to use Framos D435e camera for my application in ROS Noetic in Linux 20.04 (Focal Fossa). I am following the installation instructions accoording to their ReadMe.txt file which is inside their FRAMOS_D400e_Software_Package which I have downloaded from their [Page](https://www.framos.com/en/downloads). 

From this ReadMe.txt file I have installed FRAMOS CameraSuite then install and built Intel® RealSense™ SDK. Till now everything works fine. I can launch `realsense-viewer` and camera is detected and I see the RGB module. 

Now I have error in ROS wrapper installation part. I have added all the repos `sudo add-apt-repository main`  
`sudo add-apt-repository universe`
`sudo add-apt-repository restricted`
`sudo add-apt-repository multiverse`
`sudo apt update`

Installed additional dependency:
`sudo apt install ros-noetic-ddynamic-reconfigure -y
`
and copied the code from `/usr/src/librealsense2/wrappers/ros/` to my `framos_ws/src/` in home folder then inside framos_ws/ when I try to run `catkin_make clean` then I have the following error. 

![Screenshot from 2024-07-10 15-25-43](https://github.com/IntelRealSense/realsense-ros/assets/47303677/9cd95c0b-c245-46b9-bfdf-69ed6b10171b)

**Comment by MartyG-RealSense** [comment]
Hi @KaushalkumarPatel  Intel are unfortunately able to provide technical support for the 'e' range of industrial RealSense-compatible cameras or their software packages, as these cameras are produced by the FRAMOS company rather than Intel.  Please contact FRAMOS support by visiting the link below and clicking on the 'Contact Us' or 'Let's Talk' button.

https://www.framos.com/en/resources/support

I do apologize for the inconvenience.

**Comment by KaushalkumarPatel** [comment]
Thanks @MartyG-RealSense
