### ISSUE TITLE
Issues with features appearing as two different features when revisiting an area using RTABMAP.

### ISSUE THREAD

**Issue by GraysonWylie1** [realsenseai/realsense-ros#3167]
I am running .bag file collected using a D455 camera through RTABMAP's Slam feature to map a small forested area. My collection path is circular, but when I complete the circle and revisit an area that has already been recorded by the camera, the features (trees) don't register as the same tree. There will be two or three trees where only one exists. Any suggestions on RTABMAP parameter tuning to fix this issue would be greatly appreciated. Thanks!

**Comment by MartyG-RealSense** [comment]
Hi @GraysonWylie1  I performed research of your question.  The link below suggests that "if you want to re-use visual features already extracted by odometry node in the rtabmap node, connect **rgbd_image** output topic from the odometry node to rtabmap node (with the latter using subscribe_rgbd:=true)".

http://official-rtab-map-forum.206.s1.nabble.com/Does-the-main-rtabmap-node-slam-support-nodelet-extra-questions-td9436.html

**Comment by MartyG-RealSense** [comment]
Hi @GraysonWylie1  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
