### ISSUE TITLE
RGB image and depth image time sync

### ISSUE THREAD

**Issue by CYJ00** [realsenseai/realsense-ros#3169]
* Before opening a new issue, we wanted to provide you with some useful suggestions (Click "Preview" above for a better view):

    * Consider checking our ROS RealSense Wrapper documentation [README](https://github.com/IntelRealSense/realsense-ros/blob/ros2-master/README.md).
    * Have you looked in our [Discussions](https://github.com/IntelRealSense/realsense-ros/discussions)?
    * Try [searching our GitHub Issues](https://github.com/IntelRealSense/realsense-ros/issues) (open and closed) for a similar issue.

* All users are welcomed to report bugs, ask questions, suggest or request enhancements and generally feel free to open new issue, even if they haven't followed any of the suggestions above :)

----------------------------------------------------------------------------------------------------

| Required Info                         |                                                                                         |
|---------------------------------|------------------------------------------------------------ |
| Camera Model                       | D415                                                                                | 
| Operating System & Version |   Ubuntu 20.04                                                                 |
| Platform                                 | Laptop                                                                            |
| ROS Distro			         |  Noteic                                                                            | 

ros-noetic-librealsense2: 2.50.0-1
ros-noetic-realsense2-camera: 2.3.2-1

### Issue Description
<Describe your issue / question / feature request / etc..>

If I look at the time stamp of the image captured by the rostopic, the time is not correct. I want the time of the rgb image and the depth image to be the same time, but how can I do that?

**Comment by MartyG-RealSense** [comment]
Hi @CYJ00  Do you get the results that you require if you add **enable_sync:=true** to your roslaunch instruction, please? 
 enable_sync: gathers the closest frames of different sensors, such as infrared, color and depth, to be sent with the same timetag.

**Comment by MartyG-RealSense** [comment]
Hi @CYJ00  Do you require further assistance with this case, please?  Thanks!

**Comment by CYJ00** [comment]
Hello!
I tried `roslauch rs_camera.lanch enable_sync:=true`
The time time stamps of `/camera/color/image_raw` topic and `/camera/depth/image_rect_raw` topic are not same, but the error is acceptable.
Thank you!

**Comment by MartyG-RealSense** [comment]
You are very welcome, @CYJ00 - I'm pleased that I could help.  Thanks very much for the update!
