### ISSUE TITLE
ZR300: Non sequential timestamps

### ISSUE THREAD

**Issue by johuber** [realsenseai/realsense-ros#317]
I use the following launch file for the ZR300 without any modification to the package:

```
<launch>
<!-- RealSense -->
  <arg name="camera"       default="camera"/>
  <arg name="serial_no"    default=""/>
  <arg name="usb_port_id"  default="" /> <!-- USB "Bus#-Port#" -->
  <arg name="manager"      default="manager"/>

  <!-- These 'arg' tags are just place-holders for passing values from test files.
  The recommended way is to pass the values directly into the 'param' tags. -->
  <arg name="mode"              default="manual" />
  <arg name="color_fps"         default="30" />

  <!-- disable/enable hardware -->
  <param name="$(arg camera)/driver/enable_color"      type="bool"  value="true" />
  <param name="$(arg camera)/driver/enable_depth"      type="bool"  value="false" />
  <param name="$(arg camera)/driver/enable_ir"         type="bool"  value="false" />
  <param name="$(arg camera)/driver/enable_fisheye"    type="bool"  value="true" />
  <param name="$(arg camera)/driver/enable_imu"        type="bool"  value="true" />

  <param name="$(arg camera)/driver/fisheye_external_trigger"     type="int"  value="0" />
  <param name="$(arg camera)/driver/fisheye_enable_auto_exposure" type="int"  value="0" />

  <param name="$(arg camera)/driver/mode"              type="str"  value="$(arg mode)" />
  <param name="$(arg camera)/driver/color_fps"         type="int"  value="$(arg color_fps)" />
  <param name="$(arg camera)/driver/fisheye_fps"       type="int"  value="30" />
  <param name="$(arg camera)/driver/fisheye_strobe"    type="int"  value="1" />
  <!--param name="$(arg camera)/driver/fisheye_external_trigger"    type="int"  value="$(arg fisheye_external_trigger)" /-->
  <!-- Refer to the Wiki http://wiki.ros.org/realsense_camera for list of supported parameters -->

  <group ns="$(arg camera)">
    <node pkg="nodelet" type="nodelet" name="$(arg manager)" args="manager" output="screen"/>

    <include file="$(find realsense_camera)/launch/includes/nodelet.launch.xml">
      <arg name="manager"      value="$(arg manager)" />
      <arg name="camera"       value="$(arg camera)" />
      <arg name="camera_type"  value="ZR300" />
      <arg name="serial_no"    value="$(arg serial_no)" />
      <arg name="usb_port_id"  value="$(arg usb_port_id)" />
    </include>
  </group>
</launch>
```

I observe that many times the timestamps of the received images are not sequential, i.e. I get an image I_1 with timestamp t_1 and next i get an image I_2 with timestamp t_2, where t_1 > t_2. The same issue occurs with IMU measurements.
Of course this property breaks many conventional visual-inertial odometry pipelines because IMU pre-integration cannot function properly this way.

Does anybody else face this issue? Can I even expect these timestamps to be accurate if they do not arrive in sequential order? Is there a fix to the problem?

**Comment by jlgarcia75** [comment]
Hello @johuber,

This paper addresses your issue: https://www.researchgate.net/publication/319235394_Build_your_own_visual-inertial_odometry_aided_cost-effective_and_open-source_autonomous_drone. Scroll down to section 3.2.1 Camera-IMU time-synchronization.

Regards,
Jesus
Intel Customer Support

**Comment by johuber** [comment]
Hi @jlgarcia75 

This is definitely an interesting and useful section, it does not directly address the issue I mention though. I am aware of the synchronization problem, but as stated above, I also noticed the image messages for themselves sometimes arrive in non-sequential order. The same occurs for the IMU measurements.

I don't really understand how these messages can get scrambled up in time, and hence, I'm also uncertain, if the timestamps can still be accurate in that case.

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Close this issue for lack of activity. Please feel free to reopen if the issue is still relevant.
