### ISSUE TITLE
D435i can't find device in RK3588

### ISSUE THREAD

**Issue by ciyuan606** [realsenseai/realsense-ros#3183]
----------------------------------------------------------------------------------------------------

| Required Info                         |                                                                                         |
|---------------------------------|------------------------------------------------------------ |
| Camera Model                       | D435i }                          | 
| Firmware Version                   | /                      | 
| Operating System & Version |  Linux (Ubuntu 22.04 | 
| Kernel Version (Linux Only)    | 5.10.110-rockchip-rk3588                 | 
| Platform                                 | orange pi                           |
| Librealsense SDK Version       | 2.55.1                                                | 
| Language                               |  python      | 
| Segment			         | Robot                         | 
| ROS Distro			         |  humble                                 | 
| RealSense ROS Wrapper Version   |4.55.1                                                 | 

### Issue Description
I use  
sudo apt install ros-humble-librealsense2*     
sudo apt install ros-humble-realsense2-*

![图片](https://github.com/user-attachments/assets/a5674c1b-8193-41a3-81c6-a79596fd1063)
 but
![图片](https://github.com/user-attachments/assets/6fe23d59-c6c6-4441-b709-a95458a14d10)
how can I found device?
use realsense-viewer
![图片](https://github.com/user-attachments/assets/9aa24601-b08e-4701-993c-9fd403a41e27)

**Comment by MartyG-RealSense** [comment]
Hi @ciyuan606  On Rockchip (RK) devices it is recommended to build the librealsense SDK from source code with CMake using the **RSUSB backend** method described at https://github.com/IntelRealSense/librealsense/issues/9931#issuecomment-964289692

An easier method than the RSUSB procedure is to use the **libuvc backend** method at the link below to install using a build script called **libuvc_installation.sh**.

https://github.com/IntelRealSense/librealsense/blob/master/doc/libuvc_installation.md

If you need realsense-viewer to be included in the librealsense installation though then you will need to edit line 46 of the build script to add the following flags:

**-DBUILD_EXAMPLES=TRUE -DBUILD_GRAPHICAL_EXAMPLES=TRUE**

https://github.com/IntelRealSense/librealsense/blob/master/scripts/libuvc_installation.sh#L46

**Comment by YujieSuCWE** [comment]
I met the same problem of being not able to find my device. My system is ubuntu 24.04, my librealsense version is v2.56.2, my ros distro is jazzy, and my realsense-ros version is 4.56.1. What is different is that I can open realsense-viewer, but still cannot find the device on both rs_launch.py and the viewer. I am pretty sure I used RSUSB backend method when compiling librealsense.

**Comment by MartyG-RealSense** [comment]
@YujieSuCWE  Thanks for the reminder that this issue is still open.  I will respond to your problem at the new issue that you created.

@ciyuan606  Did you achieve a solution on this issue, please?

**Comment by MartyG-RealSense** [comment]
Hi @ciyuan606  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
