### ISSUE TITLE
ros loading d405 json doesn't work

### ISSUE THREAD

**Issue by Nanmei** [realsenseai/realsense-ros#3192]
| Required Info                         |                                                                                         |
|---------------------------------|------------------------------------------------------------ |
| Camera Model                       | { D405  }                          | 
| Firmware Version                   | (Open RealSense Viewer --> Click info)                          | 
| Operating System & Version |   {  /Linux (Ubuntu 18/)  } | 
| Kernel Version (Linux Only)    |  (e.g. 5.4)                                                                       | 
| Platform                                 | PC / etc..                           |
| Librealsense SDK Version       |  { 2.<?>.<?> }                                                    | 
| Language                               |  { }         | 
| Segment			         |  {}                             | 
| ROS Distro			         |  {Melodic/etc.. }                                           | 
| RealSense ROS Wrapper Version   |  {4.51.1, 4.54.1, etc..}                                                  | 

This is the default parameter for D405 in realsense view
![1](https://github.com/user-attachments/assets/fe9f0b35-14ae-482a-b02c-d9a9ccac5714)

This is my modified parameter and saved as JSON
![2](https://github.com/user-attachments/assets/5fe49a89-0d7a-473d-a5c9-64059e828902)

this is json file:
{
    "device": {
        "fw version": "5.15.1",
        "name": "Intel RealSense D405",
        "product line": "D400"
    },
    "parameters": {
        "aux-param-autoexposure-setpoint": "1000",
        "aux-param-colorcorrection1": "-0.0556641",
        "aux-param-colorcorrection10": "-0.194336",
        "aux-param-colorcorrection11": "-0.194336",
        "aux-param-colorcorrection12": "-0.589844",
        "aux-param-colorcorrection2": "0.560547",
        "aux-param-colorcorrection3": "0.560547",
        "aux-param-colorcorrection4": "0.170898",
        "aux-param-colorcorrection5": "-0.275391",
        "aux-param-colorcorrection6": "-0.238281",
        "aux-param-colorcorrection7": "-0.238281",
        "aux-param-colorcorrection8": "1.34766",
        "aux-param-colorcorrection9": "0.959961",
        "aux-param-depthclampmax": "65536",
        "aux-param-depthclampmin": "0",
        "aux-param-disparityshift": "0",
        "controls-autoexposure-auto": "True",
        "controls-autoexposure-manual": "33000",
        "controls-depth-gain": "16",
        "controls-depth-white-balance-auto": "True",
        "ignoreSAD": "0",
        "param-amplitude-factor": "0",
        "param-autoexposure-setpoint": "1000",
        "param-censusenablereg-udiameter": "9",
        "param-censusenablereg-vdiameter": "9",
        "param-censususize": "9",
        "param-censusvsize": "9",
        "param-depthclampmax": "65536",
        "param-depthclampmin": "0",
        "param-depthunits": "1000",
        "param-disableraucolor": "0",
        "param-disablesadcolor": "0",
        "param-disablesadnormalize": "0",
        "param-disablesloleftcolor": "0",
        "param-disableslorightcolor": "1",
        "param-disparitymode": "0",
        "param-disparityshift": "0",
        "param-lambdaad": "935",
        "param-lambdacensus": "26",
        "param-leftrightthreshold": "19",
        "param-maxscorethreshb": "887",
        "param-medianthreshold": "1021",
        "param-minscorethresha": "54",
        "param-neighborthresh": "97",
        "param-raumine": "3",
        "param-rauminn": "1",
        "param-rauminnssum": "6",
        "param-raumins": "3",
        "param-rauminw": "5",
        "param-rauminwesum": "11",
        "param-regioncolorthresholdb": "0.0136986",
        "param-regioncolorthresholdg": "0.707436",
        "param-regioncolorthresholdr": "0.181996",
        "param-regionshrinku": "3",
        "param-regionshrinkv": "1",
        "param-robbinsmonrodecrement": "23",
        "param-robbinsmonroincrement": "3",
        "param-rsmdiffthreshold": "1.8125",
        "param-rsmrauslodiffthreshold": "1",
        "param-rsmremovethreshold": "0.482143",
        "param-scanlineedgetaub": "16",
        "param-scanlineedgetaug": "259",
        "param-scanlineedgetaur": "896",
        "param-scanlinep1": "132",
        "param-scanlinep1onediscon": "77",
        "param-scanlinep1twodiscon": "234",
        "param-scanlinep2": "342",
        "param-scanlinep2onediscon": "390",
        "param-scanlinep2twodiscon": "151",
        "param-secondpeakdelta": "600",
        "param-texturecountthresh": "0",
        "param-texturedifferencethresh": "0",
        "param-usersm": "1",
        "param-zunits": "1000"
    },
    "schema version": 1,
    "viewer": {
        "stream-depth-format": "Z16",
        "stream-fps": "90",
        "stream-height": "480",
        "stream-width": "640"
    }
}

this is ros launch file:

  <arg name="serial_no"           default="323622272730"/>
  <arg name="usb_port_id"         default=""/>
  <arg name="device_type"         default=""/>
  <arg name="json_file_path"      default="$(find realsense2_camera)/launch/d405_param.json"/>

  <arg name="fisheye_width"       default="-1"/>
  <arg name="fisheye_height"      default="-1"/>
  <arg name="enable_fisheye"      default="false"/>

  <arg name="depth_width"         default="640"/>
  <arg name="depth_height"        default="480"/>
  <arg name="enable_depth"        default="true"/>

  <arg name="infra_width"         default="-1"/>
  <arg name="infra_height"        default="-1"/>
  <arg name="enable_infra1"       default="true"/>
  <arg name="enable_infra2"       default="true"/>

  <arg name="color_width"         default="640"/>
  <arg name="color_height"        default="480"/>
  <arg name="enable_color"        default="true"/>

  <arg name="fisheye_fps"         default="-1"/>
  <arg name="depth_fps"           default="90"/>
  <arg name="infra_fps"           default="-1"/>
  <arg name="color_fps"           default="90"/>
  <arg name="gyro_fps"            default="-1"/>
  <arg name="accel_fps"           default="-1"/>
  <arg name="enable_gyro"         default="false"/>
  <arg name="enable_accel"        default="false"/>

  <arg name="enable_pointcloud"   default="false"/>
  <arg name="enable_sync"         default="true"/>
  <arg name="align_depth"         default="false"/>
  <arg name="filters"             default=""/>

  <arg name="publish_tf"          default="true"/>
  <arg name="tf_publish_rate"     default="0"/> 

![3 3](https://github.com/user-attachments/assets/f6d009bc-b33d-4303-a930-55399dd8dcef)

I started the launth file and found in rqt that the parameters I just modified did not take effect

![1 1](https://github.com/user-attachments/assets/5e13def0-1260-48fd-8a82-7dcf9cca51c6)

![2 2](https://github.com/user-attachments/assets/2687be84-424a-4812-8fda-4b6b98ce7649)

I need your help ,thanks!

**Comment by MartyG-RealSense** [comment]
Hi @Nanmei  From your RealSense Viewer images, it looks as though you are modifying RGB brightness, contrast, gamma, saturation and sharpness.  Tests that I performed with a D405 confirmed that these parameters are not exported to json on a D405 though, whilst they are on other RealSense camera models such as D435.

This is likely because the D405 model does not have a dedicated RGB sensor and instead obtains its RGB color image from the depth sensor, so the RGB sensor parameters are not exportable on D405.

**Comment by MartyG-RealSense** [comment]
When programming scripts for D405, RGB features can be controlled by accessing the depth sensor instead of the RGB sensor.  You may be able to do something similar with launch file edits to configure the RGB settings.  For example, instead of:

```
<rosparam>
 /camera/rgb_camera/brightness: 100
</rosparam>
```

Use:

```
<rosparam>
 /camera/stereo_module/brightness: 100
</rosparam>
```

**Comment by Nanmei** [comment]
> When programming scripts for D405, RGB features can be controlled by accessing the depth sensor instead of the RGB sensor.  You may be able to do something similar with launch file edits to configure the RGB settings.  For example, instead of:
> 
> 
> 
> ```
> 
> <rosparam>
> 
>  /camera/rgb_camera/brightness: 100
> 
> </rosparam>
> 
> ```
> 
> 
> 
> Use:
> 
> 
> 
> ```
> 
> <rosparam>
> 
>  /camera/stereo_module/brightness: 100
> 
> </rosparam>
> 
> ```

Thanks very much ,I will test it

**Comment by Nanmei** [comment]
> 在为 D405 编写脚本时，可以通过访问深度传感器而不是 RGB 传感器来控制 RGB 功能。您可能能够对启动文件编辑执行类似操作来配置 RGB 设置。例如，而不是：
> 
> ```
> <rosparam>
>  /camera/rgb_camera/brightness: 100
> </rosparam>
> ```
> 
> 使用：
> 
> ```
> <rosparam>
>  /camera/stereo_module/brightness: 100
> </rosparam>
> ```

set stereo_module ,it can works,thanks very much.
But I found another issue. I have two d405 cameras, and when both of them start up at the same time, the second camera displays "Device 1/2 failed with exception: failed to set power state". I don't know why it displays like this.

![4 1](https://github.com/user-attachments/assets/8394fa9e-87c3-4ed4-9a16-f22a78dac208)

**Comment by MartyG-RealSense** [comment]
Mutiple cameras should be launched in separate terminals, or in a single terminal with the ROS1 launch file **rs_multiple_devices.launch** instead of rs_camera.

https://github.com/IntelRealSense/realsense-ros/tree/ros1-legacy?tab=readme-ov-file#work-with-multiple-cameras
