### ISSUE TITLE
Documentation: "Supported RealSense SDK" not present in all the releases documentation.

### ISSUE THREAD

**Issue by edgarcamilocamacho** [realsenseai/realsense-ros#3204]
Hello.

When trying to follow the installation guides, it says "Supported RealSense SDK".

![image](https://github.com/user-attachments/assets/842c5989-6a30-4ac4-8747-e2bcbbef122f)

But when you go to the releases page, not all the releases have that section. 4.56.1 and 4.55.1 do not have it.

**Comment by MartyG-RealSense** [comment]
Hi @edgarcamilocamacho  It is saying to go to the RealSense SDK 'Releases' page and download the source code for the SDK version that should be matched with a particular ROS2 wrapper version.  

https://github.com/IntelRealSense/librealsense/releases

For example, if you are using wrapper 4.55.1 then go to the information listing for the corresponding **2.55.1** SDK version on the 'Releases' page, scroll down to the 'Assets' file list and click on the 'Source code' link to initiate a download of a zip file containing the SDK source code.

![image](https://github.com/user-attachments/assets/b7741268-3bd3-4f12-a27f-c58ff0044ff8)

Sometimes the contents of the Assets list is hidden, so you have to left-click on 'Assets' to expand open the file list.

![image](https://github.com/user-attachments/assets/b8ebffd6-7ff6-4f40-a050-d70eb24440b6)

**Comment by edgarcamilocamacho** [comment]
Yes, but for versions `4.54.1` and before, each of their release documentation explicitly said the version of the SDK they needed, for example:

`4.54.1`:
![image](https://github.com/user-attachments/assets/7398f2d1-ef46-4f70-a72d-4ad8185602e4)

`4.51.1`:
![image](https://github.com/user-attachments/assets/34ddc91b-9ac1-48a0-b9b4-464aac6d9d0a)

`4.0.4`:
![image](https://github.com/user-attachments/assets/8ed4c6fb-24a1-47cb-b6de-6fb3c8a7edc3)

But the documentation of the last versions two versions `4.55.1` and `4.56.1` does not include that **Supported RealSense SDK** section.

What I understand is that, from the last versions, I just replace the major version `4` for `2` to get the corresponding SDK version, right?

**Comment by MartyG-RealSense** [comment]
I understand what you mean now.  Thanks very much for the clarification.  Yes, the 'Supported RealSense SDK' section is no longer included in the ROS wrapper release notes.  You are correct, you just replace the major version number '4' with '2' to get the correct matching librealsense SDK version.

**Comment by MartyG-RealSense** [comment]
Hi @edgarcamilocamacho  Do you require further assistance with this case, please?  Thanks!

**Comment by edgarcamilocamacho** [comment]
Nope, the last response just clarified the situation. Thanks!
