### ISSUE TITLE
can not run the realsense camera

### ISSUE THREAD

**Issue by liujl12345** [realsenseai/realsense-ros#3211]
Hi! Here is a problem I can not solve.

camera Model : D405
ubuntu 20.04.6 LTS
kernel 5.15.0-122-generic
run command : ros2 run realsense2_camera realsense2_camera_node

when i try to run my camera after  I've installed ROS Wrapper for Intel® RealSense™ cameras, by command 'sudo apt install ros-foxy-realsense2-*'
then error occured like below,

![图片](https://github.com/user-attachments/assets/3cecb269-6e49-465f-b03a-561c5a3414f6)

what's wrong? or i have made mistake when installing the ROS Wrapper for Intel® RealSense™ cameras? someone helps me~(╥_╥)

**Comment by MartyG-RealSense** [comment]
Hi @liujl12345  The log indicates that you have likely not made a mistake when installing the ROS wrapper.  These red errors occur when using the 5.16.0.1 firmware with an older librealsense SDK version such as the 2.51.1 one that you are using, as this firmware is designed for use with librealsense 2.55.1.

If you need to use librealsense 2.51.1 because you have to use Foxy then downgrading your firmware version to **5.13.0.50** should make the red errors disappear.

Do not use an older firmware than 5.13.0.50, as this is the minimum firmware version that D405 is compatible with.

**Comment by liujl12345** [comment]
> If you need to use librealsense 2.51.1 because you have to use Foxy then downgrading your firmware version to **5.13.0.50** should make the red errors disappear.

Thanks a lot for your help!

it's my shame to say that i couldn't find a way to downgrade my firmware version. Can you help me?

**Comment by MartyG-RealSense** [comment]
You are very welcome!

If you have access to the realsense-viewer tool then instructions at https://github.com/IntelRealSense/librealsense/issues/12599#issuecomment-1902680303 explain how to downgrade the firmware to 5.13.0.50.

If you are not able to use realsense-viewer on your computer then you can also downgrade the firmware using the **rs-fw-update** tool once you have downloaded the **.bin** firmware file for 5.13.0.50 from the firmware releases page.

https://dev.intelrealsense.com/docs/firmware-releases-d400

https://github.com/IntelRealSense/librealsense/tree/master/tools/fw-update

![image](https://github.com/user-attachments/assets/bfcd8b31-18cf-429b-99e9-d283117b3694)

**Comment by liujl12345** [comment]
> If you need to use librealsense 2.51.1 because you have to use Foxy then downgrading your firmware version to **5.13.0.50** should make the red errors disappear.

Hi!@MartyG-RealSense, Thanks to your help, i downgraded my firmware successfully. And the red error disappear.

But I still can not use the camera, the pictures show blow,
![图片](https://github.com/user-attachments/assets/5c52b38d-896d-44dc-8d64-aea4603ca31b)
![图片](https://github.com/user-attachments/assets/5f5e3426-3916-46ba-b5c7-87cb05b4b004)

is there something i didn't install? what's wrong?

**Comment by MartyG-RealSense** [comment]
The **rs_pointcloud_launch.py** launch file is not part of the 4.51.1 wrapper.  It was from an earlier and now obsolete 'ros2-legacy' RealSense ROS2 wrapper, which had wrapper versions starting with the number 3 instead of 4, such as '3.2.3'.

If you need to publish a pointcloud in the 4.51.1 wrapper then I recommend trying the launch command below.

`ros2 launch realsense2_camera rs_launch.py pointcloud.enable:=true`

**Comment by liujl12345** [comment]
> ros2 launch realsense2_camera rs_launch.py pointcloud.enable:=true

I tried the command 'ros2 launch realsense2_camera rs_launch.py pointcloud.enable:=true', the output as shown below,
 
![图片](https://github.com/user-attachments/assets/47ca1c3c-01d3-497c-b082-f1dba1786c17)

no errors, but it doesn't seem to be working.

**Comment by MartyG-RealSense** [comment]
Is there any difference if you set the value of **pointcloud.stream_index_filter** yourself?  Its default value should be '0'.

`ros2 launch realsense2_camera rs_launch.py pointcloud.enable:=true pointcloud.stream_index_filter:=0`

**Comment by liujl12345** [comment]
> ros2 launch realsense2_camera rs_launch.py pointcloud.enable:=true pointcloud.stream_index_filter:=0

there is nothing changed. it seems that this command can not change the value of pointcloud.stream_index_filter

**Comment by liujl12345** [comment]
> there is nothing changed. it seems that this command can not change the value of pointcloud.stream_index_filter

 Hi!@MartyG-RealSense But I can see the pointclouds after I launch the 'rviz', maybe this argument just doesn't matter. 

After all these, my task is identify aruco codes with my realsense D405. Can you recommend a teaching article or an example for me according to my situation? It is best to have an example that is simple and quick to get started.Thank you very much!(≧∇≦)ﾉ

**Comment by MartyG-RealSense** [comment]
pal-robotics have an **aruco_ros** Aruco marker detecter at https://github.com/pal-robotics/aruco_ros that is compatible with ROS2 Humble.

**Comment by MartyG-RealSense** [comment]
Hi @liujl12345  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
