### ISSUE TITLE
Inconsistent Topic Publishing with RealSenseNodeFactory on Laptop: Only PointCloud or RGB Image Published at a Time (D455)

### ISSUE THREAD

**Issue by Poodlee** [realsenseai/realsense-ros#3219]
* Before opening a new issue, we wanted to provide you with some useful suggestions (Click "Preview" above for a better view):

    * Consider checking our ROS RealSense Wrapper documentation [README](https://github.com/IntelRealSense/realsense-ros/blob/ros2-master/README.md).
    * Have you looked in our [Discussions](https://github.com/IntelRealSense/realsense-ros/discussions)?
    * Try [searching our GitHub Issues](https://github.com/IntelRealSense/realsense-ros/issues) (open and closed) for a similar issue.

* All users are welcomed to report bugs, ask questions, suggest or request enhancements and generally feel free to open new issue, even if they haven't followed any of the suggestions above :)

----------------------------------------------------------------------------------------------------

| Required Info                         |                                                                                         |
|---------------------------------|------------------------------------------------------------ |
| Camera Model                       | { D455 }                          | 
| Firmware Version                   | (5.13.0.50)                          | 
| Operating System & Version |   { Ubuntu 22.04} | 
| Kernel Version (Linux Only)    |  (6.8.0-40-generic)                                                                       | 
| Platform                                 | PC                           |
| Librealsense SDK Version       |  { 2.55.1}                                                    | 
| Language                               |  {C/python }         | 
| Segment			         |  {Robot }                             | 
| ROS Distro			         |  {Humble}                                           | 
| RealSense ROS Wrapper Version   |  {4.51.1}                                                  | 

### Issue Description
<Describe your issue / question / feature request / etc..>

I am currently running RealSenseNodeFactory using a custom launch file. When I run this custom launch file, either the RGB image or the PointCloud gets published, but not both. This issue only occurs when I run the setup on my Galaxy Book Ion2 laptop. The exact same settings work perfectly on my desktop without any problems.
[realsense_image_and_pointcloud_error.webm](https://github.com/user-attachments/assets/af647690-db13-43bb-9c11-4cbde17e0e7c)

I have attached a video showing the issue in detail. Could anyone provide guidance on how to resolve this?

Please let me know if there are any mistakes or missing details on my part. Thank you for your help!

**Comment by MartyG-RealSense** [comment]
Hi @Poodlee  Are you setting **initial_reset** to true in your launch to reset the camera hardware at launch, please?

Is color able to be published if you set **enable_color** to true (even though it is meant to be enabled by default).

**Comment by MartyG-RealSense** [comment]
Hi @Poodlee  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
