### ISSUE TITLE
Problem of D435i running with Ubuntu 20.04 and ROS1 Noetic. Help me plz.

### ISSUE THREAD

**Issue by byeongjun-YU** [realsenseai/realsense-ros#3224]
---------------------------------- Question ----------------------------------
Hello.
I tried to run D435i with Ubuntu 20.04 and ROS1 Noetic.
However, I failed with some reasons as shown below.

What is the cause ?  How can I run D435i ?

Also, I know that Intel realsense does not support ROS1.
Currently, is it never possible to use D435i in my environment ? 
Is there any way to run D435i with Ubuntu 20.04 and ROS1 Noetic ???
(For example, using old version of ROS1 Wrapper or Realsense SKD.)

SUMMARY
========

----------------------------------  My terminal  ----------------------------------  
$ roslaunch realsense2_camera rs_camera.launch filters:=pointcloud

... logging to /home/byeong/.ros/log/70b64880-86ca-11ef-a5d2-bfb6448840c3/roslaunch-jun-36560.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://jun:33191/

PARAMETERS
 * /camera/realsense2_camera/accel_fps: -1
 * /camera/realsense2_camera/accel_frame_id: camera_accel_frame
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: False
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/allow_no_texture_points: False
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/calib_odom_file: 
 * /camera/realsense2_camera/clip_distance: -2.0
 * /camera/realsense2_camera/color_fps: -1
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: -1
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: -1
 * /camera/realsense2_camera/confidence_fps: -1
 * /camera/realsense2_camera/confidence_height: -1
 * /camera/realsense2_camera/confidence_width: -1
 * /camera/realsense2_camera/depth_fps: -1
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: -1
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: -1
 * /camera/realsense2_camera/device_type: 
 * /camera/realsense2_camera/enable_accel: False
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_confidence: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye1: False
 * /camera/realsense2_camera/enable_fisheye2: False
 * /camera/realsense2_camera/enable_fisheye: False
 * /camera/realsense2_camera/enable_gyro: False
 * /camera/realsense2_camera/enable_infra1: False
 * /camera/realsense2_camera/enable_infra2: False
 * /camera/realsense2_camera/enable_infra: False
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_pose: False
 * /camera/realsense2_camera/enable_sync: False
 * /camera/realsense2_camera/filters: pointcloud
 * /camera/realsense2_camera/fisheye1_frame_id: camera_fisheye1_f...
 * /camera/realsense2_camera/fisheye1_optical_frame_id: camera_fisheye1_o...
 * /camera/realsense2_camera/fisheye2_frame_id: camera_fisheye2_f...
 * /camera/realsense2_camera/fisheye2_optical_frame_id: camera_fisheye2_o...
 * /camera/realsense2_camera/fisheye_fps: -1
 * /camera/realsense2_camera/fisheye_frame_id: camera_fisheye_frame
 * /camera/realsense2_camera/fisheye_height: -1
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: -1
 * /camera/realsense2_camera/gyro_fps: -1
 * /camera/realsense2_camera/gyro_frame_id: camera_gyro_frame
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/imu_optical_frame_id: camera_imu_optica...
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra_fps: 30
 * /camera/realsense2_camera/infra_height: 480
 * /camera/realsense2_camera/infra_rgb: False
 * /camera/realsense2_camera/infra_width: 848
 * /camera/realsense2_camera/initial_reset: False
 * /camera/realsense2_camera/json_file_path: 
 * /camera/realsense2_camera/linear_accel_cov: 0.01
 * /camera/realsense2_camera/odom_frame_id: camera_odom_frame
 * /camera/realsense2_camera/ordered_pc: False
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/pose_frame_id: camera_pose_frame
 * /camera/realsense2_camera/pose_optical_frame_id: camera_pose_optic...
 * /camera/realsense2_camera/publish_odom_tf: True
 * /camera/realsense2_camera/publish_tf: True
 * /camera/realsense2_camera/reconnect_timeout: 6.0
 * /camera/realsense2_camera/rosbag_filename: 
 * /camera/realsense2_camera/serial_no: 
 * /camera/realsense2_camera/stereo_module/exposure/1: 7500
 * /camera/realsense2_camera/stereo_module/exposure/2: 1
 * /camera/realsense2_camera/stereo_module/gain/1: 16
 * /camera/realsense2_camera/stereo_module/gain/2: 16
 * /camera/realsense2_camera/tf_publish_rate: 0.0
 * /camera/realsense2_camera/topic_odom_in: odom_in
 * /camera/realsense2_camera/unite_imu_method: 
 * /camera/realsense2_camera/usb_port_id: 
 * /camera/realsense2_camera/wait_for_device_timeout: -1.0
 * /rosdistro: noetic
 * /rosversion: 1.17.0

NODES
  /camera/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)

auto-starting new master
process[master]: started with pid [36569]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 70b64880-86ca-11ef-a5d2-bfb6448840c3
process[rosout-1]: started with pid [36581]
started core service [/rosout]
process[camera/realsense2_camera_manager-2]: started with pid [36588]
process[camera/realsense2_camera-3]: started with pid [36589]
[ INFO] [1728538950.920198784]: Initializing nodelet with 8 worker threads.
[ INFO] [1728538950.991186464]: RealSense ROS v2.3.2
[ INFO] [1728538950.991214961]: Built with LibRealSense v2.50.0
[ INFO] [1728538950.991226736]: Running with LibRealSense v2.50.0
[ INFO] [1728538951.015363411]:  
[ INFO] [1728538951.246169863]: Device with serial number 215322078943 was found.

[ INFO] [1728538951.246269687]: Device with physical ID 3-4.2-6 was found.
[ INFO] [1728538951.246304064]: Device with name Intel RealSense D435I was found.
[ INFO] [1728538951.247272435]: Device with port number 3-4.2 was found.
[ INFO] [1728538951.247616616]: Device USB type: 2.1
[ WARN] [1728538951.247661174]: Device 215322078943 is connected using a 2.1 port. Reduced performance is expected.
[ INFO] [1728538951.250220733]: getParameters...
[ INFO] [1728538951.273369390]: setupDevice...
[ INFO] [1728538951.273390888]: JSON file is not provided
[ INFO] [1728538951.273412052]: ROS Node Namespace: camera
[ INFO] [1728538951.273421236]: Device Name: Intel RealSense D435I
[ INFO] [1728538951.273426646]: Device Serial No: 215322078943
[ INFO] [1728538951.273432430]: Device physical port: 3-4.2-6
[ INFO] [1728538951.273437540]: Device FW version: 05.14.00.00
[ INFO] [1728538951.273443014]: Device Product ID: 0x0B3A
[ INFO] [1728538951.273447857]: Enable PointCloud: On
[ INFO] [1728538951.273453238]: Align Depth: Off
[ INFO] [1728538951.273458174]: Sync Mode: On
[ INFO] [1728538951.273498242]: Device Sensors: 
[ INFO] [1728538951.361686552]: Stereo Module was found.
[ INFO] [1728538951.375104152]: RGB Camera was found.
[ INFO] [1728538951.375196828]: Motion Module was found.
[ INFO] [1728538951.375223131]: (Confidence, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1728538951.375244120]: Add Filter: pointcloud
[ INFO] [1728538951.375639691]: num_filters: 1
[ INFO] [1728538951.375657183]: Setting Dynamic reconfig parameters.
hwmon command 0x80( 5 0 0 0 ) failed (response -7= HW not ready)
hwmon command 0x80( 5 0 0 0 ) failed (response -7= HW not ready)
hwmon command 0x80( 5 0 0 0 ) failed (response -7= HW not ready)
hwmon command 0x80( 5 0 0 0 ) failed (response -7= HW not ready)
[ INFO] [1728538954.263469171]: Done Setting Dynamic reconfig parameters.
[ INFO] [1728538954.263878885]: depth stream is enabled - width: 640, height: 480, fps: 15, Format: Z16
[ INFO] [1728538954.264271590]: color stream is enabled - width: 640, height: 480, fps: 15, Format: RGB8
[ INFO] [1728538954.264292100]: setupPublishers...
[ INFO] [1728538954.266329305]: Expected frequency for depth = 15.00000
[ INFO] [1728538954.294548491]: Expected frequency for color = 15.00000
[ INFO] [1728538954.314135534]: setupStreams...
 10/10 14:42:34,517 WARNING [139810429720320] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
[ INFO] [1728538954.567708371]: SELECTED BASE:Depth, 0
[ INFO] [1728538954.577146386]: RealSense Node Is Up!
 10/10 14:42:34,682 WARNING [139810429720320] (messenger-libusb.cpp:42) control_transfer returned error, index: 300, error: Success, number: 0
 10/10 14:42:34,733 WARNING [139810429720320] (messenger-libusb.cpp:42) control_transfer returned error, index: 300, error: Success, number: 0
[ WARN] [1728538954.754272612]: 
 10/10 14:42:34,784 WARNING [139810429720320] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 10/10 14:42:34,835 WARNING [139810429720320] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 10/10 14:42:34,886 WARNING [139810429720320] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 10/10 14:42:34,937 WARNING [139810429720320] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 10/10 14:42:34,988 WARNING [139810429720320] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 10/10 14:42:35,039 WARNING [139810429720320] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 10/10 14:42:35,090 WARNING [139810429720320] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 10/10 14:42:35,141 WARNING [139810429720320] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 10/10 14:42:35,191 WARNING [139810429720320] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 10/10 14:42:35,242 WARNING [139810429720320] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 10/10 14:42:35,293 WARNING [139810429720320] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 10/10 14:42:35,344 WARNING [139810429720320] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 10/10 14:42:35,395 WARNING [139810429720320] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 10/10 14:42:35,446 WARNING [139810429720320] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 10/10 14:42:35,496 WARNING [139810429720320] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 10/10 14:42:35,547 WARNING [139810429720320] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 10/10 14:42:35,598 WARNING [139810429720320] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 10/10 14:42:35,649 WARNING [139810429720320] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 10/10 14:42:35,700 WARNING [139810429720320] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 10/10 14:42:35,750 WARNING [139810429720320] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 10/10 14:42:35,801 WARNING [139810429720320] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 10/10 14:42:35,846 ERROR [139810010281728] (uvc-streamer.cpp:106) uvc streamer watchdog triggered on endpoint: 130
 10/10 14:42:35,852 WARNING [139810429720320] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 10/10 14:42:35,903 WARNING [139810429720320] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 10/10 14:42:35,954 WARNING [139810429720320] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 10/10 14:42:36,005 WARNING [139810429720320] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 10/10 14:42:36,056 WARNING [139810429720320] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 10/10 14:42:36,108 WARNING [139810429720320] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 10/10 14:42:36,159 WARNING [139810429720320] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
[ WARN] [1728538956.265165535]: Hardware Notification:Depth stream start failure,1.72854e+12,Error,Hardware Error
 10/10 14:42:36,919 WARNING [139810429720320] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 10/10 14:42:36,970 WARNING [139810429720320] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 10/10 14:42:37,123 WARNING [139810429720320] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 10/10 14:42:37,173 WARNING [139810429720320] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 10/10 14:42:37,325 WARNING [139810429720320] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 10/10 14:42:37,375 WARNING [139810429720320] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 10/10 14:42:37,527 WARNING [139810429720320] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 10/10 14:42:37,577 WARNING [139810429720320] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0

**Comment by hellovuong** [comment]
> [ INFO] [1728538951.247616616]: Device USB type: 2.1
> [ WARN] [1728538951.247661174]: Device 215322078943 is connected using a 2.1 port. Reduced performance is expected.

You are using USB2. You should use the cable provided along with the camera and plug it into a USB3 port on your computer.

**Comment by MartyG-RealSense** [comment]
Hi @byeongjun-YU  The RealSense ROS1 wrapper does support D435i.  However, the ROS1 wrapper has ceased development and so has not been updated for use with recent RealSense SDK (librealsense) versions.  The recommended librealsense version for use with the wrapper is 2.50.0 or 2.51.1, and the recommended firmware version is **5.13.0.50**.  I note that you are using firmware 5.14.0.0.  I do not think the firmware version is the problem in this particular case though, and you are also correctly using librealsense 2.50.0.

As @hellovuong mentioned, your USB connection speed is being detected as the slow '2.1' instead of the much faster USB 3.1 or 3.2.  Whilst librealsense and the ROS wrapper can work on a slow USB 2.1 connection, problems like the **control_transfer returned** one that your log is generating are more likely to occur.

I note that you have the pointcloud filter enabled in your rs_camera.launch instruction.  Please try instead publishing a pointcloud using the **rs_rgbd.launch** launch file using the instructions at https://github.com/IntelRealSense/realsense-ros/issues/3026#issuecomment-1972741737

********

@hellovuong  Thanks so much for providing advice to @byeongjun-YU - though the connection being 2.1 does not necessarily mean that the official USB3 cable supplied with the camera is not being used.  It could mean that the launch is not correctly detecting the USB connection type, or the camera is plugged into a USB 2.1 hub.

**Comment by MartyG-RealSense** [comment]
Hi @byeongjun-YU  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.

**Comment by wwwzxxzw** [comment]
wzx@wzx-911X:~/ws_camera$ roslaunch realsense2_camera rs_camera.launch 
... logging to /home/wzx/.ros/log/5a16c1cc-f4d4-11ef-8891-23e295e1ba48/roslaunch-wzx-911X-204376.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://wzx-911X:38379/

SUMMARY
========

PARAMETERS
 * /camera/realsense2_camera/accel_fps: -1
 * /camera/realsense2_camera/accel_frame_id: camera_accel_frame
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: False
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/allow_no_texture_points: False
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/calib_odom_file: 
 * /camera/realsense2_camera/clip_distance: -2.0
 * /camera/realsense2_camera/color_fps: -1
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: -1
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: -1
 * /camera/realsense2_camera/confidence_fps: -1
 * /camera/realsense2_camera/confidence_height: -1
 * /camera/realsense2_camera/confidence_width: -1
 * /camera/realsense2_camera/depth_fps: -1
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: -1
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: -1
 * /camera/realsense2_camera/device_type: 
 * /camera/realsense2_camera/enable_accel: False
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_confidence: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye1: False
 * /camera/realsense2_camera/enable_fisheye2: False
 * /camera/realsense2_camera/enable_fisheye: False
 * /camera/realsense2_camera/enable_gyro: False
 * /camera/realsense2_camera/enable_infra1: False
 * /camera/realsense2_camera/enable_infra2: False
 * /camera/realsense2_camera/enable_infra: False
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_pose: False
 * /camera/realsense2_camera/enable_sync: False
 * /camera/realsense2_camera/filters: 
 * /camera/realsense2_camera/fisheye1_frame_id: camera_fisheye1_f...
 * /camera/realsense2_camera/fisheye1_optical_frame_id: camera_fisheye1_o...
 * /camera/realsense2_camera/fisheye2_frame_id: camera_fisheye2_f...
 * /camera/realsense2_camera/fisheye2_optical_frame_id: camera_fisheye2_o...
 * /camera/realsense2_camera/fisheye_fps: -1
 * /camera/realsense2_camera/fisheye_frame_id: camera_fisheye_frame
 * /camera/realsense2_camera/fisheye_height: -1
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: -1
 * /camera/realsense2_camera/gyro_fps: -1
 * /camera/realsense2_camera/gyro_frame_id: camera_gyro_frame
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/imu_optical_frame_id: camera_imu_optica...
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra_fps: 30
 * /camera/realsense2_camera/infra_height: 480
 * /camera/realsense2_camera/infra_rgb: False
 * /camera/realsense2_camera/infra_width: 848
 * /camera/realsense2_camera/initial_reset: False
 * /camera/realsense2_camera/json_file_path: 
 * /camera/realsense2_camera/linear_accel_cov: 0.01
 * /camera/realsense2_camera/odom_frame_id: camera_odom_frame
 * /camera/realsense2_camera/ordered_pc: False
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/pose_frame_id: camera_pose_frame
 * /camera/realsense2_camera/pose_optical_frame_id: camera_pose_optic...
 * /camera/realsense2_camera/publish_odom_tf: True
 * /camera/realsense2_camera/publish_tf: True
 * /camera/realsense2_camera/reconnect_timeout: 6.0
 * /camera/realsense2_camera/rosbag_filename: 
 * /camera/realsense2_camera/serial_no: 
 * /camera/realsense2_camera/stereo_module/exposure/1: 7500
 * /camera/realsense2_camera/stereo_module/exposure/2: 1
 * /camera/realsense2_camera/stereo_module/gain/1: 16
 * /camera/realsense2_camera/stereo_module/gain/2: 16
 * /camera/realsense2_camera/tf_publish_rate: 0.0
 * /camera/realsense2_camera/topic_odom_in: odom_in
 * /camera/realsense2_camera/unite_imu_method: 
 * /camera/realsense2_camera/usb_port_id: 
 * /camera/realsense2_camera/wait_for_device_timeout: -1.0
 * /rosdistro: noetic
 * /rosversion: 1.17.0

NODES
  /camera/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)

auto-starting new master
process[master]: started with pid [204384]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 5a16c1cc-f4d4-11ef-8891-23e295e1ba48
process[rosout-1]: started with pid [204394]
started core service [/rosout]
process[camera/realsense2_camera_manager-2]: started with pid [204401]
process[camera/realsense2_camera-3]: started with pid [204402]
[ INFO] [1740637835.742043910]: Initializing nodelet with 16 worker threads.
[ INFO] [1740637835.801747129]: RealSense ROS v2.3.2
[ INFO] [1740637835.801766237]: Built with LibRealSense v2.50.0
[ INFO] [1740637835.801773148]: Running with LibRealSense v2.50.0
[ INFO] [1740637835.820057569]:  
[ INFO] [1740637835.935684721]: Device with serial number 819612071351 was found.

[ INFO] [1740637835.935728462]: Device with physical ID 4-3-15 was found.
[ INFO] [1740637835.935744243]: Device with name Intel RealSense D435 was found.
[ INFO] [1740637835.936037475]: Device with port number 4-3 was found.
[ INFO] [1740637835.936061631]: Device USB type: 3.2
[ INFO] [1740637835.937282127]: getParameters...
[ INFO] [1740637835.951380003]: setupDevice...
[ INFO] [1740637835.951401174]: JSON file is not provided
[ INFO] [1740637835.951416919]: ROS Node Namespace: camera
[ INFO] [1740637835.951431172]: Device Name: Intel RealSense D435
[ INFO] [1740637835.951444488]: Device Serial No: 819612071351
[ INFO] [1740637835.951456664]: Device physical port: 4-3-15
[ INFO] [1740637835.951468572]: Device FW version: 05.13.00.50
[ INFO] [1740637835.951480319]: Device Product ID: 0x0B07
[ INFO] [1740637835.951491981]: Enable PointCloud: Off
[ INFO] [1740637835.951503227]: Align Depth: Off
[ INFO] [1740637835.951514544]: Sync Mode: Off
[ INFO] [1740637835.951545407]: Device Sensors: 
[ INFO] [1740637835.996874165]: Stereo Module was found.
[ INFO] [1740637836.003350145]: RGB Camera was found.
[ INFO] [1740637836.003379132]: (Confidence, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1740637836.003392018]: num_filters: 0
[ INFO] [1740637836.003400314]: Setting Dynamic reconfig parameters.
[ INFO] [1740637837.277264476]: Done Setting Dynamic reconfig parameters.
[ INFO] [1740637837.277669099]: depth stream is enabled - width: 848, height: 480, fps: 30, Format: Z16
[ INFO] [1740637837.278013893]: color stream is enabled - width: 640, height: 480, fps: 30, Format: RGB8
[ INFO] [1740637837.278026858]: setupPublishers...
[ INFO] [1740637837.279222862]: Expected frequency for depth = 30.00000
[ INFO] [1740637837.280847332]: Expected frequency for color = 30.00000
[ INFO] [1740637837.282033622]: setupStreams...
 27/02 14:30:37,405 WARNING [140104366544640] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
[ INFO] [1740637837.455523122]: SELECTED BASE:Depth, 0
[ INFO] [1740637837.459692437]: RealSense Node Is Up!
[ WARN] [1740637837.523010576]: 
 27/02 14:30:37,523 WARNING [140104366544640] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 27/02 14:30:37,573 WARNING [140104366544640] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 27/02 14:30:37,819 WARNING [140104366544640] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 27/02 14:30:37,869 WARNING [140104366544640] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 27/02 14:30:38,020 WARNING [140104366544640] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 27/02 14:30:38,171 WARNING [140104366544640] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 27/02 14:30:38,322 WARNING [140104366544640] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 27/02 14:30:38,372 WARNING [140104366544640] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 27/02 14:30:38,523 WARNING [140104366544640] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 27/02 14:30:38,573 WARNING [140104366544640] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 27/02 14:30:38,724 WARNING [140104366544640] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0
 27/02 14:30:38,774 WARNING [140104366544640] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Success, number: 0

I encountered a similar issue and haven't found a solution. I hope to get some help here. My system is Ubuntu 20.04, ROS Noetic, firmware version 5.13.0.50, and the ROS Noetic librealsense2 version is v2.50.0. Why do I see the warning control_transfer returned error, index: 768, error: Success, number: 0? Even though this warning appears, I can still receive RGB images, depth maps, and point clouds from the D435 in RViz, and I can retrieve the data.

**Comment by MartyG-RealSense** [comment]
Hi @wwwzxxzw  **control_transfer returned** warnings can indicate that there is a communication problem between the camera and the computer, such as an issue with the USB port or USB cable.  When they occur, the precise cause of them can be difficult to track down.  Reducing the resolution or FPS speed can sometimes reduce the number of the warnings.

In cases where the topics can be viewed normally in RViz despite the warnings though, the warnings can be safely ignored.
