### ISSUE TITLE
SR300 color video 960x540 issues

### ISSUE THREAD

**Issue by minhkhang1795** [realsenseai/realsense-ros#325]
Hello, I'm using SR300 with `realsense_ros_camera` package and having some issues below.

**1. 960x540 color video keeps crashing**
I changed the `rs_rgbd.launch` file so that I can get 960x540 color video stream. Specifically, these two lines were changed:

```
  <arg name="color_width"         default="960"/>
  <arg name="color_height"        default="540"/>
```

However, `roslaunch` keeps crashing even though it worked yesterday. Sometimes, it works just fine, and sometimes it doesn't and I have to unplug the camera and plug it back in.

The default `rs_rgbd.launch` works fine for me.

**2. How to align 640x480 depth to 960x540 video color?** 

I found that there is a `rostopic` called `/camera/aligned_depth_to_color/image_raw` which outputs an `Image` message. I thought that this would give me the depth data with dimensions equal to that of the color data (in this case 960x540). However, it doesn't and the data from this topic still has the 640x480 dimensions. Therefore, I wonder what it does and how to use it? 

**In sum:**  my goal is to get a 960x540 video stream and register the depth data to this video stream (so that I can have a 2D array 960x540 storing the depth data). Would it be possible or am I missing something here?

Thank you.
Khang

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Close this issue for lack of activity. Please feel free to reopen if the issue is still relevant.

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Close this issue for lack of activity. Please feel free to reopen if the issue is still relevant.
