### ISSUE TITLE
No topic which includes gyro data

### ISSUE THREAD

**Issue by agari1229** [realsenseai/realsense-ros#326]
The result from rostopc list was (when i run `roslaunch realsense_ros_camera rs_camera.launch` )

/camera/color/camera_info
/camera/color/image_raw    
/camera/color/image_raw/compressed  
/camera/color/image_raw/compressed/parameter_descriptions  
/camera/color/image_raw/compressed/parameter_updates  
/camera/color/image_raw/compressedDepth  
/camera/color/image_raw/compressedDepth/parameter_descriptions  
/camera/color/image_raw/compressedDepth/parameter_updates  
/camera/color/image_raw/theora  
/camera/color/image_raw/theora/parameter_descriptions  
/camera/color/image_raw/theora/parameter_updates  
/camera/depth/camera_info  
/camera/depth/color/points  
/camera/depth/image_rect_raw  
/camera/depth/image_rect_raw/compressed  
/camera/depth/image_rect_raw/compressed/parameter_descriptions  
/camera/depth/image_rect_raw/compressed/parameter_updates  
/camera/depth/image_rect_raw/compressedDepth  
/camera/depth/image_rect_raw/compressedDepth/parameter_descriptions  
/camera/depth/image_rect_raw/compressedDepth/parameter_updates  
/camera/depth/image_rect_raw/theora  
/camera/depth/image_rect_raw/theora/parameter_descriptions  
/camera/depth/image_rect_raw/theora/parameter_updates  
/camera/extrinsics/depth_to_color  
/camera/extrinsics/depth_to_infra1  
/camera/extrinsics/depth_to_infra2  
/camera/infra1/camera_info  
/camera/infra1/image_rect_raw   
/camera/infra1/image_rect_raw/compressed  
/camera/infra1/image_rect_raw/compressed/parameter_descriptions  
/camera/infra1/image_rect_raw/compressed/parameter_updates  
/camera/infra1/image_rect_raw/compressedDepth  
/camera/infra1/image_rect_raw/compressedDepth/parameter_descriptions  
/camera/infra1/image_rect_raw/compressedDepth/parameter_updates  
/camera/infra1/image_rect_raw/theora  
/camera/infra1/image_rect_raw/theora/parameter_descriptions  
/camera/infra1/image_rect_raw/theora/parameter_updates  
/camera/infra2/camera_info  
/camera/infra2/image_rect_raw  
/camera/infra2/image_rect_raw/compressed  
/camera/infra2/image_rect_raw/compressed/parameter_descriptions  
/camera/infra2/image_rect_raw/compressed/parameter_updates  
/camera/infra2/image_rect_raw/compressedDepth  
/camera/infra2/image_rect_raw/compressedDepth/parameter_descriptions  
/camera/infra2/image_rect_raw/compressedDepth/parameter_updates  
/camera/infra2/image_rect_raw/theora  
/camera/infra2/image_rect_raw/theora/parameter_descriptions  
/camera/infra2/image_rect_raw/theora/parameter_updates  
/camera/realsense_ros_camera_manager/bond  
/camera/realsense_ros_camera_manager/parameter_descriptions  
/camera/realsense_ros_camera_manager/parameter_updates  
/rosout  
/rosout_agg  
/tf_static  

**i can't find the topic which includes gyro and accel data. **
Is there any ways to get the data?

**Comment by icarpis** [comment]
Hello @agari1229, the Intel [D415](https://click.intel.com/intelr-realsensetm-depth-camera-d415.html) and [D435](https://click.intel.com/intelr-realsensetm-depth-camera-d435.html) cameras doesn't provide IMU data.

**Comment by agari1229** [comment]
thanks

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]
