### ISSUE TITLE
Camera ros connection problem

### ISSUE THREAD

**Issue by RtJinxuWang** [realsenseai/realsense-ros#3261]
| Required Info                         |                                                                                         |
|---------------------------------|------------------------------------------------------------ |
| Camera Model                       | { D435 }                          | 
| Firmware Version                   | (Open RealSense Viewer --> Click info)                          | 
| Operating System & Version |   { Linux (Ubuntu 18/20/22) } | 
| Kernel Version (Linux Only)    |  (e.g. 5.4)                                                                       | 
| Platform                                 | NVIDIA Jetson                      |
| Librealsense SDK Version       |  { 2.<?>.<?> }                                                    | 
| Language                               |  {C/C#/labview/opencv/pcl/python/unity }         | 
| Segment			         |  {Robot }                             | 
| ROS Distro			         |  {Iron/Humble/Rolling/etc.. }                                           | 
| RealSense ROS Wrapper Version   |  {4.51.1, 4.54.1, etc..}                                                  | 

![微信图片_20241121191547](https://github.com/user-attachments/assets/de1d6d21-85d3-4aaa-8cfe-3c6053e0a46d)

Hello, I encountered the above problem using the d435i camera on the nvidia platform. In addition, I checked the support for the initial frequency, found that 1920*1080 color images only support 8hz, which may be the reason for this?

I use the same batch of cameras, some computers will only support 8HZ problem, the ros program of the computer is the same, is this related to the USB cable? How do I troubleshoot this problem?

**Comment by MartyG-RealSense** [comment]
Hi @JasonWang9805  8 FPS is not a supported FPS setting on RealSense cameras.  A D435 supports 6, 15 or 30 FPS for 1920x1080 color resolution on a USB 3 connection.  If you deliberately defined it as 8 somewhere, please try changing it to 6 to see what happens.

![image](https://github.com/user-attachments/assets/ba140c4b-4305-473e-87b8-9550cbb477e7)

**Comment by RtJinxuWang** [comment]
I used the rs-enumerate-devices command for the detection, and it indicated 8 fps. There was no image on my side. I'll provide it in the next test.

**Comment by RtJinxuWang** [comment]
I think it might be related to USB 2.0. I'll check it out during the next test.

**Comment by MartyG-RealSense** [comment]
Thanks very much.  I look forward to your next update.

**Comment by MartyG-RealSense** [comment]
Hi @JasonWang9805  Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
