### ISSUE TITLE
use realsense-ros1 open D4357 failed,tag is v2.3.2,librealsense is v2.55.1,error is:Error extracting usb port from device with physica :/sys/devices/platform/tegra-capture-vi/video4linux/video0

### ISSUE THREAD

**Issue by 38277105** [realsenseai/realsense-ros#3264]
* Before opening a new issue, we wanted to provide you with some useful suggestions (Click "Preview" above for a better view):

    * Consider checking our ROS RealSense Wrapper documentation [README](https://github.com/IntelRealSense/realsense-ros/blob/ros2-master/README.md).
    * Have you looked in our [Discussions](https://github.com/IntelRealSense/realsense-ros/discussions)?
    * Try [searching our GitHub Issues](https://github.com/IntelRealSense/realsense-ros/issues) (open and closed) for a similar issue.

* All users are welcomed to report bugs, ask questions, suggest or request enhancements and generally feel free to open new issue, even if they haven't followed any of the suggestions above :)

----------------------------------------------------------------------------------------------------

| Required Info                         |                                                                                         |
|---------------------------------|------------------------------------------------------------ |
| Camera Model                       | { D405 / D415 / D435 / D435i / D455 / D457 }                          | 
| Firmware Version                   | (Open RealSense Viewer --> Click info)                          | 
| Operating System & Version |   { Win (10/11) / Linux (Ubuntu 18/20/22) / MacOS } | 
| Kernel Version (Linux Only)    |  (e.g. 5.4)                                                                       | 
| Platform                                 | PC/Raspberry Pi/ NVIDIA Jetson / etc..                           |
| Librealsense SDK Version       |  { 2.<?>.<?> }                                                    | 
| Language                               |  {C/C#/labview/opencv/pcl/python/unity }         | 
| Segment			         |  {Robot/Smartphone/VR/AR/others }                             | 
| ROS Distro			         |  {Iron/Humble/Rolling/etc.. }                                           | 
| RealSense ROS Wrapper Version   |  {4.51.1, 4.54.1, etc..}                                                  | 

### Issue Description
<Describe your issue / question / feature request / etc..>

**Comment by MartyG-RealSense** [comment]
Hello, the recommended configuration for use with ROS1 wrapper 2.3.2 is librealsense 2.50.0 or 2.51.1 and camera firmware driver 5.13.0.50.

Can you confirm please if your RealSense camera is the **D435i** model?

Which method did you use to install the librealsense SDK and ROS wrapper 2.3.2 please?

If you have not done so already, the easiest installation method is to use the command below, which will install correctly matching SDK and wrapper versions of librealsense 2.50.0 and wrapper 2.3.2 together at the same time.

`sudo apt-get install ros-$ROS_DISTRO-realsense2-camera`

This installation method does not include the realsense-viewer tool though, so if you need it then you will need to install librealsense and the ROS wrapper separately.

**Comment by MartyG-RealSense** [comment]
Do you require further assistance with this case, please?  Thanks!

**Comment by MartyG-RealSense** [comment]
Case closed due to no further comments received.
