### ISSUE TITLE
problem with raspberrypi and realsense-ros

### ISSUE THREAD

**Issue by raffy952** [realsenseai/realsense-ros#3267]
when i run the `ros2 run realsense2_camera realsense2_camera_node ` command in the raspberrypi 4 , with ubunut 22.04 and ros2 humble, i got the following error: 

`ros2 run realsense2_camera realsense2_camera_node `
[INFO] [1732894454.489801537] [camera.camera]: RealSense ROS v4.55.1
[INFO] [1732894454.490342436] [camera.camera]: Built with LibRealSense v2.55.1
[INFO] [1732894454.490506508] [camera.camera]: Running with LibRealSense v2.55.1
 29/11 16:34:21,495 ERROR [281473137567968] (librealsense-exception.h:52) set_xu(...). xioctl(UVCIOC_CTRL_QUERY) failed Last Error: Connection timed out
 29/11 16:34:21,498 ERROR [281473137567968] (rs.cpp:237) [rs2_create_device( info_list:0xffff78024040, index:0 ) Backend] set_xu(...). xioctl(UVCIOC_CTRL_QUERY) failed Last Error: Connection timed out
 29/11 16:34:21,498 ERROR [281473137567968] (rs.cpp:237) [rs2_delete_device( device:nullptr ) UNKNOWN] null pointer passed for argument "device"
 29/11 16:34:21,498 WARNING [281473137567968] (rs.cpp:373) null pointer passed for argument "device"
[WARN] [1732894461.499027102] [camera.camera]: Device 1/1 failed with exception: set_xu(...). xioctl(UVCIOC_CTRL_QUERY) failed Last Error: Connection timed out
[ERROR] [1732894461.499266561] [camera.camera]: The requested device with  is NOT found. Will Try again.

**Comment by MartyG-RealSense** [comment]
Hi @raffy952  A ** xioctl(UVCIOC_CTRL_QUERY)** error indicates that there is a conflict between the librealsense SDK and the kernel.  What method did you use to install librealsense 2.55.1 on your Raspberry Pi please?

The **libuvc backend** method of installing librealsense from source code works well on Pi, as this method bypasses the kernel, and so it is not dependent on a particular Linux version or kernel version and does not require a patch script to be applied to the kernel.

https://github.com/IntelRealSense/librealsense/blob/master/doc/libuvc_installation.md

The libuvc backend procedure provides a pre-made install script called **libuvc_installation.sh**

https://github.com/IntelRealSense/librealsense/blob/master/scripts/libuvc_installation.sh

**Comment by raffy952** [comment]
Hi @MartyG-RealSense , thank you for your response; with it, I solved the previous problem. Now, however, I am getting the following warnings, even though I am receiving the image stream (with a bit of delay) and the realsense is connected to the usb 3.1 port:
[INFO] [1733075607.182799334] [camera.camera]: RealSense ROS v4.55.1
[INFO] [1733075607.183098664] [camera.camera]: Built with LibRealSense v2.55.1
[INFO] [1733075607.183165867] [camera.camera]: Running with LibRealSense v2.55.1
[INFO] [1733075654.716583132] [camera.camera]: Device with serial number 839112061922 was found.

[INFO] [1733075654.716853832] [camera.camera]: Device with physical ID 1-1.2-3 was found.
[INFO] [1733075654.716920442] [camera.camera]: Device with name Intel RealSense D415 was found.
[INFO] [1733075654.717623600] [camera.camera]: Device with port number 1-1.2 was found.
[INFO] [1733075654.717739506] [camera.camera]: Device USB type: 2.1
[WARN] [1733075654.717784894] [camera.camera]: Device 839112061922 is connected using a 2.1 port. Reduced performance is expected.
[INFO] [1733075654.717992706] [camera.camera]: getParameters...
[INFO] [1733075654.719266579] [camera.camera]: JSON file is not provided
[INFO] [1733075654.719394873] [camera.camera]: Device Name: Intel RealSense D415
[INFO] [1733075654.719449910] [camera.camera]: Device Serial No: 839112061922
[INFO] [1733075654.719495316] [camera.camera]: Device physical port: 1-1.2-3
[INFO] [1733075654.719533908] [camera.camera]: Device FW version: 5.16.0.1
[INFO] [1733075654.719573501] [camera.camera]: Device Product ID: 0x0AD3
[INFO] [1733075654.719617981] [camera.camera]: Sync Mode: Off
[INFO] [1733075657.929067532] [camera.camera]: Stopping Sensor: Depth Module
[INFO] [1733075657.929457972] [camera.camera]: Stopping Sensor: RGB Camera
[INFO] [1733075658.125187314] [camera.camera]: Starting Sensor: Depth Module
[INFO] [1733075658.304424314] [camera.camera]: Open profile: stream_type: Infra(1), Format: Y8, Width: 640, Height: 480, FPS: 15
[INFO] [1733075658.304740402] [camera.camera]: Open profile: stream_type: Depth(0), Format: Z16, Width: 640, Height: 480, FPS: 15
 01/12 18:54:18,305 WARNING [281472678095072] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 01/12 18:54:18,416 WARNING [281472678095072] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 01/12 18:54:18,527 WARNING [281472678095072] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
[WARN] [1733075658.549646406] [camera.camera]: frame's time domain is HARDWARE_CLOCK. Timestamps may reset periodically.
 01/12 18:54:18,638 WARNING [281472678095072] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 01/12 18:54:18,749 WARNING [281472678095072] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 01/12 18:54:18,860 WARNING [281472678095072] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11
 01/12 18:54:18,971 WARNING [281472678095072] (messenger-libusb.cpp:42) control_transfer returned error, index: 768, error: Resource temporarily unavailable, number: 11

**Comment by MartyG-RealSense** [comment]
**control_transfer returned** warning messages that generate continuously indicate that there is a communication problem between the camera and computer, likely related to an issue with the USB system (the USB cable or the ISB port).

If the depth and RGB topics are able to be published correctly in RViz despite the warning messages then the warnings can be safely disregarded.

**Comment by MartyG-RealSense** [comment]
Hi @raffy952  Do you require further assistance with this case, please?  Thanks!

**Comment by raffy952** [comment]
Hi @MartyG-RealSense, sorry for the wait. Your informations resolved my problems so i can close this section.

**Comment by MartyG-RealSense** [comment]
It's no trouble at all,  @raffy952 - it's great to hear that your problems are resolved.  Thanks very much for the update!
