### ISSUE TITLE
Multiple camera error?

### ISSUE THREAD

**Issue by j5207** [realsenseai/realsense-ros#328]
Hi,
When I try to launch the `roslaunch realsense_ros_camera rs_multiple_devices.launch`
it seems didn't works, wit error:
`[ERROR] [1519943117.208575166]: An exception has been thrown: xioctl(VIDIOC_S_FMT) failed Last Error: Device or resource busy
[ERROR] [1519943117.208662134]: An exception has been thrown: xioctl(VIDIOC_S_FMT) failed Last Error: Device or resource busy
`
what should i do?
Thanks

**Comment by icarpis** [comment]
Hello @j5207, the [rs_multiple_devices](https://github.com/intel-ros/realsense#work-with-multiple-cameras) Launch file will not work out-of-the-box. you should provide the serial numbers of the connected cameras.
```roslaunch realsense2_camera rs_multiple_devices.launch serial_no_camera1:=<serial number of the first camera> serial_no_camera2:=<serial number of the second camera>```

**Comment by j5207** [comment]
Thanks for your help! It does solve my problem. Seem I forget to close the issues.
