### ISSUE TITLE
Pointcloud data has a lot of void. (Realsense D435)

### ISSUE THREAD

**Issue by agari1229** [realsenseai/realsense-ros#329]
(Realsense D435)
The result from `roslaunch realsense_ros_camera rs_camera.launch
`
was 
![screenshot from 2018-03-02 13-53-26](https://user-images.githubusercontent.com/32511644/36884449-7721d0e2-1e24-11e8-872f-c1012b4eb07b.png). 

Although there is nothing to prevent the camera, pointcloud data has a lot of void. 
(There are many void even if i project nearby(0.3[m]~1.0[m]) objects. )

Is there any ways to improve it?
(Or, is this a limitations of camera performance?)

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Close this issue for lack of activity. Please feel free to reopen if the issue is still relevant.
