### ISSUE TITLE
Something wrong with the README.md

### ISSUE THREAD

**Issue by shijiwensjw** [realsenseai/realsense-ros#331]
`echo "source ~/catkin_ws/**devel**/setup.bash" >> ~/.bashrc` may be wrong.   
I think there should be the **install** folder other than the **devel** floder

**Comment by icarpis** [comment]
Hello @shijiwensjw, this line is looks OK to me. please review the [tutorial of Catkin workspace](http://wiki.ros.org/catkin/Tutorials/create_a_workspace) for more details.

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]
