### ISSUE TITLE
rgbd node not subscriber aware? CPU use all the time.

### ISSUE THREAD

**Issue by eric-schleicher** [realsenseai/realsense-ros#337]
In other depth camera nodes the publishers written in a fashion where there aware whether the topics they're publishing to have any subscribers.  

For example iai_kinect kinect2_bridge pays attention and only starts publishing message when a subscriber is connected.  In my initial work with the 435, it appears that the rgbd node is constantly publishing, consuming resources when other consuming processed aren't attached or listenting.  

Can someone confirm this is the behavior? it sure does consume a lot of CPU just running the node.

**Comment by eric-schleicher** [comment]
I haven't tested this but could....

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Close this issue for lack of activity. Please feel free to reopen if the issue is still relevant.
