### ISSUE TITLE
Is realsense_navigation still active?

### ISSUE THREAD

**Issue by vaibhavviswanathan** [realsenseai/realsense-ros#338]
Can I still use realsense_navigation to do SLAM with the R200?

Thanks!

**Comment by jlgarcia75** [comment]
Hello @vaibhavviswanathan,

The R200 and all related software, including realsense_navigation, is discontinued.

All development has moved to the RealSense D400 cameras.

Regards,
Jesus
Intel Customer Support

**Comment by vaibhavviswanathan** [comment]
HI @jlgarcia75 ,

Thank you for your answer.

What type of support is there for the RealSense D400 cameras? Do you have SLAM and other ROS packages?

Best,
Vai

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Close this issue for lack of activity. Please feel free to reopen if the issue is still relevant.
