### ISSUE TITLE
'rs_rgbd.launch' fails for D415

### ISSUE THREAD

**Issue by ccempathy** [realsenseai/realsense-ros#339]
when i run the order 'roslaunch realsense_ros_camera rs_rgbd.launch' , the mistake turn up follows.
![screenshot from 2018-03-06 20 40 56](https://user-images.githubusercontent.com/32675546/37032827-c68621ee-217e-11e8-9c2e-26da45be1fad.png)

**Comment by ccempathy** [comment]
if you have free time. Could you please give me some help?@icarpis

**Comment by afourteia** [comment]
If you open that file, you will find this line of code in it. The IMU currently isn't supported so if you disable that by changing true to false, it should work. Please try it and let me know

`<arg name="enable_imu"          default="true"/>`

**Comment by icarpis** [comment]
Hello @ccempathy, maybe something went wrong with the installation of ROS distribution.
Please check if the other Launch files working well. try to run `rs_camera.launch`

**Comment by ccempathy** [comment]
@afourteia I have changed it to false .But it still goes wrong and display the same mistake.

**Comment by ccempathy** [comment]
@icarpis the distribution i installed is Indigo. And when i used kinect with the ROS distribution it went well.And re_camera.launch file could be run well.

**Comment by ccempathy** [comment]
@icarpis @afourteia The mistake shows that the order 'eval' is wrong in the launch file named  rs_rgbd.launch.I tried
![2018-03-28 21 53 37](https://user-images.githubusercontent.com/32675546/38033433-9837a85c-32d2-11e8-8978-9f10774d38f2.png)
 to modify  the launch file.But eventually i failed.

**Comment by xmojiao** [comment]
@icarpis @afourteia I have the same error, help please

**Comment by pl95** [comment]
@ccempathy  Because eval is a new feature in Kinetic. Indigo won't recognize this new expression. 
http://wiki.ros.org/roslaunch/XML 
![screenshot from 2019-02-12 15 55 23](https://user-images.githubusercontent.com/36173023/52667387-a9ecda00-2ede-11e9-98af-a3405dd9116e.png)

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Thank you @pl95.
Closing it for now. Please reopen if there is any further question.
