### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by GITSHOHOKU** [realsenseai/realsense-ros#342]
I followed guide to use  `sudo apt-get install 'ros-*-realsense-camera'` under Ubuntu 16.04 LTS
Kernel 4.10.0-28 . And I have install librealsense already. When I install ros-realsense I got code like this.
I have already added the deb-src to my list
```
WARNING: Locally installed librealsense components should removed:
         sudo rm -f /etc/udev/rules.d/99-realsense-libusb.rules

Creating symlink /var/lib/dkms/uvcvideo/1.1.1-3-realsense/source ->
                 /usr/src/uvcvideo-1.1.1-3-realsense

DKMS: add completed.

**Kernel preparation unnecessary for this kernel**.  Skipping...

Running the pre_build script:

dkms: Pre-build script started...

Downloading kernel sources...

ERROR: Could not download the required kernel sources to install RealSense camera support.

       To resolve, please follow the installation directions at:
           http://wiki.ros.org/librealsense#Installation_Prerequisites


Building module:
cleaning build area....(bad exit status: 2)
make KERNELRELEASE=4.10.0-28-generic -C /var/lib/dkms/uvcvideo/1.1.1-3-realsense/build/linux-src M=drivers/media/usb/uvc/....(bad exit status: 2)
Error! Bad return status for module build on kernel: 4.10.0-28-generic (x86_64)
Consult /var/lib/dkms/uvcvideo/1.1.1-3-realsense/build/make.log for more information.
WARNING: DKMS module failed to installed; removing...

------------------------------
Deleting module version: 1.1.1-3-realsense
completely from the DKMS tree.
------------------------------
Done.
WARNING: Unknown configuration for Intel RealSense(TM) cameras!
       To resolve, please follow the installation directions at:
           http://wiki.ros.org/librealsense#Installation

```
It said this kernel version didn't need  preparation.

**Comment by ev-mp** [comment]
Hello @GITSHOHOKU .
The DKMS you're using is part of [Intel ROS Wrapper v1](http://wiki.ros.org/realsense_camera) that runs Librealsense1 and supports R200 line of devices and SR300. This package is currently in maintenance phase.
In case you're using R200/LR200/ZR300 devices than I'd suggest you remove the specific DKMS and replace it with the [DKMS from Librealsense2](https://github.com/IntelRealSense/librealsense/blob/master/doc/distribution_linux.md#installing-the-packages)   (`sudo apt-get install librealsense2-dkms`). It is both "friendly" to the latest LTS kernels 4.10 and 4.13, and backward-compatible with Librealsense1 devices.

In case you need to run D4xx devices, or SR300, then I would encourage you to move to [Intel ROS Wrapper v2](http://wiki.ros.org/realsense2_camera) as it is development stage and will continue to receive updates/enhancements

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Close this issue for lack of activity. Please feel free to reopen if the issue is still relevant.
