### ISSUE TITLE
Rosparam set not working in realsense d435 ros package

### ISSUE THREAD

**Issue by Nachmr** [realsenseai/realsense-ros#345]
Hi there!
I'm playing a bit with the realsense_ros_camera package of ROS (kinetic version) and my intel realsense d435 camera. One of the things that for me is interesting is to change some values of the color image via ros parameters. After launch the node with `roslaunch realsense_ros_camera rs_rgbd.launch` I tried to change that configuration parameters with `rosrun rqt_reconfigure rqt_reconfigure` command and I can play with them, it actually works quite well.

The problem comes when I try to change this parameters directly in the prompt. If e.g. I try `rosparam set /camera/realsense_ros_camera_manager/rs435_color_exposure 1000` or directly via python code with `rospy.set_param('/camera/realsense_ros_camera_manager/rs435_color_exposure', 1000)` nothing happens.

It is a problem of my configuration or it actually doesn't work?

My software versions:
ROS Wrapper 2.0 for Intel® RealSense™ Devices (build 2.0.2)
librealsense-2.10.1
ROS kinetic
Ubuntu 16.04
Fireware version: 05.08.15.00

**Comment by stwirth** [comment]
You have to either set the parameter before launching the camera driver or you use the dynamic reconfigure API:
Via command line:
```
rosrun dynamic_reconfigure dynparam set my_camera_node_name rs435_color_exposure 1000
```
Via python API:
```
import dynamic_reconfigure
client = dynamic_reconfigure.client.Client("my_camera_node_name")
client.update_configuration({"rs435_color_exposure": 1000})
```
Here's [the tutorial on ros.org](http://wiki.ros.org/dynamic_reconfigure/Tutorials/UsingTheDynamicReconfigurePythonClient).

**Comment by jonasgerne** [comment]
Hi, I updated to Realsense 2.17.1 today and now I'm facing the issue that dynamic_reconfigure doesn't work like it used to work. Using dynparam set via command line works fine:
`rosrun dynamic_reconfigure dynparam set /camera1/Stereo_Module/ "Enable Auto Exposure" True`

However, I want to set parameters using thy python API:
```
import dynamic_reconfigure  
client = dynamic_reconfigure.client.Client("/camera1/Stereo_Module/")  
client.update_configuration({"Enable Auto Exposure": "true"})  
```
Here, the update step doesn't work at all. Can someone help, please?

**Comment by jonasgerne** [comment]
I'm sorry, my mistake was to test it in a python console without initializing a ROS node. Everything works fine now!

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]
