### ISSUE TITLE
 ‘motion_stream_profile’ is not a member of ‘rs2’

### ISSUE THREAD

**Issue by SteveMacenski** [realsenseai/realsense-ros#348]
I'm having this error along with 

` no matching function for call to ‘rs2::stream_profile::as()’`

`error: template argument 1 is invalid
     auto sp = _enabled_profiles[stream_index].front().as<rs2::motion_stream_profile>();`

They seem to be all located from the rs_frame.hpp file, but even when modified to include it, still appearing in versions 2.10.0, 2.10.1, and current.

**Comment by deadundead** [comment]
I had this issue, try building librealsense from source.
