### ISSUE TITLE
How to change the tf name for D435 cameras?

### ISSUE THREAD

**Issue by tcjcxy30** [realsenseai/realsense-ros#354]
Hi ：
    I use a D435 to replace kinect v1 on my robot. It's hard to me because there are three problem.
    1. the tf link of the color frame is called `camera_color_frame`, but the kinect named `camera_rgb_frame`. So I change the str in the file `include/constrants.h` from `camera_color_frame` to `camera_rgb_frame`. Also i change the rgb value in the launch file. By this way, the rbg image `camera_info` can be related to `camera_rgb_frame`, but the point cloud can't be seen in rviz now, it so wired. So how can i do to change the color frame to camera_rgb_frame?
    2. After I change the code by 1, the D435 can't be reconnected again. I need to pull out the usb and pick again, the D435 can be reconnected. I get the erroe warning  `(backend-v4l2.cpp 808) empty frame has arrived` So what wrong with me?
    3. The tf name is hard to change, in openni, i can name the frame like `<arg name="camera" default="my_camera" />` and the link can be seen as `my_camera_link`, but here I can't do like this. So how to change the link name easily?

**Comment by neomanic** [comment]
1. Don't go changing the realsense source, that'll just end up being a pain. Rather, you should use the [tf_remap](http://wiki.ros.org/tf#tf_remap) node to remap /camera_color_frame to /camera_rgb_frame

2. As I commented in issue #346, this is a known issue. I have to re-plug the cameras every time I close the ROS node.

3. Use tf_remap node

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]
