### ISSUE TITLE
Is it possible to extract surface normal in real-time?

### ISSUE THREAD

**Issue by Kyungdon** [realsenseai/realsense-ros#357]
Hi,

I'm trying to get surface normals from the depth image. Is there any recommendation to extract surface normal in real-time?

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Close this issue for lack of activity. Please feel free to reopen if the issue is still relevant.
