### ISSUE TITLE
Drifting timestamps for ZR300

### ISSUE THREAD

**Issue by tytyl** [realsenseai/realsense-ros#361]
Realease 1.8.0 solved the drifting timestamp problem by adding the SyncNodelet class for F200/SR300/R200 (#207). 
Is there also a fix for ZR300?

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Close this issue for lack of activity. Please feel free to reopen if the issue is still relevant.
