### ISSUE TITLE
exposing camera name in nodelet for users with multiple cameras

### ISSUE THREAD

**Issue by SteveMacenski** [realsenseai/realsense-ros#371]
i.e.

`camera_depth_optical_frame` being `${arg camera}_depth_optical_frame` and expose the camera name as a parameter.

This helps tremendously for users with multiple cameras

**Comment by SteveMacenski** [comment]
https://github.com/intel-ros/realsense/pull/425 would resolve

**Comment by doronhi** [comment]
merged PR#426. Taking care of this issue.
