### ISSUE TITLE
depth (post processing) in ROS?

### ISSUE THREAD

**Issue by Kyungdon** [realsenseai/realsense-ros#378]
Is it possible to activate the depth post-processing in ROS?

**Comment by yuyu2172** [comment]
I was wondering the same thing.

**Comment by janisa9** [comment]
I am also wondering the same thing, is it worth even to look for post processing options in this driver?

**Comment by johannesburg** [comment]
I've added three of the four available post processing filters to the realsense ROS library (temporal, spatial, and hole filling filter) and am currently working on adding the decimation filter. If you'd like to use the code, feel free to use my [forked repo](https://github.com/johannesburg/uw-realsense). All parameters are configurable via the launch files.

**Comment by vatbrain** [comment]
It would be really nice to see this resolved (even partially) in the main development branch soon please.

**Comment by ManMan88** [comment]
I think this [forked repo](https://github.com/johannesburg/uw-realsense) won't build with the newest librealsense2.

I get the following error when trying to make:

```
 /usr/include/librealsense2/hpp/rs_sensor.hpp:109:13: error: no match for call to ‘(rs2::asynchronous_syncer) (rs2::frame)’
              on_frame_function(frame{ fref });
```

**Comment by doronhi** [comment]
Yeah, well, it’s really not up to date.
