### ISSUE TITLE
the rostopic  "aligned_depth" not accurate as topic depth/image_raw

### ISSUE THREAD

**Issue by GITSHOHOKU** [realsenseai/realsense-ros#379]
I use sr300 and need to aligned the depth to color, the accuracy of topic aligned_depth_to_color which realsense2_camer provide is much lower than the topic depth/image_raw,anybody know how to fix this?
thanks
PS:Is there an easy way to aligned depth/image_raw to color/image_raw? I find /camera/extrinsics/depth_to_color just use an identity matrix,should I change it?

**Comment by GITSHOHOKU** [comment]
Is there an easy way to aligned depth/image_raw to color/image_raw?

**Comment by AlanBB277** [comment]
Hello @GITSHOHOKU 
Perhaps this issue is same as the one the PR #367 is fixing.
The PR is not accepted yet currently, so you can do the same modification to see if it helps you.
Thanks : )
