### ISSUE TITLE
Confusion with camera models

### ISSUE THREAD

**Issue by ghost** [realsenseai/realsense-ros#382]
I was hoping someone would help me clarify some stuff.  We are planning on using a couple D415 cameras with our setup and wanted to be sure that this package will support it?  Can someone confirm this?
Also, I am confused with R410 vs D410 vs D415.  The only URDF I see in this packages is called R410, is this the same as the D410 module used in the D415 camera?  
If yes, can someone confirm how the camera_link in the URDF relates to the tripod screw hole on the D415 camera case.

Thanks in advance.

**Comment by doisyg** [comment]
Same question about the URDF of the D430 modules, how does it relate to the D435?

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Hi

In general, the difference between D410 vs D15, or D430 vs D435 is the RGB Color camera. The D410/D430 is "without RGB camera", where D415/D435 is "with RGB camera".

Thanks
