### ISSUE TITLE
Due to wrong coordinate transfomations, in camera view, PointCloud doesn't align with the actual image

### ISSUE THREAD

**Issue by mikolajz** [realsenseai/realsense-ros#384]
To reproduce:
* launch the RealSense node.
* open rviz.
* in rviz, add the PointCloud2 and a Camera for color/image_raw. If testing with objects close enough, reduce the "Size" in PointCloud2 or change "Style" to point.
* In the Camera window, we will see the pointcloud from the camera viewpoint. Since point colors are computed from color/image_row, the images should align up to floating point rounding errors, but they clearly don't.

The code in https://github.com/intel-ros/realsense/pull/383 fixes the problem.

**Comment by doronhi** [comment]
Fix was merged. Thank you for turning our attention and contributing the solution.
Will be part of next release.
