### ISSUE TITLE
Unable to switch from Custom to HighAccuracy mode (D435

### ISSUE THREAD

**Issue by PaulKemppi** [realsenseai/realsense-ros#390]
I get the following error when using the dynamic reconfigure tool to change the rs435_depth_visual_preset (e.g. from Custom to HighAccuracy): 

04/06 10:13:43,417 WARNING [139762229450624] (types.cpp:57) get_pu(id=4) failed! Last Error: Input/output error
[ WARN] [1528096423.419793437]: Reconfigure callback failed with exception get_pu(id=4) failed! Last Error: Input/output error: 

The mode is not changed. Replugging the sensor won't help. With the same sensor, the mode is always changed when using the RealsenseViewer in Windows10.

Environment:
Operating system: Ubuntu 16.04 (64bit)
ROS version: Kinetic
Sensor: Realsense D435
Realsense ROS driver: RealSense ROS v2.0.3
Realsense SDK: LibRealSense v2.11.0
Device FW version: 05.09.11.00
Device Product ID: 0x0B07

How to reproduce:
-Connect the sensor
-Start the ROS driver:
$ roslaunch realsense2_camera rs_rgbd.launch
-Start the reconfigure tool:
$ rosrun rqt_reconfigure rqt_reconfigure 
-Change the rs435_depth_visual_preset e.g. from Custom to HighAccuracy

**Comment by GuidoBartoli** [comment]
I sometimes have the  same problem on Linux and I think it is related to [this](https://github.com/IntelRealSense/librealsense/issues/1213) firmware issue.
I hope they will fix it in the next version...

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Close this issue for lack of activity. Please feel free to reopen if the issue is still relevant.
