### ISSUE TITLE
stream frames on reconnection

### ISSUE THREAD

**Issue by henryjchang** [realsenseai/realsense-ros#393]
The current behavior when a camera is disconnected is that the ROS node is terminated: https://github.com/intel-ros/realsense/blob/development/realsense2_camera/src/realsense_node_factory.cpp#L74-L82

If we don't terminate the ROS node upon disconnection and if the same camera is reconnected, we should expect the frames to be streamed again. However, that is not the case.

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Close this issue for lack of activity. Please feel free to reopen if the issue is still relevant.
