### ISSUE TITLE
water ripple result in rs_rgbd.launch ??

### ISSUE THREAD

**Issue by wennycooper** [realsenseai/realsense-ros#398]
Hi,

When I launch rs_rgbd.launch with my D435,  I saw dynamic distortion in rviz... something like water ripple effect. Is that normal??  (I'm using SDK librealsense-2.10.2)

![screenshot from 2018-06-20 13-59-18](https://user-images.githubusercontent.com/7479445/41643241-3e8b6bce-749d-11e8-9fff-90df700b2568.png)

**Comment by SteveMacenski** [comment]
Seems par for the course in my experience with these cameras

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Close this issue for lack of activity. Please feel free to reopen if the issue is still relevant.
