### ISSUE TITLE
Layered offset observed in SR300-RGBD aligned Pointcloud2 object 

### ISSUE THREAD

**Issue by midiisc** [realsenseai/realsense-ros#403]
![peek 2018-07-01 11-39](https://user-images.githubusercontent.com/12725285/42133060-b0f4f75a-7d23-11e8-8784-eaa1f9b29b82.gif)
Hi. I am using the ROS wrapper(2.0.3) for _librealsense2_ and using MATLAB ROS interface to acquire depth point clouds from my SR300 camera into _MATLAB 2018a_. The scatter plot of the depth point cloud looks like the attached GIF file(of my face). Clearly, there is a layered offset seen in the cloud with some patches of data(nose-mouth region) getting an offset from the rest of the depth data. Could you help me figure this out. I am subscribing to the /camera/depth_registered/points topic and using _readXYZ_ to extract XYZ coordinates. The launch command used for ROS network is "_roslaunch realsense2_camera rs_rgbd.launch_". I am using _Ubuntu 16.04LTS_. 

I am totally new to ROS and SR300, so pardon me for any silly mistakes in my way of writing this request.

Eagerly awaiting your help in this regard.

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Close this issue for lack of activity. Please feel free to reopen if the issue is still relevant.
