### ISSUE TITLE
/camera/aligned_depth_to_color/image_raw/compressed topic at only 2.7fps

### ISSUE THREAD

**Issue by martinakos** [realsenseai/realsense-ros#407]
The color and depth streams are configured to work at 30ps.
I can verify the 30fps on most topics but on /camera/aligned_depth_to_color/image_raw/compressed is only 2.7fps. **is this normal?** see below:

 rostopic hz /camera/aligned_depth_to_color/image_raw/compressed
subscribed to [/camera/aligned_depth_to_color/image_raw/compressed]
average rate: 2.755
	min: 0.363s max: 0.363s std dev: 0.00000s window: 2
average rate: 2.711
	min: 0.363s max: 0.377s std dev: 0.00523s window: 5
average rate: 2.708
	min: 0.363s max: 0.377s std dev: 0.00499s window: 8
average rate: 2.708
	min: 0.363s max: 0.377s std dev: 0.00473s window: 10
average rate: 2.706
	min: 0.363s max: 0.377s std dev: 0.00427s window: 13

rostopic hz /camera/aligned_depth_to_color/image_raw/
subscribed to [/camera/aligned_depth_to_color/image_raw]
average rate: 29.816
	min: 0.031s max: 0.035s std dev: 0.00066s window: 29
average rate: 29.797
	min: 0.031s max: 0.035s std dev: 0.00061s window: 59
average rate: 29.787
	min: 0.031s max: 0.035s std dev: 0.00057s window: 89
average rate: 29.780
	min: 0.031s max: 0.035s std dev: 0.00063s window: 99

rostopic hz /camera/color/image_raw/compressed
subscribed to [/camera/color/image_raw/compressed]
average rate: 29.838
	min: 0.032s max: 0.035s std dev: 0.00051s window: 30
average rate: 29.794
	min: 0.032s max: 0.035s std dev: 0.00039s window: 59
average rate: 29.685
	min: 0.028s max: 0.042s std dev: 0.00135s window: 85

I'm trying to record the /camera/aligned_depth_to_color/image_raw/compressed topic in a rosbag and I want it to be recorded at 30fps

**Comment by martinakos** [comment]
Ok. I restarted the machine and try again and now I get 30pfs for the  /camera/aligned_depth_to_color/image_raw/compressed too. But the /camera/aligned_depth_to_color/image_raw/compressedDepth is around 3fps ever after a restart.

**Comment by jakalaka** [comment]
hello,can you please share the code of how to get distance from /camera/aligned_depth_to_color/image_raw/compressed topic? I'm using image_transport plug-in and struggling...

**Comment by SHTseng** [comment]
I manage to get higher fps by setting the compression params

`<param name="/camera/depth/image_rect_raw/compressed/format" type="string" value="png" />`
`<param name="/camera/depth/image_rect_raw/compressed/png_level" type="int" value="4" />`

But I haven't reconstruct the point cloud yet, not sure how much this will affect the image quality.

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Hi martinakos,

Sorry for taking a while to come over to this one.

Not sure if which version of ROS release, which camera and FW you had. Can you please share more info?
Off an Intel NUC i5, I tested with ROS 2.2.3 with a D435 FW 5.11.6.100, and don't see issue with frame rate.


[INFO] [1555350751.681862406]: RealSense ROS v2.2.3
[INFO] [1555350751.681964526]: Running with LibRealSense v2.19.1
[INFO] [1555350751.814936599]: getParameters...
[INFO] [1555350751.913431071]: setupDevice...
[INFO] [1555350751.913473484]: JSON file is not provided
[INFO] [1555350751.913499594]: ROS Node Namespace: camera
[INFO] [1555350751.913526622]: Device Name: Intel RealSense D435
[INFO] [1555350751.913547845]: Device Serial No: 728612070408
[INFO] [1555350751.913571910]: Device FW version: 05.11.06.100
[INFO] [1555350751.913590046]: Device Product ID: 0x0B07
[INFO] [1555350751.913607663]: Enable PointCloud: Off
[INFO] [1555350751.913626197]: Align Depth: On
[INFO] [1555350751.913646816]: Sync Mode: On


Below is frame rate info (for the ones you tested) from my test:

ros@ros-desktop:~/catkin_ws$ rostopic hz /camera/aligned_depth_to_color/image_raw
subscribed to [/camera/aligned_depth_to_color/image_raw]
average rate: 30.589
 min: 0.006s max: 0.041s std dev: 0.00620s window: 29
average rate: 30.243
 min: 0.006s max: 0.041s std dev: 0.00464s window: 58
average rate: 29.870
 min: 0.006s max: 0.051s std dev: 0.00450s window: 88
average rate: 29.901
 min: 0.006s max: 0.051s std dev: 0.00433s window: 118
average rate: 29.931
 min: 0.006s max: 0.051s std dev: 0.00410s window: 148
^Caverage rate: 29.941
 min: 0.006s max: 0.051s std dev: 0.00399s window: 161
ros@ros-desktop:~/catkin_ws$ rostopic hz /camera/aligned_depth_to_color/image_raw/compressed
subscribed to [/camera/aligned_depth_to_color/image_raw/compressed]
average rate: 31.049
 min: 0.007s max: 0.058s std dev: 0.00926s window: 28
average rate: 30.382
 min: 0.007s max: 0.058s std dev: 0.00699s window: 58
average rate: 30.161
 min: 0.007s max: 0.058s std dev: 0.00650s window: 88
average rate: 29.956
 min: 0.007s max: 0.058s std dev: 0.00652s window: 117
average rate: 29.970
 min: 0.007s max: 0.058s std dev: 0.00590s window: 147
^X^Caverage rate: 29.968
 min: 0.007s max: 0.058s std dev: 0.00567s window: 161
ros@ros-desktop:~/catkin_ws$
ros@ros-desktop:~/catkin_ws$
ros@ros-desktop:~/catkin_ws$ rostopic hz /camera/color/image_raw/compressed
subscribed to [/camera/color/image_raw/compressed]
average rate: 33.347
 min: 0.003s max: 0.053s std dev: 0.01103s window: 29
average rate: 31.525
 min: 0.003s max: 0.053s std dev: 0.00801s window: 59
average rate: 30.976
 min: 0.003s max: 0.053s std dev: 0.00664s window: 89
average rate: 30.739
 min: 0.003s max: 0.053s std dev: 0.00610s window: 118
average rate: 30.566
 min: 0.003s max: 0.053s std dev: 0.00563s window: 149
average rate: 30.465
 min: 0.003s max: 0.053s std dev: 0.00520s window: 179
^Caverage rate: 30.422
 min: 0.003s max: 0.053s std dev: 0.00505s window: 194

Thanks!

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Hi martinakos,

Any update on this one?

Thanks!

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Hi martinakos,

If there is nothing else needed, this one will be closed.

Thanks!
