### ISSUE TITLE
Red image

### ISSUE THREAD

**Issue by sanjifr3** [realsenseai/realsense-ros#408]
When using the launch script, and rqt_image_view to view the topic "/camera/color/image_raw", the red in the image is pronounced. Is there a way to fix this?

![image](https://user-images.githubusercontent.com/15000600/42544864-4c52e8c8-8482-11e8-9065-c7c19bea0786.png)

**Comment by dorodnic** [comment]
Colour camera settings are persistent and stored in camera flash. You can use `realsense-viewer` tool to adjust various colour sensor options.

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Close this issue for lack of activity. Please feel free to reopen if the issue is still relevant.

**Comment by SteveMacenski** [comment]
I'd recommend updating the defaults in ROS drivers to not have this red feature. I've seen this across nearly all (several hundred) units I've touched.

**Comment by doronhi** [comment]
> I'd recommend updating the defaults in ROS drivers to not have this red feature. I've seen this across nearly all (several hundred) units I've touched.

I think it would be more beneficial to suggest it in the librealsense github.

**Comment by SteveMacenski** [comment]
Its not a librealsense issue, the defaults in librealsense are good. Its the defaults in this repo that are not

**Comment by doronhi** [comment]
> Its not a librealsense issue, the defaults in librealsense are good. Its the defaults in this repo that are not

I must have misunderstood you. What defaults are you referring to?

**Comment by SteveMacenski** [comment]
The white balance. In RS view all is good, its only the ROS realsense driver that produces the red images. I found `rs435_color_white_balance 360` to work pretty well vs the 460 that's default

**Comment by doronhi** [comment]
I don't see it, at least not in the latest realsense2_camera versions. 
I agree that 3600 is better than 4600 but that is the device's default. Also, it is, by default, set to automatic white balance so it doesn't matter. 
It's the same with realsense-viewer.  Neither of them change the device's values by default.
