### ISSUE TITLE
[realsense2] release to kinetic/ubuntu 16.04

### ISSUE THREAD

**Issue by fmessmer** [realsenseai/realsense-ros#410]
do you plan to release `realsense2_camera` and `librealsense2` into kinetic/xenial anytime soon?
it'd be highly appreciated....

**Comment by YuehChuan** [comment]
can we use D435 camera with ros wrapper? 
Without ros I could run it correctly 
I got such error  when `roslaunch realsense2_camera rs_rgbd.launch`
![realsense_error](https://user-images.githubusercontent.com/7314531/42727511-ffd37808-87da-11e8-8c30-f31dc4bed461.png)

Thanks, or I should open new issue.

**Comment by fiorano10** [comment]
@fmessmer I've been running `realsense2_camera` and `librealsense2` on Kinetic/Xenial for the past 4 months

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Close this issue for lack of activity. Please feel free to reopen if the issue is still relevant.

**Comment by SteveMacenski** [comment]
Still relevant
