### ISSUE TITLE
[D435 ]/opt/ros/kinetic/lib/libbondcpp.so: undefined symbol: _ZN3ros11SteadyTimerD1Ev

### ISSUE THREAD

**Issue by YuehChuan** [realsenseai/realsense-ros#412]
camera model D435 
4.13.0-43-generic kernel  ubuntu16.04.3
ROS kinetic
D435 Firmware :05.09.09.02
librealsense build from source: 2.13.0

package:
realsense2_camera

I get apt ros-kinetic-nodelet  ros-kinetic-nodelet-core installed

Without ros I could run it correctly.
I got such error when roslaunch realsense2_camera rs_rgbd.launch
```bash=
[ INFO] [1531594763.160792828]: Initializing nodelet with 8 worker threads.
/opt/ros/kinetic/lib/nodelet/nodelet: symbol lookup error: /opt/ros/kinetic/lib/libbondcpp.so: undefined symbol: _ZN3ros11SteadyTimer4stopEv
[FATAL] [1531594763.227766803]: Failed to load nodelet '/camera/points_xyzrgb_hw_registered` of type `depth_image_proc/point_cloud_xyzrgb` to manager `realsense2_camera_manager'
[FATAL] [1531594763.227823744]: Failed to load nodelet '/camera/realsense2_camera` of type `realsense2_camera/RealSenseNodeFactory` to manager `realsense2_camera_manager'
```

![realsense_error](https://user-images.githubusercontent.com/7314531/42727547-ea1150ca-87db-11e8-93e4-064a31706d74.png)

relate issue:
https://answers.ros.org/question/225986/nodelet-service-failed-on-symbol-lookup/
https://github.com/intel-ros/realsense/issues/343
https://github.com/intel-ros/realsense/issues/349
https://github.com/intel-ros/realsense/issues/410

**Comment by FYPBois** [comment]
Bump! Same issue.

**Comment by edwardsteds** [comment]
Same issue ..

**Comment by RatheeshRK** [comment]
Same issue .. Looking forward for support...

**Comment by qiupeizhao** [comment]
Same issue. Someone please answer

**Comment by zwzzsyxqq** [comment]
Same issue!

**Comment by Abhicoder1999** [comment]
same issue!!

**Comment by Williamc17** [comment]
same issue!!!

**Comment by doronhi** [comment]
It's not happening for me.
@YuehChuan , what do you mean by "Without ros I could run it correctly."?
Do you manage to reproduce the error with an updated version of librealsense (2.17.1)?
I assume the realsense_2_camera is up to date (version 2.1.3)

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Hi @YuehChuan,
Does the issue persist with the latest ROS wrapper (2.2.1) and librealsense (2.19.x) combo?

**Comment by YuehChuan** [comment]
@RealSenseCustomerSupport  
Thanks for pinging me, I have no hardware for now, so cannot test it.

**Comment by xtywbpute** [comment]
> camera model D435
> 4.13.0-43-generic kernel ubuntu16.04.3
> ROS kinetic
> D435 Firmware :05.09.09.02
> librealsense build from source: 2.13.0
> 
> package:
> realsense2_camera
> 
> I get apt ros-kinetic-nodelet ros-kinetic-nodelet-core installed
> 
> Without ros I could run it correctly.
> I got such error when roslaunch realsense2_camera rs_rgbd.launch
> 
> ```
> [ INFO] [1531594763.160792828]: Initializing nodelet with 8 worker threads.
> /opt/ros/kinetic/lib/nodelet/nodelet: symbol lookup error: /opt/ros/kinetic/lib/libbondcpp.so: undefined symbol: _ZN3ros11SteadyTimer4stopEv
> [FATAL] [1531594763.227766803]: Failed to load nodelet '/camera/points_xyzrgb_hw_registered` of type `depth_image_proc/point_cloud_xyzrgb` to manager `realsense2_camera_manager'
> [FATAL] [1531594763.227823744]: Failed to load nodelet '/camera/realsense2_camera` of type `realsense2_camera/RealSenseNodeFactory` to manager `realsense2_camera_manager'
> ```
> 
> ![realsense_error](https://user-images.githubusercontent.com/7314531/42727547-ea1150ca-87db-11e8-93e4-064a31706d74.png)
> 
> relate issue:
> https://answers.ros.org/question/225986/nodelet-service-failed-on-symbol-lookup/
> #343
> #349
> #410

Please upgrade the [indigo] of catkin_workspace package [ros_comm]  to [kinetic]

**Comment by ChaeChae0505** [comment]
please answer,,,,,,

**Comment by XiaoJake** [comment]
same issue!
But, D435 can work fine on my other Xavier, very strange.
I don't know what the problem is when I build the new system environment.
