### ISSUE TITLE
Setting Depth Clamp Min/Max in intel-ros

### ISSUE THREAD

**Issue by arrfou90** [realsenseai/realsense-ros#413]
Hi, setting the Depth Clamp Min/Max for Intel RealSense D400 series cameras is not provided by this ros package. Do you know how I can easily do that through the configuration file.

**Comment by frk1993** [comment]
Hi,
do you have a solution for this problem ?

best regards

**Comment by doronhi** [comment]
There is the flag `clip_distance` as described in the README.md file for clipping points at distance farther then a given value. There is no option for clipping points with shorter distance then a given value .

**Comment by TiagoTostas** [comment]
Hi,
About the clipping distance, does the clipping distance affects the resolution of the pointcloud?
Or what is the main advantage compared to the distance threshold filtering?

Thanks

**Comment by doronhi** [comment]
The distance threshold filter is not available in the ROS wrapper.
Clipping the distance has no effect on the resolution or anything else. It just remove pixels of range greater than the given value.

**Comment by TiagoTostas** [comment]
Thanks
Meanwhile I realised that my question was more about the configurations for min/max range, rather than a problem about the clipping distance
