### ISSUE TITLE
Possible time drift

### ISSUE THREAD

**Issue by pavloblindnology** [realsenseai/realsense-ros#419]
According to next lines, if device time drifts away from host time, then ROS frame timestamps will also drift, because software synchronization is done only once after the 1st frame retrieval.
https://github.com/intel-ros/realsense/blob/5210e673ec0d266c62590b433c8b568954f4fdfd/realsense2_camera/src/base_realsense_node.cpp#L543
https://github.com/intel-ros/realsense/blob/5210e673ec0d266c62590b433c8b568954f4fdfd/realsense2_camera/src/base_realsense_node.cpp#L550
The drift could be avoided if we had possibility to get current camera time.
Then we could compare it to frame timestamp and convert the latter to host time with the next formula:
`frame_timestamp_host = current_timestamp_host - (current_timestamp_camera - frame_timestamp_camera)`

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]
