### ISSUE TITLE
Is there support for relasense D410 cameras?

### ISSUE THREAD

**Issue by Vuwij** [realsenseai/realsense-ros#420]
I got the D410 camera, but when I tried RViz, I couldn't find a way to use one of the cameras as a RGB camera

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

D410 has no RGB sensor. D415 has RGB camera.
