### ISSUE TITLE
[Question] Support for streaming data to remote computer/workstation

### ISSUE THREAD

**Issue by ahasenfr** [realsenseai/realsense-ros#421]
I wanted to ask if there is the intention from the team to release launch files that separate the workload.
So that I can run a launch file on one computer where the camera is plugged in, I only stream the raw data and on another computer I run another launch file that converts the data (aligned_depth, enable_pointcloud).

Wasn't able to look in until now, if there is already a node/package that could do that work for me and also fits with the file format that the realsense package produces...

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Close this issue for lack of activity. Please feel free to reopen if the issue is still relevant.
