### ISSUE TITLE
Tx,Ty not filled in CameraInfo for infra2

### ISSUE THREAD

**Issue by pavloblindnology** [realsenseai/realsense-ros#427]
According to the next line Tx, Ty is not filled for right image CameraInfo. As the result, baseline cannot be resolved in a standard ROS way. 
https://github.com/intel-ros/realsense/blob/5210e673ec0d266c62590b433c8b568954f4fdfd/realsense2_camera/src/base_realsense_node.cpp#L828

**Comment by dorodnic** [comment]
@doronhi seems like a bug on our side, right?

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]

**Comment by doronhi** [comment]
With #1242 now merged, I believe this issue can be closed.
