### ISSUE TITLE
How calibration d415 on ROS?

### ISSUE THREAD

**Issue by SanoTetsuya** [realsenseai/realsense-ros#428]
I want to use d416 on ros.
I set up realsense2 on my environment. Then I can use realsense2. I used this command roslaunch realsense2_camera rs_camera.launch. So I want to calibration on this camera. I made yaml file for camera calibration. Then I added that yaml file path on rs_camera.launch in realsense2. But I could not change the camera calibration information. /camera/color/camera_info did not change. Please help me.

**Comment by freemanlo** [comment]
Hi @SanoTetsuya,

You can use Intel Dynamic Calibration or refer to below white paper to have your own calibration. 
Dynamic Calibration. 
https://www.intel.com/content/www/us/en/support/articles/000026723/emerging-technologies/intel-realsense-technology.html
Custom Calibration: (Y16 format is required for IR)
https://www.intel.com/content/www/us/en/support/articles/000026725/emerging-technologies/intel-realsense-technology.html

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Close this issue for lack of activity. Please feel free to reopen if the issue is still relevant.
