### ISSUE TITLE
Given depth profile is not supported even when depth is turned off.

### ISSUE THREAD

**Issue by alspitz** [realsenseai/realsense-ros#429]
It seems that the ROS node checks if the depth profile is enabled even if no depth stream is requested. This results in the error:

`Given depth profile is not supported by current device!`

I would think the check at https://github.com/intel-ros/realsense/blob/5210e673ec0d266c62590b433c8b568954f4fdfd/realsense2_camera/src/base_realsense_node.cpp#L839 should only happen if the user requests a depth stream.

Is only streaming color images not supported or am I doing something wrong?

**Comment by J-Rojas** [comment]
Realsense viewer allows the depth projector to be entirely disabled so this should be supported through some configuration.

**Comment by doronhi** [comment]
I added PR#601 to fix this issue while preserving static transforms.
It's been a long while but, if it's not too much trouble, I would appreciate your checking this out before I merge. 
Thanks and sorry for the long delay.

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Close this issue for lack of activity. Please feel free to reopen if the issue is still relevant.
