### ISSUE TITLE
Depth stream lost after restart

### ISSUE THREAD

**Issue by zyuan2009** [realsenseai/realsense-ros#434]
Depth stream was lost after D435 sensor restart, and restart again it works again.

Run 1: Depth/Color stream are available
Run 2: Only Color stream is available
Run 3: Depth/Color stream are available
Run 4: Only Color stream is available 
....

This is a pattern and I can trace down into linux/backend-v4l2.cpp: v4l_uvc_device::poll() for Depth stream is failing every other run (select for the _fd of depth stream is timeout).

Simply adding a _device.hardware_reset() in RealsenseNodeFactory::onInit would solve this problem.
Code like this:

        GetDevice(serial_no, _ctx, _device);

        ROS_INFO_STREAM("Device with serial number " << serial_no << " is bing hardware reset.");
        _device.hardware_reset();
        // Wait for the hardware reset to take effect
        std::this_thread::sleep_for(std::chrono::seconds(5));
        GetDevice(serial_no, _ctx, _device);

It looks like it is a firmware issue - please help to fix it. thanks.

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Close this issue for lack of activity. Please feel free to reopen if the issue is still relevant.
