### ISSUE TITLE
Getting distance to objects from depth_map

### ISSUE THREAD

**Issue by WelsyCZ** [realsenseai/realsense-ros#436]
Hey, I have had no success finding how to get distance to objects using the depth_map.
I'm using the '/camera/depth/image_rect_raw' topic, I made a subscriber that reads the messages, converts them to OpenCV Mats using cv_bridge and then displays them in a window (depth_map image: https://i.imgur.com/QyKWp2J.png ), however I don't know how to actually use the depth image. 

I know there is an API in the official SDK from intel, however I don't know what to use when using the ROS Wrapper. I know the map is in CV_16UC1 format, but thats about it. I dont know if the number is milimeters or if it's somehow scaled. I'd be glad for any kind of advice.

My code if you're interested, though I don't think it particularly helps:

```
#include "ros/ros.h"
#include "geometry_msgs/Twist.h"
#include "sensor_msgs/Image.h"
#include <iostream>
#include "image_transport/image_transport.h"
#include <opencv2/opencv.hpp>
#include <cv_bridge/cv_bridge.h>



void handleTwist(const geometry_msgs::Twist& msg);
void handleCamera(const sensor_msgs::ImageConstPtr& msg);

std::string OPENCV_WINDOW = "Camera";

int main(int argc, char** argv)
{
    ros::init(argc,argv,"coldetect_node");

    ros::NodeHandle nh;
    image_transport::ImageTransport it(nh);
    ros::Subscriber twist = nh.subscribe("cmd", 1000, handleTwist);
    image_transport::Subscriber camera = it.subscribe("camera/depth/image_rect_raw", 1, handleCamera);
    cv::namedWindow(OPENCV_WINDOW, cv::WINDOW_AUTOSIZE);

    ros::spin();

    cv::destroyAllWindows();
    return 0;

}

void handleTwist(const geometry_msgs::Twist& msg){
    ROS_INFO("\nlinear:{%.1f,%.1f,%.1f}\nangular:{%.1f,%.1f,%.1f}", msg.linear.x, msg.linear.y, msg.linear.z, msg.angular.x, msg.angular.y, msg.angular.z);    
}

void handleCamera(const sensor_msgs::ImageConstPtr& msg){
    //ROS_INFO("Image received");
    cv_bridge::CvImageConstPtr cv_ptr;
    try
    {
      cv_ptr = cv_bridge::toCvCopy(msg, sensor_msgs::image_encodings::TYPE_16UC1);
      ROS_INFO("copied image");
    }
    catch (cv_bridge::Exception& e)
    {
      ROS_ERROR("cv_bridge exception: %s", e.what());
      return;
    }
    cv::imshow(OPENCV_WINDOW, cv_ptr->image);
    cv::waitKey(100);
}
```

**Comment by freemanlo** [comment]
Hi @WelsyCZ,

The unit of 16bit depth value should be based on mm. You can also refer to the function "get_depth_scale" in librealsense SDK to get the depth scale.

**Comment by lchop** [comment]
Hello !
Same problem, here I am trying to get the depth of some pixels inside a ROI from the /camera/depth/image_rect_raw with no result. Did youy make any progress on this ?
Thanks !

**Comment by freemanlo** [comment]
How about trying "rostopic echo /camera/depth/image_rect_raw" to see if you can get the 16bit depth value?

**Comment by lchop** [comment]
Hi,
I finally succed but with the CV_32FUC1 format, very strange because looking at the code of the wrapper the depth image is encoded in CV_16UC1.
Best regards !

**Comment by gongyue666** [comment]
@lchop can you share the code, I get the depth image which value from 0-255, I don't know how to tranform them into meters.

**Comment by lchop** [comment]
Hello,
I used one line of code in my callback when I receive a new depth image:
```cpp
last_received_depth_ = cv_bridge::toCvCopy(*depth, sensor_msgs::image_encodings::TYPE_32FC1);
```
Depth map will be in mm. So i am using cv_bridge as you can guess.  I hope this help !
Best regards !

**Comment by gongyue666** [comment]
thx

**Comment by freemanlo** [comment]
I have some modification as follows to display depth (16UC1) as color map.

    void handleCamera(const sensor_msgs::ImageConstPtr& msg){
    //ROS_INFO("Image received");
    cv_bridge::CvImagePtr cv_ptr;

    try
    {
      cv_ptr = cv_bridge::toCvCopy(msg, sensor_msgs::image_encodings::TYPE_16UC1);
      ROS_INFO("copied image");
    }
    catch (cv_bridge::Exception& e)
    {
      ROS_ERROR("cv_bridge exception: %s", e.what());
      return;
    }

    Mat depth_colormap;
    cv::convertScaleAbs(cv_ptr->image, depth_colormap, 0.03);
    cv::applyColorMap(depth_colormap, depth_colormap, cv::COLORMAP_JET);
    cv::imshow(OPENCV_WINDOW, depth_colormap);

    cv::waitKey(100);
    }

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]
