### ISSUE TITLE
frames didn't arrived within 5 seconds

### ISSUE THREAD

**Issue by qiuchenli** [realsenseai/realsense-ros#443]
Dear sir,:
I use realsense d435 in ubuntu 16.04 for the use of pointcloud,when use
$ roslaunch realsense2_camera rs_rgbd.in terminal, 
sometims it didn't get pointcloud infomation and the terminal get the info that "frames didn't arrived within 5 seconds",any solutions?
PS: I tried the solutions that add "reset device",but found that would affect the fps,(almost 7fps).

**Comment by fiorano10** [comment]
@qiuchenli This has been documented here:[Frames didn't arrive error](https://github.com/IntelRealSense/librealsense/issues/1086)
If it's the PointCloud then the frame rate would remain stable ~6-7FPS even before the reset.

The pcl library depends heavily on the clock speed of the CPU. Do you get a higher frame rate before resetting the camera? If so, try unplugging and replugging the camera, and see if that affects the frame rate as well.

**Comment by qiuchenli** [comment]
@fiorano10 I tried the reset ros wrapper(https://github.com/icarpis/realsense/tree/reset_dev) in my laptop and the FPS down from 30Hz to 26Hz, but in the machine, the FPS down from 27Hz to 16Hz, I think maybe the problem is my hardware, the reset policy has no problem. Thanks for a lot!

**Comment by qiuchenli** [comment]
dear sir:
I make a reply on github, just as below:

I use realsense in ros wrapper, to add the reset policy I use the reset ros wrapper(https://github.com/icarpis/realsense/tree/reset_dev)  in my laptop and the FPS down from 30Hz to 26Hz, but in the machine, the FPS down from 27Hz to 16Hz, I think maybe the problem is my hardware, the reset policy has no problem. Thanks for a lot!








At 2018-08-28 11:32:18, "Vibhor Sood" <notifications@github.com> wrote:


@qiuchenli This has been documented here:Frames didn't arrive error
If it's the PointCloud then the frame rate would remain stable ~6-7FPS even before the reset.

The pcl library depends heavily on the clock speed of the CPU. Do you get a higher frame rate before resetting the camera? If so, try unplugging and replugging the camera, and see if that affects the frame rate as well.

**Comment by qiuchenli** [comment]
dear sir:
I make a reply on github, just as below:

I use realsense in ros wrapper, to add the reset policy I use the reset ros wrapper(https://github.com/icarpis/realsense/tree/reset_dev)  in my laptop and the FPS down from 30Hz to 26Hz, but in the machine, the FPS down from 27Hz to 16Hz, I think maybe the problem is my hardware, the reset policy has no problem. Thanks for a lot!







At 2018-08-28 11:32:18, "Vibhor Sood" <notifications@github.com> wrote:


@qiuchenli This has been documented here:Frames didn't arrive error
If it's the PointCloud then the frame rate would remain stable ~6-7FPS even before the reset.

The pcl library depends heavily on the clock speed of the CPU. Do you get a higher frame rate before resetting the camera? If so, try unplugging and replugging the camera, and see if that affects the frame rate as well.

**Comment by fiorano10** [comment]
@qiuchenli ,please close the issues that have been resolved. Thanks!
