### ISSUE TITLE
strange data use realsense d435 in floor ground

### ISSUE THREAD

**Issue by qiuchenli** [realsenseai/realsense-ros#444]
Dear sir:
when I use realsense d435 in smooth floor, the pointcloud data we get is strange, not as normal as the data we get from carpet ground, so the postprocess we make cannot be applied, do you have any ideas or solutions?
Hope your reply!

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Close this issue for lack of activity. Please feel free to reopen if the issue is still relevant.
