### ISSUE TITLE
Error running RealSense D435 on Ubuntu 16.04(kernel 4.4.0-131-generic)

### ISSUE THREAD

**Issue by arya001** [realsenseai/realsense-ros#445]
I am getting an error message when running `realsense-viewer`. The realsense window does appear and I can also run the launch files.

    WARNING [139658086876928] (sensor.cpp:338) Unregistered Media formats : [ UYVY ]; Supported: [ ]

**Comment by fiorano10** [comment]
It's a warning message, does it affect your image stream in any way? Can you view the image_stream? I get the same warning, but it hasn't impacted the functionality in any way, yet.

**Comment by arya001** [comment]
@fiorano10 No, the image stream is alright. But I always get that WARNING on terminal when I run any realsense file. 

Another problem I am facing is having to hardware reset everytime I run a launchfile.

**Comment by fiorano10** [comment]
The hardware reset issue has been logged multiple times, there is no fix yet, even with the new FW, or SDK updates. I've been using the ResetDevice node to reset the RealSense before re-running a RealSense launch file, or I keep it running. [Frames didn't arrive error](https://github.com/IntelRealSense/librealsense/issues/1086)

**Comment by arya001** [comment]
@fiorano10 Alright. Thanks for the help

**Comment by lchop** [comment]
Hello,
@fiorano10, where can I find thid ResetDevice node ?
Best regards,

**Comment by fiorano10** [comment]
@lchop Here you go [reset_device](https://github.com/fiorano10/realsense/blob/devel/realsense2_camera/src/reset_device.cpp)

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]

**Comment by fiorano10** [comment]
@arya001 Please close the issue, if your problem was solved.
