### ISSUE TITLE
questions for "Added hardware reset as a w/o of FW issue"------fps is too low 

### ISSUE THREAD

**Issue by qiuchenli** [realsenseai/realsense-ros#447]
Dear sir:
@icarpis 
I use realsense d435 in real machine. When I use 
$ roslaunch realsense2_camera rs_rgbd.launch
sometimes, I got the info that "frames didn't arrived within 5 seconds", I referred to the solutions you add "reset device" and it worked well. Howerer, the fps is lower than before, I set fps=30, and it turns out that 
$ rostopic echo /camera/depth_registered/points
can only get 10 fps,which cannot applied in my application, any ideas?

Hope your reply!
Qiuchen Li

**Comment by fiorano10** [comment]
@qiuchenli The point cloud generation is generally much slower than the image frames itself, can you check what frame rate you're getting on the images instead, before and after the reset? I'm doing the same thing at 15fps, and don't have this issue.

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------


Close this issue for lack of activity. Please feel free to reopen if the issue is still relevant.
