### ISSUE TITLE
Tf problem when running multiple devices

### ISSUE THREAD

**Issue by bsaendig** [realsenseai/realsense-ros#448]
Hello,
rs_multiple_devices.launch creates different namespaces for the topics, but the tfs for the cameras are all named the same (camera_link).
I think it would be very useful if the camera manager had a parameter to set the name for the specific camera.

Thanks in advance
Bertram

**Comment by rupak-d** [comment]
Hi bsaendig,
Have a look at https://github.com/intel-ros/realsense/issues/346

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Close this issue for lack of activity. Please feel free to reopen if the issue is still relevant.
