### ISSUE TITLE
ROS Simulation using D435

### ISSUE THREAD

**Issue by rupak-d** [realsenseai/realsense-ros#449]
I am using ROS Kinetic with an Ubuntu 16.04 system. 

I plan to do obstacle avoidance using 3 Realsense D435 camera's. How can I simulate the cameras in Gazebo?

Thanks.

**Comment by SteveMacenski** [comment]
That's a pretty intense operation, I hope you're running this on a very nice computer.

You can use the depth camera gazebo plugin. Grab the xml file and edit the parameters for the FOV and parameters for your specific depth cameras

**Comment by rupak-d** [comment]
Is that one of the urdf xacro files?

**Comment by SteveMacenski** [comment]
Yessir

**Comment by SteveMacenski** [comment]
http://gazebosim.org/tutorials?tut=ros_depth_camera&cat=connect_ros

**Comment by rupak-d** [comment]
Thanks Steve!

**Comment by tik0** [comment]
@rupak-d would be awesome if you could share the correct configuration of the gazebo plugin in this issue.

**Comment by saikishor** [comment]
FYI
https://github.com/pal-robotics/realsense_gazebo_plugin
