### ISSUE TITLE
realsense2_camera building error

### ISSUE THREAD

**Issue by FYPBois** [realsenseai/realsense-ros#450]
Have followed the tutorial in order to get this working but have run into some issues. Have followed this tutorial for the SDK - https://github.com/IntelRealSense/librealsense/blob/master/doc/installation.md

Then attempted to get the realsense2_camera package working but when executing catkin_make there are errors that come up (as shown below). 

What can I do to fix this?

******************************************************************************************************
CMake Warning at realsense2_camera/CMakeLists.txt:29 (find_package):
  By not providing "Findrealsense2.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "realsense2", but CMake did not find one.

  Could not find a package configuration file provided by "realsense2" with
  any of the following names:

    realsense2Config.cmake
    realsense2-config.cmake

  Add the installation prefix of "realsense2" to CMAKE_PREFIX_PATH or set
  "realsense2_DIR" to a directory containing one of the above files.  If
  "realsense2" provides a separate development package or SDK, be sure it has
  been installed.
CMake Error at realsense2_camera/CMakeLists.txt:31 (message):

   Intel RealSense SDK 2.0 is missing, please install it from https://github.com/IntelRealSense/librealsense/releases

******************************************************************************************************

**Comment by doronhi** [comment]
Hi @FYPBois ,
Can you describe how did you try to make the realsense2_camera package working, so that I'll try to reconstruct the errors? Did you follow the installation guide at https://github.com/intel-ros/realsense ?
What OS do you use? Can you provide the list of commands you used? log?
