### ISSUE TITLE
compile with catkin_tools

### ISSUE THREAD

**Issue by GITSHOHOKU** [realsenseai/realsense-ros#456]
Hi everybody 
I tried to use catkin_tools to compile the realsense2_camera under UBUNTU 16.04 with ROS Kinetic,
And I had already install realsense SDK ,When I use catkin build realsense2_camera I got this error

`This program built for x86_64-pc-linux-gnu`
Does catkin_tools can't compile this package or I miss something before
Thanks anyway!!!

**Comment by doronhi** [comment]
can you provide means to reproduce? what commands exactly did you type? log?

**Comment by GITSHOHOKU** [comment]
Sorry  I solved this problem . I used the wrong version of realsense2
