### ISSUE TITLE
d435 urdf displays mesh incorrectly

### ISSUE THREAD

**Issue by rongoldman-tri** [realsenseai/realsense-ros#459]
Hi. We just added the D435 urdf to our robot model and when it is displayed the camera orientation is off by 90 degrees.

![realsense-current](https://user-images.githubusercontent.com/25939527/45136676-20302800-b15a-11e8-9a0f-fefdbbabd7f6.png)

This is showing the camera_link frame and also the camera_right_ir_optical_frame.

By changing line 49 so the roll is `${M_PI}` instead of `${M_PI/2}`  to:

      `<origin xyz="${d435_cam_mount_from_center_offset} 0.0 ${d435_cam_height/2}" rpy="${M_PI} 0 ${M_PI/2}"/>`

it displays properly:

![realsense-corrected](https://user-images.githubusercontent.com/25939527/45136718-4eae0300-b15a-11e8-805f-e1a6fdd036d1.png)

Note the origin tag doesn't seem to affect displaying a box, only the mesh has the problem. Whether roll is pi or pi/2 the display for the box is:

![realsense-box-uncorrected](https://user-images.githubusercontent.com/25939527/45136815-b95f3e80-b15a-11e8-8f0c-5320c295f097.png)

thanks,

-- Ron --

**Comment by doronhi** [comment]
Hi @rongoldman-tri,
I can't recreate the situation you presented. I run the following command:
roslaunch realsense2_camera view_d435_model.launch

I then Show camera_right_ir_optical_frame and camera_link, set Market Scale to 0.1 and get the following image:
![image](https://user-images.githubusercontent.com/40540281/45401575-ea0f0e80-b659-11e8-8a59-92b9b9b226d4.png)

Can you tell what are we doing differently?

**Comment by rongoldman-tri** [comment]
Thanks for looking into this. The problem was on our side: we had converted the d435.dae mesh to use STL format. The converted STL file introduced the rotation I reported as a bug. Redoing the conversion with MeshLab created a good STL file that preserved the original mesh orientation. So everything is fine & I am closing the issue. Sorry to have bothered you.

-- Ron --

**Comment by doronhi** [comment]
No problem. Glad it worked out for you.
