### ISSUE TITLE
Issue launching the camera

### ISSUE THREAD

**Issue by FYPBois** [realsenseai/realsense-ros#464]
Hi,

We are having an issue running the realsense camera through ROS. Having gotten catkin_make to run without errors. However, getting an error (shown below) when trying to launch with the following command. Please let me know if anyone has any ideas to get this issue fixed.

roslaunch realsense2_camera rs_camera.launch

Error:

[ INFO] [1536546180.227283302]: Initializing nodelet with 4 worker threads.
[ERROR] [1536546180.329636650]: Failed to load nodelet [/camera/realsense2_camera] of type [realsense2_camera/RealSenseNodeFactory] even after refreshing the cache: Could not find library corresponding to plugin realsense2_camera/RealSenseNodeFactory. Make sure the plugin description XML file has the correct name of the library and that the library actually exists.
[ERROR] [1536546180.329744181]: The error before refreshing the cache was: Could not find library corresponding to plugin realsense2_camera/RealSenseNodeFactory. Make sure the plugin description XML file has the correct name of the library and that the library actually exists.
[FATAL] [1536546180.330428662]: Failed to load nodelet '/camera/realsense2_camera` of type `realsense2_camera/RealSenseNodeFactory` to manager `realsense2_camera_manager'
[camera/realsense2_camera-2] process has died [pid 9247, exit code 255, cmd /opt/ros/kinetic/lib/nodelet/nodelet load realsense2_camera/RealSenseNodeFactory realsense2_camera_manager __name:=realsense2_camera __log:=/home/fypbois/.ros/log/65e9f26c-b49e-11e8-bb44-e442a68f1f6f/camera-realsense2_camera-2.log].

**Comment by SteveMacenski** [comment]
Did you source your workspace?
Whats the ouput of rospack find realsense2_camera

**Comment by RatheeshRK** [comment]
Hello
I need your help in ROS to launch D435, I tried couple of github repository. 

The 'realsense-viewer' gives me good results with out ROS, with D435.

The error details are shared below, looking forward for kind support.

rocess[camera/realsense2_camera-3]: started with pid [12558]
[ INFO] [1537135194.214425073]: Initializing nodelet with 8 worker threads.
[ERROR] [1537135194.248706900]: Failed to load nodelet [/camera/realsense2_camera] of type [realsense2_camera/RealSenseNodeFactory] even after refreshing the cache: Could not find library corresponding to plugin realsense2_camera/RealSenseNodeFactory. Make sure the plugin description XML file has the correct name of the library and that the library actually exists.
[ERROR] [1537135194.248762292]: The error before refreshing the cache was: Could not find library corresponding to plugin realsense2_camera/RealSenseNodeFactory. Make sure the plugin description XML file has the correct name of the library and that the library actually exists.
[FATAL] [1537135194.248932871]: Failed to load nodelet '/camera/realsense2_camera` of type `realsense2_camera/RealSenseNodeFactory` to manager `realsense2_camera_manager'
[camera/realsense2_camera-3] process has died [pid 12558, exit code 255, cmd /opt/ros/kinetic/lib/nodelet/nodelet load realsense2_camera/RealSenseNodeFactory realsense2_camera_manager __name:=realsense2_camera __log:=/home/rrk/.ros/log/d734889e-b9fb-11e8-b5e5-5c969d92e04f/camera-realsense2_camera-3.log].
log file: /home

**Comment by FYPBois** [comment]
It is there when i run rospack find.

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Close this issue for lack of activity. Please feel free to reopen if the issue is still relevant.

**Comment by nikkolasedi** [comment]
Do you have the solution?

**Comment by hwb0314** [comment]
I have the exact same problem. Do you have the solution?
