### ISSUE TITLE
Create releases with static librealsense versions 

### ISSUE THREAD

**Issue by SteveMacenski** [realsenseai/realsense-ros#467]
It's been several months with several new librealsense versions brought out and its never clear what will work with what. Can we get back to releasing a static release that works with a given librealsense version?

https://github.com/intel-ros/realsense/releases

**Comment by SteveMacenski** [comment]
This is super important for those using these cameras in a production environment. If the master branch stops working with a version or a bug is introduced, production resources can be brought down too. There hasn't been a release since March with matching supported librealsense SDK and firmware versions.

We especially need this to evaluate any updates or changes due to this as it causes far too many headaches about small things going on in librealsense we have no control over

**Comment by doronhi** [comment]
I totally agree and aware of the issue. Working on it and plan to freeze a version in the next couple of weeks.

**Comment by SteveMacenski** [comment]
Awesome, thanks for all your hard work here! 
I'd ideally love to see a static release for each librealsense 2.X.0 release
