### ISSUE TITLE
cannot run 'roslaunch realsense2_camera rs_rgbd.launch' along with roslaunch realsense2_camera rs_camera.launch

### ISSUE THREAD

**Issue by houlei516** [realsenseai/realsense-ros#468]
Ubuntu 16.04, Kernel 4.15. Build librealsense2 and realsense2_cemera from source. Cannot run 'roslaunch realsense2_camera rs_camera.launch' along with roslaunch realsense2_camera rs_camera.launch.

///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
[FATAL] [1536970907.584438609]: Failed to load nodelet '/camera/realsense2_camera` of type `realsense2_camera/RealSenseNodeFactory` to manager `realsense2_camera_manager'
[ INFO] [1536970907.599534717]: Initializing nodelet with 4 worker threads.
[ WARN] [1536970907.649107773]: Shutdown request received.
[ WARN] [1536970907.649131413]: Reason given for shutdown: [new node registered with same name]
[camera/realsense2_camera_manager-1] process has finished cleanly
log file: /home/helen/.ros/log/51879152-b87d-11e8-93f7-a44cc8669e6b/camera-realsense2_camera_manager-1*.log
[camera/realsense2_camera-2] process has died [pid 7974, exit code 255, cmd /opt/ros/kinetic/lib/nodelet/nodelet load realsense2_camera/RealSenseNodeFactory realsense2_camera_manager __name:=realsense2_camera __log:=/home/helen/.ros/log/51879152-b87d-11e8-93f7-a44cc8669e6b/camera-realsense2_camera-2.log].
log file: /home/helen/.ros/log/51879152-b87d-11e8-93f7-a44cc8669e6b/camera-realsense2_camera-2*.log

**Comment by SteveMacenski** [comment]
>  Reason given for shutdown: [new node registered with same name]

This is standard and not Intel or realsense specific. Please look at examples of mulitple camera launch.

You just need to namespace the nodes. Cant have multiple instances of the same program with the same name. http://wiki.ros.org/roslaunch/XML/group

**Comment by SteveMacenski** [comment]
If you've found your issue, can you close the ticket?

**Comment by houlei516** [comment]
Thank you again for your erudite reply.

**Comment by SteveMacenski** [comment]
No problem. @houlei516 can you close the ticket to get off folk's radar if resolved?

**Comment by Manoj-Bhat97** [comment]
hello @houlei516 I have faced the same problem and I am not sure I understand what 'namespace the nodes mean' can you please enlighten me on how you solved this issue? 
I am running Ubuntu 16.04 and realsense 435 depth camera. ROS Kinetic.
Thank you in advance
