### ISSUE TITLE
D400 series: a method to pause streaming

### ISSUE THREAD

**Issue by AndyZe** [realsenseai/realsense-ros#477]
Similar to 'force_power' that the previous generation had.

This is important to me so I can switch between multiple cameras when my bandwidth is limited. Basically, I would like to put all cameras except one or two in sleep mode.

**Comment by AndyZe** [comment]
My PR solves the network bandwidth issue by pausing ROS publication. It would be better to pause the RealSense camera at the hardware level, though, to save USB3 bandwidth and power, too. I didn't see an easy way to do that.

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Close this issue for lack of activity. Please feel free to reopen if the issue is still relevant.
