### ISSUE TITLE
Unnecessary stream configuration warning when running over USB2

### ISSUE THREAD

**Issue by neomanic** [realsenseai/realsense-ros#478]
I am running a pair of D435s over USB2 (long story I can elaborate on), and even though they are working fine, streaming colour and depth at 640x480x6fps, they give the warning 
`[ WARN] [1537495167.662632674]: Given stream configuration is not supported by the device!  Stream: Infrared, Stream Index: 2, Format: Y8, Width: 640, Height: 480, FPS: 6` 
at node. (extended snippet of log below, on current firmware 05.10.03.00)

I suspect this is a holdover from old firmware before USB2 support was extended. Even though it doesn't cause any issues, I'm noting it here for reference.

```
[ INFO] [1537495167.658533881]: setupStreams...
 21/09 11:59:27,659 WARNING [139673202452352] (sensor.cpp:338) Unregistered Media formats : [ UYVY ]; Supported: [ ]
[ INFO] [1537495167.661246117]: depth stream is enabled - width: 640, height: 480, fps: 6
[ INFO] [1537495167.662278708]: infra1 stream is enabled - width: 640, height: 480, fps: 6
[ WARN] [1537495167.662632674]: Given stream configuration is not supported by the device!  Stream: Infrared, Stream Index: 2, Format: Y8, Width: 640, Height: 480, FPS: 6
[ INFO] [1537495167.664814631]: color stream is enabled - width: 640, height: 480, fps: 6
[ INFO] [1537495167.680851035]: publishStaticTransforms...
[ INFO] [1537495167.681952069]: RealSense Node Is Up!
```

**Comment by BW25** [comment]
I believe this actually is an error.
As stated in this issue by @dorodnic:
https://github.com/IntelRealSense/librealsense/issues/3218
"When connected via USB3, the camera can provide gray-scale stereo pair (including near-infrared wavelength that will see the active projector pattern) and depth and RGB data."

There should be two topics publishing these stereo gray-scale images; /camera/infra1 and /camera/infra2.

I am using a single D435i, and the same error message appears for me, but no images are appearing on these topics as I believe they should.
Unfortunately, I have not found a solution for this issue myself, but will let you know if I do.

**Comment by neomanic** [comment]
Those topics are not being published on the D435i, see this issue I raised a few weeks ago: https://github.com/IntelRealSense/librealsense/issues/3209 

AFAICT it's a firmware issue, and there's not been any indication as to whether support for the complete functionality of the D435i over USB2 will be added. We've reverted to using plain D435 cameras, which are working great over USB2 (even if we do get the same warnings from this issue at startup).

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Hi @neomanic,

The functionality of D435 as a USB2 device is limited. Depth and IR1 can stream with your configuration. Below warning is because IR2 stream is enabled, but, not supported.
