### ISSUE TITLE
List of dynamic_reconfigure parameters is brittle

### ISSUE THREAD

**Issue by AndyZe** [realsenseai/realsense-ros#488]
When I tried to add a new dynamic_reconfigure parameter for PR487, I eventually figured out that the "level" of the parameter in _base_d400_params.py_ needs to match the order of the enum in base_realsense_node.h. This seems confusing and brittle.

For example, this dynamic parameter won't work as expected. Its level is 10.
`  gen.add(str(prefix) + "my_parameter",                          str_t,    10,  "my_parameter",            "")`

If the enum is declared in this order:
`enum base_depth_param{`
`   base_depth_gain = 1,`
`   base_my_parameter,   // <-- Note, it's declared second, not 10th`
`   base_depth_enable_auto_exposure,`
`   ...`

**Comment by dorodnic** [comment]
Thanks @AndyZe 
Good point, we will try to address it.

**Comment by doronhi** [comment]
@AndyZe , did you check out the latest release?

**Comment by AndyZe** [comment]
Was this fixed by switching to ddynamic_reconfigure? Anyway - nice!
