### ISSUE TITLE
Depth height and width zero if enable pointcloud set to true

### ISSUE THREAD

**Issue by atyshka** [realsenseai/realsense-ros#491]
I'm running the latest version of this ros package with librealsense 1.16 and I'm running into issues when trying to use the pointcloud. If I launch rs_rgbd normally, I get a correct depth stream I can visualize in RVIZ. However, if I use the same launch file with the `enable_pointcloud` arg set to true, suddenly the width, height, and step of the depth image are zero. The actual image array is fully published, but without a height, width, and step this data is useless. Also, rs_aligned works fine without the pointcloud enabled, but with it enabled I get ` An error has occurred during frame callback: null pointer passed for argument "frame_ref"` when echoing the topic. Is this a known issue? A few versions back I could use both pointcloud and depth just fine.

Output of `rostopic echo /camera/depth/image_raw --noarr` with cloud disabled:
`header: 
  seq: 5792
  stamp: 
    secs: 1539267647
    nsecs: 369592057
  frame_id: "camera_depth_optical_frame"
height: 480
width: 640
encoding: "16UC1"
is_bigendian: 0
step: 1280
data: "<array type: uint8, length: 614400>"`

and with cloud enabled:

`header: 
  seq: 95
  stamp: 
    secs: 1539268016
    nsecs: 367752813
  frame_id: "camera_depth_optical_frame"
height: 0
width: 0
encoding: "16UC1"
is_bigendian: 0
step: 0
data: "<array type: uint8, length: 614400>"`

**Comment by arb93** [comment]
Same here. Any suggestions?

**Comment by atyshka** [comment]
Related to #489

**Comment by atyshka** [comment]
@doronhi Update: As of your latest commit, height and width work fine on the depth image aligned topics, but with enable_pointcloud set to true  `/camera/depth/image_raw` still has height and width zero.

**Comment by doronhi** [comment]
Thanks guys. Thanks to your notes I already made a unitest that fails for this case and hope to fix it early next week for the upcoming release.

**Comment by doronhi** [comment]
Last commit fixes this issue.

**Comment by leiw324** [comment]
I am getting this issue too, how to fix ?

**Comment by doronhi** [comment]
What versions do you use? librealsense and realsense2_camera?
