### ISSUE TITLE
Incorrect TF frame `camera_link` when using `view_d435_model.launch`

### ISSUE THREAD

**Issue by peci1** [realsenseai/realsense-ros#497]
When you are viewing the model using `view_d435_model.launch`, this is the TF you get:

```
rosrun tf tf_echo camera_link camera_depth_frame
At time 1539958677.743
- Translation: [0.015, 0.018, 0.013]
- Rotation: in Quaternion [0.000, 0.000, 0.000, 1.000]
            in RPY (radian) [0.000, -0.000, 0.000]
            in RPY (degree) [0.000, -0.000, 0.000]
```

Whereas with the live camera, you get: 

```
rosrun tf tf_echo camera_link camera_depth_frame
At time 0.000
- Translation: [0.000, 0.000, 0.000]
- Rotation: in Quaternion [0.000, 0.000, 0.000, 1.000]
            in RPY (radian) [0.000, -0.000, 0.000]
            in RPY (degree) [0.000, -0.000, 0.000]
```

Indeed, in the xacro file used in viewing, there is a [non-zero transform between camera_link and camera_depth_frame](https://github.com/intel-ros/realsense/blob/a63471f6b3885047878d623308ca4c92ac368a85/realsense2_camera/urdf/_d435.urdf.xacro#L74), whereas [in the driver source, camera_link and camera_depth_frame coincide](https://github.com/intel-ros/realsense/blob/a63471f6b3885047878d623308ca4c92ac368a85/realsense2_camera/src/base_realsense_node.cpp#L1104).

I assume the XACRO file should be fixed.

**Comment by atyshka** [comment]
@doronhi Here is a detailed video of the issue. I started the model which had the correct transforms but then everything is offset when the driver is started.
![peek 2018-11-13 10-36](https://user-images.githubusercontent.com/19317207/48425147-33e7a400-e732-11e8-9dc7-6ed4073c7eaa.gif)

When the driver is started the frames no longer line up with the geometry.
@peci1 recommends changing the xacro, but I like the origin where it is. The mounting point is a lot more logical than the 0 point corner of the model. I'd propose either changing the transforms in the driver to match the xacro or adding a launch file param to disable tf publishing if static transforms are already being published by a robot state publisher. I'd opt for the second option, many other sensors use this parameter and it won't change behavior unless used.

**Comment by atyshka** [comment]
@doronhi Any suggestions on how you'd like to handle this issue?
