### ISSUE TITLE
Add laser_power to rqt_reconfigure

### ISSUE THREAD

**Issue by afdaniele** [realsenseai/realsense-ros#505]
Is it possible to add a slider for the laser power to the node configuration so that it is possible to change it via `rqt_reconfigure`?

Thank you.

**Comment by doronhi** [comment]
What camera do you use?
Last time I checked, There is an option:
![image](https://user-images.githubusercontent.com/40540281/47960296-6cd09c00-e001-11e8-9346-5fe3498413f5.png)

**Comment by afdaniele** [comment]
I'm sorry, I think I was working with an older version of the ROS wrapper.
Thank you.
Closing.
