### ISSUE TITLE
Failed to load nodelet [/camera/realsense2_camera] of type [realsense2_camera/RealSenseNodeFactory]

### ISSUE THREAD

**Issue by Kaesarlch** [realsenseai/realsense-ros#506]
----------------------------------------------------------------------------------------------------

| Required Info                         |                                                                |
|---------------------------------|------------------------------------------- |
| Camera Model                       | D435 | 
| Firmware Version                   | 5.10.6 |
| librealsense & realsense | 2.16.1 & 2.1.0 |
| Operating System & Version |  Ubuntu 18.04.1 LTS  | 
| Kernel Version (Linux Only)    |  4.15.0.38-generic                                        | 
| Platform                                 | Intel NUC |
| Language                            |  Python 2.7 / C++                         | 
| ROS                                     | Melodic   |
| Segment			|  Robot                          | 

### Issue Description

Hello everyone,
I am working on a 2 wheeled robot and we want to use the D435 for security / mapping purpose.
Right now I am trying to get the libraries to work with the ROS wrapper.

I have been checking many post in here and other forums but could not find a solution to my problem:
After `catkin_make_isolted --install` I can start a few .launch files like `view_d435_model.launch` but all the `rs_*.launch` will return the same error like for example with `roslaunch realsense2_camera rs_camera.launch`:

... logging to /home/superrobot/.ros/log/901850f6-dd6b-11e8-b627-d4258b378539/roslaunch-superrobot-NUC7i5DNKE-6249.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://superrobot-NUC7i5DNKE:35853/

SUMMARY
========

PARAMETERS
 * /camera/realsense2_camera/accel_fps: 1000
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: False
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/color_fps: 30
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: 480
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: 640
 * /camera/realsense2_camera/depth_fps: 30
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: 480
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: 640
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye: True
 * /camera/realsense2_camera/enable_imu: True
 * /camera/realsense2_camera/enable_infra1: True
 * /camera/realsense2_camera/enable_infra2: True
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_sync: False
 * /camera/realsense2_camera/filters: 
 * /camera/realsense2_camera/fisheye_fps: 30
 * /camera/realsense2_camera/fisheye_height: 480
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: 640
 * /camera/realsense2_camera/gyro_fps: 1000
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/infra1_fps: 30
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_height: 480
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra1_width: 640
 * /camera/realsense2_camera/infra2_fps: 30
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_height: 480
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra2_width: 640
 * /camera/realsense2_camera/json_file_path: 
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/rosbag_filename: 
 * /camera/realsense2_camera/serial_no: 
 * /rosdistro: melodic
 * /rosversion: 1.14.3

NODES
  /camera/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)

auto-starting new master
process[master]: started with pid [6261]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 901850f6-dd6b-11e8-b627-d4258b378539
process[rosout-1]: started with pid [6272]
started core service [/rosout]
process[camera/realsense2_camera_manager-2]: started with pid [6278]
process[camera/realsense2_camera-3]: started with pid [6280]
[ INFO] [1541031469.092084646]: Initializing nodelet with 4 worker threads.
[ERROR] [1541031469.111536836]: Failed to load nodelet [/camera/realsense2_camera] of type [realsense2_camera/RealSenseNodeFactory] even after refreshing the cache: Could not find library corresponding to plugin realsense2_camera/RealSenseNodeFactory. Make sure the plugin description XML file has the correct name of the library and that the library actually exists.
[ERROR] [1541031469.111568268]: The error before refreshing the cache was: Could not find library corresponding to plugin realsense2_camera/RealSenseNodeFactory. Make sure the plugin description XML file has the correct name of the library and that the library actually exists.
[FATAL] [1541031469.111672617]: Failed to load nodelet '/camera/realsense2_camera` of type `realsense2_camera/RealSenseNodeFactory` to manager `realsense2_camera_manager'
[camera/realsense2_camera-3] process has died [pid 6280, exit code 255, cmd /opt/ros/melodic/lib/nodelet/nodelet load realsense2_camera/RealSenseNodeFactory realsense2_camera_manager __name:=realsense2_camera __log:=/home/superrobot/.ros/log/901850f6-dd6b-11e8-b627-d4258b378539/camera-realsense2_camera-3.log].
log file: /home/superrobot/.ros/log/901850f6-dd6b-11e8-b627-d4258b378539/camera-realsense2_camera-3*.log

What I have checked:
-updated D435 firmware to 5.10.6
-under `lsusb` I can see my D435, with a speed 5000M which should confirm USB3.0
-with `realsense-viewer` and `pyrealsense2` I can correctly stream from the camera
-I trying upgrading my linux kernel from 4.15 to 4.16 and 4.19 with no good effect.

Any help would be appreciated!

EDIT: I realized that with `catkin_make_isolated` it create a new `devel_isolated` folder and I never sourced the `setup.bash` inside.

now it gives me a different output:

... logging to /home/superrobot/.ros/log/3fe863d6-ddbc-11e8-8c95-d4258b378539/roslaunch-superrobot-NUC7i5DNKE-6548.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://superrobot-NUC7i5DNKE:34857/

SUMMARY
========

PARAMETERS
 * /camera/realsense2_camera/accel_fps: 1000
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: True
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/color_fps: 30
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: 480
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: 640
 * /camera/realsense2_camera/depth_fps: 30
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: 480
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: 640
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye: True
 * /camera/realsense2_camera/enable_imu: True
 * /camera/realsense2_camera/enable_infra1: True
 * /camera/realsense2_camera/enable_infra2: True
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_sync: True
 * /camera/realsense2_camera/filters: 
 * /camera/realsense2_camera/fisheye_fps: 30
 * /camera/realsense2_camera/fisheye_height: 480
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: 640
 * /camera/realsense2_camera/gyro_fps: 1000
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/infra1_fps: 30
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_height: 480
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra1_width: 640
 * /camera/realsense2_camera/infra2_fps: 30
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_height: 480
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra2_width: 640
 * /camera/realsense2_camera/json_file_path: 
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/rosbag_filename: 
 * /camera/realsense2_camera/serial_no: 
 * /rosdistro: melodic
 * /rosversion: 1.14.3

NODES
  /camera/
    color_rectify_color (nodelet/nodelet)
    points_xyzrgb_hw_registered (nodelet/nodelet)
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)

auto-starting new master
process[master]: started with pid [6559]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 3fe863d6-ddbc-11e8-8c95-d4258b378539
process[rosout-1]: started with pid [6570]
started core service [/rosout]
process[camera/realsense2_camera_manager-2]: started with pid [6577]
process[camera/realsense2_camera-3]: started with pid [6578]
process[camera/color_rectify_color-4]: started with pid [6579]
process[camera/points_xyzrgb_hw_registered-5]: started with pid [6585]
[ INFO] [1541066123.803391478]: Initializing nodelet with 4 worker threads.
[ INFO] [1541066123.935166058]: RealSense ROS v2.1.0
[ INFO] [1541066123.935200549]: Running with LibRealSense v2.16.1
[ INFO] [1541066124.106792542]: getParameters...
[ INFO] [1541066124.128168552]: setupDevice...
[ INFO] [1541066124.128194925]: JSON file is not provided
[ INFO] [1541066124.128213460]: ROS Node Namespace: camera
[ INFO] [1541066124.128238418]: Device Name: Intel RealSense D435
[ INFO] [1541066124.128252668]: Device Serial No: 817512070113
[ INFO] [1541066124.128269292]: Device FW version: 05.10.06.00
[ INFO] [1541066124.128285211]: Device Product ID: 0x0B07
[ INFO] [1541066124.128292649]: Enable PointCloud: Off
[ INFO] [1541066124.128301763]: Align Depth: On
[ INFO] [1541066124.128312347]: Sync Mode: On
[ INFO] [1541066124.128812898]: Device Sensors: 
[ INFO] [1541066124.129058412]: Stereo Module was found.
[ INFO] [1541066124.129108751]: RGB Camera was found.
[ INFO] [1541066124.129391667]: (Fisheye, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1541066124.129410164]: (Gyro, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1541066124.129427816]: (Accel, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1541066124.129482277]: setupPublishers...
[ INFO] [1541066124.131214100]: Expected frequency for depth = 30.00000
[ INFO] [1541066124.146673430]: Expected frequency for infra1 = 30.00000
[ INFO] [1541066124.158343919]: Expected frequency for aligned_depth_to_infra1 = 30.00000
[ INFO] [1541066124.172068810]: Expected frequency for infra2 = 30.00000
[ INFO] [1541066124.184808473]: Expected frequency for aligned_depth_to_infra2 = 30.00000
[ INFO] [1541066124.198727591]: Expected frequency for color = 30.00000
[ INFO] [1541066124.212658798]: Expected frequency for aligned_depth_to_color = 30.00000
[ INFO] [1541066124.225199898]: setupStreams...
 01/11 18:55:24,227 WARNING [140440340629376] (sensor.cpp:338) Unregistered Media formats : [ UYVY ]; Supported: [ ]
[ INFO] [1541066124.231721978]: depth stream is enabled - width: 640, height: 480, fps: 30
[ INFO] [1541066124.232103870]: infra1 stream is enabled - width: 640, height: 480, fps: 30
[ INFO] [1541066124.232309200]: infra2 stream is enabled - width: 640, height: 480, fps: 30
[ INFO] [1541066124.238074117]: color stream is enabled - width: 640, height: 480, fps: 30
 01/11 18:55:24,252 ERROR [140439285380864] (backend-v4l2.cpp:1002) Video frame arrived in idle mode.
 01/11 18:55:24,253 ERROR [140439285380864] (backend-v4l2.cpp:1002) Video frame arrived in idle mode.
 01/11 18:55:24,253 ERROR [140439285380864] (backend-v4l2.cpp:1002) Video frame arrived in idle mode.
 01/11 18:55:24,253 ERROR [140439285380864] (backend-v4l2.cpp:1002) Video frame arrived in idle mode.
[ INFO] [1541066124.265012376]: num_filters: 0
[ INFO] [1541066124.265079853]: publishStaticTransforms...
[ INFO] [1541066124.266206863]: RealSense Node Is Up!
 01/11 18:55:29,291 WARNING [140440340629376] (types.cpp:57) set_pu(id=4) failed! Last Error: Input/output error
[ WARN] [1541066129.292411971]: Reconfigure callback failed with exception set_pu(id=4) failed! Last Error: Input/output error:

from there nothing happens.

**Comment by Kaesarlch** [comment]
nevermind! it is actually working.

I had no idea I needed to started rviz by myself!

So in the end what I did is build LibRealSense from source and build realsense2_camera in a catkin workspace with a simple `catkin_make`

**Comment by Horizonzhou** [comment]
I have met this problem too, could you please share your experience about this problem?

**Comment by qinhongtju** [comment]
I want to know if your problem has been solved. I also face the same problem, can I ask you something？

**Comment by sazzath** [comment]
I have the same problem too ... Help me please ....

**Comment by sazzath** [comment]
> I want to know if your problem has been solved. I also face the same problem, can I ask you something？

![image](https://user-images.githubusercontent.com/72601348/121790522-84705800-cbe0-11eb-83cc-dc5b2899e713.png)

**Comment by HappySamuel** [comment]
Hi @Kaesarlch , @sazzath 

I also faced same issue, is this issue cannot be solved even with installing the latest ros-noetic-realsense2-camera ? Only catkin_make realsense2_camera from source can get it working?

Best,
Samuel

**Comment by kinzess** [comment]
I catkin_make from source, but not working too.

> Hi @Kaesarlch , @sazzath
> 
> I also faced same issue, is this issue cannot be solved even with installing the latest ros-noetic-realsense2-camera ? Only catkin_make realsense2_camera from source can get it working?
> 
> Best, Samuel
