### ISSUE TITLE
Pointcloud unexpected interpolation along view direction?

### ISSUE THREAD

**Issue by taochenshh** [realsenseai/realsense-ros#507]
I am using ubuntu 16.04, realsense d435 and launched the` rs_rgbd.launch` file.  THe pointcloud seems to be interpolating in the viewing direction. And because of this, there seems to be elongated tails of points where there should be empty space. I have done the calibration.

Example:
RGB Image:
![selection_124](https://user-images.githubusercontent.com/15166943/47940568-663b0b00-dec1-11e8-8e89-a39cf94fcfa1.png)

The point cloud looks like these:
**Front view**
![selection_123](https://user-images.githubusercontent.com/15166943/47940535-4a376980-dec1-11e8-9584-986f4363772c.png)
**Side view**
![selection_125](https://user-images.githubusercontent.com/15166943/47940730-042ed580-dec2-11e8-943c-eff9678c5d9e.png)
The red circle shows the issue. How to correct it? Thanks.

**Comment by MrYelameli** [comment]
How you did the calibration? what is the solution? Would you kindly let me know? I am also facing the similar problem.

**Comment by mahdipo** [comment]
step 1: due to sensor size for D435  840X480 is the standard resolution and generates less noise in this mode.
step 2: change preset in realsense viewer to HighAccuracy or HighDensity instead of default or custom, its give you much better result. also you can make this changes in your code too.
