### ISSUE TITLE
[Feature request D435] Restamp frames using hw measurements from an external board

### ISSUE THREAD

**Issue by m0oz** [realsenseai/realsense-ros#516]
Currently multiple cameras can be synced to expose simultaneously as described in this [whitepaper](https://realsense.intel.com/wp-content/uploads/sites/63/Multiple_Camera_WhitePaper_rev1.1.pdfl)
Timestamping is performed with the frame metadata by the camera which was set as master device.
This is sufficient for most time-critical applications, but it will not work for any setup where many sensors such as IMU, and/or multiple cameras have to be time synchronized. While all realsense cameras will have synchronized timestamps, the reference clock will still be the one on the master realsense's ASIC and there is no way to get IMU or other measurements with stamps in this time reference.

My suggestion would be to add a class that allows to subscribe to a topic that provides timestamps that are sent by an external board (e.g. a pixhawk or arduino).
This could work two ways. Either the board captures output pulses of the master camera or it is triggering the realsenses and sending the time of the trigger interrupts.

Let me know about your thoughts.
We have a fork that is doing just this and have been testing it for some time to use the realsenses IR frames for VIO.
If this seems like a valid feature I would go ahead and create a PR

**Comment by doronhi** [comment]
Hi,
Thanks for your suggestion. It sounds reasonable and I appreciate it. We need some time to consider and will let you know as soon as I can.
Thanks again.

**Comment by Changliu52** [comment]
I have vio setup with pixhawk hardware sync with a fisheye camera (no software sync). Currently just couldn’t use realsense simply because it is using a completely different time reference. Please share the code for triggering the realsense externally.

Thank you in advance!

Chang

**Comment by m0oz** [comment]
@doronhi Just let me know about your thoughts.
@Changliu52  I opened #520 so that you see what we did so far. I don't know if it is mergeable as is but if it sounds like a good feature I am happy to adapt it

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

There is a PR on the proposed changes and also was validated by someone outside IDC group.
Now waiting for IDC to make decision on it.

**Comment by RealSenseSupport** [comment]
@m0oz doronhi has provided some comments below for this feature request. Sorry that we won't consider this feature at this moment. Can we close it accordingly? Thanks!

https://github.com/IntelRealSense/realsense-ros/pull/520#issuecomment-511661465
https://github.com/IntelRealSense/realsense-ros/pull/520#issuecomment-511689004

**Comment by RealSenseSupport** [comment]
@m0oz Any other questions about this? Can we close it? Looking forward to your reply. Thanks!

**Comment by RealSenseSupport** [comment]
@m0oz Sorry that we didn't get your reply for weeks. Will close it at this point. Thanks!
