### ISSUE TITLE
Support for D435i with IMU

### ISSUE THREAD

**Issue by SteveMacenski** [realsenseai/realsense-ros#518]
Is that in the plan to support it here? It would be super useful to get the IMU data out

**Comment by atyshka** [comment]
Should be easy since there’s already support for imu in older models

**Comment by mfehr** [comment]
We're also interested in getting the D435i to work with this ROS node. I slightly adapted the ROS node yesterday to get it to accept the new sensor and publish all the other topics like images and depth, but even though the IMU logic is there (as @atyshka pointed out) and the motion module is recognized I cannot get it to actually publish any IMU data. If anyone is working on this or has some pointers how to configure the node we'd appreciate it. Thanks!

Update: [Here](https://github.com/intel-ros/realsense/compare/development...ethz-asl:devel/d435i) is the diff.

**Comment by doronhi** [comment]
I updated the development branch with a version that support the D435i. Waiting for some feedbacks and stability before releasing it as the next version.
I also added a white paper in the wiki section describing a use case : https://github.com/intel-ros/realsense/wiki/SLAM-with-D435i

**Comment by mfehr** [comment]
@doronhi thanks a lot for the quick response and fix/update, works like a charm!
