### ISSUE TITLE
What's the difference between /camera/color/image_raw and /camera/color/image_rect_color?

### ISSUE THREAD

**Issue by mshenyu** [realsenseai/realsense-ros#526]
Hello,
I've wrote a node that subscribes both /camera/color/image_raw and /camera/color/image_rect_color topics, and transfer them into cv::Mat images.

And then I do a pixel wise difference of these 2 cv::Mat. I found that their difference is a zero matrix, which means they are exactly the same thing in terms of pixel values:

```
    cv::Mat color = color_ptr->image; 
    cv::Mat depth = depth_ptr->image;
    cv::Mat colorRect = colorRect_ptr->image;    // the difference between image_raw and image_rect_color
    cv::Mat absolute_difference;
    cv::absdiff(color, colorRect, absolute_difference);
    double s = cv::sum( absolute_difference )[0];
    cout << s << endl;
```
 This prints '0'.

So I am curious what's the difference of these two topics?
Thanks!

**Comment by doronhi** [comment]
Where is the topic named /camera/color/image_rect_color coming from?
It could be, indeed, a copy created by rgb_processing node.

**Comment by mshenyu** [comment]
This topic is generated after I run 
```
roslaunch realsense2_camera rs_rgbd.launch
```
Yeah, I am just curious why there are two same topics published.

**Comment by Algabri** [comment]
you can see [here](http://library.isr.ist.utl.pt/docs/roswiki/openni_launch.html#Published_Topics) and [here](http://library.isr.ist.utl.pt/docs/roswiki/image_proc.html)
