### ISSUE TITLE
No data from topic /camera/infra2/image_rect_raw

### ISSUE THREAD

**Issue by adipokala** [realsenseai/realsense-ros#527]
I get the following message when I run rs_camera.launch:

> [ WARN] [1543919568.519673094]: Given stream configuration is not supported by the device!  Stream: Infrared, Stream Index: 2, Format: Y8, Width: 640, Height: 480, FPS: 30

I also dont see a message that "infra2 stream is enabled".
Can anyone suggest me on how to solve this issue.

Thank You.

**Comment by doronhi** [comment]
Sorry for the long delay. 
Could you provide more details? camera, firmware? versions? launch file? etc?
