### ISSUE TITLE
multi time run intel-ros/realsense, uvcvideo: Non-zero status (-71) happens

### ISSUE THREAD

**Issue by FENGZHANG123** [realsenseai/realsense-ros#528]
Required Info |  
-- | --
Camera Model | { D415/ D435}
Firmware Version | (5.10.6)
Operating System & Version | { Linux (Ubuntu 16)}
Kernel Version (Linux Only) | (4.15.0-42-generic)
Platform | PC
SDK Version | { 2.16.3 }
Language | {C++ }
Segment | {Robot}
intel-ros/realsense | {2.11.1}

Issue Description

Hi, when I run realsense2_camera first time, everything is fine.But when I shutdown the program with 'Ctrl C' and restart it, error happens:
PARAMETERS

    /downwire_camera/realsense2_camera/accel_fps: 1000
    /downwire_camera/realsense2_camera/accel_optical_frame_id: downwire_camera_a...
    /downwire_camera/realsense2_camera/align_depth: False
    /downwire_camera/realsense2_camera/aligned_depth_to_color_frame_id: downwire_camera_a...
    /downwire_camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: downwire_camera_a...
    /downwire_camera/realsense2_camera/aligned_depth_to_infra1_frame_id: downwire_camera_a...
    /downwire_camera/realsense2_camera/aligned_depth_to_infra2_frame_id: downwire_camera_a...
    /downwire_camera/realsense2_camera/base_frame_id: downwire_camera_link
    /downwire_camera/realsense2_camera/color_fps: 30
    /downwire_camera/realsense2_camera/color_frame_id: downwire_camera_c...
    /downwire_camera/realsense2_camera/color_height: 480
    /downwire_camera/realsense2_camera/color_optical_frame_id: downwire_camera_c...
    /downwire_camera/realsense2_camera/color_width: 848
    /downwire_camera/realsense2_camera/depth_fps: 30
    /downwire_camera/realsense2_camera/depth_frame_id: downwire_camera_d...
    /downwire_camera/realsense2_camera/depth_height: 480
    /downwire_camera/realsense2_camera/depth_optical_frame_id: downwire_camera_d...
    /downwire_camera/realsense2_camera/depth_width: 848
    /downwire_camera/realsense2_camera/enable_color: True
    /downwire_camera/realsense2_camera/enable_depth: True
    /downwire_camera/realsense2_camera/enable_fisheye: True
    /downwire_camera/realsense2_camera/enable_imu: True
    /downwire_camera/realsense2_camera/enable_infra1: True
    /downwire_camera/realsense2_camera/enable_infra2: True
    /downwire_camera/realsense2_camera/enable_pointcloud: False
    /downwire_camera/realsense2_camera/enable_sync: False
    /downwire_camera/realsense2_camera/filters:
    /downwire_camera/realsense2_camera/fisheye_fps: 30
    /downwire_camera/realsense2_camera/fisheye_height: 480
    /downwire_camera/realsense2_camera/fisheye_optical_frame_id: downwire_camera_f...
    /downwire_camera/realsense2_camera/fisheye_width: 848
    /downwire_camera/realsense2_camera/gyro_fps: 1000
    /downwire_camera/realsense2_camera/gyro_optical_frame_id: downwire_camera_g...
    /downwire_camera/realsense2_camera/infra1_fps: 30
    /downwire_camera/realsense2_camera/infra1_frame_id: downwire_camera_i...
    /downwire_camera/realsense2_camera/infra1_height: 480
    /downwire_camera/realsense2_camera/infra1_optical_frame_id: downwire_camera_i...
    /downwire_camera/realsense2_camera/infra1_width: 848
    /downwire_camera/realsense2_camera/infra2_fps: 30
    /downwire_camera/realsense2_camera/infra2_frame_id: downwire_camera_i...
    /downwire_camera/realsense2_camera/infra2_height: 480
    /downwire_camera/realsense2_camera/infra2_optical_frame_id: downwire_camera_i...
    /downwire_camera/realsense2_camera/infra2_width: 848
    /downwire_camera/realsense2_camera/json_file_path:
    /downwire_camera/realsense2_camera/pointcloud_texture_index: 0
    /downwire_camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
    /downwire_camera/realsense2_camera/rosbag_filename:
    /downwire_camera/realsense2_camera/serial_no: 827312071232
    /rosdistro: kinetic
    /rosversion: 1.12.14

NODES
/downwire_camera/
color_rectify_color (nodelet/nodelet)
points_xyzrgb_sw_registered (nodelet/nodelet)
realsense2_camera (nodelet/nodelet)
realsense2_camera_manager (nodelet/nodelet)
register_depth (nodelet/nodelet)
/
downwire_extract (downwire_extract/downwire_extract)
rviz (rviz/rviz)

auto-starting new master
process[master]: started with pid [15197]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to ba002c72-f936-11e8-a579-58fb84344185
process[rosout-1]: started with pid [15210]
started core service [/rosout]
process[downwire_camera/realsense2_camera_manager-2]: started with pid [15227]
process[downwire_camera/realsense2_camera-3]: started with pid [15228]
process[downwire_camera/color_rectify_color-4]: started with pid [15229]
process[downwire_camera/register_depth-5]: started with pid [15240]
process[downwire_camera/points_xyzrgb_sw_registered-6]: started with pid [15245]
process[downwire_extract-7]: started with pid [15264]
process[rviz-8]: started with pid [15281]
[ INFO] [1544087408.594536163]: Initializing nodelet with 4 worker threads.
[ INFO] [1544087408.643148830]: Object Recongnize starts now
[ INFO] [1544087408.680489146]: RealSense ROS v2.1.1
[ INFO] [1544087408.680530504]: Running with LibRealSense v2.16.3
[ INFO] [1544087409.058825952]: getParameters...
[ INFO] [1544087409.098457054]: setupDevice...
[ INFO] [1544087409.098486977]: JSON file is not provided
[ INFO] [1544087409.098508300]: ROS Node Namespace: downwire_camera
[ INFO] [1544087409.098528041]: Device Name: Intel RealSense D435
[ INFO] [1544087409.098608550]: Device Serial No: 827312071232
[ INFO] [1544087409.098629462]: Device FW version: 05.10.06.00
[ INFO] [1544087409.098648145]: Device Product ID: 0x0B07
[ INFO] [1544087409.098664068]: Enable PointCloud: Off
[ INFO] [1544087409.098679963]: Align Depth: Off
[ INFO] [1544087409.098695346]: Sync Mode: Off
[ INFO] [1544087409.098916490]: Device Sensors:
[ INFO] [1544087409.099052049]: Stereo Module was found.
[ INFO] [1544087409.099111661]: RGB Camera was found.
[ INFO] [1544087409.099273644]: (Fisheye, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1544087409.099291904]: (Gyro, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1544087409.099307851]: (Accel, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1544087409.099345025]: setupPublishers...
[ INFO] [1544087409.101551247]: Expected frequency for depth = 30.00000
[ INFO] [1544087409.127329309]: Expected frequency for infra1 = 30.00000
[ INFO] [1544087409.152861868]: Expected frequency for infra2 = 30.00000
[ INFO] [1544087409.177100673]: Expected frequency for color = 30.00000
[ INFO] [1544087409.205774845]: setupStreams...
06/12 17:10:09,206 WARNING [139648129361792] (sensor.cpp:338) Unregistered Media formats : [ UYVY ]; Supported: [ ]
[ INFO] [1544087409.208483653]: depth stream is enabled - width: 848, height: 480, fps: 30
[ INFO] [1544087409.208752107]: infra1 stream is enabled - width: 848, height: 480, fps: 30
[ INFO] [1544087409.208956487]: infra2 stream is enabled - width: 848, height: 480, fps: 30
06/12 17:10:09,209 WARNING [139648129361792] (backend-v4l2.cpp:1248) Pixel format 36315752-1a66-a242-9065-d01814a likely requires patch for fourcc code RW16!
06/12 17:10:09,209 WARNING [139648129361792] (sensor.cpp:338) Unregistered Media formats : [ RW16 ]; Supported: [ ]
[ INFO] [1544087409.211001498]: color stream is enabled - width: 848, height: 480, fps: 30
[ INFO] [1544087409.225294972]: num_filters: 0
[ INFO] [1544087409.225346490]: publishStaticTransforms...
[ INFO] [1544087409.225685804]: RealSense Node Is Up!
[ INFO] [1544087409.225788868]: Start updating dynamic parameters...
06/12 17:10:09,329 WARNING [139648129361792] (types.cpp:57) start_streaming(...) failed. UVC device is already streaming!
06/12 17:10:09,329 WARNING [139648129361792] (types.cpp:57) start_streaming(...) failed. UVC device is already streaming!
06/12 17:10:09,329 WARNING [139648129361792] (types.cpp:57) start_streaming(...) failed. UVC device is already streaming!
06/12 17:10:09,329 WARNING [139648129361792] (types.cpp:57) start_streaming(...) failed. UVC device is already streaming!
06/12 17:10:09,333 ERROR [139648129361792] (types.h:179) xioctl(VIDIOC_S_CTRL) failed Last Error: Numerical result out of range
[ERROR] [1544087409.334303266]: Failed. Skip initialization of parameter 24
[ INFO] [1544087409.385095769]: Done updating dynamic parameters...
06/12 17:10:09,406 WARNING [139647192524544] (ds5-timestamp.cpp:64) UVC metadata payloads not available. Please refer to installation chapter for details.
[ WARN] [1544087409.408741991]: Frame metadata isn't available! (frame_timestamp_domain = RS2_TIMESTAMP_DOMAIN_SYSTEM_TIME)
06/12 17:10:14,224 WARNING [139647212570368] (backend-v4l2.cpp:1013) Frames didn't arrived within 5 seconds
06/12 17:10:14,224 WARNING [139647204177664] (backend-v4l2.cpp:1013) Frames didn't arrived within 5 seconds
06/12 17:10:19,226 WARNING [139647212570368] (backend-v4l2.cpp:1013) Frames didn't arrived within 5 seconds
06/12 17:10:19,229 WARNING [139647204177664] (backend-v4l2.cpp:1013) Frames didn't arrived within 5 seconds

I check the usb 3.0 connection with 'ls usb', it shows:
zf@lhc-Vostro:~$ lsusb
Bus 002 Device 017: ID 8086:0b07 Intel Corp.
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 006: ID 138a:0011 Validity Sensors, Inc. VFS5011 Fingerprint Reader
Bus 001 Device 005: ID 8087:0a2a Intel Corp.
Bus 001 Device 004: ID 0bda:0129 Realtek Semiconductor Corp. RTS5129 Card Reader Controller
Bus 001 Device 003: ID 0c45:6a06 Microdia
Bus 001 Device 002: ID 046d:c534 Logitech, Inc. Unifying Receiver
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

I check sys log, it shows:
zf@lhc-Vostro:~$ dmesg
[20855.418099] uvcvideo: Non-zero status (-71) in video completion handler.
[20855.423400] uvcvideo: Non-zero status (-71) in video completion handler.
[20855.423743] uvcvideo: Failed to query (GET_CUR) UVC control 1 on unit 3: -32 (exp. 1024).
[20855.473899] uvcvideo: Failed to query (GET_CUR) UVC control 1 on unit 3: -32 (exp. 1024).
[20855.530443] uvcvideo: Failed to query (SET_CUR) UVC control 11 on unit 3: -32 (exp. 1).

I restart the realsense2_camera node again and again, sometimes it can work, but when sys report nodelet crashed, like below description, the realsense2_camera node will never get any chance to reborn, and I have to replug the device. Any method can help me out?

[ INFO] [1544088579.373052225]: Initializing nodelet with 4 worker threads.
[ INFO] [1544088579.404851532]: Object Recongnize starts now
[ INFO] [1544088579.405896438]: RealSense ROS v2.1.1
[ INFO] [1544088579.405926441]: Running with LibRealSense v2.16.3
[ INFO] [1544088579.670355461]: getParameters...
[ INFO] [1544088579.744674142]: setupDevice...
[ INFO] [1544088579.744706993]: JSON file is not provided
[ INFO] [1544088579.744744354]: ROS Node Namespace: downwire_camera
[ INFO] [1544088579.744771135]: Device Name: Intel RealSense D435
[ INFO] [1544088579.744787247]: Device Serial No: 827312071232
[ INFO] [1544088579.744801169]: Device FW version: 05.10.06.00
[ INFO] [1544088579.744817532]: Device Product ID: 0x0B07
[ INFO] [1544088579.744835146]: Enable PointCloud: Off
[ INFO] [1544088579.744874768]: Align Depth: Off
[ INFO] [1544088579.744890976]: Sync Mode: Off
[ INFO] [1544088579.745109216]: Device Sensors:
[ INFO] [1544088579.745244832]: Stereo Module was found.
[ INFO] [1544088579.745280028]: RGB Camera was found.
[ INFO] [1544088579.745461482]: (Fisheye, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1544088579.745485683]: (Gyro, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1544088579.745503641]: (Accel, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1544088579.745546619]: setupPublishers...
[ INFO] [1544088579.750161493]: Expected frequency for depth = 30.00000
[ INFO] [1544088579.791599470]: Expected frequency for infra1 = 30.00000
[ INFO] [1544088579.820627107]: Expected frequency for infra2 = 30.00000
[ INFO] [1544088579.851374611]: Expected frequency for color = 30.00000
[ INFO] [1544088579.879053737]: setupStreams...
06/12 17:29:39,879 WARNING [139908659517312] (sensor.cpp:338) Unregistered Media formats : [ UYVY ]; Supported: [ ]
[ INFO] [1544088579.880634647]: depth stream is enabled - width: 848, height: 480, fps: 30
[ INFO] [1544088579.880881410]: infra1 stream is enabled - width: 848, height: 480, fps: 30
[ INFO] [1544088579.881104228]: infra2 stream is enabled - width: 848, height: 480, fps: 30
06/12 17:29:39,881 WARNING [139908659517312] (backend-v4l2.cpp:1248) Pixel format 36315752-1a66-a242-9065-d01814a likely requires patch for fourcc code RW16!
06/12 17:29:39,881 WARNING [139908659517312] (sensor.cpp:338) Unregistered Media formats : [ RW16 ]; Supported: [ ]
[ INFO] [1544088579.883141575]: color stream is enabled - width: 848, height: 480, fps: 30
06/12 17:29:44,891 WARNING [139907938899712] (backend-v4l2.cpp:1013) Frames didn't arrived within 5 seconds
06/12 17:29:44,975 ERROR [139908659517312] (types.h:179) xioctl(VIDIOC_STREAMON) failed for buf_type=1 Last Error: Input/output error
[ERROR] [1544088590.097255257]: An exception has been thrown: xioctl(VIDIOC_STREAMON) failed for buf_type=1 Last Error: Input/output error
[ERROR] [1544088590.097558169]: An exception has been thrown: xioctl(VIDIOC_STREAMON) failed for buf_type=1 Last Error: Input/output error
[FATAL] [1544088590.245427995]: Failed to load nodelet '/downwire_camera/points_xyzrgb_sw_registeredof typedepth_image_proc/point_cloud_xyzrgbto managerrealsense2_camera_manager'
[FATAL] [1544088590.245463713]: Failed to load nodelet '/downwire_camera/realsense2_cameraof typerealsense2_camera/RealSenseNodeFactoryto managerrealsense2_camera_manager'
[FATAL] [1544088590.245472823]: Failed to load nodelet '/downwire_camera/color_rectify_colorof typeimage_proc/rectifyto managerrealsense2_camera_manager'
[FATAL] [1544088590.245516913]: Failed to load nodelet '/downwire_camera/register_depthof typedepth_image_proc/registerto managerrealsense2_camera_manager'
[downwire_camera/realsense2_camera_manager-2] process has died [pid 16466, exit code -11, cmd /opt/ros/kinetic/lib/nodelet/nodelet manager __name:=realsense2_camera_manager __log:=/home/zf/.ros/log/73d9914a-f939-11e8-a579-58fb84344185/downwire_camera-realsense2_camera_manager-2.log].
log file: /home/zf/.ros/log/73d9914a-f939-11e8-a579-58fb84344185/downwire_camera-realsense2_camera_manager-2*.log
[downwire_camera/realsense2_camera-3] process has died [pid 16467, exit code 255, cmd /opt/ros/kinetic/lib/nodelet/nodelet load realsense2_camera/RealSenseNodeFactory realsense2_camera_manager __name:=realsense2_camera __log:=/home/zf/.ros/log/73d9914a-f939-11e8-a579-58fb84344185/downwire_camera-realsense2_camera-3.log].
log file: /home/zf/.ros/log/73d9914a-f939-11e8-a579-58fb84344185/downwire_camera-realsense2_camera-3*.log
[downwire_camera/color_rectify_color-4] process has died [pid 16468, exit code 255, cmd /opt/ros/kinetic/lib/nodelet/nodelet load image_proc/rectify realsense2_camera_manager --no-bond image_mono:=color/image_raw image_rect:=color/image_rect_color __name:=color_rectify_color __log:=/home/zf/.ros/log/73d9914a-f939-11e8-a579-58fb84344185/downwire_camera-color_rectify_color-4.log].
log file: /home/zf/.ros/log/73d9914a-f939-11e8-a579-58fb84344185/downwire_camera-color_rectify_color-4*.log
[downwire_camera/register_depth-5] process has died [pid 16476, exit code 255, cmd /opt/ros/kinetic/lib/nodelet/nodelet load depth_image_proc/register realsense2_camera_manager false rgb/camera_info:=color/camera_info depth/camera_info:=depth/camera_info depth/image_rect:=depth/image_rect_raw depth_registered/image_rect:=depth_registered/sw_registered/image_rect_raw __name:=register_depth __log:=/home/zf/.ros/log/73d9914a-f939-11e8-a579-58fb84344185/downwire_camera-register_depth-5.log].
log file: /home/zf/.ros/log/73d9914a-f939-11e8-a579-58fb84344185/downwire_camera-register_depth-5*.log
[downwire_camera/points_xyzrgb_sw_registered-6] process has died [pid 16485, exit code 255, cmd /opt/ros/kinetic/lib/nodelet/nodelet load depth_image_proc/point_cloud_xyzrgb realsense2_camera_manager false rgb/image_rect_color:=color/image_rect_color rgb/camera_info:=color/camera_info depth_registered/image_rect:=depth_registered/sw_registered/image_rect_raw depth_registered/points:=depth_registered/points __name:=points_xyzrgb_sw_registered __log:=/home/zf/.ros/log/73d9914a-f939-11e8-a579-58fb84344185/downwire_camera-points_xyzrgb_sw_registered-6.log].
log file: /home/zf/.ros/log/73d9914a-f939-11e8-a579-58fb84344185/downwire_camera-points_xyzrgb_sw_registered-6*.log

**Comment by doronhi** [comment]
It seems to be a firmware issue, indeed related to the Ctrl-C shutdown.
Until it is fixed, I've merged a "reset hardware" option (usage: initial_reset:=true) in the last release (v2.1.3)

**Comment by FENGZHANG123** [comment]
Yes, I have solved this problem also by hardware reset. Sorry for forgetting to close this problem.
