### ISSUE TITLE
WARN Unrecognized sr300 param (works in realsense-viewer)

### ISSUE THREAD

**Issue by ghost** [realsenseai/realsense-ros#530]
Version | Your Configuration
-- | --
Operating System | 16.04
Kernel | 4.16
ROS | Kinetic
ROS RealSense | V2.1.2
librealsense | V2.17
Camera Type-Firmware | SR300 3.21.0.0

My camera works in the realsense-viewer as seen below. I feel I have uploaded all the information I have now. I wonder if anyone could share some ideas on how to fix this isse? I kept getting unrecognized sr300 param error as attached. I was trying to do this 
`roslaunch realsense2_camera rs_camera.launch`

I could track it back to this page [(unrecognized sr300 param](https://github.com/search?q=unrecognized+sr300+param&type=Code) but I don't know how to fix it or what is causing it.

Great thanks in advance,.

![image](https://user-images.githubusercontent.com/28070085/49692973-c6f6dc80-fb2c-11e8-8097-2270e6146612.png)
![image](https://user-images.githubusercontent.com/28070085/49692975-d83fe900-fb2c-11e8-8db5-251ba1216a4c.png)
![image](https://user-images.githubusercontent.com/28070085/49692977-e3931480-fb2c-11e8-83b9-974c662d8f92.png)

**Comment by doronhi** [comment]
Hello,
I updated the development branch so there is no longer specific consideration for each camera.
Could you check and see if it works for you and if not, what is the updated phenomena?
