### ISSUE TITLE
demo_pointcloud.launch cannot see pointcloud in rviz

### ISSUE THREAD

**Issue by dakejahl** [realsenseai/realsense-ros#532]
running `roslaunch realsense2_camera demo_pointcloud.launch`
![selection_006](https://user-images.githubusercontent.com/37091262/49909601-d59b0780-fe3c-11e8-9d03-29cafd7b4711.png)

I do not see anything in rviz. I've been successful in running `rs-pointcloud` in `/usr/local/bin` so I don't think there is anything wrong with my hardware. I am just not getting a point cloud visualization in rviz.

![selection_007](https://user-images.githubusercontent.com/37091262/49909682-27439200-fe3d-11e8-8218-49b161da4ba4.png)

**Comment by doronhi** [comment]
Where is the Error, Ignoring transform for child_frame_id "camera_color_frame" coming from?
I mean, is there anything else running that could publish a different transform for the frame_id "camera_color_frame"?

**Comment by dakejahl** [comment]
I have no idea where the error is coming from. I have simply followed the instructions in the README and am trying to using one of the launch files to visualize a pointcloud. I have nothing else in ROS running. I am using firmware version 5.9.13 on the D435. Thanks for the help!

Also I should note I am building from `master` from `librealsense` and `master` from `intel-ros/realsense`

**Comment by dakejahl** [comment]
Same issue with `realsense` `2.1.2` and `librealsense` `2.17.0`
![selection_008](https://user-images.githubusercontent.com/37091262/49957549-6a494800-fec5-11e8-9ffb-6c3d44758fcb.png)

There is a tiny little box at my origin point that changes color when I move my hand in front of it. Idk if that helps.
![selection_009](https://user-images.githubusercontent.com/37091262/49957781-1723c500-fec6-11e8-957b-692eb1e4eda0.png)

Output from `rostopic echo /tf_static`
![selection_010](https://user-images.githubusercontent.com/37091262/49958624-a0d49200-fec8-11e8-9a7d-6a4ef15a4f77.png)

**Comment by doronhi** [comment]
The values for the translation are not valid.
Could you run:
`rs-enumerate-devices -c`
and look in the output for a section starting with: "Extrinsic from "Color"	  To	  "Infrared 1"". Something like this:

```
Extrinsic from "Color"	  To	  "Infrared 1" :
Rotation Matrix:
0.99989        0.013115       -0.0062178     
-0.013114      0.99991        0.0001742      
0.0062195      -9.2639e-05    0.99998        

Translation Vector: -0.014903349801898  -0.000295773410471156  -0.000403936661314219  


```

**Comment by pavloblindnology** [comment]
Confirm that pointcloud is not published. Extrinsics are ok.

**Comment by doronhi** [comment]
Please reopen the issue if problem is not solved. Also, out of curiosity and if you have the time, i'd appreciate to learn what the problem was if it is solved.

**Comment by mzahana** [comment]
I have the same problem. I am using realsense2 v2.2.1 and librealsense v2.19.0.
When I execute ```rs-enumerate-devices -c``` I get
```
Extrinsic from "Color"	  To	  "Infrared 1" :
Rotation Matrix:
0              0              0              
0              0              0              
0              0              0              

Translation Vector: 0  0  0 
```

What could be the issue?

**Comment by nekovfra** [comment]
I am having the same issue with new D435i camera. The rotational matrices are also zero. Tried on both Ubuntu16/Kinetic and 18/Melodic, in VMware, on machine. Might be issue with the camera HW itself.

**Comment by doronhi** [comment]
It seems like a known firmware bug. You can stay updated at [issue#3788](https://github.com/IntelRealSense/librealsense/issues/3788)
