### ISSUE TITLE
what is the use of toggleSensors() function?

### ISSUE THREAD

**Issue by hayaalsh** [realsenseai/realsense-ros#534]
`BaseRealSenseNode::toggleSensors(bool enabled)` keeps throwing an annoying exception of type `wrong_api_call_sequence_error` that cannot be catched by the currently used handler of the same type nor any other more generalized exception handlers and it is driving me crazy. 
Why is this happening and is it okay if I got rid of this function all together?

**Comment by doronhi** [comment]
Hi,
Sorry about that.
The function was created a short while back to add an option to toggle the sensor on and off in run time, using dynamic_reconfigure.
The message is annoying, and it should be fixed.
However, I merged in a new version with new handling with the dynamic_reconfigure options. In this version the whole option for toggling the sensor on and off is still missing (although the function is still there), but on the plus side, the annoying message is gone.
Please check it out. Be advised that it requires librealsense v2.17.0 and up.

**Comment by hayaalsh** [comment]
Thank you very much! Yes, the recent update solves all the issues.
