### ISSUE TITLE
Urdf and mesh for D415

### ISSUE THREAD

**Issue by golftra** [realsenseai/realsense-ros#543]
Hi,

I have been using the D435 with ROS. For this model I could find correct URDF-Files and Mesh and it works fine. Now I want to use the D415 but I can't find the URDF and Mesh. I can add the camera as a blackbox to the endeffector of my robot but I don't now the internal transformations between the cam, ir, depth etc frames. Therefore my detections of objects are off.
Does anyone know where to get these files? Especially the internal tf between cam left, cam right, depth... frames is important.
Thanks

**Comment by SteveMacenski** [comment]
Adding to this a little, the mesh for the d435 is super high resolution, it actually takes more cpu to render it than the rest of my robot combined

**Comment by elbartojs** [comment]
I found the 3D model here : 
https://www.intel.fr/content/www/fr/fr/support/articles/000026841/emerging-technologies/intel-realsense-technology.html

But I'm also looking for the URDF of the D415, does someone have it ?

**Comment by doronhi** [comment]
Release 2.1.4 includes urdf file for D415 (add in PR #585)
