### ISSUE TITLE
the rviz lost some depth img 

### ISSUE THREAD

**Issue by woshisj** [realsenseai/realsense-ros#545]
Required Info |  
-- | --
Camera Model | SR300
Operating System & Version | ubuntu
Platform | PC
Language | C++ ROS

I run this commend
roslaunch realsense2_camera rs_rgbd.launch
and I find that the rviz without many black region
First image
![image](https://user-images.githubusercontent.com/32431758/50255587-813feb00-042d-11e9-9c17-9d0e0b07f278.png)

When I add one white paper in that place that‘s ok

![image](https://user-images.githubusercontent.com/32431758/50255592-8735cc00-042d-11e9-9b1e-cde28cb0314d.png)

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Close this issue for lack of activity. Please feel free to reopen if the issue is still relevant.
