### ISSUE TITLE
realsense2_camera error with D435i

### ISSUE THREAD

**Issue by xuxu123** [realsenseai/realsense-ros#549]
realsense2_camera error with D435i
ROS log as following
... logging to /home/xrx/.ros/log/c05d7e70-04c2-11e9-9d77-309c23cdb4b9/roslaunch-xrx-Com-11913.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://xrx-Com:35579/

SUMMARY
========

PARAMETERS
 * /camera/realsense2_camera/accel_fps: 1000
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: False
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/color_fps: 30
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: 480
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: 640
 * /camera/realsense2_camera/depth_fps: 30
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: 480
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: 640
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye: True
 * /camera/realsense2_camera/enable_imu: True
 * /camera/realsense2_camera/enable_infra1: True
 * /camera/realsense2_camera/enable_infra2: True
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_sync: False
 * /camera/realsense2_camera/filters: 
 * /camera/realsense2_camera/fisheye_fps: 30
 * /camera/realsense2_camera/fisheye_height: 480
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: 640
 * /camera/realsense2_camera/gyro_fps: 1000
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/infra1_fps: 30
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_height: 480
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra1_width: 640
 * /camera/realsense2_camera/infra2_fps: 30
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_height: 480
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra2_width: 640
 * /camera/realsense2_camera/json_file_path: 
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/rosbag_filename: 
 * /camera/realsense2_camera/serial_no: 
 * /rosdistro: kinetic
 * /rosversion: 1.12.14

NODES
  /camera/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)

ROS_MASTER_URI=http://localhost:11311

process[camera/realsense2_camera_manager-1]: started with pid [11930]
process[camera/realsense2_camera-2]: started with pid [11931]
[ INFO] [1545362556.957393400]: Initializing nodelet with 12 worker threads.
[ INFO] [1545362557.003169523]: RealSense ROS v2.1.2
[ INFO] [1545362557.003193714]: Running with LibRealSense v2.17.0
[ERROR] [1545362557.007423779]: No RealSense devices were found! Terminating RealSense Node...
[FATAL] [1545362557.153832532]: Failed to load nodelet '/camera/realsense2_camera` of type `realsense2_camera/RealSenseNodeFactory` to manager `realsense2_camera_manager'
[camera/realsense2_camera_manager-1] process has died [pid 11930, exit code 1, cmd /opt/ros/kinetic/lib/nodelet/nodelet manager __name:=realsense2_camera_manager __log:=/home/xrx/.ros/log/c05d7e70-04c2-11e9-9d77-309c23cdb4b9/camera-realsense2_camera_manager-1.log].
log file: /home/xrx/.ros/log/c05d7e70-04c2-11e9-9d77-309c23cdb4b9/camera-realsense2_camera_manager-1*.log
[camera/realsense2_camera-2] process has died [pid 11931, exit code 255, cmd /opt/ros/kinetic/lib/nodelet/nodelet load realsense2_camera/RealSenseNodeFactory realsense2_camera_manager __name:=realsense2_camera __log:=/home/xrx/.ros/log/c05d7e70-04c2-11e9-9d77-309c23cdb4b9/camera-realsense2_camera-2.log].
log file: /home/xrx/.ros/log/c05d7e70-04c2-11e9-9d77-309c23cdb4b9/camera-realsense2_camera-2*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done

But I can find the D435i with lsusb and realsense-viewer
![image](https://user-images.githubusercontent.com/6927726/50323200-88412900-0513-11e9-8293-fe928e3564d9.png)
![image](https://user-images.githubusercontent.com/6927726/50323212-9abb6280-0513-11e9-9c4b-74342fb70fb7.png)

**Comment by doronhi** [comment]
Do you use the realsense2_camera release version? Support for D435i is still only in the development branch. Make sure you take the “one before the last” commit as the last one also needs the latest commit of librealsense to compile.

**Comment by xuxu123** [comment]
Thanks!
