### ISSUE TITLE
Can't connect the D435I camera

### ISSUE THREAD

**Issue by AdamPengG** [realsenseai/realsense-ros#562]
I have install the realsense sdk librealsense-2.17.1 and ROS wrapper realsense-2.1.3.And I follow the https://github.com/intel-ros/realsense/wiki/SLAM-with-D435i and install all the components.
Finally I run the roslaunch realsense2_camera opensource_tracking.launch.But the terminal shows I did't connect the the D435i.

[ERROR] [1546838519.355105483]: Failed to load nodelet [/camera/realsense2_camera] of type [realsense2_camera/RealSenseNodeFactory] even after refreshing the cache: Could not find library corresponding to plugin realsense2_camera/RealSenseNodeFactory. Make sure the plugin description XML file has the correct name of the library and that the library actually exists.
 [ERROR] [1546838519.355165653]: The error before refreshing the cache was: Could not find library corresponding to plugin realsense2_camera/RealSenseNodeFactory. Make sure the plugin description XML file has the correct name of the library and that the library actually exists. 
[FATAL] [1546838519.355291096]: Failed to load nodelet '/camera/realsense2_camera of type realsense2_camera/RealSenseNodeFactory to manager `realsense2_camera_manager
[camera/realsense2_camera-3] process has died [pid 10090, exit code 255, cmd /opt/ros/kinetic/lib/nodelet/nodelet load realsense2_camera/RealSenseNodeFactory realsense2_camera_manager __name:=realsense2_camera __log:=/home/peng/.ros/log/27cdb684-123c-11e9-8909-107b447e20dc/camera-realsense2_camera-3.log].
log file: /home/peng/.ros/log/27cdb684-123c-11e9-8909-107b447e20dc/camera-realsense2_camera-3*.log
[ WARN] [1546838525.358489472]: /rtabmap/rgbd_odometry: Did not receive data since 5 seconds! Make sure the input topics are published ("$ rostopic hz my_topic") and the timestamps in their header are set.
/rtabmap/rgbd_odometry subscribed to (approx sync):
/camera/color/image_raw,
/camera/aligned_depth_to_color/image_raw,
/camera/color/camera_info

'
`What should i do?
![realsense](https://user-images.githubusercontent.com/45864105/50751014-c021cd80-1282-11e9-9b1a-9b48a731f58c.png)
![realsense2](https://user-images.githubusercontent.com/45864105/50751015-c021cd80-1282-11e9-97ad-bcf493ede911.png)

**Comment by doronhi** [comment]
Hi,
The first thing to do is isolate the problem. Is the camera working and connected at all? 
1. Can you run realsense_viewer? (install using apt-get install librealsense2-utils)
On the viewer you can also see if it's connected using USB2 ro USB3.
Can you run:
2. `roslaunch realsense2_camera rs_camera.launch`?

Sometimes the camera gets connected to USB2 or not at all - reconnecting it may solve it.

**Comment by AdamPengG** [comment]
Yes I can run roslaunch realsense2_camera rs_camera.launch.
And the camera gets connected to USB3.But when I run lsusb.The D435i isn't on the usb list.
I wanna get the left and right camera raw picture topics and IMU data topics.Which launch can show those data.
![112](https://user-images.githubusercontent.com/45864105/50756670-df772580-1297-11e9-9285-903220fb00f3.png)
![113](https://user-images.githubusercontent.com/45864105/50756671-e00fbc00-1297-11e9-9c47-a5d92eca5d53.png)
Is that only one normal(RGB) camera?There are 4 cameras the other 3 cameras are which kinds?

**Comment by AdamPengG** [comment]
is anybody here?

**Comment by doronhi** [comment]
There is 1 RGB camera and 2 IR cameras.
The topics are /camera/color/image_raw, /camera/infra1/image_rect_raw, /camera/infra2/image_rect_raw.

**Comment by AdamPengG** [comment]
Thanks
