### ISSUE TITLE
aligned depth topic fps dropped to 18-20 ！

### ISSUE THREAD

**Issue by ahuizxc** [realsenseai/realsense-ros#565]
aligned depth topic is only 18-20, could anybody have some idea about this issue?
I think it is due to cpu's capability.

**Comment by MTDzi** [comment]
I have the same problem, only in my case it's even worse (~10 fps).

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Hi ahuizxc,

Wonder what ROS, RS SDK, and FW releases you have? We just tested something today for another issue (https://github.com/intel-ros/realsense/issues/407), and no issues with the topics' frame rate maintaining 30fps.
It was done off an Intel NUC i5. What system/CPU you have?

Thanks!

**Comment by ahuizxc** [comment]
> Hi ahuizxc,
> 
> Wonder what ROS, RS SDK, and FW releases you have? We just tested something today for another issue (#407), and no issues with the topics' frame rate maintaining 30fps.
> It was done off an Intel NUC i5. What system/CPU you have?
> 
> Thanks!

hi i am using ROS2, not ros with nuc7

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Hi ahuizxc,

Thanks for the clarification.

Again to help us understand and replicate the issue , can you please share more info?
To the issue you have, is it off a release from https://github.com/intel/ros2_intel_realsense? Or something?
What kind of setup you have (system, camera model, etc.)?

Thanks!

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Hi ahuizxc,

Wonder if you have any update or info to share?

Thanks!

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Hi ahuizxc,

If there is nothing else needed, this one will be closed.

Thanks!
