### ISSUE TITLE
A lot of noise in point clouds

### ISSUE THREAD

**Issue by woshisj** [realsenseai/realsense-ros#566]
When I use roslaunch realsense2_camera rs_rgbd. Launch driver sr300
I found a lot of noise in the point cloud. How can I solve it
RealSense ROS v2.1.2
Running with LibRealSense v2.17.0
![0](https://user-images.githubusercontent.com/32431758/50833202-7375e980-138b-11e9-9398-b5aa9d7c34ba.png)

what's the matter???
![image](https://user-images.githubusercontent.com/32431758/50967684-cc708980-1513-11e9-9925-4c0ef649a531.png)

**Comment by leocorp96** [comment]
You can improve the PCL data a bit by recalibrating your camera. (You might as well be required to update the device firmware as well.)

Check this page on how to: https://www.intel.com/content/www/us/en/support/articles/000026723/emerging-technologies/intel-realsense-technology.html

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Hi @woshisj,

Is the issue resolved with @Leocorp suggestion?

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

You can try some filters like hole_filling filter to see how it helps.

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Hi @woshisj,

If no further support required, will close this.
