### ISSUE TITLE
How to change the width and height?

### ISSUE THREAD

**Issue by lucasjinreal** [realsenseai/realsense-ros#568]
I changed the width and height in launch file, but it can not be run, said device not support such configuration....What should I do if I want change the default width and height which is 640*480 into 1024*72-? (Or any other sized)?

**Comment by doronhi** [comment]
The driver supports several resolutions but not everything.
You can check available resolutions by typing:
`rs-enumerate-devices`

**Comment by togashi01** [comment]
rs-enumerate-devices
