### ISSUE TITLE
Error:IMU sensor not supported by D435

### ISSUE THREAD

**Issue by yashkothari42** [realsenseai/realsense-ros#574]
OS:Ubuntu 16.04
Camera:Realsense d435

Does the realsense d435 has inbuilt IMU sensor? If yes, where is it published? 
I remember seeing odom topic few days back but not its not there when i run rs_camera launch file.

mrleo@Jarvis:~$ roslaunch realsense2_camera rs_camera.launch align_depth:=true
... logging to /home/mrleo/.ros/log/7bfe96c4-18b8-11e9-adfe-0242a541b17b/roslaunch-Jarvis-13507.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://Jarvis:42785/

SUMMARY
========

PARAMETERS
 * /camera/realsense2_camera/accel_fps: 250
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: True
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/clip_distance: -2.0
 * /camera/realsense2_camera/color_fps: 30
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: 480
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: 640
 * /camera/realsense2_camera/depth_fps: 30
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: 480
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: 640
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye: True
 * /camera/realsense2_camera/enable_imu: True
 * /camera/realsense2_camera/enable_infra1: True
 * /camera/realsense2_camera/enable_infra2: True
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_sync: False
 * /camera/realsense2_camera/filters: 
 * /camera/realsense2_camera/fisheye_fps: 30
 * /camera/realsense2_camera/fisheye_height: 480
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: 640
 * /camera/realsense2_camera/gyro_fps: 400
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/infra1_fps: 30
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_height: 480
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra1_width: 640
 * /camera/realsense2_camera/infra2_fps: 30
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_height: 480
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra2_width: 640
 * /camera/realsense2_camera/initial_reset: True
 * /camera/realsense2_camera/json_file_path: 
 * /camera/realsense2_camera/linear_accel_cov: 0.01
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/rosbag_filename: 
 * /camera/realsense2_camera/serial_no: 
 * /camera/realsense2_camera/unite_imu_method: 
 * /rosdistro: kinetic
 * /rosversion: 1.12.14

NODES
  /camera/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)

auto-starting new master
process[master]: started with pid [13517]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 7bfe96c4-18b8-11e9-adfe-0242a541b17b
process[rosout-1]: started with pid [13530]
started core service [/rosout]
process[camera/realsense2_camera_manager-2]: started with pid [13547]
process[camera/realsense2_camera-3]: started with pid [13548]
[ INFO] [1547551625.267924453]: Initializing nodelet with 8 worker threads.
[ INFO] [1547551625.289783826]: RealSense ROS v2.1.3
[ INFO] [1547551625.289851915]: Running with LibRealSense v2.17.1
[ INFO] [1547551625.293398337]: Resetting device...
[ INFO] [1547551630.668150604]: getParameters...
[ INFO] [1547551630.712011348]: setupDevice...
[ INFO] [1547551630.712039601]: JSON file is not provided
[ INFO] [1547551630.712057034]: ROS Node Namespace: camera
[ INFO] [1547551630.712107558]: Device Name: Intel RealSense D435
[ INFO] [1547551630.712121288]: Device Serial No: 817512071721
[ INFO] [1547551630.712133173]: Device FW version: 05.10.13.00
[ INFO] [1547551630.712145515]: Device Product ID: 0x0B07
[ INFO] [1547551630.712157472]: Enable PointCloud: Off
[ INFO] [1547551630.712170892]: Align Depth: On
[ INFO] [1547551630.712182131]: Sync Mode: On
[ INFO] [1547551630.712376384]: Device Sensors: 
[ INFO] [1547551630.712481316]: Stereo Module was found.
[ INFO] [1547551630.712504446]: RGB Camera was found.
**[ INFO] [1547551630.712631313]: (Fisheye, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1547551630.712647222]: (Gyro, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1547551630.712660414]: (Accel, 0) sensor isn't supported by current device! -- Skipping...**
[ INFO] [1547551630.712751492]: setupPublishers...
[ INFO] [1547551630.715593206]: Expected frequency for depth = 30.00000
[ INFO] [1547551630.747251360]: Expected frequency for infra1 = 30.00000
[ INFO] [1547551630.770715080]: Expected frequency for aligned_depth_to_infra1 = 30.00000
[ INFO] [1547551630.794826132]: Expected frequency for infra2 = 30.00000
[ INFO] [1547551630.822050092]: Expected frequency for aligned_depth_to_infra2 = 30.00000
[ INFO] [1547551630.847578435]: Expected frequency for color = 30.00000
[ INFO] [1547551630.873183584]: Expected frequency for aligned_depth_to_color = 30.00000
[ INFO] [1547551630.899616672]: setupStreams...
 15/01 16:57:10,900 WARNING [139701820700544] (sensor.cpp:338) Unregistered Media formats : [ UYVY ]; Supported: [ ]
[ INFO] [1547551630.901143669]: depth stream is enabled - width: 640, height: 480, fps: 30
[ INFO] [1547551630.901412781]: infra1 stream is enabled - width: 640, height: 480, fps: 30
[ INFO] [1547551630.901638063]: infra2 stream is enabled - width: 640, height: 480, fps: 30
[ INFO] [1547551630.903711660]: color stream is enabled - width: 640, height: 480, fps: 30
[ INFO] [1547551630.911285503]: num_filters: 0
[ INFO] [1547551630.911678888]: RealSense Node Is Up!
[ INFO] [1547551630.911711070]: Setting Dynamic reconfig parameters.
[ INFO] [1547551631.086030626]: Done Setting Dynamic reconfig parameters.

Also harware reset(using option) is not working for me.

**Comment by doronhi** [comment]
D435 is not equipped with IMU.
Only D435i has built in IMU.
