### ISSUE TITLE
Is there any way to remove IR dots from IR Frames without toggling Depth Emitter?

### ISSUE THREAD

**Issue by gajena** [realsenseai/realsense-ros#575]
I am working with `D435i` and trying to implement Visual Inertial algorithm with IR frames and IMU.
* It is working fine when Depth Emitter is disabled, But Disabling Depth Emitter results in bad Point cloud data with artifacts.

**Comment by doronhi** [comment]
I think the following open PR, in librealsense, may help in your case:
https://github.com/IntelRealSense/librealsense/pull/3066

Notice that in order to check it out you need to wait for the upcoming release of the new firmware update. Hopefully very soon.

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]
