### ISSUE TITLE
D435i IMU msgs have big gap frequently?

### ISSUE THREAD

**Issue by Shayens** [realsenseai/realsense-ros#577]
Just shown as the figure, it appears gaps frequently. Also, the frequency of IMU msgs are not stable, however in zr300, it's stable. 
Is this the bug hasn't fixed yet? Or I'm not using it correctly.
By the way, how to enable "hold_back_imu_for_frames", is it right as this `roslaunch realsense2_camera rs_camera.launch hold_back_imu_for_frames:=on`but I didn't see any difference...
D435i bag
![screenshot from 2019-01-17 16-31-36](https://user-images.githubusercontent.com/22326338/51305667-84eb7f80-1a76-11e9-86db-71be0e0f81ca.png)
![image](https://user-images.githubusercontent.com/22326338/51305748-af3d3d00-1a76-11e9-8f09-74843f5a4477.png)
ZR300 bag
![image](https://user-images.githubusercontent.com/22326338/51305799-d0059280-1a76-11e9-9932-1f5649d75ad0.png)

**Comment by Shashika007** [comment]
@Shayens  did you find a solution for this issue ? i noticed this too

**Comment by Shashika007** [comment]
And another thing, i noticed that with new librealsense-2.18.1 and realsense-2.1.4 ros, camera/color/image_raw is aligned with camera/depth/image_raw_rect but not with camera/alignedalinged_depth_to_color/image_raw ? Do you have any idea about why ? 

![screenshot from 2019-02-14 11-06-07](https://user-images.githubusercontent.com/15320876/52762314-9d38c500-3049-11e9-9d77-a04c32261846.png)

**Comment by doronhi** [comment]
@Shayens 
I used librealsense v2.18.1, realsense2_camera v2.2.0 and firmware: 05.10.13.00.
I used python to check the time stamps in the messages' header:
```
bag = rosbag.Bag(bag_filename)
tg = np.array([msg.header.stamp.to_sec() for topic, msg, t in bag.read_messages(topics=topic_str)])
dtg = tg[1:] - tg[:-1]
max_gap = print dtg.max() / np.median(dtg)
```
np.median(dtg) == 0.0025 (fps = 250)
dtg.max() == 0.005
I get max_gap = 2, which is not what we see in the rqt_bag graph.

When I take the rosbag times, however:
```
tg = np.array([t.to_sec() for topic, msg, t in bag.read_messages(topics='/camera/gyro/sample')])
dtg = tg[1:] - tg[:-1]
```
I get max_gap = 8.98. In this case dtg.max() == 0.022.

In other words, what I see in the graph has to do with loads on the ROS environment and the bag record application. The timestamps in the messages themselves have no gaps.

**Comment by doronhi** [comment]
@Shashika007 - duplicate question in issue#573

**Comment by doronhi** [comment]
@Shayens 
regarding hold_back_imu_for_frames, it should be hold_back_imu_for_frames:=**true**
However, the argument is missing from rs_camera.launch and from nodelet.launch.xml. You need to add it there (copy the example of the argument `align_depth`)
In addition, this argument is only meaningful if `unite_imu_method` is also set to either **linear_interpolation** or **copy**.

**Comment by Shayens** [comment]
Thanks for your test. And sorry for didn't reply to you @Shashika007. I also plot by package multiplot and verify, so it seems rqt_bag is using receipt time.
![screenshot from 2019-03-01 19-49-54](https://user-images.githubusercontent.com/22326338/53637658-b56e2e00-3c5e-11e9-9754-418961e98960.png)
