### ISSUE TITLE
Can a windows10 ROS 2 RVIZ2 connect to ROS RealSense TOPIC?

### ISSUE THREAD

**Issue by tmichals** [realsenseai/realsense-ros#580]
Is there away to get RVIZ2 on my windows10 computer to connect to a Intell RealSense camera running on a nvidia TX2 ubuntu ROS(kinectic) computer?   I can get RVIZ to connect as long as I am running RVIZ on a ROS ubuntu computer, (however I need to use a  windows10 computer for RVIZ). Since only RVIZ2  will run on windows10 that is my only choice. 

I have tried getting RVIZ to work by installing ubuntu natively on windows10...but I was not able to get the video to stream into the Xming terminal. I could see the ROS Topics in Xming...just no video. 
Here is an error I would get on TX2 (lots of unknowns)...
________________
Could not initialize OpenGL for RasterGLSurface, reverting to RasterSurface.
QXcbConnection: XCB error: 170 (Unknown), sequence: 163, resource id: 90, major code: 146 (Unknown), minor code: 20
Segmentation fault (core dumped)
____________________________________________
I found no real help with this problem.  

So now I am trying to get RVIZ2 working in windows.

I am new to ROS2, but I was able to get the ROS2 Windows-Install-Binary working on Windows10.   I installed OpenSplice for Crystal.

I can start rviz2 from command prompt, and add a camera...but as I would expect the Topic has a status Error- Error Subscribing: Empty Topic name. There are no RealSense Topics to attach to.

I know from running rviz on ROS ubuntu computer there are some other prerequisites like.. exporting my ROS_IP and exporting to the ROS_MASTER_URI=http://xx.xx.xx.xx:11311 that have to be done before I can launch rviz. So how does ROS2 do this...do I need to do something in ROS2 before I start RVIZ2? Can ROS2 RVIZ2 get topics from ROS master and RealSense Node?!

Perhaps I have to install ROS 2 RealSense on my TX2?

**Comment by atyshka** [comment]
@tmichals This package only supports ROS 1, and RViz 2 is incompatible with ROS 1. If you really want to visualize on Windows I suggest using a virtual machine and running ROS 1 in it.

**Comment by tmichals** [comment]
I have installed ROS2 for windows10 on my windows10 PC.    I understand you are saying ROS2 will not work with ROS.   Can I install ROS1 for windows10 on my PC without uninstalling ROS2(for window10)?   There would not be any virtual machines installed unless you mean create another windows10 virtual machine on my windows10 computer for ROS1..confused by what you are saying about virtual ROS1 machine?  

So the plan is that I will install ROS1 on my windows10 PC.   Then on my windows10 PC ROS1 RVIZ, will be able to connect to the ROS Topics on my robots nvidia TX2 RealSense Camera.   

So for a ROS1 install ...before I startup rviz I assume it is similar to regular ROS where I need to export ROS_IP and ROS_MASTER_URI?   That I could see working.

**Comment by atyshka** [comment]
Ros 1 does not work on windows. You need to set up a Linux virtual machine on windows and run ros 1 from that virtual machine.

**Comment by tmichals** [comment]
Here are the links that I found running ROS1 on windows10:
                                   https://ms-iot.github.io/ROSOnWindows/
                                   https://ms-iot.github.io/ROSOnWindows/GettingStarted/Setup.html
_____________________
Here is a link explaining the wsl installs that I did on windows10...                               https://janbernloehr.de/2017/06/10/ros-windows

but there was no RealSense video displayed trying to use rvis. 
_________________________

    Do you know of a different camera interface for realsense other than using rviz?  That would work just to display realsense video?  Does not have to be ROS..just needs to be able to attach to camera on TX2 from windows10.

**Comment by atyshka** [comment]
Sorry, but this really has nothing to do with the realsense ros. You can’t get RViz working in Windows is the real problem, and Windows isn’t officially supported by ROS. To resolve this I’d ask some questions in the Windows ROS community.

**Comment by tmichals** [comment]
Thank you.   At least you understand the problem.  I hope if you have some pull that someone on would be able to bridge the ubuntu/windows ROS gap for RealSense.     I need RealSense to run on the nvidia TX2 ROS ubuntu and connect to a ROS RVIZ running on windows.   RVIZ will fire up in the windows10 wsl version which is ubuntu...but RVIZ has to run in a Xming type terminal which looses the video stream when RVIZ comes up there is a mapping problem...nothing shows up.   could be in the OpenGL to windows area.  The Topic selections in rviz are available ; that is specifically where someone would need to examine.   There are some settings for the Xming server that I have not tried perhaps that will work.    Second...when it comes to ROS2  the best understanding I have is ROS2 and ROS are not compatible...which is a big problem, and that is not a RealSense issue but perhaps someone is working to address that through a bridge connection.   Is this all correct?  

Here is a video link for you to see my nvidia TX2 RealSense issue.. 
https://www.youtube.com/watch?v=Bd6TBd4Z8vk&t=15s

**Comment by tmichals** [comment]
Here is a video link for you to see my nvidia TX2 RealSense issue.. https://www.youtube.com/watch?v=Bd6TBd4Z8vk&t=15s

**Comment by doronhi** [comment]
I'll quote @atyshka : "Sorry, but this really has nothing to do with the realsense ros". This is an issue with running RVIZ with ROS1 on windows.
