### ISSUE TITLE
ROS issues rs::depth_frame data topic and subscribes it at other nodes

### ISSUE THREAD

**Issue by LonelyDreamr** [realsenseai/realsense-ros#582]
The RGB image passed to the ros topic was very smooth, but there was a problem with subscribing to the depth information.
I want to subscribe “depth” from the ROS topic and calculate the 3D Points corresponding to the pixel coordinates using function "rs2_deproject_pixel_to_point" in the code below.
`
       rs2::frameset data = pipe.wait_for_frames();
       data = align_to.process(data);
       auto depth = data.get_depth_frame();
       rs2_intrinsics intr = depth.get_profile().as<rs2::video_stream_profile>().get_intrinsics(); 
       rs2_deproject_pixel_to_point(point, &intr, pixel, dist);
`
I have compiled the official ROS sample code successfully.
I would like to ask which topic I need to subscribe to so that I can use the depth_frame type of data at the subscribing node.thx:)

**Comment by doronhi** [comment]
Not sure I understand. Are you asking which topic contains the depth_frame?

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Close this issue for lack of activity.
Please feel free to reopen if the issue is still relevant.
