### ISSUE TITLE
Is it possible to sync external IMU trigger with GPIO pins?

### ISSUE THREAD

**Issue by gajena** [realsenseai/realsense-ros#586]
For VIO application time delay plays main role, So it would be great if it is possible.

**Comment by Shashika007** [comment]
@gajena did you find a method ?

**Comment by gajena** [comment]
Hi @Shashika007 ,
We tried with this [white-paper](https://realsense.intel.com/wp-content/uploads/sites/63/Multiple_Camera_WhitePaper_rev1.1.pdf) published from Intel. We found that trigger high time is around 60 us with 1.8V TTL for IR camera. We have tried it with TTL signals from Arduino. But We have not tried with IMU.
Best,
Gajendra
