### ISSUE TITLE
No stream match for pointcloud chosen texture Process - Color

### ISSUE THREAD

**Issue by atyshka** [realsenseai/realsense-ros#588]
Launching the camera, I'm getting this error and it's only happened in the last couple weeks.

I'm launching aligned depth with filter like so:

    <include file="$(find realsense2_camera)/launch/rs_aligned_depth.launch">
      <arg name="filters" value="temporal,spatial,pointcloud"/>
    </include>

And I'm getting `[ WARN] [1548347476.424286155]: No stream match for pointcloud chosen texture Process - Color`
It seems to be just a warning with no effect on functionality, but it's definitely annoying. Absolute latest librealsense debian and firmware.

**Comment by doronhi** [comment]
The warning appears every time there is a frame drop of the needed as texture. For that frame, the point cloud is not published.
I agree it's more annoying then informative.
Fixed in PR #591
