### ISSUE TITLE
E: Unable to locate package librealsense2-dkms

### ISSUE THREAD

**Issue by lz130dd** [realsenseai/realsense-ros#589]
When I follow the instructions in the file "travis.yml ", after I run the commend

$ sudo apt-get install librealsense2-dkms --allow-unauthenticated -y 

I got error like this,

$ sudo apt-get install librealsense2-dkms --allow-unauthenticated -y 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package librealsense2-dkms

I have tried to use " sudo apt-get update", but it doesn't work. Can anybody help me with this?

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]

**Comment by thanujadax** [comment]
Did you set the apt source as described in the installation guide for Ubuntu?

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Inactivity for 30+ days.
Close this issue. Please feel free to reopen if problem persists.

**Comment by q8wwe** [comment]
i have same problem how to solve it ???

**Comment by MarcoAndrade26** [comment]
Same problem here!

**Comment by doronhi** [comment]
As @thanujadax commented, Did you set the apt source as described in the installation guide for Ubuntu?

**Comment by MarcoAndrade26** [comment]
@doronhi Yes! Every command and step from installation guide
