### ISSUE TITLE
T265 Support Timeline?

### ISSUE THREAD

**Issue by atyshka** [realsenseai/realsense-ros#594]
Hi, this is just a general question as to when support for the T265 sensor will get built into this repo. ROS support was advertised on the product page and this is definitely something we're interested in, but a general timeline as to when these changes will be built in would greatly help!

**Comment by zilogo** [comment]
I also have same "schedule question" about  ROS wrapper support for the T265, many thanks for your support:)

**Comment by SteveMacenski** [comment]
Especially for just tracking - with no loop closure / SLAM due to the fact it doesn't work in even moderately large spaces. Having something like this to fuse into my filters would be immensely helpful

**Comment by atyshka** [comment]
@SteveMacenski You mean the T265 won't work in a larger space? Where did you hear that? I would think that since it's using rgb as opposed to structured light that it would be better suited to open spaces.

**Comment by SteveMacenski** [comment]
@atyshka from the intel folks, they're branding it as SLAM in a box, but it can't maintain maps that are very large so in practice I just want it for tracking. This is not a depth camear.

**Comment by atyshka** [comment]
@SteveMacenski I see what you're saying. While it does seem that it can't hold very large maps, they have promised the ability to save and load maps using librealsense. I believe that saving and loading maps could help with large areas. Without detail on how it works though, I guess we'll just have to wait for the release.

**Comment by doronhi** [comment]
Hi, as a general time frame, I hope support for T265 will be available in a week.

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]

**Comment by immotri** [comment]
Does the T265 detect loop closures? If not, is there any way to achieve bundle adjustments after loop closures with this device? I can‘t find any more detailed information on the V-SLAM used by Intel. It appears to be more a V-odometry since Feature points are not recorded. Any info from Phillip Schmidt a co would be appreciated!

**Comment by atyshka** [comment]
@immotri Yes, it does. I did some testing handheld with no wheel odometry, can’t speak for using it with wheel odometry. For small loops (25m or less) I got good results in a single loop. For larger loops I got better results taking two loops to refine the position a little more.

**Comment by immotri** [comment]
I got good results running 3 loops in my flat. Not sure whether the loops adjusted after closure. I will take it into the garden tomorrow. Any info on how to integrate a wheel odometer would be great.

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Intel is continuing to improve upon our current offering and improve wheel odometry samples under the ROS repository for T265.  Continue to monitor the ROS release for updates.  Relocalization updates are coming in a future release.
