### ISSUE TITLE
Inconsistent depth data size at 720p resolution

### ISSUE THREAD

**Issue by efernandez** [realsenseai/realsense-ros#596]
System Configuration

Version | Your Configuration
-- | --
Operating System | Ubuntu 16.04.5 LTS
Kernel | 4.15.0-43-generic
Backend | video4linux
ROS | Melodic
ROS RealSense | 2.1.2
librealsense | 2.18.0-0~realsense0.506
D435 Firmware | 5.10.13.0

With `720 x 1280` resolution (`height x width`) the depth image (in particular the `aligned_depth_to_color` one) has an inconsistent data size:
``` bash
$ rostopic echo --noarr /realsense/aligned_depth_to_color/image_raw
...
height: 720
width: 1280
encoding: "16UC1"
is_bigendian: 0
step: 2560
data: "<array type: uint8, length: 2764800>"
---
```

The `data` size should be `== height * step` and `step == 2 * width`, where `2` comes from the `16UC1` encoding (2 bytes).
In this case we have: `720 * 2560 == 1843200`, which is not `2764800`.
Indeed it seems that the data has `3` bytes (`2764800 / 1843200 == 1.5`, i.e. `720 * 1280 * 3 == 2764800`). Likely the memory allocated assumed something wrong like that.

At `640 x 360` things are consistent:
``` bash
$ rostopic echo --noarr /realsense/aligned_depth_to_color/image_raw
...
height: 360
width: 640
encoding: "16UC1"
is_bigendian: 0
step: 1280
data: "<array type: uint8, length: 460800>"
---
```

where `360 * 1280 == 460800`, which is the `data` size.

As a consequence of this inconsistency, saving a depth image fails in `cv_bridge`, because it checks that here: https://github.com/ros-perception/vision_opencv/blob/kinetic/cv_bridge/src/cv_bridge.cpp#L263

The conversion into point cloud doesn't check for the `data` size, so that explains that part works regardless of this inconsistency. Also the point cloud obtained from the depth `data` with inconsistent size seemed correct to me, so the extra bytes are likely only at the end.

Not sure if this is a problem in the ROS wrapper (this repo) or the `librealsense` library. If this should be filed on the driver repo, maybe it's worth pinging one of its maintainers here first to see how I can show this same issue at the driver level, and not in the output topics from the ROS wrapper.

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]

**Comment by doronhi** [comment]
Sorry for the long while.
It seems that the issue was solved in the following versions of realsense2_camera. I believe it had to do with bugs found in the "info" topics.
It is not reproduced in realsense2_camera 2.2.8 and librealsense v2.25.0.
