### ISSUE TITLE
Problem when running roslaunch realsense2_camera rs_camera.launch on odroid

### ISSUE THREAD

**Issue by florianspy** [realsenseai/realsense-ros#610]
I get the following exception:
[ERROR] [1549883789.649319258]: An exception has been thrown: hwmon command 0x7d failed. Error type: Invalid Command (-1).

**Comment by doronhi** [comment]
Is realsense-viewer working ok?

**Comment by florianspy** [comment]
no its not working

**Comment by doronhi** [comment]
What librealsense version do you use? 
check [librealsense issue#3137](https://github.com/IntelRealSense/librealsense/issues/3137)

**Comment by florianspy** [comment]
i am using version 2.18.0

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Hi florianspy,

To better understand and support, can you share more info of the issue?
a) This is running Ubuntu (16.04 or 18.04) off Odroid XU or something else?
b) As you said RS Viewer 2.18.0 is not working neither, has any RS releases worked off your platform?
c) Did you install from packages or build from source? Any issue along the installation/build?

Thanks!

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Hi florianspy,

Wonder if there is any update?

Thanks!
