### ISSUE TITLE
Publish projector and asic temperatures from camera driver

### ISSUE THREAD

**Issue by tulku** [realsenseai/realsense-ros#613]
It would be nice to have the driver publish the projector and ASIC temperatures like they are displayed on the RealSense Viewer software.

As the cameras have temperature protection features that might reduce the power or even turn off the projector, it would be good to be able to monitor the temperatures to be sure that the camera is operating safely.

These temperatures could be publish in diagnostics or using a new custom topics.

**Comment by SteveMacenski** [comment]
`diagnostics` would be best, that's a great suggestion! I would also make great use of that

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]

**Comment by doronhi** [comment]
added in #878.

**Comment by doronhi** [comment]
merged into [release 2.2.8](https://github.com/IntelRealSense/realsense-ros/releases/tag/2.2.8)
