### ISSUE TITLE
Continuous Integration for pull request has not been active

### ISSUE THREAD

**Issue by 130s** [realsenseai/realsense-ros#619]
# Problem

Looks like CI for PRs have not been active for awhile...If I look at the [list of all PRs](https://github.com/intel-ros/realsense/pulls?q=is%3Apr+sort%3Acreated-desc), CI hasn't run publicly (or at least visibly on github's PR view) for months.

This makes me as a contributor a bit concerned about the review process. How the reviewers verify the PR build, pass tests, perform as claimed etc.

# Suggested solution

- Enable ROS buildfarm CI as it used to? All it needs might be just this [setup](http://wiki.ros.org/buildfarm/Pull%20request%20testing).
  - For realsense_camera, not v2, it seems [enable already](https://github.com/ros/rosdistro/blob/18528139d05ba1c25050d3770a72cfce4a0d3ba3/kinetic/distribution.yaml#L9986).
- Use Travis CI as it's more convenient tool CI option IMO.
  - Looks like [config file is already available](https://github.com/intel-ros/realsense/blob/c5ea27245967e0938f7d10384f4b7279e01000b4/.travis.yml). So enable Travis CI at somewhere like https://travis-ci.org/organizations/intel-ros/realsense might be enough.
- Do both of above.

**Comment by 130s** [comment]
On a related side note, my team enabled Travis CI on our fork repo. There we found some tests are failing https://github.com/plusone-robotics/realsense/pull/16#issuecomment-459791527
IMO that's one good thing about enabling CI (i.e. found flaky tests).

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]
