### ISSUE TITLE
Add guards around clang-specific pragmas 

### ISSUE THREAD

**Issue by jarvisschultz** [realsenseai/realsense-ros#628]
There are a few clang-specific pragmas used throughout the code that throw warnings when compiling with GCC. For example, see [the beginning of dd_enum_params.cpp](https://github.com/intel-ros/realsense/blob/3e25326b4128d37b15d1e11085dd2f19d3cf1a66/ddynamic_reconfigure/src/param/dd_enum_param.cpp#L1-L5). Should all of these be wrapped with appropriate `#ifdef` calls? E.g.

```cpp
#ifdef __clang__
#pragma clang diagnostic push
#pragma ide diagnostic ignored "OCUnusedGlobalDeclarationInspection"
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma ide diagnostic ignored "modernize-loop-convert"
#pragma ide diagnostic ignored "modernize-use-auto"
#endif
```
suppresses the error.

**Comment by doronhi** [comment]
Could be a nice idea. The warnings do bother me but I never got around to handle it yet. Any help will be appreciated.

**Comment by jarvisschultz** [comment]
Added a PR. Let me know if there are any issues.
