### ISSUE TITLE
How to get the x,y,z positions of each point from the D435i in ROS? 

### ISSUE THREAD

**Issue by Levi568** [realsenseai/realsense-ros#633]
I subscribe the topic of "camera/depth/image_rect_raw" in Rviz, it shows the image successfully. However, the message type of the topic is sensor_msgs/Image, which doesn't contain depth value (or does it?). Is there a way to extract the x, y, z values of the points with respect to the camera frame? 

![screenshot from 2019-02-23 18-35-40](https://user-images.githubusercontent.com/12791539/53293103-a5a4a480-379b-11e9-9b28-c99b12f3d371.png)

**Comment by doronhi** [comment]
I think that you may be interested in the /camera/depth/color/points topic.
Or, if you want to have the points without the rgb texture, set pointcloud_texture_index:=RS2_STREAM_ANY
