### ISSUE TITLE
Question about how to get the accurate distance to object?

### ISSUE THREAD

**Issue by QiuYilin** [realsenseai/realsense-ros#637]
I know there is a function to get distance in librealsense2 api. But how to get distance by ros package if I know the x and y coordinate in camera/color/image_raw. It seems that I need to subscribe /camera/depth/color/points. But I know little about how to transform rgbxyz to distance. Can anyone give some suggestions?

**Comment by doronhi** [comment]
you should subscribe to aligned_depth_to_color and check the value of the color pixel on that image.

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]

**Comment by Ageneinair** [comment]
Can I ask you how to get distance in librealsense2 api (python wrapper)?
