### ISSUE TITLE
how I install this with Melodic?

### ISSUE THREAD

**Issue by FPSychotic** [realsenseai/realsense-ros#645]

**Comment by FPSychotic** [comment]
can I install this via source in melodic? If not, there is plan to port it?

**Comment by abylikhsanov** [comment]
Just download the source code and compile it as usual

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Close it for lack of activity. Feel free to reopen if it is still relevant.
