### ISSUE TITLE
Support for F200

### ISSUE THREAD

**Issue by techtron16** [realsenseai/realsense-ros#65]
Can someone advise how to use this package with the F200?

**Comment by ghindman** [comment]
Hi @techtron16 v1.2 provides the infrastructure to support different camera types within the nodelet, but we have not yet added support for cameras other than the R200.  We should be adding other cameras soon, or are happy to take community PR's in the meantime.

**Comment by mdhorn** [comment]
F200 supported added in release 1.3.0
