### ISSUE TITLE
Dynamic reconfigure parameters namespace

### ISSUE THREAD

**Issue by pavloblindnology** [realsenseai/realsense-ros#654]
With current implementation
https://github.com/intel-ros/realsense/blob/36dd73aae6bc1b654ad085393eac279339d7f5a0/realsense2_camera/src/base_realsense_node.cpp#L233

all dynamic_reconfigure parameters parameters reside in root nodelet namespace.
This is quite inconvenient, because with multiple cameras we need to use multiple nodelets.
Otherwise there will be names' conflict.
More reasonable is to publish them in camera namespace, by using
`ros::NodeHandle nh1(nh.getNamespace()+"/"+module_name);`
instead.

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]

**Comment by RhysMcK** [comment]
I also had to make a similar change to run all camera under the same nodelet manager.

**Comment by doronhi** [comment]
Is #702 tackles this issue?

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@pavloblindnology Can you feedback if https://github.com/IntelRealSense/realsense-ros/pull/702 works for this issue? Thanks!

**Comment by pavloblindnology** [comment]
@RealSenseCustomerSupport Yes, #702 fixes this issue.
