### ISSUE TITLE
Realsense D435 + SLAM

### ISSUE THREAD

**Issue by arb93** [realsenseai/realsense-ros#655]
I am currently using this:

https://github.com/intel-ros/realsense/wiki/SLAM-with-D435i

along with my D435i camera. I have got it working fine and outputting reasonable poses. My question pertains to the co-ordinate systems:

I know that the algorithm localizes relative to the first captured frame, but physically speaking, does that correspond to the center of the RGB camera? Or some other point on the D435 camera?

Thanks!

**Comment by abylikhsanov** [comment]
Look at your TF and the middle (intersection of 3 axes, XYZ) is the correspondence point.

If you have a robot then it depends on your tree. Usually, the base_link (or base_footprint) is the correspondence point. Localization is being done to base_link with respect to the global fixed frame map.

**Comment by RealSenseCustomerSupport** [comment]
[Please Ignore - RealSense system comment]
