### ISSUE TITLE
Dynamic transform support again

### ISSUE THREAD

**Issue by pavloblindnology** [realsenseai/realsense-ros#660]
In previous version of this library, a solution to ROS's multiple latched publishers problem existed #221 #169.
In the current version only static transforms exist, which again returns the problem of multiple cameras configuration running within a single nodelet manager.
Any plans to return the old solution?

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@pavloblindnology After checked #169, I saw Doron suggest you provide PR for this. Are you still working on this? Thanks!

**Comment by pavloblindnology** [comment]
@RealSenseCustomerSupport It's almost done. I think I'll finally find the time next week to finalize everything.

**Comment by pavloblindnology** [comment]
@RealSenseCustomerSupport Created PR #902

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@pavloblindnology Thanks very much!

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@pavloblindnology  https://github.com/IntelRealSense/realsense-ros/pull/902 merged to development branch now. Thanks again for your contribution! Will close this accordingly.
