### ISSUE TITLE
D435i: cannot run rs_camera.launch properly

### ISSUE THREAD

**Issue by yubaoliu** [realsenseai/realsense-ros#663]
yubao@yubao-Z370M-S01:~$ roslaunch realsense2_camera rs_camera.launch
... logging to /home/yubao/.ros/log/339a4e2c-4136-11e9-909c-309c23e1152f/roslaunch-yubao-Z370M-S01-4511.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://yubao-Z370M-S01:43333/

SUMMARY
========

PARAMETERS
 * /camera/realsense2_camera/accel_fps: 250
 * /camera/realsense2_camera/accel_frame_id: camera_accel_frame
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: False
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/clip_distance: -2.0
 * /camera/realsense2_camera/color_fps: 30
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: 480
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: 640
 * /camera/realsense2_camera/depth_fps: 30
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: 480
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: 640
 * /camera/realsense2_camera/enable_accel: True
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye1: True
 * /camera/realsense2_camera/enable_fisheye2: True
 * /camera/realsense2_camera/enable_fisheye: True
 * /camera/realsense2_camera/enable_gyro: True
 * /camera/realsense2_camera/enable_infra1: True
 * /camera/realsense2_camera/enable_infra2: True
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_sync: False
 * /camera/realsense2_camera/filters: 
 * /camera/realsense2_camera/fisheye1_frame_id: camera_fisheye1_f...
 * /camera/realsense2_camera/fisheye1_optical_frame_id: camera_fisheye1_o...
 * /camera/realsense2_camera/fisheye2_frame_id: camera_fisheye2_f...
 * /camera/realsense2_camera/fisheye2_optical_frame_id: camera_fisheye2_o...
 * /camera/realsense2_camera/fisheye_fps: 30
 * /camera/realsense2_camera/fisheye_frame_id: camera_fisheye_frame
 * /camera/realsense2_camera/fisheye_height: 480
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: 640
 * /camera/realsense2_camera/gyro_fps: 400
 * /camera/realsense2_camera/gyro_frame_id: camera_gyro_frame
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra_fps: 30
 * /camera/realsense2_camera/infra_height: 480
 * /camera/realsense2_camera/infra_width: 640
 * /camera/realsense2_camera/initial_reset: False
 * /camera/realsense2_camera/json_file_path: 
 * /camera/realsense2_camera/linear_accel_cov: 0.01
 * /camera/realsense2_camera/odom_frame_id: camera_odom_frame
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/pose_frame_id: camera_pose_frame
 * /camera/realsense2_camera/pose_optical_frame_id: camera_pose_optic...
 * /camera/realsense2_camera/rosbag_filename: 
 * /camera/realsense2_camera/serial_no: 
 * /camera/realsense2_camera/unite_imu_method: 
 * /rosdistro: kinetic
 * /rosversion: 1.12.14

NODES
  /camera/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)

auto-starting new master
process[master]: started with pid [4521]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 339a4e2c-4136-11e9-909c-309c23e1152f
process[rosout-1]: started with pid [4534]
started core service [/rosout]
process[camera/realsense2_camera_manager-2]: started with pid [4551]
process[camera/realsense2_camera-3]: started with pid [4552]
[ INFO] [1552003666.607480810]: Initializing nodelet with 12 worker threads.
[ERROR] [1552003666.632283699]: Failed to load nodelet [/camera/realsense2_camera] of type [realsense2_camera/RealSenseNodeFactory] even after refreshing the cache: Could not find library corresponding to plugin realsense2_camera/RealSenseNodeFactory. Make sure the plugin description XML file has the correct name of the library and that the library actually exists.
[ERROR] [1552003666.632301993]: The error before refreshing the cache was: Could not find library corresponding to plugin realsense2_camera/RealSenseNodeFactory. Make sure the plugin description XML file has the correct name of the library and that the library actually exists.
[FATAL] [1552003666.632360012]: Failed to load nodelet '/camera/realsense2_camera` of type `realsense2_camera/RealSenseNodeFactory` to manager `realsense2_camera_manager'
[camera/realsense2_camera-3] process has died [pid 4552, exit code 255, cmd /opt/ros/kinetic/lib/nodelet/nodelet load realsense2_camera/RealSenseNodeFactory realsense2_camera_manager __name:=realsense2_camera __log:=/home/yubao/.ros/log/339a4e2c-4136-11e9-909c-309c23e1152f/camera-realsense2_camera-3.log].
log file: /home/yubao/.ros/log/339a4e2c-4136-11e9-909c-309c23e1152f/camera-realsense2_camera-3*.log

yubao@yubao-Z370M-S01:~$ rostopic list 
/rosout
/rosout_agg

yubao@yubao-Z370M-S01:~$ uname -a
Linux yubao-Z370M-S01 4.15.0-46-generic #49~16.04.1-Ubuntu SMP Tue Feb 12 17:45:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

yubao@yubao-Z370M-S01:~$ rs-enumerate-devices | grep Serial
    Serial Number                 : 	841612071561

realsense-viewer  can work properly:
yubao@yubao-Z370M-S01:~$ realsense-viewer 
 08/03 09:04:42,931 WARNING [139652824631040] (types.cpp:57) hwmon command 0x4f failed. Error type: No data to return (-21).
 08/03 09:04:42,953 WARNING [139652824631040] (sensor.cpp:338) Unregistered Media formats : [ UYVY ]; Supported: [ ]
![image](https://user-images.githubusercontent.com/17697584/53997950-7ae62300-4181-11e9-8b11-73a353b88877.png)

yubao@yubao-Z370M-S01:~$ lsusb 
Bus 002 Device 002: ID 8086:0b3a Intel Corp. 
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 003: ID 0566:3107 Monterey International Corp. Keyboard
Bus 001 Device 002: ID 046d:c077 Logitech, Inc. M105 Optical Mouse
Bus 001 Device 004: ID 047f:c025 Plantronics, Inc. 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub

------------------------------------------------------------------------
I also tried https://github.com/intel-ros/realsense/wiki/SLAM-with-D435i:

yubao@yubao-Z370M-S01:~$ roslaunch realsense2_camera opensource_tracking.launch
... logging to /home/yubao/.ros/log/ddd7998a-4136-11e9-909c-309c23e1152f/roslaunch-yubao-Z370M-S01-4952.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://yubao-Z370M-S01:42525/

SUMMARY
========

CLEAR PARAMETERS
 * /ukf_se/

PARAMETERS
 * /ImuFilter/_publish_tf: False
 * /ImuFilter/_use_ma: False
 * /ImuFilter/_world_frame: enu
 * /camera/realsense2_camera/accel_fps: 250
 * /camera/realsense2_camera/accel_frame_id: camera_accel_frame
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: True
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/clip_distance: -2.0
 * /camera/realsense2_camera/color_fps: 30
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: 480
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: 640
 * /camera/realsense2_camera/depth_fps: 30
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: 480
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: 640
 * /camera/realsense2_camera/enable_accel: True
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye1: True
 * /camera/realsense2_camera/enable_fisheye2: True
 * /camera/realsense2_camera/enable_fisheye: True
 * /camera/realsense2_camera/enable_gyro: True
 * /camera/realsense2_camera/enable_infra1: True
 * /camera/realsense2_camera/enable_infra2: True
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_sync: False
 * /camera/realsense2_camera/filters: 
 * /camera/realsense2_camera/fisheye1_frame_id: camera_fisheye1_f...
 * /camera/realsense2_camera/fisheye1_optical_frame_id: camera_fisheye1_o...
 * /camera/realsense2_camera/fisheye2_frame_id: camera_fisheye2_f...
 * /camera/realsense2_camera/fisheye2_optical_frame_id: camera_fisheye2_o...
 * /camera/realsense2_camera/fisheye_fps: 30
 * /camera/realsense2_camera/fisheye_frame_id: camera_fisheye_frame
 * /camera/realsense2_camera/fisheye_height: 480
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: 640
 * /camera/realsense2_camera/gyro_fps: 400
 * /camera/realsense2_camera/gyro_frame_id: camera_gyro_frame
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra_fps: 30
 * /camera/realsense2_camera/infra_height: 480
 * /camera/realsense2_camera/infra_width: 640
 * /camera/realsense2_camera/initial_reset: False
 * /camera/realsense2_camera/json_file_path: 
 * /camera/realsense2_camera/linear_accel_cov: 1.0
 * /camera/realsense2_camera/odom_frame_id: camera_odom_frame
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/pose_frame_id: camera_pose_frame
 * /camera/realsense2_camera/pose_optical_frame_id: camera_pose_optic...
 * /camera/realsense2_camera/rosbag_filename: 
 * /camera/realsense2_camera/serial_no: 
 * /camera/realsense2_camera/unite_imu_method: linear_interpolation
 * /points_xyzrgb/approx_sync: True
 * /points_xyzrgb/decimation: 4.0
 * /points_xyzrgb/voxel_size: 0.0
 * /rosdistro: kinetic
 * /rosversion: 1.12.14
 * /rtabmap/rgbd_odometry/approx_sync: True
 * /rtabmap/rgbd_odometry/config_path: 
 * /rtabmap/rgbd_odometry/frame_id: camera_link
 * /rtabmap/rgbd_odometry/ground_truth_base_frame_id: 
 * /rtabmap/rgbd_odometry/ground_truth_frame_id: 
 * /rtabmap/rgbd_odometry/guess_frame_id: 
 * /rtabmap/rgbd_odometry/guess_min_rotation: 0.0
 * /rtabmap/rgbd_odometry/guess_min_translation: 0.0
 * /rtabmap/rgbd_odometry/odom_frame_id: odom
 * /rtabmap/rgbd_odometry/queue_size: 10
 * /rtabmap/rgbd_odometry/subscribe_rgbd: False
 * /rtabmap/rgbd_odometry/wait_for_transform_duration: 0.2
 * /rtabmap/rtabmap/Mem/IncrementalMemory: true
 * /rtabmap/rtabmap/Mem/InitWMWithAllNodes: false
 * /rtabmap/rtabmap/approx_sync: True
 * /rtabmap/rtabmap/config_path: 
 * /rtabmap/rtabmap/database_path: ~/.ros/rtabmap.db
 * /rtabmap/rtabmap/frame_id: camera_link
 * /rtabmap/rtabmap/ground_truth_base_frame_id: 
 * /rtabmap/rtabmap/ground_truth_frame_id: 
 * /rtabmap/rtabmap/map_frame_id: map
 * /rtabmap/rtabmap/odom_frame_id: 
 * /rtabmap/rtabmap/odom_sensor_sync: False
 * /rtabmap/rtabmap/odom_tf_angular_variance: 1.0
 * /rtabmap/rtabmap/odom_tf_linear_variance: 1.0
 * /rtabmap/rtabmap/queue_size: 10
 * /rtabmap/rtabmap/scan_normal_k: 0
 * /rtabmap/rtabmap/subscribe_depth: True
 * /rtabmap/rtabmap/subscribe_odom_info: True
 * /rtabmap/rtabmap/subscribe_rgbd: False
 * /rtabmap/rtabmap/subscribe_scan: False
 * /rtabmap/rtabmap/subscribe_scan_cloud: False
 * /rtabmap/rtabmap/subscribe_stereo: False
 * /rtabmap/rtabmap/subscribe_user_data: False
 * /rtabmap/rtabmap/wait_for_transform_duration: 0.2
 * /ukf_se/acceleration_gains: [0.8, 0.0, 0.0, 0...
 * /ukf_se/acceleration_limits: [1.3, 0.0, 0.0, 0...
 * /ukf_se/alpha: 0.001
 * /ukf_se/base_link_frame: camera_link
 * /ukf_se/beta: 2
 * /ukf_se/control_config: [True, False, Fal...
 * /ukf_se/control_timeout: 0.2
 * /ukf_se/debug: False
 * /ukf_se/debug_out_file: /path/to/debug/fi...
 * /ukf_se/deceleration_gains: [1.0, 0.0, 0.0, 0...
 * /ukf_se/deceleration_limits: [1.3, 0.0, 0.0, 0...
 * /ukf_se/frequency: 300
 * /ukf_se/imu0: /imu/data
 * /ukf_se/imu0_config: [False, False, Fa...
 * /ukf_se/imu0_differential: True
 * /ukf_se/imu0_linear_acceleration_rejection_threshold: 0.8
 * /ukf_se/imu0_nodelay: False
 * /ukf_se/imu0_pose_rejection_threshold: 0.8
 * /ukf_se/imu0_queue_size: 5
 * /ukf_se/imu0_relative: False
 * /ukf_se/imu0_remove_gravitational_acceleration: True
 * /ukf_se/imu0_twist_rejection_threshold: 0.8
 * /ukf_se/initial_estimate_covariance: ['1e-9', 0, 0, 0,...
 * /ukf_se/kappa: 0
 * /ukf_se/map_frame: map
 * /ukf_se/odom0: rtabmap/odom
 * /ukf_se/odom0_config: [True, True, True...
 * /ukf_se/odom0_differential: False
 * /ukf_se/odom0_nodelay: False
 * /ukf_se/odom0_pose_rejection_threshold: 10000000
 * /ukf_se/odom0_queue_size: 2
 * /ukf_se/odom0_relative: True
 * /ukf_se/odom0_twist_rejection_threshold: 10000000
 * /ukf_se/odom1: example/another_odom
 * /ukf_se/odom1_config: [False, False, Tr...
 * /ukf_se/odom1_differential: False
 * /ukf_se/odom1_nodelay: False
 * /ukf_se/odom1_pose_rejection_threshold: 2
 * /ukf_se/odom1_queue_size: 2
 * /ukf_se/odom1_relative: True
 * /ukf_se/odom1_twist_rejection_threshold: 0.2
 * /ukf_se/odom_frame: odom
 * /ukf_se/pose0: example/pose
 * /ukf_se/pose0_config: [True, True, Fals...
 * /ukf_se/pose0_differential: True
 * /ukf_se/pose0_nodelay: False
 * /ukf_se/pose0_queue_size: 5
 * /ukf_se/pose0_rejection_threshold: 2
 * /ukf_se/pose0_relative: False
 * /ukf_se/print_diagnostics: True
 * /ukf_se/process_noise_covariance: [0.05, 0, 0, 0, 0...
 * /ukf_se/sensor_timeout: 0.1
 * /ukf_se/stamped_control: False
 * /ukf_se/transform_time_offset: 0.0
 * /ukf_se/transform_timeout: 0.0
 * /ukf_se/twist0: example/twist
 * /ukf_se/twist0_config: [False, False, Fa...
 * /ukf_se/twist0_nodelay: False
 * /ukf_se/twist0_queue_size: 3
 * /ukf_se/twist0_rejection_threshold: 2
 * /ukf_se/two_d_mode: False
 * /ukf_se/use_control: False
 * /ukf_se/world_frame: odom

NODES
  /camera/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)
  /rtabmap/
    rgbd_odometry (rtabmap_ros/rgbd_odometry)
    rtabmap (rtabmap_ros/rtabmap)
  /
    ImuFilter (imu_filter_madgwick/imu_filter_node)
    points_xyzrgb (nodelet/nodelet)
    rviz (rviz/rviz)
    ukf_se (robot_localization/ukf_localization_node)

auto-starting new master
process[master]: started with pid [4963]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to ddd7998a-4136-11e9-909c-309c23e1152f
process[rosout-1]: started with pid [4976]
started core service [/rosout]
process[camera/realsense2_camera_manager-2]: started with pid [4994]
process[camera/realsense2_camera-3]: started with pid [4995]
process[ImuFilter-4]: started with pid [4996]
process[rtabmap/rgbd_odometry-5]: started with pid [5008]
process[rtabmap/rtabmap-6]: started with pid [5022]
[ INFO] [1552003952.409936078]: Initializing nodelet with 12 worker threads.
process[rviz-7]: started with pid [5060]
process[points_xyzrgb-8]: started with pid [5074]
process[ukf_se-9]: started with pid [5086]
type is rtabmap_ros/point_cloud_xyzrgb
[ERROR] [1552003952.436131279]: Failed to load nodelet [/camera/realsense2_camera] of type [realsense2_camera/RealSenseNodeFactory] even after refreshing the cache: Could not find library corresponding to plugin realsense2_camera/RealSenseNodeFactory. Make sure the plugin description XML file has the correct name of the library and that the library actually exists.
[ERROR] [1552003952.436154844]: The error before refreshing the cache was: Could not find library corresponding to plugin realsense2_camera/RealSenseNodeFactory. Make sure the plugin description XML file has the correct name of the library and that the library actually exists.
[FATAL] [1552003952.436235112]: Failed to load nodelet '/camera/realsense2_camera` of type `realsense2_camera/RealSenseNodeFactory` to manager `realsense2_camera_manager'
/opt/ros/kinetic/lib/rtabmap_ros/rtabmap/opt/ros/kinetic/lib/rtabmap_ros/rgbd_odometry: error while loading shared libraries: libOpenNI.so.0: cannot open shared object file: No such file or directory
: error while loading shared libraries: libOpenNI.so.0: cannot open shared object file: No such file or directory
[rtabmap/rgbd_odometry-5] process has died [pid 5008, exit code 127, cmd /opt/ros/kinetic/lib/rtabmap_ros/rgbd_odometry --delete_db_on_start rgb/image:=/camera/color/image_raw depth/image:=/camera/aligned_depth_to_color/image_raw rgb/camera_info:=/camera/color/camera_info rgbd_image:=rgbd_image_relay odom:=odom __name:=rgbd_odometry __log:=/home/yubao/.ros/log/ddd7998a-4136-11e9-909c-309c23e1152f/rtabmap-rgbd_odometry-5.log].
log file: /home/yubao/.ros/log/ddd7998a-4136-11e9-909c-309c23e1152f/rtabmap-rgbd_odometry-5*.log
[rtabmap/rtabmap-6] process has died [pid 5022, exit code 127, cmd /opt/ros/kinetic/lib/rtabmap_ros/rtabmap --delete_db_on_start rgb/image:=/camera/color/image_raw depth/image:=/camera/aligned_depth_to_color/image_raw rgb/camera_info:=/camera/color/camera_info rgbd_image:=rgbd_image_relay left/image_rect:=/stereo_camera/left/image_rect_color right/image_rect:=/stereo_camera/right/image_rect left/camera_info:=/stereo_camera/left/camera_info right/camera_info:=/stereo_camera/right/camera_info scan:=/scan scan_cloud:=/scan_cloud user_data:=/user_data user_data_async:=/user_data_async odom:=odom __name:=rtabmap __log:=/home/yubao/.ros/log/ddd7998a-4136-11e9-909c-309c23e1152f/rtabmap-rtabmap-6.log].
log file: /home/yubao/.ros/log/ddd7998a-4136-11e9-909c-309c23e1152f/rtabmap-rtabmap-6*.log
[ERROR] [1552003952.479027497]: Failed to load nodelet [/points_xyzrgb] of type [rtabmap_ros/point_cloud_xyzrgb] even after refreshing the cache: Failed to load library /opt/ros/kinetic/lib//librtabmap_ros.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = libOpenNI.so.0: cannot open shared object file: No such file or directory)
[ERROR] [1552003952.479067427]: The error before refreshing the cache was: Failed to load library /opt/ros/kinetic/lib//librtabmap_ros.so. Make sure that you are calling the PLUGINLIB_EXPORT_CLASS macro in the library code, and that names are consistent between this macro and your XML. Error string: Could not load library (Poco exception = libOpenNI.so.0: cannot open shared object file: No such file or directory)
[camera/realsense2_camera-3] process has died [pid 4995, exit code 255, cmd /opt/ros/kinetic/lib/nodelet/nodelet load realsense2_camera/RealSenseNodeFactory realsense2_camera_manager __name:=realsense2_camera __log:=/home/yubao/.ros/log/ddd7998a-4136-11e9-909c-309c23e1152f/camera-realsense2_camera-3.log].
log file: /home/yubao/.ros/log/ddd7998a-4136-11e9-909c-309c23e1152f/camera-realsense2_camera-3*.log
[points_xyzrgb-8] process has died [pid 5074, exit code 255, cmd /opt/ros/kinetic/lib/nodelet/nodelet standalone rtabmap_ros/point_cloud_xyzrgb rgb/image:=/camera/color/image_raw depth/image:=/camera/aligned_depth_to_color/image_raw rgb/camera_info:=/camera/color/camera_info rgbd_image:=rgbd_image_relay cloud:=voxel_cloud __name:=points_xyzrgb __log:=/home/yubao/.ros/log/ddd7998a-4136-11e9-909c-309c23e1152f/points_xyzrgb-8.log].
log file: /home/yubao/.ros/log/ddd7998a-4136-11e9-909c-309c23e1152f/points_xyzrgb-8*.log
0x2910cc0 void QWindowPrivate::setTopLevelScreen(QScreen*, bool) ( QScreen(0x2425d70) ): Attempt to set a screen on a child window.

yubao@yubao-Z370M-S01:~$ rostopic list 
/ImuFilter/parameter_descriptions
/ImuFilter/parameter_updates
/camera/imu
/camera/rgb/image_rect_color
/diagnostics
/example/another_odom
/example/pose
/example/twist
/imu/data
/imu/mag
/initialpose
/move_base_simple/goal
/odometry/filtered
/rosout
/rosout_agg
/rtabmap/odom
/set_pose
/tf
/tf_static
/voxel_cloud

![image](https://user-images.githubusercontent.com/17697584/53998339-b2090400-4182-11e9-9613-38cbe3f473af.png)

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Hi yubaoliu,

Assuming that you followed the instructions and installed all ROS dependencies and also needed RS SDK.
Which FW your D435i has? And what version of ROS wrapper you have?
Do you have a D435 working with the ROS wrapper?

I tried a D435i w/ FW 5.11,1,100, and it has no issue with rs_camera.launch when using ROS wrapper 2.2.2 + RS SDK 2.19.1 (off Ubuntu 16.04 w/ kernel 4.15.0.46).
And also no issue with D435i w/ FW5.10.13.

Thanks!

**Comment by yubaoliu** [comment]
Thanks for your help.
This error disappeared when I reconfigure my ubuntu environment. Maybe some libs are conflicted on my machine.
I recommend using Docker to avoid environmental problems.

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Hi yubaoliu,

Thanks for the updates and feedback.
Glad to hear that the issue is resolved.

Thanks!

**Comment by hustchenli** [comment]
> Thanks for your help.
> This error disappeared when I reconfigure my ubuntu environment. Maybe some libs are conflicted on my machine.
> I recommend using Docker to avoid environmental problems.

I have the same problem. Could you please explain how to reconfigure ubuntu environment? I have tried deleting all build-files and rebuild it. But unfortunately it doesn't work.
