### ISSUE TITLE
D435 - USB SCP overflow,1.55236e+12,Error,Hardware Error

### ISSUE THREAD

**Issue by jdwolk** [realsenseai/realsense-ros#669]
Device: Raspberry Pi 3 Model B
OS version: Ubuntu MATE 16.04 
Camera: D435 (over USB2)
Firmware: 5.11.1.100
librealsense version: 2.18.1 (unpatched, for USB2 support)
ROS realsense version: 2.2.0
ROS version: kinetic

Hi!

When I run `roslaunch realsense2_camera rs_camera.launch filters:=pointcloud` I get lots of warnings that say the following:
```
[ WARN] [1552356094.393717336, 194.518000000]: Hardware Notification:USB SCP overlfow,1.55236e+12,Error,Hardware Error
```
I get topics showing up in `rqt` but no Pointcloud2 data seems to be appearing in `rviz` on the `/camera/depth_registered/points` as expected.

Also, `librealsense` seems to be working ok as `realsense-viewer`, `rc-depth`, etc, are working.

Thanks in advance for any help!

**Comment by jdwolk** [comment]
I was able to find a workaround with the following:

```
roslaunch realsense2_camera rs_camera.launch filters:=pointcloud enable_infra1:=false enable_infra2:=false
```

My guess is I was getting the `USB SCP overlfow` error because too much data was being transferred over USB 2. By disabling infrared I think I took some of the pressure off so now no overflow :man_shrugging:

**Comment by jdwolk** [comment]
bump

Still seeing the same thing when I try running higher resolutions and framerates on Odroid XU4 over USB3

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@jdwolk Could you please provide more details about the higher resolution and FPS you tried? As you're using USB2, the bandwidth is limited which compared with USB3. If possible, you can have a try with USB3 for higher resolution and FPS. Thanks!

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@jdwolk Any update from your side? Looking forward to your reply. Thanks!

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@jdwolk Any other questions about this ticket?

**Comment by matriculus** [comment]
I saw a similar problem when using t265. How can I solve for that?

**Comment by chenbo1173** [comment]
I have the same problem

**Comment by chenbo1173** [comment]
![Screenshot from 2019-06-16 18-11-00](https://user-images.githubusercontent.com/23693357/59562023-38769100-9062-11e9-84e9-dc97c827b741.png)
![Screenshot from 2019-06-16 18-11-08](https://user-images.githubusercontent.com/23693357/59562027-3dd3db80-9062-11e9-8d39-29b68c759ccc.png)
please help me with the picture problem .thank you

**Comment by chenbo1173** [comment]
Hardware Notification:USB SCP overflow,1.56068e+12,Error,Hardware Error

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@chenbo1173 Did you also see this issue Raspberry Pi 3? If so, then as told in previous comment, the bandwidth of USB2 is limited which compared with USB3. The default launch files enable depth/IR1/IR2/RGB streamings which is very stress for USB2 connection case. Please disable some streaming to try again and share your result. Thanks!

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@chenbo1173 Any other questions about this ticket? If no, will close this accordingly.

**Comment by MarcoDotIO** [comment]
I'm having the same issue, and it prevents me from using the AR_Marker utility properly.

**Comment by QuarTerll** [comment]
same question and wait for a answer @RealSenseCustomerSupport

**Comment by andresgalaviz** [comment]
I'm having the same issue on a USB3 port, any resolution?

**Comment by patrickw135** [comment]
Same issues running on Rpi 4 on USB 3 (!!!) connector:

`[WARN] [1613385028.678995219] [RealSenseCameraNode]: Hardware Notification:USB SCP overflow,1.61339e+12,Error,Hardware Error`

when running:  
`ros2 launch realsense2_camera rs_launch.py enable_pointcloud:=true device_type:=d435`

after installing [Foxy Version](https://github.com/IntelRealSense/realsense-ros/tree/foxy#step-2-install-librealsense2) but replacing Step 2 with [this installation](https://github.com/IntelRealSense/librealsense/blob/master/doc/libuvc_installation.md).

**Comment by RealSenseSupport** [comment]
@QuarTerll @MarcoDotIO @AndresGalaviz @patrickw135 Please type "lsusb -t" to check USB connection is really recognized as USB3. Sometimes the connection will be recognized as USB2 if you use USB2 cable.

**Comment by huangwen0719** [comment]
I have the same issue,I have modify and rebuild the code.  when this occur, do the hardware reset, this problem can be fixed.

**FYI**: I use the usb2.1;

**Comment by huangwen0719** [comment]
see this link https://github.com/huangwen0907/realsense/commit/dc1ab20aeae8a72f77bf24e164ca93e1c0fb8a3a

**Comment by mvoelk** [comment]
I had similar issues, after hardware reset and firmware update via realsense-viewer, the errors are gone.
