### ISSUE TITLE
Question about the data of  /camera/depth_registered/points

### ISSUE THREAD

**Issue by QiuYilin** [realsenseai/realsense-ros#670]
| Required Info                         |                                                                |
|---------------------------------|------------------------------------------- |
| Camera Model                       |  SR300 | 
| Operating System & Version |   Linux Ubuntu 16.04  | 
| Kernel Version (Linux Only)    |  4.15.0  | 
| Platform                                 | PC  |
| SDK Version                            | 2.19.1 | 
| ros package version                           |  2.2.0 | 

I subscribed the topic "/camera/depth_registered/points" .
pcl::PointCloud<pcl::PointXYZ> point_pcl;
pcl::fromROSMsg(*point_cloud_msg, point_pcl);
  std::cout << "x  = " << point_pcl.at(u,v).x << std::endl;
  std::cout << "y  = " << point_pcl.at(u,v).y << std::endl;
  std::cout << "z  = " << point_pcl.at(u,v).z << std::endl;

 I don't know the unit of the x y z. I put the target almost in the center but it shows x is 0.10 y is 0.13 . if I multiply z by 0.1 ，the data is smaller than the right distance by about 5cm.  (15cm when 10cm)I have updated my ros package and lib to the latest. Is there a correct  tool or have I used wrong method?   Is the frame right?

**Comment by doronhi** [comment]
There is an issue with the scale for SR300. You can see the progress in [PR#605](https://github.com/intel-ros/realsense/pull/605)
I'm not sure yet if it implies to the pointcloud but I think you should multiply by 0.125.
Also, 10 cm is very close to the lower limit of the camera. I suggest you make your testings at around 30-50 (cm) if possible.

**Comment by QiuYilin** [comment]
> There is an issue with the scale for SR300. You can see the progress in [PR#605](https://github.com/intel-ros/realsense/pull/605)
> I'm not sure yet if it implies to the pointcloud but I think you should multiply by 0.125.
> Also, 10 cm is very close to the lower limit of the camera. I suggest you make your testings at around 30-50 (cm) if possible.

And what's the scale of x and y.   I put the target almost in the center but it shows 0.10 0.13 . How can I confirm the scale by myself ?
