### ISSUE TITLE
D435 Auto exposure not adjusting when environment changes

### ISSUE THREAD

**Issue by thanujadax** [realsenseai/realsense-ros#672]
We have observed some failures of auto exposure  (release 2.2.0 librealsense 2.18.1) that seems to happen when we change the environment dynamically (e.g. going from indoors to outdoors). Basically it is adjusting the exposure during startup and then gets stuck with the wrong exposure. 
Unchecking and re-checking the dynamic reconfigure didn't work most of the time, but restarting helped. Sometimes changing to manual exposure values and then back to automatic mode also helped.
Any ideas how to fix this?

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@thanujadax What camera are you using and what's firmware version of the camera? Did you still get the same issue with the latest ROS version 2.2.5?

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@thanujadax Did you still need support for this? Looking forward to your update. Thanks!

**Comment by thanujadax** [comment]
Hi, I didn't encounter this problem afterwards. We can close this. Thanks!

**Comment by thanujadax** [comment]
Hi, I didn't encounter this problem afterwards. We can close this. Thanks!
