### ISSUE TITLE
How to know the scale of pointcloud ?

### ISSUE THREAD

**Issue by QiuYilin** [realsenseai/realsense-ros#677]
Now, I know unit of SR300 cloudpoint coordinate is 0.125. But why? How can I get the unit by myself? Which part of source code contains this? Do I need to do calibration again?

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@QiuYilin Sorry for late response. Are you using RealSenseViewer in Linux or rviz in ROS to view the point cloud? Thanks!

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@QiuYilin Could you please update? Thanks!
