### ISSUE TITLE
rgbd_launch not found.

### ISSUE THREAD

**Issue by ShotaAk** [realsenseai/realsense-ros#678]
Could you add a dependency to package.xml ?
Thanks.

**Comment by doronhi** [comment]
rgbd is not mandatory for the package.
It just appear as an example of an outside node using the published depth map. You can get the point cloud by typing`roslaunch realsense2_camera rs_camera.launch filters:=pointcloud`

**Comment by ShotaAk** [comment]
Ok, I understand.
Thanks for the reply : )
