### ISSUE TITLE
Video4Linux backend patching

### ISSUE THREAD

**Issue by jakeju92** [realsenseai/realsense-ros#68]
### System Configuration

Please complete Your Configuration detail below. Refer to the BKC at [Configuration](../realsense_camera/README.md#configuration).

| Version | Your Configuration |
| :-- | :-- |
| Operating System | Ubuntu 16.04 LTS |
| Kernel | 4.4.0-040400-generic |
| Backend |  |
| ROS | kinetic |
| ROS RealSense | Cannot locate [realsense_camera] |
| librealsense | 0.9.1 |
| R200 Firmware | 1.0.72.06 |

When I run the example program "cpp-capture", it only can last for 2 seconds and then it crashes. So, I suspect that maybe my Video4Linux backend isn't installed correctly. Then, I tried several times to reinstall the backend and all attempts seem failed. 

Patching command:
`$ ./scripts/patch-uvcvideo-16.04.simple.sh`
After I reloaded the uvcvideo. I have some errors:

```
$ sudo dmesg | tail -n 50
...
[   27.284877] usb 4-1: Product: Intel RealSense 3D Camera R200
[   27.284878] usb 4-1: Manufacturer: Intel Corp
[   27.284879] usb 4-1: SerialNumber: SN_2421007586
[  146.474076] usb 4-1: usbfs: process 2512 (cpp-capture) did not claim interface 3 before use
[  146.477690] usb 4-1: usbfs: process 2512 (cpp-capture) did not claim interface 5 before use
[  152.267237] usb 4-1: usbfs: process 2514 (cpp-capture) did not claim interface 2 before use
[  152.283057] usb 4-1: usbfs: process 2514 (cpp-capture) did not claim interface 4 before use
[  162.653226] usb 4-1: USB disconnect, device number 2
[  597.419219] usb 4-1: new SuperSpeed USB device number 3 using xhci_hcd
[  597.437910] usb 4-1: New USB device found, idVendor=8086, idProduct=0a80
[  597.437916] usb 4-1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[  597.437920] usb 4-1: Product: Intel RealSense 3D Camera R200
[  597.437923] usb 4-1: Manufacturer: Intel Corp
[  597.437926] usb 4-1: SerialNumber: SN_2421007586
```

I have reported this issue to IntalRealsense community. However, 5 days passed and nobody reply me. Could you please help me to solve this issue? Thanks!

**Comment by ghindman** [comment]
Hi @jb892 filing the issue at librealsense is the right place to resolve this.  We have not encountered this issue on the ROS side, and I would recommend you review the installation docs at librealsense here: https://github.com/IntelRealSense/librealsense/blob/master/doc/installation.md
