### ISSUE TITLE
T265 TF is incorrect

### ISSUE THREAD

**Issue by ibaranov-cp** [realsenseai/realsense-ros#687]
TF values for T265 are incorrect, they have the left and right frames exactly co-located, and camera link to optical frame is backwards.

**Comment by doronhi** [comment]
T265 has different coordinate system then the D400 series.
You can compare 
D400: 
![D400](https://github.com/IntelRealSense/librealsense/blob/master/doc/img/LRS_CS_axis_base.png?raw=true) 
T265:
![T265](https://github.com/IntelRealSense/librealsense/blob/master/doc/img/T265_orientation_axis.png?raw=true)

**Comment by ibaranov-cp** [comment]
Yep, understood. However the camera frames for left and right should still not be identical.

**Comment by doronhi** [comment]
That is correct. The extrinsics are not available yet by the device. The TF values will be fixed automatically, as soon as the firmware is fixed.

**Comment by schmidtp1** [comment]
This had been fixed. What can be seen here are the two fisheye optical frames together with the T265 body frame (in the center).
![t265_frames2_rviz_screenshot_2019_04_25-11_19_55](https://user-images.githubusercontent.com/28366639/56758935-9ebef180-674c-11e9-8543-08467249455d.png)
Thanks for filing the issue, @ibaranov-cp!

**Comment by ibaranov-cp** [comment]
Great, thanks!

**Comment by SainaRez** [comment]
@doronhi @schmidtp1 What confuses me is that if we treat the camera_pose_frame diagram in rviz the same as the one in the image, the camera's align on the y axis in rviz while in the image they align on the x axis. 
Could you please provide a diagram with the camera and the imu_frame fisheye frame and body frame similar to the one below from vins-fusion:
![image](https://user-images.githubusercontent.com/22860616/59539478-6d9cab00-8ecb-11e9-8c43-a0927c672c55.png)

**Comment by schmidtp1** [comment]
> @doronhi @schmidtp1 What confuses me is that if we treat the camera_pose_frame diagram in rviz the same as the one in the image, the camera's align on the y axis in rviz while in the image they align on the x axis. Could you please provide a diagram with the camera and the imu_frame fisheye frame and body frame similar to the one below from vins-fusion: ![image](https://user-images.githubusercontent.com/22860616/59539478-6d9cab00-8ecb-11e9-8c43-a0927c672c55.png)

sorry, i just saw this again now... i think the confusion comes from the different reference/body frames used in ROS/rviz and T265/librealsense. T265 uses a coordinate system as depicted in the first diagram ("VR coordinates") with y pointing up, z aligned with the optical axis and x with the baseline of the cameras, that is exposed by librealsense. Here in the ROS wrapper there is a transformation that rotates the frame to follow ROS/robotics convention with z pointing up etc. as can be seen in the screenshot from rviz. hope this helps.
