### ISSUE TITLE
DDynamic Reconfigure conflicting versions

### ISSUE THREAD

**Issue by v-lopez** [realsenseai/realsense-ros#689]
The version of ddynamic_reconfigure used in this project is based on this repository: https://github.com/awesomebytes/ddynamic_reconfigure

Unfortunately, that repository's code is a fork from: https://github.com/pal-robotics/ddynamic_reconfigure

But the author, license and maintainers were removed, we have requested a fix for this here: https://github.com/awesomebytes/ddynamic_reconfigure/issues/5

Also, the whole API has changed, but the name hasn't, so now the derived package is totally incompatible with the original, but has the same name.

We are releasing the original ddynamic_reconfigure on the ROS build farm for our users, and I'm afraid this may conflict with the users of this repository.

We offer to extend our package to be able to be used as a replacement here, and can contribute to fixing #620 and #609 .

Otherwise I guess that the derived package's name should be changed. 

I'd like to hear your opinion on this, before we start working on extending our API and migrating your code.

**Comment by doronhi** [comment]
@v-lopez 
The reason the realsense repository has a copy of ddynamic_reconfigure in it was the difficulties and annoyance for users with submodules.
If you manage to release your package as a debian package it will be best.
Otherwise, assuming it's possible, I will happily sync the realsense copy with yours as soon as yours is ready.

**Comment by v-lopez** [comment]
I'm in the process of releasing the current version right now, are you targeting kinetic and melodic? Any other distro?

We'll make the necessary changes to use our version of ddynamic_reconfigure and test it with the realsense we have in the office, which is how we found out about this conflict.

**Comment by doronhi** [comment]
Officially we only support kinetic so it's good.
If, by the end of your tests, you could issue a PR it will be great.
Otherwise, let me know and I'll do the sync as soon as possible.

**Comment by v-lopez** [comment]
https://github.com/intel-ros/realsense/pull/693

**Comment by veimox** [comment]
Hi! What is the argument now to keep a semi-fork of `ddynamic_reconfigure` in this repo? Could we consider removing it?

**Comment by doronhi** [comment]
No argument. It will be removed as soon as possible.

**Comment by patelmiteshn** [comment]
Has this been fixed if not what a way around to solve this problem

**Comment by doronhi** [comment]
> Has this been fixed if not what a way around to solve this problem

The latest development branch of realsense2_camera has the ddynamic_reconfigure library removed already. What problem do you need to work around?

**Comment by patelmiteshn** [comment]
Hi doronhi,

The realsense2_camera still has ddynamic_reconfigure referenced in thee CMakeLists.txt.

https://github.com/IntelRealSense/realsense-ros/blob/development/realsense2_camera/CMakeLists.txt#L18

Edit: It looks like this is the correct version to use.  Just clone the directory in the catkin workspace.

https://github.com/pal-robotics/ddynamic_reconfigure

**Comment by doronhi** [comment]
Hi @patelmiteshn ,
realsense2_camera depends on ddynamic_reconfigure. Therefor it appears in it's CMakelists.txt file.
Is this ok? Can we close the issue?

**Comment by v-lopez** [comment]
Yeah, I think so.
