### ISSUE TITLE
T265 stops to send pose data

### ISSUE THREAD

**Issue by JozefRSTU** [realsenseai/realsense-ros#695]
When start realsense node with rs_t265.launch file I am able to view pose data using rostopic echo, T265 is tracking movement but after some times, when T265 is in rest with no movement, rostopic is receiving only "nan" instead of numbers in translation vector and orientation quaternion. I am not sure what exactly is the condition to put camera into this state, but it falls into this state every time I try. Intel realsense node is still publishing pose topic at rate approx. 200Hz but no real data available ("nan"). To recovery from this state I have to physically switch off and on again the T265 into USB port. As I am new in using of this device I am not sure what should I check for better description of this issue but hope someone can point me in right direction. Behavior of tjis issue is same on my laptop running Ubuntu 16.04 with patched (realsenselib related patch) kernel and on Jetson TX2 (Ubuntu 16.04) without kernel patch. ROS version is kinetic.

**Comment by lcluz** [comment]
Hi,
This is happening to me. But I don't understand if there is a solution for it or what's the cause. I am using librealsense 2.25 and realsense-ros 2.2.8

**Comment by manomitbal** [comment]
@JozefRSTU  Were you able to find a solution to this problem?

**Comment by neilyoung** [comment]
Having the same issue. Runs for an hour, then stop. No indication, no error :(
