### ISSUE TITLE
D435 roslaunch error:Frame metadata isn't available!

### ISSUE THREAD

**Issue by carol007** [realsenseai/realsense-ros#699]
Hi,friends!

**Environments**
Device: Dell xps15
OS version: Ubuntu  16.04 lts
Ubuntu kernel: 4.15.0-46-generic
Camera: D435 
Firmware: 5.11.4 (latest development release version)
librealsense version: SDK2.0 
Build 2.19.1
ROS realsense version: 2.2.1
ROS version: kinetic

**My issue:**
  I use USB3.0 and can run realsense-viewer successfully.
  But when I enter code `roslaunch realsense2_camera rs_camera.launch`  ,I get warn  [ WARN] [1553594396.682607742]: Frame metadata isn't available! (frame_timestamp_domain = RS2_TIMESTAMP_DOMAIN_SYSTEM_TIME).   Moreover,after I open the rviz, nothing could't been shown in the relative windows. I tried to Click "Add" and "By topic" , pointcloud2 cannot be found. The situation is same with image stream and depth stream. All the things don't work in Rviz.  Can any friend help me?

**Details:**
roslaunch realsense2_camera rs_camera.launch
... logging to /home/carol/.ros/log/e8295c7c-4fad-11e9-a9fd-9cb6d0b9f3a7/roslaunch-awesome-5027.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://awesome:42407/

SUMMARY
========

PARAMETERS
 * /camera/realsense2_camera/accel_fps: 250
 * /camera/realsense2_camera/accel_frame_id: camera_accel_frame
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: False
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/clip_distance: -2.0
 * /camera/realsense2_camera/color_fps: 30
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: 480
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: 640
 * /camera/realsense2_camera/depth_fps: 30
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: 480
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: 640
 * /camera/realsense2_camera/enable_accel: True
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye1: True
 * /camera/realsense2_camera/enable_fisheye2: True
 * /camera/realsense2_camera/enable_fisheye: True
 * /camera/realsense2_camera/enable_gyro: True
 * /camera/realsense2_camera/enable_infra1: True
 * /camera/realsense2_camera/enable_infra2: True
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_sync: False
 * /camera/realsense2_camera/filters: 
 * /camera/realsense2_camera/fisheye1_frame_id: camera_fisheye1_f...
 * /camera/realsense2_camera/fisheye1_optical_frame_id: camera_fisheye1_o...
 * /camera/realsense2_camera/fisheye2_frame_id: camera_fisheye2_f...
 * /camera/realsense2_camera/fisheye2_optical_frame_id: camera_fisheye2_o...
 * /camera/realsense2_camera/fisheye_fps: 30
 * /camera/realsense2_camera/fisheye_frame_id: camera_fisheye_frame
 * /camera/realsense2_camera/fisheye_height: 480
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: 640
 * /camera/realsense2_camera/gyro_fps: 400
 * /camera/realsense2_camera/gyro_frame_id: camera_gyro_frame
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra_fps: 30
 * /camera/realsense2_camera/infra_height: 480
 * /camera/realsense2_camera/infra_width: 640
 * /camera/realsense2_camera/initial_reset: False
 * /camera/realsense2_camera/json_file_path: 
 * /camera/realsense2_camera/linear_accel_cov: 0.01
 * /camera/realsense2_camera/odom_frame_id: camera_odom_frame
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/pose_frame_id: camera_pose_frame
 * /camera/realsense2_camera/pose_optical_frame_id: camera_pose_optic...
 * /camera/realsense2_camera/rosbag_filename: 
 * /camera/realsense2_camera/serial_no: 
 * /camera/realsense2_camera/unite_imu_method: 
 * /rosdistro: kinetic
 * /rosversion: 1.12.14

NODES
  /camera/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)

auto-starting new master
process[master]: started with pid [5037]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to e8295c7c-4fad-11e9-a9fd-9cb6d0b9f3a7
process[rosout-1]: started with pid [5050]
started core service [/rosout]
process[camera/realsense2_camera_manager-2]: started with pid [5067]
process[camera/realsense2_camera-3]: started with pid [5068]
[ INFO] [1553594396.065356641]: Initializing nodelet with 12 worker threads.
[ INFO] [1553594396.116068272]: RealSense ROS v2.2.1
[ INFO] [1553594396.116093221]: Running with LibRealSense v2.19.1
[ INFO] [1553594396.330192983]: getParameters...
[ INFO] [1553594396.424800233]: setupDevice...
[ INFO] [1553594396.424820825]: JSON file is not provided
[ INFO] [1553594396.424832471]: ROS Node Namespace: camera
[ INFO] [1553594396.424851473]: Device Name: Intel RealSense D435
[ INFO] [1553594396.424860754]: Device Serial No: 745112070286
[ INFO] [1553594396.424869161]: Device FW version: 05.11.01.100
[ INFO] [1553594396.424877838]: Device Product ID: 0x0B07
[ INFO] [1553594396.424885012]: Enable PointCloud: Off
[ INFO] [1553594396.424893911]: Align Depth: Off
[ INFO] [1553594396.424902181]: Sync Mode: Off
[ INFO] [1553594396.424968420]: Device Sensors: 
[ INFO] [1553594396.424998274]: Stereo Module was found.
[ INFO] [1553594396.425012069]: RGB Camera was found.
[ INFO] [1553594396.425032975]: (Fisheye, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1553594396.425043805]: (Fisheye, 1) sensor isn't supported by current device! -- Skipping...
[ INFO] [1553594396.425051837]: (Fisheye, 2) sensor isn't supported by current device! -- Skipping...
[ INFO] [1553594396.425059896]: (Gyro, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1553594396.425067597]: (Accel, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1553594396.425075487]: (Pose, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1553594396.425241964]: setupPublishers...
[ INFO] [1553594396.427157354]: Expected frequency for depth = 30.00000
[ INFO] [1553594396.447328987]: Expected frequency for infra1 = 30.00000
[ INFO] [1553594396.464790763]: Expected frequency for infra2 = 30.00000
[ INFO] [1553594396.482403450]: Expected frequency for color = 30.00000
[ INFO] [1553594396.501577739]: setupStreams...
 26/03 05:59:56,503 WARNING [140077112743808] (sensor.cpp:366) Unregistered Media formats : [ UYVY ]; Supported: [ ]
[ INFO] [1553594396.505088969]: depth stream is enabled - width: 640, height: 480, fps: 30
[ INFO] [1553594396.505223817]: infra1 stream is enabled - width: 640, height: 480, fps: 30
[ INFO] [1553594396.505342068]: infra2 stream is enabled - width: 640, height: 480, fps: 30
 26/03 05:59:56,506 WARNING [140077112743808] (backend-v4l2.cpp:1248) Pixel format 36315752-1a66-a242-9065-d01814a likely requires patch for fourcc code RW16!
 26/03 05:59:56,507 WARNING [140077112743808] (sensor.cpp:366) Unregistered Media formats : [ RW16 ]; Supported: [ ]
[ INFO] [1553594396.511740402]: color stream is enabled - width: 640, height: 480, fps: 30
[ INFO] [1553594396.512960004]: insert Depth to Stereo Module
[ INFO] [1553594396.512988229]: insert Color to RGB Camera
[ INFO] [1553594396.512999627]: insert Infrared to Stereo Module
[ INFO] [1553594396.513038020]: insert Infrared to Stereo Module
[ INFO] [1553594396.529810826]: num_filters: 0
[ INFO] [1553594396.529849277]: SELECTED BASE:Depth, 0
[ INFO] [1553594396.531031377]: RealSense Node Is Up!
[ INFO] [1553594396.531047843]: Setting Dynamic reconfig parameters.
 26/03 05:59:56,680 WARNING [140076182578944] (ds5-timestamp.cpp:64) UVC metadata payloads not available. Please refer to installation chapter for details.
**[ WARN] [1553594396.682607742]: Frame metadata isn't available! (frame_timestamp_domain = RS2_TIMESTAMP_DOMAIN_SYSTEM_TIME)**
 26/03 05:59:56,696 WARNING [140076323432192] (ds5-timestamp.cpp:64) UVC metadata payloads not available. Please refer to installation chapter for details.
[ INFO] [1553594396.704691789]: Done Setting Dynamic reconfig parameters.
![Screenshot from 2019-03-26 06-07-00](https://user-images.githubusercontent.com/20907787/54988758-81500980-4f8d-11e9-8bda-eda1c6c2d0cc.png)

**Comment by doronhi** [comment]
I'm not sure about the warning. Does it show every time, even when disconnecting and reconnecting the camera?
The problem with the point cloud is that you should specify param. type:
`roslaunch realsense2_camera rs_camera.launch filters:=pointcloud`
You will need to change the `fixed frame` in RViz to see it.
However, I can't see why you don't get images. Can you add the log after the point you already added?
What can you see when typing: `rostopic hz /camera/color/image_raw` ?

**Comment by carol007** [comment]
@doronhi  Thank you for your reply,Sir.
------------------------------------------------------------------------------------
**Does it show every time, even when disconnecting and reconnecting the camera?**
Ans: Yes,this situation always happen when I dis and reconnect the camera and enter `roslaunch realsense2_camera rs_camera.launch` 
![Screenshot from 2019-03-26 23-27-20](https://user-images.githubusercontent.com/20907787/55048536-e56ede00-501e-11e9-84d1-a6b805af6a76.png)
---------------------------------------------------------------------------------------
**The problem with the point cloud is that you should specify param.**
Ans: Yes. I follow your code ` roslaunch realsense2_camera rs_camera.launch filters:=pointcloud`
this terminal immediately shows that
![Screenshot from 2019-03-26 23-32-35](https://user-images.githubusercontent.com/20907787/55048686-7776e680-501f-11e9-9b03-efed8378767b.png)

then I open a new terminal to enter rviz. Nothing happened as following.

Then I check other closed issues and follow their suggestions to Click "Add" and "By topic", I cannot find the choice "PointCloud2", so I have to randomly choose a image stream or depth stream to test whether it works to show. Unfortunately, NO image received by Rviz...
![Uploading Screenshot from 2019-03-26 23-34-30.png…]()
![Uploading Screenshot from 2019-03-26 23-34-50.png…]()
-------------------------------------------------------------------------------------------
Can you add the log after the point you already added?
Ans: Sorry,cause I am a coding&ROS newcomer.I don't quiet understand how to add log after the point.
-------------------------------------------------------------------------------------------
What can you see when typing: rostopic hz /camera/color/image_raw ?
Ans: When I directly enter your code in the /root or ~/catkin_ws, something wrong. Then I realize I should launch a node with `roslaunch realsense2_camera rs_camera.launch`  then enter `rostopic hz /camera/color/image_raw `, I get some message as followed.
![Screenshot from 2019-03-26 23-46-06](https://user-images.githubusercontent.com/20907787/55049257-dd646d80-5021-11e9-9715-f0094389ff1d.png)
--------------------------------------------------------------------------------------------
Because I don't know how to change the fixed frame shown in RVIZ with red color Font, maybe my operation is wrong to some degree.  Moreover, I guess Rviz essentially doesn't receive my data stream. Is this related to my  environment ? That is too latest..
Firmware: **5.11.4** 
Build **2.19.1**  
ROS realsense version: **2.2.1**

I will try to degrade FW to 5.11.1  and Build 2.19.0 to test. Would you mind recommending me available environment solution?  Thank you!

**Comment by carol007** [comment]
@doronhi  Thank you for your reply,Sir.
-------------------------------------------------
Does it show every time, even when disconnecting and reconnecting the camera?

Ans: Yes,this situation always happen when I dis and reconnect the camera and enter `roslaunch realsense2_camera rs_camera.launch` 

![Screenshot from 2019-03-26 23-27-20](https://user-images.githubusercontent.com/20907787/55050096-52857200-5025-11e9-80c1-92c401b4beff.png)

--------------------------------------------------------------------------------------------------------------------------
The problem with the point cloud is that you should specify param.

Ans: Yes. I follow your code ` roslaunch realsense2_camera rs_camera.launch filters:=pointcloud`
this terminal immediately shows that
![Screenshot from 2019-03-26 23-32-35](https://user-images.githubusercontent.com/20907787/55050113-6d57e680-5025-11e9-9104-7b2150f72088.png)

then I open a new terminal to enter rviz. Nothing happened as following.

![Screenshot from 2019-03-26 23-33-47](https://user-images.githubusercontent.com/20907787/55050124-83fe3d80-5025-11e9-8c21-fc2487641548.png)

Then I check other closed issues and follow their suggestions to Click "Add" and "By topic", I cannot find the choice "PointCloud2", so I have to randomly choose a image stream or depth stream to test whether it works to show. Unfortunately, NO image received by Rviz...

![Screenshot from 2019-03-26 23-34-30](https://user-images.githubusercontent.com/20907787/55050138-94aeb380-5025-11e9-86ca-f6a0bf52f27d.png)

![Screenshot from 2019-03-26 23-34-50](https://user-images.githubusercontent.com/20907787/55050141-9e381b80-5025-11e9-8aac-d561868fcc8c.png)

------------------------------------------------------------------------------------------------------------------
Can you add the log after the point you already added?

Ans: Sorry,cause I am a coding&ROS newcomer.I don't quiet understand how to add log after the point.

---------------------------------------------------------------------------------------------------------------------------------
What can you see when typing: rostopic hz /camera/color/image_raw ?

What can you see when typing: rostopic hz /camera/color/image_raw ?
Ans: When I directly enter your code in the /root or ~/catkin, something wrong. Then I realize I should launch a node with `roslaunch realsense2_camera rs_camera.launch`  then enter `rostopic hz /camera/color/image_raw `, I get some message as followed.

![Screenshot from 2019-03-26 23-46-06](https://user-images.githubusercontent.com/20907787/55050246-0dae0b00-5026-11e9-9908-642a61e1c88e.png)

-----------------------------------------------------------------------------------------------------------------------
Because I don't know how to change the fixed frame shown in RVIZ with red color Font, maybe my operation is wrong to some degree.  Moreover, I guess Rviz essentially doesn't receive my data stream. Is this related to my  environment ? That is too latest..
Firmware: 5.11.4 
Build 2.19.1  
ROS realsense version: 2.2.1

I will try to degrade FW to 5.11.1  and Build 2.19.0 to test. Would you mind recommending me available environment solution?  Thank you!

**Comment by carol007** [comment]
@doronhi    Unfortunately, after I degrade my SDK from 2.19.1 to 2.19.0 to fit the recommended requirements of ROS2.2.1, the camera still cannot open with warning UVC metadata payloads not available and Frame metadata isn't available!

**Comment by doronhi** [comment]
Did you install the kernel patches?
from https://github.com/IntelRealSense/librealsense/blob/master/doc/distribution_linux.md:
```
Verify that the kernel is updated :
modinfo uvcvideo | grep "version:" should include realsense string
```
Try to run:
```
sudo apt-get update
sudo apt-get install librealsense2-dkms
```

**Comment by Jiang1206** [comment]
> 你安装了内核补丁吗？
> 来自https://github.com/IntelRealSense/librealsense/blob/master/doc/distribution_linux.md：
> 
> ```
> Verify that the kernel is updated :
> modinfo uvcvideo | grep "version:" should include realsense string
> ```
> 尝试运行：
> 
> ```
> sudo apt-get update
> sudo apt-get install librealsense2-dkms
> ```

**Comment by Jiang1206** [comment]
I also encountered this problem, I made changes according to your method, but the problem remains. Also, I use the D430 depth module with no color, no point cloud is related to no color. 
When I open rviz and try to add a pointcloud, there is a second error:"[ WARN] [1554379179.581464881]: No stream match for pointcloud chosen texture Process - Color
"

**Comment by doronhi** [comment]
@Jiang1206 , the problem you describe comes from the fact that the default texture is color. You can change it with rqt_reconfigure or by adding the following parameter to the launch command: `pointcloud_texture_stream:=RS2_STREAM_ANY`

**Comment by Jiang1206** [comment]
What do you mean by entering the command at the terminal: "roslaunch realsense2_camera demo_pointcloud.launch pointcloud_texture_stream:=RS2_STREAM_ANY"? But this still has no image in rviz, and it prompts an error: "too many values to unpack
The traceback for the exception was written to the log file”

**Comment by doronhi** [comment]
@carol007 , according to `rostopic hz` the images do arrive so I would check what I see with `rqt_image_view` now. Did you try the kernel patches?
@Jiang1206 , `demo_pointcloud.launch` doesn't include the `pointcloud_texture_stream` option. I meant `roslaunch realsense2_camera rs_camera.launch filters:=pointcloud pointcloud_texture_stream:=RS2_STREAM_ANY`
Also, can you confirm with `rostopic list` and `rostopic hz` that the topics for pointcloud and images are published? 
Which app prompts the error "too many values..."?

**Comment by SuperKuooo** [comment]
I am also experiencing a similar problem. After running
`roslaunch realsense2_camera rs_camera.launch filters:=pointcloud`
This is what I get.
![Screenshot from 2019-08-27 02-04-26](https://user-images.githubusercontent.com/44331169/63757557-23428d80-c86f-11e9-9ac5-7a96e6a8f73e.png)
However, I am getting some images on Rviz. You have to change the fixed frame parameter to camera_link.
![Screenshot from 2019-08-27 02-07-33](https://user-images.githubusercontent.com/44331169/63757885-b67bc300-c86f-11e9-84fb-39d3b79d82cf.png)

Yet, as you can see, the image is nothing close to what the readme describes. The PointCloud does respond to my movement tho. Can you please help? Thank you.

**Comment by Grandzxw** [comment]
> ## @doronhi Thank you for your reply,Sir.
> 
> Does it show every time, even when disconnecting and reconnecting the camera?
> 
> Ans: Yes,this situation always happen when I dis and reconnect the camera and enter `roslaunch realsense2_camera rs_camera.launch`
> 
> ![Screenshot from 2019-03-26 23-27-20](https://user-images.githubusercontent.com/20907787/55050096-52857200-5025-11e9-80c1-92c401b4beff.png)
> 
> The problem with the point cloud is that you should specify param.
> 
> Ans: Yes. I follow your code ` roslaunch realsense2_camera rs_camera.launch filters:=pointcloud`
> this terminal immediately shows that
> ![Screenshot from 2019-03-26 23-32-35](https://user-images.githubusercontent.com/20907787/55050113-6d57e680-5025-11e9-9104-7b2150f72088.png)
> 
> then I open a new terminal to enter rviz. Nothing happened as following.
> 
> ![Screenshot from 2019-03-26 23-33-47](https://user-images.githubusercontent.com/20907787/55050124-83fe3d80-5025-11e9-8c21-fc2487641548.png)
> 
> Then I check other closed issues and follow their suggestions to Click "Add" and "By topic", I cannot find the choice "PointCloud2", so I have to randomly choose a image stream or depth stream to test whether it works to show. Unfortunately, NO image received by Rviz...
> 
> ![Screenshot from 2019-03-26 23-34-30](https://user-images.githubusercontent.com/20907787/55050138-94aeb380-5025-11e9-86ca-f6a0bf52f27d.png)
> 
> ![Screenshot from 2019-03-26 23-34-50](https://user-images.githubusercontent.com/20907787/55050141-9e381b80-5025-11e9-8aac-d561868fcc8c.png)
> 
> Can you add the log after the point you already added?
> 
> Ans: Sorry,cause I am a coding&ROS newcomer.I don't quiet understand how to add log after the point.
> 
> What can you see when typing: rostopic hz /camera/color/image_raw ?
> 
> What can you see when typing: rostopic hz /camera/color/image_raw ?
> Ans: When I directly enter your code in the /root or ~/catkin, something wrong. Then I realize I should launch a node with `roslaunch realsense2_camera rs_camera.launch` then enter `rostopic hz /camera/color/image_raw `, I get some message as followed.
> 
> ![Screenshot from 2019-03-26 23-46-06](https://user-images.githubusercontent.com/20907787/55050246-0dae0b00-5026-11e9-9908-642a61e1c88e.png)
> 
> Because I don't know how to change the fixed frame shown in RVIZ with red color Font, maybe my operation is wrong to some degree. Moreover, I guess Rviz essentially doesn't receive my data stream. Is this related to my environment ? That is too latest..
> Firmware: 5.11.4
> Build 2.19.1
> ROS realsense version: 2.2.1
> 
> I will try to degrade FW to 5.11.1 and Build 2.19.0 to test. Would you mind recommending me available environment solution? Thank you!
Have you done it successfully?

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Is this still reproducible in the latest ROS/librealsense release?
Thank you.

**Comment by lavanya463** [comment]
Hi, 
I have a similar problem when I disconnect and reconnect it solves... But it is really difficult to do it every time manually.
I am using the following command to get a point cloud
`roslaunch realsense2_camera rs_rgbd.launch enable_infra1:=false enable_infra2:=false`

and many times my `rostopic hz /camera/depth_registered/points` produce no new messages.
Can you please help me or provide some path to solve this?
usually this happens after working with the realsense for some time (6-7 hours).

I am using realsense D415.

**Comment by doronhi** [comment]
Sorry for losing track of your issue guys. I do hope you managed after all.
@lavanya463, Do you mean that after 6-7 hours you suddenly get "Frame metadata isn't available"?
In any case, this seems like a different issue.
I think you should open a new issue and describe the problem. 
Also, when you do, it would help if you state what FW you use. What kernel, librealsenses version, machine?
An issue that happens after several hours needs as many details as possible to try to recreate..

**Comment by sbdjyl** [comment]
Hi,friends!
I face the same problem .It cames from  intel nuc  on my UAV .
The onboard computer have intel i7 7567u ,and the ubuntu environments is same as yours.
I got librealsense-2.9.0 or 2.9.1 for my D435i,when i run 

roslaunch realsense2_camera rs_camera.launch

it tells my Frame metadata isn't available! (frame_timestamp_domain = RS2_TIMESTAMP_DOMAIN_SYSTEM_TIME)

Have you done it successfully?Can you help me?
Thanks

**Comment by lavanya463** [comment]
@doronhi Sorry for the late reply. I wasn't able to reproduce the same issue with my new PC. I will let you know here if I face the same issue. Thank you.

@sbdjyl Normally Frame metadata isn't available can be solved by ignoring some outputs of realsense. For example I run " roslaunch realsense2_camera rs_camera.launch enable_infra1:=false enable_infra2:=false etc "
I hope this is helpful.

Thanks
