### ISSUE TITLE
Depth align to RGB plus post-processing 

### ISSUE THREAD

**Issue by JeffLee06** [realsenseai/realsense-ros#707]
Hi,
I am running D435i in ubuntu 16.04 under kinetic ROS, 
Is it possible to run align_depth on RGB and perform post processing on aligned depth map? 
I have tried to open both in launch/rs_camera.launch but doesn't seem to work.

**Comment by jlysnantel** [comment]
Try
```
roslaunch realsense2_camera rs_camera.launch align_depth:=true
```

**Comment by JeffLee06** [comment]
Hi, 
Enabling align_depth:=true works perfectly fine, my question was about opening align_depth and filters:=... together. The filters:= options only work on the depth_raw topic

**Comment by doronhi** [comment]
The`filters:=` option works on the raw depth and the aligning part takes place afterwards.
In other words, the filtered depth image is aligned to produce the aligned depth image.
Is that behavior not working for you? In that case, can you write down the command line you use?

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Hi @JeffLee06,

Any update? Is your issue resolved per @doronhi comment?

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Hi @JeffLee06,

If no further question, will
