### ISSUE TITLE
error of pointcloud after updating to the latest version 

### ISSUE THREAD

**Issue by QiuYilin** [realsenseai/realsense-ros#712]
I am using SR300 and there was something wrong about the scale of pointcloud in the past. But after I update to the newest modified version, all the value of coodinate become nan.

I subscribe the  "camera/depth_registered/points", topic.

```
 ros::Subscriber point_cloud_sub =
      nh.subscribe("camera/depth_registered/points", 1, pointCouldCallback);
```

and deal the msgs like this 

```
int u,v;

void darknetCallback(const darknet_ros_msgs::BoundingBoxes::ConstPtr &msg)

{
  obj_class = msg->bounding_boxes[0].Class;
  u = (msg->bounding_boxes[0].xmin + msg->bounding_boxes[0].xmax) / 2;
  v = (msg->bounding_boxes[0].ymin + msg->bounding_boxes[0].ymax) / 2;
}


void pointCouldCallback( const sensor_msgs::PointCloud2::ConstPtr &point_cloud_msg) {

  pcl::PointCloud<pcl::PointXYZ> point_pcl;
  pcl::fromROSMsg(*point_cloud_msg, point_pcl);

  auto pt = point_pcl.at(u,v);
  camera_x = 0.124987*pt.x;
  camera_y = 0.124987*pt.y;
  camera_z = 0.124987*pt.z;
   if (obj_class == target_obj &&(camera_x >= -1.5 &&camera_x<=1.5))
  {
  std::cout << "x  = " << camera_x << " y = " << camera_y
            << " z = " << camera_z << std::endl;
  }
  obj_class = "none";
}
```
pointcloud is like this in rviz
![QQ截图20190402213048](https://user-images.githubusercontent.com/26407388/55406677-26bb3c80-558f-11e9-813e-a677ecf70ae4.png)

What's the most stable version for SR300 ? I will try it up.

The test result of build 2.2.3. The point cloud is more strange.
![Screenshot from 2019-04-08 10-17-07](https://user-images.githubusercontent.com/26407388/55694624-8c705400-59e7-11e9-8e12-414be805e44b.png)

**Comment by doronhi** [comment]
Its a bug. Thank you for informing me.
I just merged PR#717 to fix it.
I'd appreciate if you checked the latest commit.

**Comment by QiuYilin** [comment]
> Its a bug. Thank you for informing me.
> I just merged PR#717 to fix it.
> I'd appreciate if you checked the latest commit.

In fact, the point cloud  is even more strange. @doronhi

**Comment by doronhi** [comment]
Checked again with latest commit (f548ca5e43229d22c75ac3f994f9e4d85debf4d8) on development branch with librealsense v2.20.0, with `rs_rgbd.launch` and `rs_camera.launch filters:=pointcloud`.
Running SR300, firmware 3.21.0.0.
Point cloud in RViz looks fine.
Where do you see the problem?

**Comment by QiuYilin** [comment]
Sorry,I found that I stll used the released version and missed the commit. @doronhi

**Comment by doronhi** [comment]
Excellent.  Thanks.
