### ISSUE TITLE
Are multiple cameras w/ hardware sync supported?

### ISSUE THREAD

**Issue by jdwolk** [realsenseai/realsense-ros#719]
Hi,

I have multiple cameras working right now via separate `nodelet`s. I see there's an option for `enable_sync` but this seems more like it's related to synchronizing input streams from one camera.

I know that hardware sync, i.e. identical frame capture, is possible because I saw this: https://www.intelrealsense.com/wp-content/uploads/2019/02/Intel_RealSense_Multi-camera_Webinar.pdf

Is this functionality enabled / exposed by `ros-realsense`?

Also: Is there a better place to ask these sorts of questions besides the GH issues? I'd be happy to use such a forum if I knew where to look

Thanks!

**Comment by doronhi** [comment]
Yes, It is.
You can see it using rqt_reconfigure: `camera->stereo_module->inter_cam_sync_mode`

**Comment by jdwolk** [comment]
Great! I'll close this now
