### ISSUE TITLE
color, depth, pointcloud mapping issue

### ISSUE THREAD

**Issue by lucasjinreal** [realsenseai/realsense-ros#720]
I have those topics:

![image](https://user-images.githubusercontent.com/21303438/55769256-a6c33400-5ab2-11e9-8786-49a540e49886.png)

It seems that, the aligned depth does not match color exactly, if I am using color coordinates and that position depth pixel to calculate point cloud point, will the point be accurate?

I need to calculate the point out and mapping back to the point cloud public, does they are the same?

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@jinfagang Sorry for late response! Is it still issue for you with the latest SDK and FW? Looking forward to your update. Thanks!

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@jinfagang Could you please update? Thanks!

**Comment by fafux** [comment]
Hi all, I am also facing the same issue with D415.

I tried to investigate how the alignment is performed in the `realsense-ros` package.
I tried to do manually the alignment with `librealsense`, calling the following functions:
 ```cpp
rs2::pipeline pipe;
rs2::align align_to_color(RS2_STREAM_DEPTH);
[...]
rs2::frameset data = pipe.wait_for_frames();
data = align_to_color.process(data);
 rs2::frame colorFrame = data.get_color_frame();
 rs2::frame depthFrame = data.get_depth_frame();
```
The results of the color_frame looked a little bit better. Can you tell me if those methods are equal? If not, is there an equivalent of the second method in `realsense-ros` ? If yes, why the result looked different?
