### ISSUE TITLE
candidate filters to set in ros launch

### ISSUE THREAD

**Issue by lucasjinreal** [realsenseai/realsense-ros#724]
Hi, I am using aligned depth, but it's still a lot of wrong depth points such as project human body on ground (outside door enviroment), So I am looking for some built in filters which can be set in ros launch files:

```
  <arg name="enable_pointcloud"   default="true"/>
  <arg name="enable_sync"         default="true"/>
  <arg name="align_depth"         default="true"/>

  <arg name="filters"             default=""/>
```

What are those candidate in arg "filters"?

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Hi @jinfagang,

Is the issue resolved? Refer to below:
The following filters have detailed descriptions in : https://github.com/IntelRealSense/librealsense/blob/master/doc/post-processing-filters.md

- `disparity` - convert depth to disparity before applying other filters and back.
- `spatial` - filter the depth image spatially.
- `temporal` - filter the depth image temporally.
- `hole_filling` - apply hole-filling filter.
- `decimation` - reduces depth scene complexity.
