### ISSUE TITLE
How to remove veiling effect created by the edge of a wall

### ISSUE THREAD

**Issue by Patrick-Lascombe** [realsenseai/realsense-ros#735]
Good morning !

I'm using the D435 mounted on a robot for 3D obstacle detection. But when the robot gets close to the edge of a new corridor, there is a veiling effect that creates obstacles points (see pictures below).

Is there an option or some post-processing filter that I missed and that can remove these points ? 

Thanks for your help

![Screenshot from 2019-04-17 15-23-50](https://user-images.githubusercontent.com/44769524/56343780-f8a74080-61bb-11e9-949f-1ff42167666b.png)
![Screenshot from 2019-04-17 15-24-11](https://user-images.githubusercontent.com/44769524/56343781-f8a74080-61bb-11e9-9b82-20fbfba303b7.png)

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@Patrick-Lascombe Sorry for late response. Is this issue still existing for you? Could you please also provide one color image of your testing environment so that we can better understand this issue? Thanks!

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@Patrick-Lascombe Could you please update? Thanks!

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@Patrick-Lascombe  Didn't get response from your side for weeks. Will close the ticket at this point. Please feel free to create another one if you still have questions or issues. Thanks!
