### ISSUE TITLE
How can I get the information about the camera_rgb_optical_frame

### ISSUE THREAD

**Issue by TouchDeeper** [realsenseai/realsense-ros#736]
Hello,

I want to run a program need the topic `camera_rgb_optical_frame`

How can I get the information about the `camera_rgb_optical_frame` from the topic published by realsense.

**Comment by doronhi** [comment]
Are you asking which topic contains the rgb image?
If so, it's `/camera/color/image_raw`

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Hi,

Do you need any further clarifications regarding this topic?

**Comment by TouchDeeper** [comment]
I'm sorry for my late reply.

If I have any further question, I will re-open this issue. Thank you a lot.
