### ISSUE TITLE
Is auto exposure region of interrest (AE ROI) exposed?

### ISSUE THREAD

**Issue by jdwolk** [realsenseai/realsense-ros#741]
Hi,

Is the auto exposure region of interest functionality exposed?

I'm having issues w/ direct sunlight like those described in https://github.com/IntelRealSense/librealsense/issues/2875. There they recommend setting the region of interest so that it won't include the sun. Is this functionality exposed in any way? I don't see it anywhere in the dynamic reconfig params

**Comment by MartyG-RealSense** [comment]
The link below has a Python script for setting the auto-exposure ROI.

https://github.com/IntelRealSense/librealsense/issues/2681#issuecomment-436391721

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@MartyG-RealSense Thanks for the help!
@jdwolk Does the script work for you? Looking forward to your update!

**Comment by doronhi** [comment]
What device are you using? When it is available, like in the D435, the option is exposed in the dynamic reconfigure params:
![image](https://user-images.githubusercontent.com/40540281/67629755-6a56fa00-f883-11e9-97fe-673a3b62f80d.png)

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@jdwolk Any other questions for this? Looking forward to your update. Thanks!

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@jdwolk  Any update from your side? Thanks!

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@jdwolk  If no other questions about this issue, will close it accordingly. Thanks!

**Comment by phufetch** [comment]
@doronhi does the settings (AE ROI) stay on camera after a power cycle ? Is there a way to query this value on the camera ?

Thanks,
-Phu

**Comment by MartyG-RealSense** [comment]
Hi @phufetch  Does the C++ script in the link below help you to query ("get") the auto-exposure ROI, please?

https://github.com/IntelRealSense/librealsense/issues/4363#issuecomment-508405760

An AE ROI "get" script in Python would look like the script in this link:

https://github.com/IntelRealSense/librealsense/issues/2681#issuecomment-436391721

I would expect the ROI to return to default values after a power-cycling.  It also cannot be set via a json configuration file.
