### ISSUE TITLE
What is the difference between camera_color_frame and camera_color_optical_frame

### ISSUE THREAD

**Issue by TouchDeeper** [realsenseai/realsense-ros#743]
Hello

As the title said, what is the difference between camera_color_frame and camera_color_optical_frame?

**Comment by doronhi** [comment]
The coordinate systems are different. 
As stated in the README.md file, in the "About frame ID" section, camera_color_frame is oriented according to a ROS convention (X-forward, Y-left, Z-Up) and camera_color_optical_frame is oriented according to original coordinate system in the device (for D400 series it would be X-right, Y-down, Z-forward).

**Comment by TouchDeeper** [comment]
I see, thank you.
