### ISSUE TITLE
Update the pose of the t265 camera during localisation algorithm

### ISSUE THREAD

**Issue by joekeo** [realsenseai/realsense-ros#751]
Hello, 

is there any way to give the camera a new pose estimate during the operation/startup of the camera?
This could be useful for sensor fusion and to correct possible pose mismatches between the t265 and a lase scan

**Comment by felix-v** [comment]
I agree, this would be very useful

**Comment by schmidtp1** [comment]
HI @joekeo, the T265 estimates its pose/motion relative to its initial pose. To transform to another frame you could just multiply the relative transformation. Does this solve your problem?

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Hi @joekeo

We plan on closing this issue unless there is anything further needed.

Thanks
