### ISSUE TITLE
Dense point cloud publishing clipped points

### ISSUE THREAD

**Issue by marcelinomalmeidan** [realsenseai/realsense-ros#755]
| Required Info                         |                                                                |
|---------------------------------|------------------------------------------- |
| Camera Model                       | D435i | 
| Firmware Version                   | 2.17.1 | 
| Operating System & Version | Linux (Ubuntu 16.04)  | 
| Kernel Version (Linux Only)    | 4.4.38-tegra| 
| Platform                                 | NVIDIA Jetson Tegra  |
| SDK Version                            |  2.0                           | 
| Language                            |  C++ | 
| Segment			|  Robotics | 

Hi, I am using the parameter ```clip_distance``` to clip points too far in the point cloud, the main reason being that I don't want to overburden the network when sending point cloud data types.
I am using the topic ```/camera/depth/color/points/width```, which is supposed to be dense, i.e., it should not publish points excluded from the point cloud. 
However, this is not happening in practice. Whereas many points in the point cloud are not being published in this topic, the clipped ones are still being published (with extremely large values), and can easily be observed in Rviz. 
Has this been fixed in newer versions of the Firmware?

**Comment by doronhi** [comment]
It is a bug. Thanks for pointing it out for me.
I submitted PR: https://github.com/IntelRealSense/realsense-ros/pull/767
I hope it meets your needs.
