### ISSUE TITLE
Unit test fail to build

### ISSUE THREAD

**Issue by mferenduros** [realsenseai/realsense-ros#758]
I'm getting a unit test build error:
test_ddynamic_reconfigure.cpp:407:31: error: ‘format’ was not declared in this scope
int_param.name = (format("param_%d") % i).str();

boost/format.hpp is indeed not included anywhere (I assume at some point it was implicitly included by one of the other boost headers).

**Comment by doronhi** [comment]
ddynamic_reconfigure is already released as a debian package and that will soon replace it's copy in realsense's repo. Checkout out PR https://github.com/IntelRealSense/realsense-ros/pull/693
