### ISSUE TITLE
Partial point cloud data separation target object

### ISSUE THREAD

**Issue by tianjincb** [realsenseai/realsense-ros#765]
Observing the data in rviz, part of the data is separated from the target object itself and cannot be removed. What is the reason? How should I do?
![pointcloub2](https://user-images.githubusercontent.com/50519386/57570014-01dca380-7430-11e9-9940-38195d8ae674.png)
![pointcloub4](https://user-images.githubusercontent.com/50519386/57570020-0ef99280-7430-11e9-88db-80eeaa4041bb.png)

**Comment by tianjincb** [comment]
Use D435

**Comment by doronhi** [comment]
Sorry for the long long delay..
Is this still relevant?
If so, I'll need more clarifications. I don't understand what is the problem I should see in the images.

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@tianjincb Is the issue still existing? If so, could you please clarify the issue details as doronhi requested? Thanks!

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@tianjincb Could you please update if you still need support on this? Thanks!

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@tianjincb Sorry that we didn't get feedback from you for weeks. Will close it at this point. Please feel free to create another one if you still have questions/issues. Thanks!
