### ISSUE TITLE
Realsense T265 power and computation machine

### ISSUE THREAD

**Issue by ArtlyStyles** [realsenseai/realsense-ros#771]
When running T265 with ROS on Nvidia  Jetson TX2, I have two questions I would like to confirm:

1. T265 does not need any additional power supply. Just plug-in the device into a USB port on the host machine (TX2).
2. All SLAM computation is on the T265 device itself. The host machine just run the ROS wrapper. This ROS wrapper will poll the position and image from the T265 device and publish them as ROS message.

Am I correct?

**Comment by doronhi** [comment]
Correct.
