### ISSUE TITLE
warning at using realsense d435

### ISSUE THREAD

**Issue by lucafei** [realsenseai/realsense-ros#785]
hi, i use realsense d435 to recognite object. but when i launch the file rs_camera.launch, the warning happened like foollowing:
[ WARN] [1558952226.177066144]: Hardware Notification:USB SCP overflow,1.55895e+12,Error,Hardware Error

anybody konws what's happened and how to solve this?
thank you in advance

**Comment by doronhi** [comment]
see discussion here: #669 
The error message usually reflects overload on the system and dropped frames as a consequence.

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Hi @lucafei,

If no additional question, will close this.
