### ISSUE TITLE
Depth and Pointcloud using T265

### ISSUE THREAD

**Issue by mzahana** [realsenseai/realsense-ros#788]
It would be nice if the following can be wrapped into a ROS node to provide depth and pointcloud from T265 as ROS messages.
https://github.com/IntelRealSense/librealsense/blob/master/wrappers/python/examples/t265_stereo.py

Related issue:
https://github.com/IntelRealSense/librealsense/issues/3964

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Hi @mzahana

Thanks for the feedback.

**Comment by mzahana** [comment]
You are welcome.

**Comment by rjam92** [comment]
Hello, was this accomplished?

**Comment by rjam92** [comment]
Hello, 
Was this accomplished?

**Comment by mzahana** [comment]
@rjam92 I didn't follow up on this for quite sometime. I am not sure what the state is. I believe, support will likely not be maintained for T265.

**Comment by whyscience** [comment]
https://github.com/IntelRealSense/librealsense/blob/v2.53.1/wrappers/python/examples/t265_stereo.py
