### ISSUE TITLE
melodic build broken

### ISSUE THREAD

**Issue by peci1** [realsenseai/realsense-ros#790]
@doronhi @v-lopez Guys, commits bf9b16fe45eb60d2d752b76e717615b9fd965472 and cfd5d0c9c40f24fbdb24f7c69ad604031b58605c just broke the build on melodic.

Please, release ddynamic_reconfigure to melodic. Thanks. I know I can build it from source, but this one I think can easily work on melodic and should be also accessible from binary repos.

**Comment by v-lopez** [comment]
Requested the release here:
https://github.com/ros/rosdistro/pull/21380

**Comment by pedropgusmao** [comment]
Please, how should we install this?

**Comment by v-lopez** [comment]
In the meantime you should be able to compile ddynamic_reconfigure yourselves, cloning it from: https://github.com/pal-robotics/ddynamic_reconfigure

The kinetic-devel branch should be ok

**Comment by constructive-realities** [comment]
should we just build this and install it from the user's home, or from within the ros workspace src folder?

**Comment by constructive-realities** [comment]
Confirming valid workaround to add ddynamic_reconfigure inside the workspace, not in the users HOME (FYI)

**Comment by doronhi** [comment]
As the workaround solution is confirmed and we wait for the release of ddynamic_reqonfigure for melodic, I think this issue can be closed.

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Hi @peci1,

Did you have a chance to try the workaround solution? Please let us know if you need any
further help with this matter.

Thank you!

**Comment by peci1** [comment]
Hi, since ddynamic_reconfigure is now properly released, this issue can be closed. It is just needed to clear your catkin workspace when switching from in-repo ddynamic to the released one.
