### ISSUE TITLE
Odometry Configuration

### ISSUE THREAD

**Issue by SainaRez** [realsenseai/realsense-ros#792]
How are we supposed to initialize the values of the calibration file for odometry [(file)](https://github.com/IntelRealSense/librealsense/blob/master/unit-tests/resources/calibration_odometry.json) and what values do we need to use for T, W and noise variance?

**Comment by MartyG-RealSense** [comment]
Have you seen the sample wheel odometry calibration file with in-script notes that was added to the T265 documentation page please?

https://github.com/IntelRealSense/librealsense/blob/master/doc/t265.md#wheel-odometry-calibration-file-format

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Hi @SainaRez

Is there anything further needed on this issue?

Thanks
