### ISSUE TITLE
Can Realsense T265 localise itself in pre-recorded trajectory .rosbag data?

### ISSUE THREAD

**Issue by yuseidesu** [realsenseai/realsense-ros#799]
I am trying to create self localization system of a robot that can track its initial path accurately and robustly through localization.

I have noticed that T265 can save and load its tracking trajectory (https://github.com/IntelRealSense/librealsense/blob/master/doc/img/t265_trajectory_tracker.gif) as .rosbag file.

Is it possible to make T265 load this pre-recorded .rosbag data and carry out localization of itself relative to the pre-recorded trajectory?
![IMG_C565F829CFBF-1](https://user-images.githubusercontent.com/28069874/58811387-af6f5b00-865a-11e9-96b7-c6c24286ae79.jpeg)

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Hi @yuseidesu

The product does have the ability to relocalize although most of the work regarding relocalization has been done in our librealsense repository - https://github.com/IntelRealSense/librealsense
https://github.com/IntelRealSense/librealsense/blob/master/doc/t265.md

Loading .rosbag file isn't something that is possible.  Although our RealSense Viewer can replay the .rosbag file, basically replaying the trajectory that the T265 took when you recorded the .rosbag file.  With regards to relocalization, there is the notion of saving and loading of maps.  But there is work continuing to be done with regards to relocalization and mapping.  Please continue to monitor the librealsense for changes and updates to the SDK package and the features made available.

This has been opened for a while please do let me know if there is anything else needed here.

Thanks
