### ISSUE TITLE
I want to know how to use the Realsense SDK together.

### ISSUE THREAD

**Issue by vusdo** [realsenseai/realsense-ros#801]
Subscription to Depth .. (/ camera / depth / image_rect_raw)
I want to know how to use the Realsense SDK together.

E.g
     cv_bridge :: CvImagePtr cam_image;
    
     try {
         cam_image = cv_bridge :: toCvCopy (msg, enc :: TYPE_16UC1);
     } catch (cv_bridge :: Exception & e) {
         ROS_ERROR ("cv_bridge exception:% s", e.what ());
         return;
     }
cv :: Mat mat_depth = cam_image-> image;
rs2 :: depth_frame df = mat_depth; // Error!!!!!!!!!

I want to subscribe to the ROS Depth topic and run the Librealsense example.
What should I do?

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Hi @vusdo,

Can you please elaborate on the goals that you are trying to achieve in the above provided code and what Librealsense example do you want to run? Regarding subscription to Depth topic,please see
the list of published topics here:

https://github.com/IntelRealSense/realsense-ros#published-topics

Thank you!

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@vusdo,

Do you still need help with this question?
