### ISSUE TITLE
Frame metadata isn't available! (frame_timestamp_domain = RS2_TIMESTAMP_DOMAIN_SYSTEM_TIME)

### ISSUE THREAD

**Issue by pedropgusmao** [realsenseai/realsense-ros#803]
Hello, 
I am trying to run the rs_t265.launch and I get the following warning message:
`Frame metadata isn't available! (frame_timestamp_domain = RS2_TIMESTAMP_DOMAIN_SYSTEM_TIME)`

I already install librealsense2-dkms:
`$ sudo apt install librealsense2-dkms` 
`Reading package lists... Done
Building dependency tree       
Reading state information... Done
librealsense2-dkms is already the newest version (1.3.5-0ubuntu1).
0 to upgrade, 0 to newly install, 0 to remove and 0 not to upgrade.
`
I have checked that uvcvideo realsense string appears
`modinfo uvcvideo | grep version`
`version:        1.1.2.realsense-1.3.5
srcversion:     3286F64D5B1431E64E8C37C
`
I am using version 2.22 of librealsense from the Ubuntu repository  18.04

**Comment by doronhi** [comment]
At this point metadata attributes are not exposed by librealsense and not used by it.
You can ignore the message.
