### ISSUE TITLE
Any realsense-ros branch for ROS-kinetic?

### ISSUE THREAD

**Issue by HappySamuel** [realsenseai/realsense-ros#813]
Hi

I see a lot of branch, but i couldn't find a branch specifically for ROS-kinetic. Is there any release branch for kinetic?

Best,
Samuel

**Comment by doronhi** [comment]
The main branch is for kinetic. There is no specific branch for anything else yet.

**Comment by HappySamuel** [comment]
Hi @doronhi 

The branch "development" is for ROS-kinetic, is this what you mean?

Best,
Samuel

**Comment by doronhi** [comment]
That's what I mean.
You can either pull from there or from the latest release.

**Comment by HappySamuel** [comment]
Hi @doronhi 

Thank your for the information.

Best,
Samuel

**Comment by HappySamuel** [comment]
Hi @doronhi 

I just tried the development branch and i got the error as shown as below when running it.

![Screenshot from 2019-06-12 16-17-12](https://user-images.githubusercontent.com/18137963/59334648-8c653b00-8d2d-11e9-9785-bf993852fd35.png)

Is there a way to solve it?

Best,
Samuel

**Comment by doronhi** [comment]
Its a recurring issue in librealsense (search in [librealsense issues](https://github.com/IntelRealSense/librealsense/issues))
The recommended action is to disconnect and reconnect the camera or to run the realsense2_camera node with flag `--initial_reset:=true`

**Comment by HappySamuel** [comment]
Hi @doronhi 

I tried both your suggestions, but i still got the same error as above. Does librealsense currently has a solution for this?

Best,
Samuel

**Comment by doronhi** [comment]
What happens when you use realsense-viewer?

**Comment by HappySamuel** [comment]
Hi @doronhi 

This is the screenshot of using realsense-viewer.
![Screenshot from 2019-06-19 14-24-21](https://user-images.githubusercontent.com/18137963/59741606-081b3680-929e-11e9-8a02-80a646503b28.png)

Best,
Samuel

**Comment by HappySamuel** [comment]
Hi @doronhi 

A quick update, after i upgrade the d435 firmware, the issue above gone. Now i can view it in both realsense viewer and RVIZ. I am following the below upgrade instruction from this website:
https://www.intel.com/content/dam/support/us/en/documents/emerging-technologies/intel-realsense-technology/Linux-RealSense-D400-DFU-Guide.pdf

Best,
Samuel
