### ISSUE TITLE
How to use disparity filter twice to post process the depth image?

### ISSUE THREAD

**Issue by zinan93** [realsenseai/realsense-ros#826]
Hi, I know that filters can be specified in the launch file and that the parameters such as decimation scale can be set using dynamic reconfigure. But how do I convert the depth frame to disparity domain, do some temporal filtering, convert it back and then apply hole_filling? I tried the the following change in the rs_camera.launch file:

>   arg name="filters"               default="decimation,disparity,spatial,temporal,disparity,hole_filling"

and got the following result:
![image](https://user-images.githubusercontent.com/29303861/60036425-80736480-96af-11e9-9e92-0c9511996851.png)

it seems like the order of the sequence is not right, and only one disparity filter appeared.

**Comment by doronhi** [comment]
Current filters interface is not as flexible as using the raw librealsense2 functionality.
Setting filter "disparity" encapsulate the other filters inside a disparity section, no matter how many times you specify disparity, it only appears once.
Decimation filter will be added only once and at the beginning of the filters queue.
You can check the code of the function [setupFilters](https://github.com/IntelRealSense/realsense-ros/blob/de1649a04ff7f96b549773fc709b3f8b2a81d397/realsense2_camera/src/base_realsense_node.cpp#L874) for a better understanding of the current situation and its limitations.

**Comment by zinan93** [comment]
Ok I see, thank you. So the disparity filter is added to the beginning and end of the _filters vector after other filters has been pushed, then the decimation goes to the very beginning. Meaning the hole_filling filter will be applied in the disparity domain then.
