### ISSUE TITLE
Realsense D435 and D435i detected with lower firmware but not working

### ISSUE THREAD

**Issue by AnthonyKyung11** [realsenseai/realsense-ros#835]
Hi, I didn't see any other issue with the same problem I'm having so I'm making one.
I'm using librealsense2 , build 2.22.0  in ubuntu 16.04 in the Intel Aero, with realsense-ros  2.2.6.
The problem I have is with the realsense cameras D435 and D435i whit firmware 5.10.3 to 5.11.6.250.
If I connect the cameras (individually) with the Firmware 5.11.6.250 the D435i does not gets recognized with rs-enumerate-devices and the D435 gets recognized but it gives me the following error when running roslaunch realsense2_camera rs_aligned_depth.launch:

SUMMARY
========

PARAMETERS
 * /camera/realsense2_camera/accel_fps: 250
 * /camera/realsense2_camera/accel_frame_id: camera_accel_frame
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: True
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/allow_no_texture_points: False
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/calib_odom_file: 
 * /camera/realsense2_camera/clip_distance: -1.0
 * /camera/realsense2_camera/color_fps: 30
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: 480
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: 640
 * /camera/realsense2_camera/depth_fps: 30
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: 480
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: 640
 * /camera/realsense2_camera/enable_accel: True
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye1: True
 * /camera/realsense2_camera/enable_fisheye2: True
 * /camera/realsense2_camera/enable_fisheye: True
 * /camera/realsense2_camera/enable_gyro: True
 * /camera/realsense2_camera/enable_infra1: True
 * /camera/realsense2_camera/enable_infra2: True
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_sync: True
 * /camera/realsense2_camera/filters: 
 * /camera/realsense2_camera/fisheye1_frame_id: camera_fisheye1_f...
 * /camera/realsense2_camera/fisheye1_optical_frame_id: camera_fisheye1_o...
 * /camera/realsense2_camera/fisheye2_frame_id: camera_fisheye2_f...
 * /camera/realsense2_camera/fisheye2_optical_frame_id: camera_fisheye2_o...
 * /camera/realsense2_camera/fisheye_fps: 30
 * /camera/realsense2_camera/fisheye_frame_id: camera_fisheye_frame
 * /camera/realsense2_camera/fisheye_height: 480
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: 640
 * /camera/realsense2_camera/gyro_fps: 400
 * /camera/realsense2_camera/gyro_frame_id: camera_gyro_frame
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/imu_optical_frame_id: camera_imu_optica...
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra_fps: 30
 * /camera/realsense2_camera/infra_height: 480
 * /camera/realsense2_camera/infra_width: 640
 * /camera/realsense2_camera/initial_reset: False
 * /camera/realsense2_camera/json_file_path: /home/aero/sandbo...
 * /camera/realsense2_camera/linear_accel_cov: 0.01
 * /camera/realsense2_camera/odom_frame_id: camera_odom_frame
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/pose_frame_id: camera_pose_frame
 * /camera/realsense2_camera/pose_optical_frame_id: camera_pose_optic...
 * /camera/realsense2_camera/publish_odom_tf: True
 * /camera/realsense2_camera/rosbag_filename: 
 * /camera/realsense2_camera/serial_no: 
 * /camera/realsense2_camera/topic_odom_in: camera/odom_in
 * /camera/realsense2_camera/unite_imu_method: none
 * /rosdistro: kinetic
 * /rosversion: 1.12.7

NODES
  /camera/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)

auto-starting new master
[master]: started with pid [1118]
ROS_MASTER_URI=http://192.168.7.125:11311/
 /run_id to cd5efbda-9d1f-11e9-99e1-00c2c6d30b21
[rosout-1]: started with pid [1133]
started core service [/rosout]
[camera/realsense2_camera_manager-2]: started with pid [1150]
[camera/realsense2_camera-3]: started with pid [1151]

[ INFO] [1562109554.099123862]: Initializing nodelet with 4 worker threads.
[ INFO] [1562109554.261802048]: RealSense ROS v2.2.6
[ INFO] [1562109554.261869751]: Running with LibRealSense v2.22.0
[ INFO] [1562109554.713957843]: getParameters...
[ INFO] [1562109555.340119557]: setupDevice...
 **ERROR [140256834295552] (types.h:243) get_xu(...). xioctl(UVCIOC_CTRL_QUERY) failed Last Error: No such file or directory**

terminate called after throwing an instance of 'rs2::backend_error'
  what():  get_xu(...). xioctl(UVCIOC_CTRL_QUERY) failed Last Error: No such file or directory
[camera/realsense2_camera_manager-2] process has died [pid 1150, exit code -6, cmd /opt/ros/kinetic/lib/nodelet/nodelet manager __name:=realsense2_camera_manager __log:=/home/aero/.ros/log/cd5efbda-9d1f-11e9-99e1-00c2c6d30b21/camera-realsense2_camera_manager-2.log].
log file: /home/aero/.ros/log/cd5efbda-9d1f-11e9-99e1-00c2c6d30b21/camera-realsense2_camera_manager-2*.log

[camera/realsense2_camera-3] killing on exit
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete

-----------------------------------------------------------------------------------------------------------------------

If I connect the cameras (individually) with the Firmware 5.10.3 both cameras get recognized with rs-enumerate-devices and both give me the following error when running roslaunch realsense2_camera rs_aligned_depth.launch:

SUMMARY
========

PARAMETERS
 * /camera/realsense2_camera/accel_fps: 250
 * /camera/realsense2_camera/accel_frame_id: camera_accel_frame
 * /camera/realsense2_camera/accel_optical_frame_id: camera_accel_opti...
 * /camera/realsense2_camera/align_depth: True
 * /camera/realsense2_camera/aligned_depth_to_color_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_fisheye_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra1_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/aligned_depth_to_infra2_frame_id: camera_aligned_de...
 * /camera/realsense2_camera/allow_no_texture_points: False
 * /camera/realsense2_camera/base_frame_id: camera_link
 * /camera/realsense2_camera/calib_odom_file: 
 * /camera/realsense2_camera/clip_distance: -1.0
 * /camera/realsense2_camera/color_fps: 30
 * /camera/realsense2_camera/color_frame_id: camera_color_frame
 * /camera/realsense2_camera/color_height: 480
 * /camera/realsense2_camera/color_optical_frame_id: camera_color_opti...
 * /camera/realsense2_camera/color_width: 640
 * /camera/realsense2_camera/depth_fps: 30
 * /camera/realsense2_camera/depth_frame_id: camera_depth_frame
 * /camera/realsense2_camera/depth_height: 480
 * /camera/realsense2_camera/depth_optical_frame_id: camera_depth_opti...
 * /camera/realsense2_camera/depth_width: 640
 * /camera/realsense2_camera/enable_accel: True
 * /camera/realsense2_camera/enable_color: True
 * /camera/realsense2_camera/enable_depth: True
 * /camera/realsense2_camera/enable_fisheye1: True
 * /camera/realsense2_camera/enable_fisheye2: True
 * /camera/realsense2_camera/enable_fisheye: True
 * /camera/realsense2_camera/enable_gyro: True
 * /camera/realsense2_camera/enable_infra1: True
 * /camera/realsense2_camera/enable_infra2: True
 * /camera/realsense2_camera/enable_pointcloud: False
 * /camera/realsense2_camera/enable_sync: True
 * /camera/realsense2_camera/filters: 
 * /camera/realsense2_camera/fisheye1_frame_id: camera_fisheye1_f...
 * /camera/realsense2_camera/fisheye1_optical_frame_id: camera_fisheye1_o...
 * /camera/realsense2_camera/fisheye2_frame_id: camera_fisheye2_f...
 * /camera/realsense2_camera/fisheye2_optical_frame_id: camera_fisheye2_o...
 * /camera/realsense2_camera/fisheye_fps: 30
 * /camera/realsense2_camera/fisheye_frame_id: camera_fisheye_frame
 * /camera/realsense2_camera/fisheye_height: 480
 * /camera/realsense2_camera/fisheye_optical_frame_id: camera_fisheye_op...
 * /camera/realsense2_camera/fisheye_width: 640
 * /camera/realsense2_camera/gyro_fps: 400
 * /camera/realsense2_camera/gyro_frame_id: camera_gyro_frame
 * /camera/realsense2_camera/gyro_optical_frame_id: camera_gyro_optic...
 * /camera/realsense2_camera/imu_optical_frame_id: camera_imu_optica...
 * /camera/realsense2_camera/infra1_frame_id: camera_infra1_frame
 * /camera/realsense2_camera/infra1_optical_frame_id: camera_infra1_opt...
 * /camera/realsense2_camera/infra2_frame_id: camera_infra2_frame
 * /camera/realsense2_camera/infra2_optical_frame_id: camera_infra2_opt...
 * /camera/realsense2_camera/infra_fps: 30
 * /camera/realsense2_camera/infra_height: 480
 * /camera/realsense2_camera/infra_width: 640
 * /camera/realsense2_camera/initial_reset: False
 * /camera/realsense2_camera/json_file_path: /home/aero/sandbo...
 * /camera/realsense2_camera/linear_accel_cov: 0.01
 * /camera/realsense2_camera/odom_frame_id: camera_odom_frame
 * /camera/realsense2_camera/pointcloud_texture_index: 0
 * /camera/realsense2_camera/pointcloud_texture_stream: RS2_STREAM_COLOR
 * /camera/realsense2_camera/pose_frame_id: camera_pose_frame
 * /camera/realsense2_camera/pose_optical_frame_id: camera_pose_optic...
 * /camera/realsense2_camera/publish_odom_tf: True
 * /camera/realsense2_camera/rosbag_filename: 
 * /camera/realsense2_camera/serial_no: 
 * /camera/realsense2_camera/topic_odom_in: camera/odom_in
 * /camera/realsense2_camera/unite_imu_method: none
 * /rosdistro: kinetic
 * /rosversion: 1.12.7

NODES
  /camera/
    realsense2_camera (nodelet/nodelet)
    realsense2_camera_manager (nodelet/nodelet)

auto-starting new master
[master]: started with pid [1583]
ROS_MASTER_URI=http://192.168.7.125:11311/
 /run_id to 211b26fe-9d20-11e9-99e1-00c2c6d30b21
[rosout-1]: started with pid [1603]
started core service [/rosout]
[camera/realsense2_camera_manager-2]: started with pid [1635]
[camera/realsense2_camera-3]: started with pid [1644]

[ INFO] [1562109694.466043136]: Initializing nodelet with 4 worker threads.
[ INFO] [1562109694.612773620]: RealSense ROS v2.2.6
[ INFO] [1562109694.612838847]: Running with LibRealSense v2.22.0
[ WARN] [1562109694.971239799]: No RealSense devices were found!
[ INFO] [1562109701.016391395]: getParameters...
[ INFO] [1562109701.688322518]: setupDevice...
[ INFO] [1562109702.032613417]: JSON file is loaded! (/home/aero/sandbox_ws/src/realsense2_camera/launch/presets/MidResHighDensityPreset.json)
[ INFO] [1562109702.032894777]: ROS Node Namespace: camera
[ INFO] [1562109702.033080270]: Device Name: Intel RealSense D435
[ INFO] [1562109702.033250664]: Device Serial No: 727212070269
[ INFO] [1562109702.033476746]: Device FW version: 05.10.03.00
[ INFO] [1562109702.033645652]: Device Product ID: 0x0B07
[ INFO] [1562109702.033775781]: Enable PointCloud: Off
[ INFO] [1562109702.033900198]: Align Depth: On
[ INFO] [1562109702.034020402]: Sync Mode: On
[ INFO] [1562109702.035712134]: Device Sensors: 
[ INFO] [1562109702.037420955]: Stereo Module was found.
[ INFO] [1562109702.037736490]: RGB Camera was found.
[ INFO] [1562109702.037998162]: (Fisheye, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1562109702.038127754]: (Fisheye, 1) sensor isn't supported by current device! -- Skipping...
[ INFO] [1562109702.038254133]: (Fisheye, 2) sensor isn't supported by current device! -- Skipping...
[ INFO] [1562109702.038410526]: (Gyro, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1562109702.038533005]: (Accel, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1562109702.038647459]: (Pose, 0) sensor isn't supported by current device! -- Skipping...
[ INFO] [1562109702.039308593]: setupPublishers...
[ INFO] [1562109702.061850593]: Expected frequency for depth = 30.00000
[ INFO] [1562109702.355267448]: Expected frequency for infra1 = 30.00000
[ INFO] [1562109702.457223931]: Expected frequency for aligned_depth_to_infra1 = 30.00000
[ INFO] [1562109702.558571219]: Expected frequency for infra2 = 30.00000
[ INFO] [1562109702.648828857]: Expected frequency for color = 30.00000
[ INFO] [1562109702.746483033]: Expected frequency for aligned_depth_to_color = 30.00000
[ INFO] [1562109702.874715254]: setupStreams...
 02/07 18:21:42,879 WARNING [140004415559424] (sensor.cpp:365) Unregistered Media formats : [ UYVY ]; Supported: [ GREY UYVY Y12I Y8I  Z16  ]
[ INFO] [1562109702.890027697]: depth stream is enabled - width: 640, height: 480, fps: 30
[ INFO] [1562109702.891296065]: infra1 stream is enabled - width: 640, height: 480, fps: 30
[ INFO] [1562109702.892338050]: infra2 stream is enabled - width: 640, height: 480, fps: 30
 02/07 18:21:42,893 WARNING [140004415559424] (backend-v4l2.cpp:1143) Pixel format 36315752-1a66-a242-9065-d01814a likely requires patch for fourcc code RW16!
 02/07 18:21:42,894 WARNING [140004415559424] (sensor.cpp:365) Unregistered Media formats : [ RW16 ]; Supported: [ RW16 YUYV ]
[ INFO] [1562109702.901786294]: color stream is enabled - width: 640, height: 480, fps: 30
[ INFO] [1562109702.909755251]: insert Depth to Stereo Module
[ INFO] [1562109702.910314545]: insert Color to RGB Camera
[ INFO] [1562109702.910512427]: insert Infrared to Stereo Module
[ INFO] [1562109702.910622806]: insert Infrared to Stereo Module
[ INFO] [1562109702.977695260]: num_filters: 0
[ INFO] [1562109702.977966894]: SELECTED BASE:Depth, 0
[ INFO] [1562109702.987011275]: RealSense Node Is Up!
[ INFO] [1562109702.987143442]: Setting Dynamic reconfig parameters.
 02/07 18:21:43,047 WARNING [140004240119552] (ds5-timestamp.cpp:64) UVC metadata payloads not available. Please refer to installation chapter for details.
[ WARN] [1562109703.056251478]: Frame metadata isn't available! (frame_timestamp_domain = RS2_TIMESTAMP_DOMAIN_SYSTEM_TIME)
 02/07 18:21:43,355 WARNING [140004248512256] (ds5-timestamp.cpp:64) UVC metadata payloads not available. Please refer to installation chapter for details.
[ INFO] [1562109703.846991567]: Done Setting Dynamic reconfig parameters.
**[ WARN] [1562109705.041660208]: Hardware Notification:Depth stream start failure,1.56211e+12,Error,Hardware Error
 02/07 18:21:46,130 ERROR [140003984758528] (types.h:243) xioctl(VIDIOC_DQBUF) failed for fd: 29 Last Error: No such device**
 02/07 18:21:46,131 ERROR [140003984758528] (backend-v4l2.cpp:1230) xioctl(VIDIOC_DQBUF) failed for fd: 29 Last Error: No such device
 02/07 18:21:46,131 ERROR [140004248512256] (types.h:243) xioctl(VIDIOC_DQBUF) failed for fd: 11 Last Error: No such device
 02/07 18:21:46,132 ERROR [140004248512256] (backend-v4l2.cpp:1230) xioctl(VIDIOC_DQBUF) failed for fd: 11 Last Error: No such device
[ WARN] [1562109706.132248031]: Hardware Notification:xioctl(VIDIOC_DQBUF) failed for fd: 29 Last Error: No such device,1.56211e+12,Error,Unknown Error[0m
[ WARN] [1562109706.132839314]: Hardware Notification:xioctl(VIDIOC_DQBUF) failed for fd: 11 Last Error: No such device,1.56211e+12,Error,Unknown Error[0m
 02/07 18:21:46,133 ERROR [140004240119552] (types.h:243) xioctl(VIDIOC_DQBUF) failed for fd: 20 Last Error: No such device
 02/07 18:21:46,133 ERROR [140004240119552] (backend-v4l2.cpp:1230) xioctl(VIDIOC_DQBUF) failed for fd: 20 Last Error: No such device
[ WARN] [1562109706.134186697]: Hardware Notification:xioctl(VIDIOC_DQBUF) failed for fd: 20 Last Error: No such device,1.56211e+12,Error,Unknown Error
 02/07 18:21:46,149 ERROR [140004214941440] (types.h:243) get_xu(...). xioctl(UVCIOC_CTRL_QUERY) failed Last Error: No such device
 02/07 18:21:46,150 ERROR [140004214941440] (error-handling.cpp:68) Error during polling error handler: get_xu(...). xioctl(UVCIOC_CTRL_QUERY) failed Last Error: No such device
 02/07 18:21:46,159 ERROR [140004231726848] (types.h:243) set_xu(...). xioctl(UVCIOC_CTRL_QUERY) failed Last Error: No such device
 02/07 18:21:46,159 ERROR [140004231726848] (global_timestamp_reader.cpp:152) Error during time_diff_keeper polling: set_xu(...). xioctl(UVCIOC_CTRL_QUERY) failed Last Error: No such device
 02/07 18:21:47,150 ERROR [140004214941440] (types.h:243) get_xu(...). xioctl(UVCIOC_CTRL_QUERY) failed Last Error: No such device
 02/07 18:21:47,151 ERROR [140004214941440] (error-handling.cpp:68) Error during polling error handler: get_xu(...). xioctl(UVCIOC_CTRL_QUERY) failed Last Error: No such device
 02/07 18:21:47,160 ERROR [140004231726848] (types.h:243) Cannot open '/dev/video0 Last Error: No such file or directory
 02/07 18:21:47,161 ERROR [140004231726848] (global_timestamp_reader.cpp:152) Error during time_diff_keeper polling: Cannot open '/dev/video0 Last Error: No such file or directory
 02/07 18:21:48,151 ERROR [140004214941440] (types.h:243) get_xu(...). xioctl(UVCIOC_CTRL_QUERY) failed Last Error: No such device
 02/07 18:21:48,152 ERROR [140004214941440] (error-handling.cpp:68) Error during polling error handler: get_xu(...). xioctl(UVCIOC_CTRL_QUERY) failed Last Error: No such device
 02/07 18:21:48,162 ERROR [140004231726848] (types.h:243) Cannot open '/dev/video0 Last Error: No such file or directory
 02/07 18:21:48,162 ERROR [140004231726848] (global_timestamp_reader.cpp:152) Error during time_diff_keeper polling: Cannot open '/dev/video0 Last Error: No such file or directory
 02/07 18:21:49,152 ERROR [140004214941440] (types.h:243) get_xu(...). xioctl(UVCIOC_CTRL_QUERY) failed Last Error: No such device
 02/07 18:21:49,153 ERROR [140004214941440] (error-handling.cpp:68) Error during polling error handler: get_xu(...). xioctl(UVCIOC_CTRL_QUERY) failed Last Error: No such device
 02/07 18:21:49,163 ERROR [140004231726848] (types.h:243) Cannot open '/dev/video0 Last Error: No such file or directory
 02/07 18:21:49,164 ERROR [140004231726848] (global_timestamp_reader.cpp:152) Error during time_diff_keeper polling: Cannot open '/dev/video0 Last Error: No such file or directory
 02/07 18:21:50,153 ERROR [140004214941440] (types.h:243) get_xu(...). xioctl(UVCIOC_CTRL_QUERY) failed Last Error: No such device
 02/07 18:21:50,153 ERROR [140004214941440] (error-handling.cpp:68) Error during polling error handler: get_xu(...). xioctl(UVCIOC_CTRL_QUERY) failed Last Error: No such device
 02/07 18:21:50,165 ERROR [140004231726848] (types.h:243) Cannot open '/dev/video0 Last Error: No such file or directory
 02/07 18:21:50,166 ERROR [140004231726848] (global_timestamp_reader.cpp:152) Error during time_diff_keeper polling: Cannot open '/dev/video0 Last Error: No such file or directory
 02/07 18:21:51,036 ERROR [140004423952128] (sensor.cpp:260) An error has occurred while stop_streaming()!
 02/07 18:21:51,037 ERROR [140004423952128] (types.h:243) xioctl(VIDIOC_STREAMOFF) failed for buf_type=1 Last Error: No such device
 02/07 18:21:51,037 ERROR [140004423952128] (sensor.cpp:260) An error has occurred while stop_streaming()!
 02/07 18:21:51,222 WARNING [140005024999296] (types.cpp:48) stop_streaming() failed. UVC device is not streaming!

[camera/realsense2_camera-3] killing on exit
[camera/realsense2_camera_manager-2] killing on exit
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
[1mdone[0m

---------------------------------------------------------------------------------------------------------------------

I tried the following firmwares for both cameras, but the only one that detects the cameras is the 5.10.3:
-5.10.6
-5.10.13
-5.11.1
-5.11.4
-5.11.6.250

Do you have any idea what could be causing this problem for both cameras?

**Comment by forwardkth** [comment]
I have the same issue. The only working firmware with Jetson TX2 is 5.10.3. The D435I can not be detected if using other firmwares.

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Is this issue still happening? I can confirm firmware latest 5.11.15 with RealSense SDK build 2.29 work on D435/D435i.
Please let us know if you have further question question on this topic. Thank you.
