### ISSUE TITLE
This problem is not been solved.

### ISSUE THREAD

**Issue by pyni** [realsenseai/realsense-ros#841]
https://github.com/IntelRealSense/realsense-ros/issues/553

Any help for the above problem?

I try the version 2.2.6,but it has the same problem.

**Comment by doronhi** [comment]
Thanks. It's a bug. Fixed in #844

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@pyni  Did you try the fix? Any other questions about this? Looking forward to your update. Thanks!

**Comment by pyni** [comment]
Hi, I did not use your package later. Our laboratory has developed our own package, which is quite simple and fast.
https://github.com/lixiny/Handeye-Calibration-ROS
I'll close this issue.
