### ISSUE TITLE
Is there a planned T265 Gazebo plugin?

### ISSUE THREAD

**Issue by antoan** [realsenseai/realsense-ros#846]
Or what will be a good place to start to implement one? 

I'm interested in simulating T265  & D435 paired together.

**Comment by Geekgineer** [comment]
any updates regarding this matter?

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Hi,


We currently do not have plans for a Gazebo plugin.


Thanks

**Comment by nilseuropa** [comment]
https://github.com/nilseuropa/realsense_ros_gazebo

**Comment by izzaaaatanishq** [comment]
@nilseuropa 
![image](https://user-images.githubusercontent.com/78026976/171995996-7170d20a-e138-46f4-8768-0a0d56e7f27c.png)
