### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by amaanda** [realsenseai/realsense-ros#853]
Can I install realsense-ros on a Windows 10 machine running ROS? Without using the Windows Subsystem for Linux.

**Comment by MartyG-RealSense** [comment]
I don't know specifically about  running realsense-ros on Windows, though Microsoft did release an official Windows 10 implementation of ROS in late 2018.

http://wiki.ros.org/Installation/Windows

**Comment by amaanda** [comment]
Yes, I have successfully installed and tested ROS on Windows. My question was specifically about realsense-ros.

**Comment by doronhi** [comment]
I know that microsoft did make an attempt at running realsense2_camera on their Windows ROS.
We didn't try it in Intel yet.

**Comment by amaanda** [comment]
@doronhi I see. Thanks for the reply!
