### ISSUE TITLE
error on compiling on AWS RoboMaker Cloud9

### ISSUE THREAD

**Issue by gbr1** [realsenseai/realsense-ros#854]
Hi!
I'm trying to install latest release on Cloud9 (ROS kinetic) but a dependency error occurs: `ros-kinetic-librealsense2`.

I tried to install using: `sudo apt-get install ros-kinetic-librealsense2` but package could not be found.

I solved using an old tag release (2.2.5).
Do you know how could I get 2.2.7 working?

Thank you in advance!

**Comment by doronhi** [comment]
Just remove the dependency from the package.xml file and install librealsense2 according to the instructions on librealsense2 github.
realsense2_camera naturally needs librealsense2 installed but as you say, the package itself is not yet available as a debian in ros distribution.

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@gbr1 Did you get it through with doronhi's suggestion? Looking forward to your update. Thanks!

**Comment by gbr1** [comment]
Yes, it works!
You can find my guide here (UP Squared AWS RoboMaker development kit):
https://github.com/gbr1/upbot_ros/wiki

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@gbr1 Glad to hear this resolved and thanks very much for the sharing! Close this accordingly.

**Comment by doronhi** [comment]
> Yes, it works!
> You can find my guide here (UP Squared AWS RoboMaker development kit):
> https://github.com/gbr1/upbot_ros/wiki

Hi,
Just wondered, why in your guide you clone and compile ddynamic-reconfigure ( in section: 7. Test Realsense with ROS ) instead of installing the debian package...?

**Comment by gbr1** [comment]
@doronhi probably at that time it was not available as debian package, yet.
If you have included in package dependencies, it should automatically install using rosdep, so probably I can eliminate that line.

**Comment by gbr1** [comment]
@doronhi yes it works ;)
I have just updated my guide

**Comment by doronhi** [comment]
Excellent. Thanks :)
