### ISSUE TITLE
ros_topic::camera_info of D435 does not match data from calibration tool

### ISSUE THREAD

**Issue by hao2921** [realsenseai/realsense-ros#856]
Hi,

i'm using D435 in ROS, i test it using launch file : rs_camera.launch. But then i got confused, that topic published from camera_info seems not right, because i find the message from camera_info_infra1 and camera_info_infra2 are exactly same.

So i install a calibration tool from Intel called Intel.Realsense.CustomRW, then make a compare. The results show that they are different. Any one can help, how i can publish the right camera_info in ROS? Thanks a lot!

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Hi @hao2921,

D435 calibration table read from CustomRW is unrectified Left/Right IR for calibration as 1280x800/Y16 image format.
The data from /camera/infra1/camera_info and /camera/infra2/camera_info is based on the rectified image.
