### ISSUE TITLE
T265 Frame metadata isn't available!

### ISSUE THREAD

**Issue by ghost** [realsenseai/realsense-ros#859]
Hi, I have a T265. When I run the ros node, it said:

[ WARN] [1563516317.828228552]: Frame metadata isn't available! (frame_timestamp_domain = RS2_TIMESTAMP_DOMAIN_SYSTEM_TIME)

What does this mean?

**Comment by thien94** [comment]
I believe you can ignore that warning, as stated here https://github.com/IntelRealSense/realsense-ros/issues/840#issuecomment-510350957.

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

This appears to be fixed in librealsense PR #4403. Is there anything else that needs to be addressed with this issue?
