### ISSUE TITLE
Provide wheel odom to T265

### ISSUE THREAD

**Issue by ghost** [realsenseai/realsense-ros#862]
In the T265 ros launch file, it said:

 For wheeled robots, odometer input is a requirement for robust and accurate tracking.

I installed T265 on my robocar which indeed publish an odom message. How can I pass this message to T265 ros node?

**Comment by doronhi** [comment]
You can use the topic_odom_in topic. See in the README.md file for references to the calibration file needed as well.

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Hi @deeprun

Were you able to find the information you needed regarding wheel odom?

Thanks
