### ISSUE TITLE
does occupancy-mapping branch work well?

### ISSUE THREAD

**Issue by jungladicitta** [realsenseai/realsense-ros#874]
I have deleted my previous realsense-ros package, and did git clone from occupancy-mapping branch. And I was trying to catkin_make, and i got these errors:

```
In file included from /home/r2/catkin_ws/src/realsense-ros/realsense2_camera/src/t265_realsense_node.cpp:1:0:

/home/user/catkin_ws/src/realsense-ros/realsense2_camera/src/../include/t265_realsense_node.h: At global scope:

/home/user/catkin_ws/src/realsense-ros/realsense2_camera/src/../include/t265_realsense_node.h:25:18: error: ‘wheel_odometer’ in namespace ‘rs2’ does not name a type
```

```
/home/user/catkin_ws/src/realsense-ros/realsense2_camera/src/t265_realsense_node.cpp: In constructor ‘realsense2_camera::T265RealsenseNode::T265RealsenseNode(ros::NodeHandle&, ros::NodeHandle&, rs2::device, const string&)’:

/home/user/catkin_ws/src/realsense-ros/realsense2_camera/src/t265_realsense_node.cpp:10:38: error: class ‘realsense2_camera::T265RealsenseNode’ does not have any field named ‘_wo_snr’
```

`/home/r2/catkin_ws/src/realsense-ros/realsense2_camera/src/t265_realsense_node.cpp:10:56: error: ‘wheel_odometer’ is not a member of ‘rs2’`

and others.

how can i fix it?

and also realsense-ros/occupancy/README.md seems incorrect

**Comment by doronhi** [comment]
@schmidtp1 , any idea?

**Comment by schmidtp1** [comment]
Hi @jungladicitta, what LRS version are you using? The occupancy mapping branch is not actively maintained and not up to date (but was working in the past). I'd have to check for the latest LRS version and any possible changes.
What is it that seems incorrect to you in the README.md?

**Comment by jungladicitta** [comment]
Hello @schmidtp1,
I am using latest version of librealsense 2.25.0 from master branch.
Recently, I fully have re-installed entire ros and librealsense, updated gcc to 9 version and cmake to 3.15.1. Now, i am not getting above errors when i am doing catkin_make.

But, I still have another problem. When i am running 
`roslaunch occupancy occupancy_live_rviz.launch`
i get randomly 1 of these 4 cases:
1) everything is not working
![2_1](https://user-images.githubusercontent.com/45363623/62615789-303b2380-b938-11e9-9b29-e516b87e1248.png)
2) only t265 camera is working
![2_rviz](https://user-images.githubusercontent.com/45363623/62615799-34674100-b938-11e9-804a-f02cb8f6f110.png)
3) t265 is working, d435 is freezing, PointCloud shows at the start, images is slowly updating
![1](https://user-images.githubusercontent.com/45363623/62615756-1bf72680-b938-11e9-8955-05eb821cfb9c.png)
4) everything works fine, at the beginning, map is drawn well, but then seems like d435 become disconnected
![hatarakite imasuka](https://user-images.githubusercontent.com/45363623/62615804-36c99b00-b938-11e9-81f9-ed156fdd06f1.png)
![bug_final](https://user-images.githubusercontent.com/45363623/62681825-c7f64b80-b9e4-11e9-9402-f23872f47f53.png)


~~about README.md, i mean: 1) why there is written "catkin build", not catkin_make; 2) "git clone <URL_TO_REPOSITORY>" without indicating occupancy-mapping branch~~
actually doesnt matter


Is this because of librealsense?
Or maybe i should update firmware for d435 camera?
https://www.intel.com/content/www/us/en/support/articles/000028171/emerging-technologies/intel-realsense-technology.html

**Comment by tommasomac** [comment]
Hello. Did you or anyone find a solution for this? I get the same problems, probably because the two cameras fail when they are launched together, but I could not find a solution.

**Comment by gezabohus** [comment]
> Hello. Did you or anyone find a solution for this? I get the same problems, probably because the two cameras fail when they are launched together, but I could not find a solution.

You might want to check out http://wiki.ros.org/timed_roslaunch. I have used it to put a few between launching the two cameras.
