### ISSUE TITLE
Modify fps of the topic /camera/depth_registered/points

### ISSUE THREAD

**Issue by yann-ro** [realsenseai/realsense-ros#877]
Hi ! I'm a beginer with ROS and in my application I don't need good fps to use the pointCloud so i need to modify this value. I have a look in the file rs_rgbd.launch but i don't want to make a mistake.. So where i need to change the value for the topic : /camera/depth_registered/points ?

**Comment by doronhi** [comment]
launch realsense2_camera node using the following command line:
```
roslaunch realsense2_camera rs_rgbd.launch color_fps:=6
```
You can also set `depth_fps:=6` and `enable_infra1:=false`, `enable_infra2:=false` to save on USB resources.

This will publish topic `/camera/aligned_depth_to_color/image_raw` at 6hz and the rgbd node will convert it into a points cloud at the same rate.
You can see other optional frequencies valid for your device using `rs-enumerate-devices`, available after installing `librealsense2-utils`.
