### ISSUE TITLE
t265 and d435 mount, extrinsic parameter doubt

### ISSUE THREAD

**Issue by svabhishek29** [realsenseai/realsense-ros#881]
Hi, 

i was looking at the extrinsic parameter for the mount for the t265 and d435 cameras, the 

> origin xyz="0.009 0.021 0.027" rpy="0.000 -0.018 0.005

line says the depth camera is at xyz offset and rpy degrees from the tracker camera, is this with respect to center of the depth camera?

if so how do i get it wrt to the rgb camera on d435?

thanks

**Comment by doronhi** [comment]
can you use the topic:
`/camera/extrinsics/depth_to_color`?
the transformation is also available in the /tf_static.

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Hi @svabhishek29

Were you able to utilize the topic that doronhi provided to get the information you needed?

Thanks
