### ISSUE TITLE
Record ROSBAG with other robot sensor streams

### ISSUE THREAD

**Issue by akouri-dd** [realsenseai/realsense-ros#897]
I'm working with both LiDAR and multiple realsense cameras. I understand that the `rosbag record -a` command won't properly get some of the metadata that the Realsense camera needs to play itself back properly with the PointCloud2 data type.

I would like to create a single rosbag that includes both the lidar data and 4x realsense cameras so that they are all time-synced. 

What is the best approach for doing so? I saw this [issue](https://github.com/IntelRealSense/librealsense/issues/3020) but the solution was never posted.

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Hi @akouri-dd

We do not have a solution specifically for what you are looking for.

Is there anything else needed here?

**If we don’t hear from you in 7 days, this issue will be closed.**
