### ISSUE TITLE
 How to adjust the camera exposure by topic 

### ISSUE THREAD

**Issue by WangyuHIT** [realsenseai/realsense-ros#900]

**Comment by doronhi** [comment]
Could you elaborate a little...?

**Comment by wikpunGitHub** [comment]
Hi, I have the same question. Is there a way to adjust the "set auto exposure" setting in launch file or node parameter rather than using rqt_reconfigure?

**Comment by doronhi** [comment]
You can add the following lines to your launch file before the section of launching realsense2_camera node:
```
<rosparam>
  /camera/rgb_camera/auto_exposure_roi/left: 30
  /camera/rgb_camera/auto_exposure_roi/right: 350
</rosparam>
```
(you can check the precise string using rqt_reconfigure)

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Hi @ WangyuHIT,

Has the comment provided by @doronhi helped to find an answer to your question? Please let us know if you need any further assistance with this matter.

Thank you!

**Comment by denseishin** [comment]
I have the same question as @wikpunGitHub, but in my case there is no /camera/rgb_camera/auto_exposure_roi visible on rqt_reconfigure, only /camera/stereo_module/auto_exposure_roi exists. I can also see a top and bottom parameter.

**Comment by MartyG-RealSense** [comment]
Hi @denseishin  Which RealSense camera model and ROS1 wrapper version are you using, please?

**Comment by denseishin** [comment]
I'm using a D405, but to do so I'm using rjwb1's fork https://github.com/IntelRealSense/realsense-ros/pull/2297

**Comment by MartyG-RealSense** [comment]
Even though development on the official ROS1 wrapper has ceased, the RealSense ROS development team recently added support for the D405 PID to the wrapper, as described at https://github.com/IntelRealSense/realsense-ros/pull/2915#issuecomment-1784192483
