### ISSUE TITLE
T265 relative tracking

### ISSUE THREAD

**Issue by pringithub** [realsenseai/realsense-ros#903]
Hello,

I wish to do relative tracking with a head-mounted T265 inside of a vehicle. To expand, I want the pose of my head in relation to the cabin of a moving vehicle. 

I have previously got this to work using the D435 (with `clip_distance:=1`) and RTAB-MAP, but as I do not want to do too much external computation, I would like to get it working with the T265. 

Is there an option similar to clip_distance which would allow me to do this with the T265? I would also want to turn off the accel/gyro feature that feeds to the internal SLAM algo (I'm assuming it's a variant of SLAM/VIO?) as I don't want global tracking. `enable_[accel/gyro]:=false` doesn't seem to turn off the [INFO] message: `SELECTED BASE: Gyro, 0` ...

Any help would be much appreciated, otherwise I'm stuck with a $200 paper-weight :)

**Comment by MartyG-RealSense** [comment]
If you have both a T265 and a D435 then the T265 is certainly not wasted, as you can pair the two devices together to provide your T256 tracking applications with  depth data.

If you wish to compute pose with just the T265 though, you could put a fiducial tag somewhere in the cabin that the T265 can follow, like in the SDK's 'Apriltag' T265 example.

https://github.com/IntelRealSense/librealsense/tree/master/examples/pose-apriltag

I do not personally know if / how you can turn accel/gyro off, though someone on the Intel team is sure to be able to give you an answer on that.

**Comment by doronhi** [comment]
I don't think that there is an option to disregard the IMU in the librealsense2 SDK. There is definitely no such option in the ros wrapper. You should check in the [librealsense2 repository](https://github.com/IntelRealSense/librealsense) issues. @radfordi ?

**Comment by radfordi** [comment]
@pringithub, the T265 does not support working without the IMU, nor does it have a clipping distance.  It does however provide the raw data on a consistent clock, so you can port an open source stereo VIO with your requirements.

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@pringithub Are these recommendations sufficient for you to accomplish what you need?
