### ISSUE TITLE
Launch camera based on port number (or model)

### ISSUE THREAD

**Issue by doisyg** [realsenseai/realsense-ros#904]
Currently, the only way to distinguish which camera to use in a multi camera/multi model configuration is to use the serial number of the camera device. This is not easy to maintain.
Would it be possible to use the *camera1_usb_port_id* as in the legacy package?
https://github.com/IntelRealSense/realsense-ros/blob/ebc06d4be1800da82595a7ccb163f3b5b6e69b23/realsense_camera/launch/r200_nodelet_multiple_cameras.launch#L18-L26

In addition having a filter based on the camera model to be able to launch concurrently a D435 and a T265 without using serial numbers.

**Comment by doronhi** [comment]
Added option in #966, #964, #960.

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Hi @doisyg, Do you need further help on this?
If we don't hear from you in 7 days, we will close it.
