### ISSUE TITLE
Recommended Setup for Multiple D435s

### ISSUE THREAD

**Issue by reyes73a** [realsenseai/realsense-ros#913]
Hi guys,

I was wondering what would be a recommended companion computer for interfacing with multiple D435s. Right now, I have been testing a D435 with a Jetson Nano and at full res @30fps and the ROS node seems to be dropping frames frequently. My intention is try to interface with up to 4 D435s at the same time. I know I can try to reduce the resolution and FPS on each device, but I was wondering what is, in your opinion, a good companion computer that could run ROS Kinetic and support 4 D435s (TX1, TX2, Intel Aero?). If I run the same experiment on an i7 it does not drop any frames, but I am not aware of a small companion computer (the size of a Jetson nano) that could pack that much processing power? I have the feeling that the Jetson nano will not be able to handle this much workload. Any help would be greatly appreciated!!!

Thanks!

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

The whitepaper about the multi-camera configuration is a great resource for hardware and software considerations when running multiple RealSense cameras to the same host.
https://dev.intelrealsense.com/docs/multiple-depth-cameras-configuration
Please take a look. Thank you.
