### ISSUE TITLE
D435 model links

### ISSUE THREAD

**Issue by YueErro** [realsenseai/realsense-ros#919]
Hi,

I have noticed that the RealSense D435 model has some links flipped:

![64526483-bc5bb480-d303-11e9-8c3d-72c73a145c83](https://user-images.githubusercontent.com/16896370/64535701-03ec3b80-d318-11e9-9b41-9f0a1d1da62f.png)

Is this on purpose? Are they flipped because those are the links in the camera frame?

Also, there is not any link placed at the IR Projector and as far as I know, the real camera records from there. I believe camera_deph_frame_link and camera_deph_frame_optical_frame should be placed there.

Am I completely wrong on this?

**Comment by doronhi** [comment]
The "_optical_frame" links are, as you said, in the camera coordinate system. Therefor they are flipped compared to the other links which are on the ROS coordinate system.
The camera calculate depth based on the images from infra1 and infra2 sensors, and the depth image is projected to infra1 frame. The projector just adds IR features on the scene to enhance the image for the depth calculation. It's location is meaningless and therefor there is no link to describe it.
