### ISSUE TITLE
occupancy-mapping branch: parameters in occupancy.launch file

### ISSUE THREAD

**Issue by jungladicitta** [realsenseai/realsense-ros#920]
what does those parameters means?
```
  <param name="HeightOfInterestMin" value="-0.5"/>
  <param name="HeightOfInterestMax" value="0.5"/>
  <param name="DepthOfInterestMin" value="0.2"/>
  <param name="DepthOfInterestMax" value="2.0"/>
```
in occupancy.launch file?
especially HeightOfInterestMin and HeightOfInterestMax

**Comment by jungladicitta** [comment]
anyone? @schmidtp1?

**Comment by schmidtp1** [comment]
@jungladicitta, hi, this is the space above and below the camera that is considered when determining if the space is occupied. This depends on where the camera is mounted on your robot and the height of the robot, for example min. is the height above ground (including some margin) and max. is the height of the robot minus height of the camera (plus some margin).
Depth of interested is used to clip the depth. There is a minimum distance in which the camera returns valid values ("minZ", here set to 20cm). As with any stereo system the depth error grows with the distance (quadratically) and the depth can be limited to bound the error (here to 2m).

**Comment by jungladicitta** [comment]
@schmidtp1 that is very interesting and good to know!
thanks for reply

**Comment by jungladicitta** [comment]
@schmidtp1 why is there "-0.5" in HeightOfInterestMin? does it mean 50cm below the ground?
Is this because we need margin due to d435 error in 2 meters?

**Comment by jungladicitta** [comment]
@schmidtp1 so, "-0.5" in HeightOfInterestMin means that our camera is located 50cm above the ground, right?

**Comment by schmidtp1** [comment]
@jungladicitta, correct!

**Comment by jungladicitta** [comment]
@schmidtp1 do I need something to take into account if i locate camera with inclination to the floor?
like this
![64243292-54872180-cf31-11e9-947a-bf43056c911d](https://user-images.githubusercontent.com/45363623/65300351-555cbc00-db9d-11e9-865e-4da1e5a31793.png)

**Comment by jungladicitta** [comment]
@schmidtp1 dont you think its vice versa? i tried as you said, and occupancyGrid become worse, everything is white, only walls considered as obstacles, there is no even 1 meter height tables

**Comment by schmidtp1** [comment]
@jungladicitta, as far as I remember, the height refers to the to the T265 reference frame.
The point cloud is transformed from the depth camera to the T265 frame using the extrinsics here: https://github.com/IntelRealSense/realsense-ros/blob/occupancy-mapping/realsense2_camera/urdf/mount_t265_d435.urdf.xacro
Then it is transformed into a world reference system using the pose estimates from T265. This reference system is initialized at the position of the T265 at startup. While the frame is gravity aligned, there is no reference for the height of the camera, i.e. it is set to 0. Everything should be expressed with respect to the (initial) position/height of the T265 thereby. (For details about the coordinate frames please refer to the T265 data sheet.)

**Comment by schmidtp1** [comment]
> @schmidtp1 do I need something to take into account if i locate camera with inclination to the floor?
> like this
> ![64243292-54872180-cf31-11e9-947a-bf43056c911d](https://user-images.githubusercontent.com/45363623/65300351-555cbc00-db9d-11e9-865e-4da1e5a31793.png)

Where is your T265 mounted? You need to take it into account in the extrinsics in the link above.

**Comment by jungladicitta** [comment]
@schmidtp1 I haven't changed that numbers. Why do I need to change them? my cameras is mounted to each other as it was intended. I even printed that stl model:
![64419210-8d0c3400-d0c6-11e9-9908-1eb822b2a97f](https://user-images.githubusercontent.com/45363623/65402900-7c182e00-ddfb-11e9-87b4-7dd095ae03a5.jpg)

Here is part of my urdf.xacro file:
```
  <!-- REALSENSE D435 -->
  <joint name="cameras_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="t265_pose_frame"/>
    <origin xyz="0.0 0.0 1.2985" rpy="0 0 0"/>
  </joint>

  <link name="t265_pose_frame"/>
  <link name="d400_link"/>

  <joint name="t265_to_d400" type="fixed">
    <parent link="t265_pose_frame"/>
    <child link="d400_link"/>
    <origin xyz="0.009 0.021 0.027" rpy="0.000 -0.018 0.005"/>
  </joint>
```

I am also using static_transform publishers in launch file. Here is my full launch file:
```
<launch>

  <!-- CAMERA -->
  <include file="$(find turtlebot3_occupancy_mapping)/launch/robot_and_cameras.launch"/>

  <!-- occupancy-mapping -->
  <include file="$(find turtlebot3_occupancy_mapping)/launch/occupancy.launch">
  </include>

  <node pkg="turtlebot3_occupancy_mapping" type="map_frame_publisher.py" name="map_frame_publisher" output="screen">
  </node>

  <node name="static_tf0" pkg="tf2_ros" type="static_transform_publisher" args="0 0 1.2985 0 0 0 /map /t265_odom_frame"/>

  <node name="static_tf1" pkg="tf2_ros" type="static_transform_publisher" args="0 0 0 0 0 0 /map /odom"/>

</launch>
```
where map_frame_publisher.py is just publishing occupancy topic to map frame:
```
#!/usr/bin/env python  
import rospy

# Because of transformations
import tf_conversions

import tf2_ros
import tf2_msgs.msg
import geometry_msgs.msg
import sensor_msgs.msg
import nav_msgs.msg
from std_msgs.msg import String

def handle_map_frame(data):
    pub = rospy.Publisher("map", nav_msgs.msg.OccupancyGrid, queue_size=10)
    rate = rospy.Rate(10) # 10hz

    data.header.frame_id = "map"

    pub.publish(data)
    rate.sleep()

if __name__ == '__main__':
    rospy.init_node('map_frame_broadcaster')
    rospy.Subscriber("/occupancy", nav_msgs.msg.OccupancyGrid, handle_map_frame)
    ##rospy.Subscriber('/sensor_us', sensor_msgs.msg.Range, handle_camera_pose)
    rospy.spin()
```
Am i doing something wrong?

**Comment by jungladicitta** [comment]
> > @schmidtp1 do I need something to take into account if i locate camera with inclination to the floor?
> > like this
> > ![64243292-54872180-cf31-11e9-947a-bf43056c911d](https://user-images.githubusercontent.com/45363623/65300351-555cbc00-db9d-11e9-865e-4da1e5a31793.png)
> 
> Where is your T265 mounted? You need to take it into account in the extrinsics in the link above.

@schmidtp1 T265 was mounted on the mast, 1.29 meters above the ground, oriented towards to ground.

But now I decided to move T265 at mid-height, 0.92 meters from the ground, oriented straight-ahead

**Comment by jungladicitta** [comment]
@schmidtp1 
these numbers is only for d435 position relatively to t265, so there is no need to change them if I move cameras on the robot, right?
```
<joint name="t265_to_d400" type="fixed">
    <parent link="t265_pose_frame"/>
    <child link="d400_link"/>
    <origin xyz="0.009 0.021 0.027" rpy="0.000 -0.018 0.005"/>
</joint>
```

**Comment by schmidtp1** [comment]
> @schmidtp1
> these numbers is only for d435 position relatively to t265, so there is no need to change them if I move cameras on the robot, right?
> 
> ```
> <joint name="t265_to_d400" type="fixed">
>     <parent link="t265_pose_frame"/>
>     <child link="d400_link"/>
>     <origin xyz="0.009 0.021 0.027" rpy="0.000 -0.018 0.005"/>
> </joint>
> ```

That's correct, @jungladicitta. (Sorry for the long reply time.)

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@jungladicitta is there anything further needed on this thread?
