### ISSUE TITLE
Cannot lauch d435i camera node

### ISSUE THREAD

**Issue by catmasteryip** [realsenseai/realsense-ros#922]
I am using Ubuntu 18.04.3 LTS
kernel version: 5.0.0-27-generic
ROS version: melodic
Intel realsense-ros SDK version: =>2.0
When I entered `roslaunch realsense2_camera rs_camera.launch` in bash after installation of Intel realsense-ros  SDK, this happened:
![image](https://user-images.githubusercontent.com/29121012/64667788-8f3b0d80-d48d-11e9-9cfe-6ae32b3deac2.png)
`11/09 12:05:41,072 WARNING [140710628022016] (ds5-timestamp.cpp:64) UVC metadata payloads not available. Please refer to the installation chapter for details.`

**Comment by catmasteryip** [comment]
D435i firmware version: 05.11.11.100

**Comment by doronhi** [comment]
As for the "Time is out of dual 32-bit range" error, I am not sure it's a realsense2_camera problem. From the little search I did, it seems like there is something more general in ROS and it occures when realsense2_camera calls `_ros_time_base.toSec()`
The other warning "UVC metadata payloads not available." suggest that something was wrong with the installation process.

**Comment by catmasteryip** [comment]
Thanks for the reply. I have reinstalled ROS and librealsense ROS wrapper but the problem persists.

**Comment by catmasteryip** [comment]
I am currently using ROS melodic on Ubuntu 18 but not the ROS kinetic on Ubuntu 16 as suggested, would that be a problem?

**Comment by catmasteryip** [comment]
[https://github.com/IntelRealSense/realsense-ros/issues/492#issuecomment-533528194](url)
It seems to me that the camera node can publish but the roslaunch command says otherwise.

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@catmasteryip Which librealsense and ROS wrapper version did you use when get the issue? Did you get chance to try the latest version? We tried Ubuntu18.04+melodic here but didn't get your issue.

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@catmasteryip Could you please update? Thanks!

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@catmasteryip Sorry that we didn't get any response from you for weeks, will close the issue at this point. Please feel free to create another new one if you still have questions or issues. Thanks!
