### ISSUE TITLE
Expose RS2_OPTION_ENABLE_POSE_JUMPING parameter

### ISSUE THREAD

**Issue by msadowski** [realsenseai/realsense-ros#923]
Hi!

It looks like since librealsense 2.25.0 a parameter for enabling/disabling pose jumping was [introduced](https://github.com/IntelRealSense/librealsense/blob/d19829788008b8e000870895a068f0c43d58895a/doc/t265.md#are-there-any-t265-specific-options).

Is there a plan to expose the parameters introduced in 2.25.0? RS2_OPTION_ENABLE_POSE_JUMPING is particularly interesting as it would allow the t265 to be used as a source of odometry in odom->base_link transform while still conforming to [REP-105](https://www.ros.org/reps/rep-0105.html)(particularly the guarantee that the robot pose is continuous in the odom frame). 

I can see these parameters are only available in dynamic reconfigure at the moment, however the settings can't be set using rqt_reconfigure since the camera is already streaming when the node is launched.

**Comment by doronhi** [comment]
You can change all the parameters that appear in dynamic reconfigure at launch time.
Add the following lines to your launch file, *before* the line `<group ns="$(arg camera)">`:
```
  <rosparam>
      /camera/tracking_module/enable_pose_jumping: false
  </rosparam>
```
Does that work for you?

**Comment by msadowski** [comment]
Thanks a lot @doronhi ! That worked perfectly!

With this last bit in I think I managed to get a perfect setup of T265 on a mobile platform. I'll document it in the next week or two and try to share it around to make it easier for others to get started with T265.

**Comment by doronhi** [comment]
> Thanks a lot @doronhi ! That worked perfectly!
> 
> With this last bit in I think I managed to get a perfect setup of T265 on a mobile platform. I'll document it in the next week or two and try to share it around to make it easier for others to get started with T265.

Excellent! I'm looking forward to it!
