### ISSUE TITLE
How to use two D435 cameras at the same time

### ISSUE THREAD

**Issue by alliansmover** [realsenseai/realsense-ros#925]
dear
       How to use two D435 cameras at the same time
thanks

**Comment by MartyG-RealSense** [comment]
The link below has a guide to using two 400 Series cameras with ROS.

https://github.com/IntelRealSense/realsense-ros/wiki/Showcase-of-using-2-cameras

**Comment by alliansmover** [comment]
> 以下链接提供了使用两个带有ROS的400系列相机的指南。
> 
> https://github.com/IntelRealSense/realsense-ros/wiki/Showcase-of-using-2-cameras

**Comment by alliansmover** [comment]
> The link below has a guide to using two 400 Series cameras with ROS.
> 
> https://github.com/IntelRealSense/realsense-ros/wiki/Showcase-of-using-2-cameras
thanks
