### ISSUE TITLE
T265 loses localization on traveling over a bump

### ISSUE THREAD

**Issue by SSusantAchary** [realsenseai/realsense-ros#930]
System:
=======
Ubuntu 18.04
Nvidia Jetson Nano
D435 & T265
ROS Melodic
Rviz (for destination input )

I have a differential robot with D435 Camera and T265 camera , both have been aligned with the help of static transform.

[What's Working]:
When the differential robot moves along a path without any bump or rise in its path, it successfully reaches the desired goal .

[Issue]:
1. But when the robot while navigation comes over a small bump(i.e moving over a wire lying on floor), T265(i.e robot) loses it localization initially and ultimately gathers errors over time and reaches to wrong location , which in turn impacts the D435 Camera in updating local & global map for obstacle updation(when robot encounters).

2. In 5 out of 10 cases of robots navigation , Even if above issue prevails the bot reaches the first destination, there after when we give next destination the Local_costmap and Global_costmap doesn't update with the dynamic obstacles.

**Comment by RealSenseSupport** [comment]
Thank you for highlighting the issue of losing localization while using T265 over bumps. We have moved our focus to our next generation of products and consequently, we will not be addressing this issue in the T265.

**Comment by SSusantAchary** [comment]
Thanks
