### ISSUE TITLE
Update to newest librealsense

### ISSUE THREAD

**Issue by kamilritz** [realsenseai/realsense-ros#935]
When can the updated librealsense version be expected to go in the ROS wrapper?

**Comment by doronhi** [comment]
You can try building with the latest librealsense version. If no interface modifications were done it should work.

**Comment by kamilritz** [comment]
Thanks for you reply. I tried, but while launching the `rs_t265.launch`, I got this error:
```
[ERROR] [1571060191.657227981]: Failed to load nodelet [/camera/realsense2_camera] 
of type [realsense2_camera/RealSenseNodeFactory] even after refreshing the cache: 
API version mismatch: librealsense.so was compiled with API version 2.29.0 
but the application was compiled with 2.25.0! Make sure correct version of the library is installed (make install)
```
Is there something I can do about this?

**Comment by kamilritz** [comment]
I had to perform a `catkin clean` in order to build the ROS wrapper with the right librealsense version.
