### ISSUE TITLE
Subscribe to relocalization events from T265 camera on ROS wrapper?

### ISSUE THREAD

**Issue by imasoul2** [realsenseai/realsense-ros#936]
Hello,

 I am trying to use the T265 for navigation of my mobile robot.
I am testing the relocalization ability of the T265 camera however I realised that it provides an odometry only and to my knowledge, there is no other way I can know when the relocalization has occurred.

 Is there any way on ROS wrapper to subscribe to a topic or other way to know when the relocalization has occurred other than looking at the covariance matrix from the /camera/odom/sample topic?

 Thank you.

**Comment by marcelino-pensa** [comment]
Has this been closed because there is a solution to detect relocalization events? Or just because this won't ever be implemented, so there is no point in keeping this issue open?

**Comment by marcelino-pensa** [comment]
@RealSenseSupport

**Comment by marcelino-pensa** [comment]
@RealSenseSupport
