### ISSUE TITLE
AprilTag support with Realsense-ros wrapper

### ISSUE THREAD

**Issue by jacksparkman** [realsenseai/realsense-ros#941]
Will the example codes be added to the realsense-ros wrapper? The example code rs-pose-apriltag is great, but cannot be published to a ROS topic. Being able to detect apriltags with the realsense cameras inside ROS would be great for development.

**Comment by stasgurevich** [comment]
Here is the ROS package that can be used to detect apriltags with any cam (including Realsense).
https://github.com/AprilRobotics/apriltag_ros

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@jacksparkman Did you get it through? Any other questions? Looking forward to your update. Thanks!

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@jacksparkman Could you please update? Thanks!

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@jacksparkma Didn't get response from you for weeks. Will close the ticket at this point. Please feel free to create new one if you still have questions or issues. Thanks!

**Comment by AndreV84** [comment]
how exactly to run it with realsense d435? Thanks
