### ISSUE TITLE
Grayscale Pointcloud2

### ISSUE THREAD

**Issue by harshitsankhla** [realsenseai/realsense-ros#942]
Hi,

I am using Realsense Pointcloud2 (depth_registered/points) to generate 3D Map using Octomap ROS package. The map render rate is terribly slow (Not even 1 Hz stable). I am presuming it is due to the high bandwidth of the Pointcloud2 stream (~300MB/S for 640x480 @ 60FPS) 

Is there a way to get the pointcloud2 topic in grayscale or any other way to reduce the bandwidth (pointcloud message size)

Any help will be appreciated

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Hi @harshitsankhla,

If it's due to the high computing power, wouldn't you consider to reduce the resolution and FPS?
And, which camera do you use?
