### ISSUE TITLE
rs_rtabmap.launch bad results

### ISSUE THREAD

**Issue by fightforge** [realsenseai/realsense-ros#945]
Hi,
i get bad results using rs_rtabmap.launch with printed mount for t265 and d435i. I'm trying to set visual_odometry to true but i get image drift in rtabmalviz from depth image to odometry. Is there a way to increase results?

Thanks

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Hi @fightforge

Were you able to get your configuration working?  Is there still issues here?  There are quite a bit of information on github regarding using T265 and D435/D435i mounted and produce depth imagery with pose data.
