### ISSUE TITLE
Pausing the camera

### ISSUE THREAD

**Issue by myles-vineland** [realsenseai/realsense-ros#947]
Does anybody know a way to pause the camera? I working on an application that is using 3 d435s connected to a jetson nano and only need them running for short periods of time.

I have tried just killing the camera nodes but that gives me problems when trying to restart them. I've tried using roslaunch.shutdown to stop the cameras nodes (which I am starting from a launch file similar to rs_multiple_devices.launch) but then when I try to start the launch file again I get" bad roslaunch process monitor initialization: process monitor is already dead".

If anyone has any suggestions it would be greatly appreciated.

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Hi @myleslidka,

Please check below to see if it can be used for your use case.
https://github.com/IntelRealSense/realsense-ros/pull/487

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

I will close this if no further question.

**Comment by chia-labradorsystems** [comment]
Hi,  @RealSenseCustomerSupport 
Seems like the solution provided in #487 is no longer available now.
`void BaseRealSenseNode::toggleSensors(bool enabled) ` is still there but there is no dynamic parameter hooks with it right now.

**Comment by doronhi** [comment]
You are right. I'll try to attend to it as soon as I manage.

**Comment by chia-labradorsystems** [comment]
@doronhi Thank you.
I tried to implement it myself yesterday, `toggleSensors` can stop the camera but cannot start it again
I'm using d435 with the latest firmware.

when turn off Stereo Module I get
`07/04 11:31:08,698 WARNING [139845326329600] (types.cpp:49) stop_streaming() failed. UVC device is not streaming!`
when tun on Stereo Module I get 
` 07/04 11:31:13,871 WARNING [139845326329600] (types.cpp:49) start_streaming(...) failed. UVC device is already streaming!`
