### ISSUE TITLE
Subsampling in ROS driver available?

### ISSUE THREAD

**Issue by JadTawil-theonly** [realsenseai/realsense-ros#952]
After reviewing the document provided by intel for post processing depth information:
https://www.mouser.com/pdfdocs/Intel-RealSense-Depth-PostProcess.pdf

One of the major speedups was due to the Sub-sampling step.

Is this step an option with the ROS driver?

I see the following as filters:
colorizer
disparity
spatial
temporal
hole_filling
decimation

I do not see sub sampling, which is v important for speed ups.

Any ideas?

**Comment by MartyG-RealSense** [comment]
Subsampling refers to use of decimation.

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Hi @JadTawil-theonly,

Do you manage to utilize the filter parameters in ROS wrapper? If no additional question, will close this.

**Comment by JadBatmobile** [comment]
Yes, all is good
