### ISSUE TITLE
Manually set position T265

### ISSUE THREAD

**Issue by JvanZijl** [realsenseai/realsense-ros#954]
Dear all,

Is there an easy way to manually overwrite the position of the Realsense T265 when the node is already running? I would like to manually set the x, y and z coordinate of the T265 to 0 or any other point, without restarting the node. Is there an easy way to do this using for example a Python script?

Kind regards

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

No unfortunately this cannot be done.

**Comment by ArkadiuszNiemiec** [comment]
@JvanZijl write a ROS node that reads the position that the R265 reports and publish a static transform in the [tf](http://wiki.ros.org/tf) from T265 frame to e.g. `map` frame. This is a proper ROS solution to a problem like this.

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Will you be needing further assistance on this?
