### ISSUE TITLE
learning based object detection on RS_D435i

### ISSUE THREAD

**Issue by JoeyLeeNPU** [realsenseai/realsense-ros#956]
I want to use a d435i to perform learning based object detection, which running on the processor inside d435i, because the center procossor of my drone is poor on computation resource. I found the code example about rs-dnn, maybe it is computed on the center device. Any suggestions?

Thanks,
Joey

**Comment by MartyG-RealSense** [comment]
The RealSense Facebook account posted a link to a sample program that performs object detection and distance measuring with the OpenVINO Toolkit and Intel Neural Compute Stick 2 (NCS2).

You can accelerate processing with an NCS2 alongside a 400 Series camera just by plugging the NCS2 into an available USB port on your drone's computing hardware.

**Sample:**
https://github.com/movidius/ncappzoo/tree/master/apps/realsense_object_distance_detection 

**RealSense Facebook:**
https://www.facebook.com/IntelRealSense/

**Intel NCS2 in the RealSense Store**
https://store.intelrealsense.com/buy-intel-neural-compute-stick-2.html

https://store.intelrealsense.com/buy-depth-camera-and-neural-compute-stick-2-bundle.html

Alternatively, you could offload graphics processing work onto your drone computing board's GPU.  

https://github.com/IntelRealSense/librealsense/issues/4905#issuecomment-533854888

The Vision Processor D4 board inside the camera can do graphics processing tasks that a GPU would normally have to do, but it is limited to the pre-programmed graphics tasks it was designed for (such as rectification of raw camera data) and cannot be used as a PC CPU processor - a computing board is still required to run Librealsense.
