### ISSUE TITLE
T265 - programmatically resetting localization? Confidence value?

### ISSUE THREAD

**Issue by reyes73a** [realsenseai/realsense-ros#958]
Hi guys,

I am looking to achieve two things from ROS:

1. Is there a way through the current ROS wrapper to programmatically reset the T265 localization? I don't want to physically power cycle the camera or the ROS node. 

2. The Realsense Viewer exposes  a confidence variable (confidence on localization) is this accessible from ROS?

Any help would be greatly appreciated! Thanks!

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Hi @reyes73a

Regarding the confidence level, have you came across this:  https://github.com/IntelRealSense/realsense-ros/blob/ec68bddb042abeba820421835c8b3e968c1016c7/realsense2_camera/src/base_realsense_node.cpp

Regarding localization, the APIs are available in librealsense (https://github.com/IntelRealSense/librealsense)


Is there anything else needed here?

Thanks
