### ISSUE TITLE
Color stream/topic frequency diagnostics not publishing

### ISSUE THREAD

**Issue by mikepurvis** [realsenseai/realsense-ros#969]
When I start instances of the driver nodelet for my cameras, I briefly get diagnostics for both depth and color, but then once it's running, I only get the depth ones— the color diagnostic goes silent. This is not a result of my diagnostic aggregator setup, as I'm inspecting the `/diagnostics` topic directly.

I'm assuming this is a bug which just needs to be fixed, as it appears from the code that the intention is for both depth and color stream publishers to have diagnostics:

https://github.com/IntelRealSense/realsense-ros/blob/432eb1c19809a637622604bd8f0f3438c04cc17e/realsense2_camera/src/base_realsense_node.cpp#L787-L789

However:

```
$ rostopic echo /diagnostics | grep realsense_camera_manager
    name: "rear_left/realsense/realsense_camera_manager_depth: Frequency Status"
    name: "rear_right/realsense/realsense_camera_manager_depth: Frequency Status"
    name: "side_left/realsense/realsense_camera_manager_depth: Frequency Status"
    name: "side_right/realsense/realsense_camera_manager_depth: Frequency Status"
    name: "rear_left/realsense/realsense_camera_manager_depth: Frequency Status"
    name: "rear_right/realsense/realsense_camera_manager_depth: Frequency Status"
    name: "side_left/realsense/realsense_camera_manager_depth: Frequency Status"
    name: "side_right/realsense/realsense_camera_manager_depth: Frequency Status"
```

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Hi.

Will you be needing further help with this?

As of  RealSense ROS v2.2.13 and LibRealsense v2.33.1 both color and depth diagnostics (attached) are being published as expected.

If we don’t hear from you in 7 days, this issue will be closed.

Thanks

Attachment(s):
Screenshot.png - https://realsensesupport.intel.com/attachments/token/ASqfRN09Fe0k6tyGQ6jnqek1s/?name=Screenshot.png
