### ISSUE TITLE
Add librealsense installation URL in realsense/realsense_camera/README.md 

### ISSUE THREAD

**Issue by testkit** [realsenseai/realsense-ros#97]
In realsense_camera/README.md file, better to add librealsense installation related URL after "Clone the librealsense GitHub repository", or user might missed to "make; make install" librealsense to generate necessary binaries.
E.g. for Ubuntu support, the URL is https://github.com/IntelRealSense/librealsense/blob/master/doc/installation.md#ubuntu-installation

**Comment by mdhorn** [comment]
Actually, we do not want you to so the make; make install step.
Both the librealsese and realsense_camera are now release ROS packages.

You should be installing them with:
`apt-get install ros-kinetic-realsense-camera`

The current ros-kinetic-librealsense package (and ros-indigo-librealsense) install the udev rules, but do not apply the necessary kernel patches. This is why we currently have a sub-set of the librealsense installation directions to download source just to patch the kernel.

We are working to have the librealsense package also automatically handle the kernel patching using DKMS. We have a working solution for ubuntu systems, but there is a complication using this in the ROS Build Farm which runs under Docker images. 

Hopefully the kernel patching will be resolved soon, and then there will new no references to the librealsense installation steps.
