### ISSUE TITLE
How to convert _d435.urdf.xacro  into urdf

### ISSUE THREAD

**Issue by gachiemchiep** [realsenseai/realsense-ros#977]
Hello guys.

I know this is a noob question. But how can i convert the _d435.urdf.xacro  into urdf ?
I try the following command

```bash
rosrun xacro xacro --inorder src/realsense-ros/realsense2_description/urdf/_d435.urdf.xacro 
```
The output is as follow

```bash
<?xml version="1.0" ?>
<!-- =================================================================================== -->
<!-- |    This document was autogenerated by xacro from src/realsense-ros/realsense2_description/urdf/_d435.urdf.xacro | -->
<!-- |    EDITING THIS FILE BY HAND IS NOT RECOMMENDED                                 | -->
<!-- =================================================================================== -->
<!--
License: Apache 2.0. See LICENSE file in root directory.
Copyright(c) 2017 Intel Corporation. All Rights Reserved

This is the URDF model for the Intel RealSense 430 camera, in it's
aluminum peripherial evaluation case.
-->
<robot name="sensor_d435" xmlns:xacro="http://ros.org/wiki/xacro">
</robot>

```

I can't include into my urdf. 
So has anyone met the same problem ? And how can i solve it.

**Comment by q8wwe** [comment]
How did you solve the problem

**Comment by gachiemchiep** [comment]
@q8wwe  
we didn't solve the problem so we stop using the urdf format and convert everything into xacro format.

**Comment by q8wwe** [comment]
Did you ever simulate realsense cam with gazebo ?
Can you share your files ?

**Comment by gachiemchiep** [comment]
@q8wwe 
No we use rviz for visualizing. 
Sorry, we couldn't share the file

**Comment by q8wwe** [comment]
So you aren't using gazebo just rviz.which mean you ate working on real robot not simulator

**Comment by gachiemchiep** [comment]
@q8wwe 
That's true. we're working on the UR5
