### ISSUE TITLE
Setting Disparity Shift

### ISSUE THREAD

**Issue by JadTawil-theonly** [realsenseai/realsense-ros#981]
Hello, 

I would like to configure the disparity shift (value from 0 -> 255), in order to control the minZ value of the depth sensing.

How can i do this via the ros wrapper? 

Would changing this require a recalibration?

**Comment by doronhi** [comment]
"Advanced Controls" are currently not supported directly by the ros wrapper.
You can, however, modify them on start up by setting a json file.
To create a configuration json file for the first time use realsense-viewer and the "export" preset button:
![image](https://user-images.githubusercontent.com/40540281/68541633-86da5280-03aa-11ea-8c6a-4ffe2a694c59.png)
To start realsense2_camera with the preset file use the "json_file_path" parameter:
`roslaunch realsense2_camera rs_camera.launch json_file_path:=/home/doronhi/catkin_ws/conf.json`

To control the disparity shift modify value for the field "param-disparityshift" in the json file.

Changing this does not require re-calibration.

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@JadTawil-theonly Did you try the suggestion from doronhi? Any update? Looking forward to your update. Thanks!

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

@JadTawil-theonly Could you please update? Thanks!

**Comment by JadTawil-theonly** [comment]
Hey!
Yes is all good
