### ISSUE TITLE
roslaunch realsense2_camera demo_t265.launch fails 

### ISSUE THREAD

**Issue by florianspy** [realsenseai/realsense-ros#985]
When starting roslaunch realsense2_camera demo_t265.launch after roslaunch realsense2_camera rs_t265.launch
the following error message appears in  demo_t265.launch window:
[FATAL] [1573545902.844163629]: Failed to load nodelet '/camera/realsense2_camera` of type `realsense2_camera/RealSenseNodeFactory` to manager `realsense2_camera_manager'
[ INFO] [1573545902.889267339]: Initializing nodelet with 32 worker threads.
[ERROR] [1573545902.900499661]: Failed to find nodelet with name '/camera/realsense2_camera' to unload.
[camera/realsense2_camera-2] process has died [pid 13891, exit code 255, cmd /opt/ros/kinetic/lib/nodelet/nodelet load realsense2_camera/RealSenseNodeFactory realsense2_camera_manager __name:=realsense2_camera __log:=/home/irobot/.ros/log/1bde6f28-0523-11ea-95e8-309c2389eb8b/camera-realsense2_camera-2.log].
log file: /home/irobot/.ros/log/1bde6f28-0523-11ea-95e8-309c2389eb8b/camera-realsense2_camera-2*.log
In realsense2_camera rs_t265.launch the following error message appears:
[ERROR] [1573545902.844024648]: Cannot load nodelet /camera/realsense2_camera for one exists with that name already
[ WARN] [1573545902.895243884]: Shutdown request received.
[ WARN] [1573545902.895295445]: Reason given for shutdown: [new node registered with same name]
[FATAL] [1573545902.901561214]: Failed to unload nodelet '/camera/realsense2_camera` from manager `realsense2_camera_manager'
[camera/realsense2_camera-3] process has finished cleanly
log file: /home/irobot/.ros/log/1bde6f28-0523-11ea-95e8-309c2389eb8b/camera-realsense2_camera-3*.log
[camera/realsense2_camera_manager-2] process has died [pid 13513, exit code -11, cmd /opt/ros/kinetic/lib/nodelet/nodelet manager __name:=realsense2_camera_manager __log:=/home/irobot/.ros/log/1bde6f28-0523-11ea-95e8-309c2389eb8b/camera-realsense2_camera_manager-2.log].
log file: /home/irobot/.ros/log/1bde6f28-0523-11ea-95e8-309c2389eb8b/camera-realsense2_camera_manager-2*.log

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

florianspy,

This is expected behavior. You can simply launch demo_t265.launch. There's no need to launch rs_t265.launch first.

Will you be needing further assistance with this? If we don’t hear from you in 7 days, this issue will be closed.

Thanks
