### ISSUE TITLE
Can I change the frequency of gyro and accel in D435i

### ISSUE THREAD

**Issue by Grandzxw** [realsenseai/realsense-ros#995]
I want to change the frequency of gyro and accel in D435i ,
 <arg name="gyro_fps"            default="400"/>
  <arg name="accel_fps"           default="250"/>
Change to
 <arg name="gyro_fps"            default="200"/>
  <arg name="accel_fps"           default="200"/>
that is ok?

**Comment by Grandzxw** [comment]
the frequency of gyro and accel change to 200hz

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Hi @Grandzxw,

Please refer to the datasheet. 200Hz is not supported for accel.
