### ISSUE TITLE
SR305

### ISSUE THREAD

**Issue by ruoxueruoxi90915** [realsenseai/realsense-ros#996]
Does this package support SR305? 
How to use SR305 under ROS?

**Comment by MartyG-RealSense** [comment]
The SR305 is an SR300 camera in a new casing designed to make it easier to mount the camera.  So the **realsense2_camera** RealSense ROS package and the RealSense ROS wrapper, which both support SR300, should work fine with it.

**RealSense ROS wrapper**
https://github.com/IntelRealSense/realsense-ros/releases

**realsense2_camera**
http://wiki.ros.org/realsense2_camera

Please note that when using the RealSense ROS Wrapper, you should use the specific version of the RealSense SDK that it is compatible  with, and not the newest version of the SDK.   The current compatible SDK version is version **2.29.0**.

https://github.com/IntelRealSense/librealsense/releases/tag/v2.29.0

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Refer to #997
