### ISSUE TITLE
 which  is the specific version of the RealSense SDK about SR305?

### ISSUE THREAD

**Issue by ruoxueruoxi90915** [realsenseai/realsense-ros#997]
The error shown now is: (sr300.cpp:55) try_fetch_usb_device(...) failed.

**Comment by doronhi** [comment]
You should get the latest version from [realsense-ros](https://github.com/IntelRealSense/realsense-ros)

**Comment by RealSenseCustomerSupport** [comment]
----------------------------------------------

Hi @ruoxueruoxi90915,

How is everything going well with the latest ros wrapper?
